R"(bra-	yer
bh r eI	@r
bra-	zeau
bh r V	z @U
bra-	zee
bh r {	z i:
bra-	zen
bh r eI	z V n
bra-	zen-	ly
bh r eI	z V n	l i:
bra-	zi-	er
bh r eI	z i:	@r
bra-	zi-	lian
bh r V	z I l	j V n
bra-	zi-	lians
bh r V	z I l	j V n z
bra-	ziers
bh r eI	Z @r z
bra-	zil
bh r V	z I l
bra-	zil's
bh r V	z I l z
bra-	zos
bh r Q	z @U s
braasch
bh r Q S
brab-	ham
bh r { b	h V m
brac-	ci
bh r Q	tS i:
brace
bh r eI s
brace-	let
bh r eI s	l V t
brace-	lets
bh r eI s	l V t s
braced
bh r eI s t
brach
bh r { tS
brack
bh r { k
brack-	nell
bh r { k	n e l
brack-	ney
bh r { k	n i:
brad
bh r { d
brad-	bu-	ry
bh r { d	b e@	i:
brad-	dock
bh r {	d V k
brad-	ford
bh r { d	f @r d
brad-	ford's
bh r { d	f @r d z
brad-	lee
bh r { d	l i:
brad-	ley
bh r { d	l i:
brad-	ley's
bh r { d	l i: z
brad-	ner
bh r { d	n @r
brad-	ney
bh r { d	n i:
brad-	shaw
bh r { d	S O:
brad-	street
bh r { d	s t r i: t
brad-	way
bh r { d	w eI
brad-	well
bh r { d	w e l
brad's
bh r { d z
brae
bh r eI
brag
bh r { g
brag-	don
bh r { g	d V n
brag-	ga-	do-	ci-	o
bh r {	g V	d @U	S i:	@U
brag-	ger
bh r {	g @r
brag-	gers
bh r {	g @r z
brag-	ging
bh r {	g I N
bragg
bh r { g
bragged
bh r { g d
braggs
bh r { g z
brags
bh r { g z
brah-	min
bh r Q	m I n
brahm
bh r Q m
brahms
bh r Q m z
brai-	ded
bh r eI	d V d
brai-	ding
bh r eI	d I N
brai-	nard
bh r eI	n @r d
brai-	ner
bh r eI	n @r
brai-	nerd
bh r eI	n @r d
brai-	ny
bh r eI	n i:
braid
bh r eI d
braid-	wood
bh r eI d	w U d
braids
bh r eI d z
braille
bh r eI l
brailles
bh r eI l z
brain
bh r eI n
brain-	child
bh r eI n	tS aI l d
brain-	less
bh r eI n	l V s
brain-	po-	wer
bh r eI n	p aU	@r
brain-	stor-	ming
bh r eI n	s t O@	m I N
brain-	storm
bh r eI n	s t O@ m
brain-	tree
bh r eI n	t r i:
brain-	wa-	shing
bh r eI n	w Q	S I N
brain-	wash
bh r eI n	w Q S
brain-	washed
bh r eI n	w Q S t
brained
bh r eI n d
brains
bh r eI n z
brain's
bh r eI n z
braise
bh r eI z
braised
bh r eI z d
braith-	waite
bh r eI T	w eI t
brake
bh r eI k
brake-	man
bh r eI k	m V n
brake-	men
bh r eI k	m e n
braked
bh r eI k t
brakes
bh r eI k s
bram
bh r { m
bram-	ble
bh r { m	b V l
bram-	bles
bh r { m	b V l z
bram-	ley
bh r { m	l i:
bram-	well
bh r { m	w e l
brame
bh r eI m
bramp-	ton
bh r { m	p t V n
bran
bh r { n
bran-	ca
bh r { N	k V
bran-	ches
bh r { n	tS V z
bran-	ching
bh r { n	tS I N
bran-	ch's
bh r { n	tS V z
bran-	co
bh r { N	k @U
bran-	ded
bh r { n	d V d
bran-	deis
bh r { n	d aI s
bran-	del
bh r { n	d V l
bran-	den
bh r { n	d V n
bran-	den-	bur-	ger
bh r { n	d V n	b @r	g @r
bran-	den-	burg
bh r { n	d V n	b @r g
bran-	der
bh r { n	d @r
bran-	di
bh r { n	d i:
bran-	di-	shes
bh r { n	d I	S V z
bran-	di-	shing
bh r { n	d I	S I N
bran-	ding
bh r { n	d I N
bran-	dish
bh r { n	d I S
bran-	dished
bh r { n	d I S t
bran-	dle
bh r { n	d V l
bran-	do
bh r { n	d @U
bran-	don
bh r { n	d V n
bran-	don's
bh r { n	d V n z
bran-	do's
bh r { n	d @U z
bran-	dy
bh r { n	d i:
bran-	dy-	wine
bh r { n	d i:	w aI n
bran-	ford
bh r { n	f @r d
bran-	ham
bh r { n	h V m
bran-	ner
bh r {	n @r
bran-	ni-	gan
bh r {	n I	g V n
bran-	ning
bh r {	n I N
bran-	non
bh r {	n V n
bran-	son
bh r { n	s V n
bran-	son's
bh r { n	s V n z
branch
bh r { n tS
branch-	let
bh r { n	tS l V t
branch-	lets
bh r { n	tS l V t s
branched
bh r { n tS t
brand
bh r { n d
brand-	name
bh r { n	d n eI m
brand-	wein
bh r { n	d w aI n
brande
bh r { n d
brandes
bh r { n d z
brands
bh r { n d z
brand's
bh r { n d z
brandt
bh r { n t
brank
bh r { N k
brans-	cum
bh r { n	s k V m
brans-	ford
bh r { n	s f @r d
brant
bh r { n t
brant-	ley
bh r { n	t l i:
braque
bh r { k
bras
bh r { s
bras-	sard
bh r {	s @r d
bras-	se-	rie
bh r {	s @r	i:
bras-	so
bh r {	s @U
bras-	so's
bh r {	s @U z
bras-	sy
bh r {	s i:
bras-	well
bh r { s	w e l
brash
bh r { S
brash-	ness
bh r { S	n V s
brass
bh r { s
brat
bh r { t
brat-	tain
bh r V	t eI n
brat-	tle
bh r {	t V l
brat-	ton
bh r {	t V n
brat-	wurst
bh r { t	w @r s t
brats
bh r { t s
brau
bh r aU
braun
bh r O: n
braun-	schweig
bh r aU n	S w aI g
braun's
bh r O: n z
brauns-	tein
bh r O: n	s t i: n
brause
bh r O: z
brave
bh r eI v
brave-	heart
bh r eI v	h Q@ t
brave-	ly
bh r eI v	l i:
braved
bh r eI v d
braves
bh r eI v z
braw-	ley
bh r O:	l i:
braw-	ling
bh r O:	l I N
braw-	ner
bh r O:	n @r
braw-	ny
bh r O:	n i:
brawl
bh r O: l
brawls
bh r O: l z
brawn
bh r O: n
brax-	ton
bh r { k	s t V n
bray
bh r eI
bray-	ton
bh r eI	t V n
braz
bh r { z
braz-	za-	ville
bh r {	z V	v I l
bre-	cher
bh r e	k @r
bre-	cken-	ridge
bh r e	k V n	r I dZ
bre-	da
bh r eI	d V
bre-	ger
bh r i:	g @r
bre-	men
bh r e	m V n
bre-	mer
bh r i:	m @r
bre-	see
bh r V	s i:
bre-	ton
bh r e	t V n
bre-	vard
bh r e	v @r d
bre-	vets
bh r V	v e t s
bre-	vi-	ty
bh r e	v I	t i:
bre-	we-	ries
bh r u:	@r	i: z
bre-	we-	ry
bh r u:	@r	i:
bre-	wer
bh r u:	@r
bre-	wers
bh r u:	@r z
bre-	wer's
bh r u:	@r z
bre-	wing
bh r u:	I N
bre-	yer
bh r eI	@r
bre-	yer's
bh r eI	@r z
brea
bh r i:
brea-	ches
bh r i:	tS V z
brea-	ching
bh r i:	tS I N
brea-	ded
bh r e	d V d
brea-	ding
bh r e	d I N
brea-	dy
bh r e	d i:
brea-	ka-	ble
bh r eI	k V	b V l
brea-	ka-	way
bh r eI	k V	w eI
brea-	kage
bh r eI	k I dZ
brea-	ke-	ven
bh r eI	k i:	v V n
brea-	ker
bh r eI	k @r
brea-	kers
bh r eI	k @r z
brea-	king
bh r eI	k I N
brea-	ther
bh r i:	D @r
brea-	thing
bh r i:	D I N
brea-	thy
bh r e	T i:
breach
bh r i: tS
breached
bh r i: tS t
bread
bh r e d
bread-	bas-	ket
bh r e d	b { s	k V t
bread-	box
bh r e d	b Q k s
bread-	fruit
bh r e d	f r u: t
bread-	win-	ner
bh r e d	w I	n @r
bread-	win-	ners
bh r e d	w I	n @r z
breads
bh r e d z
breadth
bh r e d T
break
bh r eI k
break-	down
bh r eI k	d aU n
break-	downs
bh r eI k	d aU n z
break-	e-	ven
bh r eI	k i:	v V n
break-	fast
bh r e k	f V s t
break-	fasts
bh r e k	f V s t s
break-	neck
bh r eI k	n e k
break-	out
bh r eI	k aU t
break-	outs
bh r eI	k aU t s
break-	up
bh r eI	k V p
break-	ups
bh r eI	k V p s
break-	wa-	ter
bh r eI k	w O:	t @r
breaks
bh r eI k s
breakth-	rough
bh r eI k	T r u:
breakth-	roughs
bh r eI k	T r u: z
bream
bh r i: m
breas-	ted
bh r e s	t V d
breas-	ting
bh r e s	t I N
breast
bh r e s t
breast-	fed
bh r e s	t f e d
breast-	fee-	ding
bh r e s	t f i:	d I N
breast-	feed
bh r e s	t f i: d
breast-	feeds
bh r e s	t f i: d z
breast-	plate
bh r e s	t p l eI t
breasts
bh r e s t s
breath
bh r e T
breath-	less
bh r e T	l V s
breath-	less-	ly
bh r e T	l V s	l i:
breath-	ta-	king
bh r e T	t eI	k I N
breath-	ta-	king-	ly
bh r e T	t eI	k I N	l i:
breathe
bh r i: D
breathed
bh r i: D d
breathes
bh r i: D z
breaths
bh r e T s
breaux
bh r @U
brech-	tel
bh r e k	t V l
brecht
bh r e k t
breck
bh r e k
bred
bh r e d
brede
bh r i: d
bree
bh r i:
bree-	den
bh r i:	d V n
bree-	den's
bh r i:	d V n z
bree-	der
bh r i:	d @r
bree-	ders
bh r i:	d @r z
bree-	ding
bh r i:	d I N
bree-	zes
bh r i:	z V z
bree-	zy
bh r i:	z i:
breech
bh r i: tS
breed
bh r i: d
breeds
bh r i: d z
breed's
bh r i: d z
breen
bh r i: n
brees
bh r i: z
breese
bh r i: z
breeze
bh r i: z
breeze-	way
bh r i: z	w eI
breezed
bh r i: z d
brem-	ner
bh r e m	n @r
bren
bh r e n
bren-	da
bh r e n	d V
bren-	dan
bh r e n	d V n
bren-	da's
bh r e n	d V z
bren-	del
bh r e n	d V l
bren-	den
bh r e n	d V n
bren-	na
bh r e	n V
bren-	nan
bh r e	n V n
bren-	nan's
bh r e	n V n z
bren-	nen
bh r e	n V n
bren-	ner
bh r e	n @r
bren-	ning
bh r e	n I N
bren-	ta-	no
bh r e n	t Q	n @U
bren-	ton
bh r e n	t V n
brenn
bh r e n
brent
bh r e n t
brent-	wood
bh r e n	t w U d
brents
bh r e n t s
bres-	cia
bh r e s	tS V
bres-	son
bh r e	s V n
bress
bh r e s
brest
bh r e s t
bret
bh r e t
bret-	ton
bh r e	t V n
breth
bh r e T
breth-	ren
bh r e D	r V n
brett
bh r e t
bretz
bh r e t s
breu-	er
bh r u:	@r
brew
bh r u:
brew-	ton
bh r u:	t V n
brewed
bh r u: d
brews
bh r u: z
brews-	ter
bh r u: s	t @r
brey
bh r eI
brezh-	nev
bh r e z	n V v
brezh-	nev's
bh r e z	n V v z
bri-	a
bh r i:	V
bri-	a-	na
bh r i:	{	n V
bri-	a-	na's
bh r i:	{	n V z
bri-	an
bh r aI	V n
bri-	an-	na
bh r i:	{	n V
bri-	an-	na's
bh r i:	{	n V z
bri-	and
bh r aI	V n d
bri-	an's
bh r aI	V n z
bri-	ant
bh r aI	V n t
bri-	ar
bh r aI	@r
bri-	be-	ry
bh r aI	b @r	i:
bri-	bing
bh r aI	b I N
bri-	dal
bh r aI	d V l
bri-	en
bh r aI	V n
bri-	er
bh r aI	@r
bri-	ga-	dier
bh r I	g V	d I@
bri-	gade
bh r V	g eI d
bri-	gades
bh r I	g eI d z
bri-	gham
bh r I	g V m
bri-	gham's
bh r I	g V m z
bri-	gitte
bh r I	dZ I t
bri-	ner
bh r aI	n @r
bri-	ney
bh r I	n i:
bri-	ning
bh r aI	n I N
bri-	o
bh r aI	@U
bri-	oche
bh r i:	@U S
bri-	on
bh r aI	V n
bri-	st-	ling
bh r I	s V	l I N
bri-	stle
bh r I	s V l
bri-	stled
bh r I	s V l d
bri-	stles
bh r I	s V l z
bri-	ta
bh r i:	t V
bri-	tain
bh r I	t @ n
bri-	tain's
bh r I	t @ n z
bri-	tan-	ni-	a
bh r V	t {	n i:	V
bri-	tan-	ni-	ca
bh r V	t {	n I	k V
bri-	tish
bh r I	t I S
bri-	ton
bh r I	t V n
bri-	tons
bh r I	t V n z
bri-	xey
bh r I k	s i:
briar-	cliff
bh r aI r	k l I f
bribe
bh r aI b
bribed
bh r aI b d
bribes
bh r aI b z
bric-	kel
bh r I	k V l
bric-	ker
bh r I	k @r
bric-	kle
bh r I	k V l
brice
bh r aI s
brick
bh r I k
brick-	bat
bh r I k	b { t
brick-	bats
bh r I k	b { t s
brick-	la-	yer
bh r I k	l eI	@r
brick-	la-	yers
bh r I k	l eI	@r z
brick-	yard
bh r I k	j Q@ d
bricks
bh r I k s
brid-	well
bh r I d	w e l
bride
bh r aI d
bride-	groom
bh r aI d	g r u: m
bride-	groom's
bh r aI d	g r u: m z
brides
bh r aI d z
bride's
bh r aI d z
brides-	maid
bh r aI d	z m eI d
brides-	maids
bh r aI d	z m eI d z
brides-	maid's
bh r aI d	z m eI d z
brie
bh r i:
brie-	fer
bh r i:	f @r
brie-	fers
bh r i:	f @r z
brie-	fest
bh r i:	f V s t
brie-	fing
bh r i:	f I N
brie-	fings
bh r i:	f I N z
brief
bh r i: f
brief-	ca-	ses
bh r i: f	k eI	s V z
brief-	case
bh r i: f	k eI s
brief-	ly
bh r i: f	l i:
briefed
bh r i: f t
briefs
bh r i: f s
brig
bh r I g
briggs
bh r I g z
brigh-	te-	ning
bh r aI	t V	n I N
brigh-	ten
bh r aI	t V n
brigh-	tened
bh r aI	t V n d
brigh-	tens
bh r aI	t V n z
brigh-	ter
bh r aI	t @r
brigh-	test
bh r aI	t V s t
brigh-	ton
bh r aI	t V n
bright
bh r aI t
bright-	ly
bh r aI t	l i:
bright-	man
bh r aI t	m V n
bright-	ness
bh r aI t	n V s
bright's
bh r aI t s
bril-	liance
bh r I l	j V n s
bril-	liant
bh r I l	j V n t
bril-	liant-	ly
bh r I l	j V n	t l i:
brill
bh r I l
brim
bh r I m
brim-	hall
bh r I m	h O: l
brim-	mer
bh r I	m @r
brim-	ming
bh r I	m I N
brim-	stone
bh r I m	s t @U n
brimmed
bh r I m d
brin
bh r I n
brin-	dle
bh r I n	d V l
brin-	ghurst
bh r I N	h @r s t
brin-	ging
bh r I	N I N
brin-	son
bh r I n	s V n
brine
bh r aI n
brines
bh r aI n z
bring
bh r I N
brings
bh r I N z
brink
bh r I N k
brink-	ley
bh r I N	k l i:
brink-	man
bh r I N	k m V n
brink-	man-	ship
bh r I N	k m V n	S I p
brinks
bh r I N k s
brink's
bh r I N k s
brinks-	man-	ship
bh r I N	k s m V n	S I p
brinn
bh r I n
bris-	bane
bh r I z	b eI n
bris-	bin
bh r I z	b I n
bris-	coe
bh r I s	k @U
bris-	ker
bh r I s	k @r
bris-	ket
bh r I s	k V t
bris-	ky
bh r I s	k i:
bris-	tol
bh r I s	t V l
bris-	tow
bh r I s	t @U
brisk
bh r I s k
brisk-	ly
bh r I s	k l i:
brit
bh r I t
brit-	ches
bh r I	tS V z
brit-	ta-	ny
bh r I	t V	n i:
brit-	tain
bh r I	t V n
brit-	tan
bh r I	t V n
brit-	ten
bh r I	t V n
brit-	tle
bh r I	t V l
brit-	ton
bh r I	t V n
brite
bh r aI t
b'rith
bh r I T
brits
bh r I t s
britt
bh r I t
britts
bh r I t s
brix
bh r I k s
bro
bh r @U
bro-	cade
bh r @U	k eI d
bro-	cades
bh r @U	k eI d z
bro-	chure
bh r @U	S U@
bro-	chures
bh r @U	S U@ z
bro-	de-	rick
bh r Q	d @r	I k
bro-	de-	rick's
bh r Q	d @r	I k z
bro-	der
bh r @U	d @r
bro-	der's
bh r @U	d @r z
bro-	deur
bh r Q	d @r
bro-	die
bh r @U	t i:
bro-	dy
bh r @U	d i:
bro-	dy's
bh r @U	d i: z
bro-	gan
bh r @U	g V n
bro-	kaw
bh r @U	k O:
bro-	ke-	ra-	ges
bh r @U	k @r	I	dZ V z
bro-	ke-	ra-	ge's
bh r @U	k @r	I	dZ V z
bro-	ke-	rage
bh r @U	k @r	I dZ
bro-	ken
bh r @U	k V n
bro-	ker
bh r @U	k @r
bro-	ker-	ing
bh r @U	k @r	I N
bro-	kers
bh r @U	k @r z
bro-	ker's
bh r @U	k @r z
bro-	king
bh r @U	k I N
bro-	mide
bh r @U	m aI d
bro-	mides
bh r @U	m aI d z
bro-	mine
bh r @U	m i: n
bro-	naugh
bh r Q	n O:
bro-	thel
bh r Q	T V l
bro-	thels
bh r Q	T V l z
bro-	ther
bh r V	D @r
bro-	ther-	hood
bh r V	D @r	h U d
bro-	ther-	ly
bh r V	D @r	l i:
bro-	ther-	son
bh r V	D @r	s V n
bro-	ther-	s's
bh r V	D @r	z V z
bro-	ther-	ton
bh r V	D @r	t V n
bro-	thers
bh r V	D @r z
bro-	ther's
bh r V	D @r z
bro-	wer
bh r aU	@r
broa-	ches
bh r @U	tS V z
broa-	ching
bh r @U	tS I N
broa-	de-	ning
bh r O:	d V	n I N
broa-	den
bh r O:	d V n
broa-	dened
bh r O:	d V n d
broa-	dens
bh r O:	d V n z
broa-	der
bh r O:	d @r
broa-	dest
bh r O:	d V s t
broa-	dus
bh r @U	d V s
broach
bh r @U tS
broached
bh r @U tS t
broad
bh r O: d
broad-	band
bh r O: d	b { n d
broad-	bent
bh r O: d	b e n t
broad-	cas-	ter
bh r O: d	k { s	t @r
broad-	cas-	ters
bh r O: d	k { s	t @r z
broad-	cas-	ter's
bh r O: d	k { s	t @r z
broad-	cas-	ting
bh r O: d	k { s	t I N
broad-	cast
bh r O: d	k { s t
broad-	casts
bh r O: d	k { s t s
broad-	dus
bh r O:	d V s
broad-	head
bh r O: d	h e d
broad-	ly
bh r O: d	l i:
broad-	si-	ded
bh r O: d	s aI	d V d
broad-	side
bh r O: d	s aI d
broad-	sword
bh r O: d	s O@ d
broad-	view
bh r O: d	v j u:
broad-	way
bh r O: d	w eI
broad-	way's
bh r O: d	w eI z
broad-	well
bh r O: d	w e l
broad's
bh r O: d z
brob-	ding-	na-	gi-	an
bh r O: b	d I g	n {	g i:	V n
brob-	ding-	na-	gi-	ans
bh r O: b	d I g	n {	g i:	V n z
broc-	co-	li
bh r Q	k V	l i:
broc-	kie
bh r Q	k i:
brock
bh r Q k
brock-	lin
bh r Q k	l I n
brock-	lin's
bh r Q k	l I n z
brock-	ton
bh r Q k	t V n
brock-	way
bh r Q k	w eI
brock-	way's
bh r Q k	w eI z
brock-	well
bh r Q k	w e l
brock's
bh r Q k s
brod
bh r Q d
brod-	head
bh r Q d	h e d
brod-	kin
bh r Q d	k I n
brod-	nax
bh r Q d	n { k s
brod-	sky
bh r Q d	s k i:
broe-	ker
bh r @U	k @r
broi-	ler
bh r OI	l @r
broi-	lers
bh r OI	l @r z
broi-	ling
bh r OI	l I N
broil
bh r OI l
broiled
bh r OI l d
brok
bh r Q k
broke
bh r @U k
broke-	red
bh r @U	k @r d
brol-	ly
bh r Q	l i:
brom
bh r Q m
brom-	berg
bh r Q m	b @r g
brom-	field
bh r Q m	f i: l d
brom-	field's
bh r Q m	f i: l d z
brom-	ley
bh r Q m	l i:
brom-	mer
bh r Q	m @r
brom-	wich
bh r Q m	w I tS
bron-	chi-	al
bh r Q n	tS i:	V l
bron-	chi-	tis
bh r Q N	k aI	t I s
bron-	co
bh r Q N	k @U
bron-	cos
bh r Q N	k @U z
bron-	der
bh r Q n	d @r
bron-	son
bh r Q n	s V n
bron-	te
bh r Q n	t i:
bron-	to-	sau-	rus
bh r O: n	t V	s O@	V s
bron-	wen
bh r O: n	w e n
bron-	zen
bh r Q n	z V n
bron-	zes
bh r Q n	z V z
bronc
bh r Q N k
bronk
bh r Q N k
brons-	ton
bh r Q n	s t V n
bronx
bh r Q N k s
bronze
bh r Q n z
bronzed
bh r Q n z d
broo-	ded
bh r u:	d V d
broo-	ding
bh r u:	d I N
broo-	dy
bh r u:	d i:
broo-	ker
bh r U	k @r
broo-	king
bh r U	k I N
broo-	kings
bh r U	k I N z
broo-	mall
bh r u:	m V l
brooch
bh r @U tS
brood
bh r u: d
brook
bh r U k
brook-	field
bh r U k	f i: l d
brook-	ha-	ven
bh r U k	h eI	v V n
brook-	line
bh r U k	l aI n
brook-	lyn
bh r U k	l V n
brook-	lyn's
bh r U k	l V n z
brook-	ner
bh r U k	n @r
brook-	ner's
bh r U k	n @r z
brook-	shire
bh r u: k	S aI r
brook-	side
bh r U k	s aI d
brooke
bh r U k
brookes
bh r U k s
brooke's
bh r U k s
brooks
bh r U k s
brook's
bh r U k s
brooks-	ville
bh r U k	s v I l
brooks-	ville's
bh r U k	s v I l z
broom
bh r u: m
broom-	field
bh r u: m	f i: l d
broom-	stick
bh r u: m	s t I k
broom-	sticks
bh r u: m	s t I k s
broome
bh r u: m
brooms
bh r u: m z
bro's
bh r @U z
bros-	nan
bh r Q s	n V n
brose
bh r @U z
brost
bh r Q s t
broth
bh r O: T
broths
bh r O: T s
brott
bh r Q t
brou-	cek
bh r u:	tS e k
brou-	ha-	ha
bh r u:	h Q	h Q
brou-	wer
bh r aU	w @r
broug-	ham
bh r u:	g V m
brough
bh r aU
brough-	ton
bh r O:	t V n
brought
bh r O: t
broun
bh r u: n
brous-	sard
bh r u:	s Q@ d
brow
bh r aU
brow-	beat
bh r aU	b i: t
brow-	der
bh r aU	d @r
brow-	nell
bh r aU	n e l
brow-	ner
bh r aU	n @r
brow-	nest
bh r aU	n e s t
brow-	nie
bh r aU	n i:
brow-	nies
bh r aU	n i: z
brow-	ning
bh r aU	n I N
brow-	ning's
bh r aU	n I N z
brow-	nish
bh r aU	n I S
brow-	nout
bh r aU	n aU t
brow-	nouts
bh r aU	n aU t s
brow-	ser
bh r aU	z @r
brow-	sers
bh r aU	z @r z
brow-	sing
bh r aU	z I N
browed
bh r aU d
brown
bh r aU n
brown-	back
bh r aU n	b { k
brown-	field
bh r aU n	f i: l d
brown-	fields
bh r aU n	f i: l d z
brown-	lee
bh r aU n	l i:
brown-	ley
bh r aU n	l i:
brown-	low
bh r aU n	l @U
)"
R"(brown-	son
bh r aU n	s V n
brown-	stone
bh r aU n	s t @U n
browne
bh r aU n
browned
bh r aU n d
browns
bh r aU n z
brown's
bh r aU n z
browns-	ville
bh r aU n	z v I l
brows
bh r aU z
browse
bh r aU z
browsed
bh r aU z d
brox-	ton
bh r Q k	s t V n
broz
bh r Q z
bru-	ba-	ker
bh r V	b V	k @r
bru-	beck
bh r u:	b e k
bru-	ce's
bh r u:	s V z
bru-	cie
bh r V	k i:
bru-	cite
bh r u:	s aI t
bru-	ges
bh r u:	dZ V z
bru-	in
bh r u:	I n
bru-	ing-	ton
bh r u:	I N	t V n
bru-	ins
bh r u:	I n z
bru-	neau
bh r V	n @U
bru-	nei
bh r u:	n aI
bru-	nel-	la
bh r u:	n e	l V
bru-	nell
bh r V	n V l
bru-	nelle
bh r V	n e l
bru-	ner
bh r u:	n @r
bru-	net
bh r u:	n e t
bru-	nette
bh r u:	n e t
bru-	nettes
bh r u:	n e t s
bru-	ni
bh r u:	n i:
bru-	ning
bh r u:	n I N
bru-	no
bh r u:	n @U
bru-	no's
bh r u:	n @U z
bru-	sett
bh r U	s e t
bru-	shes
bh r V	S V z
bru-	shing
bh r V	S I N
bru-	shy
bh r V	S i:
bru-	ta-	li-	ties
bh r u:	t {	l I	t i: z
bru-	ta-	li-	ty
bh r u:	t {	l I	t i:
bru-	ta-	li-	za-	tion
bh r u:	t V	l V	z eI	S V n
bru-	ta-	li-	zes
bh r u:	t V	l aI	z V z
bru-	ta-	li-	zing
bh r u:	t V	l aI	z I N
bru-	ta-	lize
bh r u:	t V	l aI z
bru-	ta-	lized
bh r u:	t V	l aI z d
bru-	tal
bh r u:	t V l
bru-	tal-	ly
bh r u:	t V	l i:
bru-	tish
bh r u:	t I S
bru-	tus
bh r u:	t V s
bru-	xel-	les
bh r V k	s e	l V s
bruce
bh r u: s
bruch
bh r V tS
bruck-	ner
bh r V k	n @r
brugh
bh r V
bruhn
bh r V n
brui-	ses
bh r u:	z V z
brui-	sing
bh r u:	z I N
bruise
bh r u: z
bruised
bh r u: z d
brule
bh r u: l
brum
bh r V m
brum-	ley
bh r V m	l i:
brum-	mel
bh r V	m V l
brum-	mell
bh r V	m V l
brum-	mer
bh r V	m @r
brun-	ches
bh r V n	tS V z
brun-	didge
bh r V n	d I dZ
brun-	hil-	da
bh r u: n	h i: l	d V
brun-	ner
bh r V	n @r
brun-	son
bh r V n	s V n
brunch
bh r V n tS
brune
bh r u: n
brunk
bh r V N k
brunn
bh r V n
brunn-	hilde
bh r V n	h I l d
bruns
bh r V n z
bruns-	wick
bh r V n	z w I k
bruns-	wick's
bh r V n	z w I k s
brunt
bh r V n t
brus-	sel
bh r V	s V l
brus-	sels
bh r V	s V l z
brush
bh r V S
brush-	fire
bh r V S	f aI r
brush-	fires
bh r V S	f aI r z
brush-	work
bh r V S	w @r k
brushed
bh r V S t
brusque
bh r V s k
brusque-	ly
bh r V s	k l i:
brust
bh r V s t
brut
bh r u: t
brute
bh r u: t
bry-	na
bh r I	n V
bryce
bh r aI s
bryn
bh r I n
bu-	bo-	nic
bh j u:	b Q	n I k
bu-	cha-	nan
bh j u:	k {	n V n
bu-	cha-	nan's
bh j u:	k {	n V n z
bu-	cha-	rest
bh j u:	k @r	e s t
bu-	chal-	ter
bh V	k V l	t @r
bu-	chan
bh V	k V n
bu-	chen-	wald
bh j u:	k e n	w Q l d
bu-	cher
bh V	k @r
bu-	co-	lic
bh j u:	k Q	l I k
bu-	da-	pest
bh u:	d V	p e s t
bu-	da-	pest's
bh u:	d V	p e s t s
bu-	ell
bh j u:	V l
bu-	ford
bh j u:	f @r d
bu-	g-	ling
bh j u:	g V	l I N
bu-	ga-	boo
bh V	g V	b u:
bu-	geye
bh V	g aI
bu-	geyed
bh V	g aI d
bu-	gle
bh j u:	g V l
bu-	gles
bh j u:	g V l z
bu-	ick
bh j u:	I k
bu-	icks
bh j u:	I k s
bu-	ick's
bh j u:	I k s
bu-	ist
bh u:	I s t
bu-	jum-	bu-	ra
bh u:	dZ V m	b U@	V
bu-	ka-	vu
bh u:	k Q	v u:
bu-	ka-	vu's
bh u:	k Q	v u: z
bu-	kha-	rin
bh V k	h @r	I n
bu-	la
bh j u:	l V
bu-	li-	mi-	a
bh j u:	l I	m i:	V
bu-	li-	mic
bh j u:	l I	m I k
bu-	low
bh j u:	l @U
bu-	rack
bh j u:	r V k
bu-	ran
bh j u:	r V n
bu-	ras
bh j u:	r V z
bu-	reau
bh j U@	@U
bu-	reau-	cra-	cies
bh j U@	Q k	r V	s i: z
bu-	reau-	cra-	cy
bh j U@	Q k	r V	s i:
bu-	reau-	cra-	cy's
bh j U@	Q k	r V	s i: z
bu-	reau-	cra-	tese
bh j U@	V k	r {	t i: z
bu-	reau-	cra-	tic
bh j U@	V k	r {	t I k
bu-	reau-	crat
bh j U@	V k	r { t
bu-	reau-	crats
bh j U@	V k	r { t s
bu-	reaus
bh j U@	@U z
bu-	reau's
bh j U@	@U z
bu-	rel
bh e@	V l
bu-	ren
bh j U@	V n
bu-	ro-	ker
bh j u:	r V	k @r
bu-	run-	di
bh @r	V n	d i:
bu-	run-	di's
bh @r	V n	d i: z
bu-	ry
bh e@	i:
bu-	ry-	ing
bh e@	i:	I N
bu-	ry's
bh e@	i: z
bu-	ses
bh V	s V z
bu-	sey
bh j u:	z i:
bu-	shel
bh U	S V l
bu-	shels
bh U	S V l z
bu-	sher
bh U	S @r
bu-	shes
bh U	S V z
bu-	shey
bh U	S i:
bu-	shings
bh U	S I N z
bu-	sh's
bh U	S V z
bu-	shy
bh U	S i:
bu-	si-	er
bh I	z i:	@r
bu-	si-	est
bh I	z i:	V s t
bu-	si-	ly
bh I	z I	l i:
bu-	sied
bh I	z i: d
bu-	sing
bh V	s I N
bu-	sy
bh I	z i:
bu-	tane
bh j u:	t eI n
bu-	tyl
bh j u:	t V l
bu-	xom
bh V k	s V m
bu-	yer
bh aI	@r
bu-	yers
bh aI	@r z
bu-	yer's
bh aI	@r z
bu-	yers'
bh aI	@r z
bub
bh V b
bub-	b-	ling
bh V	b V	l I N
bub-	ba
bh V	b V
bub-	ble
bh V	b V l
bub-	bled
bh V	b V l d
bub-	bles
bh V	b V l z
bubb
bh V b
bubb-	ly
bh V b	l i:
buc-	ca-	neer
bh V	k V	n i: r
buc-	can-	eers
bh V	k V	n i: r z
buc-	k-	ler
bh V	k V	l @r
buc-	kels
bh V	k V l z
buc-	ket
bh V	k V t
buc-	kets
bh V	k V t s
buc-	keye
bh V	k aI
buc-	king
bh V	k I N
buc-	king-	ham
bh V	k I N	h { m
buc-	kled
bh V	k V l d
buc-	kles
bh V	k V l z
buc-	ko
bh V	k @U
buc-	ky
bh V	k i:
buch
bh V tS
buch-	bin-	der
bh V k	b I n	d @r
buch-	man
bh V k	m V n
buch-	ner
bh V k	n @r
buch-	wald
bh V k	w O: l d
buck
bh V k
buck-	horn
bh V k	h O@ n
buck-	land
bh V k	l V n d
buck-	le
bh V	k V l
buck-	ley
bh V k	l i:
buck-	lin
bh V k	l I n
buck-	ling
bh V k	l I N
buck-	man
bh V k	m V n
buck-	nell
bh V k	n e l
buck-	ner
bh V k	n @r
buck-	shot
bh V k	S Q t
buck-	skin
bh V k	s k I n
buck-	thorn
bh V k	T O@ n
buck-	wheat
bh V k	w i: t
bucked
bh V k t
bucks
bh V k s
buck's
bh V k s
bud
bh V d
bud-	den-	brooks
bh V	d V n	b r U k s
bud-	dha
bh u:	d V
bud-	dha's
bh u:	d V z
bud-	dhi-	sm
bh u:	d I	z V m
bud-	dhist
bh u:	d I s t
bud-	dhists
bh u:	d I s t s
bud-	di-	er
bh V	d i:	@r
bud-	die
bh V	d i:
bud-	dies
bh V	d i: z
bud-	ding
bh V	d I N
bud-	dy
bh V	d i:
bud-	dy's
bh V	d i: z
bud-	ge-	ta-	ry
bh V	dZ V	t e@	i:
bud-	ge-	ted
bh V	dZ V	t V d
bud-	ge-	teer
bh V	dZ V	t I@
bud-	ge-	teers
bh V	dZ V	t I@ z
bud-	ge-	ting
bh V	dZ V	t I N
bud-	get
bh V	dZ V t
bud-	gets
bh V	dZ V t s
bud-	get's
bh V	dZ V t s
bud-	ging
bh V	dZ I N
bud-	long
bh V d	l O: N
bud-	wei-	ser
bh V d	w aI	z @r
budd
bh V d
budde
bh V d
budge
bh V dZ
budged
bh V dZ d
buds
bh V d z
bud's
bh V d z
bue-	na
bh u:	n V
bue-	no
bh w eI	n @U
bue-	nos
bh w eI	n @U s
bueche
bh u: tS
bueh-	ler
bh j u:	l @r
bueh-	rer
bh j u:	h @r
bueh-	ring
bh j u:	r I N
buer-	ger
bh j u: r	g @r
buf-	fa
bh V	f V
buf-	fa-	lo
bh V	f V	l @U
buf-	fa-	los
bh V	f V	l @U z
buf-	fa-	lo's
bh V	f V	l @U z
buf-	fe-	rin
bh V	f @r	I n
buf-	fe-	ting
bh V	f eI	I N
buf-	fer
bh V	f @r
buf-	fered
bh V	f @r d
buf-	fers
bh V	f @r z
buf-	fet
bh V	f eI
buf-	feted
bh V	f eI d
buf-	fets
bh V	f V t s
buf-	fin
bh V	f I n
buf-	fo
bh u:	f @U
buf-	fo-	ne
bh u:	f @U	n i:
buf-	foon
bh V	f u: n
buf-	fum
bh V	f V m
buf-	fy
bh V	f i:
buff
bh V f
buffs
bh V f s
buff's
bh V f s
bug
bh V g
bug-	bee
bh V g	b i:
bug-	eyed
bh V	g aI d
bug-	ger
bh V	g @r
bug-	gers
bh V	g @r z
bug-	gies
bh V	g i: z
bug-	ging
bh V	g I N
bug-	gy
bh V	g i:
bugged
bh V g d
bugs
bh V g z
buh-	ler
bh u:	l @r
buhl
bh j u: l
buhr
bh j U@
bui
bh I
buil-	da-	ble
bh I l	d V	b V l
buil-	der
bh I l	d @r
buil-	ders
bh I l	d @r z
buil-	der's
bh I l	d @r z
buil-	ding
bh I l	d I N
buil-	dings
bh I l	d I N z
buil-	ding's
bh I l	d I N z
buil-	dup
bh I l	d V p
buil-	dups
bh I l	d V p s
build
bh I l d
build-	up
bh I l	d V p
builds
bh I l d z
built
bh I l t
buis-	son
bh w i:	s Q n
bul-	bous
bh V l	b V s
bul-	fin-	ch's
bh U l	f I n	tS V z
bul-	finch
bh U l	f I n tS
bul-	ga-	ri-	a
bh V l	g e@	i:	V
bul-	ga-	ri-	an
bh V l	g e@	i:	V n
bul-	ga-	ri-	ans
bh V l	g e@	i:	V n z
bul-	ga-	ri-	a's
bh V l	g e@	i:	V z
bul-	ger
bh V l	g @r
bul-	ges
bh V l	dZ V z
bul-	ging
bh V l	dZ I N
bul-	ki-	er
bh V l	k i:	@r
bul-	ky
bh V l	k i:
bul-	la
bh U	l V
bul-	lard
bh U	l @r d
bul-	le-	tin
bh U	l V	t V n
bul-	le-	tins
bh U	l V	t V n z
bul-	len
bh U	l V n
bul-	ler
bh U	l @r
bul-	let
bh U	l V t
bul-	let-	proof
bh U	l V t	p r u: f
bul-	lets
bh U	l V t s
bul-	lied
bh U	l i: d
bul-	lies
bh U	l i: z
bul-	lion
bh U l	j V n
bul-	lis
bh U	l I s
bul-	lish
bh U	l I S
bul-	lish-	ly
bh U	l I S	l i:
bul-	lish-	ness
bh U	l I S	n V s
bul-	litt
bh u:	l I t
bul-	loch
bh U	l V k
bul-	lock
bh U	l V k
bul-	locks
bh U	l V k s
bul-	lock's
bh U	l V k s
bul-	ly
bh U	l i:
bul-	ly-	ing
bh U	l i:	I N
bul-	mer
bh V l	m @r
bul-	rush
bh U l	r V S
bul-	wark
bh U l	w @r k
bulb
bh V l b
bulbs
bh V l b z
bulge
bh V l dZ
bulged
bh V l dZ d
bulk
bh V l k
bulk-	head
bh V l	k h e d
bulk-	heads
bh V l	k h e d z
bull
bh U l
bull-	do-	zer
bh U l	d @U	z @r
bull-	do-	zers
bh U l	d @U	z @r z
bull-	do-	zing
bh U l	d @U	z I N
bull-	dog
bh U l	d O: g
bull-	dogs
bh U l	d O: g z
bull-	doze
bh U l	d @U z
bull-	dozed
bh U l	d @U z d
bull-	figh-	ter
bh U l	f aI	t @r
bull-	figh-	ting
bh U l	f aI	t I N
bull-	fight
bh U l	f aI t
bull-	fights
bh U l	f aI t z
bull-	frog
bh U l	f r O: g
bull-	frogs
bh U l	f r O: g z
bull-	head
bh U l	h e d
bull-	heads
bh U l	h e d z
bull-	horn
bh U l	h O@ n
bull-	horns
bh U l	h O@ n z
bull-	pen
bh U l	p e n
bull-	seye
bh u: l	z aI
bull-	shit
bh U l	S I t
bull-	win-	kle
bh U l	w I N	k V l
bulls
bh U l z
bull's
bh U l z
bult
bh V l t
bult-	man
bh U l	t m V n
bum
bh V m
bum-	b-	ling
bh V m	b V	l I N
bum-	ble
bh V m	b V l
bum-	gard-	ner
bh V m	g Q@ d	n @r
bum-	mer
bh V	m @r
bum-	per
bh V m	p @r
bum-	pers
bh V m	p @r z
bum-	pers-	ti-	cker
bh V m	p @r s	t I	k @r
bum-	ping
bh V m	p I N
bum-	pings
bh V m	p I N z
bum-	py
bh V m	p i:
bummed
bh V m d
bump
bh V m p
bump-	kin
bh V m	p k I n
bumped
bh V m p t
bumps
bh V m p s
bums
bh V m z
bun
bh V n
bun-	ches
bh V n	tS V z
bun-	ching
bh V n	tS I N
bun-	chy
bh V n	tS i:
bun-	d-	ling
bh V n	d V	l I N
bun-	da
bh V n	d V
bun-	des-	bank
bh U n	d V s	b { N k
bun-	des-	rat
bh U n	d V s	r { t
bun-	des-	tag
bh V n	d V s	t { g
bun-	dle
bh V n	d V l
bun-	dled
bh V n	d V l d
bun-	dles
bh V n	d V l z
bun-	dy
bh V n	d i:
bun-	dy's
bh V n	d i: z
bun-	g-	ling
bh V N	g V	l I N
bun-	ga-	low
bh V N	g V	l @U
bun-	ga-	lows
bh V N	g V	l @U z
bun-	gee
bh V n	dZ i:
bun-	ger
bh V	N @r
bun-	gey
bh V n	dZ i:
bun-	gled
bh V N	g V l d
bun-	ker
bh V N	k @r
bun-	kers
bh V N	k @r z
bun-	nell
bh V	n V l
bun-	ni
bh u:	n i:
bun-	nie
bh V	n i:
bun-	nies
bh V	n i: z
bun-	ning
bh V	n I N
bun-	ny
bh V	n i:
bun-	ting
bh V n	t I N
bun-	ton
bh V n	t V n
bun-	yan
bh V n	j V n
bunce
bh V n s
bunch
bh V n tS
bunche
bh V n tS
bunched
bh V n tS t
bund
bh V n d
bunde
bh V n d
bunds
bh V n d z
bung
bh V N
bung-	ler
bh V N	g l @r
bung-	lers
bh V N	g l @r z
bunk
bh V N k
bunks
bh V N k s
bunn
bh V n
buns
bh V n z
bunt
bh V n
buo-	no-	mo
bh w @U	n @U	m @U
buo-	y
bh u:	i:
buo-	yan-	cy
bh OI	V n	s i:
buo-	yant
bh OI	V n t
buo-	yed
bh u:	i: d
buo-	ying
bh OI	I N
buo-	ys
bh u:	i: z
bur
bh @r
bur-	bage
bh @r	b I dZ
bur-	bank
bh @r	b { N k
bur-	bank's
bh @r	b { N k s
bur-	chard
bh @r	S Q@ d
bur-	chett
bh @r	tS e t
bur-	de-	ning
bh @r	d V	n I N
bur-	den
bh @r	d V n
bur-	den-	some
bh @r	d V n	s V m
bur-	dened
bh @r	d V n d
bur-	dens
bh @r	d V n z
bur-	dett
bh @r	d I t
bur-	dette
bh @r	d e t
bur-	dick
bh @r	d I k
bur-	dine
bh @r	d i: n
bur-	dine's
bh @r	d i: n z
bur-	don
bh @r	d V n
bur-	ford
bh @r	f @r d
bur-	ge-	ner
bh @r	g i:	n @r
bur-	gee
bh @r	g i:
bur-	ger
bh @r	g @r
bur-	gers
bh @r	g @r z
bur-	ger's
bh @r	g @r z
bur-	gess
bh @r	dZ V s
bur-	get
bh @r	g e t
bur-	gher
bh @r	g @r
bur-	gin
bh @r	g I n
bur-	kle
bh @r	k V l
bur-	lap
bh @r	l { p
bur-	le-	son
bh @r	l V	s V n
bur-	leigh
bh @r	l I
bur-	lesque
bh @r	l e s k
bur-	ley
bh @r	l i:
bur-	li-	son
bh @r	l I	s V n
bur-	lin-	game
bh @r	l I N	g eI m
bur-	lin-	gham
bh @r	l I N	h { m
bur-	ling
bh @r	l I N
bur-	ling-	ton
bh @r	l I N	t V n
bur-	ling-	ton's
bh @r	l I N	t V n z
bur-	ly
bh @r	l i:
bur-	ma
bh @r	m V
bur-	man
bh @r	m V n
bur-	mans
bh @r	m V n z
bur-	ma's
bh @r	m V z
bur-	mese
bh @r	m i: z
bur-	na-	ble
bh @r	n V	b V l
bur-	na-	by
bh @r	n V	b i:
bur-	nard
bh @r	n Q@ d
bur-	ner
bh @r	n @r
bur-	ners
bh @r	n @r z
bur-	net
bh @r	n e t
bur-	nett
bh @r	n e t
bur-	nett's
bh @r	n e t s
bur-	ney
bh @r	n i:
bur-	nham
bh @r	n V m
bur-	nham's
bh @r	n V m z
bur-	ning
bh @r	n I N
bur-	nings
bh @r	n I N z
bur-	nish
bh @r	n I S
bur-	nished
bh @r	n I S t
bur-	nout
bh @r	n aU t
bur-	nup
bh @r	n V p
bur-	ping
bh @r	p I N
bur-	rell
bh @r	e l
bur-	rer
bh @r	@r
bur-	ri-	er
bh @r	i:	@r
bur-	ri-	to
bh @r	i:	t @U
bur-	ri-	tos
bh @r	i:	t @U s
bur-	rill
bh O@	I l
bur-	ris
bh @r	I s
bur-	ro
bh @r	@U
bur-	ro-	wer
bh @r	@U	@r
bur-	ro-	wers
bh @r	@U	@r z
bur-	ro-	wing
bh @r	@U	I N
bur-	ros
bh @r	@U z
bur-	roughs
bh V	r @U z
bur-	row
bh @r	@U
bur-	rows
bh @r	@U z
bur-	rus
bh U@	V s
bur-	ry
bh @r	i:
bur-	son
bh @r	s V n
bur-	sting
bh @r s	t I N
bur-	tis
bh @r	t I s
bur-	ton
bh @r	t V n
bur-	ton's
bh @r	t V n z
bur-	well
bh @r	w e l
burch
bh @r tS
burch-	field
bh @r tS	f i: l d
burck
bh @r k
burck-	hardt
bh @r k	h Q@ t
burd
bh @r d
burg
bh @r g
burg-	la-	ries
bh @r g	l @r	i: z
burg-	la-	rize
bh @r g	l @r	aI z
burg-	la-	rized
bh @r g	l @r	aI z d
burg-	lar
bh @r g	l @r
burge
bh @r g
burge-	o-	ning
bh @r	dZ V	n I N
burge-	on
bh @r	dZ V n
burge-	oned
bh @r	dZ V n d
burgh-	ley
bh @r g	l i:
burk-	ley
bh @r k	l i:
burks
bh @r k s
burl
bh @r l
burn
bh @r n
burn-	ley
bh @r n	l i:
burn-	ley's
bh @r n	l i: z
burn-	side
bh @r n	s aI d
burn-	side's
bh @r n	s aI d z
burn-	up
bh @r	n V p
burne
bh @r n
burned
bh @r n d
burnes
bh @r n z
burns
bh @r n z
burnsed
bh @r n z d
burnt
bh @r n t
burp
bh @r p
burr
bh @r
bursch
bh @r S
burse
bh @r s
burst
bh @r s t
bursts
bh @r s t s
burt
bh @r t
burtt
bh @r t
bus
bh V s
bus-	boy
bh V s	b OI
bus-	boys
bh V s	b OI z
bus-	by
bh V z	b i:
bus-	ch's
bh U	S V z
bus-	ker
bh V s	k @r
bus-	kirk
bh V s	k @r k
bus-	load
bh V s	l @U d
bus-	loads
bh V s	l @U d z
bus-	ser
bh V	s @r
bus-	ses
bh V	s V z
bus-	sey
bh V	s i:
bus-	sing
bh V	s I N
bus-	t-	ling
bh V	s V	l I N
bus-	tard
bh V s	t @r d
bus-	ted
bh V s	t V d
bus-	ter
bh V s	t @r
bus-	ters
bh V s	t @r z
bus-	ti
bh V s	t i:
bus-	tier
bh V s	t j @r
bus-	ting
bh V s	t I N
bus-	tle
bh V	s V l
bus-	to
bh V s	t @U
busch
bh U S
bused
bh V s t
bush
bh U S
bush-	man
bh U S	m V n
bush-	men
bh U S	m e n
bush-	nell
bh U S	n V l
busi-	nes-	ses
bh I z	n V	s V z
busi-	nes-	s's
bh I z	n V	s V z
busi-	ness
bh I z	n V s
busi-	ness-	like
bh I z	n V s	l aI k
busi-	ness-	man
bh I z	n V s	m { n
busi-	ness-	man's
bh I z	n V s	m { n z
busi-	ness-	men
bh I z	n V s	m e n
busi-	ness-	peo-	ple
bh I z	n V s	p i:	p V l
busi-	ness-	per-	son
bh I z	n V s	p @r	s V n
busi-	ness-	wo-	man
bh I z	n V s	w U	m V n
busi-	ness-	wo-	men
bh I z	n V s	w I	m e n
busk
bh V s k
buss
bh V s
bussed
bh V s t
bust
bh V s t
busts
bh V s t s
but
bh V t
but-	che-	ring
bh U	tS @r	I N
but-	che-	ry
bh U	tS @r	i:
but-	cher
bh U	tS @r
but-	chered
bh U	tS @r d
but-	chers
bh U	tS @r z
but-	cher's
bh U	tS @r z
but-	ler
bh V t	l @r
but-	lers
bh V t	l @r z
but-	ler's
bh V t	l @r z
but-	ner
bh V t	n @r
but-	te-	ry
bh V	t @r	i:
but-	ter
bh V	t @r
but-	ter-	ball
bh V	t @r	b O: l
but-	ter-	cup
bh V	t @r	k V p
but-	ter-	cups
bh V	t @r	k V p s
but-	ter-	fat
bh V	t @r	f { t
but-	ter-	field
bh V	t @r	f i: l d
but-	ter-	flies
bh V	t @r f	l aI z
but-	ter-	fly
bh V	t @r f	l aI
but-	ter-	fly's
bh V	t @r f	l aI z
but-	ter-	milk
bh V	t @r	m I l k
but-	ter-	scotch
bh V	t @r s	k Q tS
but-	ter-	worth
bh V	t @r	w @r T
but-	tered
bh V	t @r d
but-	ters
bh V	t @r z
but-	ting
bh V	t I N
but-	tock
bh V	t V k
but-	tocks
bh V	t V k s
but-	ton
bh V	t V n
but-	ton-	hole
bh V	t V n	h @U l
but-	ton-	holed
bh V	t V n	h @U l d
but-	ton-	holes
bh V	t V n	h @U l z
but-	toned
bh V	t V n d
but-	tons
bh V	t V n z
butch
bh U tS
bute
bh j u: t
buts
bh V t s
butt
bh V t
butt-	head
bh V t	h e d
butt-	res-	ses
bh V t	r V	s V z
butt-	res-	sing
bh V t	r V	s I N
butt-	ress
bh V t	r V s
butt-	ressed
bh V t	r V s t
butt-	rick
bh V t	r I k
butte
bh j u: t
butts
bh V t s
bux-	ton
bh V k	s t V n
buy
bh aI
buy-	back
bh aI	b { k
buy-	backs
bh aI	b { k s
buy-	ing
bh aI	I N
buy-	out
bh aI	aU t
buy-	outs
bh aI	aU t s
buys
bh aI z
buz-	zard
bh V	z @r d
buz-	zards
bh V	z @r d z
buz-	zard's
bh V	z @r d z
buz-	zell
bh V	z e l
buz-	zer
bh V	z @r
buz-	zes
bh V	z V z
buz-	zing
bh V	z I N
buz-	zy
bh V	z i:
buzz
bh V z
buzz-	word
bh V z	w @r d
buzz-	words
bh V z	w @r d z
buzzed
bh V z d
by
bh aI
by-	ars
bh aI	@r z
by-	bee
bh aI	b i:
by-	ers
bh aI	@r z
by-	field
bh aI	f i: l d
by-	gone
bh aI	g O: n
by-	gones
bh aI	g O: n z
by-	land
bh aI	l V n d
by-	law
bh aI	l O:
by-	laws
bh aI	l O: z
by-	ler
bh aI	l @r
by-	line
bh aI	l aI n
)"
R"(by-	lines
bh aI	l i: n z
by-	num
bh I	n V m
by-	pas-	ses
bh aI	p {	s V z
by-	pas-	sing
bh aI	p {	s I N
by-	pass
bh aI	p { s
by-	passed
bh aI	p { s t
by-	pro-	duct
bh aI p	r Q	d V k t
by-	pro-	ducts
bh aI p	r O:	d V k t s
by-	ram
bh I@	V m
by-	rle
bh aI	r V l
by-	rom
bh aI	r V m
by-	ron
bh aI	r V n
by-	ron's
bh aI	r V n z
by-	stan-	der
bh aI s	t { n	d @r
by-	stan-	ders
bh aI s	t { n	d @r z
by-	way
bh aI	w eI
by-	ways
bh aI	w eI z
by-	word
bh aI	w @r d
by-	zan-	ti-	um
bh V	z { n	t i:	V m
by-	zan-	tine
bh I	z V n	t aI n
byard
bh j Q@ d
bye
bh aI
bye-	bye
bh aI	b aI
bye-	lo-	rus-	sia
bh e	l @U	r V	S V
byrd
bh @r d
byrd's
bh @r d z
byrn
bh I@ n
byrne
bh @r n
byrnes
bh @r n z
byrne's
bh @r n z
byte
bh aI t
bytes
bh aI t s
c
s i:
c-	3
s i: T	r i:
c-	c
s i:	s i:
c-	c-	s
s i:	s i:	e s
c-	d
s i:	d i:
c-	d-	rom
s i:	d i:	r Q m
c-	ds
s i:	d i: z
c-	e-	a
s i:	i:	eI
c-	mos
s i:	m @U s
c-	n-	n
s i:	e	n e n
c.
s i:
ca
kh V
ca-	b-	ler
kh eI	b V	l @r
ca-	ba
kh Q	b V
ca-	ba-	na
kh V	b {	n V
ca-	ba-	nas
kh V	b {	n V z
ca-	ba-	ret
kh {	b @r	eI
ca-	bal
kh V	b Q l
ca-	bal-	le-	ro
kh {	b V	j e@	@U
ca-	ban
kh eI	b V n
ca-	bell
kh Q	b e l
ca-	ber-	net
kh {	b @r	n eI
ca-	ber-	nets
kh {	b @r	n e t s
ca-	bi-	net
kh {	b I	n V t
ca-	bi-	nets
kh {	b I	n V t s
ca-	bin
kh {	b I n
ca-	bin-	da
kh V	b I n	d V
ca-	bins
kh {	b I n z
ca-	ble
kh eI	b V l
ca-	ble-	gram
kh eI	b V l	g r { m
ca-	ble-	vi-	sion
kh eI	b V l	v I	Z V n
ca-	bled
kh eI	b V l d
ca-	bles
kh eI	b V l z
ca-	ble's
kh eI	b V l z
ca-	bo-	tage
kh {	b V	t I dZ
ca-	boo-	dle
kh V	b u:	d V l
ca-	boo-	ses
kh V	b u:	s V z
ca-	boose
kh V	b u: s
ca-	bot
kh {	b V t
ca-	bot's
kh {	b V t s
ca-	ca-	o
kh V	k eI	@U
ca-	ches
kh {	S V z
ca-	chet
kh {	S eI
ca-	cique
kh V	s i: k
ca-	co-	pho-	ny
kh {	k Q	f V	n i:
ca-	da-	ver
kh V	d {	v @r
ca-	da-	vers
kh V	d {	v @r z
ca-	det
kh V	d e t
ca-	dy
kh eI	d i:
ca-	fe
kh V	f eI
ca-	fe-	te-	ri-	a
kh {	f V	t I@	i:	V
ca-	fe-	te-	ri-	as
kh {	f V	t I@	i:	V z
ca-	fes
kh {	f eI z
ca-	fi-	e-	ro
kh {	f i:	e@	@U
ca-	ges
kh eI	dZ V z
ca-	ge's
kh eI	dZ V z
ca-	gey
kh eI	dZ i:
ca-	gle
kh eI	g V l
ca-	han
kh {	h V n
ca-	hill
kh eI	h I l
ca-	hoot
kh V	h u: t
ca-	hoots
kh V	h u: t s
ca-	jo-	ling
kh V	dZ @U	l I N
ca-	jole
kh V	dZ @U l
ca-	joled
kh V	dZ @U l d
ca-	jun
kh eI	dZ V n
ca-	juns
kh eI	dZ V n z
ca-	la-	ba-	sas
kh {	l V	b Q	s V s
ca-	la-	bre-	se
kh Q	l Q b	r eI	z i:
ca-	la-	di-	ums
kh V	l eI	d i:	V m z
ca-	la-	han
kh {	l V	h { n
ca-	la-	ma-	ri
kh Q	l Q	m Q@	i:
ca-	la-	man-	der
kh {	l V	m { n	d @r
ca-	la-	mi-	ties
kh V	l {	m V	t i: z
ca-	la-	mi-	tous
kh V	l {	m V	t V s
ca-	la-	mi-	ty
kh V	l {	m V	t i:
ca-	la-	mine
kh {	l V	m aI n
ca-	la-	mine's
kh {	l V	m aI n z
ca-	lab-	ri-	a
kh V	l { b	r i:	V
ca-	lais
kh V	l eI
ca-	lan
kh eI	l V n
ca-	lan-	dra
kh V	l { n	d r V
ca-	lan-	tha
kh V	l { n	T V
ca-	le-	do-	ni-	a
kh {	l V	d @U	n i:	V
ca-	le-	do-	ni-	an
kh {	l V	d @U	n i:	V n
ca-	leb
kh eI	l V b
ca-	lef
kh {	l I f
ca-	len-	dar
kh {	l V n	d @r
ca-	len-	dars
kh {	l V n	d @r z
ca-	ley
kh eI	l i:
ca-	li
kh Q	l i:
ca-	li-	a
kh Q	l i:	V
ca-	li-	ber
kh {	l I	b @r
ca-	li-	bra-	ted
kh {	l I b	r eI	t I d
ca-	li-	bra-	tion
kh {	l I b	r eI	S V n
ca-	li-	brate
kh {	l I b	r eI t
ca-	li-	co
kh {	l I	k @U
ca-	li-	da
kh Q	l i:	d V
ca-	li-	for-	nia
kh {	l I	f O@ n	j V
ca-	li-	for-	nian
kh {	l I	f O@ n	j V n
ca-	li-	for-	nians
kh {	l I	f O@ n	j V n z
ca-	li-	for-	nian's
kh {	l I	f O@ n	j V n z
ca-	li-	for-	nia's
kh {	l I	f O@ n	j V z
ca-	li-	per
kh {	l I	p @r
ca-	li-	pers
kh {	l I	p @r z
ca-	liph
kh {	l I f
ca-	lis-	ta
kh V	l I s	t V
ca-	lis-	the-	nic
kh {	l I s	T e	n I k
ca-	lis-	the-	nics
kh {	l I s	T e	n I k s
ca-	lise
kh Q	l aI z
ca-	lite
kh {	l aI t
ca-	lix
kh {	l I k s
ca-	lo
kh Q	l @U
ca-	lo-	ric
kh V	l O@	I k
ca-	lo-	rie
kh {	l @r	i:
ca-	lo-	ries
kh {	l @r	i: z
ca-	lor
kh {	l @r
ca-	lu-	met
kh { l	j V	m e t
ca-	lum-	ny
kh {	l V m	n i:
ca-	lyp-	so
kh V	l I p	s @U
ca-	lyp-	sos
kh V	l I p	s @U z
ca-	lyx
kh {	l I k s
ca-	ma-	cho
kh V	m Q	tS @U
ca-	ma-	ra
kh Q	m Q@	V
ca-	ma-	ra-	de-	rie
kh Q	m @r	Q	d @r	i:
ca-	ma-	ra-	ta
kh Q	m Q@	Q	t V
ca-	ma-	ril-	lo
kh Q	m Q@	I	l @U
ca-	man
kh eI	m V n
ca-	mar-	go
kh Q	m Q@	g @U
ca-	me-	lot
kh {	m V	l Q t
ca-	me-	o
kh {	m i:	@U
ca-	me-	os
kh {	m i:	@U z
ca-	me-	ra
kh {	m @r	V
ca-	me-	ra-	man
kh {	m @r	V	m V n
ca-	me-	ra-	men
kh {	m @r	V	m e n
ca-	me-	ras
kh {	m @r	V z
ca-	me-	ron
kh {	m @r	V n
ca-	me-	ron's
kh {	m @r	V n z
ca-	me-	roon
kh {	m @r	u: n
ca-	mels
kh {	m V l z
ca-	mel's
kh {	m V l z
ca-	mi-	no
kh V	m i:	n @U
ca-	mil-	la
kh V	m I	l V
ca-	mil-	lo
kh V	m I	l @U
ca-	mille
kh V	m i: l
ca-	mor-	ra
kh V	m O@	V
ca-	mou-	fla-	ging
kh {	m V f	l Q	Z I N
ca-	mou-	flage
kh {	m V f	l Q Z
ca-	mou-	flaged
kh {	m V f	l Q Z d
ca-	mus
kh {	m V s
ca-	na
kh {	n V
ca-	na-	ce
kh Q	n Q	tS i:
ca-	na-	da
kh {	n V	d V
ca-	na-	da's
kh {	n V	d V z
ca-	na-	di-	an
kh V	n eI	d i:	V n
ca-	na-	di-	ans
kh V	n eI	d i:	V n z
ca-	na-	le
kh Q	n Q	l i:
ca-	na-	ne-	a
kh {	n V	n i:	V
ca-	na-	ries
kh V	n e@	i: z
ca-	na-	ry
kh V	n e@	i:
ca-	na-	ve-	ral
kh V	n {	v @r	V l
ca-	naa-	nite
kh eI	n V	n aI t
ca-	naan
kh eI	n V n
ca-	nal
kh V	n { l
ca-	nales
kh {	n V l z
ca-	nals
kh V	n { l z
ca-	nal's
kh V	n { l z
ca-	nan-	dai-	gua
kh {	n V n	d eI g	w V
ca-	nard
kh V	n Q@ d
ca-	nas-	ta
kh V	n { s	t V
ca-	ne-	lo
kh V	n e	l @U
ca-	ne-	va-	ri
kh Q	n e	v Q@	i:
ca-	ni-	ster
kh {	n I s	t @r
ca-	ni-	sters
kh {	n I s	t @r z
ca-	nine
kh eI	n aI n
ca-	nines
kh eI	n aI n z
ca-	ning
kh eI	n I N
ca-	nings
kh eI	n I N z
ca-	nion
kh { n	j V n
ca-	no-	ga
kh V	n @U	g V
ca-	no-	la
kh V	n @U	l V
ca-	no-	py
kh {	n V	p i:
ca-	no-	va
kh Q	n @U	v V
ca-	noe
kh V	n u:
ca-	noe-	ing
kh V	n u:	I N
ca-	noe-	ist
kh V	n u:	V s t
ca-	noed
kh V	n u: d
ca-	noes
kh V	n u: z
ca-	non
kh {	n V n
ca-	nons
kh {	n V n z
ca-	non's
kh {	n V n z
ca-	pa-	bi-	li-	ties
kh eI	p V	b I	l V	t i: z
ca-	pa-	bi-	li-	ty
kh eI	p V	b I	l V	t i:
ca-	pa-	ble
kh eI	p V	b V l
ca-	pa-	ci-	tance
kh V	p {	s V	t V n s
ca-	pa-	ci-	ties
kh V	p {	s V	t i: z
ca-	pa-	ci-	tor
kh V	p {	s V	t @r
ca-	pa-	ci-	tors
kh V	p {	s V	t @r z
ca-	pa-	ci-	ty
kh V	p {	s V	t i:
ca-	pa-	cious
kh V	p eI	S V s
ca-	pek
kh {	p I k
ca-	pel
kh eI	p V l
ca-	pel-	la
kh V	p e	l V
ca-	pel-	lo
kh V	p e	l @U
ca-	per
kh eI	p @r
ca-	pers
kh eI	p @r z
ca-	pi-	ta
kh {	p I	t V
ca-	pi-	ta-	li-	sm
kh {	p I	t V	l I	z V m
ca-	pi-	ta-	li-	sm's
kh {	p I	t V	l I	z V m z
ca-	pi-	ta-	li-	za-	tion
kh {	p I	t V	l I	z eI	S V n
ca-	pi-	ta-	li-	za-	tions
kh {	p I	t V	l I	z eI	S V n z
ca-	pi-	ta-	li-	zes
kh {	p I	t V	l aI	z V z
ca-	pi-	ta-	li-	zing
kh {	p I	t V	l aI	z I N
ca-	pi-	ta-	lis-	tic
kh {	p I	t V	l I s	t I k
ca-	pi-	ta-	list
kh {	p I	t V	l I s t
ca-	pi-	ta-	lists
kh {	p I	t V	l I s t s
ca-	pi-	ta-	lize
kh {	p I	t V	l aI z
ca-	pi-	ta-	lized
kh {	p I	t V	l aI z d
ca-	pi-	ta-	no
kh Q	p i:	t Q	n @U
ca-	pi-	tal
kh {	p I	t V l
ca-	pi-	tals
kh {	p I	t V l z
ca-	pi-	tal's
kh {	p I	t V l z
ca-	pi-	tan
kh {	p I	t V n
ca-	pil-	la-	ries
kh {	p I	l e@	i: z
ca-	pil-	la-	ry
kh {	p I	l e@	i:
ca-	pis-	tra-	no
kh {	p I s	t r Q	n @U
ca-	po-	ten
kh V	p @U	t V n
ca-	pote
kh V	p @U t
ca-	pote's
kh V	p @U t s
ca-	pu-	a
kh { p	j u:	V
ca-	pu-	to
kh Q	p u:	t @U
ca-	ra
kh e@	V
ca-	ra-	ca-	ra
kh Q@	V	k Q@	V
ca-	ra-	cas
kh @r	Q	k V s
ca-	ra-	fate
kh e@	V	f eI t
ca-	ra-	me-	lize
kh e@	V	m V	l aI z
ca-	ra-	me-	lized
kh e@	V	m V	l aI z d
ca-	ra-	mel
kh e@	V	m V l
ca-	ra-	van
kh {	r V	v { n
ca-	ra-	vans
kh {	r V	v { n z
ca-	ra-	vel
kh e@	V	v e l
ca-	ra-	velle
kh e@	V	v e l
ca-	ra-	way
kh {	r V	w eI
ca-	ras
kh Q@	V z
ca-	ra's
kh e@	V z
ca-	rat
kh e@	V t
ca-	rats
kh e@	V t s
ca-	re-	na
kh e@	i:	n V
ca-	ree-	ning
kh @r	i:	n I N
ca-	ree-	ri-	sm
kh V	r i:	r V	z V m
ca-	ree-	rist
kh @r	I@	I s t
ca-	ree-	rists
kh @r	I@	I s t s
ca-	reen
kh @r	i: n
ca-	reened
kh @r	i: n d
ca-	reens
kh @r	i: n z
ca-	reer
kh @r	I@
ca-	reers
kh @r	I@ z
ca-	rel
kh Q@	e l
ca-	rer
kh e@	@r
ca-	res-	sing
kh @r	e	s I N
ca-	ress
kh @r	e s
ca-	resse
kh Q@	e s
ca-	rew
kh {	r u:
ca-	rey
kh e@	i:
ca-	rey's
kh e@	i: z
ca-	ri-	bou
kh e@	I	b u:
ca-	ri-	ca-	tu-	rist
kh e@	I	k V	tS @r	I s t
ca-	ri-	ca-	ture
kh e@	I	k V	tS @r
ca-	ri-	ca-	tured
kh @r	I	k V	tS @r d
ca-	ri-	ca-	tures
kh @r	I	k V	tS @r z
ca-	ri-	ne
kh Q@	i:	n i:
ca-	ri-	nii
kh e@	i:	n i:
ca-	ri-	o-	ca
kh e@	i:	@U	k V
ca-	ri-	ta
kh Q@	i:	t V
ca-	rib-	be-	an
kh @r	I	b i:	V n
ca-	ribe
kh e@	i: b
ca-	rie
kh e@	i:
ca-	rig-	nan
kh {	r I g	n V n
ca-	ril-	la
kh Q@	I	l V
ca-	ril-	lon
kh e@	I	l Q n
ca-	rin
kh {	r I n
ca-	ring
kh e@	I N
ca-	ris-	sa
kh Q@	i:	s V
ca-	ro
kh Q@	@U
ca-	ro-	lan
kh e@	V	l { n
ca-	ro-	li-	na
kh e@	V	l aI	n V
ca-	ro-	li-	nas
kh e@	V	l aI	n V z
ca-	ro-	li-	na's
kh e@	V	l aI	n V z
ca-	ro-	li-	ni-	an
kh e@	@U	l I	n i:	V n
ca-	ro-	li-	ni-	ans
kh e@	V	l I	n i:	V n z
ca-	ro-	lin-	gi-	an
kh e@	V	l I n	dZ i:	V n
ca-	ro-	line
kh e@	V	l aI n
ca-	ro-	line's
kh e@	V	l aI n z
ca-	ro-	lus
kh e@	V	l V s
ca-	ro-	lyn
kh e@	V	l V n
ca-	ro-	lyne
kh e@	V	l aI n
ca-	ro-	sel-	la
kh Q@	@U	s e	l V
ca-	ro-	ta
kh @r	@U	t V
ca-	ro-	tene
kh e@	V	t i: n
ca-	ro-	thers
kh {	r V	D @r z
ca-	ro-	tid
kh @r	Q	t I d
ca-	rob
kh e@	V b
ca-	roche
kh @r	@U tS
ca-	rol
kh {	r V l
ca-	role
kh {	r V l
ca-	rols
kh e@	V l z
ca-	rol's
kh {	r V l z
ca-	ron
kh Q@	O: n
ca-	rone
kh @r	@U n
ca-	rou-	sel
kh e@	V	s e l
ca-	rou-	sing
kh @r	aU	z I N
ca-	rouse
kh @r	aU z
ca-	ru-	so
kh @r	u:	s @U
ca-	ru-	thers
kh @r	V	D @r z
ca-	ry
kh e@	i:
ca-	ryl
kh e@	V l
ca-	ryn
kh Q@	I n
ca-	sa
kh Q	s V
ca-	sa-	dy
kh V	s Q	d i:
ca-	sa-	no-	va
kh {	s V	n @U	v V
ca-	sa-	vant
kh {	s V	v V n t
ca-	sab-	lan-	ca
kh {	s V b	l { N	k V
ca-	sal
kh Q	s Q l
ca-	sals
kh Q	s Q l z
ca-	sas
kh Q	s V z
ca-	se-	loads
kh {	s V	l @U d z
ca-	sein
kh eI	s i: n
ca-	ser-	ta
kh Q	s e@	t V
ca-	ses
kh eI	s V z
ca-	se's
kh eI	s V z
ca-	sey
kh eI	s i:
ca-	sey's
kh eI	s i: z
ca-	sher
kh {	S @r
ca-	shes
kh {	S V z
ca-	shew
kh {	S u:
ca-	shews
kh {	S u: z
ca-	shier
kh {	S I@
ca-	shiered
kh {	S I@ d
ca-	shiers
kh {	S I@ z
ca-	shier's
kh {	S I@ z
ca-	shing
kh {	S I N
ca-	shion
kh Q	S i: n
ca-	si-	mir
kh {	s I	m i: r
ca-	si-	no
kh V	s i:	n @U
ca-	si-	nos
kh V	s i:	n @U z
ca-	si-	no's
kh V	s i:	n @U z
ca-	si-	o
kh {	s i:	@U
ca-	sing
kh eI	s I N
ca-	sings
kh eI	s I N z
ca-	son
kh {	s V n
ca-	su-	al
kh {	Z V	w V l
ca-	su-	al-	ly
kh {	Z V	w V	l i:
ca-	su-	al-	ness
kh {	Z V	w V l	n V s
ca-	su-	al-	ties
kh {	Z V	w V l	t i: z
ca-	su-	al-	ty
kh {	Z V	w V l	t i:
ca-	su-	als
kh {	Z V	w V l z
ca-	ta-	comb
kh {	t V	k @U m
ca-	ta-	combs
kh {	t V	k @U m z
ca-	ta-	lan
kh {	t V	l V n
ca-	ta-	li-	na
kh {	t V	l i:	n V
ca-	ta-	lo-	ger
kh {	t V	l O:	g @r
ca-	ta-	lo-	gers
kh {	t V	l O:	g @r z
ca-	ta-	lo-	ging
kh {	t V	l Q	g I N
ca-	ta-	lo-	guing
kh {	t V	l O:	g I N
ca-	ta-	lo-	nia
kh {	t V	l @U n	j V
ca-	ta-	log
kh {	t V	l O: g
ca-	ta-	loged
kh {	t V	l O: g d
ca-	ta-	logs
kh {	t V	l Q g z
ca-	ta-	logue
kh {	t V	l O: g
ca-	ta-	logued
kh {	t V	l O: g d
ca-	ta-	logues
kh {	t V	l O: g z
ca-	ta-	ly-	tic
kh {	t V	l I	t I k
ca-	ta-	lyst
kh {	t V	l V s t
ca-	ta-	lysts
kh {	t V	l V s t s
ca-	ta-	lyst's
kh {	t V	l V s t s
ca-	ta-	lyze
kh {	t V	l aI z
ca-	ta-	lyzed
kh {	t V	l aI z d
ca-	ta-	ma-	ran
kh {	t V	m @r	{ n
ca-	ta-	ma-	rans
kh V	t {	m @r	V n z
ca-	ta-	mount
kh {	t V	m aU n t
ca-	ta-	nia
kh V	t eI n	j V
ca-	ta-	no
kh Q	t Q	n @U
ca-	ta-	pul-	ted
kh {	t V	p V l	t V d
ca-	ta-	pul-	ting
kh {	t V	p V l	t I N
ca-	ta-	pult
kh {	t V	p V l t
ca-	ta-	pults
kh {	t V	p V l t s
ca-	ta-	ract
kh {	t @r	{ k t s
ca-	ta-	racts
kh {	t @r	{ k t s
ca-	ta-	to-	nic
kh {	t V	t Q	n I k
ca-	tac-	ly-	sm
kh {	t V k	l I	s V m
ca-	tac-	lys-	mic
kh {	t V k	l I z	m I k
ca-	tal-	do
kh Q	t Q l	d @U
ca-	tan-	za-	ro
kh Q	t Q n	z Q@	@U
ca-	tas-	tro-	phe
kh V	t { s	t r V	f i:
ca-	tas-	tro-	phes
kh V	t { s	t r V	f i: z
ca-	tas-	tro-	phic
kh {	t V s	t r Q	f I k
ca-	taw-	ba
kh V	t O:	b V
ca-	te-	chi-	sm
kh {	t V	k I	z V m
ca-	te-	go-	ri-	cal
kh {	t V	g Q@	I	k V l
ca-	te-	go-	ri-	za-	tion
kh {	t V	g @r	V	z eI	S V n
ca-	te-	go-	ri-	zes
kh {	t V	g @r	aI	z V z
ca-	te-	go-	ri-	zing
kh {	t V	g @r	aI	z I N
ca-	te-	go-	rical-	ly
kh {	t V	g Q@	I k	l i:
ca-	te-	go-	ries
kh {	t V	g O@	i: z
ca-	te-	go-	rize
kh {	t V	g @r	aI z
ca-	te-	go-	rized
kh {	t V	g @r	aI z d
ca-	te-	go-	ry
kh {	t V	g O@	i:
ca-	te-	na
kh V	t i:	n V
ca-	te-	rer
kh eI	t @r	@r
ca-	te-	rers
kh eI	t @r	@r z
ca-	te-	ring
kh eI	t @r	I N
ca-	ter
kh eI	t @r
ca-	ter-	pil-	lar
kh {	t V	p I	l @r
ca-	ter-	pil-	lars
kh {	t V	p I	l @r z
ca-	ter-	pil-	lar's
kh {	t @r	p I	l @r z
ca-	tered
kh eI	t @r d
ca-	ters
kh eI	t @r z
ca-	thay
kh {	T eI
ca-	the-	dral
kh V	T i: d	r V l
ca-	the-	drals
kh V	T i: d	r V l z
ca-	the-	ri-	na
kh Q	T @r	i:	n V
ca-	the-	rine
kh {	T @r	I n
ca-	the-	ter
kh {	T V	t @r
ca-	the-	ters
kh {	T V	t @r z
ca-	ther
kh {	D @r
ca-	ther-	wood
kh {	D @r	w U d
ca-	ther's
kh {	D @r z
ca-	they
kh {	D i:
ca-	thie
kh {	T i:
ca-	tho-	li-	ci-	sm
kh V	T O:	l V	s I	z V m
ca-	thode
kh {	T @U d
ca-	thodes
kh {	T @U d z
ca-	thy
kh {	T i:
ca-	thy's
kh {	T i: z
ca-	to
kh eI	t @U
ca-	ton
kh {	t V n
ca-	va
kh Q	v V
ca-	va-	lie-	re
kh Q	v Q	l I@	i:
ca-	va-	lie-	ri
kh Q	v Q	l I@	i:
ca-	va-	lie-	rly
kh {	v V	l I@	l i:
ca-	va-	lier
kh {	v V	l I@
ca-	va-	liers
kh {	v V	l I@ z
ca-	va-	nagh
kh {	v V	n { g
ca-	va-	naugh
kh {	v V	n O:
ca-	val-	cade
kh {	v V l	k eI d
ca-	val-	la-	ro
kh Q	v Q	l Q@	@U
ca-	val-	ry
kh {	v V l	r i:
ca-	van
kh eI	v V n
ca-	ve-	at
kh eI	v i:	{ t
ca-	ve-	ats
kh eI	v i:	{ t s
ca-	vell
kh V	v e l
ca-	ven-	dish
kh {	v V n	d I S
ca-	ver
kh eI	v @r
ca-	ver-	nous
kh {	v @r	n V s
ca-	vern
kh {	v @r n
ca-	verns
kh {	v @r n z
ca-	vers
kh eI	v @r z
ca-	vey
kh eI	v i:
ca-	vi-	ar
kh {	v i:	Q@
ca-	vi-	ness
kh eI	v i:	n V s
ca-	vi-	ties
kh {	v I	t i: z
ca-	vi-	ty
kh {	v I	t i:
ca-	vin
kh {	v I n
ca-	ving
kh eI	v I N
ca-	vor-	ting
kh V	v O@	t I N
ca-	vort
kh V	v O@ t
ca-	wood
kh Q	w U d
ca-	yu-	ses
kh aI	u:	s V z
cab
kh { b
cab-	ba-	ges
kh {	b V	dZ V z
cab-	bage
kh {	b V dZ
cab-	bie
kh {	b i:
cab-	bies
kh {	b i: z
cab-	by
kh {	b i:
cab-	dri-	ver
kh { b	d r aI	v @r
cab-	dri-	vers
kh { b	d r aI	v @r z
cab-	ral
kh { b	r V l
cab-	re-	ra
kh Q b	r e@	V
cab-	ri-	ni
kh V b	r i:	n i:
cab-	ri-	ni's
kh V b	r i:	n i: z
cab-	ri-	o-	let
kh { b	r i:	@U	l eI
cabe
kh eI b
cabi-	net-	ry
kh { b	n V t	r i:
cabi-	net's
kh { b	n V t s
cabs
kh { b z
cab's
kh { b z
cac
kh { k
cac-	cia
kh Q	tS V
cac-	cia-	to-	re
kh Q	tS V	t O@	i:
cac-	k-	ling
kh {	k V	l I N
cac-	kle
kh {	k V l
cac-	ti
kh { k	t aI
cac-	tus
kh { k	t V s
cache
kh { S
cad
kh { d
cad-	bu-	ry
kh { d	b e@	i:
cad-	bu-	ry's
kh { d	b e@	i: z
cad-	dies
kh {	d i: z
cad-	wa-	la-	der
kh { d	w O:	l V	d @r
cad-	wa-	la-	der's
kh { d	w O:	l V	d @r z
cad-	wal-	la-	der
kh { d	w O:	l V	d @r
cad-	well
kh { d	w e l
cae-	sa-	re-	a
kh eI	s @r	i:	V
cae-	sa-	rean
kh eI	s @r	i: n
cae-	sa-	reans
kh eI	s @r	i: n z
cae-	sar
s i:	z @r
cae-	sars
s i:	z @r z
cae-	sar's
s i:	z @r z
cae-	ta-	no
kh V	t Q	n @U
caen
kh { n
caen's
kh { n z
caf-	fei-	na-	ted
kh {	f V	n eI	t V d
caf-	feine
kh {	f i: n
caff-	rey
kh { f	r i:
cag-	li-	a-	ri
kh { g	l i:	Q@	i:
cag-	ney
kh { g	n i:
cag-	uas
kh Q g	w Q s
cage
kh eI dZ
caged
kh eI dZ d
cahn
kh { n
cai
kh aI
cai-	ro
kh aI	r @U
cai-	ro's
kh aI	r @U z
cain
kh eI n
caine
kh eI n
caines
kh eI n z
cain's
kh eI n z
cairns
kh e@ n z
caisse
kh eI s
cait-	lin
kh eI t	l I n
cake
kh eI k
caked
kh eI k t
cakes
kh eI k s
cake's
kh eI k s
cal
kh { l
cal-	bert
kh { l	b @r t
cal-	ci-	fied
kh { l	s I	f aI d
cal-	ci-	fy
kh { l	s I	f aI
cal-	ci-	um
kh { l	s i:	V m
cal-	cite
kh { l	s aI t
cal-	comp
kh O: l	k Q m p
cal-	cu-	la-	ted
kh { l	k j V	l eI	t V d
cal-	cu-	la-	ting
kh { l	k j V	l eI	t I N
cal-	cu-	la-	tion
kh { l	k j V	l eI	S V n
cal-	cu-	la-	tions
kh { l	k j V	l eI	S V n z
cal-	cu-	la-	tor
kh { l	k j V	l eI	t @r
cal-	cu-	la-	tors
kh { l	k j V	l eI	t @r z
cal-	cu-	late
kh { l	k j V	l eI t
cal-	cu-	lates
kh { l	k j V	l eI t s
cal-	cu-	lus
kh { l	k j V	l V s
cal-	cut-	ta
kh { l	k V	t V
cal-	de-	ra
kh { l	d e@	V
cal-	de-	ron
kh O: l	d @r	Q n
cal-	dei-	ra
kh Q l	d e@	V
cal-	der
kh O: l	d @r
cal-	ga-	ry
kh { l	g @r	i:
cal-	gon
kh { l	g O: n
cal-	houn
kh { l	h u: n
cal-	kin
kh { l	k I n
cal-	kins
kh { l	k I n z
cal-	la
kh {	l V
cal-	la-	ble
kh O:	l V	b V l
cal-	la-	ghan
kh {	l V	h { n
)"
R"(cal-	la-	han
kh {	l V	h { n
cal-	la-	han's
kh {	l V	h { n z
cal-	la-	way
kh {	l V	w eI
cal-	la-	way's
kh O:	l V	w eI z
cal-	lais
kh V	l eI
cal-	lan
kh {	l V n
cal-	las
kh {	l V z
cal-	le-	ry
kh {	l @r	i:
cal-	len-	der
kh V	l e n	d @r
cal-	ler
kh O:	l @r
cal-	lers
kh O:	l @r z
cal-	ler's
kh O:	l @r z
cal-	ley
kh {	l i:
cal-	li-	gra-	phic
kh {	l I g	r {	f I k
cal-	li-	gra-	phy
kh V	l I g	r V	f i:
cal-	li-	o-	pe
kh V	l aI	V	p i:
cal-	li-	o-	pes
kh V	l aI	V	p i: z
cal-	lie
kh O:	l i:
cal-	ling
kh O:	l I N
cal-	lo-	way
kh {	l @U	w eI
cal-	lous
kh {	l V s
cal-	lous-	ly
kh {	l V s	l i:
cal-	lous-	ness
kh {	l V s	n V s
cal-	loused
kh {	l V s t
cal-	low
kh {	l @U
cal-	lum
kh {	l V m
cal-	lus
kh {	l V s
cal-	ly
kh {	l i:
cal-	mar
kh { l	m Q@
cal-	mer
kh Q	m @r
cal-	ming
kh Q	m I N
cal-	tha
kh { l	D V
cal-	va-	no
kh Q l	v Q	n @U
cal-	va-	ries
kh { l	v @r	i: z
cal-	va-	ry
kh { l	v @r	i:
cal-	vert
kh { l	v @r t
cal-	vi-	na
kh Q l	v i:	n V
cal-	vi-	nist
kh { l	v I	n I s t
cal-	vin
kh { l	v I n
cal-	ving
kh {	v I N
cal-	vin's
kh { l	v I n z
cal-	vo
kh Q l	v @U
cal-	za-	da
kh Q l	z Q	d V
cald-	well
kh O: l	d w e l
cald-	well's
kh O: l	d w e l z
cale
kh eI l
calf
kh { f
calf's
kh { f s
calk
kh O: k
call
kh O: l
calle
kh eI l
called
kh O: l d
calles
kh eI l z
calls
kh O: l z
call's
kh Q l z
calm
kh Q m
calm-	ly
kh Q m	l i:
calm-	ness
kh Q m	n V s
calmed
kh Q m d
calms
kh Q m z
calves
kh { v z
cam
kh { m
cam-	ber
kh { m	b @r
cam-	mie
kh {	m i:
cam-	my
kh {	m i:
cam-	pa
kh { m	p V
cam-	pa-	na
kh Q m	p {	n V
cam-	pa-	nel-	la
kh { m	p V	n e	l V
cam-	paig-	ner
kh { m	p eI	n @r
cam-	paig-	ners
kh { m	p eI	n @r z
cam-	paig-	ning
kh { m	p eI	n I N
cam-	paign
kh { m	p eI n
cam-	paigned
kh { m	p eI n d
cam-	paigns
kh { m	p eI n z
cam-	paign's
kh { m	p eI n z
cam-	pe-	si-	nos
kh { m	p e	s i:	n @U s
cam-	per
kh { m	p @r
cam-	pers
kh { m	p @r z
cam-	pi
kh { m	p i:
cam-	pi-	on
kh { m	p i:	V n
cam-	ping
kh { m	p I N
cam-	po
kh { m	p @U
cam-	pos
kh { m	p @U z
cam-	pu-	ses
kh { m	p V	s V z
cam-	pus
kh { m	p V s
cam-	py
kh { m	p i:
cam-	ry
kh { m	r i:
cam-	shaft
kh { m	S { f t
cam-	shafts
kh { m	S { f t s
came-	ra's
kh { m	r V z
camm
kh { m
camp
kh { m p
camp-	bell
kh { m	b V l
camp-	bell's
kh { m	b V l z
camp-	fi-	re
kh { m	p f aI	@r
camp-	fi-	res
kh { m	p f aI	@r z
camp-	ground
kh { m	p g r aU n d
camp-	grounds
kh { m	p g r aU n d z
camp-	site
kh { m	p s aI t s
camp-	sites
kh { m	p s aI t s
camp-	ton
kh { m	p t V n
camped
kh { m p t
camps
kh { m p s
camp's
kh { m p s
cam's
kh { m z
can
kh { n
can-	ber-	ra
kh { n	b e@	V
can-	by
kh { n	b i:
can-	can
kh { n	k { n
can-	ce-	ling
kh { n	s V	l I N
can-	ce-	rous
kh { n	s @r	V s
can-	cel
kh { n	s V l
can-	cel-	la-	tion
kh { n	s V	l eI	S V n
can-	cel-	la-	tions
kh { n	s V	l eI	S V n z
can-	cel-	ling
kh { n	s V	l I N
can-	celed
kh { n	s V l d
can-	celled
kh { n	s V l d
can-	cels
kh { n	s V l z
can-	cer
kh { n	s @r
can-	cer-	pho-	bi-	a
kh { n	s @r	f @U	b i:	V
can-	cers
kh { n	s @r z
can-	cer's
kh { n	s @r z
can-	cun
kh { N	k V n
can-	d-	ler
kh { n	d V	l @r
can-	dace
kh { n	d V s
can-	de-	la
kh { n	d e	l V
can-	de-	lab-	ra
kh { n	d V	l Q b	r V
can-	dee
kh { n	d i:
can-	di-	a
kh { n	d i:	V
can-	di-	ce's
kh { n	d I	s V z
can-	di-	da
kh { n	d I	d V
can-	di-	da-	cies
kh { n	d I	d V	s i: z
can-	di-	da-	cy
kh { n	d I	d V	s i:
can-	di-	date
kh { n	d I	d eI t
can-	di-	dates
kh { n	d I	d eI t s
can-	di-	date's
kh { n	d I	d eI t s
can-	di-	dly
kh { n	d I d	l i:
can-	dice
kh { n	d I s
can-	did
kh { n	d I d
can-	die
kh { n	d i:
can-	died
kh { n	d i: d
can-	dies
kh { n	d i: z
can-	dle
kh { n	d V l
can-	dle-	light
kh { n	d V l	l aI t
can-	dle-	ma-	ker
kh { n	d V l	m eI	k @r
can-	dle-	stick
kh { n	d V l	s t I k
can-	dle-	sticks
kh { n	d V l	s t I k s
can-	dles
kh { n	d V l z
can-	dor
kh { n	d @r
can-	dy
kh { n	d i:
can-	dy's
kh { n	d i: z
can-	field
kh { n	f i: l d
can-	ham
kh { n	h V m
can-	ker
kh { N	k @r
can-	kers
kh { N	k @r z
can-	na-	bis
kh {	n V	b V s
can-	ne-	ries
kh {	n @r	i: z
can-	ne-	ry
kh {	n @r	i:
can-	nel-	ton
kh {	n V l	t V n
can-	nell
kh {	n V l
can-	ner
kh {	n @r
can-	ni-	ba-	li-	sm
kh {	n I	b V	l I	z V m
can-	ni-	ba-	li-	za-	tion
kh {	n I	b V	l I	z eI	S V n
can-	ni-	ba-	li-	zing
kh {	n I	b V	l aI	z I N
can-	ni-	ba-	lize
kh {	n I	b V	l aI z
can-	ni-	bal
kh {	n I	b V l
can-	ni-	bals
kh {	n I	b V l z
can-	ning
kh {	n I N
can-	nis-	ter
kh {	n I s	t @r
can-	nis-	ters
kh {	n I s	t @r z
can-	niz-	za-	ro
kh Q	n i: t	s Q@	@U
can-	non
kh {	n V n
can-	non-	ball
kh {	n V n	b O: l
can-	nons
kh {	n V n z
can-	non's
kh {	n V n z
can-	nons-	burg
kh {	n V n	z b @r g
can-	not
kh {	n Q t
can-	ny
kh {	n i:
can-	so
kh { n	s @U
can-	ta-	loupe
kh { n	t V	l @U p
can-	ta-	loupes
kh { n	t V	l @U p s
can-	ta-	ra
kh Q n	t Q@	V
can-	ta-	ta
kh { n	t Q	t V
can-	tan-	ke-	rous
kh { n	t { N	k @r	V s
can-	teen
kh { n	t i: n
can-	teens
kh { n	t i: n z
can-	tel
kh { n	t e l
can-	ter
kh { n	t @r
can-	ter-	bu-	ry
kh { n	t @r	b e@	i:
can-	ter-	bu-	ry's
kh { n	t @r	b e@	i: z
can-	ti-	na
kh { n	t i:	n V
can-	tle
kh { n	t V l
can-	to
kh { n	t @U
can-	to-	nal
kh { n	t V	n V l
can-	to-	ne
kh Q n	t @U	n i:
can-	to-	nese
kh { n	t V	n i: z
can-	ton
kh { n	t V n
can-	tons
kh { n	t V n z
can-	tor
kh { n	t @r
can-	tor's
kh { n	t @r z
can-	tu
kh { n	t u:
can-	ty
kh { n	t i:
can-	va-	ses
kh { n	v V	s V z
can-	vas
kh { n	v V s
can-	vas-	sers
kh { n	v V	s @r z
can-	vas-	ses
kh { n	v V	s V z
can-	vas-	sing
kh { n	v V	s I N
can-	vass
kh { n	v V s
can-	vassed
kh { n	v V s t
can-	yon
kh { n	j V n
can-	yons
kh { n	j V n z
can-	yon's
kh { n	j V n z
cane
kh eI n
caned
kh eI n d
canes
kh eI n z
cann
kh { n
canned
kh { n d
cannes
kh { n z
cans
kh { n z
can's
kh { n z
cant
kh { n t
can't
kh { n t
cant-	lon
kh { n	t l V n
cant-	rall
kh { n	t r V l
cant-	rell
kh { n	t r e l
cap
kh { p
cap-	pa
kh {	p V
cap-	pel-	la
kh Q	p e	l V
cap-	pel-	let-	ti
kh Q	p e	l e	t i:
cap-	pel-	lo
kh Q	p e	l @U
cap-	per
kh {	p @r
cap-	ping
kh {	p I N
cap-	puc-	ci-	no
kh {	p u:	tS i:	n @U
cap-	py
kh {	p i:
cap-	ra
kh { p	r V
cap-	ri
kh { p	r i:
cap-	ri-	cious
kh V p	r I	S V s
cap-	ri-	cious-	ly
kh V p	r I	S V s	l i:
cap-	ri-	corn
kh { p	r I	k O@ n
cap-	rice
kh V p	r i: s
cap-	ri's
kh { p	r i: z
cap-	ron
kh { p	r V n
cap-	sai-	cin
kh { p	s eI	s I n
cap-	shaw
kh { p	S O:
cap-	size
kh { p	s aI z
cap-	sized
kh { p	s aI z d
cap-	sule
kh { p	s V l
cap-	sules
kh { p	s V l z
cap-	tain
kh { p	t @ n
cap-	tains
kh { p	t @ n z
cap-	tain's
kh { p	t @ n z
cap-	ti-	va-	ted
kh { p	t I	v eI	t I d
cap-	ti-	va-	ting
kh { p	t I	v eI	t I N
cap-	ti-	vate
kh { p	t I	v eI t
cap-	ti-	vi-	ty
kh { p	t I	v V	t i:
cap-	tion
kh { p	S V n
cap-	tion-	ing
kh { p	S V	n I N
cap-	tioned
kh { p	S V n d
cap-	tions
kh { p	S V n z
cap-	tive
kh { p	t I v
cap-	tives
kh { p	t I v z
cap-	tor
kh { p	t @r
cap-	tors
kh { p	t @r z
cap-	tur-	ing
kh { p	tS @r	I N
cap-	ture
kh { p	tS @r
cap-	tured
kh { p	tS @r d
cap-	tures
kh { p	tS @r z
cap-	well
kh { p	w e l
cape
kh eI p
cape-	town
kh eI p	t aU n
caped
kh eI p t
capes
kh eI p s
capp
kh { p
capped
kh { p t
capps
kh { p s
caps
kh { p s
cap's
kh { p s
caps-	tan
kh { p	s t V n
caps-	tone
kh { p	s t @U n
car
kh Q@
car-	ber-	ry
kh Q@	b e@	i:
car-	ber-	ry's
kh Q@	b e@	i: z
car-	bide
kh Q@	b aI d
car-	bide's
kh Q@	b aI d z
car-	bin
kh Q@	b I n
car-	bine
kh Q@	b aI n
car-	bo
kh Q@	b @U
car-	bo-	hyd-	rate
kh Q@	b @U	h aI d	r eI t
car-	bo-	hyd-	rates
kh Q@	b @U	h aI d	r eI t s
car-	bo-	na-	ra
kh Q@	b @U	n Q@	V
car-	bo-	na-	ro
kh Q@	b @U	n Q@	@U
car-	bo-	na-	ted
kh Q@	b V	n eI	t V d
car-	bo-	nate
kh Q@	b V	n eI t
car-	bo-	nates
kh Q@	b V	n eI t s
car-	bo-	ni
kh Q@	b @U	n i:
car-	bo-	ni-	fe-	rous
kh Q@	b V	n I	f @r	V s
car-	bo-	nize
kh Q@	b V	n aI z
car-	bo-	nized
kh Q@	b V	n aI z d
car-	bo-	run-	dum
kh Q@	b @r	V n	d V m
car-	bon
kh Q@	b V n
car-	bon-	dale
kh Q@	b V n	d eI l
car-	bone
kh Q@	b @U n
car-	bons
kh Q@	b V n z
car-	boy
kh Q@	b OI
car-	bu-	re-	ted
kh Q@ b	j @r	e	t V d
car-	bu-	re-	tion
kh Q@ b	j @r	i:	S V n
car-	bu-	re-	tor
kh Q@	b @r	eI	t @r
car-	bu-	re-	tors
kh Q@	b @r	eI	t @r z
car-	by
kh Q@	b i:
car-	cas-	ses
kh Q@	k V	s V z
car-	cass
kh Q@	k V s
car-	ci-	no-	ge-	nic
kh Q@	s I	n @U	dZ e	n I k
car-	ci-	no-	gen
kh Q@	s I	n V	dZ V n
car-	ci-	no-	gens
kh Q@	s I	n V	dZ V n z
car-	ci-	no-	ma
kh Q@	s I	n @U	m V
car-	de-	na-	s's
kh Q@	d i:	n V	s V z
car-	de-	nas
kh Q@	d i:	n V s
car-	ded
kh Q@	d V d
car-	der
kh Q@	d @r
car-	di-	a
kh Q@	d i:	V
car-	di-	ac
kh Q@	d i:	{ k
car-	di-	gan
kh Q@	d I	g V n
car-	di-	gans
kh Q@	d I	g V n z
car-	di-	nal
kh Q@	d I	n V l
car-	di-	nals
kh Q@	d I	n V l z
car-	di-	nal's
kh Q@	d I	n V l z
car-	di-	o-	lo-	gist
kh Q@	d i:	Q	l V	dZ V s t
car-	di-	o-	lo-	gists
kh Q@	d i:	Q	l V	dZ V s t s
car-	di-	o-	lo-	gy
kh Q@	d i:	Q	l V	dZ i:
car-	di-	o-	pul-	mo-	na-	ry
kh Q@	d i:	@U	p U l	m V	n e@	i:
car-	di-	o-	vas-	cu-	lar
kh Q@	d i:	@U	v { s	k j V	l @r
car-	di-	zem
kh Q@	d I	z e m
car-	diff
kh Q@	d I f
car-	din
kh Q@	d I n
car-	dis
kh Q@	d I s
car-	do-	na
kh Q@	d @U	n V
car-	do-	zo
kh Q@	d @U	z @U
car-	don
kh Q@	d O: n
car-	doon
kh Q@	d u: n
car-	duc-	ci
kh Q@	d u:	tS i:
car-	dy
kh Q@	d i:
car-	gill
kh Q@	g I l
car-	go
kh Q@	g @U
car-	goes
kh Q@	g @U z
car-	gos
kh Q@	g @U z
car-	go's
kh Q@	g @U z
car-	hart
kh Q@	h Q@ t
car-	jac-	ker
kh Q@	dZ {	k @r
car-	jac-	kers
kh Q@	dZ {	k @r z
car-	jac-	king
kh Q@	dZ {	k I N
car-	jac-	kings
kh Q@	dZ {	k I N z
car-	jack
kh Q@	dZ { k
car-	jacked
kh Q@	dZ { k t
car-	jacks
kh Q@	dZ { k s
car-	la
kh Q@	l V
car-	land
kh Q@	l V n d
car-	la's
kh Q@	l V z
car-	le
kh Q@	V l
car-	leen
kh Q@	l i: n
car-	len
kh Q@	l V n
car-	lene
kh Q@	l i: n
car-	ley
kh Q@	l i:
car-	li
kh Q@	l i:
car-	li-	ni
kh Q@	l i:	n i:
car-	li-	no
kh Q@	l i:	n @U
car-	li-	ta
kh Q@	l i:	t V
car-	lile
kh Q@	l aI l
car-	lin
kh Q@	l I n
car-	ling
kh Q@	l I N
car-	ling's
kh Q@	l I N z
car-	lin's
kh Q@	l I n z
car-	lisle
kh Q@	l aI l
car-	lo
kh Q@	l @U
car-	loa-	ding
kh Q@	l @U	d I N
car-	loa-	dings
kh Q@	l @U	d I N z
car-	load
kh Q@	l @U d
car-	loads
kh Q@	l @U d z
car-	lock
kh Q@	l Q k
car-	los
kh Q@	l @U s
car-	lot-	ta
kh Q@	l O:	t V
car-	low
kh Q@	l @U
car-	ly
kh Q@	l i:
car-	lyle
kh Q@	l aI l
car-	lyle's
kh Q@	l aI l z
car-	ma
kh Q@	m V
car-	ma-	ker
kh Q@	m eI	k @r
car-	ma-	kers
kh Q@	m eI	k @r z
car-	man
kh Q@	m V n
car-	me-	la
kh Q@	m e	l V
car-	me-	li-	ta
kh Q@	m V	l i:	t V
car-	me-	lite
kh Q@	m V	l aI t
car-	me-	lo
kh Q@	m e	l @U
car-	mel
kh Q@	m e l
car-	men
kh Q@	m V n
car-	mi-	chael
kh Q@	m aI	k V l
car-	mi-	ta
kh Q@	m i:	t V
car-	mine
kh Q@	m aI n
car-	mon
kh Q@	m V n
car-	na-	han
kh Q@	n V	h { n
car-	na-	tion
kh Q@	n eI	S V n
car-	na-	tions
kh Q@	n eI	S V n z
car-	nage
kh Q@	n I dZ
car-	nal
kh Q@	n V l
car-	nau-	ba
kh Q@	n O:	b V
car-	ne-	gie
kh Q@	n V	g i:
car-	ne-	gie's
kh Q@	n V	g i: z
car-	ney
kh Q@	n i:
car-	ni-	val
kh Q@	n I	v V l
car-	ni-	vals
kh Q@	n I	v V l z
car-	ni-	val's
kh Q@	n I	v V l z
car-	ni-	vo-	rous
kh Q@	n I	v @r	V s
car-	ni-	vore
kh Q@	n I	v O@
car-	ni-	vores
kh Q@	n I	v O@ z
car-	pal
kh Q@	p V l
car-	pet
kh Q@	p V t
car-	pool
kh Q@	p u: l
car-	port
kh Q@	p O@ t
car-	ports
kh Q@	p O@ t s
car-	ra
kh Q@	V
car-	ra-	ra
kh Q@	Q@	V
car-	ra-	way
kh {	r V	w eI
car-	ran-	za
kh Q@	Q n	z V
car-	re-	ras
kh Q@	e@	Q z
car-	re-	re
kh Q@	e@	eI
car-	rel
kh {	r V l
car-	rell
kh Q@	eI l
car-	ret-	ta
kh Q@	e	t V
car-	ri-	er
kh {	r i:	@r
car-	ri-	ers
kh {	r i:	@r z
car-	ri-	er's
kh {	r i:	@r z
car-	ri-	on
kh e@	i:	V n
car-	ria-	ges
kh {	r I	dZ V z
car-	riage
kh {	r I dZ
car-	rick
kh e@	I k
car-	rie
kh e@	i:
car-	rie-	re
kh Q@	I@	i:
car-	ried
kh {	r i: d
car-	ries
kh {	r i: z
car-	ril-	lo
kh @r	I	l @U
car-	ring-	ton
kh e@	I N	t V n
car-	ring-	ton's
kh e@	I N	t V n z
car-	ro-	thers
kh {	r V	D @r z
car-	rol
kh {	r V l
car-	roll
kh {	r V l
car-	roll-	ton
kh e@	V l	t V n
car-	roll's
kh {	r V l z
car-	ron
kh {	r V n
car-	rot
kh {	r V t
car-	rots
kh {	r V t s
car-	rou-	sel
kh e@	V	s e l
car-	row
kh {	r @U
car-	roz-	za
kh Q@	@U	z V
car-	ru-	thers
kh @r	V	D @r z
car-	ry
kh {	r i:
car-	ry-	for-	ward
kh e@	i:	f O@	w @r d
car-	ry-	for-	wards
kh e@	i:	f O@	w @r d z
car-	ry-	ing
kh {	r i:	I N
car-	ryo-	ver
kh e@	j @U	v @r
car-	sey
kh Q@	s i:
car-	sick
kh Q@	s I k
car-	son
kh Q@	s V n
car-	son's
kh Q@	s V n z
car-	ta
kh Q@	t V
car-	ta-	ge-	na
kh Q@	t V	dZ i:	n V
car-	te-	ret
kh Q@	t @r	e t
car-	te-	ret's
kh Q@	t @r	e t s
car-	ted
kh Q@	t V d
car-	tel
kh Q@	t e l
car-	tels
kh Q@	t e l z
car-	tel's
kh Q@	t e l z
car-	ter
kh Q@	t @r
car-	ters
kh Q@	t @r z
car-	ter's
kh Q@	t @r z
car-	ters-	ville
kh Q@	t @r z	v I l
car-	tha-	gi-	ni-	an
kh Q@	T V	dZ I	n i:	V n
car-	thage
kh Q@	T V dZ
car-	ti-	er
kh Q@	t i:	@r
car-	ti-	lage
kh Q@	t I	l V dZ
car-	ting
kh Q@	t I N
car-	ton
kh Q@	t V n
car-	tons
kh Q@	t V n z
car-	too-	ning
kh Q@	t u:	n I N
car-	too-	nist
kh Q@	t u:	n I s t
car-	too-	nists
kh Q@	t u:	n I s t s
car-	toon
kh Q@	t u: n
car-	toons
kh Q@	t u: n z
car-	ty
kh Q@	t i:
car-	vel
kh Q@	v e l
car-	ver
kh Q@	v @r
car-	vers
kh Q@	v @r z
car-	ver's
kh Q@	v @r z
car-	vey
kh Q@	v i:
car-	ville
kh Q@	v I l
car-	ville's
kh Q@	v I l z
car-	ving
kh Q@	v I N
car-	vings
kh Q@	v I N z
card
kh Q@ d
card-	board
kh Q@ d	b O@ d
card-	boards
kh Q@ d	b O@ d z
card-	hol-	der
kh Q@ d	h @U l	d @r
card-	hol-	ders
kh Q@ d	h @U l	d @r z
card-	well
kh Q@ d	w e l
cards
kh Q@ d z
card's
kh Q@ d z
care
kh e@
care-	free
kh e@ f	r i:
care-	ful
kh e@	f V l
care-	ful-	ly
kh e@	f V	l i:
care-	gi-	ver
kh e@	g I	v @r
care-	gi-	vers
kh e@	g I	v @r z
care-	gi-	ving
kh e@	g I	v I N
care-	less
kh e@	l V s
care-	less-	ly
kh e@	l V s	l i:
care-	less-	ness
kh e@	l V s	n V s
care-	ta-	ker
kh e@	t eI	k @r
care-	ta-	kers
kh e@	t eI	k @r z
cared
kh e@ d
cares
kh e@ z
care's
kh e@ z
carl
kh Q@ l
carl-	son
kh Q@ l	s V n
carl-	son's
kh Q@ l	s V n z
carl-	ton
kh Q@ l	t V n
carl-	ton's
kh Q@ l	t V n z
carle-	ton
kh Q@ l	t V n
carles
kh Q@ l z
carls
kh Q@ l z
carl's
kh Q@ l z
carls-	bad
kh Q@ l	s b { d
carls-	tadt
kh Q@ l	s t { t
carls-	trom
kh Q@ l	s t r V m
carn
kh Q@ n
carne
kh Q@ n
carnes
kh Q@ n z
carns
kh Q@ n z
carp
kh Q@ p
carr
kh Q@
carr's
kh Q@ z
carry-	o-	ver
kh e@	j @U	v @r
cars
kh Q@ z
car's
kh Q@ z
carse
kh Q@ s
cart
kh Q@ t
cart-	land
kh Q@ t	l V n d
cart-	rid-	ges
kh Q@ t	r I	dZ V z
cart-	ridge
kh Q@ t	r I dZ
cart-	wheel
kh Q@ t	w i: l
cart-	wheels
kh Q@ t	w i: l z
cart-	wright
kh Q@ t	r aI t
carte
kh Q@ t
carts
kh Q@ t s
carve
kh Q@ v
carved
kh Q@ v d
carves
kh Q@ v z
cas
kh { s
cas-	bah
kh { s	b V
cas-	ca-	ded
kh { s	k eI	d V d
cas-	ca-	ding
kh { s	k eI	d I N
cas-	cade
kh { s	k eI d
cas-	cades
kh { s	k eI d z
cas-	cade's
kh { s	k eI d z
cas-	co
kh { s	k @U
cas-	ket
kh { s	k V t
cas-	kets
kh { s	k V t s
cas-	par
kh { s	p @r
cas-	per
kh { s	p @r
cas-	pi-	an
kh { s	p i:	V n
cas-	sa-	da
kh Q	s Q	d V
cas-	sa-	dy
kh {	s V	d i:
cas-	sa-	ta
kh Q	s Q	t V
cas-	sand-	ra
kh V	s { n	d r V
cas-	sand-	ras
kh V	s { n	d r V s
cas-	satt
kh {	s V t
cas-	se-	role
kh {	s @r	@U l
cas-	sel
kh {	s V l
cas-	sel-	ber-	ry
kh {	s V l	b e@	i:
cas-	sel-	la
kh Q	s e	l V
cas-	sell
kh {	s V l
cas-	sette
kh V	s e t
cas-	settes
kh V	s e t s
cas-	si-	a
kh {	S i:	V
cas-	si-	dy
kh {	s I	d i:
cas-	si-	dy's
kh {	s I	d i: z
cas-	si-	ni
kh V	s i:	n i:
cas-	si-	no
kh V	s i:	n @U
cas-	sie
kh {	s i:
cas-	sis
kh {	s I s
cas-	so-	ne
kh Q	s @U	n i:
cas-	so-	ni
kh V	s @U	n i:
cas-	so-	wa-	ry
kh {	s V	w e@	i:
cas-	sock
kh {	s V k
cas-	son
kh {	s V n
cas-	ta
kh { s	t V
cas-	ta-	ne-	da
kh Q s	t Q	n e	d V
cas-	ta-	no
kh Q s	t Q	n @U
cas-	ta-	way
kh { s	t V	w eI
cas-	ta-	ways
kh { s	t V	w eI z
cas-	te-	lo
kh Q s	t e	l @U
cas-	teel
kh eI s	t i: l
cas-	tel
kh eI s	t V l
cas-	tel-	la-	no
kh Q s	t e	l Q	n @U
cas-	tel-	la-	nos
kh Q s	t eI	l Q	n @U z
cas-	tel-	li
kh Q s	t e	l i:
cas-	tell
kh eI s	t V l
cas-	ten
kh { s	t V n
cas-	ter
kh { s	t @r
cas-	ters
kh { s	t @r z
cas-	ti-	ga-	ted
kh { s	t I	g eI	t I d
cas-	ti-	ga-	ting
kh { s	t I	g eI	t I N
cas-	ti-	gate
kh { s	t I	g eI t
cas-	ti-	ne
kh Q s	t i:	n i:
cas-	tig-	li-	o-	ne
kh Q s	t i: g	l i:	@U	n i:
cas-	til-	la
kh Q s	t I	l V
cas-	til-	le-	ja
kh Q s	t i:	l eI	j V
cas-	til-	lo
kh { s	t i:	@U
cas-	ting
kh { s	t I N
cas-	tings
kh { s	t I N z
cas-	tle
kh {	s V l
cas-	tle-	ber-	ry
kh {	s V l	b e@	i:
)"
R"(cas-	tles
kh {	s V l z
cas-	tle's
kh {	s V l z
cas-	toff
kh { s	t O: f
cas-	toffs
kh { s	t O: f s
cas-	tor
kh { s	t @r
cas-	well
kh { z	w e l
case
kh eI s
case-	load
kh eI s	l @U d
case-	wor-	ker
kh eI s	w @r	k @r
case-	wor-	kers
kh eI s	w @r	k @r z
case-	work
kh eI s	w @r k
cash
kh { S
cash-	flow
kh { S	f l @U
cash-	less
kh { S	l V s
cash-	mere
kh { Z	m I@
cashed
kh { S t
cask
kh { s k
casks
kh { s k s
cass
kh { s
cast
kh { s t
cast-	off
kh { s	t O: f
cast-	ra-	ted
kh { s	t r eI	t V d
cast-	ra-	ting
kh { s	t r eI	t I N
cast-	ra-	tion
kh { s	t r eI	S V n
cast-	ra-	tions
kh { s	t r eI	S V n z
cast-	rate
kh { s	t r eI t
cast-	rates
kh { s	t r eI t s
cast-	ro
kh { s	t r @U
cast-	ro's
kh { s	t r @U z
caste
kh { s t
castes
kh { s t s
casts
kh { s t s
cat
kh { t
cat-	bird
kh { t	b @r d
cat-	call
kh { t	k O: l
cat-	calls
kh { t	k O: l z
cat-	chall
kh {	tS O: l
cat-	cher
kh {	tS @r
cat-	chers
kh {	tS @r z
cat-	cher's
kh {	tS @r z
cat-	ches
kh {	tS V z
cat-	ching
kh {	tS I N
cat-	chings
kh {	tS I N z
cat-	chup
kh {	tS V p
)"