R"(kee-	pers
kh i:	p @r z
kee-	ping
kh i:	p I N
kee-	ton
kh i:	t V n
kee-	ver
kh i:	v @r
keech
kh i: tS
keef
kh i: f
keefe
kh i: f
keel
kh i: l
keel-	son
kh e l	s V n
keele
kh i: l
keels
kh i: l z
keen
kh i: n
keen-	ly
kh i: n	l i:
keene
kh i: n
keep
kh i: p
keep-	sake
kh i: p	s eI k
keep-	sakes
kh i: p	s eI k s
keeps
kh i: p s
kee's
kh i: z
keese
kh i: z
kef-	fer
kh e	f @r
keg
kh e g
keg-	ler
kh e g	l @r
keg-	ley
kh e g	l i:
kegs
kh e g z
kehr
kh e@
kei-	fer
kh i:	f @r
kei-	ko
kh eI	k @U
kei-	re-	tsu
kh I@	e t	s u:
kei-	s-	ling
kh aI	s V	l I N
kei-	ser
kh aI	s @r
kei-	tel
kh aI	t V l
kei-	zer
kh aI	z @r
keil
kh i: l
keil-	lor
kh i:	l @r
keil-	lor's
kh i:	l @r z
keir
kh i: r
keith
kh i: T
keith-	ley
kh i: T	l i:
keith's
kh i: T s
kel-	by
kh e l	b i:
kel-	cey
kh e l	s i:
kel-	da
kh e l	d V
kel-	ton
kh e l	t V n
kel-	ty
kh e l	t i:
kel-	vin
kh e l	v I n
kel-	vin's
kh e l	v I n z
kem-	ble
kh e m	b V l
kem-	me-	rer
kh e	m @r	@r
kem-	per
kh e m	p @r
kem-	ple
kh e m	p V l
kemp
kh e m p
kemp-	ner
kh e m	p n @r
kemp-	ton
kh e m	p t V n
kempe
kh e m p
kemp's
kh e m p s
kemps-	ter
kh e m	p s t @r
ken
kh e n
ken-	dal
kh e n	d V l
ken-	dall
kh e n	d V l
ken-	dall's
kh e n	d V l z
ken-	dell
kh e n	d V l
ken-	ji
kh e n	dZ i:
ken-	ley
kh e n	l i:
ken-	mare
kh e n	m e@
ken-	more
kh e n	m O@
ken-	na
kh e	n V
ken-	nan
kh e	n V n
ken-	nard
kh e	n @r d
ken-	ne-	bunk-	port
kh e	n V	b V N	k p O@ t
ken-	ne-	cott
kh e	n V	k Q t
ken-	ne-	dy
kh e	n V	d i:
ken-	ne-	dy's
kh e	n V	d i: z
ken-	ne-	saw
kh e	n V	s O:
ken-	nel
kh e	n V l
ken-	nel-	ly
kh e	n V	l i:
ken-	nell
kh e	n V l
ken-	nels
kh e	n V l z
ken-	ner
kh e	n @r
ken-	ner's
kh e	n @r z
ken-	neth
kh e	n V T
ken-	nett
kh e	n V t
ken-	ney
kh e	n i:
ken-	ning
kh e	n I N
ken-	ning-	ton
kh e	n I N	t V n
ken-	ny
kh e	n i:
ken-	rick
kh e n	r I k
ken-	sing-	ton
kh e n	z I N	t V n
ken-	te
kh e n	t eI
ken-	ton
kh e n	t V n
ken-	tuc-	ki-	an
kh e n	t V	k i:	V n
ken-	tuc-	ki-	ans
kh e n	t V	k i:	V n z
ken-	tuc-	ky
kh V n	t V	k i:
ken-	tuc-	ky's
kh V n	t V	k i: z
ken-	ward
kh e n	w @r d
ken-	way
kh e n	w eI
ken-	wood
kh e n	w U d
ken-	ya
kh e n	j V
ken-	yan
kh e n	j V n
ken-	yans
kh e n	j V n z
ken-	ya's
kh e n	j V z
ken-	yon
kh e n	j V n
ken-	zie
kh e n	z i:
kend-	ra
kh e n	d r V
kend-	rick
kh e n	d r I k
kend-	ricks
kh e n	d r I k s
kenn
kh e n
ken's
kh e n z
kent
kh e n t
kent's
kh e n t s
kep-	ler
kh e p	l @r
kep-	ner
kh e p	n @r
kep-	pel
kh e	p V l
kept
kh e p t
ker
kh @r
ker-	by
kh @r	b i:
ker-	cher
kh @r	k @r
ker-	chief
kh @r	tS I f
ker-	chiefs
kh @r	tS I f s
ker-	fuf-	fle
kh @r	f V	f V l
ker-	man
kh @r	m V n
ker-	mit
kh @r	m I t
ker-	nan
kh @r	n V n
ker-	nel
kh @r	n V l
ker-	nels
kh @r	n V l z
ker-	ner
kh @r	n @r
ker-	nite
kh @r	n aI t
ker-	ri
kh e@	i:
ker-	rick
kh e@	I k
ker-	ry
kh e@	i:
ker-	ry's
kh e@	i: z
ker-	sey
kh @r	s i:
ker-	shaw
kh @r	S Q
ker-	tesz
kh @r	t I S
ker-	win
kh @r	w I n
kerb
kh @r b
kerbs
kh @r b z
kerl
kh @r l
kern
kh @r n
kernes
kh @r n z
kerns
kh @r n z
kern's
kh @r n z
kerr
kh @r
kerr-	ville
kh @r	v I l
kers-	ten
kh @r s	t V n
kerst
kh @r s t
kes-	sel
kh e	s V l
kes-	sel-	ring
kh e	s V l	r I N
kes-	ter
kh e s	t @r
kes-	ting
kh e s	t I N
kes-	wick
kh e s	w I k
kess-	ler
kh e s	l @r
kess-	ler's
kh e s	l @r z
kest-	ner
kh e s	t n @r
kest-	rels
kh e s	t r V l z
ket-	chi-	kan
kh e	tS I	k { n
ket-	chum
kh e	tS V m
ket-	chup
kh e	tS V p
ket-	t-	ler
kh e	t V	l @r
ket-	te-	ring
kh e	t @r	I N
ket-	ti
kh e	t i:
ket-	tle
kh e	t V l
ket-	tles
kh e	t V l z
ketch
kh e tS
kev-	lar
kh e v	l @r
kew
kh j u:
kew-	au-	nee
kh j u:	O:	n i:
key
kh i:
key-	board
kh i:	b O@ d
key-	boards
kh i:	b O@ d z
key-	hole
kh i:	h @U l
key-	ing
kh i:	I N
key-	less
kh i:	l V s
key-	note
kh i:	n @U t
key-	pad
kh i:	p { d
key-	pads
kh i:	p { d z
key-	pad's
kh i:	p { d z
key-	ser
kh aI	z @r
key-	stone
kh i: s	t @U n
key-	stone's
kh i: s	t @U n z
key-	stroke
kh i: s	t r @U k
key-	strokes
kh i: s	t r @U k s
key-	word
kh i:	w @r d
key-	words
kh i:	w @r d z
keyed
kh i: d
keyes
kh i: z
keyne-	si-	an
kh eI n	z i:	V n
keyne-	si-	ans
kh eI n	z i:	V n z
keynes
kh eI n z
keys
kh i: z
key's
kh i: z
kha-	ba-	rovsk
kh {	b @r	Q f s k
kha-	ki
kh Q	k i:
kha-	kis
kh {	k i: z
kha-	li-	fa
kh V	l i:	f V
kha-	lid
kh Q	l I d
kha-	lid's
kh Q	l I d z
kha-	lil
kh {	l I l
kha-	nate
kh Q	n eI t
khal-	sa
kh Q l	s V
khan
kh Q n
khan-	na
kh {	n V
khan's
kh Q n z
khar-	toum
kh Q@	t u: m
khat
kh Q t
khem
kh e m
khmer
kh m e@
kho-	mei-	ni
kh @U	m eI	n i:
kho-	mei-	ni's
h @U	m eI	n i: z
khou-	ry
kh aU	r i:
khrush-	chev
kh r u: s	tS e v
khrush-	chev's
kh r u: s	tS e v z
khu-	fu
kh u:	f u:
ki
kh i:
ki-	a
kh i:	@r
ki-	es-	ter
s aI	V s	t @r
ki-	ev
kh i:	e v
ki-	ev's
kh i:	e v z
ki-	ga-	li
kh i:	g Q	l i:
ki-	ga-	li's
kh i:	g Q	l i: z
ki-	ker
kh aI	k @r
ki-	ki
kh i:	k i:
ki-	la
kh I	l V
ki-	ley
kh aI	l i:
ki-	li-	an
kh I	l i:	V n
ki-	li-	man-	ja-	ro
kh I	l i:	m V n	dZ Q@	@U
ki-	lo
kh I	l @U
ki-	lo-	bit
kh I	l V	b I t
ki-	lo-	byte
kh I	l @U	b aI t
ki-	lo-	bytes
kh I	l @U	b aI t s
ki-	lo-	gram
kh I	l V g	r { m
ki-	lo-	grams
kh I	l V g	r { m z
ki-	lo-	me-	ter
kh V	l Q	m V	t @r
ki-	lo-	me-	ters
kh V	l Q	m V	t @r z
ki-	mo-	no
kh V	m @U	n V
ki-	mo-	nos
kh V	m @U	n V z
ki-	mu-	ra
kh i:	m U@	V
ki-	ne-	si-	o-	lo-	gy
kh I	n V	s i:	Q	l V	dZ i:
ki-	ne-	tic
kh V	n e	t I k
ki-	ne-	tics
kh V	n e	t I k s
ki-	nes-	the-	tic
kh I	n V s	T e	t I k
ki-	osk
kh i:	O: s k
ki-	osks
kh i:	O: s k s
ki-	ri
kh I@	i:
ki-	ri-	ba-	ti
kh I@	I	b Q	t i:
ki-	rin
kh I@	I n
ki-	rov
kh I@	Q v
ki-	san
kh I	z V n
ki-	shi
kh i:	S i:
ki-	sor
kh aI	z @r
ki-	ting
kh aI	t I N
ki-	wa-	nis
kh V	w Q	n V s
ki-	wi
kh i:	w i:
ki-	wis
kh i:	w i: z
ki-	wi's
kh i:	w i: z
ki-	yo-	shi
kh i:	@U	S i:
kib-	ble
kh I	b V l
kib-	but-	zim
kh I	b U t	s I m
kib-	butz
kh I	b U t s
kib-	butz-	nik
kh I	b U t	s n I k
kib-	butz-	niks
kh I	b U t	s n I k s
kibbe
kh I b
kic-	ker
kh I	k @r
kic-	kers
kh I	k @r z
kic-	king
kh I	k I N
kic-	koff
kh I	k O: f
kick
kh I k
kick-	back
kh I k	b { k
kick-	backs
kh I k	b { k s
kick-	off
kh I	k O: f
kicked
kh I k t
kicks
kh I k s
kid
kh I d
kid-	ded
kh I	d V d
kid-	der
kh I	d @r
kid-	der's
kh I	d @r z
kid-	die
kh I	d i:
kid-	dies
kh I	d i: z
kid-	ding
kh I	d I N
kid-	ding-	ly
kh I	d I N	l i:
kid-	dy
kh I	d i:
kid-	na-	ping
kh I d	n {	p I N
kid-	nap
kh I d	n { p
kid-	nap-	per
kh I d	n {	p @r
kid-	nap-	pers
kh I d	n {	p @r z
kid-	nap-	ping
kh I d	n {	p I N
kid-	nap-	pings
kh I d	n {	p I N z
kid-	naped
kh I d	n { p t
kid-	napped
kh I d	n { p t
kid-	naps
kh I d	n { p s
kid-	ney
kh I d	n i:
kid-	neys
kh I d	n i: z
kidd
kh I d
kidde
kh I d
kids
kh I d z
kid's
kh I d z
kids'
kh I d z
kie-	fer
kh i:	f @r
kie-	ler
kh i:	l @r
kie-	nan
kh i:	n V n
kie-	ran
kh i:	r V n
kie-	van
kh i:	v V n
kie-	wit
kh i:	w I t
kief
kh i: f
kief-	fer
kh i:	f @r
kiehl
kh i: l
kiehn
kh i: n
kiel
kh i: l
kiel-	ba-	sa
kh i: l	b Q	s V
kiel-	ty
kh i: l	t i:
kier
kh I@
kier-	nan
kh I@	n V n
kies
kh aI s
kight
kh aI t
kik-	wit
kh I k	w V t
kil-	bourne
kh I l	b @r n
kil-	bride
kh I l	b r aI d
kil-	by
kh I l	b i:
kil-	dee
kh I l	d i:
kil-	gore
kh I l	g O@
kil-	lam
kh I	l V m
kil-	le-	brew
kh I	l V b	r u:
kil-	leen
kh I	l i: n
kil-	len
kh I	l V n
kil-	ler
kh I	l @r
kil-	lers
kh I	l @r z
kil-	ler's
kh I	l @r z
kil-	li-	fish
kh I	l I	f I S
kil-	lian
kh I l	j V n
kil-	ling
kh I	l I N
kil-	ling-	ton
kh I	l I N	t V n
kil-	lings
kh I	l I N z
kil-	lion
kh I l	j V n
kil-	lo-	ran
kh I	l @r	V n
kil-	mar-	nock
kh I l	m Q@	n Q k
kil-	mer
kh I l	m @r
kile
kh aI l
kill
kh I l
kill-	joy
kh I l	dZ OI
killed
kh I l d
kills
kh I l z
kiln
kh I l n
kilns
kh I l n z
kim-	po
kh I m	p @U
kim's
kh I m z
kin
kh I n
kin-	caid
kh I n	k eI d
kin-	caid's
kh I n	k eI d z
kin-	che-	loe
kh I n	tS V	l @U
kin-	chen
kh I N	k V n
kin-	d-	ler
kh I n	d V	l @r
kin-	da
kh I n	d V
kin-	der
kh aI n	d @r
kin-	der-	gar-	ten
kh I n	d @r	g Q@	t V n
kin-	der-	gar-	tens
kh I n	d @r	g Q@	t V n z
kin-	der-	gart-	ner
kh I n	d @r	g Q@ t	n @r
kin-	dest
kh aI n	d V s t
kin-	dig
kh I n	d I g
kin-	dle
kh I n	d V l
kin-	dled
kh I n	d V l d
kin-	dy
kh aI n	d i:
kin-	ker
kh I N	k @r
kin-	kle
kh I N	k V l
kin-	ko
kh I N	k @U
kin-	ko's
kh I N	k @U z
kin-	ky
kh I N	k i:
kin-	loch
kh I n	l V k
kin-	nard
kh I	n @r d
kin-	near
kh I	n I@
kin-	ney
kh I	n i:
kin-	nie
kh I	n i:
kin-	nock
kh I	n V k
kin-	nock's
kh I	n V k s
kin-	ny
kh I	n i:
kin-	s-	ler
kh I n	s V	l @r
kin-	sey
kh I n	z i:
kin-	sha-	sa
kh I n	S Q	s V
kin-	ship
kh I n	S I p
kin-	zer
kh I n	z @r
kinch
kh I n tS
kind
kh aI n d
kind-	ling
kh I n	d l I N
kind-	ly
kh aI n	d l i:
kind-	ness
kh aI n	d n V s
kind-	red
kh I n	d r V d
kinds
kh aI n d z
kines
kh aI n z
king
kh I N
king-	bird
kh I N	b @r d
king-	birds
kh I N	b @r d z
king-	dom
kh I N	d V m
king-	doms
kh I N	d V m z
king-	dom's
kh I N	d V m z
king-	don
kh I N	d V n
king-	fi-	sher
kh I N	f I	S @r
king-	fi-	shers
kh I N	f I	S @r z
king-	horn
kh I N	h @r n
king-	ly
kh I N	l i:
king-	ma-	ker
kh I N	m eI	k @r
king-	man
kh I N	m V n
king-	pin
kh I N	p I n
king-	pins
kh I N	p I n z
king-	ship
kh I N	S I p
king-	sport
kh I N	s p O@ t
kings
kh I N z
king's
kh I N z
kings'
kh I N z
kings-	bu-	ry
kh I N	z b e@	i:
kings-	ford
kh I N	s f @r d
kings-	land
kh I N	z l { n d
kings-	ley
kh I N	z l i:
kings-	ley's
kh I N	z l i: z
kings-	ton
kh I N	s t V n
kings-	ville
kh I N	z v I l
kinks
kh I N k s
kin's
kh I n z
kins-	ley
kh I n	z l i:
kins-	ley's
kh I n	z l i: z
kins-	man
kh I n	z m { n
kip
kh I p
kip-	ling
kh I p	l I N
kip-	nis
kh I p	n I s
kip-	per
kh I	p @r
kip-	pers
kh I	p @r z
kip-	pur
kh I	p @r
kipp
kh I p
kir-	by
kh @r	b i:
kir-	by's
kh @r	b i: z
kir-	cher
kh @r	k @r
kir-	giz
kh I@	g I z
kir-	ker
kh @r	k @r
kir-	kuk
kh I@	k U k
kir-	sten
kh @r s	t V n
kir-	stin
kh @r s	t I n
kir-	ven
kh @r	v V n
kir-	win
kh @r	w I n
kirc-	hoff
kh @r k	h O: f
kirch
kh @r k
kirch-	hoff
kh @r k	h O: f
kirch-	ner
kh @r k	n @r
kirk
kh @r k
kirk-	by
kh @r k	b i:
kirk-	land
kh @r k	l V n d
kirk-	land's
kh @r k	l V n d z
kirk-	lin
kh @r k	l I n
kirk-	man
kh @r k	m V n
kirk-	pat-	rick
kh @r k	p { t	r I k
kirk-	sey
kh @r k	s i:
kirk-	wood
kh @r k	w U d
kirks
kh @r k s
kirk's
kh @r k s
kirn
kh @r n
kirsch
kh @r S
kirsch-	ner
kh @r S	n @r
kirsh-	baum
kh @r S	b aU m
kirst
kh @r s t
kirt
kh @r t
kirt-	land
kh @r t	l V n d
kirt-	ley
kh @r t	l i:
kis-	ma-	yu
kh I s	m Q	j u:
kis-	met
kh I z	m e t
kis-	mets
kh I z	m e t s
kis-	see
kh I	s i:
kis-	sel
kh I	s V l
kis-	ser
kh I	s @r
kis-	ses
kh I	s V z
kis-	sim-	mee
kh I	s I	m i:
kis-	sin-	ger
kh I	s I n	dZ @r
kis-	sin-	ger's
kh I	s I n	dZ @r z
kis-	sing
kh I	s I N
kish
kh I S
kiss
kh I s
kiss-	ner
kh I s	n @r
kissed
kh I s t
kist
kh I s t
kist-	ler
kh I s	t l @r
kist-	ner
kh I s	t n @r
kit
kh I t
kit-	cat
kh I t	k { t
kit-	che-	ner
kh I	tS V	n @r
kit-	che-	nette
kh I	tS V	n e t
kit-	chen
kh I	tS V n
kit-	chen-	ware
kh I	tS V n	w e@
kit-	chens
kh I	tS V n z
kit-	chen's
kh I	tS V n z
kit-	chin
kh I	tS I n
kit-	ching
kh I	tS I N
kit-	t-	ler
kh I	t V	l @r
kit-	tel
kh I	t V l
kit-	ten
kh I	t V n
kit-	tens
kh I	t V n z
kit-	ti-	wake
kh I	t I	w eI k
kit-	tle
kh I	t V l
kit-	tles
kh I	t V l z
kit-	ty
kh I	t i:
kite
kh aI t
kites
kh aI t s
kits
kh I t s
kitsch
kh I tS
kitt
kh I t
kitt-	redge
kh I t	r I dZ
kitt-	rell
kh I t	r V l
kitts
kh I t s
kitz-	mil-	ler
kh I t	s m I	l @r
klan
kh l { n
klang
kh l { N
klans
kh l { n z
klan's
kh l { n z
klans-	man
kh l { n	z m V n
klans-	men
kh l { n	z m e n
klapp
kh l { p
klatt
kh l { t
klau-	ber
kh l aU	b @r
klaus
kh l aU s
klay-	man
kh l eI	m V n
kle-	ber
kh l i:	b @r
kle-	mens
kh l e	m V n s
kle-	ment
kh l e	m V n t
kle-	pac
kh l e	p V k
klec-	ka
kh l e	k V
klee
kh l i:
klee-	man
kh l i:	m V n
klee-	nex
kh l i:	n V k s
klee's
kh l i: z
klei-	ber
kh l aI	b @r
klei-	man
kh l aI	m V n
klein
kh l aI n
klein's
kh l aI n z
kleist
kh l aI s t
klemm
kh l e m
klemme
kh l e m
klenk
kh l e N k
kleve
kh l i: v
klez-	mer
kh l e z	m @r
kli-	ment
kh l aI	m V n t
klick
kh l I k
klieg
kh l i: g
klin-	gel
kh l I N	g V l
klin-	ger
kh l I	N @r
klin-	ger's
kh l I	N @r z
klin-	gon
kh l I N	d V n
klin-	ker
kh l I N	k @r
kline
kh l aI n
kling
kh l I N
kloc
kh l Q k
klom
kh l O: m
klon-	dike
kh l Q n	d aI k
klos
kh l Q s
klos-	ter
kh l O: s	t @r
kloss-	ner
kh l Q s	n @r
klotz
kh l Q t s
klu-	ge's
kh l u:	dZ V z
kluck
kh l V k
klug
kh l V g
kluge
kh l u: dZ
klump
kh l V m p
klunk
kh l V N k
klute
kh l u: t
klutz
kh l V t s
klux
kh l V k s
knab
n { b
knack
n { k
knacks
n { k s
knap-	per
n {	p @r
knap-	sack
n { p	s { k
knape
n eI p
knapp
n { p
knapp's
n { p s
knau-	er
n aU	@r
knave
n eI v
knaves
n eI v z
knea-	ding
n i:	d I N
knead
n i: d
knee
n i:
knee-	cap
n i:	k { p
knee-	caps
n i:	k { p s
knee-	land
n i:	l V n d
knee-	ling
n i:	l I N
kneed
n i: d
kneel
n i: l
knees
n i: z
knel-	ler
n e	l @r
knell
n e l
knelt
n e l t
knep-	per
n e	p @r
knes-	set
n e	s V t
knew
n u:
kni-	fing
n aI	f I N
kni-	fings
n aI	f I N z
knic-	ker
n I	k @r
knic-	ker-	boc-	ker
n I	k @r	b Q	k @r
knic-	ker-	boc-	kered
n I	k @r	b Q	k @r d
knic-	ker-	boc-	kers
n I	k @r	b Q	k @r z
knic-	kers
n I	k @r z
knick
n I k
knick-	knack
n I k	n { k
knick-	knacks
n I k	n { k s
knicks
n I k s
knie-	rim
n I@	I m
knies
n aI z
knife
n aI f
knife-	like
n aI f	l aI k
knife-	point
n aI f	p OI n t
knifed
n aI f t
knigh-	ted
n aI	t V d
knigh-	ton
n aI	t V n
knight
n aI t
knight-	hood
n aI t	h U d
knight-	ly
n aI t	l i:
knights
n aI t s
knight's
n aI t s
knip-	pa
n I	p V
knipe
n aI p
knit
n I t
knit-	ted
n I	t V d
knit-	ter
n I	t @r
knit-	ting
n I	t I N
knit-	tle
n I	t V l
knit-	wear
n I t	w e@
knits
n I t s
knives
n aI v z
kno-	bel
n @U	b V l
kno-	wer
n @U	@r
kno-	wing
n @U	I N
kno-	wing-	ly
n @U	I N	l i:
kno-	x's
n Q k	s V z
knob
n Q b
knob-	by
n Q	b i:
knob-	loch
n Q b	l V k
knobs
n Q b z
knoc-	king
n Q	k I N
knock
n Q k
knock-	down
n Q k	d aU n
knock-	off
n Q	k O: f
knock-	offs
n Q	k O: f s
knock-	out
n Q	k aU t
knocked
n Q k t
knocks
n Q k s
knoke
n @U k
knoll
n @U l
knoll's
n @U l z
knoop
n u: p
knop
n Q p
knopf
n Q p f
knorr
n O@
knot
n Q t
knot-	ted
n Q	t V d
knot-	ty
n Q	t i:
knots
n Q t s
knott
n Q t
knott's
n Q t s
know
n @U
know-	led-	gea-	ble
n Q	l V	dZ V	b V l
know-	led-	geab-	ly
n Q	l I	dZ V b	l i:
know-	ledge
n Q	l V dZ
knowl-	ton
n @U l	t V n
knowles
n @U l z
known
n @U n
knowns
n @U n z
knows
n @U z
knox
n Q k s
knox-	ville
n Q k	s v I l
knuc-	kle
n V	k V l
knuc-	kled
n V	k V l d
knuc-	kles
n V	k V l z
ko
kh @U
ko-	di-	ak
kh @U	d i:	{ k
ko-	hen
kh @U	V n
ko-	jak
kh @U	dZ { k
ko-	ji
kh @U	dZ i:
ko-	ji-	ma
kh V	j aI	m V
ko-	kan
kh @U	k V n
ko-	ker
kh @U	k @r
ko-	ko
kh @U	k @U
ko-	ko-	mo
kh @U	k V	m @U
ko-	ko's
kh @U	k @U z
ko-	kosch-	ka
kh V	k O: S	k V
ko-	lar
kh @U	l @r
ko-	lin-	ski
kh V	l I n	s k i:
ko-	lo-	ski
kh V	l aU s	k i:
ko-	ma-	ra
kh @U	m Q@	V
ko-	ma-	rek
kh @U	m Q@	e k
ko-	mi
kh @U	m i:
ko-	mo-	do
kh V	m @U	d @U
ko-	mu-	ra
kh @U	m U@	V
ko-	nig
kh Q	n I g
ko-	no
kh @U	n @U
ko-	nop-	ka
kh V	n @U p	k V
ko-	pec
kh @U	p I k
ko-	pek
kh @U	p V k
ko-	peks
kh @U	p V k s
ko-	ra
kh O@	V
ko-	ra-	nic
kh O@	{	n I k
ko-	ral
kh O@	V l
ko-	ran
kh O@	Q n
ko-	re-	a
kh O@	i:	V
ko-	re-	an
kh O@	i:	V n
ko-	re-	ans
kh O@	i:	V n z
ko-	re-	a's
kh O@	i:	V z
ko-	ren
kh O@	V n
ko-	rey
kh O@	i:
ko-	ro-	na
kh @r	@U	n V
ko-	ru-	na
kh O@	u:	n V
ko-	ry
kh O@	i:
ko-	sak
kh @U	s V k
ko-	sel
kh @U	s V l
ko-	ser
kh @U	z @r
ko-	sher
kh @U	S @r
ko-	sin
kh @U	s I n
ko-	so-	vo
kh @U	s @U	v @U
ko-	sy-	gin
kh @U	s I	g I n
ko-	to
kh @U	t @U
ko-	vacs
kh @U	v { k s
ko-	val
kh @U	v V l
ko-	var
kh @U	v @r
ko-	wa-	lew-	ski
kh aU	V	l e f	s k i:
ko-	wal
kh aU	V l
ko-	wal-	ski
kh V	w Q l	s k i:
ko-	ziel
kh Q	z i: l
ko-	zo
kh @U	z @U
koe-	nig
kh @r	n I g
koe-	nigs-	berg
kh @U	n I g	z b @r g
koe-	st-	ler
kh @U	s V	l @r
koeh-	ler
kh @U	l @r
koep-	pel
kh @U	p V l
koer-	ner
kh O@	n @r
kof-	f-	ler
kh Q	f V	l @r
koff
kh O: f
koff-	man
kh O: f	m V n
koh
kh @U
koh-	ler
kh @U	l @r
kohl
kh @U l
kohls
kh @U l z
kohl's
kh @U l z
kohn
kh Q n
kol
kh @U l
kol-	ler
kh Q	l @r
kolb
kh @U l b
kolbe
kh @U l b
kolk
kh @U k
kom-	so-	mol
kh Q m	s @U	m V l
kom-	so-	mol's
kh Q m	s @U	m V l z
kon
kh Q n
kon-	do
kh Q n	d @U
kon-	rad
kh Q n	r V d
kong
kh O: N
kong's
kh O: N z
kons-	tan-	tin
kh Q n	s t V n	t i: n
koo
kh u:
koo-	ky
kh u:	k i:
)"
R"(koo-	ning
kh u:	n I N
koo-	te-	nay
kh u:	t V	n eI
kook
kh u: k
kooks
kh u: k s
koontz
kh u: n t s
kop-	pel
kh Q	p V l
kop-	pel's
kh Q	p V l z
kop-	pen
kh Q	p V n
kop-	pers
kh Q	p @r z
kop-	ple
kh Q	p V l
kopp
kh Q p
kops
kh Q p s
kor-	bel
kh O@	b V l
kor-	da
kh O@	d V
kor-	man
kh O@	m V n
kor-	ry
kh O@	i:
kor-	ry's
kh O@	i: z
kor-	ten
kh O@	t V n
korff
kh O@ f
korn-	berg
kh O@ n	b @r g
korns
kh O: n z
kort
kh O@ t
kos
kh Q s
kos-	suth
kh Q	s V T
koss
kh O: s
kotz
kh Q t s
kou-	rou
kh u:	r u:
kow-	tow
kh aU	t aU
koz-	lo-	ski
kh V z	l aU s	k i:
kra-	kow
kh r Q	k aU
kra-	mer
kh r eI	m @r
kra-	mer's
kh r eI	m @r z
krae-	mer
kh r e	m @r
krafft
kh r { f t
kraft
kh r { f t
kraft's
kh r { f t s
kragh
kh r { g
kral
kh r { l
krall
kh r O: l
kram
kh r { m
kram-	lich
kh r { m	l I k
krans
kh r { n z
krantz
kh r { n t s
kranz
kh r { n z
kras
kh r { s
kras-	ka
kh r Q s	k V
kras-	ner
kh r { s	n @r
kras-	no-	yarsk
kh r { s	n OI	Q@ s k
kras-	noff
kh r { s	n O: f
kras-	ny
kh r { z	n i:
kraus
kh r aU s
krause
kh r O: s
krauss
kh r aU s
kraut
kh r aU t
kraw-	czyk
kh r Q v	tS I k
kre-	mer
kh r i:	m @r
kre-	nek
kh r e	n I k
krea-	ger
kh r i:	g @r
krea-	mer
kh r i:	m @r
kreb-	s's
kh r e b	z V z
krebs
kh r e b z
kreg
kh r e g
krei-	ner
kh r aI	n @r
krein
kh r eI n
kreis
kh r i: z
kreis-	ler
kh r aI s	l @r
kreit-	man
kh r aI t	m V n
krell
kh r e l
krem-	li-	no-	lo-	gist
kh r e m	l I	n Q	l V	dZ I s t
krem-	li-	no-	lo-	gists
kh r e m	l I	n Q	l V	dZ I s t s
krem-	lin
kh r e m	l I n
krem-	lin's
kh r e m	l I n z
krenn
kh r e n
kres-	ge
kh r e s	g i:
kress
kh r e s
kretch-	mer
kh r e tS	m @r
kreu-	zer
kh r u:	z @r
kri-	ko-	ri-	an
kh r I	k O@	i:	V n
kri-	scher
kh r I	S @r
krie-	ger
kh r i:	g @r
krie-	ger's
kh r i:	g @r z
krieg
kh r i: g
krill
kh r I l
krim
kh r I m
kris
kh r I s
kris-	pies
kh r I s	p i: z
kris-	ta
kh r I s	t V
kris-	ten
kh r I	s V n
kris-	ti
kh r I s	t i:
kris-	tie
kh r I s	t i:
kris-	tin
kh r I s	t I n
kris-	tine
kh r I s	t i: n
kris-	ti's
kh r I s	t i: z
kris-	tof
kh r I s	t V f
kris-	ty
kh r I s	t i:
krish-	na
kh r I S	n V
kriss
kh r I s
kro-	ger
kh r @U	g @r
kro-	ger's
kh r @U	g @r z
kro-	na
kh r @U	n V
kro-	ne
kh r @U	n V
kro-	nen
kh r @U	n V n
kro-	ner
kh r @U	n @r
kro-	nick
kh r Q	n I k
kro-	nor
kh r @U	n @r
kro-	nos
kh r @U	n @U s
kroc
kh r Q k
krock
kh r Q k
kroc's
kh r Q k s
kroe-	ber
kh r @U	b @r
kroe-	ber's
kh r @U	b @r z
krogh
kh r @U
kroll
kh r O: l
krome
kh r @U m
kroon
kh r u: n
kru-	ger
kh r u:	g @r
kru-	ger-	rand
kh r u:	g e@	{ n d
krue-	ger
kh r u:	g @r
krug
kh r V g
krum
kh r V m
krupp
kh r V p
krupp's
kh r V p s
kruse
kh r u: z
krutz
kh r V t s
kryp-	ton
kh r I p	t Q n
k's
kh eI z
ku
kh u:
ku-	ba
kh j u:	b V
ku-	ban
kh j u:	b V n
ku-	bi-	ak
kh u:	b i:	{ k
ku-	bis
kh u:	b I s
ku-	dos
kh u:	d @U s
ku-	dzu
kh V d	z u:
ku-	gel
kh u:	g V l
ku-	la
kh u:	l V
ku-	ma-	ga-	i
kh u:	m Q	g Q	i:
ku-	mar
kh u:	m Q@
ku-	na
kh j u:	n V
ku-	nin
kh j u:	n I n
ku-	o
kh u:	@U
ku-	ril
kh @r	I l
ku-	ro-	sa-	wa
kh U@	@U	s Q	w V
ku-	sa
kh u:	z V
ku-	wai-	ti
kh u:	w eI	t i:
ku-	wai-	tis
kh u:	w eI	t i: z
ku-	wait
kh u:	w eI t
ku-	wait's
kh u:	w eI t s
kua-	la
kh w Q	l V
kuan
kh w Q n
kub-	rick
kh j u: b	r I k
kub-	rick's
kh j u: b	r I k s
kuch
kh V tS
kueh-	nel
kh U	n V l
kuehn
kh u: n
kuhl-	man
kh u: l	m V n
kuhn
kh u: n
kul-	kar-	ni
kh V l	k Q@	n i:
kul-	la
kh V	l V
kum-	ler
kh V m	l @r
kum-	mer
kh V	m @r
kum-	quat
kh V m	k w Q t
kun
kh V n
kun-	de-	ra
kh V n	d e@	V
kun-	kle
kh V N	k V l
kung
kh V N
kunz
kh V n z
kuo-	min-	tang
kh w @U	m I n	t { N
kuo-	min-	tang's
kh w @U	m I n	t { N z
kup-	per
kh V	p @r
kur-	dis-	tan
kh @r	d I s	t { n
kur-	dish
kh @r	d I S
kur-	land
kh @r	l V n d
kur-	man
kh @r	m V n
kur-	tis
kh @r	t I s
kur-	za-	wa
kh U@	z Q	w V
kurd
kh @r d
kurds
kh @r d z
kurt
kh @r t
kurth
kh @r T
kurtz
kh @r t s
kurtz-	man
kh @r t	s m V n
kus
kh V s
kus-	ter
kh V s	t @r
kusch
kh V S
kush
kh U S
kush-	ner
kh V S	n @r
kut-	tab
kh u:	t { b
kut-	zer
kh V t	z @r
kutch
kh V tS
kuz-	nets
kh V z	n e t s
kwa-	zu-	lu
kh w Q	z u:	l u:
kwai
kh w aI
kwan
kh w Q n
kwan-	za
kh w Q n	z V
kwan-	zaa
kh w Q n	z V
kwang
kh w Q N
kwang-	ju
kh w Q N	dZ u:
kwok
kh w Q k
kwon
kh w Q n
kyd
kh I d
kyd's
kh I d z
kyes
kh aI z
kyl
kh aI l
kyle
kh aI l
l
e l
l-	a-	p-	d
e	l eI	p i:	d i:
l-	c-	s
e l	s i:	e s
l-	p
e l	p i:
l-	p-	n
e l	p i:	e n
l-	s
e	l e s
l-	s-	d
e	l e s	d i:
l-	t-	d
l0 I	m V	t V d
l.
e l
la
l0 Q
la-	ba-	die
l0 {	b V	d i:
la-	ban
l0 eI	b V n
la-	band
l0 Q	b { n d
la-	bar-	re
l0 Q	b Q@	eI
la-	barge
l0 {	b Q@ g
la-	be-	ling
l0 eI	b V	l I N
la-	bel
l0 eI	b V l
la-	bel-	la
l0 V	b e	l V
la-	beled
l0 eI	b V l d
la-	belle
l0 V	b e l
la-	belled
l0 eI	b V l d
la-	bels
l0 eI	b V l z
la-	bel's
l0 eI	b V l z
la-	bo-	rer
l0 eI	b @r	@r
la-	bo-	rers
l0 eI	b @r	@r z
la-	bo-	ri-	ous
l0 V	b O@	i:	V s
la-	bo-	ri-	ous-	ly
l0 V	b O@	i:	V s	l i:
la-	bo-	ring
l0 eI	b @r	I N
la-	bor
l0 eI	b @r
la-	bored
l0 eI	b @r d
la-	bors
l0 eI	b @r z
la-	bor's
l0 eI	b @r z
la-	bour
l0 eI	b aU r
la-	byr-	in-	thine
l0 {	b @r	I n	T i: n
la-	byr-	inth
l0 {	b @r	I n T
la-	ce-	ra-	tion
l0 {	s @r	eI	S V n
la-	ce-	ra-	tions
l0 {	s @r	eI	S V n z
la-	ce-	rate
l0 {	s @r	eI t
la-	cer
l0 eI	s @r
la-	ces
l0 eI	s V z
la-	cey
l0 eI	s i:
la-	chance
l0 Q	tS V n s
la-	co-	nic
l0 Q	k Q	n I k
la-	com-	be
l0 Q	k @U m	b i:
la-	coste
l0 Q	k O: s t
la-	cy
l0 eI	s i:
la-	den
l0 eI	d V n
la-	der
l0 eI	d @r
la-	di-	no
l0 V	d i:	n @U
la-	dies
l0 eI	d i: z
la-	dies'
l0 eI	d i: z
la-	ding
l0 eI	d I N
la-	dle
l0 eI	d V l
la-	dled
l0 eI	d V l d
la-	dles
l0 eI	d V l z
la-	due
l0 Q d	w e
la-	dy
l0 eI	d i:
la-	dy-	bird
l0 eI	d i:	b @r d
la-	dy-	bug
l0 eI	d i:	b V g
la-	dy-	bugs
l0 eI	d i:	b V g z
la-	dy-	like
l0 eI	d i:	l aI k
la-	dy's
l0 eI	d i: z
la-	farge
l0 Q	f Q@ dZ
la-	fay-	ette
l0 Q	f i:	e t
la-	fite
l0 Q	f aI t
la-	fitte
l0 V	f I t
la-	fol-	lette
l0 {	f V	l e t
la-	fon-	taine
l0 {	f V n	t eI n
la-	forge
l0 V	f O@ g
la-	gan
l0 {	g V n
la-	gas-	se
l0 Q	g Q	s i:
la-	ger
l0 Q	g @r
la-	goon
l0 V	g u: n
la-	goons
l0 V	g u: n z
la-	gos
l0 eI	g O: s
la-	gu-	na
l0 V	g u:	n V
la-	gu-	nas
l0 V	g u:	n V z
la-	hey
l0 eI	h i:
la-	hore
l0 Q	h O@
la-	i-	ty
l0 eI	I	t i:
la-	ing
l0 Q	I N
la-	joie
l0 { dZ	w Q
la-	ker
l0 eI	k @r
la-	kers
l0 eI	k @r z
la-	key
l0 eI	k i:
la-	kin
l0 {	k I n
la-	kins
l0 {	k I n z
la-	ko-	ta
l0 V	k @U	t V
la-	ko-	tas
l0 V	k @U	t V z
la-	la
l0 Q	l V
la-	lan-	de
l0 Q	l Q n	d i:
la-	li-	ta
l0 V	l i:	t V
la-	ma
l0 Q	m V
la-	ma-	ist
l0 Q	m aI	I s t
la-	mar
l0 V	m Q@
la-	mar-	re
l0 Q	m Q@	i:
la-	mar's
l0 V	m Q@ z
la-	mas
l0 Q	m V z
la-	ma's
l0 Q	m V z
la-	mel-	lar
l0 V	m e	l @r
la-	men-	ta-	ble
l0 V	m e n	t V	b V l
la-	men-	ted
l0 V	m e n	t V d
la-	men-	ting
l0 V	m e n	t I N
la-	ment
l0 V	m e n t
la-	ments
l0 V	m e n t s
la-	mer
l0 eI	m @r
la-	mers
l0 eI	m @r z
la-	mi-	a
l0 eI	m i:	V
la-	mi-	na
l0 {	m I	n V
la-	mi-	na-	ted
l0 {	m I	n eI	t I d
la-	mi-	na-	ting
l0 {	m I	n eI	t I N
la-	mi-	nar
l0 {	m I	n @r
la-	mi-	nate
l0 {	m I	n V t
la-	mi-	nates
l0 {	m I	n V t s
la-	mi-	son
l0 {	m I	s V n
la-	my
l0 eI	m i:
la-	na
l0 {	n V
la-	na-	gan
l0 {	n V	g { n
la-	nete
l0 V	n i: t
la-	ney
l0 eI	n i:
la-	ni
l0 Q	n i:
la-	ni-	us
l0 eI	n i:	V s
la-	nier
l0 V	n I@
la-	no-	lin
l0 {	n V	l V n
la-	num
l0 {	n V m
la-	o-	tian
l0 eI	@U	S V n
la-	os
l0 Q	@U s
la-	pa-	ros-	co-	pic
l0 {	p @r	Q s	k V	p I k
la-	pa-	ros-	co-	py
l0 {	p @r	Q s	k V	p i:
la-	paz
l0 V	p O: z
la-	pel
l0 V	p e l
la-	pels
l0 V	p e l z
la-	pey-	rouse
l0 {	p I@	u: s
la-	pi-	da-	ry
l0 {	p I	d e@	i:
la-	pi-	ne
l0 Q	p i:	n i:
la-	pides
l0 V	p aI d z
la-	pin
l0 {	p I n
la-	pointe
l0 V	p OI n t
la-	porte
l0 V	p O@ t
la-	ra
l0 Q@	V
la-	ra-	mie
l0 e@	V	m i:
la-	raine
l0 @r	eI n
la-	re-	do
l0 @r	eI	d @U
la-	re-	na
l0 Q@	e	n V
la-	ri-	at
l0 e@	i:	V t
la-	ri-	mer
l0 {	r I	m @r
la-	ri-	more
l0 Q@	i:	m O@
la-	ri-	na
l0 Q@	i:	n V
la-	ri-	ne
l0 Q@	i:	n i:
la-	ris-	sa
l0 Q@	i:	s V
la-	ro-	chelle
l0 {	r V	S V l
la-	ro-	se
l0 Q@	@U	s i:
la-	rue
l0 @r	u:
la-	ryn-	ge-	al
l0 @r	I n	dZ i:	V l
la-	ryn-	gi-	tis
l0 e@	V n	dZ aI	t V s
la-	rynx
l0 e@	I N k s
la-	sa-	la
l0 Q	s Q	l V
la-	sag-	na
l0 Q	s Q n	j V
la-	salle
l0 V	s { l
la-	ser
l0 eI	z @r
la-	sers
l0 eI	z @r z
la-	ser's
l0 eI	z @r z
la-	sher
l0 {	S @r
la-	shes
l0 {	S V z
la-	shing
l0 {	S I N
la-	shings
l0 {	S I N z
la-	ta
l0 Q	t V
la-	ta-	sha
l0 V	t Q	S V
la-	te-	ral
l0 {	t @r	V l
la-	te-	rites
l0 {	t @r	aI t s
la-	te-	xes
l0 eI	t e k	s V z
la-	ten-	cy
l0 eI	t V n	s i:
la-	tent
l0 eI	t V n t
la-	ter
l0 eI	t @r
la-	test
l0 eI	t V s t
la-	tex
l0 eI	t e k s
la-	tham
l0 {	T V m
la-	tham's
l0 {	T V m z
la-	than
l0 {	T V n
la-	ther
l0 {	D @r
la-	thers
l0 {	D @r z
la-	ti-	go
l0 V	t i:	g @U
la-	ti-	mer
l0 {	t I	m @r
la-	ti-	more
l0 Q	t i:	m O@
la-	ti-	na
l0 Q	t i:	n V
la-	ti-	nate
l0 {	t I	n eI t
la-	tin
l0 {	t I n
la-	to-	na
l0 Q	t @U	n V
la-	to-	ni-	a
l0 Q	t @U	n i:	V
la-	to-	ya
l0 V	t OI	V
la-	to-	ya's
l0 V	t OI	V z
la-	ton
l0 {	t V n
la-	tour
l0 V	t U@
la-	va
l0 Q	v V
la-	va-	to-	ries
l0 {	v V	t O@	i: z
la-	va-	to-	ry
l0 {	v V	t O@	i:
la-	val
l0 V	v Q l
la-	val-	le
l0 Q	v Q	l i:
la-	ve-	ry
l0 eI	v @r	i:
la-	velle
l0 V	v e l
la-	ven
l0 eI	v V n
la-	ven-	der
l0 {	v V n	d @r
la-	ver
l0 eI	v @r
la-	vergne
l0 V	v @r n j
la-	verne
l0 V	v @r n
la-	vers
l0 eI	v @r z
la-	vette
l0 V	v e t
la-	vi
l0 eI	v i:
la-	vi-	na
l0 Q	v i:	n V
la-	vi-	ne
l0 Q	v i:	n i:
la-	vi-	nia
l0 V	v I n	j V
la-	vi-	shes
l0 {	v I	S V z
la-	vi-	shing
l0 {	v I	S I N
la-	vish
l0 {	v I S
la-	vish-	ly
l0 {	v I S	l i:
la-	vished
l0 {	v I S t
la-	voie
l0 V v	w Q
la-	vy
l0 eI	v i:
la-	wing
l0 O:	I N
la-	xa-	tive
l0 { k	s V	t I v
la-	xa-	tives
l0 { k	s V	t I v z
la-	xey
l0 { k	s i:
la-	xi-	ty
l0 { k	s I	t i:
la-	ye-	ring
l0 eI	@r	I N
la-	yer
l0 eI	@r
la-	yered
l0 eI	@r d
la-	yers
l0 eI	@r z
la-	za-	re
l0 Q	z Q@	eI
la-	za-	ro
l0 V	z Q@	@U
la-	za-	rus
l0 {	z @r	V s
la-	zar
l0 eI	z @r
la-	zear
l0 V	z I@
la-	zi-	er
l0 eI	z i:	@r
la-	zi-	est
l0 eI	z i:	V s t
la-	zi-	ly
l0 {	z I	l i:
la-	zi-	ness
l0 eI	z i:	n V s
la-	zo
l0 Q	z @U
la-	zor
l0 Q	z O@
la-	zu-	li
l0 V	z u:	l i:
la-	zu-	lite
l0 {	z V	l aI t
la-	zy
l0 eI	z i:
lab
l0 { b
lab-	ra-	dor
l0 { b	r V	d O@
labe
l0 eI b
labo-	ra-	to-	ries
l0 { b	r V	t O@	i: z
labo-	ra-	to-	ry
l0 { b	r V	t O@	i:
labo-	ra-	to-	ry's
l0 { b	r V	t O@	i: z
labs
l0 { b z
lab's
l0 { b z
lac
l0 { k
lac-	co-	liths
l0 {	k V	l I T s
lac-	ka-	dai-	si-	cal
l0 {	k V	d eI	z I	k V l
lac-	ka-	wan-	na
l0 {	k V	w Q	n V
lac-	key
l0 {	k i:
lac-	keys
l0 {	k i: z
lac-	king
l0 {	k I N
lac-	lede
l0 Q k	l i: d
lac-	quer
l0 {	k @r
lac-	quered
l0 {	k @r d
lac-	roix
l0 V k	r OI
lac-	rosse
l0 V k	r O: s
lac-	ta-	ting
l0 { k	t eI	t I N
lac-	ta-	tion
l0 { k	t eI	S V n
lac-	tase
l0 { k	t eI s
lac-	tate
l0 { k	t eI t
lac-	teals
l0 { k	t i: l z
lac-	tic
l0 { k	t I k
lac-	to-	ba-	cil-	lus
l0 { k	t @U	b V	s I	l V s
lac-	tone
l0 { k	t @U n
lac-	tose
l0 { k	t @U s
lace
l0 eI s
lace-	field
l0 eI s	f i: l d
laced
l0 eI s t
lach
l0 { tS
lach-	lan
l0 { k	l V n
lach-	man
l0 { k	m V n
lache
l0 { tS
lack
l0 { k
lack-	lus-	ter
l0 { k	l V s	t @r
lacked
l0 { k t
lacks
l0 { k s
lac's
l0 { k s
lad
l0 { d
lad-	der
l0 {	d @r
lad-	ders
l0 {	d @r z
lad-	ner
l0 { d	n @r
lad-	son
l0 { d	s V n
ladd
l0 { d
ladd's
l0 { d z
lade
l0 eI d
lads
l0 { d z
lae-	vo
l0 eI	v @U
laf-	fer-	ty
l0 {	f @r	t i:
laf-	lam
l0 V f	l { m
laf-	leur
l0 V f	l @r
laf-	rance
l0 V f	r { n s
laff
l0 { f
lag
l0 { g
lag-	gard
l0 {	g @r d
lag-	gards
l0 {	g @r d z
lag-	ging
l0 {	g I N
lag-	range
l0 { g	r eI n dZ
lage
l0 eI dZ
lagged
l0 { g d
lags
l0 { g z
lah-	ti
l0 Q	t i:
lai
l0 aI
laid
l0 eI d
laid-	law
l0 eI d	l O:
laid-	law's
l0 eI d	l O: z
lail
l0 eI l
lain
l0 eI n
laine
l0 eI n
lair
l0 e@
laird
l0 e@ d
lais
l0 eI z
lais-	sez
l0 eI	z eI
lait
l0 eI
lak
l0 { k
lake
l0 eI k
lake-	front
l0 eI k	f r V n t
lake-	land
l0 eI k	l V n d
lake-	shore
l0 eI k	S O@
lake-	side
l0 eI k	s aI d
lake-	view
l0 eI k	v j u:
lake-	wood
l0 eI k	w U d
lakes
l0 eI k s
lake's
l0 eI k s
lal
l0 { l
lal-	la
l0 {	l V
lal-	ly
l0 {	l i:
lall
l0 O: l
lam
l0 { m
lam-	bas-	ted
l0 { m	b { s	t V d
lam-	bas-	ting
l0 { m	b eI s	t I N
lam-	baste
l0 { m	b { s t
lam-	bastes
l0 { m	b { s t s
lam-	ber-	to
l0 Q m	b e@	t @U
lam-	ber-	ton
l0 { m	b @r	t V n
lam-	bert
l0 { m	b @r t
lam-	bert-	son
l0 { m	b @r t	s V n
lam-	bert's
l0 { m	b @r t s
lam-	beth
l0 { m	b e T
lam-	bie
l0 { m	b i:
lam-	bing
l0 {	m I N
lam-	bor-	ghi-	ni
l0 { m	b @r	g i:	n i:
lam-	bor-	ghi-	nis
l0 { m	b @r	g i:	n i: z
lam-	bor-	ghi-	ni's
l0 { m	b @r	g i:	n i: z
lam-	boy
l0 { m	b OI
lam-	brecht
l0 { m	b r I k t
lam-	by
l0 { m	b i:
lam-	ping
l0 { m	p I N
lam-	poon
l0 { m	p u: n
lam-	pooned
l0 { m	p u: n d
lam-	poon's
l0 { m	p u: n z
lam-	port
l0 { m	p O@ t
lam-	son
l0 { m	s V n
lamb
l0 { m
lamb-	da
l0 { m	d V
lambs
l0 { m z
lamb's
l0 { m z
lame
l0 eI m
lame-	ly
l0 eI m	l i:
lamp-	ligh-	ter
l0 { m	p l aI	t @r
lamp-	ligh-	ters
l0 { m	p l aI	t @r z
lamp-	ligh-	ter's
l0 { m	p l aI	t @r z
lamp-	man
l0 { m	p m V n
lamp-	post
l0 { m	p p @U s t
lamp-	posts
l0 { m	p p @U s t s
lamp-	rey
l0 { m	p r i:
lamp-	reys
l0 { m	p r i: z
lamp-	ron
l0 { m	p r V n
lamps
l0 { m p s
lan
l0 { n
lan-	ca-	shire
l0 { N	k V	S aI r
lan-	cas-	ter
l0 { n	k { s	t @r
lan-	cast-	ri-	an
l0 { N	k { s	t r i:	V n
lan-	ce-	lot
l0 { n	s V	l Q t
lan-	ce-	o-	late
l0 { n	s i:	V	l eI t
lan-	cer
l0 { n	s @r
lan-	cers
l0 { n	s @r z
lan-	ce's
l0 { n	s V z
lan-	cet
l0 { n	s V t
lan-	cets
l0 { n	s V t s
lan-	cet's
l0 { n	s V t s
lan-	cing
l0 { n	s I N
lan-	da
l0 { n	d V
lan-	dau
l0 { n	d aU
lan-	ded
l0 { n	d V d
lan-	der
l0 { n	d @r
lan-	ders
l0 { n	d @r z
lan-	dess
l0 { n	d V s
lan-	di-	ni
l0 Q n	d i:	n i:
lan-	di-	no
l0 Q n	d i:	n @U
lan-	ding
l0 { n	d I N
lan-	dings
l0 { n	d I N z
lan-	dis
l0 { n	d I s
lan-	do
l0 { n	d @U
lan-	don
l0 { n	d V n
lan-	dor
l0 { n	d @r
lan-	dow-	ner
l0 { n	d @U	n @r
lan-	dow-	ners
l0 { n	d @U	n @r z
lan-	drum
l0 { n	d r V m
lan-	dry
l0 { n	d r i:
lan-	dry's
l0 { n	d r i: z
lan-	dy
l0 { n	d i:
lan-	ford
l0 { n	f @r d
lan-	gan
l0 { N	g V n
lan-	ge-	land
l0 eI N	g V	l V n d
lan-	gel
l0 eI N	g V l
lan-	ger
l0 {	N @r
lan-	gil-	le
l0 Q N	g i:	l i:
lan-	gill
l0 { N	g I l
lan-	go
l0 Q N	g @U
lan-	gua-	ges
l0 { N	g w V	dZ V z
lan-	guage
l0 { N	g w V dZ
lan-	gui-	shes
l0 { N	g w I	S V z
lan-	gui-	shing
l0 { N	g w I	S I N
lan-	guid
l0 { N	g w I d
lan-	guish
l0 { N	g w I S
lan-	guished
l0 { N	g w I S t
lan-	ham
l0 {	n V m
lan-	ka
l0 { N	k V
lan-	kan
l0 { N	k V n
lan-	ka's
l0 { N	k V z
lan-	ky
l0 { N	k i:
lan-	na
l0 {	n V
lan-	ners
l0 {	n @r z
lan-	ni
l0 {	n i:
lan-	non
l0 {	n V n
lan-	ny
l0 {	n i:
lan-	sing
l0 { n	s I N
lan-	sing's
l0 { n	s I N z
lan-	ta-	na
l0 { n	t {	n V
lan-	tern
l0 { n	t @r n
lan-	terns
l0 { n	t @r n z
lan-	tha-	num
l0 { n	T V	n V m
lan-	try
l0 { n	t r i:
lan-	yard
l0 { n	j V r d
lan-	za
l0 { n	z V
lanc-	tot
l0 { N	k t V t
lance
l0 { n s
lance-	let
l0 { n	s l V t
land
l0 { n d
land-	fall
l0 { n	d f O: l
land-	fil-	ling
l0 { n	d f I	l I N
land-	fill
l0 { n	d f I l
land-	fills
l0 { n	d f I l z
land-	form
l0 { n	d f O@ m
land-	forms
l0 { n	d f O@ m z
land-	grave
l0 { n	d g r eI v
land-	hol-	der
l0 { n	d h @U l	d @r
land-	hol-	ders
l0 { n	d h @U l	d @r z
land-	hol-	ding
l0 { n	d h @U l	d I N
land-	hol-	dings
l0 { n	d h @U l	d I N z
land-	la-	dy
l0 { n	d l eI	d i:
land-	ler
l0 { n	d l @r
land-	less
l0 { n	d l V s
land-	lock
l0 { n	d l Q k
land-	locked
l0 { n	d l Q k t
land-	lord
l0 { n	d l O@ d
land-	lords
l0 { n	d l O@ d z
land-	lord's
l0 { n	d l O@ d z
land-	man
l0 { n	d m V n
land-	mark
l0 { n	d m Q@ k
land-	marks
l0 { n	d m Q@ k s
land-	mark's
l0 { n	d m Q@ k s
land-	mass
l0 { n	d m { s
land-	mine
l0 { n	d m aI n
land-	mines
l0 { n	d m aI n z
land-	sat
l0 { n	d s { t
land-	sca-	per
l0 { n	d s k eI	p @r
land-	sca-	pers
l0 { n	d s k eI	p @r z
land-	sca-	ping
l0 { n	d s k eI	p I N
land-	scape
l0 { n	d s k eI p
land-	scaped
l0 { n	d s k eI p t
land-	scapes
l0 { n	d s k eI p s
land-	slide
l0 { n	d s l aI d
land-	slides
l0 { n	d s l aI d z
land-	ward
l0 { n	d w @r d
land-	wehr
l0 { n	d w I@
lande
l0 { n d
landes
l0 { n d z
lands
l0 { n d z
land's
l0 { n d z
lands-	man
l0 { n	d z m V n
lane
l0 eI n
lanes
l0 eI n z
lane's
l0 eI n z
lang
l0 { N
lang-	behn
l0 { N	b e n
lang-	don
l0 { N	d V n
)"
R"(lang-	ford
l0 { N	f @r d
lang-	ham
l0 { N	h { m
lang-	hans
l0 { N	h V n z
lang-	horne
l0 { N	h O@ n
lang-	land
l0 { N	l V n d
lang-	ley
l0 { N	l i:
lang-	lois
l0 V N	l w Q
lang-	ridge
l0 { N	g r I dZ
lang-	ton
l0 { N	t V n
lang-	wor-	thy
l0 { N	w @r	D i:
lange
l0 { N
lange's
l0 { N z
langs-	ton
l0 { N	s t V n
lank
l0 { N k
lans-	dale
l0 { n	z d eI l
lans-	downe
l0 { n	s d aU n
lans-	ford
l0 { n	s f @r d
lant
l0 { n t
lantz
l0 { n t s
lao
l0 aU
lap
l0 { p
lap-	dog
l0 { p	d O: g
lap-	ham
l0 {	f V m
lap-	land
l0 { p	l { n d
lap-	ping
l0 {	p I N
lap-	ses
l0 { p	s V z
lap-	sing
l0 { p	s I N
lap-	top
l0 { p	t Q p
lap-	tops
l0 { p	t Q p s
lapp
l0 { p
lapped
l0 { p t
lapps
l0 { p s
laps
l0 { p s
lapse
l0 { p s
lapsed
l0 { p s t
lar
l0 Q@
lar-	ce-	nous
l0 Q@	s V	n V s
lar-	ce-	ny
l0 Q@	s V	n i:
lar-	ded
l0 Q@	d V d
lar-	der
l0 Q@	d @r
lar-	gen
l0 Q@	g V n
lar-	gent
l0 Q@	dZ V n t
lar-	ger
l0 Q@	dZ @r
lar-	gess
l0 Q@	dZ V s
lar-	gesse
l0 Q@	g e s
lar-	gest
l0 Q@	dZ V s t
lar-	go
l0 Q@	g @U
lar-	kin
l0 Q@	k I n
lar-	kins
l0 Q@	k I n z
lar-	ner
l0 Q@	n @r
lar-	ra-	bee
l0 {	r V	b i:
lar-	re-	a
l0 {	r i:	V
lar-	ry
l0 e@	i:
lar-	ry's
l0 e@	i: z
lar-	sen
l0 Q@	s V n
lar-	son
l0 Q@	s V n
lar-	va
l0 Q@	v V
lar-	vae
l0 Q@	v i:
lar-	val
l0 Q@	v V l
larch
l0 Q@ tS
larch-	mont
l0 Q@ tS	m Q n t
larch-	mont's
l0 Q@ tS	m Q n t s
lard
l0 Q@ d
lard-	ner
l0 Q@ d	n @r
lare
l0 e@
large
l0 Q@ dZ
large-	ly
l0 Q@ dZ	l i:
large-	ness
l0 Q@ dZ	n V s
lark
l0 Q@ k
larks
l0 Q@ k s
larks-	pur
l0 Q@ k	s p @r
larned
l0 Q@ n d
lars
l0 Q@ z
las
l0 Q s
las-	ci-	vi-	ous
l0 V	s I	v i:	V s
las-	ker
l0 { s	k @r
las-	ki
l0 Q s	k i:
las-	ko
l0 { s	k @U
las-	ky
l0 { s	k i:
las-	ley
l0 { s	l i:
las-	sa
l0 Q	s V
las-	sen
l0 {	s V n
las-	ser
l0 {	s @r
las-	si-	ter
l0 {	s aI	t @r
las-	sie
l0 {	s i:
las-	so
l0 {	s @U
las-	ted
l0 { s	t V d
las-	ter
l0 { s	t @r
las-	ting
l0 { s	t I N
lase
l0 eI z
lash
l0 { S
lashed
l0 { S t
lask
l0 { s k
lass
l0 { s
last
l0 { s t
last-	ly
l0 { s	t l i:
lasts
l0 { s t s
lasz-	lo
l0 { z	l @U
lat
l0 Q t
lat-	ches
l0 {	tS V z
lat-	ching
l0 {	tS I N
lat-	rine
l0 V t	r i: n
lat-	rines
l0 V t	r i: n z
lat-	robe
l0 Q t	r @U b
lat-	ta
l0 {	t V
lat-	te
l0 Q	t eI
lat-	ter
l0 {	t @r
lat-	ter's
l0 {	t @r z
lat-	ti-	mer
l0 {	t I	m @r
lat-	ti-	more
l0 Q	t i:	m O@
lat-	tice
l0 {	t I s
lat-	tice-	work
l0 {	t I s	w @r k
lat-	tin
l0 {	t I n
lat-	ty
l0 {	t i:
lat-	vi-	a
l0 { t	v i:	V
lat-	vi-	an
l0 { t	v i:	V n
lat-	vi-	ans
l0 { t	v i:	V n z
lat-	vi-	a's
l0 { t	v i:	V z
latch
l0 { tS
latch-	key
l0 { tS	k i:
latched
l0 { tS t
late
l0 eI t
late-	co-	mer
l0 eI t	k V	m @r
late-	co-	mers
l0 eI t	k V	m @r z
late-	ly
l0 eI t	l i:
late-	ness
l0 eI t	n V s
lath
l0 { T
lath-	rop
l0 { T	r V p
lathe
l0 eI D
lathes
l0 eI D z
lats
l0 Q t s
lau
l0 aU
lau-	ber
l0 aU	b @r
lau-	da-	ble
l0 O:	d V	b V l
lau-	da-	num
l0 O:	d V	n V m
lau-	da-	to-	ry
l0 O:	d V	t O@	i:
lau-	ded
l0 O:	d V d
lau-	der
l0 O:	d @r
lau-	der-	dale
l0 O:	d @r	d eI l
lau-	ding
l0 O:	d I N
lau-	e
l0 aU	i:
lau-	er
l0 aU	@r
lau-	fer
l0 O:	f @r
lau-	gher
l0 Q	k @r
lau-	ghing
l0 {	f I N
lau-	ghing-	ly
l0 {	f I N	l i:
lau-	ghing-	stock
l0 {	f I N	s t Q k
lau-	ra
l0 O@	V
lau-	rance
l0 O@	V n s
lau-	ra's
l0 O@	V z
lau-	re-	ate
l0 O@	i:	V t
lau-	re-	ates
l0 O@	i:	V t s
lau-	re-	na
l0 O@	e	n V
lau-	reen
l0 O@	i: n
lau-	rel
l0 O@	V l
lau-	rels
l0 O@	V l z
lau-	rel's
l0 O@	V l z
lau-	ren
l0 O@	V n
lau-	ren-	tian
l0 O@	e n	S V n
lau-	rence
l0 O@	V n s
lau-	rene
l0 O@	i: n
lau-	rens
l0 O@	V n z
lau-	rent
l0 O@	V n t
lau-	ret-	ta
l0 @r	e	t V
lau-	rette
l0 O@	e t
lau-	ri
l0 Q@	i:
lau-	rice
l0 O@	I s
lau-	rie
l0 Q@	i:
lau-	rie's
l0 Q@	i: z
lau-	rin
l0 O@	I n
lau-	ro
l0 O@	@U
lau-	ry
l0 O@	i:
lau-	sanne
l0 O:	s { n
lau-	ter
l0 aU	t @r
lau-	zon
l0 aU	z V n
lauch
l0 Q tS
laud
l0 O: d
laude
l0 O: d
lauds
l0 O: d z
lauf
l0 O: f
laug-	ha-	ble
l0 {	f V	b V l
laugh
l0 { f
laugh-	lin
l0 Q k	l I n
laugh-	ter
l0 { f	t @r
laugh-	ton
l0 O:	t V n
laughed
l0 { f t
laughs
l0 { f s
laun
l0 O: n
laun-	ce-	lot
l0 O: n	s V	l Q t
laun-	cher
l0 O: n	tS @r
laun-	chers
l0 O: n	tS @r z
laun-	ches
l0 O: n	tS V z
laun-	ching
l0 O: n	tS I N
laun-	chings
l0 O: n	tS I N z
laun-	de-	rer
l0 O: n	d @r	@r
laun-	de-	rers
l0 O: n	d @r	@r z
laun-	de-	ring
l0 O: n	d @r	I N
laun-	der
l0 O: n	d @r
laun-	dered
l0 O: n	d @r d
launch
l0 O: n tS
launched
l0 O: n tS t
laund-	ries
l0 O: n	d r i: z
laund-	ro-	mat
l0 O: n	d r V	m { t
laund-	ry
l0 O: n	d r i:
laur
l0 O@
laure
l0 O@
laux
l0 O: k s
lave
l0 eI v
law
l0 Q
law-	brea-	ker
l0 O: b	r eI	k @r
law-	brea-	kers
l0 O: b	r eI	k @r z
law-	brea-	king
l0 O: b	r eI	k I N
law-	ford
l0 O:	f @r d
law-	ful
l0 O:	f V l
law-	ful-	ly
l0 O:	f V	l i:
law-	ler
l0 O:	l @r
law-	less
l0 O:	l V s
law-	less-	ness
l0 O:	l V s	n V s
law-	ley
l0 O:	l i:
law-	lor
l0 O:	l @r
law-	ma-	ker
l0 O:	m eI	k @r
law-	ma-	kers
l0 O:	m eI	k @r z
law-	ma-	ker's
l0 O:	m eI	k @r z
law-	ma-	king
l0 O:	m eI	k I N
law-	man
l0 O:	m V n
law-	men
l0 O:	m e n
law-	ner
l0 O:	n @r
law-	ren-	ce's
l0 O@	V n	s V z
law-	ren-	ci-	um
l0 O@	e n	s i:	V m
law-	rence
l0 O@	V n s
law-	rence-	burg
l0 O@	V n	s b @r g
law-	rence-	ville
l0 O@	V n	s v I l
law-	rie
l0 O@	i:
law-	ry
l0 O@	i:
law-	son
l0 O:	s V n
law-	son's
l0 O:	s V n z
law-	suit
l0 O:	s u: t
law-	suits
l0 O:	s u: t s
law-	suit's
l0 O:	s u: t s
law-	ter
l0 O:	t @r
law-	ton
l0 O:	t V n
law-	ye-	ring
l0 O:	j @r	I N
law-	yer
l0 O:	j @r
law-	yer-	ly
l0 O:	j @r	l i:
law-	yers
l0 O:	j @r z
law-	yer's
l0 O:	j @r z
lawes
l0 O: z
lawn
l0 O: n
lawn-	mo-	wer
l0 O: n	m @U	@r
lawn-	mo-	wers
l0 O: n	m @U	@r z
lawns
l0 O: n z
laws
l0 O: z
law's
l0 O: z
lax
l0 { k s
lay
l0 eI
lay-	cock
l0 eI	k Q k
lay-	ing
l0 eI	I N
lay-	land
l0 eI	l V n d
lay-	man
l0 eI	m V n
lay-	man's
l0 eI	m V n z
lay-	men
l0 eI	m V n
lay-	o-	ver
l0 eI	@U	v @r
lay-	o-	vers
l0 eI	@U	v @r z
lay-	off
l0 eI	O: f
lay-	offs
l0 eI	O: f s
lay-	out
l0 eI	aU t
lay-	outs
l0 eI	aU t s
lay-	peo-	ple
l0 eI	p i:	p V l
lay-	per-	son
l0 eI	p @r	s V n
lay-	ton
l0 eI	t V n
lay-	up
l0 eI	V p
layne
l0 eI n
lays
l0 eI z
lay's
l0 eI z
laz-	za-	ro
l0 Q t	s Q@	@U
le
l0 V
le-	ah
l0 i:	V
le-	an-	der
l0 i:	{ n	d @r
le-	an-	dro
l0 i:	Q n	d r @U
le-	ann
l0 i:	{ n
le-	ant
l0 i:	V n t
le-	ba-	nese
l0 e	b V	n i: z
le-	ba-	non
l0 e	b V	n V n
le-	ba-	non's
l0 e	b V	n V n z
le-	ba-	ron
l0 V	b e@	V n
le-	bar
l0 V	b Q@
le-	beau
l0 V	b @U
le-	ben
l0 e	b V n
le-	ber
l0 i:	b @r
le-	blanc
l0 V b	l { N k
le-	bo
l0 eI	b @U
le-	brun
l0 e b	r V n
le-	che-	rous
l0 e	tS @r	V s
le-	cher
l0 e	tS @r
le-	ci-	thin
l0 e	s I	T I n
le-	con-	te
l0 e	k @U n	t i:
le-	croy
l0 e k	r OI
le-	da
l0 i:	d V
le-	de-	rer
l0 e	d @r	@r
le-	deen
l0 V	d i: n
le-	doux
l0 V	d u:
le-	ga-	cies
l0 e	g V	s i: z
le-	ga-	cy
l0 e	g V	s i:
le-	ga-	lese
l0 e	g V	l i: s
le-	ga-	li-	sm
l0 i:	g V	l I	z V m
le-	ga-	li-	ties
l0 i:	g {	l I	t i: z
le-	ga-	li-	ty
l0 i:	g {	l I	t i:
le-	ga-	li-	za-	tion
l0 i:	g V	l I	z eI	S V n
le-	ga-	li-	zing
l0 i:	g V	l aI	z I N
le-	ga-	lis-	tic
l0 e	g V	l I s	t I k
le-	ga-	lize
l0 i:	g V	l aI z
le-	ga-	lized
l0 i:	g V	l aI z d
le-	ga-	to
l0 V	g Q	t @U
le-	gal
l0 i:	g V l
le-	gal-	ly
l0 i:	g V	l i:
le-	gals
l0 i:	g V l z
le-	gas-	pi
l0 e	g Q s	p i:
le-	gate
l0 e	g V t
le-	gates
l0 e	g V t s
le-	gen-	da-	ry
l0 e	dZ V n	d e@	i:
le-	gen-	dre
l0 e	g V n	d r eI
le-	gend
l0 e	dZ V n d
le-	gends
l0 e	dZ V n d z
le-	ger
l0 e	dZ @r
le-	ger-	de-	main
l0 e	dZ @r	d V	m eI n
le-	gi-	bi-	li-	ty
l0 e	dZ V	b I	l V	t i:
le-	gi-	ble
l0 e	g I	b V l
le-	gio-	na-	ries
l0 i:	dZ V	n e@	i: z
le-	gion
l0 i:	dZ V n
le-	gion-	naire
l0 i:	dZ V	n e@
le-	gion-	naires
l0 i:	dZ V	n e@ z
le-	gion-	naire's
l0 i:	dZ V	n e@ z
le-	gions
l0 i:	dZ V n z
le-	gis-	la-	ted
l0 e	dZ I s	l eI	t I d
le-	gis-	la-	ting
l0 e	dZ I s	l eI	t I N
le-	gis-	la-	tion
l0 e	dZ I s	l eI	S V n
le-	gis-	la-	tion's
l0 e	dZ I s	l eI	S V n z
le-	gis-	late
l0 e	dZ I s	l eI t
le-	gis-	lates
l0 e	dZ I s	l eI t s
le-	go
l0 e	g @U
le-	gume
l0 e g	j u: m
le-	gumes
l0 e g	j u: m z
le-	high
l0 i:	h aI
le-	jeune
l0 e	j OI n
le-	la
l0 i:	l V
le-	lah
l0 e	l V
le-	land
l0 i:	l V n d
le-	lia
l0 i: l	j V
le-	ma
l0 i:	m V
le-	mai-	tre
l0 V	m eI	t @r
le-	man
l0 i:	m V n
le-	mans
l0 e	m V n z
le-	mar
l0 I	m Q@
le-	mas-	ters
l0 V	m { s	t @r z
le-	may
l0 e	m eI
le-	mi-	re
l0 eI	m I@	eI
le-	mieux
l0 V m	j u:
le-	ming
l0 i:	m I N
le-	mo-	nade
l0 e	m V	n eI d
le-	mon
l0 e	m V n
le-	mons
l0 e	m V n z
le-	mont
l0 V	m Q n t
le-	mue-	la
l0 e	m u:	l V
le-	mur
l0 i:	m @r
le-	murs
l0 i:	m @r z
le-	na
l0 i:	n V
le-	nard
l0 e	n @r d
le-	na's
l0 i:	n V z
le-	ni-	ent
l0 i:	n i:	e n t
le-	ni-	ni-	sm
l0 e	n I	n I	z V m
le-	ni-	nist
l0 e	n I	n I s t
le-	nien-	cy
l0 i: n	j e n	s i:
le-	nient-	ly
l0 i: n	j e n	t l i:
le-	nig
l0 e	n I g
le-	nin
l0 e	n I n
le-	nin-	grad
l0 e	n I n	g r { d
le-	nin's
l0 e	n I n z
le-	nis
l0 i:	n I s
le-	no
l0 e	n @U
le-	no-	ra
l0 e	n @r	V
le-	nore
l0 V	n O@
le-	nos
l0 i:	n @U z
le-	no's
l0 e	n @U z
le-	nox
l0 e	n V k s
le-	o
l0 i:	@U
le-	o-	ma
l0 I	@U	m V
le-	o-	mins-	ter
l0 i:	@U	m I n	s t @r
le-	o-	na
l0 i:	@U	n V
le-	o-	nar-	do
l0 i:	V	n Q@	d @U
le-	o-	nel
l0 i:	@U	n V l
le-	o-	nerd
l0 i:	V	n @r d
le-	o-	ni
l0 e	@U	n i:
le-	o-	nid
l0 i:	V	n V d
le-	o-	no-	ra
l0 i:	V	n O@	V
le-	o-	nore
l0 i:	V	n O@
le-	o-	pol-	do
l0 i:	V	p @U l	d @U
le-	o-	pold
l0 i:	V	p @U l d
le-	o-	tard
l0 i:	V	t Q@ d
le-	oine
l0 I	OI n
le-	on
l0 i:	Q n
le-	on-	hard
l0 i:	V n	h Q@ t
le-	on-	tyne
l0 i:	Q n	t aI n
le-	one
l0 i:	@U n
le-	ones
l0 i:	@U n z
le-	on's
l0 i:	Q n z
le-	os
l0 i:	@U z
le-	o's
l0 i:	@U z
le-	page
l0 e	p I dZ
le-	per
l0 e	p @r
le-	pers
l0 e	p @r z
le-	pi-	ne
l0 e	p i:	n i:
le-	qui-	re
l0 eI k	w I@	eI
le-	roy
l0 i:	r OI
le-	sa
l0 i:	s V
le-	sage
l0 e	s I dZ
le-	sion
l0 i:	Z V n
le-	sions
l0 i:	Z V n z
le-	so-	tho
l0 e	s @U	T @U
le-	sue-	ur
l0 e	s u:	@r
le-	ta
l0 e	t V
le-	tha
l0 e	T V
le-	tha-	li-	ty
l0 i:	T {	l I	t i:
le-	thal
l0 i:	T V l
le-	thar-	gic
l0 V	T Q@	dZ I k
le-	thar-	gy
l0 e	T @r	dZ i:
le-	thi-	a
l0 e	T i:	V
le-	ti-	cia
l0 V	t I	S V
le-	ti-	ti-	a
l0 V	t I	S i:	V
le-	ti-	zi-	a
l0 e	t i:	z i:	V
le-	to
l0 i:	t @U
le-	tup
l0 e	t V p
le-	va
l0 e	v V
le-	va-	na
l0 I	v {	n V
le-	van
l0 e	v V n
le-	vant
l0 V	v { n t
le-	vee
l0 e	v i:
le-	vees
l0 e	v i: z
le-	vel
l0 e	v V l
le-	vi-	na
l0 e	v i:	n V
le-	vi-	ner
l0 e	v I	n @r
le-	vi-	son
l0 e	v I	s V n
le-	vi-	ta-	ted
l0 e	v I	t eI	t I d
le-	vi-	ta-	ting
l0 e	v I	t eI	t I N
le-	vi-	ta-	tion
l0 e	v I	t eI	S V n
le-	vi-	tan
l0 e	v I	t V n
le-	vi-	tate
l0 e	v I	t eI t
le-	vi-	ty
l0 e	v I	t i:
le-	vin
l0 e	v I n
le-	vin-	son
l0 e	v V n	s V n
le-	vine
l0 V	v i: n
le-	vine's
l0 V	v i: n z
le-	vins
l0 e	v I n z
le-	vin's
l0 e	v I n z
le-	vis
l0 e	v V s
le-	vi's
l0 i:	v aI z
le-	vit
l0 e	v I t
le-	vit-	town
l0 e	v I	t aU n
le-	vit-	town's
l0 e	v I	t aU n z
le-	vitt
l0 e	v I t
le-	vitt's
l0 e	v I t s
le-	vy
l0 e	v i:
le-	vy-	ing
l0 e	v i:	I N
le-	vy's
l0 e	v i: z
le-	wan
l0 u:	V n
le-	wan-	na
l0 u:	V	n V
le-	wel-	len
l0 u:	e	l V n
le-	wel-	lyn
l0 u:	e	l V n
le-	wi-	s's
l0 u:	I	s V z
le-	win
l0 u:	I n
le-	win-	sky
l0 u:	I n	s k i:
le-	wing
l0 u:	I N
le-	wis
l0 u:	I s
le-	wis-	burg
l0 u:	I s	b @r g
le-	wis-	ton
l0 u:	I s	t V n
le-	xi-	cal
l0 e k	s I	k V l
le-	xi-	cog-	ra-	pher
l0 e k	s I	k Q g	r V	f @r
le-	xi-	con
l0 e k	s I	k Q n
le-	xie
l0 e k	s i:
le-	xine
l0 e k	s aI n
le-	xing-	ton
l0 e k	s I N	t V n
le-	xis
l0 e k	s I s
le-	xu-	s's
l0 e k	s V	s V z
le-	xus
l0 e k	s V s
lea
l0 i:
lea-	ches
l0 i:	tS V z
lea-	ching
l0 i:	tS I N
lea-	ch's
l0 i:	tS V z
lea-	cock
l0 i:	k Q k
lea-	ded
l0 e	d V d
lea-	den
l0 e	d V n
lea-	der
l0 i:	d @r
lea-	der-	less
l0 i:	d @r	l V s
lea-	der-	ship
l0 i:	d @r	S I p
lea-	der-	ships
l0 i:	d @r	S I p s
lea-	der-	ship's
l0 i:	d @r	S I p s
lea-	ders
l0 i:	d @r z
lea-	der's
l0 i:	d @r z
lea-	ding
l0 i:	d I N
lea-	doff
l0 i:	d O: f
lea-	fing
l0 i:	f I N
lea-	fy
l0 i:	f i:
lea-	guer
l0 i:	g @r
lea-	guers
l0 i:	g @r z
lea-	hey
l0 eI	h i:
lea-	hy
l0 eI	h i:
lea-	kage
l0 i:	k V dZ
lea-	ker
l0 i:	k @r
lea-	kers
l0 i:	k @r z
lea-	key
l0 i:	k i:
lea-	king
l0 i:	k I N
lea-	ky
l0 i:	k i:
lea-	mer
l0 i:	m @r
lea-	ming
l0 i:	m I N
lea-	ner
l0 i:	n @r
lea-	ners
l0 i:	n @r z
lea-	nest
l0 i:	n V s t
lea-	ning
l0 i:	n I N
lea-	nings
l0 i:	n I N z
lea-	ping
l0 i:	p I N
lea-	ry
l0 I@	i:
lea-	ry's
l0 I@	i: z
lea-	sa-	ble
l0 i:	s V	b V l
lea-	ser
l0 i:	s @r
lea-	ses
l0 i:	s V z
lea-	se's
l0 i:	s V z
lea-	shes
l0 i:	S V z
lea-	sing
l0 i:	s I N
lea-	sing's
l0 i:	s I N z
lea-	sure
l0 e	Z @r
lea-	the-	ry
l0 e	D @r	i:
lea-	ther
l0 e	D @r
lea-	ther-	back
l0 e	D @r	b { k
lea-	ther-	backs
l0 e	D @r	b { k s
lea-	ther-	wood
l0 e	D @r	w U d
lea-	thers
l0 e	D @r z
lea-	ve-	ning
l0 e	v V	n I N
lea-	velle
l0 V	v e l
lea-	ven
l0 e	v V n
lea-	ven-	worth
l0 e	v V n	w @r T
lea-	vened
l0 e	v V n d
lea-	vens
l0 e	v V n z
lea-	ver
l0 i:	v @r
lea-	ver's
l0 i:	v @r z
lea-	ving
l0 i:	v I N
lea-	vings
l0 i:	v I N z
lea-	vitt
l0 e	v I t
lea-	vy
l0 i:	v i:
leach
l0 i: tS
leach-	man
l0 i: tS	m V n
leached
l0 i: tS t
lead
l0 i: d
lead-	bel-	ly
l0 e d	b e	l i:
lead-	off
l0 i:	d O: f
lead-	ville
l0 e d	v I l
lead-	work
l0 e d	w @r k
leads
l0 i: d z
leaf
l0 i: f
leaf-	hop-	per
l0 i: f	h Q	p @r
leaf-	hop-	pers
l0 i: f	h Q	p @r z
leaf-	less
l0 i: f	l V s
leaf-	let
l0 i: f	l V t
leaf-	lets
l0 i: f	l V t s
leaf-	like
l0 i: f	l aI k
leafed
l0 i: f t
leafs
l0 i: f s
league
l0 i: g
leagues
l0 i: g z
league's
l0 i: g z
leak
l0 i: k
leake
l0 i: k
leaked
l0 i: k t
leaks
l0 i: k s
leal
l0 i: l
lean
l0 i: n
leaned
l0 i: n d
leans
l0 i: n z
leap
l0 i: p
leaped
l0 e p t
leapf-	rog
l0 i: p	f r O: g
leapf-	rog-	ging
l0 i: p	f r O:	g I N
leapf-	rogged
l0 i: p	f r O: g d
leaps
l0 i: p s
leapt
l0 e p t
lear
l0 I@
lear-	jet
l0 I@	dZ e t
lear-	ner
l0 @r	n @r
lear-	ners
l0 @r	n @r z
lear-	ning
l0 @r	n I N
learn
l0 @r n
learned
l0 @r n d
learns
l0 @r n z
learnt
l0 @r n t
lear's
l0 i: r z
leas
l0 i: z
lease
l0 i: s
lease-	back
l0 i: s	b { k
lease-	backs
l0 i: s	b { k s
lease-	hold
l0 i: s	h @U l d
leased
l0 i: s t
leash
l0 i: S
leashed
l0 i: S t
least
l0 i: s t
leat-	rice
l0 i: t	r I s
leath
l0 i: T
leave
l0 i: v
leaves
l0 i: v z
lec-	kie
l0 e	k i:
lec-	lair
l0 e k	l @r
lec-	laire
l0 I k	l e@
lec-	tern
l0 e k	t @r n
lec-	tor
l0 e k	t @r
lec-	tu-	rer
l0 e k	tS @r	@r
lec-	tu-	rers
l0 e k	tS @r	@r z
lec-	tu-	ring
l0 e k	tS @r	I N
lec-	ture
l0 e k	tS @r
lec-	tured
l0 e k	tS @r d
lec-	tures
l0 e k	tS @r z
lech
l0 e k
lech-	ner
l0 e k	n @r
leck
l0 e k
leck-	rone
l0 e k	r V n
led
l0 e d
led-	bet-	ter
l0 e d	b @r	t @r
led-	den
l0 e	d V n
led-	dy
l0 e	d i:
led-	ger
l0 e	dZ @r
led-	gers
l0 e	dZ @r z
led-	ges
l0 e	dZ V z
led-	yard
l0 e d	j @r d
ledge
l0 e dZ
lee
l0 i:
lee-	ches
l0 i:	tS V z
lee-	co
l0 i:	k @U
lee-	na
l0 i:	n V
lee-	per
l0 i:	p @r
lee-	ry
l0 I@	i:
lee-	ser
l0 i:	s @r
lee-	ward
l0 i:	w @r d
lee-	way
l0 i:	w eI
leech
l0 i: tS
leed
l0 i: d
leed-	s's
l0 i: d	z V z
leeds
l0 i: d z
leek
l0 i: k
leeks
l0 i: k s
leep
l0 i: p
lees
l0 i: z
lee's
l0 i: z
lees-	burg
l0 i: z	b @r g
leese
l0 i: s
leet
l0 i: t
leeth
l0 i: T
lef-	fert
l0 e	f @r t
lef-	ko-	witz
l0 e f	k V	w I t s
lef-	than-	ded
l0 e f	t h { n	d V d
lef-	thand
l0 e f	t h { n d
lef-	ti-	sm
l0 e f	t I	z V m
lef-	ties
l0 e f	t i: z
lef-	tist
l0 e f	t I s t
lef-	tists
l0 e f	t I s t s
lef-	ton
l0 e f	t V n
lef-	ty
l0 e f	t i:
leff
l0 e f
leff's
l0 e f s
left
l0 e f t
left-	han-	ded
l0 e f	t h { n	d V d
left-	hand
l0 e f	t h { n d
left-	o-	ver
l0 e f	t @U	v @r
left-	o-	vers
l0 e f	t @U	v @r z
left-	ward
l0 e f	t w @r d
left-	wich
l0 e f	t w I k
left-	win-	ger
l0 e f	t w I	N @r
left-	win-	gers
l0 e f	t w I	N @r z
left-	wing
l0 e f	t w I N
leg
l0 e g
leg-	ged
l0 e	g V d
leg-	gett
l0 e	g e t
leg-	ging
l0 e	g I N
leg-	gings
l0 e	g I N z
leg-	gy
l0 e	g i:
leg-	horn
l0 e g	h O@ n
leg-	horns
l0 e g	h O@ n z
leg-	rand
l0 e g	r { n d
leg-	ree
l0 I g	r i:
leg-	room
l0 V g	r u: m
leg-	work
l0 e g	w @r k
lege
l0 i: dZ
legge
l0 e g
legs
l0 e g z
leg's
l0 e g z
leh-	man
l0 i:	m V n
leh-	mann
l0 eI	m V n
leh-	man's
l0 i:	m V n z
leh-	mer
l0 e	m @r
leh-	rer
l0 e@	@r
lehr
l0 e@
lehr-	man
l0 e@	m V n
lei
l0 eI
lei-	fer
l0 aI	f @r
lei-	feste
l0 aI	f e s t
lei-	la
l0 i:	l V
lei-	la-	ni
l0 V	l Q	n i:
lei-	sen-	ring
l0 aI	s V n	r I N
)"
R"(lei-	ser
l0 aI	s @r
lei-	sure
l0 e	Z @r
lei-	sure-	ly
l0 i:	z @r	l i:
lei-	ter
l0 aI	t @r
leib-	man
l0 i: b	m V n
leib-	niz
l0 i: b	n I z
leices-	ter
l0 e s	t @r
leif
l0 i: f
leigh
l0 i:
leigh-	ton
l0 eI	t V n
leins-	dorf
l0 aI n	z d O@ f
leip-	zig
l0 aI p	s I g
leis
l0 eI z
leis-	ter
l0 i: s	t @r
leiss
l0 aI s
leit-	man
l0 aI t	m V n
leit-	mo-	tif
l0 aI t	m @U	t i: f
leit-	ner
l0 aI t	n @r
leith
l0 i: T
lek
l0 e k
lem
l0 e m
lem-	berg
l0 e m	b @r g
lem-	ke
l0 e m	k i:
lem-	ma
l0 e	m V
lem-	me
l0 e	m V
lem-	mie
l0 e	m i:
lem-	ming
l0 e	m I N
lem-	mings
l0 e	m I N z
lem-	mon
l0 e	m V n
lem-	pert
l0 e m	p @r t
lemcke
l0 e m k
len
l0 e n
len-	der
l0 e n	d @r
len-	ders
l0 e n	d @r z
len-	der's
l0 e n	d @r z
len-	ding
l0 e n	d I N
len-	dings
l0 e n	d I N z
len-	dl
l0 e n	d V l
l'en-	fant
l0 e n	f Q n t
len-	gel
l0 e N	g V l
len-	ger
l0 e	N @r
len-	hard
l0 e	n @r d
len-	hart
l0 e n	h Q@ t
len-	nard
l0 e	n @r d
len-	nie
l0 e	n i:
len-	non
l0 e	n V n
len-	non's
l0 e	n V n z
len-	nox
l0 e	n V k s
len-	ny
l0 e	n i:
len-	ses
l0 e n	z V z
len-	sing
l0 e n	s I N
len-	til
l0 e n	t I l
len-	tils
l0 e n	t I l z
len-	to
l0 e n	t @U
len-	zi
l0 e n	z i:
len-	z's
l0 e n	z V z
lend
l0 e n d
lends
l0 e n d z
lene
l0 i: n
leng
l0 e N
leng-	the-	ning
l0 e N	T V	n I N
leng-	then
l0 e N	T V n
leng-	thened
l0 e N	T V n d
leng-	thens
l0 e N	T V n z
leng-	thy
l0 e N	T i:
length
l0 e N k T
length-	ways
l0 e N	T w eI z
length-	wise
l0 e N	T w aI z
lengths
l0 e N k T s
lens
l0 e n z
lent
l0 e n t
lent-	ner
l0 e n	t n @r
lents
l0 e n t s
lenz
l0 e n z
leo-	la
l0 e	l V
leo-	nar-	di
l0 e	n Q@	d i:
leo-	nard
l0 e	n @r d
leo-	nard's
l0 e	n @r d z
leo-	nelle
l0 e	n e l
leo-	nie
l0 e	n i:
leo-	pard
l0 e	p @r d
leo-	pards
l0 e	p @r d z
leo-	pol-	di-	ne
l0 e	p @U l	d i:	n i:
leo-	ra
l0 e@	V
leo-	ta
l0 e	t V
leon-	ti-	ne
l0 e n	t i:	n i:
leong
l0 e N
lep
l0 e p
lep-	ley
l0 e p	l i:
lep-	pard
l0 e	p @r d
lep-	per
l0 e	p @r
lep-	re
l0 e	p @r
lep-	ro-	sy
l0 e p	r V	s i:
lep-	tin
l0 e p	t I n
lep-	to-	nic
l0 e p	t Q	n I k
lepp
l0 e p
ler-	ner
l0 @r	n @r
ler-	ner's
l0 @r	n @r z
les
l0 e s
les-	bi-	a-	ni-	sm
l0 e z	b i:	V	n I	z V m
les-	bi-	an
l0 e z	b i:	V n
les-	bi-	ans
l0 e z	b i:	V n z
les-	ko
l0 e s	k @U
les-	ley
l0 e s	l i:
les-	lie
l0 e s	l i:
les-	sard
l0 e	s @r d
les-	se-	ning
l0 e	s V	n I N
les-	see
l0 e	s i:
les-	sees
l0 e	s i: z
les-	sen
l0 e	s V n
les-	sened
l0 e	s V n d
les-	sens
l0 e	s V n z
les-	ser
l0 e	s @r
les-	sing
l0 e	s I N
les-	son
l0 e	s V n
les-	sons
l0 e	s V n z
les-	sor
l0 e	s @r
les-	sors
l0 e	s @r z
les-	ter
l0 e s	t @r
lesh
l0 e S
less
l0 e s
lest
l0 e s t
let
l0 e t
let-	cher
l0 e	tS @r
let-	down
l0 e t	d aU n
let-	te-	ring
l0 e	t @r	I N
let-	ter
l0 e	t @r
let-	ter-	head
l0 e	t @r	h e d
let-	ter-	man
l0 e	t @r	m V n
let-	ter-	man's
l0 e	t @r	m V n z
let-	ter-	press
l0 e	t @r p	r e s
let-	tered
l0 e	t @r d
let-	ters
l0 e	t @r z
let-	tice
l0 e	t I s
let-	tie
l0 e	t i:
let-	ting
l0 e	t I N
let-	tish
l0 e	t I S
let-	tuce
l0 e	t V s
let-	ty
l0 e	t i:
letch-	worth
l0 e tS	w @r T
lets
l0 e t s
let's
l0 e t s
lett
l0 e t
letts
l0 e t s
leu
l0 u:
leu-	ke-	mi-	a
l0 u:	k i:	m i:	V
leu-	ko-	cyte
l0 u:	k V	s aI t
leu-	pold
l0 OI	p @U l d
leu's
l0 u: z
lev
l0 e v
leve
l0 i: v
lew
l0 u:
lewd
l0 u: d
lex
l0 e k s
ley
l0 eI
ley-	den
l0 aI	d V n
ley-	land
l0 eI	l V n d
leys
l0 eI z
lha-	sa
l0 Q	s V
li
l0 i:
li-	a
l0 i:	V
li-	a-	bi-	li-	ties
l0 aI	V	b I	l V	t i: z
li-	a-	bi-	li-	ty
l0 aI	V	b I	l V	t i:
li-	a-	ble
l0 aI	V	b V l
li-	a-	na
l0 i:	Q	n V
li-	a-	son
l0 aI	V	s V n
li-	ai-	son
l0 i:	eI	z Q n
li-	ai-	sons
l0 i:	eI	s Q n z
li-	am
l0 i:	V m
li-	am's
l0 i:	V m z
li-	an-	na
l0 i:	Q	n V
li-	ane
l0 i:	{ n
li-	anne
l0 i:	{ n
li-	ao
l0 i:	aU
li-	ar
l0 aI	@r
li-	ars
l0 aI	@r z
li-	be-	lous
l0 aI	b V	l V s
li-	be-	ra-	ce
l0 I	b @r	Q	tS i:
li-	be-	ra-	li-	sm
l0 I	b @r	V	l I	z V m
li-	be-	ra-	li-	ty
l0 I	b @r	{	l I	t i:
li-	be-	ra-	li-	za-	tions
l0 I	b @r	V	l I	z eI	S V n z
li-	be-	ra-	li-	zing
l0 I	b @r	V	l aI	z I N
li-	be-	ra-	lize
l0 I	b @r	V	l aI z
li-	be-	ra-	lized
l0 I	b @r	V	l aI z d
li-	be-	ra-	ted
l0 I	b @r	eI	t V d
li-	be-	ra-	ti
l0 i:	b @r	Q	t i:
li-	be-	ra-	ting
l0 I	b @r	eI	t I N
li-	be-	ra-	tion
l0 I	b @r	eI	S V n
li-	be-	ra-	tor
l0 I	b @r	eI	t V r
li-	be-	ra-	tors
l0 I	b @r	eI	t V r z
li-	be-	ral
l0 I	b @r	V l
li-	be-	ral-	ly
l0 I	b @r	V	l i:
li-	be-	rals
l0 I	b @r	V l z
li-	be-	rate
l0 I	b @r	eI t
li-	be-	ri-	a
l0 aI	b I@	i:	V
li-	be-	ri-	an
l0 aI	b I@	i:	V n
li-	be-	ri-	ans
l0 aI	b I@	i:	V n z
li-	be-	ri-	a's
l0 aI	b I@	i:	V z
li-	bel
l0 aI	b V l
li-	beled
l0 aI	b V l d
li-	ber-	ta-	ri-	an
l0 I	b @r	t e@	i:	V n
li-	ber-	ta-	ri-	ans
l0 I	b @r	t e@	i:	V n z
li-	ber-	ties
l0 I	b @r	t i: z
li-	ber-	tine
l0 I	b @r	t i: n
li-	ber-	tines
l0 I	b @r	t i: n z
li-	ber-	ty
l0 I	b @r	t i:
li-	ber-	ty's
l0 I	b @r	t i: z
li-	bi-	do
l0 V	b i:	d @U
li-	by-	a
l0 I	b i:	V
li-	by-	an
l0 I	b i:	V n
li-	by-	ans
l0 I	b i:	V n z
li-	by-	a's
l0 I	b i:	V z
li-	cen-	ces
l0 aI	s V n	s V z
li-	cen-	see
l0 aI	s V n	s i:
li-	cen-	sees
l0 aI	s V n	s i: z
li-	cen-	ser
l0 aI	s V n	s @r
li-	cen-	ses
l0 aI	s V n	s V z
li-	cen-	sing
l0 aI	s V n	s I N
li-	cen-	sor
l0 aI	s V n	s @r
li-	cen-	sure
l0 aI	s V n	tS @r
li-	cen-	tious
l0 aI	s e n	tS V s
li-	cence
l0 aI	s V n s
li-	cense
l0 aI	s V n s
li-	censed
l0 aI	s V n s t
li-	chen
l0 aI	k V n
li-	chens
l0 aI	k V n z
li-	co-	rice
l0 I	k @r	I S
li-	da
l0 i:	d V
li-	do
l0 i:	d @U
li-	fer
l0 aI	f @r
li-	fers
l0 aI	f @r z
li-	fo
l0 i:	f @U
li-	ga-	ment
l0 I	g V	m V n t
li-	ga-	ments
l0 I	g V	m V n t s
li-	ga-	tion
l0 aI	g eI	S V n
li-	gand
l0 I	g V n d
li-	gands
l0 I	g V n d z
li-	gas
l0 aI	g V z
li-	gon
l0 I	g V n
li-	guo-	ri
l0 i:	g O@	i:
li-	ka-	ble
l0 aI	k V	b V l
li-	ke-	ning
l0 aI	k V	n I N
li-	kea-	ble
l0 aI	k V	b V l
li-	ken
l0 aI	k V n
li-	kened
l0 aI	k V n d
li-	kens
l0 aI	k V n z
li-	king
l0 aI	k I N
li-	kins
l0 I	k I n z
li-	kud
l0 I	k V d
li-	kud's
l0 I	k V d z
li-	la
l0 i:	l V
li-	lac
l0 aI	l { k
li-	lacs
l0 aI	l { k s
li-	lah
l0 I	l V
li-	li
l0 I	l i:
li-	li-	a
l0 i:	l i:	V
li-	li-	a-	na
l0 I	l i:	{	n V
li-	li-	an
l0 I	l i:	V n
li-	li-	ane
l0 V	l i:	{ n
li-	li-	as
l0 aI	l i:	V z
li-	lien-	thal
l0 I	l i: n	T V l
li-	lies
l0 I	l i: z
li-	lith
l0 I	l I T
li-	ly
l0 I	l i:
li-	ly-	an
l0 I	l i:	V n
li-	ly's
l0 I	l i: z
li-	ma
l0 aI	m V
li-	man
l0 aI	m V n
li-	mas
l0 aI	m V z
li-	me-	rick
l0 I	m @r	I k
li-	me-	ricks
l0 I	m @r	I k s
li-	me-	rick's
l0 I	m @r	I k s
li-	mi-	ta-	tion
l0 I	m I	t eI	S V n
li-	mi-	ta-	tions
l0 I	m I	t eI	S V n z
li-	mi-	ted
l0 I	m I	t I d
li-	mi-	ting
l0 I	m I	t I N
li-	mine
l0 I	m aI n
li-	ming
l0 aI	m I N
li-	mit
l0 I	m I t
li-	mit-	less
l0 I	m I t	l V s
li-	mits
l0 I	m I t s
li-	mo
l0 I	m @U
li-	mo-	ges
l0 V	m @U	dZ V z
li-	mo-	nite
l0 aI	m V	n aI t
li-	mon
l0 I	m V n
li-	mos
l0 I	m @U z
li-	mou-	sine
l0 I	m V	z i: n
li-	mou-	sines
l0 I	m V	z i: n z
li-	na
l0 i:	n V
li-	nage
l0 aI	n I dZ
li-	nares
l0 I	n @r z
li-	ne-	a-	ges
l0 I	n i:	I	dZ V z
li-	ne-	age
l0 I	n i:	V dZ
li-	ne-	al
l0 I	n i:	V l
li-	ne-	ar
l0 I	n i:	@r
li-	ne-	ar-	ly
l0 I	n i:	@r	l i:
li-	ne-	han
l0 I	n V	h { n
li-	nen
l0 I	n V n
li-	nens
l0 I	n V n z
li-	ner
l0 aI	n @r
li-	ner-	board
l0 aI	n @r	b O@ d
li-	ners
l0 aI	n @r z
li-	ner's
l0 aI	n @r z
li-	nette
l0 I	n e t
li-	ni
l0 i:	n i:
li-	ning
l0 aI	n I N
li-	nings
l0 aI	n I N z
li-	no
l0 i:	n @U
li-	no-	le-	um
l0 V	n @U	l i:	V m
li-	no-	type
l0 I	n @U	t aI p
li-	nus
l0 aI	n V s
li-	o-	nel
l0 aI	V	n V l
li-	o-	nize
l0 aI	V	n aI z
li-	o-	nized
l0 aI	V	n aI z d
li-	on
l0 aI	V n
li-	on-	heart
l0 aI	V n	h Q@ t
li-	ons
l0 aI	V n z
li-	on's
l0 aI	V n z
li-	ou
l0 i:	u:
li-	pa
l0 i:	p V
li-	pa-	ri
l0 i:	p Q@	i:
li-	pid
l0 aI	p I d
li-	pide
l0 V	p i: d
li-	pin-	ski
l0 V	p I n	s k i:
li-	po-	some
l0 I	p V	s @U m
li-	po-	somes
l0 I	p V	s @U m z
li-	po-	suc-	tion
l0 I	p @U	s V k	S V n
li-	pop-	ro-	tein
l0 I	p V p	r @U	t i: n
li-	pop-	ro-	teins
l0 I	p @U p	r @U	t i: n z
li-	que-	fac-	tion
l0 I k	w V	f { k	S V n
li-	que-	fied
l0 I k	w V	f aI d
li-	que-	fy
l0 I k	w V	f aI
li-	queur
l0 I	k @r
li-	queurs
l0 I	k @r z
li-	qui-	da-	ted
l0 I k	w I	d eI	t I d
li-	qui-	da-	ting
l0 I k	w I	d eI	t I N
li-	qui-	da-	tion
l0 I k	w I	d eI	S V n
li-	qui-	da-	tions
l0 I k	w I	d eI	S V n z
li-	qui-	da-	tor
l0 I k	w I	d eI	t @r
li-	qui-	da-	tors
l0 I k	w I	d eI	t @r z
li-	qui-	date
l0 I k	w I	d eI t
li-	qui-	dates
l0 I k	w I	d eI t s
li-	qui-	di-	ties
l0 I k	w I	d I	t i: z
li-	qui-	di-	ty
l0 I k	w I	d I	t i:
li-	quid
l0 I k	w I d
li-	quids
l0 I k	w I d z
li-	quor
l0 I	k @r
li-	quors
l0 I	k @r z
li-	ra
l0 I@	V
li-	ra's
l0 I@	V z
li-	re
l0 I@	V
li-	sa
l0 i:	s V
li-	sa-	bet
l0 I	s V	b e t
li-	sa-	beth
l0 I	s V	b e T
li-	sa's
l0 i:	s V z
li-	sette
l0 I	s e t
li-	sle
l0 aI	V l
li-	ste-	ner
l0 I	s V	n @r
li-	ste-	ners
l0 I	s V	n @r z
li-	ste-	ning
l0 I	s V	n I N
li-	stened
l0 I	s V n d
li-	stens
l0 I	s V n z
li-	ta
l0 i:	t V
li-	ta-	nies
l0 I	t V	n i: z
li-	ta-	ny
l0 I	t V	n i:
li-	te-	ra-	cy
l0 I	t @r	V	s i:
li-	te-	ra-	ry
l0 I	t @r	e@	i:
li-	te-	ra-	ti
l0 I	t @r	Q	t i:
li-	te-	ra-	ture
l0 I	t @r	V	tS @r
li-	te-	ral
l0 I	t @r	V l
li-	te-	ral-	ly
l0 I	t @r	V	l i:
li-	te-	rate
l0 I	t @r	V t
li-	tem
l0 aI	t e m
li-	ter
l0 i:	t @r
li-	ters
l0 i:	t @r z
li-	thi-	um
l0 I	T i:	V m
li-	thic
l0 I	T I k
li-	tho-	gra-	phic
l0 I	T V g	r {	f I k
li-	tho-	gra-	phy
l0 V	T Q g	r V	f i:
li-	tho-	graph
l0 I	T V g	r { f
li-	tho-	graphs
l0 I	T V g	r { f s
li-	tho-	trip-	ter
l0 I	T V t	r I p	t @r
li-	thu-	a-	ni-	a
l0 I	T V	w eI	n i:	V
li-	thu-	a-	ni-	an
l0 I	T V	w eI	n i:	V n
li-	thu-	a-	ni-	ans
l0 I	T V	w eI	n i:	V n z
li-	thu-	a-	ni-	a's
l0 I	T V	w eI	n i:	V z
li-	ti-	ga-	ted
l0 I	t I	g eI	t V d
li-	ti-	ga-	ting
l0 I	t I	g eI	t I N
li-	ti-	ga-	tion
l0 I	t I	g eI	S V n
li-	ti-	ga-	tions
l0 I	t I	g eI	S V n z
li-	ti-	ga-	tor
l0 I	t I	g eI	t @r
li-	ti-	ga-	tors
l0 I	t I	g eI	t @r z
li-	ti-	gant
l0 I	t I	g V n t
li-	ti-	gants
l0 I	t I	g V n t s
li-	ti-	gate
l0 I	t I	g eI t
li-	ti-	gious
l0 I	t I	dZ V s
li-	tur-	gi-	cal
l0 V	t @r	dZ I	k V l
li-	tur-	gy
l0 I	t @r	dZ i:
li-	va-	ble
l0 I	v V	b V l
li-	ve-	ry
l0 I	v @r	i:
li-	ve-	say
l0 I	v V	s eI
li-	ven
l0 aI	v V n
li-	vened
l0 aI	v V n d
li-	ver
l0 I	v @r
li-	ver-	more
l0 I	v @r	m O@
li-	ver-	pool
l0 I	v @r	p u: l
li-	ver-	wort
l0 I	v @r	w @r t
li-	ver-	worts
l0 I	v @r	w @r t s
li-	vers
l0 I	v @r z
li-	vi-	a
l0 I	v i:	V
li-	vi-	di-	ty
l0 I	v I	d I	t i:
li-	vid
l0 I	v I d
li-	ving
l0 I	v I N
li-	ving-	room
l0 I	v I N	r u: m
li-	ving-	ston
l0 I	v I N	s t V n
li-	ving-	stone
l0 I	v I N	s t @U n
li-	ving-	stone's
l0 I	v I N	s t @U n z
li-	ving-	ston's
l0 I	v I N	s t V n z
li-	vings
l0 I	v I N z
li-	vo-	nia
l0 I	v @U n	j V
li-	vor
l0 I	v O@
li-	za
l0 i:	z V
li-	za-	beth
l0 I	z V	b e T
li-	zard
l0 I	z @r d
li-	zards
l0 I	z @r d z
li-	zard's
l0 I	z @r d z
lian
l0 j Q n
liang
l0 j { N
lib
l0 I b
lib-	bey
l0 I	b i:
lib-	bing
l0 I	b I N
lib-	by
l0 I	b i:
lib-	ra
l0 i: b	r V
lib-	ra-	ri-	an
l0 aI b	r e@	i:	V n
lib-	ra-	ri-	ans
l0 aI b	r e@	i:	V n z
lib-	ra-	ries
l0 aI b	r e@	i: z
lib-	ra-	ry
l0 aI b	r e@	i:
lib-	ra-	ry's
l0 aI b	r e@	i: z
lib-	ra-	tion
l0 aI b	r eI	S V n
lib-	ret-	tist
l0 V b	r e	t V s t
lib-	ret-	to
l0 V b	r e	t @U
libbed
l0 I b d
libe-	ra-	li-	sm's
l0 I b	r V	l I	z V m z
libe-	ra-	li-	za-	tion
l0 I b	r V	l I	z eI	S V n
lic-	ke-	ty
l0 I	k V	t i:
lic-	ker
l0 I	k @r
lic-	king
l0 I	k I N
lice
l0 aI s
lich
l0 I tS
lich-	ten-	berg
l0 I k	t V n	b @r g
lich-	ten-	stein
l0 I k	t V n	s t i: n
lich-	ter
l0 I k	t @r
licht
l0 I k t
lick
l0 I k
licked
l0 I k t
licks
l0 I k s
lid
l0 I d
lid-	dell
l0 I	d V l
lid-	dle
l0 I	d V l
lid-	dy
l0 I	d i:
lid-	dy's
l0 I	d i: z
lid-	ger-	wood
l0 I	dZ @r	w U d
lide
l0 aI d
lids
l0 I d z
lie
l0 aI
lie-	ber-	man
l0 i:	b @r	m V n
lie-	ber-	mann
l0 i:	b @r	m V n
lie-	ber-	man's
l0 i:	b @r	m V n z
lie-	big
l0 i:	b I g
lie-	bo-	witz
l0 i:	b V	w I t s
lie-	der
l0 i:	d @r
lie-	der-	man
l0 i:	d @r	m V n
lie-	der-	man's
l0 i:	d @r	m V n z
lie-	fer
l0 i:	f @r
lieb-	man
l0 i: b	m V n
liech-	ten-	stein
l0 I k	t V n	s t aI n
lied
l0 aI d
lief
l0 i: f
liege
l0 i: dZ
lien
l0 i: n
lien-	hard
l0 i: n	h Q@ d
liens
l0 i: n z
lies
l0 aI z
lieu
l0 u:
lieu-	te-	nant
l0 u:	t e	n V n t
lieu-	te-	nants
l0 u:	t e	n V n t s
lif-	ted
l0 I f	t V d
lif-	ter
l0 I f	t @r
lif-	ters
l0 I f	t @r z
lif-	ting
l0 I f	t I N
lif-	toff
l0 I f	t O: f
lif-	ton
l0 I f	t V n
life
l0 aI f
life-	boat
l0 aI f	b @U t
life-	boats
l0 aI f	b @U t s
life-	guard
l0 aI f	g Q@ d
life-	guards
l0 aI f	g Q@ d z
life-	less
l0 aI f	l V s
life-	like
l0 aI f	l aI k
life-	line
l0 aI f	l aI n
life-	lines
l0 aI f	l aI n z
life-	long
l0 aI f	l O: N
life-	sa-	ver
l0 aI f	s eI	v @r
life-	sa-	vers
l0 aI f	s eI	v @r z
life-	sa-	ving
l0 aI f	s eI	v I N
life-	span
l0 aI f	s p { n
life-	style
l0 aI f	s t aI l
life-	styles
l0 aI f	s t aI l z
life-	time
l0 aI f	t aI m
life-	times
l0 aI f	t aI m z
life-	time's
l0 aI f	t aI m z
lifeb-	lood
l0 aI f	b l V d
life's
l0 aI f s
lift
l0 I f t
lift-	off
l0 I f	t O: f
lifts
l0 I f t s
lig-	get
l0 I	g e t
lig-	gett
l0 I	g e t
lig-	gett's
l0 I	g e t s
lig-	nin
l0 I g	n I n
lig-	nite
l0 I g	n aI t
ligh-	te-	ning
l0 aI	t V	n I N
ligh-	ted
l0 aI	t V d
ligh-	ten
l0 aI	t V n
ligh-	tened
l0 aI	t V n d
ligh-	ter
l0 aI	t @r
ligh-	ters
l0 aI	t @r z
ligh-	test
l0 aI	t V s t
ligh-	ting
l0 aI	t I N
ligh-	ting's
l0 aI	t I N z
ligh-	ty
l0 aI	t i:
light
l0 aI t
light-	bulb
l0 aI t	b V l b
light-	bulbs
l0 aI t	b V l b z
light-	fast
l0 aI t	f { s t
light-	fast-	ness
l0 aI t	f { s	t n V s
light-	foot
l0 aI t	f U t
light-	hea-	ded
l0 aI t	h e	d V d
light-	hea-	ded-	ness
l0 aI t	h e	d V d	n V s
light-	hear-	ted
l0 aI t	h Q@	t V d
light-	hou-	ses
l0 aI t	h aU	s V z
light-	house
l0 aI t	h aU s
light-	ly
l0 aI t	l i:
light-	ness
l0 aI t	n V s
light-	ning
l0 aI t	n I N
light-	nings
l0 aI t	n I N z
light-	ship
l0 aI t	S I p
light-	ships
l0 aI t	S I p s
light-	weight
l0 aI t	w eI t
lights
l0 aI t s
light's
l0 aI t s
like
l0 aI k
like-	li-	er
l0 aI k	l i:	@r
like-	li-	est
l0 aI k	l i:	V s t
like-	li-	hood
l0 aI k	l i:	h U d
like-	ly
l0 aI k	l i:
like-	nes-	ses
l0 aI k	n V	s V z
like-	ness
l0 aI k	n V s
like-	wise
l0 aI k	w aI z
liked
l0 aI k t
likes
l0 aI k s
lil
l0 I l
lil-	la
l0 I	l V
lil-	li
l0 I	l i:
lil-	li-	an
l0 I	l i:	V n
lil-	li-	an's
l0 I	l i:	V n z
lil-	li-	pu-	tian
l0 I	l I p	j u:	S V n
lil-	lie
l0 I	l i:
lil-	lis
l0 I	l I s
lil-	lo
l0 I	l @U
lil-	ly
l0 I	l i:
lil-	ly's
l0 I	l i: z
lile
l0 aI l
liles
l0 aI l z
lill
l0 I l
lille
l0 I l
lilt
l0 I l t
lim
l0 I m
lim-	baugh
l0 I m	b O:
lim-	baugh's
l0 I m	b O: z
lim-	ber
l0 I m	b @r
lim-	bers
l0 I m	b @r z
lim-	bert
l0 I m	b @r t
lim-	bless
l0 I m	l V s
lim-	bo
l0 I m	b @U
lim-	burg
l0 I m	b @r g
lim-	mer
l0 I	m @r
lim-	no-	lo-	gy
l0 I m	n Q	l V	dZ i:
lim-	pets
l0 I m	p V t s
lim-	ping
l0 I m	p I N
limb
l0 I m
limbed
l0 I m d
limbs
l0 I m z
lime
l0 aI m
lime-	house
l0 aI m	h aU s
lime-	light
l0 aI m	l aI t
lime-	stone
l0 aI m	s t @U n
lime-	stones
l0 aI m	s t @U n z
limes
l0 aI m z
limp
l0 I m p
limped
l0 I m p t
limps
l0 I m p s
lin
l0 I n
lin-	do
l0 I n	d @U
lin-	don
l0 I n	d V n
lin-	dy
l0 I n	d i:
lin-	ge-	rie
l0 Q n	Z @r	eI
lin-	ge-	ring
l0 I N	g @r	I N
lin-	ger
l0 I N	g @r
lin-	gered
l0 I N	g @r d
lin-	gers
l0 I N	g @r z
lin-	gle
l0 I N	g V l
lin-	go
l0 I N	g @U
lin-	gua
l0 I N	g w V
lin-	gui-	ne
l0 I N	g w i:	n i:
lin-	guis-	tic
l0 I N	g w I s	t I k
lin-	guis-	tical-	ly
l0 I N	g w I s	t I k	l i:
lin-	guis-	tics
l0 I N	g w I s	t I k s
lin-	guist
l0 I N	g w I s t
lin-	guists
l0 I N	g w I s t s
lin-	ka-	ges
l0 I N	k V	dZ V z
lin-	kage
l0 I N	k V dZ
lin-	ker
l0 I N	k @r
lin-	king
l0 I N	k I N
lin-	kup
l0 I N	k V p
lin-	kups
l0 I N	k V p s
lin-	ne-	a
l0 I	n i:	V
lin-	nell
l0 I	n V l
lin-	net
l0 I	n I t
lin-	ney
l0 I	n i:
lin-	seed
l0 I n	s i: d
lin-	sey
l0 I n	z i:
lin-	skey
l0 I n	s k i:
lin-	son
l0 I n	s V n
lin-	tel
l0 I n	t V l
lin-	ters
l0 I n	t @r z
lin-	ton
l0 I n	t V n
lin-	ville
l0 i: n	v I l
lin-	wood
l0 I n	w U d
lin-	zer
l0 I n	z @r
lin-	zy
l0 I n	z i:
lind-	ner's
l0 I n	d n @r z
lind-	quist
l0 I n	d k w I s t
lind-	say
l0 I n	d z i:
lind-	sey
l0 I n	d z i:
lind-	sey's
l0 I n	d z i: z
lind-	sley
l0 I n	d s l i:
)"
R"(lind-	strom
l0 I n	d s t r V m
line
l0 aI n
line-	bac-	ker
l0 aI n	b {	k @r
line-	bac-	kers
l0 aI n	b {	k @r z
line-	man
l0 aI n	m V n
line-	men
l0 aI n	m V n
line-	up
l0 aI	n V p
line-	ups
l0 aI	n V p s
lined
l0 aI n d
lines
l0 aI n z
line's
l0 aI n z
ling
l0 I N
link
l0 I N k
linked
l0 I N k t
links
l0 I N k s
link's
l0 I N k s
linn
l0 I n
linne
l0 I n
linne-	man
l0 I n	m V n
lins
l0 I n z
lint
l0 I n t
linz
l0 I n z
lip
l0 I p
lip-	kin
l0 I p	k I n
lip-	man
l0 I p	m V n
lip-	pens
l0 I	p V n z
lip-	per
l0 I	p @r
lip-	per's
l0 I	p @r z
lip-	pi
l0 I	p i:
lip-	pin-	cott
l0 I	p I n	k V t
lip-	po
l0 I	p @U
lip-	pold
l0 I	p @U l d
lip-	py
l0 I	p i:
lip-	schitz
l0 I p	S I t s
lip-	sey
l0 I p	s i:
lip-	ski
l0 I p	s k i:
lip-	son
l0 I p	s V n
lip-	stick
l0 I p	s t I k
lip-	sticks
l0 I p	s t I k s
lip-	ton
l0 I p	t V n
lip-	ton's
l0 I p	t V n z
lipe
l0 aI p
lipp
l0 I p
lipp-	mann
l0 I p	m V n
lippe
l0 I p
lipped
l0 I p t
lipps
l0 I p s
lips
l0 I p s
lips-	comb
l0 I p	s k V m
lis
l0 I s
li's
l0 i: z
lis-	beth
l0 I s	b e T
lis-	bon
l0 I z	b V n
)"