R"(hit-	ting
h I	t I N
hit-	tite
h I	t aI t
hitch
h I tS
hitch-	cock
h I tS	k Q k
hitch-	cock's
h I tS	k Q k s
hitch-	hi-	king
h I tS	h aI	k I N
hitch-	hike
h I tS	h aI k
hitched
h I tS t
hite
h aI t
hits
h I t s
hitt
h I t
hive
h aI v
hives
h aI v z
hix-	son
h I k	s V n
hiz-	bol-	lah
h I z	b @U	l V
hmong
m O: N
ho
h @U
ho-	ban
h @U	b V n
ho-	bart
h @U	b Q@ t
ho-	bo
h @U	b @U
ho-	bo-	ken
h @U	b @U	k V n
ho-	boes
h @U	b @U z
ho-	cus
h @U	k V s
ho-	ey
h @U	i:
ho-	fer
h @U	f @r
ho-	gan
h @U	g Q n
ho-	gans
h @U	g Q n z
ho-	gan's
h @U	g Q n z
ho-	garth
h @U	g Q@ T
ho-	ge-	land
h Q	g V	l V n d
ho-	gen
h Q	g V n
ho-	gle
h @U	g V l
ho-	kan-	son
h Q	k V n	s V n
ho-	key
h @U	k i:
ho-	kum
h @U	k V m
ho-	li-	day
h Q	l I	d eI
ho-	li-	days
h Q	l I	d eI z
ho-	li-	day's
h Q	l I	d eI z
ho-	li-	er
h @U	l i:	@r
ho-	li-	est
h @U	l i:	V s t
ho-	li-	ness
h @U	l i:	n V s
ho-	ling
h @U	l I N
ho-	lis-	tic
h @U	l I s	t I k
ho-	lo-	caust
h Q	l V	k O: s t
ho-	lo-	gra-	phic
h Q	l V g	r {	f I k
ho-	lo-	gram
h Q	l V g	r { m
ho-	lo-	grams
h Q	l V g	r { m z
ho-	lub
h @U	l V b
ho-	ly
h @U	l i:
ho-	ly-	oke
h @U	l i:	@U k
ho-	mage
Q	m V dZ
ho-	mans
h @U	m V n z
ho-	me-	o-	pa-	thic
h @U	m i:	@U	p {	T I k
ho-	me-	o-	pa-	thy
h @U	m i:	@U	p {	T i:
ho-	me-	os-	ta-	sis
h @U	m i:	@U s	t eI	s I s
ho-	me-	os-	ta-	tic
h @U	m i:	@U s	t {	t I k
ho-	me-	ric
h @U	m e@	I k
ho-	mer
h @U	m @r
ho-	mers
h @U	m @r z
ho-	mer's
h @U	m @r z
ho-	mey
h @U	m i:
ho-	mi-	ci-	dal
h Q	m I	s aI	d V l
ho-	mi-	cide
h Q	m I	s aI d
ho-	mi-	cides
h Q	m I	s aI d z
ho-	mi-	le-	tic
h Q	m I	l e	t I k
ho-	mi-	lies
h @U	m I	l i: z
ho-	mi-	ly
h Q	m I	l i:
ho-	mi-	nem
h Q	m I	n e m
ho-	mi-	nid
h Q	m I	n I d
ho-	mi-	ny
h Q	m I	n i:
ho-	ming
h @U	m I N
ho-	mo
h @U	m @U
ho-	mo-	ge-	ne-	i-	ty
h Q	m V	dZ V	n i:	V	t i:
ho-	mo-	ge-	ne-	ous
h @U	m V	dZ i:	n i:	V s
ho-	mo-	ge-	ni-	za-	tion
h @U	m Q	dZ V	n V	z eI	S V n
ho-	mo-	ge-	nize
h @U	m Q	dZ V	n aI z
ho-	mo-	ge-	nized
h @U	m Q	dZ V	n aI z d
ho-	mo-	ge-	nous
h V	m Q	dZ V	n V s
ho-	mo-	ge-	ny
h @U	m Q	dZ V	n i:
ho-	mo-	pho-	bi-	a
h @U	m V	f @U	b i:	V
ho-	mo-	pho-	bic
h @U	m V	f @U	b I k
ho-	mo-	se-	xu-	a-	li-	ty
h @U	m @U	s e k	S V	w {	l V	t i:
ho-	mo-	se-	xu-	al
h @U	m @U	s e k	S V	w V l
ho-	mo-	se-	xu-	als
h @U	m @U	s e k	S V	w V l z
ho-	mo-	spo-	rous
h V	m Q s	p @r	V s
ho-	mo-	zy-	gote
h @U	m @U	z aI	g @U t
ho-	mo-	zy-	gous
h @U	m @U	z aI	g V s
ho-	na-	ker
h Q	n V	k @r
ho-	nan
h @U	n V n
ho-	ne-	a
h Q	n i:	V
ho-	nec-	ker
h @U	n e	k @r
ho-	nec-	ker's
h @U	n e	k @r z
ho-	ner
h @U	n @r
ho-	nes-	ty
Q	n V s	t i:
ho-	nest
Q	n V s t
ho-	nest-	ly
Q	n V s	t l i:
ho-	ney
h V	n i:
ho-	ney-	bee
h V	n i:	b i:
ho-	ney-	bees
h V	n i:	b i: z
ho-	ney-	comb
h V	n i:	k @U m
ho-	ney-	dew
h V	n i:	d u:
ho-	ney-	man
h Q	n i:	m V n
ho-	ney-	moo-	ner
h V	n i:	m u:	n @r
ho-	ney-	moo-	ners
h V	n i:	m u:	n @r z
ho-	ney-	moon
h V	n i:	m u: n
ho-	ney-	mooned
h V	n i:	m u: n d
ho-	ney-	moons
h V	n i:	m u: n z
ho-	ney-	suc-	kle
h V	n i:	s V	k V l
ho-	ney-	suc-	kles
h V	n i:	s V	k V l z
ho-	ney-	well
h V	n i:	w e l
ho-	ney-	well's
h V	n i:	w e l z
ho-	neys
h V	n i: z
ho-	nig
h Q	n I g
ho-	ning
h @U	n I N
ho-	no-	lu-	lu
h Q	n V	l u:	l u:
ho-	no-	lu-	lu's
h Q	n V	l u:	l u: z
ho-	no-	ra
O:	n O@	V
ho-	no-	ra-	ble
Q	n @r	V	b V l
ho-	no-	ra-	ri-	a
Q	n @r	e@	i:	V
ho-	no-	ra-	ri-	um
Q	n @r	e@	i:	V m
ho-	no-	ra-	ri-	ums
Q	n @r	e@	i:	V m z
ho-	no-	ra-	ry
Q	n @r	e@	i:
ho-	no-	rab-	ly
Q	n @r	V b	l i:
ho-	no-	ree
Q	n @r	i:
ho-	no-	rees
Q	n @r	i: z
ho-	no-	ri-	a
Q	n @r	i:	V
ho-	no-	ri-	fic
Q	n @r	I	f I k
ho-	no-	ring
Q	n @r	I N
ho-	nor
Q	n @r
ho-	nore
Q	n @r
ho-	nored
Q	n @r d
ho-	nors
Q	n @r z
ho-	nor's
Q	n @r z
ho-	pi
h @U	p i:
ho-	ping
h @U	p I N
ho-	ra
h O@	V
ho-	ra-	ce's
h O@	V	s V z
ho-	ra-	ci-	o
h O@	eI	s i:	@U
ho-	ra-	ti-	o's
h O@	eI	S i:	@U z
ho-	ra-	tia
h O@	Q	S V
ho-	ra-	tian
h @r	eI	S V n
ho-	ra-	tio
h @r	eI	S @U
ho-	ra-	tius
h O@	eI	S V s
ho-	race
h O@	V s
ho-	ran
h O@	V n
ho-	ren-	stein
h O@	V n	s t aI n
ho-	ri-	zon
h @r	aI	z V n
ho-	ri-	zon-	tal
h O@	I	z Q n	t V l
ho-	ri-	zon-	tal-	ly
h O@	I	z Q n	t V	l i:
ho-	ri-	zons
h @r	aI	z V n z
ho-	ri-	zon's
h @r	aI	z V n z
ho-	ro-	scope
h O@	V s	k @U p
ho-	ro-	scopes
h O@	V s	k @U p s
ho-	ro-	witz
h O@	@U	I t s
ho-	rus
h O@	V s
ho-	se-	a
h @U	z i:	V
ho-	se-	a's
h @U	z i:	V z
ho-	ses
h @U	z V z
ho-	sey
h @U	z i:
ho-	sie-	ry
h @U	Z @r	i:
ho-	sing
h @U	z I N
ho-	te-	lier
h @U	t e l	j @r
ho-	te-	liers
h @U	t e l	j @r z
ho-	tel
h @U	t e l
ho-	tels
h @U	t e l z
ho-	tel's
h @U	t e l z
ho-	ur
aU	@r
ho-	ur-	glass
aU	@r g	l { s
ho-	ur's
aU	@r z
ho-	ve-	ring
h V	v @r	I N
ho-	vel
h V	v V l
ho-	vels
h V	v V l z
ho-	ven
h @U	v V n
ho-	ver
h V	v @r
ho-	ver-	craft
h V	v @r k	r { f t
ho-	vered
h V	v @r d
ho-	vers
h V	v @r z
ho-	vey
h @U	v i:
ho-	ving
h @U	v I N
ho-	ward
h aU	@r d
ho-	ward's
h aU	@r d z
ho-	warth
h aU	Q@ T
ho-	well
h aU	V l
ho-	wells
h aU	V l z
ho-	well's
h aU	V l z
ho-	wey
h aU	i:
ho-	wi-	son
h aU	I	s V n
ho-	wie
h aU	i:
ho-	wie's
h aU	i: z
ho-	wit-	zer
h aU	I t	s @r
ho-	wit-	zers
h aU	I t	s @r z
ho-	xie
h Q k	s i:
hoa-	gie
h @U	g i:
hoa-	gy
h @U	g i:
hoa-	ry
h O@	i:
hoa-	xes
h @U k	s V z
hoag
h @U g
hoag-	land
h @U g	l V n d
hoang
h @U N
hoar
h O@
hoar-	ded
h O@	d V d
hoar-	ding
h O@	d I N
hoard
h O@ d
hoards
h O@ d z
hoare
h O@
hoarse
h O@ s
hoarse-	ness
h O@ s	n V s
hoax
h @U k s
hob
h Q b
hob-	b-	ling
h Q	b V	l I N
hob-	bes
h Q	b i: z
hob-	bie
h Q	b i:
hob-	bies
h Q	b i: z
hob-	bing
h Q	b I N
hob-	ble
h Q	b V l
hob-	bled
h Q	b V l d
hob-	bles
h Q	b V l z
hob-	by
h Q	b i:
hob-	by-	ist
h Q	b i:	I s t
hob-	by-	ists
h Q	b i:	I s t s
hob-	day
h Q b	d eI
hob-	good
h Q b	g U d
hob-	nail
h Q b	n eI l
hob-	nob
h Q b	n Q b
hob-	nob-	bing
h Q b	n Q	b I N
hob-	son
h Q b	s V n
hob-	son's
h Q b	s V n z
hobbs
h Q b z
hobs
h Q b z
hoc
h Q k
hoc-	ka-	day
h Q	k V	d eI
hoc-	ker
h Q	k @r
hoc-	key
h Q	k i:
hoc-	key's
h Q	k i: z
hoc-	king
h Q	k I N
hoch
h Q k
hoch-	man
h Q k	m V n
hock
h Q k
hock-	ley
h Q k	l i:
hock-	ney
h Q k	n i:
hock-	ney's
h Q k	n i: z
hod-	der
h Q	d @r
hod-	ding
h Q	d I N
hod-	gen
h Q	dZ V n
hod-	ges
h Q	dZ V z
hod-	ge's
h Q	dZ V z
hodg-	kin
h Q dZ	k I n
hodg-	kin-	son
h Q dZ	k I n	s V n
hodg-	kin's
h Q dZ	k I n z
hodg-	son
h Q dZ	s V n
hodge
h Q dZ
hodge-	podge
h Q dZ	p Q dZ
hoe
h @U
hoe-	down
h @U	d aU n
hoe-	ing
h @U	I N
hoe-	ne
h Q	i: n
hoeg
h @U g
hoehne
h @U n
hoek
h @U k
hoes
h @U z
hof-	fa
h O:	f V
hof-	farth
h O:	f Q@ T
hof-	fa's
h O:	f V z
hof-	fer
h Q	f @r
hof-	fert
h O:	f @r t
hof-	mann
h Q f	m V n
hof-	stet-	ter
h Q f	s t e	t @r
hoff
h O: f
hoff-	man
h O: f	m V n
hoff-	mann
h O: f	m V n
hoff-	man's
h O: f	m V n z
hoff-	meis-	ter
h O: f	m aI s	t @r
hog
h Q g
hog-	ging
h O:	g I N
hog-	nose
h Q g	n @U z
hog-	wash
h Q g	w Q S
hogg
h Q g
hogs
h Q g z
hogue
h @U g
hoh
h @U
hoi
h OI
hoi-	sing-	ton
h OI	z I N	t V n
hois-	ted
h OI s	t V d
hois-	ting
h OI s	t I N
hoist
h OI s t
hoists
h OI s t s
hoit
h OI t
hok-	kai-	do
h @U	k aI	d @U
hoke
h @U k
hol-	bein
h @U l	b aI n
hol-	berg
h @U l	b @r g
hol-	brook
h @U l	b r U k
hol-	brooke
h @U l	b r U k
hol-	comb
h @U l	k V m
hol-	combe
h @U l	k V m
hol-	den
h @U l	d V n
hol-	den's
h @U l	d V n z
hol-	der
h @U l	d @r
hol-	der-	ness
h @U l	d @r	n V s
hol-	ders
h @U l	d @r z
hol-	der's
h @U l	d @r z
hol-	ding
h @U l	d I N
hol-	dings
h @U l	d I N z
hol-	ding's
h @U l	d I N z
hol-	do-	ver
h @U l	d @U	v @r
hol-	do-	vers
h @U l	d @U	v @r z
hol-	dout
h @U l	d aU t
hol-	douts
h @U l	d aU t s
hol-	dup
h @U l	d V p
hol-	dups
h @U l	d V p s
hol-	gate
h @U l	g eI t
hol-	guin
h @U l	g I n
hol-	la-	day
h Q	l I	d eI
hol-	lan-	der
h Q	l V n	d @r
hol-	lan-	ders
h Q	l V n	d @r z
hol-	land
h Q	l V n d
hol-	lands
h Q	l V n d z
hol-	land's
h Q	l V n d z
hol-	le-	ran
h Q	l @r	V n
hol-	le-	ring
h Q	l @r	I N
hol-	len-	beck
h Q	l V n	b e k
hol-	len-	berg
h Q	l V n	b @r g
hol-	ler
h Q	l @r
hol-	lered
h Q	l @r d
hol-	lers
h Q	l @r z
hol-	ley
h Q	l i:
hol-	li-	day
h Q	l I	d eI
hol-	li-	day's
h Q	l I	d eI z
hol-	li-	ston
h Q	l I s	t V n
hol-	lie
h Q	l i:
hol-	lies
h Q	l i: z
hol-	lin
h Q	l I n
hol-	lin-	ger
h Q	l I	N @r
hol-	ling-	shead
h Q	l I N	z h e d
hol-	ling-	sworth
h Q	l I N	z w @r T
hol-	lins
h Q	l I n z
hol-	lis
h Q	l I s
hol-	lis-	ter
h Q	l I s	t @r
hol-	lo
h Q	l @U
hol-	lo-	man
h Q	l @U	m V n
hol-	lo-	way
h Q	l @U	w eI
hol-	lo-	wing
h Q	l @U	I N
hol-	low
h Q	l @U
hol-	lowed
h Q	l @U d
hol-	lows
h Q	l @U z
hol-	ly
h Q	l i:
hol-	ly-	hock
h Q	l i:	h Q k
hol-	ly-	hocks
h Q	l i:	h Q k s
hol-	ly-	wood
h Q	l i:	w U d
hol-	ly-	wood's
h Q	l i:	w U d z
hol-	ly's
h Q	l i: z
hol-	man
h Q l	m V n
hol-	men
h Q l	m e n
hol-	mi-	um
h @U l	m i:	V m
hol-	ton
h @U l	t V n
hol-	torf
h @U l	t @r f
hold
h @U l d
hold-	fast
h @U l	f { s t
hold-	man
h @U l	d m V n
hold-	up
h @U l	d V p
holds
h @U l d z
hole
h @U l
hole-	man
h @U l	m V n
holed
h @U l d
holes
h @U l z
holl
h Q l
holle
h Q l
holm
h @U m
holme
h @U l m
holmes
h @U m z
hols-	tein
h @U l	s t i: n
hols-	ter
h @U l	s t @r
hols-	worth
h @U l	s w @r T
holst
h @U l s t
holt
h @U l t
holt-	z's
h @U l	t s V z
holts
h @U l t s
holt's
h @U l t s
holtz
h @U l t s
holz-	man
h @U l	z m V n
hom
h Q m
hom-	bre
h Q m	b r V
hom-	burg
h Q m	b @r g
hom-	mel
h Q	m V l
home
h @U m
home-	bound
h @U m	b aU n d
home-	boys
h @U m	b OI z
home-	buil-	der
h @U m	b I l	d @r
home-	buil-	ders
h @U m	b I l	d @r z
home-	buil-	ding
h @U m	b I l	d I N
home-	buy-	er
h @U m	b aI	@r
home-	buy-	ers
h @U m	b aI	@r z
home-	co-	ming
h @U m	k V	m I N
home-	grown
h @U m	g r @U n
home-	land
h @U m	l { n d
home-	lands
h @U m	l { n d z
home-	land's
h @U m	l { n d z
home-	less
h @U m	l V s
home-	less-	ness
h @U m	l V s	n V s
home-	like
h @U m	l aI k
home-	ly
h @U m	l i:
home-	ma-	ker
h @U m	m eI	k @r
home-	ma-	kers
h @U m	m eI	k @r z
home-	ma-	king
h @U m	m eI	k I N
home-	made
h @U m	m eI d
home-	ow-	ner
h @U	m @U	n @r
home-	ow-	ner-	ship
h @U	m @U	n @r	S I p
home-	ow-	ners
h @U	m @U	n @r z
home-	por-	ting
h @U m	p O@	t I N
home-	run
h @U m	r V n
home-	school
h @U m	s k u: l
home-	sick
h @U m	s I k
home-	sick-	ness
h @U m	s I k	n V s
home-	stea-	ded
h @U m	s t e	d V d
home-	stea-	der
h @U m	s t e	d @r
home-	stea-	ders
h @U m	s t e	d @r z
home-	stead
h @U m	s t e d
home-	stead's
h @U m	s t e d z
home-	stretch
h @U m	s t r e tS
home-	town
h @U m	t aU n
home-	ward
h @U m	w @r d
home-	wood
h @U m	w U d
home-	wor-	ker
h @U m	w @r	k @r
home-	wor-	kers
h @U m	w @r	k @r z
home-	work
h @U m	w @r k
homed
h @U m d
homes
h @U m z
home's
h @U m z
homes-	pun
h @U m	s p V n
homme
h Q m
hommes
h Q m z
homs
h Q m z
hon
h Q n
hon-	cho
h O: n	tS @U
hon-	da
h O: n	d V
hon-	das
h Q n	d V s
hon-	da's
h Q n	d V z
hon-	do
h Q n	d @U
hon-	du-	ran
h Q n	d U@	V n
hon-	du-	rans
h Q n	d U@	V n z
hon-	du-	ras
h Q n	d U@	V s
hon-	king
h O: N	k I N
hon-	ky
h O: N	k i:
hon-	shu
h Q n	S u:
hone
h @U n
honed
h @U n d
hong
h O: N
hong-	kong
h O: N	k O: N
honk
h Q N k
hons
h Q n z
hoo
h u:
hoo-	ded
h U	d V d
hoo-	dlum
h U d	l V m
hoo-	dlums
h u: d	l V m z
hoo-	ey
h u:	i:
hoo-	ker
h U	k @r
hoo-	kers
h U	k @r z
hoo-	ker's
h U	k @r z
hoo-	king
h U	k I N
hoo-	kup
h U	k V p
hoo-	kups
h U	k V p s
hoo-	ky
h U	k i:
hoo-	ley
h u:	l i:
hoo-	li-	ga-	ni-	sm
h u:	l I	g V	n I	z V m
hoo-	li-	gan
h u:	l I	g V n
hoo-	li-	gans
h u:	l I	g V n z
hoo-	li-	han
h u:	l I	h { n
hoo-	per
h u:	p @r
hoo-	per-	man
h u:	p @r	m V n
hoo-	poe
h u:	p u:
hoo-	ray
h U@	eI
hoo-	sier
h u:	Z @r
hoo-	siers
h u: z	j @r z
hoo-	ted
h u:	t V d
hoo-	ter
h u:	t @r
hoo-	ters
h u:	t @r z
hoo-	ton
h u:	t V n
hoo-	ven
h u:	v V n
hoo-	ver
h u:	v @r
hoo-	ver's
h u:	v @r z
hooch
h u: tS
hood
h U d
hood-	wink
h U d	w I N k
hood-	winked
h U d	w I N k t
hoods
h U d z
hoof
h u: f
hoofed
h U f t
hoofs
h U f s
hooge
h u: dZ
hook
h U k
hook-	up
h U	k V p
hook-	worm
h U k	w @r m
hooke
h U k
hooked
h U k t
hooks
h U k s
hook's
h U k s
hoon
h u: n
hoop
h u: p
hoop-	la
h u: p	l Q
hoopes
h u: p s
hoops
h u: p s
hoos
h u: z
hoose
h u: s
hoot
h u: t
hoot-	man
h u: t	m V n
hoots
h u: t s
hooves
h U v z
hop
h Q p
hop-	fin-	ger
h Q p	f I	N @r
hop-	kin-	son
h Q p	k I n	s V n
hop-	kin-	ton
h Q p	k I n	t V n
hop-	kins
h Q p	k I n z
hop-	per
h Q	p @r
hop-	pers
h Q	p @r z
hop-	per's
h Q	p @r z
hop-	ping
h Q	p I N
hop-	ple
h Q	p V l
hop-	py
h O:	p i:
hop-	scotch
h Q p	s k Q tS
hop-	wood
h Q p	w U d
hope
h @U p
hope-	ful
h @U p	f V l
hope-	ful-	ly
h @U p	f V	l i:
hope-	ful-	ness
h @U p	f V l	n V s
hope-	fuls
h @U p	f V l z
hope-	less
h @U p	l V s
hope-	less-	ly
h @U p	l V s	l i:
hope-	less-	ness
h @U p	l V s	n V s
hope-	well
h @U p	w e l
hoped
h @U p t
hopes
h @U p s
hope's
h @U p s
hoppe
h Q p
hopped
h Q p t
hops
h Q p s
hor-	gan
h O@	g V n
hor-	key
h O@	k i:
hor-	la-	cher
h O@	l V	k @r
hor-	mel
h O@	m e l
hor-	mo-	nal
h O@	m @U	n V l
hor-	mone
h O@	m @U n
hor-	mones
h O@	m @U n z
hor-	muz
h O@	m u: z
hor-	nell
h O@	n e l
hor-	ner
h O@	n @r
hor-	net
h O@	n V t
hor-	nets
h O@	n V t s
hor-	net's
h O@	n V t s
hor-	ney
h O@	n i:
hor-	nick
h O@	n I k
hor-	ning
h O@	n I N
hor-	ny
h O@	n i:
hor-	ren-	dous
h O@	e n	d V s
hor-	ren-	dous-	ly
h O@	e n	d V s	l i:
hor-	ri-	ble
h O@	I	b V l
hor-	ri-	fic
h O@	I	f I k
hor-	ri-	fied
h O@	I	f aI d
hor-	ri-	fy
h O@	I	f aI
hor-	ri-	fy-	ing
h O@	I	f aI	I N
hor-	rib-	ly
h O@	I b	l i:
hor-	rid
h O@	I d
hor-	rocks
h O@	V k s
hor-	ror
h O@	@r
hor-	rors
h O@	@r z
hor-	ses
h O@	s V z
hor-	se's
h O@	s V z
hor-	sey
h O@	s i:
hor-	sing
h O@	s I N
hor-	ta
h O@	t V
hor-	ten
h O@	t V n
hor-	ter
h O@	t @r
hor-	ti-	cul-	tu-	ral
h O@	t I	k V l	tS @r	V l
hor-	ti-	cul-	tu-	rist
h O@	t I	k V l	tS @r	I s t
hor-	ti-	cul-	ture
h O@	t I	k V l	tS @r
hor-	ton
h O@	t V n
hor-	vitz
h O@	v I t s
hor-	wath
h O@	w O: T
hor-	witz
h O@	w I t s
hord
h O@ d
horde
h O@ d
hordes
h O@ d z
hore-	hound
h Q@	h aU n d
horn
h O@ n
horn-	beak
h O@ n	b V k
horn-	beck
h O@ n	b e k
horn-	bill
h O@ n	b I l
horn-	bills
h O@ n	b I l z
horn-	blende
h O@ n	b l e n d
horn-	blo-	wer
h O@ n	b l @U	@r
horn-	book
h O@ n	b U k
horn-	brook
h O@ n	b r U k
horn-	by
h O@ n	b i:
horn-	less
h O@ n	l V s
horn-	like
h O@ n	l aI k
horn-	stein
h O@ n	s t aI n
horne
h O@ n
horned
h O@ n d
horns
h O@ n z
horn's
h O@ n z
horns-	by
h O@ n	z b i:
hors
h O@ z
hors-	ham
h O@	S V m
hors-	ham's
h O@	S V m z
horse
h O@ s
horse-	back
h O@ s	b { k
horse-	flesh
h O@ s	f l e S
horse-	head
h O@ s	h e d
horse-	ly
h O@ s	l i:
horse-	man
h O@ s	m V n
horse-	man-	ship
h O@ s	m V n	S I p
horse-	men
h O@ s	m V n
horse-	play
h O@ s	p l eI
horse-	po-	wer
h O@ s	p aU	@r
horse-	ra-	dish
h O@ s	r {	d I S
horse-	shoe
h O@ s	S u:
horse-	shoes
h O@ s	S u: z
horse-	tail
h O@ s	t eI l
horse-	tails
h O@ s	t eI l z
horst
h O@ s t
ho's
h @U z
hos-	ford
h Q s	f @r d
hos-	kin-	son
h Q s	k I n	s V n
hos-	kins
h Q s	k I n z
hos-	pi-	ces
h Q s	p I	s V z
hos-	pi-	ce's
h Q s	p I	s V z
hos-	pi-	ta-	ble
h Q s	p I	t V	b V l
hos-	pi-	ta-	li-	ty
h Q s	p I	t {	l I	t i:
hos-	pi-	ta-	li-	za-	tion
h Q s	p I	t V	l I	z eI	S V n
hos-	pi-	ta-	li-	za-	tions
h Q s	p I	t V	l I	z eI	S V n z
hos-	pi-	ta-	lize
h Q s	p I	t V	l aI z
hos-	pi-	ta-	lized
h Q s	p I	t V	l aI z d
hos-	pi-	tal
h Q s	p I	t V l
hos-	pi-	tals
h Q s	p I	t V l z
hos-	pi-	tal's
h Q s	p I	t V l z
hos-	pice
h Q s	p I s
hos-	ta-	ges
h Q s	t I	dZ V z
hos-	tage
h Q s	t I dZ
hos-	ted
h @U s	t V d
hos-	tel
h Q s	t V l
hos-	tels
h Q s	t V l z
hos-	ter
h @U s	t @r
hos-	tes-	ses
h @U s	t V	s V z
hos-	tess
h @U s	t V s
hos-	tet-	ter
h Q s	t e	t @r
hos-	ti-	li-	ties
h Q s	t I	l I	t i: z
hos-	ti-	li-	ty
h Q s	t I	l I	t i:
hos-	tile
h Q s	t I l
hos-	ting
h @U s	t I N
hose
h @U z
hosed
h @U z d
hoss
h Q s
host
h @U s t
host-	ler
h Q s	l @r
hosts
h @U s t s
host's
h @U s t s
hot
h Q t
hot-	bed
h Q t	b e d
hot-	beds
h Q t	b e d z
hot-	cake
h Q t	k eI k
hot-	cakes
h Q t	k eI k s
hot-	dog
h Q t	d O: g
hot-	dogs
h Q t	d O: g z
hot-	house
h Q t	h aU s
hot-	line
h Q t	l aI n
hot-	lines
h Q t	l aI n z
hot-	ly
h Q t	l i:
hot-	shot
h Q	tS Q t
hot-	ter
h Q	t @r
hot-	test
h Q	t V s t
hot-	tle
h Q	t V l
hot-	wi-	re
h Q t	w aI	@r
hotch-	kiss
h Q tS	k I s
hoth
h Q T
hots
h Q t s
hotze
h @U t z
hou-	daille
h u:	d eI l
hou-	di-	ni
h u:	d i:	n i:
hou-	di-	ni's
h u:	d i:	n i: z
hou-	ri-	gan
aU	r I	g { n
hou-	ri-	han
aU	r i:	h Q n
hou-	rs
aU	@r z
)"
R"(hou-	sel
h aU	s V l
hou-	ser
h aU	z @r
hou-	ses
h aU	s V z
hou-	se's
h aU	s V z
houck
h aU k
houff
h @U f
hough
h V f
hough-	ton
h O:	t V n
hough-	ton's
h O:	t V n z
houghs
h aU z
houl-	ton
h @U l	t V n
houn-	ded
h aU n	d V d
houn-	ding
h aU n	d I N
hound
h aU n d
hounds
h aU n d z
hour-	long
aU r	l O: N
hour-	ly
aU r	l i:
house
h aU s
house-	boat
h aU s	b @U t
house-	bro-	ken
h aU s	b r @U	k V n
house-	clea-	ning
h aU s	k l i:	n I N
house-	ful
h aU s	f V l
house-	guest
h aU s	g e s t
house-	hol-	der
h aU s	h @U l	d @r
house-	hol-	ders
h aU s	h @U l	d @r z
house-	hold
h aU s	h @U l d
house-	holds
h aU s	h @U l d z
house-	hold's
h aU s	h @U l d z
house-	kee-	per
h aU s	k i:	p @r
house-	kee-	pers
h aU s	k i:	p @r z
house-	kee-	ping
h aU s	k i:	p I N
house-	man
h aU s	m V n
house-	man's
h aU s	m V n z
housed
h aU z d
hov-	ha-	ness
h O: v	h {	n V s
hov-	land
h Q v	l V n d
hove
h @U v
how
h aU
how-	dy
h aU	d i:
how-	e-	ver
h aU	e	v @r
how-	land
h aU	l V n d
how-	ler
h aU	l @r
how-	ling
h aU	l I N
howe
h aU
howes
h aU z
howe's
h aU z
howk
h aU k
howl
h aU l
howled
h aU l d
howls
h aU l z
how's
h aU z
hox-	sie
h Q k	s i:
hoy
h OI
hoy-	ing
h OI	I N
hoy-	lake
h OI	l eI k
hoye
h OI
hoyle
h OI l
hoyt
h OI t
hrd-	lic-	ka
h @r d	l I s	k V
hru-	ska
h r V s	k V
hsia
S Q
hsu
S u:
hu
h u:
hu-	a
h u:	V
hu-	ber
h j u:	b @r
hu-	ber-	man
h u:	b @r	m V n
hu-	ber-	to
h u:	b e@	t @U
hu-	ber-	ty
h V	b @r	t i:
hu-	bert
h j u:	b @r t
hu-	bert's
h j u:	b @r t s
hu-	gel
h u:	g V l
hu-	gest
h j u:	dZ V s t
hu-	ghett
h j u:	e t
hu-	ghie
h j u:	i:
hu-	go
h j u:	g @U
hu-	go-	ton
h j u:	g @U	t V n
hu-	go's
h j u:	g @U z
hu-	gue-	not
h j u:	g V	n Q t
hu-	gue-	nots
h j u:	g V	n Q t s
hu-	i
h u:	I
hu-	kill
h j u:	k I l
hu-	la
h u:	l V
hu-	len
h V	l V n
hu-	lett
h j u:	l e t
hu-	ma-	na
h j u:	m {	n V
hu-	ma-	ni-	sm
h j u:	m V	n I	z V m
hu-	ma-	ni-	ta-	ri-	an
h j u:	m {	n I	t e@	i:	V n
hu-	ma-	ni-	ta-	ri-	ans
h j u:	m {	n I	t e@	i:	V n z
hu-	ma-	ni-	ties
h j u:	m {	n I	t i: z
hu-	ma-	ni-	ty
h j u:	m {	n I	t i:
hu-	ma-	ni-	ty's
h j u:	m {	n I	t i: z
hu-	ma-	ni-	zes
h j u:	m V	n aI	z V z
hu-	ma-	ni-	zing
h j u:	m V	n aI	z I N
hu-	ma-	nis-	tic
h j u:	m V	n I s	t I k
hu-	ma-	nist
h j u:	m V	n I s t
hu-	ma-	nists
h j u:	m V	n V s t s
hu-	ma-	nize
h j u:	m V	n aI z
hu-	ma-	nized
h j u:	m V	n aI z d
hu-	man
h j u:	m V n
hu-	man-	kind
h j u:	m V n	k aI n d
hu-	man-	kind's
h j u:	m V n	k aI n d z
hu-	man-	ly
h j u:	m V n	l i:
hu-	man-	ness
h j u:	m V n	n V s
hu-	mane
h j u:	m eI n
hu-	mane-	ly
h j u:	m eI n	l i:
hu-	mans
h j u:	m V n z
hu-	me-	rus
h j u:	m @r	V s
hu-	mi-	di-	fi-	er
h j u:	m I	d I	f aI	@r
hu-	mi-	di-	fi-	ers
h j u:	m I	d I	f aI	@r z
hu-	mi-	di-	ty
h j u:	m I	d I	t i:
hu-	mi-	di-	ty's
h j u:	m I	d I	t i: z
hu-	mi-	dor
h j u:	m I	d O@
hu-	mi-	li-	a-	ted
h j u:	m I	l i:	eI	t V d
hu-	mi-	li-	a-	ting
h j u:	m I	l i:	eI	t I N
hu-	mi-	li-	a-	tion
h j u:	m I	l i:	eI	S V n
hu-	mi-	li-	a-	tions
h j u:	m I	l i:	eI	S V n z
hu-	mi-	li-	ate
h j u:	m I	l i:	eI t
hu-	mi-	li-	ty
h j u:	m I	l I	t i:
hu-	mid
h j u:	m I d
hu-	mo-	ral
h j u:	m @r	V l
hu-	mo-	rist
h j u:	m @r	I s t
hu-	mo-	rists
h j u:	m @r	I s t s
hu-	mo-	rous
h j u:	m @r	V s
hu-	mo-	rous-	ly
h j u:	m @r	V s	l i:
hu-	mon-	gous
h j u:	m O: N	g V s
hu-	mor
h j u:	m @r
hu-	mor-	less
h j u:	m @r	l V s
hu-	mored
h j u:	m @r d
hu-	mus
h j u:	m V s
hu-	nan
h u:	n Q n
hu-	ron
h j u:	r Q n
hu-	sain
h V	s aI n
hu-	st-	ling
h V	s V	l I N
hu-	stles
h V	s V l z
hu-	ta
h u:	t V
hu-	tu
h u:	t u:
hu-	tus
h u:	t u: z
hu-	tu's
h u:	t u: z
hua-	chu-	ca
h w Q	tS u:	k V
huan
h w Q n
huang
h w { N
hub
h V b
hub-	bard
h V	b @r d
hub-	bard's
h V	b @r d z
hub-	bell
h V	b V l
hub-	bell's
h V	b V l z
hub-	ble
h V	b V l
hub-	ble's
h V	b V l z
hub-	bub
h V	b V b
hub-	by
h V	b i:
hub-	cap
h V b	k { p
hub-	caps
h V b	k { p s
hub-	ris
h j u: b	r I s
hube
h j u: b
hubs
h V b z
huc-	ka-	by
h V	k V	b i:
huc-	kle
h V	k V l
huc-	kle-	ber-	ry
h V	k V l	b e@	i:
huck
h V k
huck-	ster
h V k	s t @r
huck-	sters
h V k	s t @r z
hucks
h V k s
hud
h V d
hud-	d-	ling
h V	d V	l I N
hud-	die
h V	d i:
hud-	dle
h V	d V l
hud-	dle-	ston
h V	d V l	s t V n
hud-	dled
h V	d V l d
hud-	dles
h V	d V l z
hud-	dy
h V	d i:
hud-	gens
h V	dZ V n z
hud-	gins
h V	dZ I n z
hud-	nut
h V d	n V t
hud-	son
h V d	s V n
hud-	son's
h V d	s V n z
hud's
h V d z
hue
h j u:
hue-	y
h j u:	i:
hueb-	ner
h j u: b	n @r
hued
h j u: d
huer-	ta
h w e@	t V
hues
h j u: z
hues-	man
h U s	m V n
hues-	ton
h U s	t V n
huf-	fa-	ker
h V	f V	k @r
huf-	fer
h V	f @r
huf-	fing
h V	f I N
huf-	fy
h V	f i:
huf-	na-	gel
h V f	n eI	g V l
huff
h V f
huff-	man
h V f	m V n
huffed
h V f t
huffs
h V f s
huff's
h V f s
hug
h V g
hug-	ger
h V	g @r
hug-	ging
h V	g I N
hug-	gins
h V	g I n z
huge
h j u: dZ
huge-	ly
h j u: dZ	l i:
hugged
h V g d
hugh
h j u:
hugh-	son
h V g	s V n
hughes
h j u: z
hugs
h V g z
huh
h V
hul-	bard
h V l	b @r d
hul-	bert
h V l	b @r t
hul-	bert's
h V l	b @r t s
hul-	burt
h V l	b @r t
hul-	king
h V l	k I N
hul-	la-	ba-	loo
h V	l V	b V	l u:
hul-	ton
h V l	t V n
hulk
h V l k
hulks
h V l k s
hull
h V l
hulled
h V l d
hulls
h V l z
hull's
h V l z
hulme
h V l m
hult-	gren
h V l	t g r e n
hum
h V m
hum-	b-	ler
h V m	b V	l @r
hum-	b-	lest
h V m	b V	l V s t
hum-	b-	ling
h V m	b V	l I N
hum-	ber
h V m	b @r
hum-	ber-	to
h V m	b @r	t @U
hum-	bert
h V m	b @r t
hum-	ble
h V m	b V l
hum-	bled
h V m	b V l d
hum-	bles
h V m	b V l z
hum-	boldt
h V m	b @U l t
hum-	bug
h V m	b V g
hum-	din-	ger
h V m	d I	N @r
hum-	drum
h V m	d r V m
hum-	frey
h V m	f r i:
hum-	mel
h V	m V l
hum-	mer
h V	m @r
hum-	ming
h V	m I N
hum-	ming-	bird
h V	m I N	b @r d
hum-	ming-	birds
h V	m I N	b @r d z
hum-	phr-	eys
h V m	f @r	i: z
hum-	phr-	ies
h V m	f @r	i: z
hum-	phry
h V m	f r i:
hum-	vee
h V m	v i:
hum-	vees
h V m	v i: z
humb-	ly
h V m	b l i:
hume
h j u: m
hump
h V m p
hump-	back
h V m	p b { k
hump-	ty
h V m	p t i:
humped
h V m p t
humph
h V m f
humph-	rey's
h V m	f r i: z
hums
h V m z
hun
h V n
hun-	ches
h V n	tS V z
hun-	dred-	weight
h V n	d r V d	w eI t
hun-	dreds
h V n	d r V d z
hun-	dredth
h V n	d r V d T
hun-	dredths
h V n	d r V d T s
hun-	ga-	ri-	an
h V N	g e@	i:	V n
hun-	ga-	ri-	ans
h V N	g e@	i:	V n z
hun-	ga-	ry
h V N	g @r	i:
hun-	ga-	ry's
h V N	g @r	i: z
hun-	ge-	ring
h V N	g @r	I N
hun-	ger
h V N	g @r
hun-	ger-	ford
h V N	g @r	f @r d
hun-	ke-	ring
h V N	k @r	I N
hun-	ker
h V N	k @r
hun-	kered
h V N	k @r d
hun-	ky
h V N	k i:
hun-	ley
h V n	l i:
hun-	ne-	well
h V	n V	w e l
hun-	sin-	ger
h V n	s I	N @r
hun-	ted
h V n	t V d
hun-	ter
h V n	t @r
hun-	ters
h V n	t @r z
hun-	ter's
h V n	t @r z
hun-	ting
h V n	t I N
hun-	ting-	don
h V n	t I N	d V n
hun-	ting-	ton
h V n	t I N	t V n
hun-	ting-	ton's
h V n	t I N	t V n z
hunch
h V n tS
hunch-	back
h V n	tS b { k
hunched
h V n tS t
hund
h V n d
hund-	red
h V n	d r V d
hund-	red's
h V n	d r V d z
hung
h V N
hung-	ri-	er
h V N	g r i:	@r
hung-	ri-	ly
h V N	g r I	l i:
hung-	ry
h V N	g r i:
hunk
h V N k
hunks
h V N k s
hunt
h V n t
hunt-	ley
h V n	t l i:
hunt-	ly
h V n	t l i:
hunt-	ress
h V n	t r V s
hunts
h V n t s
hunt's
h V n t s
hunts-	man
h V n	t s m V n
hunts-	ville
h V n	t s v I l
hup-	pert
h V	p @r t
hur
h @r
hur-	d-	ler
h @r	d V	l @r
hur-	d-	ling
h @r	d V	l I N
hur-	dle
h @r	d V l
hur-	dles
h @r	d V l z
hur-	less
h @r	l V s
hur-	ley
h @r	l i:
hur-	ling
h @r	l I N
hur-	lock
h @r	l V k
hur-	ly
h @r	l i:
hur-	rah
h U@	Q
hur-	ray
h V	r eI
hur-	ri-	cane
h @r	I	k eI n
hur-	ri-	canes
h @r	I	k eI n z
hur-	ri-	cane's
h @r	I	k eI n z
hur-	ried
h @r	i: d
hur-	ried-	ly
h @r	i: d	l i:
hur-	ries
h @r	i: z
hur-	ry
h @r	i:
hur-	ry-	ing
h @r	i:	I N
hur-	ting
h @r	t I N
hur-	tle
h @r	t V l
hur-	witz
h @r	w I t s
hurd
h @r d
hurl
h @r l
hurl-	but
h @r l	b V t
hurled
h @r l d
hurs-	ton
h @r s	t V n
hurst
h @r s t
hurt
h @r t
hurt-	ful
h @r t	f V l
hurt-	ling
h @r t	l I N
hurts
h @r t s
hus-	band
h V z	b V n d
hus-	band-	ry
h V z	b V n	d r i:
hus-	bands
h V z	b V n d z
hus-	band's
h V z	b V n d z
hus-	key
h V s	k i:
hus-	ky
h V s	k i:
hus-	sar
h V	s @r
hus-	sein
h u:	s eI n
hus-	sein's
h u:	s eI n z
hus-	ser
h V	s @r
hus-	sey
h V	s i:
hus-	site
h V	s aI t
hus-	sy
h V	s i:
hus-	t-	ler
h V	s V	l @r
hus-	t-	lers
h V	s V	l @r z
hus-	tings
h V s	t I N z
hus-	tle
h V	s V l
hus-	tled
h V	s V l d
hus-	ton
h V s	t V n
huse
h j u: z
hush
h V S
hushed
h V S t
husk
h V s k
husks
h V s k s
huss
h V s
hust
h V s t
hut
h V t
hut-	che-	son
h V	tS V	s V n
hut-	chi-	son
h V	tS I	s V n
hut-	chi-	son's
h V	tS I	s V n z
hut-	chin-	son
h V	tS I n	s V n
hut-	chings
h V	tS I N z
hut-	chins
h V t	tS I n z
hut-	son
h V t	s V n
hut-	to
h u:	t @U
hut-	ton
h V	t V n
hut-	ton's
h V	t V n z
hutch
h V tS
huts
h V t s
hut's
h V t s
hutt
h V t
hux
h V k s
hux-	ford
h V k	s f @r d
hux-	ley
h V k	s l i:
hux-	ta-	ble
h V k	s t V	b V l
hwan
h w Q n
hwang
h w { N
hwan's
h w Q n z
hy
h aI
hy-	bri-	di-	za-	tion
h aI b	r I	d V	z eI	S V n
hy-	bri-	dize
h aI b	r I	d aI z
hy-	brid
h aI b	r I d
hy-	brids
h aI b	r I d z
hy-	de-	ra-	bad
h aI	d e@	V	b { d
hy-	den
h aI	d V n
hy-	der
h aI	d @r
hy-	e-	na
h aI	i:	n V
hy-	e-	nas
h aI	i:	n V z
hy-	gei-	a
h aI	dZ eI	V
hy-	gie-	nist
h aI	g i:	n I s t
hy-	gie-	nists
h aI	g i:	n I s t s
hy-	giene
h aI	dZ i: n
hy-	gro-	me-	ter
h aI g	r Q	m V	t @r
hy-	land
h aI	l V n d
hy-	man
h aI	m V n
hy-	men
h aI	m V n
hy-	mie
h aI	m i:
hy-	mies
h aI	m i: z
hy-	nek
h aI	n I k
hy-	pe-	rac-	ti-	vi-	ty
h aI	p @r	{ k	t I	v I	t i:
hy-	pe-	rac-	tive
h aI	p @r	{ k	t I v
hy-	pe-	ri-	on
h aI	p I@	i:	V n
hy-	pe-	ro-	pi-	a
h aI	p @r	@U	p i:	V
hy-	per
h aI	p @r
hy-	per-	ba-	ric
h aI	p @r	b Q@	I k
hy-	per-	bo-	la
h aI	p @r	b V	l V
hy-	per-	bo-	le
h aI	p @r	b V	l i:
hy-	per-	bo-	lic
h aI	p @r	b Q	l I k
hy-	per-	bo-	re-	an
h aI	p @r	b O@	i:	V n
hy-	per-	cri-	ti-	cal
h aI	p @r k	r I	t I	k V l
hy-	per-	ki-	ne-	tic
h aI	p @r	k I	n e	t I k
hy-	per-	link
h aI	p @r	l I N k
hy-	per-	links
h aI	p @r	l I N k s
hy-	per-	mar-	ket
h aI	p @r	m Q@	k V t
hy-	per-	mar-	kets
h aI	p @r	m Q@	k V t s
hy-	per-	sen-	si-	ti-	vi-	ty
h aI	p @r	s e n	s I	t I	v I	t i:
hy-	per-	sen-	si-	tive
h aI	p @r	s e n	s I	t I v
hy-	per-	so-	nic
h aI	p @r	s Q	n I k
hy-	per-	ten-	sion
h aI	p @r	t e n	S V n
hy-	per-	ten-	sive
h aI	p @r	t e n	s I v
hy-	per-	text
h aI	p @r	t e k s t
hy-	per-	to-	nic
h aI	p @r	t Q	n I k
hy-	phae
h aI	f i:
hy-	phe-	na-	ted
h aI	f V	n eI	t V d
hy-	phe-	nate
h aI	f V	n eI t
hy-	phen
h aI	f V n
hy-	ping
h aI	p I N
hy-	po
h aI	p @U
hy-	po-	chond-	ri-	a
h aI	p V	k Q n	d r i:	V
hy-	po-	chond-	ri-	ac
h aI	p V	k Q n	d r i:	{ k
hy-	po-	cri-	ti-	cal
h I	p I k	r I	t I	k V l
hy-	po-	crite
h I	p I k	r I t
hy-	po-	crites
h I	p I k	r I t s
hy-	po-	der-	mic
h aI	p V	d @r	m I k
hy-	po-	gly-	ce-	mi-	a
h aI	p @U g	l aI	s i:	m i:	V
hy-	po-	gly-	ce-	mic
h aI	p @U g	l aI	s i:	m I k
hy-	po-	lite
h aI	p V	l aI t
hy-	po-	ten-	sion
h aI	p @U	t e n	S V n
hy-	po-	tha-	la-	mic
h aI	p @U	T V	l {	m I k
hy-	po-	the-	ses
h aI	p Q	T V	s i: z
hy-	po-	the-	sis
h aI	p Q	T V	s V s
hy-	po-	the-	size
h aI	p Q	T V	s aI z
hy-	po-	the-	sized
h aI	p Q	T V	s aI z d
hy-	po-	the-	ti-	cal
h aI	p V	T e	t V	k V l
hy-	po-	the-	ti-	cals
h aI	p V	T e	t V	k V l z
hy-	po-	the-	tical-	ly
h aI	p V	T e	t I k	l i:
hy-	po-	ther-	mi-	a
h aI	p V	T @r	m i:	V
hy-	po-	xi-	a
h aI	p Q k	s i:	V
hy-	poc-	ri-	sy
h V	p Q k	r V	s i:
hy-	ra-	xes
h aI	r { k	s V z
hy-	son
h aI	s V n
hyd-	ra
h aI d	r V
hyd-	rant
h aI d	r V n t
hyd-	ride
h aI d	r aI d
hyd-	ro
h aI d	r @U
hyd-	ro-	car-	bon
h aI d	r @U	k Q@	b V n
hyd-	ro-	car-	bons
h aI d	r @U	k Q@	b V n z
hyd-	ro-	e-	lect-	ric
h aI d	r @U	V	l e k	t r I k
hyd-	ro-	foil
h aI d	r V	f OI l
hyd-	ro-	ge-	na-	ted
h aI d	r V	dZ V	n eI	t V d
hyd-	ro-	ge-	na-	ting
h aI d	r V	dZ V	n eI	t I N
hyd-	ro-	ge-	na-	tion
h aI d	r Q	dZ V	n eI	S V n
hyd-	ro-	ge-	nate
h aI d	r V	dZ V	n eI t
hyd-	ro-	ge-	nates
h aI d	r V	dZ V	n eI t s
hyd-	ro-	gen
h aI d	r V	dZ V n
hyd-	ro-	gens
h aI d	r V	dZ V n z
hyd-	ro-	gra-	phic
h aI d	r V g	r {	f I k
hyd-	ro-	ly-	sis
h aI d	r Q	l V	s V s
hyd-	ro-	ly-	zing
h aI d	r V	l aI	z I N
hyd-	ro-	lyze
h aI d	r V	l aI z
hyd-	ro-	lyzed
h aI d	r V	l aI z d
hyd-	ro-	me-	ter
h aI d	r Q	m V	t @r
hyd-	ro-	phi-	lic
h aI d	r V	f I	l I k
hyd-	ro-	po-	nic
h aI d	r V	p Q	n I k
hyd-	ro-	power
h aI d	r @U	p aU r
hyd-	ro-	sol
h aI d	r V	s Q l
hyd-	ro-	sul-	fide
h aI d	r @U	s V l	f aI d
hyd-	ro-	the-	ra-	py
h aI d	r @U	T e@	V	p i:
hyd-	ro-	ther-	mal
h aI d	r @U	T @r	m V l
hyd-	ro-	xide
h aI d	r Q k	s aI d
hyd-	ro-	xides
h aI d	r Q k	s aI d z
hyd-	ro-	xy
h aI d	r O: k	s i:
hyd-	ro's
h aI d	r @U z
hyd-	rous
h aI d	r V s
hyde
h aI d
hyde's
h aI d z
hye
h aI
hykes
h aI k s
hyle
h aI l
hym-	nal
h I m	n V l
hym-	nals
h I m	n V l z
hym-	no-	lo-	gy
h I m	n Q	l V	dZ i:
hymn
h I m
hymns
h I m z
hynd
h I n d
hynd-	man
h I n	d m V n
hyne-	s's
h aI n	z V z
hynes
h aI n z
hyp-	no-	sis
h I p	n @U	s I s
hyp-	no-	ti-	sm
h I p	n V	t I	z V m
hyp-	no-	ti-	sm's
h I p	n V	t I	z V m z
hyp-	no-	tic
h I p	n Q	t I k
hyp-	no-	tics
h I p	n Q	t I k s
hyp-	no-	tize
h I p	n V	t aI z
hyp-	no-	tized
h I p	n V	t aI z d
hype
h aI p
hyped
h aI p t
hypes
h aI p s
hys-	sop
h I	s V p
hys-	te-	rec-	to-	mies
h I s	t @r	e k	t V	m i:
hys-	te-	rec-	to-	my
h I s	t @r	e k	t V	m i:
hys-	te-	ri-	a
h I s	t e@	i:	V
hys-	te-	ri-	cal
h I s	t e@	I	k V l
hys-	te-	ric
h I s	t e@	I k
hys-	te-	rical-	ly
h I s	t e@	I k	l i:
hys-	te-	rics
h I s	t e@	I k s
hyun-	dai
h j V n	d eI
hyun-	dai's
h V n	d eI z
i
aI
i-	a
i:	V
i-	a-	coc-	ca
aI	V	k @U	k V
i-	a-	coc-	ca's
aI	V	k @U	k V z
i-	a-	go
i:	Q	g @U
i-	ain
i:	eI n
i-	ams
i:	Q m z
i-	an
i:	V n
i-	an-	the
i:	Q n	T eI
i-	an-	thi-	na
i:	V n	T i:	n V
i-	ba
i:	b V
i-	ba-	nez
I	b Q	n e z
i-	ba-	ra-	ki
aI	b @r	Q	k i:
i-	be-	ri-	a
aI	b I@	i:	V
i-	be-	ri-	an
aI	b I@	i:	V n
i-	be-	ri-	a's
aI	b I@	i:	V z
i-	bex
aI	b e k s
i-	bis
aI	b I s
i-	bn
I	b V n
i-	bo-	gaine
aI	b @U	g eI n
i-	bup-	ro-	fen
aI b	j u: p	r @U	f V n
i-	ca-	rus
I	k @r	V s
i-	cahn
aI	k Q n
i-	cahn's
aI	k Q n z
i-	card
I	k Q@ d
i-	ces
aI	s V z
i-	co-	no-	clas-	tic
aI	k V	n V k	l { s	t I k
i-	co-	no-	clast
aI	k Q	n V k	l { s t
i-	co-	no-	gra-	phy
aI	k V	n Q g	r V	f i:
i-	co-	noc-	la-	sm
aI	k Q	n V k	l {	z V m
i-	con
aI	k Q n
i-	cons
aI	k Q n z
i-	cy
aI	s i:
i-	d-	ler
aI	d V	l @r
i-	d-	ling
aI	d V	l I N
i-	da
aI	d V
i-	da-	ho
aI	d V	h @U
i-	da-	ho's
aI	d V	h @U z
i-	da-	li-	na
V	d Q	l i:	n V
i-	da-	lia
V	d Q l	j V
i-	da-	line
I	d V	l aI n
i-	de-	a
aI	d i:	V
i-	de-	a-	lis-	tic
aI	d i:	V	l I s	t I k
i-	de-	a-	lized
aI	d i:	V	l aI z d
i-	de-	as
aI	d i:	V z
i-	de-	a's
aI	d i:	V z
i-	de-	o-	lo-	gi-	cal
aI	d i:	V	l Q	dZ I	k V l
i-	de-	o-	lo-	gical-	ly
aI	d i:	V	l Q	dZ I k	l i:
i-	de-	o-	lo-	gies
aI	d i:	Q	l V	dZ i: z
i-	de-	o-	lo-	gist
aI	d i:	Q	l V	dZ V s t
i-	de-	o-	lo-	gists
aI	d i:	Q	l V	dZ V s t s
i-	de-	o-	lo-	gy
aI	d i:	Q	l V	dZ i:
i-	de-	o-	logue
aI	d i:	V	l @U g
i-	de-	o-	logues
aI	d i:	V	l O: g z
i-	dea-	li-	sm
aI	d i:	l I	z V m
i-	dea-	list
aI	d i:	l I s t
i-	dea-	lists
aI	d i:	l I s t s
i-	dea-	lize
aI	d i:	l aI z
i-	deal
aI	d i: l
i-	deal-	ly
aI	d i:	l i:
i-	deals
aI	d i: l z
i-	deal's
aI	d i: l z
i-	den
aI	d V n
i-	den-	ti-	cal
aI	d e n	t I	k V l
i-	den-	ti-	fi-	a-	ble
aI	d e n	t I	f aI	V	b V l
i-	den-	ti-	fi-	ca-	tion
aI	d e n	t I	f V	k eI	S V n
i-	den-	ti-	fi-	ca-	tions
aI	d e n	t I	f I	k eI	S V n z
i-	den-	ti-	fi-	er
aI	d e n	t I	f aI	@r
i-	den-	ti-	fied
aI	d e n	t I	f aI d
i-	den-	ti-	fies
aI	d e n	t I	f aI z
i-	den-	ti-	fy
aI	d e n	t I	f aI
i-	den-	ti-	fy-	ing
aI	d e n	t I	f aI	I N
i-	den-	ti-	kit
aI	d e n	t I	k I t
i-	den-	ti-	ties
aI	d e n	t I	t i: z
i-	den-	ti-	ty
aI	d e n	t I	t i:
i-	dette
aI	d e t
i-	di-	o-	cy
I	d i:	V	s i:
i-	di-	o-	ma-	tic
I	d i:	V	m {	t I k
i-	di-	o-	syn-	cra-	sies
I	d i:	@U	s I n	k r V	s i: z
i-	di-	o-	syn-	cra-	sy
I	d i:	@U	s I n	k r V	s i:
i-	di-	o-	syn-	cra-	tic
I	d i:	@U	s I n	k r {	t I k
i-	di-	o-	tic
I	d i:	Q	t I k
i-	di-	o-	tical-	ly
I	d i:	Q	t I k	l i:
i-	di-	om
I	d i:	V m
i-	di-	oms
I	d i:	V m z
i-	di-	ot
I	d i:	V t
i-	di-	ots
I	d i:	V t s
i-	di-	ta-	rod
I	d I	t V	r O: d
i-	dle
aI	d V l
i-	dle-	man
aI	d V l	m V n
i-	dle-	ness
aI	d V l	n V s
i-	dle-	wild
aI	d V l	w aI l d
i-	dled
aI	d V l d
i-	dles
aI	d V l z
i-	do
i:	d @U
i-	do-	la
V	d @U	l V
)"
R"(i-	do-	lat-	rous
aI	d Q	l V t	r V s
i-	do-	lat-	ry
aI	d Q	l V t	r i:
i-	do-	li-	zes
aI	d V	l aI	z V z
i-	do-	li-	zing
aI	d V	l aI	z I N
i-	do-	lize
aI	d V	l aI z
i-	do-	lized
aI	d V	l aI z d
i-	do-	na
V	d @U	n V
i-	dol
aI	d V l
i-	dols
aI	d V l z
i-	du-	na
V	d u:	n V
i-	dyl-	lic
aI	d I	l I k
i-	dyll
aI	d V l
i-	fill
I	f i: l
i-	fint
aI	f I n t
i-	go
i:	g @U
i-	gor
I	g O@
i-	gua-	na
aI g	w Q	n V
i-	gua-	nas
I g	w Q	n V z
i-	ke-	a
aI	k i:	V
i-	ke-	da
I	k eI	d V
i-	key
I	k i:
i-	la
i:	l V
i-	lan
i:	l Q n
i-	le-	a-	na
I	l i:	{	n V
i-	lene
I	l i: n
i-	li-	ad
I	l i:	V d
i-	liff
I	l I f
i-	lo
aI	l @U
i-	lo-	na
I	l @U	n V
i-	ma-	ges
I	m V	dZ V z
i-	ma-	gi-	na-	ble
I	m {	dZ I	n V	b V l
i-	ma-	gi-	na-	ry
I	m {	dZ I	n e@	i:
i-	ma-	gi-	na-	tion
I	m {	dZ I	n eI	S V n
i-	ma-	gi-	na-	tions
I	m {	dZ I	n eI	S V n z
i-	ma-	gi-	na-	tive
I	m {	dZ I	n V	t I v
i-	ma-	gi-	na-	tive-	ly
I	m {	dZ I	n V	t I v	l i:
i-	ma-	gi-	ning
I	m {	dZ I	n I N
i-	ma-	gine
I	m {	dZ I n
i-	ma-	gined
I	m {	dZ I n d
i-	ma-	gines
I	m {	dZ I n z
i-	ma-	ging
I	m I	dZ I N
i-	ma-	ri
i:	m Q@	i:
i-	mage
I	m V dZ
i-	mage-	ries
I	m I dZ	r i: z
i-	mage-	ry
I	m V dZ	r i:
i-	mai
I	m aI
i-	mam
aI	m { m
i-	man
aI	m V n
i-	max
aI	m { k s
i-	mel-	da
I	m e l	d V
i-	mi-	ta-	ble
I	m I	t V	b V l
i-	mi-	ta-	ted
I	m I	t eI	t I d
i-	mi-	ta-	ting
I	m I	t eI	t I N
i-	mi-	ta-	tion
I	m I	t eI	S V n
i-	mi-	tate
I	m I	t eI t
i-	mi-	tates
I	m I	t eI t s
i-	mo
aI	m @U
i-	mo-	gen
I	m V	g V n
i-	mo-	gene
I	m V	dZ i: n
i-	mus
aI	m V s
i-	na
i:	n V
i-	na-	bi-	li-	ty
I	n V	b I	l V	t i:
i-	na-	lie-	na-	ble
I	n eI l	j V	n V	b V l
i-	na-	ni-	mate
I	n {	n I	m V t
i-	nac-	ces-	si-	bi-	li-	ty
I	n V k	s e	s V	b I	l V	t i:
i-	nac-	ces-	si-	ble
I	n V k	s e	s V	b V l
i-	nac-	cu-	ra-	cies
I	n { k	j @r	{	s i: z
i-	nac-	cu-	ra-	cy
I	n { k	j @r	V	s i:
i-	nac-	cu-	rate
I	n { k	j @r	V t
i-	nac-	cu-	rate-	ly
I	n { k	j @r	V t	l i:
i-	nad-	ver-	tent-	ly
I	n V d	v @r	t V n	t l i:
i-	nad-	vi-	sa-	ble
I	n V d	v aI	z V	b V l
i-	nane
I	n eI n
i-	nap-	pli-	ca-	ble
I	n { p	l I	k V	b V l
i-	nap-	pro-	pri-	ate
I	n V p	r @U p	r i:	V t
i-	nap-	pro-	pri-	ate-	ly
I	n V p	r Q p	r i:	V t	l i:
i-	nar-	ti-	cu-	late
I	n Q@	t I k	j V	l V t
i-	nas-	much
I	n { s	m V k
i-	nat-	ten-	tion
I	n V	t e n	tS V n
i-	nat-	ten-	tive
I	n V	t e n	t I v
i-	nau-	di-	ble
I	n O:	d I	b V l
i-	nau-	gu-	ra-	ted
I	n O:	g @r	eI	t V d
i-	nau-	gu-	ra-	ting
I	n O: g	j @r	eI	t I N
i-	nau-	gu-	ra-	tion
I	n O: g	j @r	eI	S V n
i-	nau-	gu-	ra-	tions
I	n O: g	j @r	eI	S V n z
i-	nau-	gu-	ral
I	n O:	g @r	V l
i-	nau-	gu-	rate
I	n O: g	j @r	eI t
i-	nau-	gu-	rates
I	n O: g	j @r	V t s
i-	nau-	spi-	cious
I	n aU s	p I	S V s
i-	ne-	di-	ble
I	n e	d I	b V l
i-	ne-	las-	tic
I	n V	l { s	t I k
i-	ne-	li-	gi-	ble
I	n e	l I	dZ I	b V l
i-	ne-	qua-	li-	ties
I	n I k	w Q	l I	t i: z
i-	ne-	qua-	li-	ty
I	n I k	w Q	l I	t i:
i-	ne-	qui-	ta-	ble
I	n e k	w V	t V	b V l
i-	ne-	qui-	ties
I	n e k	w V	t i: z
i-	ne-	qui-	ty
I	n e k	w V	t i:
i-	ne-	vi-	ta-	bi-	li-	ty
I	n e	v I	t V	b I	l I	t i:
i-	ne-	vi-	ta-	ble
I	n e	v I	t V	b V l
i-	ne-	vi-	tab-	ly
I	n e	v I	t V b	l i:
i-	ne-	xact
I	n I g	z { k t
i-	ne-	xo-	ra-	ble
I	n e k	s @r	V	b V l
i-	ne-	xo-	rab-	ly
I	n e k	s @r	V b	l i:
i-	nef-	fa-	ble
I	n e	f V	b V l
i-	nef-	fec-	tive
I	n V	f e k	t I v
i-	nef-	fec-	tive-	ness
I	n V	f e k	t I v	n V s
i-	nef-	fec-	tu-	al
I	n V	f e k	tS u:	V l
i-	nef-	fi-	cien-	cies
I	n V	f I	S V n	s i: z
i-	nef-	fi-	cien-	cy
I	n V	f I	S V n	s i:
i-	nef-	fi-	cient
I	n V	f I	S V n t
i-	nef-	fi-	cient-	ly
I	n V	f I	S V n	t l i:
i-	nep-	ti-	tude
I	n e p	t I	t u: d
i-	nept
I	n e p t
i-	nept-	ly
I	n e p	t l i:
i-	nept-	ness
I	n e p	t n V s
i-	ner-	tia
I	n @r	S V
i-	ner-	tial
I	n @r	S V l
i-	nert
I	n @r t
i-	nert-	ness
I	n @r t	n V s
i-	nes
I	n I s
i-	nes-	ca-	pa-	ble
I	n V s	k eI	p V	b V l
i-	nex-	cu-	sa-	ble
I	n I k	s k j u:	z V	b V l
i-	nex-	haus-	ti-	ble
I	n I g	z O: s	t I	b V l
i-	nex-	pe-	ri-	ence
I	n I k	s p I@	i:	V n s
i-	nex-	pe-	ri-	enced
I	n I k	s p I@	i:	V n s t
i-	nex-	pen-	sive
I	n I k	s p e n	s I v
i-	nex-	pen-	sive-	ly
I	n V k	s p e n	s I v	l i:
i-	nex-	pli-	ca-	ble
I	n V k	s p l I	s V	b V l
i-	nex-	pli-	ca-	bly
I	n I k	s p l I	k V b	l i:
i-	nex-	tri-	ca-	bly
I	n e k	s t r I	k V b	l i:
i-	nez
I	n e z
i-	ni-	mi-	cal
I	n I	m I	k V l
i-	ni-	mi-	ta-	ble
I	n I	m I	t V	b V l
i-	ni-	ti-	a-	ted
I	n I	S i:	eI	t V d
i-	ni-	ti-	a-	ting
I	n I	S i:	eI	t I N
i-	ni-	ti-	a-	tion
I	n I	S i:	eI	S V n
i-	ni-	ti-	a-	tor
I	n I	S i:	eI	t @r
i-	ni-	ti-	a-	tors
I	n I	S i:	eI	t @r z
i-	ni-	ti-	ate
I	n I	S i:	eI t
i-	ni-	ti-	ates
I	n I	S i:	V t s
i-	ni-	ti-	o
I	n I	t i:	@U
i-	ni-	tia-	ling
I	n I	S V	l I N
i-	ni-	tia-	tive
I	n I	S V	t I v
i-	ni-	tia-	tives
I	n I	S V	t I v z
i-	ni-	tial
I	n I	S V l
i-	ni-	tial-	ly
I	n I	S V	l i:
i-	ni-	tialed
I	n I	S V l d
i-	ni-	tials
I	n I	S V l z
i-	no-	cu-	la-	ted
I	n Q k	j V	l eI	t V d
i-	no-	cu-	la-	tion
I	n Q k	j V	l eI	S V n
i-	no-	cu-	la-	tions
I	n Q k	j V	l eI	S V n z
i-	no-	cu-	late
I	n Q k	j V	l eI t
i-	no-	pe-	ra-	ble
I	n Q	p @r	V	b V l
i-	no-	pe-	ra-	tive
I	n Q	p @r	V	t I v
i-	nof-	fen-	sive
I	n V	f e n	s I v
i-	nop-	por-	tune
I	n Q	p @r	t u: n
i-	nor-	di-	nate
I	n O@	d V	n V t
i-	nor-	di-	nate-	ly
I	n O@	d V	n V t	l i:
i-	nor-	ga-	nic
I	n O@	g {	n I k
i-	nou-	e
I	n @U	eI
i-	nuit
I	n u: t
i-	nun-	da-	ted
I	n V n	d eI	t V d
i-	nun-	da-	ting
I	n V n	d eI	t I N
i-	nun-	da-	tion
I	n V n	d eI	S V n
i-	nun-	da-	tions
I	n V n	d eI	S V n z
i-	nun-	date
I	n V n	d eI t
i-	nure
I n	j U@
i-	nured
I n	j U@ d
i-	ny
I	n i:
i-	o
aI	@U
i-	o-	dide
aI	V	d aI d
i-	o-	dides
aI	V	d aI d z
i-	o-	dide's
aI	V	d aI d z
i-	o-	dine
aI	V	d aI n
i-	o-	la
aI	@U	l V
i-	o-	lan-	de
i:	@U	l Q n	d i:
i-	o-	le
i:	@U	l i:
i-	o-	na
aI	@U	n V
i-	o-	ne
aI	@U	n i:
i-	o-	ni-	za-	tion
aI	V	n V	z eI	S V n
i-	o-	ni-	zer
aI	V	n aI	z @r
i-	o-	ni-	zers
aI	V	n aI	z @r z
i-	o-	ni-	zing
aI	V	n aI	z I N
i-	o-	nic
aI	Q	n I k
i-	o-	nics
aI	Q	n I k s
i-	o-	nize
aI	V	n aI z
i-	o-	nos-	phe-	ric
aI	Q	n V s	f e@	I k
i-	o-	nos-	phere
aI	j Q	n V s	f i: r
i-	o-	ri-	o
i:	O@	i:	@U
i-	o-	sif
aI	V	s I f
i-	o-	ta
aI	@U	t V
i-	o-	u
aI	@U	j u:
i-	o-	wa
aI	V	w V
i-	o-	wan
aI	V	w V n
i-	o-	wans
aI	V	w V n z
i-	o-	wa's
aI	V	w V z
i-	on
aI	V n
i-	ons
aI	V n z
i-	os
i:	@U s
i-	ra
aI	r V
i-	ra-	ni
I@	Q	n i:
i-	ra-	ni-	an
I@	Q	n i:	V n
i-	ra-	ni-	ans
aI	r eI	n i:	V n z
i-	ra-	qi
I@	{	k i:
i-	ra-	qis
I@	{	k i: z
i-	ra-	qi's
I@	{	k i: z
i-	ran
I@	Q n
i-	ran-	gate
I@	Q n	g eI t
i-	ran's
I@	{ n z
i-	raq
I@	Q k
i-	raq's
I@	Q k s
i-	ras
aI	r V z
i-	ra's
aI	r V z
i-	ras-	ci-	ble
I@	{	s I	b V l
i-	rate
aI	r eI t
i-	re-	land
aI	@r	l V n d
i-	re-	na
I@	eI	n V
i-	re-	ton
I@	I	t Q n
i-	rene
aI	r i: n
i-	rene's
aI	r i: n z
i-	ri-	an
aI	r i:	V n
i-	ri-	de-	scent
I@	I	d e	s V n t
i-	ri-	di-	um
I@	I	d i:	V m
i-	ri-	na
I@	i:	n V
i-	ri-	ses
aI	r I	s V z
i-	ris
aI	r I s
i-	rish
aI	r I S
i-	rish-	man
aI	r I S	m V n
i-	ro-	ny
aI	r V	n i:
i-	ro-	quois
I@	V k	w OI
i-	ron
aI	@r n
i-	ron-	side
aI	@r n	s aI d
i-	ron-	sides
aI	@r n	s aI d z
i-	ron-	wood
aI	@r n	w U d
i-	ron-	wood's
aI	@r n	w U d z
i-	sa
i:	s V
i-	sa-	bel
I	z V	b e l
i-	sa-	bel-	la
I	z V	b e	l V
i-	sa-	belle
I	z V	b e l
i-	sa-	do-	re
I	s Q	d O@	eI
i-	saac
aI	z V k
i-	saac-	son
aI	z I k	s V n
i-	saacs
aI	z I k s
i-	saak
I	s Q k
i-	sai-	ah
aI	z eI	V
i-	se-	lin
I	s V	l V n
i-	sher-	wood
I	S @r	w U d
i-	shi
I	S i:
i-	shi-	ha-	ra
I	S i:	h Q@	V
i-	shi-	i
I	S i:	i:
i-	si-	dore
I	z I	d O@
i-	sis
aI	s I s
i-	sm
I	z V m
i-	sms
I	z V m z
i-	sn't
I	z V n t
i-	so-	cy-	a-	nate
aI	s V	s aI	V	n eI t
i-	so-	e-	lec-	tro-	nic
aI	s @U	V	l e k	t r Q	n I k
i-	so-	la
aI	s Q	l V
i-	so-	la-	ted
aI	s V	l eI	t V d
i-	so-	la-	ting
aI	s V	l eI	t I N
i-	so-	la-	tio-	ni-	sm
aI	s V	l eI	S V	n I	z V m
i-	so-	la-	tio-	nist
aI	s V	l eI	S V	n V s t
i-	so-	la-	tio-	nists
aI	s V	l eI	S V	n V s t s
i-	so-	la-	tion
aI	s V	l eI	S V n
i-	so-	late
aI	s V	l eI t
i-	so-	lates
aI	s V	l eI t s
i-	so-	mer
aI	s V	m @r
i-	so-	mers
aI	s V	m @r z
i-	so-	mor-	phi-	sm
aI	s V	m O@	f I	z V m
i-	so-	ther-	mal
aI	s V	T @r	m V l
i-	so-	to-	nic
aI	s V	t Q	n I k
i-	so-	to-	pic
aI	s V	t Q	p I k
i-	so-	tope
aI	s V	t @U p
i-	so-	topes
aI	s V	t @U p s
i-	sol-	de
I	s @U l	d V
i-	som
aI	s V m
i-	sop-	ri-	no-	sine
I	s V p	r I	n V	s i: n
i-	sos-	ce-	les
aI	s O:	s V	l i: z
i-	su-	zu
I	s u:	z u:
i-	ta
aI	t V
i-	ta-	li-	a
i:	t {	l i:	V
i-	ta-	lia-	nate
V	t { l	j V	n eI t
i-	ta-	lian
V	t { l	j V n
i-	ta-	ly
I	t V	l i:
i-	ta-	ly's
I	t V	l i: z
i-	tas-	ca
aI	t { s	k V
i-	t'd
I	t V d
i-	te-	mi-	zer
aI	t V	m aI	z @r
i-	te-	mi-	zers
aI	t V	m aI	z @r z
i-	te-	mi-	zing
aI	t V	m aI	z I N
i-	te-	mize
aI	t V	m aI z
i-	te-	mized
aI	t V	m aI z d
i-	te-	ra-	tive
I	t @r	eI	t I v
i-	tel
aI	t e l
i-	tem
aI	t V m
i-	tems
aI	t V m z
i-	ten
aI	t V n
i-	tha-	ca
I	T V	k V
i-	ti-	ne-	ra-	ries
aI	t I	n @r	e@	i: z
i-	ti-	ne-	ra-	ry
aI	t I	n @r	e@	i:
i-	ti-	ne-	rant
aI	t I	n @r	V n t
i-	t'll
I	t V l
i-	to
i:	t @U
i-	to's
i:	t @U z
i-	va
i:	v V
i-	va-	na
I	v Q	n V
i-	va-	nov
I	v V	n Q v
i-	van
aI	v V n
i-	van-	hoe
aI	v V n	h @U
i-	van-	na
I	v Q	n V
i-	var
I	v @r
i-	vens
aI	v V n z
i-	ver
aI	v @r
i-	ver-	son
aI	v @r	s V n
i-	vers
aI	v @r z
i-	vey
aI	v i:
i-	vie
aI	v i:
i-	vins
I	v I n z
i-	vo
aI	v @U
i-	vo-	ri-	an
aI	v O@	i:	V n
i-	vo-	ri-	ans
aI	v O@	i:	V n z
i-	vo-	ry
aI	v @r	i:
i-	vor
aI	v @r
i-	vy
aI	v i:
i-	wo
aI	w @U
i-	xi-	on
I k	s aI	V n
i-	zard
I	z @r d
i-	zod
aI	z Q d
i.
aI
ib
I b
ib-	ra-	him
I b	r Q	h i: m
ib-	sen
I b	s V n
ice
aI s
ice-	berg
aI s	b @r g
ice-	bergs
aI s	b @r g z
ice-	box
aI s	b Q k s
ice-	brea-	ker
aI s	b r eI	k @r
ice-	brea-	kers
aI s	b r eI	k @r z
ice-	fish
aI s	f I S
ice-	lan-	dic
aI s	l { n	d I k
ice-	land
aI s	l V n d
ice-	man
aI s	m { n
ice-	ska-	ting
aI s	s k eI	t I N
ice-	skate
aI s	s k eI t
iced
aI s t
ich
I tS
id
I d
i'd
aI d
id-	ly
aI d	l i:
ide
aI d
ierne
I@ n
if
I f
if-	fy
I	f i:
ifs
I f s
ig-	le-	si-	a
i: g	l eI	s i:	V
ig-	le-	si-	as
I g	l eI	s i:	V s
ig-	loo
I g	l u:
ig-	na-	ci-	o
I g	n Q	s i:	@U
ig-	na-	ci-	o's
I g	n Q	s i:	@U z
ig-	na-	tia
I g	n Q	S V
ig-	na-	tius
I g	n eI	S V s
ig-	nace
I g	n V s
ig-	natz
I g	n V t s
ig-	ne-	ous
I g	n i:	V s
ig-	ni-	ted
I g	n aI	t V d
ig-	ni-	ting
I g	n aI	t I N
ig-	ni-	tion
I g	n I	S V n
ig-	nite
I g	n aI t
ig-	nites
I g	n aI t s
ig-	no-	ble
I g	n @U	b V l
ig-	no-	mi-	ni-	ous
I g	n V	m I	n i:	V s
ig-	no-	mi-	ny
I g	n @U	m I	n i:
ig-	no-	ra-	mus
I g	n @r	eI	m V s
ig-	no-	rance
I g	n @r	V n s
ig-	no-	rant
I g	n @r	V n t
ig-	no-	ring
I g	n O@	I N
ig-	nore
I g	n O@
ig-	nored
I g	n O@ d
ig-	nores
I g	n O@ z
ige
aI dZ
ii-	e
i:	i:
ike
aI k
ike's
aI k s
il
I l
il-	ka
I l	k V
il-	le-	ga-	li-	ties
I	l i:	g {	l I	t i: z
il-	le-	ga-	li-	ty
I	l i:	g {	l I	t i:
il-	le-	gal
I	l i:	g V l
il-	le-	gal-	ly
I	l i:	g V	l i:
il-	le-	gals
I	l i:	g V l z
il-	le-	gi-	ble
I	l e	dZ I	b V l
il-	le-	gi-	ti-	ma-	cy
I	l I	dZ I	t I	m V	s i:
il-	le-	gi-	ti-	mate
I	l I	dZ I	t I	m V t
il-	li-	cit
I	l I	s I t
il-	li-	cit-	ly
I	l I	s I t	l i:
il-	li-	nois
I	l I	n OI
il-	li-	nois's
I	l I	n OI z
il-	li-	qui-	di-	ty
I	l I k	w I	d I	t i:
il-	li-	quid
I	l I k	w V d
il-	li-	te-	ra-	cy
I	l I	t @r	V	s i:
il-	li-	te-	rate
I	l I	t @r	V t
il-	li-	te-	rates
I	l I	t @r	V t s
il-	ling-	worth
I	l I N	w @r T
il-	lo-	gi-	cal
I	l Q	dZ I	k V l
il-	lo-	gic
I	l Q	dZ I k
il-	lu-	mi-	na-	ted
I	l u:	m I	n eI	t I d
il-	lu-	mi-	na-	ting
I	l u:	m I	n eI	t I N
il-	lu-	mi-	na-	tion
I	l u:	m I	n eI	S V n
il-	lu-	mi-	na-	tor
I	l u:	m I	n eI	t @r
il-	lu-	mi-	nate
I	l u:	m I	n eI t
il-	lu-	mi-	nates
I	l u:	m I	n eI t s
il-	lu-	mine
I	l u:	m I n
il-	lu-	mined
I	l u:	m I n d
il-	lu-	sio-	na-	ry
I	l u:	Z V	n e@	i:
il-	lu-	sio-	ni-	sm
I	l u:	Z V	n I	z V m
il-	lu-	sio-	nist
I	l u:	Z V	n I s t
il-	lu-	sio-	nists
I	l u:	Z V	n I s t s
il-	lu-	sio-	nist's
I	l u:	Z V	n I s t s
il-	lu-	sion
I	l u:	Z V n
il-	lu-	sions
I	l u:	Z V n z
il-	lu-	sive
I	l u:	s I v
il-	lu-	so-	ry
I	l u:	s @r	i:
il-	lust-	ra-	ted
I	l V s	t r eI	t V d
il-	lust-	ra-	ting
I	l V s	t r eI	t I N
il-	lust-	ra-	tion
I	l V s	t r eI	S V n
il-	lust-	ra-	tions
I	l V s	t r eI	S V n z
il-	lust-	ra-	tive
I	l V s	t r V	t I v
il-	lust-	ra-	tor
I	l V s	t r eI	t @r
il-	lust-	ra-	tors
I	l V s	t r eI	t @r z
il-	lust-	rate
I	l V s	t r eI t
il-	lust-	rates
I	l V s	t r eI t s
il-	lust-	ri-	ous
V	l V s	t r i:	V s
il-	ly-	ri-	an
V	l I@	i:	V n
il-	sa
I l	s V
il-	ya
I l	j V
iles
aI l z
ilk
I l k
ill
I l
i'll
aI l
ill-	nes-	ses
I l	n V	s V z
ill-	ness
I l	n V s
ills
I l z
ilse
I l s
im
I m
i'm
aI m
im-	ba-	lan-	ces
I m	b {	l V n	s V z
im-	ba-	lance
I m	b {	l V n s
im-	be-	cile
I m	b V	s V l
im-	bed
I m	b e d
im-	bed-	ded
I m	b e	d V d
im-	ber
I m	b @r
im-	bibe
I m	b aI b
im-	bibed
I m	b aI b d
im-	bo-	den
I m	b @U	d V n
im-	bro-	glio
I m	b r @U l	j @U
im-	bue
I m	b j u:
im-	bued
I m	b j u: d
im-	ma-	tu-	ri-	ty
I	m V	tS U@	V	t i:
im-	ma-	ture
I	m V t	j U@
im-	me-	di-	a-	cy
I	m i:	d i:	V	s i:
im-	me-	di-	ate
I	m i:	d i:	V t
im-	me-	di-	ate-	ly
I	m i:	d i:	V t	l i:
im-	me-	mo-	ri-	al
I	m V	m O@	i:	V l
im-	mea-	su-	ra-	ble
I	m e	Z @r	{	b V l
im-	mea-	su-	rab-	ly
I	m e	Z @r	{ b	l i:
im-	mense
I	m e n s
im-	mense-	ly
I	m e n	s l i:
im-	mer-	sion
I	m @r	Z V n
im-	merse
I	m @r s
im-	mersed
I	m @r s t
im-	mi-	nence
I	m I	n V n s
im-	mi-	nent
I	m I	n V n t
im-	mi-	nent-	ly
I	m I	n V n	t l i:
im-	mig-	ra-	ted
I	m I g	r eI	t I d
im-	mig-	ra-	tion
I	m I g	r eI	S V n
im-	mig-	rant
I	m I g	r V n t
im-	mig-	rants
I	m I g	r V n t s
im-	mig-	rant's
I	m I g	r V n t s
im-	mig-	rate
I	m I g	r eI t
im-	mis-	ci-	ble
I	m I	s V	b V l
im-	mo-	bi-	li-	ty
I	m @U	b I	l I	t i:
im-	mo-	bi-	li-	zing
I	m @U	b I	l aI	z I N
im-	mo-	bi-	lize
I	m @U	b I	l aI z z
im-	mo-	bi-	lized
I	m @U	b I	l aI z d
im-	mo-	bile
I	m @U	b V l
im-	mo-	ra-	li-	ty
I	m @r	{	l I	t i:
im-	mo-	ral
I	m O@	V l
im-	mo-	tile
I	m @U	t I l
im-	mo-	va-	ble
I	m u:	v V	b V l
im-	mor-	ta-	li-	ty
I	m O@	t {	l I	t i:
im-	mor-	ta-	li-	zes
I	m O@	t V	l aI	z V z
im-	mor-	ta-	li-	zing
I	m O@	t V	l aI	z I N
im-	mor-	ta-	lize
I	m O@	t V	l aI z
im-	mor-	ta-	lized
I	m O@	t V	l aI z d
im-	mor-	tal
I	m O@	t V l
im-	mor-	tals
I	m O@	t V l z
im-	mu-	ni-	ties
I m	j u:	n I	t i: z
im-	mu-	ni-	ty
I m	j u:	n I	t i:
im-	mu-	ni-	za-	tion
I m	j u:	n I	z eI	S V n
im-	mu-	ni-	za-	tions
I m	j u:	n I	z eI	S V n z
im-	mu-	ni-	zes
I m	j V	n aI	z V z
im-	mu-	ni-	zing
I m	j V	n aI	z I N
im-	mu-	nize
I m	j u:	n aI z
im-	mu-	nized
I m	j V	n aI z d
im-	mu-	no-	de-	fi-	cien-	cy
I m	j u:	n @U	d I	f I	S V n	s i:
im-	mu-	no-	lo-	gi-	cal
I m	j u:	n V	l Q	dZ I	k V l
im-	mu-	no-	lo-	gist
I m	j u:	n Q	l V	dZ V s t
im-	mu-	no-	lo-	gy
I m	j u:	n Q	l V	dZ i:
im-	mu-	no-	the-	ra-	py
I m	j u:	n @U	T e@	V	p i:
im-	mu-	ta-	ble
I m	j u:	t V	b V l
im-	mune
I m	j u: n
im-	pa-	la
I m	p Q	l V
im-	pa-	nel
I m	p {	n V l
im-	pa-	neled
I m	p {	n V l d
im-	pa-	tience
I m	p eI	S e n s
im-	pa-	tiens
I m	p eI	S e n z
im-	pa-	tient
I m	p eI	S e n t
im-	pa-	tient-	ly
I m	p eI	S e n	t l i:
im-	pac-	ted
I m	p { k	t V d
im-	pac-	ting
I m	p { k	t I N
im-	pact
I m	p { k t
im-	pacts
I m	p { k t s
im-	pai-	ring
I m	p e@	I N
im-	pair
I m	p e@
im-	pair-	ment
I m	p e@	m V n t
im-	pair-	ments
I m	p e@	m V n t s
im-	paired
I m	p e@ d
im-	pairs
I m	p e@ z
im-	pale
I m	p eI l
im-	paled
I m	p eI l d
im-	par-	ted
I m	p Q@	t V d
im-	par-	ti-	a-	li-	ty
I m	p Q@	S i:	{	l I	t i:
im-	par-	tial
I m	p Q@	S V l
im-	par-	tial-	ly
I m	p Q@	S V	l i:
im-	par-	ting
I m	p Q@	t I N
im-	part
I m	p Q@ t
im-	parts
I m	p Q@ t s
im-	pas-	sa-	ble
I m	p {	s V	b V l
im-	pas-	sion
I m	p {	S V n
im-	pas-	sioned
I m	p {	S V n d
im-	pas-	sive
I m	p {	s I v
im-	pas-	sive-	ly
I m	p {	s I v	l i:
im-	passe
I m	p { s
im-	pe-	dance
I m	p i:	d V n s
im-	pe-	ded
I m	p i:	d V d
im-	pe-	di-	ment
I m	p e	d I	m e n t
im-	pe-	di-	ments
I m	p e	d I	m e n t s
im-	pe-	ding
I m	p i:	d I N
im-	pe-	net-	ra-	ble
I m	p e	n V t	r V	b V l
im-	pe-	ra-	tive
I m	p e@	V	t I v
im-	pe-	ra-	tives
I m	p e@	V	t I v z
im-	pe-	ri-	a
I m	p i:	r i:	V
im-	pe-	ri-	a-	li-	sm
I m	p I@	i:	V	l I	z V m
im-	pe-	ri-	a-	lis-	tic
I m	p i:	r i:	V	l I s	t I k
im-	pe-	ri-	a-	list
I m	p I@	i:	V	l V s t
im-	pe-	ri-	a-	lists
I m	p I@	i:	V	l V s t s
im-	pe-	ri-	al
I m	p I@	i:	V l
im-	pe-	ri-	ling
I m	p e@	I	l I N
im-	pe-	ri-	ous
I m	p I@	i:	V s
im-	pe-	ril
I m	p e@	I l
)"
R"(im-	pe-	riled
I m	p e@	I l d
im-	pe-	rils
I m	p e@	I l z
im-	pe-	tuous
I m	p e tS	w V s
im-	pe-	tus
I m	p V	t V s
im-	pea-	cha-	ble
I m	p i:	tS V	b V l
im-	pea-	ches
I m	p i:	tS V z
im-	pea-	ching
I m	p i:	tS I N
im-	peach
I m	p i: tS
im-	peach-	ment
I m	p i: tS	m V n t
im-	peach-	ments
I m	p i: tS	m V n t s
im-	peached
I m	p i: tS t
im-	pec-	ca-	ble
I m	p e	k V	b V l
im-	pec-	cab-	ly
I m	p e	k V b	l i:
im-	pede
I m	p i: d
im-	pedes
I m	p i: d z
im-	pel
I m	p e l
im-	pelled
I m	p e l d
im-	pen-	ding
I m	p e n	d I N
im-	pend
I m	p e n d
im-	per-	cep-	ti-	ble
I m	p @r	s e p	t I	b V l
im-	per-	cep-	tib-	ly
I m	p @r	s e p	t I b	l i:
im-	per-	fec-	tion
I m	p @r	f e k	S V n
im-	per-	fec-	tions
I m	p @r	f e k	S V n z
im-	per-	fect
I m	p @r	f I k t
im-	per-	fect-	ly
I m	p @r	f I k	t l i:
im-	per-	mis-	si-	ble
I m	p @r	m I	s I	b V l
im-	per-	so-	na-	li-	ty
I m	p @r	s V	n {	l V	t i:
im-	per-	so-	na-	ted
I m	p @r	s V	n eI	t V d
im-	per-	so-	na-	ting
I m	p @r	s V	n eI	t I N
im-	per-	so-	na-	tion
I m	p @r	s V	n eI	S V n
im-	per-	so-	na-	tor
I m	p @r	s V	n eI	t @r
im-	per-	so-	na-	tors
I m	p @r	s V	n eI	t @r z
im-	per-	so-	nal
I m	p @r	s V	n V l
im-	per-	so-	nate
I m	p @r	s V	n eI t
im-	per-	ti-	nent
I m	p @r	t I	n e n t
im-	per-	vi-	ous
I m	p @r	v i:	V s
im-	pin-	ges
I m	p I n	dZ V z
im-	pinge
I m	p I n dZ
im-	pish
I m	p I S
im-	pla-	ca-	ble
I m	p l {	k V	b V l
im-	plan-	ta-	ble
I m	p l { n	t V	b V l
im-	plan-	ta-	tion
I m	p l { n	t eI	S V n
im-	plan-	ted
I m	p l { n	t V d
im-	plan-	ting
I m	p l { n	t I N
im-	plant
I m	p l { n t
im-	plants
I m	p l { n t s
im-	plau-	si-	ble
I m	p l O:	z I	b V l
im-	plau-	sib-	ly
I m	p l O:	z I b	l i:
im-	ple-	men-	ta-	tion
I m	p l V	m e n	t eI	S V n
im-	ple-	men-	ted
I m	p l V	m e n	t V d
im-	ple-	men-	ting
I m	p l V	m e n	t I N
im-	ple-	ment
I m	p l V	m V n t
im-	ple-	ments
I m	p l V	m V n t s
im-	pli-	ca-	ted
I m	p l I	k eI	t V d
im-	pli-	ca-	ting
I m	p l I	k eI	t I N
im-	pli-	ca-	tion
I m	p l I	k eI	S V n
im-	pli-	ca-	tions
I m	p l I	k eI	S V n z
im-	pli-	cate
I m	p l I	k eI t
im-	pli-	cates
I m	p l I	k eI t s
im-	pli-	cit
I m	p l I	s I t
im-	pli-	cit-	ly
I m	p l I	s I t	l i:
im-	ply
I m	p l aI
im-	ply-	ing
I m	p l aI	I N
im-	po-	li-	tic
I m	p O:	l I	t I k
im-	po-	lite
I m	p V	l aI t
im-	po-	ses
I m	p @U	z V z
im-	po-	si-	tion
I m	p V	z I	S V n
im-	po-	sing
I m	p @U	z I N
im-	po-	tence
I m	p V	t V n s
im-	po-	tent
I m	p V	t V n t
im-	pon-	de-	ra-	ble
I m	p Q n	d @r	V	b V l
im-	pon-	de-	ra-	bles
I m	p Q n	d @r	V	b V l z
im-	por-	ta-	tion
I m	p O@	t eI	S V n
im-	por-	tance
I m	p O@	t V n s
im-	por-	tant
I m	p O@	t V n t
im-	por-	tant-	ly
I m	p O@	t V n	t l i:
im-	por-	ted
I m	p O@	t V d
im-	por-	ter
I m	p O@	t @r
im-	por-	ters
I m	p O@	t @r z
im-	por-	ting
I m	p O@	t I N
im-	port
I m	p O@ t
im-	ports
I m	p O@ t s
im-	pos-	si-	bi-	li-	ty
I m	p O:	s I	b I	l I	t i:
im-	pos-	si-	ble
I m	p Q	s I	b V l
im-	pos-	sib-	ly
I m	p Q	s I b	l i:
im-	pos-	ter
I m	p O: s	t @r
im-	pos-	tor
I m	p O: s	t @r
im-	pos-	tors
I m	p O: s	t @r z
im-	pose
I m	p @U z
im-	posed
I m	p @U z d
im-	poun-	ded
I m	p aU n	d V d
im-	pound
I m	p aU n d
im-	pound-	ment
I m	p aU n	d m V n t
im-	pound-	ments
I m	p aU n	d m V n t s
im-	pove-	ri-	shes
I m	p Q v	r I	S V z
im-	pove-	rish
I m	p Q v	r I S
im-	pove-	rish-	ment
I m	p Q v	r I S	m V n t
im-	pove-	rished
I m	p Q v	r I S t
im-	pu-	ni-	ty
I m	p j u:	n I	t i:
im-	pu-	ri-	ties
I m	p j U@	I	t i: z
im-	pu-	ri-	ty
I m	p j U@	I	t i:
im-	pu-	ta-	tion
I m	p j V	t eI	S V n
im-	pu-	ted
I m	p j u:	t V d
im-	pug-	ning
I m	p j u:	n I N
im-	pugn
I m	p j u: n
im-	pugned
I m	p j u: n d
im-	pul-	ses
I m	p V l	s V z
im-	pul-	sive
I m	p V l	s I v
im-	pul-	sive-	ly
I m	p V l	s I v	l i:
im-	pulse
I m	p V l s
im-	pure
I m	p j U@
im-	pute
I m	p j u: t
im-	re
I m	r V
imp
I m p
imp-	lied
I m	p l aI d
imp-	lies
I m	p l aI z
imp-	lo-	ded
I m	p l @U	d V d
imp-	lo-	ding
I m	p l @U	d I N
imp-	lo-	ring
I m	p l O@	I N
imp-	lo-	sion
I m	p l @U	Z V n
imp-	lode
I m	p l @U d
imp-	lodes
I m	p l @U d z
imp-	lore
I m	p l O@
imp-	lored
I m	p l O@ d
imp-	lores
I m	p l O@ z
imp-	rac-	ti-	ca-	ble
I m	p r { k	t I	k V	b V l
imp-	rac-	ti-	cal
I m	p r { k	t I	k V l
imp-	re-	cise
I m	p r V	s aI s
imp-	re-	sa-	ri-	o
I m	p r e	s Q@	i:	@U
imp-	reg-	na-	ble
I m	p r e g	n V	b V l
imp-	reg-	na-	ted
I m	p r e g	n eI	t V d
imp-	reg-	na-	tion
I m	p r e g	n eI	S V n
imp-	reg-	nate
I m	p r e g	n eI t
imp-	res-	ses
I m	p r e	s V z
imp-	res-	sing
I m	p r e	s I N
imp-	res-	sio-	na-	ble
I m	p r e	S V	n V	b V l
imp-	res-	sio-	ni-	sm
I m	p r e	S V	n I	z V m
imp-	res-	sio-	nis-	tic
I m	p r e	S V	n I s	t I k
imp-	res-	sio-	nist
I m	p r e	S V	n I s t
imp-	res-	sio-	nists
I m	p r e	S V	n I s t s
imp-	res-	sion
I m	p r e	S V n
imp-	res-	sions
I m	p r e	S V n z
imp-	res-	sive
I m	p r e	s I v
imp-	res-	sive-	ly
I m	p r e	s I v	l i:
imp-	ress
I m	p r e s
imp-	ress-	ment
I m	p r e s	m V n t
imp-	ressed
I m	p r e s t
imp-	ri-	ma-	tur
I m	p r I	m Q	t @r
imp-	ri-	mis
I m	p r i:	m I s
imp-	ri-	so-	ning
I m	p r I	z V	n I N
imp-	ri-	son
I m	p r I	z V n
imp-	ri-	son-	ment
I m	p r I	z V n	m V n t
imp-	ri-	soned
I m	p r I	z V n d
imp-	rin-	ted
I m	p r I n	t V d
imp-	rin-	ting
I m	p r I n	t I N
imp-	rint
I m	p r I n t
imp-	rints
I m	p r I n t s
imp-	ro-	ba-	ble
I m	p r Q	b V	b V l
imp-	ro-	bab-	ly
I m	p r Q	b V b	l i:
imp-	ro-	per
I m	p r Q	p @r
imp-	ro-	per-	ly
I m	p r Q	p @r	l i:
imp-	ro-	vi-	sa-	tio-	nal
I m	p r Q	v I	z eI	S V	n V l
imp-	ro-	vi-	sa-	tion
I m	p r Q	v I	z eI	S V n
imp-	ro-	vi-	sa-	tions
I m	p r Q	v I	z eI	S V n z
imp-	ro-	vi-	sing
I m	p r V	v aI	z I N
imp-	ro-	ving
I m	p r u:	v I N
imp-	ro-	vise
I m	p r V	v aI z
imp-	ro-	vised
I m	p r V	v aI z d
imp-	romp-	tu
I m	p r Q m	p t u:
imp-	rop-	ri-	e-	ties
I m	p r V p	r aI	V	t i: z
imp-	rop-	ri-	e-	ty
I m	p r V p	r aI	V	t i:
imp-	rov
I m	p r Q v
imp-	rove
I m	p r u: v
imp-	rove-	ment
I m	p r u: v	m V n t
imp-	rove-	ments
I m	p r u: v	m V n t s
imp-	roved
I m	p r u: v d
imp-	roves
I m	p r u: v z
imp-	ru-	dence
I m	p r u:	d V n s
imp-	ru-	dent
I m	p r u:	d V n t
imp-	ru-	dent-	ly
I m	p r u:	d V n	t l i:
in
I n
in-	bo-	dy
I n	b Q	d i:
in-	board
I n	b O@ d
in-	born
I n	b O@ n
in-	bound
I n	b aU n d
in-	bred
I n	b r e d
in-	bree-	ding
I n	b r i:	d I N
in-	breed
I n	b r i: d
in-	ca
I N	k V
in-	ca-	pa-	ble
I n	k eI	p V	b V l
in-	ca-	pa-	ci-	ta-	ted
I n	k V	p {	s V	t eI	t V d
in-	ca-	pa-	ci-	ta-	ting
I n	k V	p {	s V	t eI	t I N
in-	ca-	pa-	ci-	ta-	tion
I n	k V	p {	s V	t eI	S V n
in-	ca-	pa-	ci-	tate
I n	k V	p {	s V	t eI t
in-	ca-	pa-	ci-	ty
I n	k V	p {	s V	t i:
in-	cal-	cu-	la-	ble
I n	k { l	k j V	l V	b V l
in-	can-	des-	cent
I n	k V n	d e	s V n t
in-	can-	ta-	tion
I n	k V n	t eI	S V n
in-	can-	ta-	to-	ry
I n	k { n	t V	t O@	i:
in-	cant
I n	k { n t
in-	car-	ce-	ra-	ted
I n	k Q@	s @r	eI	t V d
in-	car-	ce-	ra-	ting
I n	k Q@	s @r	eI	t I N
in-	car-	ce-	ra-	tion
I n	k Q@	s @r	eI	S V n
in-	car-	ce-	rate
I n	k Q@	s @r	eI t
in-	car-	na-	tion
I n	k Q@	n eI	S V n
in-	car-	na-	tions
I n	k Q@	n eI	S V n z
in-	car-	nate
I n	k Q@	n V t
in-	cas
I N	k V z
in-	case
I n	k eI s
in-	cen-	di-	a-	ry
I n	s e n	d i:	e@	i:
in-	cen-	tive
I n	s e n	t I v
in-	cen-	tives
I n	s e n	t I v z
in-	cense
I n	s e n s
in-	censed
I n	s e n s t
in-	cep-	tion
I n	s e p	S V n
in-	ces-	sant
I n	s e	s V n t
in-	ces-	sant-	ly
I n	s e	s V n	t l i:
in-	ces-	tuous
I n	s e s	tS w V s
in-	cest
I n	s e s t
in-	ches
I n	tS V z
in-	ching
I n	tS I N
in-	chon
I n	tS V n
in-	ci-	den-	ces
I n	s I	d e n	s V z
in-	ci-	den-	tal
I n	s I	d e n	t V l
in-	ci-	den-	tal-	ly
I n	s I	d e n	t V	l i:
in-	ci-	den-	tals
I n	s I	d e n	t V l z
in-	ci-	dence
I n	s I	d e n s
in-	ci-	dent
I n	s I	d e n t
in-	ci-	dents
I n	s I	d e n t s
in-	ci-	ne-	ra-	ted
I n	s I	n @r	eI	t I d
in-	ci-	ne-	ra-	ting
I n	s I	n @r	eI	t I N
in-	ci-	ne-	ra-	tion
I n	s I	n @r	eI	S V n
in-	ci-	ne-	ra-	tor
I n	s I	n @r	eI	t @r
in-	ci-	ne-	ra-	tors
I n	s I	n @r	eI	t @r z
in-	ci-	ne-	rate
I n	s I	n @r	eI t
in-	ci-	pi-	ent
I n	s I	p i:	e n t
in-	ci-	sion
I n	s I	Z V n
in-	ci-	sions
I n	s I	Z V n z
in-	ci-	sive
I n	s aI	s I v
in-	ci-	sor
I n	s aI	z @r
in-	ci-	sors
I n	s aI	z @r z
in-	ci-	ted
I n	s aI	t V d
in-	ci-	ting
I n	s aI	t I N
in-	ci-	vi-	li-	ty
I n	s I	v I	l I	t i:
in-	cise
I n	s aI z
in-	cised
I n	s aI z d
in-	cite
I n	s aI t
in-	cite-	ment
I n	s aI t	m V n t
in-	cite-	ments
I n	s aI t	m V n t s
in-	cites
I n	s aI t s
in-	cle-	ment
I n	k l e	m V n t
in-	cli-	na-	tion
I n	k l I	n eI	S V n
in-	cli-	na-	tions
I n	k l I	n eI	S V n z
in-	co-	he-	rence
I n	k @U	h I@	V n s
in-	co-	he-	rent
I n	k @U	h I@	V n t
in-	co-	he-	rent-	ly
I n	k @U	h I@	V n	t l i:
in-	co-	ming
I n	k V	m I N
in-	co-	or-	di-	na-	tion
I n	k @U	O@	d I	n eI	S V n
in-	cog-	ni-	to
I n	k O: g	n i:	t @U
in-	com-	mu-	ni-	ca-	do
I n	k V m	j u:	n V	k Q	d @U
in-	com-	pa-	ra-	ble
I n	k Q m	p @r	V	b V l
in-	com-	pa-	rab-	ly
I n	k Q m	p @r	V b	l i:
in-	com-	pa-	ti-	bi-	li-	ty
I n	k Q m	p V	t V	b I	l V	t i:
in-	com-	pa-	ti-	ble
I n	k V m	p {	t V	b V l
in-	com-	pe-	ten-	cy
I n	k Q m	p V	t V n	s i:
in-	com-	pe-	tence
I n	k Q m	p V	t V n s
in-	com-	pe-	tent
I n	k Q m	p V	t V n t
in-	com-	pe-	tent-	ly
I n	k Q m	p V	t V n	t l i:
in-	com-	pe-	tents
I N	k Q m	p V	t V n t s
in-	com-	pre-	hen-	si-	ble
I N	k Q m	p r V	h e n	s V	b V l
in-	com-	pres-	si-	ble
I n	k V m	p r e	s V	b V l
in-	come
I n	k V m
in-	comes
I n	k V m z
in-	comp-	lete
I n	k V m	p l i: t
in-	con-	cei-	va-	ble
I n	k V n	s i:	v V	b V l
in-	con-	clu-	sive
I n	k V n	k l u:	s I v
in-	con-	clu-	sive-	ly
I N	k Q n	k l u:	s I v	l i:
in-	con-	se-	quen-	tial
I N	k Q n	s V k	w e n	tS V l
in-	con-	sis-	ten-	cies
I N	k Q n	s I s	t e n	s i: z
in-	con-	sis-	ten-	cy
I n	k V n	s I s	t V n	s i:
in-	con-	sis-	tent
I n	k V n	s I s	t V n t
in-	con-	spi-	cuous
I N	k Q n	s p I k	w V s
in-	con-	ti-	nence
I n	k Q n	t I	n e n s
in-	con-	ti-	nent
I n	k Q n	t I	n e n t
in-	con-	ve-	nient
I n	k V n	v i: n	j V n t
in-	con-	veni-	en-	ces
I n	k V n	v i: n	j V n	s V z
in-	con-	veni-	ence
I n	k V n	v i: n	j V n s
in-	con-	veni-	enced
I n	k V n	v i: n	j V n s t
in-	cong-	ru-	i-	ty
I N	k O: N	r u:	I	t i:
in-	cong-	ru-	ous
I N	k O: N	r u:	V s
in-	cong-	ru-	ous-	ly
I N	k O: N	r u:	V s	l i:
in-	cons-	tan-	cy
I n	k Q n	s t V n	s i:
in-	cont-	ro-	ver-	ti-	ble
I N	k Q n	t r @U	v @r	t I	b V l
in-	cor-	po-	ra-	ted
I n	k O@	p @r	eI	t V d
in-	cor-	po-	ra-	ting
I n	k O@	p @r	eI	t I N
in-	cor-	po-	ra-	tion
I n	k O@	p @r	eI	S V n
in-	cor-	po-	ra-	tions
I n	k O@	p @r	eI	S V n z
in-	cor-	po-	ra-	tion's
I n	k O@	p @r	eI	S V n z
in-	cor-	po-	rate
I n	k O@	p @r	eI t
in-	cor-	po-	rates
I n	k O@	p @r	eI t s
in-	cor-	rect
I n	k @r	e k t
in-	cor-	rect-	ly
I n	k @r	e k	t l i:
in-	cor-	ri-	gi-	ble
I n	k Q@	I	dZ I	b V l
in-	cre-	di-	ble
I n	k r e	d I	b V l
in-	cre-	dib-	ly
I n	k r e	d I b	l i:
in-	cre-	du-	li-	ty
I n	k r V	d u:	l V	t i:
in-	cre-	du-	lous
I n	k r e	dZ V	l V s
in-	cre-	men-	ta-	li-	sm
I n	k r V	m e n	t V	l I	z V m
in-	cre-	men-	tal
I n	k r V	m e n	t V l
in-	cre-	men-	tal-	ly
I n	k r V	m e n	t V	l i:
in-	cre-	ment
I n	k r V	m V n t
in-	cre-	ments
I N	k r V	m V n t s
in-	crea-	ses
I n	k r i:	s V z
in-	crea-	sing
I n	k r i:	s I N
in-	crea-	sing-	ly
I n	k r i:	s I N	l i:
in-	crease
I n	k r i: s
in-	creased
I n	k r i: s t
in-	cri-	mi-	na-	ting
I n	k r I	m I	n eI	t I N
in-	cri-	mi-	na-	tion
I n	k r I	m I	n eI	S V n
in-	cri-	mi-	nate
I n	k r I	m I	n eI t
in-	crus-	ta-	tion
I n	k r V s	t eI	S V n
in-	crust
I n	k r V s t
in-	cu-	ba-	ting
I n	k j V	b eI	t I N
in-	cu-	ba-	tion
I N	k j u:	b eI	S V n
in-	cu-	ba-	tor
I N	k j V	b eI	t @r
in-	cu-	ba-	tors
I N	k j u:	b eI	t @r z
in-	cu-	bate
I n	k j V	b eI t
in-	cu-	ra-	ble
I n	k j U@	V	b V l
in-	cul-	ca-	ted
I N	k V l	k eI	t V d
in-	cul-	cate
I N	k V l	k eI t
in-	cul-	cates
I N	k V l	k eI t s
in-	cum-	ben-	cy
I n	k V m	b V n	s i:
in-	cum-	bent
I n	k V m	b V n t
in-	cum-	bents
I n	k V m	b V n t s
in-	cur
I n	k @r
in-	cur-	ring
I n	k @r	I N
in-	cur-	sion
I n	k @r	Z V n
in-	cur-	sions
I n	k @r	Z V n z
in-	curred
I n	k @r d
in-	curs
I n	k @r z
in-	da-	ba
I n	d Q	b V
in-	de-	cen-	cy
I n	d i:	s V n	s i:
in-	de-	cent
I n	d i:	s V n t
in-	de-	ci-	sion
I n	d V	s I	Z V n
in-	de-	ci-	sive
I n	d V	s aI	s I v
in-	de-	ci-	sive-	ness
I n	d e	s aI	s I v	n V s
in-	de-	fa-	ti-	ga-	ble
I n	d V	f {	t I	g V	b V l
in-	de-	fen-	si-	ble
I n	d V	f e n	s V	b V l
in-	de-	fi-	na-	ble
I n	d V	f aI	n V	b V l
in-	de-	fi-	nite
I n	d e	f I	n I t
in-	de-	fi-	nite-	ly
I n	d e	f I	n I t	l i:
in-	de-	li-	ble
I n	d e	l I	b V l
in-	de-	li-	bly
I n	d e	l I b	l i:
in-	de-	li-	cate
I n	d e	l I	k V t
in-	de-	pen-	den-	ce's
I n	d V	p e n	d V n	s V z
in-	de-	pen-	dence
I n	d V	p e n	d V n s
in-	de-	pen-	dent
I n	d V	p e n	d V n t
in-	de-	pen-	dent-	ly
I n	d V	p e n	d V n	t l i:
in-	de-	pen-	dents
I n	d V	p e n	d V n t s
in-	de-	ral
I n	d @r	V l
in-	de-	ter-	mi-	nate
I n	d V	t @r	m V	n V t
in-	de-	xa-	tion
I n	d e k	s eI	S V n
in-	de-	xer
I n	d e k	s @r
in-	de-	xers
I n	d e k	s @r z
in-	de-	xes
I n	d e k	s V z
in-	de-	xing
I n	d e k	s I N
in-	de-	x's
I n	d e k	s V z
in-	deb-	ted
I n	d e	t V d
in-	deb-	ted-	ness
I n	d e	t V d	n V s
in-	deed
I n	d i: d
in-	dem-	ni-	fi-	ca-	tion
I n	d e m	n I	f I	k eI	S V n
in-	dem-	ni-	fied
I n	d e m	n I	f aI d
in-	dem-	ni-	fy
I n	d e m	n I	f aI
in-	dem-	ni-	fy-	ing
I n	d e m	n I	f aI	I N
in-	dem-	ni-	ties
I n	d e m	n I	t i: z
in-	dem-	ni-	ty
I n	d e m	n I	t i:
in-	den-	ta-	tion
I n	d e n	t eI	S V n
in-	den-	ture
I n	d e n	tS @r
in-	den-	tured
I n	d e n	tS @r d
in-	den-	tures
I n	d e n	tS @r z
in-	dent
I n	d e n t
in-	des-	cri-	ba-	ble
I n	d V s	k r aI	b V	b V l
in-	des-	truc-	ti-	bi-	li-	ty
I n	d V s	t r V k	t V	b I	l V	t i:
in-	des-	truc-	ti-	ble
I n	d V s	t r V k	t V	b V l
in-	dex
I n	d e k s
in-	dexed
I n	d e k s t
in-	di-	a
I n	d i:	V
in-	di-	a-	na
I n	d i:	{	n V
in-	di-	a-	na-	po-	li-	s's
I n	d i:	V	n {	p V	l I	s V z
in-	di-	a-	na-	po-	lis
I n	d i:	V	n {	p V	l I s
in-	di-	a-	na's
I n	d i:	{	n V z
in-	di-	a-	ni-	an
I n	d i:	{	n i:	V n
in-	di-	a-	ni-	ans
I n	d i:	{	n i:	V n z
in-	di-	a-	no-	la
I n	d i:	V	n @U	l V
in-	di-	an
I n	d i:	V n
in-	di-	ans
I n	d i:	V n z
in-	di-	an's
I n	d i:	V n z
in-	di-	a's
I n	d i:	V z
in-	di-	ca-	ted
I n	d I	k eI	t I d
in-	di-	ca-	ting
I n	d I	k eI	t I N
in-	di-	ca-	tion
I n	d I	k eI	S V n
in-	di-	ca-	tions
I n	d I	k eI	S V n z
in-	di-	ca-	tive
I n	d I	k V	t I v
in-	di-	ca-	tor
I n	d I	k eI	t @r
in-	di-	ca-	tors
I n	d I	k eI	t @r z
in-	di-	cate
I n	d I	k eI t
in-	di-	cates
I n	d I	k eI t s
in-	di-	ces
I n	d I	s i: z
in-	di-	cia
I n	d I s	j V
in-	di-	ge-	nous
I n	d I	dZ V	n V s
in-	di-	ge-	nous-	ly
I n	d I	dZ V	n V s	l i:
in-	di-	gent
I n	d I	dZ V n t
in-	di-	gents
I n	d I	dZ V n t s
in-	di-	ges-	tion
I n	d aI	dZ e s	tS V n
in-	di-	gest
I n	d aI	dZ e s t
in-	di-	go
I n	d I	g @U
in-	di-	ted
I n	d aI	t V d
in-	di-	um
I n	d i:	V m
in-	di-	vi-	du-	a-	li-	sm
I n	d I	v I	d u:	V	l I	z V m
in-	di-	vi-	du-	a-	li-	ty
I n	d I	v I	dZ u:	{	l I	t i:
in-	di-	vi-	du-	a-	lis-	tic
I n	d I	v I	dZ u:	V	l I s	t I k
in-	di-	vi-	du-	a-	list
I n	d I	v I	d u:	V	l I s t
in-	di-	vi-	du-	a-	lists
I n	d I	v I	dZ u:	V	l I s t s
in-	di-	vi-	du-	a-	lize
I n	d I	v I	dZ u:	V	l aI z
in-	di-	vi-	du-	a-	lized
I n	d I	v I	dZ u:	V	l aI z d
in-	di-	vi-	du-	al
I n	d I	v I	dZ V	w V l
in-	di-	vi-	du-	al-	ly
I n	d I	v I	dZ u:	V	l i:
in-	di-	vi-	du-	als
I n	d I	v I	dZ V	w V l z
in-	di-	vi-	du-	al's
I n	d I	v I	dZ V	w V l z
in-	di-	vi-	si-	ble
I n	d I	v I	z I	b V l
in-	dic
I n	d I k
in-	dic-	ted
I n	d aI	t V d
in-	dic-	ting
I n	d aI	t I N
in-	dict
I n	d aI t
in-	dict-	ment
I n	d aI t	m V n t
in-	dict-	ments
I n	d aI t	m V n t s
in-	dies
I n	d i: z
in-	dif-	fe-	rence
I n	d I	f @r	V n s
in-	diffe-	rent
I n	d I f	r V n t
in-	dig-	na-	tion
I n	d I g	n eI	S V n
in-	dig-	nant
I n	d I g	n V n t
in-	dig-	nant-	ly
I n	d I g	n V n	t l i:
in-	dig-	ni-	ties
I n	d I g	n I	t i: z
in-	dig-	ni-	ty
I n	d I g	n I	t i:
in-	dis-	pen-	sa-	ble
I n	d I s	p e n	s V	b V l
in-	dis-	pu-	ta-	ble
I n	d I s	p j u:	t V	b V l
in-	dis-	pu-	ta-	bly
I n	d I s	p j u:	t V b	l i:
in-	dis-	tin-	gui-	sha-	ble
I n	d I s	t I N	g w I	S V	b V l
in-	dis-	tinct
I n	d I s	t I N k t
in-	disc-	re-	tion
I n	d I s	k r e	S V n
)"
R"(in-	disc-	re-	tions
I n	d V s	k r e	S V n z
in-	disc-	ri-	mi-	nate
I n	d I s	k r I	m I	n V t
in-	disc-	ri-	mi-	nate-	ly
I n	d I s	k r I	m I	n V t	l i:
in-	dite
I n	d aI t
in-	do
I n	d @U
in-	do-	chi-	na
I n	d @U	tS aI	n V
in-	do-	chi-	nese
I n	d @U	tS aI	n i: z
in-	do-	eu-	ro-	pe-	an
I n	d @U	j U@	V	p i:	V n
in-	do-	lent
I n	d V	l V n t
in-	do-	mi-	ta-	ble
I n	d Q	m I	t V	b V l
in-	do-	ne-	sia
I n	d @U	n i:	Z V
in-	do-	ne-	sian
I n	d @U	n i:	Z V n
in-	do-	ne-	sians
I n	d @U	n i:	Z V n z
in-	do-	ne-	sia's
I n	d @U	n i:	Z V z
in-	doc-	tri-	na-	ted
I n	d Q k	t r I	n eI	t I d
in-	doc-	tri-	na-	tion
I n	d Q k	t r I	n eI	S V n
in-	doc-	tri-	nate
I n	d Q k	t r I	n eI t
in-	door
I n	d O@
in-	doors
I n	d O@ z
in-	dri
I n	d r i:
in-	du-	ces
I n	d u:	s V z
in-	du-	cing
I n	d u:	s I N
in-	duc-	tance
I n	d V k	t V n s
in-	duc-	ted
I n	d V k	t V d
in-	duc-	tee
I n	d V k	t i:
in-	duc-	tees
I n	d V k	t i: z
in-	duc-	tion
I n	d V k	S V n
in-	duc-	tor
I n	d V k	t @r
in-	duce
I n	d u: s
in-	duce-	ment
I n	d u: s	m V n t
in-	duce-	ments
I n	d u: s	m V n t s
in-	duced
I n	d u: s t
)"