R"(cat-	chy
kh {	tS i:
cat-	kins
kh { t	k I n z
cat-	lett
kh { t	l e t
cat-	like
kh { t	l aI k
cat-	lin
kh { t	l I n
cat-	nap
kh { t	n { p
cat-	nip
kh { t	n I p
cat-	ron
kh { t	r V n
cat-	skill
kh { t	s k I l
cat-	skills
kh { t	s k I l z
cat-	sup
kh e	tS V p
cat-	tell
kh V	t e l
cat-	tle
kh {	t V l
cat-	tle-	men
kh {	t V l	m V n
cat-	to
kh {	t @U
cat-	ton
kh {	t V n
cat-	ty
kh {	t i:
cat-	walk
kh { t	w Q k
catch
kh { tS
catch-	all
kh {	tS O: l
catch-	up
kh {	tS V p
catch-	word
kh { tS	w @r d
cate
kh eI t
cath-	leen
kh { T	l i: n
cathe-	rine's
kh { T	r I n z
catho-	lic
kh { T	l I k
catho-	lics
kh { T	l I k s
cats
kh { t s
cat's
kh { t s
catt
kh { t
cau-	ca-	sian
kh O:	k eI	Z V n
cau-	ca-	sians
kh O:	k eI	Z V n z
cau-	ca-	sus
kh O:	k V	s V s
cau-	cu-	ses
kh O:	k V	s V z
cau-	cu-	s's
kh O:	k V	s V z
cau-	cus
kh Q	k V s
cau-	dal
kh Q	d V l
cau-	dil-	lo
kh O:	d I	l @U
cau-	dle
kh O:	d V l
cau-	ghey
kh O:	i:
cau-	li-	flo-	wer
kh Q	l I f	l aU	@r
cau-	sa-	li-	ties
kh O:	z {	l I	t i: z
cau-	sa-	li-	ty
kh O:	z {	l I	t i:
cau-	sa-	tion
kh O:	z eI	S V n
cau-	sa-	tive
kh Q	z V	t I v
cau-	sal
kh O:	z V l
cau-	ser
kh O:	z @r
cau-	ses
kh Q	z V z
cau-	sey
kh O:	z i:
cau-	sing
kh Q	z I N
cau-	tio-	na-	ry
kh O:	S V	n e@	i:
cau-	tio-	ning
kh O:	S V	n I N
cau-	tion
kh Q	S V n
cau-	tioned
kh Q	S V n d
cau-	tions
kh O:	S V n z
cau-	tious
kh O:	S V s
cau-	tious-	ly
kh O:	S V s	l i:
cau-	tious-	ness
kh O:	S V s	n V s
caught
kh Q t
caul
kh Q l
caul-	der
kh O: l	d @r
caul-	field
kh O: l	f i: l d
caul-	king
kh O:	k I N
cauld-	ron
kh Q l	d r V n
caulk
kh Q k
caus-	tic
kh Q s	t I k
cause
kh Q z
cause-	way
kh Q z	w eI
cause-	ways
kh O: z	w eI z
caused
kh Q z d
cave
kh eI v
cave-	man
kh eI v	m { n
caved
kh eI v d
caves
kh eI v z
cave's
kh eI v z
caw
kh O:
caw-	ley
kh O:	l i:
cax-	ton
kh { k	s t V n
cay
kh eI
cay-	enne
kh aI	e n
cay-	lor
kh eI	l @r
cay-	man
kh eI	m V n
cay-	mans
kh eI	m V n z
cayce
kh eI s
cayes
kh eI z
ce-	bu
s i:	b u:
ce-	bu's
s i:	b u: z
ce-	ce-	lia
s V	s i: l	j V
ce-	ci-	lia
s V	s i: l	j V
ce-	cil
s i:	s I l
ce-	cile
s V	s i: l
ce-	cil's
s i:	s I l z
ce-	dar
s i:	d @r
ce-	dars
s i:	d @r z
ce-	ded
s i:	d V d
ce-	der
s i:	d @r
ce-	ding
s i:	d I N
ce-	ja
s eI	j V
ce-	la
s e	l V
ce-	la-	don
s e	l V	d Q n
ce-	la-	nese
s e	l V	n i: z
ce-	la-	ya
s eI	l eI	V
ce-	lan-	dine
s e	l V n	d aI n
ce-	le-	ry
s e	l @r	i:
ce-	leb-	ra-	ted
s e	l V b	r eI	t V d
ce-	leb-	ra-	ting
s e	l V b	r eI	t I N
ce-	leb-	ra-	tion
s e	l V b	r eI	S V n
ce-	leb-	ra-	tions
s e	l V b	r eI	S V n z
ce-	leb-	ra-	to-	ry
s V	l e b	r V	t O@	i:
ce-	leb-	rant
s e	l V b	r V n t
ce-	leb-	rants
s e	l V b	r V n t s
ce-	leb-	rate
s e	l V b	r eI t
ce-	leb-	rates
s e	l V b	r eI t s
ce-	leb-	re
s e	l V b	r V
ce-	leb-	ri-	ties
s V	l e b	r V	t i: z
ce-	leb-	ri-	ty
s V	l e b	r V	t i:
ce-	lene
tS e	l i: n
ce-	les-	ta
s V	l e s	t V
ce-	les-	ti-	na
tS e	l e s	t i:	n V
ce-	les-	ti-	ne
tS e	l e s	t i:	n i:
ce-	les-	tial
s V	l e s	tS V l
ce-	leste
s V	l e s t
ce-	li-	ba-	cy
s e	l I	b V	s i:
ce-	li-	bate
s e	l I	b V t
ce-	li-	na
s V	l i:	n V
ce-	li-	o
s i:	l i:	@U
ce-	lia
s i: l	j V
ce-	lie
s e	l i:
ce-	lin-	da
tS e	l i: n	d V
ce-	line
s V	l i: n
ce-	lo-	si-	a
tS e	l @U	s i:	V
ce-	me-	te-	ries
s e	m V	t e@	i: z
ce-	me-	te-	ry
s e	m V	t e@	i:
ce-	men-	ted
s V	m e n	t V d
ce-	men-	ting
s V	m e n	t I N
ce-	ment
s V	m e n t
ce-	no-	zo-	ic
s i:	n V	z @U	I k
ce-	pha-	lo-	pod
s e	f V	l V	p Q d
ce-	pha-	lon
s e	f V	l Q n
ce-	pha-	los-	po-	rin
s e	f V	l O: s	p @r	V n
ce-	phas
s e	f V z
ce-	phus
s e	f V s
ce-	ra
s e@	V
ce-	ra-	ceous
s @r	eI	S V s
ce-	ra-	mic
s @r	{	m I k
ce-	ra-	mics
s @r	{	m I k s
ce-	re-	al
s I@	i:	V l
ce-	re-	als
s I@	i:	V l z
ce-	re-	li-	a
tS @r	e	l i:	V
ce-	re-	mo-	ni-	al
s e@	V	m @U	n i:	V l
ce-	re-	mo-	nies
s e@	V	m @U	n i: z
ce-	re-	mo-	ny
s e@	V	m @U	n i:
ce-	re-	no
s @r	eI	n @U
ce-	reb-	ral
s e@	V b	r V l
ce-	reb-	ral-	ly
s @r	i: b	r V	l i:
ce-	res
s I@	i: z
ce-	ryl
s e@	V l
ce-	sa-	re
tS eI	z Q@	eI
ce-	sa-	ro
tS e	s Q@	@U
ce-	sar
s i:	z @r
ce-	se-	na
tS e	s e	n V
ce-	si-	um
s i:	z i:	V m
ce-	ta
s e	t V
ce-	ta-	cean
s V	t eI	S V n
ce-	te-	ra
s e	t @r	V
ce-	tu-	s's
s i:	t V	s V z
ce-	tus
s i:	t V s
ce-	zanne
s e	z { n
cea-	ra
s i:	r V
cea-	ses
s i:	s V z
cea-	sing
s i:	s I N
cease
s i: s
cease-	fi-	re
s i: s	f aI	@r
cease-	fi-	res
s i: s	f aI	@r z
cease-	less
s i: s	l V s
cease-	less-	ly
s i: z	l V s	l i:
ceased
s i: s t
ceau-	ses-	cu
tS aU	tS e s	k j u:
ceau-	ses-	cu's
tS aU	tS e s	k j u: z
cece
s i: s
ced-	ric
s e d	r I k
cede
s i: d
cedes
s i: d z
cees
s i: z
cei-	ling
s i:	l I N
cei-	lings
s i:	l I N z
cel
s e l
cel-	la
s e	l V
cel-	lar
s e	l @r
cel-	lars
s e	l @r z
cel-	li
tS e	l i:
cel-	li-	ni
tS e	l i:	n i:
cel-	list
tS e	l I s t
cel-	lo
tS e	l @U
cel-	lo-	phane
s e	l V	f eI n
cel-	lu-	lar
s e l	j V	l @r
cel-	lu-	lar's
s e l	j V	l @r z
cel-	lu-	loid
s e	l V	l OI d
cel-	lu-	lose
s e l	j V	l @U s
cel-	si-	us
s e l	s i:	V s
cel-	tic
s e l	t I k
cel-	tics
s e l	t I k s
cele
s i: l
cell
s e l
cell-	net
s e l	n e t
cell-	phone
s e l	f @U n
celled
s e l d
cells
s e l z
cell's
s e l z
cels
s e l z
celt
s e l t
celts
s e l t s
cen-	ci
tS e n	tS i:
cen-	ser
s e n	s @r
cen-	so-	ring
s e n	s @r	I N
cen-	sor
s e n	s @r
cen-	sor-	ship
s e n	s @r	S I p
cen-	sored
s e n	s @r d
cen-	sors
s e n	s @r z
cen-	su-	ses
s e n	s V	s V z
cen-	sure
s e n	S @r
cen-	sured
s e n	S @r d
cen-	sus
s e n	s V s
cen-	ta-	vos
s e n	t Q	v @U s
cen-	taur
s e n	t O@
cen-	taurs
s e n	t O@ z
cen-	taur's
s e n	t O@ z
cen-	te-	na-	ri-	an
s e n	t V	n e@	i:	V n
cen-	te-	na-	ri-	ans
s e n	t V	n e@	i:	V n z
cen-	te-	na-	ry
s e n	t V	n e@	i:
cen-	te-	no
tS e n	t e	n @U
cen-	ten-	ni-	al
s e n	t e	n i:	V l
cen-	ter
s e n	t @r
cen-	ter-	fold
s e n	t @r	f @U l d
cen-	ter-	ing
s e n	t @r	I N
cen-	ter-	piece
s e n	t @r	p i: s
cen-	ter-	ville
s e n	t @r	v I l
cen-	tered
s e n	t @r d
cen-	ters
s e n	t @r z
cen-	ter's
s e n	t @r z
cen-	ti-	me-	ter
s e n	t I	m i:	t @r
cen-	ti-	me-	ters
s e n	t I	m i:	t @r z
cen-	ti-	pede
s e n	t I	p i: d
cen-	tig-	rade
s e n	t I g	r eI d
cen-	tig-	ram
s e n	t I g	r { m
cen-	time
s e n	t aI m
cen-	times
s e n	t aI m z
cen-	tre
s e n	t @r
cen-	tri-	fu-	gal
s e n	t r I f	j I	g V l
cen-	tri-	fu-	ges
s e n	t r I f	j u:	dZ V z
cen-	tri-	fuge
s e n	t r I f	j u: dZ
cen-	trist
s e n	t r I s t
cen-	trists
s e n	t r I s t s
cen-	tu-	ri-	on
s e n	t U@	i:	V n
cen-	tu-	ries
s e n	tS @r	i: z
cen-	tu-	ry
s e n	tS @r	i:
cen-	tu-	ry's
s e n	tS @r	i: z
cen-	tum
kh e n	t V m
cent
s e n t
cent-	ner
s e n	t n @r
cent-	ra-	li-	a
s e n	t r eI	l i:	V
cent-	ral
s e n	t r V l
cent-	rale
s e n	t r Q l
cent-	ro
s e n	t r @U
cents
s e n t s
cep
s e p
cer-	ise
s @r	i: s
cer-	nu-	da
s @r	n u:	d V
cer-	nu-	da's
s @r	n u:	d V z
cer-	ri-	to
tS @r	i:	t @U
cer-	ri-	tos
s e@	i:	t @U s
cer-	ro
s e@	@U
cer-	tain
s @r	t @ n
cer-	tain-	ly
s @r	t @ n	l i:
cer-	tain-	ties
s @r	t @ n	t i: z
cer-	tain-	ty
s @r	t @ n	t i:
cer-	ti-	fi-	ca-	tion
s @r	t I	f V	k eI	S V n
cer-	ti-	fi-	ca-	tions
s @r	t I	f V	k eI	S V n z
cer-	ti-	fi-	cate
s @r	t I	f I	k V t
cer-	ti-	fi-	cates
s @r	t I	f I	k V t s
cer-	ti-	fied
s @r	t I	f aI d
cer-	ti-	fies
s @r	t I	f aI z
cer-	ti-	fy
s @r	t I	f aI
cer-	ti-	fy-	ing
s @r	t I	f aI	I N
cer-	ti-	tude
s @r	t I	t u: d
cer-	ve-	ny
tS @r	v i:	n i:
cer-	ve-	ra
tS @r	v e@	V
cer-	vi-	cal
s @r	v I	k V l
cer-	vix
s @r	v I k s
cerf
s @r f
cern
s @r n
ces-	sa-	tion
s e	s eI	S V n
cess-	na
s e s	n V
cess-	na's
s e s	n V z
cess-	pool
s e s	p u: l
c'est
s e s t
cey-	lon
s V	l Q n
ch-	mie-	lew-	ski
tS V	m V	l e f	s k i:
cha
tS Q
cha-	bot
S V	b @U
cha-	chas
tS Q	tS Q z
cha-	con
tS {	k V n
cha-	di-	an
tS eI	d i:	V n
cha-	fee
tS {	f i:
cha-	fee's
tS eI	f i: z
cha-	fing
tS eI	f I N
cha-	gall
tS V	g Q l
cha-	im
h aI	I m
cha-	let
S {	l eI
cha-	lets
S V	l eI z
cha-	me-	le-	on
tS V	m e	l i:	V n
cha-	na
tS {	n V
cha-	nel
S V	n e l
cha-	ney
tS eI	n i:
cha-	nu-	kah
h Q	n V	k V
cha-	ny
tS eI	n i:
cha-	o-	tic
kh eI	Q	t I k
cha-	os
kh eI	Q s
cha-	pa
tS Q	p V
cha-	par-	ral
S {	p @r	{ l
cha-	par-	ro
kh Q	p Q@	@U
cha-	pe-	ro-	ning
S {	p @r	@U	n I N
cha-	pe-	rone
S {	p @r	@U n
cha-	pel
tS {	p V l
cha-	pell
S V	p e l
cha-	pel's
tS {	p V l z
cha-	pin
S V	p { n
cha-	rac-	te-	ri-	za-	tion
kh e@	V k	t @r	V	z eI	S V n
cha-	rac-	te-	ri-	za-	tions
tS e@	V k	t @r	V	z eI	S V n z
cha-	rac-	te-	ri-	zes
kh e@	V k	t @r	aI	z V z
cha-	rac-	te-	ri-	zing
kh e@	I k	t @r	aI	z I N
cha-	rac-	te-	ris-	tic
kh e@	V k	t @r	I s	t I k
cha-	rac-	te-	ris-	tical-	ly
kh e@	V k	t @r	I s	t I k	l i:
cha-	rac-	te-	ris-	tics
kh e@	V k	t @r	I s	t I k s
cha-	rac-	te-	rize
kh e@	V k	t @r	aI z
cha-	rac-	te-	rized
kh e@	V k	t @r	aI z d
cha-	rac-	ter
kh e@	I k	t @r
cha-	rac-	ters
kh {	r I k	t @r z
cha-	rac-	ter's
kh e@	I k	t @r z
cha-	rade
S @r	eI d
cha-	rades
S @r	eI d z
cha-	rette
S @r	e t
cha-	ri-	ot
tS e@	i:	V t
cha-	ri-	ots
tS e@	i:	V t s
cha-	ri-	ta
kh Q@	i:	t V
cha-	ri-	ta-	ble
tS e@	I	t V	b V l
cha-	ri-	tab-	ly
tS e@	I	t V b	l i:
cha-	ri-	ties
tS e@	I	t i: z
cha-	ri-	ty
tS e@	I	t i:
cha-	ri-	ty's
tS e@	I	t i: z
cha-	ris-	ma
kh @r	I z	m V
cha-	ris-	ma-	tic
kh e@	I z	m {	t I k
cha-	ris-	ma-	tics
kh e@	I z	m {	t I k s
cha-	ris-	sa
kh Q@	i:	s V
cha-	ron
kh e@	V n
cha-	ry
tS Q@	i:
cha-	ryl
tS {	r V l
cha-	ser
tS eI	s @r
cha-	sers
tS eI	s @r z
cha-	ses
tS eI	s V z
cha-	se's
tS eI	s V z
cha-	sing
tS eI	s I N
cha-	sm
kh {	z V m
cha-	teau
S {	t @U
cha-	teaux
S V	t @U
cha-	tham
tS {	t V m
cha-	vez
S Q	v e z
cha-	vin
tS eI	v I n
chab-	lis
S V b	l i:
chace
tS eI s
chad
tS { d
chad-	bourne
S V d	b U@ n
chad-	ron
tS { d	r V n
chad-	wick
tS { d	w I k
chad-	wick's
tS { d	w I k s
chadd
tS { d
chad's
tS { d z
chae
tS aI
chae-	bol
tS eI	b V l
chaf-	fee
tS {	f i:
chaf-	fin
tS {	f I n
chaf-	fy
tS {	f i:
chafe
tS eI f
chafed
tS eI f t
chafes
tS eI f s
chaff
tS { f
chag-	rin
S V g	r I n
chag-	rined
S V g	r I n d
chai
tS aI
chai-	ken
tS eI	k V n
chai-	ning
tS eI	n I N
chai-	ring
tS e@	I N
chain
tS eI n
chain-	saw
tS eI n	s O:
chain-	saws
tS eI n	s O: z
chained
tS eI n d
chains
tS eI n z
chain's
tS eI n z
chair
tS e@
chair-	man
tS e@	m V n
chair-	man-	ship
tS e@	m V n	S I p
chair-	man-	ships
tS e@	m V n	S I p s
chair-	man's
tS e@	m V n z
chair-	men
tS e@	m e n
chair-	per-	son
tS e@	p @r	s V n
chair-	wo-	man
tS e@	w U	m V n
chair-	wo-	men
tS e@	w I	m e n
chaired
tS e@ d
chairs
tS e@ z
chaise
S eI z
chait
tS eI t
chal-	ker
tS O:	k @r
chal-	king
tS O:	k I N
chal-	len-	ger
tS {	l V n	dZ @r
chal-	len-	gers
tS {	l V n	dZ @r z
chal-	len-	ger's
tS {	l V n	dZ @r z
chal-	len-	ges
tS {	l V n	dZ V z
chal-	len-	ging
tS {	l V n	dZ I N
chal-	lenge
tS {	l V n dZ
chal-	lenged
tS {	l V dZ d
chal-	lis
tS {	l I s
chal-	mers
tS Q	m @r z
chal-	mette
S { l	m e t
chalk
tS Q k
chalked
tS O: k t
chalks
tS O: k s
cham
tS { m
cham-	ber
tS eI m	b @r
cham-	ber-	lain
tS eI m	b @r	l I n
cham-	ber-	lain's
tS eI m	b @r	l I n z
cham-	ber-	lin
tS eI m	b @r	l I n
cham-	ber-	s's
tS eI m	b @r	z V z
cham-	bered
tS eI m	b @r d
cham-	bers
tS eI m	b @r z
cham-	ber's
tS eI m	b @r z
cham-	pi-	on-	ship
tS { m	p i:	V n	S I p
cham-	pi-	on-	ships
tS { m	p i:	V n	S I p s
cham-	pi-	ons
tS { m	p i:	V n z
cham-	pi-	on's
tS { m	p i:	V n z
chamb-	lee
tS { m	b l i:
champ-	lain
S { m	p l eI n
champ-	lin
tS { m	p l I n
champs
tS { m p s
chan
tS { n
chan-	ce-	ry
tS { n	s @r	i:
chan-	cel-	lor
tS { n	s V	l @r
chan-	cel-	lors
tS { n	s V	l @r z
chan-	cel-	lor's
tS { n	s V	l @r z
chan-	ces
tS { n	s V z
chan-	cey
tS { n	s i:
chan-	cy
tS { n	s i:
chan-	da
tS { n	d V
chan-	de-	lier
S { n	d V	l I@
chan-	de-	liers
S { n	d V	l I z
chan-	don
tS { n	d V n
chan-	gea-	ble
tS eI n	dZ V	b V l
chan-	geo-	ver
tS eI n	dZ @U	v @r
chan-	geo-	vers
tS eI n	dZ @U	v @r z
chan-	ger
tS eI n	dZ @r
chan-	gers
tS eI n	dZ @r z
chan-	ges
tS eI n	dZ V z
chan-	ging
tS eI n	dZ I N
chan-	ne-	ling
tS {	n V	l I N
chan-	nel
tS {	n V l
chan-	neled
tS {	n V l d
chan-	nels
tS {	n V l z
chan-	nel's
tS {	n V l z
chan-	ning
tS {	n I N
chan-	tal
tS { n	t V l
chan-	ted
tS { n	t V d
chan-	til-	ly
S { n	t I	l i:
chan-	ting
tS { n	t I N
chance
tS { n s
chand-	ler
tS { n	d l @r
chand-	ler's
tS { n	d l @r z
chand-	ra
tS { n	d r V
chang
tS { N
chang-	chun
tS Q N	tS U n
change
tS eI n dZ
changed
tS eI n dZ d
chan's
tS { n z
chant
tS { n t
chants
tS { n t s
chao
tS aU
chap
tS { p
chap-	lain
tS { p	l I n
chap-	lains
tS { p	l I n z
chap-	lin
tS { p	l I n
chap-	lin's
tS { p	l I n z
chap-	man
tS { p	m V n
chap-	man's
tS { p	m V n z
chap-	nick
tS { p	n I k
chap-	pa-	quid-	dick
tS {	p V k	w I	d I k
chap-	pel
tS {	p V l
chap-	pell
tS {	p V l
chap-	pie
tS {	p i:
chap-	ter
tS { p	t @r
chap-	ters
tS { p	t @r z
chapp
tS { p
chaps
tS { p s
char
tS Q@
char-	bon-	neau
S Q@	b V	n @U
char-	coal
tS Q@	k @U l
char-	coals
tS Q@	k @U l z
char-	don-	nay
tS Q@	d Q	n eI
char-	don-	nays
tS Q@	d Q	n eI z
char-	gea-	ble
tS Q@	dZ V	b V l
char-	ger
tS Q@	dZ @r
char-	gers
tS Q@	dZ @r z
char-	ges
tS Q@	dZ V z
char-	ging
tS Q@	dZ I N
char-	la
tS Q@	l V
char-	la-	tan
S Q@	l V	t V n
char-	la-	tans
S Q@	l V	t V n z
char-	le-	magne
S Q@	l V	m eI n
char-	leen
tS Q@	l i: n
char-	lene
S Q@	l i: n
char-	les-	worth
tS Q@	V l	s w @r T
char-	let
tS Q@	l V t
char-	ley
tS Q@	l i:
char-	ley's
tS Q@	l i: z
char-	lie
tS Q@	l i:
char-	lie's
tS Q@	l i: z
char-	line
S Q@	l i: n
char-	lot
tS Q@	l V t
char-	lotte
S Q@	l V t
char-	lotte-	town
S Q@	l V t	t aU n
char-	lotte-	ville
S Q@	l V t	v I l
char-	lotte's
S Q@	l V t s
char-	lottes-	ville
S Q@	l V t	s v I l
char-	main
S Q@	m eI n
char-	maine
S Q@	m eI n
char-	mer
tS Q@	m @r
char-	mers
tS Q@	m @r z
char-	mi-	an
tS Q@	m i:	V n
char-	mi-	on
tS Q@	m i:	V n
char-	ming
tS Q@	m I N
char-	ming-	ly
tS Q@	m I N	l i:
char-	nock
tS Q@	n V k
char-	pen-	tier
S Q@	p V n	t I@
char-	pie
tS Q@	p i:
char-	ri-	er
tS {	r i:	@r
char-	ring
tS Q@	I N
char-	ron
tS e@	V n
char-	ry
tS {	r i:
char-	ted
tS Q@	t V d
char-	ter
tS Q@	t @r
char-	ter-	house
tS Q@	t @r	h aU s
char-	ter-	ing
tS Q@	t @r	I N
char-	tered
tS Q@	t @r d
char-	ters
tS Q@	t @r z
char-	ter's
tS Q@	t @r z
char-	ting
tS Q@	t I N
char-	tist
tS Q@	t I s t
char-	tists
tS Q@	t I s t s
chard
tS Q@ d
charge
tS Q@ dZ
charged
tS Q@ dZ d
charl-	ton
tS Q@ l	t V n
charle-	s's
tS Q@ l	z V z
charles
tS Q@ l z
charles'
tS Q@ l z
charles-	ton
tS Q@ l	s t V n
charles-	ton's
tS Q@ l	s t V n z
charles-	town
tS Q@ l	z t aU n
charm
tS Q@ m
charmed
tS Q@ m d
charms
tS Q@ m z
charred
tS Q@ d
chart
tS Q@ t
chart-	res
tS Q@ t	r i: z
chart-	well
tS Q@ t	w e l
charts
tS Q@ t s
chas
tS Q@ l z
chas-	ka
tS { s	k V
chas-	sis
tS {	s i:
chas-	tain
S V s	t eI n
chas-	ten
tS eI	s V n
chas-	tened
tS eI	s V n d
chas-	ti-	ses
tS { s	t aI	z V z
chas-	ti-	sing
tS { s	t aI	z I N
chas-	ti-	ty
tS { s	t V	t i:
chas-	tise
tS { s	t aI z
chas-	tised
tS { s	t aI z d
chase
tS eI s
chased
tS eI s t
chasse
tS { s
chaste
tS eI s t
chat
tS { t
chat-	field
tS { t	f i: l d
chat-	ta-	hoo-	chee
tS {	t V	h u:	tS i:
chat-	ta-	hoo-	chee's
tS {	t V	h u:	tS i: z
chat-	ta-	noo-	ga
tS {	t V	n u:	g V
chat-	ta-	noo-	ga's
tS {	t V	n u:	g V z
chat-	te-	ring
tS {	t @r	I N
chat-	ted
tS {	t V d
chat-	tel
tS {	t V l
chat-	ter
tS {	t @r
chat-	ter-	jee
tS V	t @r	dZ i:
chat-	ter-	ton
tS {	t @r	t V n
chat-	ter-	ton's
tS {	t @r	t V n z
chat-	ting
tS {	t I N
chat-	ty
tS {	t i:
chat-	win
tS { t	w I n
chats
tS { t s
chats-	worth
tS { t	s w @r T
chau-	cer
tS O:	s @r
chau-	cer's
tS O:	s @r z
chau-	tau-	qua
S V	t O: k	w V
chau-	tau-	quan
S V	t O: k	w V n
chau-	tau-	quans
S V	t O: k	w V n z
chau-	vi-	ni-	sm
S @U	v I	n I	z V m
chau-	vi-	nis-	tic
tS @U	v I	n I s	t I k
chau-	vi-	nist
S @U	v I	n I s t
chau-	vin
S @U	v { n
chaudo-	in
S @U	d OI n
chauf-	feur
S @U	f @r
chauf-	feured
S @U	f @r d
chauf-	feurs
S @U	f @r z
chauf-	feur's
S @U	f @r z
chaun-	cey
tS O: n	s i:
chaunce
tS O: n s
chaus
tS aU s
chaus-	see
tS aU	s i:
chausse
tS aU s
chaves
tS eI v z
chaw
tS O:
che
tS eI
che-	chen
tS e	tS V n
che-	chens
tS e	tS V n z
che-	chen's
tS e	tS V n z
che-	khov
tS e	k Q v
che-	khov's
tS e	k Q v z
che-	lan
tS e	l V n
che-	mins
tS e	m I n z
che-	mise
S V	m i: z
che-	mist
kh e	m I s t
che-	mist-	ry
kh e	m I s	t r i:
che-	mists
kh e	m I s t s
che-	mo
kh i:	m @U
che-	mo-	the-	ra-	py
kh i:	m @U	T e@	V	p i:
che-	ney
tS eI	n i:
che-	ney's
tS eI	n i: z
)"
R"(che-	ni-	er
tS i:	n i:	@r
che-	no-	weth
tS e	n V	w e T
che-	ri
S e@	i:
che-	ri-	shes
tS e@	I	S V z
che-	rie
tS I@	i:
che-	rish
tS e@	I S
che-	rished
tS e@	I S t
che-	ro-	kee
tS e@	V	k i:
che-	ro-	kees
tS e@	V	k i: z
che-	ro-	kee's
tS e@	V	k i: z
che-	ru-	bi-	ni
kh @r	u:	b i:	n i:
che-	ru-	bic
tS @r	u:	b I k
che-	rub
tS e@	V b
che-	rubs
tS e@	V b z
che-	ry
tS e@	i:
che-	ryl
S e@	V l
che-	sa-	peake
tS e	s V	p i: k
che-	shire
tS e	S @r
che-	v-	ri-	er
tS e	v @r	i:	@r
che-	va-	lier
S e	v V	l I@
che-	ver-	ly
tS e	v @r	l i:
che-	vi-	ot
S e	v i:	V t
che-	vi-	ots
tS i:	v i:	V t s
che-	vies
tS e	v i: z
che-	vro-	let
S e v	r V	l eI
che-	vro-	lets
S e v	r V	l eI z
che-	vro-	let's
S e v	r V	l eI z
che-	vy
tS e	v i:
che-	vy's
tS e	v i: z
che-	wer
tS u:	@r
che-	wers
tS u:	@r z
che-	wy
tS u:	i:
chea-	dle
tS i:	d V l
chea-	pe-	ning
tS i:	p V	n I N
chea-	pen
tS i:	p V n
chea-	pened
tS i:	p V n d
chea-	per
tS i:	p @r
chea-	pest
tS i:	p V s t
chea-	po
tS i:	p @U
chea-	ted
tS i:	t V d
chea-	ter
tS i:	t @r
chea-	ters
tS i:	t @r z
chea-	tham
tS i:	t V m
chea-	ting
tS i:	t I N
cheap
tS i: p
cheap-	ly
tS i: p	l i:
cheap-	ness
tS i: p	n V s
cheaps-	kate
tS i: p	s k eI t
cheat
tS i: t
cheats
tS i: t s
chec-	ker
tS e	k @r
chec-	ker-	boar-	ding
tS e	k @r	b O@	d I N
chec-	ker-	board
tS e	k @r	b O@ d
chec-	ker-	boards
tS e	k @r	b O@ d z
chec-	kered
tS e	k @r d
chec-	kers
tS e	k @r z
chec-	kers-	pot
tS e	k @r s	p Q t
chec-	king
tS e	k I N
chec-	kup
tS e	k V p
chec-	kups
tS e	k V p s
chech-	n-	ya
tS e tS	n i:	V
chech-	n-	yan
tS e tS	n i:	V n
chech-	n-	yans
tS e tS	n i:	V n z
chech-	n-	ya's
tS e tS	n i:	V z
check
tS e k
check-	book
tS e k	b U k
check-	books
tS e k	b U k s
check-	list
tS e k	l I s t
check-	mate
tS e k	m eI t
check-	off
tS e	k O: f
check-	out
tS e	k aU t
check-	outs
tS e	k aU t s
check-	point
tS e k	p OI n t
check-	points
tS e k	p OI n t s
check-	up
tS e	k V p
checked
tS e k t
checks
tS e k s
ched-	dar
tS e	d @r
ched-	dars
tS e	d @r z
chee
tS i:
chee-	ky
tS i:	k i:
chee-	ri-	o
tS I@	i:	@U
chee-	ri-	os
tS I@	i:	@U s
chee-	ring
tS I@	I N
chee-	ry
tS I@	i:
chee-	ser
tS i:	z @r
chee-	ses
tS i:	z V z
chee-	si-	er
tS i:	z i:	@r
chee-	si-	est
tS i:	z i:	I s t
chee-	sy
tS i:	z i:
chee-	tah
tS i:	t V
chee-	tahs
tS i:	t V z
chee-	tal
tS i:	t V l
chee-	ver
tS i:	v @r
cheek
tS i: k
cheek-	bone
tS i: k	b @U n
cheek-	bones
tS i: k	b @U n z
cheek-	to-	wa-	ga
tS i: k	t V	w Q	g V
cheeked
tS i: k t
cheeks
tS i: k s
cheer
tS I@
cheer-	ful
tS I@	f V l
cheer-	ful-	ly
tS I@	f V	l i:
cheer-	lea-	der
tS I@	l i:	d @r
cheer-	lea-	ders
tS I@	l i:	d @r z
cheer-	lea-	ding
tS I@	l i:	d I N
cheered
tS I@ d
cheers
tS I@ z
cheese
tS i: z
cheese-	bur-	ger
tS i: z	b @r	g @r
cheese-	bur-	gers
tS i: z	b @r	g @r z
cheese-	cake
tS i: z	k eI k
chef
S e f
chefs
S e f s
chef's
S e f s
chel-	sea
tS e l	s i:
chel-	sea's
tS e l	s i: z
chelms-	ford
tS e l	m s f @r d
chen
tS e n
chen-	nault
tS e	n O: l t
cheng
tS e N
cheng-	du
tS e N	d u:
chen's
tS e n z
cher
S e@
cher-	bourg
S e@	b V r g
cher-	nen-	ko
tS @r	n e N	k @U
cher-	no-	byl
tS @r	n @U	b V l
cher-	no-	byl's
tS @r	n @U	b V l z
cher-	no-	myr-	din
tS e@	n @U	m I@	d I n
cher-	no-	myr-	din's
tS e@	n @U	m I@	d I n z
cher-	now
tS @r	n @U
cher-	ri-	er
tS e@	i:	@r
cher-	ries
tS e@	i: z
cher-	ry
tS e@	i:
cher-	rys-	tone
tS e@	i: s	t @U n
cher-	rys-	tones
tS e@	i: s	t @U n z
chert
tS @r t
cherts
tS @r t s
ches
tS e s
ches-	ney
tS e s	n i:
ches-	nut
tS e s	n V t
ches-	ser
tS e	s @r
ches-	ted
tS e s	t V d
ches-	ter
tS e s	t @r
ches-	ter-	field
tS e s	t @r	f i: l d
ches-	ter-	ton
tS e s	t @r	t V n
ches-	ton
tS e s	t V n
chess
tS e s
chess-	board
tS e s	b O@ d
chess-	man
tS e s	m V n
chest
tS e s t
chest-	nut
tS e s	n V t
chest-	nuts
tS e s	n V t s
chests
tS e s t s
chet
tS e t
chet-	niks
tS e t	n I k s
cheung
tS j u: N
chev-	rette
S I v	r e t
chev-	ron
S e v	r V n
chev-	ron's
S e v	r V n z
cheves
tS i: v z
chew
tS u:
chew-	ing
tS u:	I N
chewed
tS u: d
chews
tS u: z
chey-	enne
S aI	{ n
chey-	ennes
S aI	{ n z
chey-	enne's
S aI	{ n z
chey-	ney
tS eI	n i:
cheyne
tS eI n
chez
tS e z
chi
kh aI
chi-	a
tS i:	V
chi-	a-	pas
tS i:	Q	p V s
chi-	a-	vet-	ta
kh i:	Q	v e	t V
chi-	an-	ti
tS i:	{ n	t i:
chi-	at
tS i:	{ t
chi-	ba
tS i:	b V
chi-	ca-	go
S V	k Q	g @U
chi-	ca-	go-	ans
S V	k Q	g @U	V n z
chi-	ca-	goan
tS I	k V	g @U n
chi-	ca-	go's
S V	k Q	g @U z
chi-	ca-	ne-	ry
S I	k eI	n @r	i:
chi-	ca-	no
tS I	k Q	n @U
chi-	ca-	nos
tS I	k Q	n @U z
chi-	ches-	ter
tS I	tS e s	t @r
chi-	chi
tS i:	tS i:
chi-	co
tS i:	k @U
chi-	coine
tS I	k OI n
chi-	co's
tS i:	k @U z
chi-	ded
tS aI	d V d
chi-	des-	ter
tS I	d V s	t @r
chi-	ding
tS aI	d I N
chi-	hua-	hua
tS V	w Q	w Q
chi-	le
tS I	l i:
chi-	le-	an
tS I	l i:	V n
chi-	le-	ans
tS I	l i:	V n z
chi-	le's
tS I	l i: z
chi-	li
tS I	l i:
chi-	lies
tS I	l i: z
chi-	lis
tS I	l i: z
chi-	li's
tS I	l i: z
chi-	ma-	yo
tS I	m aI	@U
chi-	me-	ra
tS I	m e@	V
chi-	na
tS aI	n V
chi-	na-	town
tS aI	n V	t aU n
chi-	na's
tS aI	n V z
chi-	nese
tS aI	n i: z
chi-	no
tS i:	n @U
chi-	nook
S I	n U k
chi-	nooks
tS I	n U k s
chi-	qui-	ta
kh I k	w i:	t V
chi-	rac
S I@	{ k
chi-	rac's
S I@	{ k s
chi-	ri-	co
kh I@	i:	k @U
chi-	ron
tS aI	r V n
chi-	ron's
tS aI	r V n z
chi-	rop-	rac-	tic
kh aI	r @U p	r { k	t I k
chi-	rop-	rac-	tor
kh aI	r V p	r { k	t @r
chi-	rop-	rac-	tors
kh aI	r V p	r { k	t @r z
chi-	rop-	rac-	tor's
kh aI	r @U p	r { k	t @r z
chi-	sel
tS I	z V l
chi-	seled
tS I	z V l d
chi-	sels
tS I	z V l z
chi-	sholm
tS I	z V m
chi-	ta
tS i:	t V
chi-	ti-	nous
kh aI	t I	n V s
chiang
tS { N
chiang's
tS { N z
chic
S i: k
chic-	ka-	saw
tS I	k V	s O:
chic-	ka-	saws
tS I	k V	s O: z
chic-	ken
tS I	k V n
chic-	kened
tS I	k V n d
chic-	kens
tS I	k V n z
chic-	ken's
tS I	k V n z
chick
tS I k
chicks
tS I k s
chide
tS aI d
chides
tS aI d z
chief
tS i: f
chief-	dom
tS i: f	d V m
chief-	ly
tS i: f	l i:
chief-	tain
tS i: f	t V n
chief-	tains
tS i: f	t V n z
chief-	tain's
tS i: f	t V n z
chiefs
tS i: f s
chief's
tS i: f s
chien
tS e n
chieng-	mai
tS e N	m aI
chif-	fon
S I	f Q n
chig-	gers
tS I	g @r z
chil-	cote
tS I l	k @U t
chil-	ders
tS I l	d @r z
chil-	dish
tS aI l	d I S
chil-	ler
tS I	l @r
chil-	li-	cothe
tS I	l I	k O: T
chil-	li-	er
tS I	l i:	@r
chil-	lies
tS I	l i: z
chil-	ling
tS I	l I N
chil-	ling-	ly
tS I	l I N	l i:
chil-	ly
tS I	l i:
chil-	mark
tS I l	m Q@ k
chil-	son
tS I l	s V n
chil-	ton
tS I l	t V n
child
tS aI l d
child-	bea-	ring
tS aI l	d b e@	I N
child-	birth
tS aI l	d b @r T
child-	care
tS aI l	d k e@
child-	hood
tS aI l	d h U d
child-	hoods
tS aI l	d h U d z
child-	less
tS aI l	d l V s
child-	like
tS aI l	d l aI k
child-	ren
tS I l	d r V n
child-	ren's
tS I l	d r V n z
child-	ress
tS I l	d r V s
childe
tS I l d
childs
tS aI l d z
child's
tS aI l d z
chiles
tS aI l z
chill
tS I l
chilled
tS I l d
chills
tS I l z
chim-	ney
tS I m	n i:
chim-	neys
tS I m	n i: z
chim-	pan-	zee
tS I m	p { n	z i:
chim-	pan-	zees
tS I m	p { n	z i: z
chime
tS aI m
chimed
tS aI m d
chimes
tS aI m z
chimp
tS I m p
chimps
tS I m p s
chin
tS I n
chin-	chil-	la
tS I n	tS I	l V
ching
tS I N
chink
tS I N k
chinks
tS I N k s
chint-	zy
tS I n	t s i:
chip
tS I p
chip-	board
tS I p	b O@ d
chip-	ley
tS I p	l i:
chip-	man
tS I p	m V n
chip-	pe-	wa
tS I	p V	w Q
chip-	per
tS I	p @r
chip-	ping
tS I	p I N
chip-	py
tS I	p i:
chipped
tS I p t
chips
tS I p s
chip's
tS I p s
chir-	ping
tS @r	p I N
chir-	py
tS @r	p i:
chirp
tS @r p
chirps
tS @r p s
chi's
kh aI z
chit
tS I t
chit-	chat
tS I t	tS { t
chit-	ra
tS I t	r V
chit-	ten-	den
tS I	t V n	d V n
chit-	ty
tS I	t i:
chits
tS I t s
chlo-	e
kh l @U	i:
chlo-	rate
kh l O@	eI t
chlo-	ri-	na-	ted
kh l O@	I	n eI	t I d
chlo-	ri-	na-	ting
kh l O@	I	n eI	t I N
chlo-	ri-	nate
kh l O@	I	n eI t
chlo-	ride
kh l O@	aI d
chlo-	rine
kh l O@	i: n
chlo-	ris
kh l O@	I s
chlo-	ro-	fluo-	ro-	car-	bon
kh l O@	@U f	l O@	@U	k Q@	b Q n
chlo-	ro-	fluo-	ro-	car-	bons
kh l O@	@U f	l O@	@U	k Q@	b Q n z
chlo-	ro-	form
kh l O@	V	f O@ m
chlo-	ro-	phyll
kh l O@	V	f I l
chlo-	rop-	last
kh l O@	V p	l { s t
chlo-	rop-	lasts
kh l O@	V p	l { s t s
chlo-	rop-	rene
kh l O@	V p	r i: n
chlor-	dane
kh l O@	d eI n
cho
tS @U
cho-	ir
kh w aI	@r
cho-	king
tS @U	k I N
cho-	le-	ra
kh Q	l @r	V
cho-	le-	ric
kh Q	l @r	I k
cho-	les-	te-	rol
kh V	l e s	t @r	O: l
cho-	les-	ty-	ra-	mine
tS @U	l e s	t I@	V	m aI n
cho-	pin
S @U	p { n
cho-	ral
kh O@	V l
cho-	rals
kh O@	V l z
cho-	re-	o-	gra-	pher
kh O@	i:	Q g	r V	f @r
cho-	re-	o-	gra-	phers
kh O@	i:	Q g	r V	f @r z
cho-	re-	o-	gra-	pher's
kh O@	i:	Q g	r V	f @r z
cho-	re-	o-	gra-	phic
kh O@	i:	V g	r {	f I k
cho-	re-	o-	gra-	phing
kh O@	i:	Q g	r V	f I N
cho-	re-	o-	gra-	phy
kh O@	i:	Q g	r V	f i:
cho-	re-	o-	graph
kh O@	i:	V g	r { f
cho-	re-	o-	graphed
kh O@	i:	V g	r { f t
cho-	ric
kh O@	I k
cho-	ru-	ses
kh O@	V	s V z
cho-	rus
kh O@	V s
cho-	sen
tS @U	z V n
choate
tS @U t
chock
tS Q k
choco-	late
tS O: k	l V t
choco-	lates
tS O: k	l V t s
choi
tS OI
choi-	cer
tS OI	s @r
choi-	ces
tS OI	s V z
choi-	cest
tS OI	s V s t
choice
tS OI s
choirs
kh w aI r z
chok
tS Q k
choke
tS @U k
choke-	hold
tS @U k	h @U l d
choked
tS @U k t
chokes
tS @U k s
chol-	la
tS Q	l V
chom-	ping
tS Q m	p I N
chomp
tS Q m p
chon
tS Q n
chong
tS O: N
chong-	qing
tS O: N	k I N
choo
tS u:
choo-	ses
tS u:	z V z
choo-	sing
tS u:	z I N
choo-	sy
tS u:	z i:
choong
tS u: N
choose
tS u: z
chop
tS Q p
chop-	per
tS Q	p @r
chop-	pers
tS Q	p @r z
chop-	per's
tS Q	p @r z
chop-	ping
tS Q	p I N
chop-	py
tS Q	p i:
chop-	ra
tS Q p	r V
chop-	stick
tS Q p	s t I k
chop-	sticks
tS Q p	s t I k s
chop-	su-	ey
tS Q p	s u:	i:
chopped
tS Q p t
chops
tS Q p s
chor-	dates
kh O@	d eI t s
chor-	t-	ling
tS O@	t V	l I N
chor-	tle
tS O@	t V l
chor-	tled
tS O@	t V l d
chor-	tles
tS O@	t V l z
chord
kh O@ d
chords
kh O@ d z
chore
tS O@
chores
tS O@ z
chose
tS @U z
chou
tS u:
chow
tS aU
chow-	der
tS aU	d @r
chows
tS aU z
choy
tS OI
chre-	tien
S r I	t i: n
chri-	sta
kh r I s	t V
chri-	sta-	belle
S r I s	t V	b V l
chris
kh r I s
chris-	man
kh r I s	m V n
chris-	mon
kh r I z	m V n
chris-	sie
kh r I	s i:
chris-	sy
kh r I	s i:
chris-	tal
kh r I s	t V l
chris-	te-	ning
kh r I	s V	n I N
chris-	tel
kh r I s	t V l
chris-	ten
kh r I	s V n
chris-	ten-	dom
kh r I	s V n	d V m
chris-	ten-	sen
kh r I s	t V n	s V n
chris-	ten-	son
kh r I s	t V n	s V n
chris-	tened
kh r I	s V n d
chris-	ti
kh r I s	t i:
chris-	ti-	a-	na
kh r I s	t i:	{	n V
chris-	ti-	a-	ni-	ty
kh r I s	tS i:	{	n V	t i:
chris-	ti-	a-	no
kh r i: s	t i:	Q	n @U
chris-	ti-	an-	na
kh r I s	t i:	{	n V
chris-	ti-	ane
kh r I s	t i:	Q n
chris-	ti-	na
kh r I s	t i:	n V
chris-	tia-	an
kh r I s	t i:	Q n
chris-	tia-	ni-	za-	tion
kh r I s	tS V	n V	z eI	S V n
chris-	tia-	nize
kh r I s	tS V	n aI z
chris-	tia-	nized
kh r I s	tS V	n aI z d
chris-	tian
kh r I s	tS V n
chris-	tian-	sen
kh r I s	tS V n	s V n
chris-	tian-	son
kh r I s	tS V n	s V n
chris-	tians
kh r I s	tS V n z
chris-	tie
kh r I s	t i:
chris-	ties
kh r I s	t i: z
chris-	tie's
kh r I s	t i: z
chris-	tine
kh r I s	t i: n
chris-	tine's
kh r I s	t i: n z
chris-	to-	pher
kh r I s	t V	f @r
chris-	to-	pher's
kh r I s	t V	f @r z
chris-	tof-	fel
kh r I s	t V	f e l
chris-	toff
kh r I s	t O: f
chris-	toph
kh r I s	t O: f
chris-	tophe
kh r I s	t r O: f
chris-	ty
kh r I s	t i:
chris-	ty's
kh r I s	t i: z
christ
kh r aI s t
christ-	church
kh r aI s	t tS @r tS
christ-	ma-	ses
kh r I s	m V	s V z
christ-	mann
kh r I s	t m V n
christ-	mas
kh r I s	m V s
christ-	mas-	time
kh r I s	t m V s	t aI m
christ's
kh r aI s t s
chro-	ma-	to-	gra-	phy
kh r @U	m V	t Q g	r V	f i:
chro-	ma-	to-	gram
kh r @U	m {	t V g	r { m
chro-	ma-	to-	grams
kh r @U	m {	t V g	r { m z
chro-	mi-	nance
kh r @U	m I	n V n s
chro-	mi-	um
kh r @U	m i:	V m
chro-	mo-	some
kh r @U	m V	s @U m
chro-	mo-	somes
kh r @U	m V	z @U m z
chro-	ni-	cal-	ly
kh r Q	n I	k V	l i:
chro-	ni-	cle
kh r Q	n I	k V l
chro-	ni-	cled
kh r Q	n I	k V l d
chro-	ni-	cler
kh r Q	n I k	l @r
chro-	ni-	clers
kh r Q	n I k	l @r z
chro-	ni-	cles
kh r Q	n I	k V l z
chro-	ni-	cle's
kh r Q	n I	k V l z
chro-	nic
kh r Q	n I k
chro-	nic-	ling
kh r Q	n I k	l I N
chro-	no-	lo-	gy
kh r V	n Q	l V	dZ i:
chrome
kh r @U m
chry-	san-	the-	mum
kh r V	s { n	T V	m V m
chry-	san-	the-	mums
kh r V	s { n	T V	m V m z
chry-	seis
kh r I	s V z
chrys-	ler
kh r aI s	l @r
chrys-	lers
kh r aI s	l @r z
chrys-	ler's
kh r aI s	l @r z
chrys-	tal
kh r I s	t V l
chu
tS u:
chu-	ah
tS u:	Q
chu-	i
kh u:	I
chu-	la
tS u:	l V
chu-	ra
tS U@	V
chub-	by
tS V	b i:
chubb
tS V b
chubb's
tS V b z
chuc-	kie
tS V	k i:
chuc-	king
tS V	k I N
chuc-	kle
tS V	k V l
chuc-	kled
tS V	k V l d
chuc-	kles
tS V	k V l z
chuck
tS V k
chuck-	a-	luck
tS V	k V	l V k
chuck-	ling
tS V k	l I N
chucked
tS V k t
chuck's
tS V k s
chug
tS V g
chug-	ging
tS V	g I N
chugged
tS V g d
chuk-	chi
tS u: k	tS i:
chum
tS V m
chum-	ley
tS V m	l i:
chum-	my
tS V	m i:
chump
tS V m p
chums
tS V m z
chun
tS V n
chun-	ky
tS V N	k i:
chun-	nel
tS V	n V l
chung
tS V N
chung's
tS V N z
chunk
tS V N k
chunks
tS V N k s
chun's
tS V n z
chur-	ches
tS @r	tS V z
chur-	chill
tS @r	tS I l
chur-	chill's
tS @r	tS I l z
chur-	ch's
tS @r	tS V z
chur-	lish
tS @r	l I S
chur-	ning
tS @r	n I N
church
tS @r tS
church-	go-	er
tS @r tS	g @U	@r
church-	go-	ers
tS @r tS	g @U	@r z
church-	go-	ing
tS @r tS	g @U	I N
church-	man
tS @r tS	m V n
church-	men
tS @r tS	m V n
church-	yard
tS @r tS	j Q@ d
churn
tS @r n
churned
tS @r n d
churns
tS @r n z
chuse
tS j u: z
chut-	ney
tS V t	n i:
chute
S u: t
chutes
S u: t s
chutz-	pah
tS V t	s p Q
ci-	a
s i:	V
ci-	a-	no
tS i:	Q	n @U
ci-	ca-	da
s V	k eI	d V
ci-	ca-	das
s I	k eI	d V z
ci-	ca-	la
s I	k Q	l V
ci-	ce-	ly
s I	s V	l i:
ci-	ce-	ro
s I	s @r	@U
ci-	ce-	rone
s I	s @r	@U n
ci-	cho-	cki
s I	tS Q	k i:
ci-	ci-	ly
tS I	tS I	l i:
ci-	der
s aI	d @r
ci-	ga-	rette
s I	g @r	e t
ci-	ga-	rettes
s I	g @r	e t s
ci-	ga-	rette's
s I	g @r	e t s
ci-	gar
s I	g Q@
ci-	gars
s I	g Q@ z
ci-	lan-	tro
s V	l { n	t r @U
ci-	li-	ates
s I	l i:	V t s
ci-	li-	cia
s V	l I	S V
ci-	ma
tS i:	m V
ci-	mar-	ron
s I	m @r	Q n
ci-	ne-	ma
s I	n V	m V
ci-	ne-	ma-	tic
s I	n V	m {	t I k
ci-	ne-	ma-	to-	gra-	pher
s I	n V	m V	t Q g	r V	f @r
ci-	ne-	ma-	to-	gra-	phy
s I	n V	m V	t Q g	r V	f i:
ci-	ne-	mas
s I	n V	m V z
ci-	ne-	ma's
s I	n V	m V z
ci-	ne-	plex
s I	n V p	l e k s
ci-	nel-	li
s V	n e	l i:
ci-	ni
tS i:	n i:
ci-	pher
s aI	f @r
ci-	ra
s @r	V
ci-	ril-	lo
s I@	I	l @U
ci-	rone
s I@	@U n
ci-	ti-	bank
s I	t i:	b { N k
ci-	ti-	bank's
s I	t i:	b { N k s
ci-	ti-	corp
s I	t i:	k O@ p
ci-	ti-	zen
s I	t I	z V n
ci-	ti-	zen-	ry
s I	t I	z V n	r i:
ci-	ti-	zen-	ship
s I	t I	z V n	S I p
ci-	ti-	zens
s I	t I	z V n z
ci-	ti-	zen's
s I	t I	z V n z
ci-	ti-	zens'
s I	t I	z V n z
ci-	ties
s I	t i: z
ci-	ting
s aI	t I N
ci-	ty
s I	t i:
ci-	ty-	wide
s I	t i:	w aI d
ci-	ty's
s I	t i: z
ci-	u-	dad
s i:	u:	d { d
ci-	vet
s I	v V t
ci-	vi-	li-	ty
s V	v I	l V	t i:
ci-	vi-	li-	za-	tion
s I	v I	l V	z eI	S V n
ci-	vi-	li-	za-	tions
s I	v I	l V	z eI	S V n z
ci-	vi-	lian
s V	v I l	j V n
ci-	vi-	lians
s V	v I l	j V n z
ci-	vi-	lize
s I	v I	l aI z
ci-	vi-	lized
s I	v I	l aI z d
ci-	vic
s I	v I k
ci-	vics
s I	v I k s
ci-	vil
s I	v I l
ci-	vil-	ly
s I	v I	l i:
ciar-	di
tS @r	d i:
cid
s I d
cie
s i:
ciel
s i: l
cin-	cin-	na-	ti
s I n	s I	n {	t i:
cin-	cin-	na-	ti's
s I n	s I	n {	t i: z
cin-	de-	rel-	la
s I n	d @r	e	l V
cin-	der
s I n	d @r
cin-	ders
s I n	d @r z
cin-	die
s aI n	d i:
cin-	dy
s I n	d i:
cin-	dy's
s I n	d i: z
cin-	na-	bar
s I	n V	b Q@
cin-	na-	mon
s I	n V	m V n
cinch
s I n tS
cinched
s I n tS t
cinque
s I N k
cir-	c-	ling
s @r	k V	l I N
cir-	ca
s @r	k V
cir-	ca-	di-	an
s @r	k eI	d i:	V n
cir-	cle
s @r	k V l
cir-	cled
s @r	k V l d
cir-	cles
s @r	k V l z
cir-	cle's
s @r	k V l z
cir-	cu-	i-	tous
s @r k	j u:	I	t V s
cir-	cu-	la-	ted
s @r k	j V	l eI	t V d
cir-	cu-	la-	ting
s @r k	j V	l eI	t I N
cir-	cu-	la-	tion
s @r k	j V	l eI	S V n
cir-	cu-	la-	tions
s @r k	j V	l eI	S V n z
cir-	cu-	la-	to-	ry
s @r k	j V	l V	t O@	i:
cir-	cu-	lar
s @r k	j V	l @r
cir-	cu-	lar-	ly
s @r k	j V	l @r	l i:
cir-	cu-	lars
s @r k	j V	l @r z
cir-	cu-	late
s @r k	j V	l eI t
cir-	cu-	lates
s @r k	j V	l eI t s
cir-	cu-	ses
s @r	k V	s V z
cir-	cu-	s's
s @r	k V	s V z
cir-	cui-	ted
s @r	k I	t V d
cir-	cuit
s @r	k I t
cir-	cuit-	ry
s @r	k I t	r i:
)"
R"(cir-	cuits
s @r	k I t s
cir-	cuit's
s @r	k I t s
cir-	cum-	ci-	sion
s @r	k V m	s I	Z V n
cir-	cum-	cise
s @r	k V m	s aI z
cir-	cum-	cised
s @r	k V m	s aI z d
cir-	cum-	scribe
s @r	k V m	s k r aI b
cir-	cum-	scribed
s @r	k V m	s k r aI b d
cir-	cum-	stan-	ces
s @r	k V m	s t { n	s V z
cir-	cum-	stan-	tial
s @r	k V m	s t { n	tS V l
cir-	cum-	stan-	tial-	ly
s @r	k V m	s t { n	tS V	l i:
cir-	cum-	stance
s @r	k V m	s t { n s
cir-	cum-	ven-	ted
s @r	k V m	v e n	t V d
cir-	cum-	ven-	ting
s @r	k V m	v e n	t I N
cir-	cum-	ven-	tion
s @r	k V m	v e n	tS V n
cir-	cum-	vent
s @r	k V m	v e n t
cir-	cum-	vents
s @r	k V m	v e n t s
cir-	cumfe-	rence
s @r	k V m	f r V n s
cir-	cums-	pec-	tion
s @r	k V m	s p e k	S V n
cir-	cums-	pect
s @r	k V m	s p e k t
cir-	cus
s @r	k V s
cir-	rho-	sis
s @r	@U	s I s
cir-	rus
s I@	V s
cirque
s @r k
cis-	co
s I s	k @U
cis-	co's
s I s	k @U z
cis-	kei
s I s	k eI
cis-	ne-	ros
s I s	n e@	@U s
cis-	sie
s I	s i:
cist
s I s t
cit-	ric
s I t	r I k
cit-	rin
s I t	r I n
cit-	rine
s I t	r i: n
cit-	ro-	nel-	la
s I t	r Q	n e	l V
cit-	roen
s I t	r @U n
cit-	ron
s I t	r V n
cit-	ron's
s I t	r V n z
cit-	ru-	s's
s I t	r V	s V z
cit-	rus
s I t	r V s
cla-	bo
kh l Q	b @U
cla-	flin
kh l { f	l I n
cla-	mor
kh l {	m @r
cla-	mor-	ing
kh l {	m @r	I N
cla-	mored
kh l {	m @r d
cla-	pham
kh l {	f V m
cla-	ra
kh l {	r V
cla-	ra-	belle
kh l {	r V	b e l
cla-	ra-	mae
kh l Q@	Q	m aI
cla-	ren-	don
kh l e@	V n	d V n
cla-	rence
kh l e@	V n s
cla-	res-	ta
kh l Q@	e s	t V
cla-	rette
kh l @r	e t
cla-	rey
kh l {	r i:
cla-	ri-	bel
kh l e@	I	b e l
cla-	ri-	fi-	ca-	tion
kh l e@	I	f I	k eI	S V n
cla-	ri-	fi-	ca-	tions
kh l e@	I	f I	k eI	S V n z
cla-	ri-	fied
kh l e@	I	f aI d
cla-	ri-	fies
kh l e@	I	f aI z
cla-	ri-	fy
kh l e@	I	f aI
cla-	ri-	fy-	ing
kh l e@	I	f aI	I N
cla-	ri-	ne-	tist
kh l e@	I	n e	t I s t
cla-	ri-	ne-	tists
kh l e@	I	n e	t I s t s
cla-	ri-	net
kh l e@	I	n e t
cla-	ri-	on
kh l e@	i:	V n
cla-	ri-	ta
kh l Q@	i:	t V
cla-	ri-	ty
kh l e@	I	t i:
cla-	rice
kh l @r	i: s
cla-	rin-	da
kh l @r	I n	d V
cla-	rine
kh l e@	i: n
cla-	ris-	sa
kh l @r	I	s V
cla-	risse
kh l {	r i: s
cla-	ro
kh l Q@	@U
cla-	ry
kh l e@	i:
cla-	shes
kh l {	S V z
cla-	shing
kh l {	S I N
cla-	vi-	chord
kh l {	v I	k O@ d
cla-	vi-	cle
kh l {	v I	k V l
cla-	wing
kh l O:	I N
cla-	xon
kh l { k	s V n
cla-	yey
kh l eI	i:
clac-	ka-	mas
kh l {	k V	m V s
clack
kh l { k
clad
kh l { d
clad-	dagh
kh l {	d V
claes
kh l eI z
clai-	born
kh l eI	b @r n
clai-	borne
kh l eI	b @r n
clai-	borne's
kh l eI	b O@ n z
clai-	mant
kh l eI	m V n t
clai-	mants
kh l eI	m V n t s
clai-	ming
kh l eI	m I N
clai-	rol
kh l e@	Q l
claim
kh l eI m
claimed
kh l eI m d
claims
kh l eI m z
clair
kh l e@
clair-	vo-	yance
kh l e@	v OI	V n s
clair-	vo-	yant
kh l e@	v OI	V n t
claire
kh l e@
claire's
kh l e@ z
clam
kh l { m
clam-	ber
kh l { m	b @r
clam-	bered
kh l { m	b @r d
clam-	my
kh l {	m i:
clam-	pdown
kh l { m	p d aU n
clam-	ping
kh l { m	p I N
clam-	shell
kh l { m	S e l
clamp
kh l { m p
clamped
kh l { m p t
clamps
kh l { m p s
clams
kh l { m z
clan
kh l { n
clan-	cy
kh l { n	s i:
clan-	cy's
kh l { n	s i: z
clan-	des-	tine
kh l { n	d e s	t V n
clan-	des-	tine-	ly
kh l { n	d e s	t V n	l i:
clan-	ging
kh l {	N I N
clan-	king
kh l { N	k I N
clan-	nish
kh l {	n I S
clan-	ton
kh l { n	t V n
clang
kh l { N
clank
kh l { N k
clans
kh l { n z
clap
kh l { p
clap-	board
kh l { p	b O@ d
clap-	boards
kh l { p	b O@ d z
clap-	per
kh l {	p @r
clap-	ping
kh l {	p I N
clap-	ton
kh l { p	t V n
clap-	ton's
kh l { p	t V n z
clapp
kh l { p
clapped
kh l { p t
claps
kh l { p s
clar
kh l Q@
clar-	dy
kh l Q@	d i:
clar-	kin
kh l Q@	k I n
clar-	ridge
kh l {	r I dZ
clare
kh l e@
clare-	mont
kh l e@	m Q n t
clark
kh l Q@ k
clark-	son
kh l Q@ k	s V n
clark-	ston
kh l Q@ k	s t V n
clark-	sville
kh l Q@ k	s v I l
clarke
kh l Q@ k
clarke's
kh l Q@ k s
clarks
kh l Q@ k s
clark's
kh l Q@ k s
clarks-	burg
kh l Q@ k	s b @r g
clas-	ses
kh l {	s V z
clas-	si-	cal
kh l {	s I	k V l
clas-	si-	ci-	sm
kh l {	s V	s I	z V m
clas-	si-	cist
kh l {	s V	s V s t
clas-	si-	er
kh l {	s i:	@r
clas-	si-	fi-	a-	ble
kh l {	s I	f aI	V	b V l
clas-	si-	fi-	ca-	tion
kh l {	s I	f I	k eI	S V n
clas-	si-	fi-	cat-	ions
kh l {	s I	f I	k eI	S V n z
clas-	si-	fied
kh l {	s I	f aI d
clas-	si-	fies
kh l {	s I	f aI z
clas-	si-	fy
kh l {	s I	f aI
clas-	si-	fy-	ing
kh l {	s I	f aI	I N
clas-	sic
kh l {	s I k
clas-	sical-	ly
kh l {	s I k	l i:
clas-	sics
kh l {	s I k s
clas-	sing
kh l {	s I N
clas-	son
kh l {	s V n
clas-	s's
kh l {	s V z
clas-	sy
kh l {	s i:
clash
kh l { S
clashed
kh l { S t
clasp
kh l { s p
clasped
kh l { s p t
class
kh l { s
class-	less
kh l { s	l V s
class-	mate
kh l { s	m eI t
class-	mates
kh l { s	m eI t s
class-	room
kh l { s	r u: m
class-	rooms
kh l { s	r u: m z
classed
kh l { s t
clat-	ter
kh l {	t @r
clau-	dette
kh l @U	d e t
clau-	di-	a
kh l O:	d i:	V
clau-	di-	an
kh l O:	d i:	V n
clau-	di-	na
kh l O:	d i:	n V
clau-	di-	o
kh l O:	d i:	@U
clau-	di-	us
kh l O:	d i:	V s
clau-	die
kh l O:	d i:
clau-	dine
kh l O:	d i: n
clau-	sen
kh l aU	s V n
clau-	ses
kh l O:	z V z
claud
kh l O: d
claude
kh l O: d
claunch
kh l O: n tS
claus
kh l O: z
claus-	tro-	pho-	bi-	a
kh l O: s	t r V	f @U	b i:	V
claus-	tro-	pho-	bic
kh l O: s	t r V	f @U	b I k
clause
kh l O: z
claw
kh l O:
claw-	son
kh l O:	s V n
clawed
kh l O: d
claws
kh l O: z
clax-	ton
kh l { k	s t V n
clay
kh l eI
clay-	born
kh l eI	b @r n
clay-	borne
kh l eI	b @r n
clay-	bourne
kh l eI	b @r n
clay-	ma-	tion
kh l eI	m eI	S V n
clay-	man
kh l eI	m V n
clay-	mont
kh l eI	m Q n t
clay-	more
kh l eI	m O@
clay-	pool
kh l eI	p u: l
clay-	son
kh l eI	z V n
clay-	ton
kh l eI	t V n
clay-	ton's
kh l eI	t V n z
clays
kh l eI z
cle-	land
kh l e	l V n d
cle-	ma-	tis
kh l e	m V	t I s
cle-	men
kh l e	m V n
cle-	men-	cy
kh l e	m V n	s i:
cle-	men-	te
kh l V	m e n	t eI
cle-	men-	ti
kh l eI	m eI n	t i:
cle-	men-	tia
kh l eI	m eI n	S V
cle-	men-	tine
kh l e	m V n	t aI n
cle-	mence
kh l e	m V n s
cle-	mens
kh l e	m V n z
cle-	ment
kh l e	m V n t
cle-	ments
kh l e	m V n t s
cle-	mons
kh l e	m V n z
cle-	o
kh l i:	@U
cle-	o-	pat-	ra
kh l i:	V	p { t	r V
cle-	o-	pat-	ra's
kh l i:	V	p { t	r V z
cle-	ri-	cal
kh l e@	I	k V l
cle-	ric
kh l e@	I k
cle-	rics
kh l e@	I k s
cle-	ris-	sa
kh l @r	i:	s V
cle-	va
kh l i:	v V
cle-	ven-	ger
kh l e	v V n	dZ @r
cle-	ver
kh l e	v @r
cle-	ver-	ly
kh l e	v @r	l i:
cle-	ver-	ness
kh l e	v @r	n V s
cle-	vie
kh l i:	v i:
clea-	ner
kh l i:	n @r
clea-	ners
kh l i:	n @r z
clea-	nest
kh l i:	n V s t
clea-	ning
kh l i:	n I N
clea-	nup
kh l i:	n V p
clea-	nups
kh l i:	n V p s
clea-	ran-	ces
kh l I@	V n	s V z
clea-	rance
kh l I@	V n s
clea-	rer
kh l I@	@r
clea-	rest
kh l I@	I s t
clea-	ring
kh l I@	I N
clea-	ring-	hou-	ses
kh l i:	r I N	h aU	s V z
clea-	ring-	house
kh l I@	I N	h aU s
clea-	ry
kh l I@	i:
clea-	vage
kh l i:	v V dZ
clea-	ver
kh l i:	v @r
clean
kh l i: n
clean-	li-	ness
kh l e n	l i:	n V s
clean-	ly
kh l i: n	l i:
clean-	ness
kh l i: n	n V s
clean-	ser
kh l e n	z @r
clean-	sers
kh l e n	z @r z
clean-	sing
kh l e n	z I N
clean-	tha
kh l i: n	T V
cleaned
kh l i: n d
cleans
kh l i: n z
cleanse
kh l e n z
cleansed
kh l e n z d
clear
kh l I@
clear-	cut
kh l I@	k V t
clear-	cut-	ting
kh l I@	k V	t I N
clear-	cuts
kh l I@	k V t s
clear-	ly
kh l I@	l i:
clear-	wa-	ter
kh l I@	w O:	t @r
cleared
kh l I@ d
clears
kh l I@ z
cleat
kh l i: t
cleats
kh l i: t s
cleave
kh l i: v
cleaves
kh l i: v z
cleek
kh l i: k
cleese
kh l i: s
clef
kh l e f
cleft
kh l e f t
cleg-	horn
kh l e g	h @r n
clegg
kh l e g
clem
kh l e m
clem-	mie
kh l e	m i:
clem-	mons
kh l e	m V n z
clem-	my
kh l e	m i:
clem-	son
kh l e m	s V n
clen-	cher
kh l e n	tS @r
clen-	ches
kh l e n	tS V z
clen-	de-	nin
kh l e n	d e	n I n
clench
kh l e n tS
clenched
kh l e n tS t
cler-	gy
kh l @r	dZ i:
cler-	gy-	man
kh l @r	dZ i:	m V n
cler-	gy-	men
kh l @r	dZ i:	m e n
cler-	mont
kh l e@	m Q n t
clerc
kh l @r k
clercq
kh l @r k
clerk
kh l @r k
clerks
kh l @r k s
clerk's
kh l @r k s
cleve
kh l i: v
cleve-	lan-	der
kh l i: v	l V n	d @r
cleve-	lan-	ders
kh l i: v	l V n	d @r z
cleve-	land
kh l i: v	l V n d
cleve-	land's
kh l i: v	l V n d z
clews
kh l u: z
cli-	burn
kh l aI	b @r n
cli-	che
kh l i:	S eI
cli-	ched
kh l i:	S eI d
cli-	ches
kh l i:	S eI z
cli-	en-	tele
kh l aI	V n	t e l
cli-	ent
kh l aI	V n t
cli-	ents
kh l aI	V n t s
cli-	ent's
kh l aI	V n t s
cli-	ma-	tic
kh l aI	m {	t I k
cli-	ma-	to-	lo-	gist
kh l I	m V	t Q	l V	dZ I s t
cli-	ma-	xes
kh l I	m { k	s V z
cli-	mac-	tic
kh l aI	m { k	t I k
cli-	mate
kh l aI	m V t
cli-	mates
kh l aI	m V t s
cli-	max
kh l aI	m { k s
cli-	maxed
kh l aI	m { k s t
cli-	ni-	cal
kh l I	n I	k V l
cli-	ni-	cal-	ly
kh l I	n I	k V	l i:
cli-	ni-	cian
kh l V	n I	S V n
cli-	ni-	cians
kh l V	n I	S V n z
cli-	nic
kh l I	n I k
cli-	nics
kh l I	n I k s
cli-	nic's
kh l I	n I k s
cli-	o
kh l i:	@U
cli-	to-	ris
kh l aI	t O@	I s
cli-	ver
kh l aI	v @r
clic-	ker
kh l I	k @r
clic-	king
kh l I	k I N
click
kh l I k
clicked
kh l I k t
clicks
kh l I k s
clif-	ford
kh l I	f @r d
clif-	ford's
kh l I	f @r d z
clif-	ton
kh l I f	t V n
cliff
kh l I f
cliff-	han-	ger
kh l I f	h {	N @r
cliff-	han-	gers
kh l I f	h {	N @r z
cliffs
kh l I f s
cliff's
kh l I f s
clift
kh l I f t
clim
kh l I m
clim-	ber
kh l aI	m @r
clim-	bers
kh l aI	m @r z
clim-	bing
kh l aI	m I N
climb
kh l aI m
climbed
kh l aI m d
climbs
kh l aI m z
climes
kh l aI m z
clin-	cher
kh l I n	tS @r
clin-	ches
kh l I n	tS V z
clin-	ching
kh l I n	tS I N
clin-	gan
kh l I N	g V n
clin-	ger
kh l I	N @r
clin-	ging
kh l I	N I N
clin-	to-	nite
kh l I n	t V	n aI t
clin-	ton
kh l I n	t V n
clin-	ton's
kh l I n	t V n z
clinch
kh l I n tS
clinched
kh l I n tS t
cline
kh l aI n
clines
kh l aI n z
cling
kh l I N
clings
kh l I N z
clink
kh l I N k
clint
kh l I n t
clip
kh l I p
clip-	board
kh l I p	b O@ d
clive
kh l aI v
clo-	mi-	pra-	mine
kh l @U	m I p	r V	m aI n
clo-	ni-	dine
kh l Q	n I	d i: n
clo-	ning
kh l @U	n I N
clo-	rin-	da
kh l O@	i: n	d V
clo-	rox
kh l O@	Q k s
clo-	se-	ted
kh l Q	z V	t V d
clo-	ser
kh l @U	s @r
clo-	ses
kh l @U	z V z
clo-	sest
kh l @U	s V s t
clo-	set
kh l Q	z V t
clo-	sets
kh l Q	z V t s
clo-	sing
kh l @U	z I N
clo-	sings
kh l @U	z I N z
clo-	sure
kh l @U	Z @r
clo-	sures
kh l @U	Z @r z
clo-	thier
kh l @U D	j @r
clo-	thiers
kh l @U D	j @r z
clo-	thil-	da
kh l V	T I l	d V
clo-	thilde
kh l Q	T I l d
clo-	thing
kh l @U	D I N
clo-	til-	da
kh l V	t I l	d V
clo-	ture
kh l @U	tS @r
clo-	ver
kh l @U	v @r
clo-	ver-	leaf
kh l @U	v @r	l i: f
clo-	vis
kh l @U	v I s
clo-	wer
kh l aU	@r
clo-	za-	pine
kh l @U	z V	p aI n
cloa-	king
kh l @U	k I N
cloak
kh l @U k
cloak-	room
kh l @U k	r u: m
cloaked
kh l @U k t
clob-	ber
kh l Q	b @r
clob-	ber-	ing
kh l Q	b @r	I N
clob-	bered
kh l Q	b @r d
cloc-	ker
kh l Q	k @r
cloc-	kers
kh l Q	k @r z
clock
kh l Q k
clock-	wise
kh l Q k	w aI z
clock-	work
kh l Q k	w @r k
clocked
kh l Q k t
clocks
kh l Q k s
clock's
kh l Q k s
cloe
kh l @U
clog
kh l Q g
clog-	ging
kh l Q	g I N
clogged
kh l O: g d
clogs
kh l Q g z
clois-	ter
kh l OI s	t @r
clois-	tered
kh l OI s	t @r d
clois-	ters
kh l OI s	t @r z
cloke
kh l @U k
clone
kh l @U n
cloned
kh l @U n d
clones
kh l @U n z
cloo-	tie
kh l u:	t i:
clop-	ton
kh l Q p	t V n
clos
kh l Q s
close
kh l @U s
close-	down
kh l @U z	d aU n
close-	downs
kh l @U z	d aU n z
close-	ly
kh l @U s	l i:
close-	ness
kh l @U s	n V s
close-	up
kh l @U	s V p
close-	ups
kh l @U	s V p s
closed
kh l @U z d
clot
kh l Q t
clot-	ted
kh l Q	t V d
clot-	ting
kh l Q	t I N
cloth
kh l O: T
clothe
kh l @U D
clothe-	shorse
kh l @U z	h O@ s
clothed
kh l @U D d
clothes
kh l @U D z
cloths
kh l O: T s
clots
kh l Q t s
clou-	ded
kh l aU	d V d
clou-	di-	ness
kh l aU	d i:	n V s
clou-	ding
kh l aU	d I N
clou-	dy
kh l aU	d i:
cloud
kh l aU d
cloud-	burst
kh l aU d	b @r s t
cloud-	less
kh l aU d	l V s
clouds
kh l aU d z
clough
kh l aU
clout
kh l aU t
cloves
kh l @U v z
clow
kh l @U
clow-	ning
kh l aU	n I N
clown
kh l aU n
clowns
kh l aU n z
cloy
kh l OI
cloy-	ing
kh l OI	I N
clu-	ny
kh l u:	n i:
club
kh l V b
club-	bing
kh l V	b I N
club-	by
kh l V	b i:
club-	hou-	ses
kh l V b	h aU	s V z
club-	house
kh l V b	h aU s
clubb
kh l V b
clubbed
kh l V b d
clubs
kh l V b z
club's
kh l V b z
cluc-	king
kh l V	k I N
cluck
kh l V k
clucks
kh l V k s
clue
kh l u:
clue-	less
kh l u:	l V s
clued
kh l u: d
clues
kh l u: z
cluff
kh l V f
cluj
kh l u: dZ
clum
kh l V m
clum-	ping
kh l V m	p I N
clum-	py
kh l V m	p i:
clum-	si-	ly
kh l V m	s I	l i:
clum-	si-	ness
kh l V m	z i:	n V s
clum-	sy
kh l V m	z i:
clump
kh l V m p
clumps
kh l V m p s
clun-	ker
kh l V N	k @r
clun-	kers
kh l V N	k @r z
clun-	ky
kh l V N	k i:
clune
kh l u: n
clung
kh l V N
clunk
kh l V N k
clunks
kh l V N k s
clus-	te-	ring
kh l V s	t @r	I N
clus-	ter
kh l V s	t @r
clus-	tered
kh l V s	t @r d
clus-	ters
kh l V s	t @r z
clut-	ches
kh l V	tS V z
clut-	ching
kh l V	tS I N
clut-	te-	ring
kh l V	t @r	I N
clut-	ter
kh l V	t @r
clut-	tered
kh l V	t @r d
clutch
kh l V tS
clutched
kh l V tS t
clute
kh l u: t
cly-	mene
kh l I	m i: n
cly-	mer
kh l aI	m @r
cly-	tie
kh l I	t i:
clyde
kh l aI d
clydes-	dale
kh l aI d	z d eI l
clyte
kh l aI t
clyve
kh l aI v
co
kh @U
co-	a-	gu-	la-	ting
kh @U	{ g	j V	l eI	t I N
co-	a-	gu-	la-	tion
kh @U	{ g	j V	l eI	S V n
co-	a-	gu-	late
kh @U	{ g	j V	l eI t
co-	a-	les-	cing
kh @U	V	l e	s I N
co-	a-	lesce
kh @U	V	l e s
co-	a-	lesced
kh @U	V	l e s t
co-	a-	li-	tion
kh @U	V	l I	S V n
co-	a-	li-	tions
kh @U	V	l I	S V n z
co-	a-	li-	tion's
kh @U	V	l I	S V n z
co-	a-	xi-	al
kh @U	{ k	s i:	V l
co-	au-	thor
kh @U	Q	T @r
co-	au-	thors
kh @U	Q	T @r z
co-	bain
kh @U	b eI n
co-	bain's
kh @U	b eI n z
co-	balt
kh @U	b O: l t
co-	ben
kh @U	b V n
co-	bi-	a
kh @U	b i:	V
co-	ble
kh @U	b V l
co-	burn
kh @U	b @r n
co-	ca
kh @U	k V
co-	caine
kh @U	k eI n
co-	chair-	man
kh @U	tS e@	m V n
co-	chin
kh @U	tS I n
co-	co
kh @U	k @U
co-	co-	ni-	no
kh @U	k V	n i:	n @U
co-	co-	nut
kh @U	k V	n V t
co-	co-	nuts
kh @U	k V	n V t s
co-	coa
kh @U	k @U
co-	coa-	nuts
kh @U	k @U	n V t s
co-	com
kh @U	k Q m
co-	coo-	ning
kh V	k u:	n I N
co-	coon
kh V	k u: n
co-	coons
kh V	k u: n z
co-	cos
kh @U	k @U z
co-	da
kh @U	d V
co-	ded
kh @U	d V d
co-	der
kh @U	d @r
co-	di-	fi-	ca-	tion
kh Q	d I	f I	k eI	S V n
co-	di-	fied
kh Q	d I	f aI d
co-	di-	fies
kh @U	d V	f aI z
co-	di-	fy
kh @U	d V	f aI
co-	di-	fy-	ing
kh @U	d V	f aI	I N
co-	ding
kh @U	d I N
co-	dy
kh @U	d i:
co-	e-	du-	ca-	tio-	nal
kh @U	e	dZ V	k eI	S V	n V l
co-	e-	qual
kh @U	i: k	w V l
co-	e-	xis-	ted
kh @U	V g	z I s	t V d
co-	e-	xis-	tence
kh @U	I g	z I s	t V n s
co-	e-	xis-	ting
kh @U	I g	z I s	t I N
co-	e-	xist
kh @U	V g	z I s t
co-	ed
kh @U	e d
co-	eds
kh @U	e d z
co-	ef-	fi-	cient
kh @U	V	f I	S V n t
co-	ef-	fi-	cients
kh @U	V	f I	S V n t s
co-	el-	ho
kh @U	e	l @U
co-	el-	lo
kh @U	e	l @U
co-	en-	zyme
kh @U	e n	z aI m
co-	er-	cing
kh @U	@r	s I N
co-	er-	cion
kh @U	@r	S V n
co-	er-	cive
kh @U	@r	s I v
co-	erce
kh @U	@r s
co-	erced
kh @U	@r s t
co-	field
kh @U	f i: l d
co-	foun-	der
kh @U	f aU n	d @r
co-	gan
kh @U	g V n
co-	ge-	ne-	ra-	tion
kh @U	dZ e	n @r	eI	S V n
co-	ge-	ne-	ra-	tor
kh @U	dZ e	n @r	eI	t @r
co-	ge-	ne-	ra-	tors
kh @U	dZ e	n @r	eI	t @r z
co-	gen-	cy
kh @U	dZ V n	s i:
co-	gent
kh @U	dZ V n t
co-	gi-	ta-	tion
kh Q	dZ I	t eI	S V n
co-	gi-	tate
kh Q	dZ I	t eI t
co-	ha-	bi-	ta-	tion
kh @U	h {	b I	t eI	S V n
co-	ha-	bi-	ting
kh @U	h {	b I	t I N
co-	ha-	bit
kh @U	h {	b I t
co-	han
kh @U	h V n
co-	has-	set
kh @U	h {	s V t
co-	he-	rence
kh @U	h I@	V n s
co-	he-	rent
kh @U	h I@	V n t
co-	he-	rent-	ly
kh @U	h i:	r V n	t l i:
co-	he-	sion
kh @U	h i:	Z V n
co-	he-	sive
kh @U	h i:	s I v
co-	he-	sive-	ly
kh @U	h i:	s I v	l i:
co-	he-	sive-	ness
kh @U	h i:	s I v	n V s
co-	hen
kh @U	V n
co-	hen's
kh @U	V n z
co-	ho
kh @U	h @U
co-	hort
kh @U	h O@ t
co-	horts
kh @U	h O@ t s
co-	host
kh @U	h @U s t
co-	hosts
kh @U	h @U s t s
co-	in-	ci-	ded
kh @U	I n	s aI	d I d
co-	in-	ci-	den-	ces
kh @U	I n	s I	d e n	s V z
co-	in-	ci-	den-	tal
kh @U	I n	s I	d e n	t V l
co-	in-	ci-	den-	tal-	ly
kh @U	I n	s I	d e n	t V	l i:
co-	in-	ci-	dence
kh @U	I n	s I	d V n s
co-	in-	ci-	dent
kh @U	I n	s I	d V n t
co-	in-	ci-	ding
kh @U	I n	s aI	d I N
co-	in-	cide
kh @U	I n	s aI d
)"
R"(co-	in-	cides
kh @U	I n	s aI d z
co-	in-	su-	rance
kh @U	I n	S @r	V n s
co-	ker
kh @U	k @r
co-	kie
kh @U	k i:
co-	king
kh @U	k I N
co-	la
kh @U	l V
co-	lan
kh @U	l V n
co-	las
kh @U	l V s
co-	la's
kh @U	l V z
co-	le-	us
kh @U	l i:	V s
co-	leen
kh O:	l i: n
co-	len
kh @U	l V n
co-	let-	ta
kh @U	l e	t V
co-	lette
kh @U	l e t
co-	ley
kh @U	l i:
co-	li
kh @U	l i:
co-	li-	er
kh @U	l i:	@r
co-	li-	se-	um
kh Q	l I	s i:	V m
co-	lin
kh @U	l I n
co-	lis
kh @U	l I s
co-	llec-	tors
kh V	l e k	t @r z
co-	lo
kh @U	l @U
co-	lo-	ma
kh @U	l @U	m V
co-	lo-	ni-	a
kh V	l @U	n i:	V
co-	lo-	ni-	a-	li-	sm
kh V	l @U	n i:	V	l I	z V m
co-	lo-	ni-	a-	list
kh V	l @U	n i:	V	l V s t
co-	lo-	ni-	a-	lists
kh V	l @U	n i:	V	l V s t s
co-	lo-	ni-	al
kh V	l @U	n i:	V l
co-	lo-	ni-	als
kh V	l @U	n i:	V l z
co-	lo-	ni-	za-	tion
kh Q	l V	n V	z eI	S V n
co-	lo-	ni-	zer
kh Q	l V	n aI	z @r
co-	lo-	ni-	zers
kh Q	l V	n aI	z @r z
co-	lo-	nies
kh Q	l V	n i: z
co-	lo-	nist
kh Q	l V	n V s t
co-	lo-	nists
kh Q	l V	n V s t s
co-	lo-	nize
kh Q	l V	n aI z
co-	lo-	nized
kh Q	l V	n aI z d
co-	lo-	nus
kh V	l @U	n V s
co-	lo-	ny
kh Q	l V	n i:
co-	lo-	ny's
kh Q	l V	n i: z
co-	lo-	ra-	dan
kh Q	l @r	Q	d V n
co-	lo-	ra-	dans
kh Q	l @r	Q	d V n z
co-	lo-	ra-	do
kh Q	l @r	Q	d @U
co-	lo-	ra-	do's
kh Q	l @r	Q	d @U z
co-	lo-	ra-	tion
kh V	l @r	eI	S V n
co-	lo-	ra-	tu-	ra
kh V	l @r	V	t U@	V
co-	lo-	reds
kh Q	l @r	V d z
co-	lo-	ri-	za-	tion
kh V	l @r	I	z eI	S V n
co-	lo-	ri-	zing
kh V	l @r	aI	z I N
co-	lo-	rize
kh V	l @r	aI z
co-	lo-	rized
kh V	l @r	aI z d
co-	logne
kh V	l @U n
co-	lom-	bi-	a
kh V	l V m	b i:	V
co-	lom-	bi-	an
kh V	l V m	b i:	V n
co-	lom-	bi-	ans
kh V	l V m	b i:	V n z
co-	lom-	bi-	a's
kh V	l V m	b i:	V z
co-	lom-	bo
kh V	l V m	b @U
co-	lomb
kh Q	l V m
co-	lon
kh @U	l V n
co-	lon-	nade
kh Q	l V	n eI d
co-	lor
kh V	l @r
co-	lor-	fast
kh V	l @r	f { s t
co-	lor-	ful
kh V	l @r	f V l
co-	lor-	fully
kh V	l @r f	l i:
co-	lor-	ing
kh V	l @r	I N
co-	lor-	is-	tic
kh V	l @r	I s	t I k
co-	lor-	less
kh V	l @r	l V s
co-	lorb-	lind
kh V	l @r b	l aI n d
co-	lored
kh V	l @r d
co-	lors
kh V	l @r z
co-	los-	sal
kh V	l Q	s V l
co-	los-	sal-	ly
kh V	l Q	s V	l i:
co-	los-	se-	um
kh Q	l V	s i:	V m
co-	los-	sus
kh V	l Q	s V s
co-	loured
kh V	l @r d
co-	lum-	ba
kh @U	l V m	b V
co-	lum-	bi-	a
kh V	l V m	b i:	V
co-	lum-	bi-	an
kh @U	l V m	b i:	V n
co-	lum-	bi-	a's
kh V	l V m	b i:	V z
co-	lum-	bine
kh Q	l V m	b aI n
co-	lum-	bines
kh Q	l V m	b aI n z
co-	lum-	bo
kh @U	l V m	b @U
co-	lum-	bu-	s's
kh V	l V m	b V	s V z
co-	lum-	bus
kh V	l V m	b V s
co-	lum-	nist
kh Q	l V m	n V s t
co-	lum-	nists
kh Q	l V m	n V s t s
co-	lumn
kh Q	l V m
co-	lumned
kh Q	l V m d
co-	lumns
kh Q	l V m z
co-	ly-	er
kh @U	l i:	@r
co-	ma
kh @U	m V
co-	ma-	tose
kh @U	m V	t @U s
co-	man
kh @U	m V n
co-	man-	che
kh V	m { n	tS i:
co-	man-	ches
kh V	m { n	tS i: z
co-	man-	dan-	te
kh @U	m V n	d Q n	t eI
co-	man-	dan-	tes
kh @U	m V n	d Q n	t e z
co-	mas
kh @U	m V z
co-	me-	con
kh Q	m V	k Q n
co-	me-	di-	an
kh V	m i:	d i:	V n
co-	me-	di-	ans
kh V	m i:	d i:	V n z
co-	me-	di-	an's
kh V	m i:	d i:	V n z
co-	me-	di-	enne
kh V	m i:	d i:	e n
co-	me-	dic
kh V	m i:	d I k
co-	me-	dies
kh Q	m V	d i: z
co-	me-	dy
kh Q	m V	d i:
co-	me-	dy's
kh Q	m V	d i: z
co-	me-	ta-	ry
kh Q	m V	t e@	i:
co-	mer
kh V	m @r
co-	mers
kh V	m @r z
co-	met
kh Q	m V t
co-	meth
kh V	m I T
co-	mets
kh Q	m V t s
co-	met's
kh Q	m V t s
co-	meup-	pance
kh V	m V	p V n s
co-	mex
kh Q	m e k s
co-	mi-	cal
kh Q	m I	k V l
co-	mi-	cal-	ly
kh Q	m I	k V	l i:
co-	mi-	no
kh V	m i:	n @U
co-	mi-	ta-	tus
kh O:	m I	t eI	t V s
co-	mi-	ty
kh @U	m I	t i:
co-	mic
kh Q	m I k
co-	mics
kh Q	m I k s
co-	ming
kh V	m I N
co-	mings
kh V	m I N z
co-	mins
kh @U	m I n z
co-	mo
kh @U	m @U
co-	na-	ble
kh @U	n V	b V l
co-	na-	way
kh Q	n V	w eI
co-	nal
kh @U	n V l
co-	nan
kh @U	n V n
co-	nant
kh @U	n V n t
co-	nard
kh Q	n @r d
co-	nes-	to-	ga
kh Q	n V s	t @U	g V
co-	ney
kh @U	n i:
co-	ni-	cal
kh Q	n I	k V l
co-	ni-	fe-	rous
kh V	n I	f @r	V s
co-	ni-	fer
kh Q	n I	f @r
co-	ni-	fers
kh Q	n I	f @r z
co-	ni-	fer's
kh Q	n I	f @r z
co-	nic
kh Q	n I k
co-	nics
kh Q	n I k s
co-	nis-	ton
kh Q	n I s	t V n
co-	no-	ver
kh Q	n V	v @r
co-	nus
kh @U	n V s
co-	o-	pe-	ra-	ted
kh @U	Q	p @r	eI	t V d
co-	o-	pe-	ra-	ting
kh @U	Q	p @r	eI	t I N
co-	o-	pe-	ra-	tion
kh @U	Q	p @r	eI	S V n
co-	o-	pe-	ra-	tions
kh @U	Q	p @r	eI	S V n z
co-	o-	pe-	ra-	tive
kh @U	Q	p @r	V	t I v
co-	o-	pe-	rate
kh @U	Q	p @r	eI t
co-	o-	pe-	rates
kh @U	Q	p @r	eI t s
co-	op
kh @U	Q p
co-	op-	ted
kh @U	Q p	t V d
co-	opt
kh @U	Q p t
co-	or-	di-	na-	ted
kh @U	O@	d I	n eI	t I d
co-	or-	di-	na-	ting
kh @U	O@	d I	n eI	t I N
co-	or-	di-	na-	tion
kh @U	O@	d I	n eI	S V n
co-	or-	di-	na-	tor
kh @U	O@	d I	n eI	t @r
co-	or-	di-	na-	tors
kh @U	O@	d I	n eI	t @r z
co-	or-	di-	nate
kh @U	O@	d I	n V t
co-	or-	di-	nates
kh @U	O@	d I	n V t s
co-	pa
kh @U	p V
co-	pa-	ca-	ba-	na
kh @U	p V	k V	b {	n V
co-	part-	ner
kh @U	p Q@ t	n @r
co-	part-	ners
kh @U	p Q@ t	n @r z
co-	pay-	ment
kh @U	p eI	m V n t
co-	pay-	ments
kh @U	p eI	m V n t s
co-	pen
kh @U	p V n
co-	pen-	ha-	gen
kh @U	p V n	h eI	g V n
co-	per-	ni-	can
kh V	p @r	n V	k V n
co-	per-	ni-	cus
kh V	p @r	n V	k V s
co-	pi-	ague
kh @U	p i:	{ g
co-	pi-	er
kh Q	p i:	@r
co-	pi-	ers
kh Q	p i:	@r z
co-	pi-	lot
kh @U	p aI	l V t
co-	pi-	ous
kh @U	p i:	V s
co-	pied
kh Q	p i: d
co-	pies
kh Q	p i: z
co-	ping
kh @U	p I N
co-	pu-	late
kh Q p	j V	l eI t
co-	pus
kh @U	p V s
co-	py
kh Q	p i:
co-	py-	cat
kh Q	p i:	k { t
co-	py-	cat-	ting
kh Q	p i:	k {	t I N
co-	py-	cats
kh Q	p i:	k { t s
co-	py-	ing
kh Q	p i:	I N
co-	py-	rea-	der
kh Q	p i:	r i:	d @r
co-	py-	rea-	ders
kh Q	p i:	r i:	d @r z
co-	py-	righ-	ta-	ble
kh Q	p i:	r aI	t V	b V l
co-	py-	righ-	ted
kh Q	p i:	r aI	t V d
co-	py-	right
kh Q	p i:	r aI t
co-	py-	rights
kh Q	p i:	r aI t s
co-	py-	wri-	ter
kh Q	p i:	r aI	t @r
co-	py-	wri-	ters
kh Q	p i:	r aI	t @r z
co-	ra
kh O@	V
co-	ra-	belle
kh O@	V	b V l
co-	ra-	cle
kh O@	V	k V l
co-	ra-	lie
kh O@	V	l i:
co-	ra-	line
kh O@	V	l aI n
co-	ral
kh O@	V l
co-	rals
kh O@	V l z
co-	ram
kh O@	{ m
co-	ra's
kh O@	V z
co-	rel
kh O@	e l
co-	rel-	la
kh @r	e	l V
co-	rell
kh O@	e l
co-	res-	pon-	dent
kh O@	V s	p Q n	d V n t
co-	ret-	ta
kh O@	e	t V
co-	rette
kh O@	e t
co-	rey
kh O@	i:
co-	ri-	a
kh O@	i:	V
co-	ri-	an-	der
kh O@	i:	{ n	d @r
co-	ri-	na
kh O@	i:	n V
co-	rin-	na
kh O@	I	n V
co-	rin-	thi-	an
kh @r	I n	T i:	V n
co-	rinne
kh @r	i: n
co-	rinth
kh O@	I n T
co-	ris-	sa
kh O@	I	s V
co-	ro-	na
kh @r	@U	n V
co-	ro-	na-	do
kh @r	@U	n Q	d @U
co-	ro-	na-	ry
kh O@	V	n e@	i:
co-	ro-	na-	tion
kh O@	V	n eI	S V n
co-	ro-	na's
kh @r	@U	n V z
co-	ro-	ner
kh O@	V	n @r
co-	ro-	ners
kh O@	V	n @r z
co-	ro-	ner's
kh O@	V	n @r z
co-	ro-	net
kh O@	V	n e t
co-	ro-	nets
kh O@	V	n e t s
co-	rol-	la
kh @r	Q	l V
co-	rol-	la-	ries
kh O@	V	l e@	i: z
co-	rol-	la-	ry
kh O@	V	l e@	i:
co-	rum
kh O@	V m
co-	run-	dum
kh @r	V n	d V m
co-	ry
kh O@	i:
co-	sa
kh @U	s V
co-	sen-	za
kh @U	s e n	z V
co-	sette
kh V	s e t
co-	sey
kh @U	z i:
co-	star
kh @U s	t Q@
co-	sy
kh @U	z i:
co-	ta
kh @U	t V
co-	ty
kh @U	t i:
co-	var-	ru-	bi-	as
kh @U	v Q@	u:	b i:	V z
co-	ve-	nan-	ter
kh V	v V	n V n	t @r
co-	ve-	nan-	ters
kh V	v V	n V n	t @r z
co-	ve-	nant
kh V	v V	n V n t
co-	ve-	nants
kh V	v V	n V n t s
co-	ve-	ney
kh Q	v V	n i:
co-	ve-	ra-	ges
kh V	v @r	eI	dZ V z
co-	ve-	rage
kh V	v @r	V dZ
co-	ve-	rall
kh V	v @r	O: l
co-	ve-	ralls
kh V	v @r	O: l z
co-	ve-	ring
kh V	v @r	I N
co-	ve-	rings
kh V	v @r	I N z
co-	ve-	rup
kh V	v @r	V p
co-	ve-	rups
kh V	v @r	V p s
co-	ve-	ted
kh V	v V	t V d
co-	vel
kh @U	v V l
co-	vell
kh Q	v V l
co-	ven
kh V	v V n
co-	vent
kh V	v V n t
co-	vent-	ry
kh V	v V n	t r i:
co-	ver
kh V	v @r
co-	ver-	dale
kh V	v @r	d eI l
co-	vered
kh V	v @r d
co-	vers
kh V	v @r z
co-	vert
kh @U	v @r t
co-	vert-	ly
kh V	v @r t	l i:
co-	vet
kh V	v V t
co-	vets
kh V	v V t s
co-	vey
kh V	v i:
co-	vi-	el-	lo
kh @U	v i:	e	l @U
co-	vi-	na
kh @U	v i:	n V
co-	ville
kh @U	v I l
co-	vin
kh @U	v I n
co-	ving-	ton
kh V	v I N	t V n
co-	wan
kh aU	V n
co-	wans
kh aU	V n z
co-	war-	dice
kh aU	@r	d I s
co-	ward
kh aU	@r d
co-	ward-	ly
kh aU	@r d	l i:
co-	wards
kh aU	@r d z
co-	ward's
kh aU	@r d z
co-	we-	ring
kh aU	@r	I N
co-	well
kh Q	w e l
co-	wen
kh aU	V n
co-	wer
kh aU	@r
co-	wie
kh aU	i:
co-	wing
kh aU	I N
co-	wor-	ker
kh @U	w @r	k @r
co-	wor-	kers
kh @U	w @r	k @r z
co-	x's
kh Q k	s V z
co-	yer
kh OI	@r
co-	yo-	te
kh aI	@U	t i:
co-	yo-	tes
kh aI	@U	t i: s
co.
kh @U
coa-	ches
kh @U	tS V z
coa-	ching
kh @U	tS I N
coa-	ch's
kh @U	tS V z
coa-	dy
kh @U	d i:
coa-	te
kh @U	eI t
coa-	ted
kh @U	t V d
coa-	tes
kh @U	eI t s
coa-	ting
kh @U	t I N
coa-	tings
kh @U	t I N z
coa-	xes
kh @U k	s V z
coa-	xing
kh @U k	s I N
coach
kh @U tS
coach-	man
kh @U tS	m V n
coached
kh @U tS t
coad
kh @U d
coal
kh @U l
coals
kh @U l z
coal's
kh @U l z
coan
kh @U n
coar-	se-	ning
kh O@	s V	n I N
coar-	ser
kh O@	s @r
coarse
kh O@ s
coas-	tal
kh @U s	t V l
coas-	ted
kh @U s	t V d
coas-	ter
kh @U s	t @r
coas-	ters
kh @U s	t @r z
coas-	ting
kh @U s	t I N
coast
kh @U s t
coast-	line
kh @U s	t l aI n
coast-	lines
kh @U s	t l aI n z
coasts
kh @U s t s
coast's
kh @U s t s
coat
kh @U t
coat-	tail
kh @U t	t eI l
coat-	tails
kh @U t	t eI l z
coates-	ville
kh @U t	s v I l
coats
kh @U t s
coat's
kh @U t s
coax
kh @U k s
coaxed
kh @U k s t
cob
kh Q b
cob-	bett
kh Q	b I t
cob-	ble
kh Q	b V l
cob-	bled
kh Q	b V l d
cob-	bles-	tone
kh Q	b V l	s t @U n
cob-	bles-	tones
kh Q	b V l	s t @U n z
cob-	ra
kh @U b	r V
cob-	ras
kh @U b	r V z
cob-	web
kh Q b	w e b
cob-	webs
kh Q b	w e b z
cobb
kh Q b
cobb-	ler
kh Q b	l @r
cobb-	lers
kh Q b	l @r z
cobb-	ler's
kh Q b	l @r z
cobbs
kh Q b z
cobe
kh @U b
cobs
kh Q b z
coc-	co
kh @U	k @U
coc-	cus
kh Q	k V s
coc-	ka-	ma-	mie
kh O:	k V	m eI	m i:
coc-	ka-	too
kh Q	k V	t u:
coc-	ka-	toos
kh Q	k V	t u: z
coc-	ke-	rell
kh Q	k @r	e l
coc-	ker
kh Q	k @r
coc-	keyed
kh Q	k aI d
coc-	ki-	ness
kh Q	k i:	n V s
coc-	king
kh Q	k I N
coc-	ky
kh Q	k i:
coch-	le-	a
kh Q k	l i:	V
coch-	le-	ar
kh Q k	l i:	@r
coch-	ran
kh Q k	r V n
coch-	rane
kh Q k	r V n
coch-	ran's
kh Q k	r V n z
cock
kh Q k
cock-	burn
kh Q k	b @r n
cock-	burn's
kh @U	b @r n z
cock-	tail
kh Q k	t eI l
cock-	tails
kh Q k	t eI l z
cocke
kh @U k
cocked
kh Q k t
cod
kh Q d
cod-	d-	ling
kh Q	d V	l I N
cod-	ding
kh Q	d I N
cod-	ding-	ton
kh Q	d I N	t V n
cod-	dle
kh Q	d V l
cod-	dled
kh Q	d V l d
cod-	lin
kh Q d	l I n
codd
kh Q d
code
kh @U d
code-	brea-	ker
kh @U d	b r eI	k @r
codes
kh @U d z
code's
kh @U d z
coe
kh @U
coe-	burn
kh @U	b @r n
coe-	la-	canth
s i:	l V	k { n T
coeur
kh u: r
cof-	fee
kh Q	f i:
cof-	fee-	hou-	ses
kh O:	f i:	h aU	s V z
cof-	fee-	house
kh O:	f i:	h aU s
cof-	feen
kh V	f i: n
cof-	fees
kh O:	f i: z
cof-	fee's
kh Q	f i: z
cof-	fer
kh O:	f @r
cof-	fers
kh Q	f @r z
cof-	fey
kh Q	f i:
cof-	fin
kh O:	f I n
cof-	fing
kh O:	f I N
cof-	fins
kh O:	f I n z
cof-	fin's
kh O:	f I n z
coff-	man
kh O: f	m V n
cog
kh O: g
cog-	nac
kh @U n	j { k
cog-	ni-	tion
kh Q g	n I	S V n
cog-	ni-	tive
kh Q g	n I	t I v
cog-	ni-	zance
kh Q g	n I	z V n s
cog-	ni-	zant
kh Q g	n I	z V n t
cog-	nos-	cen-	ti
kh Q g	n O:	S e n	t i:
cogs-	well
kh Q g	s w e l
cohn
kh @U n
coi-	nage
kh OI	n I dZ
coi-	ner
kh OI	n @r
coi-	ning
kh OI	n I N
coiffe
kh OI f
coiffed
kh OI f t
coil
kh OI l
coiled
kh OI l d
coils
kh OI l z
coin
kh OI n
coin-	treau
kh O: n	t r @U
coined
kh OI n d
coins
kh OI n z
coin's
kh OI n z
coit
kh OI t
coke
kh @U k
cokes
kh @U k s
coke's
kh @U k s
col-	bert
kh @U l	b @r t
col-	burn
kh @U l	b @r n
col-	by
kh @U l	b i:
col-	by's
kh @U l	b i: z
col-	cord
kh @U l	k @r d
col-	den
kh @U l	d V n
col-	der
kh @U l	d @r
col-	dest
kh @U l	d V s t
col-	gate
kh @U l	g eI t
col-	gate's
kh @U l	g eI t s
col-	la
kh @U	l V
col-	la-	bo-	ra-	ted
kh V	l {	b @r	eI	t V d
col-	la-	bo-	ra-	ting
kh V	l {	b @r	eI	t I N
col-	la-	bo-	ra-	tion
kh V	l {	b @r	eI	S V n
col-	la-	bo-	ra-	tions
kh Q	l V	b @r	eI	S V n z
col-	la-	bo-	ra-	tive
kh V	l {	b @r	eI	t I v
col-	la-	bo-	ra-	tor
kh V	l {	b @r	eI	t @r
col-	la-	bo-	ra-	tors
kh V	l {	b @r	eI	t @r z
col-	la-	bo-	rate
kh V	l {	b @r	eI t
col-	la-	gen
kh Q	l V	g V n
col-	la-	ges
kh V	l Q	Z V z
col-	la-	te-	ra-	lize
kh V	l {	t @r	V	l aI z
col-	la-	te-	ra-	lized
kh V	l {	t @r	V	l aI z d
col-	la-	te-	ral
kh V	l {	t @r	V l
col-	lage
kh V	l Q Z
col-	lap-	ses
kh V	l { p	s V z
col-	lap-	si-	ble
kh V	l { p	s V	b V l
col-	lap-	sing
kh V	l { p	s I N
col-	lapse
kh V	l { p s
col-	lapsed
kh V	l { p s t
col-	lar
kh Q	l @r
col-	lar-	bone
kh Q	l @r	b @U n
col-	lard
kh Q	l @r d
col-	lards
kh Q	l @r d z
col-	lared
kh Q	l @r d
col-	lars
kh Q	l @r z
col-	late
kh V	l eI t
col-	le-	ges
kh Q	l I	dZ V z
col-	le-	ge's
kh Q	l I	dZ V z
col-	le-	gi-	a-	li-	ty
kh V	l i:	dZ i:	{	l V	t i:
col-	le-	gi-	al
kh V	l i:	dZ i:	V l
col-	le-	gian
kh V	l i:	dZ V n
col-	le-	gians
kh V	l i:	dZ V n z
col-	le-	giate
kh V	l i:	dZ V t
col-	league
kh Q	l i: g
col-	leagues
kh Q	l i: g z
col-	lec-	ted
kh V	l e k	t V d
col-	lec-	ti-	bi-	li-	ty
kh V	l e k	t V	b I	l V	t i:
col-	lec-	ti-	ble
kh V	l e k	t V	b V l
col-	lec-	ti-	bles
kh V	l e k	t V	b V l z
col-	lec-	ti-	vi-	sm
kh V	l e k	t I	v I	z V m
col-	lec-	ti-	vi-	za-	tion
kh V	l e k	t I	v V	z eI	S V n
col-	lec-	ti-	vist
kh V	l e k	t I	v I s t
col-	lec-	ti-	vize
kh V	l e k	t I	v aI z
col-	lec-	ti-	vized
kh V	l e k	t I	v aI z d
col-	lec-	ting
kh V	l e k	t I N
col-	lec-	tion
kh V	l e k	S V n
col-	lec-	tions
kh V	l e k	S V n z
col-	lec-	tive
kh V	l e k	t I v
col-	lec-	tive-	ly
kh V	l e k	t I v	l i:
col-	lec-	tives
kh V	l e k	t I v z
col-	lec-	tor
kh V	l e k	t @r
col-	lec-	tor's
kh V	l e k	t @r z
col-	lect
kh V	l e k t
col-	lects
kh V	l e k t s
col-	leen
kh Q	l i: n
col-	lege
kh Q	l I dZ
col-	len
kh Q	l V n
col-	let
kh Q	l V t
col-	lette
kh V	l e t
col-	ley
kh Q	l i:
col-	li-	ded
kh V	l aI	d V d
col-	li-	der
kh V	l aI	d @r
col-	li-	ding
kh V	l aI	d I N
col-	li-	sio-	nal
kh V	l I	Z V	n V l
col-	li-	sion
kh V	l I	Z V n
col-	li-	sions
kh V	l I	Z V n z
col-	li-	son
kh Q	l I	s V n
col-	lide
kh V	l aI d
col-	lides
kh V	l aI d z
col-	lie
kh Q	l i:
col-	lier
kh Q l	j @r
col-	liers
kh Q l	j @r z
col-	lier's
kh Q l	j @r z
col-	lis
kh Q	l I s
col-	lo-	di-	on
kh V	l @U	d i:	V n
col-	lo-	qui-	al
kh V	l @U k	w i:	V l
col-	lo-	qui-	um
kh V	l @U k	w i:	V m
col-	lo-	quy
kh Q	l V k	w i:
col-	loi-	dal
kh V	l OI	d V l
col-	loid
kh Q	l OI d
col-	lu-	ded
kh V	l u:	d V d
col-	lu-	ding
kh V	l u:	d I N
col-	lu-	sion
kh V	l u:	Z V n
col-	lu-	sive
kh V	l u:	s I v
col-	lude
kh V	l u: d
col-	lum
kh Q	l V m
col-	ly
kh Q	l i:
col-	ly-	er
kh Q	l i:	@r
col-	man
kh @U l	m V n
col-	mer
kh @U	m @r
col-	quitt
kh @U l	k w I t
col-	son
kh @U l	s V n
col-	ston
kh @U l	s t V n
col-	strip
kh @U l	s t r I p
col-	ter
kh @U l	t @r
col-	ton
kh @U l	t V n
col-	ver
kh @U l	v @r
col-	vert
kh Q l	v @r t
col-	ville
kh Q l	v I l
col-	vin
kh @U l	v I n
col-	well
kh @U l	w e l
cold
kh @U l d
cold-	bloo-	ded
kh @U l	d b l V	d V d
cold-	blood
kh @U l	d b l V d
cold-	ly
kh @U l	d l i:
cold-	ness
kh @U l	d n V s
cold-	wa-	ter
kh @U l	d w O:	t @r
colds
kh @U l d z
cole
kh @U l
cole-	brook
kh @U l	b r U k
cole-	man
kh @U l	m V n
cole-	man's
kh @U l	m V n z
cole-	ridge
kh @U l	r I dZ
cole-	ville
kh @U l	v I l
coles
kh @U l z
cole's
kh @U l z
coles-	law
kh @U l	s l Q
coll
kh Q l
colo-	nel
kh @r	n V l
colo-	nels
kh @r	n V l z
colo-	nel's
kh @r	n V l z
colt
kh @U l t
colt-	rane
kh @U l	t r V n
colt-	rane's
kh @U l	t r V n z
colts
kh @U l t s
colt's
kh @U l t s
colts-	foot
kh @U l	t s f U t
com
kh Q m
com-	ba-	tant
kh V m	b {	t V n t
com-	ba-	tants
kh V m	b {	t V n t s
com-	ba-	ting
kh V m	b {	t I N
com-	ba-	tive
kh V m	b {	t I v
com-	ba-	tive-	ness
kh V m	b {	t I v	n V s
com-	bat
kh Q m	b { t
com-	bat-	ting
kh V m	b {	t I N
com-	bats
kh V m	b { t s
com-	ber
kh @U	m @r
com-	bi-	na-	bi-	li-	ty
kh V m	b aI	n V	b I	l I	t i:
com-	bi-	na-	ble
kh V m	b aI	n V	b V l
com-	bi-	na-	tion
kh Q m	b I	n eI	S V n
com-	bi-	na-	tions
kh Q m	b I	n eI	S V n z
com-	bi-	ning
kh V m	b aI	n I N
com-	bine
kh Q m	b aI n
com-	bined
kh V m	b aI n d
com-	bines
kh V m	b aI n z
com-	bing
kh @U	m I N
com-	bo
kh Q m	b @U
com-	bus-	tion
kh V m	b V s	tS V n
com-	bust
kh V m	b V s t
com-	dex
kh Q m	d V k s
com-	for-	ta-	ble
kh V m	f @r	t V	b V l
)"
R"(com-	for-	tab-	ly
kh V m	f @r	t V b	l i:
com-	for-	ted
kh V m	f @r	t V d
com-	for-	ter
kh V m	f @r	t @r
com-	for-	ters
kh V m	f @r	t @r z
com-	for-	ting
kh V m	f @r	t I N
com-	fort
kh V m	f @r t
com-	forts
kh V m	f @r t s
com-	fy
kh V m	f i:
com-	ma
kh Q	m V
com-	mack
kh Q	m V k
com-	man-	dant
kh Q	m V n	d Q n t
com-	man-	ded
kh V	m { n	d V d
com-	man-	deer
kh Q	m V n	d I@
com-	man-	deered
kh Q	m V n	d I@ d
com-	man-	der
kh V	m { n	d @r
com-	man-	ders
kh V	m { n	d @r z
com-	man-	der's
kh V	m { n	d @r z
com-	man-	ding
kh V	m { n	d I N
com-	man-	do
kh V	m { n	d @U
com-	man-	dos
kh V	m { n	d @U z
com-	mand
kh V	m { n d
com-	mand-	ment
kh V	m { n	d m V n t
com-	mand-	ments
kh V	m { n	d m V n t s
com-	mands
kh V	m { n d z
com-	mand's
kh V	m { n d z
com-	mas
kh Q	m V z
com-	me-	mo-	ra-	ted
kh V	m e	m @r	eI	t V d
com-	me-	mo-	ra-	ting
kh V	m e	m @r	eI	t I N
com-	me-	mo-	ra-	tion
kh V	m e	m @r	eI	S V n
com-	me-	mo-	ra-	tions
kh V	m e	m @r	eI	S V n z
com-	me-	mo-	rate
kh V	m e	m @r	eI t
com-	me-	mo-	rates
kh V	m e	m @r	eI t s
)"