R"(o-	ver-	sen-	si-	tive
@U	v @r	s e n	s I	t I v
o-	ver-	sha-	dow
@U	v @r	S {	d @U
o-	ver-	sha-	dow-	ing
@U	v @r	S {	d @U	I N
o-	ver-	sha-	dowed
@U	v @r	S {	d @U d
o-	ver-	sha-	dows
@U	v @r	S {	d @U z
o-	ver-	shoo-	ting
@U	v @r	S u:	t I N
o-	ver-	shoot
@U	v @r	S u: t
o-	ver-	shot
@U	v @r	S Q t
o-	ver-	si-	zes
@U	v @r	s aI	z V z
o-	ver-	sight
@U	v @r	s aI t
o-	ver-	sim-	pli-	fi-	ca-	tion
@U	v @r	s I m	p l I	f I	k eI	S V n
o-	ver-	sim-	pli-	fied
@U	v @r	s I m	p l I	f aI d
o-	ver-	sim-	pli-	fy
@U	v @r	s I m	p l I	f aI
o-	ver-	sim-	pli-	fy-	ing
@U	v @r	s I m	p l I	f aI	I N
o-	ver-	size
@U	v @r	s aI z
o-	ver-	sized
@U	v @r	s aI z d
o-	ver-	slept
@U	v @r s	l e p t
o-	ver-	spen-	ding
@U	v @r s	p e n	d I N
o-	ver-	spend
@U	v @r s	p e n d
o-	ver-	spends
@U	v @r s	p e n d z
o-	ver-	spent
@U	v @r s	p e n t
o-	ver-	sta-	ted
@U	v @r s	t eI	t V d
o-	ver-	sta-	ting
@U	v @r s	t eI	t I N
o-	ver-	staff
@U	v @r s	t { f
o-	ver-	staffed
@U	v @r s	t { f t
o-	ver-	state
@U	v @r s	t eI t
o-	ver-	state-	ment
@U	v @r s	t eI t	m V n t
o-	ver-	state-	ments
@U	v @r s	t eI t	m V n t s
o-	ver-	states
@U	v @r s	t eI t s
o-	ver-	stay
@U	v @r s	t eI
o-	ver-	stayed
@U	v @r s	t eI d
o-	ver-	step
@U	v @r s	t e p
o-	ver-	step-	ping
@U	v @r s	t e	p I N
o-	ver-	stepped
@U	v @r s	t e p t
o-	ver-	stock
@U	v @r s	t Q k
o-	ver-	stocked
@U	v @r s	t Q k t
o-	ver-	stuff
@U	v @r s	t V f
o-	ver-	stuffed
@U	v @r s	t V f t
o-	ver-	sub-	scribe
@U	v @r	s V b	s k r aI b
o-	ver-	sub-	scribed
@U	v @r	s V b	s k r aI b d
o-	ver-	supp-	lied
@U	v @r	s V p	l aI d
o-	ver-	supp-	ly
@U	v @r	s V p	l aI
o-	ver-	ta-	ken
@U	v @r	t eI	k V n
o-	ver-	ta-	king
@U	v @r	t eI	k I N
o-	ver-	take
@U	v @r	t eI k
o-	ver-	tax
@U	v @r	t { k s
o-	ver-	taxed
@U	v @r	t { k s t
o-	ver-	threw
@U	v @r T	r u:
o-	ver-	throw
@U	v @r T	r @U
o-	ver-	throw-	ing
@U	v @r T	r @U	I N
o-	ver-	thrown
@U	v @r T	r @U n
o-	ver-	time
@U	v @r	t aI m
o-	ver-	ton
@U	v @r	t V n
o-	ver-	tone
@U	v @r	t @U n
o-	ver-	tones
@U	v @r	t @U n z
o-	ver-	took
@U	v @r	t U k
o-	ver-	trai-	ning
@U	v @r t	r eI	n I N
o-	ver-	train
@U	v @r t	r eI n
o-	ver-	tur-	ning
@U	v @r	t @r	n I N
o-	ver-	ture
@U	v @r	tS @r
o-	ver-	tures
@U	v @r	tS U@ z
o-	ver-	turn
@U	v @r	t @r n
o-	ver-	turned
@U	v @r	t @r n d
o-	ver-	turns
@U	v @r	t @r n z
o-	ver-	u-	sing
@U	v @r	j u:	z I N
o-	ver-	use
@U	v @r	j u: z
o-	ver-	used
@U	v @r	j u: z d
o-	ver-	va-	lu-	a-	tion
@U	v @r	v { l	j u:	eI	S V n
o-	ver-	va-	lue
@U	v @r	v { l	j u:
o-	ver-	va-	lued
@U	v @r	v { l	j u: d
o-	ver-	view
@U	v @r v	j u:
o-	ver-	weigh-	ted
@U	v @r	w eI	t V d
o-	ver-	weight
@U	v @r	w eI t
o-	ver-	whel-	ming
@U	v @r	w e l	m I N
o-	ver-	whel-	ming-	ly
@U	v @r	w e l	m I N	l i:
o-	ver-	whelm
@U	v @r	w e l m
o-	ver-	whelmed
@U	v @r	w e l m d
o-	ver-	whelms
@U	v @r	w e l m z
o-	ver-	win-	ter
@U	v @r	w I n	t @r
o-	ver-	work
@U	v @r	w @r k
o-	ver-	worked
@U	v @r	w @r k t
o-	ver-	writ-	ten
@U	v @r	r I	t V n
o-	ver-	write
@U	v @r	r aI t
o-	ver-	wrought
@U	v @r	r O: t
o-	ver-	zea-	lous
@U	v @r	z e	l V s
o-	vers
@U	v @r z
o-	vert
@U	v @r t
o-	vert-	ly
@U	v @r t	l i:
o-	vett
@U	v e t
o-	vett's
@U	v e t s
o-	vi-	e-	do
@U	v i:	eI	d @U
o-	vi-	pa-	rous
@U	v I	p @r	V s
o-	vo-	nic
@U	v Q	n I k
o-	vo-	vi-	vi-	pa-	rous
@U	v @U	v aI	v I	p @r	V s
o-	void
@U	v OI d
o-	vu-	la-	tion
@U v	j V	l eI	S V n
o-	vule
@U v	j u: l
o-	vum
@U	v V m
o-	wades
@U	Q d z
o-	wen
@U	V n
o-	wens
@U	V n z
o-	wen's
@U	V n z
o-	wens-	bo-	ro
@U	V n	z b @r	@U
o-	wing
@U	I N
o-	wings
@U	I N z
o-	wos-	so
@U	O:	s @U
o-	wy-	hee
@U	i:	h i:
o-	xa-	lates
Q k	s V	l eI t s
o-	xa-	lis
Q k	s V	l V s
o-	xen
Q k	s V n
o-	xi-	da-	tion
Q k	s I	d eI	S V n
o-	xi-	dant
Q k	s I	d V n t
o-	xi-	dants
Q k	s I	d V n t s
o-	xi-	di-	zer
Q k	s I	d aI	z @r
o-	xi-	di-	zing
Q k	s I	d aI	z I N
o-	xi-	dize
Q k	s I	d aI z
o-	xi-	dized
Q k	s I	d aI z d
o-	xide
Q k	s aI d
o-	xides
Q k	s aI d z
o-	xy
Q k	s i:
o-	xy-	ge-	na-	ted
Q k	s V	dZ V	n eI	t V d
o-	xy-	ge-	nate
Q k	s V	dZ V	n eI t
o-	xy-	gen
Q k	s V	dZ V n
o-	xy-	mo-	ron
Q k	s i:	m O@	Q n
o-	xy-	to-	cin
Q k	s V	t @U	s V n
o-	ya-	ma
@U	j Q	m V
o-	yer
OI	@r
o-	za-	wa
@U	z Q	w V
o-	zark
@U	z Q@ k
o-	zarks
@U	z Q@ k s
o-	zone
@U	z @U n
o.
@U
oa-	tis
@U	t I s
oa-	xa-	ca
@U k	s V	k V
oak
@U k
oak-	dale
@U k	d eI l
oak-	land
@U k	l V n d
oak-	land's
@U k	l V n d z
oak-	leaf
@U k	l i: f
oak-	ley
@U k	l i:
oak-	ley's
@U k	l i: z
oak-	man
@U k	m V n
oak-	mont
@U k	m Q n t
oak-	ville
@U k	v I l
oak-	wood
@U k	w U d
oakes
@U k s
oaks
@U k s
oak's
@U k s
oar
O@
oar-	lock
O@	l Q k
oared
O@ d
oars
O@ z
oars-	man
O@ z	m V n
oat
@U t
oat-	man
@U t	m V n
oat-	meal
@U t	m i: l
oates
@U t s
oath
@U T
oaths
@U D z
oats
@U t s
ob-	fus-	ca-	tion
Q b	f V s	k eI	S V n
ob-	fus-	cate
Q b	f V s	k eI t
ob-	jec-	ted
V b	dZ e k	t V d
ob-	jec-	ti-	vi-	ty
Q b	dZ e k	t I	v I	t i:
ob-	jec-	ting
V b	dZ e k	t I N
ob-	jec-	tio-	na-	ble
V b	dZ e k	S V	n V	b V l
ob-	jec-	tion
V b	dZ e k	S V n
ob-	jec-	tions
V b	dZ e k	S V n z
ob-	jec-	tion's
V b	dZ e k	S V n z
ob-	jec-	tive
V b	dZ e k	t I v
ob-	jec-	tive-	ly
Q b	dZ e k	t I v	l i:
ob-	jec-	tives
V b	dZ e k	t I v z
ob-	jec-	tor
V b	dZ e k	t @r
ob-	jec-	tors
V b	dZ e k	t @r z
ob-	ject
Q b	dZ e k t
ob-	jects
Q b	dZ e k t s
ob-	last
Q b	l { s t
ob-	late
Q b	l eI t
ob-	li-	ga-	ted
Q b	l I	g eI	t I d
ob-	li-	ga-	tion
Q b	l I	g eI	S V n
ob-	li-	ga-	tions
Q b	l I	g eI	S V n z
ob-	li-	ga-	to-	ry
V b	l I	g V	t O@	i:
ob-	li-	gate
Q b	l I	g eI t
ob-	li-	gates
Q b	l I	g eI t s
ob-	li-	ges
V b	l aI	dZ V z
ob-	li-	ging
V b	l aI	dZ I N
ob-	li-	ging-	ly
V b	l aI	dZ I N	l i:
ob-	li-	te-	ra-	ted
V b	l I	t @r	eI	t V d
ob-	li-	te-	ra-	ting
V b	l I	t @r	eI	t I N
ob-	li-	te-	rate
V b	l I	t @r	eI t
ob-	li-	vi-	on
V b	l I	v i:	V n
ob-	li-	vi-	ous
V b	l I	v i:	V s
ob-	lige
V b	l aI dZ
ob-	liged
V b	l aI dZ d
ob-	lique
V b	l i: k
ob-	lique-	ly
@U b	l i: k	l i:
ob-	long
Q b	l O: N
ob-	no-	xious
Q b	n Q k	S V s
ob-	re-	no-	vich
V b	r e	n V	v I tS
ob-	recht
Q b	r I k t
ob-	ri-	en
@U b	r aI	V n
ob-	sce-	ni-	ties
Q b	s e	n I	t i: z
ob-	sce-	ni-	ty
V b	s e	n I	t i:
ob-	scene
Q b	s i: n
ob-	scene-	ly
Q b	s i: n	l i:
ob-	se-	qui-	ous
V b	s i: k	w i:	V s
ob-	ser-	va-	ble
V b	z @r	v V	b V l
ob-	ser-	va-	bles
V b	z @r	v V	b V l z
ob-	ser-	va-	tion
Q b	z @r	v eI	S V n
ob-	ser-	va-	tions
Q b	z @r	v eI	S V n z
ob-	ser-	va-	to-	ries
V b	z @r	v V	t O@	i: z
ob-	ser-	va-	to-	ry
V b	z @r	v V	t O@	i:
ob-	ser-	va-	to-	ry's
V b	z @r	v V	t O@	i: z
ob-	ser-	van-	ces
V b	z @r	v V n	s V z
ob-	ser-	vance
V b	z @r	v V n s
ob-	ser-	vant
V b	z @r	v V n t
ob-	ser-	ver
V b	z @r	v @r
ob-	ser-	vers
V b	z @r	v @r z
ob-	ser-	ving
V b	z @r	v I N
ob-	serve
V b	z @r v
ob-	served
V b	z @r v d
ob-	serves
V b	z @r v z
ob-	ses-	sing
V b	s e	s I N
ob-	ses-	sio-	nal
V b	s e	S V	n V l
ob-	ses-	sion
V b	s e	S V n
ob-	ses-	sions
V b	s e	S V n z
ob-	ses-	sive
V b	s e	s I v
ob-	ses-	sive-	ly
Q b	s e	s I v	l i:
ob-	sess
V b	s e s
ob-	sessed
V b	s e s t
ob-	si-	di-	an
V b	s I	d i:	V n
ob-	so-	le-	scence
Q b	s V	l e	s V n s
ob-	so-	le-	scent
Q b	s V	l e	s V n t
ob-	so-	lete
Q b	s V	l i: t
ob-	struc-	ted
V b	s t r V k	t V d
ob-	struc-	ting
V b	s t r V k	t I N
ob-	struc-	tio-	ni-	sm
V b	s t r V k	S V	n I	z V m
ob-	struc-	tio-	nist
V b	s t r V k	S V	n V s t
ob-	struc-	tio-	nists
V b	s t r V k	S V	n V s t s
ob-	struc-	tion
V b	s t r V k	S V n
ob-	struc-	tions
V b	s t r V k	S V n z
ob-	struc-	tive
V b	s t r V k	t I v
ob-	struct
V b	s t r V k t
ob-	tai-	na-	ble
V b	t eI	n V	b V l
ob-	tai-	ning
V b	t eI	n I N
ob-	tain
V b	t eI n
ob-	tained
V b	t eI n d
ob-	tains
V b	t eI n z
ob-	tru-	sive
V b	t r u:	s I v
ob-	trude
V b	t r u: d
ob-	trudes
V b	t r u: d z
ob-	tuse
Q b	t u: s
ob-	verse
V b	v @r s
ob-	vi-	a-	ting
Q b	v i:	eI	t I N
ob-	vi-	ate
Q b	v i:	eI t
ob-	vi-	ous
Q b	v i:	V s
ob-	vi-	ous-	ly
Q b	v i:	V s	l i:
obs-	cu-	ri-	ty
V b	s k j U@	V	t i:
obs-	cu-	ring
V b	s k j U@	I N
obs-	cure
V b	s k j U@
obs-	cured
V b	s k j U@ d
obs-	cures
V b	s k j U@ z
obs-	ta-	cle
Q b	s t V	k V l
obs-	ta-	cles
Q b	s t V	k V l z
obs-	tet-	ri-	cian
Q b	s t V t	r I	S V n
obs-	tet-	ri-	cians
Q b	s t V t	r I	S V n z
obs-	tet-	ric
V b	s t e t	r I k
obs-	tet-	rics
V b	s t e t	r I k s
obs-	ti-	na-	cy
Q b	s t I	n V	s i:
obs-	ti-	nate
Q b	s t I	n V t
obst
Q b s t
oc-	ca-	sio-	nal
V	k eI	Z V	n V l
oc-	ca-	sio-	nal-	ly
V	k eI	Z V	n V	l i:
oc-	ca-	sion
V	k eI	Z V n
oc-	ca-	sioned
V	k eI	Z V n d
oc-	ca-	sions
V	k eI	Z V n z
oc-	ci-	den-	tal
Q k	s I	d e n	t V l
oc-	ci-	den-	tale
Q k	s I	d e n	t V l
oc-	ci-	dent
Q k	s I	d e n t
oc-	clu-	sion
V k	l u:	Z V n
oc-	cu-	pa-	tio-	nal
Q k	j V	p eI	S V	n V l
oc-	cu-	pa-	tion
Q k	j V	p eI	S V n
oc-	cu-	pa-	tions
Q k	j V	p eI	S V n z
oc-	cu-	pan-	cy
Q k	j V	p V n	s i:
oc-	cu-	pant
Q k	j V	p V n t
oc-	cu-	pants
Q k	j V	p V n t s
oc-	cu-	pi-	er
Q k	j V	p aI	@r
oc-	cu-	pi-	ers
Q k	j V	p aI	@r z
oc-	cu-	pied
Q k	j V	p aI d
oc-	cu-	pies
Q k	j V	p aI z
oc-	cu-	py
Q k	j V	p aI
oc-	cu-	py-	ing
Q k	j V	p aI	I N
oc-	cult
V	k V l t
oc-	cur
V	k @r
oc-	cur-	ren-	ces
V	k @r	V n	s V z
oc-	cur-	rence
V	k @r	V n s
oc-	cur-	ring
V	k @r	I N
oc-	curred
V	k @r d
oc-	curs
V	k @r z
oc-	ker
Q	k @r
oc-	ta-	go-	nal
Q k	t {	g V	n V l
oc-	ta-	gon
Q k	t V	g Q n
oc-	ta-	hed-	ral
Q k	t V	h i: d	r V l
oc-	ta-	hed-	ron
Q k	t V	h i: d	r V n
oc-	ta-	vi-	a
Q k	t eI	v i:	V
oc-	ta-	vi-	o
Q k	t eI	v i:	@U
oc-	ta-	vi-	us
Q k	t eI	v i:	V s
oc-	ta-	vus
Q k	t V	v u: s
oc-	tane
Q k	t eI n
oc-	tave
Q k	t I v
oc-	taves
Q k	t I v z
oc-	tet
Q k	t e t
oc-	til-	lion
Q k	t I l	j V n
oc-	to-	ber
Q k	t @U	b @r
oc-	to-	ber's
Q k	t @U	b @r z
oc-	to-	ge-	na-	ri-	an
Q k	t V	dZ V	n e@	i:	V n
oc-	to-	pi
Q k	t V	p aI
oc-	to-	pus
Q k	t V	p U s
och
Q k
ochs
Q k s
oct.
O: k t
od-	der
Q	d @r
od-	dest
Q	d V s t
od-	di-	ties
Q	d I	t i: z
od-	di-	ty
Q	d I	t i:
od-	wy-	er
Q d	w i:	@r
odd
Q d
odd-	ball
Q d	b O: l
odd-	balls
Q d	b O: l z
odd-	ly
Q d	l i:
odds
Q d z
odds-	ma-	ker
Q d	z m eI	k @r
odds-	ma-	kers
Q d	z m eI	k @r z
odds-	on
Q d	z Q n
ode
@U d
odes
@U d z
oe-	di-	pal
e	d I	p V l
oe-	di-	pus
@U	d i:	p V s
oer-	li-	kon
O@	l I	k Q n
oes-	ter-	reich
@U s	t @r	aI k
oeu-	vre
u: v	r V
of
V v
of-	fe-	rer
O:	f @r	@r
of-	fe-	ring
O:	f @r	I N
of-	fe-	rings
O:	f @r	I N z
of-	fe-	ring's
O:	f @r	I N z
of-	fen
O:	f V n
of-	fen-	ded
V	f e n	d V d
of-	fen-	der
V	f e n	d @r
of-	fen-	ders
V	f e n	d @r z
of-	fen-	ding
V	f e n	d I N
of-	fen-	ses
V	f e n	s V z
of-	fen-	sive
V	f e n	s I v
of-	fen-	sive-	ly
V	f e n	s I v	l i:
of-	fen-	sives
V	f e n	s I v z
of-	fend
V	f e n d
of-	fends
V	f e n d z
of-	fense
V	f e n s
of-	fer
O:	f @r
of-	fer-	man
O:	f @r	m V n
of-	fered
O:	f @r d
of-	fers
O:	f @r z
of-	fi-	cer
O:	f I	s @r
of-	fi-	cers
O:	f I	s @r z
of-	fi-	cer's
O:	f I	s @r z
of-	fi-	ces
O:	f I	s V z
of-	fi-	ce's
O:	f I	s V z
of-	fi-	ci-	a-	ted
V	f I	S i:	eI	t V d
of-	fi-	ci-	a-	ting
V	f I	S i:	eI	t I N
of-	fi-	ci-	ate
V	f I	S i:	eI t
of-	fi-	ci-	o
V	f I	s i:	@U
of-	fi-	cial
V	f I	S V l
of-	fi-	cial-	dom
V	f I	S V l	d V m
of-	fi-	cial-	ly
V	f I	S V	l i:
of-	fi-	cials
V	f I	S V l z
of-	fi-	cial's
V	f I	S V l z
of-	fice
O:	f I s
of-	fice-	hol-	der
O:	f I s	h @U l	d @r
of-	fice-	hol-	ders
O:	f I s	h @U l	d @r z
of-	fice-	max
O:	f I s	m { k s
of-	fing
O:	f I N
of-	futt
Q	f V t
of-	te-	ner
O:	f V	n @r
of-	ten
O:	f V n
of-	ten-	times
O:	f V n	t aI m z
off
Q f
off-	beat
O: f	b i: t
off-	hand
O: f	h { n d
off-	set
O: f	s e t
off-	set-	ting
O: f	s e	t I N
off-	sets
O: f	s e t s
off-	shoot
O: f	S u: t
off-	shoots
O: f	S u: t s
off-	shore
O: f	S O@
off-	spring
O: f	s p r I N
off-	stage
O: f	s t eI dZ
offs
O: f s
oft
O: f t
og
Q g
og-	burn
Q g	b @r n
og-	den
Q g	d V n
og-	la-	la
@U g	l Q	l V
ogg
Q g
oh
@U
ohl
@U l
ohl-	man
@U l	m V n
ohm
@U m
ohms
@U m z
ohm's
@U m z
ohs
@U z
oh's
@U z
oi
OI
oi-	ler
OI	l @r
oi-	lers
OI	l @r z
oi-	ling
OI	l I N
oi-	ly
OI	l i:
oie
OI
oil
OI l
oil-	field
OI l	f i: l d
oil-	fields
OI l	f i: l d z
oil-	man
OI l	m { n
oil-	men
OI l	m e n
oil-	seed
OI l	s i: d
oil-	seeds
OI l	s i: d z
oil-	well
OI l	w e l
oiled
OI l d
oils
OI l z
oil's
OI l z
oint-	ment
OI n	t m V n t
ok-	la-	ho-	ma
@U k	l V	h @U	m V
ok-	la-	ho-	man
@U k	l V	h @U	m V n
ok-	la-	ho-	mans
@U k	l V	h @U	m V n z
ok-	la-	ho-	ma's
@U k	l V	h @U	m V z
ok-	ra
@U k	r V
ok-	wu
O: k	w u:
ol'
@U l
ol-	cott
@U l	k V t
ol-	den
@U l	d V n
ol-	den-	burg
@U l	d V n	b @r g
ol-	der
@U l	d @r
ol-	dest
@U l	d V s t
ol-	die
@U l	d i:
ol-	dies
@U l	d i: z
ol-	fac-	to-	ry
@U l	f { k	t @r	i:
ol-	ga
@U l	g V
ol-	lie
Q	l i:
ol-	ly
Q	l i:
ol-	ney
@U l	n i:
ol-	sen
@U l	s V n
ol-	son
@U l	s V n
ol-	son's
@U l	s V n z
ol-	va
@U l	v V
old
@U l d
old-	fa-	shioned
@U l	d f {	S V n d
old-	field
@U l	d f i: l d
old-	ham
@U l	d V m
old-	man
@U l	d m V n
old-	ti-	mer
@U l	d t aI	m @r
old-	ti-	mers
@U l	d t aI	m @r z
olde
@U l d
olds
@U l d z
old's
@U l d z
olds-	mo-	bile
@U l	d z m @U	b i: l
olds-	mo-	bile's
@U l	d z m @U	b i: l z
olds-	ter
@U l	d s t @r
olds-	ters
@U l	d s t @r z
ole
@U l
olm-	stead
@U l	m s t e d
ols-	son
@U l	s V n
olt
@U l t
om-	buds-	man
Q m	b V d	z m V n
om-	ni
Q m	n i:
om-	ni-	bu-	ses
Q m	n I	b V	s V z
om-	ni-	bus
Q m	n I	b V s
om-	ni-	po-	tence
Q m	n I	p V	t V n s
om-	ni-	po-	tent
Q m	n I	p V	t V n t
om-	ni-	pre-	sence
Q m	n I p	r e	z V n s
om-	ni-	pre-	sent
Q m	n I p	r e	z V n t
om-	ni-	scient
Q m	n I	S V n t
om-	ni-	vo-	rous
Q m	n I	v @r	V s
ome-	let
Q m	l V t
ome-	lets
Q m	l V t s
on
Q n
on-	board
Q n	b O@ d
on-	co-	ge-	nes
Q N	k Q	dZ e	n i: s
on-	co-	gen
Q N	k @U	g V n
on-	co-	gene
Q N	k @U	dZ i: n
on-	co-	lo-	gist
Q N	k Q	l V	dZ V s t
on-	co-	lo-	gists
Q N	k Q	l V	dZ V s t s
on-	co-	lo-	gy
Q N	k Q	l V	dZ i:
on-	co-	ming
O: n	k V	m I N
on-	daa-	tje
Q n	d Q t	j V
on-	der
Q n	d @r
on-	do
O: n	d @U
on-	go-	ing
Q n	g @U	I N
on-	ley
Q n	l i:
on-	line
O: n	l aI n
on-	loo-	ker
O: n	l U	k @r
on-	loo-	kers
O: n	l U	k @r z
on-	ly
@U n	l i:
on-	ru-	shing
Q n	r V	S I N
on-	screen
Q n	s k r i: n
on-	set
Q n	s e t
on-	shore
Q n	S O@
on-	site
Q n	s aI t
on-	slaught
O: n	s l O: t
on-	slow
Q n	s l @U
on-	stad
Q n	s t V d
on-	stage
Q n	s t eI dZ
on-	ta-	ri-	o
Q n	t e@	i:	@U
on-	ta-	ri-	o's
Q n	t e@	i:	@U z
on-	to
Q n	t u:
on-	to-	ge-	ny
Q n	t Q	dZ V	n i:
on-	to-	lo-	gi-	cal
Q n	t V	l Q	dZ I	k V l
on-	to-	lo-	gy
Q n	t Q	l V	dZ i:
on-	ward
O: n	w @r d
on-	wards
Q n	w @r d z
on-	yx
Q	n I k s
once
w V n s
one
w V n
one-	ness
w V n	n V s
one-	self
w V n	s e l f
one-	time
w V n	t aI m
one-	up-	man-	ship
w V	n V p	m V n	S I p
one-	year
w V n	j I@
ones
w V n z
one's
w V n z
ong
O: N
ons
Q n z
oo-	dles
u:	d V l z
oo-	long
u:	l O: N
oo-	na
u:	n V
oo-	zes
u:	z V z
oo-	zing
u:	z I N
oohs
u: z
oomph
u: m f
oops
u: p s
ooze
u: z
oozed
u: z d
op
Q p
op-	dyke
Q p	d aI k
op-	he-	lia
V	f i: l	j V
op-	heim
Q p	h aI m
op-	pen-	hei-	mer
Q	p V n	h aI	m @r
op-	pen-	hei-	mer's
Q	p V n	h aI	m @r z
op-	pen-	heim
Q	p V n	h aI m
op-	pens
Q	p V n z
op-	po-	nent
V	p @U	n V n t
op-	po-	nents
V	p @U	n V n t s
op-	po-	nent's
V	p @U	n V n t s
op-	po-	ses
V	p @U	z V z
op-	po-	si-	tion
Q	p V	z I	S V n
op-	po-	si-	tion's
Q	p V	z I	S V n z
op-	po-	sing
V	p @U	z I N
op-	po-	site
Q	p V	z V t
op-	po-	sites
Q	p V	z V t s
op-	por-	tu-	ni-	sm
Q	p @r	t u:	n I	z V m
op-	por-	tu-	ni-	ties
Q	p @r	t u:	n I	t i: z
op-	por-	tu-	ni-	ty
Q	p @r	t u:	n I	t i:
op-	por-	tu-	nis-	tic
Q	p @r	t u:	n I s	t I k
op-	por-	tu-	nist
Q	p @r	t u:	n I s t
op-	por-	tu-	nists
Q	p @r	t u:	n I s t s
op-	por-	tune
Q	p @r	t u: n
op-	pose
V	p @U z
op-	posed
V	p @U z d
op-	pres-	sing
V p	r e	s I N
op-	pres-	sion
V p	r e	S V n
op-	pres-	sions
V p	r e	S V n z
op-	pres-	sive
V p	r e	s I v
op-	pres-	sor
V p	r e	s @r
op-	pres-	sors
V p	r e	s @r z
op-	press
V p	r e s
op-	pressed
V p	r e s t
op-	pro-	bri-	um
V p	r @U b	r i:	V m
op-	rah
@U p	r V
op-	rah's
@U p	r V z
op-	ta-	tion
Q p	t eI	S V n
op-	ted
Q p	t V d
op-	ti-	cal
Q p	t I	k V l
op-	ti-	cian
Q p	t I	S V n
op-	ti-	cians
Q p	t I	S V n z
op-	ti-	ma
Q p	t I	m V
op-	ti-	mal
Q p	t I	m V l
op-	ti-	mi-	sm
Q p	t I	m I	z V m
op-	ti-	mi-	za-	tion
Q p	t I	m I	z eI	S V n
op-	ti-	mis-	ti-	cal-	ly
Q p	t I	m I s	t I	k V	l i:
op-	ti-	mis-	tic
Q p	t I	m I s	t I k
op-	ti-	mist
Q p	t I	m I s t
op-	ti-	mists
Q p	t I	m I s t s
op-	ti-	mize
Q p	t I	m aI z
op-	ti-	mum
Q p	t I	m V m
op-	tic
Q p	t I k
op-	tical-	ly
Q p	t I k	l i:
)"
R"(op-	tics
Q p	t I k s
op-	ting
Q p	t I N
op-	tio-	nal
Q p	S V	n V l
op-	tion
Q p	S V n
op-	tioned
Q p	S V n d
op-	tions
Q p	S V n z
op-	tion's
Q p	S V n z
op-	to-	met-	ric
Q p	t @U	m e t	r I k
op-	to-	met-	rist
Q p	t Q	m V t	r I s t
op-	to-	met-	rists
Q p	t Q	m V t	r I s t s
op-	to-	met-	ry
Q p	t Q	m V t	r i:
ope-	ra
Q p	r V
ope-	ras
Q p	r V z
ope-	ra's
Q p	r V z
oph-	thal-	mic
Q f	T { l	m I k
oph-	thal-	mo-	lo-	gist
Q p	T V	m Q	l V	dZ V s t
oph-	thal-	mo-	lo-	gists
Q p	T V	m Q	l V	dZ V s t s
oph-	thal-	mo-	lo-	gy
Q p	T V	m Q	l V	dZ i:
oph-	thal-	mo-	scope
Q f	T { l	m V s	k @U p
opp
Q p
ops
Q p s
op's
Q p s
opt
Q p t
opts
Q p t s
or
O@
or-	ban
O@	b V n
or-	bi-	tal
O@	b I	t V l
or-	bi-	ted
O@	b I	t I d
or-	bi-	ter
O@	b I	t @r
or-	bi-	ters
O@	b I	t @r z
or-	bi-	ting
O@	b I	t I N
or-	bit
O@	b I t
or-	bits
O@	b I t s
or-	ca
O@	k V
or-	cas
O@	k V s
or-	chard
O@	tS @r d
or-	chards
O@	tS @r d z
or-	ches-	tra
O@	k V s	t r V
or-	ches-	tra-	ted
O@	k V s	t r eI	t V d
or-	ches-	tral
O@	k e s	t r V l
or-	ches-	tral-	ly
O@	k e s	t r V	l i:
or-	ches-	tras
O@	k V s	t r V z
or-	ches-	tra's
O@	k V s	t r V z
or-	ches-	trate
O@	k V s	t r eI t
or-	ches-	trates
O@	k V s	t r eI t s
or-	chest-	ra-	ting
O@	k V s	t r eI	t I N
or-	chest-	ra-	tion
O@	k V s	t r eI	S V n
or-	chest-	ra-	tions
O@	k V s	t r eI	S V n z
or-	chid
O@	k I d
or-	chids
O@	k I d z
or-	dai-	ning
O@	d eI	n I N
or-	dain
O@	d eI n
or-	dained
O@	d eI n d
or-	daz
O@	d Q z
or-	de-	ring
O@	d @r	I N
or-	deal
O@	d i: l
or-	deals
O@	d i: l z
or-	der
O@	d @r
or-	der-	li-	ness
O@	d @r	l i:	n V s
or-	der-	ly
O@	d @r	l i:
or-	dered
O@	d @r d
or-	ders
O@	d @r z
or-	der's
O@	d @r z
or-	di-	na-	ri-	ly
O@	d I	n e@	I	l i:
or-	di-	na-	ries
O@	d I	n e@	i: z
or-	di-	na-	ry
O@	d I	n e@	i:
or-	di-	na-	tion
O@	d I	n eI	S V n
or-	di-	nan-	ces
O@	d I	n V n	s V z
or-	di-	nance
O@	d I	n V n s
or-	field
O@	f i: l d
or-	ford
O@	f @r d
or-	ga-	nelles
O@	g V	n e l z
or-	ga-	ni-	sa-	tion
O@	g V	n V	z eI	S V n
or-	ga-	ni-	sm
O@	g V	n I	z V m
or-	ga-	ni-	sms
O@	g V	n I	z V m z
or-	ga-	ni-	sm's
O@	g V	n I	z V m z
or-	ga-	ni-	za-	tio-	nal
O@	g V	n V	z eI	S V	n V l
or-	ga-	ni-	za-	tion
O@	g V	n V	z eI	S V n
or-	ga-	ni-	za-	tions
O@	g V	n V	z eI	S V n z
or-	ga-	ni-	za-	tion's
O@	g V	n V	z eI	S V n z
or-	ga-	ni-	zer
O@	g V	n aI	z @r
or-	ga-	ni-	zers
O@	g V	n aI	z @r z
or-	ga-	ni-	zes
O@	g V	n aI	z V z
or-	ga-	ni-	zing
O@	g V	n aI	z I N
or-	ga-	nic
O@	g {	n I k
or-	ga-	nical-	ly
O@	g {	n I k	l i:
or-	ga-	nis-	mic
O@	g V	n I z	m I k
or-	ga-	nist
O@	g V	n V s t
or-	ga-	nize
O@	g V	n aI z
or-	ga-	nized
O@	g V	n aI z d
or-	ga-	no-	ge-	ne-	sis
O@	g V	n @U	dZ e	n V	s V s
or-	ga-	num
O@	g V	n V m
or-	ga-	sm
O@	g {	z V m
or-	ga-	sms
O@	g {	z V m z
or-	gan
O@	g V n
or-	gans
O@	g V n z
or-	gel
O@	g V l
or-	gies
O@	dZ i: z
or-	gy
O@	dZ i:
or-	lan
O@	l V n
or-	lan-	do
O@	l { n	d @U
or-	lan-	do's
O@	l { n	d @U z
or-	land
O@	l V n d
or-	le-	an
O@	l i:	V n
or-	le-	ans
O@	l i:	V n z
or-	le-	an's
O@	l i:	V n z
or-	le-	na
O@	l e	n V
or-	lene
O@	l i: n
or-	lich
O@	l I k
or-	lick
O@	l I k
or-	lo-	sky
O@	l @U s	k i:
or-	loff
O@	l O: f
or-	ly
O@	l i:
or-	man
O@	m V n
or-	mand
O@	m V n d
or-	mis-	ton
O@	m I s	t Q n
or-	mond
O@	m V n d
or-	na
O@	n V
or-	na-	men-	ta-	tion
O@	n V	m e n	t eI	S V n
or-	na-	men-	tal
O@	n V	m e n	t V l
or-	na-	men-	ted
O@	n V	m e n	t V d
or-	na-	ment
O@	n V	m V n t
or-	na-	ments
O@	n V	m V n t s
or-	nate
O@	n eI t
or-	ne-	ry
O@	n @r	i:
or-	ni-	tho-	lo-	gi-	cal
O@	n I	T V	l O:	dZ I	k V l
or-	ni-	tho-	lo-	gy
O@	n I	T Q	l V	dZ i:
or-	pah
O@	p Q
or-	pha-	na-	ges
O@	f V	n I	dZ V z
or-	pha-	nage
O@	f V	n V dZ
or-	pha-	ning
O@	f V	n I N
or-	phan
O@	f V n
or-	phaned
O@	f V n d
or-	phans
O@	f V n z
or-	phe-	um
O@	f i:	u: m
or-	phe-	us
O@	f i:	V s
or-	phic
O@	f I k
or-	pi-	ment
O@	p I	m e n t
or-	ran
O@	Q n
or-	re-	ry
O@	@r	i:
or-	ren
O@	V n
or-	rick
O@	I k
or-	rin
O@	I n
or-	ris
O@	I s
or-	sa
O@	s V
or-	say
O@	s eI
or-	si-	ni
O@	s i:	n i:
or-	si-	no
O@	s i:	n @U
or-	so-	la
O@	s @U	l V
or-	son
O@	s V n
or-	te-	ga
O@	t eI	g V
or-	te-	ga's
O@	t eI	g V z
or-	ten
O@	t V n
or-	tho
O@	T @U
or-	tho-	clase
O@	T V k	l eI s
or-	tho-	do-	xy
O@	T V	d Q k	s i:
or-	tho-	don-	ti-	a
O@	T V	d Q n	tS i:	V
or-	tho-	don-	tic
O@	T V	d Q n	t I k
or-	tho-	don-	tics
O@	T V	d Q n	t I k s
or-	tho-	don-	tist
O@	T V	d Q n	t V s t
or-	tho-	don-	tists
O@	T V	d Q n	t V s t s
or-	tho-	don-	tist's
O@	T V	d Q n	t V s t s
or-	tho-	dox
O@	T V	d Q k s
or-	tho-	gra-	phy
O@	T Q g	r V	f i:
or-	tho-	pe-	dic
O@	T V	p i:	d I k
or-	tho-	pe-	dist
O@	T V	p i:	d V s t
or-	tho-	pe-	dists
O@	T V	p i:	d V s t s
or-	tiz
O@	t i: z
or-	ton
O@	t V n
or-	va
O@	v V
or-	val
O@	v V l
or-	ville
O@	v I l
or-	wel-	li-	an
O@	w e	l i:	V n
or-	well
O@	w e l
or-	well's
O@	w e l z
orb
O@ b
ord
O@ d
ord-	nan-	ce's
O@ d	n V n	s V z
ord-	nance
O@ d	n V n s
ord-	way
O@ d	w eI
ore
O@
ores
O@ z
orf
O@ f
org
O@ g
ork-	ney
O@ k	n i:
orme
O@ m
orms-	by
O@ m	z b i:
orne
O@ n
orr
O@
ort
O@ t
ort-	man
O@ t	m V n
orth
O@ T
os
Q s
o's
@U z
os-	bert
Q s	b @r t
os-	born
O: z	b O@ n
os-	borne
O: z	b O@ n
os-	borne's
O: z	b O@ n z
os-	bourn
Q s	b @r n
os-	bourne
Q s	b @r n
os-	burn
Q s	b @r n
os-	car
O: s	k @r
os-	cars
O: s	k @r z
os-	car's
O: s	k @r z
os-	ce-	o-	la
O: s	k i:	@U	l V
os-	cil-	la-	ting
Q	s I	l eI	t I N
os-	cil-	la-	tion
Q	s I	l eI	S V n
os-	cil-	la-	tions
Q	s I	l eI	S V n z
os-	cil-	la-	to-	ry
Q	s I	l V	t O@	i:
os-	cil-	la-	tor
Q	s I	l eI	t @r
os-	cil-	la-	tors
Q	s I	l eI	t @r z
os-	cil-	late
Q	s I	l eI t
os-	cil-	lates
Q	s I	l eI t s
os-	cil-	los-	cope
O:	s I	l V s	k @U p
os-	cil-	los-	copes
O:	s I	l V s	k @U p s
os-	co
Q s	k @U
os-	good
Q s	g U d
os-	kar
O: s	k @r
os-	ler
Q z	l @r
os-	lo
Q z	l @U
os-	man
Q s	m V n
os-	mi-	um
Q z	m i:	V m
os-	mo-	sis
O: z	m @U	s I s
os-	mo-	tic
Q z	m Q	t I k
os-	mond
Q s	m V n d
os-	mund
Q s	m V n d
os-	ric
Q z	r I k
os-	sa
Q	s V
os-	se-	tia
Q	s e S	j V
os-	se-	tian
Q	s e S	j V n
os-	se-	tians
Q	s e S	j V n z
os-	si-	cles
Q	s I	k V l z
os-	si-	fi-	ca-	tion
Q	s I	f I	k eI	S V n
os-	si-	fied
Q	s I	f aI d
os-	si-	fy
Q	s I	f aI
os-	so
@U	s @U
os-	te-	o-	arth-	ri-	tis
Q s	t i:	@U	Q@ T	r aI	t I s
os-	te-	o-	pa-	thic
Q s	t i:	V	p {	T I k
os-	te-	o-	po-	ro-	sis
O: s	t i:	Q	p @r	@U	s I s
os-	teen
Q s	t i: n
os-	ten
Q	s V n
os-	ten-	si-	ble
Q s	t e n	s I	b V l
os-	ten-	sib-	ly
Q s	t e n	s I b	l i:
os-	ten-	ta-	tion
O: s	t e n	t eI	S V n
os-	ten-	ta-	tious
Q s	t V n	t eI	S V s
os-	ten-	ta-	tious-	ly
Q s	t V n	t eI	S V s	l i:
os-	ter
Q s	t @r
os-	ti-	a
Q s	t i:	V
os-	ti-	na-	to
Q s	t I	n Q	t @U
os-	wald
O: z	w O: l d
os-	wald's
O: z	w O: l d z
os-	we-	go
Q s	w i:	g @U
os-	well
Q s	w e l
ose
@U z
osh
Q S
osh-	kosh
O: S	k O: S
osp-	rey
O: s	p r i:
oss
O: s
oss-	wald
Q s	w V l d
ost
@U s t
ost-	po-	li-	tik
@U s	t p @U	l I	t I k
ost-	ra-	ci-	sm
O: s	t r V	s I	z V m
ost-	ra-	cize
O: s	t r V	s aI z
ost-	ra-	cized
O: s	t r V	s aI z d
ost-	ran-	der
Q s	t r V n	d @r
ost-	ri-	ches
Q s	t r I	tS V z
ost-	rich
O: s	t r I tS
ost-	ro-	goth
Q s	t r V	g Q T
ost-	ro-	goths
Q s	t r V	g Q T s
ost-	wald
Q s	t w V l d
ot
O: t
ot-	se-	go
Q t	s eI	g @U
ot-	ta-	wa
Q	t V	w Q
ot-	ta-	wa's
Q	t V	w V z
ot-	ter
Q	t @r
ot-	ter-	bein
Q	t @r	b aI n
ot-	ters
Q	t @r z
ot-	ti-	lie
Q	t I	l i:
ot-	to
Q	t @U
ot-	to-	man
Q	t V	m V n
ot-	to-	sen
Q	t @U	s V n
ot-	to's
Q	t @U z
ot-	well
Q t	w e l
oth-	man
Q T	m V n
ott
Q t
ott-	ley
Q t	l i:
otte
Q t
ou-	r-	self
aU	@r	s e l f
ou-	r-	selves
aU	@r	s e l v z
ou-	rs
aU	@r z
ou-	t-	ler
aU	t V	l @r
ou-	tage
aU	t V dZ
ou-	ted
aU	t V d
ou-	ten
aU	t V n
ou-	ter
aU	t @r
ou-	ter-	most
aU	t @r	m @U s t
ou-	ter-	wear
aU	t @r	w e@
ou-	ting
aU	t I N
ou-	tings
aU	t I N z
ouch
aU tS
ough-	tn't
O:	t V n t
ought
O: t
oui
w i:
oun-	ces
aU n	s V z
ounce
aU n s
out
aU t
out-	bid
aU t	b I d
out-	bid-	ding
aU t	b I	d I N
out-	board
aU t	b O@ d
out-	bound
aU t	b aU n d
out-	break
aU t	b r eI k
out-	breaks
aU t	b r eI k s
out-	burst
aU t	b @r s t
out-	bursts
aU t	b @r s t s
out-	cast
aU t	k { s t
out-	casts
aU t	k { s t s
out-	class
aU t	k l { s
out-	come
aU t	k V m
out-	comes
aU t	k V m z
out-	cries
aU t	k r aI z
out-	cry
aU t	k r aI
out-	da-	ted
aU t	d eI	t V d
out-	date
aU t	d eI t
out-	did
aU t	d I d
out-	dis-	tan-	cing
aU t	d I s	t V n	s I N
out-	do
aU t	d u:
out-	done
aU t	d V n
out-	door
aU t	d O@
out-	doors
aU t	d O@ z
out-	fiel-	der
aU t	f i: l	d @r
out-	fiel-	ders
aU t	f i: l	d @r z
out-	field
aU t	f i: l d
out-	fit
aU t	f I t
out-	fit-	ted
aU t	f I	t V d
out-	fit-	ter
aU t	f I	t @r
out-	fit-	ting
aU t	f I	t I N
out-	fits
aU t	f I t s
out-	flank
aU t	f l { N k
out-	flanked
aU t	f l { N k t
out-	flow
aU t	f l @U
out-	flows
aU t	f l @U z
out-	fox
aU t	f Q k s
out-	foxed
aU t	f Q k s t
out-	gain
aU t	g eI n
out-	gained
aU t	g eI n d
out-	go
aU t	g @U
out-	go-	ing
aU t	g @U	I N
out-	grew
aU t	g r u:
out-	gro-	wing
aU t	g r @U	I N
out-	grow
aU t	g r @U
out-	grown
aU t	g r @U n
out-	growth
aU t	g r @U T
out-	guess
aU t	g e s
out-	gun
aU t	g V n
out-	gunned
aU t	g V n d
out-	hou-	ses
aU t	h aU	s V z
out-	house
aU t	h aU s
out-	lan-	dish
aU t	l { n	d I S
out-	land
aU t	l { n d
out-	las-	ted
aU t	l { s	t V d
out-	last
aU t	l { s t
out-	law
aU t	l O:
out-	law-	ing
aU t	l O:	I N
out-	law-	ry
aU t	l O@	i:
out-	lawed
aU t	l O: d
out-	laws
aU t	l O: z
out-	lay
aU t	l eI
out-	lays
aU t	l eI z
out-	let
aU t	l e t
out-	lets
aU t	l e t s
out-	let's
aU t	l e t s
out-	li-	er
aU t	l aI	@r
out-	li-	ning
aU t	l aI	n I N
out-	line
aU t	l aI n
out-	lined
aU t	l aI n d
out-	lines
aU t	l aI n z
out-	live
aU t	l I v
out-	lived
aU t	l I v d
out-	look
aU t	l U k
out-	looks
aU t	l U k s
out-	ly-	ing
aU t	l aI	I N
out-	ma-	neu-	ver
aU t	m V	n u:	v @r
out-	ma-	neu-	vered
aU t	m V	n u:	v @r d
out-	man
aU t	m V n
out-	manned
aU t	m { n d
out-	mo-	ded
aU t	m @U	d V d
out-	mode
aU t	m @U d
out-	num-	be-	ring
aU t	n V m	b @r	I N
out-	num-	ber
aU t	n V m	b @r
out-	num-	bered
aU t	n V m	b @r d
out-	num-	bers
aU t	n V m	b @r z
out-	pa-	ces
aU t	p eI	s V z
out-	pa-	cing
aU t	p eI	s I N
out-	pa-	tient
aU t	p eI	S V n t
out-	pace
aU t	p eI s
out-	paced
aU t	p eI s t
out-	per-	for-	ming
aU t	p @r	f O@	m I N
out-	per-	form
aU t	p @r	f O@ m
out-	per-	formed
aU t	p @r	f O@ m d
out-	per-	forms
aU t	p @r	f O@ m z
out-	place-	ment
aU t	p l eI s	m V n t
out-	post
aU t	p @U s t
out-	posts
aU t	p @U s t s
out-	pou-	ching
aU t	p aU	tS I N
out-	pou-	ring
aU t	p O@	I N
out-	pour
aU t	p O@
out-	put
aU t	p U t
out-	puts
aU t	p U t s
out-	ra-	geous
aU t	r eI	dZ V s
out-	ra-	geous-	ly
aU t	r eI	dZ V s	l i:
out-	ra-	geous-	ness
aU t	r eI	dZ V s	n V s
out-	ra-	ges
aU t	r eI	dZ V z
out-	ra-	ging
aU t	r eI	dZ I N
out-	rage
aU t	r eI dZ
out-	raged
aU t	r eI dZ d
out-	reach
aU t	r i: tS
out-	ri-	der
aU t	r aI	d @r
out-	ri-	ders
aU t	r aI	d @r z
out-	rig-	ger
aU t	r I	g @r
out-	right
aU t	r aI t
out-	run
aU t	r V n
out-	score
aU t	s k O@
out-	scored
aU t	s k O@ d
out-	sel-	ling
aU t	s e	l I N
out-	sell
aU t	s e l
out-	sells
aU t	s e l z
out-	set
aU t	s e t
out-	shine
aU	tS aI n
out-	shone
aU t	S @U n
out-	si-	der
aU t	s aI	d @r
out-	si-	ders
aU t	s aI	d @r z
out-	si-	der's
aU t	s aI	d @r z
out-	side
aU t	s aI d
out-	sides
aU t	s aI d z
out-	size
aU t	s aI z
out-	sized
aU t	s aI z d
out-	skirt
aU t	s k @r t
out-	skirts
aU t	s k @r t s
out-	smart
aU t	s m Q@ t
out-	sold
aU t	s @U l d
out-	sour-	cing
aU t	s O@	s I N
out-	source
aU t	s O@ s
out-	spen-	ding
aU t	s p e n	d I N
out-	spend
aU t	s p e n d
out-	spent
aU t	s p e n t
out-	spo-	ken
aU t	s p @U	k V n
out-	spo-	ken-	ness
aU t	s p @U	k V	n V s
out-	stan-	ding
aU t	s t { n	d I N
out-	stretch
aU t	s t r e tS
out-	strip
aU t	s t r I p
out-	strip-	ping
aU t	s t r I	p I N
out-	strips
aU t	s t r I p s
out-	ta
u:	t V
out-	take
aU t	t eI k
out-	takes
aU t	t eI k s
out-	vo-	ted
aU t	v @U	t V d
out-	vote
aU t	v @U t
out-	ward
aU t	w @r d
out-	ward-	ly
aU t	w @r d	l i:
out-	wards
aU t	w @r d z
out-	weigh
aU t	w eI
out-	weigh-	ing
aU t	w eI	I N
out-	weighed
aU t	w eI d
out-	weighs
aU t	w eI z
out-	wit
aU t	w I t
out-	wit-	ting
aU t	w I	t I N
outs
aU t s
ow
@U
ow-	ner
@U	n @r
ow-	ner-	ship
@U	n @r	S I p
ow-	ners
@U	n @r z
ow-	ner's
@U	n @r z
ow-	ning
@U	n I N
owe
@U
owed
@U d
owes
@U z
owl
aU l
owls
aU l z
own
@U n
owned
@U n d
owns
@U n z
ox
Q k s
ox-	bow
Q k	s b @U
ox-	bridge
Q k	s b r I dZ
ox-	cart
Q k	s k Q@ t
ox-	fam
Q k	s f { m
ox-	fam's
Q k	s f { m z
ox-	ford
Q k	s f @r d
ox-	fords
Q k	s f @r d z
ox-	ford's
Q k	s f @r d z
ox-	ley
Q k	s l i:
ox-	man
Q k	s m V n
ox-	nard
Q k	s n @r d
oy
OI
oy-	ster
OI s	t @r
oy-	sters
OI s	t @r z
oye
OI
oz
Q z
oz-	zie
Q	z i:
p
ph i:
p-	h
ph i:	eI tS
p-	j's
ph i:	dZ eI z
p-	m
ph i:	e m
p-	p-	m
ph i:	p i:	e m
p.
ph i:
pa
ph Q
pa-	ca
ph Q	k V
pa-	cer
ph eI	s @r
pa-	cers
ph eI	s @r z
pa-	ces
ph eI	s V z
pa-	ce's
ph eI	s V z
pa-	cey
ph eI	s i:
pa-	che-	co
ph V	tS e	k @U
pa-	chin-	ko
ph V	tS I N	k @U
pa-	chy-	san-	dra
ph {	tS V	s { n	d r V
pa-	ci-	fi-	ca
ph V	s I	f I	k V
pa-	ci-	fi-	ca-	tion
ph {	s I	f I	k eI	S V n
pa-	ci-	fi-	co
ph Q	tS i:	f i:	k @U
pa-	ci-	fi-	er
ph {	s I	f aI	@r
pa-	ci-	fi-	ers
ph {	s I	f aI	@r z
pa-	ci-	fi-	sm
ph {	s I	f I	z V m
pa-	ci-	fic
ph V	s I	f I k
pa-	ci-	fic's
ph V	s I	f I k s
pa-	ci-	fied
ph {	s I	f aI d
pa-	ci-	fist
ph {	s I	f I s t
pa-	ci-	fists
ph {	s I	f I s t s
pa-	ci-	fy
ph {	s I	f aI
pa-	ci-	no
ph V	s i:	n @U
pa-	cing
ph eI	s I N
pa-	co
ph eI	k @U
pa-	de-	rew-	ski
ph Q	d @r	u: s	k i:
pa-	den
ph eI	d V n
pa-	dil-	la
ph V	d I	l V
pa-	ga-	ni-	ni
ph {	g V	n i:	n i:
pa-	ga-	ni-	sm
ph eI	g V	n I	z V m
pa-	gan
ph eI	g V n
pa-	gean-	try
ph {	dZ V n	t r i:
pa-	geant
ph {	dZ V n t
pa-	geants
ph {	dZ V n t s
pa-	ger
ph eI	dZ @r
pa-	gers
ph eI	dZ @r z
pa-	ges
ph eI	dZ V z
pa-	ge's
ph eI	dZ V z
pa-	get
ph {	dZ V t
pa-	gi-	na-	tion
ph {	dZ I	n eI	S V n
pa-	ging
ph eI	dZ I N
pa-	go-	da
ph V	g @U	d V
pa-	gu-	ri-	an
ph V g	j U@	i:	V n
pa-	ja-	ma
ph V	dZ Q	m V
pa-	ja-	mas
ph V	dZ Q	m V z
pa-	ke-	ha
ph V	k eI	h Q
pa-	kis-	ta-	ni
ph {	k I s	t {	n i:
pa-	kis-	ta-	nis
ph {	k I s	t {	n i: z
pa-	kis-	tan
ph {	k I s	t { n
pa-	kis-	tan's
ph {	k I s	t { n z
pa-	la-	ces
ph {	l V	s V z
pa-	la-	ci-	o
ph V	l eI	s i:	@U
pa-	la-	ci-	os
ph Q	l Q	s i:	@U z
pa-	la-	ta-	bi-	li-	ty
ph {	l V	t V	b I	l V	t i:
pa-	la-	ta-	ble
ph {	l V	t V	b V l
pa-	la-	tial
ph V	l eI	S V l
pa-	la-	tine
ph {	l V	t aI n
pa-	lace
ph {	l V s
pa-	lais
ph V	l eI
pa-	late
ph {	l V t
pa-	lates
ph {	l V t s
pa-	lau
ph {	l aU
pa-	lau-	ans
ph V	l aU	V n z
pa-	lay
ph eI	l eI
pa-	laz-	zi
ph Q	l Q t	s i:
pa-	laz-	zo
ph V	l Q	z @U
pa-	le-	cek
ph Q	l I	tS e k
pa-	le-	o-	bo-	ta-	ny
ph eI	l i:	@U	b Q	t V	n i:
pa-	le-	o-	cene
ph eI	l i:	V	s i: n
pa-	le-	o-	zo-	ic
ph eI	l i:	V	z @U	I k
pa-	le-	on-	to-	lo-	gist
ph eI	l i:	V n	t Q	l V	dZ V s t
pa-	le-	on-	to-	lo-	gists
ph eI	l i:	V n	t Q	l V	dZ V s t s
pa-	le-	on-	to-	lo-	gy
ph eI	l i:	V n	t Q	l V	dZ i:
pa-	ler-	mo
ph V	l e@	m @U
pa-	les-	ti-	ni-	an
ph {	l V s	t I	n i:	V n
pa-	les-	ti-	ni-	ans
ph {	l V s	t I	n i:	V n z
pa-	les-	tine
ph {	l V s	t aI n
pa-	lest
ph eI	l V s t
pa-	lette
ph {	l V t
pa-	ley
ph eI	l i:
pa-	li-	mo-	ny
ph {	l I	m @U	n i:
pa-	li-	sade
ph {	l I	s eI d
pa-	li-	sades
ph {	l I	s eI d z
pa-	lin
ph {	l I n
pa-	lo
ph {	l @U
pa-	lo-	ma
ph Q	l @U	m V
pa-	lo-	mar
ph {	l V	m Q@
pa-	lo-	me-	ta
ph Q	l @U	m e	t V
pa-	lo-	mi-	no
ph {	l V	m i:	n @U
pa-	los
ph Q	l @U z
pa-	lum-	bo
ph V	l V m	b @U
pa-	me-	la
ph {	m V	l V
pa-	me-	la's
ph {	m V	l V z
pa-	me-	li-	na
ph Q	m e	l i:	n V
pa-	mel-	la
ph V	m e	l V
pa-	na-	ce-	a
ph {	n V	s i:	V
pa-	na-	ma
ph {	n V	m Q
pa-	na-	ma-	ni-	an
ph {	n V	m eI	n i:	V n
pa-	na-	ma-	ni-	ans
ph {	n V	m eI	n i:	V n z
pa-	na-	ma's
ph {	n V	m Q z
pa-	na-	so-	nic
ph {	n V	s Q	n I k
pa-	nache
ph V	n Q S
pa-	ne-	li-	za-	tion
ph {	n V	l V	z eI	S V n
pa-	ne-	ling
ph {	n V	l I N
pa-	ne-	list
ph {	n V	l V s t
pa-	ne-	lists
ph {	n V	l V s t s
pa-	ne-	lized
ph {	n V	l aI z d
pa-	nel
ph {	n V l
pa-	neled
ph {	n V l d
pa-	nels
ph {	n V l z
pa-	nel's
ph {	n V l z
pa-	nic
ph {	n I k
pa-	nic-	king
ph {	n I	k I N
pa-	nic-	ky
ph {	n I	k i:
pa-	nicked
ph {	n I k t
pa-	nics
ph {	n I k s
pa-	nic's
ph {	n I k s
pa-	no-	ply
ph {	n Q p	l i:
pa-	no-	ra
ph V	n O@	V
pa-	no-	ra-	ma
ph {	n @r	{	m V
pa-	no-	ra-	mic
ph {	n @r	{	m I k
)"
R"(pa-	pa
ph Q	p V
pa-	pa-	cy
ph eI	p V	s i:
pa-	pa-	do-	pou-	los
ph {	p V	d Q	p V	l V s
pa-	pa-	go
ph Q	p V	g @U
pa-	pa-	raz-	zi
ph Q	p Q@	O:	z i:
pa-	pa-	ya
ph V	p aI	V
pa-	pa-	yas
ph V	p aI	V z
pa-	pal
ph eI	p V l
pa-	pan-	dre-	ou
ph V	p { n	d r i:	u:
pa-	pas
ph Q	p V z
pa-	paw
ph O:	p O:
pa-	pe-	ring
ph eI	p @r	I N
pa-	pe-	ry
ph eI	p @r	i:
pa-	per
ph eI	p @r
pa-	per-	back
ph eI	p @r	b { k
pa-	per-	backs
ph eI	p @r	b { k s
pa-	per-	board
ph eI	p @r	b O@ d
pa-	per-	boy
ph eI	p @r	b O: j
pa-	per-	boys
ph eI	p @r	b O: j z
pa-	per-	boy's
ph eI	p @r	b O: j z
pa-	per-	less
ph eI	p @r	l V s
pa-	per-	ma-	king
ph {	p @r	m eI	k I N
pa-	per-	weight
ph eI	p @r	w eI t
pa-	per-	work
ph eI	p @r	w @r k
pa-	pered
ph eI	p @r d
pa-	pers
ph eI	p @r z
pa-	per's
ph eI	p @r z
pa-	pesh
ph {	p I S
pa-	pi-	neau
ph {	p I	n @U
pa-	pier
ph eI p	j @r
pa-	pil-	lo-	ma
ph {	p I	l @U	m V
pa-	pu-	a
ph { p	j u:	V
pa-	quet
ph Q	k eI t
pa-	ra
ph e@	V
pa-	ra-	ble
ph e@	V	b V l
pa-	ra-	bles
ph e@	V	b V l z
pa-	ra-	bo-	la
ph @r	{	b V	l V
pa-	ra-	bo-	lic
ph e@	V	b Q	l I k
pa-	ra-	chu-	ted
ph e@	I	S u:	t V d
pa-	ra-	chu-	ting
ph e@	I	S u:	t I N
pa-	ra-	chute
ph e@	I	S u: t
pa-	ra-	chutes
ph e@	I	S u: t s
pa-	ra-	da
ph @r	{	d V
pa-	ra-	ded
ph @r	eI	d V d
pa-	ra-	di-	so
ph @r	V	d i:	s @U
pa-	ra-	digm
ph e@	V	d aI m
pa-	ra-	digms
ph e@	V	d aI m z
pa-	ra-	ding
ph @r	eI	d I N
pa-	ra-	dis
ph @r	{	d I s
pa-	ra-	dise
ph e@	V	d aI s
pa-	ra-	do-	xes
ph e@	V	d Q k	s V z
pa-	ra-	do-	xi-	cal
ph e@	V	d Q k	s I	k V l
pa-	ra-	do-	xical-	ly
ph e@	V	d Q k	s V k	l i:
pa-	ra-	dor
ph e@	V	d O@
pa-	ra-	dox
ph e@	V	d Q k s
pa-	ra-	gon
ph e@	V	g Q n
pa-	ra-	graph
ph e@	V g	r { f
pa-	ra-	graphs
ph e@	V g	r { f s
pa-	ra-	guay
ph e@	V g	w eI
pa-	ra-	guay-	an
ph e@	V g	w aI	V n
pa-	ra-	keet
ph e@	V	k i: t
pa-	ra-	keets
ph e@	V	k i: t s
pa-	ra-	le-	gal
ph e@	V	l i:	g V l
pa-	ra-	le-	gals
ph e@	V	l i:	g V l z
pa-	ra-	ly-	sis
ph @r	{	l V	s I s
pa-	ra-	lym-	pic
ph e@	V	l I m	p I k
pa-	ra-	me-	ters
ph @r	{	m V	t @r z
pa-	ra-	met-	ric
ph e@	V	m e t	r I k
pa-	ra-	mi-	li-	ta-	ries
ph e@	V	m I	l V	t e@	i: z
pa-	ra-	mi-	li-	ta-	ry
ph e@	V	m I	l V	t e@	i:
pa-	ra-	mo
ph @r	{	m @U
pa-	ra-	mount
ph e@	V	m aU n t
pa-	ra-	mount's
ph e@	V	m aU n t s
pa-	ra-	mus
ph @r	{	m V s
pa-	ra-	na
ph @r	Q	n V
pa-	ra-	noi-	a
ph e@	V	n OI	V
pa-	ra-	noi-	ac
ph e@	V	n OI	{ k
pa-	ra-	noid
ph e@	V	n OI d
pa-	ra-	nor-	mal
ph e@	V	n O@	m V l
pa-	ra-	pher-	na-	lia
ph e@	V	f V	n eI l	j V
pa-	ra-	phra-	sing
ph e@	V f	r eI	z I N
pa-	ra-	phrase
ph e@	V f	r eI z
pa-	ra-	ple-	gi-	a
ph e@	V p	l i:	dZ i:	V
pa-	ra-	ple-	gic
ph e@	V p	l i:	dZ I k
pa-	ra-	si-	tic
ph e@	V	s I	t I k
pa-	ra-	site
ph e@	V	s aI t
pa-	ra-	sites
ph e@	V	s aI t s
pa-	ra-	sym-	pa-	the-	tic
ph e@	V	s I m	p V	T e	t I k
pa-	ra-	troo-	per
ph e@	V t	r u:	p @r
pa-	ra-	troo-	pers
ph e@	V t	r u:	p @r z
pa-	ra-	troop
ph e@	V t	r u: p
pa-	ra-	troops
ph e@	V t	r u: p s
pa-	ra-	zo-	a
ph e@	V	z @U	V
pa-	rade
ph @r	eI d
pa-	rades
ph @r	eI d z
pa-	raf-	fin
ph e@	V	f V n
pa-	ral-	lax
ph e@	V	l { k s
pa-	ral-	le-	li-	sm
ph e@	V	l e	l I	z V m
pa-	ral-	le-	ling
ph e@	V	l e	l I N
pa-	ral-	lel
ph e@	V	l e l
pa-	ral-	leled
ph e@	V	l e l d
pa-	ral-	lels
ph e@	V	l e l z
pa-	rel-	la
ph Q@	e	l V
pa-	ren-	tage
ph e@	V n	t V dZ
pa-	ren-	tal
ph @r	e n	t V l
pa-	ren-	the-	ses
ph @r	e n	T V	s i: z
pa-	ren-	the-	sis
ph @r	e n	T V	s I s
pa-	ren-	the-	ti-	cal-	ly
ph @r	e n	T e	t I	k V	l i:
pa-	ren-	ting
ph e@	V n	t I N
pa-	rent
ph e@	V n t
pa-	rent-	hood
ph e@	V n	t h U d
pa-	rents
ph e@	V n t s
pa-	rent's
ph e@	V n t s
pa-	ri-	ah
ph @r	aI	V
pa-	ri-	ahs
ph @r	aI	V z
pa-	ri-	e-	tal
ph @r	aI	V	t V l
pa-	ri-	mu-	tu-	el
ph e@	I m	j u:	tS u:	V l
pa-	ri-	shes
ph {	r I	S V z
pa-	ri-	shio-	ner
ph @r	I	S V	n @r
pa-	ri-	shio-	ners
ph @r	I	S V	n @r z
pa-	ri-	si-	ans
ph @r	I	s i:	V n z
pa-	ri-	si-	enne
ph @r	I	s i:	e n
pa-	ri-	sian
ph @r	I	Z V n
pa-	ri-	s's
ph {	r I	s V z
pa-	ri-	ties
ph e@	I	t i: z
pa-	ri-	ty
ph e@	I	t i:
pa-	ring
ph e@	I N
pa-	ris
ph {	r I s
pa-	rish
ph {	r I S
pa-	ro-	chi-	a-	li-	sm
ph @r	@U	k i:	V	l I	z V m
pa-	ro-	chi-	al
ph @r	@U	k i:	V l
pa-	ro-	di
ph Q@	@U	d i:
pa-	ro-	died
ph e@	V	d i: d
pa-	ro-	dies
ph e@	V	d i: z
pa-	ro-	dist
ph {	r V	d I s t
pa-	ro-	dy
ph e@	V	d i:
pa-	ro-	lee
ph @r	@U	l i:
pa-	ro-	lees
ph @r	@U	l i: z
pa-	ro-	ling
ph @r	@U	l I N
pa-	role
ph @r	@U l
pa-	roled
ph @r	@U l d
pa-	roles
ph @r	@U l z
pa-	sa-	de-	na
ph {	s V	d i:	n @r
pa-	se-	o
ph Q	s eI	@U
pa-	sha
ph Q	S Q
pa-	so
ph {	s @U
pa-	so's
ph {	s @U z
pa-	ta-	go-	ni-	a
ph {	t V	g @U	n i:	V
pa-	ta-	go-	ni-	an
ph {	t V	g @U	n i:	V n
pa-	te-	ra
ph Q	t e@	V
pa-	tel
ph V	t e l
pa-	tel-	la
ph V	t e	l V
pa-	ten-	ta-	ble
ph {	t V n	t V	b V l
pa-	ten-	ted
ph {	t V n	t V d
pa-	ten-	ting
ph {	t V n	t I N
pa-	tent
ph {	t V n t
pa-	tent-	ly
ph {	t V n	t l i:
pa-	tents
ph {	t V n t s
pa-	ter
ph eI	t @r
pa-	ter-	na-	li-	sm
ph V	t @r	n V	l I	z V m
pa-	ter-	na-	lis-	tic
ph V	t @r	n V	l I s	t I k
pa-	ter-	nal
ph V	t @r	n V l
pa-	ter-	ni-	ty
ph V	t @r	n V	t i:
pa-	ter-	son
ph {	t @r	s V n
pa-	than
ph {	T V n
pa-	thans
ph {	T V n z
pa-	the-	ti-	cal-	ly
ph V	T e	t I	k V	l i:
pa-	the-	tic
ph V	T e	t I k
pa-	tho-	ge-	nic
ph {	T V	dZ e	n I k
pa-	tho-	gen
ph {	T V	dZ V n
pa-	tho-	gens
ph {	T V	dZ V n z
pa-	tho-	lo-	gi-	cal
ph {	T V	l Q	dZ I	k V l
pa-	tho-	lo-	gical-	ly
ph {	T V	l Q	dZ I k	l i:
pa-	tho-	lo-	gies
ph V	T Q	l V	dZ i: z
pa-	tho-	lo-	gist
ph V	T Q	l V	dZ V s t
pa-	tho-	lo-	gists
ph V	T Q	l V	dZ V s t s
pa-	tho-	lo-	gy
ph V	T Q	l V	dZ i:
pa-	thos
ph eI	T Q s
pa-	ti-	na
ph V	t i:	n V
pa-	ti-	o
ph {	t i:	@U
pa-	ti-	os
ph {	t i:	@U z
pa-	tience
ph eI	S V n s
pa-	tient
ph eI	S V n t
pa-	tient-	ly
ph eI	S V n	t l i:
pa-	tients
ph eI	S V n t s
pa-	tient's
ph eI	S V n t s
pa-	tin
ph {	t I n
pa-	ton
ph {	t V n
pa-	ty
ph eI	t i:
pa-	va-	rot-	ti
ph {	v @r	Q	t i:
pa-	ve-	se
ph Q	v eI	z i:
pa-	vel
ph {	v V l
pa-	ver
ph eI	v @r
pa-	vi-	a
ph eI	v i:	V
pa-	vi-	lion
ph V	v I l	j V n
pa-	vi-	lions
ph V	v I l	j V n z
pa-	vil-	lion
ph V	v I l	j V n
pa-	ving
ph eI	v I N
pa-	vo
ph Q	v @U
pa-	vone
ph V	v @U n
pa-	xon
ph { k	s V n
pa-	ya-	ble
ph eI	V	b V l
pa-	ya-	bles
ph eI	V	b V l z
pa-	yer
ph eI	@r
pa-	yers
ph eI	@r z
pa-	yer's
ph eI	@r z
pa-	yette
ph eI	e t
pa-	yo-	la
ph eI	@U	l V
paar
ph Q@
pab-	lo
ph Q b	l @U
pab-	lum
ph { b	l V m
pabst
ph { b s t
pac
ph { k
pac-	ka-	ger
ph {	k I	dZ @r
pac-	ka-	gers
ph {	k I	dZ @r z
pac-	ka-	ges
ph {	k V	dZ V z
pac-	ka-	ge's
ph {	k I	dZ V z
pac-	ka-	ging
ph {	k I	dZ I N
pac-	kage
ph {	k I dZ
pac-	kaged
ph {	k I dZ d
pac-	kard
ph {	k @r d
pac-	kard's
ph {	k @r d z
pac-	ker
ph {	k @r
pac-	kers
ph {	k @r z
pac-	ket
ph {	k V t
pac-	kets
ph {	k V t s
pac-	king
ph {	k I N
pac-	king-	house
ph {	k I N	h aU s
pac-	man
ph { k	m V n
pace
ph eI s
pace-	ma-	ker
ph eI s	m eI	k @r
pace-	ma-	kers
ph eI s	m eI	k @r z
pace-	set-	ter
ph eI	s e	t @r
pace-	way
ph eI s	w eI
paced
ph eI s t
pack
ph { k
pack-	man
ph { k	m V n
pack-	wood
ph { k	w U d
pack-	wood's
ph { k	w U d z
packed
ph { k t
packs
ph { k s
pacs
ph { k s
pact
ph { k t
pacts
ph { k t s
pact's
ph { k t s
pad
ph { d
pad-	d-	ling
ph {	d V	l I N
pad-	ded
ph {	d V d
pad-	dies
ph {	d i: z
pad-	ding
ph {	d I N
pad-	ding-	ton
ph {	d I N	t V n
pad-	dle
ph {	d V l
pad-	dled
ph {	d V l d
pad-	dles
ph {	d V l z
pad-	dock
ph {	d V k
pad-	dy
ph {	d i:
pad-	dy's
ph {	d i: z
pad-	get
ph {	dZ V t
pad-	gett
ph {	dZ V t
pad-	lock
ph { d	l Q k
pad-	locked
ph { d	l Q k t
pad-	locks
ph { d	l Q k s
pad-	re
ph { d	r eI
pad-	res
ph { d	r eI z
pae
ph aI
paff
ph { f
pag-	li-	a
ph { g	l i:	V
page
ph eI dZ
paged
ph eI dZ d
pah
ph {
pahl
ph Q l
pai-	ring
ph e@	I N
pai-	ute
ph aI	j u: t
paid
ph eI d
paige
ph eI dZ
paik
ph eI k
pail
ph eI l
pails
ph eI l z
pain
ph eI n
pain-	ful
ph eI n	f V l
pain-	ful-	ly
ph eI n	f V	l i:
pain-	kil-	ler
ph eI n	k I	l @r
pain-	kil-	lers
ph eI n	k I	l @r z
pain-	less
ph eI n	l V s
pain-	less-	ly
ph eI n	l V s	l i:
pain-	sta-	king
ph eI n	s t eI	k I N
pain-	sta-	king-	ly
ph eI n	s t eI	k I N	l i:
pain-	ted
ph eI n	t V d
pain-	ter
ph eI n	t @r
pain-	ter-	ly
ph eI n	t @r	l i:
pain-	ters
ph eI n	t @r z
pain-	ter's
ph eI n	t @r z
pain-	ting
ph eI n	t I N
pain-	tings
ph eI n	t I N z
paine
ph eI n
pained
ph eI n d
paines-	ville
ph eI n	z v I l
pains
ph eI n z
paint
ph eI n t
paint-	ball
ph eI n	t b Q l
paint-	bru-	shes
ph eI n	t b r V	S V z
paint-	brush
ph eI n	t b r V S
paints
ph eI n t s
pair
ph e@
paired
ph e@ d
pairs
ph e@ z
pais
ph eI z
pais-	ley
ph eI z	l i:
pais-	ley's
ph eI z	l i: z
pak
ph { k
pal
ph { l
pal-	co
ph { l	k @U
pal-	frey
ph { l	f r i:
pal-	la
ph {	l V
pal-	la-	di-	um
ph V	l eI	d i:	V m
pal-	las
ph {	l V s
pal-	let
ph {	l V t
pal-	lets
ph {	l V t s
pal-	li-	a-	tive
ph {	l i:	V	t I v
pal-	li-	a-	tives
ph {	l i:	V	t I v z
pal-	lid
ph {	l I d
pal-	lo-	ne
ph Q	l @U	n i:
pal-	ma
ph Q l	m V
pal-	ma's
ph Q l	m V z
pal-	me-	ri
ph Q l	m e@	i:
pal-	mer
ph Q	m @r
pal-	mer-	ton
ph Q	m @r	t V n
pal-	mer's
ph Q	m @r z
pal-	met-	to
ph { l	m e	t @U
pal-	mi-	ra
ph Q l	m I@	V
pal-	mi-	tic
ph { l	m I	t I k
pal-	mis-	try
ph Q	m I s	t r i:
pal-	mo-	live
ph Q l	m Q	l I v
pal-	more
ph { l	m O@
pal-	pa-	ble
ph { l	p V	b V l
pal-	pab-	ly
ph { l	p V b	l i:
pal-	pi-	ta-	tion
ph { l	p I	t eI	S V n
pal-	pi-	ta-	tions
ph { l	p I	t eI	S V n z
pal-	sy
ph O: l	z i:
pal-	try
ph O: l	t r i:
pale
ph eI l
paled
ph eI l d
pales
ph eI l z
pall
ph Q l
palm
ph Q m
palm-	dale
ph Q m	d eI l
palm-	dale's
ph Q m	d eI l z
palm-	gren
ph { l	m g r e n
palms
ph Q m z
pals
ph { l z
pal's
ph { l z
paltz
ph O: l t s
pam
ph { m
pam-	my
ph {	m i:
pam-	pas
ph { m	p V z
pam-	pe-	ring
ph { m	p @r	I N
pam-	per
ph { m	p @r
pam-	pered
ph { m	p @r d
pam-	pers
ph { m	p @r z
pam-	phlet
ph { m	f l V t
pamp-	lin
ph { m	p l I n
pamp-	lo-	na
ph { m	p l @U	n V
pamph-	le-	teer
ph { m	f l V	t I@
pamph-	lets
ph { m	f l V t s
pam's
ph { m z
pan
ph { n
pan-	cre-	a-	tic
ph { n	k r i:	{	t I k
pan-	da
ph { n	d V
pan-	da-	nus
ph { n	d eI	n V s
pan-	das
ph { n	d V z
pan-	de-	mic
ph { n	d e	m I k
pan-	de-	mo-	ni-	um
ph { n	d V	m @U	n i:	V m
pan-	de-	ring
ph { n	d @r	I N
pan-	der
ph { n	d @r
pan-	dered
ph { n	d @r d
pan-	dit
ph V n	d I t
pan-	do-	ra
ph { n	d O@	V
pan-	do-	ra's
ph { n	d O@	V z
pan-	dol-	fi
ph Q n	d @U l	f i:
pan-	fil
ph { n	f I l
pan-	ful
ph { n	f V l
pan-	fuls
ph { n	f V l z
pan-	gloss
ph { n	g l Q s
pan-	han-	dle
ph { n	h { n	d V l
pan-	han-	dle's
ph { n	h { n	d V l z
pan-	hand-	ler
ph { n	h { n	d l @r
pan-	hand-	lers
ph { n	h { n	d l @r z
pan-	hand-	ling
ph { n	h { n	d l I N
pan-	ky
ph { N	k i:
pan-	mun-	jom
ph { n	m u: n	dZ O: m
pan-	ni-	er
ph {	n i:	@r
pan-	ning
ph {	n I N
pan-	sies
ph { n	z i: z
pan-	so-	phic
ph { n	s V	f I k
pan-	sy
ph { n	z i:
pan-	ta-	lone
ph { n	t V	l @U n
pan-	ta-	loon
ph { n	t V	l u: n
pan-	ta-	loons
ph { n	t V	l u: n z
pan-	ted
ph { n	t V d
pan-	ter
ph { n	t @r
pan-	the-	a
ph { n	T i:	V
pan-	the-	is-	tic
ph { n	T i:	I s	t I k
pan-	the-	on
ph { n	T i:	Q n
pan-	ther
ph { n	T @r
pan-	thers
ph { n	T @r z
pan-	ther's
ph { n	T @r z
pan-	ties
ph { n	t i: z
pan-	ting
ph { n	t I N
pan-	tle
ph { n	t V l
pan-	to-	mime
ph { n	t V	m aI m
pan-	ton
ph { n	t V n
pan-	try
ph { n	t r i:
pan-	ty
ph { n	t i:
pan-	ty-	hose
ph { n	t i:	h @U z
pan-	za
ph { n	z V
pan-	zer
ph { n	z @r
pane
ph eI n
panes
ph eI n z
pang
ph { N
pang-	burn
ph { N	b @r n
pangs
ph { N z
panned
ph { n d
pans
ph { n z
pan's
ph { n z
pant
ph { n t
pant-	suit
ph { n	t s u: t
pant-	suits
ph { n	t s u: t s
pants
ph { n t s
pao
ph aU
pao-	li
ph aU	l i:
pao-	lo
ph aU	l @U
pap
ph { p
pap-	pa
ph {	p V
pap-	pas
ph {	p V s
pap-	ri-	ka
ph { p	r i:	k V
pape
ph eI p
papke
ph eI p k
papp
ph { p
paque
ph { k
par
ph Q@
par-	boi-	ling
ph Q@	b OI	l I N
par-	boil
ph Q@	b OI l
par-	ce-	ling
ph Q@	s V	l I N
par-	cel
ph Q@	s V l
par-	celed
ph Q@	s V l d
par-	cels
ph Q@	s V l z
par-	cher
ph Q@	tS @r
par-	dee
ph Q@	d i:
par-	di
ph Q@	d i:
par-	do
ph Q@	d @U
par-	do-	ning
ph Q@	d V	n I N
par-	don
ph Q@	d V n
par-	doned
ph Q@	d V n d
par-	dons
ph Q@	d V n z
par-	dus
ph Q@	d V s
par-	dy
ph Q@	d i:
par-	fitt
ph Q@	f I t
par-	ka
ph Q@	k V
par-	kas
ph Q@	k V z
par-	ker
ph Q@	k @r
par-	kers
ph Q@	k @r z
par-	ker's
ph Q@	k @r z
par-	kers-	burg
ph Q@	k @r z	b @r g
par-	kin
ph Q@	k I n
par-	kin-	so-	ni-	sm
ph Q@	k I n	s V	n I	z V m
par-	kin-	son
ph Q@	k I n	s V n
par-	kin-	son's
ph Q@	k I n	s V n z
par-	king
ph Q@	k I N
par-	kins
ph Q@	k I n z
par-	lance
ph Q@	l V n s
par-	lay
ph Q@	l eI
par-	lay-	ing
ph Q@	l eI	I N
par-	layed
ph Q@	l eI d
par-	ley
ph Q@	l i:
par-	li-	er
ph Q@	l i:	@r
par-	lia-	men-	ta-	ri-	a-	ni-	sm
ph Q@	l V	m e n	t e@	i:	V	n I	z V m
par-	lia-	men-	ta-	ri-	an
ph Q@	l V	m e n	t e@	i:	V n
par-	lia-	men-	ta-	ri-	ans
ph Q@	l V	m e n	t e@	i:	V n z
par-	lia-	men-	ta-	ry
ph Q@	l V	m e n	t @r	i:
par-	lia-	ment
ph Q@	l V	m e n t
par-	lia-	ments
ph Q@	l V	m e n t s
par-	lia-	ment's
ph Q@	l V	m e n t s
par-	lin
ph Q@	l I n
par-	lor
ph Q@	l @r
par-	lors
ph Q@	l @r z
par-	lour
ph Q@	l @r
par-	ma
ph Q@	m V
par-	me-	le
ph Q@	m e	l i:
par-	me-	lee
ph Q@	m V	l i:
par-	me-	san
ph Q@	m V	z Q n
par-	men-	ti-	er
ph Q@	m V n	t i:	@r
par-	nas-	sus
ph Q@	n {	s V s
par-	nell
ph Q@	n V l
par-	quet
ph Q@	k eI
par-	ra
ph Q@	V
par-	ried
ph e@	i: d
par-	ril-	lo
ph Q@	I	l @U
par-	ris
ph e@	I s
par-	rish
ph e@	I S
par-	rot
ph e@	V t
par-	rots
ph e@	V t s
par-	rott
ph e@	V t
par-	ry
ph e@	i:
par-	sec
ph Q@	s e k
par-	ser
ph Q@	s @r
par-	shall
ph Q@	S V l
par-	si-	fal
ph Q@	s I	f V l
par-	si-	mo-	ny
ph Q@	s I	m @U	n i:
par-	sing
ph Q@	s I N
par-	sip-	pa-	ny
ph Q@	s I	p V	n i:
par-	so-	nage
ph Q@	s V	n I dZ
par-	son
ph Q@	s V n
par-	sons
ph Q@	s V n z
par-	take
ph Q@	t eI k
par-	ted
ph Q@	t V d
par-	ten
ph Q@	t V n
par-	the-	ni-	a
ph Q@	T e	n i:	V
par-	the-	no-	ge-	ne-	tic
ph Q@	T V	n @U	dZ V	n e	t I k
par-	the-	non
ph Q@	T V	n Q n
par-	thi-	an
ph Q@	T i:	V n
par-	ti
ph Q@	t i:
par-	ti-	a-	li-	ty
ph Q@	S i:	{	l I	t i:
par-	ti-	ci-	pa-	ted
ph Q@	t I	s I	p eI	t I d
par-	ti-	ci-	pa-	ting
ph Q@	t I	s I	p eI	t I N
par-	ti-	ci-	pa-	tion
ph Q@	t I	s I	p eI	S V n
par-	ti-	ci-	pa-	tions
ph Q@	t I	s I	p eI	S V n z
par-	ti-	ci-	pa-	tive
ph Q@	t I	s I	p V	t I v
par-	ti-	ci-	pa-	to-	ry
ph Q@	t I	s I	p V	t O@	i:
par-	ti-	ci-	pant
ph Q@	t I	s I	p V n t
par-	ti-	ci-	pants
ph Q@	t I	s I	p V n t s
par-	ti-	ci-	pate
ph Q@	t I	s I	p eI t
par-	ti-	ci-	pates
ph Q@	t I	s I	p eI t s
par-	ti-	cle
ph Q@	t I	k V l
par-	ti-	cles
ph Q@	t I	k V l z
par-	ti-	cu-	la-	ri-	ty
ph @r	t I k	j V	l {	r V	t i:
par-	ti-	cu-	lar
ph @r	t I k	j V	l @r
par-	ti-	cu-	lar-	ly
ph Q@	t I k	j V	l @r	l i:
par-	ti-	cu-	lars
ph @r	t I k	j V	l @r z
par-	ti-	cu-	late
ph @r	t I k	j V	l V t
par-	ti-	cu-	lates
ph Q@	t I k	j V	l V t s
par-	ti-	san
ph Q@	t I	z V n
par-	ti-	san-	ship
ph Q@	t I	z V n	S I p
par-	ti-	sans
ph Q@	t I	z V n z
par-	ti-	tio-	ning
ph Q@	t I	S V	n I N
par-	ti-	tion
ph Q@	t I	S V n
par-	ti-	tioned
ph Q@	t I	S V n d
par-	ti-	tions
ph Q@	t I	S V n z
par-	tial
ph Q@	S V l
par-	tial-	ly
ph Q@	S V	l i:
par-	tied
ph Q@	t i: d
par-	ties
ph Q@	t i: z
par-	ting
ph Q@	t I N
par-	ton
ph Q@	t V n
par-	tum
ph Q@	t V m
par-	ty
ph Q@	t i:
par-	ty-	ing
ph Q@	t i:	I N
par-	ty's
ph Q@	t i: z
parc
ph Q@ k
parch
ph Q@ tS
parch-	ment
ph Q@ tS	m V n t
parch-	ment-	like
ph Q@ tS	m V n	t l aI k
parched
ph Q@ tS t
parde
ph Q@ d
pare
ph e@
pared
ph e@ d
pares
ph e@ z
park
ph Q@ k
park-	land
ph Q@ k	l { n d
park-	man
ph Q@ k	m V n
park-	way
ph Q@ k	w eI
parke
ph Q@ k
parked
ph Q@ k t
parks
ph Q@ k s
park's
ph Q@ k s
parr
ph Q@
pars
ph Q@ z
par's
ph Q@ z
pars-	ley
ph Q@ s	l i:
parse
ph Q@ s
part
ph Q@ t
part-	low
ph Q@ t	l @U
part-	ly
ph Q@ t	l i:
part-	ner
ph Q@ t	n @r
part-	ner-	ing
ph Q@ t	n @r	I N
part-	ner-	ship
ph Q@ t	n @r	S I p
part-	ner-	ships
ph Q@ t	n @r	S I p s
part-	ner-	ship's
ph Q@ t	n @r	S I p s
part-	ners
ph Q@ t	n @r z
part-	ner's
ph Q@ t	n @r z
part-	ners'
ph Q@ t	n @r z
part-	rid-	ges
ph Q@ t	r I	dZ V z
part-	ridge
ph Q@ t	r I dZ
part-	time
ph Q@ t	t aI m
parte
ph Q@ t
parts
ph Q@ t s
part's
ph Q@ t s
pas
ph Q z
pas-	ca-	gou-	la
ph { s	k V	g u:	l V
pas-	cal
ph { s	k { l
pas-	cale
ph { s	k { l
pas-	chal
ph {	S V l
pas-	co
ph Q s	k @U
pas-	coe
ph { s	k @U
pas-	cu-	a
ph Q s	k u:	V
)"
R"(pas-	cu-	al
ph { s	k u:	V l
pas-	qua-	le
ph Q s	k w Q	l eI
pas-	se-	ro
ph Q	s e@	@U
pas-	sen-	ger
ph {	s V n	dZ @r
pas-	sen-	gers
ph {	s V n	dZ @r z
pas-	sen-	ger's
ph {	s V n	dZ @r z
pas-	ser
ph {	s @r
pas-	ser-	by
ph {	s @r	b i:
pas-	sers
ph {	s @r z
pas-	sers-	by
ph {	s @r z	b i:
pas-	ses
ph {	s V z
pas-	si-	vi-	ty
ph V	s I	v V	t i:
pas-	sim
ph {	s i: m
pas-	sing
ph {	s I N
pas-	sio-	nate
ph {	S V	n I t
pas-	sio-	nate-	ly
ph {	S V	n I t	l i:
pas-	sion
ph {	S V n
pas-	sions
ph {	S V n z
pas-	sive
ph {	s I v
pas-	sive-	ly
ph {	s I v	l i:
pas-	ta
ph Q s	t V
pas-	tas
ph Q s	t V z
pas-	ted
ph eI s	t V d
pas-	tel
ph { s	t e l
pas-	tels
ph { s	t e l z
pas-	ter
ph { s	t @r
pas-	ter-	nak
ph { s	t @r	n { k
pas-	ter-	nak's
ph { s	t @r	n { k s
pas-	teu-	ri-	za-	tion
ph { s	tS @r	I	z eI	S V n
pas-	teu-	rize
ph { s	tS @r	aI z
pas-	teu-	rized
ph { s	tS @r	aI z d
pas-	teur
ph V s	t u: r
pas-	tiche
ph { s	t i: S
pas-	time
ph { s	t aI m
pas-	times
ph { s	t aI m z
pas-	ting
ph eI s	t I N
pas-	to-	ra
ph { s	t O@	V
pas-	to-	ra-	li-	sm
ph { s	t @r	V	l I	z V m
pas-	to-	ral
ph { s	t @r	V l
pas-	tor
ph { s	t @r
pas-	tore
ph { s	t O@
pas-	tors
ph { s	t @r z
pas-	tor's
ph { s	t @r z
pas-	tra-	mi
ph V s	t r Q	m i:
pas-	tries
ph eI s	t r i: z
pas-	try
ph eI s	t r i:
pas-	ture
ph { s	tS @r
pas-	tures
ph { s	tS @r z
pasch
ph { s k
pash
ph { S
pask
ph { s k
paske
ph eI s k
pasque
ph { s k
pass
ph { s
pass-	man
ph { s	m V n
pass-	o-	ver
ph {	s @U	v @r
pass-	port
ph { s	p O@ t
pass-	ports
ph { s	p O@ t s
pass-	word
ph { s	w @r d
pass-	words
ph { s	w @r d z
past
ph { s t
paste
ph eI s t
pastes
ph eI s t s
pasts
ph { s t s
pat
ph { t
pat-	ches
ph {	tS V z
pat-	ching
ph {	tS I N
pat-	chy
ph {	tS i:
pat-	man
ph { t	m V n
pat-	more
ph { t	m O@
pat-	node
ph { t	n @U d
pat-	ri-	ar-	chal
ph eI t	r i:	Q@	k V l
pat-	ri-	ar-	chate
ph eI t	r i:	Q@	k V t
pat-	ri-	ar-	chy
ph eI t	r i:	Q@	k i:
pat-	ri-	arch
ph eI t	r i:	Q@ k
pat-	ri-	archs
ph eI t	r i:	Q@ k s
pat-	ri-	arch's
ph eI t	r i:	Q@ k s
pat-	ri-	ci-	o
ph V t	r I	s i:	@U
pat-	ri-	cia
ph V t	r I	S V
pat-	ri-	cian
ph V t	r I	S V n
pat-	ri-	cians
ph V t	r I	S V n z
pat-	ri-	li-	ne-	al
ph { t	r I	l I	n i:	V l
pat-	ri-	mo-	nial
ph { t	r I	m @U n	j V l
pat-	ri-	mo-	ny
ph { t	r I	m @U	n i:
pat-	ri-	o-	ti-	sm
ph eI t	r i:	V	t I	z V m
pat-	ri-	o-	tic
ph eI t	r i:	Q	t I k
pat-	ri-	ot
ph eI t	r i:	V t
pat-	ri-	ots
ph eI t	r i:	V t s
pat-	ri-	ot's
ph eI t	r i:	V t s
pat-	ri-	zi-	o
ph Q t	r i:	z i:	@U
pat-	rice
ph V t	r i: s
pat-	rick
ph { t	r I k
pat-	ricks
ph { t	r I k s
pat-	rick's
ph { t	r I k s
pat-	ridge
ph { t	r I dZ
pat-	ris-	tic
ph V t	r I s	t I k
pat-	ro-	nage
ph { t	r V	n I dZ
pat-	ro-	ni-	zing
ph eI t	r V	n aI	z I N
pat-	ro-	nize
ph eI t	r V	n aI z
pat-	ro-	nized
ph eI t	r V	n aI z d
pat-	ro-	ny-	mic
ph { t	r V	n I	m I k
pat-	ro-	nym
ph { t	r V	n I m
pat-	rol
ph V t	r @U l
pat-	rol-	ling
ph V t	r @U	l I N
pat-	rol-	man
ph V t	r @U l	m { n
pat-	rol-	men
ph V t	r @U l	m e n
pat-	rolled
ph V t	r @U l d
pat-	rols
ph V t	r @U l z
pat-	rol's
ph V t	r @U l z
pat-	ron
ph eI t	r V n
pat-	rons
ph eI t	r V n z
pat-	sies
ph { t	s i: z
pat-	sy
ph { t	s i:
pat-	ted
ph {	t V d
pat-	ten
ph {	t V n
pat-	ten's
ph {	t V n z
pat-	ter
ph {	t @r
pat-	ter-	son
ph {	t @r	s V n
pat-	ter-	son's
ph {	t @r	s V n z
pat-	tered
ph {	t @r d
pat-	tern
ph {	t @r n
pat-	terned
ph {	t @r n d
pat-	terns
ph {	t @r n z
pat-	ti
ph {	t i:
pat-	ti-	son
ph {	t I	s V n
pat-	tie
ph {	t i:
pat-	ties
ph {	t i: z
pat-	tin
ph {	t I n
pat-	ting
ph {	t I N
pat-	ton
ph {	t V n
pat-	ton's
ph {	t V n z
pat-	ty
ph {	t i:
pat-	ty's
ph {	t i: z
pat-	zer
ph eI t	z @r
patch
ph { tS
patch-	work
ph { tS	w @r k
patch-	works
ph { tS	w @r k s
patched
ph { tS t
pate
ph eI t
pates
ph eI t s
path
ph { T
path-	fin-	der
ph { T	f aI n	d @r
path-	way
ph { T	w eI
path-	ways
ph { T	w eI z
pathe
ph { T
paths
ph { D z
pats
ph { t s
pat's
ph { t s
patt
ph { t
pau-	ci-	ty
ph O:	s I	t i:
pau-	la
ph O:	l V
pau-	let-	ta
ph Q	l e	t V
pau-	lette
ph O:	l e t
pau-	li
ph O:	l i:
pau-	li-	na
ph O:	l i:	n V
pau-	li-	ta
ph O:	l i:	t V
pau-	lin
ph O:	l I n
pau-	line
ph O:	l i: n
pau-	ling
ph O:	l I N
pau-	lo
ph O:	l @U
pau-	lus
ph O:	l V s
pau-	ly
ph O:	l i:
pau-	per
ph O:	p @r
pau-	pers
ph O:	p @r z
pau-	ses
ph O:	z V z
pau-	sing
ph O:	z I N
paugh
ph O:
paul
ph O: l
paul-	ding
ph O: l	d I N
paul-	sen
ph aU l	s V n
paul-	son
ph O: l	s V n
paule
ph O: l
paull
ph O: l
pauls
ph O: l z
paul's
ph O: l z
paun-	chy
ph O: n	tS i:
paup
ph O: p
pause
ph O: z
paused
ph O: z d
pav-	lo-	vi-	an
ph { v	l @U	v i:	V n
pav-	lo-	vich
ph { v	l V	v I tS
pav-	lov
ph { v	l Q v
pave
ph eI v
pave-	ment
ph eI v	m V n t
pave-	ments
ph eI v	m V n t s
paved
ph eI v d
paves
ph eI v z
paw
ph O:
paw-	ling
ph O:	l I N
paw-	nee
ph O:	n i:
paw-	nees
ph O:	n i: z
paw-	tuc-	ket
ph O:	t V	k V t
pawn
ph O: n
pawn-	shop
ph O: n	S Q p
pawn-	shops
ph O: n	S Q p s
pawned
ph O: n d
pawns
ph O: n z
paws
ph O: z
pax
ph { k s
pax-	ton
ph { k	s t V n
pay
ph eI
pay-	back
ph eI	b { k
pay-	check
ph eI	tS e k
pay-	checks
ph eI	tS e k s
pay-	day
ph eI	d eI
pay-	ing
ph eI	I N
pay-	load
ph eI	l @U d
pay-	loads
ph eI	l @U d z
pay-	load's
ph eI	l @U d z
pay-	ment
ph eI	m V n t
pay-	ments
ph eI	m V n t s
pay-	off
ph eI	O: f
pay-	offs
ph eI	O: f s
pay-	out
ph eI	aU t
pay-	outs
ph eI	aU t s
pay-	roll
ph eI	r @U l
pay-	rolls
ph eI	r @U l z
pay-	son
ph eI	z V n
pay-	ton
ph eI	t V n
paye
ph eI
payn-	ter
ph eI n	t @r
payne
ph eI n
pays
ph eI z
paz
ph Q z
pe-	can
ph i:	k Q n
pe-	cans
ph I	k { n z
pe-	cho-	ra
ph V	k O@	V
pe-	co-	ra
ph e	k O@	V
pe-	cu-	li-	a-	ri-	ties
ph I k	j u:	l i:	e@	I	t i: z
pe-	cu-	li-	a-	ri-	ty
ph I k	j u:	l i:	e@	I	t i:
pe-	cu-	liar-	ly
ph I k	j u: l	j @r	l i:
pe-	cu-	ni-	a-	ry
ph e k	j u:	n i:	e@	i:
pe-	da-	go-	gi-	cal
ph e	d V	g Q	dZ I	k V l
pe-	da-	go-	gy
ph e	d V	g @U	dZ i:
pe-	da-	ling
ph e	d V	l I N
pe-	dal
ph e	d V l
pe-	daled
ph e	d V l d
pe-	dalled
ph e	d V l d
pe-	dals
ph e	d V l z
pe-	dan-	tic
ph V	d { n	t I k
pe-	dan-	try
ph e	d V n	t r i:
pe-	den
ph e	d V n
pe-	der-	sen
ph e	d @r	s V n
pe-	der-	son
ph e	d @r	s V n
pe-	des-	tal
ph e	d V s	t V l
pe-	des-	tals
ph e	d V s	t V l z
pe-	des-	tri-	an
ph V	d e s	t r i:	V n
pe-	des-	tri-	ans
ph V	d e s	t r i:	V n z
pe-	di-	at-	ri-	cian
ph i:	d i:	V t	r I	S V n
pe-	di-	at-	ri-	cians
ph i:	d i:	V t	r I	S V n z
pe-	di-	at-	ric
ph i:	d i:	{ t	r I k
pe-	di-	at-	rics
ph i:	d i:	{ t	r I k s
pe-	di-	cure
ph e	d I k	j @r
pe-	di-	gree
ph e	d I g	r i:
pe-	do-	phi-	lia
ph e	d V	f I l	j V
pe-	do-	phi-	liac
ph e	d V	f I l	j { k
pe-	do-	phi-	liacs
ph e	d V	f I l	j { k s
pe-	do-	phi-	lic
ph e	d @U	f I	l I k
pe-	do-	phile
ph e	d @U	f aI l
pe-	do-	philes
ph e	d @U	f aI l z
pe-	ga-	sus
ph e	g V	s V s
pe-	jo-	ra-	tive
ph V	dZ O@	V	t I v
pe-	kin
ph i:	k I n
pe-	king
ph i:	k I N
pe-	la-	gi-	an
ph V	l eI	dZ i:	V n
pe-	la-	gi-	ans
ph V	l eI	dZ i:	V n z
pe-	la-	gia
ph e	l Q	dZ V
pe-	la-	gic
ph V	l {	dZ I k
pe-	le
ph e	l eI
pe-	le-	rin
ph e	l @r	I n
pe-	li-	can
ph e	l I	k V n
pe-	li-	cans
ph e	l I	k V n z
pe-	li-	can's
ph e	l I	k V n z
pe-	lo-	pon-	ne-	sian
ph e	l V	p V	n i:	Z V n
pe-	lon
ph e	l V n
pe-	na
ph e	n V
pe-	na-	li-	zes
ph e	n V	l aI	z V z
pe-	na-	li-	zing
ph i:	n V	l aI	z I N
pe-	na-	lize
ph e	n V	l aI z
pe-	na-	lized
ph i:	n V	l aI z d
pe-	nal
ph i:	n V l
pe-	nal-	ties
ph e	n V l	t i: z
pe-	nal-	ty
ph e	n V l	t i:
pe-	nance
ph e	n V n s
pe-	nang
ph e	n { N
pe-	na's
ph e	n V z
pe-	ne-	lo-	pe
ph V	n e	l V	p i:
pe-	ne-	tra-	ted
ph e	n V t	r eI	t V d
pe-	ne-	tra-	ting
ph e	n V t	r eI	t I N
pe-	ne-	tra-	tion
ph e	n V t	r eI	S V n
pe-	ne-	trate
ph e	n V t	r eI t
pe-	ne-	trates
ph e	n V t	r eI t s
pe-	ni-	cil-	lin
ph e	n I	s I	l I n
pe-	ni-	cil-	lins
ph e	n I	s I	l I n z
pe-	ni-	ses
ph i:	n I	s V z
pe-	ni-	ten-	tia-	ries
ph e	n I	t e n	tS @r	i: z
pe-	ni-	ten-	tia-	ry
ph e	n I	t e n	tS @r	i:
pe-	ni-	tent
ph e	n I	t V n t
pe-	nile
ph i:	n aI l
pe-	nin-	su-	la
ph V	n I n	s V	l V
pe-	nin-	su-	lar
ph V	n I n	s V	l @r
pe-	nis
ph i:	n I s
pe-	no-	lo-	gy
ph i:	n Q	l V	dZ i:
pe-	no-	yer
ph e	n OI	@r
pe-	nob-	scot
ph V	n Q b	s k Q t
pe-	nu-	ri-	ous
ph e n	j u:	r i:	V s
pe-	nu-	ry
ph e n	j @r	i:
pe-	num-	bra
ph V	n V m	b r V
pe-	o-	nies
ph i:	V	n i: z
pe-	o-	ny
ph i:	V	n i:
pe-	o-	ri-	a
ph i:	O@	i:	V
pe-	o-	ri-	a's
ph i:	O@	i:	V z
pe-	on
ph i:	V n
pe-	ons
ph i:	V n z
pe-	pe
ph e	p i:
pe-	per
ph e	p @r
pe-	pi
ph e	p i:
pe-	pi-	ta
ph e	p i:	t V
pe-	pin
ph e	p I n
pe-	ra
ph @r	V
pe-	ral-	ta
ph @r	Q l	t V
pe-	re-	a
ph @r	i:	V
pe-	re-	grine
ph e@	V g	r i: n
pe-	re-	grines
ph e@	V g	r i: n z
pe-	re-	stroi-	ka
ph e@	V s	t r OI	k V
pe-	rei-	ra
ph @r	e@	V
pe-	rel-	man
ph e@	V l	m V n
pe-	rel-	man's
ph e@	V l	m V n z
pe-	rem-	pto-	ry
ph @r	e m	p t @r	i:
pe-	ren-	ni-	al
ph @r	e	n i:	V l
pe-	ren-	ni-	al-	ly
ph @r	e	n i:	V	l i:
pe-	ren-	ni-	als
ph @r	e	n i:	V l z
pe-	res
ph e@	e z
pe-	retz
ph @r	e t s
pe-	rez
ph e@	e z
pe-	ri-	a
ph e@	i:	V
pe-	ri-	a's
ph e@	i:	V z
pe-	ri-	lous
ph e@	I	l V s
pe-	ri-	lous-	ly
ph e@	I	l V s	l i:
pe-	ri-	me-	ter
ph @r	I	m V	t @r
pe-	ri-	me-	ters
ph @r	I	m V	t @r z
pe-	ri-	ne
ph @r	i:	n i:
pe-	ri-	o-	di-	cal
ph I@	i:	Q	d I	k V l
pe-	ri-	o-	di-	cal-	ly
ph i:	r i:	Q	d I	k V	l i:
pe-	ri-	o-	di-	cals
ph I@	i:	Q	d I	k V l z
pe-	ri-	o-	dic
ph I@	i:	Q	d I k
pe-	ri-	o-	don-	tal
ph e@	i:	V	d Q n	t V l
pe-	ri-	od
ph I@	i:	V d
pe-	ri-	ods
ph I@	i:	V d z
pe-	ri-	od's
ph I@	i:	V d z
pe-	ri-	pa-	te-	tic
ph e@	I	p V	t e	t I k
pe-	ri-	phe-	ral
ph @r	I	f @r	V l
pe-	ri-	phe-	ral-	ly
ph @r	I	f @r	V	l i:
pe-	ri-	phe-	rals
ph @r	I	f @r	V l z
pe-	ri-	phe-	ry
ph @r	I	f @r	i:
pe-	ri-	scope
ph e@	I s	k @U p
pe-	ri-	sha-	ble
ph e@	I	S V	b V l
pe-	ril
ph e@	I l
pe-	rils
ph e@	I l z
pe-	rish
ph e@	I S
pe-	rished
ph e@	I S t
pe-	ro
ph @r	@U
pe-	ro-	ni-	sm
ph e@	V	n I	z V m
pe-	ro-	nist
ph e@	V	n I s t
pe-	ro-	nists
ph e@	V	n I s t s
pe-	ro-	xide
ph @r	Q k	s aI d
pe-	ron
ph @r	O: n
pe-	rone
ph @r	@U n
pe-	rot
ph @r	@U
pe-	rot's
ph @r	@U z
pe-	ru
ph @r	u:
pe-	ru-	sal
ph @r	u:	z V l
pe-	ru's
ph @r	u: z
pe-	se-	ta
ph V	s eI	t V
pe-	se-	tas
ph V	s eI	t V z
pe-	sek
ph e	s e k
pe-	sha-	war
ph e	S V	w O@
pe-	sky
ph e s	k i:
pe-	so
ph eI	s @U
pe-	sos
ph eI	s @U z
pe-	so's
ph eI	s @U z
pe-	ta
ph i:	t V
pe-	ta-	lu-	ma
ph e	t V	l u:	m V
pe-	tal
ph e	t V l
pe-	tals
ph e	t V l z
pe-	tard
ph e	t @r d
pe-	ta's
ph i:	t V z
pe-	te-	ring
ph i:	t @r	I N
pe-	ter
ph i:	t @r
pe-	ter-	bo-	rough
ph i:	t @r	b @r	@U
pe-	ter-	kin
ph V	t @r	k V n
pe-	ter-	man
ph i:	t @r	m V n
pe-	ter-	mann
ph i:	t @r	m V n
pe-	ter-	sen
ph i:	t @r	s V n
pe-	ter-	sen's
ph i:	t @r	s V n z
pe-	ter-	son
ph i:	t @r	s V n
pe-	ter-	son's
ph i:	t @r	s V n z
pe-	tered
ph i:	t @r d
pe-	ters
ph i:	t @r z
pe-	ter's
ph i:	t @r z
pe-	ters-	burg
ph i:	t @r z	b @r g
pe-	tey
ph i:	t i:
pe-	ti-	pa
ph e	t i:	p V
pe-	ti-	pa's
ph e	t i:	p V z
pe-	ti-	tio-	ner
ph V	t I	S V	n @r
pe-	ti-	tio-	ners
ph V	t I	S V	n @r z
pe-	ti-	tio-	ning
ph V	t I	S V	n I N
pe-	ti-	tion
ph V	t I	S V n
pe-	ti-	tioned
ph V	t I	S V n d
pe-	ti-	tions
ph V	t I	S V n z
pe-	tie
ph e	t i:
pe-	tit
ph e	t i:
pe-	tite
ph V	t i: t
pe-	tites
ph e	t i: t s
pe-	to
ph i:	t @U
pe-	tre
ph e	t @r
pe-	tu-	lance
ph e	tS V	l V n s
pe-	tu-	lant
ph e	tS V	l V n t
pe-	tu-	ni-	a
ph V	t u:	n i:	V
pe-	tu-	ni-	as
ph V	t u:	n i:	V z
pea
ph i:
pea-	bo-	dy
ph i:	b Q	d i:
pea-	bo-	dy's
ph i:	b Q	d i: z
pea-	cea-	ble
ph i:	s V	b V l
pea-	ceab-	ly
ph i:	s V b	l i:
pea-	cher
ph i:	tS @r
pea-	ches
ph i:	tS V z
pea-	chy
ph i:	tS i:
pea-	cock
ph i:	k Q k
pea-	cocks
ph i:	k Q k s
pea-	fowl
ph i:	f aU l
pea-	king
ph i:	k I N
pea-	ler
ph i:	l @r
pea-	nut
ph i:	n V t
pea-	nuts
ph i:	n V t s
pea-	pack
ph i:	p { k
pea-	pod
ph i:	p O: d
pea-	ry
ph i:	r i:
pea-	sant
ph e	z V n t
pea-	sant-	ry
ph e	z V n	t r i:
pea-	sants
ph e	z V n t s
pea-	vey
ph i:	v i:
pea-	vy
ph i:	v i:
peace
ph i: s
peace-	ful
ph i: s	f V l
peace-	ful-	ly
ph i: s	f V	l i:
peace-	ful-	ness
ph i: s	f V l	n V s
peace-	kee-	per
ph i: s	k i:	p @r
peace-	kee-	pers
ph i: s	k i:	p @r z
peace-	kee-	ping
ph i: s	k i:	p I N
peace-	ma-	ker
ph i: s	m eI	k @r
peace-	ma-	kers
ph i: s	m eI	k @r z
peace-	ma-	ker's
ph i: s	m eI	k @r z
peace-	ma-	king
ph i: s	m eI	k I N
peace-	time
ph i: s	t aI m
peach
ph i: tS
peach-	tree
ph i: tS	t r i:
peak
ph i: k
peake
ph i: k
peaked
ph i: k t
peaks
ph i: k s
peal
ph i: l
peale
ph i: l
pear
ph e@
pear-	cy
ph @r	k i:
pear-	line
ph @r	l aI n
pear-	ling
ph @r	l I N
pear-	ly
ph @r	l i:
pear-	man
ph e@	m V n
pear-	son
ph I@	s V n
pear-	son's
ph I@	s V n z
pearce
ph I@ s
pearl
ph @r l
pearl-	man
ph @r l	m { n
pearl-	stein
ph @r l	s t aI n
pearle
ph @r l
pearls
ph @r l z
pears
ph e@ z
pearse
ph @r s
peart
ph @r t
peas
ph i: z
pease
ph i: z
peat
ph i: t
peat's
ph i: t s
peb-	ble
ph e	b V l
peb-	bles
ph e	b V l z
pec-	kham
ph e	k V m
pec-	king
ph e	k I N
pec-	tic
ph e k	t I k
pec-	tin
ph e k	t I n
pech
ph e k
pecht
ph e k t
peck
ph e k
peck's
ph e k s
ped-	d-	ling
ph e	d V	l I N
ped-	dle
ph e	d V l
ped-	dled
ph e	d V l d
ped-	dles
ph e	d V l z
ped-	rick
ph e d	r I k
ped-	ro
ph eI d	r @U
ped-	ro-	za
ph eI d	r @U	z V
ped-	ros
ph eI d	r @U z
ped-	rot-	ti
ph e d	r @U	t i:
pedd-	ler
ph e d	l @r
pedd-	lers
ph e d	l @r z
pee
ph i:
pee-	bles
ph i:	b V l z
pee-	king
ph i:	k I N
pee-	ler
ph i:	l @r
pee-	ling
ph i:	l I N
pee-	ping
ph i:	p I N
pee-	rage
ph I@	V dZ
pee-	ring
ph i:	r I N
pee-	ry
ph i:	r i:
pee-	vish
ph i:	v I S
pee-	wee
ph i:	w i:
peed
ph i: d
peek
ph i: k
peeked
ph i: k t
peeks
ph i: k s
peel
ph i: l
peele
ph i: l
peeled
ph i: l d
peels
ph i: l z
peens
ph i: n z
peep
ph i: p
peeps
ph i: p s
peer
ph I@
peer-	less
ph I@	l V s
peered
ph I@ d
peers
ph I@ z
peetz
ph i: t s
peeve
ph i: v
peeved
ph i: v d
peeves
ph i: v z
peg
ph e g
peg-	board
ph e g	b O@ d
peg-	boards
ph e g	b O@ d z
peg-	gie
ph e	g i:
peg-	ging
ph e	g I N
peg-	gy
ph e	g i:
peg-	ma-	tite
ph e g	m V	t aI t
peg-	ram
ph e g	r { m
pegg
ph e g
pegged
ph e g d
peggs
ph e g z
pegs
ph e g z
pei
ph eI
pei-	ser
ph aI	s @r
peine
ph i: n
peirce
ph I@ s
pel-	ham
ph e	l V m
pel-	la
ph e	l V
pel-	la-	gra
ph V	l { g	r V
pel-	le-	ted
ph e	l V	t V d
pel-	le-	tier
ph e	l V	t I@
pel-	leg-	ri-	ni
ph e	l e g	r i:	n i:
pel-	ler
ph e	l @r
pel-	let
ph e	l V t
pel-	lets
ph e	l V t s
pel-	ted
ph e l	t V d
pel-	ti-	er
ph e l	t i:	@r
pel-	ton
ph e l	t V n
pel-	vic
ph e l	v I k
pel-	vis
ph e l	v I s
pel-	zer
ph e l	z @r
pell
ph e l
pell's
ph e l z
pelt
ph e l t
pelts
ph e l t s
peltz
ph e l t s
pem-	ber
ph e m	b @r
pem-	ber-	ton
ph e m	b @r	t V n
pem-	bi-	na
ph e m	b I	n V
pem-	broke
ph e m	b r @U k
pen
ph e n
pen-	chant
ph e n	tS V n t
pen-	cil
ph e n	s I l
pen-	ciled
ph e n	s I l d
pen-	cils
ph e n	s I l z
pen-	dant
ph e n	d V n t
pen-	der
ph e n	d @r
pen-	der-	gast
ph e n	d @r	g { s t
pen-	der-	grass
ph e n	d @r g	r V s
pen-	ding
ph e n	d I N
pen-	dle-	ton
ph e n	d V l	t V n
pen-	du-	lous
ph e n	dZ V	l V s
pen-	du-	lum
ph e n	dZ V	l V m
pen-	field
ph e n	f i: l d
pen-	fold
ph e n	f @U l d
pen-	gel-	ly
ph e N	g V	l i:
pen-	go
ph e N	g @U
pen-	guin
ph e N	g w I n
pen-	guins
ph e N	g w I n z
pen-	land
ph e n	l V n d
pen-	man
ph e n	m V n
pen-	na
ph e	n V
pen-	nant
ph e	n V n t
pen-	nants
ph e	n V n t s
pen-	ne-	ba-	ker
ph e	n V	b eI	k @r
pen-	nell
ph e	n V l
pen-	ner
ph e	n @r
pen-	ney
ph e	n i:
pen-	ney's
ph e	n i: z
pen-	ni-	less
ph e	n i:	l V s
pen-	nie
ph e	n i:
pen-	nies
ph e	n i: z
pen-	ning
ph e	n I N
pen-	ning-	ton
ph e	n I N	t V n
pen-	nock
ph e	n V k
pen-	ny
ph e	n i:
pen-	ny's
ph e	n i: z
pen-	rod
ph e n	r Q d
pen-	rod's
ph e n	r Q d z
pen-	rose
ph e n	r @U z
pen-	sa-	co-	la
ph e n	s V	k @U	l V
pen-	sio-	ner
ph e n	S V	n @r
pen-	sio-	ners
ph e n	S V	n @r z
pen-	sion
ph e n	S V n
pen-	sions
ph e n	S V n z
pen-	sive
ph e n	s I v
pen-	ta
ph e n	t V
pen-	ta-	mi-	dine
ph e n	t {	m I	d i: n
pen-	tane
ph e n	t eI n
pen-	tath-	lon
ph e n	t { T	l V n
pen-	tax
ph e n	t { k s
pen-	te-	cos-	tal
ph e n	t V	k O: s	t V l
pen-	te-	cost
ph e n	t V	k O: s t
pen-	the-	a
ph e n	T i:	V
pen-	ti-	men-	to
ph e n	t I	m e n	t @U
pen-	ti-	um
ph e n	t i:	V m
pen-	ti-	ums
ph e n	t i:	V m z
pen-	to-	thal
ph e n	t V	T Q l
pen-	well
ph e n	w e l
pen-	za
ph e n	z V
pence
ph e n s
peng
ph e N
penh
ph e n
penh's
ph e n z
penn
ph e n
)"
R"(penn-	sau-	ken
ph e n	s O:	k V n
penn-	syl-	va-	ni-	an
ph e n	s V l	v eI	n i:	V n
penn-	syl-	va-	ni-	ans
ph e n	s V l	v eI	n i:	V n z
penn-	syl-	va-	nia
ph e n	s V l	v eI n	j V
penn-	syl-	va-	nia's
ph e n	s V l	v eI n	j V z
penn-	zoil
ph e n	z OI l
penn-	zoil's
ph e n	z OI l z
penned
ph e n d
penns
ph e n z
penn's
ph e n z
pens
ph e n z
pen's
ph e n z
pense
ph e n s
pent
ph e n t
pent-	house
ph e n	t h aU s
pent-	land
ph e n	t l V n d
peo-	ple
ph i:	p V l
peo-	pled
ph i:	p V l d
peo-	ples
ph i:	p V l z
peo-	ple's
ph i:	p V l z
pep
ph e p
pep-	cid
ph e p	s I d
pep-	pard
ph e	p @r d
pep-	pe-	rell
ph e	p @r	V l
pep-	pe-	ridge
ph e	p @r	I dZ
pep-	pe-	ring
ph e	p @r	I N
pep-	pe-	ro-	ni
ph e	p @r	@U	n i:
pep-	pel
ph e	p V l
pep-	per
ph e	p @r
pep-	per-	mint
ph e	p @r	m I n t
pep-	pered
ph e	p @r d
pep-	pers
ph e	p @r z
pep-	per's
ph e	p @r z
pep-	pi
ph e	p i:
pep-	pin
ph e	p I n
pep-	py
ph e	p i:
pep-	si
ph e p	s i:
pep-	si-	co
ph e p	s I	k @U
pep-	si-	co's
ph e p	s I	k @U z
pep-	si's
ph e p	s i: z
pep-	tic
ph e p	t I k
)"