R"(a-	b-	s
eI	b i:	e s
a-	ba-	ba
V	b Q	b V
a-	ba-	co
{	b V	k @U
a-	ba-	cus
{	b V	k V s
a-	ba-	lo-	ne
{	b V	l @U	n i:
a-	ba-	ted
V	b eI	t V d
a-	ba-	ting
V	b eI	t I N
a-	back
V	b { k
a-	bad
V	b Q d
a-	ban-	do-	ning
V	b { n	d V	n I N
a-	ban-	don
V	b { n	d V n
a-	ban-	don-	ment
V	b { n	d V n	m V n t
a-	ban-	don-	ments
V	b { n	d V n	m V n t s
a-	ban-	doned
V	b { n	d V n d
a-	ban-	dons
V	b { n	d V n z
a-	bash
V	b { S
a-	bashed
V	b { S t
a-	bate
V	b eI t
a-	bate-	ment
V	b eI t	m V n t
a-	bate-	ments
V	b eI t	m V n t s
a-	bates
V	b eI t s
a-	bbas
V	b Q s
a-	be-	lard
{	b V	l @r d
a-	be-	yance
V	b eI	V n s
a-	bed
V	b e d
a-	bel
eI	b V l
a-	bel-	son
{	b V l	s V n
a-	bele
V	b i: l
a-	beles
V	b i: l z
a-	bell
eI	b V l
a-	bend
{	b e n d
a-	ber-	deen
{	b @r	d i: n
a-	ber-	na-	thy
{	b @r	n {	T i:
a-	ber-	ne-	thy
{	b @r	n e	T i:
a-	ber-	ra-	tio-	nal
{	b @r	eI	S V	n V l
a-	ber-	ra-	tion
{	b @r	eI	S V n
a-	ber-	ra-	tions
{	b @r	eI	S V n z
a-	ber-	rant
{	b e@	V n t
a-	berc-	rom-	bie
{	b @r k	r Q m	b i:
a-	bert
{	b @r t
a-	bet
V	b e t
a-	bet-	ted
V	b e	t V d
a-	bet-	ting
V	b e	t I N
a-	bhor
{ b	h O@
a-	bhor-	rence
V b	h O@	V n s
a-	bhor-	rent
{ b	h O@	V n t
a-	bhorred
V b	h O@ d
a-	bhors
V b	h O@ z
a-	bi-	ded
V	b aI	d V d
a-	bi-	ding
V	b aI	d I N
a-	bi-	gail
{	b I	g eI l
a-	bi-	lene
{	b I	l i: n
a-	bi-	li-	ties
V	b I	l V	t i: z
a-	bi-	li-	ty
V	b I	l V	t i:
a-	bi-	ti-	bi
{	b I	t i:	b i:
a-	bid
eI	b I d
a-	bide
V	b aI d
a-	bides
V	b aI d z
a-	bie
{	b i:
a-	bing-	ton
{	b I N	t V n
a-	bo
Q	b @U
a-	bo-	li-	shes
V	b Q	l I	S V z
a-	bo-	li-	shing
V	b Q	l I	S I N
a-	bo-	li-	tio-	ni-	sm
{	b V	l I	S V	n I	z V m
a-	bo-	li-	tio-	nist
{	b V	l I	S V	n V s t
a-	bo-	li-	tio-	nists
{	b V	l I	S V	n V s t s
a-	bo-	li-	tion
{	b V	l I	S V n
a-	bo-	lish
V	b Q	l I S
a-	bo-	lished
V	b Q	l I S t
a-	bo-	mi-	na-	ble
V	b Q	m V	n V	b V l
a-	bo-	mi-	na-	tion
V	b Q	m V	n eI	S V n
a-	bo-	ri-	gi-	nal
{	b @r	I	dZ I	n V l
a-	bo-	ri-	gi-	ne
{	b @r	I	dZ I	n i:
a-	bo-	ri-	gi-	nes
{	b @r	I	dZ I	n i: z
a-	board
V	b O@ d
a-	bode
V	b @U d
a-	bor-	ted
V	b O@	t V d
a-	bor-	ti-	fa-	cient
V	b O@	t V	f eI	S V n t
a-	bor-	ti-	fa-	cients
V	b O@	t V	f eI	S V n t s
a-	bor-	ting
V	b O@	t I N
a-	bor-	tio-	nist
V	b O@	S V	n V s t
a-	bor-	tio-	nists
V	b O@	S V	n V s t s
a-	bor-	tion
V	b O@	S V n
a-	bor-	tions
V	b O@	S V n z
a-	bor-	tive
V	b O@	t I v
a-	born
V	b O@ n
a-	bort
V	b O@ t
a-	bo's
Q	b @U z
a-	bott
V	b Q t
a-	boun-	ded
V	b aU n	d V d
a-	boun-	ding
V	b aU n	d I N
a-	bound
V	b aU n d
a-	bounds
V	b aU n d z
a-	bout
V	b aU t
a-	bove
V	b V v
a-	bove-	board
V	b V v	b O@ d
a-	bu
{	b u:
a-	bu-	ser
V b	j u:	z @r
a-	bu-	sers
V b	j u:	z @r z
a-	bu-	ses
V b	j u:	s V z
a-	bu-	sing
V b	j u:	z I N
a-	bu-	sive
V b	j u:	s I v
a-	bun-	dance
V	b V n	d V n s
a-	bun-	dant
V	b V n	d V n t
a-	bun-	dant-	ly
V	b V n	d V n	t l i:
a-	buse
V b	j u: s
a-	bused
V b	j u: z d
a-	but
V	b V t
a-	but-	ted
V	b V	t V d
a-	but-	ting
V	b V	t I N
a-	buts
V	b V t s
a-	buzz
V	b V z
a-	bys-	mal
V	b I z	m V l
a-	bys-	mal-	ly
V	b I z	m V	l i:
a-	byss
V	b I s
a-	c
eI	s i:
a-	ca-	cia
V	k eI	S V
a-	ca-	de-	mi-	a
{	k V	d i:	m i:	V
a-	ca-	de-	mi-	cally
{	k V	d e	m I k	l i:
a-	ca-	de-	mi-	cian
{	k V	d V	m I	S V n
a-	ca-	de-	mi-	cians
{	k V	d V	m I	S V n z
a-	ca-	de-	mic
{	k V	d e	m I k
a-	ca-	de-	mics
{	k V	d e	m I k s
a-	ca-	de-	mies
V	k {	d V	m i: z
a-	ca-	de-	my
V	k {	d V	m i:
a-	ca-	de-	my's
V	k {	d V	m i: z
a-	ca-	deme
{	k V	d i: m
a-	ca-	di-	a
V	k eI	d i:	V
a-	ca-	pul-	co
{	k V	p U l	k @U
a-	can-	tha
Q	k Q n	D V
a-	ccre-	di-	ting
V k	r e	d V	t I N
a-	ce-	ta-	mi-	no-	phen
V	s i:	t V	m I	n V	f V n
a-	ce-	tate
{	s V	t eI t
a-	ce-	tic
V	s e	t I k
a-	ce-	tone
{	s V	t @U n
a-	ce-	ty-	lene
V	s e	t V	l i: n
a-	ce-	tyl-	cho-	line
V	s e	t V l	k @U	l i: n
a-	ce-	ve-	do
{	s V	v eI	d @U
a-	cer-	bic
V	s e@	b I k
a-	cer-	ra
V	s e@	V
a-	ces
eI	s V z
a-	cey
eI	s i:
a-	che-	be
Q	tS eI	b i:
a-	che-	son
{	tS V	s V n
a-	chie-	va-	ble
V	tS i:	v V	b V l
a-	chie-	ver
V	tS i:	v @r
a-	chie-	vers
V	tS i:	v @r z
a-	chie-	ving
V	tS i:	v I N
a-	chieve
V	tS i: v
a-	chieve-	ment
V	tS i: v	m V n t
a-	chieve-	ments
V	tS i: v	m V n t s
a-	chieved
V	tS i: v d
a-	chieves
V	tS i: v z
a-	chil-	le
V	k I	l i:
a-	chil-	les
V	k I	l i: z
a-	chil-	les'
V	k I	l i: z
a-	ching
eI	k I N
a-	chmed
Q h	m e d
a-	chor
eI	k @r
a-	chorn
{	k @r n
a-	chy
eI	k i:
a-	ci-	di-	fi-	ca-	tion
V	s I	d V	f V	k eI	S V n
a-	ci-	di-	fied
V	s I	d V	f aI d
a-	ci-	di-	fies
V	s I	d V	f aI z
a-	ci-	di-	fy
V	s I	d V	f aI
a-	ci-	di-	ty
V	s I	d V	t i:
a-	ci-	dic
V	s I	d I k
a-	ci-	do-	sis
{	s I	d @U	s I s
a-	ci-	du-	ri-	a
{	s I	d U@	i:	V
a-	cid
{	s I d
a-	cid-	ly
{	s I d	l i:
a-	cids
{	s I d z
a-	cker
{	k @r
a-	cker-	ley
{	k @r	l i:
a-	cker-	ly
{	k @r	l i:
a-	cker-	man
{	k @r	m V n
a-	cker's
{	k @r z
a-	co-	lyte
{	k V	l aI t
a-	co-	lytes
{	k V	l aI t s
a-	corn
eI	k O@ n
a-	corns
eI	k O@ n z
a-	cos-	ta
V	k O: s	t V
a-	cous-	ti-	cal
V	k u: s	t I	k V l
a-	cous-	ti-	cally
V	k u: s	t I k	l i:
a-	cous-	tic
V	k u: s	t I k
a-	cous-	tics
V	k u: s	t I k s
a-	cre
eI	k @r
a-	cu-	i-	ty
V k	j u:	V	t i:
a-	cu-	men
V k	j u:	m V n
a-	cu-	na
Q	k u:	n V
a-	cu-	punc-	ture
{ k	j u:	p V N	k tS @r
a-	cuff
V	k V f
a-	cute
V k	j u: t
a-	cute-	ly
V k	j u: t	l i:
a-	cute-	ness
V k	j u: t	n V s
a-	cyc-	lo-	vir
V	s I k	l @U	v I@
a-	da
eI	d V
a-	da-	bel
{	d V	b e l
a-	da-	belle
{	d V	b V l
a-	da-	chi
Q	d Q	k i:
a-	da-	gi-	o
V	d Q	Z i:	@U
a-	da-	li-	a
Q	d Q	l i:	V
a-	da-	mant
{	d V	m V n t
a-	da-	mant-	ly
{	d V	m V n	t l i:
a-	da-	mec
V	d Q	m I k
a-	da-	mek
V	d Q	m e k
a-	da-	mi-	na
Q	d Q	m i:	n V
a-	da-	mik
V	d Q	m I k
a-	da-	mo
Q	d Q	m @U
a-	dage
{	d V dZ
a-	dah
{	d Q
a-	dair
V	d e@
a-	dam
{	d V m
a-	dam-	son
{	d V m	s V n
a-	dams
{	d V m z
a-	dam's
{	d V m z
a-	dams-	ki
V	d { m	s k i:
a-	dams-	town
{	d V m	s t aU n
a-	dan
eI	d V n
a-	dap-	ta-	bi-	li-	ty
V	d { p	t V	b I	l I	t i:
a-	dap-	ta-	ble
V	d { p	t V	b V l
a-	dap-	ta-	plex
V	d { p	t V p	l e k s
a-	dap-	ta-	tion
{	d V p	t eI	S V n
a-	dap-	ta-	tions
{	d { p	t eI	S V n z
a-	dap-	ted
V	d { p	t V d
a-	dap-	ter
V	d { p	t @r
a-	dap-	ters
V	d { p	t @r z
a-	dap-	ting
V	d { p	t I N
a-	dap-	tive
V	d { p	t I v
a-	dap-	tor
V	d { p	t @r
a-	dapt
V	d { p t
a-	dapts
V	d { p t s
a-	dar
V	d Q@
a-	de-	la
V	d e	l V
a-	de-	laide
{	d V	l eI d
a-	de-	line
{	d V	l aI n
a-	de-	na
{	d V	n V
a-	de-	nauer
eI	d V	n aU r
a-	de-	nine
{	d V	n i: n
a-	de-	noid
{	d V	n OI d
a-	de-	noids
{	d V	n OI d z
a-	de-	qua-	cy
{	d V k	w V	s i:
a-	de-	quate
{	d V k	w V t
a-	de-	quate-	ly
{	d V k	w V t	l i:
a-	dee
V	d i:
a-	del
V	d e l
a-	del-	bert
V	d e l	b @r t
a-	del-	phi-	a
V	d e l	f i:	V
a-	del-	phi-	a's
V	d e l	f i:	V z
a-	dele
V	d e l
a-	dele's
V	d e l z
a-	dell
V	d e l
a-	delle
V	d e l
a-	dell's
V	d e l z
a-	den
eI	d V n
a-	dept
V	d e p t
a-	der
eI	d @r
a-	dey
eI	d i:
a-	di-	das
V	d i:	d V s
a-	di-	na
Q	d i:	n V
a-	di-	ne
Q	d i:	n i:
a-	di-	os
Q	d i:	@U s
a-	di-	pose
{	d I	p @U s
a-	di-	ron-	dack
{	d @r	Q n	d { k
a-	dieu
V	d u:
a-	din
V	d I n
a-	do
V	d u:
a-	do-	be
V	d @U	b i:
a-	do-	be's
V	d @U	b i: z
a-	do-	les-	cence
{	d V	l e	s V n s
a-	do-	les-	cent
{	d V	l e	s V n t
a-	do-	les-	cents
{	d V	l e	s V n t s
a-	do-	ni-	a
Q	d @U	n i:	V
a-	do-	ra
Q	d O@	V
a-	do-	ra-	ble
V	d O@	V	b V l
a-	do-	ra-	tion
{	d @r	eI	S V n
a-	do-	ree
{	d @r	i:
a-	do-	ring
V	d O@	I N
a-	dol-	fo
V	d Q l	f @U
a-	dolf
eI	d Q l f
a-	dolf's
eI	d Q l f s
a-	dolph
eI	d O: l f
a-	don
Q	d O: n
a-	dop-	ta-	ble
V	d Q p	t V	b V l
a-	dop-	ted
V	d Q p	t V d
a-	dop-	tee
V	d Q p	t i:
a-	dop-	tees
V	d Q p	t i: z
a-	dop-	ting
V	d Q p	t I N
a-	dop-	tion
V	d Q p	S V n
a-	dop-	tions
V	d Q p	S V n z
a-	dop-	tive
V	d Q p	t I v
a-	dopt
V	d Q p t
a-	dopts
V	d Q p t s
a-	dor
Q	d O@
a-	dor-	no
Q	d O@	n @U
a-	dore
V	d O@
a-	dored
V	d O@ d
a-	dores
V	d O@ z
a-	dorn
V	d O@ n
a-	dorn-	ment
V	d O@ n	m V n t
a-	dorned
V	d O@ n d
a-	dorns
V	d O@ n z
a-	du-	la-	tion
{	dZ V	l eI	S V n
a-	du-	late
{	dZ V	l eI t
a-	dul-	te-	ra-	ted
V	d V l	t @r	eI	t V d
a-	dul-	te-	rate
V	d V l	t @r	eI t
a-	dul-	te-	rer
V	d V l	t @r	@r
a-	dul-	te-	rers
V	d V l	t @r	@r z
a-	dul-	te-	rous
V	d V l	t @r	V s
a-	dul-	te-	ry
V	d V l	t @r	i:
a-	dult
V	d V l t
a-	dult-	hood
V	d V l	t h U d
a-	dults
V	d V l t s
a-	dy
eI	d i:
a-	far
V	f Q@
a-	ffi-	xing
V	f I k	s I N
a-	ffir-	ma-	tion
{	f @r	m eI	S V n
a-	ffir-	ma-	tions
{	f @r	m eI	S V n z
a-	ffir-	ma-	tive
V	f @r	m V	t I v
a-	ffir-	ma-	tive-	ly
V	f @r	m V	t I v	l i:
a-	ffir-	ming
V	f @r	m I N
a-	ffirm
V	f @r m
a-	ffirmed
V	f @r m d
a-	ffirms
V	f @r m z
a-	ffix
{	f I k s
a-	ffix-	es
{	f I k	s V z
a-	ffixed
V	f I k s t
a-	fi-	cio-	na-	do
V	f i: S	j V	n Q	d @U
a-	fi-	cio-	na-	dos
V	f I	S V	n Q	d @U z
a-	field
V	f i: l d
a-	fire
V	f aI r
a-	fon-	so
V	f Q n	s @U
a-	foot
V	f U t
a-	fore-	men-	tioned
V	f O@	m e n	S V n d
a-	fore-	said
V	f O@	s e d
a-	foret-	hought
V	f O@	T Q t
a-	foul
V	f aU l
a-	ga
Q	g V
a-	ga-	mem-	non
{	g V	m e m	n Q n
a-	ga-	mem-	non's
{	g V	m e m	n Q n z
a-	ga-	tha
{	g V	T V
a-	gain
V	g e n
a-	gainst
V	g e n s t
a-	gan
eI	g V n
a-	gape
V	g eI p
a-	gar
eI	g @r
a-	gar-	wal
Q	g Q@	w Q l
a-	gas-	si
{	g V	s i:
a-	gas-	siz
V	g {	s I z
a-	gate
{	g V t
a-	gates
{	g V t s
a-	ge-	ra-	tum
V	dZ e@	V	t V m
a-	ge-	ra-	tums
V	dZ e@	V	t V m z
a-	gee
eI	dZ i:
a-	gee's
eI	dZ i: z
a-	gen-	cies
eI	dZ V n	s i: z
a-	gen-	cy
eI	dZ V n	s i:
a-	gen-	cy's
eI	dZ V n	s i: z
a-	gen-	da
V	dZ e n	d V
a-	gen-	das
V	dZ e n	d V z
a-	gent
eI	dZ V n t
a-	gents
eI	dZ V n t s
a-	gent's
eI	dZ V n t s
a-	ger
eI	dZ @r
a-	gers
eI	dZ @r z
a-	ges
eI	dZ V z
a-	ge's
eI	dZ V z
a-	ghast
V	g { s t
a-	gi-	li-	ty
V	dZ I	l V	t i:
a-	gi-	lis
V	dZ I	l V s
a-	gi-	ta-	ted
{	dZ I	t eI	t V d
a-	gi-	ta-	ting
{	dZ I	t eI	t I N
a-	gi-	ta-	tion
{	dZ I	t eI	S V n
a-	gi-	ta-	tor
{	dZ I	t eI	t @r
a-	gi-	ta-	tors
{	dZ I	t eI	t @r z
a-	gi-	tate
{	dZ I	t eI t
a-	gile
{	dZ V l
a-	gin
Q	dZ i: n
a-	gin-	court
{	dZ V n	k O@ t
a-	ging
eI	dZ I N
a-	go
V	g @U
a-	go-	ni-	zes
{	g V	n aI	z V z
a-	go-	ni-	zing
{	g V	n aI	z I N
a-	go-	ni-	zing-	ly
{	g V	n aI	z I N	l i:
a-	go-	nies
{	g V	n i: z
a-	go-	nist
{	g V	n V s t
a-	go-	nists
{	g V	n V s t s
a-	go-	nize
{	g V	n aI z
a-	go-	nized
{	g V	n aI z d
a-	go-	ny
{	g V	n i:
a-	go-	ra
{	g @r	V
a-	gog
V	g Q g
a-	gos-	ti-	ni
Q	g @U s	t i:	n i:
a-	gos-	ti-	no
Q	g O: s	t i:	n @U
a-	gos-	to
Q	g @U s	t @U
a-	gra
{ g	r V
a-	gua
Q g	w V
a-	gua-	cate
{ g	w V	k eI t
a-	gua-	yo
Q g	w eI	@U
a-	gui-	la
Q g	w i:	l V
a-	gui-	lar
{	g I	l Q@
a-	guir-	re
Q g	w I@	eI
a-	guir-	re's
Q g	w I@	eI z
a-	gus-	tin
V	g O: s	t V n
a-	ha
Q	h Q
a-	ha-	ron
{	h @r	Q n
a-	hab
eI	h { b
a-	hah
Q	h Q
a-	head
V	h e d
a-	hearn
V	h @r n
a-	hern
V	h @r n
a-	ho
Q	h @U
a-	ho-	la
{	h V	l V
a-	hold
V	h @U l d
a-	i-	da
aI	i:	d V
a-	i-	dan
Q	i:	d Q n
a-	i-	sa
aI	i:	s V
a-	ja
aI	V
a-	ja-	x's
eI	dZ { k	s V z
a-	jar
V	dZ Q@
a-	jax
eI	dZ { k s
a-	ka
Q	k V
a-	ka-	li
V	k Q	l i:
a-	kel
V	k e l
a-	ker
{	k @r
a-	ker-	ley
V	k @r	l i:
a-	kers
eI	k @r z
a-	key
V	k i:
a-	ki-	ba
V	k i:	b V
a-	ki-	h-	ito
Q	k i:	h i:	t @U
a-	ki-	ra
V	k i:	r V
a-	ki-	ta
V	k i:	t V
a-	ki-	ta's
V	k i:	t V z
a-	ki-	va
V	k i:	v V
a-	kim-	bo
V	k I m	b @U
a-	kin
V	k I n
a-	kins
V	k I n z
a-	la
eI	l V
a-	la-	ba-	ma
{	l V	b {	m V
a-	la-	ba-	man
{	l V	b {	m V n
a-	la-	ba-	mans
{	l V	b {	m V n z
a-	la-	ba-	ma's
{	l V	b {	m V z
a-	la-	bas-	ter
{	l V	b { s	t @r
a-	la-	chu-	a
V	l {	tS u:	V
a-	la-	goas
{	l V	g @U z
a-	la-	me-	da
{	l V	m i:	d V
a-	la-	mein
{	l V	m aI n
a-	la-	mi-	tos
{	l V	m i:	t @U s
a-	la-	mo
{	l V	m @U
a-	la-	mos
{	l V	m @U z
a-	la-	na
Q	l {	n V
a-	la-	ric
{	l @r	I k
a-	la-	rice
Q	l Q@	I s
a-	lac-	ri-	ty
V	l { k	r V	t i:
a-	lad-	din
V	l {	d V n
a-	lai
V	l aI
a-	lain
V	l eI n
a-	laine
V	l eI n
a-	lair
V	l e@
a-	lan
{	l V n
a-	lan-	na
Q	l Q	n V
a-	land
{	l V n d
a-	lane
V	l eI n
a-	lan's
{	l V n z
a-	lar
eI	l Q@
a-	lar-	con
V	l Q@	k Q n
a-	lar-	ming
V	l Q@	m I N
a-	lar-	ming-	ly
V	l Q@	m I N	l i:
a-	lar-	mist
V	l Q@	m V s t
a-	lard
V	l Q@ d
a-	larm
V	l Q@ m
a-	larmed
V	l Q@ m d
a-	larms
V	l Q@ m z
a-	las
V	l { s
a-	las-	ka
V	l { s	k V
a-	las-	kan
V	l { s	k V n
a-	las-	kans
V	l { s	k V n z
a-	las-	ka's
V	l { s	k V z
a-	las-	tair
{	l V s	t e@
a-	las-	ter
{	l V s	t @r
a-	layne
V	l eI n
a-	le-	a-	to-	ry
eI	l i:	V	t O@	i:
a-	le-	da
Q	l eI	d V
a-	le-	gre
Q	l e g	r i:
a-	le-	jan-	dro
Q	l eI	j Q n	d r @U
a-	le-	jo
Q	l eI	j @U
a-	le-	na
Q	l eI	n V
a-	le-	ron
Q	l e@	O: n
a-	le-	ta
Q	l e	t V
a-	le-	the-	a
{	l V	T i:	V
a-	le-	xa
V	l e k	s V
a-	le-	xan-	der
{	l V g	z { n	d @r
a-	le-	xan-	ders
{	l I g	z { n	d @r z
a-	le-	xan-	der's
{	l V g	z { n	d @r z
a-	le-	xand-	ra
{	l e g	z { n	d r V
a-	le-	xand-	re
{	l I k	s Q n	d @r
a-	le-	xand-	ri-	a
{	l V g	z { n	d r i:	V
a-	le-	xand-	rine
{	l V g	z { n	d r i: n
a-	le-	xand-	rines
{	l V g	z { n	d r i: n z
a-	le-	xei
V	l e k	s eI
a-	le-	xi
V	l e k	s i:
a-	le-	xi-	a
V	l e k	s i:	V
a-	le-	xine
V	l e k	s aI n
a-	le-	xis
V	l e k	s I s
a-	le-	xi's
V	l e k	s i: z
a-	le-	x's
{	l V k	s V z
a-	lec
{	l I k
a-	leen
V	l i: n
a-	lei-	chem
V	l e	h e m
a-	lek-	san-	dr
{	l V g	z { n	d @r
a-	lene
V	l i: n
a-	leph
Q	l V f
a-	ler-	ted
V	l @r	t V d
a-	ler-	ting
V	l @r	t I N
a-	lert
V	l @r t
a-	lert-	ness
V	l @r t	n V s
a-	lerts
V	l @r t s
a-	les-	san-	dra
{	l e	s { n	d r V
a-	les-	san-	dro
Q	l eI	z Q n	d r @U
a-	leu-	tian
V	l u:	S V n
a-	leu-	tians
V	l u:	S V n z
a-	leve
V	l i: v
a-	lex
{	l V k s
a-	ley
eI	l i:
a-	li
Q	l i:
a-	li-	a-	ses
eI	l i:	V	s V z
a-	li-	as
eI	l i:	V s
a-	li-	bi
{	l I	b aI
a-	li-	bis
{	l I	b aI z
a-	li-	ce-	a
V	l I	s i:	V
a-	li-	ce's
{	l I	s V z
a-	li-	cia
V	l I	S V
a-	li-	cia's
V	l I	S V z
a-	li-	da
Q	l i:	d V
a-	li-	e-	na-	ted
eI	l i:	V	n eI	t I d
a-	li-	e-	na-	ting
eI	l i:	V	n eI	t I N
a-	li-	e-	na-	tion
eI	l i:	V	n eI	S V n
a-	li-	e-	nates
eI	l i:	V	n eI t s
a-	li-	en
eI	l i:	V n
a-	li-	ens
eI	l i:	V n z
a-	li-	ma
Q	l i:	m V
a-	li-	men-	ta-	ry
{	l I	m e n	t @r	i:
a-	li-	mo-	ny
{	l I	m @U	n i:
a-	li-	na
V	l i:	n V
a-	li-	quip-	pa
{	l I k	w I	p V
a-	li-	quip-	pa's
{	l I k	w I	p V z
a-	li-	son
{	l I	s V n
a-	li-	ta
Q	l i:	t V
a-	li-	ta-	li-	a
{	l I	t eI	l i:	V
a-	li-	ta-	li-	a's
{	l I	t eI	l i:	V z
a-	li-	thi-	a
V	l I	T i:	V
a-	lice
{	l I s
a-	lie
{	l i:
a-	lie-	nate
eI l	j I	n eI t
a-	lig-	ning
V	l aI	n I N
a-	light
V	l aI t
a-	lign
V	l aI n
a-	lign-	ment
V	l aI n	m V n t
a-	lign-	ments
V	l aI n	m V n t s
a-	ligned
V	l aI n d
a-	ligns
V	l aI n z
a-	like
V	l aI k
a-	line
V	l aI n
a-	lines
V	l aI n z
a-	li's
Q	l i: z
a-	lis-	sa
V	l I	s V
a-	lis-	tair
{	l I s	t e@
a-	lis-	ter
{	l I s	t @r
a-	live
V	l aI v
a-	lix
{	l I k s
a-	lley
{	l i:
a-	lley's
{	l i: z
a-	lo-	die
V	l Q	d i:
a-	lo-	ha
V	l @U	h Q
a-	loe
{	l @U
a-	loft
V	l O: f t
a-	loi-	si-	a
Q	l OI	s i:	V
a-	lois
Q	l OI s
a-	lon
V	l Q n
a-	lon-	so
V	l Q n	s @U
a-	lon-	zo
V	l Q n	z @U
a-	lone
V	l @U n
a-	long
V	l O: N
a-	long-	side
V	l O: N	s aI d
a-	loof
V	l u: f
a-	loof-	ness
V	l u: f	n V s
a-	loud
V	l aU d
a-	loy-	si-	a
Q	l OI	s i:	V
a-	loy-	si-	us
{	l @U	I	S V s
a-	loys
V	l OI z
a-	lu
Q	l u:
a-	lu-	mi-	na
V	l u:	m V	n V
a-	lu-	mi-	nium
V	l u:	m V	n V m
a-	lu-	mi-	nize
V	l u:	m V	n aI z
a-	lu-	mi-	nized
V	l u:	m V	n aI z d
a-	lu-	mi-	no-	si-	li-	cate
V	l u:	m V	n @U	s I	l V	k eI t
a-	lu-	mi-	num
V	l u:	m V	n V m
a-	lu-	mi-	num's
V	l u:	m V	n V m z
a-	lum
{	l V m
a-	lum-	ni
V	l V m	n aI
a-	lum-	nus
V	l V m	n V s
a-	lums
{	l V m z
a-	ly
eI	l i:
a-	ly-	es-	ka
{	l i:	e s	k V
a-	ly-	si-	a
V	l I	s i:	V
a-	lyce
{	l I s
a-	lyes-	ka's
{ l	j e s	k V z
a-	lys
{	l i: z
a-	lys-	sa
V	l I	s V
a-	ma-	bel
{	m V	b e l
a-	ma-	belle
{	m V	b V l
a-	ma-	bile
Q	m Q	b I l
a-	ma-	de-	o
Q	m Q	d i:	@U
a-	ma-	de-	us
{	m V	d eI	V s
a-	ma-	do
Q	m Q	d @U
a-	ma-	dor
{	m V	d O@
a-	ma-	dou
{	m V	d u:
a-	ma-	le-	a
{	m V	l i:	V
a-	ma-	lia
V	m Q l	j V
a-	ma-	lie
{	m V	l i:
a-	ma-	na
V	m {	n V
a-	ma-	ra
Q	m Q@	V
a-	ma-	ral
Q	m Q@	{ l
a-	ma-	ranth
{	m @r	{ n T
a-	ma-	ri
Q	m Q@	i:
a-	ma-	ril-	lo
{	m @r	I	l @U
a-	ma-	rin
{	m @r	I n
a-	ma-	ris
{	m @r	I s
a-	ma-	ryl-	li-	ses
{	m @r	I	l I	s I z
a-	ma-	ryl-	lis
{	m @r	I	l I s
a-	ma-	sa
{	m V	s V
a-	ma-	teu-	ri-	sm
{	m V	tS @r	I	z V m
a-	ma-	teu-	rish
{	m V	tS @r	I S
a-	ma-	teur
{	m V	t @r
a-	ma-	teurs
{	m V	t @r z
a-	ma-	to
Q	m Q	t @U
a-	ma-	ya
Q	m Q	j V
a-	ma-	zes
V	m eI	z V z
a-	ma-	zing
V	m eI	z I N
a-	ma-	zing-	ly
V	m eI	z I N	l i:
)"
R"(a-	ma-	zo-	ni-	a
{	m V	z @U	n i:	V
a-	ma-	zo-	ni-	an
{	m V	z @U	n i:	V n
a-	ma-	zon
{	m V	z Q n
a-	ma-	zons
{	m V	z Q n z
a-	ma-	zon's
{	m V	z Q n z
a-	mal
V	m Q l
a-	mal-	ga-	ma-	ted
V	m { l	g V	m eI	t V d
a-	mal-	ga-	ma-	tion
V	m { l	g V	m eI	S V n
a-	mal-	ga-	mate
V	m { l	g V	m eI t
a-	mal-	gam
V	m { l	g V m
a-	mal-	gams
V	m { l	g V m z
a-	man
Q	m V n
a-	man-	da
V	m { n	d V
a-	man-	da's
V	m { n	d V z
a-	man-	te
Q	m Q n	t i:
a-	mann
{	m V n
a-	mar
V	m Q@
a-	mas-	sing
V	m {	s I N
a-	mass
V	m { s
a-	massed
V	m { s t
a-	maze
V	m eI z
a-	maze-	ment
V	m eI z	m V n t
a-	mazed
V	m eI z d
a-	me-	li-	ne
Q	m e	l i:	n i:
a-	me-	li-	ta
Q	m e	l i:	t V
a-	me-	lia
V	m i: l	j V
a-	me-	lio-	ra-	ted
V	m i: l	j @r	eI	t V d
a-	me-	lio-	ra-	tion
V	m i: l	j @r	eI	S V n
a-	me-	lio-	rate
V	m i: l	j @r	eI t
a-	me-	na-	ble
V	m e	n V	b V l
a-	me-	ni-	ties
V	m e	n V	t i: z
a-	me-	ni-	ty
V	m e	n V	t i:
a-	me-	ri-	ca
V	m e@	V	k V
a-	me-	ri-	can
V	m e@	V	k V n
a-	me-	ri-	cas
V	m e@	V	k V z
a-	me-	ri-	ca's
V	m e@	V	k V z
a-	me-	ri-	cus
V	m e@	I	k V s
a-	me-	ri-	go
Q	m @r	i:	g @U
a-	me-	ri-	ka
V	m e@	I	k V
a-	me-	ri-	tech
V	m e@	V	t e k
a-	me-	rin-	di-	an
{	m @r	I n	d i:	V n
a-	me-	ro
Q	m e@	@U
a-	me-	ry
{	m @r	i:
a-	me-	thyst
{	m V	T V s t
a-	me-	x's
{	m e k	s V z
a-	meen
V	m i: n
a-	men
eI	m e n
a-	men-	da-	ble
V	m e n	d V	b V l
a-	men-	ded
V	m e n	d V d
a-	men-	ding
V	m e n	d I N
a-	men-	ta
V	m e n	t V
a-	mend
V	m e n d
a-	mend-	ment
V	m e n	d m V n t
a-	mend-	ments
V	m e n	d m V n t s
a-	mend-	ment's
V	m e n	d m V n t s
a-	mends
V	m e n d z
a-	ment
{	m e n t
a-	mer-	sham
{	m @r	S { m
a-	mex
{	m e k s
a-	mi
Q	m i:
a-	mi-	a-	bi-	li-	ty
eI	m i:	V	b I	l V	t i:
a-	mi-	a-	ble
eI	m i:	V	b V l
a-	mi-	a-	bly
eI	m i:	V b	l i:
a-	mi-	ca-	ble
{	m I	k V	b V l
a-	mi-	ca-	bly
{	m I	k V b	l i:
a-	mi-	cus
V	m i:	k V s
a-	mi-	don
{	m I	d Q n
a-	mi-	ga
V	m i:	g V
a-	mi-	go
V	m i:	g @U
a-	mi-	gos
V	m i:	g @U z
a-	mi-	no
V	m i:	n @U
a-	mi-	ty
{	m I	t i:
a-	mi-	tyvil-	le
{	m I	t i:	v I l
a-	mick
{	m I k
a-	mid
V	m I d
a-	mid-	ships
V	m I d	S V p s
a-	midst
V	m I d s t
a-	mie
{	m i:
a-	min
Q	m i: n
a-	min-	ta
V	m I n	t V
a-	mir
V	m I@
a-	mir's
V	m I@ z
a-	mis
{	m I s
a-	mish
Q	m I S
a-	miss
V	m I s
a-	mit
Q	m i: t
a-	mo
Q	m @U
a-	mo-	co
{	m V	k @U
a-	mo-	co's
{	m V	k @U z
a-	mo-	ral
eI	m O@	V l
a-	mo-	rette
{	m @r	e t
a-	mo-	ri-	ta
Q	m O@	i:	t V
a-	mo-	rist
{	m @r	I s t
a-	mo-	ro-	so
Q	m O@	@U	s @U
a-	mo-	rous
{	m @r	V s
a-	mo-	ry
eI	m @r	i:
a-	moe-	ba
V	m i:	b V
a-	moe-	bas
V	m i:	b V z
a-	moe-	bic
V	m i:	b I k
a-	mok
V	m V k
a-	mon
Q	m O: n
a-	mong
V	m Q N
a-	mongst
V	m V N s t
a-	mor
{	m @r
a-	mor-	phous
V	m O@	f V s
a-	mor-	ti-	za-	tion
{	m @r	t I	z eI	S V n
a-	mor-	ti-	zing
{	m @r	t aI	z I N
a-	mor-	tize
{	m @r	t aI z
a-	mor-	tized
{	m @r	t aI z d
a-	more
Q	m O@
a-	mos
eI	m V s
a-	mos-	keag
{	m V s	k eI g
a-	mos-	keag's
{	m V s	k eI g z
a-	moun-	ted
V	m aU n	t V d
a-	moun-	ting
V	m aU n	t I N
a-	mount
V	m aU n t
a-	mounts
V	m aU n t s
a-	mu-	let
{ m	j V	l V t
a-	mu-	lets
{ m	j V	l V t s
a-	mu-	ses
V m	j u:	z V z
a-	mu-	sing
V m	j u:	z I N
a-	mu-	sing-	ly
V m	j u:	z I N	l i:
a-	muck
V	m V k
a-	mun-	dsen
eI	m V n	d s V n
a-	muse
V m	j u: z
a-	muse-	ment
V m	j u: z	m V n t
a-	muse-	ments
V m	j u: z	m V n t s
a-	mused
V m	j u: z d
a-	my
eI	m i:
a-	my-	lin
{	m V	l I n
a-	my-	loid
{	m V	l OI d
a-	my-	ot-	ro-	phic
{	m aI	V t	r @U	f I k
a-	my's
eI	m i: z
a-	na
Q	n V
a-	na-	bap-	tist
{	n V	b { p	t V s t
a-	na-	bo-	lic
{	n V	b Q	l I k
a-	na-	cin
{	n V	s I n
a-	na-	con-	da
{	n V	k Q n	d V
a-	na-	cos-	ti-	a
{	n V	k Q s	t i:	V
a-	na-	cos-	ti-	a's
{	n V	k Q s	t i:	V z
a-	na-	dar-	ko
{	n V	d Q@	k @U
a-	na-	dar-	ko's
{	n V	d Q@	k @U z
a-	na-	heim
{	n V	h aI m
a-	na-	ly-	ti-	cal
{	n V	l I	t I	k V l
a-	na-	ly-	ti-	ci-	ty
{	n V	l V	t I	s V	t i:
a-	na-	ly-	tic
{	n V	l I	t I k
a-	na-	ly-	tical-	ly
{	n V	l I	t I k	l i:
a-	na-	ly-	tics
{	n V	l I	t I k s
a-	na-	ly-	za-	ble
{	n V	l aI	z V	b V l
a-	na-	ly-	zer
{	n V	l aI	z @r
a-	na-	ly-	zers
{	n V	l aI	z @r z
a-	na-	ly-	zes
{	n V	l aI	z V z
a-	na-	ly-	zing
{	n V	l aI	z I N
a-	na-	lyst
{	n V	l V s t
a-	na-	lysts
{	n V	l V s t s
a-	na-	lyst's
{	n V	l V s t s
a-	na-	lyze
{	n V	l aI z
a-	na-	lyzed
{	n V	l aI z d
a-	na-	pho-	ra
V	n {	f @r	V
a-	na-	sa-	zi
{	n V	s {	z i:
a-	na-	the-	ma
V	n {	T V	m V
a-	na-	to-	la
Q	n Q	t @U	l V
a-	na-	to-	li-	a
{	n V	t @U	l i:	V
a-	na-	to-	li-	an
{	n V	t @U	l i:	V n
a-	na-	to-	mi-	cal
{	n V	t Q	m V	k V l
a-	na-	to-	mical-	ly
{	n V	t Q	m V k	l i:
a-	na-	to-	mist
V	n {	t V	m V s t
a-	na-	to-	my
V	n {	t V	m i:
a-	na-	tole
{	n V	t @U l
a-	nac
{	n { k
a-	nach-	ro-	ni-	sm
V	n { k	r V	n I	z V m
a-	nach-	ro-	ni-	sms
V	n { k	r V	n I	z V m z
a-	nach-	ro-	nis-	tic
V	n { k	r V	n I s	t I k
a-	nae-	ro-	bic
{	n @r	@U	b I k
a-	nae-	robe
{	n @r	@U b
a-	nae-	robes
{	n @r	@U b z
a-	naes-	the-	sia
{	n V s	T i:	Z V
a-	naf-	ra-	nil
V	n { f	r V	n I l
a-	nag-	nos
Q	n Q g	n @U z
a-	nag-	ram
{	n V g	r { m
a-	nal
eI	n V l
a-	nal-	ge-	sic
{	n V l	dZ i:	s I k
a-	nal-	ge-	sics
{	n V l	dZ i:	z I k s
a-	nand
{	n V n d
a-	nar-	chi-	cal
{	n Q@	k I	k V l
a-	nar-	chic
{	n Q@	k I k
a-	nar-	chist
{	n @r	k I s t
a-	nar-	chists
{	n @r	k I s t s
a-	nar-	chy
{	n @r	k i:
a-	nas
{	n V s
a-	nas-	ta-	si-	o
Q	n Q s	t Q	s i:	@U
a-	nas-	ta-	sia
{	n V s	t eI	Z V
a-	nas-	tas
{	n V s	t V z
a-	nas-	tos
{	n V s	t @U z
a-	ne-	mi-	a
V	n i:	m i:	V
a-	ne-	mi-	as
V	n i:	m i:	V z
a-	ne-	mic
V	n i:	m I k
a-	ne-	mo-	me-	ter
{	n V	m Q	m V	t @r
a-	ne-	mone
{	n V	m @U n
a-	nec-	do-	ta-	lly
{	n V k	d @U	t V	l i:
a-	nec-	do-	tal
{	n V k	d @U	t V l
a-	nec-	dote
{	n V k	d @U t
a-	nec-	dotes
{	n V k	d @U t s
a-	nen-	ce-	pha-	lic
{	n e n	s V	f {	l I k
a-	nen-	ce-	pha-	ly
{	n V n	s e	f V	l i:
a-	nes-	the-	si-	o-	lo-	gist
{	n V s	T i:	z i:	Q	l V	dZ V s t
a-	nes-	the-	si-	o-	lo-	gists
{	n V s	T i:	z i:	Q	l V	dZ V s t s
a-	nes-	the-	si-	o-	lo-	gy
{	n V s	T i:	z i:	Q	l V	dZ i:
a-	nes-	the-	sia
{	n V s	T i:	Z V
a-	nes-	the-	tic
{	n V s	T e	t I k
a-	nes-	the-	tics
{	n V s	T e	t I k s
a-	nes-	the-	tist
V	n e s	T V	t V s t
a-	nette
V	n e t
a-	neu-	ri-	sm
{ n	j U@	I	z V m
a-	new
V	n u:
a-	ni-	bal
{	n I	b V l
a-	ni-	line
{	n I	l i: n
a-	ni-	ma-	ted
{	n I	m eI	t I d
a-	ni-	ma-	tion
{	n I	m eI	S V n
a-	ni-	ma-	tions
{	n I	m eI	S V n z
a-	ni-	ma-	tor
{	n I	m eI	t @r
a-	ni-	ma-	tors
{	n I	m eI	t @r z
a-	ni-	mal
{	n I	m V l
a-	ni-	mals
{	n I	m V l z
a-	ni-	mal's
{	n I	m V l z
a-	ni-	mate
{	n I	m eI t
a-	ni-	mates
{	n I	m eI t s
a-	ni-	mi-	sm
{	n I	m I	z V m
a-	ni-	mist
{	n I	m I s t
a-	ni-	mists
{	n I	m I s t s
a-	ni-	mo-	si-	ties
{	n I	m Q	s I	t i: z
a-	ni-	mo-	si-	ty
{	n I	m Q	s I	t i:
a-	ni-	mous
{	n I	m V s
a-	ni-	mus
{	n I	m V s
a-	ni-	seed
{	n I	s i: d
a-	ni-	sette
{	n I	s e t
a-	ni-	ta
V	n i:	t V
a-	nise
{	n I s
a-	no-	ma-	lies
V	n Q	m V	l i: z
a-	no-	ma-	lous
V	n Q	m V	l V s
a-	no-	ma-	ly
V	n Q	m V	l i:
a-	no-	mie
{	n V	m i:
a-	no-	na
Q	n @U	n V
a-	no-	ny-	mi-	ty
{	n V	n I	m V	t i:
a-	no-	ny-	mous
V	n Q	n V	m V s
a-	no-	ny-	mous-	ly
V	n Q	n V	m V s	l i:
a-	no-	ra
Q	n O@	V
a-	no-	rak
{	n @r	{ k
a-	no-	re-	xi-	a
{	n @r	e k	s i:	V
a-	no-	re-	xic
{	n @r	e k	s I k
a-	no-	re-	xics
{	n @r	e k	s I k s
a-	no-	ther
V	n V	D @r
a-	no-	ther's
V	n V	D @r z
a-	node
{	n @U d
a-	nodes
{	n @U d z
a-	noin-	ted
V	n OI	n V d
a-	noint
V	n OI n t
a-	nor-	thite
{	n O@	T aI t
a-	ny
e	n i:
a-	ny-	bo-	dy
e	n i:	b V	d i:
a-	ny-	how
e	n i:	h aU
a-	ny-	more
e	n i:	m O@
a-	ny-	on
e	n i:	Q n
a-	ny-	one
e	n i:	w V n
a-	ny-	one's
e	n i:	w V n z
a-	ny-	place
e	n i: p	l eI s
a-	ny-	thing
e	n i:	T I N
a-	ny-	time
e	n i:	t aI m
a-	ny-	way
e	n i:	w eI
a-	ny-	ways
e	n i:	w eI z
a-	ny-	where
e	n i:	w e@
a-	o-	ki
eI	@U	k i:
a-	o-	l
eI	@U	e l
a-	on
eI	@U n
a-	or-	ta
eI	O@	t V
a-	or-	tic
eI	O@	t I k
a-	p-	c
eI	p i:	s i:
a-	pa-	che
V	p {	tS i:
a-	pa-	ches
V	p {	tS i: z
a-	pa-	che's
V	p {	tS i: z
a-	pa-	la-	chi-	co-	la
{	p V	l {	tS V	k @U	l V
a-	pa-	la-	chi-	co-	la's
{	p V	l {	tS V	k @U	l V z
a-	pa-	the-	tic
{	p V	T e	t I k
a-	pa-	thy
{	p V	T i:
a-	pa-	tite
{	p V	t aI t
a-	pa-	tites
{	p V	t aI t s
a-	pace
V	p eI s
a-	par-	theid
V	p Q@	t aI t
a-	par-	theid's
V	p Q@	t aI t s
a-	part
V	p Q@ t
a-	part-	ment
V	p Q@ t	m V n t
a-	part-	ments
V	p Q@ t	m V n t s
a-	pe-	x's
eI	p e k	s V z
a-	pen-	nine
{	p V	n i: n
a-	per-	ture
{	p @r	tS @r
a-	pex
eI	p e k s
a-	pha-	sia
V	f eI	Z V
a-	phid
eI	f V d
a-	phids
{	f V d z
a-	pho-	ri-	sm
{	f @r	I	z V m
a-	pho-	ri-	sms
{	f @r	I	z V m z
a-	pi-	cel-	la
{	p I	s e	l V
a-	piece
V	p i: s
a-	ping
eI	p I N
a-	po-	ca-	lyp-	tic
V	p Q	k V	l I p	t I k
a-	po-	ca-	lypse
V	p Q	k V	l I p s
a-	po-	cry-	phal
V	p Q k	r V	f V l
a-	po-	gee
{	p V	dZ i:
a-	po-	li-	ti-	cal
eI	p V	l I	t I	k V l
a-	po-	lo-	ge-	tic
V	p Q	l V	dZ e	t I k
a-	po-	lo-	ge-	tical-	ly
V	p Q	l V	dZ e	t I k	l i:
a-	po-	lo-	gi-	zes
V	p Q	l V	dZ aI	z V z
a-	po-	lo-	gi-	zing
V	p Q	l V	dZ aI	z I N
a-	po-	lo-	gies
V	p Q	l V	dZ i: z
a-	po-	lo-	gist
V	p Q	l V	dZ V s t
a-	po-	lo-	gists
V	p Q	l V	dZ V s t s
a-	po-	lo-	gize
V	p Q	l V	dZ aI z
a-	po-	lo-	gized
V	p Q	l V	dZ aI z d
a-	po-	lo-	gy
V	p Q	l V	dZ i:
a-	po-	the-	ca-	ry
V	p Q	T V	k e@	i:
a-	po-	the-	o-	sis
V	p Q	T i:	@U	s V s
a-	pol-	li-	ni-	an
{	p V	l I	n i:	V n
a-	pol-	line
{	p V	l aI n
a-	pol-	lo
V	p Q	l @U
a-	pol-	lo-	ni-	an
{	p V	l @U	n i:	V n
a-	pol-	lo's
V	p Q	l @U z
a-	pop-	ka
V	p O: p	k V
a-	pop-	le-	xy
{	p V p	l e k	s i:
a-	pop-	lec-	tic
{	p V p	l e k	t I k
a-	pos-	tle
V	p Q	s V l
a-	pos-	tles
V	p Q	s V l z
a-	pos-	tro-	phe
V	p Q s	t r V	f i:
a-	qa-	ba
V	k Q	b V
a-	qua
{ k	w V
a-	qua-	cul-	ture
{ k	w V	k V l	tS @r
a-	qua-	lung
{ k	w V	l V N
a-	qua-	ma-	rine
Q k	w V	m @r	i: n
a-	qua-	naut
Q k	w V	n Q t
a-	qua-	nauts
Q k	w V	n Q t s
a-	qua-	ri-	um
V k	w e@	i:	V m
a-	qua-	ri-	ums
V k	w e@	i:	V m z
a-	qua-	ri-	us
V k	w e@	i:	V s
a-	qua-	rist
V k	w e@	V s t
a-	qua-	rists
V k	w e@	V s t s
a-	qua-	tic
V k	w Q	t I k
a-	que-	duct
{ k	w V	d V k t
a-	que-	ducts
{ k	w V	d V k t s
a-	que-	ous
eI k	w i:	V s
a-	qui-	fer
{ k	w I	f @r
a-	qui-	fers
{ k	w I	f @r z
a-	qui-	la
{ k	w I	l V
a-	qui-	li-	no
Q k	w i:	l i:	n @U
a-	qui-	nas
V k	w aI	n V s
a-	qui-	no
V	k i:	n @U
a-	qui-	no's
V	k i:	n @U z
a-	qui-	taine
{ k	w I	t eI n
a-	ra
{	r V
a-	ra-	bel-	la
{	r V	b e	l V
a-	ra-	bi-	a
@r	eI	b i:	V
a-	ra-	bi-	an
@r	eI	b i:	V n
a-	ra-	bi-	ans
@r	eI	b i:	V n z
a-	ra-	bi-	a's
@r	eI	b i:	V z
a-	ra-	bi-	ca
@r	{	b I	k V
a-	ra-	bic
{	r V	b I k
a-	ra-	ble
e@	V	b V l
a-	ra-	chnid
@r	{ k	n I d
a-	ra-	chnids
@r	{ k	n I d z
a-	ra-	fat
e@	V	f { t
a-	ra-	fat's
Q@	V	f Q t s
a-	ra-	gon
e@	V	g Q n
a-	ra-	ka-	wa
Q@	Q	k Q	w V
a-	ra-	mid
e@	V	m V d
a-	ra-	min-	ta
{	r V	m I n	t V
a-	ra-	mis
e@	V	m I s
a-	ra-	pa-	ho
@r	{	p V	h @U
a-	rab
{	r V b
a-	rabs
{	r V b z
a-	rai-	za
@r	eI	z V
a-	ral
Q@	V l
a-	ram-	co
@r	{ m	k @U
a-	ran
e@	V n
a-	ran-	da
@r	{ n	d V
a-	ran-	go
Q@	Q N	g @U
a-	ran-	sas
@r	{ n	s V s
a-	re-	a
e@	i:	V
a-	re-	as
e@	i:	V z
a-	re-	a's
e@	i:	V z
a-	re-	na
@r	i:	n V
a-	re-	nas
@r	i:	n V z
a-	re-	na's
@r	i:	n V z
a-	re-	ta
Q@	e	t V
a-	re-	tha
@r	i:	T V
a-	re-	ti-	na
Q@	e	t i:	n V
a-	rel
Q@	e l
a-	ren
Q@	V n
a-	rend
@r	e n d
a-	rends
@r	e n d z
a-	rendt
e@	e n t
a-	rent
Q@	V n t
a-	ren't
Q@	V n t
a-	ret-	ta
Q@	e	t V
a-	ri
Q@	i:
a-	ri-	a
Q@	i:	V
a-	ri-	a-	na
Q@	i:	{	n V
a-	ri-	a-	ni-	sm
{	r i:	V	n I	z V m
a-	ri-	ad-	ne
e@	i:	{ d	n i:
a-	ri-	an
{	r i:	V n
a-	ri-	an-	na
Q@	i:	{	n V
a-	ri-	an-	na's
Q@	i:	{	n V z
a-	ri-	ane
e@	i:	{ n
a-	ri-	as
Q@	i:	V z
a-	ri-	el
e@	i:	V l
a-	ri-	el-	la
Q@	i:	e	l V
a-	ri-	sen
@r	I	z V n
a-	ri-	ses
@r	aI	z V z
a-	ri-	sing
@r	aI	z I N
a-	ri-	spe
Q@	i: s	p i:
a-	ri-	zo-	na
e@	I	z @U	n V
a-	ri-	zo-	nan
@r	I	z @U	n V n
a-	ri-	zo-	nans
@r	I	z @U	n V n z
a-	ri-	zo-	na's
e@	I	z @U	n V z
a-	ric
{	r I k
a-	rid
{	r I d
a-	rie
e@	i:
a-	ries
e@	i: z
a-	ris
@r	i: s
a-	ris-	ta
@r	I s	t V
a-	ris-	tide
Q@	I s	t i: d
a-	ris-	tide's
Q@	I s	t i: d z
a-	ris-	to-	te-	li-	an
@r	I s	t V	t i:	l i:	V n
a-	ris-	to-	tle
e@	I s	t Q	t V l
a-	ris-	to-	tle's
e@	I s	t Q	t V l z
a-	ris-	toc-	ra-	cy
e@	I s	t Q k	r V	s i:
a-	ris-	toc-	ra-	tic
@r	I s	t V k	r {	t I k
a-	ris-	toc-	rat
@r	I s	t V k	r { t
a-	ris-	toc-	rats
@r	I s	t V k	r { t s
a-	rise
@r	aI z
a-	rith-	met-	ic
e@	I T	m e	t I k
a-	ro
Q@	@U
a-	ro-	ma
@r	@U	m V
a-	ro-	ma-	tic
e@	V	m {	t I k
a-	ro-	mas
@r	@U	m V z
a-	ro-	noff
e@	V	n O: f
a-	ro-	now
@r	@U	n @U
a-	ron
e@	V n
a-	ron-	son
e@	V n	s V n
a-	rose
@r	@U z
a-	rou-	sal
@r	aU	z V l
a-	rou-	ses
@r	aU	z V z
a-	rou-	sing
@r	aU	z I N
a-	round
@r	aU n d
a-	rouse
@r	aU z
a-	roused
@r	aU z d
a-	rrant
{	r V n t
a-	ru-	ba
@r	u:	b V
a-	rum
e@	V m
a-	run-	del
e@	V n	d V l
a-	rup
@r	u: p
a-	ry
e@	i:
a-	sa
Q	s V
a-	sa-	hi
V	s Q	h i:
a-	sat
{	z { t
a-	sce-	tic
V	s e	t I k
a-	scent
V	s e n t
a-	scer-	tai-	ning
{	s @r	t eI	n I N
a-	scer-	tain
{	s @r	t eI n
a-	scer-	tained
{	s @r	t eI n d
a-	scher
{	S @r
a-	se-	a
V	z i:	V
a-	se-	an
V	z i:	V n
a-	shame
V	S eI m
a-	shamed
V	S eI m d
a-	shen
{	S V n
a-	sher
{	S @r
a-	shes
{	S V z
a-	she's
{	S V z
a-	shok
{	S Q k
a-	shore
V	S O@
a-	shur
{	S @r
a-	shville
{ S	v I l
a-	shy
{	S i:
a-	si-	a-	tic
eI	Z i:	{	t I k
a-	si-	mov
{	s V	m Q v
a-	si-	nine
{	s I	n aI n
a-	sia
eI	Z V
a-	sian
eI	Z V n
a-	sians
eI	Z V n z
a-	sia's
eI	Z V z
a-	sic
{	z I k
a-	side
V	s aI d
a-	sides
V	s aI d z
a-	sun-	cion
V	s V n	S V n
a-	sun-	der
V	s V n	d @r
a-	sy-	lum
V	s aI	l V m
a-	sym-	met-	ri-	cal
eI	s V	m e t	r I	k V l
a-	sym-	met-	ries
eI	s I	m V t	r i: z
a-	sym-	met-	ry
eI	s I	m V t	r i:
a-	symp-	to-	ma-	tic
eI	s I m	p t V	m {	t I k
a-	symp-	tote
{	s V m	t @U t
a-	symp-	totes
{	s V m	t @U t s
a-	synch-	ro-	nous
eI	s I N	k r V	n V s
a-	t-	p
eI	t i:	p i:
a-	ta
Q	t V
a-	ta-	la-	ya
Q	t Q	l eI	V
a-	ta-	lan-	ta
{	t V	l { n	t V
a-	ta-	lie
{	t V	l i:
a-	ta-	ri
V	t Q@	i:
a-	ta-	ri's
V	t Q@	i: z
a-	ta-	turk
{	t V	t @r k
a-	ta-	vi-	sm
{	t V	v I	z V m
a-	ta-	vis-	tic
{	t V	v I s	t I k
a-	ta-	xi-	a
eI	t { k	s i:	V
a-	ta-	xi-	a's
eI	t { k	s i:	V z
a-	tche-	son
{	tS V	s V n
a-	tchi-	son
{	tS I	s V n
a-	ten
eI	t V n
a-	ter
eI	t @r
a-	tha-	li-	a
eI	T {	l i:	V
a-	the-	i-	sm
eI	T i:	I	z V m
a-	the-	is-	tic
eI	T i:	I s	t I k
a-	the-	ist
eI	T i:	I s t
a-	the-	ists
eI	T i:	I s t s
a-	the-	na
V	T i:	n V
a-	the-	nae-	um
{	T V	n i:	V m
a-	the-	neum
{	T V	n u: m
a-	the-	ni-	an
V	T i:	n i:	V n
a-	the-	ni-	ans
V	T i:	n i:	V n z
a-	the-	rosc-	le-	ro-	sis
{	T @r	@U s	k l @r	@U	s V s
a-	thens
{	T V n z
a-	ther-	ton
{	T @r	t V n
a-	they
{	T i:
a-	thie
eI	T i:
a-	thle-	ti-	cism
{ T	l e	t I	s I z m
a-	thle-	tic
{ T	l e	t I k
a-	thle-	tical-	ly
{ T	l e	t I k	l i:
a-	thle-	tics
{ T	l e	t I k s
a-	thlete
{ T	l i: t
a-	thletes
{ T	l i: t s
a-	to-	cha
V	t Q	tS V
a-	to-	mi-	zer
{	t V	m aI	z @r
a-	to-	mic
V	t Q	m I k
a-	to-	nal
eI	t @U	n V l
a-	toll
{	t Q l
a-	tom
{	t V m
a-	toms
{	t V m z
a-	ton
V	t Q n
a-	tone
V	t @U n
a-	tone-	ment
V	t @U n	m V n t
a-	top
V	t Q p
a-	tor
e	t @r
a-	ty-	pi-	cal
eI	t I	p I	k V l
a-	va
eI	v V
a-	va-	lan-	ches
{	v V	l { n	tS V z
a-	va-	lanche
{	v V	l { n tS
a-	va-	lon
{	v V	l Q n
a-	va-	lon's
{	v V	l Q n z
a-	va-	rice
{	v @r	I s
a-	vai-	la-	bi-	li-	ties
V	v eI	l V	b I	l V	t i: z
a-	vai-	la-	bi-	li-	ty
V	v eI	l V	b I	l V	t i:
a-	vai-	la-	ble
V	v eI	l V	b V l
a-	vail
V	v eI l
a-	vailed
V	v eI l d
a-	van-	ti
V	v Q n	t i:
a-	vant
V	v Q n t
a-	vant-	garde
V	v Q n	t g Q@ d
a-	ve-	li-	ne
Q	v e	l i:	n i:
a-	ve-	na
Q	v eI	n V
a-	ve-	nel
Q	v eI	n e l
a-	ve-	rage
{	v @r	I dZ
a-	ve-	ry
eI	v @r	i:
a-	ve-	ryl
{	v @r	V l
a-	ve-	ry's
eI	v @r	i: z
a-	vel-	la
V	v e	l V
a-	vel-	li-	no
{	v V	l i:	n @U
a-	vel-	li-	no's
{	v V	l i:	n @U z
a-	ven-	ger
V	v e n	dZ @r
a-	venge
V	v e n dZ
a-	venged
V	v e n dZ d
a-	ver-	sion
V	v @r	Z V n
a-	ver-	sive
V	v @r	s I v
a-	ver-	ted
V	v @r	t V d
a-	ver-	ting
V	v @r	t I N
a-	vers
eI	v @r z
a-	verse
V	v @r s
a-	vert
V	v @r t
a-	verts
V	v @r t s
a-	vi
Q	v i:
a-	vi-	a-	ries
eI	v i:	e@	i: z
a-	vi-	a-	ry
eI	v i:	e@	i:
a-	vi-	a-	tion
eI	v i:	eI	S V n
a-	vi-	a-	tion's
eI	v i:	eI	S V n z
a-	vi-	a-	tor
eI	v i:	eI	t @r
a-	vi-	a-	tors
eI	v i:	eI	t @r z
a-	vi-	la
V	v I	l V
a-	vi-	o-	nic
eI	v i:	Q	n I k
a-	vi-	o-	nics
eI	v i:	Q	n I k s
a-	vi-	ons
eI	v i:	V n z
a-	vi-	tal
V	v i:	t V l
a-	vice
Q	v aI s
a-	vid
{	v I d
a-	vid-	ly
{	v I d	l i:
a-	vil-	la
V	v I	l V
a-	vin-	ger
eI	v I	N @r
a-	vis
eI	v I s
)"
R"(a-	viv
Q	v i: v
a-	viv's
Q	v i: v z
a-	vo-	ca-	do
{	v V	k Q	d @U
a-	vo-	ca-	dos
{	v V	k Q	d @U z
a-	vo-	ca-	tion
{	v V	k eI	S V n
a-	vo-	cet
{	v V	s e t
a-	vo-	wed-	ly
V	v aU	V d	l i:
a-	voi-	da-	ble
V	v OI	d V	b V l
a-	voi-	dance
V	v OI	d V n s
a-	voi-	ded
V	v OI	d V d
a-	voi-	ding
V	v OI	d I N
a-	void
V	v OI d
a-	voids
V	v OI d z
a-	von
eI	v Q n
a-	von-	dale
{	v V n	d eI l
a-	von's
{	v V n z
a-	vow
V	v aU
a-	vowed
V	v aU d
a-	vun-	cu-	lar
V	v V N	k j V	l @r
a-	wa-	ke-	ning
V	w eI	k V	n I N
a-	wa-	ken
V	w eI	k V n
a-	wa-	kened
V	w eI	k V n d
a-	wa-	kens
V	w eI	k V n z
a-	wacs
eI	w { k s
a-	wad
V	w Q d
a-	wai-	ted
V	w eI	t V d
a-	wai-	ting
V	w eI	t I N
a-	wait
V	w eI t
a-	waits
V	w eI t s
a-	wake
V	w eI k
a-	walt
Q	v V l t
a-	wan
eI	w V n
a-	war-	ded
V	w O@	d V d
a-	war-	ding
V	w O@	d I N
a-	ward
V	w O@ d
a-	wards
V	w O@ d z
a-	ware
V	w e@
a-	ware-	ness
V	w e@	n V s
a-	wash
V	w Q S
a-	way
V	w eI
a-	ways
eI	w eI z
a-	while
V	w aI l
a-	woke
V	w @U k
a-	xa
{ k	s V
a-	xa's
{ k	s V z
a-	xel
{ k	s V l
a-	xes
{ k	s V z
a-	xi-	o-	ma-	tic
{ k	s i:	V	m {	t I k
a-	xi-	om
{ k	s i:	V m
a-	xi-	oms
{ k	s i:	V m z
a-	xis
{ k	s I s
a-	xle
{ k	s V l
a-	xles
{ k	s V l z
a-	xon
{ k	s Q n
a-	xons
{ k	s Q n z
a-	ya-	cu-	cho
aI	V	k V	tS @U
a-	ya-	la
V	j Q	l V
a-	ya-	tol-	lah
aI	V	t @U	l V
a-	ya-	tol-	lahs
aI	V	t Q	l Q z
a-	yer
aI	@r
a-	yers
aI	@r z
a-	yo
eI	@U
a-	za-	lea
V	z eI l	j V
a-	za-	leas
V	z eI l	j V z
a-	za-	li-	a
Q	z Q	l i:	V
a-	zac-	tam
V	z { k	t { m
a-	zar
Q	z Q@
a-	ze-	ri
V	z e@	i:
a-	zer-	bai-	ja-	ni
Q	z @r	b aI	dZ Q	n i:
a-	zer-	bai-	ja-	nis
Q	z @r	b aI	dZ Q	n i: z
a-	zer-	bai-	jan
Q	z @r	b aI	dZ Q n
a-	zer-	bai-	jan's
Q	z @r	b aI	dZ Q n z
a-	zi-	do-	thy-	mi-	dine
V	z I	d V	T aI	m V	d i: n
a-	zides
{	z aI d z
a-	zores
V	z O@ z
a-	zure
{	Z @r
a.
eI
aa-	berg
Q	b @r g
aa-	chen
Q	k V n
aa-	ron
e@	V n
aa-	ron-	son
e@	V n	s V n
aa-	ron-	son's
e@	V n	s V n z
aa-	ron's
e@	V n z
aar-	dvark
Q@ d	v Q@ k
ab
{ b
ab-	ba
{	b V
ab-	ba-	do
V	b Q	d @U
ab-	ba-	si
Q	b Q	s i:
ab-	bate
Q	b eI t
ab-	be
{	b i:
ab-	bey
{	b i:
ab-	bey's
{	b i: z
ab-	bie
{	b i:
ab-	bot
{	b V t
ab-	bott
{	b V t
ab-	bott's
{	b V t s
ab-	boud
V	b u: d
ab-	bre-	vi-	a-	ting
V b	r i:	v i:	eI	t I N
ab-	bre-	vi-	a-	tion
V b	r i:	v i:	eI	S V n
ab-	bre-	vi-	a-	tions
V b	r i:	v i:	eI	S V n z
ab-	bre-	vi-	at-	ed
V b	r i:	v i:	eI	t V d
ab-	bre-	vi-	ate
V b	r i:	v i:	eI t
ab-	bre-	vi-	ates
V b	r i:	v i:	eI t s
ab-	by
{	b i:
ab-	de-	lla
{ b	d e	l V
ab-	del
{ b	d e l
ab-	di-	ca-	ted
{ b	d I	k eI	t V d
ab-	di-	ca-	ting
{ b	d I	k eI	t I N
ab-	di-	ca-	tion
{ b	d I	k eI	S V n
ab-	di-	cate
{ b	d I	k eI t
ab-	di-	cates
{ b	d I	k eI t s
ab-	do-	men
{ b	d @U	m V n
ab-	do-	mi-	nal
{ b	d Q	m I	n V l
ab-	du-	lla
Q b	d u:	l V
ab-	du-	llah
{ b	d V	l V
ab-	duc-	ted
{ b	d V k	t V d
ab-	duc-	tee
{ b	d V k	t i:
ab-	duc-	tees
{ b	d V k	t i: z
ab-	duc-	ting
{ b	d V k	t I N
ab-	duc-	tion
{ b	d V k	S V n
ab-	duc-	tions
{ b	d V k	S V n z
ab-	duc-	tor
{ b	d V k	t @r
ab-	duc-	tors
{ b	d V k	t @r z
ab-	duct
{ b	d V k t
ab-	ducts
{ b	d V k t s
ab-	dul
{ b	d u: l
ab-	ject
{ b	dZ e k t
ab-	nor-	ma-	lly
{ b	n O@	m V	l i:
ab-	ra
Q b	r V
ab-	ra-	ca-	da-	bra
{ b	r V	k V	d { b	r V
ab-	ra-	ham
eI b	r V	h { m
ab-	ra-	ham-	sen
{ b	r V	h { m	s V n
ab-	ra-	hams
eI b	r V	h { m z
ab-	ra-	mo
Q b	r Q	m @U
ab-	ra-	sion
V b	r eI	Z V n
ab-	ra-	sions
V b	r eI	Z V n z
ab-	ra-	sive
V b	r eI	s I v
ab-	ra-	sives
V b	r eI	s I v z
ab-	ram
V b	r { m
ab-	ram-	son
eI b	r V m	s V n
ab-	rams
eI b	r V m z
ab-	reast
V b	r e s t
ab-	ridge
V b	r I dZ
ab-	ridged
V b	r I dZ d
ab-	ril
V b	r I l
ab-	ro-	ga-	ted
{ b	r V	g eI	t V d
ab-	ro-	ga-	ting
{ b	r V	g eI	t I N
ab-	ro-	ga-	tion
{ b	r V	g eI	S V n
ab-	ro-	gate
{ b	r V	g eI t
ab-	road
V b	r O: d
ab-	rupt
V b	r V p t
ab-	rupt-	ly
V b	r V p	t l i:
ab-	rupt-	ness
V b	r V p	t n V s
ab-	sa-	lom
{ b	s V	l V m
ab-	sen-	ces
{ b	s V n	s V z
ab-	sen-	tee
{ b	s V n	t i:
ab-	sen-	tee-	i-	sm
{ b	s V n	t i:	I	z V m
ab-	sen-	tees
{ b	s V n	t i: z
ab-	sen-	tia
{ b	s e n	S V
ab-	sence
{ b	s V n s
ab-	sent
{ b	s V n t
ab-	shi-	er
{ b	S i:	@r
ab-	so-	lu-	ti-	sm
{ b	s V	l u:	t I	z V m
ab-	so-	lu-	tion
{ b	s V	l u:	S V n
ab-	so-	lu-	tist
{ b	s V	l u:	t V s t
ab-	so-	lute
{ b	s V	l u: t
ab-	so-	lute-	ly
{ b	s V	l u: t	l i:
ab-	so-	lute-	ness
{ b	s V	l u: t	n V s
ab-	so-	lutes
{ b	s V	l u: t s
ab-	sol-	ving
V b	z Q l	v I N
ab-	solve
V b	z Q l v
ab-	solved
V b	z Q l v d
ab-	solves
V b	z Q l v z
ab-	sor-	ben-	cy
V b	z O@	b V n	s i:
ab-	sor-	bent
V b	z O@	b V n t
ab-	sor-	ber
V b	z O@	b @r
ab-	sor-	bers
V b	z O@	b @r z
ab-	sor-	bing
V b	z O@	b I N
ab-	sorb
V b	z O@ b
ab-	sorbed
V b	z O@ b d
ab-	sorbs
V b	z O@ b z
ab-	sorp-	tion
V b	z O@ p	S V n
ab-	stai-	ning
V b	s t eI	n I N
ab-	stain
V b	s t eI n
ab-	stained
V b	s t eI n d
ab-	sten-	tion
V b	s t e n	tS V n
ab-	sten-	tions
V b	s t e n	tS V n z
ab-	sti-	nence
{ b	s t I	n V n s
ab-	sti-	nent
{ b	s t I	n V n t
ab-	sur-	di-	ties
V b	s @r	d I	t i: z
ab-	sur-	di-	ty
V b	s @r	d I	t i:
ab-	sur-	dist
V b	s @r	d I s t
ab-	surd
V b	s @r d
ab-	surd-	ly
V b	s @r d	l i:
abbe-	ville
{ b	v I l
abbs
{ b z
abd-	el
{ b	d e l
abe
eI b
abs-	cam
{ b	s k { m
abs-	cess
{ b	s e s
abst-	rac-	ted
{ b	s t r { k	t V d
abst-	rac-	tion
{ b	s t r { k	S V n
abst-	rac-	tions
{ b	s t r { k	S V n z
abst-	ract
{ b	s t r { k t
abst-	racts
{ b	s t r { k t s
abst-	ruse
V b	s t r u: s
abt
{ b t
ac-	ce-	ded
{ k	s i:	d V d
ac-	ce-	ding
{ k	s i:	d I N
ac-	ce-	le-	ra-	ted
{ k	s e	l @r	eI	t V d
ac-	ce-	le-	ra-	ting
{ k	s e	l @r	eI	t I N
ac-	ce-	le-	ra-	tion
{ k	s e	l @r	eI	S V n
ac-	ce-	le-	ra-	tor
{ k	s e	l @r	eI	t @r
ac-	ce-	le-	rant
{ k	s e	l @r	V n t
ac-	ce-	le-	rants
{ k	s e	l @r	V n t s
ac-	ce-	le-	rate
{ k	s e	l @r	eI t
ac-	ce-	le-	rates
{ k	s e	l @r	eI t s
ac-	ce-	le-	ro-	me-	ter
{ k	s e	l @r	Q	m V	t @r
ac-	ce-	le-	ro-	me-	ters
{ k	s e	l @r	Q	m V	t @r z
ac-	cede
{ k	s i: d
ac-	cedes
{ k	s i: d z
ac-	cel
V k	s e l
ac-	cen-	ted
{ k	s e n	t V d
ac-	cen-	ting
{ k	s e n	t I N
ac-	cen-	tu-	a-	ted
{ k	s e n	tS V	w eI	t V d
ac-	cen-	tu-	a-	ting
{ k	s e n	tS V	w eI	t I N
ac-	cen-	tu-	ate
V k	s e n	tS u:	eI t
ac-	cen-	tu-	ates
V k	s e n	tS u:	eI t s
ac-	cent
V k	s e n t
ac-	cents
{ k	s e n t s
ac-	cep-	ta-	bi-	li-	ty
V k	s e p	t V	b I	l V	t i:
ac-	cep-	ta-	ble
{ k	s e p	t V	b V l
ac-	cep-	tan-	ces
{ k	s e p	t V n	s V z
ac-	cep-	tance
{ k	s e p	t V n s
ac-	cep-	ted
{ k	s e p	t V d
ac-	cep-	ting
{ k	s e p	t I N
ac-	cept
{ k	s e p t
ac-	cepts
{ k	s e p t s
ac-	ces-	si-	bi-	li-	ty
{ k	s e	s I	b I	l I	t i:
ac-	ces-	si-	ble
{ k	s e	s I	b V l
ac-	ces-	sing
{ k	s e	s I N
ac-	ces-	sion
V k	s e	S V n
ac-	ces-	so-	ries
{ k	s e	s @r	i: z
ac-	ces-	so-	rize
{ k	s e	s @r	aI z
ac-	ces-	so-	rized
{ k	s e	s @r	aI z d
ac-	ces-	so-	ry
{ k	s e	s @r	i:
ac-	cess
{ k	s e s
ac-	cessed
{ k	s e s t
ac-	ci-	den-	tal
{ k	s I	d e n	t V l
ac-	ci-	den-	tal-	ly
{ k	s I	d e n	t V	l i:
ac-	ci-	dent
{ k	s I	d V n t
ac-	ci-	dent-	ly
{ k	s I	d V n	t l i:
ac-	ci-	dents
{ k	s I	d V n t s
ac-	ci-	dent's
{ k	s I	d V n t s
ac-	clai-	ming
V k	l eI	m I N
ac-	claim
V k	l eI m
ac-	claimed
V k	l eI m d
ac-	cli-	ma-	ted
{ k	l I	m eI	t V d
ac-	cli-	ma-	tion
{ k	l I	m eI	S V n
ac-	cli-	mate
{ k	l I	m eI t
ac-	co-	lade
{	k V	l eI d
ac-	co-	lades
{	k V	l eI d z
ac-	com-	mo-	da-	ted
V	k Q	m V	d eI	t V d
ac-	com-	mo-	da-	ting
V	k Q	m V	d eI	t I N
ac-	com-	mo-	da-	tion
V	k Q	m V	d eI	S V n
ac-	com-	mo-	da-	tions
V	k Q	m V	d eI	S V n z
ac-	com-	mo-	da-	tive
V	k Q	m V	d eI	t I v
ac-	com-	mo-	date
V	k Q	m V	d eI t
ac-	com-	mo-	dates
V	k Q	m V	d eI t s
ac-	com-	pa-	nied
V	k V m	p V	n i: d
ac-	com-	pa-	nies
V	k V m	p V	n i: z
ac-	com-	pa-	nist
V	k V m	p V	n V s t
ac-	com-	pa-	ny
V	k V m	p V	n i:
ac-	com-	pa-	ny-	ing
V	k V m	p V	n i:	I N
ac-	com-	pli
Q	k Q m	p l i:
ac-	comp-	li-	ces
V	k Q m	p l V	s V z
ac-	comp-	li-	shes
V	k Q m	p l I	S V z
ac-	comp-	li-	shing
V	k Q m	p l I	S I N
ac-	comp-	lice
V	k Q m	p l V s
ac-	comp-	lish
V	k Q m	p l I S
ac-	comp-	lish-	ment
V	k Q m	p l I S	m V n t
ac-	comp-	lish-	ments
V	k Q m	p l I S	m V n t s
ac-	comp-	lished
V	k Q m	p l I S t
ac-	cor-	dance
V	k O@	d V n s
ac-	cor-	ded
V	k O@	d V d
ac-	cor-	di-	on
V	k O@	d i:	V n
ac-	cor-	di-	ons
V	k O@	d i:	V n z
ac-	cor-	ding
V	k O@	d I N
ac-	cor-	ding-	ly
V	k O@	d I N	l i:
ac-	cord
V	k O@ d
ac-	cords
V	k O@ d z
ac-	cord's
V	k O@ d z
ac-	cos-	ted
V	k Q s	t V d
ac-	cos-	ting
V	k Q s	t I N
ac-	cost
V	k O: s t
ac-	cou-	ter-	ment
V	k u:	t @r	m V n t
ac-	cou-	ter-	ments
V	k u:	t @r	m V n t s
ac-	coun-	ta-	bi-	li-	ty
V	k aU n	t V	b I	l V	t i:
ac-	coun-	ta-	ble
V	k aU n	t V	b V l
ac-	coun-	tan-	cy
V	k aU n	t V n	s i:
ac-	coun-	tant
V	k aU n	t V n t
ac-	coun-	tants
V	k aU n	t V n t s
ac-	coun-	tant's
V	k aU n	t V n t s
ac-	coun-	ted
V	k aU n	t V d
ac-	coun-	ting
V	k aU n	t I N
ac-	count
V	k aU n t
ac-	counts
V	k aU n t s
ac-	count's
V	k aU n t s
ac-	cre-	di-	ta-	tion
V k	r e	d V	t eI	S V n
ac-	cre-	di-	ta-	tions
V k	r e	d V	d eI	S V n z
ac-	cre-	di-	ted
V k	r e	d V	t V d
ac-	cre-	dit
V k	r e	d V t
ac-	cre-	tion
V k	r i:	S V n
ac-	cru-	al
V k	r u:	V l
ac-	cru-	als
V k	r u:	V l z
ac-	cru-	ing
V k	r u:	I N
ac-	crue
V k	r u:
ac-	crued
V k	r u: d
ac-	crues
V k	r u: z
ac-	cu-	mu-	la-	ted
V k	j u: m	j V	l eI	t V d
ac-	cu-	mu-	la-	ting
V k	j u: m	j V	l eI	t I N
ac-	cu-	mu-	la-	tion
V k	j u: m	j V	l eI	S V n
ac-	cu-	mu-	la-	tions
V k	j u: m	j V	l eI	S V n z
ac-	cu-	mu-	la-	tive
V k	j u: m	j V	l eI	t I v
ac-	cu-	mu-	la-	tive-	ly
V k	j u: m	j V	l eI	t I v	l i:
ac-	cu-	mu-	la-	tor
V k	j u: m	j V	l eI	t @r
ac-	cu-	mu-	la-	tors
V k	j u: m	j V	l eI	t @r z
ac-	cu-	mu-	late
V k	j u: m	j V	l eI t
ac-	cu-	mu-	lates
V k	j u: m	j V	l eI t s
ac-	cu-	ra-	cies
{ k	j @r	V	s i: z
ac-	cu-	ra-	cy
{ k	j @r	V	s i:
ac-	cu-	rate
{ k	j @r	V t
ac-	cu-	rate-	ly
{ k	j @r	V t	l i:
ac-	cu-	sa-	tion
{ k	j V	z eI	S V n
ac-	cu-	sa-	tions
{ k	j V	z eI	S V n z
ac-	cu-	sa-	tive
V k	j u:	z V	t I v
ac-	cu-	sa-	to-	ry
V k	j u:	z V	t O@	i:
ac-	cu-	ser
V k	j u:	z @r
ac-	cu-	sers
V k	j u:	z @r z
ac-	cu-	ses
V k	j u:	z V z
ac-	cu-	sing
V k	j u:	z I N
ac-	cu-	sing-	ly
V k	j u:	z I N	l i:
ac-	cus-	tom
V	k V s	t V m
ac-	cus-	tomed
V	k V s	t V m d
ac-	cuse
V k	j u: z
ac-	cused
V k	j u: z d
ac-	know-	led-	gea-	ble
{ k	n Q	l I	dZ V	b V l
ac-	know-	led-	ges
{ k	n Q	l I	dZ V z
ac-	know-	led-	ging
{ k	n Q	l I	dZ I N
ac-	know-	ledg-	ment
{ k	n Q	l I dZ	m V n t
ac-	know-	ledge-	ment
{ k	n Q	l I dZ	m V n t
ac-	know-	ledged
{ k	n Q	l I dZ d
ac-	me
{ k	m i:
ac-	me's
{ k	m i: z
ac-	ne
{ k	n i:
ac-	qua-	vi-	va
Q k	w Q	v i:	v V
ac-	quain-	tan-	ces
V k	w eI n	t V n	s V z
ac-	quain-	tance
V k	w eI n	t V n s
ac-	quain-	tance-	ship
V k	w eI n	t V n	s S V p
ac-	quain-	ted
V k	w eI n	t V d
ac-	quaint
V k	w eI n t
ac-	qui-	e-	scence
{ k	w i:	e	s V n s
ac-	qui-	e-	scing
{ k	w i:	e	s I N
ac-	qui-	esce
{ k	w i:	e s
ac-	qui-	esced
{ k	w i:	e s t
ac-	qui-	r-	er
V k	w aI	@r	@r
ac-	qui-	r-	ers
V k	w aI	@r	@r z
ac-	qui-	re
V k	w aI	@r
ac-	qui-	red
V k	w aI	@r d
ac-	qui-	res
V k	w aI	@r z
ac-	qui-	ring
V k	w aI	r I N
ac-	qui-	si-	tion
{ k	w I	z I	S V n
ac-	qui-	si-	tions
{ k	w I	z I	S V n z
ac-	qui-	si-	tion's
{ k	w I	z I	S V n z
ac-	qui-	si-	tive
V k	w I	z I	t I v
ac-	quit
V k	w I t
ac-	quit-	tal
V k	w I	t V l
ac-	quit-	tals
V k	w I	t V l z
ac-	quit-	ted
V k	w I	t V d
ac-	quit-	ting
V k	w I	t I N
ac-	quits
V k	w I t s
ac-	reage
eI k	r V dZ
ac-	res
eI	k @r z
ac-	ri-	mo-	ni-	ous
{ k	r I	m @U	n i:	V s
ac-	ri-	mo-	ny
{ k	r I	m @U	n i:
ac-	rid
{ k	r I d
ac-	ro-	ba-	tic
{ k	r V	b {	t I k
ac-	ro-	ba-	tics
{ k	r V	b {	t I k s
ac-	ro-	bat
{ k	r V	b { t
ac-	ro-	bats
{ k	r V	b { t s
ac-	ro-	nym
{ k	r V	n V m
ac-	ro-	nyms
{ k	r V	n V m z
ac-	ro-	po-	lis
V k	r Q	p V	l V s
ac-	ross
V k	r O: s
ac-	ry-	lic
V k	r I	l I k
ac-	ry-	lics
V k	r I	l I k s
ac-	ted
{ k	t V d
ac-	ti-	ni-	di-	a
{ k	t I	n I	d i:	V
ac-	ti-	nide
{ k	t I	n aI d
ac-	ti-	va-	ted
{ k	t I	v eI	t V d
ac-	ti-	va-	ting
{ k	t I	v eI	t I N
ac-	ti-	va-	tion
{ k	t I	v eI	S V n
ac-	ti-	va-	tor
{ k	t I	v eI	t @r
ac-	ti-	vase
{ k	t I	v eI z
ac-	ti-	vate
{ k	t I	v eI t
ac-	ti-	vates
{ k	t I	v eI t s
ac-	ti-	vi-	sm
{ k	t I	v I	z V m
ac-	ti-	vi-	ties
{ k	t I	v I	t i: z
ac-	ti-	vi-	ty
{ k	t I	v I	t i:
ac-	ti-	vist
{ k	t I	v I s t
ac-	ti-	vists
{ k	t V	v I s t s
ac-	tin
{ k	t I n
ac-	ting
{ k	t I N
ac-	tio-	na-	ble
{ k	S V	n V	b V l
ac-	tion
{ k	S V n
ac-	tions
{ k	S V n z
ac-	tion's
{ k	S V n z
ac-	tive
{ k	t I v
ac-	tive-	ly
{ k	t I v	l i:
ac-	tives
{ k	t I v z
ac-	ton
{ k	t V n
ac-	tor
{ k	t @r
ac-	tors
{ k	t @r z
ac-	tor's
{ k	t @r z
ac-	tors'
{ k	t @r z
ac-	tu-	a-	li-	ty
{ k	tS V	w {	l V	t i:
ac-	tu-	a-	lize
{ k	tS V	w V	l aI z
ac-	tu-	a-	ri-	al
{ k	tS V	w e@	i:	V l
ac-	tu-	a-	ries
{ k	tS V	w e@	i: z
ac-	tu-	a-	ry
{ k	tS V	w e@	i:
ac-	tu-	a-	tor
{ k	t j u:	eI	t @r
ac-	tu-	a-	tors
{ k	t j u:	eI	t @r z
ac-	tu-	al
{ k	tS V	w V l
ac-	tu-	al-	ly
{ k	tS V	w V	l i:
ac-	tu-	ate
{ k	tS V	w eI t
ac-	tus
{ k	t V s
ace
eI s
ache
eI k
aches
eI k s
ack
{ k
ack-	ley
{ k	l i:
ack-	man
{ k	m V n
ack-	now-	ledge
{ k	n Q	l I dZ
act
{ k t
act-	res-	ses
{ k	t r V	s V z
act-	res-	s's
{ k	t r V	s V z
act-	ress
{ k	t r V s
acts
{ k t s
act's
{ k t s
ad
{ d
ad-	di-	son's
{	d I	s V n z
ad-	di-	tio-	nal
V	d I	S V	n V l
ad-	di-	tio-	nal-	ly
V	d I	S V	n V	l i:
ad-	di-	tion
V	d I	S V n
ad-	di-	tions
V	d I	S V n z
ad-	di-	tive
{	d I	t I v
ad-	di-	tives
{	d I	t I v z
ad-	dic-	tion
V	d I k	S V n
ad-	dict
V	d I k t
ad-	dle
{	d V l
ad-	dled
{	d V l d
ad-	dy
{	d i:
ad-	ger
{	dZ @r
ad-	ham
{ d	h { m
ad-	he-	rence
V d	h I@	V n s
ad-	he-	rent
V d	h I@	V n t
ad-	he-	rents
{ d	h I@	V n t s
ad-	he-	ring
V d	h I@	I N
ad-	he-	sive
{ d	h i:	s I v
ad-	he-	sives
{ d	h i:	s I v z
ad-	here
V d	h I@
ad-	hered
{ d	h I@ d
ad-	heres
V d	h I@ z
ad-	hoc
{ d	h Q k
ad-	ja-	cent
V	dZ eI	s V n t
ad-	jec-	tive
{	dZ I k	t I v
ad-	jec-	tives
{	dZ I k	t I v z
ad-	joi-	ning
V	dZ OI	n I N
ad-	join
V	dZ OI n
ad-	joins
V	dZ OI n z
ad-	jour-	ning
V	dZ @r	n I N
ad-	journ
V	dZ @r n
ad-	journ-	ment
V	dZ @r n	m V n t
ad-	journed
V	dZ @r n d
ad-	journs
V	dZ @r n z
ad-	ju-	di-	ca-	ted
V	dZ u:	d V	k eI	t V d
ad-	ju-	di-	ca-	ting
V	dZ u:	d I	k eI	t I N
ad-	ju-	di-	ca-	tion
V	dZ u:	d V	k eI	S V n
ad-	ju-	di-	cate
V	dZ u:	d I	k eI t
ad-	ju-	tant
{	dZ V	t V n t
ad-	judge
V	dZ V dZ
ad-	judged
V	dZ V dZ d
ad-	junct
{	dZ V N k t
ad-	juncts
{	dZ V N k t s
ad-	jus-	ta-	ble
V	dZ V s	t V	b V l
ad-	jus-	ted
V	dZ V s	t V d
ad-	jus-	ter
V	dZ V s	t @r
ad-	jus-	ters
V	dZ V s	t @r z
ad-	jus-	ting
V	dZ V s	t I N
ad-	just
V	dZ V s t
ad-	just-	ment
V	dZ V s	t m V n t
ad-	just-	ments
V	dZ V s	t m V n t s
ad-	justs
V	dZ V s t s
ad-	kins
{ d	k I n z
ad-	la-	i
Q d	l Q	i:
ad-	ler
{ d	l @r
ad-	ley
{ d	l i:
ad-	lib
{ d	l I b
ad-	man
{ d	m V n
ad-	men
{ d	m V n
ad-	mi-	nis-	te-	ring
{ d	m I	n I s	t @r	I N
ad-	mi-	nis-	ter
V d	m I	n V s	t @r
ad-	mi-	nis-	tered
V d	m I	n V s	t @r d
ad-	mi-	nis-	ters
{ d	m I	n I s	t @r z
ad-	mi-	nist-	ra-	ting
V d	m I	n I s	t r eI	t I N
ad-	mi-	nist-	ra-	tion
{ d	m I	n I s	t r eI	S V n
ad-	mi-	nist-	ra-	tions
{ d	m I	n I s	t r eI	S V n z
ad-	mi-	nist-	ra-	tion's
{ d	m I	n I s	t r eI	S V n z
ad-	mi-	nist-	ra-	tive
V d	m I	n I s	t r eI	t I v
ad-	mi-	nist-	ra-	tive-	ly
{ d	m I	n I s	t r eI	t I v	l i:
ad-	mi-	nist-	ra-	tor
V d	m I	n I s	t r eI	t @r
ad-	mi-	nist-	ra-	tors
{ d	m I	n I s	t r eI	t @r z
ad-	mi-	nist-	rate
{ d	m I	n I s	t r eI t
ad-	mi-	ra-	ble
{ d	m @r	V	b V l
ad-	mi-	ra-	tion
{ d	m @r	eI	S V n
ad-	mi-	ra-	tions
{ d	m @r	eI	S V n s
ad-	mi-	rab-	ly
{ d	m @r	V b	l i:
ad-	mi-	ral
{ d	m @r	V l
ad-	mi-	ral-	ty
{ d	m @r	V l	t i:
ad-	mi-	rals
{ d	m @r	V l z
ad-	mi-	ral's
{ d	m @r	V l z
ad-	mi-	red
V d	m aI	@r d
ad-	mi-	rer
{ d	m aI	r @r
ad-	mi-	rers
V d	m aI	r @r z
ad-	mi-	ring
{ d	m aI	r I N
ad-	mi-	ring-	ly
{ d	m aI	r I N	l i:
ad-	mire
{ d	m aI r
ad-	mires
{ d	m aI r z
ad-	mis-	si-	bi-	li-	ty
V d	m I	s V	b I	l V	t i:
ad-	mis-	si-	ble
V d	m I	s V	b V l
ad-	mis-	sion
{ d	m I	S V n
ad-	mis-	sions
{ d	m I	S V n z
ad-	mit
V d	m I t
ad-	mit-	tance
V d	m I	t V n s
ad-	mit-	ted
V d	m I	t V d
ad-	mit-	ted-	ly
{ d	m I	t V d	l i:
ad-	mit-	ting
{ d	m I	t I N
ad-	mits
V d	m I t s
ad-	mo-	ni-	shes
{ d	m Q	n I	S V z
ad-	mo-	ni-	shing
{ d	m Q	n I	S I N
ad-	mo-	ni-	tion
{ d	m V	n I	S V n
)"
R"(ad-	mo-	ni-	tions
{ d	m V	n I	S V n z
ad-	mo-	nish
{ d	m Q	n I S
ad-	mo-	nish-	ment
{ d	m Q	n I S	m e n t
ad-	mo-	nished
V d	m Q	n I S t
ad-	nan
{ d	n V n
ad-	re-	a
Q d	r i:	V
ad-	re-	na-	lin
V d	r e	n V	l V n
ad-	re-	na-	line
V d	r e	n V	l V n
ad-	re-	nal
V d	r i:	n V l
ad-	ri-	a
Q d	r i:	V
ad-	ri-	a-	na
eI d	r i:	{	n V
ad-	ri-	a-	no
Q d	r i:	Q	n @U
ad-	ri-	a-	tic
eI d	r i:	{	t I k
ad-	ri-	an
eI d	r i:	V n
ad-	ri-	enne
Q d	r i:	e n
ad-	riel
V d	r i: l
ad-	rift
V d	r I f t
ad-	roit
V d	r OI t
ad-	roit-	ly
V d	r OI t	l i:
ad-	van-	cer
V d	v { n	s @r
ad-	van-	cers
V d	v { n	s @r z
ad-	van-	ces
V d	v { n	s V z
ad-	van-	cing
V d	v { n	s I N
ad-	van-	ta-	geous
{ d	v V n	t eI	dZ V s
ad-	van-	ta-	ges
{ d	v { n	t I	dZ V z
ad-	van-	tage
{ d	v { n	t I dZ
ad-	van-	taged
{ d	v { n	t I dZ d
ad-	vance
V d	v { n s
ad-	vance-	ment
V d	v { n	s m V n t
ad-	vance-	ments
V d	v { n	s m V n t s
ad-	vanced
V d	v { n s t
ad-	vec-	tion
{ d	v e k	S V n
ad-	ven-	tist
{ d	v e n	t I s t
ad-	ven-	tists
{ d	v e n	t I s t s
ad-	ven-	tu-	rer
{ d	v e n	tS @r	@r
ad-	ven-	tu-	rers
{ d	v e n	tS @r	@r z
ad-	ven-	tu-	ri-	sm
{ d	v e n	tS @r	I	z V m
ad-	ven-	tu-	rous
{ d	v e n	tS @r	V s
ad-	ven-	ture
{ d	v e n	tS @r
ad-	ven-	ture-	some
{ d	v e n	tS @r	s V m
ad-	ven-	tures
{ d	v e n	tS @r z
ad-	vent
{ d	v e n t
ad-	ver-	bi-	al
{ d	v @r	b i:	V l
ad-	ver-	sa-	ri-	al
{ d	v @r	s e@	i:	V l
ad-	ver-	sa-	ries
{ d	v @r	s e@	i: z
ad-	ver-	sa-	ry
{ d	v @r	s e@	i:
ad-	ver-	si-	ty
{ d	v @r	s I	t i:
ad-	ver-	ti-	ser
{ d	v @r	t aI	z @r
ad-	ver-	ti-	sers
{ d	v @r	t aI	z @r z
ad-	ver-	ti-	ser's
{ d	v @r	t aI	z @r z
ad-	ver-	ti-	ses
{ d	v @r	t aI	z V z
ad-	ver-	ti-	sing
{ d	v @r	t aI	z I N
ad-	ver-	ti-	sing's
{ d	v @r	t aI	z I N z
ad-	ver-	tise
{ d	v @r	t aI z
ad-	ver-	tise-	ment
V d	v @r	t V z	m V n t
ad-	ver-	tise-	ments
{ d	v @r	t aI z	m V n t s
ad-	ver-	tised
{ d	v @r	t aI z d
ad-	ver-	to-	ri-	al
{ d	v @r	t O@	i:	V l
ad-	ver-	to-	ri-	als
{ d	v @r	t O@	i:	V l z
ad-	verb
{ d	v @r b
ad-	verbs
{ d	v @r b z
ad-	verse
{ d	v @r s
ad-	verse-	ly
{ d	v @r s	l i:
ad-	vi-	sa-	bi-	li-	ty
{ d	v aI	z V	b I	l V	t i:
ad-	vi-	sa-	ble
V d	v aI	z V	b V l
ad-	vi-	sed-	ly
{ d	v aI	z V d	l i:
ad-	vi-	ser
{ d	v aI	z @r
ad-	vi-	sers
{ d	v aI	z @r z
ad-	vi-	ser's
V d	v aI	z @r z
ad-	vi-	ses
{ d	v aI	z V z
ad-	vi-	sing
{ d	v aI	z I N
ad-	vi-	so-	ries
V d	v aI	z @r	i: z
ad-	vi-	so-	ry
{ d	v aI	z @r	i:
ad-	vi-	sor
{ d	v aI	z @r
ad-	vi-	sors
{ d	v aI	z @r z
ad-	vice
{ d	v aI s
ad-	vil
{ d	v I l
ad-	vil's
{ d	v I l z
ad-	vise
{ d	v aI z
ad-	vise-	ment
V d	v aI z	m V n t
ad-	vised
{ d	v aI z d
ad-	vo-	ca-	cy
{ d	v V	k V	s i:
ad-	vo-	ca-	ted
{ d	v V	k eI	t V d
ad-	vo-	ca-	ting
{ d	v V	k eI	t I N
ad-	vo-	ca-	tion
{ d	v V	k eI	S V n
ad-	vo-	cate
{ d	v V	k V t
ad-	vo-	cates
{ d	v V	k V t s
add-	res-	sa-	ble
V d	r e	s V	b V l
add-	res-	see
{ d	r e	s i:
add-	res-	ses
{ d	r V	s V z
add-	res-	sing
V d	r e	s I N
add-	ress
{ d	r e s
add-	ressed
V d	r e s t
adds
{ d z
ade
eI d
ads
{ d z
ad's
{ d z
adz
{ d z
ae
eI
ae-	ge-	an
I	dZ i:	V n
ae-	gis
i:	dZ I s
ae-	ne-	as
{	n i:	V s
ae-	ri-	al
e@	i:	V l
ae-	ro
e@	@U
ae-	ro-	ba-	tic
e@	V	b {	t I k
ae-	ro-	ba-	tics
e@	V	b {	t I k s
ae-	ro-	bic
e@	@U	b I k
ae-	ro-	bical-	ly
e@	@U	b I k	l i:
ae-	ro-	bics
@r	@U	b I k s
ae-	ro-	nau-	ti-	cal
e@	@U	n Q	t I	k V l
ae-	ro-	nau-	tic
e@	@U	n Q	t I k
ae-	ro-	nau-	tics
e@	V	n O:	t I k s
ae-	ro-	sol
e@	V	s Q l
ae-	ro-	sols
e@	V	s Q l z
ae-	rod-	rome
e@	V d	r @U m
ae-	ros-	pa-	ce's
e@	@U s	p eI	s V z
ae-	ros-	pace
e@	@U s	p eI s
ae-	ros-	tat
e@	@U s	t { t
ae-	ros-	tats
e@	@U s	t { t s
ae-	sop
i:	s Q p
ae-	sop's
i:	s Q p s
aer
e@
aes-	the-	tic
e s	T e	t I k
aes-	the-	tical-	ly
e s	T e	t I k	l i:
aes-	the-	tics
e s	T e	t I k s
aes-	thete
e s	T i: t
aet-	na
e t	n V
aet-	na's
e t	n V z
af-	fa-	ble
{	f V	b V l
af-	fair
V	f e@
af-	fairs
V	f e@ z
af-	fe-	rent
{	f @r	V n t
af-	fec-	ta-	tion
{	f e k	t eI	S V n
af-	fec-	ted
V	f e k	t V d
af-	fec-	ting
V	f e k	t I N
af-	fec-	tio-	nate
V	f e k	S V	n V t
af-	fec-	tio-	nate-	ly
V	f e k	S V	n V t	l i:
af-	fec-	tion
V	f e k	S V n
af-	fec-	tions
V	f e k	S V n z
af-	fec-	tive
V	f e k	t I v
af-	fec-	tive-	ly
V	f e k	t I v	l i:
af-	fect
V	f e k t
af-	fects
V	f e k t s
af-	fi-	ant
{	f i:	V n t
af-	fi-	da-	vit
{	f I	d eI	v I t
af-	fi-	da-	vits
{	f I	d eI	v I t s
af-	fi-	li-	a-	ted
V	f I	l i:	eI	t V d
af-	fi-	li-	a-	ting
V	f I	l i:	eI	t I N
af-	fi-	li-	a-	tion
V	f I	l i:	eI	S V n
af-	fi-	li-	a-	tions
V	f I	l i:	eI	S V n z
af-	fi-	li-	ate
V	f I	l i:	eI t
af-	fi-	li-	ates
V	f I	l i:	V t s
af-	fi-	li-	ate's
V	f I	l i:	eI t s
af-	fi-	ni-	ties
V	f I	n V	t i: z
af-	fi-	ni-	ty
V	f I	n V	t i:
af-	for-	da-	bi-	li-	ty
V	f O@	d V	b I	l V	t i:
af-	for-	da-	ble
V	f O@	d V	b V l
af-	for-	ded
V	f O@	d V d
af-	for-	ding
V	f O@	d I N
af-	ford
V	f O@ d
af-	fords
V	f O@ d z
af-	gha-	ni
{ f	g Q	n i:
af-	gha-	nis
{ f	g {	n i: z
af-	gha-	ni's
{ f	g {	n i: z
af-	gha-	nis-	tan
{ f	g {	n I s	t { n
af-	gha-	nis-	tan's
{ f	g {	n I s	t { n z
af-	ghan
{ f	g { n
af-	ghans
{ f	g { n z
af-	la-	to-	xin
{ f	l V	t Q k	s V n
af-	lame
V f	l eI m
af-	loat
V f	l @U t
af-	lut-	ter
V f	l V	t @r
af-	raid
V f	r eI d
af-	resh
V f	r e S
af-	ri-	ca
{ f	r I	k V
af-	ri-	ca-	nist
{ f	r I	k V	n I s t
af-	ri-	ca-	nize
{ f	r I	k V	n aI z
af-	ri-	ca-	nized
{ f	r I	k V	n aI z d
af-	ri-	can
{ f	r I	k V n
af-	ri-	cans
{ f	r I	k V n z
af-	ri-	ca's
{ f	r I	k V z
af-	ri-	ka-	ner
{ f	r I	k Q	n @r
af-	ri-	ka-	ner-	dom
{ f	r I	k Q	n @r	d V m
af-	ri-	ka-	ners
{ f	r I	k Q	n @r z
af-	ri-	kaans
{ f	r I	k Q n z
af-	ro
{ f	r @U
af-	shar
{ f	S @r
af-	te-	rall
{ f	t @r	Q l
af-	ter
{ f	t @r
af-	ter-	bur-	ner
{ f	t @r	b @r	n @r
af-	ter-	bur-	ners
{ f	t @r	b @r	n @r z
af-	ter-	ef-	fect
{ f	t @r	V	f e k t
af-	ter-	ef-	fects
{ f	t @r	V	f e k t s
af-	ter-	glow
{ f	t @r g	l @U
af-	ter-	i-	mage
{ f	t @r	I	m I dZ
af-	ter-	life
{ f	t @r	l aI f
af-	ter-	mar-	ket
{ f	t @r	m Q@	k V t
af-	ter-	math
{ f	t @r	m { T
af-	ter-	noon
{ f	t @r	n u: n
af-	ter-	noons
{ f	t @r	n u: n z
af-	ter-	noon's
{ f	t @r	n u: n z
af-	ter-	shock
{ f	t @r	S Q k
af-	ter-	shocks
{ f	t @r	S Q k s
af-	ter-	taste
{ f	t @r	t eI s t
af-	ter-	tax
{ f	t @r	t { k s
af-	ter-	thought
{ f	t @r	T Q t
af-	ter-	ward
{ f	t @r	w @r d
af-	ter-	wards
{ f	t @r	w @r d z
aff-	lic-	ted
V f	l I k	t V d
aff-	lic-	ting
V f	l I k	t I N
aff-	lic-	tion
V f	l I k	S V n
aff-	lic-	tions
V f	l I k	S V n z
aff-	lict
V f	l I k t
aff-	licts
V f	l I k t s
aff-	lu-	ence
{ f	l u:	V n s
aff-	lu-	ent
{ f	l u:	V n t
aff-	ri-	ca-	tion
{ f	r I	k eI	S V n
aff-	ri-	cate
{ f	r I	k V t
aff-	ri-	cates
{ f	r I	k V t s
aff-	ron-	ted
V f	r V n	t V d
aff-	ront
V f	r V n t
aff-	ronts
V f	r V n t s
aft
{ f t
ag
{ g
ag-	gar-	wal
V	g Q@	w V l
ag-	gie
{	g i:
ag-	gies
{	g i: z
ag-	glo-	me-	ra-	tion
V g	l Q	m @r	eI	S V n
ag-	glo-	me-	rate
V g	l Q	m @r	eI t
ag-	glu-	ti-	nate
V g	l u:	t V	n eI t
ag-	gra-	va-	ted
{ g	r V	v eI	t V d
ag-	gra-	va-	ting
{ g	r V	v eI	t I N
ag-	gra-	va-	tion
{ g	r V	v eI	S V n
ag-	gra-	vate
{ g	r V	v eI t
ag-	gra-	vates
{ g	r V	v eI t s
ag-	gran-	di-	zing
{ g	r V n	d aI	z I N
ag-	gran-	dize
V g	r { n	d aI z
ag-	gran-	dize-	ment
{ g	r V n	d aI z	m V n t
ag-	gre-	ga-	ted
{ g	r V	g eI	t V d
ag-	gre-	gate
{ g	r V	g V t
ag-	gre-	gates
{ g	r V	g V t s
ag-	gres-	si-	vi-	ty
V g	r e	s I	v V	t i:
ag-	gres-	sion
V g	r e	S V n
ag-	gres-	sions
V g	r e	S V n z
ag-	gres-	sive
V g	r e	s I v
ag-	gres-	sive-	ly
V g	r e	s I v	l i:
ag-	gres-	sive-	ness
V g	r e	s I v	n V s
ag-	gres-	sor
V g	r e	s @r
ag-	gres-	sors
V g	r e	s @r z
ag-	gress
V g	r e s
ag-	grieve
V g	r i: v
ag-	grieved
V g	r i: v d
ag-	gy
{	g i:
ag-	leam
V g	l i: m
ag-	ler
{ g	l @r
ag-	lit-	ter
V g	l I	t @r
ag-	low
V g	l @U
ag-	na
{ g	n V
ag-	ne-	ta
Q g	n e	t V
ag-	nel-	la
{ g	n e	l V
ag-	nes
{ g	n V s
ag-	new
{ g	n u:
ag-	nos-	tic
{ g	n Q s	t I k
ag-	ra-	ri-	a-	ni-	sm
V g	r e@	i:	V	n I	z V m
ag-	ra-	ri-	an
V g	r e@	i:	V n
ag-	ree
V g	r i:
ag-	ree-	a-	ble
V g	r i:	V	b V l
ag-	ree-	ing
V g	r i:	I N
ag-	ree-	ment
V g	r i:	m V n t
ag-	ree-	ments
V g	r i:	m V n t s
ag-	ree-	ment's
V g	r i:	m V n t s
ag-	reed
V g	r i: d
ag-	rees
V g	r i: z
ag-	ri-	busi-	ness
{ g	r I	b I z	n V s
ag-	ri-	co-	la
{ g	r I	k @U	l V
ag-	ri-	cole
{ g	r I	k @U l
ag-	ri-	cul-	tu-	ra-	list
{ g	r I	k V l	tS @r	@	l I s t
ag-	ri-	cul-	tu-	ral
{ g	r I	k V l	tS @r	@ l
ag-	ri-	cul-	tu-	ral-	ly
{ g	r I	k V l	tS @r	@	l i:
ag-	ri-	cul-	ture
{ g	r I	k V l	tS @r
ag-	ri-	cul-	ture's
{ g	r I	k V l	tS @r z
ag-	round
V g	r aU n d
age
eI dZ
age-	less
eI dZ	l V s
aged
eI dZ d
ah
Q
ah-	ma-	di
Q	m Q	d i:
ah-	mad
Q	m Q d
ah-	med
Q	m V d
ah-	rendt
Q@	e n t
ah-	rens
Q@	e n z
ahh
Q
ahl
Q l
ahlg-	ren
Q l	g r e n
ahs
Q z
ai
aI
ai-	ded
eI	d V d
ai-	ding
eI	d I N
ai-	el-	lo
aI	e	l @U
ai-	ken
eI	k V n
ai-	le-	ron
eI	l @r	Q n
ai-	le-	rons
eI	l @r	Q n z
ai-	lee
eI	l i:
ai-	leen
aI	l i: n
ai-	ley
eI	l i:
ai-	ling
eI	l I N
ai-	mee
eI	m i:
ai-	ming
eI	m I N
ai-	res
e@	i: z
ai-	ring
e@	I N
ai-	ry
e@	i:
aid
eI d
aide
eI d
aides
eI d z
aide's
eI d z
aids
eI d z
ail
eI l
ail-	ment
eI l	m V n t
ail-	ments
eI l	m V n t s
ail-	sa
eI l	s V
ails
eI l z
aim
eI m
aim-	less
eI m	l V s
aim-	less-	ly
eI m	l V s	l i:
aime
eI m
aimed
eI m d
aims
eI m z
ains-	ley
eI n	s l i:
ains-	lie
eI n	z l i:
ains-	worth
eI n	s w @r T
ains-	worth's
eI n	z w @r T s
ain't
eI n t
air
e@
air-	ba-	ses
e@	b eI	s V z
air-	bag
e@	b { g
air-	bags
e@	b { g z
air-	base
e@	b eI s
air-	boat
e@	b @U t
air-	boats
e@	b @U t s
air-	borne
e@	b O@ n
air-	bu-	s's
e@	b V	s V z
air-	bus
e@	b V s
air-	craft
e@ k	r { f t
air-	crafts
e@ k	r { f t s
air-	craft's
e@ k	r { f t s
air-	crew
e@ k	r u:
air-	drop
e@ d	r Q p
air-	drops
e@ d	r Q p s
air-	fare
e@	f e@
air-	fares
e@	f e@ z
air-	field
e@	f i: l d
air-	fields
e@	f i: l d z
air-	flow
e@ f	l @U
air-	foil
e@	f OI l
air-	foils
e@	f OI l z
air-	force
e@	f O@ s
air-	frame
e@ f	r eI m
air-	freight
e@ f	r eI t
air-	glow
e@ g	l @U
air-	head
e@	h e d
air-	less
e@	l V s
air-	li-	a
e@	l i:	V
air-	li-	ner
e@	l aI	n @r
air-	li-	ners
e@	l aI	n @r z
air-	li-	ner's
e@	l aI	n @r z
air-	lie
e@	l i:
air-	lif-	ted
e@	l I f	t V d
air-	lif-	ting
e@	l I f	t I N
air-	lift
e@	l I f t
air-	lifts
e@	l I f t s
air-	line
e@	l aI n
air-	lines
e@	l aI n z
air-	line's
e@	l aI n z
air-	lock
e@	l O: k
air-	mail
e@	m eI l
air-	man
e@	m V n
air-	man's
e@	m V n z
air-	men
e@	m e n
air-	plane
e@ p	l eI n
air-	planes
e@ p	l eI n z
air-	plane's
e@ p	l eI n z
air-	po-	wer
e@	p aU	@r
air-	port
e@	p O@ t
air-	ports
e@	p O@ t s
air-	port's
e@	p O@ t s
air-	ship
e@	S I p
air-	ships
e@	S I p s
air-	space
e@ s	p eI s
air-	speed
e@ s	p i: d
air-	strike
e@ s	t r aI k
air-	strikes
e@ s	t r aI k s
air-	strip
e@ s	t r I p
air-	strips
e@ s	t r I p s
air-	tight
e@	t aI t
air-	time
e@	t aI m
air-	wave
e@	w eI v
air-	waves
e@	w eI v z
air-	way
e@	w eI
air-	ways
e@	w eI z
air-	way's
e@	w eI z
air-	wor-	thi-	ness
e@	w @r	D i:	n V s
air-	wor-	thy
e@	w @r	D i:
aire-	dale
e@	d eI l
aired
e@ d
airs
e@ z
air's
e@ z
ais
aI z
aisle
aI l
aisles
aI l z
ait-	ken
aI t	k V n
aix-	la-	cha-	pelle
aI k	s l V	S V	p e l
ak-	bar
{ k	b @r
ak-	ka-	di-	an
V	k eI	d i:	V n
ak-	ker-	man
{	k @r	m V n
ak-	re
{	k @r
ak-	ron
{ k	r V n
akc
{ k
ake
eI k
akst
{ k s t
al
{ l
al-	ba
{ l	b V
al-	ba-	core
{ l	b V	k O@
al-	ba-	ne-	se
Q l	b Q	n eI	z i:
al-	ba-	ni-	a
{ l	b eI	n i:	V
al-	ba-	ni-	an
{ l	b eI	n i:	V n
al-	ba-	ni-	ans
{ l	b eI	n i:	V n z
al-	ba-	ni-	a's
{ l	b eI	n i:	V z
al-	ba-	ny
O: l	b V	n i:
al-	ba-	ny's
O: l	b V	n i: z
al-	ban
Q l	b V n
al-	bans
{ l	b { n z
al-	bar-	ran
{ l	b {	r V n
al-	bat-	ros-	ses
{ l	b V t	r Q	s V z
al-	bat-	ross
{ l	b V t	r Q s
al-	be-	it
O: l	b i:	I t
al-	be-	marle
{ l	b V	m Q@ l
al-	bee
V l	b i:
al-	ben
O: l	b V n
al-	ber
{ l	b @r
al-	ber-	go
Q l	b e@	g @U
al-	ber-	ta
{ l	b @r	t V
al-	ber-	ti
Q l	b e@	t i:
al-	ber-	ti-	na
Q l	b @r	t i:	n V
al-	ber-	tine
{ l	b @r	t i: n
al-	ber-	to
{ l	b @r	t @U
al-	ber-	tus
{ l	b @r	t V s
al-	bers
O: l	b @r z
al-	bert
{ l	b @r t
al-	bert-	son
{ l	b @r t	s V n
al-	bert-	son's
{ l	b @r t	s V n z
al-	bert-	ville
{ l	b @r t	v I l
al-	berts
{ l	b @r t s
al-	bi-	na
Q l	b i:	n V
al-	bi-	no
{ l	b aI	n @U
al-	bi-	on
{ l	b i:	V n
al-	bie
O: l	b i:
al-	bin
{ l	b I n
al-	bo
{ l	b @U
al-	brecht
O: l	b r e k t
al-	bright
O: l	b r aI t
al-	bu-	min
{ l	b j u:	m @ n
al-	bu-	quer-	que
{ l	b V	k @r	k i:
al-	bu-	ry
{ l	b e@	i:
al-	bu-	te-	rol
{ l	b j u:	t @r	O: l
al-	bum
{ l	b V m
al-	bums
{ l	b V m z
al-	bum's
{ l	b V m z
al-	bus
{ l	b V s
al-	can
{ l	k { n
al-	can-	ta-	ra
Q l	k Q n	t Q@	V
al-	cat-	raz
{ l	k V t	r { z
al-	che-	mical-	ly
{ l	k e	m I k	l i:
al-	che-	mist
{ l	tS V	m V s t
al-	che-	my
{ l	k V	m i:
al-	ci-	na
Q l	tS i:	n V
al-	cide
{ l	s aI d
al-	cids
{ l	s I d z
al-	co
{ l	k @U
al-	co-	a
{ l	k @U	V
al-	co-	a's
{ l	k @U	V z
al-	co-	ho-	li-	sm
{ l	k V	h O:	l I	z V m
al-	co-	ho-	lic
{ l	k V	h Q	l I k
al-	co-	ho-	lics
{ l	k V	h Q	l I k s
al-	co-	hol
{ l	k V	h Q l
al-	cock
V l	k Q k
al-	con
V l	k Q n
al-	co's
{ l	k @U z
al-	cott
{ l	k Q t
al-	cove
{ l	k @U v
al-	coves
{ l	k @U v z
al-	der-	son
O: l	d @r	s V n
al-	di-	carb
O: l	d I	k Q@ b
al-	din
Q l	d i: n
al-	dis
Q l	d I s
al-	do
Q l	d @U
al-	do-	ra
Q l	d O@	V
al-	dus
Q l	d V s
al-	fa
{ l	f V
al-	fal-	fa
{ l	f { l	f V
al-	fa's
{ l	f V z
al-	fie
{ l	f i:
al-	fie-	ri
Q l	f I@	i:
al-	fin
{ l	f I n
al-	fon-	sin
{ l	f Q n	s I n
al-	fon-	so
{ l	f Q n	s @U
al-	fons
Q l	f @U n z
al-	fonse
{ l	f Q n s
al-	ford
{ l	f @r d
al-	gae
{ l	dZ i:
al-	gal
{ l	g V l
al-	gar
Q l	g Q@
al-	ge-	ri-	a
{ l	dZ I@	i:	V
al-	ge-	ri-	an
{ l	dZ I@	i:	V n
al-	ge-	ri-	ans
{ l	dZ i:	r i:	V n z
al-	ge-	ri-	a's
{ l	dZ i:	r i:	V z
al-	geb-	ra
{ l	dZ V b	r V
al-	geb-	ra-	ic
{ l	dZ V b	r eI	I k
al-	geb-	rai-	cal-	ly
{ l	dZ V b	r eI	I k	l i:
al-	ger
{ l	dZ @r
al-	ger-	non
{ l	dZ @r	n Q n
al-	gie
O: l	g i:
al-	giers
{ l	dZ I@ z
al-	go-	ma
{ l	g @U	m V
al-	go-	ri-	thm
{ l	g @r	I	D V m
al-	go-	ri-	thms
{ l	g @r	I	D V m z
al-	gol
{ l	g Q l
al-	gon-	qui-	an
{ l	g Q N	k i:	V n
al-	gon-	quin
{ l	g Q N	k w I n
al-	gui-	re
Q l	g w I@	eI
al-	gy
{ l	dZ i:
al-	ham-	bra
{ l	h { m	b r V
al-	ka-	hest
{ l	k V	h e s t
al-	ka-	li
{ l	k V	l aI
al-	ka-	li-	ni-	ty
{ l	k V	l I	n V	t i:
al-	ka-	lies
{ l	k V	l aI z
al-	ka-	line
{ l	k V	l aI n
al-	ka-	loi-	dal
{ l	k V	l OI	d V l
al-	ka-	loid
{ l	k V	l OI d
al-	ka-	loids
{ l	k V	l OI d z
al-	kanes
{ l	k eI n z
al-	kene
{ l	k i: n
al-	kenes
{ l	k i: n z
al-	la
Q	l V
al-	lah
Q	l V
al-	lain
V	l eI n
al-	lan
{	l V n
al-	lard
{	l @r d
al-	lay
V	l eI
al-	lay-	ing
V	l eI	I N
al-	layed
V	l eI d
al-	lays
V	l eI z
al-	le-	ga-	tion
{	l V	g eI	S V n
al-	le-	ga-	tions
{	l V	g eI	S V n z
al-	le-	ged-	ly
V	l e	dZ V d	l i:
al-	le-	ges
V	l e	dZ V z
al-	le-	gha-	ny
{	l V	g eI	n i:
al-	le-	ghe-	ny
{	l V	g eI	n i:
al-	le-	ghe-	ny's
{	l V	g eI	n i: z
al-	le-	gi-	an-	ces
{	l i:	dZ i:	{ n	s V z
al-	le-	ging
V	l e	dZ I N
al-	le-	go-	ri-	cal
{	l V	g O@	V	k V l
al-	le-	go-	ries
{	l V	g O@	i: z
al-	le-	go-	ry
{	l V	g O@	i:
al-	le-	gra
Q	l e g	r V
al-	le-	le
V	l e	l i:
al-	le-	les
V	l e	l i: z
al-	le-	lic
V	l e	l I k
al-	le-	mand
{	l V	m V n d
al-	le-	vi-	a-	ted
V	l i:	v i:	eI	t V d
al-	le-	vi-	a-	ting
V	l i:	v i:	eI	t I N
al-	le-	vi-	a-	tion
V	l i:	v i:	eI	S V n
al-	le-	vi-	ate
V	l i:	v i:	eI t
al-	le-	vi-	ates
V	l i:	v i:	eI t s
al-	lee
V	l i:
al-	leg-	ro
V	l e g	r @U
al-	lege
V	l e dZ
al-	leged
V	l e dZ d
al-	legi-	ance
V	l i:	dZ V n s
al-	len
{	l V n
al-	len-	dale
{	l V n	d eI l
al-	len-	de
Q	j e n	d eI
al-	len-	dorf
{	l V n	d O@ f
al-	len-	hurst
{	l V n	h @r s t
al-	len-	town
{	l V n	t aU n
al-	len-	wood
{	l V n	w U d
al-	lene
{	l i: n
al-	len's
{	l V n z
al-	ler
O:	l @r
al-	ler-	gen
{	l @r	dZ V n
al-	ler-	gens
{	l @r	dZ V n z
al-	ler-	gic
V	l @r	dZ I k
al-	ler-	gies
{	l @r	dZ i: z
al-	ler-	gist
{	l @r	dZ I s t
al-	ler-	gy
{	l @r	dZ i:
al-	ler-	ton
{	l @r	t V n
al-	ley-	way
{	l i:	w eI
al-	ley-	ways
{	l i:	w eI z
al-	leyne
{	l eI n
al-	leys
{	l i: z
al-	li
{	l i:
al-	li-	an-	ces
V	l aI	V n	s V z
al-	li-	an-	ce's
V	l aI	V n	s V z
al-	li-	ance
V	l aI	V n s
al-	li-	ant
V	l aI	V n t
al-	li-	ga-	tor
{	l I	g eI	t @r
al-	li-	ga-	tors
{	l I	g eI	t @r z
al-	li-	son
{	l I	s V n
al-	li-	son's
{	l I	s V n z
al-	li-	te-	ra-	tion
V	l I	t @r	eI	S V n
)"
R"(al-	li-	te-	ra-	tive
V	l I	t @r	V	t I v
al-	lie
{	l i:
al-	lied
V	l aI d
al-	lies
{	l aI z
al-	lin
V	l I n
al-	ling-	ham
O:	l I N	h { m
al-	lis
{	l I s
al-	lis-	ter
O:	l I s	t @r
al-	lo-	ca-	ted
{	l V	k eI	t V d
al-	lo-	ca-	ting
{	l V	k eI	t I N
al-	lo-	ca-	tion
{	l V	k eI	S V n
al-	lo-	ca-	tions
{	l V	k eI	S V n z
al-	lo-	ca-	tor
{	l V	k eI	t @r
al-	lo-	ca-	tors
{	l V	k eI	t @r z
al-	lo-	cate
{	l V	k eI t
al-	lo-	cates
{	l V	k eI t s
al-	lo-	morph
{	l V	m O@ f
al-	lo-	morphs
{	l V	m O@ f s
al-	lo-	pho-	nic
{	l V	f Q	n I k
al-	lo-	phone
{	l V	f @U n
al-	lo-	phones
{	l V	f @U n z
al-	lo-	ted
V	l Q	t V d
al-	lot
V	l Q t
al-	lot-	ment
V	l Q t	m V n t
al-	lot-	ments
V	l Q t	m V n t s
al-	lot-	rope
{	l V t	r @U p
al-	lot-	ropes
{	l V t	r @U p s
al-	lot-	ted
V	l Q	t V d
al-	lot-	ting
V	l Q	t I N
al-	lots
V	l Q t s
al-	lu-	sion
V	l u:	Z V n
al-	lu-	sions
V	l u:	Z V n z
al-	lu-	sive
V	l u:	s I v
al-	lu-	vi-	al
{	l u:	v i:	V l
al-	lu-	vi-	um
V	l u:	v i:	V m
al-	ly
{	l aI
al-	ly-	ing
{	l aI	I N
al-	ly-	son
{	l V	s V n
al-	lyn
{	l I n
al-	lys
{	l aI z
)"