R"(rice
r aI s
rice-	ville
r aI s	v I l
rich
r I tS
rich-	burg
r I tS	b @r g
rich-	field
r I tS	f i: l d
rich-	field's
r I tS	f i: l d z
rich-	ford
r I tS	f @r d
rich-	land
r I tS	l V n d
rich-	ly
r I tS	l i:
rich-	man
r I tS	m { n
rich-	mond
r I tS	m V n d
rich-	mond's
r I tS	m V n d z
rich-	ness
r I tS	n V s
rich-	ter
r I k	t @r
rich-	ton
r I tS	t V n
riche
r I tS
richts
r I k t s
rick
r I k
rick-	man
r I k	m V n
rick-	wood
r I k	w U d
ricks
r I k s
rick's
r I k s
rid
r I d
rid-	dance
r I	d V n s
rid-	den
r I	d V n
rid-	der
r I	d @r
rid-	der's
r I	d @r z
rid-	ding
r I	d I N
rid-	dle
r I	d V l
rid-	dled
r I	d V l d
rid-	dles
r I	d V l z
rid-	ges
r I	dZ V z
rid-	ge's
r I	dZ V s
rid-	ley
r I d	l i:
rid-	path
r I d	p { T
ridd-	ler
r I d	l @r
ride
r aI d
rides
r aI d z
ridg-	efield
r I dZ	f i: l d
ridg-	ley
r I dZ	l i:
ridg-	way
r I dZ	w eI
ridge
r I dZ
ridge-	crest
r I dZ	k r e s t
ridge-	ly
r I dZ	l i:
ridge-	way
r I dZ	w eI
ridge-	wood
r I dZ	w U d
ridged
r I dZ d
rids
r I d z
rie-	del
r i:	d V l
rie-	gel
r i:	g V l
rie-	ger
r i:	g @r
rie-	mann
r i:	m V n
riehl
r i: l
riel
r i: l
ries
r aI z
ries-	ling
r i: z	l I N
riess
r i: s
riet-	veld
r i: t	v e l d
rieves
r i: v z
rif-	fle
r I	f V l
rif-	kin
r I f	k I n
rif-	kin's
r I f	k I n z
rif-	ling
r aI f	l I N
rife
r aI f
riff
r I f
riff-	raff
r I f	r { f
riffs
r I f s
rift
r I f t
rifts
r I f t s
rig
r I g
rig-	by
r I g	b i:
rig-	don
r I g	d V n
rig-	ging
r I	g I N
rig-	gings
r I	g I N z
rig-	gins
r I	g I n z
rigg
r I g
rigged
r I g d
riggs
r I g z
righ-	ted
r aI	t V d
righ-	teous
r aI	tS V s
righ-	teous-	ly
r aI	tS V s	l i:
righ-	teous-	ness
r aI	tS V s	n V s
righ-	ter
r aI	t @r
righ-	tish
r aI	t I S
righ-	tist
r aI	t I s t
righ-	tists
r aI	t I s t s
righ-	ty
r aI	t i:
right
r aI t
right-	ful
r aI t	f V l
right-	ful-	ly
r aI t	f V	l i:
right-	han-	ded
r aI t	h { n	d V d
right-	hand
r aI t	h { n d
right-	ly
r aI t	l i:
right-	ness
r aI t	n V s
right-	ward
r aI t	w @r d
right-	win-	ger
r aI t	w I	N @r
right-	win-	gers
r aI t	w I	N @r z
right-	wing
r aI t	w I N
rights
r aI t s
rigs
r I g z
rigs-	by
r I g	z b i:
rik-	ki
r I	k i:
riks-	dag
r I k	s d { g
ril-	lette
r V	l e t
ril-	ling
r I	l I N
rile
r aI l
riled
r aI l d
riles
r aI l z
rill
r I l
rill's
r I l z
rim
r I m
rim-	mer
r I	m @r
rimes
r aI m z
rimmed
r I m d
rims
r I m z
rin-	con
r I N	k V n
rin-	g-	ler
r I N	g V	l @r
rin-	gel
r I N	g V l
rin-	ger
r I	N @r
rin-	gers
r I	N @r z
rin-	ging
r I	N I N
rin-	gle
r I N	g V l
rin-	go
r i: N	g @U
rin-	gold
r I N	g @U l d
rin-	ker
r I N	k @r
rin-	sing
r I n	s I N
rind
r aI n d
rinds
r aI n d z
rine
r aI n
rine-	hart
r aI n	h Q@ t
rines
r aI n z
ring
r I N
ring-	git
r I	N I t
ring-	gold
r I N	g @U l d
ring-	lea-	der
r I N	l i:	d @r
ring-	lea-	ders
r I N	l i:	d @r z
ring-	ling
r I N	l I N
ring-	mas-	ter
r I N	m { s	t @r
ring-	neck
r I N	n e k
ring-	side
r I N	s aI d
ring-	wood
r I N	w U d
ringe
r I N
ringed
r I N d
rings
r I N z
ring's
r I N z
rink
r I N k
rinks
r I N k s
rinse
r I n s
rior-	dan
r I@	d V n
rior-	dan's
r I@	d V n z
rip
r I p
rip-	ley
r I p	l i:
rip-	off
r I	p O: f
rip-	offs
r I	p O: f s
rip-	p-	ling
r I	p V	l I N
rip-	per
r I	p @r
rip-	pey
r I	p i:
rip-	ping
r I	p I N
rip-	ple
r I	p V l
rip-	pled
r I	p V l d
rip-	ples
r I	p V l z
rip-	pon
r I	p V n
ripe
r aI p
ripp
r I p
ripped
r I p t
rips
r I p s
ris-	ki-	er
r I s	k i:	@r
ris-	ki-	est
r I s	k i:	V s t
ris-	ki-	ness
r I s	k i:	n V s
ris-	king
r I s	k I N
ris-	ky
r I s	k i:
ris-	ley
r I z	l i:
ris-	que
r I s	k eI
ris-	ser
r I	s @r
risc
r I s k
rise
r aI z
risk
r I s k
risk-	less
r I s	k l V s
risked
r I s k t
risks
r I s k s
riss
r I s
risse
r I s
rist
r I s t
rit-	chie
r I	tS i:
rit-	ner
r I t	n @r
rit-	ter
r I	t @r
rit-	zi-	est
r I t	s i:	V s t
rit-	zy
r I t	s i:
ritch
r I tS
rite
r aI t
rites
r aI t s
rite's
r aI t s
ritt
r I t
ritt-	man
r I t	m V n
ritts
r I t s
ritz
r I t s
riv-	lin
r I v	l I n
rives
r aI v z
rix
r I k s
riz
r I z
riz-	zi
r I	z i:
riz-	zo
r I	z @U
ro
r @U
ro-	a
r @U	V
ro-	a-	noke
r @U	V	n @U k
ro-	bai-	na
r @U	b eI	n V
ro-	bards
r Q	b @r d z
ro-	be-	son
r @U	b V	s V n
ro-	ber
r @U	b @r
ro-	ber-	son
r Q	b @r	s V n
ro-	ber-	ta
r V	b @r	t V
ro-	ber-	to
r V	b e@	t @U
ro-	bers
r @U	b @r z
ro-	bert
r Q	b @r t
ro-	bert-	son
r Q	b @r t	s V n
ro-	bert-	son's
r Q	b @r t	s V n z
ro-	berts
r Q	b @r t s
ro-	bert's
r Q	b @r t s
ro-	bi-	na
r V	b i:	n V
ro-	bi-	nett
r Q	b I	n e t
ro-	bi-	nette
r Q	b I	n e t
ro-	bi-	ni-	a
r @U	b i:	n i:	V
ro-	bi-	son
r Q	b I	s V n
ro-	bi-	tus-	sin
r Q	b I	t V	s I n
ro-	bil-	lard
r Q	b I	l @r d
ro-	bin
r Q	b I n
ro-	bin-	son
r Q	b I n	s V n
ro-	bin-	son's
r Q	b I n	s V n z
ro-	bins
r Q	b I n z
ro-	bin's
r Q	b I n z
ro-	ble
r @U	b V l
ro-	bles
r @U	b V l z
ro-	bo-	tic
r @U	b Q	t I k
ro-	bo-	tics
r @U	b Q	t I k s
ro-	bot
r @U	b Q t
ro-	bots
r @U	b Q t s
ro-	bot's
r @U	b Q t s
ro-	bus-	ta
r Q	b V s	t V
ro-	bus-	tas
r Q	b V s	t V s
ro-	bust
r @U	b V s t
ro-	bust-	ly
r @U	b V s	t l i:
ro-	bust-	ness
r @U	b V s	t n V s
ro-	by
r @U	b i:
ro-	byn
r Q	b I n
ro-	ca
r @U	k V
ro-	cha
r @U	k V
ro-	chel-	la
r V	tS e	l V
ro-	chelle
r @U	S e l
ro-	cher
r @U	tS @r
ro-	che's
r @U	S V z
ro-	ches-	ter
r Q	tS e s	t @r
ro-	ches-	ter's
r Q	tS e s	t @r z
ro-	chette
r V	S e t
ro-	chon
r Q	tS V n
ro-	co-	co
r V	k @U	k @U
ro-	da
r @U	d V
ro-	de-	o
r @U	d i:	@U
ro-	de-	os
r @U	d i:	@U z
ro-	de-	ri-	ca
r @U	d @r	i:	k V
ro-	dent
r @U	d V n t
ro-	dents
r @U	d V n t s
ro-	di
r @U	d i:
ro-	din
r @U	d I n
ro-	dol-	fo
r @U	d Q l	f @U
ro-	dolph
r @U	d Q l f
ro-	gaine
r @U	g eI n
ro-	gan
r @U	g V n
ro-	ge-	li-	o
r @U	g i:	l i:	@U
ro-	ger
r Q	dZ @r
ro-	ger-	son
r Q	g @r	s V n
ro-	gers
r Q	dZ @r z
ro-	ger's
r Q	dZ @r z
ro-	gi-	er
r @U	g i:	@r
ro-	han
r @U	V n
ro-	hyp-	nol
r @U	h aI p	n O: l
ro-	jas
r @U	h Q s
ro-	ka
r @U	k V
ro-	lan
r @U	l V n
ro-	lan-	da
r @U	l Q n	d V
ro-	lan-	do
r @U	l Q n	d @U
ro-	land
r @U	l V n d
ro-	lette
r @U	l e t
ro-	lex
r @U	l e k s
ro-	ley
r @U	l i:
ro-	lo-	dex
r @U	l V	d e k s
ro-	ma
r @U	m V
ro-	ma-	nesque
r @U	m V	n e s k
ro-	ma-	ni
r @U	m Q	n i:
ro-	ma-	ni-	a
r @U	m eI	n i:	V
ro-	ma-	ni-	an
r @U	m eI	n i:	V n
ro-	ma-	ni-	ans
r @U	m eI	n i:	V n z
ro-	ma-	ni-	a's
r @U	m eI	n i:	V z
ro-	ma-	no
r @U	m Q	n @U
ro-	ma-	noff
r @U	m V	n O: f
ro-	ma-	no's
r @U	m Q	n @U z
ro-	ma-	nov
r @U	m V	n O: v
ro-	ma-	ny
r Q	m V	n i:
ro-	main
r @U	m eI n
ro-	maine
r @U	m eI n
ro-	man
r @U	m V n
ro-	man-	ces
r @U	m { n	s V z
ro-	man-	cing
r @U	m { n	s I N
ro-	man-	ti-	cal-	ly
r @U	m { n	t I	k V	l i:
ro-	man-	ti-	ci-	sm
r @U	m { n	t I	s I	z V m
ro-	man-	ti-	ci-	zing
r @U	m { n	t I	s aI	z I N
ro-	man-	ti-	cize
r @U	m { n	t I	s aI z
ro-	man-	ti-	cized
r @U	m { n	t I	s aI z d
ro-	man-	tic
r @U	m { n	t I k
ro-	man-	tics
r @U	m { n	t I k s
ro-	mance
r @U	m { n s
ro-	mans
r @U	m V n z
ro-	man's
r @U	m V n z
ro-	mas
r @U	m V z
ro-	me-	o
r @U	m i:	@U
ro-	me-	ro
r @U	m e@	@U
ro-	melle
r V	m e l
ro-	mi-	na
r V	m i:	n V
ro-	mi-	ne
r V	m i:	n i:
ro-	mi-	to
r @U	m i:	t @U
ro-	mil-	da
r V	m i: l	d V
ro-	mo
r @U	m @U
ro-	mo-	la
r Q	m V	l V
ro-	mu-	lus
r Q m	j V	l V s
ro-	na
r @U	n V
ro-	nal-	da
r @U	n Q l	d V
ro-	nald
r Q	n V l d
ro-	nan
r @U	n V n
ro-	nan's
r @U	n V n z
ro-	nen
r @U	n V n
ro-	nin
r @U	n I n
ro-	per
r @U	p @r
ro-	pers
r @U	p @r z
ro-	per's
r @U	p @r z
ro-	ping
r @U	p I N
ro-	rie
r O@	i:
ro-	ry
r O@	i:
ro-	sa
r @U	z V
ro-	sa-	bel
r @U	z V	b e l
ro-	sa-	belle
r Q	s V	b V l
ro-	sa-	lee
r @U	s V	l i:
ro-	sa-	li-	a
r @U	z V	l i:	V
ro-	sa-	lie
r @U	z V	l i:
ro-	sa-	lin-	da
r @U	s Q	l i: n	d V
ro-	sa-	lind
r Q	z V	l V n d
ro-	sa-	lyn
r Q	z V	l V n
ro-	sa-	lynd
r Q	z V	l V n d
ro-	sa-	lyn's
r Q	z V	l V n z
ro-	sa-	mond
r @U	z V	m V n d
ro-	sa-	mund
r @U	z V	m U n d
ro-	sa-	ri-	a
r @U	z Q@	i:	V
ro-	sa-	ri-	o
r @U	z Q@	i:	@U
ro-	sa-	ries
r @U	z @r	i: z
ro-	sa-	ry
r @U	z @r	i:
ro-	sa-	ti
r @U	z Q	t i:
ro-	sales
r @U	s eI l z
ro-	san
r @U	z V n
ro-	san-	na
r @U	z {	n V
ro-	sanne
r @U	z { n
ro-	sa's
r @U	z V z
ro-	seanne
r @U	z { n
ro-	sel
r @U	z V l
ro-	sel-	la
r @U	z e	l V
ro-	sel-	len
r @U	z V	l V n
ro-	sen
r @U	z V n
ro-	sen-	baum
r @U	z V n	b aU m
ro-	sen-	ber-	ger
r @U	z V n	b @r	g @r
ro-	sen-	berg
r @U	z V n	b @r g
ro-	sen-	berg's
r @U	z V n	b @r g z
ro-	sen-	blatt
r @U	z V n	b l { t
ro-	sen-	blum
r @U	z V n	b l u: m
ro-	sen-	dale
r @U	z V n	d eI l
ro-	sen-	feld
r @U	z V n	f e l d
ro-	sen-	krantz
r @U	z V n	k r { n t s
ro-	sen-	kranz
r @U	z V n	k r { n t s
ro-	sen-	quist
r @U	z V n	k w I s t
ro-	sen-	stein
r @U	z V n	s t aI n
ro-	sen-	thal
r @U	z V n	T O: l
ro-	sen-	wald
r @U	z V n	w O: l d
ro-	sene
r Q	s i: n
ro-	sen's
r @U	z V n z
ro-	senz-	weig
r @U	z V n	z w aI g
ro-	ser
r @U	z @r
ro-	ses
r @U	z V z
ro-	se's
r @U	z V z
ro-	set-	ta
r @U	z e	t V
ro-	sette
r V	s e t
ro-	settes
r @U	z e t s
ro-	si-	er
r @U	z i:	@r
ro-	si-	na
r @U	z i:	n V
ro-	si-	ne
r @U	s i:	n i:
ro-	si-	ta
r @U	z i:	t V
ro-	sie
r @U	z i:
ro-	sie's
r @U	z i: z
ro-	sin
r Q	z I n
ro-	sin-	ski
r V	s I n	s k i:
ro-	sing
r @U	z I N
ro-	sol
r @U	s O: l
ro-	sy
r @U	z i:
ro-	ta
r @U	t V
ro-	ta-	ry
r @U	t @r	i:
ro-	ta-	ted
r @U	t eI	t V d
ro-	ta-	ting
r @U	t eI	t I N
ro-	ta-	tio-	nal
r @U	t eI	S V	n V l
ro-	ta-	tion
r @U	t eI	S V n
ro-	ta-	tions
r @U	t eI	S V n z
ro-	tan
r @U	t V n
ro-	tate
r @U	t eI t
ro-	tates
r @U	t eI t s
ro-	tel-	la
r @U	t e	l V
ro-	then-	berg
r O:	T V n	b @r g
ro-	ther
r O:	T @r
ro-	ti
r @U	t i:
ro-	tis-	se-	rie
r @U	t I	s @r	i:
ro-	to
r @U	t @U
ro-	to-	lo
r @U	t @U	l @U
ro-	to-	til-	ler
r @U	t V	t I	l @r
ro-	to-	til-	ling
r @U	t V	t I	l I N
ro-	to-	till
r @U	t V	t I l
ro-	to-	tilled
r @U	t V	t I l d
ro-	tor
r @U	t @r
ro-	tors
r @U	t @r z
ro-	tun-	da
r @U	t V n	d V
ro-	tun-	do
r @U	t u: n	d @U
ro-	tund
r @U	t V n d
ro-	wan
r @U	V n
ro-	wan's
r @U	V n z
ro-	we-	na
r @U	i:	n V
ro-	well
r @U	I l
ro-	wen
r @U	V n
ro-	wer
r @U	@r
ro-	wing
r @U	I N
ro-	xa-	na
r Q k	s {	n V
ro-	xan-	na
r Q k	s {	n V
ro-	xanne
r Q k	s { n
ro-	xie
r Q k	s i:
ro-	xine
r Q k	s aI n
ro-	x's
r Q k	s V z
ro-	xy
r Q k	s i:
ro-	ya-	list
r OI	V	l I s t
ro-	yal
r OI	V l
ro-	yal-	ly
r OI	V	l i:
ro-	yal-	ties
r OI	V l	t i: z
ro-	yal-	ty
r OI	V l	t i:
ro-	yale
r OI	{ l
ro-	yall
r OI	V l
ro-	yals
r OI	V l z
ro-	yal's
r OI	V l z
ro-	zek
r @U	z e k
ro-	zel-	la
r @U	z e	l V
ro-	zelle
r V	z e l
roa-	ches
r @U	tS V z
roa-	die
r @U	d i:
roa-	dy
r @U	d i:
roa-	ming
r @U	m I N
roa-	ring
r O@	I N
roach
r @U tS
road
r @U d
road-	block
r @U d	b l Q k
road-	blocks
r @U d	b l Q k s
road-	house
r @U d	h aU s
road-	mas-	ter
r @U d	m { s	t @r
road-	run-	ner
r @U d	r V	n @r
road-	show
r @U d	S @U
road-	side
r @U d	s aI d
road-	sides
r @U d	s aI d z
road-	ster
r @U d	s t @r
road-	way
r @U d	w eI
road-	ways
r @U d	w eI z
road-	work
r @U d	w @r k
roads
r @U d z
road's
r @U d z
roald
r @U l d
roam
r @U m
roamed
r @U m d
roams
r @U m z
roan
r @U n
roan-	na
r @U	n V
roane
r @U n
roar
r O@
roared
r O@ d
roark
r O@ k
roarke
r O@ k
roars
r O@ z
roas-	ted
r @U s	t V d
roas-	ter
r @U s	t @r
roas-	ters
r @U s	t @r z
roas-	ting
r @U s	t I N
roast
r @U s t
roasts
r @U s t s
roath
r @U T
rob
r Q b
rob-	be-	ries
r Q	b @r	i: z
rob-	be-	ry
r Q	b @r	i:
rob-	ben
r Q	b V n
rob-	ber
r Q	b @r
rob-	bers
r Q	b @r z
rob-	bie
r Q	b i:
rob-	bie's
r Q	b i: z
rob-	bin
r Q	b I n
rob-	bing
r Q	b I N
rob-	bins
r Q	b I n z
rob-	by
r Q	b i:
rob-	by's
r Q	b i: z
rob-	son
r Q b	s V n
robb
r Q b
robbed
r Q b d
robb's
r Q b z
robe
r @U b
robed
r @U b d
robes
r @U b z
robs
r Q b z
rob's
r Q b z
roc
r Q k
roc-	ca
r Q	k V
roc-	co
r Q	k @U
roc-	co's
r Q	k @U z
roc-	ka-	bil-	ly
r Q	k V	b I	l i:
roc-	ka-	fel-	low
r Q	k V	f e	l @U
roc-	ka-	way
r Q	k V	w eI
roc-	ke-	fel-	ler
r Q	k V	f e	l @r
roc-	ke-	fel-	ler's
r Q	k V	f e	l @r z
roc-	ke-	ted
r Q	k V	t V d
roc-	ke-	ting
r Q	k V	t I N
roc-	kel
r Q	k V l
roc-	ker
r Q	k @r
roc-	kers
r Q	k @r z
roc-	ket
r Q	k V t
roc-	ket-	ry
r Q	k V t	r i:
roc-	kets
r Q	k V t s
roc-	ket's
r Q	k V t s
roc-	kettes
r Q	k e t s
roc-	key
r Q	k i:
roc-	kies
r Q	k i: z
roc-	kin-	gham
r Q	k I N	h { m
roc-	king
r Q	k I N
roc-	ky
r Q	k i:
roch
r Q k
roch-	berg
r @U tS	b @r g
roch-	ford
r Q tS	f @r d
roche
r @U tS
rock
r Q k
rock-	and-	roll
r Q	k { n	d r @U l
rock-	ford
r Q k	f @r d
rock-	land
r Q k	l V n d
rock-	lin
r Q k	l I n
rock-	man
r Q k	m V n
rock-	'n'-	roll
r Q	k V n	r @U l
rock-	ne
r Q k	n i:
rock-	port
r Q k	p O@ t
rock-	rose
r Q k	r @U z
rock-	ville
r Q k	v I l
rock-	well
r Q k	w e l
rock-	well's
r Q k	w e l z
rock-	wood
r Q k	w U d
rocked
r Q k t
rocks
r Q k s
rock's
r Q k s
rod
r Q d
rod-	den
r Q	d V n
rod-	den-	ber-	ry
r Q	d V n	b e@	i:
rod-	dick
r Q	d I k
rod-	die
r Q	d i:
rod-	ding
r Q	d I N
rod-	dy
r Q	d i:
rod-	ger
r Q	dZ @r
rod-	gers
r Q	dZ @r z
rod-	ham
r O:	d V m
rod-	man
r Q d	m V n
rod-	man's
r Q d	m V n z
rod-	ney
r Q d	n i:
rod-	ri-	go
r V d	r i:	g @U
rod-	ri-	gue-	z's
r Q d	r i:	g e	z V z
rod-	ri-	guez
r Q d	r i:	g e z
rod-	ri-	quez
r Q d	r i:	k e z
rod-	rick
r Q d	r I k
rodd
r Q d
rode
r @U d
rode-	rick
r Q d	r I k
rode-	rick's
r Q d	r I k s
rode-	way
r @U d	w eI
rodes
r @U d z
rodge
r Q dZ
rods
r Q d z
roe
r @U
roe-	buck
r @U	b V k
roe-	buck's
r @U	b V k s
roe-	land
r @U	l V n d
roe-	mer
r @U	m @r
roe-	ser
r @U	z @r
roeb-	ling
r @U b	l I N
roed
r @U d
roehm
r @U m
roes
r @U z
roff
r O: f
rog
r Q g
rogue
r @U g
rogues
r @U g z
roh
r @U
rohe
r @U
rohn
r Q n
roi
r OI
roi-	ling
r OI	l I N
roil
r OI l
roiled
r OI l d
rois-	ter
r OI s	t @r
rol-	dan
r @U l	d V n
rol-	la
r Q	l V
rol-	land
r Q	l V n d
rol-	land's
r @U	l V n d z
rol-	ler
r @U	l @r
rol-	ler-	bla-	ding
r @U	l @r b	l eI	d I N
rol-	ler-	blade
r @U	l @r b	l eI d
rol-	ler-	blades
r @U	l @r b	l eI d z
rol-	ler-	coas-	ter
r @U	l @r	k @U s	t @r
rol-	lers
r @U	l @r z
rol-	let
r @U	l e t
rol-	ley
r Q	l i:
rol-	lic-	king
r Q	l I	k I N
rol-	lie
r @U	l i:
rol-	lin
r Q	l I n
rol-	ling
r @U	l I N
rol-	lings
r @U	l I N z
rol-	lins
r Q	l I n z
rol-	lo
r Q	l @U
rol-	lout
r @U	l aU t
rol-	nick
r @U l	n I k
role
r @U l
role-	mo-	del
r @U l	m Q	d V l
role-	play-	ing
r @U l	p l eI	I N
roles
r @U l z
rolf
r @U l f
rolfe
r @U l f
rolfs
r @U l f s
roll
r @U l
roll-	back
r @U l	b { k
roll-	backs
r @U l	b { k s
roll-	man
r @U l	m V n
roll-	o-	ver
r @U	l @U	v @r
roll-	o-	vers
r @U	l @U	v @r z
roll-	out
r @U	l aU t
roll-	top
r @U l	t Q p
rolled
r @U l d
rolls
r @U l z
rolph
r @U l f
rom
r Q m
rom-	berg
r Q m	b @r g
rom-	mel
r Q	m V l
rom-	ney
r Q m	n i:
rom-	ney's
r Q m	n i: z
rom-	ping
r Q m	p I N
rome
r @U m
rome's
r @U m z
romp
r Q m p
roms
r Q m z
rom's
r Q m z
ron
r Q n
ron-	co
r @U n	k @U
ron-	da
r Q n	d V
ron-	deau
r Q n	d @U
ron-	do-	ni-	a
r Q n	d @U	n i:	V
ron-	don
r Q n	d V n
ron-	na
r Q	n V
ron-	nie
r Q	n i:
ron-	ning
r Q	n I N
ron-	ny
r Q	n i:
ron-	stadt
r Q n	s t { t
rone
r @U n
rong
r O: N
ronne
r Q n
ron's
r Q n z
roo-	fer
r u:	f @r
roo-	fers
r u:	f @r z
roo-	fing
r u:	f I N
roo-	ker
r U	k @r
roo-	kie
r U	k i:
roo-	kies
r U	k i: z
roo-	mi-	er
r u:	m i:	@r
roo-	mi-	ness
r u:	m i:	n V s
roo-	ming
r u:	m I N
roo-	my
r u:	m i:
roo-	ney
r u:	n i:
roo-	ney's
r u:	n i: z
roo-	sa
r u:	s V
roo-	se-	velt
r @U	z V	v e l t
roo-	se-	velt's
r @U	z V	v e l t s
roo-	ted
r u:	t V d
roo-	ter
r u:	t @r
roo-	ters
r u:	t @r z
roo-	ting
r u:	t I N
rood
r u: d
roof
r u: f
roof-	top
r u: f	t Q p
roof-	tops
r u: f	t Q p s
roof-	tree
r u: f	t r i:
roofed
r u: f t
roofs
r u: f s
rook
r U k
rooke
r U k
rooks
r U k s
room
r u: m
room-	ful
r u: m	f U l
room-	mate
r u:	m eI t
room-	mates
r u:	m eI t s
rooms
r u: m z
room's
r u: m z
roop
r u: p
roos
r u: z
roos-	ted
r u: s	t V d
roos-	ter
r u: s	t @r
roos-	ters
r u: s	t @r z
roose
r u: z
roost
r u: s t
root
r u: t
root-	less
r u: t	l V s
roots
r u: t s
rope
r @U p
roped
r @U p t
ropes
r @U p s
ropp
r Q p
rops
r Q p s
roque
r @U k
roque-	more
r @U k	m O@
ror-	schach
r O@	S Q
rorke
r O@ k
ros
r O: s
ros-	coe
r Q s	k @U
ros-	lyn
r Q z	l I n
ros-	man
r Q s	m V n
ros-	mun-	da
r @U s	m u: n	d V
ros-	ner
r Q s	n @r
ros-	sen
r O:	s V n
ros-	ser
r O:	s @r
ros-	set-	ti
r @U	s e	t i:
ros-	si
r O:	s i:
ros-	si-	ni
r @U	s i:	n i:
ros-	si-	ter
r O:	s I	t @r
ros-	si-	ya
r O:	s i:	V
ros-	sie
r O:	s i:
ros-	sing
r O:	s I N
ros-	ten
r Q	s V n
ros-	ter
r Q s	t @r
ros-	ters
r Q s	t @r z
ros-	tov
r Q s	t Q v
)"
R"(ros-	tro-	po-	vich
r O: s	t r V	p @U	v I tS
ros-	trum
r Q s	t r V m
ros-	wald
r Q s	w V l d
ros-	well
r Q s	w e l
ros-	zak
r Q	S V k
rose
r @U z
rose-	ber-	ry
r @U z	b e@	i:
rose-	bo-	ro
r @U z	b @r	@U
rose-	boom
r @U z	b u: m
rose-	bud
r @U z	b V d
rose-	bush
r @U z	b U S
rose-	crans
r @U z	k r { n z
rose-	land
r @U z	l V n d
rose-	lawn
r @U z	l O: n
rose-	lawn's
r @U z	l O: n z
rose-	line
r @U z	l aI n
rose-	ma-	rie
r @U z	m @r	i:
rose-	ma-	ry
r @U z	m e@	i:
rose-	mead
r @U z	m i: d
rose-	mont
r @U z	m Q n t
rose-	ville
r @U z	v I l
rose-	wood
r @U z	w U d
rose-	wood's
r @U z	w U d z
rosh
r O: S
ross
r Q s
ross-	bach
r Q s	b Q k
ross-	lyn
r Q s	l I n
ross-	more
r Q s	m O@
ross-	ner
r Q s	n @r
rosse
r Q s
rost
r Q s t
rot
r Q t
rot-	berg
r Q t	b @r g
rot-	man
r Q t	m V n
rot-	ted
r Q	t V d
rot-	ten
r Q	t V n
rot-	ter
r Q	t @r
rot-	ter-	dam
r Q	t @r	d { m
rot-	ting
r Q	t I N
rote
r @U t
roth
r O: T
roth-	berg
r O: T	b @r g
roth-	well
r O: T	w e l
roth's
r Q T s
roths-	child
r O: T	s tS aI l d
roths-	child's
r O: T	tS aI l d z
roths-	tein
r O: T	s t aI n
rots
r Q t s
rou-	ble
r u:	b V l
rou-	geau
r u:	Z @U
rou-	gher
r V	f @r
rou-	ghest
r V	f V s t
rou-	ghing
r V	f I N
rou-	leau
r u:	l @U
rou-	lette
r u:	l e t
rou-	lettes
r u:	l e t s
rou-	lette's
r u:	l e t s
rouge
r u: Z
rough
r V f
rough-	ly
r V f	l i:
rough-	neck
r V f	n e k
rough-	necks
r V f	n e k s
rough-	ness
r V f	n V s
rough-	shod
r V f	S Q d
roughed
r V f t
rought
r O: t
roun-	da-	bout
r aU n	d V	b aU t
roun-	ded
r aU n	d V d
roun-	der
r aU n	d @r
roun-	ding
r aU n	d I N
roun-	dup
r aU n	d V p
roun-	dy
r aU n	d i:
round
r aU n d
round-	head
r aU n	d h e d
round-	house
r aU n	d h aU s
round-	ly
r aU n	d l i:
round-	ta-	ble
r aU n	d t eI	b V l
round-	tree
r aU n	d t r i:
round-	trip
r aU n	d t r I p
round-	worm
r aU n	d w @r m
round-	worms
r aU n	d w @r m z
rounds
r aU n d z
row
r @U
row-	bo-	tham
r @U	b V	T { m
row-	boat
r @U	b @U t
row-	di-	ness
r aU	d i:	n V s
row-	dies
r aU	d i: z
row-	dy
r aU	d i:
row-	land
r @U	l V n d
row-	land's
r @U	l V n d z
row-	lett
r @U	l e t
row-	ley
r @U	l i:
row-	ney
r @U	n i:
rowe
r @U
rowed
r @U d
rowe's
r @U z
rown-	tree
r @U n	t r i:
rows
r @U z
row's
r @U z
rox
r Q k s
rox-	bu-	ry
r Q k	s b e@	i:
roy
r OI
roy-	ce's
r OI	s V z
roy-	den
r OI	d V n
royce
r OI s
royd
r OI d
roye
r OI
roy's
r OI z
roys-	ter
r OI s	t @r
roys-	ton
r OI s	t V n
roz
r Q z
r's
Q@ z
ru
r u:
ru-	a
r u:	V
ru-	bel
r u:	b V l
ru-	bel-	la
r u:	b e	l V
ru-	ben
r u:	b V n
ru-	ben-	stein
r u:	b V n	s t aI n
ru-	bens
r u:	b V n z
ru-	bi
r u:	b i:
ru-	bi-	a
r u:	b i:	V
ru-	bi-	con
r u:	b I	k O: n
ru-	bi-	na
r u:	b i:	n V
ru-	bi-	o
r u:	b i:	@U
ru-	bie
r u:	b i:
ru-	bies
r u:	b i: z
ru-	bik
r u:	b I k
ru-	bik's
r u:	b I k s
ru-	bin
r u:	b I n
ru-	bin-	stein
r u:	b I n	s t i: n
ru-	bin's
r u:	b I n z
ru-	ble
r u:	b V l
ru-	bles
r u:	b V l z
ru-	ble's
r u:	b V l z
ru-	bout
r V	b aU t
ru-	by
r u:	b i:
ru-	by's
r u:	b i: z
ru-	der
r u:	d @r
ru-	der's
r u:	d @r z
ru-	dest
r u:	d V s t
ru-	di-	ger
r V	d I	g @r
ru-	di-	men-	ta-	ry
r u:	d I	m e n	t @r	i:
ru-	di-	ment
r u:	d I	m e n t
ru-	di-	ments
r u:	d I	m e n t s
ru-	dich
r V	d I k
ru-	die
r u:	d i:
ru-	din
r u:	d I n
ru-	dolf
r u:	d Q l f
ru-	dolph
r u:	d O: l f
ru-	dy
r u:	d i:
ru-	dy's
r u:	d i: z
ru-	el-	la
r u:	e	l V
ru-	elle
r u:	e l
ru-	fi-	na
r u:	f i:	n V
ru-	ford
r u:	f @r d
ru-	fus
r u:	f V s
ru-	gen
r V	g V n
ru-	i-	ning
r u:	I	n I N
ru-	i-	nous
r u:	I	n V s
ru-	in
r u:	I n
ru-	ined
r u:	I n d
ru-	ins
r u:	I n z
ru-	iz
r u:	w i: z
ru-	key-	ser
r u:	k eI	z @r
ru-	ler
r u:	l @r
ru-	lers
r u:	l @r z
ru-	ling
r u:	l I N
ru-	lings
r u:	l I N z
ru-	ling's
r u:	l I N z
ru-	ma-	ni-	a
r u:	m eI	n i:	V
ru-	ma-	ni-	an
r u:	m eI	n i:	V n
ru-	mage
r V	m I dZ
ru-	man
r u:	m V n
ru-	me-	ry
r V	m @r	i:
ru-	men
r u:	m V n
ru-	mi-	na
r u:	m I	n V
ru-	mi-	na-	ted
r u:	m I	n eI	t I d
ru-	mi-	na-	tion
r u:	m I	n eI	S V n
ru-	mi-	na-	tions
r u:	m I	n eI	S V n z
ru-	mi-	nant
r u:	m I	n V n t
ru-	mi-	nate
r u:	m I	n eI t
ru-	mor
r u:	m @r
ru-	mored
r u:	m @r d
ru-	mors
r u:	m @r z
ru-	mour
r u:	m @r
ru-	mours
r u:	m @r z
ru-	na-	bout
r V	n V	b aU t
ru-	na-	round
r V	n V	r aU n d
ru-	na-	way
r V	n V	w eI
ru-	na-	ways
r V	n V	w eI z
ru-	nion
r u: n	j V n
ru-	nny
r V	n i:
ru-	nup
r V	n V p
ru-	nups
r V	n V p s
ru-	pee
r u:	p i:
ru-	pees
r u:	p i: z
ru-	per-	ta
r u:	p e@	t V
ru-	pert
r u:	p @r t
ru-	pi-	ah
r u:	p aI	V
ru-	ral
r U@	V l
ru-	ri-	ta-	ni-	a
r U@	I	t eI	n i:	V
ru-	rik
r U@	I k
ru-	sal-	ka
r u:	s { l	k V
ru-	ses
r u:	z V z
ru-	sher
r V	S @r
ru-	shes
r V	S V z
ru-	shing
r V	S I N
ru-	sh's
r V	S V z
ru-	sin
r u:	s I n
ru-	stle
r V	s V l
ru-	ta
r u:	t V
ru-	tan
r u:	t V n
ru-	thann
r u:	T { n
ru-	ther
r u:	T @r
ru-	ther-	ford
r V	T @r	f @r d
ru-	thie
r u:	T i:
ru-	tile
r u:	t i: l
ru-	vo-	lo
r u:	v @U	l @U
ru-	zich
r V	z I h
rub
r V b
rub-	be-	rize
r V	b @r	aI z
rub-	be-	rized
r V	b @r	aI z d
rub-	be-	ry
r V	b @r	i:
rub-	ber
r V	b @r
rub-	ber-	maid
r V	b @r	m eI d
rub-	ber-	maid's
r V	b @r	m eI d z
rub-	bers
r V	b @r z
rub-	bing
r V	b I N
rub-	bish
r V	b I S
rub-	ble
r V	b V l
rub-	ric
r u: b	r I k
rubbed
r V b d
rube
r u: b
rubs
r V b z
ruc-	ker
r V	k @r
ruc-	kle
r V	k V l
ruc-	kus
r V	k V s
ruck
r V k
ruck-	man
r V k	m V n
rucks
r V k s
rud
r V d
rud-	der
r V	d @r
rud-	der-	less
r V	d @r	l V s
rud-	dle
r V	d V l
rud-	dock
r V	d V k
rud-	dy
r V	d i:
rud-	loff
r V d	l O: f
rud-	man
r V d	m V n
rud-	man's
r V d	m V n z
rud-	yard
r V d	j @r d
rudd
r V d
rude
r u: d
rude-	ly
r u: d	l i:
rude-	ness
r u: d	n V s
rudge
r V dZ
rue
r u:
rue-	ful
r u:	f V l
rue-	ful-	ly
r u:	f V	l i:
rue-	ter
r u:	t @r
ruel
r u: l
ruf-	f-	ling
r V	f V	l I N
ruf-	fer
r V	f @r
ruf-	fin
r V	f I n
ruf-	fing
r V	f I N
ruf-	fle
r V	f V l
ruf-	fled
r V	f V l d
ruf-	fles
r V	f V l z
ruf-	fo
r V	f @U
ruf-	ford
r V	f @r d
rufe
r u: f
ruff
r V f
rug
r V g
rug-	by
r V g	b i:
rug-	ged
r V	g V d
rug-	ged-	ly
r V	g V d	l i:
rug-	gie-	ro
r u:	dZ I@	@U
rugg
r V g
rugs
r V g z
ruh
r V
ruhl
r V l
ruhnke
r V N k
ruhr
r U@
rule
r u: l
rule-	book
r u: l	b U k
ruled
r u: l d
rules
r u: l z
rule's
r u: l z
rum
r V m
rum-	b-	ling
r V m	b V	l I N
rum-	b-	lings
r V m	b V	l I N z
rum-	ble
r V m	b V l
rum-	bled
r V m	b V l d
rum-	bles
r V m	b V l z
rum-	ford
r V m	f @r d
rum-	ma-	ging
r V	m I	dZ I N
rum-	mage
r V	m I dZ
rum-	mel
r V	m V l
rum-	my
r V	m i:
rum-	ney
r V m	n i:
rum-	ple
r V m	p V l
rum-	pled
r V m	p V l d
rum-	sey
r V m	z i:
rum-	son
r V m	s V n
rump
r V m p
rumpf
r V m p f
rums
r V m z
rums-	feld
r V m	z f e l d
run
r V n
run-	a-	round
r V	n V	r aU n d
run-	cie
r V n	s i:
run-	dle
r V n	d V l
run-	down
r V n	d aU n
run-	kel
r V N	k V l
run-	kle
r V N	k V l
run-	kles
r V N	k V l z
run-	nells
r V	n V l z
run-	nels
r V	n V l z
run-	ner
r V	n @r
run-	ners
r V	n @r z
run-	ner's
r V	n @r z
run-	ning
r V	n I N
run-	nings
r V	n I N z
run-	nion
r V n	j V n
run-	off
r V	n O: f
run-	on
r V	n Q n
run-	up
r V	n V p
run-	way
r V n	w eI
run-	ways
r V n	w eI z
run-	yon
r V n	j V n
runck
r V N k
rund
r V n d
rung
r V N
runge
r V n dZ
rungs
r V N z
runs
r V n z
rup-	pert
r V	p @r t
rup-	recht
r V p	r I k t
rup-	tu-	ring
r V p	tS @r	I N
rup-	ture
r V p	tS @r
rup-	tured
r V p	tS @r d
rup-	tures
r V p	tS @r z
rus
r V s
rus-	kin
r V s	k I n
rus-	sel
r V	s V l
rus-	sell
r V	s V l
rus-	sell-	ville
r V	s V l	v I l
rus-	sell's
r V	s V l z
rus-	sel's
r V	s V l z
rus-	set
r V	s V t
rus-	sets
r V	s V t s
rus-	si
r u:	s i:
rus-	si-	fi-	ca-	tion
r V	s I	f I	k eI	S V n
rus-	si-	fied
r u:	s I	f aI d
rus-	si-	fy
r u:	s I	f aI
rus-	sia
r V	S V
rus-	sian
r V	S V n
rus-	sians
r V	S V n z
rus-	sian's
r V	S V n z
rus-	sia's
r V	S V z
rus-	so
r u:	s @U
rus-	som
r V	s V m
rus-	ted
r V s	t V d
rus-	tic
r V s	t I k
rus-	tin
r V s	t I n
rus-	ting
r V s	t I N
rus-	ton
r V s	t V n
rus-	ty
r V s	t i:
ruse
r u: z
rush
r V S
rush-	die
r V S	d i:
rush-	die's
r V S	d i: z
rush-	ford
r V S	f @r d
rush-	more
r V S	m O@
rushed
r V S t
rusk
r V s k
rusk's
r V s k s
russ
r V s
russe
r V s
rust
r V s t
rust-	ler
r V s	l @r
rust-	lers
r V s	l @r z
rust-	ling
r V s	l I N
rust-	proo-	fing
r V s	t p r u:	f I N
rust-	proof
r V s	t p r u: f
rusts
r V s t s
rust's
r V s t s
rut
r V t
rut-	gers
r V t	g @r z
rut-	ger's
r V t	g @r z
rut-	land
r V t	l V n d
rut-	ledge
r V t	l I dZ
rut-	ted
r V	t V d
rut-	ter
r V	t @r
ruth
r u: T
ruth-	less
r u: T	l V s
ruth-	less-	ly
r u: T	l V s	l i:
ruth-	less-	ness
r u: T	l V s	n V s
ruth-	ven
r V T	v V n
ruth's
r u: T s
ruts
r V t s
rux
r V k s
ruyle
r aI l
ry-	al
r i:	Q l
ry-	als
r i:	Q l z
ry-	an
r aI	V n
ry-	an's
r aI	V n z
ry-	der
r aI	d @r
ry-	der's
r aI	d @r z
ry-	en
r aI	V n
ry-	land
r I	l V n d
ry-	ley
r aI	l i:
ry-	on
r aI	V n
ryd-	berg
r I d	b @r g
rye
r aI
ryle
r aI l
s
e s
s-	d-	n
e s	d i:	e n
s-	edu-	cing
s V	d u:	s I N
s-	h
e	s eI tS
s-	r
s i: n	j @r
s'-	s
e	s V z
s-	u-	u
e s	j u:	j u:
s.
e s
sa
s Q
sa-	ba
s Q	b V
sa-	ba-	ti-	ni
s {	b V	t i:	n i:
sa-	bah
s Q	b V
sa-	ban
s eI	b V n
sa-	bel-	la
s V	b e	l V
sa-	ber
s eI	b @r
sa-	bers
s eI	b @r z
sa-	bi-	a
s Q	b i:	V
sa-	bi-	na
s V	b i:	n V
sa-	bi-	no
s Q	b i:	n @U
sa-	bin
s eI	b I n
sa-	bine
s V	b i: n
sa-	bins
s eI	b I n z
sa-	ble
s eI	b V l
sa-	bles
s eI	b V l z
sa-	bo-	ta-	ging
s {	b V	t Q	Z I N
sa-	bo-	tage
s {	b V	t Q Z
sa-	bo-	taged
s {	b V	t Q Z d
sa-	bo-	teur
s {	b V	t @r
sa-	bo-	teurs
s {	b V	t @r z
sa-	bol
s Q	b O: l
sa-	bre
s eI	b @r
sa-	bres
s eI	b @r z
sa-	cha
s {	tS V
sa-	cher
s {	k @r
sa-	chi
s {	tS i:
sa-	co
s eI	k @U
sa-	da
s Q	d V
sa-	dat
s Q	d Q t
sa-	dat's
s Q	d Q t s
sa-	del-	la
s V	d e	l V
sa-	di-	ra
s Q	d I@	V
sa-	di-	sm
s eI	d I	z V m
sa-	die
s {	d i:
sa-	die's
s eI	d i: z
sa-	dis-	tic
s V	d I s	t I k
sa-	dist
s eI	d I s t
sa-	do
s eI	d @U
sa-	doff
s {	d O: f
sa-	dow-	ski
s V	d O: f	s k i:
sa-	dye
s {	d aI
sa-	eed
s Q	i: d
sa-	fa-	ri
s V	f Q@	i:
sa-	fa-	ris
s V	f Q@	i: z
sa-	fer
s eI	f @r
sa-	fest
s eI	f V s t
sa-	fier
s V	f I@
sa-	fing
s eI	f I N
sa-	fir
s {	f @r
sa-	fire
s V	f aI r
sa-	fire's
s V	f aI r z
sa-	ga
s Q	g V
sa-	gan
s eI	g V n
sa-	gas
s Q	g V z
sa-	ger
s eI	g @r
sa-	ges
s eI	dZ V z
sa-	ge's
s eI	dZ V z
sa-	gi-	naw
s {	g I	n O:
sa-	go
s eI	g @U
sa-	gua-	ro
s V g	w O@	@U
sa-	ha-	ra
s V	h e@	V
sa-	ha-	ran
s {	h @r	V n
sa-	ka-	i
s Q	k Q	i:
sa-	ker
s eI	k @r
sa-	ki
s Q	k i:
sa-	ko
s Q	k @U
sa-	la
s Q	l V
sa-	la-	ble
s eI	l V	b V l
sa-	la-	cious
s V	l eI	S V s
sa-	la-	da
s V	l Q	d V
sa-	la-	din
s {	l V	d V n
sa-	la-	man-	ca
s {	l V	m { N	k V
sa-	la-	man-	der
s {	l V	m { n	d @r
sa-	la-	man-	ders
s {	l V	m { n	d @r z
sa-	la-	mi
s V	l Q	m i:
sa-	la-	mis
s V	l Q	m i: z
sa-	la-	mon
s {	l V	m V n
sa-	la-	mone
s {	l V	m @U n
sa-	la-	ried
s {	l @r	i: d
sa-	la-	ries
s {	l @r	i: z
sa-	la-	ry
s {	l @r	i:
sa-	la-	ry-	men
s {	l @r	i:	m V n
sa-	la-	zar
s {	l V	z Q@
sa-	laam
s V	l Q m
sa-	lad
s {	l V d
sa-	lads
s {	l V d z
sa-	las
s Q	l Q z
sa-	lay
s {	l eI
sa-	le-	ma
s V	l i:	m V
sa-	lea-	ble
s eI	l V	b V l
sa-	leem
s {	l i: m
sa-	lem
s eI	l V m
sa-	lem's
s eI	l V m z
sa-	ler-	no
s V	l e@	n @U
sa-	li-	ent
s eI	l i:	V n t
sa-	li-	na
s V	l i:	n V
sa-	li-	nas
s V	l i:	n V s
sa-	li-	ni-	ty
s V	l I	n V	t i:
sa-	li-	va
s V	l aI	v V
sa-	li-	va-	ted
s {	l I	v eI	t I d
sa-	li-	va-	ting
s {	l I	v eI	t I N
sa-	li-	vate
s {	l I	v eI t
sa-	lim
s {	l I m
sa-	lin-	ger
s {	l I	N @r
sa-	lin-	ger's
s {	l I	N @r z
sa-	line
s V	l i: n
sa-	lis
s Q	l I s
sa-	lo-	ma
s Q	l @U	m V
sa-	lo-	me
s V	l @U	m i:
sa-	lo-	mi
s Q	l @U	m i:
sa-	lo-	mo-	ne
s Q	l @U	m @U	n i:
sa-	lo-	mon
s {	l V	m V n
sa-	lo-	mon's
s {	l V	m V n z
sa-	lon
s V	l Q n
sa-	lons
s V	l Q n z
sa-	loon
s V	l u: n
sa-	loons
s V	l u: n z
sa-	lu-	ta-	ry
s { l	j V	t e@	i:
sa-	lu-	ta-	to-	ri-	an
s V	l u:	t V	t O@	i:	V n
sa-	lu-	ted
s V	l u:	t V d
sa-	lu-	ting
s V	l u:	t I N
sa-	lus
s {	l V s
sa-	lute
s V	l u: t
sa-	lutes
s V	l u: t s
sa-	ly-	er
s Q	l i:	@r
sa-	ma
s Q	m V
sa-	ma-	ra
s {	m @r	V
sa-	ma-	ras
s {	m @r	V z
sa-	ma-	ri-	a
s eI	m @r	i:	V
sa-	ma-	ri-	tan
s V	m e@	V	t V n
sa-	ma-	ri-	tans
s V	m e@	V	t V n z
sa-	man-	tha
s V	m { n	T V
sa-	mar
s {	m Q@
sa-	mar-	kand
s {	m Q@	k { n d
sa-	mek
s {	m I k
sa-	mel-	la
s V	m e	l V
sa-	mi
s {	m i:
sa-	mi's
s {	m i: z
sa-	mo-	a
s V	m @U	V
sa-	mo-	an
s V	m @U	V n
sa-	mos
s eI	m Q s
sa-	mu-	e-	la
s { m	j u:	e	l V
sa-	mu-	el-	son
s { m	j u:	V l	s V n
sa-	mu-	els
s { m	j u:	V l z
sa-	mu-	rai
s {	m @r	aI
sa-	mu-	rais
s {	m @r	aI z
sa-	mu-	rai's
s {	m @r	aI z
sa-	muel
s { m	j u: l
sa-	muel's
s { m	j u: l z
sa-	na
s Q	n V
sa-	naa
s V	n Q
sa-	ner
s eI	n @r
sa-	ni-	ta-	ry
s {	n I	t e@	i:
sa-	ni-	ta-	tion
s {	n I	t eI	S V n
sa-	ni-	ti-	zing
s {	n I	t aI	z I N
sa-	ni-	tize
s {	n I	t aI z
sa-	ni-	tized
s {	n I	t aI z d
sa-	ni-	ty
s {	n I	t i:
sa-	one
s eI	@U n
sa-	pi-	ens
s eI	p i:	V n z
sa-	pien-	za
s Q	p i: n	z V
sa-	po-	ni-	fi-	ca-	tion
s V	p Q	n V	f V	k eI	S V n
sa-	ra
s e@	V
sa-	ra-	cens
s e@	V	s V n z
sa-	ra-	je-	vo
s Q@	V	j eI	v @U
sa-	ra-	je-	vo's
s Q@	V	j eI	v @U z
sa-	ra-	so-	ta
s e@	V	s @U	t V
sa-	ra-	to-	ga
s e@	V	t @U	g V
sa-	ra-	tov
s e@	V	t O: v
sa-	ra-	wak
s e@	V	w Q k
sa-	ra-	zen
s e@	V	z V n
sa-	rah
s e@	V
sa-	rah's
s e@	V z
sa-	ran
s @r	{ n
sa-	ra's
s e@	V z
sa-	rene
s @r	i: n
sa-	rette
s @r	e t
sa-	ri
s Q@	i:
sa-	ri-	ne
s Q@	i:	n i:
sa-	rin
s Q@	I n
sa-	ris
s Q@	i: z
sa-	ri's
s Q@	i: z
sa-	rong
s @r	O: N
sa-	rongs
s @r	O: N z
sa-	ros
s Q@	@U s
sa-	rum
s {	r V m
sa-	sha
s {	S V
sa-	shes
s {	S V z
sa-	ta-	ni-	sm
s eI	t V	n I	z V m
sa-	ta-	nic
s V	t {	n I k
sa-	ta-	nist
s eI	t V	n I s t
sa-	tan
s eI	t V n
sa-	ted
s eI	t V d
sa-	tel-	lite
s {	t V	l aI t
sa-	tel-	lites
s {	t V	l aI t s
sa-	tel-	lite's
s {	t V	l aI t s
sa-	ti-	re
s {	t aI	@r
sa-	ti-	res
s {	t aI	@r z
sa-	ti-	ri-	cal
s V	t I@	I	k V l
sa-	ti-	ri-	zes
s {	t @r	aI	z V z
sa-	ti-	ri-	zing
s {	t @r	aI	z I N
sa-	ti-	ric
s V	t I@	I k
sa-	ti-	rist
s {	t @r	I s t
sa-	ti-	rists
s {	t @r	I s t s
sa-	ti-	rize
s {	t @r	aI z
sa-	tin
s {	t I n
sa-	tis-	fac-	tion
s {	t I s	f { k	S V n
sa-	tis-	fac-	tions
s {	t I s	f { k	S V n z
sa-	tis-	fac-	to-	ry
s {	t I s	f { k	t @r	i:
sa-	tis-	facto-	ri-	ly
s {	t I s	f { k	t r V	l i:
sa-	tis-	fied
s {	t I s	f aI d
sa-	tis-	fies
s {	t I s	f aI z
sa-	tis-	fy
s {	t I s	f aI
sa-	tis-	fy-	ing
s {	t I s	f aI	I N
sa-	to
s Q	t @U
sa-	tu-	ra-	ted
s {	tS @r	eI	t V d
sa-	tu-	ra-	ting
s {	tS @r	eI	t I N
sa-	tu-	ra-	tion
s {	tS @r	eI	S V n
sa-	tu-	rate
s {	tS @r	eI t
sa-	tur-	day
s {	t @r	d i:
sa-	tur-	days
s {	t @r	d i: z
sa-	tur-	day's
s {	t @r	d i: z
sa-	turn
s {	t @r n
sa-	turn's
s {	t @r n z
sa-	va
s Q	v V
sa-	va-	ge-	ry
s {	v I	dZ e@	i:
sa-	va-	ges
s {	v V	dZ V z
sa-	va-	ging
s {	v I	dZ I N
sa-	vage
s {	v I dZ
sa-	vage-	ly
s {	v I dZ	l i:
sa-	vaged
s {	v I dZ d
sa-	van-	na
s V	v {	n V
sa-	van-	nah
s V	v {	n V
sa-	van-	nas
s V	v {	n V z
sa-	vant
s V	v Q n t
sa-	vants
s {	v V n t s
sa-	vas
s Q	v Q z
sa-	ve-	ry
s eI	v @r	i:
sa-	vell
s Q	v eI l
sa-	ver
s eI	v @r
sa-	vers
s eI	v @r z
sa-	vi-	na
s V	v i:	n V
sa-	vill
s Q	v i: l
sa-	ville
s Q	v I l
sa-	vin
s {	v I n
sa-	ving
s eI	v I N
sa-	vings
s eI	v I N z
sa-	vin's
s {	v I n z
sa-	vior
s eI v	j @r
sa-	viors
s eI v	j @r z
sa-	vior's
s eI v	j @r z
sa-	vitt
s V	v I t
sa-	vo-	na
s Q	v @U	n V
sa-	vo-	ring
s eI	v @r	I N
sa-	vo-	ry
s eI	v @r	i:
sa-	voie
s Q v	w Q
sa-	vor
s eI	v @r
sa-	vored
s eI	v @r d
sa-	vors
s eI	v @r z
sa-	voy
s V	v OI
sa-	wing
s O:	I N
sa-	xe-	na
s { k	s V	n V
sa-	xo-	ny
s { k	s V	n i:
sa-	xo-	pho-	nist
s { k	s V	f @U	n I s t
sa-	xo-	phone
s { k	s V	f @U n
sa-	xo-	phones
s { k	s V	f @U n z
sa-	xon
s { k	s V n
sa-	xons
s { k	s V n z
sa-	xon's
s { k	s V n z
sa-	yed
s Q	j e d
sa-	yer
s eI	@r
sa-	yers
s eI	@r z
sa-	ying
s eI	I N
sa-	yings
s eI	I N z
saa-	ri-	nen
s Q@	I	n e n
saab
s Q b
saab's
s Q b z
saad
s Q d
saam
s Q m
saar
s Q@
saat-	chi
s Q	tS i:
sab-	ba-	ti-	cal
s V	b {	t I	k V l
sab-	bath
s {	b V T
sab-	ra
s Q b	r V
sab-	ri-	na
s V b	r i:	n V
sab's
s { b z
sac
s { k
sac-	cha-	rin
s {	k @r	I n
sac-	cha-	rine
s {	k @r	aI n
sac-	co
s {	k @U
sac-	co's
s {	k @U z
sac-	cule
s { k	j u: l
sac-	king
s {	k I N
sac-	ra
s { k	r V
sac-	ra-	men-	to
s { k	r V	m e n	t @U
sac-	ra-	men-	to's
s { k	r V	m e n	t @U z
sac-	ra-	ment
s { k	r V	m V n t
sac-	ra-	ments
s { k	r V	m V n t s
)"
R"(sac-	red
s eI k	r V d
sac-	red-	ness
s eI k	r V d	n V s
sac-	ri-	fi-	ces
s { k	r I	f aI	s V z
sac-	ri-	fi-	cial
s { k	r I	f I	S V l
sac-	ri-	fi-	cing
s { k	r I	f aI	s I N
sac-	ri-	fice
s { k	r I	f aI s
sac-	ri-	ficed
s { k	r I	f aI s t
sac-	ri-	le-	gious
s { k	r I	l e	dZ V s
sac-	ri-	lege
s { k	r I	l I dZ
sac-	ro-	sanct
s { k	r @U	s { N k t
sach-	s's
s { k	s V z
sachs
s { k s
sack
s { k
sack-	man
s { k	m V n
sack-	ville
s { k	v I l
sacked
s { k t
sacks
s { k s
sacs
s { k s
sad
s { d
sad-	d-	ler
s {	d V	l @r
sad-	d-	ling
s {	d V	l I N
sad-	dam
s Q	d V m
sad-	dam's
s Q	d V m z
sad-	de-	ning
s {	d V	n I N
sad-	den
s {	d V n
sad-	dened
s {	d V n d
sad-	dens
s {	d V n z
sad-	der
s {	d @r
sad-	dest
s {	d V s t
sad-	dle
s {	d V l
sad-	dle-	bag
s {	d V l	b { g
sad-	dle-	bags
s {	d V l	b { g z
sad-	dled
s {	d V l d
sad-	dles
s {	d V l z
sad-	ler
s { d	l @r
sad-	ly
s { d	l i:
sad-	ness
s { d	n V s
sae-	ger
s e	g @r
saf-	fell
s {	f V l
saf-	ford
s {	f @r d
saf-	ko
s Q f	k @U
safe
s eI f
safe-	guar-	ded
s eI f	g Q@	d V d
safe-	guar-	ding
s eI f	g Q@	d I N
safe-	guard
s eI f	g Q@ d
safe-	guards
s eI f	g Q@ d z
safe-	kee-	ping
s eI f	k i:	p I N
safe-	ly
s eI f	l i:
safe-	ty
s eI f	t i:
safe-	ty's
s eI f	t i: z
safe-	way
s eI f	w eI
safe-	way's
s eI f	w eI z
safes
s eI f s
saff-	lo-	wer
s { f	l aU	@r
saff-	ron
s { f	r V n
sag
s { g
sag-	ging
s {	g I N
sage
s eI dZ
sage-	brush
s eI dZ	b r V S
sagged
s { g d
sags
s { g z
sai
s aI
sai-	gon
s aI	g Q n
sai-	ler
s eI	l @r
sai-	ling
s eI	l I N
sai-	lor
s eI	l @r
sai-	lors
s eI	l @r z
sai-	lor's
s eI	l @r z
sai-	pan
s eI	p V n
sai-	pan's
s eI	p V n z
sai-	to
s eI	t @U
said
s e d
sail
s eI l
sail-	boat
s eI l	b @U t
sail-	boats
s eI l	b @U t s
sail-	fish
s eI l	f I S
sailed
s eI l d
sails
s eI l z
sain
s eI n
sain-	ted
s eI n	t V d
saine
s eI n
sains-	bu-	ry
s eI n	s b e@	i:
saint
s eI n t
saint-	hood
s eI n	t h U d
saint-	ly
s eI n	t l i:
saints
s eI n t s
saint's
s eI n t s
saints'
s eI n t s
sais
s eI z
sak
s { k
sak-	ha-	lin
s { k	h V	l V n
sak-	ha-	rov
s Q	k @r	Q v
sake
s eI k
sakes
s eI k s
saks
s { k s
sal
s { l
sal-	lade
s {	l eI d
sal-	lee
s {	l i:
sal-	ley
s {	l i:
sal-	lie
s {	l i:
sal-	lies
s {	l i: z
sal-	lis
s {	l I s
sal-	ly
s {	l i:
sal-	ly's
s {	l i: z
sal-	man
s {	m V n
sal-	mi
s Q l	m i:
sal-	mi-	nen
s { l	m I	n e n
sal-	mo-	nel-	la
s { l	m V	n e	l V
sal-	mon
s {	m V n
sal-	mons
s {	m V n z
sal-	sa
s O: l	s V
sal-	ta-	rel-	li
s O: l	t Q@	e	l i:
sal-	ted
s O: l	t V d
sal-	ter
s O: l	t @r
sal-	ters
s O: l	t @r z
sal-	ter's
s O: l	t @r z
sal-	ti-	er
s O: l	t i:	@r
sal-	ting
s O: l	t I N
sal-	ton
s O: l	t V n
sal-	ty
s O: l	t i:
sal-	va
s Q l	v V
sal-	va-	do-	ran
s { l	v V	d O@	V n
sal-	va-	do-	rans
s { l	v V	d O@	V n z
sal-	va-	do-	re
s Q l	v Q	d O@	eI
sal-	va-	dor
s { l	v V	d O@
sal-	va-	dor's
s { l	v V	d O@ z
sal-	va-	gea-	ble
s { l	v I	dZ V	b V l
sal-	va-	ger
s { l	v I	dZ @r
sal-	va-	gers
s { l	v I	dZ @r z
sal-	va-	ging
s { l	v I	dZ I N
sal-	va-	tion
s { l	v eI	S V n
sal-	va-	to-	re
s { l	v V	t O@	i:
sal-	vage
s { l	v V dZ
sal-	vaged
s { l	v I dZ d
sal-	vi-	a
s { l	v i:	V
sal-	vo
s { l	v @U
sal-	vos
s { l	v @U z
sal-	vuc-	ci
s Q l	v u:	tS i:
sale
s eI l
sales
s eI l z
sale's
s eI l z
sales-	man
s eI l	z m V n
sales-	man-	ship
s eI l	z m V n	S I p
sales-	man's
s eI l	z m V n z
sales-	men
s eI l	z m e n
sales-	peo-	ple
s eI l	z p i:	p V l
sales-	per-	son
s eI l	z p @r	s V n
sales-	wo-	man
s eI l	z w U	m V n
sales-	wo-	men
s eI l	z w I	m V n
salis-	bu-	ry
s { l	z b @r	i:
salk
s O: k
salk's
s O: k s
sall
s O: l
salle
s eI l
salm
s Q m
sal's
s { l z
sals-	bu-	ry
s { l	z b @r	i:
salt
s O: l t
salt-	box
s O: l	t b Q k s
salt-	like
s O: l	t l aI k
salt-	marsh
s O: l	t m Q@ S
salt-	wa-	ter
s O: l	t w Q	t @r
salts
s O: l t s
salts-	man
s O: l	t s m V n
saltz-	man
s O: l	t s m V n
salve
s Q v
salves
s Q v z
salz
s O: l z
salz-	burg
s O: l	z b @r g
salz-	git-	ter
s O: l	t s g I	t @r
salz-	hauer
s O: l	t s h aU r
sam
s { m
sam-	ba
s Q m	b V
sam-	bo
s { m	b @U
sam-	bre
s { m	b r V
sam-	bu-	ca
s { m	b j u:	k V
sam-	ford
s { m	f @r d
sam-	mie
s {	m i:
sam-	mons
s {	m V n z
sam-	my
s {	m i:
sam-	pan
s { m	p { n
sam-	pans
s { m	p { n z
sam-	ple
s { m	p V l
sam-	pled
s { m	p V l d
sam-	ples
s { m	p V l z
sam-	ple's
s { m	p V l z
sam-	sa-	ra
s V m	s Q@	V
sam-	so-	nite
s { m	s V	n aI t
sam-	son
s { m	s V n
sam-	sung
s { m	s V N
same
s eI m
same-	ness
s eI m	n V s
sames
s eI m z
samp
s { m p
samp-	ler
s { m	p l @r
samp-	lers
s { m	p l @r z
samp-	ling
s { m	p l I N
samp-	lings
s { m	p l I N z
samp-	ra-	s's
s { m	p r V	s V z
samp-	ras
s { m	p r V s
samp-	son
s { m	p s V n
sams
s { m z
sam's
s { m z
san
s { n
san-	born
s { n	b O@ n
san-	che-	z's
s { n	tS e	z V z
san-	chez
s { n	tS e z
san-	cho
s Q n	k @U
san-	dal
s { n	d V l
san-	dals
s { n	d V l z
san-	ded
s { n	d V d
san-	dell
s { n	d e l
san-	der
s { n	d @r
san-	der-	son
s { n	d @r	s V n
san-	ders
s { n	d @r z
san-	di
s { n	d i:
san-	di-	a
s { n	d i:	V
san-	di-	nis-	ta
s { n	d I	n I s	t V
san-	di-	nis-	tas
s { n	d I	n i: s	t V z
san-	die
s { n	d i:
san-	ding
s { n	d I N
san-	do-	val
s { n	d @U	v V l
san-	don
s { n	d O: n
san-	dor
s { n	d @r
san-	dus-	ky
s { n	d V s	k i:
san-	dy
s { n	d i:
san-	dy's
s { n	d i: z
san-	ford
s { n	f @r d
san-	ford's
s { n	f @r d z
san-	ger
s {	N @r
san-	gi-	o-	vese
s { n	dZ i:	@U	v i: s
san-	guine
s { N	g w I n
san-	jay
s { n	dZ eI
san-	jiv
s Q n	dZ i: v
san-	ka
s { N	k V
san-	key
s { N	k i:
san-	ko
s { N	k @U
san-	som
s { n	s V m
san-	son
s { n	s V n
san-	sone
s { n	s V n
san-	ta
s { n	t V
san-	ta-	na
s { n	t {	n V
san-	ta-	ya-	na
s { n	t aI	Q	n V
san-	tan-	der
s { n	t { n	d @r
san-	ta's
s { n	t V
san-	te-	ri-	a
s { n	t e@	i:	V
san-	ter
s { n	t @r
san-	ti-	a-	go
s { n	t i:	Q	g @U
san-	ti-	ni
s { n	t i:	n i:
san-	to
s { n	t @U
san-	to-	ro
s { n	t O@	@U
san-	ton
s { n	t V n
san-	tos
s { n	t @U s
san-	ty
s { n	t i:
san-	wa
s { n	w V
sanc-	ti-	fi-	ca-	tion
s { N	k t I	f I	k eI	S V n
sanc-	ti-	fy
s { N	k t I	f aI
sanc-	ti-	mo-	ni-	ous
s { N	k t I	m @U	n i:	V s
sanc-	ti-	mo-	ny
s { N	k t I	m @U	n i:
sanc-	ti-	ty
s { N	k t I	t i:
sanc-	tio-	ning
s { N	k S V	n I N
sanc-	tion
s { N	k S V n
sanc-	tioned
s { N	k S V n d
sanc-	tions
s { N	k S V n z
sanc-	tu-	a-	ries
s { N	k tS u:	e@	i: z
sanc-	tu-	a-	ry
s { N	k tS u:	e@	i:
sanc-	tum
s { N	k t V m
sand
s { n d
sand-	bag
s { n	d b { g
sand-	bag-	ger
s { n	d b {	g @r
sand-	bag-	gers
s { n	d b {	g @r z
sand-	bag-	ging
s { n	d b {	g I N
sand-	bagged
s { n	d b { g d
sand-	bags
s { n	d b { g z
sand-	bar
s { n	d b Q@
sand-	berg
s { n	d b @r g
sand-	box
s { n	d b Q k s
sand-	burg
s { n	d b @r g
sand-	hill
s { n	d h I l
sand-	hog
s { n	d h O: g
sand-	hogs
s { n	d h O: g z
sand-	ler
s { n	d l @r
sand-	ling
s { d	l I N
sand-	man
s { n	d m { n
sand-	pa-	per
s { n	d p eI	p @r
sand-	point
s { n	d p OI n t
sand-	ra
s { n	d r V
sand-	ro
s { n	d r @U
sand-	rock
s { n	d r Q k
sand-	stone
s { n	d s t @U n
sand-	storm
s { n	d s t O@ m
sand-	storms
s { n	d s t O@ m z
sand-	strom
s { n	d s t r V m
sand-	wi-	ches
s { n	d w I	tS V z
sand-	wich
s { n	d w I tS
sand-	wiched
s { n	d w I tS t
sandb-	las-	ted
s { n	d b l { s	t V d
sandb-	last
s { n	d b l { s t
sande
s { n d
sands
s { n d z
sand's
s { n d z
sane
s eI n
sang
s { N
sank
s { N k
sans
s { n z
sans-	bu-	ry
s { n	s b e@	i:
sansk-	rit
s { n	s k r I t
sant
s { n t
sao
s aU
sap
s { p
sap-	ling
s { p	l I N
sap-	lings
s { p	l I N z
sap-	per
s {	p @r
sap-	phi-	re
s {	f aI	@r
sap-	ping
s {	p I N
sap-	po-	ro
s V	p O@	@U
sapped
s { p t
saps
s { p s
sar
s Q@
sar-	ca-	sm
s Q@	k {	z V m
sar-	cas-	tic
s Q@	k { s	t I k
sar-	cas-	tical-	ly
s Q@	k { s	t I k	l i:
sar-	chet
s Q@	S e t
sar-	co-	ma
s Q@	k @U	m @r
sar-	co-	pha-	gus
s Q@	k Q	f V	g V s
sar-	del-	la
s Q@	d e	l V
sar-	di-	na
s Q@	d i:	n V
sar-	di-	ni-	a
s Q@	d i:	n i:	V
sar-	dine
s Q@	d i: n
sar-	dines
s Q@	d i: n z
sar-	do
s Q@	d @U
sar-	do-	ni-	cal-	ly
s Q@	d Q	n I	k V	l i:
sar-	do-	nic
s Q@	d Q	n I k
sar-	gas-	so
s Q@	g {	s @U
sar-	geant
s Q@	dZ V n t
sar-	gent
s Q@	dZ V n t
sar-	kar
s Q@	k Q@
sar-	kis
s Q@	k I s
sar-	ma-	tian
s Q@	m eI	S V n
sar-	na
s Q@	n V
sar-	ney
s Q@	n i:
sar-	noff
s Q@	n O: f
sar-	ra
s Q@	V
sar-	ra-	zin
s Q@	V	z I n
sar-	tain
s Q@	t eI n
sar-	ti
s Q@	t i:
sar-	tin
s Q@	t I n
sar-	to-	ri-	al
s Q@	t O@	i:	V l
sar-	to-	ri-	us
s Q@	t O@	i:	V s
sar-	tor
s Q@	t @r
sar-	tre
s Q@ t	r V
sar-	ver
s Q@	v @r
sare
s e@
sarge
s Q@ dZ
sark
s Q@ k
sarles
s Q@ l z
sars
s Q@ z
sas
s { s
sas-	ka-	toon
s { s	k V	t u: n
sas-	kat-	che-	wan
s { s	k {	tS V	w O: n
sas-	nett
s { s	n e t
sas-	sa-	fra-	s's
s {	s V f	r {	s V z
sas-	sa-	fras
s {	s V f	r { s
sas-	ser
s {	s @r
sas-	ser's
s {	s @r z
sas-	soon
s V	s u: n
sas-	sy
s {	s i:
sash
s { S
sass
s { s
sasse
s { s
sat
s { t
sat-	ter-	field
s {	t @r	f i: l d
sat-	ter-	lee
s {	t @r	l i:
sat-	ya
s Q t	j V
sate
s eI t
sates
s eI t s
sau-	cer
s O:	s @r
sau-	cers
s O:	s @r z
sau-	ces
s O:	s V z
sau-	ci-	er
s O:	s i:	@r
sau-	cy
s O:	s i:
sau-	der
s O:	d @r
sau-	di
s O:	d i:
sau-	dis
s O:	d i: z
sau-	er
s aU	@r
sau-	er-	kraut
s aU	@r k	r aU t
sau-	ers
s aU	@r z
sau-	ger-	ties
s O:	g @r	t i: z
sau-	na
s O:	n V
sau-	nas
s O:	n V z
sau-	sa-	ges
s O:	s I	dZ V z
sau-	sa-	li-	to
s O:	s V	l i:	t @U
sau-	sage
s O:	s V dZ
sau-	te
s O:	t eI
sau-	te-	r
s O:	t eI	@r
sau-	teed
s O:	t eI d
sau-	terne
s @U	t @r n
sau-	ternes
s @U	t @r n z
sau-	vig-	non
s O:	v I n	j Q n
sauce
s O: s
sauce-	pan
s O: s	p { n
saud
s O: d
sauk
s O: k
saul
s O: l
saul-	ter
s O: l	t @r
sauls
s O: l z
sauls-	bu-	ry
s O: l	s b e@	i:
sault
s O: l t
saum
s O: m
saun-	der-	son
s O: n	d @r	s V n
saun-	ders
s O: n	d @r z
saun-	dra
s O: n	d r V
saun-	dra's
s O: n	d r V z
saun-	ter
s O: n	t @r
saur
s O@
sauve
s O: v
sav-	vi-	est
s {	v i:	V s t
sav-	vy
s {	v i:
save
s eI v
saved
s eI v d
saves
s eI v z
save's
s eI v z
saw
s O:
saw-	dust
s O:	d V s t
saw-	mill
s O:	m I l
saw-	mills
s O:	m I l z
saw-	telle
s O:	t e l
saw-	yer
s O:	j @r
saw-	yers
s O:	j @r z
saw-	yer's
s O:	j @r z
sawed
s O: d
saws
s O: z
sax
s { k s
sax-	ton
s { k	s t V n
saxe
s { k s
say
s eI
say-	brook
s eI b	r U k
say-	lor
s eI	l @r
say-	yid
s aI	I d
saye
s eI
sayles
s eI l z
sayre
s e@
sayres
s e@ z
says
s e z
sca-	la
s k Q	l V
sca-	lar
s k eI	l @r
sca-	li-	a
s k Q	l i:	V
sca-	li-	a's
s k Q	l i:	V z
sca-	ling
s k eI	l I N
sca-	ni-	a
s k Q	n i:	V
sca-	pa
s k Q	p V
sca-	pu-	la
s k { p	j V	l V
sca-	ra-	mouch
s k {	r V	m aU tS
sca-	ri-	er
s k e@	i:	@r
sca-	ri-	est
s k e@	i:	V s t
sca-	ring
s k e@	I N
sca-	ro-	la
s k Q@	@U	l V
sca-	ry
s k e@	i:
sca-	thing
s k eI	D I N
sca-	ven-	ger
s k {	v V n	dZ @r
sca-	ven-	gers
s k {	v V n	dZ @r z
sca-	ven-	ging
s k {	v V n	dZ I N
sca-	venge
s k {	v V n dZ
scab
s k { b
scab-	bard
s k {	b @r d
scabs
s k { b z
scad
s k { d
scads
s k { d z
scaf-	fol-	ding
s k {	f V l	d I N
scaf-	fold
s k {	f V l d
scaf-	folds
s k {	f V l d z
scaff
s k { f
scags
s k { g z
scaife
s k eI f
scal-	ded
s k O: l	d V d
scal-	ding
s k O: l	d I N
scal-	lion
s k { l	j V n
scal-	lions
s k { l	j V n z
scal-	lop
s k {	l V p
scal-	loped
s k Q	l V p t
scal-	lops
s k {	l V p s
scal-	ly
s k {	l i:
scal-	pel
s k { l	p V l
scal-	pels
s k { l	p V l z
scal-	per
s k { l	p @r
scal-	pers
s k { l	p @r z
scal-	ping
s k { l	p I N
scald
s k O: l d
scalds
s k O: l d z
scale
s k eI l
scaled
s k eI l d
scales
s k eI l z
scalf
s k { l f
scalp
s k { l p
scalped
s k { l p t
scalps
s k { l p s
scam
s k { m
scam-	mer
s k {	m @r
scam-	mers
s k {	m @r z
scam-	mon
s k {	m V n
scam-	pe-	ring
s k { m	p @r	I N
scam-	per
s k { m	p @r
scam-	pered
s k { m	p @r d
scammed
s k { m d
scams
s k { m z
scan
s k { n
scan-	da-	lize
s k { n	d V	l aI z
scan-	da-	lized
s k { n	d V	l aI z d
scan-	da-	lous
s k { n	d V	l V s
scan-	dal
s k { n	d V l
scan-	dals
s k { n	d V l z
scan-	dal's
s k { n	d V l z
scan-	di-	a
s k { n	d i:	V
scan-	di-	na-	vi-	a
s k { n	d I	n eI	v i:	V
scan-	di-	na-	vi-	an
s k { n	d I	n eI	v i:	V n
scan-	di-	na-	vi-	ans
s k { n	d I	n eI	v i:	V n z
scan-	di-	na-	vi-	a's
s k { n	d I	n eI	v i:	V z
scan-	ner
s k {	n @r
scan-	ners
s k {	n @r z
scan-	ning
s k {	n I N
scan-	ti-	ly
s k { n	t I	l i:
scan-	ti-	ness
s k { n	t i:	n e s
scan-	ty
s k { n	t i:
scanned
s k { n d
scans
s k { n z
scant
s k { n t
scape
s k eI p
scape-	goa-	ted
s k eI p	g @U	t V d
scape-	goa-	ting
s k eI p	g @U	t I N
scape-	goat
s k eI p	g @U t
scape-	goats
s k eI p	g @U t s
scar
s k Q@
scar-	bo-	rough
s k Q@	b @r	@U
scar-	cer
s k e@	s @r
scar-	ci-	ty
s k e@	s I	t i:
scar-	face
s k Q@	f eI s
scar-	gill
s k Q@	g I l
scar-	let
s k Q@	l V t
scar-	lett
s k Q@	l e t
scar-	pa
s k Q@	p V
scar-	ring
s k Q@	I N
scar-	ry
s k {	r i:
scarb-	ro
s k Q@ b	r @U
scarce
s k e@ s
scarce-	ly
s k e@ s	l i:
scare
s k e@
scare-	crow
s k { r	k r @U
scared
s k e@ d
scares
s k e@ z
scarf
s k Q@ f
scarfs
s k Q@ f s
scarp
s k Q@ p
scarred
s k Q@ d
scars
s k Q@ z
scars-	dale
s k Q@ z	d eI l
scarves
s k Q@ v z
scat
s k { t
scat-	te-	ring
s k {	t @r	I N
scat-	ter
s k {	t @r
scat-	ter-	good
s k {	t @r	g U d
scat-	ter-	shot
s k {	t @r	S Q t
scat-	tered
s k {	t @r d
sce-	na-	ri-	o
s V	n e@	i:	@U
sce-	na-	ri-	os
s V	n e@	i:	@U z
sce-	ne-	ries
s i:	n @r	i: z
sce-	ne-	ry
s i:	n @r	i:
sce-	nic
s i:	n I k
scen-	ted
s e n	t V d
scene
s i: n
scenes
s i: n z
scent
s e n t
scents
s e n t s
scep-	tre
s e p	t @r
scha-	fer
S eI	f @r
scha-	per
S eI	p @r
scha-	pi-	ro
S {	p aI	r @U
schaab
S Q b
schacht
S { k t
schae-	fer
S eI	f @r
schaef-	fer
S e	f @r
schaf-	fer
S eI	f @r
schaff-	ner
S { f	n @r
schal-	ler
S O:	l @r
schantz
S { n t s
schanz
S { n s
scharf
S Q@ f
scharff
S Q@ f
scharn-	horst
S Q@ n	h O@ s t
schatz
S { t s
schaum-	burg
S aU m	b @r g
sche-	du-	ler
s k e d	dZ U	l @r
sche-	du-	lers
s k e d	dZ U	l @r z
sche-	du-	ling
s k e	dZ U	l I N
sche-	dule
s k e	dZ U l
sche-	duled
s k e	dZ U l d
sche-	dules
s k e	dZ U l z
sche-	ler
S i:	l @r
sche-	ma-	ta
s k V	m {	t V
sche-	ma-	tic
s k V	m {	t I k
sche-	mer
s k i:	m @r
sche-	ming
s k i:	m I N
sche-	nec-	ta-	dy
s k V	n e k	t V	d i:
sche-	nec-	ta-	dy's
s k V	n e k	t V	d i: z
schear
S I@
schec-	ter
S e k	t @r
schech-	ter
S e k	t @r
scheck
S e k
scheel
S i: l
scheele
S i: l
scheer
S I@
schef-	fel
S e	f V l
schei-	der
S aI	d @r
schei-	ner
S aI	n @r
scheidt
S aI t
schein
S aI n
schel-	ler
s k e	l @r
schel-	ling
s k e	l I N
schell
s k e l
scheme
s k i: m
schemed
s k i: m d
schemes
s k i: m z
schen-	ley
S e n	l i:
schenck
S e N k
schenk
S e N k
scher-	man
S @r	m V n
schertz
S @r t s
schi-	a-	vo-	ne
s k i:	Q	v @U	n i:
schi-	a-	vo-	ni
s k i:	Q	v @U	n i:
schi-	ro
s k I@	@U
schi-	sm
s k I	z V m
schi-	sms
s k I	z V m z
schi-	zoph-	re-	ni-	a
s k I t	s V f	r i:	n i:	V
schi-	zoph-	re-	nic
S I	z V f	r e	n I k
schick
S I k
schiele
S i: l
schiff
S I f
schiff-	man
S I f	m V n
schil-	ler
S I	l @r
schil-	ler's
S I	l @r z
schil-	ling
S I	l I N
schil-	lings
S I	l I N z
schil-	ling's
S I	l I N z
schild
S aI l d
schilt
S I l t
schim-	mel
S I	m V l
schind-	ler
S I n	d l @r
schind-	ler's
S I n	d l @r z
schip-	pers
S I	p @r z
schist
S I s t
schists
S I s t s
schla-	ter
S l eI	t @r
schlang
S l { N
schle-	gel
S l eI	g V l
schle-	sin-	ger
S l e	s I n	dZ @r
schlepp
S l e p
schles-	sin-	ger
S l e	s I n	dZ @r
schles-	wig
S l e s	w I g
schley
S l eI
schli-	cher
S l I	k @r
schlick
S l I k
schlitz
S l I t s
schlock
S l Q k
schlos-	ser
S l O:	s @r
schloss
S l O: s
schlu-	ter
S l u:	t @r
schmaltz
S m Q l t s
schmalz
S m O: l z
schme-	ling
S m e	l I N
schmeck
S m e k
schmelt-	zer
S m e l	t z @r
schmelz
S m e l z
schmidt
S m I t
schmidt's
S m I t s
schmitt
S m I t
schmitz
S m I t s
schmoo-	zing
S m u:	z I N
schmooze
S m u: z
schmuck
S m V k
schna-	bel
S n {	b V l
schnapp
S n { p
schnapps
S n { p s
schnau-	zer
S n aU	z @r
schnei-	der
S n aI	d @r
schnei-	der-	man
S n aI	d @r	m V n
schnei-	der-	man's
S n aI	d @r	m V n z
schnei-	der's
S n aI	d @r z
schnell
S n e l
schnitt-	ke
S n I t	k i:
schnitz
S n I t s
schnitz-	ler
S n I t	s l @r
schnook
S n U k
schnooks
S n U k s
schnorr
S n O@
schnur
S n @r
schnurr
S n @r
scho-	ber
S @U	b @r
scho-	e-	ning
S Q	V	n I N
scho-	field
s k @U	f i: l d
scho-	lar
s k Q	l @r
scho-	lar-	ly
s k Q	l @r	l i:
scho-	lar-	ship
s k Q	l @r	S I p
scho-	lar-	ships
s k Q	l @r	S I p s
)"
R"(scho-	lars
s k Q	l @r z
scho-	lar's
s k Q	l @r z
scho-	las-	tic
s k V	l { s	t I k
scho-	u-	ten
S Q	u:	t V n
schoen-	berg
S @U n	b @r g
schoen-	fel-	der
S @U n	f e l	d @r
scholz
S @U l z
schon-	berg
S Q n	b @r g
schon-	feld
S Q n	f e l d
schone
S @U n
schoo-	ler
s k u:	l @r
schoo-	lers
s k u:	l @r z
schoo-	ling
s k u:	l I N
schoo-	ner
s k u:	n @r
schoo-	ners
s k u:	n @r z
schoof
S U f
school
s k u: l
school-	book
s k u: l	b U k
school-	books
s k u: l	b U k s
school-	boy
s k u: l	b OI
school-	boys
s k u: l	b OI z
school-	child
s k u: l	tS aI l d
school-	child-	ren
s k u: l	tS I l	d r V n
school-	craft
s k u: l	k r { f t
school-	house
s k u: l	h aU s
school-	mas-	ter
s k u: l	m { s	t @r
school-	mate
s k u: l	m eI t
school-	mates
s k u: l	m eI t s
school-	room
s k u: l	r u: m
school-	tea-	cher
s k u: l	t i:	tS @r
school-	tea-	chers
s k u: l	t i:	tS @r z
school-	time
s k u: l	t aI m
school-	work
s k u: l	w @r k
school-	yard
s k u: l	j Q@ d
schooled
s k u: l d
schools
s k u: l z
school's
s k u: l z
schoon
s k u: n
schott
S Q t
schott's
S Q t s
schou
S u:
schow
S aU
schra-	der
S r eI	d @r
schram
S r { m
schrank
S r { N k
schreck
S r e k
schrei-	ber
S r aI	b @r
schrei-	ner
S r aI	n @r
schreib-	man
S r aI b	m V n
schrick
S r I k
schrie-	ver
S r i:	v @r
schro-	der
S r @U	d @r
schro-	er
S r @U	@r
schroe-	der
S r @U	d @r
schroe-	der's
S r @U	d @r z
schroth
S r O: T
schtick
S t I k
schu-	bert
S u:	b @r t
schu-	bert's
S u:	b @r t s
schu-	len-	burg
S u:	l V n	b @r g
schu-	ler
S u:	l @r
schu-	ma-	cher
S u:	m Q	k @r
schu-	man
S u:	m V n
schu-	mann
S u:	m V n
schu-	mann's
S u:	m V n z
schu-	mer
S u:	m @r
schu-	mer's
S u:	m @r z
schug
S V g
schuh
S u:
schul
S U l
schul-	man
S u: l	m V n
schultz
S U l t s
schultze
S V l t z
schulz
S U l t s
schulze
S U l t s
schur-	man
S @r	m V n
schus-	ter
S u: s	t @r
schuy-	ler
s k aI	l @r
schuyl-	kill
s k j u: l	k I l
schwab
S w Q b
schwab's
S w Q b z
schwar-	ze-	neg-	ger
S w O@	z V	n eI	g @r
schwar-	ze-	neg-	ger's
S w O@	z V	n eI	g @r z
schwar-	zkopf
S w O@ t	s k O: p f
schwar-	zkopf's
S w O@ t	s k O: p f s
schwartz
S w O@ t s
schwarz
S w O@ t s
schwe-	rin
S w e@	I n
schwei-	zer
S w aI	z @r
schweit-	zer
S w aI t	s @r
schweit-	zer's
S w aI t	s @r z
schwenk
S w e N k
schweppes
S w e p s
schwert-	ner
S w @r t	n @r
schwin-	ger
S w I	N @r
schwing
S w I N
schwinn
S w I n
sci
s i:
sci-	en-	ces
s aI	V n	s V z
sci-	en-	ce's
s aI	V n	s V z
sci-	en-	ti-	fi-	cal-	ly
s aI	V n	t I	f I	k V	l i:
sci-	en-	ti-	fic
s aI	V n	t I	f I k
sci-	en-	ti-	fic's
s aI	V n	t I	f I k s
sci-	en-	tist
s aI	V n	t V s t
sci-	en-	tists
s aI	V n	t V s t s
sci-	en-	tist's
s aI	V n	t V s t s
sci-	en-	to-	lo-	gist
s aI	e n	t Q	l V	dZ I s t
sci-	en-	to-	lo-	gists
s aI	e n	t Q	l V	dZ I s t s
sci-	en-	to-	lo-	gy
s aI	V n	t Q	l V	dZ i:
sci-	ence
s aI	V n s
sci-	mone
s V	m @U n
sci-	on
s aI	V n
sci-	pi-	o
s I	p i:	@U
scia-	ra
S Q@	V
scil-	la
s I	l V
scil-	las
s I	l V z
scin-	til-	la
s I n	t I	l V
scire
s aI r
scis-	sor
s I	z @r
scis-	sors
s I	z @r z
scle-	ro-	der-	ma
s k l I@	V	d @r	m V
scle-	ro-	sis
s k l @r	@U	s I s
sco-	bey
s k @U	b i:
sco-	field
s k @U	f i: l d
sco-	lia
s k @U l	j V
sco-	ping
s k @U	p I N
sco-	po-	la-	mine
s k O:	p V	l V	m i: n
sco-	rer
s k O@	@r
sco-	rers
s k O@	@r z
sco-	ring
s k O@	I N
sco-	tia
s k @U	S V
sco-	tia's
s k @U	S V z
sco-	ur
s k aU	@r
sco-	vel
s k @U	v V l
sco-	ville
s k @U	v I l
scof-	flaws
s k Q f	l O: z
scoff
s k O: f
scoffed
s k O: f t
scoffs
s k O: f s
scog-	gin
s k Q	g I n
scol-	ded
s k @U l	d V d
scol-	ding
s k @U l	d I N
scold
s k @U l d
scolds
s k @U l d z
scoles
s k @U l z
scon-	ces
s k Q n	s V z
sconce
s k Q n s
scone
s k @U n
scones
s k @U n z
scoo-	per
s k u:	p @r
scoo-	ping
s k u:	p I N
scoo-	ter
s k u:	t @r
scoo-	ters
s k u:	t @r z
scoop
s k u: p
scooped
s k u: p t
scoops
s k u: p s
scoot
s k u: t
scoots
s k u: t s
scope
s k @U p
scopes
s k @U p s
scor-	cher
s k O@	tS @r
scor-	ching
s k O@	tS I N
scor-	pi-	o
s k O@	p i:	@U
scor-	pi-	on
s k O@	p i:	V n
scor-	pi-	ons
s k O@	p i:	V n z
scor-	se-	se's
s k O@	s i:	z V z
scor-	sese
s k O@	s i: z
scor-	za
s k O@	z V
scorch
s k O@ tS
scorched
s k O@ tS t
score
s k O@
score-	board
s k O@	b O@ d
score-	card
s k O@	k Q@ d
score-	cards
s k O@	k Q@ d z
score-	kee-	per
s k O@	k i:	p @r
score-	kee-	pers
s k O@	k i:	p @r z
score-	kee-	ping
s k O@	k i:	p I N
score-	less
s k O@	l V s
scored
s k O@ d
scores
s k O@ z
scorn
s k O@ n
scorn-	ful
s k O@ n	f V l
scorned
s k O@ n d
scorns
s k O@ n z
scot
s k Q t
scot-	ches
s k Q	tS V z
scot-	land
s k Q t	l V n d
scot-	land's
s k Q t	l V n d z
scot-	tie
s k Q	t i:
scot-	tish
s k Q	t I S
scot-	to
s k @U	t @U
scot-	ty
s k Q	t i:
scot-	ty's
s k Q	t i: z
scotch
s k Q tS
scotch-	gard
s k Q tS	g Q@ d
scotched
s k Q tS t
scots
s k Q t s
scots-	man
s k Q t	s m V n
scott
s k Q t
scotts
s k Q t s
scott's
s k Q t s
scotts-	bluff
s k Q t	s b l V f
scotts-	dale
s k Q t	s d eI l
scou-	r-	ing
s k aU	@r	I N
scou-	red
s k aU	@r d
scou-	rs
s k aU	@r z
scou-	ted
s k aU	t V d
scou-	ter
s k aU	t @r
scou-	ters
s k aU	t @r z
scou-	ting
s k aU	t I N
scoun-	drel
s k aU n	d r V l
scoun-	drels
s k aU n	d r V l z
scour-	ges
s k @r	dZ V z
scourge
s k @r dZ
scout
s k aU t
scout-	mas-	ter
s k aU t	m { s	t @r
scouts
s k aU t s
scout's
s k aU t s
scow
s k aU
scow-	ling
s k aU	l I N
scowl
s k aU l
scowled
s k aU l d
scra-	per
s k r eI	p @r
scra-	pers
s k r eI	p @r z
scra-	ping
s k r eI	p I N
scra-	pings
s k r eI	p I N z
scra-	tches
s k r {	tS V z
scra-	tching
s k r {	tS I N
scra-	tchy
s k r {	tS i:
scrab-	ble
s k r {	b V l
scrag-	gle
s k r {	g V l
scragg-	ly
s k r { g	l i:
scram-	b-	ling
s k r { m	b V	l I N
scram-	ble
s k r { m	b V l
scram-	bled
s k r { m	b V l d
scram-	bles
s k r { m	b V l z
scran-	ton
s k r { n	t V n
scrap
s k r { p
scrap-	book
s k r { p	b U k
scrap-	books
s k r { p	b U k s
scrap-	ping
s k r {	p I N
scrap-	py
s k r {	p i:
scrape
s k r eI p
scraped
s k r eI p t
scrapes
s k r eI p s
scrapped
s k r { p t
scraps
s k r { p s
scratch
s k r { tS
scratched
s k r { tS t
scraw-	ny
s k r O:	n i:
scrawl
s k r O: l
scrawled
s k r O: l d
scre-	wy
s k r u:	i:
screa-	mer
s k r i:	m @r
screa-	mers
s k r i:	m @r z
screa-	ming
s k r i:	m I N
screa-	ming-	ly
s k r i:	m I N	l i:
scream
s k r i: m
screamed
s k r i: m d
screams
s k r i: m z
scree-	ches
s k r i:	tS V z
scree-	ching
s k r i:	tS I N
scree-	ner
s k r i:	n @r
scree-	ners
s k r i:	n @r z
scree-	ning
s k r i:	n I N
scree-	nings
s k r i:	n I N z
screech
s k r i: tS
screeched
s k r i: tS t
screed
s k r i: d
screen
s k r i: n
screen-	play
s k r i: n	p l eI
screen-	plays
s k r i: n	p l eI z
screen-	wri-	ter
s k r i: n	r aI	t @r
screen-	wri-	ters
s k r i: n	r aI	t @r z
screen-	wri-	ting
s k r i: n	r aI	t I N
screened
s k r i: n d
screens
s k r i: n z
screw
s k r u:
screw-	ball
s k r u:	b O: l
screw-	dri-	ver
s k r u: d	r aI	v @r
screw-	dri-	vers
s k r u: d	r aI	v @r z
screw-	ing
s k r u:	I N
screwed
s k r u: d
screws
s k r u: z
scri-	ber
s k r aI	b @r
scri-	ven
s k r I	v I n
scri-	vens
s k r aI	v V n z
scri-	ver
s k r aI	v @r
scrib-	b-	ling
s k r I	b V	l I N
scrib-	ble
s k r I	b V l
scrib-	bled
s k r I	b V l d
scrib-	bles
s k r I	b V l z
scrib-	ner
s k r I b	n @r
scrib-	ners
s k r I b	n @r z
scrib-	ner's
s k r I b	n @r z
scribb-	ler
s k r I b	l @r
scribb-	lers
s k r I b	l @r z
scribe
s k r aI b
scribes
s k r aI b z
scrim-	mage
s k r I	m I dZ
scrim-	ping
s k r I m	p I N
scrim-	shaw
s k r I m	S O:
scrimp
s k r I m p
scrip
s k r I p
scrip-	ted
s k r I p	t V d
scrip-	tu-	ral
s k r I p	tS @r	V l
scrip-	ture
s k r I p	tS @r
scrip-	tures
s k r I p	tS @r z
scripps
s k r I p s
script
s k r I p t
script-	wri-	ter
s k r I p	t r aI	t @r
script-	wri-	ters
s k r I p	t r aI	t @r z
script-	wri-	ting
s k r I p	t r aI	t I N
scripts
s k r I p t s
scrive-	ner
s k r I v	n @r
scrod
s k r Q d
scrog-	gins
s k r Q	g I n z
scroll
s k r @U l
scrolls
s k r @U l z
scrooge
s k r u: dZ
scroun-	ging
s k r aU n	dZ I N
scrounge
s k r aU n dZ
scrounged
s k r aU n dZ d
scru-	ple
s k r u:	p V l
scru-	ples
s k r u:	p V l z
scru-	pu-	lous
s k r u: p	j V	l V s
scru-	pu-	lous-	ly
s k r u: p	j V	l V s	l i:
scru-	ti-	ni-	zes
s k r u:	t I	n aI	z V z
scru-	ti-	ni-	zing
s k r u:	t I	n aI	z I N
scru-	ti-	nize
s k r u:	t I	n aI z
scru-	ti-	nized
s k r u:	t I	n aI z d
scru-	ti-	ny
s k r u:	t I	n i:
scrub
s k r V b
scrub-	ber
s k r V	b @r
scrub-	bers
s k r V	b @r z
scrub-	bing
s k r V	b I N
scrub-	by
s k r V	b i:
scrubbed
s k r V b d
scruf-	fy
s k r V	f i:
scruggs
s k r V g z
scrunch
s k r V n tS
scrunched
s k r V n tS t
scu-	ba
s k u:	b V
scud
s k V d
scud-	der
s k V	d @r
scuds
s k V d z
scuf-	fle
s k V	f V l
scuf-	fled
s k V	f V l d
scuf-	fles
s k V	f V l z
scuff
s k V f
scuffed
s k V f t
scul-	ley
s k V	l i:
scul-	ley's
s k V	l i: z
scul-	lin
s k V	l I n
scul-	lion
s k V l	j V n
scul-	ly
s k V	l i:
scull
s k V l
sculp-	ted
s k V l	p t V d
sculp-	ting
s k V l	p t I N
sculp-	tor
s k V l	p t @r
sculp-	tors
s k V l	p t @r z
sculp-	tu-	ral
s k V l	p tS @r	V l
sculp-	tu-	ring
s k V l	p t @r	I N
sculp-	ture
s k V l	p tS @r
sculp-	tured
s k V l	p tS @r d
sculp-	tures
s k V l	p tS @r z
sculpt
s k V l p t
sculpts
s k V l p t s
scum
s k V m
scup-	per
s k V	p @r
scur-	lock
s k @r	l V k
scur-	ri-	lous
s k @r	I	l V s
scur-	ried
s k @r	i: d
scur-	ry
s k @r	i:
scur-	ry-	ing
s k @r	i:	I N
scut-	t-	ling
s k V	t V	l I N
scut-	tle
s k V	t V l
scut-	tle-	butt
s k V	t V l	b V t
scut-	tled
s k V	t V l d
scutt
s k V t
scy-	thi-	an
s I	T i:	V n
se-	ance
s eI	Q n s
se-	at-	tle
s i:	{	t V l
se-	at-	tle's
s i:	{	t V l z
se-	ba-	ceous
s V	b eI	S V s
se-	bas-	ti-	a-	na
s V	b { s	t i:	Q	n V
se-	bas-	tian
s V	b { s	tS V n
se-	bas-	tian's
s V	b { s	tS V n z
se-	bree
s V b	r i:
se-	cau-	cus
s I	k O:	k V s
se-	ce-	ded
s V	s i:	d V d
se-	ce-	ding
s V	s i:	d I N
se-	cede
s V	s i: d
se-	ces-	sio-	nist
s V	s e	S V	n V s t
se-	ces-	sio-	nists
s V	s e	S V	n V s t s
se-	ces-	sion
s V	s e	S V n
se-	co
s e	k @U
se-	con-	da-	ri-	ly
s e	k V n	d e@	V	l i:
se-	con-	da-	ries
s e	k V n	d e@	i: z
se-	con-	da-	ry
s e	k V n	d e@	i:
se-	con-	ded
s e	k V n	d V d
se-	cond
s e	k V n d
se-	cond-	hand
s e	k V n	d h { n d
se-	cond-	ly
s e	k V n	d l i:
se-	conds
s e	k V n d z
se-	cor
s e	k @r
se-	cr-	est
s e	k @r	I s t
se-	cre-	cy
s i: k	r V	s i:
se-	cu-	la-	ri-	sm
s e k	j V	l @r	I	z V m
se-	cu-	la-	rist
s e k	j V	l @r	V s t
se-	cu-	la-	rists
s e k	j V	l @r	V s t s
se-	cu-	la-	rized
s e k	j V	l @r	aI z d
se-	cu-	lar
s e k	j V	l @r
se-	cu-	ri-	ti-	za-	tion
s I k	j U@	I	t I	z eI	S V n
se-	cu-	ri-	ti-	zing
s I k	j U@	I	t aI	z I N
se-	cu-	ri-	ties
s I k	j U@	I	t i: z
se-	cu-	ri-	tize
s I k	j U@	I	t aI z
se-	cu-	ri-	tized
s I k	j U@	I	t aI z d
se-	cu-	ri-	ty
s I k	j U@	I	t i:
se-	cu-	ri-	ty's
s I k	j U@	I	t i: z
se-	cu-	ring
s I k	j U@	I N
se-	cun-	da
s I	k V n	d V
se-	cure
s I k	j U@
se-	cure-	ly
s I k	j U@	l i:
se-	cured
s I k	j U@ d
se-	cures
s I k	j U@ z
se-	da
s eI	d V
se-	da-	ted
s V	d eI	t V d
se-	da-	ting
s V	d eI	t I N
se-	da-	tion
s V	d eI	S V n
se-	da-	tive
s e	d V	t I v
se-	dan
s V	d { n
se-	dans
s V	d { n z
se-	date
s V	d eI t
se-	den-	ta-	ry
s e	d V n	t e@	i:
se-	der
s eI	d @r
se-	di-	men-	ta-	ry
s e	d I	m e n	t @r	i:
se-	di-	men-	ta-	tion
s e	d I	m e n	t eI	S V n
se-	di-	ment
s e	d I	m e n t
se-	di-	ments
s e	d I	m e n t s
se-	di-	tion
s V	d I	S V n
se-	di-	tious
s V	d I	S V s
se-	do-	na
s V	d @U	n V
se-	du-	cer
s V	d u:	s @r
se-	duc-	tion
s V	d V k	S V n
se-	duc-	tive
s V	d V k	t I v
se-	duc-	tive-	ly
s V	d V k	t I v	l i:
se-	duce
s V	d u: s
se-	duced
s V	d u: s t
se-	dum
s e	d V m
se-	dums
s e	d V m z
se-	ga
s i:	g V
se-	gal
s i:	g V l
se-	gar
s i:	g @r
se-	gars
s e	g @r z
se-	ga's
s eI	g V z
se-	ger
s i:	g @r
se-	go
s i:	g @U
se-	go-	vi-	a
s e	g @U	v i:	V
se-	gre-	ga-	ted
s e g	r V	g eI	t V d
se-	gre-	ga-	ting
s e g	r I	g eI	t I N
se-	gre-	ga-	tio-	nist
s e g	r V	g eI	S V	n V s t
se-	gre-	ga-	tio-	nists
s e g	r V	g eI	S V	n V s t s
se-	gre-	ga-	tion
s e g	r V	g eI	S V n
se-	gre-	gate
s e g	r V	g eI t
se-	gu-	ra
s eI	g U@	V
se-	guin
s V	g i: n
se-	gun-	do
s e	g U n	d @U
se-	gur
s eI	g U@
se-	la
s e	l V
se-	lan-	der
s e	l V n	d @r
se-	las-	sie
s V	l {	s i:
se-	le-	na
s V	l i:	n V
se-	le-	na's
s V	l i:	n V z
se-	le-	ni-	um
s V	l i:	n i:	V m
se-	le-	nite
s e	l V	n aI t
se-	lec-	ted
s V	l e k	t V d
se-	lec-	ti-	vi-	ty
s V	l e k	t I	v V	t i:
se-	lec-	ting
s V	l e k	t I N
se-	lec-	tion
s V	l e k	S V n
se-	lec-	tions
s V	l e k	S V n z
se-	lec-	tive
s V	l e k	t I v
se-	lec-	tive-	ly
s V	l e k	t I v	l i:
se-	lect
s V	l e k t
se-	lects
s V	l e k t s
se-	lene
s V	l i: n
se-	les
s e	l e s
se-	li-	a
s e	l i:	V
se-	li-	na
s V	l i:	n V
se-	lie
s e	l i:
se-	lig
s e	l I g
se-	lig-	man
s e	l I g	m V n
se-	lig-	mann
s e	l I g	m V n
se-	lin-	da
s e	l i: n	d V
se-	man-	tic
s V	m { n	t I k
se-	man-	tics
s V	m { n	t I k s
se-	me-	le
s e	m V	l i:
se-	mel
s e	m V l
se-	men
s i:	m V n
se-	mes-	ter
s V	m e s	t @r
se-	mes-	ters
s V	m e s	t @r z
se-	mi
s e	m i:
se-	mi-	an-	nu-	al
s e	m i:	{ n	j V	w V l
se-	mi-	an-	nu-	al-	ly
s e	m i:	{	n u:	V	l i:
se-	mi-	au-	to-	ma-	tic
s e	m i:	O:	t V	m {	t I k
se-	mi-	cir-	cu-	lar
s e	m i:	s @r k	j V	l @r
se-	mi-	clas-	si-	cal
s e	m i: k	l {	s I	k V l
se-	mi-	co-	lon
s e	m i:	k @U	l V n
se-	mi-	con-	duc-	tor
s e	m i:	k V n	d V k	t @r
se-	mi-	con-	duc-	tors
s e	m i:	k V n	d V k	t @r z
se-	mi-	con-	duc-	tor's
s e	m i:	k V n	d V k	t @r z
se-	mi-	cy-	lin-	dri-	cal
s e	m i:	s V	l I n	d r I	k V l
se-	mi-	dry
s e	m i: d	r aI
se-	mi-	dry-	ing
s e	m i: d	r aI	I N
se-	mi-	fi-	na-	list
s e	m i:	f aI	n V	l V s t
se-	mi-	fi-	na-	lists
s e	m i:	f aI	n V	l V s t s
se-	mi-	fi-	nal
s e	m i:	f aI	n V l
se-	mi-	fi-	nals
s e	m i:	f aI	n V l z
se-	mi-	fi-	nish
s e	m i:	f I	n I S
se-	mi-	fi-	nished
s e	m i:	f I	n I S t
se-	mi-	gloss
s e	m i: g	l Q s
se-	mi-	le-	gen-	da-	ry
s e	m i:	l e	dZ V n	d e@	i:
se-	mi-	na-	ri-	an
s e	m I	n e@	i:	V n
se-	mi-	na-	ri-	ans
s e	m I	n e@	i:	V n z
se-	mi-	na-	ries
s e	m I	n e@	i: z
se-	mi-	na-	ry
s e	m I	n e@	i:
se-	mi-	nal
s e	m I	n V l
se-	mi-	nar
s e	m I	n Q@
se-	mi-	nars
s e	m I	n Q@ z
se-	mi-	nole
s e	m I	n @U l
se-	mi-	noles
s e	m I	n @U l z
se-	mi-	o-	tic
s i:	m i:	Q	t I k
se-	mi-	o-	tics
s i:	m i:	Q	t I k s
se-	mi-	per-	ma-	nent
s e	m i:	p @r	m V	n V n t
se-	mi-	pre-	cious
s e	m i: p	r e	S V s
se-	mi-	re-	li-	gious
s e	m i:	r V	l I	dZ V s
se-	mi-	sec-	re-	cy
s e	m i:	s i: k	r V	s i:
se-	mi-	ti-	sm
s e	m I	t I	z V m
se-	mi-	tic
s V	m I	t I k
se-	mi-	trai-	ler
s e	m i: t	r eI	l @r
se-	mi-	tro-	pi-	cal
s e	m i: t	r Q	p I	k V l
se-	mis
s e	m aI z
se-	mite
s e	m aI t
se-	na
s e	n V
se-	na-	to-	ri-	al
s e	n V	t O@	i:	V l
se-	na-	tor
s e	n V	t @r
se-	na-	tors
s e	n V	t @r z
se-	na-	tor's
s e	n V	t @r z
se-	nate
s e	n V t
se-	nate's
s e	n V t s
se-	ne-	ca
s e	n V	k V
se-	ne-	cal
s e	n I	k V l
se-	ne-	chal
s e	n I	k V l
se-	ne-	gal
s e	n V	g O: l
se-	ne-	sac
s e	n V	s { k
se-	ne-	scence
s V	n e	s V n s
se-	ney
s e	n i:
se-	ni-	li-	ty
s V	n I	l V	t i:
se-	nile
s i:	n aI l
se-	nio-	ri-	ty
s i: n	j O@	I	t i:
se-	nior
s i: n	j @r
se-	niors
s i: n	j @r z
se-	no-	ra
s i: n	j O@	V
se-	nor
s i: n	j O@
se-	o
s i:	@U
se-	ow
s i:	@U
se-	ow's
s i:	@U z
se-	pa-	ra-	ted
s e	p @r	eI	t V d
se-	pa-	ra-	ti-	sm
s e	p @r	V	t I	z V m
se-	pa-	ra-	ting
s e	p @r	eI	t I N
se-	pa-	ra-	tion
s e	p @r	eI	S V n
se-	pa-	ra-	tions
s e	p @r	eI	S V n z
se-	pa-	ra-	tist
s e	p @r	V	t V s t
se-	pa-	ra-	tists
s e	p @r	V	t V s t s
se-	pa-	rate
s e	p @r	eI t
se-	pa-	rate-	ly
s e	p @r	V t	l i:
se-	pa-	rate-	ness
s e	p @r	V t	n V s
se-	pa-	rates
s e	p @r	eI t s
se-	phar-	dic
s V	f Q@	d I k
se-	phar-	dim
s e	f Q@	d I m
se-	pi-	a
s i:	p i:	V
se-	pul-	ve-	da
s eI	p u: l	v eI	d V
se-	qua
s e k	w V
se-	quel
s i: k	w V l
se-	quels
s i: k	w V l z
se-	quen-	ces
s i: k	w V n	s V z
se-	quen-	cing
s i: k	w V n	s I N
se-	quen-	tial
s V k	w e n	tS V l
se-	quen-	tial-	ly
s V k	w e n	tS V	l i:
se-	quence
s i: k	w V n s
se-	quent
s i: k	w V n t
se-	ques-	te-	ring
s I k	w e s	t @r	I N
se-	ques-	ter
s I k	w e s	t @r
se-	ques-	tered
s I k	w e s	t @r d
se-	ques-	ters
s I k	w e s	t @r z
se-	ques-	tra-	tion
s e k	w V s	t r eI	S V n
se-	qui-	tur
s e k	w I	t @r
se-	qui-	turs
s e k	w I	t @r z
se-	quin
s i: k	w I n
)"
R"(se-	quined
s i: k	w I n d
se-	quins
s i: k	w I n z
se-	quo-	yah
s V k	w OI	V
se-	quoi-	a
s I k	w OI	V
se-	quoi-	as
s I k	w OI	V z
se-	ra
s I@	V
se-	ra-	fi-	na
s @r	Q	f i:	n V
se-	ra-	fi-	ne
s @r	Q	f i:	n i:
se-	ra-	fin
s e@	V	f I n
se-	ra-	phi-	na
s @r	Q	f i:	n V
se-	ra-	phi-	ne
s @r	Q	f i:	n i:
se-	raw
s @r	Q
se-	re-	na-	ded
s e@	V	n eI	d V d
se-	re-	na-	ding
s e@	V	n eI	d I N
se-	re-	nade
s e@	V	n eI d
se-	re-	ne-	ly
s @r	i:	n V	l i:
se-	re-	ni-	ty
s @r	e	n I	t i:
se-	re-	no
s e@	eI	n @U
se-	ren-	di-	pi-	tous
s e@	V n	d I	p V	t V s
se-	ren-	di-	pi-	ty
s e@	V n	d I	p V	t i:
se-	ren-	ge-	ti
s e@	V n	g e	t i:
se-	rene
s @r	i: n
se-	ri-	a
s i:	r i:	V
se-	ri-	a-	lize
s I@	i:	V	l aI z
se-	ri-	a-	lized
s I@	i:	V	l aI z d
se-	ri-	al
s I@	i:	V l
se-	ri-	als
s I@	i:	V l z
se-	ri-	o
s i:	r i:	@U
se-	ri-	ous
s I@	i:	V s
se-	ri-	ous-	ly
s I@	i:	V s	l i:
se-	ri-	ous-	ness
s I@	i:	V s	n V s
se-	ries
s I@	i: z
se-	ril-	da
s @r	i: l	d V
se-	ro-	ka
s e@	@U	k V
se-	ro-	lo-	gi-	cal
s e@	V	l O:	dZ I	k V l
se-	ro-	lo-	gist
s e@	Q	l V	dZ V s t
)"