R"(cri-	tique
kh r V	t i: k
cri-	tiqued
kh r V	t i: k t
cri-	tiques
kh r V	t i: k s
crib
kh r I b
crib-	bage
kh r I	b I dZ
cribs
kh r I b z
cric-	ket
kh r I	k V t
cric-	kets
kh r I	k V t s
cric-	ket's
kh r I	k V t s
crich-	ton
kh r I tS	t V n
crick
kh r I k
crid-	dle
kh r I	d V l
cried
kh r aI d
cries
kh r aI z
crim
kh r I m
crim-	ping
kh r I m	p I N
crim-	son
kh r I m	z V n
crime
kh r aI m
crimes
kh r aI m z
crime's
kh r aI m z
crimp
kh r I m p
crimped
kh r I m p t
crimps
kh r I m p s
crin-	ges
kh r I n	dZ V z
crin-	ging
kh r I n	dZ I N
cringe
kh r I n dZ
cringed
kh r I n dZ d
crip
kh r I p
crip-	p-	ling
kh r I	p V	l I N
crip-	pen
kh r I	p V n
crip-	ple
kh r I	p V l
crip-	pled
kh r I	p V l d
crip-	ples
kh r I	p V l z
cripe
kh r aI p
cripps
kh r I p s
crips
kh r I p s
cris
kh r I s
cris-	co
kh r i: s	k @U
cris-	pen
kh r I s	p V n
cris-	per
kh r I s	p @r
cris-	pin
kh r I s	p I n
cris-	py
kh r I s	p i:
crise
kh r aI z
crisp
kh r I s p
crisp-	ly
kh r I s	p l i:
crisp-	ness
kh r I s	p n V s
criss
kh r I s
criss-	cross
kh r I s	k r O: s
crit-	ten-	den
kh r I	t e n	d V n
crit-	ter
kh r I	t @r
crit-	ters
kh r I	t @r z
critz
kh r I t s
cro
kh r @U
cro-	a-	tia
kh r @U	eI	S V
cro-	a-	tian
kh r @U	eI	S V n
cro-	a-	tians
kh r @U	eI	S V n z
cro-	a-	tia's
kh r @U	eI	S V z
cro-	at
kh r @U	Q t
cro-	ats
kh r @U	Q t s
cro-	at's
kh r @U	Q t s
cro-	ce
kh r @U	tS i:
cro-	che-	ting
kh r @U	S eI	I N
cro-	chet
kh r @U	S eI
cro-	cheted
kh r @U	S eI d
cro-	co-	dile
kh r Q	k V	d aI l
cro-	co-	diles
kh r Q	k V	d aI l z
cro-	cu-	ses
kh r @U	k V	s V z
cro-	cus
kh r @U	k V s
cro-	foot
kh r @U	f U t
cro-	ghan
kh r Q g	h V n
cro-	ker
kh r @U	k @r
cro-	mer
kh r @U	m @r
cro-	ner
kh r @U	n @r
cro-	nies
kh r @U	n i: z
cro-	nin
kh r @U	n I n
cro-	nus
kh r @U	n V s
cro-	ny
kh r @U	n i:
cro-	ny-	i-	sm
kh r @U	n i:	I	z V m
cro-	quet
kh r @U	k eI
cro-	well
kh r @U	V l
cro-	wing
kh r @U	I N
cro-	zier
kh r @U	Z @r
croa-	ker
kh r @U	k @r
croa-	king
kh r @U	k I N
croak
kh r @U k
croc
kh r Q k
croc-	ke-	ry
kh r Q	k @r	i:
croc-	ker
kh r Q	k @r
croc-	ker's
kh r Q	k @r z
croc-	kett
kh r Q	k V t
crock
kh r Q k
crock-	ford
kh r Q k	f @r d
crof-	ton
kh r Q f	t V n
croft
kh r O: f t
crofts
kh r O: f t s
crois-	sant
kh w Q	s Q n t
crois-	sants
kh w Q	s Q n t s
croix
kh r OI
croix's
kh r OI z
crom
kh r Q m
crom-	bie
kh r Q m	b i:
crom-	well
kh r Q m	w V l
crom-	well's
kh r Q m	w V l z
cromp-	ton
kh r Q m	p t V n
cron-	kite
kh r Q N	k aI t
crone
kh r @U n
cronk
kh r Q N k
croo-	ked
kh r U	k V d
croo-	ked-	ness
kh r U	k V d	n V s
croo-	ker
kh r U	k @r
croo-	ner
kh r u:	n @r
croo-	ning
kh r u:	n I N
crook
kh r U k
crooks
kh r U k s
crooks-	ton
kh r U k	s t V n
croom
kh r u: m
croon
kh r u: n
croons
kh r u: n z
crop
kh r Q p
crop-	land
kh r Q p	l { n d
crop-	per
kh r Q	p @r
crop-	ping
kh r Q	p I N
crop-	sey
kh r Q p	s i:
cropped
kh r Q p t
crops
kh r Q p s
crop's
kh r Q p s
cros-	by
kh r O: z	b i:
cros-	by's
kh r O: z	b i: z
cros-	ley
kh r Q s	l i:
cros-	ser
kh r O:	s @r
cros-	ses
kh r O:	s V z
cros-	sett
kh r Q	s V t
cros-	sing
kh r O:	s I N
cros-	sings
kh r O:	s I N z
cros-	s's
kh r O:	s V z
cros-	well
kh r Q s	w e l
crose
kh r @U z
cross
kh r O: s
cross-	bill
kh r O: s	b I l
cross-	bills
kh r O: s	b I l z
cross-	bones
kh r O: s	b @U n z
cross-	bow
kh r O: s	b @U
cross-	cur-	rent
kh r O: s	k @r	V n t
cross-	cur-	rents
kh r O: s	k @r	V n t s
cross-	field
kh r O: s	f i: l d
cross-	fire
kh r O: s	f aI r
cross-	fire's
kh r O: s	f aI r z
cross-	ley
kh r Q s	l i:
cross-	man
kh r O: s	m V n
cross-	o-	ver
kh r O:	s @U	v @r
cross-	pie-	ces
kh r O: s	p i:	s V z
cross-	piece
kh r O: s	p i: s
cross-	pol-	li-	nate
kh r O: s	p Q	l I	n eI t
cross-	road
kh r O: s	r @U d
cross-	roads
kh r O: s	r @U d z
cross-	talk
kh r O: s	t O: k
cross-	town
kh r O: s	t aU n
cross-	ville
kh r Q s	v I l
cross-	walk
kh r Q s	w Q k
cross-	wise
kh r O: s	w aI z
cross-	word
kh r O: s	w @r d
cross-	words
kh r O: s	w @r d z
crosse
kh r Q s
crossed
kh r O: s t
crot-	che-	ty
kh r Q	tS V	t i:
crot-	eau
kh r V	t @U
crot-	ty
kh r Q	t i:
crotch
kh r Q tS
crou-	cher
kh r aU	tS @r
crou-	ching
kh r aU	tS I N
crouch
kh r aU tS
crouched
kh r aU tS t
croup
kh r u: p
crouse
kh r aU s
crout
kh r aU t
crow
kh r @U
crow-	bar
kh r @U	b Q@
crow-	ded
kh r aU	d V d
crow-	der
kh r aU	d @r
crow-	ding
kh r aU	d I N
crow-	kee-	per
kh r @U	k i:	p @r
crow-	kee-	pers
kh r @U	k i:	p @r z
crow-	ley
kh r aU	l i:
crow-	ley's
kh r aU	l i: z
crow-	ner
kh r aU	n @r
crow-	ning
kh r aU	n I N
crowd
kh r aU d
crowds
kh r aU d z
crowd's
kh r aU d z
crowe
kh r @U
crowed
kh r @U d
crowl
kh r aU l
crown
kh r aU n
crown-	like
kh r aU n	l aI k
crowned
kh r aU n d
crowns
kh r aU n z
crown's
kh r aU n z
crows
kh r @U z
crow's
kh r @U z
croy
kh r OI
cru-	ces
kh r u:	s i: z
cru-	ci-	ble
kh r u:	s I	b V l
cru-	ci-	fi-	xes
kh r u:	s I	f I k	s V z
cru-	ci-	fi-	xion
kh r u:	s I	f I k	S V n
cru-	ci-	fied
kh r u:	s I	f aI d
cru-	ci-	fix
kh r u:	s I	f I k s
cru-	ci-	fy
kh r u:	s I	f aI
cru-	cial
kh r u:	S V l
cru-	cial-	ly
kh r u:	S V l	l i:
cru-	el
kh r u:	V l
cru-	ger
kh r u:	dZ @r
cru-	ik-	shank
kh r u:	I k	S { N k
cru-	sa-	der
kh r u:	s eI	d @r
cru-	sa-	ders
kh r u:	s eI	d @r z
cru-	sa-	ding
kh r u:	s eI	d I N
cru-	sade
kh r u:	s eI d
cru-	sades
kh r u:	s eI d z
cru-	sher
kh r V	S @r
cru-	shers
kh r V	S @r z
cru-	shes
kh r V	S V z
cru-	shing
kh r V	S I N
cru-	soe
kh r u:	s @U
cru-	sta-	cean
kh r V s	t eI	S V n
cru-	sta-	ceans
kh r V s	t eI	S V n z
cru-	za-	do
kh r u:	z Q	d @U
cru-	za-	dos
kh r u:	z Q	d @U s
cru-	zan
kh r u:	z V n
cru-	z's
kh r u:	z V z
cruce
kh r u: s
crud
kh r V d
crud-	dy
kh r V	d i:
crude
kh r u: d
crude-	ly
kh r u: d	l i:
crudes
kh r u: d z
crue-	lest
kh r u:	l V s t
cruel-	ly
kh r u:	l i:
cruel-	ties
kh r u: l	t i: z
cruel-	ty
kh r u: l	t i:
crui-	ser
kh r u:	z @r
crui-	sers
kh r u:	z @r z
crui-	ser's
kh r u:	z @r z
crui-	ses
kh r u:	z V z
crui-	sing
kh r u:	z I N
cruick-	shank
kh r U k	S { N k
cruise
kh r u: z
cruised
kh r u: z d
crull
kh r V l
crum
kh r V m
crum-	b-	ling
kh r V m	b V	l I N
crum-	ble
kh r V m	b V l
crum-	bled
kh r V m	b V l d
crum-	bles
kh r V m	b V l z
crum-	by
kh r V m	b i:
crum-	my
kh r V	m i:
crum-	p-	ler
kh r V m	p V	l @r
crum-	ple
kh r V m	p V l
crum-	pled
kh r V m	p V l d
crumb
kh r V m
crumbs
kh r V m z
crump
kh r V m p
crump-	ton
kh r V m	p t V n
crun-	cher
kh r V n	tS @r
crun-	chers
kh r V n	tS @r z
crun-	ches
kh r V n	tS V z
crun-	ching
kh r V n	tS I N
crun-	chy
kh r V n	tS i:
crunch
kh r V n tS
crunched
kh r V n tS t
crunk
kh r V N k
crus-	tal
kh r V s	t V l
crus-	ted
kh r V s	t V d
crus-	ty
kh r V s	t i:
cruse
kh r u: z
crush
kh r V S
crushed
kh r V S t
crust
kh r V s t
crusts
kh r V s t s
crut-	cher
kh r V	tS @r
crut-	ches
kh r V	tS V z
crutch
kh r V tS
crux
kh r V k s
cruz
kh r u: z
cry
kh r aI
cry-	ba-	by
kh r aI	b eI	b i:
cry-	er
kh r aI	@r
cry-	ing
kh r aI	I N
cry-	o-	ge-	nic
kh r aI	V	dZ e	n V k
cry-	o-	ge-	nics
kh r aI	V	dZ e	n V k s
cry-	o-	lite
kh r aI	V	l aI t
cryp-	tic
kh r I p	t I k
cryp-	to
kh r I p	t @U
cryp-	tos-	po-	ri-	di-	um
kh r I p	t @U s	p O@	I	d i:	V m
crypt
kh r I p t
crypts
kh r I p t s
crys-	tal
kh r I s	t V l
crys-	tal-	li-	zing
kh r I s	t V	l aI	z I N
crys-	tal-	line
kh r I s	t V	l aI n
crys-	tal-	lize
kh r I s	t V	l aI z
crys-	tal-	lized
kh r I s	t V	l aI z d
crys-	tal-	lo-	gra-	pher
kh r I s	t V	l Q g	r V	f @r
crys-	tal-	lo-	gra-	phy
kh r I s	t V	l Q g	r V	f i:
crys-	tals
kh r I s	t V l z
crys-	tal's
kh r I s	t V l z
c's
s i: z
cs-	pan
s i: s	p { n
csar
z Q@
ct
kh O@ t
cu-	ba
kh j u:	b V
cu-	ban
kh j u:	b V n
cu-	bans
kh j u:	b V n z
cu-	ba's
kh j u:	b V z
cu-	bi-	cle
kh j u:	b I	k V l
cu-	bi-	cles
kh j u:	b I	k V l z
cu-	bi-	sm
kh j u:	b I	z V m
cu-	bic
kh j u:	b I k
cu-	bist
kh j u:	b I s t
cu-	bit
kh j u:	b I t
cu-	cum-	ber
kh j u:	k V m	b @r
cu-	cum-	bers
kh j u:	k V	m @r z
cu-	da-	hy
kh V	d V	h i:
cu-	li-	na-	ry
kh j u:	l I	n e@	i:
cu-	mings
kh u:	m I N z
cu-	mu-	la-	tive
kh j u: m	j V	l V	t I v
cu-	mu-	la-	tive-	ly
kh j u: m	j V	l V	t I v	l i:
cu-	nard
kh j u:	n @r d
cu-	ne-	i-	form
kh j u:	n i:	V	f O@ m
cu-	ne-	o
kh j u:	n i:	@U
cu-	ny
kh j u:	n i:
cu-	per-	ti-	no
kh u:	p @r	t i:	n @U
cu-	pid
kh j u:	p I d
cu-	pids
kh j u:	p I d z
cu-	po
kh j u:	p @U
cu-	ra-	ble
kh j U@	V	b V l
cu-	ra-	cao
kh j U@	V	s aU
cu-	ra-	tive
kh j U@	V	t I v
cu-	ra-	to-	ri-	al
kh j U@	V	t O@	i:	V l
cu-	ra-	tor
kh j U@	eI	t @r
cu-	ra-	tors
kh j U@	V	t @r z
cu-	ra-	tor's
kh j U@	eI	t @r z
cu-	rate
kh j U@	V t
cu-	ri-	o-	si-	ties
kh j U@	i:	Q	s I	t i: z
cu-	ri-	o-	si-	ty
kh j U@	i:	Q	s I	t i:
cu-	ri-	ou-	ser
kh j U@	i:	V	s @r
cu-	ri-	ous
kh j U@	i:	V s
cu-	ri-	ous-	ly
kh j U@	i:	V s	l i:
cu-	ri-	ti-	ba
kh j U	I	t i:	b V
cu-	rie
kh j U@	i:
cu-	ring
kh j U@	I N
cu-	sack
kh j u:	z V k
cu-	shi-	tic
kh V	S I	t I k
cu-	shing
kh U	S I N
cu-	shio-	ning
kh U	S V	n I N
cu-	shion
kh U	S V n
cu-	shioned
kh U	S V n d
cu-	shions
kh U	S V n z
cu-	shy
kh U	S i:
cu-	sick
kh j u:	z I k
cu-	so
kh j u:	s @U
cu-	ta-	way
kh V	t V	w eI
cu-	ter
kh j u:	t @r
cu-	test
kh j u:	t I s t
cu-	ti-	cle
kh j u:	t I	k V l
cu-	ya-	ho-	ga
kh aI	V	h @U	g V
cub
kh V b
cub-	bies
kh V	b i: z
cub-	by-	hole
kh V	b i:	h @U l
cube
kh j u: b
cubed
kh j u: b d
cubes
kh j u: b z
cubs
kh V b z
cuc-	koo
kh V	k u:
cuc-	koos
kh u:	k u: z
cuc-	koo's
kh u:	k u: z
cud-	dle
kh V	d V l
cud-	dled
kh V	d V l d
cud-	dy
kh V	d i:
cud-	gel
kh V	dZ V l
cud-	gels
kh V	dZ V l z
cudd-	ling
kh V d	l I N
cudd-	ly
kh V d	l i:
cue
kh j u:
cue-	ro
kh w e@	@U
cue-	va
kh w e	v V
cued
kh j u: d
cuen-	ca
kh w e n	k V
cuer-	vo
kh U@	v @U
cues
kh j u: z
cues-	ta
kh w e s	t V
cuff
kh V f
cuffed
kh V f t
cuffs
kh V f s
cui-	si-	nart
kh w i:	s I	n Q t
cui-	si-	narts
kh w i:	z I	n Q@ t s
cui-	sine
kh w I	z i: n
cui-	sines
kh w I	z i: n z
cul
kh V l
cul-	ber-	son
kh V l	b @r	s V n
cul-	bert
kh V l	b @r t
cul-	bert-	son
kh V l	b @r t	s V n
cul-	de-	sac
kh V l	d V	s { k
cul-	lan
kh V	l V n
cul-	len
kh V	l V n
cul-	ler
kh V	l @r
cul-	lers
kh V	l @r z
cul-	ler's
kh V	l @r z
cul-	ley
kh V	l i:
cul-	li-	nan
kh V	l I	n V n
cul-	lin
kh V	l I n
cul-	ling
kh V	l I N
cul-	lom
kh V	l V m
cul-	ly
kh V	l i:
cul-	mi-	na-	ted
kh V l	m I	n eI	t I d
cul-	mi-	na-	ting
kh V l	m I	n eI	t I N
cul-	mi-	na-	tion
kh V l	m I	n eI	S V n
cul-	mi-	nate
kh V l	m I	n eI t
cul-	mi-	nates
kh V l	m I	n eI t s
cul-	pa
kh V l	p V
cul-	pa-	bi-	li-	ty
kh V l	p V	b I	l V	t i:
cul-	pa-	ble
kh V l	p V	b V l
cul-	ti-	va-	ted
kh V l	t I	v eI	t I d
cul-	ti-	va-	ting
kh V l	t I	v eI	t I N
cul-	ti-	va-	tion
kh V l	t I	v eI	S V n
cul-	ti-	vate
kh V l	t I	v eI t
cul-	ti-	vates
kh V l	t I	v eI t s
cul-	tic
kh V l	t I k
cul-	tist
kh V l	t I s t
cul-	tists
kh V l	t I s t s
cul-	tu-	ral
kh V l	tS @r	V l
cul-	tu-	ral-	ly
kh V l	tS @r	V	l i:
cul-	tu-	ring
kh V l	tS @r	I N
cul-	ture
kh V l	tS @r
cul-	tured
kh V l	tS @r d
cul-	tures
kh V l	tS @r z
cul-	ture's
kh V l	tS @r z
cul-	ver
kh V l	v @r
cul-	ver-	house
kh V l	v @r	h aU s
cul-	ver's
kh V l	v @r z
cul-	vert
kh V l	v @r t
cull
kh V l
cull-	man
kh V l	m V n
culled
kh V l d
culp
kh V l p
culp-	rit
kh V l	p r I t
culp-	rits
kh V l	p r I t s
cult
kh V l t
cults
kh V l t s
cult's
kh V l t s
cum
kh V m
cum-	ber
kh V m	b @r
cum-	ber-	land
kh V m	b @r	l V n d
cum-	ber-	some
kh V m	b @r	s V m
cum-	by
kh V m	b i:
cum-	min-	s's
kh V	m I n	z V z
cum-	ming
kh V	m I N
cum-	ming-	ton
kh V	m I N	t V n
cum-	mings
kh V	m I N z
cum-	mins
kh V	m I n z
cun-	diff
kh V n	d I f
cun-	dy
kh V n	d i:
cun-	ha
kh V n	h V
cun-	ning
kh V	n I N
cun-	ning-	ham
kh V	n I N	h { m
cun-	ning-	ham's
kh V	n I N	h { m z
cup
kh V p
cup-	board
kh V	b @r d
cup-	boards
kh V	b @r d z
cup-	cake
kh V p	k eI k
cup-	cakes
kh V p	k eI k s
cup-	py
kh V	p i:
cups
kh V p s
cur
kh @r
cur-	bing
kh @r	b I N
cur-	by
kh @r	b i:
cur-	ci-	o
kh U@	tS i:	@U
cur-	few
kh @r f	j u:
cur-	fews
kh @r f	j u: z
cur-	ler
kh @r	l @r
cur-	lers
kh @r	l @r z
cur-	ley
kh @r	l i:
cur-	ling
kh @r	l I N
cur-	ly
kh @r	l i:
cur-	mud-	geon
kh @r	m V	dZ V n
cur-	ragh
kh V	r V
cur-	ran
kh @r	V n
cur-	ren
kh @r	V n
cur-	ren-	cies
kh @r	V n	s i: z
cur-	ren-	cy
kh @r	V n	s i:
cur-	ren-	cy's
kh @r	V n	s i: z
cur-	rent
kh @r	V n t
cur-	rent-	ly
kh @r	V n	t l i:
cur-	rents
kh @r	V n t s
cur-	rent's
kh @r	V n t s
cur-	rey
kh @r	i:
cur-	ri-	cu-	la
kh @r	I k	j V	l V
cur-	ri-	cu-	lar
kh @r	I k	j V	l @r
cur-	ri-	cu-	lum
kh @r	I k	j V	l V m
cur-	ri-	cu-	lums
kh @r	I k	j V	l V m z
cur-	ri-	er
kh @r	i:	@r
cur-	rie
kh @r	i:
cur-	ried
kh @r	i: d
cur-	ries
kh @r	i: z
cur-	ry
kh V	r i:
cur-	ry-	ing
kh @r	i:	I N
cur-	ry's
kh V	r i: z
cur-	ses
kh @r	s V z
cur-	sing
kh @r	s I N
cur-	so-	ry
kh @r	s @r	i:
cur-	sor
kh @r	s @r
cur-	tai-	ling
kh @r	t eI	l I N
cur-	tail
kh @r	t eI l
cur-	tail-	ment
kh @r	t eI l	m V n t
cur-	tail-	ments
kh @r	t eI l	m V n t s
cur-	tailed
kh @r	t eI l d
cur-	tails
kh @r	t eI l z
cur-	tain
kh @r	t @ n
cur-	tains
kh @r	t @ n z
cur-	tice
kh U@	t I s
cur-	tin
kh @r	t I n
cur-	tis
kh @r	t I s
cur-	tiss
kh @r	t I s
cur-	va-	ture
kh @r	v V	tS @r
cur-	ving
kh @r	v I N
cur-	vy
kh @r	v i:
curb
kh @r b
curb-	side
kh @r b	s aI d
curb-	stone
kh @r b	s t @U n
curbed
kh @r b d
curbs
kh @r b z
curd
kh @r d
cure
kh j U@
cured
kh j U@ d
cures
kh j U@ z
curl
kh @r l
curled
kh @r l d
curls
kh @r l z
curse
kh @r s
cursed
kh @r s t
curt
kh @r t
curt-	ly
kh @r t	l i:
curt's
kh @r t s
curve
kh @r v
curved
kh @r v d
curves
kh @r v z
cus-	sing
kh V	s I N
cus-	tard
kh V s	t @r d
cus-	ter
kh V s	t @r
cus-	ter's
kh V s	t @r z
cus-	to-	di-	al
kh V s	t @U	d i:	V l
cus-	to-	di-	an
kh V s	t @U	d i:	V n
cus-	to-	di-	ans
kh V s	t @U	d i:	V n z
cus-	to-	dy
kh V s	t V	d i:
cus-	to-	ma-	ri-	ly
kh V s	t V	m e@	V	l i:
cus-	to-	ma-	ry
kh V s	t V	m e@	i:
cus-	to-	mer
kh V s	t V	m @r
cus-	to-	mers
kh V s	t V	m @r z
cus-	to-	mer's
kh V s	t V	m @r z
cus-	to-	mi-	zing
kh V s	t V	m aI	z I N
cus-	to-	mize
kh V s	t V	m aI z
cus-	to-	mized
kh V s	t V	m aI z d
cus-	tom
kh V s	t V m
cus-	toms
kh V s	t V m z
cush
kh V S
cush-	man
kh U S	m V n
cusk
kh V s k
cusp
kh V s p
cuss
kh V s
cussed
kh V s t
cut
kh V t
cut-	back
kh V t	b { k
cut-	backs
kh V t	b { k s
cut-	cher
kh V	tS @r
cut-	lass
kh V t	l V s
cut-	le-	ry
kh V t	l @r	i:
cut-	ler
kh V t	l @r
cut-	ler's
kh V t	l @r z
cut-	lip
kh V t	l I p
cut-	off
kh V	t O: f
cut-	offs
kh V	t O: f s
cut-	out
kh V	t aU t
cut-	outs
kh V	t aU t s
cut-	ter
kh V	t @r
cut-	ters
kh V	t @r z
cut-	ting
kh V	t I N
cut-	tings
kh V	t I N z
cut-	tle-	fish
kh V	t V l	f I S
cut-	ty
kh V	t i:
cut-	worm
kh V t	w @r m
cut-	worms
kh V t	w @r m z
cute
kh j u: t
cute-	ness
kh j u: t	n V s
cute-	si-	ness
kh j u: t	s i:	n V s
cute-	sy
kh j u: t	s i:
cuth-	bert
kh V T	b @r t
cuth-	bert-	son
kh V T	b @r t	s V n
cuts
kh V t s
cutth-	roat
kh V t	T r @U t
cuy-	ler
kh aI	l @r
cy
s aI
cy-	a-	nu-	ric
s aI	{	n @r	I k
cy-	ber
s aI	b @r
cy-	ber-	sex
s aI	b @r	s e k s
cy-	ber-	space
s aI	b @r s	p eI s
cy-	bill
s aI	b I l
cy-	c-	ling
s aI	k V	l I N
cy-	c-	list
s aI	k V	l I s t
cy-	c-	lists
s aI	k V	l I s t s
cy-	cads
s aI	k { d z
cy-	cle
s aI	k V l
cy-	cled
s aI	k V l d
cy-	cles
s aI	k V l z
cy-	do-	ni-	a
s V	d @U	n i:	V
cy-	lin-	der
s I	l I n	d @r
cy-	lin-	ders
s I	l I n	d @r z
cy-	lind-	ri-	cal
s V	l I n	d r I	k V l
cy-	na-	ra
kh I	n Q@	V
cy-	ni-	cal
s I	n I	k V l
cy-	ni-	cal-	ly
s I	n I	k V	l i:
cy-	ni-	ci-	sm
s I	n I	s I	z V m
cy-	nic
s I	n I k
cy-	nics
s I	n I k s
cy-	pher
s aI	f @r
cy-	phers
s aI	f @r z
cy-	ra-	no
kh i:	r Q	n @U
cy-	re-	na
kh I@	i:	n V
cy-	ril
s I@	I l
cy-	ril-	la
s I@	I	l V
cy-	ril-	lic
s @r	I	l I k
cy-	rus
s aI	r V s
cy-	the-	re-	a
s I	T @r	i:	V
cy-	to-	lo-	gy
s aI	t Q	l V	dZ i:
cy-	to-	me-	ga-	lo-	vi-	rus
s aI	t V	m e	g V	l @U	v aI	r V s
cy-	top-	la-	sm
s aI	t V p	l {	z V m
cy-	top-	las-	mic
s aI	t V p	l { z	m I k
cyb
s aI b
cyc-	la-	des
s aI k	l eI	d i: z
cyc-	li-	ca-	li-	ty
s I k	l I	k {	l I	t i:
cyc-	li-	cal
s aI k	l I	k V l
cyc-	li-	cals
s I k	l I	k V l z
cyc-	lo-	he-	xane
s aI k	l V	h e k	s eI n
cyc-	lo-	pe-	an
s aI k	l V	p i:	V n
cyc-	lone
s I k	l @U n
cyc-	lones
s I k	l @U n z
cyc-	lop-	s's
s aI k	l O: p	s V z
cyc-	lops
s aI k	l O: p s
cyc-	los-	po-	rine
s I k	l O: s	p @r	i: n
cyc-	los-	tome
s aI k	l V s	t @U m
cyc-	los-	tomes
s aI k	l V s	t @U m z
)"
R"(cyd
s I d
cyg-	nus
s I g	n V s
cym-	bal
s I m	b V l
cym-	bals
s I m	b V l z
cyn-	di
s I n	d i:
cyn-	thi-	a
s I n	T i:	V
cyn-	thi-	a's
s I n	T i:	V z
cyn-	thie
s I n	T i:
cyn-	wyd
s I n	w V d
cynth
s I n T
cyp-	res-	s's
s aI p	r V	s V z
cyp-	ress
s aI p	r V s
cyp-	ri-	an
s I p	r i:	V n
cyp-	ri-	ot
s I p	r i:	V t
cyp-	ri-	ots
s I p	r i:	V t s
cyp-	ris
s aI p	r I s
cyp-	rus
s aI p	r V s
cyr
s I@
cys-	tic
s I s	t I k
cyst
s I s t
cysts
s I s t s
cza-	rist
z Q@	I s t
czar
z Q@
czars
z Q@ z
czar's
z Q@ z
cze-	chos-	lo-	va-	ki-	a
tS e	k V s	l @U	v Q	k i:	V
cze-	chos-	lo-	va-	ki-	an
tS e	tS V s	l @U	v Q	k i:	V n
cze-	chos-	lo-	va-	ki-	a's
tS e	k V s	l @U	v Q	k i:	V z
cze-	chos-	lo-	vak
tS e	k V s	l @U	v Q k
cze-	chos-	lo-	vaks
tS e	k V s	l @U	v Q k s
czech
tS e k
czechs
tS e k s
czer-	ni-	ak
tS @r	n i:	{ k
czer-	ny
tS @r	n i:
d
dh i:
d'-	a-	mo-	re
dh i:	V	m O@	eI
d-	a's
dh i:	eI z
d-	k
dh i:	k eI
d-	mi-	tri
dh V	m i: t	r i:
d-	nase
dh i:	n eI s
d-	nies-	ter
dh V	n i: s	t @r
d-	s-	s
dh i:	e	s e s
d-	s-	v
dh i:	e s	v i:
d-	u-	i
dh i:	j u:	aI
d.
dh i:
da
dh Q
da-	cey
dh eI	s i:
da-	cha
dh Q	tS V
da-	chau
dh {	k aU
da-	ci-	a
dh eI	S i:	V
da-	cus
dh {	k V s
da-	cy
dh eI	s i:
da-	da
dh Q	d Q
da-	do
dh eI	d @U
da-	gan
dh eI	g V n
da-	gen-	ham
dh {	g V n	h { m
da-	ges-	tan
dh {	g e s	t { n
da-	kar
dh Q	k Q@
da-	ko-	ta
dh V	k @U	t V
da-	ko-	tan
dh V	k @U	t V n
da-	ko-	tans
dh V	k @U	t V n z
da-	ko-	tas
dh V	k @U	t V z
da-	ko-	ta's
dh V	k @U	t V z
da-	lai
dh {	l eI
da-	len
dh {	l V n
d'a-	lene
dh V	l i: n
da-	leth
dh Q	l e T
da-	ley
dh eI	l i:
da-	ley's
dh eI	l i: z
da-	li
dh Q	l i:
da-	li-	an
dh eI	l i:	V n
da-	li-	la
dh V	l aI	l V
da-	lia
dh Q l	j V
da-	lis
dh {	l I s
da-	lo
dh Q	l @U
da-	ly
dh eI	l i:
da-	ma
dh Q	m V
da-	ma-	ges
dh {	m V	dZ V z
da-	ma-	ging
dh {	m I	dZ I N
da-	ma-	ris
dh V	m Q@	V s
da-	mage
dh {	m V dZ
da-	maged
dh {	m V dZ d
da-	man
dh eI	m V n
da-	mas
dh Q	m V z
da-	mas-	cu-	s's
dh V	m { s	k V	s V z
da-	mas-	cus
dh V	m { s	k V s
da-	mask
dh {	m V s k
da-	masks
dh {	m V s k s
da-	me-	ron
dh Q	m e@	O: n
da-	mi-	a-	ni
dh Q	m i:	Q	n i:
da-	mi-	a-	no
dh Q	m i:	Q	n @U
da-	mi-	an
dh eI	m i:	V n
da-	mi-	en
dh eI	m i:	V n
da-	mi-	en's
dh eI	m i:	V n z
da-	mi-	et-	ta
dh {	m i:	e	t V
da-	mi-	no-	zide
dh {	m I	n V	z aI d
da-	mi-	ta
dh Q	m i:	t V
da-	moc-	les
dh {	m V k	l i: z
da-	mon
dh eI	m V n
da-	mon's
dh eI	m V n z
da-	mour
dh V	m U@
da-	na
dh eI	n V
da-	na-	her
dh {	n V	h @r
da-	na's
dh eI	n V z
da-	ne-	se
dh Q	n eI	z i:
da-	nel-	la
dh V	n e	l V
da-	nelle
dh V	n e l
da-	ney
dh eI	n i:
da-	ni
dh Q	n i:
da-	ni-	ca
dh {	n I	k V
da-	ni-	elle
dh {	n i:	e l
da-	nia
dh eI n	j V
da-	nie-	la
dh { n	j e	l V
da-	niel
dh { n	j V l
da-	niel-	la
dh { n	j e	l V
da-	niel-	son
dh { n	j V l	s V n
da-	niele
dh { n	j e l
da-	niell
dh {	n i: l
da-	niels
dh { n	j V l z
da-	niel's
dh { n	j V l z
da-	nish
dh eI	n I S
da-	nube
dh { n	j u: b
da-	ra
dh {	r V
da-	ren
dh {	r V n
da-	ri-	a
dh Q@	i:	V
da-	ri-	en
dh e@	i:	V n
da-	ri-	o
dh e@	i:	@U
da-	ri-	us
dh @r	aI	V s
da-	rice
dh Q@	I s
da-	rin
dh {	r I n
da-	ring
dh e@	I N
da-	ryl
dh e@	V l
da-	shel
dh {	S V l
da-	sher
dh {	S @r
da-	shes
dh {	S V z
da-	shi-	ki
dh V	S i:	k i:
da-	shing
dh {	S I N
da-	ta
dh eI	t V
da-	ta-	ba-	ses
dh eI	t V	b eI	s V z
da-	ta-	base
dh eI	t V	b eI s
da-	ta-	point
dh eI	t V	p OI n t
da-	ta's
dh eI	t V z
da-	ted
dh eI	t V d
da-	ting
dh eI	t I N
da-	to
dh Q	t @U
da-	tu-	ra
dh V	t U@	V
da-	tuk
dh Q	t u: k
da-	tum
dh {	t V m
da-	vao
dh V	v @U
da-	ven-	port
dh {	v V n	p O@ t
da-	ven-	port's
dh {	v V n	p O@ t s
da-	vey
dh eI	v i:
da-	vi-	da
dh Q	v i:	d V
da-	vi-	de
dh V	v i:	d eI
da-	vi-	di-	an
dh V	v I	d i:	V n
da-	vi-	di-	an's
dh V	v I	d i:	V n z
da-	vi-	doff
dh eI	v I	d O: f
da-	vi-	na
dh Q	v i:	n V
da-	vi-	son
dh eI	v I	s V n
da-	vi-	s's
dh eI	v I	s V z
da-	vid
dh eI	v I d
da-	vid-	son
dh eI	v I d	s V n
da-	vid-	son's
dh eI	v I d	s V n z
da-	vids
dh eI	v I d z
da-	vid's
dh eI	v I d z
da-	vie
dh eI	v i:
da-	vies
dh eI	v i: z
da-	vil-	la
dh V	v I	l V
da-	vin
dh {	v I n
da-	vis
dh eI	v I s
da-	vis'
dh eI	v I s
da-	vis-	son
dh {	v I	s V n
da-	vos
dh Q	v @U s
da-	vy
dh eI	v i:
da-	x's
dh { k	s V z
da-	yan
dh eI	V n
dab
dh { b
dab-	b-	ling
dh {	b V	l I N
dab-	bing
dh {	b I N
dab-	ble
dh {	b V l
dab-	bled
dh {	b V l d
dab-	bles
dh {	b V l z
dab-	chick
dh { b	tS I k
dab-	ney
dh { b	n i:
dabbs
dh { b z
dac
dh { k
dac-	ron
dh { k	r Q n
dace
dh eI s
dach-	shund
dh Q k	s h U n d
dach-	shunds
dh Q k	s h U n t s
dacs
dh { k s
dad
dh { d
dad-	dies
dh {	d i: z
dad-	dy
dh {	d i:
dad-	dy's
dh {	d i: z
dade
dh eI d
dads
dh { d z
dad's
dh { d z
dae
dh eI
dae-	da-	lus
dh e	d V	l V s
dae-	mon
dh i:	m V n
d'af-	faires
dh V	f e@ z
daf-	fo-	dil
dh {	f V	d I l
daf-	fo-	dils
dh {	f V	d I l z
daf-	fy
dh {	f i:
daf-	na
dh { f	n V
daft
dh { f t
dag
dh { g
dag-	ger
dh {	g @r
dag-	gers
dh {	g @r z
dag-	gett
dh {	g V t
dag-	gy
dh {	g i:
dag-	ley
dh { g	l i:
dag-	mar
dh { g	m Q@
dai-	ley
dh eI	l i:
dai-	lies
dh eI	l i: z
dai-	ly
dh eI	l i:
dai-	mones
dh eI	m @U n z
dai-	ries
dh e@	i: z
dai-	ry
dh e@	i:
dai-	ry-	ing
dh e@	i:	I N
dai-	ry-	men
dh eI	r i:	m V n
dai-	sey
dh eI	s i:
dai-	sies
dh eI	z i: z
dai-	sy
dh eI	z i:
dai-	sy's
dh eI	z i: z
dail
dh eI l
daile
dh eI l
daim-	ler
dh eI m	l @r
daim-	ler's
dh eI m	l @r z
dain
dh eI n
dain-	ty
dh eI n	t i:
daines
dh eI n z
dais
dh eI z
dak
dh { k
dal
dh { l
dal-	la-	s's
dh {	l V	s V z
dal-	las
dh {	l V s
dal-	li-	ance
dh {	l i:	V n s
dal-	lied
dh {	l i: d
dal-	ly
dh {	l i:
dal-	ma-	tian
dh { l	m eI	S V n
dal-	ma-	tians
dh { l	m eI	S V n z
dal-	rym-	ple
dh { l	r I m	p V l
dal-	ton
dh O: l	t V n
dal-	tons
dh O: l	t V n z
dal-	ton's
dh O: l	t V n z
dal-	zell
dh { l	z V l
dale
dh eI l
dales
dh eI l z
dale's
dh eI l z
dall
dh O: l
dall-	man
dh O: l	m V n
dalpe
dh eI l p
dam
dh { m
dam-	mer
dh {	m @r
dam-	ming
dh {	m I N
dam-	mit
dh {	m I t
dam-	na-	tion
dh { m	n eI	S V n
dam-	ning
dh {	m I N
dam-	pe-	ning
dh { m	p V	n I N
dam-	pen
dh { m	p V n
dam-	pened
dh { m	p V n d
dam-	per
dh { m	p @r
dam-	pers
dh { m	p @r z
dam-	pi-	er
dh { m	p i:	@r
dam-	ping
dh { m	p I N
dam-	sel
dh { m	z V l
dam-	son
dh { m	s V n
dame
dh eI m
dames
dh eI m z
dame's
dh eI m z
damme
dh { m
dammed
dh { m d
damn
dh { m
damned
dh { m d
damp
dh { m p
damp-	ness
dh { m	p n V s
damped
dh { m p t
damps
dh { m p s
dams
dh { m z
dam's
dh { m z
dan
dh { n
dan-	bu-	ry
dh { n	b @r	i:
dan-	by
dh { n	b i:
dan-	cer
dh { n	s @r
dan-	cers
dh { n	s @r z
dan-	cer's
dh { n	s @r z
dan-	ces
dh { n	s V z
dan-	cey
dh { n	s i:
dan-	cing
dh { n	s I N
dan-	cy
dh { n	s i:
dan-	de-	li-	on
dh { n	d V	l aI	V n
dan-	de-	li-	ons
dh { n	d V	l aI	V n z
dan-	dy
dh { n	d i:
dan-	dy-	i-	sm
dh { n	d i:	I	z V m
dan-	ford
dh { n	f @r d
dan-	forth
dh { n	f @r T
dan-	g-	ler
dh { N	g V	l @r
dan-	g-	ling
dh { N	g V	l I N
dan-	ge-	rous
dh eI n	dZ @r	V s
dan-	ge-	rous-	ly
dh eI n	dZ @r	V s	l i:
dan-	ger
dh eI n	dZ @r
dan-	ger-	field
dh eI n	dZ @r	f i: l d
dan-	gers
dh eI n	dZ @r z
dan-	gle
dh { N	g V l
dan-	gled
dh { N	g V l d
dan-	gles
dh { N	g V l z
dan-	ker
dh { N	k @r
dan-	na
dh {	n V
dan-	ner
dh {	n @r
dan-	nie
dh {	n i:
dan-	ny
dh {	n i:
dan-	ny's
dh {	n i: z
dan-	te
dh Q n	t eI
dan-	te's
dh { n	t i: z
dan-	ton
dh { n	t V n
dan-	vers
dh { n	v @r z
dan-	ville
dh { n	v I l
dan-	zi-	ger
dh { n	z I	g @r
dan-	zig
dh { n	z I g
dance
dh { n s
danced
dh { n s t
dand-	ruff
dh { n	d r V f
dane
dh eI n
danes
dh eI n z
dane's
dh eI n z
dang
dh { N
dank
dh { N k
danks
dh { N k s
dann
dh { n
dan's
dh { n z
dans-	ville
dh { n	z v I l
dans-	ville's
dh { n	z v I l z
dant
dh { n t
dao
dh aU
dap-	per
dh {	p @r
daph-	ne
dh { f	n i:
daph-	ne's
dh { f	n i: z
daph-	nis
dh { f	n I s
dar
dh Q@
dar-	by
dh Q@	b i:
dar-	by's
dh Q@	b i: z
dar-	cey
dh Q@	s i:
dar-	cie
dh Q@	k i:
dar-	cy
dh Q@	s i:
d'ar-	cy
dh Q@	s i:
dar-	den
dh Q@	d V n
dar-	den's
dh Q@	d V n z
dar-	ga
dh Q@	g V
dar-	jee-	ling
dh Q@	dZ i:	l I N
dar-	ke-	ning
dh Q@	k V	n I N
dar-	ken
dh Q@	k V n
dar-	kened
dh Q@	k V n d
dar-	ker
dh Q@	k @r
dar-	kest
dh Q@	k V s t
dar-	kie
dh Q@	k i:
dar-	lene
dh Q@	l i: n
dar-	line
dh Q@	l aI n
dar-	ling
dh Q@	l I N
dar-	ling-	ton
dh Q@	l I N	t V n
dar-	lings
dh Q@	l I N z
dar-	nall
dh Q@	n V l
dar-	nel
dh Q@	n V l
dar-	nell
dh Q@	n e l
dar-	ner
dh Q@	n @r
dar-	pa
dh Q@	p V
dar-	ragh
dh e@	V
dar-	rell
dh e@	V l
dar-	relle
dh @r	e l
dar-	ren
dh Q@	V n
dar-	rick
dh {	r I k
dar-	ring-	ton
dh {	r I N	t V n
dar-	row
dh e@	@U
dar-	ryl
dh e@	V l
dar-	sey
dh Q@	s i:
dar-	ted
dh Q@	t V d
dar-	ter
dh Q@	t @r
dar-	ting
dh Q@	t I N
dar-	ton
dh Q@	t V n
dar-	wi-	ni-	an
dh Q@	w I	n i:	V n
dar-	wi-	ni-	sm
dh Q@	w I	n I	z V m
dar-	win
dh Q@	w I n
dare
dh e@
dare-	de-	vil
dh e@	d e	v V l
dare-	say
dh e@	s eI
dared
dh e@ d
dares
dh e@ z
dark
dh Q@ k
dark-	ly
dh Q@ k	l i:
dark-	ness
dh Q@ k	n V s
dark-	room
dh Q@ k	r u: m
darm-	stadt
dh Q@ m	s t { t
darn
dh Q@ n
darne-	dest
dh Q@ n	d e s t
darned
dh Q@ n d
darns
dh Q@ n z
darr
dh e@
darst
dh Q@ s t
dart
dh Q@ t
dart-	board
dh Q@ t	b O@ d
dart-	mouth
dh Q@ t	m V T
dart-	mouth's
dh Q@ t	m V T s
darth
dh Q@ T
darts
dh Q@ t s
dart's
dh Q@ t s
das
dh { s
das-	tard-	ly
dh { s	t @r d	l i:
dase
dh eI z
dash
dh { S
dash-	board
dh { S	b O@ d
dash-	boards
dh { S	b O@ d z
dashed
dh { S t
dat
dh { t
dat-	sun
dh { t	s V n
dat-	sun's
dh { t	s V n z
date
dh eI t
date-	line
dh eI t	l aI n
date-	lines
dh eI t	l aI n z
date-	line's
dh eI t	l aI n z
dates
dh eI t s
dau
dh @U
dau-	ber
dh aU	b @r
dau-	gher-	ty
dh Q	k @r	t i:
dau-	phin
dh aU	f I n
daub
dh O: b
daube
dh O: b
daubed
dh O: b d
daugh-	ter
dh O:	t @r
daugh-	ters
dh O:	t @r z
daugh-	ter's
dh O:	t @r z
daught-	ry
dh O: t	r i:
dault
dh O: l t
daun
dh O: n
daun-	ted
dh O: n	t V d
daun-	ting
dh O: n	t I N
daunt
dh O: n t
dave
dh eI v
dave's
dh eI v z
daw
dh O:
daw-	dle
dh O:	d V l
daw-	dy
dh O:	d i:
daw-	kins
dh O:	k I n z
daw-	ning
dh O:	n I N
daw-	son
dh O:	s V n
daw-	son's
dh O:	s V n z
dawd-	ling
dh O: d	l I N
dawe
dh O:
dawes
dh O: z
dawn
dh O: n
dawned
dh O: n d
dawns
dh O: n z
dawn's
dh O: n z
daws
dh O: z
dax
dh { k s
day
dh eI
day-	break
dh eI b	r eI k
day-	care
dh eI	k e@
day-	drea-	ming
dh eI d	r i:	m I N
day-	dream
dh eI d	r i: m
day-	dreamed
dh eI d	r i: m d
day-	light
dh eI	l aI t
day-	lights
dh eI	l aI t s
day-	long
dh eI	l O: N
daye
dh eI
dayle
dh eI l
days
dh eI z
day's
dh eI z
days'
dh eI z
de
dh i:
de-	a-	na
dh i:	{	n V
de-	ac-	ti-	va-	ted
dh i:	{ k	t I	v eI	t V d
de-	ac-	ti-	vate
dh i:	{ k	t I	v eI t
de-	an-	na
dh i:	{	n V
de-	ba-	cle
dh V	b Q	k V l
de-	ba-	cles
dh eI	b Q	k V l z
de-	ba-	sing
dh V	b eI	s I N
de-	ba-	ta-	ble
dh V	b eI	t V	b V l
de-	ba-	ted
dh V	b eI	t V d
de-	ba-	ter
dh V	b eI	t @r
de-	ba-	ters
dh V	b eI	t @r z
de-	ba-	ting
dh V	b eI	t I N
de-	ba-	tor
dh i:	b eI	t @r
de-	bar-	ment
dh V	b Q@	m V n t
de-	base
dh V	b eI s
de-	base-	ment
dh V	b eI s	m V n t
de-	based
dh V	b eI s t
de-	bate
dh V	b eI t
de-	bates
dh V	b eI t s
de-	bate's
dh V	b eI t s
de-	bau-	che-	ry
dh V	b O:	tS @r	i:
de-	bell
dh i:	b e l
de-	ben-	ture
dh V	b e n	tS @r
de-	ben-	tures
dh V	b e n	tS @r z
de-	ber-	ry
dh i:	b e@	i:
de-	bi
dh e	b i:
de-	bi-	li-	ta-	ted
dh V	b I	l V	t eI	t V d
de-	bi-	li-	ta-	ting
dh V	b I	l V	t eI	t I N
de-	bi-	li-	tate
dh V	b I	l V	t eI t
de-	bi-	li-	ty
dh V	b I	l V	t i:
de-	bit
dh e	b I t
de-	bo-	nair
dh e	b V	n e@
de-	bo-	rah
dh e	b @r	V
de-	bo-	rah's
dh e	b @r	V z
de-	bolt
dh e	b @U l t
de-	bor
dh e	b O@
de-	bord
dh I	b O@ d
de-	bu-	tante
dh e b	j V	t Q n t
de-	bu-	tantes
dh e b	j V	t Q n t s
de-	bu-	ting
dh eI b	j u:	I N
de-	bug
dh i:	b V g
de-	bug-	ging
dh i:	b V	g I N
de-	bun-	king
dh V	b V N	k I N
de-	bunk
dh V	b V N k
de-	bunked
dh V	b V N k t
de-	bus
dh e	b V s
de-	bus-	sy
dh e	b V	s i:
de-	bus-	sy's
dh e	b V	s i: z
de-	but
dh eI b	j u:
de-	buted
dh eI b	j u: d
de-	buts
dh eI b	j u: z
de-	ca-	dence
dh e	k V	d V n s
de-	ca-	dent
dh e	k V	d V n t
de-	ca-	pi-	ta-	ted
dh i:	k {	p I	t eI	t I d
de-	ca-	pi-	ta-	tion
dh I	k {	p I	t eI	S V n
de-	ca-	pi-	ta-	tions
dh I	k {	p I	t eI	S V n z
de-	ca-	pi-	tate
dh i:	k {	p I	t eI t
de-	ca-	to
dh I	k Q	t @U
de-	ca-	tur
dh I	k eI	t @r
de-	cade
dh e	k eI d
de-	cades
dh e	k eI d z
de-	cade's
dh e	k eI d z
de-	caf
dh i:	k { f
de-	caf-	fei-	na-	ted
dh i:	k {	f I	n eI	t I d
de-	caf-	fei-	na-	ting
dh i:	k {	f I	n eI	t I N
de-	caf-	fei-	na-	tion
dh i:	k {	f I	n eI	S V n
de-	caf-	fei-	nate
dh i:	k {	f I	n eI t
de-	cals
dh i:	k { l z
de-	camp
dh V	k { m p
de-	camped
dh i:	k { m p t
de-	can-	ting
dh V	k { n	t I N
de-	cant
dh V	k { n t
de-	cath-	lete
dh i:	k { T	l i: t
de-	cath-	lon
dh i:	k { T	l O: n
de-	cay
dh V	k eI
de-	cay-	ing
dh V	k eI	I N
de-	cayed
dh V	k eI d
de-	cays
dh V	k eI z
de-	ce-	dent
dh e	s i:	d V n t
de-	ce-	dents
dh e	s i:	d V n t s
de-	ce-	dent's
dh e	s i:	d V n t s
de-	ce-	le-	ra-	ted
dh V	s e	l @r	eI	t V d
de-	ce-	le-	ra-	ting
dh V	s e	l @r	eI	t I N
de-	ce-	le-	ra-	tion
dh V	s e	l @r	eI	S V n
de-	ce-	le-	rate
dh V	s e	l @r	eI t
de-	cease
dh V	s i: s
de-	ceased
dh V	s i: s t
de-	cei-	ving
dh V	s i:	v I N
de-	ceit
dh V	s i: t
de-	ceit-	ful
dh V	s i: t	f V l
de-	ceits
dh V	s i: t s
de-	ceive
dh V	s i: v
de-	ceived
dh V	s i: v d
de-	cem-	ber
dh V	s e m	b @r
de-	cem-	ber's
dh V	s e m	b @r z
de-	cen-	cy
dh i:	s V n	s i:
de-	cen-	ni-	al
dh V	s e	n i:	V l
de-	cent
dh i:	s V n t
de-	cent-	ly
dh i:	s V n	t l i:
de-	cent-	ra-	li-	za-	tion
dh V	s e n	t r V	l V	z eI	S V n
de-	cent-	ra-	li-	zing
dh V	s e n	t r V	l aI	z I N
de-	cent-	ra-	lize
dh V	s e n	t r V	l aI z
de-	cent-	ra-	lized
dh V	s e n	t r V	l aI z d
de-	cep-	tion
dh V	s e p	S V n
de-	cep-	tions
dh V	s e p	S V n z
de-	cep-	tive
dh V	s e p	t I v
de-	cep-	tive-	ly
dh V	s e p	t I v	l i:
de-	cer-	ti-	fi-	ca-	tion
dh i:	s @r	t I	f I	k eI	S V n
de-	cer-	ti-	fied
dh i:	s @r	t I	f aI d
de-	cer-	ti-	fy
dh i:	s @r	t I	f aI
de-	cherd
dh e	tS @r d
de-	ci-	bel
dh e	s I	b e l
de-	ci-	bels
dh e	s I	b V l z
de-	ci-	ded
dh V	s aI	d V d
de-	ci-	ded-	ly
dh V	s aI	d V d	l i:
de-	ci-	ding
dh V	s aI	d I N
de-	ci-	du-	ous
dh V	s I	dZ u:	V s
de-	ci-	li-	ter
dh e	s I	l i:	t @r
de-	ci-	ma
dh I	tS i:	m V
de-	ci-	ma-	ted
dh e	s I	m eI	t I d
de-	ci-	ma-	ting
dh e	s I	m eI	t I N
de-	ci-	ma-	tion
dh e	s I	m eI	S V n
de-	ci-	mal
dh e	s I	m V l
de-	ci-	mals
dh e	s I	m V l z
de-	ci-	mate
dh e	s I	m eI t
de-	ci-	phe-	ring
dh V	s aI	f @r	I N
de-	ci-	pher
dh V	s aI	f @r
de-	ci-	phered
dh V	s aI	f @r d
de-	ci-	sion
dh V	s I	Z V n
de-	ci-	sion-	ma-	ker
dh V	s I	Z V n	m eI	k @r
de-	ci-	sions
dh V	s I	Z V n z
de-	ci-	sion's
dh V	s I	Z V n z
de-	ci-	sive
dh V	s aI	s I v
de-	ci-	sive-	ly
dh V	s aI	s I v	l i:
de-	ci-	sive-	ness
dh V	s aI	s I v	n V s
de-	cide
dh V	s aI d
de-	cides
dh V	s aI d z
de-	co
dh e	k @U
de-	co-	der
dh I	k @U	d @r
de-	co-	ders
dh I	k @U	d @r z
de-	co-	ding
dh I	k @U	d I N
de-	co-	rum
dh I	k O@	V m
de-	code
dh I	k @U d
de-	com-	mis-	sio-	ning
dh i:	k V	m I	S V	n I N
de-	com-	mis-	sion
dh i:	k V	m I	S V n
de-	com-	mis-	sioned
dh i:	k V	m I	S V n d
de-	com-	po-	ses
dh i:	k V m	p @U	z V z
de-	com-	po-	si-	tion
dh i:	k V m	p @U	z I	S V n
de-	com-	po-	sing
dh i:	k V m	p @U	z I N
de-	com-	pose
dh i:	k V m	p @U z
de-	com-	posed
dh i:	k V m	p @U z d
de-	com-	pres-	sion
dh i:	k V m	p r e	S V n
de-	con-	ges-	tant
dh I	k V n	dZ e s	t V n t
de-	con-	ges-	tants
dh I	k V n	dZ e s	t V n t s
de-	cou-	ple
dh i:	k V	p V l
de-	coup-	ling
dh i:	k V p	l I N
de-	coy
dh V	k OI
de-	coys
dh i:	k OI z
de-	cre-	pit
dh V k	r e	p V t
de-	crea-	ses
dh I k	r i:	s V z
de-	crea-	sing
dh I k	r i:	s I N
de-	crease
dh I k	r i: s
de-	creased
dh I k	r i: s t
de-	cree
dh I k	r i:
de-	creed
dh I k	r i: d
de-	crees
dh I k	r i: z
de-	cri-	mi-	na-	li-	za-	tion
dh i: k	r I	m I	n V	l I	z eI	S V n
de-	cri-	mi-	na-	li-	zing
dh i: k	r I	m I	n V	l aI	z I N
de-	cri-	mi-	na-	lize
dh i: k	r I	m I	n V	l aI z
de-	cried
dh I k	r aI d
de-	cries
dh I k	r aI z
de-	di-	ca-	ted
dh e	d I	k eI	t I d
de-	di-	ca-	ting
dh e	d I	k eI	t I N
de-	di-	ca-	tion
dh e	d I	k eI	S V n
de-	di-	cate
dh e	d I	k eI t
de-	di-	cates
dh e	d I	k eI t s
de-	do
dh eI	d @U
de-	duc-	ted
dh V	d V k	t V d
de-	duc-	ti-	bi-	li-	ty
dh V	d V k	t V	b I	l V	t i:
de-	duc-	ti-	ble
dh V	d V k	t V	b V l
de-	duc-	ti-	bles
dh V	d V k	t V	b V l z
)"
R"(de-	duc-	ting
dh V	d V k	t I N
de-	duc-	tion
dh V	d V k	S V n
de-	duc-	tions
dh V	d V k	S V n z
de-	duce
dh V	d u: s
de-	duced
dh V	d u: s t
de-	duct
dh V	d V k t
de-	ducts
dh V	d V k t s
de-	em-	pha-	si-	zing
dh i:	e m	f V	s aI	z I N
de-	em-	pha-	size
dh i:	e m	f V	s aI z
de-	ex-	cite
dh i:	I k	s aI t
de-	fa-	cing
dh V	f eI	s I N
de-	fa-	ma-	tion
dh e	f V	m eI	S V n
de-	fa-	ma-	to-	ry
dh V	f {	m V	t O@	i:
de-	face
dh V	f eI s
de-	faced
dh V	f eI s t
de-	fal-	co
dh V	f Q l	k @U
de-	fame
dh V	f eI m
de-	famed
dh V	f eI m d
de-	faul-	ted
dh V	f O: l	t V d
de-	faul-	ters
dh V	f O: l	t @r z
de-	faul-	ting
dh V	f O: l	t I N
de-	fault
dh V	f O: l t
de-	faults
dh V	f O: l t s
de-	fe-	ren-	tial
dh e	f @r	e n	tS V l
de-	fe-	rence
dh e	f @r	V n s
de-	fea-	sance
dh V	f i:	z V n s
de-	fea-	ted
dh V	f i:	t V d
de-	fea-	ti-	sm
dh V	f i:	t I	z V m
de-	fea-	ting
dh V	f i:	t I N
de-	fea-	tist
dh V	f i:	t I s t
de-	feat
dh V	f i: t
de-	feats
dh V	f i: t s
de-	fec-	ted
dh V	f e k	t V d
de-	fec-	ting
dh V	f e k	t I N
de-	fec-	tion
dh V	f e k	S V n
de-	fec-	tions
dh V	f e k	S V n z
de-	fec-	tive
dh V	f e k	t I v
de-	fec-	tor
dh V	f e k	t @r
de-	fec-	tors
dh V	f e k	t @r z
de-	fect
dh i:	f e k t
de-	fects
dh i:	f e k t s
de-	fen-	dant
dh V	f e n	d V n t
de-	fen-	dants
dh V	f e n	d V n t s
de-	fen-	dant's
dh V	f e n	d V n t s
de-	fen-	ded
dh V	f e n	d V d
de-	fen-	der
dh V	f e n	d @r
de-	fen-	ders
dh V	f e n	d @r z
de-	fen-	der's
dh V	f e n	d @r z
de-	fen-	ding
dh V	f e n	d I N
de-	fen-	ses
dh V	f e n	s V z
de-	fen-	se's
dh V	f e n	s V z
de-	fen-	si-	ble
dh V	f e n	s V	b V l
de-	fen-	sive
dh V	f e n	s I v
de-	fen-	sive-	ly
dh V	f e n	s I v	l i:
de-	fen-	sive-	ness
dh V	f e n	s I v	n V s
de-	fence
dh V	f e n s
de-	fend
dh V	f e n d
de-	fends
dh V	f e n d z
de-	fense
dh V	f e n s
de-	fense-	less
dh V	f e n	s l V s
de-	fer
dh V	f @r
de-	fer-	ment
dh V	f @r	m V n t
de-	fer-	ments
dh V	f @r	m V n t s
de-	fer-	ral
dh V	f @r	V l
de-	fer-	rals
dh V	f @r	V l z
de-	fer-	ring
dh V	f @r	I N
de-	ferred
dh V	f @r d
de-	fers
dh V	f @r z
de-	fi-	ance
dh V	f aI	V n s
de-	fi-	ant
dh V	f aI	V n t
de-	fi-	ant-	ly
dh V	f aI	V n	t l i:
de-	fi-	bril-	la-	tor
dh i:	f I b	r I	l eI	t @r
de-	fi-	bril-	la-	tors
dh i:	f I b	r I	l eI	t @r z
de-	fi-	cien-	cies
dh V	f I	S V n	s i: z
de-	fi-	cien-	cy
dh V	f I	S V n	s i:
de-	fi-	cient
dh V	f I	S V n t
de-	fi-	cit
dh e	f I	s I t
de-	fi-	cits
dh e	f I	s I t s
de-	fi-	cit's
dh e	f I	s I t s
de-	fi-	na-	ble
dh V	f aI	n V	b V l
de-	fi-	ni-	tion
dh e	f I	n I	S V n
de-	fi-	ni-	tions
dh e	f I	n I	S V n z
de-	fi-	ni-	tive
dh V	f I	n I	t I v
de-	fi-	ni-	tive-	ly
dh V	f I	n I	t I v	l i:
de-	fi-	ning
dh V	f aI	n I N
de-	fi-	nite
dh e	f I	n I t
de-	fi-	nite-	ly
dh e	f I	n I t	l i:
de-	fied
dh V	f aI d
de-	fies
dh V	f aI z
de-	fine
dh V	f aI n
de-	fined
dh V	f aI n d
de-	fines
dh V	f aI n z
de-	fo-	li-	ant
dh V	f @U	l i:	V n t
de-	fo-	li-	ants
dh V	f @U	l i:	V n t s
de-	fo-	res-	ta-	tion
dh V	f O@	V s	t eI	S V n
de-	fo-	rest
dh V	f O@	V s t
de-	foe
dh V	f @U
de-	foe's
dh V	f @U z
de-	for-	ma-	tion
dh i:	f O@	m eI	S V n
de-	for-	mi-	ties
dh V	f O@	m V	t i: z
de-	for-	mi-	ty
dh V	f O@	m V	t i:
de-	ford
dh e	f @r d
de-	ford's
dh e	f @r d z
de-	form
dh i:	f O@ m
de-	formed
dh V	f O@ m d
de-	fu-	sing
dh V f	j u:	z I N
de-	fun-	ding
dh i:	f V n	d I N
de-	funct
dh V	f V N k t
de-	fund
dh i:	f V n d
de-	fuse
dh V f	j u: z
de-	fused
dh V f	j u: z d
de-	fy
dh V	f aI
de-	fy-	ing
dh V	f aI	I N
de-	gas
dh eI	g V s
de-	ge-	ne-	ra-	cy
dh I	dZ e	n @r	V	s i:
de-	ge-	ne-	ra-	ted
dh I	dZ e	n @r	eI	t V d
de-	ge-	ne-	ra-	ting
dh I	dZ e	n @r	eI	t I N
de-	ge-	ne-	ra-	tion
dh I	dZ e	n @r	eI	S V n
de-	ge-	ne-	ra-	tive
dh I	dZ e	n @r	V	t I v
de-	ge-	ne-	rate
dh I	dZ e	n @r	V t
de-	ge-	ne-	rates
dh I	dZ e	n @r	V t s
de-	ge-	ne-	res
dh I	dZ V	n e@	e s
de-	ge-	ner
dh e	g i:	n @r
de-	hoff
dh e	h O: f
de-	hu-	ma-	ni-	za-	tion
dh i: h	j u:	m V	n V	z eI	S V n
de-	hu-	ma-	ni-	zing
dh i: h	j u:	m V	n aI	z I N
de-	hu-	ma-	nize
dh V h	j u:	m V	n aI z
de-	hu-	ma-	nized
dh V h	j u:	m V	n aI z d
de-	hyd-	ra-	ted
dh V	h aI d	r eI	t V d
de-	hyd-	ra-	tion
dh i:	h aI d	r eI	S V n
de-	hyd-	rate
dh V	h aI d	r eI t
de-	i-	fi-	ca-	tion
dh i:	V	f V	k eI	S V n
de-	i-	fy
dh i:	V	f aI
de-	i-	sm
dh i:	I	z V m
de-	i-	ties
dh i:	I	t i: z
de-	i-	ty
dh i:	I	t i:
de-	in-	sti-	tu-	tio-	na-	li-	za-	tion
dh i:	I n	s t I	t u:	S V	n V	l I	z eI	S V n
de-	in-	sti-	tu-	tio-	na-	lize
dh i:	I n	s t I	t u:	S V	n V	l aI z
de-	ist
dh i:	I s t
de-	ja
dh i:	dZ V
de-	je-	sus
dh I	dZ i:	z V s
de-	jec-	ted
dh I	dZ e k	t V d
de-	ject
dh I	dZ e k t
de-	kalb
dh I	k { l b
de-	kle
dh e	k V l
de-	la
dh e	l V
de-	la-	cruz
dh eI	l Q k	r u: z
de-	la-	field
dh e	l V	f i: l d
de-	la-	ney
dh V	l eI	n i:
de-	la-	no
dh V	l Q	n @U
de-	la-	van
dh e	l V	v V n
de-	la-	wa-	ri-	an
dh e	l V	w e@	i:	V n
de-	la-	ware
dh e	l V	w e@
de-	la-	ware's
dh e	l V	w e@ z
de-	laine
dh V	l eI n
de-	lan-	cey
dh e	l V n	s i:
de-	land
dh V	l { n d
de-	lay
dh V	l eI
de-	lay-	ing
dh V	l eI	I N
de-	layed
dh V	l eI d
de-	lays
dh V	l eI z
de-	le-	ga-	ted
dh e	l V	g eI	t V d
de-	le-	ga-	ting
dh e	l V	g eI	t I N
de-	le-	ga-	tion
dh e	l V	g eI	S V n
de-	le-	ga-	tions
dh e	l V	g eI	S V n z
de-	le-	ga-	tion's
dh e	l V	g eI	S V n z
de-	le-	gate
dh e	l V	g eI t
de-	le-	gates
dh e	l V	g eI t s
de-	le-	gate's
dh e	l I	g V t s
de-	le-	on
dh e	l i:	V n
de-	le-	te-	ri-	ous
dh e	l V	t I@	i:	V s
de-	le-	ted
dh V	l i:	t V d
de-	le-	ting
dh V	l i:	t I N
de-	le-	tion
dh V	l i:	S V n
de-	le-	tions
dh V	l i:	S V n z
de-	lec-	ta-	ble
dh V	l e k	t V	b V l
de-	lete
dh V	l i: t
de-	li
dh e	l i:
de-	li-	be-	ra-	ted
dh V	l I	b @r	eI	t V d
de-	li-	be-	ra-	ting
dh V	l I	b @r	eI	t I N
de-	li-	be-	ra-	tion
dh V	l I	b @r	eI	S V n
de-	li-	be-	ra-	tions
dh V	l I	b @r	eI	S V n z
de-	li-	be-	ra-	tive
dh V	l I	b @r	eI	t I v
de-	li-	be-	rate
dh V	l I	b @r	V t
de-	li-	be-	rate-	ly
dh V	l I	b @r	V t	l i:
de-	li-	be-	rates
dh V	l I	b @r	eI t s
de-	li-	ca-	cies
dh e	l I	k V	s i: z
de-	li-	ca-	cy
dh e	l I	k V	s i:
de-	li-	ca-	tes-	sen
dh e	l I	k V	t e	s V n
de-	li-	ca-	tes-	sens
dh e	l I	k V	t e	s V n z
de-	li-	cate
dh e	l I	k V t
de-	li-	cate-	ly
dh e	l I	k V t	l i:
de-	li-	cia
dh e	l i:	tS V
de-	li-	cious
dh V	l I	S V s
de-	li-	cious-	ly
dh V	l I	S V s	l i:
de-	li-	la
dh e	l i:	l V
de-	li-	lah
dh V	l aI	l V
de-	li-	ri-	ous
dh V	l I@	i:	V s
de-	li-	ri-	um
dh V	l I@	i:	V m
de-	li-	ve-	ra-	ble
dh V	l I	v @r	V	b V l
de-	li-	ve-	rance
dh V	l I	v @r	V n s
de-	li-	ve-	rer
dh V	l I	v @r	@r
de-	li-	ve-	rers
dh V	l I	v @r	@r z
de-	li-	ve-	ries
dh V	l I	v @r	i: z
de-	li-	ve-	ring
dh V	l I	v @r	I N
de-	li-	ve-	ry
dh V	l I	v @r	i:
de-	li-	ver
dh V	l I	v @r
de-	li-	vered
dh V	l I	v @r d
de-	li-	vers
dh V	l I	v @r z
de-	lia
dh i: l	j V
de-	ligh-	ted
dh V	l aI	t V d
de-	ligh-	ting
dh V	l aI	t I N
de-	light
dh V	l aI t
de-	light-	ful
dh V	l aI t	f V l
de-	light-	ful-	ly
dh V	l aI t	f V	l i:
de-	lights
dh V	l aI t s
de-	lil-	lo
dh V	l I	l @U
de-	lin-	quent
dh V	l I N	k w V n t
de-	lis-	ted
dh i:	l I s	t V d
de-	lis-	ting
dh i:	l I s	t I N
de-	lisle
dh V	l aI l
de-	list
dh i:	l I s t
de-	lo-	ra
dh e	l O@	V
de-	lo-	re-	an
dh V	l O@	i:	V n
de-	lo-	ren-	zo
dh e	l O@	e n	z @U
de-	lo-	res
dh V	l O@	V s
de-	lo-	ri-	a
dh e	l O@	i:	V
de-	lo-	ris
dh e	l @r	I s
de-	long
dh V	l O: N
de-	lor-	me
dh e	l O@	m i:
de-	lors
dh V	l O@ z
de-	lu-	ded
dh V	l u:	d V d
de-	lu-	ding
dh V	l u:	d I N
de-	lu-	sio-	nal
dh V	l u:	Z V	n V l
de-	lu-	sion
dh V	l u:	Z V n
de-	lu-	sions
dh V	l u:	Z V n z
de-	lude
dh V	l u: d
de-	luge
dh e l	j u: dZ
de-	luged
dh e l	j u: dZ d
de-	luxe
dh V	l V k s
de-	ma-	go-	gic
dh e	m V	g Q	dZ I k
de-	ma-	go-	gue-	ry
dh e	m V	g Q	g @r	i:
de-	ma-	go-	guing
dh e	m V	g Q	g I N
de-	ma-	go-	gy
dh e	m V	g Q	dZ i:
de-	ma-	gogue
dh e	m V	g Q g
de-	ma-	gogues
dh e	m V	g Q g z
de-	ma-	i-	o
dh V	m Q	i:	@U
de-	ma-	re-	st
dh eI	m Q@	eI	e s t
de-	ma-	ree
dh e	m @r	i:
de-	ma-	ri-	a
dh I	m Q@	i:	V
de-	mag-	gi-	o
dh V	m Q	dZ i:	@U
de-	main
dh V	m eI n
de-	man
dh i:	m V n
de-	man-	ded
dh I	m { n	d V d
de-	man-	ding
dh I	m { n	d I N
de-	man-	ding-	ly
dh I	m { n	d I N	l i:
de-	mand
dh I	m { n d
de-	mands
dh I	m { n d z
de-	mar-	ca-	tion
dh i:	m Q@	k eI	S V n
de-	mar-	ca-	tions
dh i:	m Q@	k eI	S V n z
de-	mar-	ti-	ni
dh I	m Q@	t i:	n i:
de-	marche
dh I	m Q@ tS
de-	mark
dh V	m Q@ k
de-	me-	rit
dh i:	m e@	I t
de-	me-	rits
dh i:	m e@	I t s
de-	me-	ter
dh I	m i:	t @r
de-	me-	tre
dh e	m i:	t @r
de-	me-	yer
dh e	m aI	@r
de-	mea-	ning
dh I	m i:	n I N
de-	mea-	nor
dh I	m i:	n @r
de-	mean
dh I	m i: n
de-	meaned
dh I	m i: n d
de-	means
dh I	m i: n z
de-	men-	ted
dh I	m e n	t V d
de-	men-	ti-	a
dh I	m e n	S i:	V
de-	ment
dh V	m e n t
de-	mer-	ger
dh i:	m @r	dZ @r
de-	met-	ri-	a
dh I	m e t	r i:	V
de-	met-	ri-	us
dh I	m i: t	r i:	V s
de-	mi
dh e	m i:
de-	mi-	li-	ta-	ri-	za-	tion
dh i:	m I	l I	t @r	I	z eI	S V n
de-	mi-	li-	ta-	ri-	zes
dh i:	m I	l I	t @r	aI	z V z
de-	mi-	li-	ta-	ri-	zing
dh i:	m I	l I	t @r	aI	z I N
de-	mi-	li-	ta-	rize
dh i:	m I	l I	t @r	aI z
de-	mi-	li-	ta-	rized
dh i:	m I	l I	t @r	aI z d
de-	mi-	rel
dh V	m I@	V l
de-	ming
dh e	m I N
de-	mise
dh I	m aI z
de-	mo
dh e	m @U
de-	mo-	bi-	li-	za-	tion
dh i:	m @U	b V	l aI	z eI	S V n
de-	mo-	bi-	lize
dh I	m @U	b I	l aI z
de-	mo-	bi-	lized
dh I	m @U	b I	l aI z d
de-	mo-	cra-	cies
dh I	m Q k	r V	s i: z
de-	mo-	cra-	cy
dh I	m Q k	r V	s i:
de-	mo-	cra-	cy's
dh I	m Q k	r V	s i: z
de-	mo-	cra-	ti-	za-	tion
dh I	m Q k	r V	t V	z eI	S V n
de-	mo-	cra-	ti-	zing
dh I	m Q k	r V	t aI	z I N
de-	mo-	cra-	tic
dh e	m V k	r {	t I k
de-	mo-	cra-	tical-	ly
dh e	m V k	r {	t I k	l i:
de-	mo-	cra-	tize
dh I	m Q k	r V	t aI z
de-	mo-	cra-	tized
dh I	m Q k	r V	t aI z d
de-	mo-	crat
dh e	m V k	r { t
de-	mo-	crats
dh e	m V k	r { t s
de-	mo-	crat's
dh e	m V k	r { t s
de-	mo-	du-	la-	tion
dh i:	m Q	dZ V	l eI	S V n
de-	mo-	du-	late
dh i:	m Q	dZ V	l eI t
de-	mo-	li-	shing
dh I	m Q	l I	S I N
de-	mo-	li-	tion
dh e	m V	l I	S V n
de-	mo-	lish
dh V	m Q	l I S
de-	mo-	lished
dh I	m Q	l I S t
de-	mo-	ni-	za-	tion
dh i:	m V	n V	z eI	S V n
de-	mo-	ni-	zing
dh i:	m V	n aI	z I N
de-	mo-	nic
dh I	m Q	n I k
de-	mo-	nize
dh i:	m V	n aI z
de-	mo-	nized
dh i:	m V	n aI z d
de-	mo-	ra-	li-	za-	tion
dh I	m O@	V	l V	z eI	S V n
de-	mo-	ra-	li-	zing
dh I	m O@	V	l aI	z I N
de-	mo-	ra-	lize
dh I	m O@	V	l aI z
de-	mo-	ra-	lized
dh I	m O@	V	l aI z d
de-	mo-	rest
dh eI	m O@	e s t
de-	mo-	ted
dh I	m @U	t V d
de-	mo-	tion
dh I	m @U	S V n
de-	mo-	tions
dh I	m @U	S V n z
de-	mog-	ra-	pher
dh e	m Q g	r V	f @r
de-	mog-	ra-	phers
dh e	m Q g	r V	f @r z
de-	mog-	ra-	phic
dh e	m V g	r {	f I k
de-	mog-	ra-	phical-	ly
dh e	m V g	r {	f I k	l i:
de-	mog-	ra-	phics
dh e	m V g	r {	f I k s
de-	mog-	ra-	phy
dh e	m Q g	r V	f i:
de-	mon
dh i:	m V n
de-	mons
dh i:	m V n z
de-	mons-	tra-	ble
dh e	m V n	s t r V	b V l
de-	mons-	tra-	ted
dh e	m V n	s t r eI	t V d
de-	mons-	tra-	ting
dh e	m V n	s t r eI	t I N
de-	mons-	tra-	tion
dh e	m V n	s t r eI	S V n
de-	mons-	tra-	tions
dh e	m V n	s t r eI	S V n z
de-	mons-	tra-	tive
dh I	m Q n	s t r V	t I v
de-	mons-	tra-	tor
dh e	m V n	s t r eI	t @r
de-	mons-	tra-	tors
dh e	m V n	s t r eI	t @r z
de-	mons-	trab-	ly
dh I	m Q n	s t r V b	l i:
de-	mons-	trate
dh e	m V n	s t r eI t
de-	mons-	trates
dh e	m V n	s t r eI t s
de-	mos
dh e	m @U z
de-	mote
dh I	m @U t
de-	mott
dh V	m Q t
de-	mur
dh I	m @r
de-	mur-	ring
dh I	m @r	I N
de-	mure
dh I m	j U@
de-	mure-	ly
dh I m	j U@	l i:
de-	murred
dh I	m @r d
de-	murs
dh I	m @r z
de-	mus
dh i:	m V s
de-	muth
dh i:	m V T
de-	mys-	ti-	fy
dh i:	m I s	t I	f aI
de-	na
dh i:	n V
de-	na-	ri-	us
dh V	n {	r i:	V s
de-	na-	rii
dh V	n {	r i:
de-	na-	ro
dh V	n Q@	@U
de-	na-	tio-	na-	li-	za-	tion
dh i:	n {	S V	n V	l I	z eI	S V n
de-	na-	tio-	na-	li-	za-	tions
dh i:	n {	S V	n V	l I	z eI	S V n z
de-	na-	tio-	na-	li-	zing
dh V	n {	S V	n V	l aI	z I N
de-	na-	tio-	na-	lize
dh V	n {	S V	n V	l aI z
de-	na-	tio-	na-	lized
dh V	n {	S V	n V	l aI z d
de-	na-	ture
dh V	n eI	tS @r
de-	na-	tured
dh V	n eI	tS @r d
de-	neen
dh I	n i: n
de-	neuve
dh I	n V v
de-	ni-	a-	bi-	li-	ty
dh V	n aI	V	b I	l V	t i:
de-	ni-	al
dh V	n aI	V l
de-	ni-	als
dh V	n aI	V l z
de-	ni-	o
dh i:	n i:	@U
de-	ni-	son
dh e	n I	s V n
de-	ni-	son's
dh e	n I	s V n z
de-	ni-	zen
dh e	n V	z V n
de-	ni-	zens
dh e	n V	z V n z
de-	nice
dh I	n i: s
de-	nied
dh V	n aI d
de-	nies
dh V	n aI z
de-	nig-	ra-	ted
dh e	n I g	r eI	t V d
de-	nig-	ra-	ting
dh e	n I g	r eI	t I N
de-	nig-	rate
dh e	n I g	r eI t
de-	nim
dh e	n I m
de-	nis
dh e	n I s
de-	nise
dh V	n i: s
de-	niz
dh eI	n i: z
de-	no-	mi-	na-	ted
dh V	n Q	m V	n eI	t V d
de-	no-	mi-	na-	tio-	nal
dh V	n O:	m V	n eI	S V	n V l
de-	no-	mi-	na-	tion
dh V	n O:	m V	n eI	S V n
de-	no-	mi-	na-	tions
dh V	n O:	m V	n eI	S V n z
de-	no-	mi-	na-	tion's
dh V	n O:	m V	n eI	S V n z
de-	no-	mi-	na-	tor
dh V	n Q	m V	n eI	t @r
de-	no-	mi-	nate
dh V	n Q	m V	n eI t
de-	no-	ted
dh V	n @U	t V d
de-	note
dh V	n @U t
de-	notes
dh V	n @U t s
de-	noue-	ment
dh eI	n u:	m Q n
de-	noun-	ces
dh V	n aU n	s V z
de-	noun-	cing
dh V	n aU n	s I N
de-	nounce
dh V	n aU n s
de-	nounced
dh V	n aU n s t
de-	nu-	ded
dh V	n u:	d V d
de-	nu-	ding
dh V	n u:	d I N
de-	nuc-	le-	a-	ri-	za-	tion
dh i:	n u: k	l i:	@r	I	z eI	S V n
de-	nuc-	le-	a-	rize
dh i:	n u: k	l i:	@r	aI z
de-	nuc-	le-	a-	rized
dh i:	n u: k	l i:	@r	aI z d
de-	nude
dh V	n u: d
de-	nun-	ci-	a-	tion
dh V	n V n	s i:	eI	S V n
de-	nun-	ci-	a-	tions
dh V	n V n	s i:	eI	S V n z
de-	ny
dh V	n aI
de-	ny-	ing
dh V	n aI	I N
de-	nys
dh e	n I s
de-	nyse
dh e	n aI s
de-	o
dh i:	@U
de-	o-	do-	rant
dh i:	@U	d @r	V n t
de-	o-	do-	rants
dh i:	@U	d @r	V n t s
de-	o-	xy-	ri-	bo-	nuc-	le-	ic
dh i:	Q k	s i:	r aI	b @U	n u: k	l eI	I k
de-	on
dh i:	Q n
de-	par-	dieu
dh i:	p Q@ d	j V
de-	par-	ted
dh V	p Q@	t V d
de-	par-	ting
dh V	p Q@	t I N
de-	part
dh V	p Q@ t
de-	part-	men-	ta-	lize
dh V	p Q@ t	m e n	t V	l aI z
de-	part-	men-	ta-	lized
dh V	p Q@ t	m e n	t V	l aI z d
de-	part-	men-	tal
dh V	p Q@ t	m e	n V l
de-	part-	ment
dh V	p Q@ t	m V n t
de-	pen-	ded
dh V	p e n	d V d
de-	pen-	den-	cies
dh V	p e n	d V n	s i: z
de-	pen-	den-	cy
dh V	p e n	d V n	s i:
de-	pen-	dence
dh V	p e n	d V n s
de-	pen-	dent
dh V	p e n	d V n t
de-	pen-	dents
dh V	p e n	d V n t s
de-	pen-	ding
dh V	p e n	d I N
de-	pends
dh V	p e n d z
de-	per-	so-	na-	lize
dh i:	p @r	s V	n V	l aI z
de-	pew
dh V p	j u:
de-	pi-	la-	to-	ry
dh V	p I	l V	t O@	i:
de-	pic-	ted
dh V	p I k	t V d
de-	pic-	ting
dh V	p I k	t I N
de-	pic-	tion
dh V	p I k	S V n
de-	pic-	tions
dh V	p I k	S V n z
de-	pict
dh V	p I k t
de-	picts
dh V	p I k t s
de-	ple-	ted
dh V p	l i:	t V d
de-	ple-	ting
dh V p	l i:	t I N
de-	ple-	tion
dh V p	l i:	S V n
de-	plete
dh V p	l i: t
de-	pletes
dh V p	l i: t s
de-	plo-	ra-	ble
dh V p	l O@	V	b V l
de-	plo-	ring
dh V p	l O@	I N
de-	plo-	ya-	ble
dh V p	l OI	V	b V l
de-	plore
dh V p	l O@
de-	plored
dh V p	l O@ d
de-	plores
dh V p	l O@ z
de-	ploy
dh V p	l OI
de-	ploy-	ing
dh V p	l OI	I N
de-	ploy-	ment
dh V p	l OI	m V n t
de-	ploy-	ments
dh V p	l OI	m V n t s
de-	ployed
dh V p	l OI d
de-	ploys
dh V p	l OI z
de-	po-	pu-	la-	tion
dh V	p Q p	j V	l eI	S V n
de-	po-	pu-	late
dh i:	p Q p	j V	l eI t
de-	po-	si-	ta-	ry
dh V	p Q	z V	t e@	i:
de-	po-	si-	ted
dh V	p Q	z V	t V d
de-	po-	si-	ting
dh V	p Q	z V	t I N
de-	po-	si-	tio-	nal
dh e	p V	z I	S V	n V l
de-	po-	si-	tion
dh e	p V	z I	S V n
de-	po-	si-	tions
dh e	p V	z I	S V n z
de-	po-	si-	to-	ry
dh V	p Q	z V	t O@	i:
de-	po-	si-	tor
dh V	p Q	z V	t @r
de-	po-	si-	tors
dh V	p Q	z V	t @r z
de-	po-	si-	tor's
dh V	p Q	z V	t @r z
de-	po-	sit
dh V	p Q	z V t
de-	po-	sits
dh V	p Q	z V t s
de-	por-	ta-	tion
dh i:	p O@	t eI	S V n
de-	por-	ta-	tions
dh i:	p O@	t eI	S V n z
de-	por-	ted
dh V	p O@	t V d
de-	por-	tee
dh i:	p O@	t i:
de-	por-	tees
dh i:	p O@	t i: z
de-	por-	ting
dh V	p O@	t I N
de-	port
dh V	p O@ t
de-	port-	ment
dh V	p O@ t	m V n t
de-	pose
dh V	p @U z
de-	posed
dh V	p @U z d
de-	pot
dh i:	p @U
de-	pots
dh i:	p @U z
de-	pot's
dh i:	p @U z
de-	poy
dh e	p OI
de-	pu-	ties
dh e p	j V	t i: z
de-	pu-	tize
dh e p	j V	t aI z
de-	pu-	tized
dh e p	j V	t aI z d
de-	pu-	ty
dh e p	j V	t i:
de-	pue
dh V p	j u:
de-	puy
dh V p	w i:
de-	rai-	ling
dh I@	eI	l I N
de-	rail
dh I@	eI l
)"
R"(de-	rail-	ment
dh I@	eI l	m V n t
de-	rail-	ments
dh I@	eI l	m V n t s
de-	railed
dh I@	eI l d
de-	rails
dh I@	eI l z
de-	range
dh I@	eI n dZ
de-	ranged
dh I@	eI n dZ d
de-	re-	gu-	la-	ted
dh i:	r e g	j V	l eI	t V d
de-	re-	gu-	la-	ting
dh i:	r e g	j V	l eI	t I N
de-	re-	gu-	la-	tion
dh i:	r e g	j V	l eI	S V n
de-	re-	gu-	la-	to-	ry
dh i:	r e g	j V	l V	t O@	i:
de-	re-	gu-	la-	tor
dh i:	r e g	j V	l eI	t @r
de-	re-	gu-	la-	tors
dh i:	r e g	j V	l eI	t @r z
de-	re-	gu-	late
dh i:	r e g	j V	l eI t
de-	re-	lic-	tion
dh e@	V	l I k	S V n
de-	re-	lict
dh e@	V	l I k t
de-	re-	licts
dh e@	V	l I k t s
de-	rek
dh e@	I k
de-	ri-	ded
dh I@	aI	d V d
de-	ri-	ding
dh I@	aI	d I N
de-	ri-	sion
dh @r	I	Z V n
de-	ri-	sive
dh @r	I	s I v
de-	ri-	sive-	ly
dh @r	I	s I v	l i:
de-	ri-	va-	tion
dh e@	V	v eI	S V n
de-	ri-	va-	tive
dh @r	I	v V	t I v
de-	ri-	va-	tives
dh @r	I	v V	t I v z
de-	ri-	ving
dh @r	aI	v I N
de-	rick
dh e@	I k
de-	ride
dh I@	aI d
de-	rides
dh I@	aI d z
de-	rin-	ger
dh e@	I n	dZ @r
de-	ring
dh I@	I N
de-	rive
dh @r	aI v
de-	rived
dh @r	aI v d
de-	rives
dh @r	aI v z
de-	ro-	ga-	to-	ry
dh @r	Q	g V	t O@	i:
de-	ro-	sa
dh I@	@U	s V
de-	roo
dh e@	u:
de-	ruy-	ter
dh I@	aI	t @r
de-	sa-	i
dh eI	s Q	i:
de-	sa-	li-	na-	tion
dh i:	s eI	l I	n eI	S V n
de-	sa-	li-	ni-	za-	tion
dh i:	s eI	l I	n I	z eI	S V n
de-	san-	tis
dh eI	s Q n	t I s
de-	se-	ret
dh e	s @r	e t
de-	sec-	ra-	ted
dh e	z V k	r eI	t V d
de-	sec-	ra-	tion
dh e	s V k	r eI	S V n
de-	sec-	ra-	tions
dh e	s V k	r eI	S V n z
de-	sec-	rate
dh e	z V k	r eI t
de-	seg-	re-	ga-	ted
dh i:	s e g	r I	g eI	t V d
de-	seg-	re-	ga-	tion
dh i:	s e g	r V	g eI	S V n
de-	seg-	re-	gate
dh i:	s e g	r V	g eI t
de-	sen-	si-	ti-	zing
dh V	s e n	s V	t aI	z I N
de-	sen-	si-	tize
dh V	s e n	s V	t aI z
de-	sen-	si-	tized
dh V	s e n	s V	t aI z d
de-	ser-	ted
dh V	z @r	t V d
de-	ser-	ter
dh e	z @r	t @r
de-	ser-	ters
dh e	z @r	t @r z
de-	ser-	ting
dh e	z @r	t I N
de-	ser-	tion
dh V	z @r	S V n
de-	ser-	tions
dh V	z @r	S V n z
de-	ser-	ved-	ly
dh V	z @r	v V d	l i:
de-	ser-	ving
dh V	z @r	v I N
de-	sert
dh e	z @r t
de-	serts
dh e	z @r t s
de-	serve
dh V	z @r v
de-	served
dh V	z @r v d
de-	serves
dh V	z @r v z
de-	sha
dh e	S V
de-	si
dh e	z i:
de-	si-	mo-	ne
dh V	s i:	m @U	n i:
de-	si-	r-	ing
dh V	z aI	@r	I N
de-	si-	ra-	bi-	li-	ty
dh V	z aI	r V	b I	l V	t i:
de-	si-	ra-	ble
dh V	z aI	r V	b V l
de-	si-	re
dh V	z aI	@r
de-	si-	red
dh V	z aI	@r d
de-	si-	ree
dh e	s aI	r i:
de-	si-	res
dh V	z aI	@r z
de-	si-	rous
dh V	z aI	r V s
de-	sic-	ca-	tion
dh e	s I	k eI	S V n
de-	sig-	na-	ted
dh e	z I g	n eI	t I d
de-	sig-	na-	ting
dh e	z I g	n eI	t I N
de-	sig-	na-	tion
dh e	z I g	n eI	S V n
de-	sig-	na-	tions
dh e	z I g	n eI	S V n z
de-	sig-	nate
dh e	z I g	n eI t
de-	sig-	nates
dh e	z I g	n eI t s
de-	sig-	nee
dh e	z I g	n i:
de-	sig-	nees
dh e	z I g	n i: z
de-	sig-	ner
dh V	z aI	n @r
de-	sig-	ners
dh V	z aI	n @r z
de-	sig-	ner's
dh V	z aI	n @r z
de-	sig-	ning
dh V	z aI	n I N
de-	sign
dh V	z aI n
de-	signed
dh V	z aI n d
de-	signs
dh V	z aI n z
de-	sist
dh V	s I s t
de-	so-	la-	tion
dh e	s V	l eI	S V n
de-	so-	late
dh e	s V	l V t
de-	so-	to
dh I	s @U	t @U
de-	spai-	ring
dh I s	p e@	I N
de-	spair
dh I s	p e@
de-	spaired
dh I s	p e@ d
de-	spairs
dh I s	p e@ z
de-	ta-	cha-	ble
dh V	t {	tS V	b V l
de-	ta-	ches
dh V	t {	tS V z
de-	tach
dh V	t { tS
de-	tach-	ment
dh V	t { tS	m V n t
de-	tached
dh V	t { tS t
de-	tai-	ler
dh i:	t eI	l @r
de-	tai-	ling
dh V	t eI	l I N
de-	tai-	nee
dh i:	t eI	n i:
de-	tai-	nees
dh V	t eI	n i: z
de-	tai-	ning
dh V	t eI	n I N
de-	tail
dh V	t eI l
de-	tailed
dh V	t eI l d
de-	tails
dh V	t eI l z
de-	tain
dh V	t eI n
de-	tained
dh V	t eI n d
de-	tar
dh i:	t Q@
d'e-	tat
dh e	t { t
de-	te-	ri-	o-	ra-	ted
dh V	t I@	i:	@r	eI	t V d
de-	te-	ri-	o-	ra-	ting
dh V	t I@	i:	@r	eI	t I N
de-	te-	ri-	o-	ra-	tion
dh V	t I@	i:	@r	eI	S V n
de-	te-	ri-	o-	rate
dh V	t I@	i:	@r	eI t
de-	te-	ri-	o-	rates
dh V	t I@	i:	@r	eI t s
de-	tec-	ta-	ble
dh V	t e k	t V	b V l
de-	tec-	ted
dh V	t e k	t V d
de-	tec-	ting
dh V	t e k	t I N
de-	tec-	tion
dh V	t e k	S V n
de-	tec-	tive
dh V	t e k	t I v
de-	tec-	tives
dh V	t e k	t I v z
de-	tec-	tive's
dh V	t e k	t I v z
de-	tec-	tor
dh V	t e k	t @r
de-	tec-	tors
dh V	t e k	t @r z
de-	tect
dh V	t e k t
de-	tects
dh V	t e k t s
de-	ten-	tion
dh V	t e n	S V n
de-	ten-	tions
dh V	t e n	S V n z
de-	tente
dh eI	t Q n t
de-	ter
dh V	t @r
de-	ter-	gent
dh V	t @r	dZ V n t
de-	ter-	gents
dh V	t @r	dZ V n t s
de-	ter-	ment
dh V	t @r	m V n t
de-	ter-	mi-	na-	ble
dh V	t @r	m V	n V	b V l
de-	ter-	mi-	na-	tion
dh V	t @r	m V	n eI	S V n
de-	ter-	mi-	na-	tions
dh V	t @r	m V	n eI	S V n z
de-	ter-	mi-	na-	tion's
dh V	t @r	m V	n eI	S V n z
de-	ter-	mi-	na-	tive
dh V	t @r	m V	n V	t I v
de-	ter-	mi-	nant
dh V	t @r	m V	n V n t
de-	ter-	mi-	nants
dh V	t @r	m V	n V n t s
de-	ter-	mi-	nate
dh V	t @r	m V	n eI t
de-	ter-	mi-	ned-	ly
dh V	t @r	m V	n V d	l i:
de-	ter-	mi-	ni-	sm
dh V	t @r	m V	n I	z V m
de-	ter-	mi-	ning
dh V	t @r	m V	n I N
de-	ter-	mi-	nis-	tic
dh V	t @r	m V	n I s	t I k
de-	ter-	mi-	nist
dh V	t @r	m V	n V s t
de-	ter-	mine
dh V	t @r	m V n
de-	ter-	mined
dh V	t @r	m V n d
de-	ter-	mines
dh V	t @r	m V n z
de-	ter-	rence
dh V	t @r	V n s
de-	ter-	rent
dh V	t @r	r V n t
de-	ter-	rents
dh V	t @r	V n t s
de-	ter-	ring
dh V	t @r	I N
de-	terred
dh V	t @r d
de-	ters
dh V	t @r z
de-	tes-	ted
dh V	t e s	t V d
de-	test
dh V	t e s t
de-	to-	na-	ted
dh e	t V	n eI	t V d
de-	to-	na-	ting
dh e	t V	n eI	t I N
de-	to-	na-	tion
dh e	t V	n eI	S V n
de-	to-	na-	tions
dh e	t V	n eI	S V n z
de-	to-	na-	tor
dh e	t V	n eI	t @r
de-	to-	na-	tors
dh e	t V	n eI	t @r z
de-	to-	nate
dh e	t V	n eI t
de-	to-	xi-	ca-	tion
dh V	t Q k	s I	k eI	S V n
de-	to-	xi-	fi-	ca-	tion
dh V	t Q k	s V	f I	k eI	S V n
de-	to-	xi-	fy
dh V	t Q k	s V	f aI
de-	tour
dh I	t U@
de-	toured
dh i:	t U@ d
de-	tours
dh I	t U@ z
de-	tox
dh i:	t Q k s
d'e-	tre
dh e t	r i:
de-	va
dh eI	v V
de-	va-	lu-	a-	ted
dh I	v { l	j u:	eI	t V d
de-	va-	lu-	a-	tion
dh I	v { l	j u:	eI	S V n
de-	va-	lu-	a-	tions
dh i:	v { l	j u:	eI	S V n z
de-	va-	lu-	ate
dh I	v { l	j u:	eI t
de-	va-	lu-	ing
dh I	v { l	j u:	I N
de-	va-	lue
dh I	v { l	j u:
de-	va-	lued
dh I	v { l	j u: d
de-	va-	ney
dh e	v V	n i:
de-	val
dh I	v Q l
de-	vall
dh eI	v Q l
de-	van
dh e	v V n
de-	vas-	ta-	ted
dh e	v V s	t eI	t V d
de-	vas-	ta-	ting
dh e	v V s	t eI	t I N
de-	vas-	ta-	ting-	ly
dh e	v V s	t eI	t I N	l i:
de-	vas-	ta-	tion
dh e	v V s	t eI	S V n
de-	vas-	tate
dh e	v V s	t eI t
de-	vaul
dh I	v @U l
de-	vault
dh I	v @U
de-	ve-	lo-	pa-	ble
dh I	v e	l V	p V	b V l
de-	ve-	lo-	per
dh I	v e	l V	p @r
de-	ve-	lo-	pers
dh I	v e	l V	p @r z
de-	ve-	lo-	per's
dh I	v e	l V	p @r z
de-	ve-	lo-	ping
dh I	v e	l V	p I N
de-	ve-	lop
dh I	v e	l V p
de-	ve-	lop-	men-	tal
dh I	v e	l V p	m e n	t V l
de-	ve-	lop-	men-	tal-	ly
dh I	v e	l V p	m e n	t V	l i:
de-	ve-	lop-	ment
dh I	v e	l V p	m V n t
de-	ve-	lop-	ments
dh I	v e	l V p	m V n t s
de-	ve-	lop-	ment's
dh I	v e	l V p	m V n t s
de-	ve-	loped
dh I	v e	l V p t
de-	ve-	lops
dh I	v e	l V p s
de-	ve-	reux
dh e	v @r	u:
de-	ver
dh i:	v @r
de-	vers
dh e	v @r z
de-	vi-	a-	ted
dh i:	v i:	eI	t V d
de-	vi-	a-	tion
dh i:	v i:	eI	S V n
de-	vi-	a-	tions
dh i:	v i:	eI	S V n z
de-	vi-	an-	cy
dh i:	v i:	e n	s i:
de-	vi-	ance
dh i:	v i:	V n s
de-	vi-	ant
dh i:	v i:	V n t
de-	vi-	ants
dh i:	v i:	V n t s
de-	vi-	ate
dh i:	v i:	eI t
de-	vi-	ates
dh i:	v i:	eI t s
de-	vi-	ces
dh I	v aI	s V z
de-	vi-	ce's
dh I	v aI	s V z
de-	vi-	lish-	ly
dh e	v I	l I S	l i:
de-	vi-	ous
dh i:	v i:	V s
de-	vi-	ses
dh I	v aI	z V z
de-	vi-	sing
dh I	v aI	z I N
de-	vice
dh I	v aI s
de-	vil
dh e	v I l
de-	vil-	wood
dh e	v I l	w U d
de-	vilish
dh e v	l I S
de-	ville
dh V	v I l
de-	ville's
dh V	v I l z
de-	vils
dh e	v I l z
de-	vil's
dh e	v I l z
de-	vin
dh e	v I n
de-	vine
dh V	v aI n
de-	vise
dh I	v aI z
de-	vised
dh I	v aI z d
de-	vitt
dh I	v I t
de-	vo-	lu-	tion
dh e	v V	l u:	S V n
de-	vo-	na
dh e	v V	n V
de-	vo-	ni-	an
dh I	v @U	n i:	V n
de-	vo-	ted
dh I	v @U	t V d
de-	vo-	tee
dh e	v V	t i:
de-	vo-	tees
dh e	v V	t i: z
de-	vo-	ting
dh I	v @U	t I N
de-	vo-	tio-	nal
dh I	v @U	S V	n V l
de-	vo-	tion
dh I	v @U	S V n
de-	vo-	to
dh I	v @U	t @U
de-	vo-	ur
dh I	v aU	@r
de-	void
dh I	v OI d
de-	vol
dh e	v O: l
de-	volve
dh I	v Q l v
de-	volved
dh I	v Q l v d
de-	von
dh e	v V n
de-	von-	shire
dh I	v Q n	S aI r
de-	vore
dh e	v @r
de-	vote
dh I	v @U t
de-	votes
dh I	v @U t s
de-	vou-	r-	ing
dh I	v aU	@r	I N
de-	vou-	red
dh I	v aU	@r d
de-	vou-	rs
dh I	v aU	@r z
de-	vout
dh I	v aU t
de-	vout-	ly
dh I	v aU t	l i:
de-	wan
dh u:	V n
de-	war
dh u:	@r
de-	war's
dh u:	@r z
de-	wart
dh u:	Q@ t
de-	wayne
dh I	w eI n
de-	wees
dh u:	i: z
de-	weese
dh u:	i: z
de-	wey
dh u:	i:
de-	wey's
dh u:	i: z
de-	whirst
dh e	w @r s t
de-	whurst
dh e	w @r s t
de-	wing
dh u:	I N
de-	witt
dh V	w I t
de-	wy
dh u:	i:
de-	young
dh e	j V N
dea-	co-	ness
dh i:	k V	n V s
dea-	con
dh i:	k V n
dea-	cons
dh i:	k V n z
dea-	de-	ning
dh e	d V	n I N
dea-	den
dh e	d V n
dea-	der
dh e	d @r
dea-	dy
dh e	d i:
dea-	fe-	ning
dh e	f V	n I N
dea-	fen
dh e	f V n
dea-	kin
dh i:	k I n
dea-	ler
dh i:	l @r
dea-	ler-	ship
dh i:	l @r	S I p
dea-	ler-	ships
dh i:	l @r	S I p s
dea-	ler-	ship's
dh i:	l @r	S I p s
dea-	lers
dh i:	l @r z
dea-	ler's
dh i:	l @r z
dea-	ling
dh i:	l I N
dea-	lings
dh i:	l I N z
dea-	ner
dh i:	n @r
dea-	rest
dh I@	V s t
dea-	ring
dh I@	I N
dea-	ry
dh I@	i:
dea-	ver
dh i:	v @r
dea-	ver's
dh i:	v @r z
dead
dh e d
dead-	beat
dh e d	b i: t
dead-	beats
dh e d	b i: t s
dead-	bolt
dh e d	b @U l t
dead-	head
dh e d	h e d
dead-	heads
dh e d	h e d z
dead-	li-	er
dh e d	l i:	@r
dead-	li-	est
dh e d	l i:	V s t
dead-	li-	ness
dh e d	l i:	n V s
dead-	line
dh e d	l aI n
dead-	lines
dh e d	l aI n z
dead-	lock
dh e d	l Q k
dead-	locked
dh e d	l Q k t
dead-	locks
dh e d	l Q k s
dead-	ly
dh e d	l i:
dead-	pan
dh e d	p { n
dead-	weight
dh e d	w eI t
dead-	wood
dh e d	w U d
deaf
dh e f
deaf-	ness
dh e f	n V s
deal
dh i: l
deal-	fish
dh i: l	f I S
deal-	ma-	ker
dh i: l	m eI	k @r
deal-	ma-	kers
dh i: l	m eI	k @r z
deal-	ma-	king
dh i: l	m eI	k I N
deale
dh i: l
deals
dh i: l z
dealt
dh e l t
dean
dh i: n
deane
dh i: n
deans
dh i: n z
dean's
dh i: n z
dear
dh I@
dear-	born
dh I@	b O@ n
dear-	den
dh I@	d V n
dear-	ly
dh I@	l i:
dear-	man
dh I@	m V n
dearth
dh @r T
deas
dh i: z
death
dh e T
death-	bed
dh e T	b e d
death-	ly
dh e T	l i:
death-	shot
dh e T	S O: t
death-	watch
dh e T	w Q tS
deaths
dh e T s
death's
dh e T s
deb
dh e b
deb-	bie
dh e	b i:
deb-	bie's
dh e	b i: z
deb-	by
dh e	b i:
deb-	lock
dh e b	l V k
deb-	ra
dh e b	r V
deb-	rie-	fing
dh V b	r i:	f I N
deb-	rief
dh V b	r i: f
deb-	riefed
dh V b	r i: f t
deb-	ris
dh V b	r i:
deb-	tor
dh e	t @r
deb-	tors
dh e	t @r z
deb-	tor's
dh e	t @r z
debes
dh i: b z
debo-	ra
dh e b	r V
debs
dh e b z
debt
dh e t
debts
dh e t s
debt's
dh e t s
dec
dh e k
dec-	ca
dh e	k V
dec-	ker
dh e	k @r
dec-	ker's
dh e	k @r z
dec-	kert
dh e	k @r t
dec-	king
dh e	k I N
dec-	la-	ra-	tion
dh e k	l @r	eI	S V n
dec-	la-	ra-	tions
dh e k	l @r	eI	S V n z
dec-	la-	ra-	to-	ry
dh I k	l e@	V	t O@	i:
dec-	la-	rant
dh I k	l e@	V n t
dec-	la-	ring
dh I k	l e@	I N
dec-	laim
dh I k	l eI m
dec-	laimed
dh I k	l eI m d
dec-	lare
dh I k	l e@
dec-	lared
dh I k	l e@ d
dec-	lares
dh I k	l e@ z
dec-	las-	si-	fied
dh I k	l {	s I	f aI d
dec-	las-	si-	fy
dh I k	l {	s I	f aI
dec-	li-	ner
dh I k	l aI	n @r
dec-	li-	ners
dh I k	l aI	n @r z
dec-	li-	ning
dh I k	l aI	n I N
dec-	line
dh I k	l aI n
dec-	lined
dh I k	l aI n d
dec-	lines
dh I k	l aI n z
dec-	ry
dh I k	r aI
dec-	ry-	ing
dh I k	r aI	I N
deck
dh e k
deck-	man
dh e k	m V n
decked
dh e k t
decks
dh e k s
dec's
dh e k s
ded-	ham
dh e	d V m
ded-	rick
dh e d	r I k
dede
dh i: d
dee
dh i:
dee-	ded
dh i:	d V d
dee-	dee
dh i:	d i:
dee-	dy
dh i:	d i:
dee-	gan
dh i:	g V n
dee-	mer
dh i:	m @r
dee-	ner
dh i:	n @r
dee-	pe-	ning
dh i:	p V	n I N
dee-	pen
dh i:	p V n
dee-	pened
dh i:	p V n d
dee-	pens
dh i:	p V n z
dee-	per
dh i:	p @r
dee-	pest
dh i:	p V s t
dee-	ring
dh I@	I N
dee-	ry
dh I@	i:
deed
dh i: d
deeds
dh i: d z
deem
dh i: m
deemed
dh i: m d
deems
dh i: m z
deen
dh i: n
deep
dh i: p
deep-	ly
dh i: p	l i:
deep-	wa-	ter
dh i: p	w O:	t @r
deer
dh I@
deer-	field
dh I@	f i: l d
deer-	skin
dh I@ s	k I n
deere
dh I@
deere's
dh I@ z
dees
dh i: z
dee's
dh i: z
deets
dh i: t s
def-	la-	ted
dh V f	l eI	t V d
def-	la-	ting
dh V f	l eI	t I N
def-	la-	tio-	na-	ry
dh V f	l eI	S V	n e@	i:
def-	la-	tion
dh V f	l eI	S V n
def-	la-	tor
dh V f	l eI	t @r
def-	late
dh V f	l eI t
def-	lec-	ted
dh V f	l e k	t V d
def-	lec-	ting
dh V f	l e k	t I N
def-	lect
dh V f	l e k t
def-	lects
dh V f	l e k t s
def-	rau-	ded
dh V f	r O:	d V d
def-	rau-	ding
dh V f	r O:	d I N
def-	raud
dh V f	r O: d
def-	ray
dh V f	r eI
def-	rays
dh V f	r eI z
def-	ros-	ting
dh V f	r O: s	t I N
def-	rost
dh V f	r O: s t
deft
dh e f t
deft-	ly
dh e f	t l i:
deg-	ra-	da-	ble
dh I g	r eI	d V	b V l
deg-	ra-	da-	tion
dh e g	r V	d eI	S V n
deg-	ra-	da-	tions
dh e g	r V	d eI	S V n z
deg-	ra-	ded
dh I g	r eI	d V d
deg-	ra-	ding
dh I g	r eI	d I N
deg-	rade
dh I g	r eI d
deg-	rades
dh I g	r eI d z
deg-	raff
dh e g	r V f
deg-	ree
dh I g	r i:
deg-	reed
dh I g	r i: d
deg-	rees
dh I g	r i: z
dei-	bel
dh aI	b V l
dei-	dre
dh i: d	r V
dei-	dre's
dh i: d	r V z
dei-	on
dh i:	j Q n
deigh-	ton
dh eI	t V n
deir-	dre
dh i: r	d r V
deis
dh i: z
dek-	ker
dh e	k @r
dek-	lerk
dh V k	l @r k
del
dh e l
del-	bert
dh e l	b @r t
del-	cam-	bre
dh e l	k Q m	b r i:
del-	ci-	ne
dh e l	tS i:	n i:
del-	co
dh e l	k @U
del-	fi-	ne
dh e l	f i:	n i:
del-	ga-	do
dh e l	g Q	d @U
del-	hi
dh e	l i:
del-	hi's
dh e	l i: z
del-	la
dh e	l V
del-	ler
dh e	l @r
del-	ma
dh e l	m V
del-	mar
dh e l	m @r
del-	mar-	va
dh e l	m Q@	v V
del-	mer
dh e l	m @r
del-	mo-	ni-	co
dh e l	m Q	n i:	k @U
del-	mont
dh eI l	m @U n t
del-	more
dh e l	m O@
del-	phi
dh e l	f aI
del-	phi-	a
dh e l	f i:	V
del-	phi-	na
dh e l	f i:	n V
del-	phi-	ne
dh e l	f i:	n i:
del-	phic
dh e l	f I k
del-	ray
dh e l	r eI
del-	ri-	o
dh e l	r i:	@U
del-	ta
dh e l	t V
del-	ta-	ic
dh e l	t eI	I k
del-	ta's
dh e l	t V z
del-	val-	le
dh e l	v {	l i:
del-	val-	le's
dh e l	v {	l i: z
del-	ving
dh e l	v I N
del-	win
dh e l	w I n
del-	wyn
dh e l	w I n
delfs
dh e l f s
delft
dh e l f t
delft-	ware
dh e l	f t w e@
dell
dh e l
delle
dh e l
dell's
dh e l z
delp
dh e l p
delph
dh e l f
delve
dh e l v
delved
dh e l v d
delves
dh e l v z
dem-	bow-	ski
dh e m	b O: f	s k i:
dem-	jan-	juk
dh e m	j Q n	j u: k
dem-	jan-	juk's
dh e m	j Q n	j u: k s
dem-	mer
dh e	m @r
demp-	sey
dh e m	p s i:
demps-	ter
dh e m	p s t @r
den
dh e n
den-	bo
dh i: n	b @U
den-	by
dh e n	b i:
den-	ham
dh e	n V m
den-	man
dh e n	m V n
den-	mark
dh e n	m Q@ k
den-	mark's
dh e n	m Q@ k s
den-	nard
dh V	n Q@ d
den-	nett
dh e	n V t
den-	ney
dh e	n i:
den-	ni-	son
dh e	n V	s V n
den-	nie
dh e	n i:
den-	ning
dh e	n I N
den-	nis
dh e	n I s
den-	nis-	ton
dh e	n V s	t Q n
den-	ny
dh e	n i:
den-	ny's
dh e	n i: z
den-	ser
dh e n	s @r
den-	sest
dh e n	s V s t
den-	si-	ties
dh e n	s I	t i: z
den-	si-	to-	me-	ter
dh e n	s I	t Q	m V	t @r
den-	si-	ty
dh e n	s I	t i:
den-	tal
dh e n	t V l
den-	tals
dh e n	t V l z
den-	ted
dh e n	t I d
den-	ti-	tion
dh e n	t I	S V n
den-	tin
dh e n	t I n
den-	tine
dh e n	t i: n
den-	ting
dh e n	t I N
den-	tist
dh e n	t I s t
den-	tist-	ry
dh e n	t I s	t r i:
den-	tists
dh e n	t I s t s
den-	tist's
dh e n	t I s t s
den-	ton
dh e n	t V n
den-	ture
dh e n	tS @r
den-	tures
dh e n	tS @r z
den-	ver
dh e n	v @r
den-	ver's
dh e n	v @r z
den-	zil
dh e n	z I l
dend-	ri-	tic
dh e n	d r I	t I k
dend-	roch-	ro-	no-	lo-	gy
dh e n	d r @U k	r V	n Q	l V	dZ i:
denes
dh i: n z
deng
dh e N
deng's
dh e N z
dengue
dh e n g
denn
dh e n
dens
dh e n z
dens-	more
dh i: n	s m O@
dense
dh e n s
dense-	ly
dh e n	s l i:
dent
dh e n t
dente
dh e n t
dents
dh e n t s
dep-	ra-	va-	tion
dh e p	r V	v eI	S V n
dep-	ra-	vi-	ty
dh V p	r {	v V	t i:
dep-	rave
dh i: p	r eI v
dep-	raved
dh i: p	r eI v d
dep-	re-	ca-	ting
dh e p	r V	k eI	t I N
dep-	re-	cate
dh e p	r V	k eI t
dep-	re-	ci-	a-	ted
dh V p	r i:	S i:	eI	t V d
dep-	re-	ci-	a-	ting
dh V p	r i:	S i:	eI	t I N
dep-	re-	ci-	a-	tion
dh V p	r i:	S i:	eI	S V n
)"
R"(dep-	re-	ci-	a-	tions
dh V p	r i:	S i:	eI	S V n z
dep-	re-	ci-	ate
dh V p	r i:	S i:	eI t
dep-	re-	ci-	ates
dh V p	r i:	S i:	eI t s
dep-	re-	cia-	ble
dh V p	r I	S V	b V l
dep-	re-	da-	tion
dh e p	r V	d eI	S V n
dep-	re-	da-	tions
dh e p	r V	d eI	S V n z
dep-	ree
dh V p	r i:
dep-	res-	sant
dh V p	r e	s V n t
dep-	res-	sants
dh V p	r e	s V n t s
dep-	res-	ses
dh V p	r e	s V z
dep-	res-	sing
dh V p	r e	s I N
dep-	res-	sing-	ly
dh V p	r e	s I N	l i:
dep-	res-	sion
dh V p	r e	S V n
dep-	res-	sions
dh V p	r e	S V n z
dep-	res-	sive
dh V p	r e	s I v
dep-	res-	su-	rize
dh V p	r e	S @r	aI z
dep-	res-	su-	rized
dh V p	r e	S @r	aI z d
dep-	ress
dh V p	r e s
dep-	ressed
dh V p	r e s t
dep-	rez
dh eI p	r e z
dep-	ri-	va-	tion
dh e p	r I	v eI	S V n
dep-	ri-	va-	tions
dh e p	r I	v eI	S V n z
dep-	ri-	ving
dh V p	r aI	v I N
dep-	rive
dh V p	r aI v
dep-	rived
dh V p	r aI v d
dep-	rives
dh V p	r aI v z
dep-	rog-	ram
dh i: p	r @U g	r { m
dep-	rog-	ram-	ming
dh i: p	r @U g	r {	m I N
depp
dh e p
depth
dh e p T
depths
dh e p T s
der
dh @r
der-	by
dh @r	b i:
der-	ham
dh @r	h V m
)"