R"(mul-	lahs
m V	l V z
mul-	lan
m V	l V n
mul-	lane
m V	l V n
mul-	len
m V	l V n
mul-	lens
m V	l V n z
mul-	ler
m V	l @r
mul-	ler's
m V	l @r z
mul-	let
m V	l V t
mul-	li-	gan
m V	l I	g V n
mul-	li-	ken
m V	l I	k V n
mul-	lin
m V	l I n
mul-	ling
m V	l I N
mul-	lins
m V	l I n z
mul-	loy
m V	l OI
mul-	ro-	ney
m V l	r @U	n i:
mul-	ro-	ney's
m V l	r @U	n i: z
mul-	ry
m V l	r i:
mul-	ti
m V l	t i:
mul-	ti-	bank
m V l	t i:	b { N k
mul-	ti-	bil-	lion
m V l	t aI	b I l	j V n
mul-	ti-	cen-	ter
m V l	t i:	s e n	t @r
mul-	ti-	co-	lor
m V l	t i:	k V	l @r
mul-	ti-	co-	lored
m V l	t i:	k V	l @r d
mul-	ti-	cul-	tu-	ra-	li-	sm
m V l	t i:	k V l	tS @r	V	l I	z V m
mul-	ti-	cul-	tu-	ral
m V l	t i:	k V l	tS @r	V l
mul-	ti-	em-	plo-	yer
m V l	t i:	V m	p l OI	@r
mul-	ti-	eth-	nic
m V l	t i:	e T	n I k
mul-	ti-	fa-	ce-	ted
m V l	t i:	f {	s V	t V d
mul-	ti-	fa-	mi-	ly
m V l	t aI	f {	m I	l i:
mul-	ti-	la-	te-	ra-	li-	sm
m V l	t I	l {	t @r	V	l I	z V m
mul-	ti-	la-	te-	ral
m V l	t I	l {	t @r	V l
mul-	ti-	la-	te-	ral-	ly
m V l	t I	l {	t @r	V	l i:
mul-	ti-	la-	yer
m V l	t i:	l eI	@r
mul-	ti-	la-	yered
m V l	t i:	l eI	@r d
mul-	ti-	le-	vel
m V l	t aI	l e	v V l
mul-	ti-	lin-	gual
m V l	t i:	l I N	w V l
mul-	ti-	line
m V l	t i:	l aI n
mul-	ti-	me-	di-	a
m V l	t i:	m i:	d i:	V
mul-	ti-	mil-	lio-	naire
m V l	t i:	m I l	j V	n e@
mul-	ti-	mil-	lio-	naires
m V l	t i:	m I l	j V	n e@ z
mul-	ti-	mil-	lion
m V l	t aI	m I l	j V n
mul-	ti-	na-	tio-	nal
m V l	t aI	n {	S V	n V l
mul-	ti-	na-	tio-	nals
m V l	t aI	n {	S V	n V l z
mul-	ti-	par-	ty
m V l	t i:	p Q@	t i:
mul-	ti-	part
m V l	t i:	p Q@ t
mul-	ti-	pla-	yer
m V l	t i: p	l eI	@r
mul-	ti-	ple
m V l	t I	p V l
mul-	ti-	ple-	xer
m V l	t i: p	l e k	s @r
mul-	ti-	ple-	xers
m V l	t i: p	l e k	s @r z
mul-	ti-	ples
m V l	t I	p V l z
mul-	ti-	plex
m V l	t i: p	l e k s
mul-	ti-	pli-	ca-	tion
m V l	t I p	l I	k eI	S V n
mul-	ti-	pli-	ci-	ty
m V l	t I p	l I	s V	t i:
mul-	ti-	pli-	er
m V l	t I p	l aI	@r
mul-	ti-	plied
m V l	t I p	l aI d
mul-	ti-	plies
m V l	t I p	l aI z
mul-	ti-	ply
m V l	t I p	l aI
mul-	ti-	ply-	ing
m V l	t I p	l aI	I N
mul-	ti-	pro-	ces-	sor
m V l	t i: p	r Q	s e	s @r
mul-	ti-	pur-	pose
m V l	t i:	p @r	p V s
mul-	ti-	ra-	cial
m V l	t aI	r eI	S V l
mul-	ti-	state
m V l	t i: s	t eI t
mul-	ti-	tas-	king
m V l	t i:	t { s	k I N
mul-	ti-	task
m V l	t i:	t { s k
mul-	ti-	tude
m V l	t I	t u: d
mul-	ti-	tudes
m V l	t I t	j u: d z
mul-	ti-	u-	ser
m V l	t i:	j u:	z @r
mul-	ti-	valve
m V l	t i:	v { l v
mul-	ti-	year
m V l	t i:	j i: r
mul-	tis-	to-	ry
m V l	t i: s	t O@	i:
mul-	vi-	hill
m V l	v i:	h I l
mulch
m V l tS
mulched
m V l tS t
mule
m j u: l
mules
m j u: l z
mull
m V l
mulled
m V l d
mulls
m V l z
mum
m V m
mum-	b-	ling
m V m	b V	l I N
mum-	ble
m V m	b V l
mum-	bled
m V m	b V l d
mum-	bles
m V m	b V l z
mum-	bo
m V m	b @U
mum-	ford
m V m	f @r d
mum-	mi-	fi-	ca-	tion
m V	m I	f I	k eI	S V n
mum-	mi-	fied
m V	m I	f aI d
mum-	mi-	fy
m V	m I	f aI
mum-	mi-	fy-	ing
m V	m I	f aI	I N
mum-	mies
m V	m i: z
mum-	my
m V	m i:
mum-	my's
m V	m i: z
mum-	per
m V m	p @r
mumm
m V m
mumps
m V m p s
mums
m V m z
mun
m V n
mun-	cey
m V n	s i:
mun-	chau-	sen
m V n	tS aU	z V n
mun-	chies
m V n	tS i: z
mun-	ching
m V n	tS I N
mun-	cie
m V n	s i:
mun-	cy
m V n	s i:
mun-	dane
m V n	d eI n
mun-	day
m V n	d eI
mun-	den
m V n	d V n
mun-	di
m V n	d i:
mun-	dy
m V n	d i:
mun-	ford
m V n	f @r d
mun-	ford's
m V n	f @r d z
mun-	ger
m V	N @r
mun-	go
m V N	g @U
mun-	ro
m V n	r @U
mun-	roe
m V n	r @U
mun-	sell
m V n	s V l
mun-	sey
m V n	z i:
mun-	son
m V n	s V n
mun-	ster
m V n	s t @r
munch
m V n tS
munched
m V n tS t
mund
m V n d
mundt
m V n t
munn
m V n
muns
m V n z
munt
m V n t
muntz
m V n t s
mup-	pet
m V	p V t
mup-	pets
m V	p V t s
mur-	chi-	son
m @r	tS I	s V n
mur-	ki-	er
m @r	k i:	@r
mur-	ky
m @r	k i:
mur-	mansk
m @r	m { n s k
mur-	mu-	ring
m @r	m @r	I N
mur-	mur
m @r	m @r
mur-	mured
m @r	m @r d
mur-	murs
m @r	m @r z
mur-	phy
m @r	f i:
mur-	phys
m @r	f i: z
mur-	phy's
m @r	f i: z
mur-	rah
m @r	r Q
mur-	ray
m @r	i:
mur-	ray's
m @r	i: z
mur-	relet
m @r	l e t
mur-	rell
m O@	V l
mur-	ren
m @r	V n
mur-	rey
m @r	i:
mur-	rie-	ta
m U@	i:	t V
mur-	rin
m O@	I n
mur-	row
m V	r @U
mur-	ry
m @r	i:
mur-	tagh
m @r	t V g
mur-	taugh
m @r	t O:
mur-	tha
m @r	T V
mur-	ton
m @r	t V n
murk
m @r k
murr
m @r
mus-	ca-	tine
m V s	k V	t i: n
mus-	cat
m V s	k { t
mus-	co-	vite
m V s	k V	v aI t
mus-	co-	vites
m V s	k V	v aI t s
mus-	cu-	la-	ture
m V s	k j V	l V	tS @r
mus-	cu-	lar
m V s	k j V	l @r
mus-	grave
m V s	g r V v
mus-	grave's
m V s	g r V v z
mus-	ke-	gon
m V s	k i:	g V n
mus-	ke-	teer
m V s	k V	t i: r
mus-	ke-	teers
m V s	k V	t i: r z
mus-	ket
m V s	k V t
mus-	kie
m V s	k i:
mus-	kie's
m V s	k i: z
mus-	ko-	gee
m V s	k @U	g i:
mus-	ky
m V s	k i:
mus-	lim
m V z	l I m
mus-	lims
m V z	l I m z
mus-	lin
m V z	l I n
mus-	sel
m V	s V l
mus-	sels
m V	s V l z
mus-	ser
m V	s @r
mus-	so-	li-	ni
m u:	s @U	l i:	n i:
mus-	so-	li-	ni's
m u:	s @U	l i:	n i: z
mus-	ta-	ches
m V s	t {	S V z
mus-	ta-	chi-	o
m V s	t {	S i:	@U
mus-	ta-	chi-	oed
m V s	t {	S i:	@U d
mus-	ta-	fa
m u: s	t Q	f V
mus-	tache
m V s	t { S
mus-	tached
m V s	t { S t
mus-	tang
m V s	t { N
mus-	tangs
m V s	t { N z
mus-	tard
m V s	t @r d
mus-	tards
m V s	t @r d z
mus-	te-	ring
m V s	t @r	I N
mus-	ter
m V s	t @r
mus-	tered
m V s	t @r d
mus-	ters
m V s	t @r z
mus-	toe
m V s	t @U
mus-	t've
m V s	t I v
mus-	ty
m V s	t i:
muse
m j u: z
mused
m j u: z d
mush
m V S
mush-	roo-	ming
m V S	r U	m I N
mush-	room
m V S	r u: m
mush-	roomed
m V S	r U m d
mush-	rooms
m V S	r u: m z
musk
m V s k
musk-	me-	lon
m V s	k m e	l V n
musk-	rat
m V s	k r { t
musk-	rats
m V s	k r { t z
muss-	man
m V s	m V n
must
m V s t
mut-	te-	ring
m V	t @r	I N
mut-	te-	rings
m V	t @r	I N z
mut-	ter
m V	t @r
mut-	tered
m V	t @r d
mut-	ters
m V	t @r z
mut-	ton
m V	t V n
mutch
m V tS
mute
m j u: t
muth
m u: T
mutt
m V t
mutts
m V t s
mutz
m V t s
muz-	zle
m V	z V l
muz-	zled
m V	z V l d
muz-	zles
m V	z V l z
muz-	zy
m V	z i:
mwan-	za
m w Q n	z V
my
m aI
my-	ce-	nae-	an
m aI	s V	n i:	V n
my-	co-	lo-	gy
m aI	k Q	l V	dZ i:
my-	e-	lin
m aI	V	l I n
my-	er
m aI	@r
my-	ers
m aI	@r z
my-	lan
m aI	l V n
my-	lar
m aI	l Q@
my-	na
m aI	n V
my-	o-	car-	di-	al
m aI	V	k Q@	d i:	V l
my-	o-	car-	di-	um
m aI	V	k Q@	d i:	V m
my-	o-	pi-	a
m aI	@U	p i:	V
my-	o-	pic
m aI	Q	p I k
my-	o-	sin
m aI	V	s V n
my-	ra
m aI	r V
my-	ri-	ad
m I@	i:	V d
my-	ri-	am
m I@	i:	V m
my-	ril-	la
m I@	I	l V
my-	ron
m aI	r V n
my-	self
m aI	s e l f
my-	thi-	cal
m I	T I	k V l
my-	thic
m I	T I k
my-	tho-	lo-	gi-	cal
m I	T V	l Q	dZ I	k V l
my-	tho-	lo-	gy
m V	T Q	l V	dZ i:
myan-	mar
m j Q n	m Q@
myles
m aI l z
myr-	lene
m I@	l i: n
myr-	mi-	don
m @r	m I	d V n
myr-	mi-	dons
m @r	m I	d V n z
myr-	na
m @r	n V
myr-	ta
m @r	t V
myr-	tia
m @r	S V
myr-	tice
m I@	t I s
myr-	tle
m @r	t V l
myr-	tles
m @r	t V l z
myrrh
m @r
mys-	te-	ri-	ous
m I s	t I@	i:	V s
mys-	te-	ri-	ous-	ly
m I s	t I@	i:	V s	l i:
mys-	te-	ries
m I s	t @r	i: z
mys-	te-	ry
m I s	t @r	i:
mys-	ti-	cal
m I s	t I	k V l
mys-	ti-	ci-	sm
m I s	t I	s I	z V m
mys-	ti-	fied
m I s	t I	f aI d
mys-	ti-	fies
m I s	t I	f aI z
mys-	ti-	fy
m I s	t I	f aI
mys-	ti-	fy-	ing
m I s	t I	f aI	I N
mys-	tic
m I s	t I k
mys-	tics
m I s	t I k s
mys-	tique
m I s	t i: k
myth
m I T
n
e n
n-	i-	c
e	n aI	s i:
n-	p-	r
e n	p i:	Q@
n.
e n
na
n Q
na-	bis-	co
n V	b I s	k @U
na-	bis-	co's
n V	b I s	k @U z
na-	bo-	kov
n {	b V	k Q v
na-	bo-	kov's
n {	b V	k Q v z
na-	bob
n {	b Q b
na-	bobs
n {	b Q b z
na-	cho
n {	tS @U
na-	chos
n Q	tS @U z
na-	d-	ler
n eI	d V	l @r
na-	da
n Q	d V
na-	deau
n V	d @U
na-	der
n eI	d @r
na-	der's
n eI	d @r z
na-	dia
n { d	j V
na-	dine
n V	d i: n
na-	dir
n eI	d @r
na-	ga-	no
n Q	g Q	n @U
na-	ga-	sa-	ki
n Q	g Q	s Q	k i:
na-	gel
n eI	g V l
na-	gi
n Q	g i:
na-	gle
n eI	g V l
na-	go-	ya
n V	g OI	V
na-	gy
n eI	g i:
na-	hum
n {	h V m
na-	i-	ve-	te
n Q	i:	v V	t eI
na-	ish
n Q	I S
na-	ive
n aI	i: v
na-	ive-	ly
n Q	i: v	l i:
na-	ka-	mu-	ra
n Q	k Q	m U@	V
na-	ka-	shi-	ma
n Q	k Q	S i:	m V
na-	ka-	ya-	ma
n Q	k Q	j Q	m V
na-	ked
n eI	k V d
na-	ma-	ra
n V	m Q@	V
na-	mer
n eI	m @r
na-	mi-	bi-	a
n V	m I	b i:	V
na-	mi-	bi-	an
n V	m I	b i:	V n
na-	mi-	bi-	a's
n V	m I	b i:	V z
na-	ming
n eI	m I N
na-	na
n {	n V
na-	nette
n V	n e t
na-	no-	gram
n {	n @U g	r { m
na-	no-	grams
n {	n @U g	r { m z
na-	no-	se-	cond
n {	n @U	s e	k V n d
na-	no-	se-	conds
n {	n @U	s e	k V n d z
na-	o-	ma
n Q	@U	m V
na-	o-	mi
n eI	@U	m i:
na-	pa
n {	p V
na-	palm
n eI	p Q m
na-	pe-	a
n Q	p i:	V
na-	per-	ville
n eI	p @r	v I l
na-	pi-	er
n eI	p i:	@r
na-	ples
n eI	p V l z
na-	po-	le-	o-	nic
n V	p @U	l i:	Q	n I k
na-	po-	le-	on
n V	p @U	l i:	V n
na-	po-	le-	on's
n V	p @U	l i:	V n z
na-	po-	li
n {	p V	l i:
na-	quin
n { k	w I n
na-	ra
n Q@	V
na-	ra-	yan
n Q@	Q	j Q n
na-	ry
n e@	i:
na-	sa
n {	s V
na-	sal
n eI	z V l
na-	sal-	ly
n eI	z V	l i:
na-	sh's
n {	S V z
na-	shu-	a
n {	S u:	V
na-	shu-	a's
n {	S u:	V z
na-	so
n Q	s @U
na-	so-	pha-	rynx
n V	s Q	f @r	I N k s
na-	son
n {	s V n
na-	ta
n Q	t V
na-	ta-	la
n Q	t Q	l V
na-	ta-	le
n Q	t Q	l i:
na-	ta-	lia
n V	t Q l	j V
na-	ta-	lie
n {	t V	l i:
na-	ta-	sha
n V	t Q	S V
na-	ta-	sha's
n V	t Q	S V z
na-	tal
n eI	t V l
na-	tha-	li-	a
n V	T {	l i:	V
na-	tha-	lie
n {	t V	l i:
na-	tha-	nael
n {	T V	n eI l
na-	tha-	niel
n V	T { n	j V l
na-	than
n eI	T V n
na-	than-	son
n {	T V n	s V n
na-	than's
n eI	T V n z
na-	ti-	vi-	dad
n V	t I	v I	d Q d
na-	ti-	vi-	sm
n eI	t I	v I	z V m
na-	ti-	vi-	ty
n V	t I	v I	t i:
na-	ti-	vist
n eI	t I	v I s t
na-	tick
n eI	t I k
na-	tio-	na-	li-	sm
n {	S V	n V	l I	z V m
na-	tio-	na-	li-	ties
n {	S V	n {	l I	t i: z
na-	tio-	na-	li-	ty
n {	S V	n {	l I	t i:
na-	tio-	na-	li-	za-	tion
n {	S V	n V	l I	z eI	S V n
na-	tio-	na-	li-	za-	tions
n {	S V	n V	l I	z eI	S V n z
na-	tio-	na-	li-	zing
n {	S V	n V	l aI	z I N
na-	tio-	na-	lis-	tic
n {	S V	n V	l I s	t I k
na-	tio-	na-	list
n {	S V	n V	l I s t
na-	tio-	na-	lists
n {	S V	n V	l I s t s
na-	tio-	na-	lize
n {	S V	n V	l aI z
na-	tio-	na-	lized
n {	S V	n V	l aI z d
na-	tio-	nal
n {	S V	n V l
na-	tio-	nal-	ly
n {	S V	n V	l i:
na-	tio-	nals
n {	S V	n V l z
na-	tio-	nal's
n {	S V	n V l z
na-	tion
n eI	S V n
na-	tion-	hood
n eI	S V n	h U d
na-	tion-	wide
n eI	S V n	w aI d
na-	tion-	wide's
n eI	S V n	w aI d z
na-	tions
n eI	S V n z
na-	tion's
n eI	S V n z
na-	tive
n eI	t I v
na-	tives
n eI	t I v z
na-	to
n eI	t @U
na-	to's
n eI	t @U z
na-	tu-	ra-	li-	sm
n {	tS @r	V	l I	z V m
na-	tu-	ra-	li-	za-	tion
n {	tS @r	V	l V	z eI	S V n
na-	tu-	ra-	lis-	tic
n {	tS @r	V	l I s	t I k
na-	tu-	ra-	list
n {	tS @r	V	l V s t
na-	tu-	ra-	lists
n {	tS @r	V	l V s t s
na-	tu-	ra-	lize
n {	tS @r	V	l aI z
na-	tu-	ra-	lized
n {	tS @r	V	l aI z d
na-	tu-	ral
n {	tS @r	V l
na-	tu-	ral-	ly
n {	tS @r	V	l i:
na-	tu-	ral's
n {	tS @r	V l z
na-	ture
n eI	tS @r
na-	tured
n eI	tS @r d
na-	tured-	ly
n eI	tS @r d	l i:
na-	tures
n eI	tS @r z
na-	ture's
n eI	tS @r z
na-	vi-	ga-	ted
n {	v I	g eI	t V d
na-	vi-	ga-	ting
n {	v I	g eI	t I N
na-	vi-	ga-	tio-	nal
n {	v I	g eI	S V	n V l
na-	vi-	ga-	tion
n {	v I	g eI	S V n
na-	vi-	ga-	tor
n {	v I	g eI	t @r
na-	vi-	ga-	tors
n {	v I	g eI	t @r z
na-	vi-	gate
n {	v I	g eI t
na-	vis
n Q	v I s
na-	vy
n eI	v i:
na-	vy's
n eI	v i: z
na-	za-	reth
n {	z V	r V T
na-	za-	ri-	o
n Q	z Q@	i:	@U
na-	zar
n Q	z Q@
na-	zi
n Q t	s i:
na-	zi-	sm
n Q	z I	z V m
na-	zis
n Q t	s i: z
na-	zi's
n Q t	s i: z
naas
n Q z
nab
n { b
nab-	bing
n {	b I N
nab-	lus
n { b	l V s
nabb
n { b
nabbed
n { b d
nace
n eI s
nad
n { d
nad-	ja
n { d	j V
naeve
n i: v
naf-	ta
n { f	t V
naff
n { f
nag
n { g
nag-	ging
n {	g I N
nagged
n { g d
nags
n { g z
nah
n Q
nai-	ling
n eI	l I N
nai-	ra
n e@	V
nai-	ro-	bi
n aI	r @U	b i:
naik
n eI k
nail
n eI l
nailed
n eI l d
nails
n eI l z
nair
n e@
nairn
n e@ n
nais-	mith
n eI z	m I T
nal-	do
n Q l	d @U
nal-	ly
n {	l i:
nale
n eI l
nam
n { m
name
n eI m
name-	less
n eI m	l V s
name-	ly
n eI m	l i:
name-	plate
n eI m	p l eI t
name-	plates
n eI m	p l eI t s
name-	sake
n eI m	s eI k
named
n eI m d
names
n eI m z
name's
n eI m z
nan
n { n
nan-	chang
n { n	tS { N
nan-	cy
n { n	s i:
nan-	cy's
n { n	s i: z
nan-	di
n Q n	d i:
nan-	jing
n { n	dZ I N
nan-	king
n { N	k I N
nan-	na
n {	n V
nan-	ni
n {	n i:
nan-	nies
n {	n i: z
nan-	ny
n {	n i:
nan-	tuc-	ket
n { n	t V	k V t
nan-	tuc-	ket's
n { n	t V	k V t s
nance
n { n s
nang
n { N
nan's
n { n z
nantes
n { n t s
nantz
n { n t s
nap
n { p
nap-	kin
n { p	k I n
nap-	kins
n { p	k I n z
nap-	pa
n {	p V
nap-	per
n {	p @r
nap-	pi-	er
n {	p i:	@r
nap-	ping
n {	p I N
nap-	ro-	syn
n { p	r V	s I n
naph-	tha
n { f	T V
naph-	tha-	lene
n { f	T V	l i: n
napped
n { p t
naps
n { p s
nar-	cis-	si-	sm
n Q@	s V	s I	z V m
nar-	cis-	sis-	tic
n Q@	s I	s I s	t I k
nar-	cis-	sus
n Q@	s I	s V s
nar-	co
n Q@	k @U
nar-	co-	lep-	sy
n Q@	k V	l e p	s i:
nar-	co-	tic
n Q@	k Q	t I k
nar-	co-	tics
n Q@	k Q	t I k s
nar-	cos
n Q@	k @U s
nar-	da
n Q@	d V
nar-	do
n Q@	d @U
nar-	ra-	gan-	sett
n e@	V	g { n	s V t
nar-	ra-	ted
n e@	eI	t V d
nar-	ra-	tion
n e@	eI	S V n
nar-	ra-	tive
n e@	V	t I v
nar-	ra-	tives
n e@	V	t I v z
nar-	ra-	tor
n e@	eI	t @r
nar-	ra-	tors
n e@	eI	t @r z
nar-	rate
n e@	eI t
nar-	rates
n e@	eI t s
nar-	ro-	wer
n e@	@U	@r
nar-	ro-	west
n e@	@U	V s t
nar-	ro-	wing
n e@	@U	I N
nar-	row
n e@	@U
nar-	row-	ly
n e@	@U	l i:
nar-	row-	ness
n e@	@U	n V s
nar-	rowed
n e@	@U d
nar-	rows
n e@	@U z
nar-	va-	ez
n Q@	v Q	e z
narc
n Q@ k
nard
n Q@ d
nares
n { r z
nas-	by
n { s	b i:
nas-	ca
n Q s	k V
nas-	car
n { s	k Q@
nas-	cent
n eI	s V n t
nas-	daq
n { z	d { k
nas-	sau
n {	s O:
nas-	ser
n {	s @r
nas-	ti-	er
n { s	t i:	@r
nas-	ti-	est
n { s	t i:	V s t
nas-	ti-	ness
n { s	t i:	n V s
nas-	ty
n { s	t i:
nash
n { S
nash-	ville
n { S	v I l
nash-	ville's
n { S	v I l z
nass
n { s
nast
n { s t
nast's
n { s t s
nat
n { t
nat-	chez
n {	tS e z
nat-	te-	ring
n {	t @r	I N
nat-	ter
n {	t @r
nat-	ti-	ly
n {	t I	l i:
nat-	tie
n {	t i:
nat-	ty
n {	t i:
nate
n eI t
nath
n { T
nathe
n eI D
nats
n { t s
nau
n @U
nau-	ga-	tuck
n O:	g V	t V k
nau-	mann
n aU	m V n
nau-	se-	a
n O:	z i:	V
nau-	se-	a-	ted
n O:	z i:	eI	t V d
nau-	se-	a-	ting
n O:	Z i:	eI	t I N
nau-	se-	ate
n O:	z i:	eI t
nau-	seam
n aU	z i: m
nau-	seous
n O:	S V s
nau-	ti-	cal
n O:	t I	k V l
naugh-	ty
n O:	t i:
naught
n O: t
nav-	ra-	ti-	lo-	va
n { v	r {	t I	l @U	v V
nav-	ra-	ti-	lo-	va's
n { v	r {	t I	l @U	v V z
naw
n Q
naw-	roc-	ki
n Q v	r @U t	s k i:
nay
n eI
nay-	lor
n eI	l @r
nay-	sa-	yer
n eI	s eI	@r
nay-	sa-	yers
n eI	s eI	@r z
nays
n eI z
n'dja-	me-	na
n d j V	m i:	n V
ne
n i:
ne-	a-	po-	li-	tan
n i:	V	p Q	l V	t V n
ne-	an-	der-	thal
n i:	{ n	d @r	T O: l
ne-	an-	der-	thals
n i:	{ n	d @r	T O: l z
ne-	bel
n e	b V l
ne-	bu-	la
n e b	j V	l V
ne-	bu-	lous
n e b	j V	l V s
ne-	ces-	sa-	ri-	ly
n e	s V	s e@	V	l i:
ne-	ces-	sa-	ry
n e	s V	s e@	i:
ne-	ces-	si-	ta-	ted
n V	s e	s V	t eI	t V d
ne-	ces-	si-	ta-	ting
n V	s e	s V	t eI	t I N
ne-	ces-	si-	tate
n V	s e	s V	t eI t
ne-	ces-	si-	tates
n V	s e	s V	t eI t s
ne-	ces-	si-	ties
n V	s e	s V	t i: z
ne-	ces-	si-	ty
n V	s e	s V	t i:
ne-	da
n eI	d V
ne-	der-	land
n e	d @r	l V n d
ne-	fa-	ri-	ous
n V	f e@	i:	V s
ne-	ga-	ra
n e	g Q@	V
ne-	ga-	ted
n V	g eI	t V d
ne-	ga-	ti-	vi-	sm
n e	g V	t I	v I	z V m
ne-	ga-	ti-	vi-	ty
n e	g V	t I	v V	t i:
ne-	ga-	ting
n V	g eI	t I N
ne-	ga-	tion
n V	g eI	S V n
ne-	ga-	tive
n e	g V	t I v
ne-	ga-	tive-	ly
n e	g V	t I v	l i:
ne-	ga-	tives
n e	g V	t I v z
ne-	ga-	tron
n e	g V t	r Q n
ne-	ga-	trons
n e	g V t	r Q n z
ne-	gate
n I	g eI t
ne-	gates
n V	g eI t s
ne-	gev
n e	g e v
ne-	go-	ti-	a-	ted
n V	g @U	S i:	eI	t V d
ne-	go-	ti-	a-	ting
n V	g @U	S i:	eI	t I N
ne-	go-	ti-	a-	tion
n V	g @U	S i:	eI	S V n
ne-	go-	ti-	a-	tions
n V	g @U	S i:	eI	S V n z
ne-	go-	ti-	a-	tor
n V	g @U	S i:	eI	t @r
ne-	go-	ti-	a-	tors
n V	g @U	S i:	eI	t @r z
ne-	go-	ti-	a-	tor's
n V	g @U	S i:	eI	t @r z
ne-	go-	ti-	ate
n V	g @U	S i:	eI t
ne-	go-	ti-	ates
n I	g @U	S i:	eI t s
ne-	go-	tia-	ble
n V	g @U	S V	b V l
ne-	gus
n i:	g V s
ne-	he-	mi-	ah
n i:	V	m aI	V
ne-	koo-	sa
n I	k u:	s V
ne-	la
n e	l V
ne-	li-	a
n e	l i:	V
ne-	ma-	tode
n e	m V	t @U d
ne-	ma-	todes
n e	m V	t @U d z
ne-	me-	an
n i:	m i:	V n
ne-	me-	sis
n e	m V	s V s
ne-	mo
n e	m @U
ne-	mos
n i:	m @U z
ne-	mours
n V	m O@ z
ne-	o
n i:	@U
)"
R"(ne-	o-	clas-	si-	cal
n i:	@U k	l {	s I	k V l
ne-	o-	clas-	sic
n i:	@U k	l {	s I k
ne-	o-	con-	ser-	va-	tive
n i:	@U	k V n	s @r	v V	t I v
ne-	o-	con-	ser-	va-	tives
n i:	@U	k V n	s @r	v V	t I v z
ne-	o-	la
n i:	Q	l V
ne-	o-	li-	be-	ral
n i:	@U	l I	b @r	V l
ne-	o-	li-	be-	rals
n i:	@U	l I	b @r	V l z
ne-	o-	ma
n eI	@U	m V
ne-	o-	na-	tal
n i:	@U	n eI	t V l
ne-	o-	phyte
n i:	V	f aI t
ne-	o-	phytes
n i:	V	f aI t s
ne-	o-	pla-	sm
n i:	V p	l {	z V m
ne-	o-	pla-	to-	nic
n i:	@U p	l V	t Q	n I k
ne-	o-	pla-	to-	nist
n i:	@U p	l eI	t V	n V s t
ne-	o-	prene
n i:	V p	r i: n
ne-	o-	te-	nic
n i:	V	t i:	n I k
ne-	o-	te-	ny
n i:	Q	t V	n i:
ne-	on
n i:	Q n
ne-	ons
n i:	Q n z
ne-	pa
n i:	p V
ne-	pa-	lese
n e	p V	l i: z
ne-	pa-	li
n V	p O:	l i:
ne-	pal
n V	p O: l
ne-	phew
n e f	j u:
ne-	phews
n e f	j u: z
ne-	phew's
n e f	j u: z
ne-	po-	ti-	sm
n e	p V	t I	z V m
ne-	pon-	set
n V	p Q n	s V t
ne-	ri
n e@	i:
ne-	ri-	tic
n @r	I	t I k
ne-	rine
n e@	i: n
ne-	ro
n I@	@U
ne-	ro's
n I@	@U z
ne-	ru-	da
n V	r u:	d V
ne-	st-	ler
n e	s V	l @r
ne-	stle
n e	s V l
ne-	stled
n e	s V l d
ne-	stles
n e	s V l z
ne-	stle's
n e	s V l z
ne-	ther
n e	D @r
ne-	ther-	lan-	dic
n e	D @r	l { n	d I k
ne-	ther-	land
n e	D @r	l V n d
ne-	ther-	lands
n e	D @r	l V n d z
ne-	ther-	world
n e	D @r	w @r l d
ne-	to
n e	t @U
ne-	va
n eI	v V
ne-	va-	da
n V	v Q	d V
ne-	va-	dan
n V	v {	d V n
ne-	va-	dans
n V	v {	d V n z
ne-	va-	da's
n V	v {	d V z
ne-	vel
n eI	v e l
ne-	vels
n e	v V l z
ne-	ver
n e	v @r
ne-	ver-	land
n e	v @r	l { n d
ne-	ver-	mind
n e	v @r	m aI n d
ne-	ver-	more
n e	v @r	m O@
ne-	ver-	the-	less
n e	v @r	D V	l e s
ne-	vers
n e	v @r z
ne-	vil
n eI	v i: l
ne-	vile
n eI	v aI l
ne-	ville
n e	v I l
ne-	vin
n e	v I n
ne-	vins
n e	v I n z
ne-	vin's
n e	v I n z
ne-	vis
n e	v I s
ne-	wark
n u:	@r k
ne-	wark's
n j u:	@r k s
ne-	well
n u:	V l
ne-	well's
n u:	V l z
ne-	wer
n u:	@r
ne-	west
n u:	V s t
ne-	wish
n u:	I S
ne-	xis
n e k	s I s
ne-	xus
n e k	s V s
nea-	gle
n i:	g V l
nea-	la
n i:	l V
nea-	ley
n i:	l i:
nea-	lon
n i:	l V n
nea-	ly
n i:	l i:
nea-	rer
n I@	@r
nea-	rest
n I@	V s t
nea-	ring
n I@	I N
nea-	ter
n i:	t @r
nea-	test
n i:	t V s t
neal
n i: l
neal-	son
n i: l	s V n
neale
n i: l
neall
n i: l
neal's
n i: l z
near
n I@
near-	by
n I@	b aI
near-	ly
n I@	l i:
near-	sigh-	ted
n i: r	s aI	t V d
near-	sigh-	ted-	ness
n i: r	s aI	t V d	n V s
neared
n I@ d
nears
n I@ z
neat
n i: t
neat-	ly
n i: t	l i:
neat-	ness
n i: t	n V s
neb-	lett
n e b	l I t
neb-	ras-	ka
n V b	r { s	k V
neb-	ras-	kan
n V b	r { s	k V n
neb-	ras-	kans
n V b	r { s	k V n z
neb-	ras-	ka's
n V b	r { s	k V z
nec
n e k
nec-	ker
n e	k @r
nec-	ro-	man-	cy
n e k	r V	m { n	s i:
nec-	ro-	po-	lis
n V k	r Q	p V	l V s
nec-	ro-	sis
n V k	r @U	s V s
nec-	tar
n e k	t @r
neck
n e k
neck-	la-	ces
n e k	l V	s V z
neck-	la-	cing
n e k	l V	s I N
neck-	lace
n e k	l V s
neck-	tie
n e k	t aI
neck-	ties
n e k	t aI z
neck-	wear
n e k	w e@
necked
n e k t
necks
n e k s
ned
n e d
ned-	da
n e	d V
ned-	row
n e d	r @U
ned's
n e d z
nee
n i:
nee-	d-	ler
n i:	d V	l @r
nee-	ded
n i:	d V d
nee-	di-	est
n i:	d i:	V s t
nee-	ding
n i:	d I N
nee-	dle
n i:	d V l
nee-	dle-	fish
n i:	d V l	f I S
nee-	dle-	like
n i:	d V l	l aI k
nee-	dle-	man
n i:	d V l	m V n
nee-	dle-	point
n i:	d V l	p OI n t
nee-	dle-	work
n i:	d V l	w @r k
nee-	dled
n i:	d V l d
nee-	dles
n i:	d V l z
nee-	dn't
n i:	d V n t
nee-	dy
n i:	d i:
nee-	ly
n i:	l i:
need
n i: d
need-	ful
n i: d	f V l
need-	ham
n i:	d V m
need-	ham's
n i:	d V m z
need-	less
n i: d	l V s
need-	less-	ly
n i: d	l V s	l i:
need-	ling
n i: d	l I N
needs
n i: d z
neel
n i: l
neeld
n i: l d
neer
n I@
ne'er
n e@
neese
n i: z
neet
n i: t
neff
n e f
neg
n e g
neg-	lec-	ted
n V g	l e k	t V d
neg-	lec-	ting
n I g	l e k	t I N
neg-	lect
n V g	l e k t
neg-	lect-	ful
n I g	l e k	t f V l
neg-	lects
n I g	l e k t s
neg-	ley
n e g	l i:
neg-	li-	gence
n e g	l I	dZ e n s
neg-	li-	gent
n e g	l I	dZ e n t
neg-	li-	gent-	ly
n e g	l I	dZ e n	t l i:
neg-	li-	gi-	ble
n e g	l I	dZ I	b V l
neg-	ri
n e g	r i:
neg-	ro
n i: g	r @U
neg-	ro-	ni
n e g	r @U	n i:
neg-	roes
n i: g	r @U z
neg-	roid
n i: g	r OI d
neg-	ros
n i: g	r @U z
negs
n e g z
neh-	ru
n eI	r u:
nei-	man
n i:	m V n
nei-	ther
n i:	D @r
neid-	hardt
n aI d	h Q@ t
neigh-	bo-	ring
n eI	b @r	I N
neigh-	bor
n eI	b @r
neigh-	bor-	hood
n eI	b @r	h U d
neigh-	bor-	hoods
n eI	b @r	h U d z
neigh-	bor-	hood's
n eI	b @r	h U d z
neigh-	bor-	ly
n eI	b @r	l i:
neigh-	bors
n eI	b @r z
neigh-	bor's
n eI	b @r z
neil
n i: l
neil-	son
n i: l	s V n
neile
n i: l
neill
n i: l
neils
n i: l z
neil's
n i: l z
nein
n i: n
nek-	ton
n e k	t V n
nel
n e l
nel-	da
n e l	d V
nel-	la
n e	l V
nel-	li
n e	l i:
nel-	lie
n e	l i:
nel-	lis
n e	l I s
nel-	ly
n e	l i:
nel-	sen
n e l	s V n
nel-	son
n e l	s V n
nel-	son's
n e l	s V n z
nell
n e l
nelle
n e l
nels
n e l z
nene
n i: n
nep-	tu-	ni-	um
n e p	t u:	n i:	V m
nep-	tune
n e p	t u: n
neph-	ro-	sis
n V f	r @U	s V s
neph-	ron
n e f	r Q n
ner-	dy
n @r	d i:
ner-	vo-	sa
n @r	v @U	s V
ner-	vous
n @r	v V s
ner-	vous-	ly
n @r	v V s	l i:
ner-	vous-	ness
n @r	v V s	n V s
ner-	vy
n @r	v i:
nerd
n @r d
nerds
n @r d z
nerve
n @r v
nerves
n @r v z
nes
n e s
nes-	bit
n e s	b I t
nes-	bitt
n e z	b I t
nes-	mith
n e z	m I T
nes-	sa
n e	s V
nes-	si
n e	s i:
nes-	sie
n e	s i:
nes-	ta
n e s	t V
nes-	ted
n e s	t V d
nes-	ter
n e s	t @r
nes-	ters
n e s	t @r z
nes-	ting
n e s	t I N
nes-	to-	ri-	a-	ni-	sm
n e s	t O@	i:	V	n I	z V m
nes-	to-	ri-	an
n e s	t O@	i:	V n
nes-	tor
n e s	t @r
ness
n e s
nest
n e s t
nest-	ling
n e s	t l I N
nest-	lings
n e s	t l I N z
nests
n e s t s
net
n e t
net-	back
n e t	b { k
net-	like
n e t	l aI k
net-	scape
n e t	s k eI p
net-	scape's
n e t	s k eI p s
net-	ta
n e	t V
net-	ted
n e	t V d
net-	ter
n e	t @r
net-	tie
n e	t i:
net-	ting
n e	t I N
net-	tle
n e	t V l
net-	tle-	some
n e	t V l	s V m
net-	tle-	ton
n e	t V l	t V n
net-	tle-	ton's
n e	t V l	t V n z
net-	tled
n e	t V l d
net-	tles
n e	t V l z
net-	ty
n e	t i:
net-	wor-	king
n e t	w @r	k I N
net-	work
n e t	w @r k
net-	worked
n e t	w @r k t
net-	works
n e t	w @r k s
net-	work's
n e t	w @r k s
neth
n e T
nets
n e t s
nett
n e t
neu
n OI
neu-	ber-	ger
n u:	b @r	g @r
neu-	bur-	ger
n u:	b @r	g @r
neu-	kam
n u:	k V m
neu-	ma-	yer
n u:	m eI	@r
neu-	mann
n u:	m V n
neu-	me-	yer
n u:	m aI	@r
neu-	ral
n U@	V l
neu-	ras-	the-	ni-	a
n U@	{ s	T i:	n i:	V
neu-	ro
n U@	@U
neu-	ro-	fib-	ro-	ma-	to-	sis
n U@	@U	f aI b	r @U	m V	t @U	s V s
neu-	ro-	lo-	gi-	cal
n U@	V	l Q	dZ I	k V l
neu-	ro-	lo-	gic
n U@	V	l Q	dZ I k
neu-	ro-	lo-	gist
n U@	Q	l V	dZ V s t
neu-	ro-	lo-	gists
n U@	Q	l V	dZ V s t s
neu-	ro-	lo-	gy
n U@	Q	l V	dZ i:
neu-	ro-	pa-	thy
n U@	@U	p {	T i:
neu-	ro-	sci-	en-	tist
n j U@	@U	s aI	V n	t V s t
neu-	ro-	sci-	ence
n j U@	@U	s aI	V n s
neu-	ro-	ses
n U@	@U	s i: z
neu-	ro-	sis
n U@	@U	s I s
neu-	ro-	sur-	ge-	ry
n U@	@U	s @r	dZ @r	i:
neu-	ro-	sur-	geon
n U@	@U	s @r	dZ V n
neu-	ro-	sur-	geons
n U@	@U	s @r	dZ V n z
neu-	ro-	tic
n U@	Q	t I k
neu-	rons
n U@	Q n z
neu-	te-	ring
n u:	t @r	I N
neu-	ter
n u:	t @r
neu-	tered
n u:	t @r d
neus-	tadt
n u: S	t { t
neut-	ra-	li-	sm
n u: t	r V	l I	z V m
neut-	ra-	li-	ty
n u: t	r {	l I	t i:
neut-	ra-	li-	za-	tion
n u: t	r V	l I	z eI	S V n
neut-	ra-	li-	zes
n u: t	r V	l aI	z V z
neut-	ra-	li-	zing
n u: t	r V	l aI	z I N
neut-	ra-	list
n u: t	r V	l V s t
neut-	ra-	lize
n u: t	r V	l aI z
neut-	ra-	lized
n u: t	r V	l aI z d
neut-	ral
n u: t	r V l
neut-	rals
n u: t	r V l z
neut-	ri-	no
n u: t	r i:	n @U
neut-	ri-	nos
n u: t	r i:	n @U z
neut-	ron
n u: t	r Q n
neut-	rons
n u: t	r Q n z
neve
n i: v
neves
n i: v z
new
n u:
new-	be-	ry
n u:	b e@	i:
new-	ber-	ry
n u:	b e@	i:
new-	berg
n u:	b @r g
new-	bill
n u:	b I l
new-	bold
n u:	b @U l d
new-	born
n u:	b O@ n
new-	borns
n u:	b O@ n z
new-	bu-	ry
n u:	b e@	i:
new-	bu-	ry's
n u:	b e@	i: z
new-	burg
n u:	b @r g
new-	burgh
n u:	b @r g
new-	by
n u:	b i:
new-	ca-	stle
n u:	k {	s V l
new-	ca-	stle's
n u:	k {	s V l z
new-	co-	mer
n u:	k V	m @r
new-	co-	mers
n u:	k V	m @r z
new-	comb
n u:	k V m
new-	combe
n u:	k V m
new-	come
n u:	k V m
new-	fan-	gle
n u:	f { N	g V l
new-	fan-	gled
n u:	f { N	g V l d
new-	found
n u:	f aU n d
new-	found-	land
n u:	f V n	d l V n d
new-	gate
n u:	g eI t
new-	hall
n u:	h O: l
new-	hall's
n u:	h O: l z
new-	house
n u:	h aU s
new-	kirk
n u:	k @r k
new-	land
n u:	l V n d
new-	lin
n u:	l I n
new-	lon
n u:	l V n
new-	ly
n u:	l i:
new-	ly-	wed
n u:	l i:	w e d
new-	ly-	weds
n u:	l i:	w e d z
new-	man
n u:	m V n
new-	mann
n u:	m V n
new-	man's
n u:	m V n z
new-	mar-	ket
n u:	m Q@	k V t
new-	mark
n u:	m Q@ k
new-	ness
n u:	n V s
new-	port
n u:	p O@ t
new-	port's
n u:	p O@ t s
new-	sies
n u:	z i: z
new-	som
n u:	z V m
new-	s's
n u:	z V z
new-	sy
n u:	z i:
new-	to-	ni-	an
n u:	t @U	n i:	V n
new-	ton
n u:	t V n
new-	ton's
n u:	t V n z
new-	town
n u:	t aU n
new-	zea-	land
n u:	z i:	l V n d
news
n u: z
news-	cas-	ter
n u: z	k { s	t @r
news-	cas-	ters
n u: z	k { s	t @r z
news-	cast
n u: z	k { s t
news-	casts
n u: z	k { s t s
news-	group
n u: z	g r u: p
news-	groups
n u: z	g r u: p s
news-	let-	ter
n u: z	l e	t @r
news-	let-	ters
n u: z	l e	t @r z
news-	let-	ter's
n u: z	l e	t @r z
news-	ma-	ga-	zine
n u: z	m {	g V	z i: n
news-	ma-	ker
n u: z	m eI	k @r
news-	ma-	kers
n u: z	m eI	k @r z
news-	man
n u: z	m { n
news-	men
n u: z	m e n
news-	pa-	per
n u: z	p eI	p @r
news-	pa-	per-	man
n u: z	p eI	p @r	m { n
news-	pa-	per-	men
n u: z	p {	p @r	m e n
news-	pa-	pers
n u: z	p eI	p @r z
news-	pa-	per's
n u: z	p eI	p @r z
news-	peak
n u: s	p i: k
news-	peo-	ple
n u: z	p i:	p V l
news-	per-	son
n u: z	p @r	s V n
news-	per-	sons
n u: z	p @r	s V n z
news-	print
n u: z	p r I n t
news-	reel
n u: z	r i: l
news-	reels
n u: z	r i: l z
news-	room
n u: z	r u: m
news-	rooms
n u: z	r u: m z
news-	stand
n u: z	s t { n d
news-	stands
n u: z	s t { n d z
news-	week
n u: z	w i: k
news-	week-	ly
n u: z	w i: k	l i:
news-	week's
n u: z	w i: k s
news-	wire
n u: z	w aI r
news-	wires
n u: z	w aI r z
news-	wo-	man
n u: z	w U	m V n
news-	wo-	men
n u: z	w I	m V n
news-	wor-	thy
n u: z	w @r	D i:
newt
n u: t
newts
n u: t s
newt's
n u: t s
nex-	rad
n e k	s r { d
next
n e k s t
ney
n eI
ney-	sa
n eI	s V
nez
n e z
ng
e N
ngai
gh aI
ngo
gh @U
ngo's
gh @U z
ngu-	yen
n u:	j e n
ni-	a-	cin
n aI	V	s I n
ni-	aga-	ra
n aI	{ g	r V
ni-	aga-	ra's
n aI	{ g	r V z
ni-	al
n aI	V l
ni-	ca-	ra-	gua
n I	k @r	Q g	w V
ni-	ca-	ra-	guan
n I	k @r	Q g	w V n
ni-	ca-	ra-	guans
n I	k @r	Q g	w V n z
ni-	ca-	ra-	gua's
n I	k @r	Q g	w V z
ni-	ce-	ties
n aI	s V	t i: z
ni-	cer
n aI	s @r
ni-	cest
n aI	s I s t
ni-	ches
n I	tS V z
ni-	cho-	la
n I	h @U	l V
ni-	cho-	las
n I	k V	l V s
ni-	chol
n I	k O: l
ni-	chol-	son
n I	k V l	s V n
ni-	chol-	son's
n I	k V l	s V n z
ni-	choll
n I	k V l
ni-	cholls
n I	k V l z
ni-	chols
n I	k V l z
ni-	co
n i:	k @U
ni-	co-	la
n I	k @U	l V
ni-	co-	la-	i
n i:	k @U	l Q	i:
ni-	co-	las
n I	k V	l V s
ni-	co-	lau
n I	k V	l aU
ni-	co-	laus
n I	k V	l aU z
ni-	co-	lay
n I	k V	l eI
ni-	co-	let
n I	k V	l e t
ni-	co-	lette
n I	k V	l e t
ni-	co-	li
n i:	k @U	l i:
ni-	co-	li-	na
n i:	k @U	l i:	n V
ni-	co-	li-	ne
n i:	k @U	l i:	n i:
ni-	co-	lo
n I	k V	l @U
ni-	co-	si-	a
n I	k V	s i:	V
ni-	co-	tine
n I	k V	t i: n
ni-	co-	tine's
n I	k V	t i: n z
ni-	col
n I	k V l
ni-	col-	son
n I	k @U l	s V n
ni-	cole
n I	k @U l
ni-	cole's
n I	k @U l z
ni-	colle
n I	k @U l
ni-	cols
n I	k V l z
ni-	da
n i:	d V
ni-	dal
n V	d Q l
ni-	e-	ves
n i:	e	v e s
ni-	er
n i:	@r
ni-	fe-	di-	pine
n aI	f e	d I	p i: n
ni-	ge-	ri-	a
n aI	dZ I@	i:	V
ni-	ge-	ri-	an
n aI	dZ I@	i:	V n
ni-	ge-	ri-	ans
n aI	dZ I@	i:	V n z
ni-	ge-	ri-	a's
n aI	dZ I@	i:	V z
ni-	gel
n aI	dZ V l
ni-	ger
n aI	dZ @r
ni-	hi-	li-	sm
n aI	I	l I	z V m
ni-	hi-	lists
n aI	I	l I s t s
ni-	hon
n I	h Q n
ni-	ke
n aI	k i:
ni-	ke's
n aI	k i: z
ni-	ki-	ta
n I	k i:	t V
ni-	ko
n i:	k @U
ni-	ko-	lai
n I	k @U	l aI
ni-	ko-	laus
n I	k V	l aU z
ni-	kon
n aI	k Q n
ni-	ko's
n i:	k @U z
ni-	la
n i:	l V
ni-	land
n aI	l V n d
ni-	mitz
n I	m I t s
ni-	moy
n i:	m OI
ni-	na
n aI	n V
ni-	ne-	veh
n I	n V	v V
ni-	ner
n aI	n @r
ni-	nette
n I	n e t
ni-	no
n i:	n @U
ni-	non
n I	n V n
ni-	o-	bi-	um
n aI	@U	b i:	V m
ni-	o-	bite
n aI	@U	b aI t
ni-	pon
n I	p Q n
ni-	ren-	berg
n aI	r V n	b @r g
ni-	sei
n I	s eI
ni-	shi
n i:	S i:
ni-	ta
n i:	t V
ni-	ven
n aI	v V n
ni-	xes
n I k	s V z
ni-	xie
n I k	s i:
ni-	xon
n I k	s V n
ni-	xon's
n I k	s V n z
niall
n aI l
nib
n I b
nib-	b-	ling
n I	b V	l I N
nib-	ble
n I	b V l
nib-	bled
n I	b V l d
nib-	bles
n I	b V l z
nibs
n I b z
nic-	co-	lite
n I	k V	l aI t
nic-	ke-	lo-	de-	on
n I	k V	l @U	d i:	V n
nic-	kel
n I	k V l
nic-	kels
n I	k V l z
nic-	kel's
n I	k V l z
nic-	ker-	son
n I	k @r	s V n
nic-	key
n I	k i:
nic-	ki
n I	k i:
nic-	kle
n I	k V l
nic-	kle-	by
n I	k V l	b i:
nic-	kles
n I	k V l z
nic-	ko-	las
n I	k V	l V z
nic-	kum
n I	k V m
nic-	ky
n I	k i:
nic-	ky's
n I	k i: z
nice
n aI s
nice-	ly
n aI s	l i:
nice-	ness
n aI s	n V s
niche
n I tS
nick
n I k
nick-	lau-	s's
n I k	l V	s V z
nick-	laus
n I k	l V s
nick-	name
n I k	n eI m
nick-	named
n I k	n eI m d
nick-	names
n I k	n eI m z
nicked
n I k t
nicks
n I k s
nick's
n I k s
nie
n i:
nie-	buhr
n i:	b U@
nie-	ces
n i:	s V z
nie-	ce's
n i:	s V z
nie-	haus
n i:	h aU s
nie-	moel-	ler
n aI	m O:	l @r
niece
n i: s
nied
n i: d
niel
n i: l
niel-	sen
n i: l	s V n
niel-	sen's
n i: l	s V n z
niel-	son
n i: l	s V n
niels
n i: l z
nier-	man
n I@	m V n
nies
n aI z
nietz-	sche
n i:	tS i:
nif-	ty
n I f	t i:
nig-	gard-	li-	ness
n I	g @r d	l i:	n V s
nig-	gard-	ly
n I	g @r d	l i:
nig-	ger
n I	g @r
nig-	gers
n I	g @r z
nig-	ger's
n I	g @r z
nigh
n aI
night
n aI t
night-	shade
n aI	tS eI d
night-	shirt
n aI	tS @r t
night-	stand
n aI t	s t { n d
night-	stick
n aI t	s t I k
night-	time
n aI t	t aI m
night-	times
n aI t	t aI m z
nights
n aI t s
night's
n aI t s
nights'
n aI t s
nii-	hau
n i:	h aU
nik-	kei
n I	k eI
nik-	ki
n I	k i:
nik-	ko
n i:	k @U
nik-	ko's
n i:	k @U z
nil
n I l
nil-	ly
n I	l i:
nil-	sen
n I l	s V n
nil-	son
n I l	s V n
nile
n aI l
niles
n aI l z
nill
n I l
nils
n I l z
nils-	son
n I l	s V n
nim-	ble
n I m	b V l
nim-	bus
n I m	b V s
nim-	by
n I m	b i:
nim-	mer
n I	m @r
nim-	rod
n I m	r Q d
nimb-	ly
n I m	b l i:
nims
n I m z
nin-	com-	poop
n I N	k V m	p u: p
nin-	com-	poops
n I N	k V m	p u: p s
nin-	ja
n I n	dZ V
nin-	jas
n I n	dZ V z
nin-	ten-	do
n I n	t e n	d @U
nine
n aI n
nine-	fold
n I n	f @U l d
nine-	teen
n aI n	t i: n
nine-	teenth
n aI n	t i: n T
nine-	ti-	eth
n aI n	t i:	V T
nine-	ties
n aI n	t i: z
nine-	ty
n aI n	t i:
nine-	ty's
n aI n	t i: z
nines
n aI n z
nine's
n aI n z
ninth
n aI n T
ninths
n aI n T s
nip
n I p
nip-	per
n I	p @r
nip-	ping
n I	p I N
nip-	ple
n I	p V l
nip-	pon
n I	p Q n
nip-	py
n I	p i:
nipped
n I p t
nir
n I@
nir-	va-	na
n I@	v Q	n V
nir-	va-	na's
n I@	v Q	n V z
nis-	bet
n I z	b V t
nis-	sa
n I	s V
nis-	san
n i:	s Q n
nis-	sans
n i:	s Q n z
nis-	san's
n i:	s Q n z
nis-	sen
n I	s V n
nist
n I s t
nit
n I t
nit-	pic-	king
n I t	p I	k I N
nit-	pick
n I t	p I k
nit-	ra-	ting
n aI t	r eI	t I N
nit-	ra-	tion
n aI t	r eI	S V n
nit-	rate
n aI t	r eI t
nit-	rates
n aI t	r eI t s
nit-	ric
n aI t	r I k
nit-	ride
n aI t	r aI d
nit-	riles
n aI t	r V l z
nit-	ro
n I t	r @U
nit-	ro-	cel-	lu-	lose
n aI t	r @U	s e l	j V	l @U s
nit-	ro-	ge-	nous
n aI t	r Q	dZ V	n V s
nit-	ro-	gen
n aI t	r V	dZ V n
nit-	ro-	gly-	ce-	rin
n aI t	r @U g	l I	s @r	I n
nit-	ro-	gly-	ce-	rine
n aI t	r @U g	l I	s @r	I n
nit-	ro-	sa-	mines
n V t	r Q	s V	m i: n z
nit-	rous
n I t	r V s
nit-	ta
n I	t V
nit-	ty
n I	t i:
nit-	za
n I t	z V
nit-	za's
n I t	z V z
nite
n aI t
nitz
n I t s
nix
n I k s
nixed
n I k s t
no
n @U
no-	a
n @U	V
no-	aa
n @U	V
no-	ah
n @U	V
no-	ah's
n @U	V z
no-	be-	li-	um
n @U	b e	l i:	V m
no-	bel
n @U	b e l
no-	bi-	li-	ty
n @U	b I	l I	t i:
no-	bile
n Q	b I l
no-	bis
n @U	b I s
no-	ble
n @U	b V l
no-	ble-	man
n @U	b V l	m V n
no-	ble-	man's
n @U	b V l	m V n z
no-	ble-	wo-	man
n @U	b V l	w U	m V n
no-	bles
n @U	b V l z
no-	ble's
n @U	b V l z
no-	bo-	dies
n @U	b Q	d i: z
no-	bo-	dy
n @U	b Q	d i:
no-	bo-	dy'd
n @U	b Q	d i: d
no-	bo-	dy's
n @U	b Q	d i: z
no-	du-	lar
n Q	dZ V	l @r
no-	dule
n Q	dZ u: l
no-	dules
n Q	dZ u: l z
no-	el
n @U	e l
no-	elle
n @U	e l
no-	el's
n @U	e l z
)"
R"(no-	ga-	les
n @U	g Q	l e s
no-	gu-	chi
n @U	g u:	tS i:
no-	ki-	a
n @U	k i:	V
no-	la
n @U	l V
no-	la-	na
n @U	l {	n V
no-	lan
n @U	l V n
no-	land
n @U	l V n d
no-	le-	ta
n @U	l e	t V
no-	li-	ta
n @U	l i:	t V
no-	lie
n Q	l i:
no-	lo
n @U	l @U
no-	ma-	dic
n @U	m {	d I k
no-	mad
n @U	m { d
no-	mads
n @U	m { d z
no-	mad's
n @U	m { d z
no-	men-	cla-	to-	ri-	al
n @U	m V n	k l V	t O@	i:	V l
no-	men-	cla-	tu-	ral
n @U	m V n	k l eI	tS @r	V l
no-	men-	cla-	ture
n @U	m V n	k l eI	tS @r
no-	men-	kla-	tu-	ra
n @U	m e N	k l V	tS U@	V
no-	mi
n @U	m i:
no-	mi-	na-	ted
n Q	m I	n eI	t I d
no-	mi-	na-	ting
n Q	m I	n eI	t I N
no-	mi-	na-	tion
n Q	m I	n eI	S V n
no-	mi-	na-	tions
n Q	m I	n eI	S V n z
no-	mi-	nal
n Q	m I	n V l
no-	mi-	nal-	ly
n Q	m I	n V	l i:
no-	mi-	nate
n Q	m I	n eI t
no-	mi-	nates
n Q	m I	n eI t s
no-	mi-	nee
n Q	m I	n i:
no-	mi-	nees
n Q	m I	n i: z
no-	mi-	nee's
n Q	m I	n i: z
no-	mu-	ra
n @U	m U@	V
no-	mu-	ra's
n @U	m U@	V z
no-	na
n Q	n V
no-	na-	ca-	de-	mic
n Q	n {	k V	d e	m I k
no-	na-	ligned
n Q	n V	l aI n d
no-	nac-	cru-	al
n Q	n V k	r u:	V l
no-	nac-	cru-	ing
n Q	n V k	r u:	I N
no-	nag-	gres-	sion
n Q	n V g	r e	S V n
no-	nag-	ri-	cul-	tu-	ral
n Q	n { g	r I	k V l	tS @r	V l
no-	nal-	co-	ho-	lic
n Q	n { l	k V	h Q	l I k
no-	nau-	to-	mo-	tive
n Q	n O:	t @U	m @U	t I v
no-	ne-	co-	no-	mic
n Q	n e	k V	n Q	m I k
no-	ne-	lec-	tri-	cal
n Q	n V	l e k	t r I	k V l
no-	ne-	mer-	gen-	cy
n Q	n V	m @r	dZ V n	s i:
no-	nen-	ti-	ty
n Q	n e n	t I	t i:
no-	nes-	sen-	tial
n Q	n V	s e n	tS V l
no-	nie
n Q	n i:
no-	nin-	fla-	tio-	na-	ry
n Q	n I n	f l eI	S V	n e@	i:
no-	nu-	nio-	nized
n Q n	j u: n	j V	n aI z d
no-	nu-	nion
n Q n	j u: n	j V n
no-	nu-	ti-	li-	ty
n Q n	j u:	t I	l I	t i:
no-	ra
n O@	V
no-	rah
n O@	V
no-	ra's
n O@	V z
no-	reen
n @r	i: n
no-	ri-	e-	ga
n O@	i:	eI	g V
no-	ri-	e-	ga's
n O@	i:	eI	g V z
no-	ro-	dom
n O@	@U	d V m
no-	ses
n @U	z V z
no-	si-	ness
n @U	z i:	n V s
no-	sing
n @U	z I N
no-	sy
n @U	z i:
no-	ta-	ble
n @U	t V	b V l
no-	ta-	bles
n @U	t V	b V l z
no-	ta-	ry
n @U	t @r	i:
no-	ta-	tion
n @U	t eI	S V n
no-	ta-	tions
n @U	t eI	S V n z
no-	tab-	ly
n @U	t V b	l i:
no-	ted
n @U	t V d
no-	ther
n V	D @r
no-	thing
n V	T I N
no-	thing-	ness
n V	T I N	n V s
no-	things
n V	T I N z
no-	ti-	cea-	ble
n @U	t I	s V	b V l
no-	ti-	ceab-	ly
n @U	t I	s V b	l i:
no-	ti-	ces
n @U	t I	s V z
no-	ti-	cing
n @U	t I	s I N
no-	ti-	fi-	ca-	tion
n @U	t I	f I	k eI	S V n
no-	ti-	fi-	ca-	tions
n @U	t I	f I	k eI	S V n z
no-	ti-	fied
n @U	t I	f aI d
no-	ti-	fies
n @U	t I	f aI z
no-	ti-	fy
n @U	t I	f aI
no-	ti-	fy-	ing
n @U	t I	f aI	I N
no-	tice
n @U	t I s
no-	ticed
n @U	t I s t
no-	ting
n @U	t I N
no-	tion
n @U	S V n
no-	tions
n @U	S V n z
no-	tis
n @U	t I s
no-	to-	chord
n @U	t V	k O@ d
no-	to-	ri-	e-	ty
n @U	t @r	aI	V	t i:
no-	to-	ri-	ous
n @U	t O@	i:	V s
no-	to-	ri-	ous-	ly
n @U	t O@	i:	V s	l i:
no-	va
n @U	v V
no-	va-	to
n @U	v Q	t @U
no-	vak
n @U	v { k
no-	vak's
n @U	v { k s
no-	vas
n @U	v V z
no-	va's
n @U	v V z
no-	ve-	lis-	tic
n Q	v V	l I s	t I k
no-	ve-	list
n Q	v V	l V s t
no-	ve-	lists
n Q	v V	l V s t s
no-	vel
n Q	v V l
no-	vel-	la
n @U	v e	l V
no-	vel-	lo
n @U	v e	l @U
no-	vel-	ly
n @U	v V	l i:
no-	vel-	ties
n Q	v V l	t i: z
no-	vel-	ty
n Q	v V l	t i:
no-	vels
n Q	v V l z
no-	vel's
n Q	v V l z
no-	vem-	ber
n @U	v e m	b @r
no-	vem-	ber's
n @U	v e m	b @r z
no-	vi
n @U	v i:
no-	vi-	a
n @U	v i:	V
no-	vi-	ces
n Q	v I	s V z
no-	vice
n Q	v I s
no-	vick
n @U	v I k
no-	vin-	ger
n @U	v I	N @r
no-	vo
n @U	v @U
no-	vo-	si-	birsk
n @U	v V	s I	b @r s k
no-	vot-	ny
n V	v @U t	n i:
no-	vum
n @U	v V m
no-	wa-	day
n aU	V	d eI
no-	wa-	days
n aU	V	d eI z
no-	well
n @U	V l
no-	wels
n aU	V l z
no-	where
n @U	w e@
no-	xious
n Q k	S V s
no-	xon
n Q k	s V n
noa-	mi
n @U	m i:
noakes
n @U k s
noam
n @U m
nob-	lesse
n @U b	l e s
nob-	lest
n @U b	l V s t
nob-	ly
n Q b	l i:
noc-	tur-	nal
n Q k	t @r	n V l
nock
n Q k
nod
n Q d
nod-	ded
n Q	d V d
nod-	ding
n Q	d I N
node
n @U d
nodes
n @U d z
nods
n Q d z
noe
n @U
noell
n @U l
noes
n @U z
noh
n @U
noi-	ses
n OI	z V z
noi-	si-	er
n OI	z i:	@r
noi-	si-	est
n OI	z i:	V s t
noi-	si-	ly
n OI	z I	l i:
noi-	sy
n OI	z i:
noir
n OI r
noirs
n OI r z
noise
n OI z
nol-	lie
n @U	l i:
nold
n @U l d
nolde
n @U l d
nole
n @U l
noles
n @U l z
noll
n @U l
nolls
n @U l z
nolt
n @U l t
nolte
n @U l t
nom
n Q m
nome
n @U m
nome's
n @U m z
non
n Q n
non-	a
n Q	n V
non-	al-	co-	ho-	lic
n Q	n { l	k V	h Q	l I k
non-	ban-	king
n Q n	b { N	k I N
non-	bank
n Q n	b { N k
non-	be-	lie-	ver
n Q n	b V	l i:	v @r
non-	be-	lie-	vers
n Q n	b V	l i:	v @r z
non-	bi-	nding
n Q n	b aI n	d I N
non-	bi-	ting
n Q n	b aI	t I N
non-	buil-	ding
n Q n	b I l	d I N
non-	busi-	ness
n Q n	b I z	n V s
non-	cal-	la-	ble
n Q n	k O:	l V	b V l
non-	cash
n Q n	k { S
non-	catho-	lic
n Q n	k { T	l I k
non-	cha-	lance
n Q n	S V	l Q n s
non-	cha-	lant
n Q n	S V	l Q n t
non-	cha-	lant-	ly
n Q n	S V	l Q n	t l i:
non-	co-	lor
n Q n	k V	l @r
non-	com-	ba-	tant
n Q n	k V m	b {	t V n t
non-	com-	ba-	tants
n Q n	k V m	b {	t V n t s
non-	com-	mer-	cial
n Q n	k V	m @r	S V l
non-	com-	mit-	tal
n Q n	k V	m I	t V l
non-	com-	mu-	nist
n Q n	k Q m	j u:	n I s t
non-	com-	pe-	ti-	tive
n Q n	k V m	p e	t I	t I v
non-	comp-	li-	ance
n Q n	k V m	p l aI	V n s
non-	con-	for-	mi-	ty
n Q n	k V n	f O@	m V	t i:
non-	con-	for-	mist
n Q n	k V n	f O@	m V s t
non-	con-	for-	mists
n Q n	k V n	f O@	m V s t s
non-	con-	tract
n Q n	k Q n	t r { k t
non-	con-	tro-	ver-	sial
n Q n	k Q n	t r V	v @r	S V l
non-	con-	ver-	ti-	ble
n Q n	k V n	v @r	t V	b V l
non-	corpo-	rate
n Q n	k O@ p	r V t
non-	cri-	mi-	nal
n Q n	k r I	m I	n V l
non-	cu-	mu-	la-	tive
n Q n	k j u: m	j V	l V	t I v
non-	de-	duc-	ti-	ble
n Q n	d V	d V k	t V	b V l
non-	de-	fense
n Q n	d V	f e n s
non-	de-	script
n Q n	d V s	k r I p t
non-	dis-	cri-	mi-	na-	tion
n Q n	d I s	k r I	m I	n eI	S V n
non-	dis-	cri-	mi-	na-	to-	ry
n Q n	d I s	k r I	m I	n V	t O@	i:
non-	disc-	ri-	mi-	na-	tion
n Q n	d I s	k r I	m I	n eI	S V n
non-	dol-	lar
n Q n	d Q	l @r
non-	du-	ra-	ble
n Q n	d U@	V	b V l
non-	du-	ra-	bles
n Q n	d U@	V	b V l z
non-	e-	vent
n Q	n I	v e n t
non-	e-	xe-	cu-	tive
n Q	n I g	z e k	j V	t I v
non-	e-	xis-	tent
n Q	n V g	z I s	t V n t
non-	ex-	clu-	sive
n Q	n I k	s k l u:	s I v
non-	fa-	tal
n Q n	f eI	t V l
non-	farm
n Q n	f Q@ m
non-	fat
n Q n	f { t
non-	fer-	rous
n Q n	f e@	V s
non-	fi-	nan-	cial
n Q n	f I	n { n	S V l
non-	fic-	tion
n Q n	f I k	S V n
non-	food
n Q n	f u: d
non-	go-	vern-	men-	tal
n Q n	g V	v @r n	m e n	t V l
non-	go-	vern-	ment
n Q n	g V	v @r n	m V n t
non-	greek
n Q n	g r i: k
non-	hu-	man
n Q n	h j u:	m V n
non-	in-	ter-	fe-	rence
n Q	n I n	t @r	f I@	V n s
non-	in-	ter-	ven-	tion
n Q	n I n	t @r	v e n	tS V n
non-	inte-	rest
n Q	n I n	t r V s t
non-	le-	thal
n Q n	l i:	T V l
non-	li-	ne-	ar
n Q n	l I	n i:	@r
non-	li-	tur-	gi-	cal
n Q n	l I	t @r	dZ I	k V l
non-	ma-	nage-	ment
n Q n	m {	n I dZ	m V n t
non-	ma-	nu-	fac-	tu-	ring
n Q n	m { n	j V	f { k	tS @r	I N
non-	mem-	ber
n Q n	m e m	b @r
non-	mem-	bers
n Q n	m e m	b @r z
non-	mi-	li-	ta-	ry
n Q n	m I	l I	t e@	i:
non-	na-	tive
n Q	n eI	t I v
non-	nu-	cle-	ar
n Q	n u: k	l i:	@r
non-	o-	pe-	ra-	ting
n Q	n O:	p @r	eI	t I N
non-	pa-	ci-	fist
n Q n	p {	s I	f I s t
non-	par-	ti-	san
n Q n	p Q@	t I	z V n
non-	pay-	ing
n Q n	p eI	I N
non-	pay-	ment
n Q n	p eI	m V n t
non-	per-	for-	ming
n Q n	p @r	f O@	m I N
non-	pla-	nar
n Q n	p l eI	n @r
non-	plussed
n Q n	p l V s t
non-	po-	li-	ti-	cal
n Q n	p V	l I	t I	k V l
non-	poi-	so-	nous
n Q n	p OI	z V	n V s
non-	pre-	scrip-	tion
n Q n	p r V s	k r I p	S V n
non-	pro-	duc-	tive
n Q n	p r V	d V k	t I v
non-	pro-	fes-	sio-	nal
n Q n	p r V	f e	S V	n V l
non-	pro-	fes-	sio-	nals
n Q n	p r V	f e	S V	n V l z
non-	pub-	lic
n Q n	p V b	l I k
non-	ra-	cial
n Q n	r eI	S V l
non-	re-	cur-	ring
n Q n	r I	k @r	I N
non-	re-	fun-	da-	ble
n Q n	r V	f V n	d V	b V l
non-	re-	gu-	la-	ted
n Q n	r e g	j V	l eI	t V d
non-	re-	li-	gious
n Q n	r V	l I	dZ V s
non-	re-	ne-	wa-	ble
n Q n	r i:	n u:	V	b V l
non-	re-	si-	den-	tial
n Q n	r e	z I	d e n	S V l
non-	re-	si-	dent
n Q n	r e	z I	d V n t
non-	re-	si-	dents
n Q n	r e	z I	d e n t s
non-	res-	pon-	sive
n Q n	r V s	p Q n	s I v
non-	ro-	man
n Q n	r @U	m V n
non-	ru-	ling
n Q n	r u:	l I N
non-	sec-	ta-	ri-	an
n Q n	s e k	t e@	i:	V n
non-	sen-	si-	cal
n Q n	s e n	s I	k V l
non-	sense
n Q n	s e n s
non-	smo-	ker
n Q n	s m @U	k @r
non-	smo-	kers
n Q n	s m @U	k @r z
non-	smo-	king
n Q n	s m @U	k I N
non-	spe-	ci-	fic
n Q n	s p V	s I	f I k
non-	spor-	ting
n Q n	s p O@	t I N
non-	stan-	dard
n Q n	s t { n	d @r d
non-	star-	ter
n Q n	s t Q@	t @r
non-	stick
n Q n	s t I k
non-	stop
n Q n	s t Q p
non-	stra-	te-	gic
n Q n	s t r V	t i:	dZ I k
non-	su-	per-	vi-	so-	ry
n Q n	s u:	p @r	v aI	z @r	i:
non-	sur-	gi-	cal
n Q n	s @r	dZ I	k V l
non-	ta-	xa-	ble
n Q n	t { k	s V	b V l
non-	tech-	ni-	cal
n Q n	t e k	n I	k V l
non-	to-	xic
n Q n	t Q k	s I k
non-	tra-	di-	tio-	nal
n Q n	t r V	d I	S V	n V l
non-	trans-	fe-	ra-	ble
n Q n	t r { n	s f @r	V	b V l
non-	u-	nion
n Q n	j u: n	j V n
non-	ver-	bal
n Q n	v @r	b V l
non-	vi-	o-	lence
n Q n	v aI	V	l V n s
non-	vi-	o-	lent
n Q n	v aI	V	l V n t
non-	vo-	la-	tile
n Q n	v Q	l V	t V l
non-	vo-	ting
n Q n	v @U	t I N
non-	white
n Q n	w aI t
non-	whites
n Q n	w aI t s
non-	wo-	ven
n Q n	w @U	v V n
non-	wo-	vens
n Q n	w @U	v V n z
none
n V n
none-	such
n V n	s V tS
none-	the-	less
n V n	D V	l e s
nonp-	ro-	fit
n Q n	p r Q	f I t
noo-	dle
n u:	d V l
noo-	dles
n u:	d V l z
noo-	nan
n u:	n V n
nook
n U k
nooks
n U k s
noon
n u: n
noon-	time
n u: n	t aI m
noone
n u: n
noons
n u: n z
noose
n u: s
nope
n @U p
nor
n O@
nor-	ber-	to
n O@	b @r	t @U
nor-	bert
n O@	b @r t
nor-	by
n O@	b i:
nor-	co
n O@	k @U
nor-	cross
n O@ k	r O: s
nor-	den
n O@	d V n
nor-	di-	ca
n O@	d I	k V
nor-	di-	ne
n O@	d i:	n i:
nor-	dic
n O@	d I k
nor-	din
n O@	d I n
nor-	folk
n O@	f V k
nor-	folk's
n O@	f V k s
nor-	lan-	der
n O@	l V n	d @r
nor-	land
n O@	l V n d
nor-	ling
n O@	l I N
nor-	ma
n O@	m V
nor-	ma-	li-	ty
n O@	m {	l I	t i:
nor-	ma-	li-	za-	tion
n O@	m V	l I	z eI	S V n
nor-	ma-	li-	zing
n O@	m V	l aI	z I N
nor-	ma-	lize
n O@	m V	l aI z
nor-	ma-	lized
n O@	m V	l aI z d
nor-	ma-	tive
n O@	m V	t I v
nor-	mal
n O@	m V l
nor-	mal-	cy
n O@	m V l	s i:
nor-	mal-	ly
n O@	m V	l i:
nor-	man
n O@	m V n
nor-	man-	die
n O@	m V n	d i:
nor-	man-	dy
n O@	m V n	d i:
nor-	mand
n O@	m V n d
nor-	man's
n O@	m V n z
nor-	mie
n O@	m i:
nor-	ming
n O@	m I N
nor-	my
n O@	m i:
nor-	na
n O@	n V
nor-	plant
n O@ p	l { n t
nor-	rie
n O@	i:
nor-	ris
n O@	I s
nor-	ry
n O@	i:
nor-	tham
n O@	T V m
nor-	thamp-	ton
n O@	T { m	p t V n
nor-	ther
n O@	D @r
nor-	ther-	ly
n O@	D @r	l i:
nor-	ther-	ner
n O@	D @r	n @r
nor-	ther-	ners
n O@	D @r	n @r z
nor-	thern
n O@	D @r n
nor-	thern-	most
n O@	D @r n	m @U s t
nor-	they
n O@	D i:
nor-	thing-	ton
n O@	T I N	t V n
nor-	ton
n O@	t V n
nor-	ton's
n O@	t V n z
nor-	vell
n O@	v V l
nor-	vil
n O@	v I l
nor-	vin
n O@	v I n
nor-	walk
n O@	w O: k
nor-	ward
n O@	w @r d
nor-	way
n O@	w eI
nor-	way's
n O@	w eI z
nor-	we-	gian
n O@	w i:	dZ V n
nor-	we-	gians
n O@	w i:	dZ V n z
nor-	well
n O@	w e l
nor-	west
n O@	w e s t
nor-	wich
n O@	w I tS
nor-	wood
n O@	w U d
nord
n O@ d
nord-	gren
n O@ d	g r e n
nord-	man
n O@ d	m V n
nord-	strom
n O@ d	s t r V m
nord-	strom's
n O@ d	s t r V m z
norge
n O@ dZ
nork
n O@ k
norm
n O@ m
norms
n O@ m z
norse
n O@ s
norse-	men
n O@ s	m e n
norsk
n O@ s k
norte
n O@ t
north
n O@ T
north-	bound
n O@ T	b aU n d
north-	eas-	ter-	ly
n O@	T i: s	t @r	l i:
north-	eas-	ter-	ner
n O@	T i: s	t @r	n @r
north-	eas-	ter-	ners
n O@	T i: s	t @r	n @r z
north-	eas-	tern
n O@	T i: s	t @r n
north-	east
n O@	T i: s t
north-	east-	ward
n O@	T i: s	t w @r d
north-	east's
n O@	T i: s t s
north-	field
n O@ T	f i: l d
north-	land
n O@ T	l { n d
north-	rop
n O@ T	r V p
north-	rop's
n O@ T	r V p s
north-	rup
n O@ T	r V p
north-	rup's
n O@ T	r V p s
north-	vale
n O@ T	v eI l
north-	ward
n O@ T	w @r d
north-	way
n O@ T	w eI
north-	wes-	ter-	ly
n O@ T	w e s	t @r	l i:
north-	wes-	tern
n O@ T	w e s	t @r n
north-	west
n O@ T	w e s t
north-	west's
n O@ T	w e s t s
north's
n O@ T s
no's
n @U z
nos-	tal-	gia
n O: s	t { l	dZ V
nos-	tal-	gic
n O: s	t { l	dZ I k
nos-	tra
n O: s	t r V
nos-	tra-	da-	mus
n O: s	t r V	d {	m V s
nos-	trand
n Q s	t r V n d
nos-	tril
n Q s	t r I l
nos-	trils
n Q s	t r I l z
nos-	trums
n Q s	t r V m z
nose
n @U z
nose-	bleed
n @U z	b l i: d
nose-	dive
n @U z	d aI v
nose-	dived
n @U z	d aI v d
nosed
n @U z d
noss
n O: s
not
n Q t
not-	ches
n Q	tS V z
not-	re
n @U t	r V
not-	tage
n Q	t I dZ
not-	ting-	ham
n Q	t I N	h { m
not-	with-	stan-	ding
n Q t	w I T	s t { n	d I N
notch
n Q tS
notched
n Q tS t
note
n @U t
note-	book
n @U t	b U k
note-	books
n @U t	b U k s
note-	hol-	der
n @U t	h @U l	d @r
note-	wor-	thy
n @U t	w @r	D i:
notes
n @U t s
note's
n @U t s
nots
n Q t s
nott
n Q t
notte
n Q t
nou-	ri-	shing
n @r	I	S I N
nou-	rish
n @r	I S
nou-	rish-	ment
n @r	I S	m V n t
nou-	rished
n @r	I S t
nou-	veau
n u:	v @U
nou-	velle
n u:	v e l
noun
n aU n
nov-	go-	rod
n Q v	g @r	Q d
now
n aU
noyce
n OI s
noyes
n OI z
noz-	zle
n Q	z V l
noz-	zles
n Q	z V l z
n's
e n z
nth
e n T
nu
n u:
nu-	an-	ces
n u:	Q n	s V z
nu-	ance
n u:	Q n s
nu-	anced
n u:	Q n s t
nu-	bi-	an
n j u:	b i:	V n
nu-	cle-	a-	tion
n u: k	l i:	eI	S V n
nu-	cle-	ar
n u: k	l i:	@r
nu-	cle-	ic
n u: k	l eI	I k
nu-	cle-	o-	nic
n V k	l i:	Q	n I k
nu-	cle-	o-	nics
n V k	l i:	Q	n I k s
nu-	cle-	o-	tide
n u: k	l i:	V	t aI d
nu-	cle-	us
n u: k	l i:	V s
nu-	di-	ty
n u:	d I	t i:
nu-	dist
n u:	d I s t
nu-	gent
n u:	dZ V n t
nu-	me-	ral
n u:	m @r	V l
nu-	me-	rals
n u:	m @r	V l z
nu-	me-	ri-	cal
n u:	m e@	I	k V l
nu-	me-	ric
n u:	m e@	I k
nu-	me-	rical-	ly
n u:	m e@	I k	l i:
nu-	me-	ro-	lo-	gy
n u:	m @r	Q	l V	dZ i:
nu-	me-	rous
n u:	m @r	V s
nu-	mi-	di-	a
n u:	m I	d i:	V
nu-	mia
n u: m	j V
nu-	mis-	ma-	tic
n u:	m I s	m {	t I k
nu-	mis-	ma-	tics
n u:	m I s	m {	t I k s
nu-	mis-	ma-	tists
n u:	m I s	m V	t I s t s
nu-	nez
n u:	n e z
nu-	rem-	berg
n U@	V m	b @r g
nu-	rey-	ev
n @r	aI	V v
nu-	tra-	sweet
n u: t	r V s	w i: t
nub
n V b
nuc-	ci
n u:	tS i:
nuc-	le-	i
n u: k	l i:	aI
nud-	ges
n V	dZ V z
nud-	ging
n V	dZ I N
nudd
n V d
nude
n u: d
nudes
n u: d z
nudge
n V dZ
nudged
n V dZ d
nue-	vo
n w eI	v @U
nug-	get
n V	g V t
nug-	gets
n V	g V t s
nug-	get's
n V	g V t s
nui-	sance
n u:	s V n s
nuke
n u: k
nukes
n u: k s
null
n V l
num-	ber
n V m	b @r
num-	bing
n V	m I N
num-	bing-	ly
n V	m I N	l i:
num-	mi
n u:	m i:
numb-	ness
n V m	n V s
nun
n V n
nun-	ci-	o
n V n	s i:	@U
nun-	ne-	ry
n V	n @r	i:
nun-	nel-	ly
n V	n V	l i:
nunes
n u: n z
nunn
n V n
nunn's
n V n z
nuns
n V n z
nun's
n V n z
nuo-	va
n w @U	v V
nuo-	vo
n w @U	v @U
nup-	tial
n V p	tS V l
nur-	mi
n U@	m i:
nur-	se-	ries
n @r	s @r	i: z
nur-	se-	ry
n @r	s @r	i:
nur-	se-	ry-	man
n @r	s @r	i:	m { n
nur-	se-	ry-	men
n @r	s @r	i:	m V n
nur-	ses
n @r	s V z
nur-	se's
n @r	s V z
nur-	sing
n @r	s I N
nur-	tu-	rer
n @r	t @r	@r
nur-	tu-	ring
n @r	tS @r	I N
nur-	ture
n @r	tS @r
nur-	tured
n @r	tS @r d
nur-	tures
n @r	tS @r z
nurse
n @r s
nursed
n @r s t
nuss-	baum
n V s	b aU m
nuss-	baum's
n V s	b aU m z
nut
n V t
nut-	crac-	ker
n V t	k r {	k @r
nut-	lets
n V t	l V t s
nut-	ley
n V t	l i:
nut-	meg
n V t	m e g
nut-	ri-	a
n u: t	r i:	V
nut-	ri-	ent
n u: t	r i:	V n t
nut-	ri-	ents
n u: t	r i:	V n t s
nut-	ri-	tio-	nal
n u: t	r I	S V	n V l
nut-	ri-	tio-	nal-	ly
n u: t	r I	S V	n V	l i:
nut-	ri-	tio-	nist
n u: t	r I	S V	n I s t
nut-	ri-	tio-	nists
n u: t	r I	S V	n I s t s
nut-	ri-	tion
n u: t	r I	S V n
nut-	ri-	tious
n u: t	r I	S V s
nut-	ri-	tive
n u: t	r I	t I v
nut-	shell
n V	tS e l
nut-	tall
n V	t V l
nut-	ter
n V	t @r
nut-	ting
n V	t I N
nut-	ty
n V	t i:
nuts
n V t s
nut's
n V t s
nuz-	zi
n u: t	s i:
nuz-	zle
n V	z V l
ny-	ack
n aI	{ k
ny-	berg
n aI	b @r g
ny-	di-	a
n I	d i:	V
ny-	ere-	re
n aI	@r	I@
ny-	lon
n aI	l Q n
ny-	lons
n aI	l Q n z
ny-	man
n aI	m V n
ny-	nex
n aI	n e k s
ny-	quist
n I k	w I s t
nye
n aI
nyet
n j e t
nym-	pho-	ma-	ni-	ac
n I m	f V	m eI	n i:	{ k
nym-	pho-	ma-	ni-	acs
n I m	f V	m eI	n i:	{ k s
nymph
n I m f
nymphs
n I m f s
nys-	sa
n I	s V
nyx
n I k s
o
@U
o'
@U
o-	a-	d
@U	eI	d i:
o-	a-	hu
@U	Q	h u:
)"
R"(o-	a-	s
@U	eI	e s
o-	a-	ses
@U	eI	s i: z
o-	a-	sis
@U	eI	s I s
o-	ba
@U	b V
o-	ba-	di-	ah
@U	b V	d aI	V
o-	ba-	ra
@U	b Q@	V
o-	be-	di-	ence
@U	b i:	d i:	V n s
o-	be-	di-	ent
@U	b i:	d i:	V n t
o-	be-	di-	ent-	ly
@U	b i:	d i:	V n	t l i:
o-	be-	li-	a
@U	b e	l i:	V
o-	be-	ron
@U	b @r	Q n
o-	be-	si-	ty
@U	b i:	s I	t i:
o-	beid
@U	b aI d
o-	ber
@U	b @r
o-	ber-	hau-	sen
@U	b @r	h aU	z V n
o-	ber-	lin
@U	b @r	l I n
o-	berg
@U	b @r g
o-	bert
Q	b @r t
o-	bese
@U	b i: s
o-	bey
@U	b eI
o-	bey-	ing
@U	b eI	I N
o-	beyed
@U	b eI d
o-	beys
@U	b eI z
o-	bi-	tu-	a-	ries
@U	b I	tS u:	e@	i: z
o-	bi-	tu-	a-	ry
@U	b I	tS u:	e@	i:
o-	bie
@U	b i:
o-	bis-	po
@U	b I s	p @U
o-	bit
@U	b I t
o-	bits
Q	b I t s
o-	bo-	ist
@U	b @U	I s t
o-	boe
@U	b @U
o'-	boyle
@U	b OI l
o'-	bri-	en
@U b	r aI	V n
o'-	bri-	en's
@U b	r aI	V n z
o-	ca-	la
@U	k {	l V
o-	ca-	na
@U	k {	n V
o-	ce-	a-	nic
@U	S i:	{	n I k
o-	ce-	lot
Q	s V	l Q t
o-	ce-	lot's
Q	s V	l Q t s
o-	cea-	no-	gra-	pher
@U	S V	n Q g	r V	f @r
o-	cea-	no-	gra-	phic
@U	S V	n V g	r {	f I k
o-	cea-	no-	gra-	phy
@U	S V	n Q g	r V	f i:
o-	cean
@U	S V n
o-	cean-	front
@U	S V n	f r V n t
o-	cean-	go-	ing
@U	S V n	g @U	I N
o-	cean-	side
@U	S V n	s aI d
o-	cean-	view
@U	S V n	v j u:
o-	ceans
@U	S V n z
o-	cean's
@U	S V n z
o-	cho-	a
Q	tS @U	V
o-	chre
@U	k @r
o-	cil-	la
@U	s I	l V
o'-	clock
V k	l Q k
o'-	con-	nell
@U	k Q	n V l
o-	con-	nell
@U	k Q	n V l
o'-	con-	ner
@U	k Q	n @r
o'-	con-	nor
@U	k Q	n @r
o-	con-	nor
@U	k Q	n @r
o'-	con-	nor's
@U	k Q	n @r z
o-	da
@U	d V
o-	de-	a
Q	d i:	V
o-	de-	le
@U	d e	l i:
o-	de-	let
Q	d V	l V t
o-	de-	li-	a
@U	d e	l i:	V
o-	de-	lin-	da
@U	d e	l i: n	d V
o-	de-	on
@U	d i:	V n
o-	ded
@U	d e d
o-	del-	la
@U	d e	l V
o'-	dell
@U	d e l
o-	dell
@U	d e l
o-	dem
@U	d e m
o-	den
@U	d V n
o-	der
@U	d @r
o-	des-	sa
@U	d e	s V
o-	dette
@U	d e t
o-	di-	li-	a
@U	d i:	l i:	V
o-	di-	ous
@U	d i:	V s
o-	din
@U	d I n
o-	dle
@U	d V l
o-	do-	me-	ter
@U	d Q	m V	t @r
o-	do-	me-	ters
@U	d Q	m V	t @r z
o'-	do-	no-	ghue
@U	d Q	n V g	j u:
o-	do-	rant
@U	d @r	V n t
o-	do-	rous
@U	d @r	V s
o-	dom
@U	d V m
o'-	don-	nell
@U	d Q	n V l
o-	don-	nell
@U	d Q	n V l
o'-	don-	nell's
@U	d Q	n V l z
o-	dor
@U	d @r
o-	dor-	less
@U	d @r	l V s
o-	dors
@U	d @r z
o-	dum
@U	d V m
o'-	dwyer
@U d	w aI r
o-	dys-	se-	us
@U	d I	s i:	V s
o-	dys-	sey
Q	d V	s i:
o-	dys-	sey's
Q	d V	s i: z
o-	fal-	lon
Q	f V	l Q n
o-	fe-	li-	a
@U	f eI	l i:	V
o-	fi-	li-	a
@U	f i:	l i:	V
o-	ga-	ta
@U	g Q	t V
o-	ga-	wa
@U	g Q	w V
o-	gil-	vie
Q	dZ I l	v i:
o-	gil-	vy
@U	g I l	v i:
o-	gil-	vy's
@U	g I l	v i: z
o-	gle
@U	g V l
o-	gle-	thorpe
@U	g V l	T O@ p
o-	gled
@U	g V l d
o-	gles
@U	g V l z
o-	gles-	by
Q	g V l	s b i:
o'-	gra-	dy
@U g	r eI	d i:
o-	gre
@U	g @r
o-	gren
Q g	r e n
o-	gress
@U g	r V s
o'-	ha-	ra
@U	h e@	V
o-	ha-	re
@U	h Q@	eI
o-	ha-	shi
@U	h Q	S i:
o'-	hare
@U	h e@
o-	hi-	o
@U	h aI	@U
o-	hi-	o-	an
@U	h aI	@U	V n
o-	hi-	o-	ans
@U	h aI	@U	V n z
o-	hi-	o's
@U	h aI	@U z
o-	j
@U	dZ eI
o-	jib-	wa
@U	dZ I b	w V
o-	k
@U	k eI
o-	k-	en
@U	k eI	V n
o-	ka
@U	k V
o-	ka-	mo-	to
@U	k V	m @U	t @U
o-	ka-	za-	ki
@U	k Q	z Q	k i:
o-	kay
@U	k eI
o-	kayed
@U	k eI d
o-	kays
@U	k eI z
o-	kee-	cho-	bee
@U	k i:	tS @U	b i:
o'-	keeffe
@U	k i: f
o-	key
@U	k i:
o-	ki
@U	k i:
o-	ki-	na-	wa
@U	k I	n Q	w V
o-	ki-	na-	wans
@U	k I	n Q	w V n z
o-	kie
@U	k i:
o-	ku-	bo
@U	k u:	b @U
o-	kun
@U	k u: n
o-	la
@U	l V
o-	la-	ju-	won
V	l aI	dZ u:	Q n
o-	la-	ju-	won's
V	l aI	dZ u:	Q n z
o-	la-	the
@U	l {	T i:
o-	laf
@U	l Q f
o-	land
Q	l V n d
o-	le-	a
Q	l i:	V
o-	le-	an-	der
@U	l i:	{ n	d @r
o-	le-	and-	rin
@U	l i:	{ n	d r I n
o-	le-	as-	ter
@U	l i:	{ s	t @r
o-	le-	fin
@U	l V	f I n
o-	le-	fins
@U	l V	f I n z
o'-	lea-	ry
@U	l I@	i:
o-	lea-	ry
Q	l @r	i:
o'-	lea-	ry's
@U	l I@	i: z
o-	lean
@U	l i: n
o-	leg
@U	l V g
o-	li-	gar-	chy
Q	l I	g Q@	k i:
o-	li-	garch
@U	l I	g Q@ k
o-	li-	garchs
@U	l I	g Q@ k z
o-	li-	go-	cene
Q	l I	g @U	s i: n
o-	li-	go-	po-	lis-	tic
@U	l I	g V	p @U	l I s	t I k
o-	li-	go-	po-	ly
Q	l I	g Q	p V	l i:
o-	li-	phant
Q	l I	f V n t
o-	li-	va
@U	l i:	v V
o-	li-	ve-	ro
@U	l i:	v e@	@U
o-	li-	vei-	ra
Q	l I	v eI	r V
o-	li-	ver
Q	l I	v @r
o-	li-	ver's
Q	l I	v @r z
o-	li-	vet-	ti
Q	l I	v e	t i:
o-	li-	vet-	ti's
Q	l I	v e	t i: z
o-	li-	vette
Q	l I	v e t
o-	li-	vi-	a
@U	l I	v i:	V
o-	li-	vi-	er
@U	l I	v i:	eI
o-	li-	vine
Q	l I	v i: n
o-	lin
@U	l I n
o-	linde
Q	l I n d
o-	lin's
@U	l I n z
o-	live
Q	l I v
o-	lives
Q	l I v z
o-	lym-	pi-	a
@U	l I m	p i:	V
o-	lym-	pi-	ad
@U	l I m	p i:	{ d
o-	lym-	pi-	an
@U	l I m	p i:	V n
o-	lym-	pi-	ans
@U	l I m	p i:	V n z
o-	lym-	pi-	as
@U	l I m	p i:	V s
o-	lym-	pi-	a's
@U	l I m	p i:	V z
o-	lym-	pic
@U	l I m	p I k
o-	lym-	pics
@U	l I m	p I k s
o-	lym-	pus
@U	l I m	p V s
o-	ma-	ha
@U	m V	h Q
o-	ma-	ha's
@U	m V	h Q z
o-	ma-	ni
@U	m Q	n i:
o'-	mal-	ley
@U	m {	l i:
o-	man
@U	m Q n
o-	mar
@U	m Q@
o-	me-	ga
@U	m e	g V
o-	men
@U	m V n
o-	mens
@U	m V n z
o-	mer
@U	m @r
o-	mi-	nous
Q	m I	n V s
o-	mi-	nous-	ly
Q	m I	n V s	l i:
o-	mis-	sion
@U	m I	S V n
o-	mis-	sions
@U	m I	S V n z
o-	mit
@U	m I t
o-	mit-	ted
@U	m I	t V d
o-	mit-	ting
@U	m I	t I N
o-	mits
@U	m I t s
o-	na
V	n Q
o-	na-	gers
Q	n V	dZ @r z
o-	na-	wa
@U	n Q	w V
o-	nan
@U	n V n
o-	nas-	si-	s's
@U	n {	s I	s V z
o-	nas-	sis
@U	n {	s I s
o-	ne-	rous
@U	n @r	V s
o-	neal
@U	n i: l
o-	nei-	da
@U	n aI	d V
o'-	neil
@U	n i: l
o-	neil
@U	n i: l
o'-	neill
@U	n i: l
o-	neill
@U	n i: l
o'-	neill's
@U	n i: l z
o-	nion
V n	j V n
o-	nions
V n	j V n z
o-	no
@U	n @U
o-	no-	mas-	tic
Q	n V	m { s	t I k
o-	no-	mas-	tics
Q	n V	m { s	t I k s
o-	non-	da-	ga
Q	n V n	d O:	g V
o-	nus
@U	n V s
o-	pa-	ci-	ty
@U	p {	s I	t i:
o-	pa-	li-	na
@U	p Q	l i:	n V
o-	pa-	line
@U	p V	l i: n
o-	pa-	lines
@U	p V	l i: n z
o-	pal
@U	p V l
o-	pal's
@U	p V l z
o-	paque
@U	p eI k
o-	pe-	ner
@U	p V	n @r
o-	pe-	ners
@U	p V	n @r z
o-	pe-	ning
@U	p V	n I N
o-	pe-	nings
@U	p V	n I N z
o-	pe-	ra-	ble
Q	p @r	V	b V l
o-	pe-	ra-	ted
Q	p @r	eI	t V d
o-	pe-	ra-	tic
Q	p @r	{	t I k
o-	pe-	ra-	ting
Q	p @r	eI	t I N
o-	pe-	ra-	tio-	nal
Q	p @r	eI	S V	n V l
o-	pe-	ra-	tio-	nal-	ly
Q	p @r	eI	S V	n V	l i:
o-	pe-	ra-	tion
Q	p @r	eI	S V n
o-	pe-	ra-	tions
Q	p @r	eI	S V n z
o-	pe-	ra-	tion's
Q	p @r	eI	S V n z
o-	pe-	ra-	tive
Q	p @r	V	t I v
o-	pe-	ra-	tives
Q	p @r	V	t I v z
o-	pe-	ra-	tor
Q	p @r	eI	t @r
o-	pe-	ra-	tors
Q	p @r	eI	t @r z
o-	pe-	ra-	tor's
Q	p @r	eI	t @r z
o-	pe-	ran-	di
Q	p @r	{ n	d i:
o-	pe-	rant
Q	p @r	V n t
o-	pe-	rate
Q	p @r	eI t
o-	pe-	rates
Q	p @r	eI t s
o-	pe-	ret-	ta
Q	p @r	e	t V
o-	pe-	ret-	tas
Q	p @r	e	t V z
o-	pec
@U	p e k
o-	pel
@U	p V l
o-	pel's
@U	p V l z
o-	pen
@U	p V n
o-	pen-	ly
@U	p V n	l i:
o-	pen-	ness
@U	p V n	n V s
o-	pen-	work
@U	p V n	w @r k
o-	pened
@U	p V n d
o-	pens
@U	p V n z
o-	pi-	ate
@U	p i:	V t
o-	pi-	ates
@U	p i:	V t s
o-	pi-	ning
@U	p aI	n I N
o-	pi-	nio-	na-	ted
V	p I n	j V	n eI	t V d
o-	pi-	nio-	nate
V	p I n	j V	n eI t
o-	pi-	nion
V	p I n	j V n
o-	pi-	nions
V	p I n	j V n z
o-	pi-	um
@U	p i:	V m
o-	pie
@U	p i:
o-	pine
@U	p aI n
o-	pined
@U	p aI n d
o-	pines
@U	p aI n z
o-	pos-	sum
@U	p Q	s V m
o-	pu-	lence
Q p	j V	l V n s
o-	pu-	lent
Q p	j V	l V n t
o-	pus
@U	p V s
o-	ra
O@	V
o-	ra-	bel
O@	Q	b e l
o-	ra-	belle
O@	V	b V l
o-	ra-	cle
O@	V	k V l
o-	ra-	cles
O@	V	k V l z
o-	ra-	cle's
O@	V	k V l z
o-	ra-	li-	a
O@	Q	l i:	V
o-	ra-	lie
O@	V	l i:
o-	ra-	tion
O@	eI	S V n
o-	ra-	tions
O@	eI	S V n z
o-	ra-	to-	ri-	cal
O@	V	t O@	V	k V l
o-	ra-	to-	ri-	o
Q@	V	t O@	i:	@U
o-	ra-	to-	ry
O@	V	t O@	i:
o-	ra-	tor
O@	V	t @r
o-	ra-	tors
O@	V	t @r z
o-	ral
O@	V l
o-	ral-	ly
O@	V	l i:
o-	ram
O@	V m
o-	ran
O@	Q n
o-	ran-	ges
O@	V n	dZ V z
o-	ran-	gu-	tan
O@	{	N V	t { n
o-	ran-	gu-	tans
O@	{	N V	t { n z
o-	ran-	gu-	tan's
O@	{	N V	t { n z
o-	range
O@	V n dZ
o-	range-	burg
O@	V n	dZ b @r g
o-	re-	ga-	no
O@	e	g V	n @U
o-	re-	go-	ni-	an
O@	V	g @U	n i:	V n
o-	re-	go-	ni-	ans
O@	V	g @U	n i:	V n z
o-	re-	gon
O@	V	g V n
o-	re-	gon's
O@	V	g V n z
o-	re-	li-	a
O@	e	l i:	V
o-	re-	o
O@	i:	@U
o-	re-	stes
O@	e s	t i: z
o'-	reil-	ly
@U	r aI	l i:
o-	rel
O@	V l
o-	rem
O@	e m
o-	ren
O@	V n
o-	ren-	da
O@	e n	d V
o-	ri
O@	i:
o-	ri-	a-	na
O@	i:	{	n V
o-	ri-	en-	ta-	ted
O@	i:	V n	t eI	t V d
o-	ri-	en-	ta-	tion
O@	i:	e n	t eI	S V n
o-	ri-	en-	ta-	tions
O@	i:	e n	t eI	S V n z
o-	ri-	en-	tal
O@	i:	e n	t V l
o-	ri-	en-	tals
O@	i:	e n	t V l z
o-	ri-	en-	ted
O@	i:	e n	t V d
o-	ri-	ent
O@	i:	e n t
o-	ri-	fi-	ce
O@	V	f I	s V
o-	ri-	fi-	ces
O@	V	f I	s V z
o-	ri-	gi-	na-	li-	ty
@r	I	dZ I	n {	l I	t i:
o-	ri-	gi-	na-	ted
O@	I	dZ I	n eI	t I d
o-	ri-	gi-	na-	ting
@r	I	dZ I	n eI	t I N
o-	ri-	gi-	na-	tion
@r	I	dZ I	n eI	S V n
o-	ri-	gi-	na-	tions
@r	I	dZ I	n eI	S V n z
o-	ri-	gi-	na-	tor
@r	I	dZ I	n eI	t @r
o-	ri-	gi-	na-	tors
@r	I	dZ I	n eI	t @r z
o-	ri-	gi-	nal
@r	I	dZ I	n V l
o-	ri-	gi-	nal-	ly
@r	I	dZ I	n V	l i:
o-	ri-	gi-	nals
@r	I	dZ I	n V l z
o-	ri-	gi-	nate
@r	I	dZ I	n eI t
o-	ri-	gi-	nates
@r	I	dZ I	n eI t s
o-	ri-	gin
O@	I	dZ I n
o-	ri-	gins
O@	I	dZ I n z
o-	ri-	no-	co
O@	I	n @U	k @U
o-	ri-	ole
O@	i:	@U l
o-	ri-	oles
O@	i:	@U l z
o-	ri-	on
@U	r aI	V n
o-	ri-	on's
@U	r aI	V n z
o-	rick
O@	I k
o-	rin
O@	I n
o-	rin-	da
@r	I n	d V
o-	ro
O@	@U
o-	ro-	ge-	nic
O@	V	dZ e	n I k
o-	ro-	gra-	phic
O@	V g	r {	f I k
o'-	rourke
@U	r O@ k
o-	roz-	co
O@	@U z	k @U
o-	ry
O@	i:
o-	ryx
O@	I k s
o-	sa-	ges
@U	s eI	dZ V z
o-	sa-	ka
@U	s Q	k V
o-	sage
@U	s eI dZ
o-	sha
@U	S V
o-	sha-	wa
O:	S Q	w V
o-	she-	a
Q	S i:	V
o'-	shea
@U	S eI
o-	sher
Q	S @r
o'-	sul-	li-	van
@U	s V	l I	v V n
o-	sul-	li-	van
Q	s V	l I	v V n
o-	ta
@U	t V
o-	te-	ro
@U	t e@	@U
o-	tel-	lo
@U	t e	l @U
o-	tha
V	D Q
o-	thel-	lo
V	T e	l @U
o-	ther
V	D @r
o-	ther-	ness
V	D @r	n V s
o-	ther-	wise
V	D @r	w aI z
o-	ther-	world-	ly
V	D @r	w @r l	d l i:
o-	thers
V	D @r z
o-	ther's
V	D @r z
o-	thi-	li-	a
@U	T i:	l i:	V
o-	tis
@U	t I s
o-	to-	lo-	gy
@U	t Q	l V	dZ i:
o'-	toole
@U	t u: l
o-	ur
aU	@r
o-	va-	ry
@U	v @r	i:
o-	va-	tion
@U	v eI	S V n
o-	va-	tions
@U	v eI	S V n z
o-	vate
@U	v eI t
o-	ve-	ra-	bun-	dance
@U	v @r	V	b V n	d V n s
o-	ve-	rac-	ted
@U	v @r	{ k	t V d
o-	ve-	rac-	tive
@U	v @r	{ k	t I v
o-	ve-	ract
@U	v @r	{ k t
o-	ve-	rall
@U	v @r	O: l
o-	ve-	rea-	ger
@U	v @r	i:	g @r
o-	ve-	rop-	ti-	mi-	sm
@U	v @r	Q p	t I	m I	z V m
o-	ven
V	v V n
o-	vens
V	v V n z
o-	ver
@U	v @r
o-	ver-	alls
@U	v @r	O: l z
o-	ver-	am-	bi-	tious
@U	v @r	{ m	b I	S V s
o-	ver-	ar-	ching
@U	v @r	Q@	tS I N
o-	ver-	bea-	ring
@U	v @r	b e@	I N
o-	ver-	bil-	ling
@U	v @r	b I	l I N
o-	ver-	blown
@U	v @r b	l @U n
o-	ver-	board
@U	v @r	b O@ d
o-	ver-	boo-	king
@U	v @r	b U	k I N
o-	ver-	book
@U	v @r	b U k
o-	ver-	booked
@U	v @r	b U k t
o-	ver-	bought
@U	v @r	b O: t
o-	ver-	buil-	ding
@U	v @r	b I l	d I N
o-	ver-	built
@U	v @r	b I l t
o-	ver-	bur-	den
@U	v @r	b @r	d V n
o-	ver-	bur-	dened
@U	v @r	b @r	d V n d
o-	ver-	buy
@U	v @r	b aI
o-	ver-	by
@U	v @r	b i:
o-	ver-	ca-	pa-	ci-	ty
@U	v @r	k V	p {	s V	t i:
o-	ver-	came
@U	v @r	k eI m
o-	ver-	cast
@U	v @r	k { s t
o-	ver-	char-	ges
@U	v @r	tS Q@	dZ V z
o-	ver-	char-	ging
@U	v @r	tS Q@	dZ I N
o-	ver-	charge
@U	v @r	tS Q@ dZ
o-	ver-	charged
@U	v @r	tS Q@ dZ d
o-	ver-	co-	ming
@U	v @r	k V	m I N
o-	ver-	coat
@U	v @r	k @U t
o-	ver-	coats
@U	v @r	k @U t s
o-	ver-	come
@U	v @r	k V m
o-	ver-	comes
@U	v @r	k V m z
o-	ver-	con-	fi-	dence
@U	v @r	k Q n	f I	d V n s
o-	ver-	con-	fi-	dent
@U	v @r	k Q n	f I	d V n t
o-	ver-	con-	sump-	tion
@U	v @r	k V n	s V m	p S V n
o-	ver-	cook
@U	v @r	k U k
o-	ver-	cooked
@U	v @r	k U k t
o-	ver-	crow-	ded
@U	v @r k	r aU	d V d
o-	ver-	crow-	ding
@U	v @r k	r aU	d I N
o-	ver-	crowd
@U	v @r k	r aU d
o-	ver-	de-	pen-	dence
@U	v @r	d V	p e n	d V n s
o-	ver-	did
@U	v @r	d I d
o-	ver-	do
@U	v @r	d u:
o-	ver-	do-	ing
@U	v @r	d u:	I N
o-	ver-	do-	ses
@U	v @r	d @U	s V z
o-	ver-	done
@U	v @r	d V n
o-	ver-	dose
@U	v @r	d @U s
o-	ver-	dosed
@U	v @r	d @U s t
o-	ver-	draft
@U	v @r d	r { f t
o-	ver-	drafts
@U	v @r d	r { f t s
o-	ver-	draw
@U	v @r d	r O:
o-	ver-	drawn
@U	v @r d	r O: n
o-	ver-	dress
@U	v @r d	r e s
o-	ver-	drew
@U	v @r d	r u:
o-	ver-	drive
@U	v @r d	r aI v
o-	ver-	due
@U	v @r	d u:
o-	ver-	ea-	ting
@U	v @r	i:	t I N
o-	ver-	eat
@U	v @r	i: t
o-	ver-	em-	pha-	size
@U	v @r	e m	f V	s aI z
o-	ver-	es-	ti-	ma-	ted
@U	v @r	e s	t I	m eI	t I d
o-	ver-	es-	ti-	ma-	ting
@U	v @r	e s	t I	m eI	t I N
o-	ver-	es-	ti-	mate
@U	v @r	e s	t I	m eI t
o-	ver-	es-	ti-	mates
@U	v @r	e s	t I	m eI t s
o-	ver-	ex-	ci-	ted
@U	v @r	e k	s aI	t V d
o-	ver-	ex-	cite
@U	v @r	e k	s aI t
o-	ver-	ex-	pan-	sion
@U	v @r	I k	s p { n	S V n
o-	ver-	ex-	po-	sure
@U	v @r	I k	s p @U	Z @r
o-	ver-	ex-	pose
@U	v @r	I k	s p @U z
o-	ver-	ex-	posed
@U	v @r	I k	s p @U z d
o-	ver-	ex-	ten-	ded
@U	v @r	I k	s t e n	d V d
o-	ver-	ex-	ten-	ding
@U	v @r	I k	s t e n	d I N
o-	ver-	ex-	tend
@U	v @r	I k	s t e n d
o-	ver-	fed
@U	v @r	f e d
o-	ver-	feed
@U	v @r	f i: d
o-	ver-	fi-	shing
@U	v @r	f I	S I N
o-	ver-	fill
@U	v @r	f I l
o-	ver-	flight
@U	v @r f	l aI t
o-	ver-	flights
@U	v @r f	l aI t s
o-	ver-	flow
@U	v @r f	l @U
o-	ver-	flow-	ing
@U	v @r f	l @U	I N
o-	ver-	flowed
@U	v @r f	l @U d
o-	ver-	flows
@U	v @r f	l @U z
o-	ver-	fly
@U	v @r f	l aI
o-	ver-	fly-	ing
@U	v @r f	l aI	I N
o-	ver-	ge-	ne-	rous
@U	v @r	dZ e	n @r	V s
o-	ver-	gra-	zing
@U	v @r g	r eI	z I N
o-	ver-	grown
@U	v @r g	r @U n
o-	ver-	han-	ging
@U	v @r	h {	N I N
o-	ver-	hang
@U	v @r	h { N
o-	ver-	hangs
@U	v @r	h { N z
o-	ver-	hau-	ling
@U	v @r	h O:	l I N
o-	ver-	haul
@U	v @r	h O: l
o-	ver-	hauled
@U	v @r	h O: l d
o-	ver-	hauls
@U	v @r	h O: l z
o-	ver-	hea-	ring
@U	v @r	h I@	I N
o-	ver-	hea-	ted
@U	v @r	h i:	t V d
o-	ver-	hea-	ting
@U	v @r	h i:	t I N
o-	ver-	head
@U	v @r	h e d
o-	ver-	heads
@U	v @r	h e d z
o-	ver-	hear
@U	v @r	h I@
o-	ver-	heard
@U	v @r	h @r d
o-	ver-	heat
@U	v @r	h i: t
o-	ver-	joyed
@U	v @r	dZ OI d
o-	ver-	kil-	ling
@U	v @r	k I	l I N
o-	ver-	kill
@U	v @r	k I l
o-	ver-	laid
@U	v @r	l eI d
o-	ver-	lain
@U	v @r	l eI n
o-	ver-	land
@U	v @r	l { n d
o-	ver-	lap
@U	v @r	l { p
o-	ver-	lap-	ping
@U	v @r	l {	p I N
o-	ver-	lapped
@U	v @r	l { p t
o-	ver-	laps
@U	v @r	l { p s
o-	ver-	lay
@U	v @r	l eI
o-	ver-	lays
@U	v @r	l eI z
o-	ver-	loa-	ded
@U	v @r	l @U	d V d
o-	ver-	loa-	ding
@U	v @r	l @U	d I N
o-	ver-	load
@U	v @r	l @U d
o-	ver-	loads
@U	v @r	l @U d z
o-	ver-	lock
@U	v @r	l Q k
o-	ver-	loo-	king
@U	v @r	l U	k I N
o-	ver-	look
@U	v @r	l U k
o-	ver-	looked
@U	v @r	l U k t
o-	ver-	looks
@U	v @r	l U k s
o-	ver-	lord
@U	v @r	l O@ d
o-	ver-	lords
@U	v @r	l O@ d z
o-	ver-	ly
@U	v @r	l i:
o-	ver-	ly-	ing
@U	v @r	l aI	I N
o-	ver-	man
@U	v @r	m V n
o-	ver-	match
@U	v @r	m { tS
o-	ver-	matched
@U	v @r	m { tS t
o-	ver-	nigh-	ter
@U	v @r	n aI	t @r
o-	ver-	nigh-	ters
@U	v @r	n aI	t @r z
o-	ver-	night
@U	v @r	n aI t
o-	ver-	paid
@U	v @r	p eI d
o-	ver-	pas-	ses
@U	v @r	p {	s V z
o-	ver-	pass
@U	v @r	p { s
o-	ver-	pay
@U	v @r	p eI
o-	ver-	pay-	ing
@U	v @r	p eI	I N
o-	ver-	pay-	ment
@U	v @r	p eI	m V n t
o-	ver-	pay-	ments
@U	v @r	p eI	m V n t s
o-	ver-	peck
@U	v @r	p e k
o-	ver-	play
@U	v @r p	l eI
o-	ver-	play-	ing
@U	v @r p	l eI	I N
o-	ver-	played
@U	v @r p	l eI d
o-	ver-	po-	pu-	la-	ted
@U	v @r	p Q p	j V	l eI	t V d
o-	ver-	po-	pu-	la-	tion
@U	v @r	p Q p	j V	l eI	S V n
o-	ver-	po-	pu-	late
@U	v @r	p Q p	j V	l eI t
o-	ver-	po-	wer
@U	v @r	p aU	@r
o-	ver-	po-	wered
@U	v @r	p aU	@r d
o-	ver-	powe-	ring
@U	v @r	p aU	r I N
o-	ver-	price
@U	v @r p	r aI s
o-	ver-	priced
@U	v @r p	r aI s t
o-	ver-	pro-	du-	cer
@U	v @r p	r V	d u:	s @r
o-	ver-	pro-	du-	cers
@U	v @r p	r V	d u:	s @r z
o-	ver-	pro-	du-	cing
@U	v @r p	r V d	j u:	s I N
o-	ver-	pro-	duc-	tion
@U	v @r p	r V	d V k	S V n
o-	ver-	pro-	duce
@U	v @r p	r V	d u: s
o-	ver-	pro-	duced
@U	v @r p	r V	d u: s t
o-	ver-	pro-	tec-	tion
@U	v @r p	r V	t e k	S V n
o-	ver-	pro-	tec-	tive
@U	v @r p	r V	t e k	t V v
o-	ver-	pro-	tect
@U	v @r p	r V	t e k t
o-	ver-	qua-	li-	fied
@U	v @r k	w Q	l I	f aI d
o-	ver-	qua-	li-	fy
@U	v @r k	w Q	l I	f aI
o-	ver-	ra-	ted
@U	v @r	r eI	t V d
o-	ver-	ran
@U	v @r	r { n
o-	ver-	rate
@U	v @r	r eI t
o-	ver-	re-	ac-	ted
@U	v @r	r i:	{ k	t V d
o-	ver-	re-	ac-	ting
@U	v @r	r i:	{ k	t I N
o-	ver-	re-	ac-	tion
@U	v @r	r i:	{ k	S V n
o-	ver-	re-	act
@U	v @r	r i:	{ k t
o-	ver-	re-	gu-	la-	ted
@U	v @r	r e g	j V	l eI	t V d
o-	ver-	re-	gu-	la-	tion
@U	v @r	r e g	j V	l eI	S V n
o-	ver-	re-	gu-	late
@U	v @r	r e g	j V	l eI t
)"
R"(o-	ver-	re-	li-	ance
@U	v @r	r V	l aI	V n s
o-	ver-	rea-	ches
@U	v @r	r i:	tS V z
o-	ver-	rea-	ching
@U	v @r	r i:	tS I N
o-	ver-	reach
@U	v @r	r i: tS
o-	ver-	reached
@U	v @r	r i: tS t
o-	ver-	rep-	re-	sen-	ted
@U	v @r	r e p	r V	z e n	t V d
o-	ver-	rep-	re-	sent
@U	v @r	r e p	r V	z e n t
o-	ver-	ri-	ding
@U	v @r	r aI	d I N
o-	ver-	rid-	den
@U	v @r	r I	d V n
o-	ver-	ride
@U	v @r	r aI d
o-	ver-	rides
@U	v @r	r aI d z
o-	ver-	ripe
@U	v @r	r aI p
o-	ver-	rode
@U	v @r	r @U d
o-	ver-	ru-	ling
@U	v @r	r u:	l I N
o-	ver-	rule
@U	v @r	r u: l
o-	ver-	ruled
@U	v @r	r u: l d
o-	ver-	run
@U	v @r	r V n
o-	ver-	run-	ning
@U	v @r	r V	n I N
o-	ver-	runs
@U	v @r	r V n z
o-	ver-	saw
@U	v @r	s O:
o-	ver-	se-	er
@U	v @r	s i:	@r
o-	ver-	se-	ers
@U	v @r	s i:	@r z
o-	ver-	sea
@U	v @r	s i:
o-	ver-	seas
@U	v @r	s i: z
o-	ver-	see
@U	v @r	s i:
o-	ver-	see-	ing
@U	v @r	s i:	I N
o-	ver-	seen
@U	v @r	s i: n
o-	ver-	sees
@U	v @r	s i: z
o-	ver-	sel-	ling
@U	v @r	s e	l I N
o-	ver-	sell
@U	v @r	s e l
o-	ver-	sen-	si-	ti-	vi-	ty
@U	v @r	s e n	s I	t I	v I	t i:
)"