R"(bar-	ba-	ra
bh Q@	b @r	V
bar-	ba-	ra's
bh Q@	b @r	V z
bar-	ba-	ri-	an
bh Q@	b e@	i:	V n
bar-	ba-	ri-	ans
bh Q@	b e@	i:	V n z
bar-	ba-	ri-	sm
bh Q@	b @r	I	z V m
bar-	ba-	ri-	ty
bh Q@	b {	r I	t i:
bar-	ba-	ric
bh Q@	b {	r I k
bar-	ba-	rous
bh Q@	b @r	V s
bar-	ba-	ry
bh Q@	b @r	i:
bar-	be-	cue
bh Q@	b I k	j u:
bar-	be-	cue-	ing
bh Q@	b I k	j u:	I N
bar-	be-	cued
bh Q@	b I k	j u: d
bar-	be-	cues
bh Q@	b I k	j u: z
bar-	be-	cue's
bh Q@	b I k	j u: z
bar-	be-	que
bh Q@	b I k	j u:
bar-	be-	qued
bh Q@	b I k	j u: d
bar-	be-	ques
bh Q@	b I k	j u: z
bar-	be-	ra
bh Q@	b e@	V
bar-	be-	ro
bh Q@	b e@	@U
bar-	beau
bh Q@	b @U
bar-	bee
bh Q@	b i:
bar-	bell
bh Q@	b e l
bar-	bells
bh Q@	b e l z
bar-	bels
bh Q@	b V l z
bar-	ber
bh Q@	b @r
bar-	ber-	shop
bh Q@	b @r	S Q p
bar-	bers
bh Q@	b @r z
bar-	ber's
bh Q@	b @r z
bar-	bette
bh Q@	b e t
bar-	bi-	tu-	rate
bh Q@	b I	tS @r	V t
bar-	bi-	tu-	rates
bh Q@	b I	tS @r	V t s
bar-	bie
bh Q@	b i:
bar-	bies
bh Q@	b i: z
bar-	bie's
bh Q@	b i: z
bar-	bo-	za
bh Q@	b @U	z V
bar-	bone
bh Q@	b @U n
bar-	bour
bh Q@	b @r
bar-	bour's
bh Q@	b @r z
bar-	bra
bh Q@ b	r V
bar-	bre
bh Q@	b @r
bar-	by
bh Q@	b i:
bar-	ca
bh Q@	k V
bar-	ce-	lo-	na
bh Q@	s V	l @U	n V
bar-	cel-	la
bh Q@	s e	l V
bar-	co
bh Q@	k @U
bar-	co's
bh Q@	k @U z
bar-	cus
bh Q@	k V s
bar-	den
bh Q@	d V n
bar-	do
bh Q@	d @U
bar-	dolph
bh Q@	d Q l f
bar-	dulph
bh Q@	d V l f
bar-	en-	boim's
bh e@	V n	b OI m z
bar-	fuss
bh Q@	f V s
bar-	gai-	ner
bh Q@	g @	n @r
bar-	gai-	ners
bh Q@	g @	n @r z
bar-	gai-	ning
bh Q@	g @	n I N
bar-	gain
bh Q@	g @ n
bar-	gained
bh Q@	g @ n d
bar-	gains
bh Q@	g @ n z
bar-	ger
bh Q@	dZ @r
bar-	ges
bh Q@	dZ V z
bar-	kan
bh Q@	k V n
bar-	ker
bh Q@	k @r
bar-	kers
bh Q@	k @r z
bar-	key
bh Q@	k i:
bar-	king
bh Q@	k I N
bar-	let-	ta
bh Q@	l e	t V
bar-	ley
bh Q@	l i:
bar-	low
bh Q@	l @U
bar-	man
bh Q@	m V n
bar-	mitz-	vah
bh Q@	m I t	s v V
bar-	na
bh Q@	n V
bar-	na-	bas
bh Q@	n V	b V s
bar-	na-	by
bh Q@	n V	b i:
bar-	na-	by's
bh Q@	n V	b i: z
bar-	na-	cle
bh Q@	n V	k V l
bar-	na-	cles
bh Q@	n V	k V l z
bar-	nard
bh Q@	n @r r d
bar-	nard's
bh Q@	n @r d z
bar-	net
bh Q@	n e t
bar-	nett
bh Q@	n e t
bar-	nett's
bh Q@	n e t s
bar-	ney
bh Q@	n i:
bar-	neys
bh Q@	n i: z
bar-	ney's
bh Q@	n i: z
bar-	num
bh Q@	n V m
bar-	ny
bh Q@	n i:
bar-	ra
bh Q@	V
bar-	ra-	cu-	da
bh e@	V	k u:	d V
bar-	ra-	gan
bh e@	V	g V n
bar-	ra-	ges
bh @r	Q	Z V z
bar-	ra-	za
bh Q@	Q	z V
bar-	rack
bh {	r V k
bar-	racks
bh {	r V k s
bar-	rage
bh @r	Q Z
bar-	raged
bh @r	Q Z d
bar-	ran-	co
bh Q@	Q n	k @U
bar-	ras
bh {	r V z
bar-	re
bh e@	i:
bar-	re-	ling
bh {	r V	l I N
bar-	re-	ra
bh Q@	e@	V
bar-	rel
bh {	r V l
bar-	reled
bh {	r V l d
bar-	rels
bh {	r V l z
bar-	ren
bh {	r V n
bar-	rens
bh {	r V n z
bar-	ret
bh {	r I t
bar-	rett
bh {	r I t
bar-	rette
bh @r	e t
bar-	ri-	ca-	ded
bh {	r I	k eI	d I d
bar-	ri-	cade
bh {	r I	k eI d
bar-	ri-	cades
bh {	r I	k eI d z
bar-	ri-	er
bh {	r i:	@r
bar-	ri-	ers
bh {	r i:	@r z
bar-	ri-	o
bh Q@	i:	@U
bar-	ri-	os
bh Q@	i:	@U z
bar-	rie
bh {	r i:
bar-	rien-	tos
bh Q@	i: n	t @U z
bar-	rin-	ger
bh {	r I	N @r
bar-	ring
bh Q@	I N
bar-	ring-	ton
bh {	r I N	t V n
bar-	rings
bh Q@	I N z
bar-	ris
bh {	r I s
bar-	ris-	ter
bh {	r I s	t @r
bar-	ris-	ters
bh {	r I s	t @r z
bar-	ron
bh {	r V n
bar-	ron's
bh {	r V n z
bar-	room
bh Q@	r u: m
bar-	ros
bh Q@	@U z
bar-	row
bh {	r @U
bar-	row-	man
bh {	r @U	m V n
bar-	rows
bh {	r @U z
bar-	rus
bh {	r V s
bar-	ry
bh {	r i:
bar-	ry-	more
bh {	r i:	m O@
bar-	ry's
bh {	r i: z
bar-	sky
bh Q@ s	k i:
bar-	ta
bh Q@	t V
bar-	te-	ring
bh Q@	t @r	I N
bar-	tel
bh Q@	t V l
bar-	ten-	der
bh Q@	t e n	d @r
bar-	ten-	ders
bh Q@	t e n	d @r z
bar-	ter
bh Q@	t @r
bar-	tered
bh Q@	t @r d
bar-	the-	le-	my
bh Q@	T e	l V	m i:
bar-	thel
bh Q@	T V l
bar-	tho-	lo-	mew
bh Q@	T Q	l V m	j u:
bar-	thold
bh Q@	T @U l d
bar-	tle
bh Q@	t V l
bar-	to
bh Q@	t @U
bar-	to-	let-	ti
bh Q@	t @U	l e	t i:
bar-	to-	lo-	me-	o
bh Q@	t O:	l V	m eI	@U
bar-	tok
bh Q@	t V k
bar-	ton
bh Q@	t V n
bar-	ton's
bh Q@	t V n z
bar-	tosch
bh Q@	t O: S
bar-	tow
bh Q@	t @U
bar-	wick
bh Q@	w I k
barb
bh Q@ b
barbe
bh Q@ b
barbed
bh Q@ b d
barbs
bh Q@ b z
barb's
bh Q@ b z
barc-	lay
bh Q@ k	l eI
barc-	lay's
bh Q@ k	l i: z
barc-	roft
bh Q@ k	r O: f t
barch
bh Q@ k
bard
bh Q@ d
bard-	well
bh Q@ d	w e l
bard's
bh Q@ d z
bare
bh e@
bare-	foot
bh e@	f U t
bare-	ly
bh e@	l i:
bared
bh e@ d
bares
bh e@ z
barge
bh Q@ dZ
barged
bh Q@ dZ d
bark
bh Q@ k
bark-	ley
bh Q@ k	l i:
barked
bh Q@ k t
barks
bh Q@ k s
barks-	dale
bh Q@ k	s d eI l
barn
bh Q@ n
barn-	hard
bh Q@ n	h Q@ d
barn-	hart
bh Q@ n	h Q@ t
barn-	well
bh Q@ n	w e l
barn-	yard
bh Q@ n	j Q@ d
barnes
bh Q@ n z
barns
bh Q@ n z
barns-	tor-	ming
bh Q@ n	s t O@	m I N
barns-	torm
bh Q@ n	s t O@ m
barr
bh Q@
barred
bh Q@ d
barres
bh Q@ z
barr's
bh Q@ z
bars
bh Q@ z
bar's
bh Q@ z
bars-	tow
bh Q@ s	t @U
bart
bh Q@ t
bart-	ko
bh Q@ t	k @U
bart-	les-	ville
bh Q@	t V l	z v I l
bart-	lett
bh Q@ t	l V t
bart-	lett's
bh Q@ t	l V t s
bart-	ley
bh Q@ t	l i:
bart-	ram
bh Q@ t	r { m
barth
bh Q@ T
barthes
bh Q@ T s
bas-	co
bh Q s	k @U
bas-	com
bh { s	k V m
bas-	ker-	ville
bh { s	k @r	v I l
bas-	ket
bh { s	k V t
bas-	ket-	ball
bh { s	k V t	b O: l
bas-	ket-	balls
bh { s	k V t	b O: l z
bas-	ket-	ball's
bh { s	k V t	b O: l z
bas-	ket-	ma-	ker
bh { s	k V t	m eI	k @r
bas-	ket-	ma-	king
bh { s	k V t	m eI	k I N
bas-	ket-	ry
bh { s	k V t	r i:
bas-	kets
bh { s	k V t s
bas-	kett
bh { s	k e t
bas-	kin
bh { s	k I n
bas-	king
bh { s	k I N
bas-	ra
bh Q s	r Q
bas-	re-	lief
bh Q@	i:	l i: f
bas-	re-	liefs
bh Q@	i:	l i: f s
bas-	sa
bh {	s V
bas-	ses
bh {	s V z
bas-	set
bh {	s V t
bas-	set-	ti
bh Q	s e	t i:
bas-	sett
bh {	s e t
bas-	sette
bh V	s e t
bas-	si
bh {	s i:
bas-	sist
bh eI	s I s t
bas-	sists
bh eI	s I s t s
bas-	so
bh {	s @U
bas-	soon
bh V	s u: n
bas-	s's
bh eI	s V z
bas-	ta
bh { s	t V
bas-	tard
bh { s	t @r d
bas-	tards
bh { s	t @r d z
bas-	ten
bh eI s	t V n
bas-	tian
bh { s	tS V n
bas-	tien
bh { s	t V n
bas-	tille
bh { s	t I l
bas-	tion
bh { s	tS V n
bas-	tions
bh { s	tS V n z
bas-	togne
bh { s	t @U n
bas-	togne's
bh { s	t @U n z
bas-	ton
bh { s	t V n
base
bh eI s
base-	ball
bh eI s	b O: l
base-	balls
bh eI s	b O: l z
base-	ball's
bh eI s	b O: l z
base-	board
bh eI s	b O@ d
base-	boards
bh eI s	b O@ d z
base-	less
bh eI s	l V s
base-	line
bh eI s	l aI n
base-	man
bh eI s	m V n
base-	ment
bh eI s	m V n t
base-	ments
bh eI s	m V n t s
based
bh eI s t
bash
bh { S
bash-	ful
bh { S	f V l
bashed
bh { S t
bask
bh { s k
basked
bh { s k t
basks
bh { s k s
basque
bh { s k
basques
bh { s k s
bass
bh { s
basse
bh { s
bast
bh { s t
bat
bh { t
bat-	che-	lor
bh {	tS V	l @r
bat-	chel-	der
bh {	tS e l	d @r
bat-	ches
bh {	tS V z
bat-	ley
bh { t	l i:
bat-	man
bh { t	m { n
bat-	son
bh { t	s V n
bat-	son's
bh { t	s V n z
bat-	t-	ling
bh {	t V	l I N
bat-	ta-	lion
bh V	t { l	j V n
bat-	ta-	lions
bh V	t { l	j V n z
bat-	te-	ning
bh {	t V	n I N
bat-	te-	rer
bh {	t @r	@r
bat-	te-	rers
bh {	t @r	@r z
bat-	te-	ries
bh {	t @r	i: z
bat-	te-	ring
bh {	t @r	I N
bat-	te-	ry
bh {	t @r	i:
bat-	ted
bh {	t V d
bat-	telle
bh V	t e l
bat-	telle's
bh V	t e l z
bat-	ten
bh {	t V n
bat-	ten-	berg
bh {	t V n	b @r g
bat-	ter
bh {	t @r
bat-	ter-	man
bh {	t @r	m V n
bat-	tered
bh {	t @r d
bat-	ters
bh {	t @r z
bat-	ti-	ca-	lo-	a
bh {	t I	k V	l @U	V
bat-	ti-	pag-	li-	a
bh {	t I	p { g	l i:	V
bat-	ting
bh {	t I N
bat-	tis-	ta
bh V	t i: s	t V
bat-	tis-	te
bh Q	t i: s	t i:
bat-	tle
bh {	t V l
bat-	tle-	field
bh {	t V l	f i: l d
bat-	tle-	fields
bh {	t V l	f i: l d z
bat-	tle-	front
bh {	t V l	f r V n t
bat-	tle-	ground
bh {	t V l	g r aU n d
bat-	tle-	grounds
bh {	t V l	g r aU n d z
bat-	tle-	ment
bh {	t V l	m V n t
bat-	tle-	ments
bh {	t V l	m V n t s
bat-	tle-	ship
bh {	t V l	S I p
bat-	tle-	ships
bh {	t V l	S I p s
bat-	tled
bh {	t V l d
bat-	tles
bh {	t V l z
bat-	tle's
bh {	t V l z
bat-	ton
bh {	t V n
bat-	ty
bh {	t i:
batch
bh { tS
bate
bh eI t
bate-	man
bh eI t	m V n
bates
bh eI t s
bates-	ville
bh eI t	s v I l
bath
bh { T
bath-	robe
bh { T	r @U b
bath-	robes
bh { T	r @U b z
bath-	room
bh { T	r u: m
bath-	rooms
bh { T	r u: m z
bath-	she-	ba
bh { T	S i:	b V
bath-	tub
bh { T	t V b
bath-	tubs
bh { T	t V b z
bath-	urst
bh {	T @r s t
bath-	urst's
bh {	T @r s t s
bathe
bh eI D
bathed
bh eI D d
bathes
bh eI D z
baths
bh { T s
bats
bh { t s
batt
bh { t
batts
bh { t s
batz
bh { t s
bau-	ble
bh O:	b V l
bau-	bles
bh O:	b V l z
bau-	do-	in
bh @U d	w Q	eI n
bau-	dou-	in
bh O:	d u:	I n
bau-	er
bh aU	@r
bau-	mann
bh aU	m V n
bau-	meis-	ter
bh aU	m aI s	t @r
bau-	tis-	ta
bh O:	t i: s	t V
bau-	xite
bh O: k	s aI t
bauch
bh O: tS
baud
bh O: d
baugh
bh O:
baugh-	man
bh O:	m V n
baum
bh O: m
baun
bh O: n
baur
bh O@
baus-	man
bh aU s	m V n
bausch
bh aU S
baw-	den
bh O:	d V n
baw-	dy
bh O:	d i:
bawd
bh O: d
bawl
bh O: l
bawled
bh O: l d
bax
bh { k s
bax-	ley
bh { k	s l i:
bax-	ter
bh { k	s t @r
bax-	ter's
bh { k	s t @r z
bay
bh eI
bay-	less
bh eI	l I s
bay-	ley
bh eI	l i:
bay-	lis
bh eI	l I s
bay-	lor
bh eI	l @r
bay-	ly
bh eI	l i:
bay-	man
bh eI	m V n
bay-	reuth
bh eI	r OI T
bay-	side
bh eI	s aI d
bay-	town
bh eI	t aU n
bay-	watch
bh eI	w Q tS
baye
bh eI
bayed
bh eI d
bayes
bh eI z
bayh
bh eI
bayle
bh eI l
bayles
bh eI l z
bays
bh eI z
bay's
bh eI z
baze
bh eI z
be
bh i:
be-	a-	ta
bh i:	{	t V
be-	be
bh i:	b i:
be-	be's
bh i:	b i: z
be-	bop
bh i:	b Q p
be-	calm
bh I	k Q m
be-	calmed
bh I	k Q m d
be-	came
bh I	k eI m
be-	cause
bh I	k O: z
be-	cher
bh e	k @r
be-	co-	ming
bh I	k V	m I N
be-	come
bh I	k V m
be-	comes
bh I	k V m z
be-	de-	vil
bh V	d e	v V l
be-	de-	viled
bh V	d e	v V l d
be-	deck
bh V	d e k
be-	decked
bh V	d e k t
be-	del
bh V	d e l
be-	dell
bh e	d V l
be-	dou-	in
bh e	d @U	I n
be-	dou-	ins
bh e	d @U	I n z
be-	fal-	len
bh V	f {	l V n
be-	fall
bh V	f O: l
be-	falls
bh V	f O: l z
be-	fell
bh V	f e l
be-	fit
bh V	f I t
be-	fit-	ting
bh V	f I	t I N
be-	fits
bh V	f I t s
be-	fore
bh I	f O@
be-	fore-	hand
bh V	f O@	h { n d
be-	frien-	ded
bh V f	r e n	d V d
be-	friend
bh V f	r e n d
be-	friends
bh V f	r e n d z
be-	fud-	dle
bh V	f V	d V l
be-	fud-	dled
bh V	f V	d V l d
be-	fud-	dles
bh V	f V	d V l z
be-	gan
bh I	g { n
be-	gat
bh I	g { t
be-	gay
bh e	g eI
be-	get
bh I	g e t
be-	get-	ting
bh I	g e	t I N
be-	gets
bh I	g e t s
be-	gin
bh I	g I n
be-	gin-	ner
bh I	g I	n @r
be-	gin-	ners
bh I	g I	n @r z
be-	gin-	ner's
bh I	g I	n @r z
be-	gin-	ning
bh I	g I	n I N
be-	gin-	nings
bh I	g I	n I N z
be-	gins
bh I	g I n z
be-	gin's
bh I	g I n z
be-	go-	nia
bh I	g @U n	j V
be-	go-	nias
bh I	g @U n	j V z
be-	got
bh i:	g O: t
be-	got-	ten
bh i:	g O:	t V n
be-	gui-	ling
bh I	g aI	l I N
be-	guile
bh I	g aI l
be-	guiled
bh I	g aI l d
be-	gun
bh I	g V n
be-	ha-	ving
bh V	h eI	v I N
be-	ha-	vio-	ral
bh V	h eI v	j @r	V l
be-	ha-	vio-	rist
bh V	h eI v	j @r	V s t
be-	ha-	vio-	rists
bh V	h eI v	j @r	V s t s
be-	ha-	vior
bh V	h eI v	j @r
be-	ha-	viors
bh V	h eI v	j @r z
be-	half
bh V	h { f
be-	han
bh e	h V n
be-	har
bh e	h @r
be-	have
bh V	h eI v
be-	haved
bh V	h eI v d
be-	haves
bh V	h eI v z
be-	he-	moth
bh V	h i:	m V T
be-	he-	moths
bh V	h i:	m V T s
be-	hea-	ded
bh V	h e	d V d
be-	hea-	ding
bh V	h e	d I N
be-	hea-	dings
bh V	h e	d I N z
be-	head
bh V	h e d
be-	hest
bh I	h e s t
be-	hind
bh V	h aI n d
be-	hinds
bh V	h aI n d z
be-	hol-	den
bh V	h @U l	d V n
be-	hol-	der
bh i:	h @U l	d @r
be-	hol-	ding
bh V	h @U l	d I N
be-	hold
bh V	h @U l d
be-	hoove
bh V	h u: v
be-	hooves
bh V	h u: v z
be-	ing
bh i:	I N
be-	ings
bh i:	I N z
be-	ing's
bh i:	I N z
be-	kaa
bh e	k Q
be-	ker
bh e	k @r
be-	ker's
bh e	k @r z
be-	la
bh e	l V
be-	la-	bo-	ring
bh V	l eI	b @r	I N
be-	la-	bor
bh V	l eI	b @r
be-	la-	bored
bh V	l eI	b @r d
be-	la-	bors
bh V	l eI	b @r z
be-	la-	fon-	te
bh e	l V	f Q n	t i:
be-	la-	rus
bh e	l Q@	V s
be-	la-	ted
bh V	l eI	t V d
be-	la-	ted-	ly
bh V	l eI	t V d	l i:
be-	lair
bh e	l e@
be-	lak
bh e	l V k
be-	lan-	ger
bh e	l V	N @r
be-	las-	co
bh e	l Q s	k @U
be-	late
bh V	l eI t
be-	lea-	gue-	ring
bh V	l i:	g @r	I N
be-	lea-	guer
bh V	l i:	g @r
be-	lea-	guered
bh V	l i:	g @r d
be-	len
bh e	l V n
be-	lie
bh V	l aI
be-	lie-	va-	bi-	li-	ty
bh I	l i:	v V	b I	l V	t i:
be-	lie-	va-	ble
bh I	l i:	v V	b V l
be-	lie-	ver
bh I	l i:	v @r
be-	lie-	vers
bh I	l i:	v @r z
be-	lie-	ving
bh I	l i:	v I N
be-	lied
bh V	l aI d
be-	lief
bh V	l i: f
be-	liefs
bh V	l i: f s
be-	lier
bh e l	j @r
be-	lies
bh V	l aI z
be-	lieve
bh I	l i: v
be-	lieved
bh I	l i: v d
be-	lieves
bh I	l i: v z
be-	lin-	da
bh V	l I n	d V
be-	lit-	t-	ling
bh V	l I	t V	l I N
be-	lit-	tle
bh V	l I	t V l
be-	lit-	tled
bh V	l I	t V l d
be-	lit-	tles
bh V	l I	t V l z
be-	lize
bh e	l i: z
be-	lo
bh e	l @U
be-	loit
bh V	l OI t
be-	lon-	ging
bh I	l O:	N I N
be-	lon-	gings
bh I	l O:	N I N z
be-	long
bh I	l O: N
be-	longed
bh I	l O: N d
be-	longs
bh I	l O: N z
be-	love
bh V	l V v
be-	loved
bh V	l V v d
be-	low
bh V	l @U
be-	lu-	ga
bh V	l u:	g V
be-	lu-	shi
bh e	l u:	S i:
be-	lue
bh e l	j u:
be-	ly
bh V	l aI
be-	ly-	ing
bh V	l aI	I N
be-	man
bh i:	m V n
be-	na
bh e	n V
be-	na-	mi
bh e	n V	m i:
be-	na-	ven-	te
bh e	n Q	v e n	t i:
be-	na-	vi-	des
bh eI	n Q	v i:	d e s
be-	nac-	ko-	va
bh e	n V	k @U	v V
be-	ne
bh e	n V
be-	ne-	det-	to
bh e	n V	d e	t @U
be-	ne-	dic-	ta
bh e	n V	d i: k	t V
be-	ne-	dic-	tine
bh e	n V	d I k	t i: n
be-	ne-	dic-	tines
bh e	n V	d I k	t i: n z
be-	ne-	dic-	tine's
bh e	n V	d I k	t i: n z
be-	ne-	dic-	tion
bh e	n V	d I k	S V n
be-	ne-	dick
bh e	n V	d I k
be-	ne-	dict
bh e	n V	d I k t
be-	ne-	dikt
bh e	n V	d I k t
be-	ne-	dix
bh e	n V	d I k s
be-	ne-	fac-	tor
bh e	n V	f { k	t @r
be-	ne-	fac-	tors
bh e	n V	f { k	t @r z
be-	ne-	fac-	tor's
bh e	n V	f { k	t @r z
be-	ne-	fi-	cence
bh V	n e	f V	s V n s
be-	ne-	fi-	cent
bh e	n V	f I	S V n t
be-	ne-	fi-	ci-	a-	ries
bh e	n V	f I	S i:	e@	i: z
be-	ne-	fi-	ci-	a-	ry
bh e	n V	f I	S i:	e@	i:
be-	ne-	fi-	ci-	a-	ry's
bh e	n V	f I	S i:	e@	i: z
be-	ne-	fi-	cial
bh e	n V	f I	S V l
be-	ne-	fi-	cial-	ly
bh e	n V	f I	S V	l i:
be-	ne-	fi-	ted
bh e	n V	f I	t V d
be-	ne-	fi-	ting
bh e	n V	f I	t I N
be-	ne-	fit
bh e	n V	f I t
be-	ne-	fit-	ted
bh e	n V	f I	t V d
be-	ne-	fit-	ting
bh e	n V	f I	t I N
be-	ne-	fits
bh e	n V	f I t s
be-	ne-	lux
bh e	n V	l V k s
be-	ne-	ven-	to
bh e	n V	v eI n	t @U
be-	ne-	vo-	lence
bh V	n e	v V	l V n s
be-	ne-	vo-	lent
bh V	n e	v V	l V n t
be-	neath
bh V	n i: T
be-	nes
bh e	n i: s
be-	nesh
bh e	n I S
be-	net-	ton
bh e	n V	t V n
be-	net-	ton's
bh e	n V	t V n z
be-	ni
bh e	n i:
be-	ni-	ta
bh V	n i:	t V
be-	ni-	to
bh e	n i:	t @U
be-	nigh-	ted
bh V	n aI	t V d
be-	nign
bh V	n aI n
be-	nign-	ly
bh V	n aI n	l i:
be-	nin
bh i:	n I n
be-	nin-	ca-	sa
bh e	n i: n	k Q	s V
be-	no
bh eI	n @U
be-	no-	ni
bh e	n @U	n i:
be-	noit
bh V	n OI t
be-	o-	wulf
bh eI	V	w U l f
be-	queath
bh I k	w i: T
be-	quest
bh I k	w e s t
be-	quests
bh I k	w e s t s
be-	ra-	ted
bh I@	eI	t V d
be-	ra-	ting
bh I@	eI	t I N
be-	rar-	do
bh @r	Q@	d @U
be-	rard
bh @r	Q@ d
be-	rate
bh I@	eI t
be-	re-	a
bh @r	i:	V
be-	reave
bh @r	i: v
be-	reave-	ment
bh @r	i: v	m V n t
be-	reaved
bh @r	i: v d
be-	reft
bh @r	e f t
be-	ren-	son
bh e@	V n	s V n
be-	rend
bh e@	e n d
be-	ret
bh e@	V t
be-	ret-	ta
bh @r	e	t V
be-	ret-	tas
bh @r	e	t V s
be-	rets
bh e@	V t s
be-	ri-	a
bh e@	i:	V
be-	rin-	ger
bh e@	I	N @r
be-	ring
bh e@	I N
be-	ryl
bh e@	V l
be-	ryl-	li-	um
bh @r	I	l i:	V m
be-	san-	con
bh V	s { n	k V n
be-	sant
bh e	z V n t
be-	saw
bh i:	s O:
be-	set
bh V	s e t
be-	set-	ting
bh V	s e	t I N
be-	side
bh V	s aI d
be-	sides
bh V	s aI d z
be-	sie-	ging
bh V	s i:	dZ I N
be-	siege
bh V	s i: dZ
be-	sieged
bh V	s i: dZ d
be-	ta
bh eI	t V
be-	tide
bh I	t aI d
be-	van
bh e	v V n
be-	ve-	rage
bh e	v @r	I dZ
be-	ve-	ridge
bh e	v @r	I dZ
be-	vel
bh e	v V l
be-	velled
bh e	v V l d
be-	ver
bh e	v @r
be-	ver-	ley
bh e	v @r	l i:
be-	ver-	ly
bh e	v @r	l i:
be-	ver-	ly's
bh e	v @r	l i: z
be-	vers
bh e	v @r z
be-	vi-	er
bh e	v i:	@r
be-	vil
bh e	v I l
be-	vin
bh e	v I n
be-	ving-	ton
bh e	v I N	t V n
be-	vis
bh e	v I s
be-	vy
bh e	v i:
be-	ware
bh V	w e@
be-	wil-	de-	ring
bh V	w I l	d @r	I N
be-	wil-	der
bh V	w I l	d @r
be-	wil-	der-	ment
bh V	w I l	d @r	m V n t
be-	wil-	dered
bh V	w I l	d @r d
be-	wil-	ders
bh V	w I l	d @r z
be-	witch
bh V	w I tS
be-	witched
bh V	w I tS t
)"
R"(be-	yer
bh eI	@r
be-	yond
bh I	Q n d
be-	zan-	son
bh e	z V n	s V n
bea
bh i:
bea-	cham
bh i:	tS V m
bea-	cher
bh i:	tS @r
bea-	ches
bh i:	tS V z
bea-	ching
bh i:	tS I N
bea-	ch's
bh i:	tS V z
bea-	chy
bh i:	tS i:
bea-	con
bh i:	k V n
bea-	cons
bh i:	k V n z
bea-	ded
bh i:	d V d
bea-	dle
bh i:	d V l
bea-	dles
bh i:	d V l z
bea-	dy
bh i:	d i:
bea-	gle
bh i:	g V l
bea-	gles
bh i:	g V l z
bea-	ker
bh i:	k @r
bea-	man
bh i:	m V n
bea-	mer
bh i:	m @r
bea-	ming
bh i:	m I N
bea-	mish
bh i:	m I S
bea-	ra-	ble
bh e@	V	b V l
bea-	rer
bh e@	@r
bea-	rers
bh e@	@r z
bea-	ring
bh e@	I N
bea-	rings
bh e@	I N z
bea-	rish
bh e@	I S
bea-	rish-	ly
bh e@	I S	l i:
bea-	rish-	ness
bh e@	I S	n V s
bea-	son
bh i:	z V n
bea-	t-	ri-	ce's
bh i:	V t	r I	s V z
bea-	t-	rice
bh i:	V t	r I s
bea-	ten
bh i:	t V n
bea-	ter
bh i:	t @r
bea-	ters
bh i:	t @r z
bea-	tie
bh i:	t i:
bea-	ting
bh i:	t I N
bea-	tings
bh i:	t I N z
bea-	tles
bh i:	t V l z
bea-	ton
bh i:	t V n
bea-	ver
bh i:	v @r
bea-	ver-	ton
bh i:	v @r	t V n
bea-	vers
bh i:	v @r z
beach
bh i: tS
beach-	com-	ber
bh i: tS	k @U	m @r
beach-	front
bh i: tS	f r Q n t
beach-	head
bh i: tS	h e d
beach-	heads
bh i: tS	h e d z
beached
bh i: tS t
bead
bh i: d
bead-	work
bh i: d	w @r k
beads
bh i: d z
beak
bh i: k
beak-	like
bh i: k	l aI k
beal
bh i: l
beale
bh i: l
beall
bh i: l
beals
bh i: l z
beam
bh i: m
beamed
bh i: m d
beams
bh i: m z
beam's
bh i: m z
bean
bh i: n
bean-	town
bh i: n	t aU n
beane
bh i: n
beans
bh i: n z
bean's
bh i: n z
bear
bh e@
bear-	ded
bh I@	d V d
bear-	den
bh I@	d V n
bearce
bh @r s
beard
bh I@ d
beard-	more
bh I@ d	m O@
beards
bh I@ d z
beards-	ley
bh I@ d	z l i:
beards-	town
bh I@ d	s t aU n
beare
bh I@
bears
bh e@ z
bear's
bh e@ z
beas
bh i: z
beas-	ley
bh i: z	l i:
beas-	tie
bh i: s	t i:
beas-	ton
bh i: s	t V n
beast
bh i: s t
beasts
bh i: s t s
beat
bh i: t
beat-	nik
bh i: t	n I k
beat-	niks
bh i: t	n I k s
beat-	rix
bh i: t	r I k s
beat-	tie
bh i:	t i:
beat-	ty
bh i:	t i:
beats
bh i: t s
beau
bh @U
beau-	champ
bh @U	S Q m p
beau-	doin
bh @U	d OI n
beau-	ford
bh @U	f O@ d
beau-	fort
bh @U	f @r t
beau-	jo-	lais
bh @U	dZ @U	l eI
beau-	mont
bh @U	m O: n t
beau-	re-	gard
bh @U	r I	g Q@ d
beau-	ti-	cian
bh @U	t I	S V n
beau-	ti-	ful
bh j u:	t I	f V l
beau-	ti-	fy
bh j u:	t I	f aI
beau-	ties
bh j u:	t i: z
beau-	tiful-	ly
bh j u:	t I f	l i:
beau-	ty
bh j u:	t i:
beau-	vais
bh @U	v eI
beaux
bh @U
bec
bh e k
bec-	ka
bh e s	k V
bec-	ker
bh e	k @r
bec-	ker-	man
bh e	k @r	m V n
bec-	ker's
bh e	k @r z
bec-	ket
bh e	k V t
bec-	kett
bh e	k e t
bec-	ki
bh e	k i:
bec-	kie
bh e	k i:
bec-	ko-	ning
bh e	k V	n I N
bec-	kon
bh e	k V n
bec-	koned
bh e	k V n d
bec-	kons
bh e	k V n z
bec-	ky
bh e	k i:
bech-	ler
bh e k	l @r
bech-	tel
bh e k	t e l
becht
bh e k t
beck
bh e k
beck-	ford
bh e k	f O@ d
beck-	ley
bh e k	l i:
beck-	man
bh e k	m V n
beck-	mann
bh e k	m V n
beck-	with
bh e k	w I T
beck-	with's
bh e k	w I T s
becks
bh e k s
beck's
bh e k s
bed
bh e d
bed-	ded
bh e	d V d
bed-	ding
bh e	d I N
bed-	fel-	low
bh e d	f e	l @U
bed-	fel-	lows
bh e d	f e	l @U z
bed-	ford
bh e d	f @r d
bed-	lam
bh e d	l V m
bed-	ling-	ton
bh e d	l I N	t V n
bed-	mins-	ter
bh e d	m I n	s t @r
bed-	pan
bh e d	p { n
bed-	pans
bh e d	p { n z
bed-	rag-	gle
bh V d	r {	g V l
bed-	rag-	gled
bh V d	r {	g V l d
bed-	rid-	den
bh e d	r I	d V n
bed-	rock
bh e d	r Q k
bed-	room
bh e d	r u: m
bed-	rooms
bh e d	r u: m z
bed-	side
bh e d	s aI d
bed-	spread
bh e d	s p r e d
bed-	straw
bh e d	s t r O:
bed-	time
bh e d	t aI m
bed-	well
bh e d	w e l
bede
bh i: d
beds
bh e d z
bee
bh i:
bee-	be
bh i:	b i:
bee-	be's
bh i:	b i: z
bee-	cham
bh i:	tS V m
bee-	cham's
bh i:	tS V m z
bee-	cher
bh i:	tS @r
bee-	chy
bh i:	tS i:
bee-	fing
bh i:	f I N
bee-	fy
bh i:	f i:
bee-	hive
bh i:	h aI v
bee-	kee-	per
bh i:	k i:	p @r
bee-	kee-	pers
bh i:	k i:	p @r z
bee-	ler
bh i:	l @r
bee-	man
bh i:	m V n
bee-	mer
bh i:	m @r
bee-	per
bh i:	p @r
bee-	pers
bh i:	p @r z
bee-	ping
bh i:	p I N
bee-	ry
bh I@	i:
bee-	son
bh i:	z V n
bee-	tho-	ve-	ni-	an
bh eI	t @U	v i:	n i:	V n
bee-	tho-	ven
bh eI	t @U	v V n
bee-	tho-	ven's
bh eI	t @U	v V n z
bee-	tle
bh i:	t V l
bee-	tles
bh i:	t V l z
bee-	ton
bh i:	t V n
beech
bh i: tS
beech-	wood
bh i: tS	w U d
beeck
bh i: k
beef
bh i: f
beef-	ea-	ter
bh i:	f i:	t @r
beef-	steak
bh i: f	s t eI k
beefed
bh i: f t
beefs
bh i: f s
beek
bh i: k
beek-	man
bh i: k	m V n
been
bh I n
beens
bh I n z
beep
bh i: p
beeps
bh i: p s
beer
bh I@
beers
bh I@ z
beer's
bh I@ z
bees
bh i: z
bee's
bh i: z
bees-	ley
bh i: z	l i:
beet
bh i: t
beets
bh i: t s
beg
bh e g
beg-	gar
bh e	g @r
beg-	gars
bh e	g @r z
beg-	ging
bh e	g I N
beg-	rudge
bh I g	r V dZ
begged
bh e g d
beggs
bh e g z
begs
bh e g z
beh-	rens
bh e@	V n z
beh-	ring
bh e@	I N
behl
bh e l
behlke
bh e l k
behm
bh e m
behn
bh e n
behn-	ken
bh e N	k V n
behr-	man
bh e@	m V n
bei-	gel
bh aI	g V l
bei-	ges
bh eI	Z V z
bei-	ge's
bh eI	Z V z
bei-	jing
bh eI	Z I N
bei-	ra
bh eI	r V
bei-	rut
bh eI	r u: t
bei-	rut's
bh eI	r u: t s
bei-	sel
bh aI	s V l
beige
bh eI Z
bein
bh i: n
beirne
bh I@ n
beitz
bh i: t s
bek-	ki
bh e	k i:
bel
bh e l
bel-	cher
bh e l	tS @r
bel-	ching
bh e l	tS I N
bel-	court
bh e l	k O@ t
bel-	den
bh e l	d V n
bel-	ding
bh e l	d I N
bel-	fast
bh e l	f { s t
bel-	field
bh e l	f i: l d
bel-	ford
bh e l	f @r d
bel-	gard
bh e l	g Q@ d
bel-	ge
bh e l	dZ i:
bel-	gian
bh e l	dZ V n
bel-	gians
bh e l	dZ V n z
bel-	gique
bh e l	Z i: k
bel-	gique's
bh e l	dZ i: k s
bel-	gium
bh e l	dZ V m
bel-	gium's
bh e l	dZ V m z
bel-	grade
bh e l	g r eI d
bel-	grade's
bh e l	g r eI d z
bel-	la
bh e	l V
bel-	la-	my
bh e	l V	m i:
bel-	lan-	ca
bh e	l Q n	k V
bel-	le-	rose
bh e	l @r	V z
bel-	leau
bh e	l @U
bel-	ler
bh e	l @r
bel-	lew
bh e	l u:
bel-	li
bh e	l i:
bel-	li-	cose
bh e	l I	k @U s
bel-	li-	ge-	rence
bh V	l I	dZ @r	V n s
bel-	li-	ge-	rent
bh V	l I	dZ @r	V n t
bel-	li-	ge-	rents
bh V	l I	dZ @r	V n t s
bel-	li-	na
bh e	l i:	n V
bel-	li-	ni
bh e	l i:	n i:
bel-	li-	ni's
bh e	l i:	n i: z
bel-	lied
bh e	l i: d
bel-	lies
bh e	l i: z
bel-	lin-	gham
bh e	l I N	h { m
bel-	ling
bh e	l I N
bel-	lis
bh e	l I s
bel-	lo
bh e	l @U
bel-	lo-	wing
bh e	l @U	I N
bel-	lon
bh e	l V n
bel-	low
bh e	l @U
bel-	lowed
bh e	l @U d
bel-	lows
bh e	l @U z
bel-	low's
bh e	l @U z
bel-	ly
bh e	l i:
bel-	ly-	ache
bh e	l i:	eI k
bel-	mon-	te
bh e l	m Q n	t i:
bel-	mont
bh e l	m Q n t
bel-	ted
bh e l	t V d
bel-	ter
bh e l	t @r
bel-	ting
bh e l	t I N
bel-	ton
bh e l	t V n
bel-	va
bh eI l	v V
bel-	ve-	dere
bh e l	v I	d I@
bel-	vi-	a
bh e l	v i:	V
bel-	vi-	dere
bh e l	v V	d I@
belch
bh e l tS
belched
bh e l tS t
belf-	ry
bh e l	f r i:
belk
bh e l k
belk-	nap
bh e l	n { p
bell
bh e l
bell-	core
bh e l	k O@
bell-	flo-	wer
bh e l	f l aU	@r
bell-	flo-	wers
bh e l	f l aU	@r z
bell-	hop
bh e l	h Q p
bell-	hops
bh e l	h Q p s
bell-	man
bh e l	m V n
bell-	more
bh e l	m O@
bell-	ville
bh e l	v I l
bell-	we-	ther
bh e l	w e	D @r
bell-	we-	thers
bh e l	w e	D @r z
bell-	wood
bh e l	w U d
belle
bh e l
belle-	ville
bh V l	v I l
belle-	vue
bh e l	v j u:
belles
bh e l z
bells
bh e l z
bell's
bh e l z
bels
bh e l z
bels-	ky
bh e l	s k i:
belt
bh e l t
belt-	ran
bh e l	t r V n
belt-	way
bh e l	t w eI
belts
bh e l t s
belt's
bh e l t s
belts-	ville
bh e l	t s v I l
bem
bh e m
ben
bh e n
ben-	bow
bh e n	b @U
ben-	brook
bh e n	b r U k
ben-	cher
bh e n	tS @r
ben-	chers
bh e n	tS @r z
ben-	ches
bh e n	tS V z
ben-	da
bh e n	d V
ben-	ded
bh e n	d V d
ben-	del
bh e n	d V l
ben-	der
bh e n	d @r
ben-	ders
bh e n	d @r z
ben-	der's
bh e n	d @r z
ben-	dick
bh e n	d I k
ben-	ding
bh e n	d I N
ben-	dix
bh e n	d I k s
ben-	ga-	li
bh e N	g Q	l i:
ben-	ga-	lis
bh e N	g Q	l i: z
ben-	gal
bh e N	g V l
ben-	gals
bh e N	g V l z
ben-	ham
bh e n	h V m
ben-	ja-	min
bh e n	dZ V	m V n
ben-	ja-	min's
bh e n	dZ V	m V n z
ben-	jy
bh e n	dZ i:
ben-	net
bh e	n V t
ben-	nett
bh e	n V t
ben-	nett's
bh e	n V t s
ben-	nie
bh e	n i:
ben-	ning-	ton
bh e	n I N	t V n
ben-	nink
bh e	n I N k
ben-	nion
bh e n	j V n
ben-	nis
bh e	n I s
ben-	ny
bh e	n i:
ben-	sa-	lem
bh e n	s eI	l V m
ben-	sel
bh e n	s V l
ben-	sen
bh e n	s V n
ben-	son
bh e n	s V n
ben-	son's
bh e n	s V n z
ben-	to
bh e n	t @U
ben-	to-	nite
bh e n	t V	n aI t
ben-	ton
bh e n	t V n
ben-	ton-	ville
bh e n	t V n	v I l
ben-	ve-	nu-	to
bh e n	v e	n u:	t @U
ben-	ya-	min
bh e n	j V	m i: n
ben-	zel
bh e n	z V l
ben-	zene
bh e n	z i: n
ben-	zine
bh e n	z i: n
bench
bh e n tS
bench-	ley
bh e n	tS l i:
bench-	mark
bh e n	tS m Q@ k
bench-	marks
bh e n	tS m Q@ k s
bench-	mark's
bh e n	tS m Q@ k s
bend
bh e n d
bends
bh e n d z
benge
bh e n dZ
bengt
bh e N k t
benn
bh e n
benne
bh e n
bens
bh e n z
ben's
bh e n z
bent
bh e n t
bent-	ley
bh e n	t l i:
bent-	ley's
bh e n	t l i: z
bent-	ly
bh e n	t l i:
benz
bh e n z
ber-	be-	ri-	an
bh @r	b I@	i:	V n
ber-	ber
bh @r	b @r
ber-	ga-	mo
bh @r	g Q	m @U
ber-	ge-	ron
bh @r	g @r	O: n
ber-	gen
bh @r	g V n
ber-	gen-	field
bh @r	g V n	f i: l d
ber-	ger
bh @r	g @r
ber-	ger's
bh @r	g @r z
ber-	get
bh @r	g e t
ber-	gin
bh @r	g I n
ber-	key
bh @r	k i:
ber-	ko-	witz
bh @r	k V	w I t s
ber-	koff
bh @r	k O: f
ber-	li-	ner
bh @r	l I	n @r
ber-	li-	ners
bh @r	l I	n @r z
ber-	lin
bh @r	l I n
ber-	lin's
bh @r	l I n z
ber-	litz
bh @r	l I t s
ber-	man
bh @r	m V n
ber-	man's
bh @r	m V n z
ber-	mu-	da
bh @r m	j u:	d V
ber-	mu-	das
bh @r m	j u:	d V z
ber-	na
bh e@	n V
ber-	na-	dene
bh @r	n V	d i: n
ber-	na-	dette
bh @r	n V	d e t
ber-	na-	dine
bh @r	n V	d i: n
ber-	nal
bh @r	n V l
ber-	nar-	di
bh @r	n Q@	d i:
ber-	nar-	di-	no
bh @r	n V	d i:	n @U
ber-	nar-	din
bh @r	n Q@	d i: n
ber-	nar-	do
bh @r	n Q@	d @U
ber-	nar-	do's
bh @r	n Q@	d @U z
ber-	nard
bh @r	n Q@ d
ber-	nard's
bh @r	n Q@ d z
ber-	nat
bh @r	n V t
ber-	ner
bh @r	n @r
ber-	net
bh @r	n e t
ber-	ni
bh e@	n i:
ber-	ni-	ta
bh @r	n i:	t V
ber-	nice
bh @r	n i: s
ber-	nie
bh @r	n i:
ber-	nie's
bh @r	n i: z
ber-	noul-	li
bh @r	n u:	l i:
ber-	ny
bh @r	n i:
ber-	ra
bh e@	V
ber-	ra's
bh e@	V z
ber-	ri
bh e@	i:
ber-	ri-	er
bh e@	i:	@r
ber-	ri-	gan
bh e@	I	g V n
ber-	rie
bh e@	i:
ber-	ries
bh e@	i: z
ber-	ry
bh e@	i:
ber-	ry-	like
bh e@	i:	l aI k
ber-	ry-	man
bh e@	i:	m V n
ber-	ry's
bh e@	i: z
ber-	serk
bh @r	s @r k
ber-	ta
bh @r	t V
ber-	tel-	li
bh @r	t e	l i:
ber-	tels-	mann
bh @r	t V l	z m V n
ber-	tels-	mann's
bh @r	t V l	z m V n z
ber-	tha
bh @r	T V
ber-	ti
bh e@	t i:
ber-	tie
bh @r	t i:
ber-	tin
bh @r	t I n
ber-	to-	luc-	ci
bh @r	t @U	l u:	tS i:
ber-	told
bh @r	t @U l d
ber-	ton
bh @r	t V n
ber-	ty
bh @r	t i:
ber-	wick
bh @r	w I k
ber-	wyn
bh @r	w I n
bere
bh I@
beres
bh i: r z
beres-	ford
bh I@ z	f @r d
berg
bh @r g
berg-	hoff
bh @r g	h O: f
berg-	land
bh @r g	l { n d
berg-	lund
bh @r g	l V n d
berg-	man
bh @r g	m V n
berg-	mann
bh @r g	m V n
berg-	quist
bh @r g	k w I s t
berg-	ren
bh @r g	r e n
berge-	man
bh @r g	m V n
bergh
bh @r g
bergs
bh @r g z
berg's
bh @r g z
bergs-	ma
bh e@ g	z m V
bergs-	tein
bh @r g	s t aI n
bergs-	ten
bh @r g	s V n
bergs-	trom
bh @r g	s t r Q m
berk
bh @r k
berk-	ley
bh @r k	l i:
berk-	man
bh @r k	m V n
berk-	shire
bh @r k	S @r
berk-	shires
bh @r k	S I@ z
berke
bh @r k
berke-	ley
bh @r k	l i:
berke-	ley's
bh @r k	l i: z
berle
bh @r l
berm
bh @r m
bern
bh @r n
bern-	bach
bh @r n	b Q k
bern-	hard
bh @r n	h Q@ d
bern-	hardt
bh @r n	h Q@ t
berne
bh @r n
berns
bh @r n z
berns-	tein
bh @r n	s t aI n
berns-	tein's
bh @r n	s t i: n z
bernt
bh @r n t
bert
bh @r t
bert-	hold
bh @r	T @U l d
bert-	ram
bh @r t	r V m
bert-	rand
bh @r t	r V n d
berte
bh @r t
berth
bh @r T
berths
bh @r T s
bertsche
bh @r tS
bes
bh i: z
bes-	hore
bh e	S @r
bes-	peak
bh V s	p i: k
bes-	peaks
bh V s	p i: k s
bes-	pec-	ta-	cled
bh V s	p e k	t V	k V l d
bes-	se-	mer
bh e	s V	m @r
bes-	sie
bh e	s i:
bes-	sy
bh e	s i:
bes-	ted
bh e s	t V d
bes-	ter
bh e s	t @r
bes-	tia-	li-	ty
bh e s	tS I@	l I	t i:
bes-	tial
bh e s	tS V l
bes-	ting
bh e s	t I N
bes-	tow
bh V s	t @U
bes-	tow-	ing
bh V s	t @U	I N
bes-	towed
bh V s	t @U d
bes-	tows
bh V s	t @U z
bess
bh e s
besse
bh e s
best
bh e s t
best-	rode
bh V s	t r @U d
best-	sel-	ler
bh e s	t s e	l @r
best-	sel-	lers
bh e s	t s e	l @r z
best-	sel-	ling
bh e s	t s e	l I N
best's
bh e s t s
bet
bh e t
bet-	hune
bh V T	j u: n
bet-	ra-	yal
bh V t	r eI	V l
bet-	ra-	yals
bh V t	r eI	V l z
bet-	ra-	ying
bh V t	r eI	I N
bet-	ray
bh V t	r eI
bet-	rayed
bh V t	r eI d
bet-	rays
bh V t	r eI z
bet-	sey
bh e t	s i:
bet-	sy
bh e t	s i:
bet-	sy's
bh e t	s i: z
bet-	ta
bh e	t V
bet-	te
bh e	t i:
bet-	te-	ring
bh e	t @r	I N
bet-	ten-	court
bh e	t V n	k O@ t
bet-	ten-	dorf
bh e	t V n	d O@ f
bet-	ter
bh e	t @r
bet-	ter-	ment
bh e	t @r	m V n t
bet-	ter-	ton
bh e	t @r	t V n
bet-	tered
bh e	t @r d
bet-	ters
bh e	t @r z
bet-	ti
bh e	t i:
bet-	ti-	na
bh V	t i:	n V
bet-	ting
bh e	t I N
bet-	tor
bh e	t @r
bet-	tors
bh e	t @r z
bet-	ty
bh e	t i:
bet-	ty's
bh e	t i: z
bet-	ween
bh I t	w i: n
bet-	weens
bh I t	w i: n z
beth-	le-	hem's
bh e T	l V	h e m z
beth-	page
bh e T	p eI dZ
bets
bh e t s
bet's
bh e t s
bett
bh e t
betz
bh e t s
beu-	lah
bh j u:	l V
beu-	t-	ler
bh OI	t V	l @r
bev
bh e v
beve-	ra-	ges
bh e v	r I	dZ V z
bex-	ley
bh e k	s l i:
bey
bh eI
bha-	ra-	ta
bh Q@	Q	t V
bhak-	ta
bh Q k	t V
bhan-	gra
bh Q N	g r V
bhatt
bh { t
bho-	pal
bh @U	p Q l
bhu-	tan
bh u:	t { n
bhut-	to
bh u:	t @U
bhut-	to's
bh u:	t @U z
bi
bh aI
bi-	a-	gi
bh i:	Q	dZ i:
bi-	a-	lik
bh i:	Q	l I k
bi-	a-	ly
bh i:	Q	l i:
bi-	a-	mon-	te
bh i:	V	m O: n	t i:
bi-	a-	ses
bh aI	V	s V z
bi-	an-	ca
bh i:	Q N	k V
bi-	an-	chi
bh i:	Q n	tS i:
bi-	an-	chi-	ni
bh i:	Q n	tS i:	n i:
bi-	an-	co
bh i:	Q N	k @U
bi-	an-	nu-	al
bh aI	{	n u:	V l
bi-	as
bh aI	V s
bi-	ased
bh aI	V s t
bi-	ax-	i-	al
bh aI	{ k	s i:	V l
bi-	beau
bh I	b @U
bi-	bi
bh I	b i:
bi-	bi's
bh I	b i: z
bi-	ble
bh aI	b V l
bi-	bles
bh aI	b V l z
bi-	ble's
bh aI	b V l z
bi-	car-	bo-	nate
bh aI	k Q@	b V	n V t
bi-	cen-	te-	na-	ry
bh aI	s e n	t V	n e@	i:
bi-	cen-	ten-	ni-	al
bh aI	s e n	t e	n i:	V l
bi-	ceps
bh aI	s e p s
bi-	coas-	tal
bh I	k @U s	t V l
bi-	cus-	pid
bh aI	k V s	p I d
bi-	cus-	pids
bh aI	k V s	p I d z
bi-	cy-	c-	ling
bh aI	s I	k V	l I N
bi-	cy-	cle
bh aI	s I	k V l
bi-	cy-	cled
bh aI	s I	k V l d
bi-	cy-	cles
bh aI	s I	k V l z
bi-	cyc-	list
bh aI	s I k	l I s t
bi-	cyc-	lists
bh aI	s I k	l I s t s
bi-	den
bh aI	d V n
bi-	ding
bh aI	d I N
bi-	en-	ni-	al
bh aI	e	n i:	V l
bi-	fi-	da
bh I	f I	d V
bi-	fo-	cal
bh aI	f @U	k V l
bi-	fo-	cals
bh aI	f @U	k V l z
bi-	fur-	ca-	ted
bh I	f @r	k eI	t V d
bi-	fur-	ca-	tion
bh I	f @r	k eI	S V n
bi-	fur-	cate
bh I	f @r	k eI t
bi-	g-	ler
bh aI	g V	l @r
bi-	ge-	low
bh I	g V	l @U
bi-	ge-	low's
bh I	g V	l @U z
bi-	geyes
bh I	g aI z
bi-	go-	ted
bh I	g V	t V d
bi-	gos
bh i:	g @U z
bi-	got
bh I	g V t
bi-	got-	ry
bh I	g V t	r i:
bi-	gots
bh I	g V t s
bi-	ha-	ri
bh I	h Q@	i:
bi-	ker
bh aI	k @r
bi-	kers
bh aI	k @r z
bi-	ki-	ni
bh I	k i:	n i:
bi-	ki-	nis
bh V	k i:	n i: z
bi-	king
bh aI	k I N
bi-	ko
bh i:	k @U
bi-	la-	te-	ral
bh aI	l {	t @r	V l
bi-	la-	te-	ral-	ly
bh aI	l {	t @r	V	l i:
bi-	lek
bh I	l e k
bi-	li-	ous
bh I	l i:	V s
bi-	lic-	ki
bh V	l I t	s k i:
bi-	lin-	gua-	li-	sm
bh aI	l I N	g w V	l I	z V m
bi-	lin-	gual
bh aI	l I N	g w V l
bi-	lo-	xi
bh V	l V k	s i:
bi-	lo-	xi's
bh V	l V k	s i: z
bi-	low
bh I	l @U
bi-	na-	ry
bh aI	n @r	i:
bi-	na-	tio-	nal
bh aI	n {	S V	n V l
bi-	nette
bh I	n e t
bi-	no-	cu-	lar
bh V	n Q k	j V	l @r
bi-	no-	cu-	lars
bh V	n Q k	j V	l @r z
bi-	no-	mi-	al
bh aI	n @U	m i:	V l
bi-	o
bh aI	@U
bi-	o-	che-	mi-	cal
bh aI	@U	k e	m I	k V l
bi-	o-	che-	mist
bh aI	@U	k e	m I s t
bi-	o-	che-	mist-	ry
bh aI	@U	k e	m I s	t r i:
bi-	o-	cont-	rol
bh aI	V	k Q n	t r Q l
bi-	o-	deg-	ra-	da-	ble
bh aI	@U	d V g	r eI	d V	b V l
bi-	o-	di-	ver-	si-	ty
bh aI	@U	d aI	v @r	s I	t i:
bi-	o-	e-	thics
bh aI	@U	e	T I k s
bi-	o-	en-	gi-	neer
bh aI	@U	e n	dZ I	n I@
bi-	o-	en-	gi-	neered
bh aI	@U	e n	dZ I	n I@ d
bi-	o-	en-	gin-	ee-	ring
bh aI	@U	e n	dZ I	n I@	I N
bi-	o-	feed-	back
bh aI	@U	f i: d	b { k
bi-	o-	gen
bh aI	@U	dZ e n
bi-	o-	gen's
bh aI	@U	dZ e n z
bi-	o-	gra-	pher
bh aI	Q g	r V	f @r
bi-	o-	gra-	phers
bh aI	Q g	r V	f @r z
bi-	o-	gra-	phi-	cal
bh aI	V g	r {	f I	k V l
bi-	o-	gra-	phies
bh aI	Q g	r V	f i: z
bi-	o-	gra-	phy
bh aI	Q g	r V	f i:
bi-	o-	ha-	zard
bh aI	@U	h {	z @r d
)"
R"(bi-	o-	ha-	zards
bh aI	@U	h {	z @r d z
bi-	o-	lo-	gi-	cal
bh aI	V	l Q	dZ I	k V l
bi-	o-	lo-	gi-	cals
bh aI	V	l Q	dZ I	k V l z
bi-	o-	lo-	gic
bh aI	V	l Q	dZ I k
bi-	o-	lo-	gical-	ly
bh aI	V	l Q	dZ I k	l i:
bi-	o-	lo-	gics
bh aI	V	l Q	dZ I k s
bi-	o-	lo-	gist
bh aI	Q	l V	dZ V s t
bi-	o-	lo-	gists
bh aI	Q	l V	dZ V s t s
bi-	o-	lo-	gy
bh aI	Q	l V	dZ i:
bi-	o-	lo-	gy's
bh aI	Q	l V	dZ i: z
bi-	o-	ma-	te-	ri-	al
bh aI	@U	m V	t I@	i:	V l
bi-	o-	ma-	te-	ri-	als
bh aI	@U	m V	t I@	i:	V l z
bi-	o-	mass
bh aI	V	m { s
bi-	o-	me-	di-	cal
bh aI	@U	m e	d I	k V l
bi-	o-	phy-	sics
bh aI	@U	f I	s I k s
bi-	o-	safe-	ty
bh aI	@U	s eI f	t i:
bi-	o-	sci-	en-	ces
bh aI	O:	s i:	e n	s V z
bi-	o-	sci-	ence
bh aI	@U	s i:	V n s
bi-	o-	sen-	sor
bh aI	@U	s e n	s @r
bi-	o-	sen-	sors
bh aI	@U	s e n	s @r z
bi-	o-	sis
bh i:	@U	z I s
bi-	o-	tech
bh aI	@U	t e k
bi-	o-	tech-	no-	lo-	gi-	cal
bh aI	@U	t e k	n V	l Q	dZ I	k V l
bi-	o-	tech-	no-	lo-	gies
bh aI	@U	t e k	n Q	l V	dZ i: z
bi-	o-	tech-	no-	lo-	gy
bh aI	@U	t e k	n Q	l V	dZ i:
bi-	o-	tech-	no-	lo-	gy's
bh aI	@U	t e k	n Q	l V	dZ i: z
bi-	o-	techs
bh aI	@U	t e k s
bi-	o-	tin
bh aI	V	t V n
bi-	o-	tite
bh aI	V	t aI t
bi-	ome
bh aI	@U m
bi-	omes
bh aI	@U m z
bi-	on-	do
bh i:	@U n	d @U
bi-	op-	sies
bh aI	Q p	s i: z
bi-	op-	sy
bh aI	Q p	s i:
bi-	os
bh aI	@U s
bi-	os-	phere
bh aI	@U s	f I@
bi-	os-	pheres
bh aI	@U s	f I@ z
bi-	os-	phere's
bh aI	@U s	f I@ z
bi-	par-	ti-	san
bh aI	p Q@	t I	z V n
bi-	par-	ti-	san-	ship
bh aI	p Q@	t I	z V n	S I p
bi-	phe-	nyl
bh I	f V	n V l
bi-	phe-	nyls
bh I	f V	n V l z
bi-	po-	lar
bh aI	p @U	l @r
bi-	ra-	cial
bh aI	r eI	S V l
bi-	reme
bh aI	r i: m
bi-	remes
bh aI	r i: m z
bi-	ro
bh I@	@U
bi-	ron
bh aI	r V n
bi-	ros
bh aI	r @U z
bi-	se-	xu-	a-	li-	ty
bh aI	s e k	S u:	{	l I	t i:
bi-	se-	xu-	al
bh aI	s e k	S u:	V l
bi-	se-	xu-	als
bh aI	s e k	S u:	V l z
bi-	shop
bh I	S V p
bi-	shop-	rics
bh I	S V p	r I k s
bi-	shops
bh I	S V p s
bi-	shop's
bh I	S V p s
bi-	son
bh aI	s V n
bi-	ter
bh aI	t @r
bi-	ting
bh aI	t I N
bi-	tu-	men
bh I	t u:	m V n
bi-	tu-	mi-	nous
bh V	t u:	m V	n V s
bi-	valve
bh aI	v { l v
bi-	valves
bh aI	v { l v z
bi-	vins
bh I	v I n z
bi-	vouac
bh I v	w { k
bi-	week-	ly
bh aI	w i: k	l i:
bi-	zarre
bh V	z Q@
bib
bh I b
bib-	by
bh I	b i:
bib-	li-	cal
bh I b	l I	k V l
bib-	li-	o-	gra-	phies
bh I b	l i:	Q g	r V	f i: z
bib-	li-	o-	gra-	phy
bh I b	l i:	Q g	r V	f i:
bibb
bh I b
bibbs
bh I b z
bibs
bh I b z
bic
bh I k
bic-	ke-	ring
bh I	k @r	I N
bic-	ker
bh I	k @r
bic-	kered
bh I	k @r d
bic-	kers
bh I	k @r z
bice
bh aI s
bick
bh I k
bick-	more
bh I k	m O@
bick-	nell
bh I k	n V l
bid
bh I d
bid-	der
bh I	d @r
bid-	ders
bh I	d @r z
bid-	der's
bh I	d @r z
bid-	die
bh I	d i:
bid-	ding
bh I	d I N
bid-	dy
bh I	d i:
bid-	well
bh I d	w e l
bidd-	le
bh I	d V l
bidd-	le's
bh I	d V l z
bide
bh aI d
bids
bh I d z
bid's
bh I d z
bie-	bel
bh i:	b V l
bie-	ber
bh i:	b @r
bie-	der-	mann
bh aI	d @r	m V n
bie-	der-	meier
bh i:	d @r	m aI r
bie-	gel
bh i:	g V l
bie-	la
bh i:	l V
bie-	le-	feld
bh i:	l V	f e l d
biel
bh i: l
biel-	by
bh i: l	b i:
bien
bh i: n
bien-	na-	le
bh i:	e	n eI l
bien-	ve-	nu
bh V n	v e	n u:
bien-	ve-	nue
bh V n	v eI n	w e
bier
bh i: r
bier-	man
bh I@	m V n
bier-	nat
bh I@	n { t
bierce
bh I@ s
biers
bh i: r z
biff
bh I f
big
bh I g
big-	foot
bh I g	f U t
big-	ford
bh I g	f @r d
big-	ger
bh I	g @r
big-	gest
bh I	g V s t
big-	gie
bh I	g i:
big-	gies
bh I	g i: z
big-	gins
bh I	g I n z
big-	horn
bh I g	h O@ n
big-	horns
bh I g	h O@ n z
big-	low
bh I g	l @U
big-	ness
bh I g	n V s
big-	time
bh I g	t aI m
big-	wig
bh I g	w I g
big-	wigs
bh I g	w I g z
biggs
bh I g z
bigs
bh I g z
bike
bh aI k
biked
bh aI k t
bikes
bh aI k s
bil
bh I l
bil-	bao
bh I l	b aU
bil-	bo
bh I l	b @U
bil-	by
bh I l	b i:
bil-	king
bh I l	k I N
bil-	la-	ble
bh I	l V	b V l
bil-	lan-	court
bh I	l V n	k O@ t
bil-	lard
bh V	l Q@ d
bil-	le-	ri-	ca
bh I	l @r	i:	k V
bil-	le-	ter
bh I	l i:	t @r
bil-	ler
bh I	l @r
bil-	let
bh I	l V t
bil-	lets
bh I	l V t s
bil-	li-	ton
bh I	l I	t V n
bil-	liard
bh I l	j @r d
bil-	liards
bh I l	j @r d z
bil-	lie
bh I	l i:
bil-	lin-	gham
bh I	l I N	h { m
bil-	ling
bh I	l I N
bil-	lings
bh I	l I N z
bil-	lings-	ley
bh I	l I N	z l i:
bil-	lio-	naire
bh I l	j V	n e@
bil-	lio-	naires
bh I l	j V	n e@ z
bil-	lion
bh I l	j V n
bil-	lions
bh I l	j V n z
bil-	lionth
bh I l	j V n T
bil-	lionths
bh I l	j V n T s
bil-	lon
bh I	l V n
bil-	low
bh I	l @U
bil-	low-	ing
bh I	l @U	I N
bil-	lowed
bh I	l @U d
bil-	lows
bh I	l @U z
bil-	ly
bh I	l i:
bil-	ly's
bh I	l i: z
bile
bh aI l
biles
bh aI l z
bilk
bh I l k
bilked
bh I l k t
bill
bh I l
bill-	board
bh I l	b O@ d
bill-	boards
bh I l	b O@ d z
bill-	board's
bh I l	b O@ d z
bill-	fold
bh I l	f @U l d
bill-	man
bh I l	m V n
bille
bh aI l
billed
bh I l d
bills
bh I l z
bill's
bh I l z
bils-	ki
bh I l	s k i:
bilt-	more
bh I l	t m O@
bin-	der
bh aI n	d @r
bin-	ders
bh aI n	d @r z
bin-	ding
bh aI n	d I N
bin-	dle
bh I n	d V l
bin-	dles
bh I n	d V l z
bin-	ford
bh I n	f @r d
bin-	ger
bh I	N @r
bin-	ges
bh I n	dZ V z
bin-	ging
bh I N	g I N
bin-	go
bh I N	g @U
bin-	nie
bh I	n i:
bin-	ning
bh I	n I N
bind
bh aI n d
binds
bh aI n d z
bines
bh aI n z
bing
bh I N
bing-	ham
bh I	N V m
bing-	ham-	ton
bh I	N V m	t V n
bing-	le
bh I N	g V l
binge
bh I n dZ
bink
bh I N k
bins
bh I n z
bip-	lane
bh aI p	l eI n
bip-	pus
bh I	p V s
bir-	chard
bh @r	k @r d
bir-	cher
bh @r	tS @r
bir-	ch's
bh @r	tS V z
bir-	der
bh @r	d @r
bir-	ders
bh @r	d @r z
bir-	die
bh @r	d i:
bir-	died
bh @r	d i: d
bir-	dy
bh @r	d i:
bir-	kett
bh @r	k V t
bir-	khead
bh @r k	h e d
bir-	ky
bh @r	k i:
bir-	man
bh @r	m V n
bir-	ming-	ham
bh @r	m I N	h { m
bir-	ney
bh @r	n i:
bir-	thing
bh @r	T I N
birch
bh @r tS
bird
bh @r d
bird-	cage
bh @r d	k eI dZ
bird-	life
bh @r d	l aI f
bird-	man
bh @r d	m { n
bird-	sall
bh @r d	z O: l
bird-	song
bh @r d	s O: N
birds
bh @r d z
bird's
bh @r d z
birk
bh @r k
birk-	ner
bh @r k	n @r
birks
bh @r k s
birle
bh @r l
birr
bh @r
birt
bh @r t
birth
bh @r T
birth-	day
bh @r T	d eI
birth-	days
bh @r T	d eI z
birth-	mark
bh @r T	m Q@ k
birth-	marks
bh @r T	m Q@ k s
birth-	place
bh @r T	p l eI s
birth-	rate
bh @r T	r eI t
birth-	rates
bh @r T	r eI t s
birth-	right
bh @r T	r aI t
births
bh @r T s
bis
bh I s
bis-	bee
bh I s	b i:
bis-	cayne
bh I s	k eI n
bis-	coe
bh I s	k @U
bis-	cuit
bh I s	k I t
bis-	cuits
bh I s	k I t s
bis-	marck
bh I z	m Q@ k
bis-	marck's
bh I z	m Q@ k s
bis-	mark
bh I z	m Q@ k
bis-	muth
bh I z	m V T
bis-	sell
bh I	s V l
bis-	set
bh I	s I t
bis-	so
bh i:	s @U
bis-	son
bh I	s V n
bise
bh aI z
bish
bh I S
bisque
bh I s k
bist-	ro
bh I s	t r @U
bit
bh I t
bit-	ches
bh I	tS V z
bit-	chy
bh I	tS i:
bit-	sy
bh I t	s i:
bit-	te-	rest
bh I	t @r	V s t
bit-	ten
bh I	t V n
bit-	ter
bh I	t @r
bit-	ter-	ly
bh I	t @r	l i:
bit-	ter-	ness
bh I	t @r	n V s
bit-	ter-	root
bh I	t @r	r u: t
bit-	ters
bh I	t @r z
bit-	ters-	weet
bh I	t @r s	w i: t
bit-	tin-	ger
bh I	t I	N @r
bit-	ting
bh I	t I N
bit-	ty
bh I	t i:
bitch
bh I tS
bite
bh aI t
bite-	size
bh I t	s aI z
bites
bh aI t s
bits
bh I t s
bitt-	ner
bh I t	n @r
bix
bh I k s
bix-	by
bh I k	s b i:
bix-	ler
bh I k	s l @r
biz
bh I z
bjork
bh j O@ k
bjorn
bh j O@ n
bla-	ded
bh l eI	d V d
bla-	den
bh l eI	d V n
bla-	ding
bh l eI	d I N
bla-	key
bh l eI	k i:
bla-	lock
bh l {	l Q k
bla-	ming
bh l eI	m I N
bla-	si-	a
bh l Q	s i:	V
bla-	si-	us
bh l eI	s i:	V s
bla-	sin-	ga-	me
bh l Q	s I N	g Q	m i:
bla-	tant
bh l eI	t V n t
bla-	tant-	ly
bh l eI	t V n	t l i:
bla-	ther
bh l {	D @r
bla-	zer
bh l eI	z @r
bla-	zers
bh l eI	z @r z
bla-	zes
bh l eI	z V z
bla-	zing
bh l eI	z I N
blac-	ke-	ning
bh l {	k V	n I N
blac-	ken
bh l {	k V n
blac-	kened
bh l {	k V n d
blac-	kens
bh l {	k V n z
blac-	ker
bh l {	k @r
blac-	kest
bh l {	k V s t
blac-	kett
bh l {	k I t
blach-	ly
bh l Q tS	l i:
black
bh l { k
black-	ball
bh l { k	b O: l
black-	ber-	ries
bh l { k	b e@	i: z
black-	ber-	ry
bh l { k	b e@	i:
black-	bird
bh l { k	b @r d
black-	birds
bh l { k	b @r d z
black-	board
bh l { k	b O@ d
black-	boards
bh l { k	b O@ d z
black-	burn
bh l { k	b @r n
black-	foot
bh l { k	f U t
black-	ford
bh l { k	f @r d
black-	hawk
bh l { k	h O: k
black-	hawk's
bh l { k	h O: k s
black-	heath
bh l { k	h i: T
black-	jack
bh l { k	dZ { k
black-	lis-	ted
bh l { k	l I s	t V d
black-	lis-	ting
bh l { k	l I s	t I N
black-	list
bh l { k	l I s t
black-	mail
bh l { k	m eI l
black-	mailed
bh l { k	m eI l d
black-	well
bh l { k	w e l
black-	wood
bh l { k	w U d
blacked
bh l { k t
blad-	der
bh l {	d @r
blad-	ders
bh l {	d @r z
blade
bh l eI d
blades
bh l eI d z
blagg
bh l { g
blah
bh l Q
blain
bh l eI n
blaine
bh l eI n
blair
bh l e@
blair's
bh l e@ z
blais-	dell
bh l eI s	d V l
blaise
bh l eI z
blaize
bh l eI z
blake
bh l eI k
blake-	ley
bh l eI k	l i:
blake-	ley's
bh l eI k	l i: z
blake-	ly
bh l eI k	l i:
blake-	ly's
bh l eI k	l i: z
blake-	more
bh l eI k	m O@
blake's
bh l eI k s
blakes-	lee
bh l eI k	s l i:
blame
bh l eI m
blame-	less
bh l eI m	l V s
blamed
bh l eI m d
blames
bh l eI m z
blan
bh l { n
blan-	ca
bh l Q N	k V
blan-	chard
bh l { n	tS @r d
blan-	chard's
bh l { n	tS @r d z
blan-	chette
bh l V n	S e t
blan-	co
bh l { N	k @U
blan-	da
bh l { n	d V
blan-	der
bh l { n	d @r
blan-	ding
bh l { n	d I N
blan-	dish-	ment
bh l { n	d I S	m V n t
blan-	dish-	ments
bh l { n	d I S	m V n t s
blan-	don
bh l { n	d V n
blan-	ford
bh l { n	f @r d
blan-	ke-	ted
bh l { N	k V	t V d
blan-	ke-	ting
bh l { N	k V	t I N
blan-	ken-	ship
bh l { N	k V n	S I p
blan-	ket
bh l { N	k V t
blan-	kets
bh l { N	k V t s
blan-	king
bh l { N	k I N
blan-	ton
bh l { n	t V n
blanc
bh l { N k
blanch
bh l { n tS
blanche
bh l { n tS
bland
bh l { n d
bland-	ford
bh l { n	d f O@ d
bland-	ly
bh l { n	d l i:
bland-	ness
bh l { n	d n V s
blane
bh l eI n
blank
bh l { N k
blank-	ly
bh l { N	k l i:
blanked
bh l { N k t
blanks
bh l { N k s
blar-	ing
bh l e@	I N
blare
bh l e@
blared
bh l e@ d
blares
bh l e@ z
blas
bh l Q s
blas-	co
bh l Q s	k @U
blas-	dell
bh l { s	d V l
blas-	phe-	mous
bh l { s	f V	m V s
blas-	phe-	my
bh l { s	f V	m i:
blas-	ted
bh l { s	t V d
blas-	ter
bh l { s	t @r
blas-	ting
bh l { s	t I N
blas-	toff
bh l { s	t O: f
blase
bh l eI z
blast
bh l { s t
blast-	off
bh l { s	t O: f
blasts
bh l { s t s
blat-	ter
bh l {	t @r
blatt
bh l { t
blatz
bh l { t s
blau
bh l aU
blau-	velt
bh l aU	v e l t
blay
bh l eI
blay-	don
bh l eI	d V n
blayne
bh l eI n
blayze
bh l eI z
blaze
bh l eI z
blazed
bh l eI z d
ble-	gen
bh l e	g V n
ble-	mi-	shes
bh l e	m I	S V z
ble-	mish
bh l e	m I S
ble-	mished
bh l e	m I S t
ble-	vins
bh l e	v I n z
blea
bh l i:
blea-	cher
bh l i:	tS @r
blea-	chers
bh l i:	tS @r z
blea-	ching
bh l i:	tS I N
blea-	ker
bh l i:	k @r
blea-	kest
bh l i:	k V s t
blea-	ry
bh l I@	i:
bleach
bh l i: tS
bleached
bh l i: tS t
bleak
bh l i: k
bleak-	ness
bh l i: k	n V s
blech
bh l e k
bleck
bh l e k
bled
bh l e d
bled-	soe
bh l e d	s @U
blee-	ding
bh l i:	d I N
blee-	ker
bh l i:	k @r
blee-	ping
bh l i:	p I N
bleed
bh l i: d
bleeds
bh l i: d z
bleep
bh l i: p
blei-	er
bh l aI	@r
blen-	da
bh l e n	d V
blen-	ded
bh l e n	d V d
blen-	der
bh l e n	d @r
blen-	ders
bh l e n	d @r z
blen-	ding
bh l e n	d I N
blen-	heim
bh l e n	h aI m
blend
bh l e n d
blends
bh l e n d z
bles-	ses
bh l e	s V z
bles-	sing
bh l e	s I N
bles-	sing-	ton
bh l e	s I N	t V n
bles-	sings
bh l e	s I N z
bless
bh l e s
blessed
bh l e s t
blest
bh l e s t
bleu
bh l u:
blew
bh l u:
bley
bh l eI
blick
bh l I k
bligh
bh l aI
bligh-	ted
bh l aI	t V d
blight
bh l aI t
blimp
bh l I m p
blimps
bh l I m p s
blin-	ded
bh l aI n	d V d
blin-	der
bh l aI n	d @r
blin-	ders
bh l aI n	d @r z
blin-	der's
bh l aI n	d @r z
blin-	ding
bh l aI n	d I N
blin-	king
bh l I N	k I N
blind
bh l aI n d
blind-	fol-	ded
bh l aI n	d f @U l	d V d
blind-	fold
bh l aI n	d f @U l d
blind-	ly
bh l aI n	d l i:
blind-	ness
bh l aI n	d n V s
blind-	si-	ded
bh l aI n	d s aI	d V d
blind-	side
bh l aI n	d s aI d
blinds
bh l aI n d z
blink
bh l I N k
blinked
bh l I N k t
blinks
bh l I N k s
blinn
bh l I n
blip
bh l I p
blips
bh l I p s
blis-	te-	ring
bh l I s	t @r	I N
blis-	ter
bh l I s	t @r
blis-	tered
bh l I s	t @r d
blis-	ters
bh l I s	t @r z
bliss
bh l I s
bliss-	ful
bh l I s	f V l
bliss-	ful-	ly
bh l I s	f V	l i:
blit-	zer
bh l I t	z @r
blit-	zes
bh l I t	s V z
blithe
bh l aI D
blithe-	ly
bh l aI T	l i:
blitz
bh l I t s
blitzed
bh l I t s t
blitzk-	rieg
bh l I t	s k r i: g
bliz-	zard
bh l I	z @r d
bliz-	zards
bh l I	z @r d z
blo-	wer
bh l @U	@r
blo-	wers
bh l @U	@r z
blo-	wy
bh l @U	i:
bloa-	ted
bh l @U	t V d
bloa-	ting
bh l @U	t I N
bloat
bh l @U t
blob
bh l Q b
blob-	by
bh l Q	b i:
blobs
bh l Q b z
bloc
bh l Q k
bloc-	ka-	ded
bh l Q	k eI	d V d
bloc-	ka-	ding
bh l Q	k eI	d I N
bloc-	ka-	ges
bh l Q	k I	dZ V z
bloc-	kade
bh l Q	k eI d
bloc-	kades
bh l Q	k eI d z
bloc-	kage
bh l Q	k I dZ
bloc-	ker
bh l Q	k @r
bloc-	kers
bh l Q	k @r z
bloc-	king
bh l Q	k I N
bloch
bh l Q k
bloch's
bh l Q k s
block
bh l Q k
block-	bus-	ter
bh l Q k	b V s	t @r
block-	bus-	ters
bh l Q k	b V s	t @r z
block-	bus-	ter's
bh l Q k	b V s	t @r z
blocked
bh l Q k t
blocks
bh l Q k s
block's
bh l Q k s
blocs
bh l Q k s
bloc's
bh l Q k s
blod-	gett
bh l Q	dZ V t
bloem
bh l @U m
blok
bh l Q k
bloke
bh l @U k
blokes
bh l @U k s
blom-	berg
bh l Q m	b @r g
blom-	quist
bh l Q m	k w I s t
blon-	dell
bh l Q n	d V l
blon-	der
bh l Q n	d @r
blon-	die
bh l Q n	d i:
blon-	din
bh l Q n	d I n
blond
bh l Q n d
blonde
bh l Q n d
blondes
bh l Q n d z
blonde's
bh l Q n d z
blonds
bh l Q n d z
bloo-	ded
bh l V	d V d
bloo-	di-	er
bh l V	d i:	@r
bloo-	di-	est
bh l V	d i:	V s t
bloo-	died
bh l V	d i: d
bloo-	dy
bh l V	d i:
bloo-	mer
bh l u:	m @r
bloo-	mers
bh l u:	m @r z
bloo-	ming
bh l u:	m I N
bloo-	ming-	dale
bh l u:	m I N	d eI l
bloo-	ming-	dale's
bh l u:	m I N	d eI l z
bloo-	ming-	ton
bh l u:	m I N	t V n
bloo-	per
bh l u:	p @r
bloo-	pers
bh l u:	p @r z
blood
bh l V d
blood-	bath
bh l V d	b { T
blood-	hound
bh l V d	h aU n d
blood-	hounds
bh l V d	h aU n d z
blood-	less
bh l V d	l V s
blood-	let-	ting
bh l V d	l e	t I N
blood-	line
bh l V d	l aI n
blood-	lines
bh l V d	l aI n z
blood-	shed
bh l V d	S e d
blood-	stain
bh l V d	s t eI n
blood-	stained
bh l V d	s t eI n d
blood-	stains
bh l V d	s t eI n z
blood-	stone
bh l V d	s t @U n
blood-	stream
bh l V d	s t r i: m
blood-	suc-	ker
bh l V d	s V	k @r
blood-	suc-	kers
bh l V d	s V	k @r z
blood-	suc-	king
bh l V d	s V	k I N
blood-	thirs-	ty
bh l V d	T @r s	t i:
bloods
bh l V d z
blood's
bh l V d z
bloom
bh l u: m
bloom-	field
bh l u: m	f i: l d
bloomed
bh l u: m d
blooms
bh l u: m z
bloom's
bh l u: m z
blos-	so-	ming
bh l Q	s V	m I N
blos-	som
bh l Q	s V m
blos-	somed
bh l Q	s V m d
blos-	soms
bh l Q	s V m z
blot
bh l Q t
blot-	ter
bh l Q	t @r
blots
bh l Q t s
blou-	ses
bh l aU	s V z
blount
bh l aU n t
blouse
bh l aU s
blow
bh l @U
blow-	fish
bh l @U	f I S
blow-	ing
bh l @U	I N
blow-	out
bh l @U	aU t
blow-	outs
bh l @U	aU t s
blow-	torch
bh l @U	t O@ tS
blow-	up
bh l @U	V p
blowed
bh l @U d
blown
bh l @U n
blows
bh l @U z
blox-	om
bh l Q k	s V m
blu-	er
bh l u:	@r
blu-	est
bh l u:	V s t
blu-	ey
bh l u:	i:
blu-	ford
bh l u:	f @r d
blu-	ing
bh l u:	I N
blu-	ish
bh l u:	I S
blu-	men-	feld
bh l V	m V n	f e l d
blu-	men-	thal
bh l u:	m V n	T O: l
blu-	shes
bh l V	S V z
blu-	shing
bh l V	S I N
blub-	ber
bh l V	b @r
blud-	geo-	ning
bh l V	dZ V	n I N
blud-	geon
bh l V	dZ V n
blud-	geoned
bh l V	dZ V n d
blue
bh l u:
blue-	ber-	ries
bh l u:	b e@	i: z
blue-	ber-	ry
bh l u:	b e@	i:
blue-	bird
bh l u:	b @r d
blue-	bon-	net
bh l u:	b Q	n V t
blue-	bon-	nets
bh l u:	b Q	n V t s
blue-	chip
bh l u:	tS I p
blue-	field
bh l u:	f i: l d
blue-	grass
bh l u: g	r { s
blue-	jay
bh l u:	dZ eI
blue-	print
bh l u: p	r I n t
blue-	prints
bh l u: p	r I n t s
blue-	stone
bh l u: s	t @U n
blues
bh l u: z
blue's
bh l u: z
bluf-	fing
bh l V	f I N
bluff
bh l V f
bluffed
bh l V f t
bluffs
bh l V f s
bluhm
bh l V m
blum
bh l u: m
blume
bh l u: m
blun-	de-	ring
bh l V n	d @r	I N
blun-	dell
bh l V n	d V l
blun-	der
bh l V n	d @r
blun-	dered
bh l V n	d @r d
blun-	ders
bh l V n	d @r z
blun-	ted
bh l V n	t V d
blun-	ter
bh l V n	t @r
blun-	test
bh l V n	t V s t
blun-	ting
bh l V n	t I N
blunk
bh l V N k
blunt
bh l V n t
)"
R"(blunt-	ly
bh l V n	t l i:
blunt-	ness
bh l V n	t n V s
blunts
bh l V n t s
blur
bh l @r
blur-	ring
bh l @r	I N
blur-	ry
bh l @r	i:
blur-	ted
bh l @r	t V d
blurb
bh l @r b
blurbs
bh l @r b z
blurred
bh l @r d
blurs
bh l @r z
blurt
bh l @r t
blurts
bh l @r t s
blus-	te-	ry
bh l V s	t @r	i:
blus-	ter
bh l V s	t @r
blus-	ter-	ing
bh l V s	t @r	I N
blush
bh l V S
blushed
bh l V S t
bly
bh l aI
bo
bh @U
bo-	as
bh @U	V z
bo-	az
bh @U	{ z
bo-	ba-	dil-	la
bh @U	b Q	d I	l V
bo-	bak
bh @U	b V k
bo-	bo
bh @U	b @U
bo-	ca
bh @U	k V
bo-	ches
bh Q	tS V z
bo-	cock
bh Q	k V k
bo-	de-	gas
bh @U	d eI	g V s
bo-	den
bh @U	d V n
bo-	di
bh @U	d i:
bo-	di-	ly
bh Q	d I	l i:
bo-	di-	ne
bh @U	d i:	n i:
bo-	died
bh Q	d i: d
bo-	dies
bh Q	d i: z
bo-	do
bh @U	d @U
bo-	dy
bh Q	d i:
bo-	dy-	guard
bh Q	d i:	g Q@ d
bo-	dy-	guards
bh Q	d i:	g Q@ d z
bo-	dy's
bh Q	d i: z
bo-	for-	s's
bh @U	f @r	z V z
bo-	fors
bh @U	f @r z
bo-	gan
bh @U	g V n
bo-	gard
bh Q	g @r d
bo-	gart
bh @U	g Q@ t
bo-	gey
bh @U	g i:
bo-	gey-	man
bh @U	g i:	m { n
bo-	gey-	men
bh @U	g i:	m I n
bo-	geyed
bh @U	g i: d
bo-	gie
bh U	g i:
bo-	go-	sian
bh V	g Q	Z V n
bo-	go-	ta
bh @U	g V	t Q
bo-	gor
bh @U	g O@
bo-	gus
bh @U	g V s
bo-	gusz
bh Q	g I S
bo-	han-	non
bh Q	h V	n Q n
bo-	he-	me
bh @U	h eI	m eI
bo-	he-	mi-	a
bh @U	h i:	m i:	V
bo-	he-	mi-	an
bh @U	h i:	m i:	V n
bo-	hon
bh @U	h V n
bo-	kas-	sa
bh V	k Q	s V
bo-	la
bh @U	l V
bo-	lan
bh @U	l V n
bo-	lan-	ger
bh @U	l V n	dZ @r
bo-	land
bh @U	l V n d
bo-	lar
bh @U	l @r
bo-	le-	ro
bh @U	l e@	@U
bo-	len
bh @U	l V n
bo-	ley
bh @U	l i:
bo-	li-	tho
bh @U	l I	T V
bo-	li-	var
bh Q	l I	v @r
bo-	li-	vars
bh Q	l I	v @r z
bo-	li-	vi-	a
bh V	l I	v i:	V
bo-	li-	vi-	an
bh @U	l I	v i:	V n
bo-	li-	vi-	a's
bh V	l I	v i:	V z
bo-	lin-	ger
bh @U	l I	N @r
bo-	ling
bh @U	l I N
bo-	log-	na
bh V	l @U	n i:
bo-	log-	ne-	se
bh @U	l @U g	n eI	z i:
bo-	lus
bh @U	l V s
bo-	na
bh @U	n V
bo-	na-	fide
bh Q	n V	f aI d
bo-	na-	parte
bh @U	n V	p Q@ t
bo-	na-	parte's
bh @U	n V	p Q@ t s
bo-	na-	ven-	tu-	ra
bh @U	n Q	v e n	t U@	V
bo-	na-	ven-	ture
bh Q	n V	v e n	tS @r
bo-	nac-	ci
bh @U	n Q	tS i:
bo-	nan-	za
bh V	n { n	z V
bo-	nar
bh @U	n @r
bo-	ner
bh @U	n @r
bo-	ney
bh @U	n i:
bo-	ni
bh @U	n i:
bo-	ni-	fay
bh Q	n I	f eI
bo-	ni-	ne
bh @U	n i:	n i:
bo-	ni-	ta
bh @U	n i:	t V
bo-	ni-	to
bh V	n i:	t @U
bo-	nier
bh Q n	j @r
bo-	nil-	la
bh V	n I	l V
bo-	nin
bh @U	n I n
bo-	ning
bh @U	n I N
bo-	no
bh @U	n @U
bo-	no-	bos
bh Q	n Q	b @U z
bo-	nu-	ses
bh @U	n V	s V z
bo-	num
bh Q	n V m
bo-	nus
bh @U	n V s
bo-	ny
bh @U	n i:
bo-	peep
bh @U	p i: p
bo-	phu-	thats-	wa-	na
bh @U	f u:	T Q t	s w Q	n V
bo-	ra
bh O@	V
bo-	rah
bh O@	V
bo-	rak
bh O@	V k
bo-	ral
bh O@	V l
bo-	rax
bh O@	{ k s
bo-	re-	a-	lis
bh O@	i:	{	l I s
bo-	rek
bh O@	I k
bo-	rel
bh O@	V l
bo-	rer
bh O@	@r
bo-	ric
bh O@	I k
bo-	ring
bh O@	I N
bo-	ris
bh O@	I s
bo-	ro
bh @r	@U
bo-	ron
bh O@	Q n
bo-	rough
bh @r	@U
bo-	roughs
bh @r	@U z
bo-	rough's
bh @r	@U z
bo-	rup
bh O@	V p
bo-	s-	ler
bh Q	s V	l @r
bo-	ser
bh @U	z @r
bo-	sher
bh Q	S @r
bo-	som
bh U	z V m
bo-	ta-	ni-	cal
bh V	t {	n I	k V l
bo-	ta-	ni-	cal-	ly
bh V	t {	n V	k V	l i:
bo-	ta-	nic
bh V	t {	n I k
bo-	ta-	nist
bh Q	t V	n V s t
bo-	ta-	nists
bh Q	t V	n V s t s
bo-	ta-	ny
bh Q	t V	n i:
bo-	te-	ler
bh Q	t V	l @r
bo-	tha
bh Q	T V
bo-	tham
bh Q	T V m
bo-	tham's
bh Q	T V m z
bo-	tha's
bh Q	T V z
bo-	the-	ring
bh Q	D @r	I N
bo-	thell
bh Q	T V l
bo-	ther
bh Q	D @r
bo-	ther-	some
bh Q	D @r	s V m
bo-	thered
bh Q	D @r d
bo-	thers
bh Q	D @r z
bo-	tos
bh @U	t @U z
bo-	tu-	li-	sm
bh Q	tS u:	l I	z V m
bo-	uil-	lon
bh u:	w I	l V n
bo-	vard
bh V	v Q@ d
bo-	vey
bh @U	v i:
bo-	vine
bh @U	v aI n
bo-	we-	ry
bh aU	@r	i:
bo-	we-	ry's
bh aU	@r	i: z
bo-	wel
bh aU	V l
bo-	well
bh Q	w e l
bo-	wels
bh aU	V l z
bo-	wen
bh @U	V n
bo-	wer
bh aU	@r
bo-	wer-	man
bh @U	@r	m V n
bo-	wers
bh aU	@r z
bo-	wie
bh @U	i:
bo-	wing
bh @U	I N
bo-	xer
bh Q k	s @r
bo-	xers
bh Q k	s @r z
bo-	xer's
bh Q k	s @r z
bo-	xes
bh Q k	s V z
bo-	xing
bh Q k	s I N
bo-	xing's
bh Q k	s I N z
bo-	xy
bh Q k	s i:
bo-	yar
bh @U	j Q@
bo-	yer
bh OI	@r
bo-	yers
bh OI	@r z
bo-	yish
bh OI	I S
bo-	za
bh @U	z V
bo-	zo
bh @U	z @U
bo-	zos
bh @U	z @U z
boa-	ted
bh @U	t V d
boa-	ters
bh @U	t @r z
boa-	ting
bh @U	t I N
board
bh O@ d
board-	walk
bh O@ d	w O: k
boart
bh O@ t
boas-	ted
bh @U s	t V d
boas-	ting
bh @U s	t I N
boast
bh @U s t
boast-	ful
bh @U s	t f V l
boasts
bh @U s t s
boat
bh @U t
boat-	house
bh @U t	h aU s
boat-	lift
bh @U t	l I f t
boat-	lifts
bh @U t	l I f t s
boat-	load
bh @U t	l @U d
boat-	loads
bh @U t	l @U d z
boat-	man
bh @U t	m V n
boat-	wright
bh @U t	r aI t
boat-	yard
bh @U t	j Q@ d
boats
bh @U t s
boat's
bh @U t s
bob
bh Q b
bob-	ber
bh Q	b @r
bob-	bette
bh Q	b V t
bob-	bi
bh Q	b i:
bob-	bie
bh Q	b i:
bob-	bin
bh Q	b I n
bob-	bing
bh Q	b I N
bob-	bitt
bh Q	b I t
bob-	bitts
bh Q	b I t s
bob-	bitt's
bh Q	b I t s
bob-	by
bh Q	b i:
bob-	by's
bh Q	b i: z
bob-	cat
bh Q b	k { t
bob-	cats
bh Q b	k { t z
bob-	row
bh Q b	r @U
bob's
bh Q b z
bobs-	led
bh Q b	s l e d
boc-	ce
bh @U	tS i:
boc-	cia
bh @U	tS V
boche
bh Q tS
bock
bh Q k
bod-	kin
bh Q d	k I n
bod-	kins
bh Q d	k I n z
bod-	le
bh @U	d V l
bod-	ley
bh Q d	l i:
bod-	nar
bh V d	n Q@
bod-	well
bh Q d	w e l
bode
bh @U d
bodes
bh @U d z
boe
bh @U
boe-	ing
bh @U	I N
boe-	ing's
bh @U	I N z
boeh-	mer
bh @U	m @r
boehm
bh @U m
boehme
bh @U m
boeke
bh @U k
boel-	ter
bh @U l	t @r
boer
bh O@
boers
bh O@ z
boesch
bh @U S
boett-	ner
bh @U t	n @r
bof-	fa
bh Q	f V
bof-	fo
bh O:	f @U
boff
bh O: f
bog
bh Q g
bog-	g-	ling
bh Q	g V	l I N
bog-	ging
bh O:	g I N
bog-	gle
bh Q	g V l
bog-	gled
bh Q	g V l d
bog-	gles
bh Q	g V l z
bog-	le
bh @U	g V l
bogged
bh Q g d
boggs
bh O: g z
bogs
bh Q g z
bogue
bh @U g
boh-	len
bh @U	l V n
boh-	lin
bh @U	l I n
boh-	man
bh @U	m V n
boh-	ner
bh @U	n @r
boh-	rer
bh O@	@r
bohm
bh Q m
bohr
bh O@
boi-	leau
bh OI	l @U
boi-	ler
bh OI	l @r
boi-	ler-	ma-	ker
bh OI	l @r	m eI	k @r
boi-	ler-	plate
bh OI	l @r p	l eI t
boi-	lers
bh OI	l @r z
boi-	ling
bh OI	l I N
boi-	se
bh OI	z i:
boi-	se's
bh OI	z i: z
boice
bh OI s
boies
bh OI z
boil
bh OI l
boiled
bh OI l d
boils
bh OI l z
bois
bh w Q
bois-	seau
bh w Q	s @U
bois-	te-	rous
bh OI s	t @r	V s
bok
bh Q k
bol
bh Q l
bol-	den
bh @U l	d V n
bol-	der
bh @U l	d @r
bol-	dest
bh @U l	d V s t
bol-	din
bh @U l	d I n
bol-	ding
bh @U l	d I N
bol-	ger
bh @U l	dZ @r
bol-	ger's
bh @U l	dZ @r z
bol-	land
bh Q	l V n d
bol-	lard
bh Q	l @r d
bol-	len
bh Q	l V n
bol-	ler
bh Q	l @r
bol-	lin-	ger
bh Q	l I	N @r
bol-	ling
bh @U	l I N
bol-	she-	vi-	sm
bh @U l	S V	v I	z V m
bol-	she-	vik
bh @U l	S V	v I k
bol-	she-	viks
bh @U l	S V	v I k s
bol-	she-	vist
bh @U l	S I	v I s t
bol-	shoi
bh @U l	S OI
bol-	shoi's
bh @U l	S OI z
bol-	son
bh @U l	s V n
bol-	ted
bh @U l	t V d
bol-	ten
bh @U l	t V n
bol-	ter
bh @U l	t @r
bol-	ting
bh @U l	t I N
bol-	ton
bh @U l	t V n
bold
bh @U l d
bold-	face
bh @U l	d f eI s
bold-	ly
bh @U l	d l i:
bold-	ness
bh @U l	d n V s
bolds
bh @U l d z
bole
bh @U l
boles
bh @U l z
boll
bh @U l
bolls
bh @U l z
bols-	te-	ring
bh @U l	s t @r	I N
bols-	ter
bh @U l	s t @r
bols-	tered
bh @U l	s t @r d
bols-	ters
bh @U l	s t @r z
bolt
bh @U l t
bolte
bh @U l t
bolts
bh @U l t s
boltz-	mann's
bh @U l	t s m V n z
bom
bh Q m
bom-	ba
bh Q m	b V
bom-	bar-	ded
bh Q m	b Q@	d V d
bom-	bar-	dier
bh Q m	b @r	d I@
bom-	bar-	ding
bh Q m	b Q@	d I N
bom-	bard
bh Q m	b Q@ d
bom-	bard-	ment
bh Q m	b Q@ d	m V n t
bom-	bard-	ments
bh Q m	b Q@ d	m V n t s
bom-	bas-	tic
bh Q m	b { s	t I k
bom-	bast
bh Q m	b { s t
bom-	bay
bh Q m	b eI
bom-	bay's
bh Q m	b eI z
bom-	ber
bh Q	m @r
bom-	bers
bh Q	m @r z
bom-	ber's
bh Q	m @r z
bom-	bing
bh Q	m I N
bom-	bings
bh Q	m I N z
bomb
bh Q m
bomb-	shell
bh Q m	S e l
bomb-	shells
bh Q m	S e l z
bombed
bh Q m d
bombs
bh Q m z
bon
bh Q n
bon-	dage
bh Q n	d I dZ
bon-	dar
bh V n	d Q@
bon-	ded
bh Q n	d V d
bon-	der-	man
bh Q n	d @r	m V n
bon-	ding
bh Q n	d I N
bon-	du-	rant
bh @U n	d U@	V n t
bon-	dy
bh Q n	d i:
bon-	fi-	re
bh Q n	f aI	@r
bon-	fi-	res
bh Q n	f aI	@r z
bon-	field
bh Q n	f i: l d
bon-	fig-	li-	o
bh Q n	f I g	l i:	@U
bon-	go
bh Q N	g @U
bon-	gos
bh Q N	g @U z
bon-	ham
bh Q n	h V m
bon-	jour
bh V n	Z U@
bon-	kers
bh Q N	k @r z
bon-	ne-	ville
bh Q	n V	v I l
bon-	neau
bh V	n @U
bon-	nell
bh Q	n V l
bon-	ner
bh O:	n @r
bon-	net
bh Q	n V t
bon-	nette
bh V	n e t
bon-	ney
bh Q	n i:
bon-	ni-	bel
bh Q	n I	b V l
bon-	ni-	belle
bh Q	n I	b e l
bon-	nie
bh Q	n i:
bon-	nie's
bh Q	n i: z
bon-	nor
bh Q	n @r
bon-	ny
bh Q	n i:
bon-	sai
bh Q n	s aI
bon-	sall
bh @U n	s Q l
bon-	ser
bh Q n	s @r
bon-	tem-	po
bh Q n	t e m	p @U
bond
bh Q n d
bond-	hol-	der
bh Q n	d h @U l	d @r
bond-	hol-	ders
bh Q n	d h @U l	d @r z
bonds
bh Q n d z
bond's
bh Q n d z
bone
bh @U n
bone-	less
bh @U n	l V s
boned
bh @U n d
bones
bh @U n z
bones-	teel
bh @U n	s t i: l
bong
bh Q N
bonk
bh Q N k
bonn
bh Q n
bonne
bh Q n
bonnes
bh O: n z
bonn's
bh Q n z
boo
bh u:
boo-	by
bh u:	b i:
boo-	dle
bh u:	d V l
boo-	dles
bh u:	d V l z
boo-	dy
bh u:	d i:
boo-	gie
bh u:	g i:
boo-	gie-	woo-	gie
bh u:	g i:	w u:	g i:
boo-	ing
bh u:	I N
boo-	ker
bh U	k @r
boo-	kers
bh U	k @r z
boo-	kie
bh U	k i:
boo-	kies
bh U	k i: z
boo-	king
bh U	k I N
boo-	kings
bh U	k I N z
boo-	kish
bh U	k I S
boo-	me-	rang
bh u:	m @r	{ N
boo-	me-	ranged
bh u:	m @r	{ N d
boo-	mer
bh u:	m @r
boo-	mers
bh u:	m @r z
boo-	ming
bh u:	m I N
boo-	ty
bh u:	t i:
boo-	zer
bh u:	z @r
boo-	zi-	er
bh u:	z i:	@r
boo-	zing
bh u:	z I N
boo-	zy
bh u:	z i:
boob
bh u: b
boobs
bh u: b z
booed
bh u: d
book
bh U k
book-	bin-	der
bh U k	b aI n	d @r
book-	ca-	ses
bh U k	k eI	s V z
book-	case
bh U k	k eI s
book-	end
bh U	k e n d
book-	ends
bh U	k e n d z
book-	kee-	per
bh U k	k i:	p @r
book-	kee-	pers
bh U k	k i:	p @r z
book-	kee-	ping
bh U k	k i:	p I N
book-	let
bh U k	l V t
book-	lets
bh U k	l V t s
book-	ma-	king
bh U k	m eI	k I N
book-	man
bh U k	m V n
book-	mo-	bile
bh U k	m @U	b i: l
book-	sel-	ler
bh U k	s e	l @r
book-	sel-	lers
bh U k	s e	l @r z
book-	shelf
bh U k	S e l f
book-	shelves
bh U k	S e l v z
book-	shop
bh U k	S Q p
book-	shops
bh U k	S Q p s
book-	store
bh U k	s t O@
book-	stores
bh U k	s t O@ z
book-	worm
bh U k	w @r m
booked
bh U k t
books
bh U k s
book's
bh U k s
boole
bh u: l
boom
bh u: m
boom-	box
bh U m	b Q k s
boom-	let
bh u: m	l V t
boom-	town
bh u: m	t aU n
boomed
bh u: m d
booms
bh u: m z
boon
bh u: n
boon-	docks
bh u: n	d Q k s
boon-	dog-	gle
bh u: n	d Q	g V l
boon-	dog-	gles
bh u: n	d Q	g V l z
boon-	ton
bh u: n	t V n
boon-	ville
bh u: n	v I l
boone
bh u: n
boor
bh U@
boord
bh U@ d
booth
bh u: T
boots
bh u: t s
boots-	trap
bh u: t	s t r { p
boots-	traps
bh u: t	s t r { p s
booz
bh u: z
booze
bh u: z
bop
bh Q p
bop-	per
bh Q	p @r
bop-	pers
bh Q	p @r z
bopp
bh Q p
bor-	chers
bh O@	k @r z
bor-	chert
bh O@	k @r t
bor-	da
bh O@	d V
bor-	da's
bh O@	d V z
bor-	de-	ring
bh O@	d @r	I N
bor-	deaux
bh O@	d @U
bor-	del-	lo
bh O@	d e	l @U
bor-	den
bh O@	d V n
bor-	den's
bh O@	d V n z
bor-	der
bh O@	d @r
bor-	der-	line
bh O@	d @r	l aI n
bor-	dered
bh O@	d @r d
bor-	ders
bh O@	d @r z
bor-	der's
bh O@	d @r z
bor-	ge-	son
bh O@	g V	s V n
bor-	ger
bh O@	g @r
bor-	ges
bh O@	g eI s
bor-	ghi
bh O@	g i:
bor-	gia
bh O@	dZ V
bor-	land
bh O@	l V n d
bor-	man
bh O@	m V n
bor-	man's
bh O@	m V n z
bor-	ne-	o
bh O@	n i:	@U
bor-	ras
bh O@	V z
bor-	rell
bh O@	eI l
bor-	ro-	wer
bh Q@	@U	@r
bor-	ro-	wers
bh Q@	@U	@r z
bor-	ro-	wer's
bh Q@	@U	@r z
bor-	ro-	wing
bh Q@	@U	I N
bor-	ro-	wings
bh Q@	@U	I N z
bor-	roff
bh O@	O: f
bor-	row
bh Q@	@U
bor-	rowed
bh Q@	@U d
bor-	rows
bh Q@	@U z
bord-	man
bh O@ d	m V n
bordes
bh O@ d z
bore
bh O@
bore-	dom
bh O@	d V m
bored
bh O@ d
bores
bh O@ z
borg
bh O@ g
bork
bh O@ k
bork's
bh O@ k s
born
bh O@ n
borne
bh O@ n
borns-	tein
bh O@ n	s t aI n
bors
bh O@ z
borsch
bh O@ S
borscht
bh O@ S t
bort
bh O@ t
bortz
bh O@ t s
bos
bh Q s
bos-	ni-	a
bh Q z	n i:	V
bos-	ni-	an
bh Q z	n i:	V n
bos-	ni-	ans
bh Q z	n i:	V n z
bos-	ni-	a's
bh Q z	n i:	V z
bos-	ses
bh O:	s V z
bos-	si-	er
bh O:	s i:	@r
bos-	s's
bh O:	s V z
bos-	sy
bh O:	s i:
bos-	tic
bh Q s	t I k
bos-	to-	ni-	an
bh Q s	t @U	n i:	V n
bos-	to-	ni-	ans
bh Q s	t @U	n i:	V n z
bos-	ton
bh Q s	t V n
bos-	ton's
bh Q s	t V n z
bos-	well
bh Q z	w e l
bos-	worth
bh O: z	w @r T
bosch
bh O: S
bose
bh @U z
bosh
bh Q S
boss
bh O: s
bossed
bh Q s t
bost-	wick
bh Q s	t w I k
bot-	fly
bh Q t	f l aI
bot-	kin
bh Q t	k I n
bot-	kins
bh Q t	k I n z
bot-	ry-	tis
bh V t	r I	t I s
bot-	t-	ling
bh Q	t V	l I N
bot-	ting
bh Q	t I N
bot-	tle
bh Q	t V l
bot-	tle-	neck
bh Q	t V l	n e k
bot-	tle-	necks
bh Q	t V l	n e k s
bot-	tled
bh Q	t V l d
bot-	tles
bh Q	t V l z
bot-	to-	ming
bh Q	t V	m I N
bot-	tom
bh Q	t V m
bot-	tom-	less
bh Q	t V m	l V s
bot-	tomed
bh Q	t V m d
bot-	toms
bh Q	t V m z
bot-	tom's
bh Q	t V m z
botch
bh Q tS
botched
bh Q tS t
both
bh @U T
both-	well
bh Q T	w e l
bothe
bh @U D
bots-	ford
bh Q t	s f @r d
bots-	wa-	na
bh Q t	s w Q	n V
bott
bh Q t
bott-	ger
bh Q t	g @r
bott-	ler
bh Q t	l @r
bott-	lers
bh Q t	l @r z
botts
bh Q t s
bou-	chard
bh u:	S Q@ d
bou-	cher
bh u:	S V
bou-	din
bh u:	d I n
bou-	doir
bh u:	d OI r
bou-	dreaux
bh u: d	r @U
bou-	gain-	vil-	le-	a
bh u:	g eI n	v I	l i:	V
bou-	gain-	ville
bh u:	g V n	v I l
bou-	gie
bh u:	Z i:
bou-	lan-	ger
bh aU	l V	N @r
bou-	le-	vard
bh U	l V	v Q@ d
bou-	le-	vards
bh U	l V	v Q@ d z
bou-	ley
bh u:	l i:
bou-	lez
bh u:	l e z
bou-	quet
bh u:	k eI
bou-	quets
bh @U	k eI z
bou-	tell
bh u:	t e l
bou-	tique
bh u:	t i: k
bou-	tiques
bh u:	t i: k s
bou-	ton
bh aU	t V n
bou-	vi-	er
bh u:	v i:	eI
bouch
bh aU tS
bouche
bh aU tS
bough
bh aU
bough-	ten
bh O:	t V n
bough-	ton
bh aU	t V n
boughs
bh aU z
bought
bh Q t
boul-	der
bh @U l	d @r
boul-	ders
bh @U l	d @r z
boul-	ter
bh @U l	t @r
boule
bh u: l
boun-	cer
bh aU n	s @r
boun-	cers
bh aU n	s @r z
boun-	ces
bh aU n	s V z
boun-	ci-	ness
bh aU n	s i:	n V s
boun-	cing
bh aU n	s I N
boun-	cy
bh aU n	s i:
boun-	da-	ries
bh aU n	d @r	i: z
boun-	da-	ry
bh aU n	d @r	i:
boun-	ded
bh aU n	d V d
boun-	der
bh aU n	d @r
boun-	ding
bh aU n	d I N
boun-	ti-	ful
bh aU n	t I	f V l
boun-	ties
bh aU n	t i: z
boun-	ty
bh aU n	t i:
bounce
bh aU n s
bounced
bh aU n s t
bound
bh aU n d
bound-	less
bh aU n	d l V s
bounds
bh aU n d z
bour
bh aU r
bour-	bon
bh @r	b V n
bour-	bons
bh @r	b V n z
bour-	geoi-	sie
bh U@ Z	w Q	z i:
bour-	geois
bh U@ Z	w Q
bour-	get
bh U@	Z e t
bour-	gui-	ba
bh O@ g	w i:	b V
bour-	guig-	non
bh U@	g i: n	j @U n
bour-	ses
bh O@	s V z
bour-	se's
bh O@	s V z
bourg
bh O@ g
bourke
bh @r k
bourn
bh O@ n
bourne
bh O@ n
bourque
bh U@ k
bourse
bh O@ s
bouse
bh aU s
bout
bh aU t
bout-	well
bh aU t	w e l
bouts
bh aU t s
boutte
bh u: t
bove
bh @U v
bow
bh aU
bow-	den
bh @U	d V n
bow-	ditch
bh @U	d I tS
bow-	dle
bh @U	d V l
bow-	doin
bh @U	d OI n
bow-	ker
bh @U	k @r
bow-	ler
bh @U	l @r
bow-	lers
bh @U	l @r z
bow-	lin
bh @U	l I n
bow-	ling
bh @U	l I N
bow-	ling's
bh @U	l I N z
bow-	lus
bh @U	l V s
bow-	man
bh @U	m V n
bow-	man's
bh @U	m V n z
bow-	men
bh @U	m V n
bow-	ring
bh @U	r I N
bow-	ser
bh @U	z @r
bow-	ses
bh aU	z V z
bow-	sing
bh aU	z I N
bow-	yer
bh @U	j @r
bowe
bh @U
bowed
bh aU d
bowes
bh @U z
bowl
bh @U l
bowlds
bh @U l d z
bowled
bh @U l d
bowles
bh @U l z
bowls
bh @U l z
bown
bh @U n
bowne
bh @U n
bows
bh aU z
bowse
bh @U s
bowsed
bh aU z d
box
bh Q k s
box-	car
bh Q k	s k Q@
box-	cars
bh Q k	s k Q@ z
box-	wood
bh Q k	s w U d
boxed
bh Q k s t
boy
bh OI
boy-	cot-	ted
bh OI	k Q	t V d
boy-	cot-	ting
bh OI	k Q	t I N
boy-	cott
bh OI	k Q t
boy-	cotts
bh OI	k Q t s
boy-	den
bh OI	d V n
boy-	friend
bh OI f	r e n d
boy-	friends
bh OI f	r e n d z
boy-	hood
bh OI	h U d
boy-	kin
bh OI	k I n
boy-	kins
bh OI	k I n z
boy-	lan
bh OI	l V n
boyce
bh OI s
boyd
bh OI d
boyd's
bh OI d z
boyes
bh OI z
boyl-	ston
bh OI l	s t V n
boyl-	ston's
bh OI l	s t V n z
boyle
bh OI l
boyn-	ton
bh OI n	t V n
boyne
bh OI n
boys
bh OI z
boy's
bh OI z
boys'
bh OI z
boyt
bh OI t
boz-	man
bh Q z	m V n
boze-	man
bh @U z	m V n
br-	ca
bh r I	k V
br-	yan
bh r aI	V n
br-	yan's
bh r aI	V n z
br-	yant
bh r aI	V n t
bra
bh r Q
bra-	bant
bh r Q	b V n t
bra-	ce-	ro
bh r Q	tS e@	@U
bra-	cer
bh r eI	s @r
bra-	ces
bh r eI	s V z
bra-	ce's
bh r eI	s V z
bra-	cey
bh r eI	s i:
bra-	chi-	o-	pod
bh r eI	k i:	V	p Q d
)"
R"(bra-	chi-	o-	pods
bh r eI	k i:	V	p Q d z
bra-	cing
bh r eI	s I N
bra-	cing-	ly
bh r eI	s I N	g l i:
bra-	cken
bh r {	k V n
bra-	ckens
bh r {	k V n z
bra-	ckets
bh r {	k V t s
bra-	ckett
bh r {	k I t
bra-	ckish
bh r {	k I S
bra-	den
bh r eI	d V n
bra-	den-	ton
bh r {	d V n	t V n
bra-	der
bh r {	d @r
bra-	dy
bh r eI	d i:
bra-	dy-	car-	di-	a
bh r {	d V	k Q@	d i:	V
bra-	dy-	ki-	nin
bh r V	d I	k V	n I n
bra-	dy's
bh r eI	d i: z
bra-	ga
bh r Q	g V
bra-	ger
bh r eI	g @r
bra-	ham
bh r {	h V m
bra-	ker
bh r eI	k @r
bra-	king
bh r eI	k I N
bra-	mah
bh r Q	m V
bra-	man
bh r eI	m V n
bra-	nagh
bh r {	n V g
bra-	niff
bh r {	n I f
bra-	niff's
bh r {	n I f s
bra-	num
bh r {	n V m
bra-	sel-	ton
bh r V	s e l	t V n
bra-	shear
bh r {	S I@
bra-	sher
bh r {	S @r
bra-	shi-	er
bh r {	S i:	@r
bra-	si-	lia
bh r V	z I l	j V
bra-	sil
bh r {	s I l
bra-	va-	do
bh r V	v Q	d @U
bra-	ve-	ry
bh r eI	v @r	i:
bra-	ver
bh r eI	v @r
bra-	vest
bh r eI	v V s t
bra-	ving
bh r eI	v I N
bra-	vo
bh r Q	v @U
bra-	vu-	ra
bh r V v	j U@	V
bra-	wer
bh r O:	@r
)"