R"(fore-	front
f O@ f	r V n t
fore-	go
f O@	g @U
fore-	go-	ing
f O@	g @U	I N
fore-	gone
f O@	g O: n
fore-	ground
f O@ g	r aU n d
fore-	hand
f O@	h { n d
fore-	hands
f O@	h { n d z
fore-	head
f O@	h e d
fore-	heads
f O@	h e d z
fore-	limb
f O@	l I m
fore-	limbs
f O@	l I m z
fore-	per-	son
f O@	p @r	s V n
fore-	play
f O@ p	l eI
fore-	run-	ner
f O@	V	n @r
fore-	run-	ners
f O@	V	n @r z
fore-	saw
f O@	s O:
fore-	see
f O@	s i:
fore-	see-	a-	ble
f O@	s i:	V	b V l
fore-	see-	ing
f O@	s i:	I N
fore-	seen
f O@	s i: n
fore-	sees
f O@	s i: z
fore-	sha-	dow
f O@	S {	d @U
fore-	sha-	dow-	ing
f O@	S {	d @U	I N
fore-	sha-	dowed
f O@	S {	d @U d
fore-	sha-	dows
f O@	S {	d @U z
fore-	sight
f O@	s aI t
fore-	taste
f O@	t eI s t
fore-	tel-	ling
f O@	t e	l I N
fore-	tell
f O@	t e l
fore-	thought
f O@	T O: t
fore-	told
f O@	t @U l d
fore-	warned
f O@	w O@ n d
fore-	wing
f O@	w I N
fore-	wings
f O@	w I N z
fore-	wo-	man
f O@	w u:	m V n
fore-	word
f O@	w @r d
fores-	tal-	ling
f O@ s	t Q	l I N
fores-	tall
f O@ s	t O: l
fores-	talled
f O@ s	t Q l d
foret
f O@ t
forge
f O@ dZ
forged
f O@ dZ d
fork
f O@ k
fork-	lift
f O@ k	l I f t
fork-	lifts
f O@ k	l I f t s
forked
f O@ k t
forks
f O@ k s
form
f O@ m
form-	by
f O@ m	b i:
formed
f O@ m d
forms
f O@ m z
fors-	ter
f O@ s	t @r
fors-	wear
f O@ s	w e@
fors-	worn
f O@ s	w O@ n
forst
f O@ s t
forst-	ner
f O@ s	t n @r
fort
f O@ t
fort-	man
f O@ t	m V n
fort-	na
f O@ t	n V
fort-	night
f O@ t	n aI t
fort-	night-	ly
f O@ t	n aI t	l i:
forth
f O@ T
forth-	co-	ming
f O@ T	k V	m I N
forth-	right
f O@ T	r aI t
forth-	right-	ly
f O@ T	r aI t	l i:
forth-	right-	ness
f O@ T	r aI t	n V s
forth-	with
f O@ T	w I T
forts
f O@ t s
fos-	dick
f Q s	d I k
fos-	kett
f Q s	k V t
fos-	si-	li-	fe-	rous
f Q	s I	l I	f @r	V s
fos-	si-	lize
f Q	s I	l aI z
fos-	si-	lized
f Q	s I	l aI z d
fos-	sil
f Q	s V l
fos-	sils
f Q	s I l z
fos-	te-	ring
f Q s	t @r	I N
fos-	ter
f Q s	t @r
fos-	tered
f Q s	t @r d
fos-	ters
f Q s	t @r z
fos-	ter's
f Q s	t @r z
foss
f Q s
fosse
f Q s
fou-	gere
f aU	g @r
fou-	ling
f aU	l I N
fou-	shee
f aU	S i:
fou-	ty
f aU	t i:
fought
f O: t
foul
f aU l
foul-	ness
f aU l	n V s
fouled
f aU l d
foulk
f aU l k
fouls
f aU l z
foun-	da-	tio-	nal
f aU n	d eI	S V	n V l
foun-	da-	tion
f aU n	d eI	S V n
foun-	da-	tions
f aU n	d eI	S V n z
foun-	da-	tion's
f aU n	d eI	S V n z
foun-	de-	ring
f aU n	d @r	I N
foun-	ded
f aU n	d V d
foun-	der
f aU n	d @r
foun-	dered
f aU n	d @r d
foun-	ders
f aU n	d @r z
foun-	der's
f aU n	d @r z
foun-	ders'
f aU n	d @r z
foun-	ding
f aU n	d I N
foun-	dry
f aU n	d r i:
foun-	tain
f aU n	t I n
foun-	tains
f aU n	t I n z
found
f aU n d
found-	ling
f aU n	d l I N
found-	ries
f aU n	d r i: z
four
f O@
four-	fold
f O@	f @U l d
four-	net
f U@	n e t
four-	ni-	er
f O@	n i:	@r
four-	some
f O@	s V m
four-	square
f O@ s	k w e@
four-	teen
f O@	t i: n
four-	teens
f O@	t i: n z
four-	teenth
f O@	t i: n T
fours
f O@ z
four's
f O@ z
fourth
f O@ T
fourth-	ly
f O@ T	l i:
fourths
f O@ T s
fow-	le
f aU	V l
fow-	ler
f aU	l @r
fow-	ler's
f aU	l @r z
fow-	les
f aU	V l z
fowkes
f aU k s
fowl
f aU l
fowlkes
f aU l k s
fox
f Q k s
fox-	bo-	ro
f Q k	s b @r	@U
fox-	fire
f Q k	s f aI r
fox-	glove
f Q k	s g l V v
fox-	hole
f Q k	s h @U l
fox-	holes
f Q k	s h @U l z
fox-	hound
f Q k	s h aU n d
fox-	tail
f Q k	s t eI l
fox-	wood
f Q k	s w U d
fox-	worth
f Q k	s w @r T
foy
f OI
foyle
f OI l
fr-	yer
f r aI	@r
fr-	yers
f r aI	@r z
fra-	cas
f r eI	k V s
fra-	ger
f r eI	g @r
fra-	gi-	li-	ty
f r V	dZ I	l V	t i:
fra-	gile
f r {	dZ V l
fra-	mer
f r eI	m @r
fra-	mers
f r eI	m @r z
fra-	ming
f r eI	m I N
fra-	ming-	ham
f r eI	m I N	h { m
fra-	nek
f r {	n I k
fra-	ry
f r e@	i:
fra-	ser
f r eI	z @r
fra-	ser's
f r eI	z @r z
fra-	sier
f r eI	Z @r
fra-	ter
f r eI	t @r
fra-	ter-	nal
f r V	t @r	n V l
fra-	ter-	ni-	ties
f r V	t @r	n V	t i: z
fra-	ter-	ni-	ty
f r V	t @r	n V	t i:
fra-	ter-	ni-	zing
f r {	t @r	n aI	z I N
fra-	ter-	nize
f r {	t @r	n aI z
fra-	tri-	cide
f r { t	r I	s aI d
fra-	tri-	cides
f r { t	r I	s aI d z
fra-	ying
f r eI	I N
fra-	zee
f r V	z i:
fra-	zer
f r eI	z @r
fra-	zier
f r eI	Z @r
frac-	tal
f r { k	t V l
frac-	tio-	nal
f r { k	S V	n V l
frac-	tio-	nal-	ly
f r { k	S V	n V	l i:
frac-	tion
f r { k	S V n
frac-	tions
f r { k	S V n z
frac-	tious
f r { k	S V s
frac-	tious-	ness
f r { k	S V s	n V s
frac-	tu-	ring
f r { k	tS @r	I N
frac-	ture
f r { k	tS @r
frac-	tured
f r { k	tS @r d
frac-	tures
f r { k	tS @r z
frag-	ment
f r { g	m V n t
frame
f r eI m
frame-	work
f r eI m	w @r k
framed
f r eI m d
frames
f r eI m z
fran
f r { n
fran-	ca
f r { N	k V
fran-	caise
f r Q n	s e z
fran-	ces
f r { n	s V s
fran-	ce's
f r { n	s V z
fran-	ces-	ca
f r { n	tS e s	k V
fran-	ces-	co
f r { n	tS e s	k @U
fran-	ces-	co's
f r { n	tS e s	k @U z
fran-	chi-	see
f r { n	tS aI	z i:
fran-	chi-	sees
f r { n	tS aI	z i: z
fran-	chi-	ser
f r { n	tS aI	z @r
fran-	chi-	sers
f r { n	tS aI	z @r z
fran-	chi-	ses
f r { n	tS aI	z V z
fran-	chi-	se's
f r { n	tS aI	z V z
fran-	chi-	sing
f r { n	tS aI	z I N
fran-	chise
f r { n	tS aI z
fran-	chised
f r { n	tS aI z d
fran-	chot
f r { n	k V t
fran-	cia
f r Q n	tS V
fran-	cie
f r { N	k i:
fran-	cine
f r { n	s i: n
fran-	cine's
f r { n	s i: n z
fran-	cis
f r { n	s I s
fran-	cis-	can
f r { n	s I s	k V n
fran-	cis-	cans
f r { n	s I s	k V n z
fran-	cis-	co
f r { n	s I s	k @U
fran-	cis-	co's
f r { n	s I s	k @U z
fran-	co
f r { N	k @U
fran-	co-	phile
f r { N	k V	f aI l
fran-	cois
f r Q n	s w Q
fran-	coise
f r { n	s w Q z
fran-	co's
f r { N	k @U z
fran-	cy
f r { n	s i:
fran-	cyne
f r { n	s aI n
fran-	gos
f r { N	g @U z
fran-	kel
f r { N	k V l
fran-	ken-	stein
f r { N	k V n	s t aI n
fran-	ken-	stein's
f r { N	k V n	s t aI n z
fran-	kie
f r { N	k i:
fran-	kin-	cense
f r { N	k I n	s e n s
fran-	king
f r { N	k I N
fran-	kish
f r { N	k I S
fran-	ko
f r { N	k @U
fran-	nie
f r {	n i:
fran-	ny
f r {	n i:
fran-	sen
f r { n	s V n
fran-	ti-	cal-	ly
f r { n	t I	k V	l i:
fran-	tic
f r { n	t I k
fran-	zen
f r { n	z V n
fran-	zo-	ni
f r Q n	z @U	n i:
franc
f r { N k
france
f r { n s
franck
f r { N k
franck-	lin
f r { N	k l I n
franck-	lyn
f r { N	k l I n
francs
f r { N k s
franc's
f r { N k s
frank
f r { N k
frank-	fort
f r { N	k f @r t
frank-	fort's
f r { N	k f @r t s
frank-	fur-	ter
f r { N	k f @r	t @r
frank-	fur-	ters
f r { N	k f @r	t @r z
frank-	furt
f r { N	k f @r t
frank-	furt's
f r { N	k f @r t s
frank-	li-	nite
f r { N	k l I	n aI t
frank-	lin
f r { N	k l I n
frank-	lin-	ville
f r { N	k l I n	v I l
frank-	lin's
f r { N	k l I n z
frank-	ly
f r { N	k l i:
frank-	lyn
f r { N	k l I n
frank-	ness
f r { N	k n V s
franke
f r { N k
franked
f r { N k t
franks
f r { N k s
frank's
f r { N k s
frans
f r { n z
frantz
f r { n t s
franz
f r { n z
frap
f r { p
fras-	co
f r Q s	k @U
frasch
f r { S
frase
f r eI z
frate
f r eI t
frau
f r aU
frau-	du-	lent
f r O:	dZ V	l V n t
frau-	du-	lent-	ly
f r O:	d u:	l V n	t l i:
fraud
f r O: d
frauds
f r O: d z
frauds-	ter
f r O: d	s t @r
frauds-	ters
f r O: d	s t @r z
fraught
f r O: t
fray
f r eI
frayed
f r eI d
frayn
f r eI n
frayne
f r eI n
fraz-	zle
f r {	z V l
fraz-	zled
f r {	z V l d
fraze
f r eI z
fre-	berg
f r i:	b @r g
fre-	chette
f r e	S e t
fre-	de-	ri-	ca
f r e	d @r	i:	k V
fre-	de-	ri-	co
f r e	d @r	i:	k @U
fre-	de-	ri-	ka
f r eI	d e@	i:	k V
fre-	de-	ric-	ka
f r eI	d e@	i:	k V
fre-	de-	rik-	sen
f r e	d @r	I k	s V n
fre-	del-	la
f r e	d e	l V
fre-	den-	burg
f r i:	d V n	b @r g
fre-	dette
f r V	d e t
fre-	er
f r i:	@r
fre-	est
f r i:	V s t
fre-	li-	mo
f r e	l I	m @U
fre-	mont
f r i:	m Q n t
fre-	ne-	tic
f r V	n e	t I k
fre-	ni
f r e	n i:
fre-	on
f r i:	Q n
fre-	ons
f r i:	Q n z
fre-	quen-	cies
f r i: k	w V n	s i: z
fre-	quen-	cy
f r i: k	w V n	s i:
fre-	quen-	ted
f r i: k	w V n	t V d
fre-	quent
f r i: k	w V n t
fre-	quent-	ly
f r i: k	w V n	t l i:
fre-	quents
f r i: k	w V n t s
fre-	richs
f r e@	I k s
fre-	she-	ner
f r e	S V	n @r
fre-	she-	ners
f r e	S V	n @r z
fre-	she-	ning
f r e	S V	n I N
fre-	shen
f r e	S V n
fre-	sher
f r e	S @r
fre-	shest
f r e	S V s t
fre-	ya
f r eI	V
frea-	king
f r i:	k I N
frea-	ky
f r i:	k i:
freak
f r i: k
freaked
f r i: k t
freaks
f r i: k s
frear
f r I@
frec-	kle
f r e	k V l
frec-	kled
f r e	k V l d
frec-	kles
f r e	k V l z
frech
f r e k
freck
f r e k
fred
f r e d
fred-	die
f r e	d i:
fred-	dy
f r e	d i:
fred-	dy's
f r e	d i: z
fred-	kin
f r e d	k I n
fred-	ric
f r e d	r I k
fred-	rich
f r e d	r I k
fred-	rick
f r e d	r I k
fred-	rick-	son
f r e d	r I k	s V n
freda
f r e d
frede-	ric
f r e d	r I k
frede-	rick
f r e d	r I k
frede-	ricks
f r e d	r I k s
frede-	rick's
f r e d	r I k s
frede-	ricks-	burg
f r e d	r I k	s b @r g
fred's
f r e d z
free
f r i:
free-	bie
f r i:	b i:
free-	bies
f r i:	b i: z
free-	born
f r i:	b @r n
free-	burg
f r i:	b @r g
free-	burn
f r i:	b @r n
free-	dom
f r i:	d V m
free-	doms
f r i:	d V m z
free-	dom's
f r i:	d V m z
free-	fall
f r i:	f O: l
free-	form
f r i:	f O@ m
free-	hand
f r i:	h { n d
free-	hol-	der
f r i:	h @U l	d @r
free-	hol-	ders
f r i:	h @U l	d @r z
free-	hold
f r i:	h @U l d
free-	ing
f r i:	I N
free-	lan-	cer
f r i:	l { n	s @r
free-	lan-	cers
f r i:	l { n	s @r z
free-	lan-	cing
f r i:	l { n	s I N
free-	lance
f r i:	l { n s
free-	land
f r i:	l V n d
free-	loa-	der
f r i:	l @U	d @r
free-	loa-	ders
f r i:	l @U	d @r z
free-	ly
f r i:	l i:
free-	ma-	son
f r i:	m eI	s V n
free-	ma-	son-	ry
f r i:	m eI	s V n	r i:
free-	man
f r i:	m V n
free-	man's
f r i:	m V n z
free-	men
f r i:	m e n
free-	mon
f r i:	m V n
free-	port
f r i:	p O@ t
free-	port's
f r i:	p O@ t s
free-	stan-	ding
f r i: s	t { n	d I N
free-	stone
f r i: s	t @U n
free-	style
f r i: s	t aI l
free-	thin-	ker
f r i:	T I N	k @r
free-	thin-	kers
f r i:	T I N	k @r z
free-	town
f r i:	t aU n
free-	way
f r i:	w eI
free-	ways
f r i:	w eI z
free-	whee-	ling
f r i:	w i:	l I N
free-	zer
f r i:	z @r
free-	zers
f r i:	z @r z
free-	zes
f r i:	z V z
free-	zing
f r i:	z I N
freed
f r i: d
freed-	man
f r i: d	m V n
freed-	man's
f r i: d	m V n z
freen
f r i: n
frees
f r i: z
freet
f r i: t
freeze
f r i: z
frei
f r aI
frei-	a
f r i:	V
frei-	man
f r aI	m V n
freigh-	ter
f r eI	t @r
freigh-	ters
f r eI	t @r z
freight
f r eI t
freight-	li-	ner
f r eI t	l aI	n @r
fremd
f r e m d
fren-	ch's
f r e n	tS V z
fren-	zied
f r e n	z i: d
fren-	zy
f r e n	z i:
french
f r e n tS
french-	man
f r e n	tS m { n
french-	men
f r e n	tS m e n
frentz
f r e n t s
frere
f r I@
fres-	co
f r e s	k @U
fres-	coed
f r e s	k @U d
fres-	coes
f r e s	k @U z
fres-	co's
f r e s	k @U z
fres-	no
f r e z	n @U
fres-	no's
f r e z	n @U z
fresh
f r e S
fresh-	ly
f r e S	l i:
fresh-	man
f r e S	m V n
fresh-	men
f r e S	m e n
fresh-	ness
f r e S	n V s
fresh-	wa-	ter
f r e S	w O:	t @r
fret
f r e t
fret-	ful
f r e t	f V l
fret-	ted
f r e	t V d
fret-	ter
f r e	t @r
fret-	ting
f r e	t I N
fret-	well
f r e t	w e l
frets
f r e t s
frett
f r e t
freu-	di-	an
f r u:	d i:	V n
freud
f r OI d
freud's
f r OI d z
frey
f r eI
frey-	tag
f r eI	t V g
freyre
f r e@
fri-	a-	ry
f r aI	@r	i:
fri-	ar
f r aI	@r
fri-	ars
f r aI	@r z
fri-	bourg
f r aI	b O@ g
fri-	da
f r i:	d V
fri-	day
f r aI	d i:
fri-	days
f r aI	d i: z
fri-	day's
f r aI	d i: z
fri-	er
f r aI	@r
fri-	gate
f r I	g V t
fri-	gates
f r I	g V t s
fri-	gate's
f r I	g V t s
fri-	gid
f r I	dZ I d
fri-	o-	na
f r i:	@U	n V
fri-	sa
f r i:	z V
fri-	son
f r I	s V n
fri-	to
f r i:	t @U
fri-	vo-	li-	ty
f r V	v Q	l V	t i:
fri-	vo-	lous
f r I	v V	l V s
fri-	vo-	lous-	ly
f r I	v V	l V s	l i:
fric-	tion
f r I k	S V n
fric-	tion-	less
f r I k	S V n	l V s
fric-	tions
f r I k	S V n z
frick
f r I k
fricke
f r I k
frid-	ley
f r I d	l i:
fridge
f r I dZ
frie-	da
f r i:	d V
frie-	dan
f r i:	d V n
frie-	de-	rike
f r i:	d @r	I k
frie-	der
f r aI	d @r
fried
f r aI d
fried-	berg
f r aI d	b @r g
fried-	lan-	der
f r i: d	l V n	d @r
fried-	land
f r i: d	l V n d
fried-	ly
f r i: d	l i:
fried-	man
f r i: d	m V n
fried-	man's
f r i: d	m V n z
fried-	rich
f r i: d	r I k
fried-	rick
f r i: d	r I k
friede
f r i: d
friend
f r e n d
friend-	li-	er
f r e n	d l i:	@r
friend-	li-	est
f r e n	d l i:	V s t
friend-	li-	ness
f r e n	d l i:	n V s
friend-	ly
f r e n	d l i:
friend-	ly's
f r e n	d l i: z
friend-	ship
f r e n	d S I p
friend-	ships
f r e n	d S I p s
friends
f r e n d z
friend's
f r e n d z
frier-	son
f r I@	s V n
fries
f r aI z
friese
f r i: z
friesz
f r i: S
frieze
f r i: z
frigh-	te-	ning
f r aI	t V	n I N
frigh-	te-	ning-	ly
f r aI	t V	n I N	l i:
frigh-	ten
f r aI	t V n
frigh-	tened
f r aI	t V n d
frigh-	tens
f r aI	t V n z
fright
f r aI t
fright-	ful
f r aI t	f V l
fright-	ful-	ly
f r aI t	f V	l i:
fril-	ly
f r I	l i:
frill
f r I l
frills
f r I l z
frin-	ges
f r I n	dZ V z
fringe
f r I n dZ
frink
f r I N k
fris-	bee
f r I s	b i:
fris-	co
f r i: s	k @U
fris-	kin
f r I s	k I n
fris-	ky
f r I s	k i:
frisch
f r I S
frisk
f r I s k
frisked
f r I s k t
frist
f r I s t
frit-	te-	ring
f r I	t @r	I N
frit-	ter
f r I	t @r
frit-	tered
f r I	t @r d
frit-	zie
f r I t	z i:
fritch
f r I tS
frith
f r I T
frits
f r I t s
fritts
f r I t s
fritz
f r I t s
fritze
f r I t z
fritzsche
f r I t S
fro
f r @U
fro-	lic
f r Q	l I k
fro-	lic-	king
f r Q	l I	k I N
fro-	zen
f r @U	z V n
frock
f r Q k
frocks
f r Q k s
froeh-	lich
f r @U	l I k
froem-	ming
f r @U	m I N
frog
f r Q g
frog-	man
f r Q g	m { n
frog-	men
f r Q g	m e n
frog-	mouth
f r Q g	m aU T
frog-	mouths
f r Q g	m aU T s
frogs
f r Q g z
frog's
f r Q g z
froh
f r @U
froh-	lich
f r @U	l I k
froh-	man
f r @U	m V n
from
f r Q m
frome
f r @U m
fromm
f r Q m
fron-	tage
f r V n	t I dZ
fron-	tal
f r V n	t V l
fron-	te-	ra
f r @U n	t e@	V
fron-	ted
f r V n	t V d
fron-	tier
f r V n	t I@
fron-	tiers
f r V n	t I@ z
fron-	tier's
f r V n	t I@ z
fron-	ting
f r V n	t I N
frond
f r Q n d
fronde
f r Q n d
fronds
f r Q n d z
front
f r V n t
front-	line
f r V n	t l aI n
front-	run-	ner
f r V n	t r V	n @r
front-	run-	ners
f r V n	t r V	n @r z
fronts
f r V n t s
front's
f r V n t s
frost
f r O: s t
frost-	bit-	ten
f r O: s	t b I	t V n
frost-	bite
f r O: s	t b aI t
frow-	ning
f r aU	n I N
frow-	ning-	ly
f r aU	n I N	l i:
frowns
f r aU n z
froze
f r @U z
fru-	ga-	li-	ty
f r u:	g {	l I	t i:
fru-	gal
f r u:	g V l
fru-	gal-	ly
f r u:	g V	l i:
fru-	i-	tion
f r u:	I	S V n
fru-	in
f r u:	I n
fruc-	tose
f r V k	t @U s
frue-	hauf
f r u:	h O: f
frui-	ting
f r u:	t I N
frui-	ty
f r u:	t i:
fruit
f r u: t
fruit-	cake
f r u: t	k eI k
fruit-	cakes
f r u: t	k eI k s
fruit-	ful
f r u: t	f V l
fruit-	less
f r u: t	l V s
fruit-	less-	ly
f r u: t	l V s	l i:
fruits
f r u: t s
frum
f r V m
frum-	py
f r V m	p i:
frump
f r V m p
frunze
f r V n z
frush
f r V S
frust-	ra-	ted
f r V s	t r eI	t V d
frust-	ra-	ting
f r V s	t r eI	t I N
frust-	ra-	ting-	ly
f r V s	t r eI	t I N	l i:
frust-	ra-	tion
f r V s	t r eI	S V n
frust-	ra-	tions
f r V s	t r eI	S V n z
frust-	rate
f r V s	t r eI t
frust-	rates
f r V s	t r eI t s
fry
f r aI
fry-	ing
f r aI	I N
fry-	mire
f r i:	m aI r
frye
f r aI
fry's
f r aI z
f's
e f s
fsi
f s i:
fu
f u:
fu-	el
f j u:	V l
fu-	eled
f j u:	V l d
fu-	elled
f j u:	V l d
fu-	els
f j u:	V l z
fu-	el's
f j u:	V l z
fu-	ga-	zy
f j u:	g V	z i:
fu-	gard
f j u:	g Q@ d
fu-	gate
f V	g eI t
fu-	gere
f j u:	g @r
fu-	gi-	tive
f j u:	dZ V	t I v
fu-	gi-	tives
f j u:	dZ V	t I v z
fu-	ji
f u:	dZ i:
fu-	ji-	o
f u:	dZ i:	@U
fu-	ji-	tsu
f u:	dZ I t	s u:
fu-	ji-	tsu's
f u:	dZ I t	s u: z
fu-	ji-	wa-	ra
f u:	dZ i:	w Q@	V
fu-	ji-	ya-	ma
f u:	dZ i:	j Q	m V
fu-	jis
f j u:	dZ I s
fu-	ji's
f u:	dZ i: z
fu-	ku-	da
f u:	k u:	d V
fu-	ku-	o-	ka
f u:	k u:	@U	k V
fu-	ku-	shi-	ma
f u:	k u:	S i:	m V
fu-	la-	ni
f u:	l Q	n i:
fu-	ma-	roles
f j u:	m @r	@U l z
fu-	mi-	ga-	tion
f j u:	m I	g eI	S V n
fu-	mi-	gate
f j u:	m I	g eI t
fu-	ming
f j u:	m I N
fu-	ne-	ra-	ry
f j u:	n @r	e@	i:
fu-	ne-	ral
f j u:	n @r	V l
fu-	ne-	rals
f j u:	n @r	V l z
fu-	o-	co
f u:	@U	k @U
fu-	quay
f u:	k eI
fu-	rey
f j U@	i:
fu-	ri-	ou-	ser
f j U@	i:	V	s @r
fu-	ri-	ous
f j U@	i:	V s
fu-	ri-	ous-	ly
f j U@	i:	V s	l i:
fu-	ror
f j U@	O@
fu-	ry
f j U@	i:
fu-	se-	la-	ges
f j u:	s V	l Q	dZ V z
fu-	se-	lage
f j u:	s V	l Q dZ
fu-	ses
f j u:	z V z
fu-	si-	ble
f j u:	z I	b V l
fu-	sil-	lade
f j u:	s I	l eI d
fu-	sil-	li
f j u:	s I	l i:
fu-	sing
f j u:	z I N
fu-	sion
f j u:	Z V n
)"
R"(fu-	ti-	li-	ty
f j u:	t I	l I	t i:
fu-	tile
f j u:	t V l
fu-	tu-	ri-	sm
f j u:	tS @r	I	z V m
fu-	tu-	ris-	tic
f j u:	tS @r	I s	t I k
fu-	tu-	rist
f j u:	tS @r	I s t
fu-	tu-	rists
f j u:	tS @r	I s t s
fu-	ture
f j u:	tS @r
fu-	tures
f j u:	tS @r z
fu-	ture's
f j u:	tS @r z
fu-	zes
f j u:	z V z
fuc-	king
f V	k I N
fuch-	sias
f j u:	S V z
fuchs
f j u: k s
fuck
f V k
fucked
f V k t
fucks
f V k s
fud-	dy
f V	d i:
fud-	ging
f V	dZ I N
fud-	gy
f V	dZ i:
fudge
f V dZ
fudged
f V dZ d
fue-	ling
f j u:	l I N
fuel-	ling
f j u:	l I N
fuen-	tes
f w e n	t eI z
fugue
f j u: g
fugues
f j u: g z
fuh-	rer
f U@	@r
fuhr-	man
f U@	m V n
fuhr-	man's
f U@	m V n z
ful-	bright
f U l	b r aI t
ful-	cher
f U l	tS @r
ful-	crum
f U l	k r V m
ful-	fil-	ling
f U l	f I	l I N
ful-	fill
f U l	f I l
ful-	fill-	ment
f U l	f I l	m V n t
ful-	filled
f U l	f I l d
ful-	fills
f U l	f I l z
ful-	lam
f U	l V m
ful-	ler
f U	l @r
ful-	ler-	ton
f U	l @r	t V n
ful-	ler's
f U	l @r z
ful-	lest
f U	l V s t
ful-	ly
f U	l i:
ful-	mer
f V l	m @r
ful-	mi-	nate
f U l	m I	n eI t
ful-	some
f U l	s V m
ful-	ton
f U l	t V n
ful-	ton's
f U l	t V n z
ful-	vi-	a
f U l	v i:	V
fuld
f U l d
fulk
f V l k
fulks
f V l k s
full
f U l
full-	back
f U l	b { k
full-	ness
f U l	n V s
full-	time
f U l	t aI m
fults
f U l t s
fultz
f U l t s
fum-	b-	ling
f V m	b V	l I N
fum-	ble
f V m	b V l
fum-	bled
f V m	b V l d
fum-	bles
f V m	b V l z
fume
f j u: m
fumed
f j u: m d
fumes
f j u: m z
fun
f V n
fun-	da-	men-	ta-	li-	sm
f V n	d V	m e n	t V	l I	z V m
fun-	da-	men-	ta-	list
f V n	d V	m e n	t V	l V s t
fun-	da-	men-	ta-	lists
f V n	d V	m e n	t V	l V s t s
fun-	da-	men-	tal
f V n	d V	m e n	t V l
fun-	da-	men-	tal-	ly
f V n	d V	m e n	t V	l i:
fun-	da-	men-	tals
f V n	d V	m e n	t V l z
fun-	ded
f V n	d V d
fun-	der
f V n	d @r
fun-	ders
f V n	d @r z
fun-	ding
f V n	d I N
fun-	gal
f V N	g V l
fun-	gi
f V n	dZ aI
fun-	gi-	ble
f V n	dZ I	b V l
fun-	gi-	cide
f V n	dZ I	s aI d
fun-	gi-	cides
f V n	dZ I	s aI d z
fun-	gus
f V N	g V s
fun-	ky
f V N	k i:
fun-	ne-	ling
f V	n V	l I N
fun-	nel
f V	n V l
fun-	neled
f V	n V l d
fun-	nels
f V	n V l z
fun-	nest
f V	n V s t
fun-	ni-	er
f V	n i:	@r
fun-	ni-	est
f V	n i:	V s t
fun-	ni-	ness
f V	n i:	n V s
fun-	ny
f V	n i:
func-	tio-	na-	li-	ty
f V N	k S V	n {	l I	t i:
func-	tio-	na-	ries
f V N	k S V	n e@	i: z
func-	tio-	na-	ry
f V N	k S V	n e@	i:
func-	tio-	nal
f V N	k S V	n V l
func-	tio-	nal-	ly
f V N	k S V	n V	l i:
func-	tio-	ning
f V N	k S V	n I N
func-	tion
f V N	k S V n
func-	tioned
f V N	k S V n d
func-	tions
f V N	k S V n z
fund
f V n d
fund-	rai-	ser
f V n	d r eI	z @r
fund-	rai-	sers
f V n	d r eI	z @r z
fund-	rai-	ser's
f V n	d r eI	z @r z
fund-	rai-	sing
f V n	d r eI	s I N
funds
f V n d z
fund's
f V n d z
fung
f V N
funk
f V N k
funks
f V N k s
funs
f V n z
funs-	ton
f V n	s t V n
fur
f @r
fur-	bi-	shing
f @r	b I	S I N
fur-	bish
f @r	b I S
fur-	ge-	son
f @r	g V	s V n
fur-	lan
f @r	l V n
fur-	long
f @r	l O: N
fur-	lough
f @r	l @U
fur-	loughed
f @r	l @U d
fur-	loughs
f @r	l @U z
fur-	man
f @r	m { n
fur-	mark
f @r	m Q@ k
fur-	na-	ces
f @r	n V	s V z
fur-	nace
f @r	n V s
fur-	ner
f @r	n @r
fur-	ness
f @r	n I s
fur-	ni-	shes
f @r	n I	S V z
fur-	ni-	shing
f @r	n I	S I N
fur-	ni-	shings
f @r	n I	S I N z
fur-	ni-	ture
f @r	n I	tS @r
fur-	ni-	ture's
f @r	n I	tS @r z
fur-	nish
f @r	n I S
fur-	nished
f @r	n I S t
fur-	ri-	er
f @r	i:	@r
fur-	ri-	ers
f @r	i:	@r z
fur-	row
f @r	@U
fur-	rowed
f @r	@U d
fur-	ry
f @r	i:
fur-	the-	rance
f @r	T @r	V n s
fur-	the-	ring
f @r	D @r	I N
fur-	ther
f @r	D @r
fur-	ther-	more
f @r	D @r	m O@
fur-	thered
f @r	D @r d
fur-	thers
f @r	D @r z
fur-	thest
f @r	T V s t
fur-	tive
f @r	t I v
fur-	tive-	ly
f @r	t I v	l i:
furr
f @r
furr's
f @r z
furs
f @r z
furth
f @r T
fus-	co
f u: s	k @U
fus-	ses
f V	s V z
fus-	sing
f V	s I N
fus-	sy
f V	s i:
fuse
f j u: z
fused
f j u: z d
fuss
f V s
fussed
f V s t
fust
f V s t
fuz-	zi-	er
f V	z i:	@r
fuz-	zy
f V	z i:
fuzz
f V z
fyffe
f aI f
fyke
f aI k
fyo-	dor
f j @U	d @r
fyo-	dor's
f j @U	d @r z
g
dZ i:
g-	dansk
gh V	d { n s k
ga
gh Q
ga-	b-	ler
gh eI	b V	l @r
ga-	ba
gh Q	b V
ga-	bar-	dine
gh {	b @r	d i: n
ga-	bar-	dines
gh {	b @r	d i: n z
ga-	bel
gh V	b e l
ga-	bert
gh {	b @r t
ga-	bie
gh {	b i:
ga-	ble
gh eI	b V l
ga-	bles
gh eI	b V l z
ga-	bon
gh V	b Q n
ga-	bor
gh V	b O@
ga-	bri-	e-	la
gh Q b	r i:	e	l V
ga-	bri-	el
gh eI b	r i:	V l
ga-	bri-	el-	la
gh Q b	r i:	e	l V
ga-	bri-	ele
gh Q b	r i:	e l
ga-	ga-	rin
gh V	g {	r V n
ga-	ger
gh eI	g @r
ga-	han
gh {	h V n
ga-	la
gh {	l V
ga-	la-	had
gh {	l V	h { d
ga-	la-	pa-	gos
gh V	l Q	p V	g @U z
ga-	la-	te-	a
gh {	l V	t i:	V
ga-	la-	ti
gh Q	l Q	t i:
ga-	la-	xies
gh {	l V k	s i: z
ga-	la-	xy
gh {	l V k	s i:
ga-	la-	xy's
gh {	l V k	s i: z
ga-	lac-	tic
gh V	l { k	t I k
ga-	lac-	tose
gh V	l { k	t @U s
ga-	lan
gh eI	l V n
ga-	lan-	te
gh Q	l Q n	t i:
ga-	lan-	ti
gh V	l { n	t i:
ga-	lang
gh {	l V N
ga-	lant
gh Q	l V n t
ga-	las
gh eI	l V z
ga-	lax
gh {	l { k s
ga-	le-	a
gh eI	l i:	V
ga-	le-	na
gh V	l i:	n V
ga-	le-	ni-	cal
gh V	l e	n I	k V l
ga-	len
gh eI	l V n
ga-	len's
gh eI	l V n z
ga-	ler
gh eI	l @r
ga-	ley
gh eI	l i:
ga-	li
gh Q	l i:
ga-	li-	ci-	a
gh V	l I	S i:	V
ga-	li-	le-	an
gh {	l I	l i:	V n
ga-	li-	le-	o
gh {	l I	l i:	@U
ga-	li-	le-	o's
gh {	l I	l i:	@U z
ga-	li-	lee
gh {	l I	l i:
ga-	lik
gh {	l I k
ga-	lo-	shes
gh V	l Q	S V z
ga-	lore
gh V	l O@
ga-	losh
gh V	l Q S
ga-	lu-	sha
gh {	l I	S V
ga-	ma
gh Q	m V
ga-	mal
gh V	m Q l
ga-	me-	lin
gh {	m V	l I n
ga-	me-	tan-	gi-	a
gh {	m V	t { n	dZ i:	V
ga-	me-	to-	phyte
gh V	m i:	t V	f aI t
ga-	mer
gh eI	m @r
ga-	mers
gh eI	m @r z
ga-	mete
gh {	m i: t
ga-	ming
gh eI	m I N
ga-	ming's
gh eI	m I N z
ga-	mut
gh {	m V t
ga-	ny-	mede
gh {	n V	m i: d
ga-	ping
gh eI	p I N
ga-	ra
gh {	r V
ga-	ra-	ges
gh @r	Q	Z V z
ga-	rage
gh @r	Q Z
ga-	rand
gh {	r V n d
ga-	rard
gh @r	Q@ d
ga-	ri
gh Q@	i:
ga-	ri-	bal-	di
gh {	r I	b O: l	d i:
ga-	rie-	py
gh @r	i:	p i:
ga-	rin
gh e@	I n
ga-	rish
gh e@	I S
ga-	ro
gh e@	@U
ga-	ro-	fa-	lo
gh Q@	@U	f Q	l @U
ga-	ron
gh Q@	O: n
ga-	ru-	da
gh V	r u:	d V
ga-	ry
gh e@	i:
ga-	ry's
gh e@	i: z
ga-	se-	ous
gh {	s i:	V s
ga-	ses
gh {	s V z
ga-	shes
gh {	S V z
ga-	si-	fi-	ca-	tion
gh {	s I	f I	k eI	S V n
ga-	si-	fy
gh {	s I	f aI
ga-	so-	hol
gh {	s V	h O: l
ga-	so-	line
gh {	s V	l i: n
ga-	so-	lines
gh {	s V	l i: n z
ga-	s's
gh {	s V z
ga-	ted
gh eI	t V d
ga-	the-	rer
gh {	D @r	@r
ga-	the-	rers
gh {	D @r	@r z
ga-	the-	ring
gh {	D @r	I N
ga-	the-	rings
gh {	D @r	I N z
ga-	ther
gh {	D @r
ga-	thered
gh {	D @r d
ga-	thers
gh {	D @r z
ga-	things
gh {	T I N z
ga-	to-	rade
gh {	t @r	eI d
ga-	tor
gh eI	t @r
ga-	tors
gh eI	t @r z
ga-	tos
gh Q	t @U s
ga-	van
gh eI	v V n
ga-	vel
gh {	v V l
ga-	ven
gh eI	v V n
ga-	vin
gh {	v I n
ga-	wain
gh Q	w I n
ga-	wen
gh O:	V n
ga-	yer
gh eI	@r
ga-	za
gh Q	z V
ga-	zans
gh Q	z V n z
ga-	za's
gh Q	z V z
ga-	zel-	la
gh V	z e	l V
ga-	zelle
gh V	z e l
ga-	zelles
gh V	z e l z
ga-	zes
gh eI	z V z
ga-	zette
gh V	z e t
ga-	zing
gh eI	z I N
gaal
gh Q l
gab
gh { b
gab-	bard
gh V	b Q@ d
gab-	bert
gh {	b @r t
gab-	bing
gh {	b I N
gab-	bro-	ic
gh { b	r @U	I k
gab-	by
gh {	b i:
gabb-	ro
gh { b	r @U
gabe
gh eI b
gads
gh { d z
gads-	den
gh { d	z d V n
gae
gh aI
gae-	a
gh i:	V
gae-	lic
gh eI	l I k
gae-	ta
gh i:	t V
gae-	ta-	no
gh aI	t Q	n @U
gael
gh eI l
gaf
gh { f
gaff
gh { f
gaff-	ney
gh { f	n i:
gaffe
gh { f
gaffes
gh { f s
gag
gh { g
gag-	gle
gh {	g V l
gag-	li-	a-	no
gh Q g	l i:	Q	n @U
gag-	ne
gh eI	n i:
gag-	non
gh { n	j V n
gage
gh eI dZ
gagged
gh { g d
gags
gh { g z
gai-	a
gh aI	V
gai-	ly
gh eI	l i:
gai-	ner
gh eI	n @r
gai-	ners
gh eI	n @r z
gai-	ning
gh eI	n I N
gai-	nor
gh eI	n @r
gai-	ser
gh eI	z @r
gai-	ter
gh eI	t @r
gai-	ther
gh eI	T @r
gai-	thers-	burg
gh eI	T @r z	b @r g
gaige
gh eI dZ
gail
gh eI l
gail-	lard
gh eI	l @r d
gaile
gh eI l
gail's
gh eI l z
gain
gh eI n
gain-	ful
gh eI n	f V l
gain-	ful-	ly
gh eI n	f V	l i:
gain-	say
gh eI n	s eI
gained
gh eI n d
gaines
gh eI n z
gaines-	ville
gh eI n	z v I l
gains
gh eI n z
gair
gh e@
gait
gh eI t
gaj-	da
gh aI	d V
gal
gh { l
gal-	ban
gh { l	b V n
gal-	braith
gh { l	b r eI T
gal-	breath
gh { l	b r e T
gal-	la
gh {	l V
gal-	la-	ger
gh O:	l I	dZ @r
gal-	la-	gher
gh {	l V	g @r
gal-	la-	tin
gh {	l V	t I n
gal-	la-	way
gh O:	l V	w eI
gal-	lant
gh {	l V n t
gal-	lant-	ry
gh {	l V n	t r i:
gal-	lard
gh V	l Q@ d
gal-	las
gh {	l V z
gal-	lau-	det
gh {	l V	d e t
gal-	le-	gos
gh {	l I	g @U z
gal-	le-	on
gh {	l i:	V n
gal-	le-	ons
gh {	l i:	V n z
gal-	le-	ri-	a
gh {	l @r	i:	V
gal-	le-	ries
gh {	l @r	i: z
gal-	le-	ry
gh {	l @r	i:
gal-	le-	ry's
gh {	l @r	i: z
gal-	len
gh O:	l V n
gal-	ler
gh O:	l @r
gal-	let
gh {	l e t
gal-	ley
gh {	l i:
gal-	leys
gh {	l i: z
gal-	li
gh {	l i:
gal-	li-	a-	no
gh Q	l i:	Q	n @U
gal-	li-	gan
gh {	l I	g V n
gal-	li-	na
gh Q	l i:	n V
gal-	li-	um
gh {	l i:	V m
gal-	lia
gh { l	j V
gal-	lic
gh {	l I k
gal-	ling
gh O:	l I N
gal-	lion
gh { l	j V n
gal-	lo
gh {	l @U
gal-	lo-	ping
gh {	l V	p I N
gal-	lo-	way
gh {	l @U	w eI
gal-	lo-	ways
gh {	l @U	w eI z
gal-	lon
gh {	l V n
gal-	lons
gh {	l V n z
gal-	loon
gh V	l u: n
gal-	lop
gh {	l V p
gal-	loped
gh {	l V p t
gal-	lo's
gh {	l @U z
gal-	low
gh {	l @U
gal-	lows
gh {	l @U z
gal-	lup
gh {	l V p
gal-	lus
gh {	l V s
gal-	ton
gh { l	t V n
gal-	va-	ni-	zes
gh { l	v V	n aI	z V z
gal-	va-	ni-	zing
gh { l	v V	n aI	z I N
gal-	va-	nic
gh { l	v {	n I k
gal-	va-	nize
gh { l	v V	n aI z
gal-	va-	nized
gh { l	v V	n aI z d
gal-	van
gh Q l	v Q n
gal-	ven
gh Q l	v V n
gal-	ves-	ton
gh { l	v V s	t V n
gal-	vin
gh { l	v I n
gal-	vin's
gh { l	v I n z
gal-	way
gh Q l	w eI
gale
gh eI l
gales
gh eI l z
gale's
gh eI l z
gales-	burg
gh eI l	z b @r g
gall
gh O: l
gall-	blad-	der
gh O: l	b l {	d @r
gall-	man
gh O: l	m V n
gall-	stone
gh O: l	s t @U n
gall-	stones
gh Q l	s t @U n z
galle
gh eI l
galls
gh O: l z
gals
gh { l z
gals-	wor-	thy
gh { l	z w @r	D i:
galt
gh O: l t
gam-	b-	ling
gh { m	b V	l I N
gam-	ba
gh { m	b V
gam-	ber
gh { m	b @r
gam-	bi-	a
gh { m	b i:	V
gam-	bit
gh { m	b I t
gam-	bits
gh { m	b I t s
gam-	ble
gh { m	b V l
gam-	bled
gh { m	b V l d
gam-	bles
gh { m	b V l z
gam-	ble's
gh { m	b V l z
gam-	bone
gh Q m	b @U n
gam-	ma
gh {	m V
gam-	mon
gh {	m V n
gam-	mons
gh {	m V n z
gamb-	ler
gh { m	b l @r
gamb-	lers
gh { m	b l @r z
gamb-	ler's
gh { m	b l @r z
gamb-	rel
gh { m	b r V l
gamb-	rell
gh { m	b r V l
gamb-	rill
gh { m	b r I l
game
gh eI m
game-	ly
gh eI m	l i:
game-	show
gh eI m	S @U
games
gh eI m z
game's
gh eI m z
games-	man-	ship
gh eI m	z m V n	S I p
gamp
gh { m p
gan
gh { n
gan-	da
gh { n	d V
gan-	dalf
gh { n	d O: l f
gan-	der
gh { n	d @r
gan-	dhi
gh Q n	d i:
gan-	dhi's
gh Q n	d i: z
gan-	dol-	fo
gh Q n	d @U l	f @U
gan-	dy
gh { n	d i:
gan-	ger
gh {	N @r
gan-	ges
gh { n	dZ i: z
gan-	ging
gh {	N I N
gan-	ley
gh { n	l i:
gan-	nett
gh {	n V t
gan-	nett's
gh {	n V t s
gan-	non
gh {	n V n
gan-	ser
gh { n	s @r
gang
gh { N
gang-	ban-	ger
gh { N	b { N	g @r
gang-	ban-	gers
gh { N	b { N	g @r z
gang-	bus-	ter
gh { N	b V s	t @r
gang-	bus-	ters
gh { N	b V s	t @r z
gang-	li-	a
gh { N	g l i:	V
gang-	li-	o-	nic
gh { N	g l i:	Q	n I k
gang-	ly
gh { N	l i:
gange
gh { n dZ
gangp-	lank
gh { N	p l { N k
gangs
gh { N z
gang's
gh { N z
gangs-	ta
gh { N	s t V
gangs-	ter
gh { N	s t @r
gangs-	ters
gh { N	s t @r z
gans
gh { n z
gant
gh { n t
gant-	let
gh O: n	t l V t
gant-	ry
gh { n	t r i:
gantt
gh { n t
gap
gh { p
gape
gh eI p
gaps
gh { p s
gap's
gh { p s
gar
gh Q@
gar-	bage
gh Q@	b I dZ
gar-	ber
gh Q@	b @r
gar-	bers
gh Q@	b @r z
gar-	ble
gh Q@	b V l
gar-	bled
gh Q@	b V l d
gar-	bo
gh Q@	b @U
gar-	ceau
gh Q@	s @U
gar-	ci-	a
gh Q@	s i:	V
gar-	ci-	a's
gh Q@	s i:	V z
gar-	da
gh Q@	d V
gar-	de-	na
gh Q@	d i:	n V
gar-	de-	ner
gh Q@	d V	n @r
gar-	de-	ners
gh Q@	d V	n @r z
gar-	de-	ner's
gh Q@	d V	n @r z
gar-	de-	nia
gh Q@	d i: n	j V
gar-	de-	nias
gh Q@	d i: n	j V z
gar-	de-	ning
gh Q@	d V	n I N
gar-	den
gh Q@	d V n
gar-	dened
gh Q@	d V n d
gar-	dens
gh Q@	d V n z
gar-	lan
gh Q@	l V n
gar-	land
gh Q@	l V n d
gar-	li-	cky
gh Q@	l I	k i:
gar-	lic
gh Q@	l I k
gar-	ling
gh Q@	l I N
gar-	ment
gh Q@	m V n t
gar-	ments
gh Q@	m V n t s
gar-	ne-	ring
gh Q@	n @r	I N
gar-	neau
gh Q@	n @U
gar-	ner
gh Q@	n @r
gar-	nered
gh Q@	n @r d
gar-	ners
gh Q@	n @r z
gar-	net
gh Q@	n V t
gar-	nett
gh Q@	n e t
gar-	nette
gh Q@	n e t
gar-	ni-	shes
gh Q@	n I	S V z
gar-	nish
gh Q@	n I S
gar-	nish-	ment
gh Q@	n I S	m V n t
gar-	nished
gh Q@	n I S t
gar-	rard
gh {	r @r d
gar-	ratt
gh e@	V t
gar-	ret
gh e@	V t
gar-	ret-	son
gh {	r V t	s V n
gar-	rets
gh e@	V t s
gar-	ret's
gh e@	V t s
gar-	rett
gh e@	V t
gar-	rett's
gh e@	V t z
gar-	ri-	gues
gh Q@	i:	g e s
gar-	ri-	son
gh {	r I	s V n
gar-	ri-	soned
gh {	r I	s V n d
gar-	ri-	ty
gh e@	I	t i:
gar-	rick
gh e@	I k
gar-	ris
gh {	r I s
gar-	ron
gh {	r V n
gar-	rott
gh {	r V t
gar-	ru-	lous
gh e@	V	l V s
gar-	ry
gh {	r i:
gar-	son
gh Q@	s V n
gar-	ten
gh Q@	t V n
gar-	ter
gh Q@	t @r
gar-	ters
gh Q@	t @r z
gar-	vey
gh Q@	v i:
gar-	vie
gh Q@	v i:
gar-	vin
gh Q@	v I n
gar-	win
gh Q@	w I n
gar-	wood
gh Q@	w U d
gar-	za
gh Q@	z V
gar-	zon
gh Q@	z V n
garb
gh Q@ b
garbe
gh Q@ b
garbed
gh Q@ b d
gard
gh Q@ d
garde
gh Q@ d
garn
gh Q@ n
garnes
gh Q@ n z
gars
gh Q@ z
gars-	ton
gh Q@ s	t V n
gart-	ner
gh Q@ t	n @r
garth
gh Q@ T
gas
gh { s
gas-	con
gh { s	k V n
gas-	cons
gh { s	k V n z
gas-	kell
gh { s	k V l
gas-	ket
gh { s	k V t
gas-	kets
gh { s	k V t s
gas-	kill
gh { s	k I l
gas-	kin
gh { s	k I n
gas-	kins
gh { s	k I n z
gas-	light
gh { s	l aI t
gas-	par
gh { s	p @r
gas-	pard
gh V s	p Q@ d
gas-	pe
gh { s	p i:
gas-	per
gh { s	p @r
gas-	ping
gh { s	p I N
gas-	sa-	way
gh {	s V	w eI
gas-	ser
gh {	s @r
gas-	ses
gh {	s V z
gas-	sing
gh {	s I N
gas-	ter
gh { s	t @r
gas-	ti-	neau
gh { s	t I	n @U
gas-	to-	ni-	a
gh V s	t @U	n i:	V
gas-	ton
gh { s	t V n
gas-	ton's
gh { s	t V n z
gash
gh { S
gashed
gh { S t
gasp
gh { s p
gasped
gh { s p t
gasps
gh { s p s
gass
gh { s
gass-	man
gh { s	m V n
gassed
gh { s t
gast
gh { s t
gast-	ri-	tis
gh { s	t r aI	t I s
gast-	ric
gh { s	t r I k
gast-	ro-	in-	tes-	ti-	nal
gh { s	t r @U	I n	t e s	t I	n V l
gast-	ro-	no-	mic
gh V s	t r Q	n Q	m I k
gast-	ro-	no-	my
gh { s	t r Q	n V	m i:
gast-	ro-	scope
gh { s	t r V s	k @U p
gast-	ro-	vas-	cu-	lar
gh { s	t r @U	v { s	k j V	l @r
gast-	ru-	la-	tion
gh { s	t r V	l eI	S V n
gast-	ru-	late
gh { s	t r V	l eI t
gat
gh { t
gat-	ling
gh { t	l I N
gat-	ling's
gh { t	l I N z
gat-	ten
gh {	t V n
gat-	ting
gh {	t I N
gat-	wick
gh { t	w I k
gatch
gh { tS
gate
gh eI t
gate-	kee-	per
gh eI t	k i:	p @r
gate-	kee-	pers
gh eI t	k i:	p @r z
gate-	way
gh eI t	w eI
gate-	ways
gh eI t	w eI z
gate-	way's
gh eI t	w eI z
gate-	wood
gh eI t	w U d
gates
gh eI t s
gath
gh { T
gats-	by
gh { t	s b i:
gatt
gh { t
gatzke
gh { t s k
gau
gh @U
gau-	cher
gh @U	S @r
gau-	cho
gh aU	tS @U
gau-	chos
gh aU	tS @U z
gau-	det
gh @U	d e t
gau-	dette
gh @U	d e t
gau-	dy
gh O:	d i:
gau-	ger
gh eI	dZ @r
gau-	ges
gh eI	dZ V z
gau-	ghan
gh O:	V n
gau-	ging
gh eI	dZ I N
gau-	guin
gh O: g	w I n
gau-	lin
gh @U	l { n
gau-	thi-	er
gh aU	T i:	@r
gau-	ti-	er
gh aU	t i:	@r
gaub
gh O: b
gauche
gh @U S
gauge
gh eI dZ
gauged
gh eI dZ d
gaul
gh O: l
gaul-	ding
gh O: l	d I N
gaul-	list
gh O:	l I s t
gaul-	tier
gh @U l	t j eI
gaulle
gh O: l
gauls
gh O: l z
gault
gh O: l t
gaunt
gh O: n t
gaunt-	let
gh O: n	t l V t
gaunt-	ness
gh O: n	t n V s
gaus
gh O: z
gaus-	man
gh aU s	m V n
gause
gh O: z
gauss
gh aU s
gaut
gh O: t
gauze
gh O: z
gave
gh eI v
gaw
gh O:
gaw-	ker
gh Q	k @r
gaw-	kers
gh Q	k @r z
gaw-	king
gh O:	k I N
gaw-	ky
gh O:	k i:
gawk
gh O: k
gay
gh eI
gay-	ler
gh eI	l @r
gay-	lor
gh eI	l @r
gay-	lord
gh eI	l O@ d
gay-	ner
gh eI	n @r
gay-	ness
gh eI	n V s
gay-	nor
gh eI	n @r
gaye
gh eI
gayle
gh eI l
gays
gh eI z
gaz
gh Q z
gaze
gh eI z
gazed
gh eI z d
ge-	b-	ler
gh e	b V	l @r
ge-	bel
gh e	b V l
ge-	la-	si-	a
dZ e	l Q	s i:	V
ge-	la-	ti-	nous
dZ V	l {	t V	n V s
ge-	la-	tin
dZ e	l V	t V n
ge-	la-	tine
dZ e	l V	t i: n
ge-	lett
dZ e	l e t
ge-	mi-	na
gh e	m i:	n V
ge-	mi-	nate
dZ e	m I	n eI t
ge-	mi-	ni
dZ e	m I	n aI
ge-	ne-	ra
dZ e	n @r	V
ge-	ne-	ra-	li-	ties
dZ e	n @r	{	l I	t i: z
ge-	ne-	ra-	li-	ty
dZ e	n @r	{	l I	t i:
ge-	ne-	ra-	li-	za-	tion
dZ e	n @r	V	l V	z eI	S V n
)"
R"(ge-	ne-	ra-	li-	za-	tions
dZ e	n @r	V	l V	z eI	S V n z
ge-	ne-	ra-	li-	zing
dZ e	n @r	V	l aI	z I N
ge-	ne-	ra-	lis-	si-	mo
dZ e	n e@	V	l I	s V	m @U
ge-	ne-	ra-	list
dZ e	n @r	V	l V s t
ge-	ne-	ra-	lists
dZ e	n @r	V	l V s t s
ge-	ne-	ra-	lize
dZ e	n @r	V	l aI z
ge-	ne-	ra-	lized
dZ e	n @r	V	l aI z d
ge-	ne-	ra-	ted
dZ e	n @r	eI	t V d
ge-	ne-	ra-	ting
dZ e	n @r	eI	t I N
ge-	ne-	ra-	tio-	nal
dZ e	n @r	eI	S V	n V l
ge-	ne-	ra-	tio-	nal-	ly
dZ e	n @r	eI	S V	n V	l i:
ge-	ne-	ra-	tion
dZ e	n @r	eI	S V n
ge-	ne-	ra-	tions
dZ e	n @r	eI	S V n z
ge-	ne-	ra-	tion's
dZ e	n @r	eI	S V n z
ge-	ne-	ra-	tive
dZ e	n @r	V	t I v
ge-	ne-	ra-	tor
dZ e	n @r	eI	t @r
ge-	ne-	ra-	tors
dZ e	n @r	eI	t @r z
ge-	ne-	ral
dZ e	n @r	V l
ge-	ne-	ral-	ly
dZ e	n @r	V	l i:
ge-	ne-	ral-	ship
dZ e	n @r	V l	S I p
ge-	ne-	rale
dZ e	n @r	{ l
ge-	ne-	rals
dZ e	n @r	V l z
ge-	ne-	ral's
dZ e	n @r	V l z
ge-	ne-	rate
dZ e	n @r	eI t
ge-	ne-	rates
dZ e	n @r	eI t s
ge-	ne-	ric
dZ V	n e@	I k
ge-	ne-	rical-	ly
dZ V	n e@	I k	l i:
ge-	ne-	rics
dZ V	n e@	I k s
ge-	ne-	ro-	si-	ty
dZ e	n @r	Q	s I	t i:
ge-	ne-	rous
dZ e	n @r	V s
ge-	ne-	rous-	ly
dZ e	n @r	V s	l i:
ge-	ne-	see
dZ e	n V	s i:
ge-	ne-	sis
dZ e	n V	s V s
ge-	ne-	ti-	cist
dZ V	n e	t V	s V s t
ge-	ne-	ti-	cists
dZ V	n e	t V	s V s t s
ge-	ne-	tic
dZ V	n e	t I k
ge-	ne-	tical-	ly
dZ V	n e	t I k	l i:
ge-	ne-	tics
dZ V	n e	t I k s
ge-	ne-	va
dZ V	n i:	v V
ge-	ne-	vieve
dZ e	n V	v i: v
ge-	neen
dZ V	n i: n
ge-	nes-	co
dZ e	n e s	k @U
ge-	net
dZ e	n e t
ge-	neve
dZ V	n i: v
ge-	ni-	a-	li-	ty
dZ i:	n i:	{	l I	t i:
ge-	ni-	ta-	lia
dZ e	n I	t Q l	j V
ge-	ni-	tal
dZ e	n I	t V l
ge-	ni-	tals
dZ e	n I	t V l z
ge-	nial
dZ i: n	j V l
ge-	nie
dZ i:	n i:
ge-	niu-	ses
dZ i: n	j V	s V z
ge-	nius
dZ i: n	j V s
ge-	no
dZ i:	n @U
ge-	no-	a
dZ e	n @U	V
ge-	no-	ci-	dal
dZ e	n V	s aI	d V l
ge-	no-	cide
dZ e	n V	s aI d
ge-	no-	type
dZ e	n V	t aI p
ge-	no-	types
dZ e	n V	t aI p s
ge-	no-	va
dZ e	n @U	v V
ge-	no-	vese
dZ e	n V	v i: z
ge-	noese
dZ e	n @U s
ge-	nome
dZ i:	n @U m
ge-	nu-	ine
dZ e n	j V	w V n
ge-	nu-	ine-	ly
dZ e n	j V	w V n	l i:
ge-	nu-	ine-	ness
dZ e n	j V	w V	n V s
ge-	nus
dZ i:	n V s
ge-	o
dZ i:	@U
ge-	o-	cent-	ric
dZ i:	@U	s e n	t r I k
ge-	o-	che-	mis-	try
dZ i:	@U	k e	m I s	t r i:
ge-	o-	de-	sic
dZ i:	V	d e	s I k
ge-	o-	de-	sy
dZ i:	Q	d V	s i:
ge-	o-	gra-	pher
dZ i:	Q g	r V	f @r
ge-	o-	gra-	phi-	cal
dZ i:	V g	r {	f I	k V l
ge-	o-	gra-	phi-	cal-	ly
dZ i:	V g	r {	f I	k V	l i:
ge-	o-	gra-	phic
dZ i:	V g	r {	f I k
ge-	o-	gra-	phy
dZ i:	Q g	r V	f i:
ge-	o-	lo-	gi-	cal
dZ i:	V	l Q	dZ I	k V l
ge-	o-	lo-	gic
dZ i:	V	l Q	dZ I k
ge-	o-	lo-	gist
dZ i:	Q	l V	dZ V s t
ge-	o-	lo-	gists
dZ i:	Q	l V	dZ V s t s
ge-	o-	lo-	gy
dZ i:	Q	l V	dZ i:
ge-	o-	mag-	ne-	tic
dZ i:	@U	m { g	n e	t I k
ge-	o-	met-	ri-	cal
dZ i:	V	m e t	r I	k V l
ge-	o-	met-	ric
dZ i:	V	m e t	r I k
ge-	o-	met-	rical-	ly
dZ i:	V	m e t	r I k	l i:
ge-	o-	met-	rics
dZ i:	V	m e t	r I k s
ge-	o-	met-	ries
dZ i:	Q	m V t	r i: z
ge-	o-	met-	ry
dZ i:	Q	m V t	r i:
ge-	o-	mor-	pho-	lo-	gy
dZ i:	V	m O@	f Q	l V	dZ i:
ge-	o-	phy-	si-	cal
dZ i:	@U	f I	z I	k V l
ge-	o-	po-	li-	ti-	cal
dZ i:	@U	p V	l I	t I	k V l
ge-	o-	po-	li-	tic
dZ i:	@U	p Q	l I	t I k
ge-	o-	po-	li-	tical-	ly
dZ i:	@U	p V	l I	t I k	l i:
ge-	o-	po-	li-	tics
dZ i:	@U	p Q	l I	t I k s
ge-	o-	syn-	cline
dZ i:	@U	s I n	k l aI n
ge-	o-	ta-	xis
dZ i:	@U	t { k	s I s
ge-	o-	ther-	mal
dZ i:	@U	T @r	m V l
ge-	o-	tro-	pi-	sm
dZ i:	Q t	r V	p I	z V m
ge-	o-	tro-	pic
dZ i:	V t	r Q	p I k
ge-	oid
dZ i:	OI d
ge-	on
dZ i:	Q n
ge-	or-	die
dZ i:	@r	d i:
ge-	or-	gi
dZ i:	Q@	dZ i:
ge-	org
gh eI	O@ g
ge-	os-	tro-	phic
dZ i:	@U s	t r Q	f I k
ge-	ra
dZ e@	V
ge-	ra-	ni-	um
dZ @r	eI	n i:	V m
ge-	ra-	ni-	ums
dZ @r	eI	n i:	V m z
ge-	rais
dZ @r	eI
ge-	ral-	di-	na
dZ @r	Q l	d i:	n V
ge-	ral-	dine
dZ e@	V l	d i: n
ge-	rald
dZ e@	V l d
ge-	rar-	do
dZ @r	Q@	d @U
ge-	rard
dZ @r	Q@ d
ge-	ri-	at-	ri-	cian
dZ e@	i:	V t	r I	S V n
ge-	ri-	at-	ri-	cians
dZ e@	i:	V t	r I	S V n z
ge-	ri-	at-	ric
dZ e@	i:	{ t	r I k
ge-	ri-	at-	rics
dZ e@	i:	{ t	r I k s
ge-	ring
gh I@	I N
ge-	ro-	ni-	mo
dZ V	r O:	n V	m @U
ge-	rome
gh e@	V m
ge-	ron-	to-	lo-	gist
dZ e@	V n	t Q	l V	dZ V s t
ge-	ron-	to-	lo-	gy
dZ e@	V n	t Q	l V	dZ i:
ge-	ry
dZ e@	i:
ge-	sell
gh e	s V l
ge-	sell-	schaft
gh V	s e l	S { f t
ge-	sell's
gh e	s V l z
ge-	ta-	way
gh e	t V	w eI
ge-	ta-	ways
gh e	t V	w eI z
ge-	vaert
gh V	v e@ t
ge-	wirtz
gh u:	@r t s
ge-	yer
gh eI	@r
gea-	ring
gh I@	I N
gea-	ry
gh I@	i:
gean
dZ i: n
gear
gh I@
gear-	bo-	xes
gh I@	b Q k	s V z
gear-	box
gh I@	b Q k s
gear-	hart
gh I@	h Q@ t
geared
gh I@ d
gears
gh I@ z
gear's
gh I@ z
geb-	bie
dZ e	b i:
geb-	hardt
gh e b	h Q@ t
gec-	ko
gh e	k @U
gec-	kos
gh e	k @U z
geck
dZ e k
ged
gh e d
ged-	des
gh e	d V s
gee
dZ i:
gee-	ing
dZ i:	I N
gee-	ky
gh i:	k i:
gee-	sey
gh i:	s i:
geek
gh i: k
geeks
gh i: k s
geer
gh I@
geerts
gh I@ t s
gees
dZ i: s
gee's
dZ i: z
geese
gh i: s
geez
dZ i: z
gef-	fen
gh e	f V n
geff-	ner
gh e f	n @r
gegg
dZ e g
geh-	man
gh e	m V n
geh-	rig
gh e@	I g
geh-	rig's
gh e@	I g z
gei-	bel
gh aI	b V l
gei-	er
gh aI	@r
gei-	ger
gh aI	g @r
gei-	gy
gh aI	g i:
gei-	gy's
gh aI	g i: z
gei-	sel
gh aI	s V l
gei-	sha
gh eI	S V
geis
gh aI z
geiss
gh aI s
geiss-	ler
gh aI s	l @r
geist
gh aI s t
gek-	ko
gh e	k @U
gel
dZ e l
gel-	der
gh e l	d @r
gel-	ler
gh e	l @r
gel-	lert
gh e	l @r t
gel-	man
gh e l	m V n
gelb
dZ e l b
gell
dZ e l
gell-	man
gh e l	m V n
gels
dZ e l z
gem
dZ e m
gem-	ma
dZ e	m V
gem-	mell
gh e	m V l
gem-	mer
gh e	m @r
gen-	ghis
dZ e N	h I s
gen-	na
dZ e	n V
gen-	na-	ro
dZ V	n Q@	@U
gen-	ni-	fer
dZ e	n I	f @r
gen-	re
Z Q n	r V
gen-	res
Z Q n	r V z
gen-	s-	ler
gh e n	s V	l @r
gen-	son
dZ e n	s V n
gen-	t-	lest
dZ e n	t V	l V s t
gen-	teel
dZ e n	t i: l
gen-	ti-	li-	ty
dZ e n	t I	l I	t i:
gen-	tian
dZ e n	S V n
gen-	tile
dZ e n	t aI l
gen-	tiles
dZ e n	t aI l z
gen-	tile's
dZ e n	t aI l z
gen-	tle
dZ e n	t V l
gen-	tle-	man
dZ e n	t V l	m V n
gen-	tle-	man-	ly
dZ e n	t V l	m V n	l i:
gen-	tle-	man's
dZ e n	t V l	m V n z
gen-	tle-	men
dZ e n	t V l	m e n
gen-	tle-	men's
dZ e n	t V l	m e n z
gen-	tle-	ness
dZ e n	t V l	n V s
gen-	tle-	wo-	man
dZ e n	t V l	w U	m V n
gen-	tle-	wo-	man's
dZ e n	t V l	w U	m V n z
gen-	tle-	wo-	men
dZ e n	t V l	w I	m V n
gen-	tle-	wo-	men's
dZ e n	t V l	w I	m V n z
gen-	tles
dZ e n	t V l z
genes
dZ i: n z
gene's
dZ i: n z
genk
dZ e N k
gens
dZ e n z
gent
dZ e n t
gent-	ler
dZ e n	t l @r
gent-	ly
dZ e n	t l i:
gent-	ri-	fi-	ca-	tion
dZ e n	t r I	f I	k eI	S V n
gent-	ri-	fied
dZ e n	t r I	f aI d
gent-	ri-	fy
dZ e n	t r I	f aI
gent-	ri-	fy-	ing
dZ e n	t r I	f aI	I N
gent-	ry
dZ e n	t r i:
geof-	frey
dZ e f	r i:
geof-	frey's
dZ e f	r i: z
geoff
dZ e f
geor-	gann
dZ O@	dZ { n
geor-	gene
dZ O@	dZ i: n
geor-	ges
dZ O@	dZ V z
geor-	ge's
dZ O@	dZ V z
geor-	gette
dZ O@	dZ e t
geor-	gi-	a-	na
dZ O@	dZ i:	{	n V
geor-	gi-	na
dZ O@	dZ i:	n V
geor-	gia
dZ O@	dZ V
geor-	gian
dZ O@	dZ V n
geor-	gians
dZ O@	dZ V n z
geor-	gia's
dZ O@	dZ V z
geor-	gie
dZ O@	dZ i:
geor-	gine
dZ O@	dZ i: n
geor-	gy
dZ O@	dZ i:
george
dZ O@ dZ
george-	town
dZ O@ dZ	t aU n
ger-	ber
gh @r	b @r
ger-	ber's
gh @r	b @r z
ger-	da
gh @r	d V
ger-	ger
gh @r	g @r
ger-	hard
gh @r	h Q@ d
ger-	hardt
gh @r	h Q@ t
ger-	hart
gh @r	h Q@ t
ger-	kin
dZ @r	k I n
ger-	lach
gh @r	l V k
ger-	ma-	ni-	a
dZ @r	m eI	n i:	V
ger-	ma-	nic
dZ @r	m {	n I k
ger-	ma-	no
dZ @r	m Q	n @U
ger-	ma-	ny
dZ @r	m V	n i:
ger-	ma-	ny's
dZ @r	m V	n i: z
ger-	main
dZ @r	m eI n
ger-	maine
Z @r	m eI n
ger-	main's
dZ @r	m eI n z
ger-	man
dZ @r	m V n
ger-	man-	town
dZ @r	m V n	t aU n
ger-	mane
dZ @r	m eI n
ger-	mann
gh @r	m V n
ger-	mans
dZ @r	m V n z
ger-	man's
dZ @r	m V n z
ger-	mi-	cide
dZ @r	m I	s aI d
ger-	mi-	na-	ted
dZ @r	m I	n eI	t I d
ger-	mi-	na-	tion
dZ @r	m I	n eI	S V n
ger-	mi-	nate
dZ @r	m I	n eI t
ger-	mi-	ston
dZ @r	m I s	t Q n
ger-	mi-	ston's
dZ @r	m I s	t Q n z
ger-	rald
dZ e@	V l d
ger-	ri
dZ e@	i:
ger-	rie
dZ e@	i:
ger-	rit
dZ e@	I t
ger-	ry
dZ e@	i:
ger-	ry-	man-	de-	ring
dZ e@	i:	m { n	d @r	I N
ger-	ry-	man-	der
dZ e@	i:	m { n	d @r
ger-	ry-	man-	dered
dZ e@	i:	m { n	d @r d
ger-	ry-	man-	ders
dZ e@	i:	m { n	d @r z
ger-	ry's
dZ e@	i: z
ger-	shon
gh @r	S V n
ger-	son
dZ @r	s V n
ger-	tie
dZ @r	t i:
ger-	ty
dZ @r	t i:
ger-	vais
Z @r	v eI
ger-	vase
gh @r	v V s
gerd
gh @r d
gere
dZ I@
germ
dZ @r m
germs
dZ @r m z
gers-	tein
gh @r s	t aI n
gersh-	win
gh @r S	w I n
gersh-	win's
gh @r S	w I n z
gerst-	ner
gh @r s	t n @r
gerst-	ner's
gh @r s	t n @r z
gert
gh @r t
gert-	ner
gh @r t	n @r
gert-	rud
gh @r t	r u: d
gert-	rude
gh @r t	r u: d
ges-	ner
gh e s	n @r
ges-	ta-	po
gh V s	t Q	p @U
ges-	ta-	tion
dZ e s	t eI	S V n
ges-	tate
dZ e s	t eI t
ges-	tu-	ring
dZ e s	tS @r	I N
ges-	ture
dZ e s	tS @r
ges-	tured
dZ e s	tS @r d
ges-	tures
dZ e s	tS @r z
gess
dZ e s
gess-	ner
gh e s	n @r
gest
dZ e s t
get
gh e t
get-	ter
gh e	t @r
get-	ters
gh e	t @r z
get-	ting
gh e	t I N
get-	tings
gh e	t I N z
get-	to-	ge-	ther
gh e t	t V	g e	D @r
get-	ty
gh e	t i:
get-	ty's
gh e	t i: z
get-	tys-	burg
gh e	t i: z	b @r g
get-	well
gh e t	w e l
gets
gh e t s
getz
gh e t s
gey-	ser
gh aI	z @r
gey-	sers
gh aI	z @r z
gha-	na
gh {	n V
gha-	nai-	an
gh V	n aI	V n
gha-	nai-	ans
gh V	n aI	V n z
gha-	na's
gh {	n V z
ghast-	li-	ness
gh { s	t l i:	n V s
ghast-	ly
gh { s	t l i:
ghe-	rar-	di
gh @r	Q@	d i:
ghee
gh i:
gheen
gh i: n
ghent
gh e n t
ghet-	to
gh e	t @U
ghet-	tos
gh e	t @U z
ghost
gh @U s t
gi-	an
dZ i:	Q n
gi-	ant
dZ aI	V n t
gi-	ants
dZ aI	V n t s
gi-	ant's
dZ aI	V n t s
gi-	ants'
dZ aI	V n t s
gi-	bert
gh I	b @r t
gi-	bral-	tar
dZ V b	r O: l	t @r
gi-	de-	on
gh I	d i:	V n
gi-	g-	gly
gh I	g V	l i:
gi-	ga-	byte
gh I	g V	b aI t
gi-	ga-	bytes
gh I	g V	b aI t s
gi-	ga-	flop
gh I	g V f	l Q p
gi-	ga-	flops
gh I	g V f	l Q p s
gi-	gan-	te
dZ i:	g Q n	t i:
gi-	gan-	tic
dZ aI	g { n	t I k
gi-	gi
dZ i:	dZ i:
gi-	got
dZ I	g V t
gi-	got's
dZ I	g V t s
gi-	gu-	ere
dZ i:	g e@	eI
gi-	lead
gh I	l i: d
gi-	na
dZ i:	n V
gi-	na's
dZ i:	n V z
gi-	nev-	ra
dZ V	n e v	r V
gi-	no
dZ i:	n @U
gi-	o-	van-	ni
dZ i:	@U	v Q	n i:
gi-	o-	van-	ni's
dZ i:	@U	v Q	n i: z
gi-	ral-	do
dZ I@	Q l	d @U
gi-	rar-	di
dZ I@	Q@	d i:
gi-	rard
dZ @r	Q@ d
gi-	raud
Z aI	r @U
gi-	ro-	la-	mo
dZ I@	@U	l Q	m @U
gi-	ron
gh O@	V n
gi-	s-	ler
gh I	s V	l @r
gi-	se-	la
gh i:	z V	l V
gi-	sel-	la
dZ I	s e	l V
gi-	selle
Z I	s e l
gi-	ta-	na
dZ i:	t {	n V
gi-	ta-	no
gh I	t Q	n @U
gi-	thens
gh I	T V n z
gi-	vea-	way
gh I	v V	w eI
gi-	vea-	ways
gh I	v V	w eI z
gi-	ven
gh I	v V n
gi-	ven-	chy
gh I	v e n	tS i:
gi-	ven-	ness
gh I	v V	n V s
gi-	vens
gh I	v V n z
gi-	ver
gh I	v @r
gi-	vers
gh I	v @r z
gi-	veth
gh I	v e T
gi-	ving
gh I	v I N
gi-	za
gh I	z V
gia-	cin-	ta
dZ Q	tS i: n	t V
gia-	co-	met-	ti
dZ V	k V	m e	t i:
gia-	co-	mo
dZ Q	k V	m @U
giai-	mo
dZ eI	m @U
gian-	ni
dZ Q	n i:
gian-	ni-	ni
dZ V	n i:	n i:
gib
gh I b
gib-	be-	rish
gh I	b @r	I S
gib-	bon
gh I	b V n
gib-	bons
gh I	b V n z
gib-	by
dZ I	b i:
gib-	let
dZ I b	l V t
gib-	son
gh I b	s V n
gib-	son's
gh I b	s V n z
gibb
dZ I b
gibbs
gh I b z
gibb's
gh I b z
gibe
dZ aI b
gid-	dings
gh I	d I N z
gid-	dy
gh I	d i:
gie-	fer
gh i:	f @r
gie-	secke
gh i:	s I k
giel-	gud
gh i: l	g V d
gies
gh i: z
gies-	sen
gh i: z	s V n
gif-	fard
gh I	f @r d
gif-	ferd
gh I	f @r d
gif-	ford
gh I	f @r d
gif-	ford's
gh I	f @r d z
gif-	fy
gh I	f i:
gif-	ted
gh I f	t V d
gif-	ting
gh I f	t I N
giff
gh I f
gift
gh I f t
gift-	ware
gh I f	t w e@
gifts
gh I f t s
gig
gh I g
gig-	g-	ling
gh I	g V	l I N
gig-	ging
gh I	g I N
gig-	gle
gh I	g V l
gig-	gled
gh I	g V l d
gig-	gles
gh I	g V l z
gig-	li-	o
dZ I g	l i:	@U
gig-	nac
gh I g	n V k
gigs
gh I g z
gil
gh I l
gil-	ber-	ta
dZ i: l	b e@	t V
gil-	ber-	ti-	na
dZ i: l	b @r	t i:	n V
gil-	ber-	ti-	ne
dZ i: l	b @r	t i:	n i:
gil-	ber-	to
gh I l	b e@	t @U
gil-	bert
gh I l	b @r t
gil-	bert-	son
gh I l	b @r t	s V n
gil-	berte
gh I l	b @r t
gil-	bert's
gh I l	b @r t s
gil-	by
gh I l	b i:
gil-	cr-	est
gh I l	k @r	I s t
gil-	da
gh I l	d V
gil-	de-	a
dZ i: l	d i:	V
gil-	ded
gh I l	d V d
gil-	den
gh I l	d V n
gil-	der
gh I l	d @r
gil-	der's
gh I l	d @r z
gil-	ding
gh I l	d I N
gil-	ford
gh I l	f @r d
gil-	lan
gh I	l V n
gil-	ler
gh I	l @r
gil-	lers
gh I	l @r z
gil-	les-	pie
gh V	l e s	p i:
gil-	let
gh I	l e t
gil-	lett
dZ I	l I t
gil-	lette
dZ V	l e t
gil-	lette's
dZ V	l e t s
gil-	ley
gh I	l i:
gil-	li-	am
gh I	l i:	V m
gil-	li-	an
dZ I	l i:	V n
gil-	li-	gan
gh I	l I	g V n
gil-	li-	gan's
gh I	l I	g V n z
gil-	lie
gh I	l i:
gil-	lies
gh I	l i: z
gil-	lin-	gham
gh I	l I N	h { m
gil-	ly
gh I	l i:
gil-	man
gh I l	m V n
gil-	mer
gh I l	m @r
gil-	more
gh I l	m O@
gil-	mour
Z I l	m U@
gil-	pin
gh I l	p I n
gil-	roy
gh I l	r OI
gil-	son
gh I l	s V n
gilch-	rist
gh I l	k r I s t
gild
gh I l d
gile
gh aI l
giles
dZ aI l z
gill
gh I l
gill-	ham
gh I l	h V m
gill-	man
gh I l	m V n
gill-	more
dZ i: l	m O@
gilles
Z i: l
gills
gh I l z
gill's
gh I l z
gilt
gh I l t
gilt-	ner
gh I l	t n @r
gilts
gh I l t s
gim-	bel
gh I m	b V l
gim-	me
gh I	m i:
gim-	mic-	ky
gh I	m I	k i:
gim-	mick
gh I	m I k
gim-	mick-	ry
gh I	m I k	r i:
gim-	micks
gh I	m I k s
gim-	pel
gh I m	p V l
gin
dZ I n
gin-	der
gh aI n	d @r
gin-	ge-	ry
dZ I n	dZ @r	i:
gin-	ger
dZ I n	dZ @r
gin-	ger-	bread
dZ I n	dZ @r b	r e d
gin-	ger-	ly
dZ I n	dZ @r	l i:
gin-	gles
dZ I N	g V l z
gin-	nie
dZ I	n i:
gin-	ning
dZ I	n I N
gin-	ny
dZ I	n i:
gin-	seng
dZ I n	s e N
gin-	su
gh I n	s u:
gin-	su's
gh I n	s u: z
gin-	za
gh I n	z V
ging
dZ I N
ging-	ham
gh I	N V m
ging-	hams
gh I	N V m z
ging-	ras
gh I N	g r V z
ging-	ri-	ch's
gh I N	g r I	tS V z
ging-	rich
gh I N	g r I tS
ginn
dZ I n
ginned
dZ I n d
gins-	berg
gh I n	s b @r g
gins-	burg
gh I n	z b @r g
gins-	burg's
gh I n	z b @r g z
gintz
gh I n t s
ginz-	berg
gh I n	z b @r g
gior-	da-	no
dZ O@	d Q	n @U
gior-	gi
dZ O@	dZ i:
gior-	gi-	o
dZ O@	dZ i:	@U
gior-	gia
dZ O@	dZ V
gip-	per
gh I	p @r
gip-	son
gh i: p	s V n
gir-	affe
dZ @r	{ f
gir-	affes
dZ @r	{ f s
gir-	d-	ler
gh @r	d V	l @r
gir-	der
gh @r	d @r
gir-	ders
gh @r	d @r z
gir-	ding
gh @r	d I N
gir-	dle
gh @r	d V l
gir-	gen-	ti
dZ I@	dZ e n	t i:
gir-	lie
gh @r	l i:
gir-	lish
gh @r	l I S
gir-	lish-	ly
gh @r	l I S	l i:
gir-	ton
gh @r	t V n
gir-	vin
gh @r	v I n
gird
gh @r d
girds
gh @r d z
gire
gh aI r
girl
gh @r l
girl-	friend
gh @r l	f r e n d
girl-	friends
gh @r l	f r e n d z
girl-	hood
gh @r l	h U d
girls
gh @r l z
girl's
gh @r l z
girt
gh @r t
girth
gh @r T
gis-	card
gh I s	k Q@ d
gish
dZ I S
gist
dZ I s t
git-	ter
gh I	t @r
giu-	li-	a-	ni
dZ u:	l i:	Q	n i:
giu-	li-	a-	ni's
dZ u:	l i:	Q	n i: z
giu-	li-	a-	no
dZ u:	l i:	Q	n @U
giu-	li-	o
dZ u:	l i:	@U
giu-	sep-	pe
dZ V	s e	p i:
giun-	ta
dZ u: n	t V
gius-	to
dZ u: s	t @U
give
gh I v
give-	back
gh aI v	b { k
give-	backs
gh aI v	b { k s
gives
gh I v z
giz-	mo
gh I z	m @U
giz-	mos
gh I z	m @U z
giz-	zard
gh I	z @r d
gla-	ci-	a-	ted
gh l eI	S i:	eI	t V d
gla-	ci-	a-	tion
gh l eI	S i:	eI	S V n
gla-	ci-	ate
gh l eI	S i:	eI t
gla-	cial
gh l eI	S V l
gla-	cier
gh l eI	S @r
gla-	ciers
gh l eI	S @r z
gla-	cier's
gh l eI	S @r z
gla-	cis
gh l eI	s I s
gla-	di-	a-	tor
gh l {	d i:	eI	t @r
gla-	di-	a-	tors
gh l {	d i:	eI	t @r z
gla-	di-	o-	lus
gh l {	d i:	@U	l V s
gla-	dis
gh l {	d I s
gla-	dys
gh l {	d I s
gla-	mo-	ri-	zing
gh l {	m @r	aI	z I N
gla-	mo-	rize
gh l {	m @r	aI z
gla-	mo-	rized
gh l {	m @r	aI z d
gla-	mo-	rous
gh l {	m @r	V s
gla-	mor
gh l {	m @r
gla-	mour
gh l {	m @r
gla-	ring
gh l e@	I N
gla-	ser
gh l eI	z @r
gla-	vin
gh l {	v I n
gla-	xo
gh l { k	s @U
gla-	xo's
gh l { k	s @U z
gla-	zer
gh l eI	z @r
gla-	zes
gh l eI	z V z
gla-	zi-	er
gh l eI	z i:	@r
gla-	zing
gh l eI	z I N
gla-	zu-	nov
gh l {	z u:	n Q v
glaab
gh l Q b
glace
gh l eI s
glad
gh l { d
glad-	den
gh l {	d V n
glad-	ding
gh l {	d I N
glad-	ly
gh l { d	l i:
glad-	win
gh l { d	w I n
glade
gh l eI d
glades
gh l eI d z
glads-	tone
gh l { d	s t @U n
glads-	tones
gh l { d	s t @U n z
glan-	ces
gh l { n	s V z
glan-	cing
gh l { n	s I N
glan-	der
gh l { n	d @r
glan-	du-	lar
gh l { n	dZ V	l @r
glan-	ville
gh l { n	v I l
glance
gh l { n s
glanced
gh l { n s t
gland
gh l { n d
glands
gh l { n d z
glantz
gh l { n t s
glare
gh l e@
glared
gh l e@ d
glares
gh l e@ z
glas-	co
gh l Q s	k @U
glas-	gow
gh l { s	k @U
glas-	nost
gh l { s	n Q s t
)"
R"(glas-	ser
gh l {	s @r
glas-	ses
gh l {	s V z
glas-	s's
gh l {	s V z
glas-	sy
gh l {	s i:
glass
gh l { s
glass-	blo-	wer
gh l { s	b l @U	@r
glass-	blo-	wers
gh l { s	b l @U	@r z
glass-	blo-	wing
gh l { s	b l @U	I N
glass-	blow-	ing
gh l { s	b l @U	I N
glass-	co
gh l { s	k @U
glass-	like
gh l { s	l aI k
glass-	ma-	ker
gh l { s	m eI	k @r
glass-	ma-	king
gh l { s	m eI	k I N
glass-	man
gh l { s	m { n
glass-	ware
gh l { s	w e@
glassed
gh l { s t
glau-	ber
gh l aU	b @r
glau-	co-	ma
gh l O:	k @U	m V
glaze
gh l eI z
glazed
gh l eI z d
gle-	ba
gh l i:	b V
gle-	da
gh l eI	d V
glea-	ming
gh l i:	m I N
glea-	son
gh l i:	s V n
glea-	son's
gh l i:	s V n z
gleam
gh l i: m
gleamed
gh l i: m d
gleams
gh l i: m z
glean
gh l i: n
gleaned
gh l i: n d
gleave
gh l i: v
gleaves
gh l i: v z
glee
gh l i:
glee-	ful
gh l i:	f V l
glee-	ful-	ly
gh l i:	f V	l i:
glee-	son
gh l i:	z V n
gleich
gh l aI k
glen
gh l e n
glen-	brook
gh l e n	b r U k
glen-	view
gh l e n	v j u:
glen-	ville
gh l e n	v I l
glen-	wood
gh l e n	w U d
glen-	wood's
gh l e n	w U d z
glens
gh l e n z
glew
gh l u:
gli-	ded
gh l aI	d V d
gli-	der
gh l aI	d @r
gli-	ders
gh l aI	d @r z
gli-	ding
gh l aI	d I N
gli-	ste-	ning
gh l I	s V	n I N
gli-	sten
gh l I	s V n
gli-	stened
gh l I	s V n d
glib
gh l I b
glib-	ly
gh l I b	l i:
glick
gh l I k
glick-	man
gh l I k	m V n
glid-	den
gh l I	d V n
glide
gh l aI d
glides
gh l aI d z
glim-	me-	ring
gh l I	m @r	I N
glim-	mer
gh l I	m @r
glim-	mers
gh l I	m @r z
glimp-	ses
gh l I m	p s V z
glimpse
gh l I m p s
glimpsed
gh l I m p s t
glin-	ka
gh l I N	k V
glin-	ting
gh l I n	t I N
glint
gh l I n t
glis-	san-	di
gh l V	s Q n	d i:
glit-	ches
gh l I	tS V z
glit-	te-	ring
gh l I	t @r	I N
glit-	te-	ry
gh l I	t @r	i:
glit-	ter
gh l I	t @r
glit-	tered
gh l I	t @r d
glit-	ters
gh l I	t @r z
glit-	zy
gh l I t	s i:
glitch
gh l I tS
glitz
gh l I t s
glo-	ba-	li-	za-	tion
gh l @U	b V	l V	z eI	S V n
glo-	ba-	lize
gh l @U	b V	l aI z
glo-	ba-	lized
gh l @U	b V	l aI z d
glo-	bal
gh l @U	b V l
glo-	bal-	ly
gh l @U	b V	l i:
glo-	bu-	lar
gh l Q b	j V	l @r
glo-	bu-	lin
gh l Q b	j V	l V n
glo-	bu-	lins
gh l Q b	j V	l V n z
glo-	bus
gh l @U	b V s
glo-	cken-	spiel
gh l Q	k V n	s p i: l
glo-	ri
gh l O@	i:
glo-	ri-	a
gh l O@	i:	V
glo-	ri-	a-	na
gh l O@	i:	{	n V
glo-	ri-	ane
gh l O@	i:	{ n
glo-	ri-	fi-	ca-	tion
gh l O@	I	f I	k eI	S V n
glo-	ri-	fied
gh l O@	I	f aI d
glo-	ri-	fies
gh l O@	I	f aI z
glo-	ri-	fy
gh l O@	I	f aI
glo-	ri-	fy-	ing
gh l O@	I	f aI	I N
glo-	ri-	o-	so
gh l O@	i:	@U	s @U
glo-	ri-	ous
gh l O@	i:	V s
glo-	ri-	ous-	ly
gh l O@	i:	V s	l i:
glo-	ries
gh l O@	i: z
glo-	ry
gh l O@	i:
glo-	ver
gh l V	v @r
glo-	we-	ring
gh l aU	@r	I N
glo-	wer
gh l aU	@r
glo-	wered
gh l aU	@r d
glo-	wing
gh l @U	I N
glo-	wing-	ly
gh l @U	I N	l i:
gloa-	ming
gh l @U	m I N
gloa-	ted
gh l @U	t V d
gloa-	ting
gh l @U	t I N
gloat
gh l @U t
gloats
gh l @U t s
glob
gh l Q b
globe
gh l @U b
globes
gh l @U b z
globe's
gh l @U b z
globet-	rot-	ter
gh l @U b	t r O:	t @r
globet-	rot-	ters
gh l @U b	t r O:	t @r z
globs
gh l Q b z
glock
gh l Q k
glod
gh l Q d
gloo-	mi-	er
gh l u:	m i:	@r
gloo-	mi-	ly
gh l u:	m I	l i:
gloo-	my
gh l u:	m i:
gloom
gh l u: m
glop
gh l Q p
glop-	py
gh l Q	p i:
glor
gh l O@
glore
gh l O@
glos-	sa-	ry
gh l O:	s @r	i:
glos-	ser
gh l O:	s @r
glos-	ses
gh l O:	s V z
glos-	si-	er
gh l O:	s i:	@r
glos-	sy
gh l O:	s i:
glos-	ter
gh l Q s	t @r
gloss
gh l O: s
glossed
gh l O: s t
glot-	tal
gh l Q	t V l
glot-	tis
gh l Q	t I s
glouces-	ter
gh l O: s	t @r
glove
gh l V v
gloved
gh l V v d
gloves
gh l V v z
glow
gh l @U
glowed
gh l @U d
glows
gh l @U z
glu-	co-	side
gh l u:	k V	s aI d
glu-	co-	sides
gh l u:	k V	s aI d z
glu-	cose
gh l u:	k @U s
glu-	ta-	mate
gh l u:	t V	m eI t
glu-	ta-	mic
gh l u:	t {	m I k
glu-	ta-	ric
gh l u:	t {	r I k
glu-	ten
gh l u:	t V n
gluck
gh l V k
gluck's
gh l V k s
glue
gh l u:
glued
gh l u: d
glues
gh l u: z
glum
gh l V m
glum-	ly
gh l V m	l i:
glut
gh l V t
glut-	ted
gh l V	t V d
glut-	to-	nous
gh l V	t V	n V s
glut-	to-	ny
gh l V	t V	n i:
glut-	tons
gh l V	t V n z
gluts
gh l V t s
gly-	ce-	rol
gh l I	s @r	@U l
gly-	cine
gh l aI	s i: n
gly-	co-	gen
gh l aI	k V	dZ V n
gly-	co-	lic
gh l aI	k O:	l I k
gly-	co-	side
gh l aI	k V	s aI d
gly-	col
gh l aI	k O: l
gly-	nis
gh l I	n I s
glyn
gh l I n
glyn-	nis
gh l I	n I s
glynde-	bourne
gh l I n	d b O@ n
glynn
gh l I n
gmbh
gh V m
gna-	shing
n {	S I N
gna-	wing
n O:	I N
gnar-	ly
n Q@	l i:
gnarl
n Q@ l
gnarled
n Q@ l d
gnash
n { S
gnat
n { t
gnat-	cat-	cher
n { t	k {	tS @r
gnats
n { t s
gnaw
n O:
gnawed
n O: d
gnaws
n O: z
gneiss
n aI s
gno-	mic
n @U	m I k
gno-	mo-	nic
n @U	m Q	n I k
gno-	sti-	ci-	sm
n Q s	t I	s I	z V m
gnomes
n @U m z
gnu
n u:
go
gh @U
go-	a
gh @U	V
go-	ber
gh @U	b @r
go-	bert
gh Q	b @r t
go-	bi
gh @U	b i:
go-	cart
gh @U	k Q@ t
go-	da
gh @U	d V
go-	dard
gh V	d Q@ d
go-	dart
gh Q	d Q@ t
go-	di-	va
gh V	d aI	v V
go-	din
gh @U	d I n
go-	dot
gh @U	d V t
go-	down
gh @U	d aU n
go-	du-	nov
gh @U	d u:	n Q v
go-	e-	ring
gh @U	@r	I N
go-	er
gh @U	@r
go-	ers
gh @U	@r z
go-	go
gh @U	g @U
go-	ing
gh @U	I N
go-	ings
gh @U	I N z
go-	key
gh @U	k i:
go-	la
gh @U	l V
go-	lan
gh @U	l V n
go-	lem
gh @U	l V m
go-	li-	ath
gh V	l aI	V T
go-	li-	aths
gh @U	l i:	{ T s
go-	light-	ly
gh @U	l aI t	l i:
go-	lub
gh @U	l V b
go-	ma
gh @U	m V
go-	mer
gh @U	m @r
go-	mez
gh @U	m e z
go-	mor-	rah
gh V	m O@	V
go-	naives
gh @U	n aI v z
go-	ner
gh Q	n @r
go-	ni-	a
gh @U	n i:	V
go-	ni-	o-	me-	ter
gh @U	n i:	Q	m V	t @r
go-	ni-	um
gh @U	n i:	V m
go-	no-	coc-	cal
gh Q	n V	k Q	k V l
go-	nor-	rhe-	a
gh Q	n @r	i:	V
go-	pher
gh @U	f @r
go-	phers
gh @U	f @r z
go-	ra
gh O@	V
go-	ral
gh O@	V l
go-	ree
gh O@	i:
go-	ren
gh O@	V n
go-	rey
gh O@	i:
go-	ril-	la
gh @r	I	l V
go-	ril-	las
gh @r	I	l V z
go-	rin
gh O@	I n
go-	ring
gh O@	I N
go-	rum
gh O@	V m
go-	ry
gh O@	i:
go-	shawk
gh Q s	h O: k
go-	shen
gh @U	S V n
go-	tham
gh Q	T V m
go-	thard
gh Q	T @r d
go-	then-	burg
gh @U	t V n	b @r g
go-	thic
gh Q	T I k
go-	to
gh @U	t u:
go-	ver-	nance
gh V	v @r	n V n s
go-	ver-	ness
gh V	v @r	n V s
go-	ver-	ning
gh V	v @r	n I N
go-	ver-	nor
gh V	v @r	n @r
go-	ver-	nor-	ship
gh V	v @r	n @r	S I p
go-	ver-	nor-	ships
gh V	v @r	n @r	S I p s
go-	ver-	nors
gh V	v @r	n @r z
go-	ver-	nor's
gh V	v @r	n @r z
go-	vern
gh V	v @r n
go-	vern-	men-	tal
gh V	v @r	m e n	t V l
go-	vern-	men-	tal-	ly
gh V	v @r	m e n	t V	l i:
go-	vern-	ment
gh V	v @r	m V n t
go-	vern-	ments
gh V	v @r	m V n t s
go-	vern-	ment's
gh V	v @r	m V n t s
go-	verned
gh V	v @r n d
go-	verns
gh V	v @r n z
go-	wan
gh aU	V n
go-	wans
gh aU	V n z
go-	wen
gh aU	V n
go-	wer
gh aU	@r
go-	ya
gh OI	V
go-	yim
gh OI	I m
goa-	ded
gh @U	d V d
goa-	ding
gh @U	d I N
goa-	lie
gh @U	l i:
goa-	tee
gh @U	t i:
goad
gh @U d
goal
gh @U l
goal-	kee-	per
gh @U l	k i:	p @r
goal-	post
gh @U l	p @U s t
goals
gh @U l z
goan
gh @U n
goans
gh @U n z
goar
gh O@
goat
gh @U t
goats
gh @U t s
goat's
gh @U t s
gob
gh Q b
gob-	b-	ling
gh Q	b V	l I N
gob-	bl-	er
gh Q	b V	l @r
gob-	bl-	ers
gh Q	b V	l @r z
gob-	ble
gh Q	b V l
gob-	ble-	dy-	gook
gh Q	b V l	d i:	g U k
gob-	bled
gh Q	b V l d
gob-	let
gh Q b	l V t
gob-	lin
gh Q b	l I n
gob-	lins
gh Q b	l I n z
gobs
gh Q b z
god
gh Q d
god-	dam
gh Q d	d { m
god-	damn
gh Q d	d { m
god-	dard
gh Q	d @r d
god-	dart
gh Q	d Q@ t
god-	den
gh Q	d V n
god-	des-	ses
gh Q	d V	s V z
god-	dess
gh Q	d V s
god-	ding
gh Q	d I N
god-	fa-	ther
gh Q d	f Q	D @r
god-	fa-	ther's
gh Q d	f Q	D @r z
god-	frey
gh Q d	f r i:
god-	head
gh Q d	h e d
god-	kin
gh Q d	k I n
god-	less
gh Q d	l V s
god-	ley
gh Q d	l i:
god-	ly
gh Q d	l i:
god-	man
gh Q d	m V n
god-	mo-	ther
gh Q d	m V	D @r
god-	send
gh Q d	s e n d
god-	speed
gh Q d	s p i: d
god-	win
gh Q d	w I n
god-	zil-	la
gh Q d	z I	l V
gods
gh Q d z
god's
gh Q d z
goe
gh @U
goe-	bel
gh @U	b V l
goe-	thals
gh @U	T V l z
goeb-	bels
gh @U	b V l z
goeh-	ner
gh @U	n @r
goen
gh @U n
goer-	litz
gh O@	l I t s
goerke
gh O@ k
goes
gh @U z
goethe
gh @U T
goetz
gh e t s
goff
gh O: f
gog-	gin
gh Q	g I n
gog-	gle
gh Q	g V l
gog-	gles
gh Q	g V l z
gogh
gh @U
goi-	ter
gh OI	t @r
goines
gh OI n z
gol-	con-	da
gh Q l	k Q n	d V
gol-	da
gh @U l	d V
gol-	dy
gh @U l	d i:
gol-	fer
gh Q l	f @r
gol-	fers
gh Q l	f @r z
gol-	fer's
gh Q l	f @r z
gol-	fing
gh Q l	f I N
gol-	gi
gh @U l	dZ i:
gol-	ler
gh Q	l @r
gol-	ly
gh Q	l i:
gold
gh @U l d
gold-	bach
gh @U l	d b Q k
gold-	berg
gh @U l	d b @r g
gold-	berg's
gh @U l	d b @r g z
gold-	blum
gh @U l	d b l V m
gold-	crest
gh @U l	d k r e s t
gold-	mark
gh @U l	d m Q@ k
gold-	mine
gh @U l	d m aI n
gold-	ner
gh @U l	d n @r
gold-	star
gh @U l	d s t Q@
gold-	stein
gh @U l	d s t aI n
gold-	stein's
gh @U l	d s t aI n z
gold-	ston
gh @U l	d s t V n
gold-	stone
gh @U l	d s t @U n
gold-	swor-	thy
gh @U l	d z w @r	D i:
gold-	wa-	ter
gh @U l	d w O:	t @r
gold-	wa-	ter's
gh @U l	d w O:	t @r z
gold-	was-	ser
gh @U l	d w O:	s @r
gold-	win
gh @U l	d w I n
gold-	wyn
gh @U l	d w I n
golds
gh @U l d z
gold's
gh @U l d z
golds-	mith
gh @U l	d s m I T
golds-	mith's
gh @U l	d s m I T s
goldsch-	midt
gh @U l	d S m I t
goldth-	waite
gh @U l	d T w eI t
golf
gh Q l f
golfed
gh Q l f t
golfs
gh Q l f s
golf's
gh Q l f s
goll
gh Q l
goltz
gh @U l t s
gom-	berg
gh Q m	b @r g
gom-	bos
gh @U m	b @U z
gon-	cha-	rov
gh Q n	tS @r	Q v
gon-	do-	la
gh Q n	d V	l V
gon-	do-	las
gh Q n	d V	l V z
gon-	do-	lier
gh Q n	d V	l I@
gon-	do-	liers
gh Q n	d V	l I@ z
gon-	na
gh Q	n V
gon-	nel-	la
gh @U	n e	l V
gon-	yea
gh @U n	j e
gon-	za-	le-	z's
gh Q n	z Q	l V	z V z
gon-	za-	les
gh Q n	z Q	l V s
gon-	za-	lez
gh Q n	z Q	l V z
gon-	za-	lo
gh Q n	z Q	l @U
gon-	zo
gh Q n	z @U
gond
gh Q n d
gone
gh Q n
gong
gh O: N
gongs
gh O: N z
goo
gh u:
goo-	dall
gh U	d O: l
goo-	dell
gh U	d e l
goo-	der
gh U	d @r
goo-	ders
gh U	d @r z
goo-	die
gh U	d i:
goo-	dies
gh U	d i: z
goo-	ding
gh U	d I N
goo-	ding's
gh U	d I N z
goo-	dy
gh U	d i:
goo-	dy's
gh U	d i: z
goo-	ey
gh u:	i:
goo-	fing
gh u:	f I N
goo-	fy
gh u:	f i:
goo-	gins
gh u:	g I n z
goo-	ley
gh u:	l i:
goo-	sey
gh u:	s i:
goo-	tee
gh u:	t i:
gooch
gh u: tS
good
gh U d
good-	by
gh U d	b aI
good-	bye
gh U d	b aI
good-	byes
gh U d	b aI z
good-	fel-	low
gh U d	f e	l @U
good-	fel-	lows
gh U d	f e	l @U z
good-	hear-	ted-	ly
gh U d	h Q@	t V d	l i:
good-	hue
gh U d	h j u:
good-	kin
gh U d	k I n
good-	land
gh U d	l V n d
good-	ly
gh U d	l i:
good-	man
gh U d	m V n
good-	man's
gh U d	m { n z
good-	na-	tured-	ly
gh U d	n eI	tS @r d	l i:
good-	ness
gh U d	n V s
good-	night
gh U d	n aI t
good-	ri-	ch's
gh U d	r I	tS V z
good-	rich
gh U d	r I tS
good-	row
gh U d	r @U
good-	son
gh U d	s V n
good-	son's
gh U d	s V n z
good-	speed
gh U d	s p i: d
good-	speed's
gh U d	s p i: d z
good-	will
gh U d	w I l
good-	win
gh U d	w I n
good-	wine
gh U d	w aI n
good-	year
gh U d	j I@
good-	year's
gh U d	j I@ z
goode
gh U d
goods
gh U d z
good's
gh U d z
goof
gh u: f
goofed
gh u: f t
goofs
gh u: f s
gook
gh U k
goold
gh u: l d
goon
gh u: n
goons
gh u: n z
goop
gh u: p
goos
gh u: z
goos-	sens
gh u:	s V n z
goose
gh u: s
goose-	ber-	ry
gh u: s	b e@	i:
goose-	fish
gh u: s	f I S
goose-	foot
gh u: s	f U t
gor-	ba-	chev
gh O@	b V	tS e v
gor-	da
gh O@	d V
gor-	dan
gh O@	d V n
gor-	den
gh O@	d V n
gor-	di-	an
gh O@	d i:	V n
gor-	die
gh O@	d i:
gor-	don
gh O@	d V n
gor-	don's
gh O@	d V n z
gor-	dy
gh O@	d i:
gor-	gas
gh O@	g V z
gor-	geous
gh O@	dZ V s
gor-	ges
gh O@	dZ V z
gor-	go-	ni-	an
gh O@	g @U	n i:	V n
gor-	gon
gh O@	g V n
gor-	gons
gh O@	g V n z
gor-	ham
gh O@	V m
gor-	ki
gh O@	k i:
gor-	ky
gh O@	k i:
gor-	ky's
gh O@	k i: z
gor-	man
gh O@	m V n
gor-	ski
gh O@ s	k i:
gor-	ton
gh O@	t V n
gore
gh O@
gored
gh O@ d
gores
gh O@ z
gore's
gh O@ z
gorge
gh O@ dZ
gos-	nell
gh Q s	n V l
gos-	ney
gh Q s	n i:
gos-	pel
gh Q s	p V l
gos-	pels
gh Q s	p V l z
gos-	plan
gh O: s	p l { n
gos-	sa-	mer
gh Q	s V	m @r
gos-	sard
gh V	s Q@ d
gos-	se-	lin
gh Q	s V	l I n
gos-	ser
gh O:	s @r
gos-	si-	per
gh Q	s V	p @r
gos-	si-	pers
gh Q	s V	p @r z
gos-	si-	ping
gh Q	s V	p I N
gos-	si-	py
gh Q	s I	p i:
gos-	sip
gh Q	s V p
gos-	sips
gh Q	s I p s
gosh
gh Q S
goss
gh O: s
gosse
gh Q s
got
gh Q t
got-	cha
gh Q	tS V
got-	cher
gh Q	tS @r
got-	ta
gh Q	t V
got-	ten
gh Q	t V n
got-	ter-	dam-	me-	rung
gh Q	t @r	d {	m @r	V N
gotch
gh Q tS
goth
gh Q T
gott
gh Q t
gott-	fried
gh O: t	f r i: d
gott-	helf
gh Q t	h e l f
gott-	lieb
gh Q t	l i: b
gott-	lieb's
gh Q t	l i: b z
gott-	schalk
gh Q	tS V k
gott-	wald
gh Q t	w V l d
gotz
gh Q t s
gou-	cher
gh aU	k @r
gou-	deau
gh u:	d @U
gou-	dy
gh aU	d i:
gou-	ger
gh aU	dZ @r
gou-	ging
gh aU	dZ I N
gou-	lash
gh u:	l Q S
gou-	let
gh u:	l e t
gou-	lette
gh u:	l e t
gou-	ty
gh aU	t i:
gouge
gh aU dZ
gouged
gh aU dZ d
gough
gh O: f
goul-	den
gh U	d V n
gould
gh u: l d
gould's
gh u: l d z
gour-	dine
gh U@	d aI n
gour-	met
gh U@	m eI
gour-	mets
gh U@	m eI z
gourd
gh O@ d
gourds
gh O@ d z
gout
gh aU t
gov
gh V v
gove
gh @U v
govs
gh Q v z
gow
gh aU
gow-	dy
gh aU	d i:
gown
gh aU n
gowns
gh aU n z
goy
gh OI
gra-	ben
gh r {	b V n
gra-	bens
gh r Q	b V n z
gra-	bill
gh r V	b I l
gra-	ble
gh r eI	b V l
gra-	ces
gh r eI	s V z
gra-	ce's
gh r eI	s V z
gra-	cey
gh r eI	s i:
gra-	cia
gh r Q	tS V
gra-	cie
gh r eI	s i:
gra-	cile
gh r {	s I l
gra-	cious
gh r eI	S V s
gra-	cious-	ly
gh r eI	S V s	l i:
gra-	cious-	ness
gh r eI	S V s	n V s
gra-	ckle
gh r {	k V l
gra-	ckles
gh r {	k V l z
gra-	cy
gh r eI	s i:
gra-	da-	tion
gh r eI	d eI	S V n
gra-	da-	tions
gh r eI	d eI	S V n z
gra-	ded
gh r eI	d V d
gra-	der
gh r eI	d @r
gra-	ders
gh r eI	d @r z
gra-	ding
gh r eI	d I N
gra-	du-	a-	li-	sm
gh r {	dZ V	w V	l I	z V m
gra-	du-	a-	list
gh r {	dZ V	w V	l I s t
gra-	du-	a-	ted
gh r {	dZ u:	eI	t V d
gra-	du-	a-	ting
gh r {	dZ V	w eI	t I N
gra-	du-	a-	tion
gh r {	dZ u:	eI	S V n
gra-	du-	a-	tions
gh r {	dZ u:	eI	S V n z
gra-	du-	al
gh r {	dZ u:	V l
gra-	du-	al-	ly
gh r {	dZ u:	V	l i:
gra-	du-	ate
gh r {	dZ V	w V t
gra-	du-	ates
gh r {	dZ V	w V t s
gra-	dus
gh r eI	d V s
gra-	dy
gh r eI	d i:
gra-	na
gh r {	n V
gra-	na-	da
gh r V	n Q	d V
gra-	na-	da's
gh r V	n Q	d V z
gra-	na-	do
gh r Q	n Q	d @U
gra-	na-	dos
gh r Q	n Q	d @U z
gra-	nat
gh r {	n V t
gra-	ner
gh r eI	n @r
gra-	nese
gh r {	n i: z
gra-	ni-	tic
gh r V	n I	t I k
gra-	nite
gh r {	n I t
gra-	no
gh r Q	n @U
gra-	no-	la
gh r V	n @U	l V
gra-	noff
gh r {	n O: f
gra-	nu-	la-	tion
gh r { n	j V	l eI	S V n
gra-	nu-	lar
gh r { n	j V	l @r
gra-	nu-	lo-	cyte
gh r V	n u:	l @U	s aI t
gra-	nule
gh r { n	j V l
gra-	nules
gh r { n	j V l z
gra-	num
gh r {	n V m
gra-	phi-	cal
gh r {	f I	k V l
gra-	phic
gh r {	f I k
gra-	phical-	ly
gh r {	f I k	l i:
gra-	phics
gh r {	f I k s
gra-	phite
gh r {	f aI t
gra-	pho-	lo-	gy
gh r V	f Q	l V	dZ i:
gra-	ta
gh r Q	t V
gra-	ted
gh r eI	t V d
gra-	ter
gh r eI	t @r
gra-	ti-	fi-	ca-	tion
gh r {	t I	f I	k eI	S V n
gra-	ti-	fied
gh r {	t I	f aI d
gra-	ti-	fy
gh r {	t I	f aI
gra-	ti-	fy-	ing
gh r {	t I	f aI	I N
gra-	ti-	tude
gh r {	t I	t u: d
gra-	ting
gh r eI	t I N
gra-	tis
gh r {	t I s
gra-	tu-	i-	ties
gh r V	t u:	V	t i: z
gra-	tu-	i-	tous
gh r V	t u:	V	t V s
gra-	tu-	i-	tous-	ly
gh r V	t u:	V	t V s	l i:
gra-	tu-	i-	ty
gh r V	t u:	V	t i:
gra-	vel
gh r {	v V l
gra-	vel-	ly
gh r {	v V	l i:
gra-	ven
gh r eI	v V n
gra-	ver
gh r eI	v @r
gra-	vest
gh r {	v V s t
gra-	vette
gh r V	v e t
gra-	vi-	me-	ter
gh r {	v I	m i:	t @r
gra-	vi-	met-	ric
gh r {	v I	m e t	r I k
gra-	vi-	ta-	ted
gh r {	v I	t eI	t I d
gra-	vi-	ta-	ting
gh r {	v I	t eI	t I N
gra-	vi-	ta-	tio-	nal
gh r {	v I	t eI	S V	n V l
gra-	vi-	ta-	tion
gh r {	v I	t eI	S V n
gra-	vi-	tas
gh r {	v I	t V s
gra-	vi-	tate
gh r {	v I	t eI t
gra-	vi-	tates
gh r {	v I	t eI t s
gra-	vi-	tatio-	nal-	ly
gh r {	v I	t eI S	n V	l i:
gra-	vi-	ty
gh r {	v I	t i:
gra-	vies
gh r eI	v i: z
gra-	vy
gh r eI	v i:
gra-	yer
gh r eI	@r
gra-	yest
gh r eI	V s t
gra-	ying
gh r eI	I N
gra-	yish
gh r eI	I S
gra-	zer
gh r eI	z @r
gra-	zi-	er
gh r eI	z i:	@r
gra-	zing
gh r eI	z I N
grab
gh r { b
grab-	ber
gh r {	b @r
grab-	bers
gh r {	b @r z
grab-	bing
gh r {	b I N
grabbed
gh r { b d
grabs
gh r { b z
grace
gh r eI s
grace-	ful
gh r eI s	f V l
grace-	ful-	ly
gh r eI s	f V	l i:
grace-	land
gh r eI s	l { n d
grace-	less
gh r eI s	l V s
graced
gh r eI s t
grad
gh r { d
grade
gh r eI d
grades
gh r eI d z
grads
gh r { d z
)"
R"(graeme
gh r eI m
graf
gh r { f
graf-	fi-	ti
gh r V	f i:	t i:
graf-	ted
gh r { f	t V d
graf-	ting
gh r { f	t I N
graf-	ton
gh r { f	t V n
graff
gh r { f
graft
gh r { f t
gram-	ling
gh r { m	l I N
gram-	ma-	ti-	cal
gh r V	m {	t V	k V l
gram-	mar
gh r {	m @r
gram-	mies
gh r {	m i: z
gram-	my
gh r {	m i:
gram-	mys
gh r {	m i: z
grams
gh r { m z
gran
gh r { n
gran-	dad
gh r { n	d { d
gran-	der
gh r { n	d @r
gran-	dest
gh r { n	d V s t
gran-	deur
gh r { n	d u: r
gran-	di-	lo-	quent
gh r { n	d I	l V k	w V n t
gran-	di-	ose
gh r { n	d i:	@U s
gran-	dis
gh r { n	d I s
gran-	dun-	cle
gh r { n	d V N	k V l
gran-	ger
gh r eI n	dZ @r
gran-	gers
gh r eI n	dZ @r z
gran-	ges
gh r eI n	dZ V z
gran-	lund
gh r { n	l V n d
gran-	nis
gh r {	n I s
gran-	ny
gh r {	n i:
gran-	ted
gh r { n	t V d
gran-	tham
gh r { n	T V m
gran-	ting
gh r { n	t I N
gran-	tor
gh r { n	t @r
gran-	tors
gh r { n	t @r z
gran-	ville
gh r { n	v I l
gran-	ville's
gh r { n	v I l z
grand
gh r { n d
grand-	ba-	by
gh r { n	d b eI	b i:
grand-	child
gh r { n	d tS aI l d
)"