R"(al-	ly's
V	l aI z
al-	ma
{ l	m V
al-	ma-	da
Q l	m Q	d V
al-	ma-	den
{ l	m V	d V n
al-	ma-	nac
O: l	m V	n { k
al-	man
{ l	m V n
al-	mas
{ l	m V z
al-	me-	da
Q l	m eI	d V
al-	mei-	da
Q l	m i:	d V
al-	mi-	ra
Q l	m I@	V
al-	migh-	ty
O: l	m aI	t i:
al-	mo
Q l	m @U
al-	mon
Q l	m V n
al-	mond
Q	m V n d
al-	monds
Q l	m V n d z
al-	most
O: l	m @U s t
al-	pa-	ca
{ l	p {	k V
al-	paugh
V l	p O:
al-	per
{ l	p @r
al-	pers
{ l	p @r z
al-	pert
{ l	p @r t
al-	pha
{ l	f V
al-	pha-	be-	ti-	cal
{ l	f V	b e	t I	k V l
al-	pha-	be-	ti-	za-	tion
{ l	f V	b e	t V	z eI	S V n
al-	pha-	be-	tic
{ l	f V	b e	t I k
al-	pha-	be-	tical-	ly
{ l	f V	b e	t I k	l i:
al-	pha-	be-	tize
{ l	f V	b V	t aI z
al-	pha-	bet
{ l	f V	b e t
al-	pha-	nu-	me-	ric
{ l	f V	n u:	m e@	I k
al-	pha-	ret-	ta
{ l	f @r	e	t V
al-	pha's
{ l	f V z
al-	phin
{ l	f I n
al-	phon-	sine
V l	f Q n	s i: n
al-	phon-	so
{ l	f Q n	s @U
al-	phonse
{ l	f Q n z
al-	pine
{ l	p aI n
al-	po
{ l	p @U
al-	rea-	dy
O: l	r e	d i:
al-	right
O: l	r aI t
al-	roy
V l	r OI
al-	sa-	tian
{ l	s eI	S V n
al-	sace
{ l	s Q s
al-	sip
{ l	s V p
al-	so
O: l	s @U
al-	sop
{ l	s Q p
al-	ta
Q l	t V
al-	ta-	de-	na
Q l	t V	d i:	n V
al-	ta-	ic
{ l	t eI	I k
al-	ta-	vis-	ta
O: l	t V	v I s	t V
al-	tai
{ l	t aI
al-	tar
O: l	t @r
al-	tar-	piece
O: l	t @r	p i: s
al-	tars
O: l	t @r z
al-	tay
O: l	t aI
al-	te-	ra-	tion
O: l	t @r	eI	S V n
al-	te-	ra-	tions
O: l	t @r	eI	S V n z
al-	te-	ring
O: l	t @r	I N
al-	ten-	burg
O: l	t V n	b @r g
al-	ter
O: l	t @r
al-	ter-	ca-	tion
Q l	t @r	k eI	S V n
al-	ter-	ca-	tions
Q l	t @r	k eI	S V n z
al-	ter-	man
O: l	t @r	m V n
al-	ter-	na-	ted
O: l	t @r	n eI	t V d
al-	ter-	na-	ting
O: l	t @r	n eI	t I N
al-	ter-	na-	tion
O: l	t @r	n eI	S V n
al-	ter-	na-	tive
O: l	t @r	n V	t I v
al-	ter-	na-	tive-	ly
O: l	t @r	n V	t I v	l i:
al-	ter-	na-	tives
O: l	t @r	n V	t I v z
al-	ter-	na-	tor
O: l	t @r	n eI	t @r
al-	ter-	nate
O: l	t @r	n V t
al-	ter-	nate-	ly
O: l	t @r	n V t	l i:
al-	ter-	nates
O: l	t @r	n eI t s
al-	tered
O: l	t @r d
al-	ters
O: l	t @r z
al-	the-	a
{ l	T i:	V
al-	though
O: l	D @U
al-	ti-	me-	ter
{ l	t I	m V	t @r
al-	ti-	tude
{ l	t I	t u: d
al-	ti-	tudes
{ l	t I	t u: d z
al-	tip-	la-	no
{ l	t I p	l Q	n @U
al-	to
{ l	t @U
al-	to-	ge-	ther
O: l	t V	g e	D @r
al-	ton
O: l	t V n
al-	too-	na
{ l	t u:	n V
al-	tos
{ l	t @U z
al-	tu-	ras
Q l	t U@	V s
al-	tus
{ l	t V s
al-	va
{ l	v V
al-	va-	ra-	do
{ l	v @r	Q	d @U
al-	va-	rez
{ l	v @r	e z
al-	va-	ro
V l	v Q@	@U
al-	vah
{ l	v Q
al-	van
{ l	v V n
al-	ve-	o-	lar
{ l	v i:	V	l @r
al-	ve-	o-	li
{ l	v i:	V	l aI
al-	ver-	son
Q l	v e@	s V n
al-	ves
Q l	v e s
al-	vey
{ l	v i:
al-	vi-	na
{ l	v aI	n V
al-	vi-	no
Q l	v i:	n @U
al-	vi-	ta
Q l	v i:	t V
al-	vin
{ l	v I n
al-	vis
Q l	v I s
al-	vite
{ l	v aI t
al-	vord
{ l	v O@ d
al-	ways
O: l	w eI z
al-	win
{ l	w I n
al-	wyn
{ l	w I n
al-	zhei-	mer
{ l	z h aI	m @r
al-	zhei-	mer's
{ l	z h aI	m @r z
al.
{ l
ald-	red
{ l	d @r d
ald-	redge
O: l	d r e dZ
ald-	ric
{ l	d r I k
ald-	rich
O: l	d r I tS
ald-	ridge
O: l	d r I dZ
ald-	rin
O: l	d r I n
ald-	rin's
O: l	d r I n z
ald-	win
O: l	d w I n
aldo-	us
Q l	d V s
ale
eI l
ale-	house
eI l	h aU s
ale-	man
eI l	m V n
ale-	wife
eI l	w aI f
ale-	wives
eI l	w aI v z
ales
eI l z
alf
{ l f
alf-	re-	do
{ l	f r eI	d @U
alf-	red
{ l	f r V d
all
O: l
all-	bee
O: l	b i:
all-	day
O: l	d eI
all-	good
O: l	g U d
all-	in
V	l I n
all-	mon
O: l	m V n
alle-	man
eI l	m V n
alles
eI l z
alm
Q m
alms
Q l m z
alps
{ l p s
als
{ l z
al's
{ l z
als-	ton
O: l	s t V n
alt
Q l t
alt-	man
O: l	t m V n
alt-	man's
O: l	t m V n z
alt-	ru-	is-	tic
O: l	t r u:	I s	t I k
alt-	ru-	ism
{ l	t r u:	I z m
am
{ m
am-	b-	ling
{ m	b V	l I N
am-	bas-	sa-	do-	ri-	al
{ m	b {	s V	d O@	i:	V l
am-	bas-	sa-	dor
{ m	b {	s V	d @r
am-	bas-	sa-	dor-	ship
{ m	b {	s V	d @r	S I p
am-	bas-	sa-	dor-	ships
{ m	b {	s V	d @r	S I p s
am-	bas-	sa-	dors
{ m	b {	s V	d @r z
am-	bas-	sa-	dor's
{ m	b {	s V	d @r z
am-	bas-	sa-	dress
{ m	b {	s V d	r V s
am-	ber
{ m	b @r
am-	ber-	gris
{ m	b @r g	r I s
am-	ber-	son
{ m	b @r	s V n
am-	berg
{ m	b @r g
am-	bers
{ m	b @r z
am-	ber's
{ m	b @r
am-	bi-	ance
{ m	b i:	V n s
am-	bi-	dext-	rous
{ m	b I	d e k	s t r V s
am-	bi-	ence
{ m	b i:	V n s
am-	bi-	ent
{ m	b i:	V n t
am-	bi-	gu-	i-	ties
{ m	b I g	j u:	I	t i: z
am-	bi-	gu-	i-	ty
{ m	b I g	j u:	I	t i:
am-	bi-	gu-	ous
{ m	b I g	j u:	V s
am-	bi-	tion
{ m	b I	S V n
am-	bi-	tions
{ m	b I	S V n z
am-	bi-	tious
{ m	b I	S V s
am-	bi-	tious-	ly
{ m	b I	S V s	l i:
am-	bi-	va-	lence
{ m	b I	v V	l V n s
am-	bi-	va-	lent
{ m	b I	v V	l V n t
am-	ble
{ m	b V l
am-	bro-	gi-	o
{ m	b r @U	dZ i:	@U
am-	bro-	si-	ne
Q m	b r @U	s i:	n i:
am-	bro-	si-	o
{ m	b r @U	s i:	@U
am-	bro-	si-	us
{ m	b r V	s i:	V s
am-	bro-	sia
{ m	b r @U	Z @
am-	bro-	sial
{ m	b r @U	Z @ l
am-	bro-	sian
{ m	b r @U	z @ n
am-	brose
{ m	b r @U z
am-	bu-	la-	to-	ry
{ m	b j V	l V	t O@	i:
am-	bu-	lan-	ces
{ m	b j V	l V n	s V z
am-	bu-	lance
{ m	b j V	l V n s
am-	bu-	shes
{ m	b U	S V z
am-	bu-	shing
{ m	b U	S I N
am-	bur-	gey
{ m	b @r	g i:
am-	bush
{ m	b U S
am-	bushed
{ m	b U S t
am-	dahl
{ m	d Q l
am-	herst
{	m @r s t
am-	man
{	m V n
am-	mann
{	m V n
am-	me-	ter
{	m i:	t @r
am-	me-	ters
{	m i:	t @r z
am-	mer-	man
{	m @r	m V n
am-	mo
{	m @U
am-	mo-	ni-	um
V	m @U	n i:	V m
am-	mo-	nia
V	m @U n	j V
am-	mo-	nite
{	m V	n aI t
am-	mo-	nites
{	m V	n aI t s
am-	mon
{	m V n
am-	mons
{	m V n z
am-	mu-	ni-	tion
{ m	j V	n I	S V n
am-	mu-	ni-	tions
{ m	j V	n I	S V n z
am-	ne-	si-	ac
{ m	n i:	z i:	{ k
am-	ne-	sia
{ m	n i:	Z @
am-	nes-	ties
{ m	n V s	t i: z
am-	nes-	ty
{ m	n V s	t i:
am-	ni-	o
{ m	n i:	@U
am-	ni-	o-	cen-	te-	sis
{ m	n i:	@U	s e n	t i:	s I s
am-	ni-	o-	tic
{ m	n i:	O:	t I k
am-	pe-	rage
{ m	p @r	I dZ
am-	per-	sand
{ m	p @r	s { n d
am-	pex
{ m	p e k s
am-	phe-	ta-	mine
{ m	f e	t V	m i: n
am-	phe-	ta-	mines
{ m	f e	t V	m i: n z
am-	phi-	bi-	an
{ m	f I	b i:	V n
am-	phi-	bi-	ans
{ m	f I	b i:	V n z
am-	phi-	bi-	ous
{ m	f I	b i:	V s
am-	phi-	bole
{ m	f @	b @U l
am-	phi-	the-	a-	ter
{ m	f I	T i:	V	t @r
am-	phi-	the-	a-	ters
{ m	f I	T i:	V	t @r z
am-	phi-	the-	a-	tre
{ m	p I	T i:	V	t @r
am-	pho-	ra
{ m	f @r	V
am-	pho-	rae
{ m	f @r	i:
am-	ple
{ m	p V l
am-	pli-	cons
{ m	p l I	k O: n z
am-	pli-	fi-	ca-	tion
{ m	p l I	f I	k eI	S V n
am-	pli-	fi-	ca-	tions
{ m	p l I	f I	k eI	S V n z
am-	pli-	fi-	er
{ m	p l I	f aI	@r
am-	pli-	fi-	ers
{ m	p l I	f aI	@r z
am-	pli-	fied
{ m	p l I	f aI d
am-	pli-	fies
{ m	p l I	f aI z
am-	pu-	ta-	ted
{ m	p j V	t eI	t V d
am-	pu-	ta-	tion
{ m	p j @	t eI	S V n
am-	pu-	ta-	tions
{ m	p j u:	t eI	S V n z
am-	pu-	tate
{ m	p j V	t eI t
am-	pu-	tee
{ m	p j V	t i:
am-	pu-	tees
{ m	p j V	t i: z
am-	r
Q	m @r
am-	raam
{ m	r Q m
am-	rit-	sar
{ m	r I t	s @r
am-	way
{ m	w eI
amb-	led
{ m	b V l d
amb-	ler
{ m	b l @r
amb-	les
{ m	b V l z
amc
{ m k
ame
eI m
ames
eI m z
amp
{ m p
amp-	li-	fy
{ m	p l I	f aI
amp-	li-	fy-	ing
{ m	p l I	f aI	I N
amp-	li-	tude
{ m	p l I	t u: d
amp-	ly
{ m	p l i:
ams
{ m z
am's
{ m z
ams-	den
{ m	z d V n
ams-	ter-	dam
{ m	s t @r	d { m
ams-	ter-	dam's
{ m	s t @r	d { m z
ams-	trad
{ m	s t r { d
amt-	rack
{ m	t r { k
amt-	rak
{ m	t r { k
amt-	rak's
{ m	t r { k s
an
{ n
an-	cel
V n	s e l
an-	cell
Q n	s eI l
an-	ces-	tor
{ n	s e s	t @r
an-	ces-	tors
{ n	s e s	t @r z
an-	cest-	ral
{ n	s e s	t r V l
an-	cest-	ry
{ n	s e s	t r i:
an-	cho
{ n	tS @U
an-	cho-	rage
{ N	k @r	V dZ
an-	cho-	ring
{ N	k @r	I N
an-	cho-	vies
{ n	tS @U	v i: z
an-	cho-	vy
{ n	tS @U	v i:
an-	chor
{ N	k @r
an-	chor-	man
{ N	k @r	m { n
an-	chor-	men
{ N	k @r	m e n
an-	chored
{ N	k @r d
an-	chors
{ N	k @r z
an-	chor's
{ N	k @r z
an-	cient
eI n	S V n t
an-	cients
eI n	S V n t s
an-	cil-	la-	ry
{ n	s I	l e@	i:
an-	co-	na
Q n	k @U	n V
an-	da-	lu-	sia
{ n	d V	l u:	Z V
an-	da-	lu-	sian
{ n	d V	l u:	S V n
an-	dan-	te
Q n	d Q n	t eI
an-	dan-	ti-	no
Q n	d Q n	t i:	n @U
an-	de-	an
{ n	d i:	V n
an-	de-	regg
{ n	d @r	I g
an-	de-	site
{ n	d V	s aI t
an-	del
{ n	d V l
an-	der
{ n	d @r
an-	der-	sen
{ n	d @r	s V n
an-	der-	sen's
{ n	d @r	s V n z
an-	der-	son
{ n	d @r	s V n
an-	der-	son-	ville
{ n	d @r	s V n	v I l
an-	der-	son's
{ n	d @r	s V n z
an-	ders
{ n	d @r z
an-	dert
{ n	d @r t
an-	des
{ n	d i: z
an-	di-	no
Q n	d i:	n @U
an-	di-	ron
{ n	d aI	@r n
an-	die
{ n	d i:
an-	ding
{ n	d I N
an-	do
{ n	d @U
an-	do-	ver
{ n	d @U	v @r
an-	dor-	ra
{ n	d O@	V
an-	dy
{ n	d i:
an-	dy's
{ n	d i: z
an-	ge-	la
{ n	dZ V	l V
an-	ge-	la's
{ n	dZ V	l V z
an-	ge-	le-	no
{ n	dZ V	l i:	n @U
an-	ge-	le-	nos
{ n	dZ V	l i:	n @U z
an-	ge-	les
{ n	dZ V	l V s
an-	ge-	li
Q N	g e	l i:
an-	ge-	li-	ca
{ n	dZ e	l I	k V
an-	ge-	li-	cas
{ n	dZ e	l I	k V z
an-	ge-	li-	co
Q N	g e	l i:	k @U
an-	ge-	li-	ka
{ n	dZ e	l I	k V
an-	ge-	li-	na
{ n	dZ e	l i:	n V
an-	ge-	li-	ta
Q N	g e	l i:	t V
an-	ge-	lic
{ n	dZ e	l I k
an-	ge-	lical-	ly
{ n	dZ e	l I k	l i:
an-	ge-	line
eI N	g e	l aI n
an-	ge-	lo
{ n	dZ V	l @U
an-	ge-	lo's
{ n	dZ V	l @U z
an-	ge-	lou
{ n	dZ V	l u:
an-	ge-	ring
{ N	g @r	I N
an-	ge-	vine
eI N	g I	v aI n
an-	gel
eI n	dZ V l
an-	gel-	fish
eI n	dZ V l	f I S
an-	gell
eI n	dZ V l
an-	gelle
eI N	g e l
an-	gels
eI n	dZ V l z
an-	ger
{ N	g @r
an-	gered
{ N	g @r d
an-	gers
{ N	g @r z
an-	gi
{ n	dZ i:
an-	gi-	er
{ n	dZ i:	@r
an-	gi-	na
{ n	dZ aI	n V
an-	gi-	o-	plas-	ty
{ n	dZ i:	V p	l { s	t i:
an-	gi-	o-	ten-	sin
{ n	dZ i:	@U	t e n	s I n
an-	gi-	og-	ram
{ n	dZ i:	@U g	r { m
an-	gie
{ n	dZ i:
an-	gle
{ N	g V l
an-	gled
{ N	g V l d
an-	gu-	la-	ted
{ N	g j u:	l eI	t V d
an-	gu-	lar
{ N	g j V	l @r
an-	gu-	late
{ N	g j u:	l eI t
an-	gui-	shing
{ N	g w I	S I N
an-	guil-	la
{ N	w I	l V
an-	guish
{ N	g w I S
an-	guished
{ N	g w I S t
an-	gus
{ N	g V s
an-	gy
{ n	dZ i:
an-	halt
{ n	h V l t
an-	heu-	ser
{ n	h aI	z @r
an-	heu-	ser's
{ n	h j u:	z @r z
an-	hyd-	ride
{ n	h aI d	r aI d
an-	ka-	ra
{ N	k @r	V
an-	ka-	ra's
{ N	k @r	V z
an-	ke-	ny
V N	k i:	n i:
an-	ker
{ N	k @r
an-	kle
{ N	k V l
an-	kle-	bone
{ N	k V l	b @U n
an-	kles
{ N	k V l z
an-	klet
{ N	k l V t
an-	klets
{ N	k l V t s
an-	na
{	n V
an-	na-	bel
{	n V	b e l
an-	na-	bel-	la
{	n V	b e	l V
an-	na-	belle
{	n V	b V l
an-	na-	po-	li-	s's
V	n {	p V	l I	s V z
an-	na-	po-	lis
V	n {	p V	l I s
an-	nal
{	n V l
an-	nals
{	n V l z
an-	nan-	dale
{	n V n	d eI l
an-	nas
{	n V z
an-	na's
{	n V z
an-	ne-	lid
{	n V	l V d
an-	ne-	lids
{	n V	l V d z
an-	ne-	xa-	tion
{	n e k	s eI	S V n
an-	nea-	ling
V	n i:	l I N
an-	neal
V	n i: l
an-	nen-	berg
{	n V n	b @r g
an-	nette
V	n e t
an-	nex
{	n e k s
an-	nex-	es
{	n e k	s V z
an-	nex-	ing
V	n e k	s I N
an-	nexed
{	n e k s t
an-	ni-	hi-	la-	ted
V	n aI	V	l eI	t V d
an-	ni-	hi-	la-	tion
V	n aI	V	l eI	S V n
an-	ni-	hi-	late
V	n aI	V	l eI t
an-	ni-	ver-	sa-	ries
{	n I	v @r	s @r	i: z
an-	ni-	ver-	sa-	ry
{	n I	v @r	s @r	i:
an-	nie
{	n i:
an-	nie's
{	n i: z
an-	nis
{	n i: z
an-	nis-	ton
{	n I s	t V n
an-	no
{	n @U
an-	no-	ta-	ted
{	n V	t eI	t V d
an-	no-	ta-	ting
{	n V	t eI	t I N
an-	no-	ta-	tion
{	n V	t eI	S V n
an-	no-	ta-	tions
{	n V	t eI	S V n z
an-	no-	tate
{	n V	t eI t
an-	no-	tates
{	n V	t eI t s
an-	noun-	cer
V	n aU n	s @r
an-	noun-	cers
V	n aU n	s @r z
an-	noun-	ces
V	n aU n	s V z
an-	noun-	cing
V	n aU n	s I N
an-	nounce
V	n aU n s
an-	nounce-	ment
V	n aU n	s m V n t
an-	nounce-	ments
V	n aU n	s m V n t s
an-	nounced
V	n aU n s t
an-	noy
V	n OI
an-	noy-	an-	ces
V	n OI	V n	s V z
an-	noy-	ance
V	n OI	V n s
an-	noy-	ing
V	n OI	I N
an-	noyed
V	n OI d
an-	noys
V	n OI z
an-	nu-	a-	lize
{ n	j u:	w V	l aI z
an-	nu-	a-	lized
{ n	j u:	w V	l aI z d
an-	nu-	a-	lly
{ n	j u:	V	l i:
an-	nu-	al
{ n	j u:	V l
an-	nu-	als
{	n u:	V l z
an-	nu-	i-	ties
V	n u:	V	t i: z
an-	nu-	i-	ty
V	n u:	V	t i:
an-	nu-	lar
{ n	j V	l @r
an-	nul
{	n V l
an-	nul-	ment
{	n V l	m V n t
an-	nulled
{	n V l d
an-	num
{	n V m
an-	nun-	cia-	ta
Q	n u: n	tS Q	t V
an-	nun-	zi-	a-	ta
Q	n u: n	z i:	Q	t V
an-	ny
{	n i:
an-	sa
{ n	s V
an-	said
{ n	s eI d
an-	sa's
{ n	s V z
an-	sel
V n	s e l
an-	sel-	ma
Q n	s e l	m V
an-	sel-	mi
Q n	s e l	m i:
an-	sel-	mo
Q n	s e l	m @U
an-	sell
{ n	s e l
an-	selm
{ n	s e l m
an-	so-	ni-	a
{ n	s @U	n i:	V
an-	son
{ n	s V n
an-	swe-	ring
{ n	s @r	I N
an-	swered
{ n	s @r d
an-	swers
{ n	s @r z
an-	ta-	cid
{ n	t {	s I d
an-	ta-	cids
{ n	t {	s I d z
an-	ta-	go-	ni-	sm
{ n	t {	g V	n I	z V m
an-	ta-	go-	ni-	sms
{ n	t {	g V	n I	z V m z
an-	ta-	go-	ni-	zing
{ n	t {	g V	n aI	z I N
an-	ta-	go-	nis-	tic
{ n	t {	g V	n I s	t I k
an-	ta-	go-	nist
{ n	t {	g V	n V s t
an-	ta-	go-	nists
{ n	t {	g V	n V s t s
an-	ta-	go-	nize
{ n	t {	g V	n aI z
an-	ta-	go-	nized
{ n	t {	g V	n aI z d
an-	ta-	res
{ n	t e@	i: z
an-	tal
{ n	t V l
an-	tar
{ n	t @r
an-	tarc-	ti-	ca
{ n	t Q@ k	t I	k V
an-	tarc-	ti-	ca's
{ n	t Q@ k	t I	k V z
an-	tarc-	tic
{ n	t Q@ k	t I k
an-	tar's
{ n	t @r z
an-	te
{ n	t i:
an-	te-	bel-	lum
{ n	t V	b e	l V m
an-	te-	ce-	dent
{ n	t V	s i:	d V n t
an-	te-	ce-	dents
{ n	t V	s i:	d V n t s
an-	te-	lope
{ n	t V	l @U p
an-	te-	me-	ri-	di-	an
{ n	t V	m e@	I	d i:	V n
an-	te-	mor-	tem
{ n	t V	m O@	t V m
an-	te-	ri-	or
{ n	t I@	i:	@r
an-	tea-	ter
{ n	t i:	t @r
an-	tea-	ters
{ n	t i:	t @r z
an-	ted
{ n	t V d
an-	ten-	na
{ n	t e	n V
an-	ten-	nae
{ n	t e	n i:
an-	ten-	nas
{ n	t e	n V z
an-	ten-	na's
{ n	t e	n V z
an-	tes
{ n	t i: z
an-	the-	a
{ n	T i:	V
an-	them
{ n	T V m
an-	thems
{ n	T V m z
an-	thill
{ n	t h I l
an-	thills
{ n	t h I l z
an-	tho-	lo-	gies
{ n	T Q	l V	dZ i: z
an-	tho-	lo-	gy
{ n	T Q	l V	dZ i:
an-	tho-	ny
{ n	T V	n i:
an-	tho-	ny's
{ n	T V	n i: z
an-	thon
{ n	T V n
an-	thra-	cite
{ n	T r V	s aI t
an-	thro-	po-	cent-	ric
{ n	T r V	p V	s e n	t r I k
an-	thro-	po-	lo-	gi-	cal
{ n	T r V	p V	l Q	dZ V	k V l
an-	thro-	po-	lo-	gist
{ n	T r V	p Q	l V	dZ V s t
an-	thro-	po-	lo-	gists
{ n	T r V	p Q	l V	dZ V s t s
an-	thro-	po-	lo-	gy
{ n	T r V	p Q	l V	dZ i:
an-	thro-	po-	mor-	phic
{ n	T r V	p V	m O@	f I k
an-	ti
{ n	t i:
an-	ti-	a-	bor-	tion
{ n	t i:	V	b O@	S V n
an-	ti-	air-	craft
{ n	t aI	e@ k	r { f t
an-	ti-	bac-	te-	ri-	al
{ n	t i:	b { k	t I@	i:	V l
an-	ti-	bal-	lis-	tic
{ n	t i:	b V	l I s	t I k
an-	ti-	bi-	o-	tic
{ n	t i:	b i:	Q	t I k
an-	ti-	bi-	o-	tics
{ n	t i:	b i:	Q	t I k s
an-	ti-	bo-	dies
{ n	t I	b Q	d i: z
an-	ti-	bo-	dy
{ n	t I	b Q	d i:
an-	ti-	can-	cer
{ n	t aI	k { n	s @r
an-	ti-	ci-	pa-	ted
{ n	t I	s I	p eI	t I d
an-	ti-	ci-	pa-	ting
{ n	t I	s I	p eI	t I N
an-	ti-	ci-	pa-	tion
{ n	t I	s I	p eI	S V n
an-	ti-	ci-	pa-	tions
{ n	t I	s I	p eI	S V n z
an-	ti-	ci-	pa-	to-	ry
{ n	t I	s I	p V	t O@	i:
an-	ti-	ci-	pate
{ n	t I	s I	p eI t
an-	ti-	ci-	pates
{ n	t I	s I	p eI t s
an-	ti-	cli-	mac-	tic
{ n	t i: k	l aI	m { k	t I k
an-	ti-	co
Q n	t i:	k @U
an-	ti-	com-	mu-	nist
{ n	t i:	k Q m	j V	n V s t
an-	ti-	com-	pe-	ti-	tive
{ n	t I	k V m	p e	t V	t I v
an-	ti-	cor-	rup-	tion
{ n	t aI	k @r	V p	S V n
an-	ti-	dep-	res-	sant
{ n	t i:	d V p	r e	s V n t
an-	ti-	dep-	res-	sants
{ n	t aI	d V p	r e	s V n t s
an-	ti-	disc-	ri-	mi-	na-	tion
{ n	t i:	d I s	k r I	m I	n eI	S V n
an-	ti-	dote
{ n	t I	d @U t
an-	ti-	drug
{ n	t I d	r V g
an-	ti-	dum-	ping
{ n	t i:	d V m	p I N
an-	ti-	fede-	ra-	list
{ n	t i:	f e d	r V	l V s t
an-	ti-	fede-	ra-	lists
{ n	t i:	f e d	r V	l V s t s
an-	ti-	fraud
{ n	t i: f	r Q d
an-	ti-	freeze
{ n	t i: f	r i: z
an-	ti-	fun-	gal
{ n	t aI	f V N	g V l
an-	ti-	gay
{ n	t aI	g eI
an-	ti-	gen
{ n	t I	dZ V n
an-	ti-	gens
{ n	t I	dZ V n z
an-	ti-	go-	ne
{	t I	g V	n i:
an-	ti-	go-	ne's
{ n	t I	g V	n i: z
an-	ti-	go-	vern-	ment
{ n	t i:	g V	v @r	m V n t
an-	ti-	gua
{ n	t i: g	w V
an-	ti-	his-	ta-	mine
{ n	t i:	h I s	t V	m V n
an-	ti-	his-	ta-	mines
{ n	t i:	h I s	t V	m V n z
an-	ti-	knock
{ n	t i:	n Q k
an-	ti-	lock
{ n	t i:	l Q k
an-	ti-	mis-	sile
{ n	t aI	m I	s V l
an-	ti-	o-	xi-	dant
{ n	t i:	Q k	s I	d e n t
an-	ti-	o-	xi-	dants
{ n	t i:	Q k	s I	d e n t s
an-	ti-	och
{ n	t i:	Q k
an-	ti-	pa-	thies
{ n	t I	p V	T i: z
an-	ti-	pa-	thy
{ n	t I	p V	T i:
an-	ti-	phon
{ n	t I	f Q n
an-	ti-	phons
{ n	t I	f Q n z
an-	ti-	po-	dal
{ n	t I	p V	d V l
an-	ti-	po-	ver-	ty
{ n	t aI	p Q	v @r	t i:
an-	ti-	qua-	ted
{ n	t I k	w eI	t I d
an-	ti-	quate
{ n	t I k	w eI t
an-	ti-	qui-	ties
{ n	t I k	w I	t i: z
an-	ti-	qui-	ty
{ n	t I k	w I	t i:
an-	ti-	re-	for-	mer
{ n	t i:	r V	f O@	m @r
an-	ti-	smo-	king
{ n	t i: s	m @U	k I N
an-	ti-	so-	cial
{ n	t aI	s @U	S V l
an-	ti-	sub-	ma-	rine
{ n	t aI	s V b	m @r	i: n
)"
R"(an-	ti-	take-	o-	ver
{ n	t i:	t eI	k @U	v @r
an-	ti-	tank
{ n	t i:	t { N k
an-	ti-	tax
{ n	t aI	t { k s
an-	ti-	the-	sis
{ n	t I	T V	s V s
an-	ti-	the-	ti-	cal
{ n	t I	T e	t I	k V l
an-	ti-	theft
{ n	t aI	T e f t
an-	ti-	to-	xin
{ n	t i:	t Q k	s V n
an-	ti-	to-	xins
{ n	t i:	t Q k	s V n z
an-	ti-	trust
{ n	t aI t	r V s t
an-	ti-	vi-	ral
{ n	t i:	v aI	r V l
an-	ti-	war
{ n	t aI	w O@
an-	tic
{ n	t I k
an-	tic-	line
{ n	t I k	l aI n
an-	tic-	rime
{ n	t i: k	r aI m
an-	tics
{ n	t I k s
an-	til-	les
{ n	t I	l i: z
an-	tique
{ n	t i: k
an-	tiques
{ n	t i: k s
an-	tis
{ n	t aI z
an-	to-	ne
Q n	t @U	n i:
an-	to-	ni
Q n	t @U	n i:
an-	to-	ni-	a
{ n	t @U	n i:	V
an-	to-	ni-	o
{ n	t @U	n i:	@U
an-	to-	ni-	o's
{ n	t @U	n i:	@U z
an-	to-	ni-	us
{ n	t @U	n i:	V s
an-	to-	nin
{ n	t V	n I n
an-	to-	no-	vich
{ n	t Q	n V	v I tS
an-	to-	ny
{ n	t V	n i:
an-	toi-	nette
{ n	t w V	n e t
an-	toine
Q n	t w Q n
an-	ton
{ n	t O: n
an-	trim
{ n	t r I m
an-	vil
{ n	v V l
an-	xi-	e-	ties
{ N	z aI	V	t i: z
an-	xi-	e-	ty
{ N	z aI	V	t i:
an-	xious
{ N	k S V s
an-	xious-	ly
{ N	k S V s	l i:
an-	za
{ n	z V
an-	zi-	o
{ n	z i:	@U
an-	zus
{ n	z V s
and
{ n d
and-	ra-	da
Q n	d r Q	d V
and-	rade
{ n	d r eI d
and-	rae
Q n	d r aI
and-	ras
Q n	d r V s
and-	re
Q n	d r eI
and-	re-	a
{ n	d r i:	V
and-	re-	as
Q n	d r eI	V s
and-	re-	a's
{ n	d r i:	V z
and-	re-	ot-	ti
Q n	d r i:	Q	t i:
and-	rea-	na
{ n	d r i:	n V
and-	ree
V n	d r i:
and-	rei
{ n	d r eI
and-	rej
Q n	d r eI
and-	res
Q n	d r eI z
and-	ret-	ti
{ n	d r e	t i:
and-	rew
{ n	d r u:
and-	rews
{ n	d r u: z
and-	rew's
{ n	d r u: z
and-	rey
{ n	d r i:
and-	ri-	a
{ n	d r i:	V
and-	ri-	a-	na
Q n	d r i:	{	n V
and-	ric
{ n	d r I k
and-	ro-	gy-	nous
{ n	d r O:	dZ V	n V s
and-	ro-	me-	da
{ n	d r Q	m V	d V
and-	ro-	pov
{ n	d r Q	p Q v
and-	roid
{ n	d r OI d
and-	ros
{ n	d r Q s
and-	rus
{ n	d r V s
ands
{ n d z
ang
{ N
ang-	le-	ton
{ N	g V l	t V n
ang-	ler
{ N	g l @r
ang-	lers
{ N	g l @r z
ang-	les
{ N	g V l z
ang-	li-	a
{ N	g l i:	V
ang-	li-	can
{ N	g l I	k V n
ang-	li-	cize
{ N	l I	s aI z
ang-	li-	cized
{ N	l I	s aI z d
ang-	lim
{ N	g l I m
ang-	ling
{ N	g l I N
ang-	lo
{ N	g l @U
ang-	lo-	ca-	tho-	li-	ci-	sm
{ N	g l @U	k V	T O:	l V	s I	z V m
ang-	los
{ N	g l @U z
ang-	o-	la
{ N	g @U	l V
ang-	o-	lan
{ N	g @U	l V n
ang-	o-	lans
{ N	g @U	l V n z
ang-	o-	la's
{ N	g @U	l V z
ang-	o-	ra
{ N	g O@	V
ang-	o-	ras
{ N	g O@	V z
ang-	ri-	er
{ N	g r i:	@r
ang-	ri-	est
{ N	g r i:	V s t
ang-	ri-	ly
{ N	g r I	l i:
ang-	ry
{ N	g r i:
ange
eI n dZ
angst
Q N k s t
angst-	rom
{ N	s t r V m
angst-	roms
{ N	s t r V m z
ank-	ney
{ N	k n i:
ann
{ n
anne
{ n
anne's
{ n z
ann's
{ n z
ans-	han
{ n	S V n
ans-	ley
{ n	s l i:
ans-	tice
Q n	s t I s
ans-	we-	ra-	ble
{ n	s @r	V	b V l
ans-	wer
{ n	s @r
ans-	wer's
{ n	s @r z
ansch-	luss
{ n	S l V s
anse
{ n s
ant
{ n t
ant-	ler
{ n	t l @r
ant-	lered
{ n	t l @r d
ant-	lers
{ n	t l @r z
ant-	sy
{ n	t s i:
ant-	werp
{ n	t w @r p
anth-	rax
{ n	T r { k s
ants
{ n t s
ao-	i
aU	i:
ap-	fel
{ p	f V l
ap-	gar
{ p	g @r
ap-	len-	ty
V p	l e n	t i:
ap-	lomb
V p	l Q m
ap-	ne-	a
{ p	n i:	V
ap-	p-	ling
{	p V	l I N
ap-	pa-	la-	chi-	a
{	p V	l {	tS i:	V
ap-	pa-	la-	chian
{	p V	l eI	tS V n
ap-	pa-	la-	chians
{	p V	l eI	tS V n z
ap-	pa-	ra-	tchik
{	p @r	{	tS I k
ap-	pa-	ra-	tchiks
{	p @r	{	tS I k s
ap-	pa-	ra-	tu-	ses
{	p @r	{	t V	s V z
ap-	pa-	ra-	tus
{	p @r	{	t V s
ap-	pa-	rel
V	p e@	V l
ap-	pa-	rent
V	p e@	V n t
ap-	pa-	rent-	ly
V	p e@	V n	t l i:
ap-	pa-	ri-	tion
{	p @r	I	S V n
ap-	pa-	ri-	tions
{	p @r	I	S V n z
ap-	pal-	ling
V	p O:	l I N
ap-	pal-	ling-	ly
V	p O:	l I N	l i:
ap-	pall
V	p O: l
ap-	palled
V	p O: l d
ap-	palls
V	p O: l z
ap-	pe-	ti-	zer
{	p V	t aI	z @r
ap-	pe-	ti-	zers
{	p V	t aI	z @r z
ap-	pe-	ti-	zing
{	p V	t aI	z I N
ap-	pe-	tite
{	p V	t aI t
ap-	pe-	tites
{	p V	t aI t s
ap-	pea-	la-	ble
V	p i:	l V	b V l
ap-	pea-	ling
V	p i:	l I N
ap-	pea-	ling-	ly
V	p i:	l I N	l i:
ap-	pea-	ran-	ces
V	p I@	V n	s V z
ap-	pea-	rance
V	p I@	V n s
ap-	pea-	ring
V	p I@	I N
ap-	pea-	sing
V	p i:	z I N
ap-	peal
V	p i: l
ap-	pealed
V	p i: l d
ap-	peals
V	p i: l z
ap-	pear
V	p I@
ap-	peared
V	p I@ d
ap-	pears
V	p I@ z
ap-	pease
V	p i: z
ap-	pease-	ment
V	p i: z	m V n t
ap-	peased
V	p i: z d
ap-	pel
{	p V l
ap-	pel-	la-	tion
{	p V	l eI	S V n
ap-	pel-	la-	tions
{	p V	l eI	S V n z
ap-	pel-	late
V	p e	l V t
ap-	pen-	da-	ges
V	p e n	d I	dZ V z
ap-	pen-	dage
V	p e n	d I dZ
ap-	pen-	dec-	to-	mies
{	p V n	d e k	t V	m i: z
ap-	pen-	dec-	to-	my
{	p V n	d e k	t V	m i:
ap-	pen-	ded
V	p e n	d V d
ap-	pen-	di-	xes
V	p e n	d I k	s V z
ap-	pen-	dix
V	p e n	d I k s
ap-	pend
V	p e n d
ap-	pert
{	p @r t
ap-	pi-	a
{	p i:	V
ap-	pi-	an
{	p i:	V n
ap-	ple
{	p V l
ap-	poin-	ted
V	p OI n	t V d
ap-	poin-	tee
V	p OI n	t i:
ap-	poin-	tees
V	p OI n	t i: z
ap-	poin-	ting
V	p OI n	t I N
ap-	poin-	tive
V	p OI n	t I v
ap-	point
V	p OI n t
ap-	point-	ment
V	p OI n	t m V n t
ap-	point-	ments
V	p OI n	t m V n t s
ap-	points
V	p OI n t s
ap-	por-	tio-	ning
V	p O@	S V	n I N
ap-	por-	tion
V	p O@	S V n
ap-	por-	tion-	ment
V	p O@	S V n	m V n t
ap-	por-	tioned
V	p O@	S V n d
ap-	pro-	pri-	a-	ting
V p	r @U p	r i:	eI	t I N
ap-	pro-	pri-	a-	tion
V p	r @U p	r i:	eI	S V n
ap-	pro-	pri-	a-	tions
V p	r @U p	r i:	eI	S V n z
ap-	pro-	pri-	a-	tor
V p	r @U p	r i:	eI	t @r
ap-	pro-	pri-	a-	tors
V p	r @U p	r i:	eI	t @r z
ap-	pro-	pri-	ate-	ly
V p	r @U p	r i:	V t	l i:
ap-	pro-	pri-	ate-	ness
V p	r @U p	r i:	V t	n V s
ap-	pro-	pri-	ates
V p	r @U p	r i:	eI t s
ap-	pro-	va-	ble
V p	r u:	v V	b V l
ap-	pro-	val
V p	r u:	v V l
ap-	pro-	vals
V p	r u:	v V l z
ap-	pro-	ving
V p	r u:	v I N
ap-	pro-	ving-	ly
V p	r u:	v I N	l i:
ap-	pro-	xi-	ma-	ted
V p	r Q k	s V	m eI	t V d
ap-	pro-	xi-	ma-	ting
V p	r Q k	s V	m eI	t I N
ap-	pro-	xi-	ma-	tion
V p	r Q k	s V	m eI	S V n
ap-	pro-	xi-	ma-	tions
V p	r Q k	s V	m eI	S V n z
ap-	pro-	xi-	mate
V p	r Q k	s V	m V t
ap-	pro-	xi-	mate-	ly
V p	r Q k	s V	m V t	l i:
ap-	pro-	xi-	mates
V p	r Q k	s V	m V t s
ap-	prove
V p	r u: v
ap-	proved
V p	r u: v d
ap-	proves
V p	r u: v z
ap-	ra
eI p	r V
ap-	ri-	cot
eI p	r I	k Q t
ap-	ri-	cots
{ p	r I	k Q t s
ap-	ril
eI p	r I l
ap-	rile
Q p	r I l
ap-	ril's
eI p	r I l z
ap-	ro-	pos
{ p	r V	p @U
ap-	ron
eI p	r V n
ap-	rons
eI p	r V n z
ap-	so
{ p	s @U
ap-	ter
{ p	t @r
ap-	ti-	tude
{ p	t I	t u: d
ap-	ti-	tudes
{ p	t I	t u: d z
ape
eI p
ape-	like
eI p	l aI k
apes
eI p s
aph-	ro-	di-	si-	ac
{ f	r @U	d i:	z i:	{ k
aph-	ro-	di-	te
{ f	r V	d aI	t i:
aph-	ro-	di-	tes
{ f	r V	d aI	t i: z
aph-	ro-	di-	te's
{ f	r V	d aI	t i: z
app
{ p
app-	lau-	ded
V p	l O:	d V d
app-	lau-	ding
V p	l O:	d I N
app-	laud
V p	l O: d
app-	lauds
V p	l O: d z
app-	lause
V p	l O: z
app-	lied
V p	l aI d
app-	lies
V p	l aI z
app-	ly
V p	l aI
app-	ly-	ing
V p	l aI	I N
app-	rai-	sal
V p	r eI	z V l
app-	rai-	sals
V p	r eI	z V l z
app-	rai-	ser
V p	r eI	z @r
app-	rai-	sers
V p	r eI	z @r z
app-	rai-	ses
V p	r eI	z V z
app-	rai-	sing
V p	r eI	z I N
app-	raise
V p	r eI z
app-	raised
V p	r eI z d
app-	re-	ci-	a-	ted
V p	r i:	S i:	eI	t V d
app-	re-	ci-	a-	ting
V p	r i:	S i:	eI	t I N
app-	re-	ci-	a-	tion
V p	r i:	S i:	eI	S V n
app-	re-	ci-	a-	tive
V p	r i:	S i:	eI	t I v
app-	re-	ci-	a-	tive-	ly
V p	r i:	S i:	eI	t I v	l i:
app-	re-	ci-	ate
V p	r i:	S i:	eI t
app-	re-	ci-	ates
V p	r i:	S i:	eI t s
app-	re-	cia-	ble
V p	r i:	S V	b V l
app-	re-	ciab-	ly
V p	r i:	S V b	l i:
app-	re-	hen-	ded
{ p	r V	h e n	d V d
app-	re-	hen-	ding
{ p	r V	h e n	d I N
app-	re-	hen-	sion
{ p	r V	h e n	S V n
app-	re-	hen-	sions
{ p	r V	h e n	S V n z
app-	re-	hen-	sive
{ p	r V	h e n	s I v
app-	re-	hend
{ p	r V	h e n d
app-	ren-	ti-	ces
V p	r e n	t V	s V z
app-	ren-	tice
V p	r e n	t V s
app-	ren-	tice-	ship
V p	r e n	t V s	S I p
app-	ren-	tice-	ships
V p	r e n	t V s	S I p s
app-	ren-	ticed
V p	r e n	t V s t
app-	rise
V p	r aI z
app-	rised
V p	r aI z d
app-	ro-	ba-	tion
{ p	r V	b eI	S V n
app-	ro-	pri-	a-	ted
V p	r @U p	r i:	eI	t V d
app-	ro-	pri-	ate
V p	r @U p	r i:	V t
app-	roa-	cha-	ble
V p	r @U	tS V	b V l
app-	roa-	ches
V p	r @U	tS V z
app-	roa-	ching
V p	r @U	tS I N
app-	roach
V p	r @U tS
app-	roached
V p	r @U tS t
apps
{ p s
apt
{ p t
apt-	ly
{ p	t l i:
ar
Q@
ar-	ba
Q@	b V
ar-	bi-	ter
Q@	b I	t @r
ar-	bi-	ters
Q@	b I	t @r z
ar-	bit-	ra-	ger
Q@	b I t	r Q	Z @r
ar-	bit-	ra-	gers
Q@	b I t	r Q	Z @r z
ar-	bit-	ra-	geur
Q@	b I t	r Q	Z @r
ar-	bit-	ra-	geurs
Q@	b I t	r Q	Z @r z
ar-	bit-	ra-	ging
Q@	b I t	r Q	dZ I N
ar-	bit-	ra-	ri-	ly
Q@	b I t	r e@	V	l i:
ar-	bit-	ra-	ri-	ness
Q@	b I t	r e@	i:	n V s
ar-	bit-	ra-	ry
Q@	b I t	r e@	i:
ar-	bit-	ra-	ted
Q@	b I t	r eI	t V d
ar-	bit-	ra-	ting
Q@	b I t	r eI	t I N
ar-	bit-	ra-	tion
Q@	b I t	r eI	S V n
ar-	bit-	ra-	tions
Q@	b I t	r eI	S V n z
ar-	bit-	ra-	tor
Q@	b I t	r eI	t @r
ar-	bit-	ra-	tors
Q@	b I t	r eI	t @r z
ar-	bit-	ra-	tor's
Q@	b I t	r eI	t @r z
ar-	bit-	rage
Q@	b I t	r Q Z
ar-	bit-	rate
Q@	b I t	r eI t
ar-	bit-	rates
Q@	b I t	r eI t s
ar-	bit-	ron
Q@	b I t	r Q n
ar-	bo-	re-	al
Q@	b O@	i:	V l
ar-	bo-	re-	tum
Q@	b @r	i:	t V m
ar-	bor
Q@	b @r
ar-	bour
Q@	b @r
ar-	bu-	ckle
Q@	b V	k V l
ar-	buth-	not
Q@	b V T	n V t
ar-	ca-	di-	a
Q@	k eI	d i:	V
ar-	ca-	di-	an
Q@	k eI	d i:	V n
ar-	ca-	di-	ans
Q@	k eI	d i:	V n z
ar-	ca-	na
Q@	k {	n V
ar-	ca-	num
Q@	k V	n V m
ar-	ca-	num's
Q@	k V	n V m z
ar-	ca-	ro
Q@	k Q@	@U
ar-	ca-	ta
Q@	k Q	t V
ar-	cade
Q@	k eI d
ar-	cades
Q@	k eI d z
ar-	cane
Q@	k eI n
ar-	cha-	ic
Q@	k eI	I k
ar-	chae-	o-	lo-	gi-	cal
Q@	k i:	V	l Q	dZ I	k V l
ar-	chae-	o-	lo-	gist
Q@	k i:	Q	l V	dZ V s t
ar-	chae-	o-	lo-	gists
Q@	k i:	Q	l V	dZ V s t s
ar-	chae-	o-	lo-	gy
Q@	k i:	Q	l V	dZ i:
ar-	cham-	bault
Q@	S V m	b @U
ar-	chan-	gel
Q@	k eI n	dZ V l
ar-	chan-	gels
Q@	k eI n	dZ V l z
ar-	che-	ne-	my
Q@	tS e	n V	m i:
ar-	che-	o-	lo-	gi-	cal
Q@	k i:	V	l Q	dZ I	k V l
ar-	che-	o-	lo-	gy
Q@	k i:	Q	l V	dZ i:
ar-	che-	ry
Q@	tS @r	i:
ar-	che-	type
Q@	k V	t aI p
ar-	che-	types
Q@	k V	t aI p s
ar-	cher
Q@	tS @r
ar-	cher's
Q@	tS @r z
ar-	ches
Q@	tS V z
ar-	chi-	bald
Q@	tS I	b O: l d
ar-	chi-	me-	des
Q@	k I	m i:	d i: z
ar-	chi-	pe-	la-	go
Q@	k I	p e	l V	g @U
ar-	chi-	tec-	tu-	ral
Q@	k I	t e k	tS @r	V l
ar-	chi-	tec-	tu-	ral-	ly
Q@	k I	t e k	tS @r	V	l i:
ar-	chi-	tec-	ture
Q@	k I	t e k	tS @r
ar-	chi-	tec-	tures
Q@	k I	t e k	tS @r z
ar-	chi-	tect
Q@	k I	t e k t
ar-	chi-	tects
Q@	k I	t e k t s
ar-	chi-	tect's
Q@	k I	t e k t s
ar-	chi-	trave
Q@	k I t	r eI v
ar-	chi-	traves
Q@	k I t	r eI v z
ar-	chi-	val
Q@	k aI	v V l
ar-	chi-	vist
Q@	k I	v I s t
ar-	chi-	vists
Q@	k I	v I s t s
ar-	chie
Q@	tS i:
ar-	ching
Q@	tS I N
ar-	chive
Q@	k aI v
ar-	chives
Q@	k aI v z
ar-	co
Q@	k @U
ar-	co-	la
Q@	k @U	l V
ar-	cos
Q@	k @U z
ar-	co's
Q@	k @U z
ar-	da
Q@	d V
ar-	dath
Q@	d V T
ar-	de-	li-	a
Q@	d e	l i:	V
ar-	deen
Q@	d i: n
ar-	del-	la
Q@	d e	l V
ar-	delle
Q@	d e l
ar-	den
Q@	d V n
ar-	dene
Q@	d i: n
ar-	den's
Q@	d V n z
ar-	dent
Q@	d V n t
ar-	dent-	ly
Q@	d V n	t l i:
ar-	di-	ne
Q@	d i:	n i:
ar-	di-	to
Q@	d i:	t @U
ar-	din
Q@	d I n
ar-	dis
Q@	d I s
ar-	dith
Q@	d I T
ar-	do-	li-	no
Q@	d @U	l i:	n @U
ar-	dor
Q@	d @r
ar-	du-	ous
Q@	dZ u:	V s
ar-	gall
Q@	g V l
ar-	gen-	ta
Q@	dZ e n	t V
ar-	gen-	ti-	na
Q@	dZ V n	t i:	n V
ar-	gen-	ti-	na's
Q@	dZ V n	t i:	n V z
ar-	gen-	ti-	ni-	an
Q@	dZ V n	t I	n i:	V n
ar-	gen-	ti-	ni-	ans
Q@	dZ V n	t I	n i:	V n z
ar-	gen-	tine
Q@	dZ V n	t i: n
ar-	gen-	tines
Q@	dZ V n	t i: n z
ar-	gent
Q@	dZ V n t
ar-	go
Q@	g @U
ar-	go-	naut
Q@	g V	n O: t
ar-	go-	nauts
Q@	g V	n O: t s
ar-	go-	naut's
Q@	g V	n O: t s
ar-	go-	sy
Q@	g V	s i:
ar-	gon
Q@	g Q n
ar-	gonne
Q@	g Q n
ar-	go's
Q@	g @U z
ar-	got
Q@	g V t
ar-	gu-	a-	ble
Q@ g	j u:	V	b V l
ar-	gu-	ab-	ly
Q@ g	j u:	V b	l i:
ar-	gu-	ing
Q@ g	j u:	I N
ar-	gu-	men-	ta-	tion
Q@ g	j V	m e n	t eI	S V n
ar-	gu-	men-	ta-	tive
Q@ g	j V	m e n	t V	t I v
ar-	gu-	ment
Q@ g	j V	m V n t
ar-	gu-	ments
Q@ g	j V	m V n t s
ar-	gu-	ment's
Q@ g	j V	m V n t s
ar-	gue
Q@ g	j u:
ar-	gued
Q@ g	j u: d
ar-	gues
Q@ g	j u: z
ar-	gus
Q@	g V s
ar-	gyle
Q@	g aI l
ar-	gyll
Q@	g aI l
ar-	ka-	del-	phi-	a
Q@	k V	d e l	f i:	V
ar-	kan-	san
Q@	k { n	z V n
ar-	kan-	sans
Q@	k { n	z V n z
ar-	kan-	sas
Q@	k V n	s Q
ar-	kan-	sas's
Q@	k V n	s Q z
ar-	kose
Q@	k @U s
ar-	la-	na
Q@	l {	n V
ar-	le-	na
Q@	l e	n V
ar-	le-	ta
Q@	l e	t V
ar-	leen
Q@	l i: n
ar-	len
Q@	l V n
ar-	lene
Q@	l i: n
ar-	lene's
Q@	l i: n z
ar-	lette
Q@	l e t
ar-	ley
Q@	l i:
ar-	lie
Q@	l i:
ar-	lin
Q@	l I n
ar-	lin-	da
Q@	l I n	d V
ar-	line
Q@	l aI n
ar-	ling-	ton
Q@	l I N	t V n
ar-	ling-	ton's
Q@	l I N	t V n z
ar-	lyne
Q@	l aI n
ar-	ma-	da
Q@	m Q	d V
ar-	ma-	dil-	lo
Q@	m V	d I	l @U
ar-	ma-	dil-	los
Q@	m V	d I	l @U z
ar-	ma-	ged-	don
Q@	m V	g e	d V n
ar-	ma-	ment
Q@	m V	m V n t
ar-	ma-	ments
Q@	m V	m V n t s
ar-	ma-	ni
Q@	m Q	n i:
ar-	man
Q@	m V n
ar-	man-	do
Q@	m Q n	d @U
ar-	mand
Q@	m V n d
ar-	me-	ni-	a
Q@	m i:	n i:	V
ar-	me-	ni-	an
Q@	m i:	n i:	V n
ar-	me-	ni-	ans
Q@	m i:	n i:	V n z
ar-	me-	ni-	a's
Q@	m i:	n i:	V z
ar-	men
Q@	m V n
ar-	mer
Q@	m @r
ar-	mi-	da
Q@	m i:	d V
ar-	mi-	ger
Q@	m I	g @r
ar-	mi-	na
Q@	m i:	n V
ar-	mi-	ne
Q@	m i:	n i:
ar-	mi-	tage
Q@	m I	t I dZ
ar-	mies
Q@	m i: z
ar-	mil-	la
Q@	m I	l V
ar-	min
Q@	m I n
ar-	ming
Q@	m I N
ar-	ming-	ton
Q@	m I N	t V n
ar-	mis-	tice
Q@	m I s	t I s
ar-	mo-	ries
Q@	m @r	i: z
ar-	mo-	ry
Q@	m @r	i:
ar-	mond
Q@	m V n d
ar-	monk
Q@	m V N k
ar-	mor
Q@	m @r
ar-	mored
Q@	m @r d
ar-	mour
Q@	m @r
ar-	my
Q@	m i:
ar-	my's
Q@	m i: z
ar-	nal-	do
Q@	n Q l	d @U
ar-	naud
Q@	n @U
ar-	nelle
Q@	n e l
ar-	nelle's
Q@	n e l z
ar-	nett
Q@	n e t
ar-	ney
Q@	n i:
ar-	nie
Q@	n i:
ar-	no
Q@	n @U
ar-	nold
Q@	n V l d
ar-	nold's
Q@	n V l d z
ar-	not
Q@	n V t
ar-	nul-	fo
Q@	n V l	f @U
ar-	pa
Q@	p V
ar-	pa-	net
Q@	p V	n e t
ar-	pin
Q@	p I n
ar-	raign
@r	eI n
ar-	raign-	ment
@r	eI n	m V n t
ar-	raign-	ments
@r	eI n	m V n t s
ar-	raigned
@r	eI n d
ar-	ran-	ger
@r	eI n	dZ @r
ar-	ran-	ges
@r	eI n	dZ V z
ar-	ran-	ging
@r	eI n	dZ I N
ar-	range
@r	eI n dZ
ar-	range-	ment
@r	eI n	dZ m V n t
ar-	range-	ments
@r	eI n	dZ m V n t s
ar-	ranged
@r	eI n dZ d
ar-	ray
@r	eI
ar-	rayed
@r	eI d
ar-	rays
@r	eI z
ar-	rea-	ra-	ges
@r	I@	I	dZ V z
ar-	rea-	rage
@r	i:	r I dZ
ar-	rears
@r	I@ z
ar-	res-	ted
@r	e s	t V d
ar-	res-	ting
@r	e s	t I N
ar-	rest
@r	e s t
ar-	rests
@r	e s t s
ar-	rhyth-	mi-	a
@r	I D	m i:	V
ar-	rhyth-	mi-	as
@r	I D	m i:	V z
ar-	ri-	go
Q@	i:	g @U
ar-	ri-	val
@r	aI	v V l
ar-	ri-	vals
@r	aI	v V l z
ar-	ri-	ving
@r	aI	v I N
ar-	ring-	ton
e@	I N	t V n
ar-	ris
{	r I s
ar-	rive
@r	aI v
ar-	rived
@r	aI v d
ar-	rives
@r	aI v z
ar-	ro-	gance
e@	V	g V n s
ar-	ro-	gant
e@	V	g V n t
ar-	ro-	gant-	ly
e@	V	g V n	t l i:
ar-	ro-	gate
{	r @U	g eI t
ar-	ro-	yo
@r	OI	@U
ar-	ro-	yo's
@r	OI	@U z
ar-	row
{	r @U
ar-	row-	head
{	r @U	h e d
ar-	row-	heads
{	r @U	h e d z
ar-	row-	root
{	r @U	r u: t
ar-	rows
{	r @U z
ar-	row's
{	r @U z
ar-	rows-	mith
{	r @U s	m I T
ar-	rows-	mith's
{	r @U s	m I T s
ar-	se-	nal
Q@	s V	n V l
ar-	se-	nals
Q@	s V	n V l z
ar-	se-	nic
Q@	s V	n I k
ar-	se-	nide
Q@	s V	n aI d
ar-	so-	nist
Q@	s V	n V s t
ar-	so-	nists
Q@	s V	n V s t s
ar-	son
Q@	s V n
ar-	sons
Q@	s V n z
ar-	te-	mas
Q@	t V	m V z
ar-	te-	mus
Q@	t V	m V s
ar-	te-	ri-	al
Q@	t I@	i:	V l
ar-	te-	ri-	osc-	le-	ro-	sis
Q@	t I@	i:	@U s	k l @r	@U	s I s
ar-	te-	ries
Q@	t @r	i: z
ar-	te-	ry
Q@	t @r	i:
ar-	te-	sian
Q@	t i:	Z V n
ar-	ter
Q@	t @r
ar-	thu-	ri-	an
Q@	T U@	i:	V n
ar-	thur
Q@	T @r
ar-	thur's
Q@	T @r z
ar-	ti-	choke
Q@	t I	tS @U k
ar-	ti-	chokes
Q@	t I	tS @U k s
ar-	ti-	cle
Q@	t I	k V l
ar-	ti-	cles
Q@	t I	k V l z
ar-	ti-	cle's
Q@	t I	k V l z
ar-	ti-	cu-	la-	ted
Q@	t I k	j V	l eI	t V d
ar-	ti-	cu-	la-	ting
Q@	t I k	j V	l eI	t I N
ar-	ti-	cu-	la-	tion
Q@	t I k	j V	l eI	S V n
ar-	ti-	cu-	la-	to-	ry
Q@	t I k	j V	l V	t O@	i:
ar-	ti-	cu-	late
Q@	t I k	j V	l eI t
ar-	ti-	cu-	lates
Q@	t I k	j V	l V t s
ar-	ti-	fact
Q@	t I	f { k t
ar-	ti-	facts
Q@	t I	f { k t s
ar-	ti-	fi-	cial
Q@	t I	f I	S V l
ar-	ti-	fi-	cial-	ly
Q@	t I	f I	S V	l i:
ar-	ti-	fice
Q@	t I	f I s
ar-	ti-	o-	dac-	tyl
Q@	t i:	@U	d { k	t V l
ar-	ti-	o-	dac-	tyls
Q@	t i:	@U	d { k	t V l z
ar-	ti-	san
Q@	t I	z V n
ar-	ti-	sans
Q@	t I	z V n z
ar-	tie
Q@	t i:
ar-	til-	le-	ry
Q@	t I	l @r	i:
ar-	tis
Q@	t I s
ar-	tis-	tic
Q@	t I s	t I k
ar-	tis-	tical-	ly
Q@	t I s	t I k	l i:
ar-	tist
Q@	t I s t
ar-	tist-	ry
Q@	t I s	t r i:
ar-	tists
Q@	t I s t s
)"
R"(ar-	tist's
Q@	t I s t s
ar-	tois
Q@ t	w Q
ar-	tsy
Q@ t	s i:
ar-	tu-	ro
Q@	t U@	@U
ar-	tur
Q@	t U@
ar-	tus
Q@	t V s
ar-	ty
Q@	t i:
ar-	ty's
Q@	t i: z
ar-	va
Q@	v V
ar-	vad
Q@	v { d
ar-	val
Q@	v V l
ar-	vel
Q@	v e l
ar-	vi-	da
Q@	v i:	d V
ar-	vi-	da's
Q@	v i:	d V z
ar-	vid
Q@	v I d
ar-	vin
Q@	v I n
ar-	vind
Q@	v I n d
ar-	vin's
Q@	v I n z
ar-	y-	an
Q@	i:	V n
arb
Q@ b
arbs
Q@ b z
arc
Q@ k
arc-	tu-	rus
Q@ k	t U@	V s
arce
Q@ s
arch
Q@ tS
arch-	bi-	shop
Q@ tS	b I	S V p
arch-	bold
Q@ tS	b @U l d
arch-	di-	o-	cese
Q@ tS	d aI	V	s V s
arch-	duke
Q@ tS	d u: k
arch-	ly
Q@ tS	l i:
arch-	ri-	val
Q@ tS	r aI	v V l
arch-	ri-	vals
Q@ tS	r aI	v V l z
arch-	way
Q@ tS	w eI
arche-	ty-	pal
Q@ k	t aI	p V l
arched
Q@ tS t
ard
Q@ d
ard-	more
Q@ d	m O@
ard-	ra
Q@ d	r V
ard-	rey
Q@ d	r i:
ards-	ley
Q@ d	z l i:
are
Q@
ares
Q@ z
ark
Q@ k
ark-	wright
Q@ k	r aI t
arm
Q@ m
arm-	band
Q@ m	b { n d
arm-	bands
Q@ m	b { n d z
arm-	brus-	ter
Q@ m	b r V s	t @r
arm-	brust
Q@ m	b r V s t
arm-	chair
Q@ m	tS e@
arm-	chairs
Q@ m	tS e@ z
arm-	co
Q@ m	k @U
arm-	co's
Q@ m	k @U z
arm-	pit
Q@ m	p I t
arm-	pits
Q@ m	p I t s
arm-	rest
Q@ m	r e s t
arm-	rests
Q@ m	r e s t s
arm-	strong
Q@ m	s t r Q N
armed
Q@ m d
armes
Q@ m z
arms
Q@ m z
arm's
Q@ m z
arn
Q@ n
arndt
Q@ n t
arne
Q@ n
arnst
Q@ n s t
arp
Q@ p
art
Q@ t
art-	ful
Q@ t	f V l
art-	ful-	ly
Q@ t	f V	l i:
art-	work
Q@ t	w @r k
art-	works
Q@ t	w @r k s
arth-	ri-	tic
Q@ T	r I	t I k
arth-	ro-	pods
Q@ T	r V	p Q d z
arts
Q@ t s
art's
Q@ t s
arx
Q@ k s
as
{ z
a's
eI z
as-	bes-	to-	sis
{ s	b e s	t @U	s I s
as-	bes-	tos
{ s	b e s	t V s
as-	bu-	ry
{ z	b e@	i:
as-	cap
{ s	k { p
as-	cen-	dan-	cy
V	s e n	d V n	s i:
as-	cen-	dance
V	s e n	d V n s
as-	cen-	dant
V	s e n	d V n t
as-	cen-	ded
V	s e n	d V d
as-	cen-	den-	cy
V	s e n	d V n	s i:
as-	cen-	ding
V	s e n	d I N
as-	cen-	sion
V	s e n	S V n
as-	cend
V	s e n d
as-	cends
V	s e n d z
as-	cii
{ s	k i:
as-	cor-	bic
V s	k O@	b I k
as-	cot
{ s	k Q t
as-	cribe
V s	k r aI b
as-	cribed
V s	k r aI b d
as-	cribes
V s	k r aI b z
as-	kance
V s	k { n s
as-	ker
{ s	k @r
as-	kers
{ s	k @r z
as-	ker's
{ s	k @r z
as-	kew
V s	k j u:
as-	key
V s	k i:
as-	king
{ s	k I N
as-	leep
V s	l i: p
as-	ma-	ra
{ z	m Q@	V
as-	pa-	ra-	gus
V s	p e@	V	g V s
as-	par-	tame
{ s	p @r	t eI m
as-	pect
{ s	p e k t
as-	pects
{ s	p e k t s
as-	pen
{ s	p V n
as-	pens
{ s	p V n z
as-	pen's
{ s	p V n z
as-	per
{ s	p @r
as-	per-	sion
V s	p @r	Z V n
as-	per-	sions
V s	p @r	Z V n z
as-	phalt
{ s	f O: l t
as-	pi-	ra-	ted
{ s	p I	r eI	t I d
as-	pi-	ra-	tion
{ s	p @r	eI	S V n
as-	pi-	ra-	tions
{ s	p @r	eI	S V n z
as-	pi-	rant
{ s	p @r	V n t
as-	pi-	rants
{ s	p @r	V n t s
as-	pi-	rate
{ s	p I	r eI t
as-	pi-	rates
{ s	p I	r eI t s
as-	pi-	res
V s	p aI	@r z
as-	pi-	ring
V s	p aI	r I N
as-	pin-	wall
{ s	p I n	w O: l
as-	pire
V s	p aI r
as-	pired
V s	p aI r d
as-	quith
{ s	k w I T
as-	sad
V	s Q d
as-	sad's
V	s Q d z
as-	sai-	lant
V	s eI	l V n t
as-	sai-	lants
V	s eI	l V n t s
as-	sai-	lant's
V	s eI	l V n t s
as-	sai-	ling
V	s eI	l I N
as-	sail
V	s eI l
as-	sailed
V	s eI l d
as-	sails
V	s eI l z
as-	sas-	si-	na-	ted
V	s {	s V	n eI	t V d
as-	sas-	si-	na-	ting
V	s {	s V	n eI	t I N
as-	sas-	si-	na-	tion
V	s {	s V	n eI	S V n
as-	sas-	si-	na-	tions
V	s {	s V	n eI	S V n z
as-	sas-	si-	nate
V	s {	s V	n eI t
as-	sas-	sin
V	s {	s V n
as-	sas-	sins
V	s {	s V n z
as-	sas-	sin's
V	s {	s V n z
as-	saul-	ted
V	s O: l	t V d
as-	saul-	ting
V	s O: l	t I N
as-	saul-	tive
V	s O: l	t I v
as-	sault
V	s O: l t
as-	saults
V	s O: l t s
as-	say
{	s i:
as-	say-	er
{	s eI	@r
as-	sem-	b-	ling
V	s e m	b V	l I N
as-	sem-	ble
V	s e m	b V l
as-	sem-	bled
V	s e m	b V l d
as-	sem-	bles
V	s e m	b V l z
as-	semb-	lage
V	s e m	b l V dZ
as-	semb-	ler
V	s e m	b l @r
as-	semb-	lers
V	s e m	b l @r z
as-	semb-	lies
V	s e m	b l i: z
as-	semb-	ly
V	s e m	b l i:
as-	semb-	ly-	man
V	s e m	b l i:	m { n
as-	semb-	ly-	men
V	s e m	b l i:	m e n
as-	semb-	ly-	wo-	man
V	s e m	b l i:	w U	m V n
as-	semb-	ly's
V	s e m	b l i: z
as-	sent
V	s e n t
as-	ser-	ted
V	s @r	t V d
as-	ser-	ted-	ly
V	s @r	t V d	l i:
as-	ser-	ting
V	s @r	t I N
as-	ser-	tion
V	s @r	S V n
as-	ser-	tions
V	s @r	S V n z
as-	ser-	tive
V	s @r	t I v
as-	ser-	tive-	ly
V	s @r	t I v	l i:
as-	ser-	tive-	ness
V	s @r	t I v	n V s
as-	sert
V	s @r t
as-	serts
V	s @r t s
as-	ses
{	s V z
as-	ses-	ses
V	s e	s V z
as-	ses-	sing
V	s e	s I N
as-	ses-	sor
V	s e	s @r
as-	ses-	sors
V	s e	s @r z
as-	sess
V	s e s
as-	sess-	ment
V	s e s	m V n t
as-	sess-	ments
V	s e s	m V n t s
as-	sessed
V	s e s t
as-	set
{	s e t
as-	sets
{	s e t s
as-	si-	duous
V	s I d	w V s
as-	si-	duous-	ly
V	s I d	w V s	l i:
as-	si-	mi-	la-	ted
V	s I	m V	l eI	t V d
as-	si-	mi-	la-	ting
V	s I	m V	l eI	t I N
as-	si-	mi-	la-	tion
V	s I	m V	l eI	S V n
as-	si-	mi-	late
V	s I	m V	l eI t
as-	si-	si
V	s i:	s i:
as-	sig-	ning
V	s aI	n I N
as-	sign
V	s aI n
as-	sign-	ment
V	s aI n	m V n t
as-	sign-	ments
V	s aI n	m V n t s
as-	sign-	ment's
V	s aI n	m V n t s
as-	signed
V	s aI n d
as-	signs
V	s aI n z
as-	sis-	tance
V	s I s	t V n s
as-	sis-	tant
V	s I s	t V n t
as-	sis-	tants
V	s I s	t V n t s
as-	sis-	ted
V	s I s	t V d
as-	sis-	ting
V	s I s	t I N
as-	sist
V	s I s t
as-	sists
V	s I s t s
as-	so-	ci-	a-	ted
V	s @U	s i:	eI	t V d
as-	so-	ci-	a-	ting
V	s @U	s i:	eI	t I N
as-	so-	ci-	a-	tion
V	s @U	s i:	eI	S V n
as-	so-	ci-	a-	tions
V	s @U	s i:	eI	S V n z
as-	so-	ci-	a-	tion's
V	s @U	S i:	eI	S V n z
as-	so-	ci-	ate
V	s @U	s i:	V t
as-	so-	ci-	ates
V	s @U	s i:	V t s
as-	so-	ci-	ate's
V	s @U	s i:	V t s
as-	sor-	ted
V	s O@	t V d
as-	sort
V	s O@ t
as-	sort-	ment
V	s O@ t	m V n t
as-	suage
V s	w eI dZ
as-	suaged
V s	w eI dZ d
as-	ta
Q s	t V
as-	taire
V s	t e@
as-	te-	risk
{ s	t @r	I s k
as-	te-	roid
{ s	t @r	OI d
as-	te-	roids
{ s	t @r	OI d z
as-	te-	roid's
{ s	t @r	OI d z
as-	ter
{ s	t @r
as-	ters
{ s	t @r z
as-	tig-	ma-	ti-	sm
V s	t I g	m V	t I	z V m
as-	to-	ni-	shing
V s	t Q	n I	S I N
as-	to-	ni-	shing-	ly
V s	t Q	n I	S I N	l i:
as-	to-	nish
V s	t Q	n I S
as-	to-	nish-	ment
V s	t Q	n I S	m V n t
as-	to-	nished
V s	t Q	n I S t
as-	to-	ri-	a
{ s	t O@	i:	V
as-	ton
{ s	t V n
as-	tor
{ s	t @r
as-	tor's
{ s	t @r z
as-	toun-	ded
V s	t aU n	d V d
as-	toun-	ding
V s	t aU n	d I N
as-	toun-	ding-	ly
V s	t aU n	d I N	l i:
as-	tound
V s	t aU n d
as-	tounds
V s	t aU n d z
as-	tute
V s	t u: t
as-	tute-	ly
V s	t u: t	l i:
as-	tute-	ness
V s	t u: t	n V s
asc-	hoff
{ s	k h O: f
asch
{ S
ash
{ S
ash-	baugh
{ S	b O:
ash-	bu-	ry
{ S	b e@	i:
ash-	burn
{ S	b @r n
ash-	by
{ S	b i:
ash-	croft
{ S	k r O: f t
ash-	down
{ S	d aU n
ash-	ford
{ S	f @r d
ash-	land
{ S	l V n d
ash-	land's
{ S	l V n d z
ash-	ley
{ S	l i:
ash-	ley's
{ S	l i: z
ash-	lin
{ S	l I n
ash-	man
{ S	m V n
ash-	mead
{ S	m i: d
ash-	more
{ S	m O@
ash-	ton
{ S	t V n
ash-	ton's
{ S	t V n z
ash-	tray
{ S	t r eI
ash-	trays
{ S	t r eI z
ash-	well
{ S	w e l
ash-	wood
{ S	w U d
ashe
{ S
ashe-	ville
{ S	v I l
ask
{ s k
asked
{ s k t
asks
{ s k s
asp
{ s p
aspi-	rin
{ s	p r I n
aspi-	rin's
{ s	p r I n z
ass
{ s
assed
{ s t
ast
{ s t
ast-	ra
{ s	t r V
ast-	rad-	dle
V s	t r {	d V l
ast-	rak-	han
{ s	t r V	k Q n
ast-	ral
{ s	t r V l
ast-	ra's
{ s	t r V z
ast-	ray
V s	t r eI
ast-	red
{ s	t @r d
ast-	rid
{ s	t r I d
ast-	ride
V s	t r aI d
ast-	rin-	gent
V s	t r I n	dZ V n t
ast-	rin-	gents
V s	t r I n	dZ V n t s
ast-	ro
{ s	t r @U
ast-	ro-	dome
{ s	t r V	d @U m
ast-	ro-	ge-	o-	lo-	gy
{ s	t r V	dZ i:	Q	l V	dZ i:
ast-	ro-	lo-	ger
V s	t r Q	l V	dZ @r
ast-	ro-	lo-	gers
V s	t r Q	l V	dZ @r z
ast-	ro-	lo-	gi-	cal
{ s	t r V	l Q	dZ I	k V l
ast-	ro-	lo-	gy
V s	t r Q	l V	dZ i:
ast-	ro-	nau-	ti-	cal
{ s	t r V	n Q	t I	k V l
ast-	ro-	nau-	tic
{ s	t r V	n Q	t I k
ast-	ro-	nau-	tics
{ s	t r V	n Q	t I k s
ast-	ro-	naut
{ s	t r V	n Q t
ast-	ro-	nauts
{ s	t r V	n O: t s
ast-	ro-	naut's
{ s	t r V	n Q t s
ast-	ro-	no-	mer
V s	t r Q	n V	m @r
ast-	ro-	no-	mers
V s	t r Q	n V	m @r z
ast-	ro-	no-	mi-	cal
{ s	t r V	n Q	m I	k V l
ast-	ro-	no-	mical-	ly
{ s	t r V	n Q	m I k	l i:
ast-	ro-	no-	my
V s	t r Q	n V	m i:
ast-	ro-	pho-	tog-	ra-	phy
{ s	t r @U	f V	t Q g	r V	f i:
ast-	ro-	phy-	si-	cist
{ s	t r @U	f I	z I	s I s t
ast-	ro-	phy-	sics
{ s	t r @U	f I	z I k s
ast-	ro-	turf
{ s	t r @U	t @r f
asth-	ma
{ z	m V
asth-	ma-	tic
{ z	m {	t I k
asth-	ma-	tics
e s	T m e	t I k s
at
{ t
at-	bat
{ t	b { t
at-	co
{ t	k @U
at-	kin-	son
{ t	k I n	s V n
at-	kin-	son's
{ t	k I n	s V n z
at-	kin-	s's
{ t	k I n	z V z
at-	kins
{ t	k I n z
at-	la-	ses
{ t	l eI	s V z
at-	la-	s's
{ t	l V	s V z
at-	lan-	ta
{ t	l { n	t V
at-	lan-	tan
{ t	l { n	t V n
at-	lan-	tans
{ t	l { n	t V n z
at-	lan-	ta's
{ t	l { n	t V z
at-	lan-	ti-	ca
{ t	l { n	t I	k V
at-	lan-	ti-	s's
{ t	l { n	t I	s V z
at-	lan-	tic
V t	l { n	t I k
at-	lan-	tic's
V t	l { n	t I k s
at-	lan-	tis
{ t	l { n	t I s
at-	las
{ t	l V s
at-	mos-	phe-	ric
{ t	m V s	f e@	I k
at-	mos-	phe-	rics
{ t	m V s	f e@	I k s
at-	mos-	phere
{ t	m V s	f I@
at-	ra
eI t	r V
at-	ri-	a
eI t	r i:	V
at-	ri-	um
eI t	r i:	V m
at-	ro-	ci-	ties
V t	r Q	s V	t i: z
at-	ro-	ci-	ty
V t	r Q	s V	t i:
at-	ro-	cious
V t	r @U	S V s
at-	ro-	phied
{ t	r V	f i: d
at-	ro-	phy
{ t	r V	f i:
at-	ta
{	t V
at-	ta-	boy
{	t V	b OI
at-	ta-	boys
{	t V	b OI z
at-	ta-	che
{	t V	S eI
at-	ta-	ches
V	t {	tS V z
at-	ta-	ching
V	t {	tS I N
at-	tac-	ker
V	t {	k @r
at-	tac-	kers
V	t {	k @r z
at-	tac-	king
V	t {	k I N
at-	tach
V	t { tS
at-	tach-	ment
V	t { tS	m V n t
at-	tach-	ments
V	t { tS	m V n t s
at-	tached
V	t { tS t
at-	tack
V	t { k
at-	tacked
V	t { k t
at-	tacks
V	t { k s
at-	tai-	na-	ble
V	t eI	n V	b V l
at-	tai-	ning
V	t eI	n I N
at-	tain
V	t eI n
at-	tain-	der
V	t eI n	d @r
at-	tain-	ment
V	t eI n	m V n t
at-	tained
V	t eI n d
at-	tains
V	t eI n z
at-	tal-	la
V	t {	l V
at-	tar
{	t @r
at-	te-	nu-	a-	ted
V	t e n	j u:	eI	t V d
at-	te-	nu-	ate
V	t e n	j u:	eI t
at-	te-	nu-	ates
V	t e n	j u:	eI t s
at-	temp-	ted
V	t e m	p t V d
at-	temp-	ting
V	t e m	p t I N
at-	tempt
V	t e m p t
at-	tempts
V	t e m p t s
at-	ten-	bo-	rough
{	t V n	b @r	@U
at-	ten-	dance
V	t e n	d V n s
at-	ten-	dant
V	t e n	d V n t
at-	ten-	dants
V	t e n	d V n t s
at-	ten-	ded
V	t e n	d V d
at-	ten-	dee
V	t e n	d i:
at-	ten-	dees
V	t e n	d i: z
at-	ten-	ding
V	t e n	d I N
at-	ten-	tion
V	t e n	S V n
at-	ten-	tions
V	t e n	S V n z
at-	ten-	tive
V	t e n	t I v
at-	ten-	tive-	ly
V	t e n	t I v	l i:
at-	ten-	tive-	ness
V	t e n	t I v	n V s
at-	tend
V	t e n d
at-	tends
V	t e n d z
at-	ter-	bu-	ry
{	t @r	b e@	i:
at-	tes-	ted
V	t e s	t V d
at-	tes-	ting
V	t e s	t I N
at-	test
V	t e s t
at-	tests
V	t e s t s
at-	ti-	ca
{	t I	k V
at-	ti-	cus
{	t I	k V s
at-	ti-	la
V	t I	l V
at-	ti-	la's
V	t I	l V z
at-	ti-	re
V	t aI	@r
at-	ti-	tu-	di-	nal
{	t I	t u:	d I	n V l
at-	ti-	tude
{	t I	t u: d
at-	ti-	tudes
{	t I	t u: d z
at-	tic
{	t I k
at-	tics
{	t I k s
at-	tired
V	t aI r d
at-	tor-	ney
V	t @r	n i:
at-	tor-	neys
V	t @r	n i: z
at-	tor-	ney's
V	t @r	n i: z
at-	tune
V	t u: n
at-	tuned
V	t u: n d
at-	wa-	ter
{ t	w O:	t @r
at-	wood
{ t	w U d
at-	worth
{ t	w @r T
ate
eI t
ates
eI t s
ath-	lone
{ T	l @U n
ath-	wart
V T	w O@ t
att-	le-	bo-	ro
{	t V l	b @r	@U
att-	lee
{ t	l i:
att-	rac-	ted
V t	r { k	t V d
att-	rac-	ting
V t	r { k	t I N
att-	rac-	tion
V t	r { k	S V n
att-	rac-	tions
V t	r { k	S V n z
att-	rac-	tive
V t	r { k	t I v
att-	rac-	tive-	ly
V t	r { k	t I v	l i:
att-	rac-	tive-	ness
V t	r { k	t I v	n V s
att-	ract
V t	r { k t
att-	racts
V t	r { k t s
att-	ri-	bu-	ta-	ble
V t	r I b	j V	t V	b V l
att-	ri-	bu-	ted
V t	r I b	j V	t V d
att-	ri-	bu-	ting
V t	r I b	j V	t I N
att-	ri-	bu-	tion
{ t	r I b	j u:	S V n
att-	ri-	bute
{ t	r I b	j u: t
att-	ri-	butes
{ t	r I b	j u: t s
att-	ri-	tion
V t	r I	S V n
att-	wood
{ t	w U d
au
@U
au-	ber
O:	b @r
au-	ber-	ry
O:	b e@	i:
au-	bert
O:	b @r t
au-	bin
O:	b I n
au-	burn
Q	b @r n
au-	d-	rie
O:	d @r	i:
au-	di-	o-	philes
O:	d i:	@U	f i: l z
au-	di-	o-	tape
O:	d i:	@U	t eI p
au-	di-	o-	tapes
O:	d i:	@U	t eI p s
au-	di-	o-	vi-	su-	al
O:	d i:	@U	v I	Z u:	V l
au-	di-	ted
O:	d I	t V d
au-	di-	ting
Q	d I	t I N
au-	di-	tio-	ning
Q	d I	S V	n I N
au-	di-	tion
Q	d I	S V n
au-	di-	tioned
O:	d I	S V n d
au-	di-	tions
O:	d I	S V n z
au-	di-	to-	ri-	um
O:	d I	t O@	i:	V m
au-	di-	to-	ri-	ums
O:	d I	t O@	i:	V m z
au-	di-	to-	ry
O:	d I	t O@	i:
au-	di-	tor
O:	d I	t @r
au-	di-	tors
Q	d I	t @r z
au-	di-	tor's
O:	d I	t @r z
au-	di's
O:	d i: z
au-	dit
O:	d I t
au-	dits
Q	d I t s
au-	du-	bon
O:	d V	b Q n
au-	er
aU	@r
au-	er-	bach
aU	@r	b Q k
au-	ger
O:	g @r
au-	gers
O:	g @r z
au-	gu-	ring
O:	g @r	I N
au-	gur
O:	g @r
au-	gurs
O:	g @r z
au-	gus-	ta
V	g V s	t V
au-	gus-	ta's
V	g V s	t V z
au-	gus-	ti-	ni-	an
Q	g V s	t I	n i:	V n
au-	gus-	ti-	ni-	ans
Q	g V s	t I	n i:	V n z
au-	gus-	tin
aU	g u: s	t i: n
au-	gus-	tine
Q	g V s	t i: n
au-	gus-	to
O:	g V s	t @U
au-	gus-	tus
Q	g V s	t V s
au-	gust
Q	g V s t
au-	guste
O:	g V s t
au-	gust's
O:	g V s t s
au-	ra
O@	V
au-	ral
O@	V l
au-	re-	a
aU	r eI	Q
au-	re-	li-	o
aU	r eI	l i:	@U
au-	ri-	a
O@	i:	V
au-	ro-	ra
@r	O@	V
au-	ro-	ral
@r	O@	V l
au-	rum
O@	V m
au-	then-	ti-	ca-	ted
O:	T e n	t I	k eI	t V d
au-	then-	ti-	ca-	ting
O:	T e n	t I	k eI	t I N
au-	then-	ti-	ca-	tion
O:	T e n	t I	k eI	S V n
au-	then-	ti-	ca-	tions
O:	T e n	t I	k eI	S V n z
au-	then-	ti-	cate
O:	T e n	t I	k eI t
au-	then-	ti-	ci-	ty
O:	T V n	t I	s V	t i:
au-	then-	tic
V	T e n	t I k
au-	then-	tical-	ly
O:	T e n	t I k	l i:
au-	tho-	ri-	ta-	ri-	a-	ni-	sm
V	T O@	V	t e@	i:	V	n I	z V m
au-	tho-	ri-	ta-	ri-	an
V	T O@	V	t e@	i:	V n
au-	tho-	ri-	ta-	tive
V	T O@	V	t eI	t I v
au-	tho-	ri-	ta-	tive-	ly
V	T O@	V	t eI	t I v	l i:
au-	tho-	ri-	ties
V	T O@	V	t i: z
au-	tho-	ri-	ty
V	T O@	V	t i:
au-	tho-	ri-	ty's
V	T O@	V	t i: z
au-	tho-	ri-	za-	tion
O:	T @r	V	z eI	S V n
au-	tho-	ri-	za-	tions
O:	T @r	V	z eI	S V n z
au-	tho-	ri-	zes
O:	T @r	aI	z V z
au-	tho-	ri-	zing
O:	T @r	aI	z I N
au-	tho-	rize
O:	T @r	aI z
au-	tho-	rized
O:	T @r	aI z d
au-	thor
O:	T @r
au-	thor-	ship
O:	T @r	S I p
au-	thored
O:	T @r d
au-	thors
O:	T @r z
au-	thor's
O:	T @r z
au-	ti-	sm
O:	t I	z V m
au-	tis-	tic
O:	t I s	t I k
au-	to
O:	t @U
au-	to-	bahn
O:	t @U	b Q n
au-	to-	bi-	o-	gra-	pher
O:	t V	b aI	Q g	r V	f @r
au-	to-	bi-	o-	gra-	phi-	cal
O:	t V	b aI	V g	r {	f I	k V l
au-	to-	bi-	o-	gra-	phies
O:	t V	b aI	Q g	r V	f i: z
au-	to-	bi-	o-	gra-	phy
O:	t V	b aI	Q g	r V	f i:
au-	to-	graph
O:	t V g	r { f
au-	to-	graphed
O:	t V g	r { f t
au-	to-	graphs
O:	t V g	r { f s
au-	to-	ma-	ker
O:	t @U	m eI	k @r
au-	to-	ma-	kers
O:	t @U	m eI	k @r z
au-	to-	ma-	ta
O:	t Q	m V	t V
au-	to-	ma-	ted
O:	t V	m eI	t V d
au-	to-	ma-	tic
O:	t V	m {	t I k
au-	to-	ma-	tical-	ly
O:	t V	m {	t I k	l i:
au-	to-	ma-	tics
O:	t V	m {	t I k s
au-	to-	ma-	ting
O:	t V	m eI	t I N
au-	to-	ma-	tion
O:	t V	m eI	S V n
au-	to-	ma-	ton
O:	t Q	m V	t Q n
au-	to-	mate
O:	t V	m eI t
au-	to-	mates
O:	t V	m eI t s
au-	to-	mo-	bile
O:	t V	m @U	b i: l
au-	to-	mo-	biles
O:	t V	m @U	b i: l z
au-	to-	mo-	tive
O:	t V	m @U	t I v
au-	to-	no-	mic
O:	t V	n Q	m I k
au-	to-	no-	mous
O:	t Q	n V	m V s
au-	to-	no-	mous-	ly
O:	t Q	n @U	m V s	l i:
au-	to-	no-	my
O:	t Q	n V	m i:
au-	to-	pi-	lot
O:	t @U	p aI	l V t
au-	to-	ra-	di-	o-	graph
Q	t @U	r eI	d i:	@U g	r { f
au-	to-	tro-	phic
O:	t V t	r @U	f I k
au-	to-	wor-	ker
O:	t @U	w @r	k @r
au-	to-	wor-	kers
O:	t @U	w @r	k @r z
au-	toc-	lave
O:	t @U k	l eI v
au-	toc-	ra-	cy
O:	t Q k	r V	s i:
au-	toc-	ra-	tic
O:	t V k	r {	t I k
au-	toc-	rat
O:	t V k	r { t
au-	toi-	mmune
O:	t OI m	j u: n
au-	top-	sied
O:	t Q p	s i: d
au-	top-	sies
O:	t Q p	s i: z
au-	top-	sy
O:	t Q p	s i:
au-	tos
O:	t @U z
au-	to's
O:	t @U z
au-	tum-	nal
O:	t V m	n V l
au-	tumn
O:	t V m
au-	tumn's
O:	t V m z
au-	vil
@U	v I l
au-	xi-	er
O: k	s i:	@r
au-	xi-	lia-	ry
Q g	z I l	j @r	i:
aub-	rey
O: b	r i:
aub-	ry
O: b	r i:
aube
O: b
auc-	tio-	nee-	ring
O: k	S V	n I@	I N
auc-	tio-	neer
Q k	S V	n I@
auc-	tio-	neers
O: k	S V	n I@ z
auc-	tio-	ning
O: k	S V	n I N
auc-	tion
Q k	S V n
auc-	tioned
O: k	S V n d
auc-	tions
Q k	S V n z
auc-	tion's
O: k	S V n z
auck-	land
Q k	l V n d
aud-	rey
O: d	r i:
aud-	ris
@U d	r i: s
aud-	ry
O: d	r i:
aud-	win
O: d	w I n
aug-	men-	ta-	ble
Q g	m e n	t V	b V l
aug-	men-	ta-	tion
Q g	m e n	t eI	S V n
aug-	men-	ted
Q g	m e n	t V d
aug-	men-	ting
O: g	m e n	t I N
aug-	ment
O: g	m e n t
auge
O: dZ
)"
R"(augs-	burg
O: g	z b @r g
aul
O: l
auld
O: l d
ault
O: l t
ault-	man
O: l	t m V n
aun-	tie
{ n	t i:
aune
O: n
aunt
{ n t
aunts
{ n t s
aunt's
{ n t s
aus
aU z
aus-	lan-	der
aU s	l V n	d @r
aus-	pi-	ces
O: s	p I	s V z
aus-	pi-	cious
Q s	p I	S V s
aus-	pice
O: s	p I s
aus-	sie
O:	s i:
aus-	te-	ri-	ty
O: s	t e@	I	t i:
aus-	tell
aU s	t V l
aus-	ten
O: s	t V n
aus-	ten's
O: s	t V n z
aus-	ter
O: s	t @r
aus-	tere
O: s	t I@
aus-	tere-	ly
O: s	t I@	l i:
aus-	tin
O: s	t I n
aus-	tine
O: s	t i: n
aus-	tin's
O: s	t I n z
aus-	ton
O: s	t V n
ausch-	witz
O: S	w I t s
aust
O: s t
aust-	ra-	la-	sia
O: s	t r V	l eI	Z V
aust-	ra-	lia
O: s	t r eI l	j V
aust-	ra-	lian
O: s	t r eI l	j V n
aust-	ra-	lians
O: s	t r eI l	j V n z
aust-	ra-	lia's
O: s	t r eI l	j V z
aust-	ra-	lo-	pi-	the-	cine
O: s	t r eI	l @U	p I	T V	s aI n
aust-	ra-	lo-	pi-	the-	cus
O: s	t r eI	l @U	p I	T V	k V s
aust-	ra-	sia
O: s	t r eI	Z V
aust-	ral
O: s	t r V l
aust-	rals
O: s	t r V l z
aust-	ri-	a
O: s	t r i:	V
aust-	ri-	an
O: s	t r i:	V n
aust-	ri-	ans
O: s	t r i:	V n z
aust-	ri-	a's
O: s	t r i:	V z
aust-	ro-	a-	si-	a-	tic
O: s	t r @U	eI	Z i:	{	t I k
aut-	rey
O: t	r i:
aut-	ry
O: t	r i:
auth
O: T
aux
@U
av-	ner
{ v	n @r
av-	ra-	ham
eI v	r V	h { m
av-	ram
eI v	r V m
av-	ril
{ v	r I l
aw
O:
aw-	ful
Q	f V l
aw-	ful-	ness
O:	f V l	n V s
aw-	ning
Q	n I N
aw-	ry
@r	aI
awb
Q w b
awe
Q
awe-	some
Q	s V m
awe-	some-	ly
Q	s V m	l i:
awe-	struck
Q s	t r V k
awed
O: d
awest-	ruck
Q s	t r V k
awful-	ly
Q f	l i:
awk-	ward
Q k	w @r d
awk-	ward-	ly
Q k	w @r d	l i:
awk-	ward-	ness
Q k	w @r d	n V s
ax
{ k s
ax-	tell
{ k	s t e l
ax-	ton
{ k	s t V n
axe
{ k s
axed
{ k s t
ay
eI
ay-	de-	lotte
eI	d V	l Q t
ay-	din
eI	d I n
aye
aI
ayer's
e@ z
ayes
aI z
ayk-	royd
eI k	r OI d
ayl-	mer
eI l	m @r
ayl-	ward
eI l	w @r d
ayls-	worth
eI l	s w @r T
ayn
eI n
ayr
eI r
ayre
e@
ayres
e@ z
az-	pur-	u-	a
{ z	p j U@	u:	V
az-	te-	ca
{ z	t e	k V
az-	tec
{ z	t e k
az-	tecs
{ z	t e k s
b
bh i:
b-	b-	c
bh i:	b i:	s i:
b-	b-	q
bh i:	b i: k	j u:
b-	t
bh i:	t i:
b-	y-	u
bh i:	w aI	j u:
b-	yam
bh aI	V m
b.
bh i:
ba-	ba
bh Q	b V
ba-	bel
bh {	b V l
ba-	ber
bh eI	b @r
ba-	bette
bh V	b e t
ba-	bi-	ta
bh Q	b i:	t V
ba-	bies
bh eI	b i: z
ba-	bies'
bh eI	b i: z
ba-	bins-	ki
bh V	b I n	s k i:
ba-	bish
bh {	b I S
ba-	boon
bh V	b u: n
ba-	boons
bh {	b u: n z
ba-	boon's
bh {	b u: n z
ba-	bu
bh Q	b u:
ba-	bush-	ka
bh V	b U S	k V
ba-	bush-	kas
bh V	b U S	k V z
ba-	by
bh eI	b i:
ba-	by-	hood
bh eI	b i:	h U d
ba-	by-	ish
bh eI	b i:	I S
ba-	by-	lo-	ni-	an
bh {	b V	l @U	n i:	V n
ba-	by-	lo-	ni-	ans
bh {	b V	l @U	n i:	V n z
ba-	by-	lon
bh {	b V	l Q n
ba-	by-	sat
bh eI	b i:	s { t
ba-	by-	sit
bh eI	b i:	s I t
ba-	by-	sit-	ter
bh eI	b i:	s I	t @r
ba-	by-	sit-	ters
bh eI	b i:	s I	t @r z
ba-	by-	sit-	ting
bh eI	b i:	s I	t I N
ba-	by's
bh eI	b i: z
ba-	call
bh V	k O: l
ba-	car-	di
bh V	k Q@	d i:
ba-	cha-	rach
bh {	k @r	{ k
ba-	che-	lor
bh {	tS V	l @r
ba-	che-	lor's
bh {	tS V	l @r z
ba-	chel-	ler
bh Q	k V	l @r
ba-	che's
bh {	tS V z
ba-	cil-	lus
bh V	s I	l V s
ba-	ckache
bh {	k eI k
ba-	ckaches
bh {	k eI k s
ba-	con
bh eI	k V n
ba-	con's
bh eI	k V n z
ba-	den
bh eI	d V n
ba-	den's
bh Q	d V n z
ba-	der
bh {	d @r
ba-	ez
bh aI	e z
ba-	gel
bh eI	g V l
ba-	gels
bh eI	g V l z
ba-	ha-	ma
bh V	h Q	m V
ba-	ha-	mas
bh V	h Q	m V z
ba-	ha-	mi-	an
bh V	h eI	m i:	V n
ba-	ham
bh Q	V m
ba-	han
bh {	h V n
ba-	hi-	a
bh Q	h i:	V
ba-	ja
bh Q	h Q
ba-	ka
bh Q	k V
ba-	ke-	ries
bh eI	k @r	i: z
ba-	ke-	ry
bh eI	k @r	i:
ba-	ker
bh eI	k @r
ba-	kers
bh eI	k @r z
ba-	ker's
bh eI	k @r z
ba-	kers-	field
bh eI	k @r z	f i: l d
ba-	king
bh eI	k I N
ba-	ku
bh Q	k u:
ba-	ku-	la
bh V	k u:	l V
ba-	la
bh Q	l V
ba-	la-	ta
bh {	l V	t V
ba-	lan
bh eI	l V n
ba-	lan-	cer
bh {	l V n	s @r
ba-	lan-	ces
bh {	l V n	s V z
ba-	lan-	chine
bh {	l V n	tS i: n
ba-	lan-	chine's
bh {	l V n	tS i: n z
ba-	lan-	cing
bh {	l V n	s I N
ba-	lance
bh {	l V n s
ba-	lanced
bh {	l V n s t
ba-	las
bh {	l V s
ba-	leen
bh V	l i: n
ba-	les-	tra
bh V	l e s	t r V
ba-	li
bh Q	l i:
ba-	li-	an
bh eI	l i:	V n
ba-	li-	nese
bh {	l I	n i: z
ba-	ling
bh eI	l I N
ba-	lo-	ney
bh V	l @U	n i:
ba-	lon
bh Q	l O: n
ba-	low
bh {	l @U
ba-	lu-	chi
bh V	l u:	tS i:
ba-	na-	li-	ties
bh V	n {	l V	t i: z
ba-	na-	li-	ty
bh V	n {	l V	t i:
ba-	na-	na
bh V	n {	n V
ba-	na-	nas
bh V	n {	n V z
ba-	nach
bh {	n V k
ba-	nal
bh V	n Q l
ba-	ner-	jee
bh V	n @r	dZ i:
ba-	ni-	a
bh Q	n i:	V
ba-	ni-	shing
bh {	n I	S I N
ba-	nis-	ter
bh {	n I s	t @r
ba-	nish
bh {	n I S
ba-	nish-	ment
bh {	n I S	m V n t
ba-	nished
bh {	n I S t
ba-	nos
bh Q	n @U z
ba-	ra
bh Q@	V
ba-	ra-	ho-	na
bh {	r V	h @U	n V
ba-	ra-	jas
bh Q@	Q	j Q z
ba-	ra-	ny
bh @r	O:	n i:
ba-	rak
bh Q@	V k
ba-	ram
bh e@	{ m
ba-	ren-	boim
bh e@	V n	b OI m
ba-	rents
bh e@	V n t s
ba-	rest
bh e@	V s t
ba-	ri
bh Q@	i:
ba-	ri-	tone
bh e@	I	t @U n
ba-	ri-	um
bh e@	i:	V m
ba-	rile
bh Q@	I l
ba-	ring
bh e@	I N
ba-	ring's
bh e@	I N z
ba-	ris
bh Q@	i: z
ba-	ri's
bh Q@	i: z
ba-	rish
bh e@	I S
ba-	rite
bh e@	aI t
ba-	rites
bh e@	aI t s
ba-	ro-	me-	ter
bh @r	Q	m V	t @r
ba-	ro-	me-	ters
bh @r	Q	m V	t @r z
ba-	ro-	met-	ric
bh {	r V	m e t	r I k
ba-	ro-	ness
bh e@	V	n e s
ba-	ro-	net
bh e@	V	n V t
ba-	ro-	nets
bh e@	V	n V t s
ba-	ro-	ni
bh Q@	@U	n i:
ba-	ron
bh {	r V n
ba-	rons
bh {	r V n z
ba-	ron's
bh {	r V n z
ba-	roque
bh @r	@U k
ba-	ruch
bh Q@	u: k
ba-	ry-	shni-	kov
bh @r	I S	n I	k Q v
ba-	s-	ler
bh eI	z V	l @r
ba-	sal
bh eI	s V l
ba-	salt
bh V	s O: l t
ba-	salts
bh V	s O: l t s
ba-	sel
bh Q	z V l
ba-	sen-	ji
bh V	s e n	dZ i:
ba-	ses
bh eI	s V z
ba-	se's
bh eI	s V z
ba-	sham
bh {	S V m
ba-	shaw
bh I	S O:
ba-	sher
bh {	S @r
ba-	shers
bh {	S @r z
ba-	shes
bh {	S V z
ba-	shing
bh {	S I N
ba-	sic
bh eI	s I k
ba-	sical-	ly
bh eI	s I k	l i:
ba-	sics
bh eI	s I k s
ba-	sic's
bh eI	s I k s
ba-	sin
bh eI	s I n
ba-	sin-	ger
bh eI	s I	N @r
ba-	sing
bh eI	s I N
ba-	sins
bh eI	s V n z
ba-	sis
bh eI	s I s
ba-	sle
bh {	s V l
ba-	son
bh {	s V n
ba-	sye
bh {	s aI
ba-	ta-	vi-	a
bh V	t eI	v i:	V
ba-	taan
bh V	t Q n
ba-	tan
bh eI	t V n
ba-	ted
bh eI	t V d
ba-	ther
bh {	D @r
ba-	thers
bh {	D @r z
ba-	thing
bh eI	D I N
ba-	tho-	lith
bh {	T V	l I T
ba-	tho-	liths
bh {	T V	l I T s
ba-	tik
bh V	t i: k
ba-	tiks
bh {	t I k s
ba-	tis-	ta
bh V	t I s	t V
ba-	ton
bh V	t Q n
ba-	tons
bh {	t Q n z
ba-	tor
bh Q	t O@
ba-	va-	ri-	a
bh V	v e@	i:	V
ba-	va-	ri-	an
bh V	v e@	i:	V n
ba-	va-	ri-	a's
bh V	v e@	i:	V z
ba-	yar
bh eI	@r
ba-	yard
bh eI	@r d
ba-	yer
bh eI	@r
ba-	yer's
bh eI	@r z
ba-	ying
bh eI	I N
ba-	yo-	net
bh eI	V	n e t
ba-	yo-	nets
bh eI	V	n e t s
ba-	yonne
bh eI	j @U n
ba-	you
bh aI	u:
ba-	yous
bh aI	u: z
ba-	zaar
bh V	z Q@
ba-	zaars
bh V	z Q@ z
ba-	zar
bh V	z Q@
ba-	zoo-	ka
bh V	z u:	k V
ba-	zoo-	kas
bh V	z u:	k V z
baal-	bek
bh Q l	b e k
baar
bh Q@
baas
bh Q z
bab
bh { b
bab-	b-	ling
bh {	b V	l I N
bab-	ba-	ge's
bh {	b I	dZ V z
bab-	bage
bh {	b I dZ
bab-	bit
bh {	b I t
bab-	bitt
bh {	b I t
bab-	bitts
bh {	b I t s
bab-	bitt's
bh {	b I t s
bab-	ble
bh {	b V l
bab-	bled
bh {	b V l d
bab-	bler
bh { b	l @r
bab-	blers
bh { b	l @r z
bab-	cock
bh { b	k O: k
bab-	ka
bh { b	k V
bab-	son
bh { b	s V n
babb
bh { b
babe
bh eI b
babes
bh eI b z
babs
bh { b z
bac-	ca-	lau-	re-	ate
bh {	k V	l O@	i:	V t
bac-	ca-	rat
bh Q	k @r	Q
bac-	cha-	na-	lia
bh {	k V	n eI l	j V
bac-	chus
bh {	k V s
bac-	ker
bh {	k @r
bac-	kers
bh {	k @r z
bac-	ker's
bh {	k @r z
bac-	te-	ri-	a
bh { k	t I@	i:	V
bac-	te-	ri-	al
bh { k	t I@	i:	V l
bac-	te-	ri-	o-	lo-	gy
bh { k	t I@	i:	Q	l V	dZ i:
bac-	te-	ri-	um
bh { k	t I@	i:	V m
bach
bh Q k
bach-	man
bh Q k	m V n
bache
bh { tS
bache-	lors
bh { tS	l @r z
back
bh { k
back-	bi-	ting
bh { k	b aI	t I N
back-	bite
bh { k	b aI t
back-	board
bh { k	b O: d
back-	bone
bh { k	b @U n
back-	da-	ted
bh { k	d eI	t V d
back-	date
bh { k	d eI t
back-	door
bh { k	d O@
back-	drop
bh { k	d r Q p
back-	drops
bh { k	d r Q p s
back-	fi-	r-	ing
bh { k	f aI	@r	I N
back-	fi-	red
bh { k	f aI	@r d
back-	fi-	res
bh { k	f aI	@r z
back-	field
bh { k	f i: l d
back-	fire
bh { k	f aI r
back-	gam-	mon
bh { k	g {	m V n
back-	ground
bh { k	g r aU n d
back-	grounds
bh { k	g r aU n d z
back-	han-	ded
bh { k	h { n	d V d
back-	hand
bh { k	h { n d
back-	haus
bh { k	h aU s
back-	hoe
bh { k	h @U
back-	ing
bh {	k I N
back-	lash
bh { k	l { S
back-	less
bh { k	l V s
back-	light
bh { k	l aI t
back-	lights
bh { k	l aI t s
back-	list
bh { k	l I s t
back-	log
bh { k	l Q g
back-	logged
bh { k	l Q g d
back-	logs
bh { k	l O: g z
back-	pack
bh { k	p { k
back-	packs
bh { k	p { k s
back-	pe-	da-	ling
bh { k	p e	d V	l I N
back-	pe-	dal
bh { k	p e	d V l
back-	pe-	daled
bh { k	p e	d V l d
back-	rest
bh { k	r e s t
back-	room
bh { k	r u: m
back-	saw
bh { k	s Q
back-	seat
bh { k	s i: t
back-	set
bh { k	s e t
back-	side
bh { k	s aI d
back-	slap-	ping
bh { k	s l {	p I N
back-	woods-	man
bh { k	w U d	z m V n
back-	yard
bh { k	j Q@ d
back-	yards
bh { k	j Q@ d z
backed
bh { k t
backs
bh { k s
backs-	lap
bh { k	s l { p
backs-	lap-	ping
bh { k	s l {	p I N
backs-	lash
bh { k	s l { S
backs-	li-	ding
bh { k	s l aI	d I N
backs-	lide
bh { k	s l aI d
backs-	pin
bh { k	s p I n
backs-	tage
bh { k	s t eI dZ
backs-	tairs
bh { k	s t e@ z
backs-	titch
bh { k	s t I tS
backs-	top
bh { k	s t Q p
bad
bh { d
bad-	ge-	ring
bh {	dZ @r	I N
bad-	ger
bh {	dZ @r
bad-	gered
bh {	dZ @r d
bad-	gers
bh {	dZ @r z
bad-	ger's
bh {	dZ @r z
bad-	ges
bh {	dZ V z
bad-	land
bh { d	l { n d
bad-	lands
bh { d	l { n d z
bad-	ly
bh { d	l i:
bad-	man
bh { d	m V n
bad-	min-	ton
bh { d	m I n	t V n
bad-	min-	tons
bh { d	m I n	t V n z
bad-	ness
bh { d	n V s
bade
bh eI d
badge
bh { dZ
bae
bh aI
bae-	de-	ker
bh eI	d V	k @r
bae-	de-	ker's
bh eI	d V	k @r z
baer
bh e@
baf-	f-	ling
bh {	f V	l I N
baf-	fle
bh {	f V l
baf-	fled
bh {	f V l d
baf-	fles
bh {	f V l z
bag
bh { g
bag-	dad
bh { g	d { d
bag-	ful
bh { g	f U l
bag-	gage
bh {	g V dZ
bag-	gett
bh {	g I t
bag-	gi-	ness
bh {	g i:	n V s
bag-	gie
bh {	g i:
bag-	ging
bh {	g I N
bag-	gott
bh {	g V t
bag-	gy
bh {	g i:
bag-	ley
bh { g	l i:
bag-	man
bh { g	m V n
bag-	pi-	per
bh { g	p aI	p @r
bag-	pipe
bh { g	p aI p
bag-	pipes
bh { g	p aI p s
bag-	well
bh { g	w e l
bagge
bh { g
bagged
bh { g d
baggs
bh { g z
bagh-	dad
bh { g	d { d
bagh-	dad's
bh { g	d { d z
bags
bh { g z
bah
bh Q
bah-	ner
bh Q	n @r
bah-	rai-	ni
bh @r	eI	n i:
bah-	rai-	ni-	an
bh @r	eI	n i:	V n
bah-	rai-	nis
bh @r	eI	n i: z
bah-	rain
bh Q@	eI n
bah-	rain's
bh Q@	eI n z
bahr
bh e@
baht
bh Q t
bai-	ler
bh eI	l @r
bai-	ley
bh eI	l i:
bai-	leys
bh eI	l i: z
bai-	ley's
bh eI	l i: z
bai-	li-	wick
bh eI	l I	w I k
bai-	lie
bh eI	l i:
bai-	liff
bh eI	l I f
bai-	liffs
bh eI	l I f s
bai-	ling
bh eI	l I N
bai-	lor
bh eI	l @r
bai-	lout
bh eI	l aU t
bai-	louts
bh eI	l aU t s
bai-	ly
bh eI	l i:
bai-	ted
bh eI	t V d
bai-	ting
bh eI	t I N
bail
bh eI l
bail-	lie
bh eI	l i:
bail-	ly
bh eI	l i:
baile
bh eI l
bailed
bh eI l d
bails
bh eI l z
bain
bh eI n
bain-	brid-	ge's
bh eI n	b r I	dZ V z
bain-	bridge
bh eI n	b r I dZ
bain-	ter
bh eI n	t @r
baines
bh eI n z
bains
bh eI n z
bain's
bh eI n z
baird
bh e@ d
baird's
bh e@ d z
bais-	den
bh eI s	d V n
bait
bh eI t
baits
bh eI t s
baize
bh eI z
bak
bh { k
bak-	shi
bh { k	S i:
bake
bh eI k
bake-	man
bh eI k	m V n
bake-	off
bh eI	k O: f
bake-	ware
bh eI k	w e@
bake-	well
bh eI k	w e l
baked
bh eI k t
bakes
bh eI k s
bakke
bh { k
bakst
bh { k s t
bal
bh { l
bal-	bo
bh { l	b @U
bal-	bo-	a
bh Q l	b @U	V
bal-	brig-	gan
bh { l	b r I	g V n
bal-	brig-	gans
bh { l	b r I	g V n z
bal-	cer
bh eI l	s @r
bal-	co-	nies
bh { l	k V	n i: z
bal-	co-	ny
bh { l	k V	n i:
bal-	das-	sa-	re
bh Q l	d Q	s Q@	i:
bal-	der
bh O: l	d @r
bal-	der-	dash
bh O: l	d @r	d { S
bal-	ding
bh O: l	d I N
bal-	dric
bh { l	d r I k
bal-	dridge
bh { l	d r I dZ
bal-	dur
bh Q l	d U@
bal-	four
bh { l	f O@
bal-	ka-	ni-	za-	tion
bh O: l	k V	n V	z eI	S V n
bal-	ka-	nize
bh O: l	k V	n aI z
bal-	ka-	nized
bh O: l	k V	n aI z d
bal-	kan
bh O: l	k V n
bal-	kans
bh O: l	k V n z
bal-	kin
bh { l	k I n
bal-	king
bh O:	k I N
bal-	ko
bh { l	k @U
bal-	ky
bh O:	k i:
bal-	la
bh {	l V
bal-	lad
bh {	l V d
bal-	lade
bh V	l Q d
bal-	lads
bh {	l V d z
bal-	lan-	tine
bh {	l V n	t aI n
bal-	lan-	tyne
bh V	l { n	t aI n
bal-	lance
bh Q	l V n s
bal-	lard
bh {	l @r d
bal-	lard's
bh {	l @r d z
bal-	las
bh {	l V z
bal-	last
bh {	l V s t
bal-	lasts
bh {	l V s t s
bal-	le-	ri-	na
bh {	l @r	i:	n V
bal-	le-	ri-	nas
bh {	l @r	i:	n V z
bal-	len-	gee
bh V	l e N	g i:
bal-	len-	ti-	ne
bh Q	l e n	t i:	n i:
bal-	ler
bh O:	l @r
bal-	les-	te-	ros
bh {	l V s	t @r	@U z
bal-	let
bh {	l eI
bal-	lets
bh {	l eI z
bal-	let's
bh {	l eI z
bal-	li
bh {	l i:
bal-	liett
bh {	l i: t
bal-	lin-	ger
bh O:	l I n	dZ @r
bal-	ling
bh O:	l I N
bal-	lis-	tic
bh V	l I s	t I k
bal-	lis-	tics
bh V	l I s	t I k s
bal-	lo
bh {	l @U
bal-	lo-	ting
bh {	l V	t I N
bal-	lon
bh {	l V n
bal-	loo-	ning
bh V	l u:	n I N
bal-	loo-	nist
bh V	l u:	n V s t
bal-	loo-	nists
bh V	l u:	n V s t s
bal-	loon
bh V	l u: n
bal-	looned
bh V	l u: n d
bal-	loons
bh V	l u: n z
bal-	lot
bh {	l V t
bal-	lots
bh {	l V t s
bal-	lou
bh V	l u:
bal-	low
bh {	l @U
bal-	ly
bh {	l i:
bal-	ly-	hoo
bh {	l i:	h u:
bal-	ly-	hooed
bh {	l i:	h u: d
bal-	ly's
bh {	l i: z
bal-	mer
bh Q	m @r
bal-	mo-	ral
bh { l	m O@	V l
bal-	mo-	rals
bh { l	m O@	V l z
bal-	my
bh Q	m i:
bal-	sa
bh O: l	s V
bal-	sa-	mo
bh Q l	s Q	m @U
bal-	sam
bh O: l	s V m
bal-	ter
bh O: l	t @r
bal-	tha-	sar
bh { l	T V	s @r
bal-	tha-	zar
bh { l	T V	z @r
bal-	ti-	more
bh O: l	t I	m O@
bal-	ti-	more's
bh O: l	t I	m O@ z
bal-	tic
bh O: l	t I k
balch
bh { l tS
bald
bh O: l d
bald-	ly
bh O: l	d l i:
bald-	ness
bh O: l	d n V s
bald-	win
bh O: l	d w I n
bald-	win's
bh O: l	d w I n z
bale
bh eI l
bale-	ful
bh eI l	f V l
bales
bh eI l z
balk
bh O: k
balked
bh O: k t
balks
bh O: k s
ball
bh O: l
ball-	cock
bh O: l	k Q k
ball-	cocks
bh O: l	k Q k s
ball-	game
bh O: l	g eI m
ball-	man
bh O: l	m V n
ball-	park
bh O: l	p Q@ k
ball-	parks
bh O: l	p Q@ k s
ball-	pla-	yer
bh O: l	p l eI	@r
ball-	pla-	yers
bh O: l	p l eI	@r z
ball-	point
bh O: l	p OI n t
ball-	points
bh O: l	p OI n t s
ball-	room
bh O: l	r u: m
ball-	rooms
bh O: l	r u: m z
balled
bh O: l d
balls
bh O: l z
ball's
bh O: l z
balm
bh Q m
balms
bh Q m z
balt-	sa
bh O: l	t s V
balt's
bh O: l t s
bam
bh { m
bam-	ber-	ger
bh { m	b @r	g @r
bam-	berg
bh { m	b @r g
bam-	bi
bh { m	b i:
bam-	bi-	no
bh { m	b i:	n @U
bam-	bi-	nos
bh { m	b i:	n @U z
bam-	boo
bh { m	b u:
bam-	ford
bh { m	f @r d
ban
bh { n
ban-	bu-	ry
bh { n	b e@	i:
ban-	ca
bh { N	k V
ban-	co
bh { N	k @U
ban-	da
bh { n	d V
ban-	da-	ges
bh { n	d I	dZ V z
ban-	da-	na
bh { n	d {	n V
ban-	da-	nas
bh { n	d {	n V z
ban-	dage
bh { n	d I dZ
ban-	daged
bh { n	d I dZ d
ban-	daid
bh { n	d eI d
ban-	dar
bh { n	d Q@
ban-	ded
bh { n	d V d
ban-	del
bh { n	d V l
ban-	der
bh { n	d @r
ban-	di-	coots
bh { n	d I	k u: t s
ban-	died
bh { n	d i: d
ban-	ding
bh { n	d I N
ban-	dit
bh { n	d I t
ban-	dit-	ry
bh { n	d I t	r i:
ban-	dits
bh { n	d I t s
ban-	dy
bh { n	d i:
ban-	ga-	lore
bh { N	g V	l O@
ban-	ga-	lore's
bh { N	g V	l O@ z
ban-	ger
bh {	N @r
ban-	gers
bh {	N @r z
ban-	ging
bh {	N I N
ban-	gish
bh {	N I S
ban-	gle
bh { N	g V l
ban-	gor
bh { N	g @r
ban-	ja
bh Q n	j V
ban-	jo
bh { n	dZ @U
ban-	ka-	ble
bh { N	k V	b V l
ban-	ker
bh { N	k @r
ban-	kers
bh { N	k @r z
ban-	ker's
bh { N	k @r z
ban-	king
bh { N	k I N
ban-	king's
bh { N	k I N z
ban-	knote
bh { N	k n @U t
ban-	ner
bh {	n @r
ban-	ner-	man
bh {	n @r	m V n
ban-	ners
bh {	n @r z
ban-	ner's
bh {	n @r z
ban-	ning
bh {	n I N
ban-	nis-	ter
bh {	n V s	t @r
ban-	non
bh {	n V n
ban-	quet
bh { N	k w V t
ban-	quets
bh { N	k w V t s
ban-	quo's
bh { N	k w @U z
ban-	shee
bh { n	S i:
ban-	tam
bh { n	t V m
ban-	tams
bh { n	t V m z
ban-	tam's
bh { n	t V m z
ban-	te-	ring
bh { n	t @r	I N
ban-	ter
bh { n	t @r
ban-	tered
bh { n	t @r d
ban-	tu
bh { n	t u:
ban-	ville
bh Q n	v I l
ban-	ya
bh Q n	j V
ban-	yan
bh { n	j V n
banc
bh { N k
banc-	roft
bh { N	k r O: f t
banc-	roft's
bh { n	k r O: f t s
band
bh { n d
band-	aid
bh { n	d eI d
band-	wa-	gon
bh { n	d w {	g V n
band-	width
bh { n	d w I d T
bane
bh eI n
banes
bh eI n z
banff
bh { n f
bang
bh { N
bang-	kok
bh { N	k Q k
bang-	kok's
bh { N	k Q k s
bang-	la-	de-	shi
bh { N	l V	d e	S i:
bang-	la-	de-	shis
bh { N	l V	d e	S i: z
)"
R"(bang-	la-	de-	sh's
bh { N	l V	d e	S V z
bang-	la-	desh
bh { N	l V	d e S
bange
bh { n dZ
banged
bh { N d
bangs
bh { N z
bank
bh { N k
bank-	card
bh { N	k Q@ d
bank-	head
bh { N	k h e d
bank-	notes
bh { N	k n @U t s
bank-	rol-	ling
bh { N	k r @U	l I N
bank-	roll
bh { N	k r @U l
bank-	rolled
bh { N	k r @U l d
bank-	rolls
bh { N	k r @U l z
bank-	rup-	ted
bh { N	k r V p	t V d
bank-	rup-	ting
bh { N	k r V p	t I N
bank-	rupt
bh { N	k r V p t
bank-	rupt-	cies
bh { N	k r V p	t s i: z
bank-	rupt-	cy
bh { N	k r V p	s i:
bank-	rupt-	cy's
bh { N	k r V p	s i: z
banked
bh { N k t
banks
bh { N k s
bank's
bh { N k s
banks'
bh { N k s
banks-	ton
bh { N	k s t V n
bann
bh { n
banned
bh { n d
banque
bh { N k
bans
bh { n z
bao
bh aU
bap-	ti-	sm
bh { p	t I	z V m
bap-	ti-	sms
bh { p	t I	z V m z
bap-	tis-	mal
bh { p	t I z	m V l
bap-	tis-	ta
bh { p	t I s	t V
bap-	tist
bh { p	t I s t
bap-	tiste
bh V p	t I s t
bap-	tiste-	ry
bh { p	t I s	t r i:
bap-	tists
bh { p	t I s t s
bap-	tize
bh { p	t aI z
bap-	tized
bh { p	t aI z d
bar
bh Q@
bar-	ba
bh Q@	b V
bar-	ba-	dos
bh Q@	b eI	d @U s
)"