R"(subs-	tan-	ces
s V b	s t V n	s V z
subs-	tan-	dard
s V b	s t { n	d @r d
subs-	tan-	ti-	a-	ted
s V b	s t { n	S i:	eI	t V d
subs-	tan-	ti-	a-	tion
s V b	s t { n	tS i:	eI	S V n
subs-	tan-	ti-	ate
s V b	s t { n	tS i:	eI t
subs-	tan-	ti-	ates
s V b	s t { n	tS i:	eI t s
subs-	tan-	tial
s V b	s t { n	tS V l
subs-	tan-	tial-	ly
s V b	s t { n	S V	l i:
subs-	tan-	tive
s V b	s t V n	t I v
subs-	tan-	tive-	ly
s V b	s t V n	t I v	l i:
subs-	tance
s V b	s t V n s
subs-	ti-	tu-	ted
s V b	s t I	t u:	t I d
subs-	ti-	tu-	ting
s V b	s t I	t u:	t I N
subs-	ti-	tu-	tion
s V b	s t I	t u:	S V n
subs-	ti-	tu-	tions
s V b	s t I	t u:	S V n z
subs-	ti-	tute
s V b	s t I	t u: t
subs-	ti-	tutes
s V b	s t I	t u: t s
subst-	rate
s V b	s t r eI t
subst-	rates
s V b	s t r eI t s
subt-	rac-	ted
s V b	t r { k	t V d
subt-	rac-	ting
s V b	t r { k	t I N
subt-	rac-	tion
s V b	t r { k	S V n
subt-	ract
s V b	t r { k t
suc-	cee-	ded
s V k	s i:	d V d
suc-	cee-	ding
s V k	s i:	d I N
suc-	ceed
s V k	s i: d
suc-	ceeds
s V k	s i: d z
suc-	ces-	ses
s V k	s e	s V z
suc-	ces-	sion
s V k	s e	S V n
suc-	ces-	sive
s V k	s e	s I v
suc-	ces-	sive-	ly
s V k	s e	s I v	l i:
suc-	ces-	sor
s V k	s e	s @r
suc-	ces-	sors
s V k	s e	s @r z
suc-	cess
s V k	s e s
suc-	cess-	ful
s V k	s e s	f V l
suc-	cess-	ful-	ly
s V k	s e s	f V	l i:
suc-	cinct
s V k	s I N k t
suc-	cinct-	ly
s V k	s I N	k t l i:
suc-	cor
s V	k @r
suc-	cu-	lent
s V k	j V	l V n t
suc-	cu-	lents
s V k	j V	l V n t s
suc-	cum-	bing
s V	k V	m I N
suc-	cumb
s V	k V m
suc-	cumbed
s V	k V m d
suc-	cumbs
s V	k V m z
suc-	ker
s V	k @r
suc-	kered
s V	k @r d
suc-	kers
s V	k @r z
suc-	king
s V	k I N
suc-	kle
s V	k V l
suc-	kow
s V	k aU
suc-	rose
s u: k	r @U s
suc-	tion
s V k	S V n
such
s V tS
suck
s V k
suck-	ling
s V k	l I N
sucked
s V k t
sucks
s V k s
sud-	bu-	ry
s V d	b e@	i:
sud-	bu-	ry's
s V d	b e@	i: z
sud-	den
s V	d V n
sud-	den-	ly
s V	d V n	l i:
sud-	den-	ness
s V	d V n	n V s
sud-	derth
s V	d @r T
sudd
s V d
suds
s V d z
sue
s u:
sued
s u: d
suede
s w eI d
suedes
s w eI d z
sues
s u: z
suf-	fe-	rer
s V	f @r	@r
suf-	fe-	rers
s V	f @r	@r z
suf-	fe-	ring
s V	f @r	I N
suf-	fe-	rings
s V	f @r	I N z
suf-	fer
s V	f @r
suf-	fered
s V	f @r d
suf-	fern
s V	f @r n
suf-	fers
s V	f @r z
suf-	fi-	ces
s V	f aI	s V z
suf-	fi-	cien-	cy
s V	f I	S V n	s i:
suf-	fi-	cient
s V	f I	S V n t
suf-	fi-	cient-	ly
s V	f I	S V n	t l i:
suf-	fice
s V	f aI s
suf-	ficed
s V	f aI s t
suf-	field
s V	f i: l d
suf-	field's
s V	f i: l d z
suf-	fix
s V	f I k s
suf-	fo-	ca-	ted
s V	f V	k eI	t V d
suf-	fo-	ca-	ting
s V	f V	k eI	t I N
suf-	fo-	ca-	tion
s V	f V	k eI	S V n
suf-	fo-	cate
s V	f V	k eI t
suf-	folk
s V	f V k
suf-	fuse
s V f	j u: z
suf-	fused
s V f	j u: z d
suff-	ra-	gette
s V f	r V	dZ e t
suff-	ra-	gettes
s V f	r V	dZ e t s
suff-	ra-	gist
s V f	r V	dZ I s t
suff-	ra-	gists
s V f	r V	dZ I s t s
suff-	rage
s V f	r I dZ
sug-	den
s V g	d V n
sug-	ges-	ted
s V g	dZ e s	t V d
sug-	ges-	ti-	ble
s V g	dZ e s	t V	b V l
sug-	ges-	ting
s V g	dZ e s	t I N
sug-	ges-	tion
s V g	dZ e s	tS V n
sug-	ges-	tions
s V g	dZ e s	tS V n z
sug-	ges-	tive
s V g	dZ e s	t I v
sug-	ges-	tive-	ness
s V g	dZ e s	t I v	n V s
sug-	gest
s V g	dZ e s t
sug-	gests
s V g	dZ e s t s
sugg
s V g
suh
s V
sui-	ta-	bi-	li-	ty
s u:	t V	b I	l V	t i:
sui-	ta-	ble
s u:	t V	b V l
sui-	tab-	ly
s u:	t V b	l i:
sui-	ted
s u:	t V d
sui-	ter
s u:	t @r
sui-	tor
s u:	t @r
sui-	tors
s u:	t @r z
sui-	tor's
s u:	t @r z
suis-	se's
s w I	s V z
suisse
s w I s
suit
s u: t
suit-	ca-	ses
s u: t	k eI	s V z
suit-	case
s u: t	k eI s
suite
s w i: t
suites
s w i: t s
suits
s u: t s
suit's
s u: t s
suk
s V k
suk-	hu-	mi
s u: k	h u:	m i:
sul
s V l
sul-	fa
s V l	f V
sul-	fate
s V l	f eI t
sul-	fide
s V l	f aI d
sul-	fite
s V l	f aI t
sul-	fites
s V l	f aI t s
sul-	fu-	ric
s V l	f j U@	I k
sul-	fur
s V l	f @r
sul-	king
s V l	k I N
sul-	len
s V	l V n
sul-	lens
s V	l V n z
sul-	li-	van
s V	l I	v V n
sul-	li-	van's
s V	l I	v V n z
sul-	lied
s V	l i: d
sul-	ly
s V	l i:
sul-	phate
s V l	f eI t
sul-	phates
s V l	f eI t s
sul-	phur
s V l	f @r
sul-	ta-	nate
s V l	t V	n V t
sul-	tan
s V l	t V n
sul-	tans
s V l	t V n z
sul-	tan's
s V l	t V n z
sul-	try
s V l	t r i:
sulk
s V l k
sulked
s V l k t
sulz-	ber-	ger
s V l	t s b @r	g @r
sum
s V m
sum-	gait
s V m	g eI t
sum-	ma
s u:	m V
sum-	ma-	ri-	ly
s V	m e@	V	l i:
sum-	ma-	ri-	zes
s V	m @r	aI	z V z
sum-	ma-	ri-	zing
s V	m @r	aI	z I N
sum-	ma-	ries
s V	m @r	i: z
sum-	ma-	rize
s V	m @r	aI z
sum-	ma-	rized
s V	m @r	aI z d
sum-	ma-	ry
s V	m @r	i:
sum-	ma-	tion
s V	m eI	S V n
sum-	ma-	tions
s V	m eI	S V n z
sum-	mar
s V	m @r
sum-	mer
s V	m @r
sum-	mer-	field
s V	m @r	f i: l d
sum-	mer-	time
s V	m @r	t aI m
sum-	mer-	ville
s V	m @r	v I l
sum-	mers
s V	m @r z
sum-	mer's
s V	m @r z
sum-	mi-	teer
s V	m I	t I@
sum-	mi-	teers
s V	m I	t I@ z
sum-	mi-	try
s V	m I t	r i:
sum-	ming
s V	m I N
sum-	mit
s V	m I t
sum-	mit-	ville
s V	m I t	v I l
sum-	mits
s V	m I t s
sum-	mit's
s V	m I t s
sum-	mo-	ning
s V	m V	n I N
sum-	mon
s V	m V n
sum-	mon-	ses
s V	m V n	z V z
sum-	moned
s V	m V n d
sum-	mons
s V	m V n z
sum-	monsed
s V	m V n z d
sum-	mum
s V	m V m
sum-	ner
s V m	n @r
sum-	rall
s V m	r V l
sum-	ter
s V m	t @r
summed
s V m d
sump
s V m p
sump-	ter
s V m	p t @r
sump-	tuous
s V m	p tS w V s
sums
s V m z
sun
s V n
sun-	ba-	thing
s V n	b eI	D I N
sun-	bath
s V n	b { T
sun-	bathe
s V n	b eI D
sun-	beam
s V n	b i: m
sun-	beam's
s V n	b i: m z
sun-	belt
s V n	b e l t
sun-	belt's
s V n	b e l t s
sun-	bird
s V n	b @r d
sun-	birds
s V n	b @r d z
sun-	burn
s V n	b @r n
sun-	burned
s V n	b @r n d
sun-	cook
s V n	k U k
sun-	dae
s V n	d eI
sun-	dae's
s V n	d eI z
sun-	dance
s V n	d { n s
sun-	day
s V n	d eI
sun-	days
s V n	d eI z
sun-	day's
s V n	d eI z
sun-	der
s V n	d @r
sun-	der-	land
s V n	d @r	l V n d
sun-	dews
s V n	d u: z
sun-	dial
s V n	d aI l
sun-	din
s V n	d I n
sun-	down
s V n	d aU n
sun-	fish
s V n	f I S
sun-	flo-	wer
s V n	f l aU	@r
sun-	flo-	wers
s V n	f l aU	@r z
sun-	glas-	ses
s V n	g l {	s V z
sun-	glass
s V n	g l { s
sun-	ken
s V N	k V n
sun-	kist
s V n	k I s t
sun-	land
s V n	l { n d
sun-	light
s V n	l aI t
sun-	lit
s V n	l I t
sun-	ni
s u:	n i:
sun-	ning
s V	n I N
sun-	nis
s U	n i: z
sun-	ny
s V	n i:
sun-	ny-	side
s V	n i:	s aI d
sun-	ny-	vale
s V	n i:	v eI l
sun-	ri-	se's
s V n	r aI	z V z
sun-	rise
s V n	r aI z
sun-	roof
s V n	r u: f
sun-	room
s V n	r u: m
sun-	set
s V n	s e t
sun-	sets
s V n	s e t s
sun-	shi-	ny
s V n	S aI	n i:
sun-	shine
s V n	S aI n
sun-	shine's
s V n	S aI n z
sun-	tan
s V n	t { n
sun-	ward
s V n	w @r d
sund-	berg
s V n	d b @r g
sund-	ry
s V n	d r i:
sunds-	trom
s V n	d s t r V m
sung
s V N
sung's
s V N z
sunk
s V N k
suns
s V n z
sun's
s V n z
suns-	pot
s V n	s p Q t
suns-	pots
s V n	s p Q t s
suns-	tar
s V n	s t Q@
sunsc-	reen
s V n	s k r i: n
sunsc-	reens
s V n	s k r i: n z
sup
s V p
sup-	pa
s u:	p V
sup-	per
s V	p @r
sup-	pers
s V	p @r z
sup-	ple
s V	p V l
sup-	ple-	men-	ta-	ry
s V p	l V	m e n	t @r	i:
sup-	ple-	men-	tal
s V p	l V	m e n	t V l
sup-	ple-	ment
s V p	l V	m V n t
sup-	po-	sed-	ly
s V	p @U	z V d	l i:
sup-	po-	ses
s V	p @U	z V z
sup-	po-	si-	tion
s V	p V	z I	S V n
sup-	po-	si-	tions
s V	p V	z I	S V n z
sup-	po-	sing
s V	p @U	z I N
sup-	por-	ta-	ble
s V	p O@	t V	b V l
sup-	por-	ted
s V	p O@	t V d
sup-	por-	ter
s V	p O@	t @r
sup-	por-	ters
s V	p O@	t @r z
sup-	por-	ting
s V	p O@	t I N
sup-	por-	tive
s V	p O@	t I v
sup-	port
s V	p O@ t
sup-	ports
s V	p O@ t s
sup-	pose
s V	p @U z
sup-	posed
s V	p @U z d
sup-	pres-	sant
s V p	r e	s V n t
sup-	pres-	ses
s V p	r e	s V z
sup-	pres-	sing
s V p	r e	s I N
sup-	pres-	sion
s V p	r e	S V n
sup-	pres-	sor
s V p	r e	s @r
sup-	press
s V p	r e s
sup-	pressed
s V p	r e s t
sup-	ra
s u: p	r V
sup-	ra-	na-	tio-	nal
s u: p	r V	n {	S V	n V l
sup-	re-	ma-	cist
s u: p	r e	m V	s V s t
sup-	re-	ma-	cists
s u: p	r e	m V	s V s t s
sup-	re-	ma-	cy
s V p	r e	m V	s i:
sup-	re-	me-	ly
s u: p	r i:	m V	l i:
sup-	reme
s V p	r i: m
sup-	remes
s u: p	r i: m z
supp-	lan-	ted
s V p	l { n	t V d
supp-	lan-	ting
s V p	l { n	t I N
supp-	lant
s V p	l { n t
supp-	le-	men-	ted
s V p	l V	m e n	t V d
supp-	le-	men-	ting
s V p	l V	m V n	t I N
supp-	le-	ments
s V p	l V	m V n t s
supp-	li-	cant
s V p	l I	k V n t
supp-	li-	er
s V p	l aI	@r
supp-	li-	ers
s V p	l aI	@r z
supp-	li-	er's
s V p	l aI	@r z
supp-	lied
s V p	l aI d
supp-	lies
s V p	l aI z
supp-	ly
s V p	l aI
supp-	ly-	ing
s V p	l aI	I N
supp-	ly's
s V p	l aI z
sur
s @r
sur-	char-	ges
s @r	tS Q@	dZ V z
sur-	charge
s @r	tS Q@ dZ
sur-	fa-	ces
s @r	f V	s V z
sur-	fa-	cing
s @r	f V	s I N
sur-	fac-	tant
s @r	f { k	t V n t
sur-	face
s @r	f V s
sur-	face-	ness
s @r	f V s	n V s
sur-	faced
s @r	f V s t
sur-	feit
s @r	f V t
sur-	fer
s @r	f @r
sur-	fers
s @r	f @r z
sur-	fing
s @r	f I N
sur-	ge-	ries
s @r	dZ @r	i: z
sur-	ge-	ry
s @r	dZ @r	i:
sur-	geon
s @r	dZ V n
sur-	geons
s @r	dZ V n z
sur-	geon's
s @r	dZ V n z
sur-	ges
s @r	dZ V z
sur-	gi-	cal
s @r	dZ I	k V l
sur-	gi-	cal-	ly
s @r	dZ I	k V	l i:
sur-	ging
s @r	dZ I N
sur-	ly
s @r	l i:
sur-	ma
s @r	m V
sur-	mi-	ses
s @r	m aI	z V z
sur-	mise
s @r	m aI z
sur-	mised
s @r	m aI z d
sur-	moun-	ted
s @r	m aU n	t V d
sur-	moun-	ting
s @r	m aU n	t I N
sur-	mount
s @r	m aU n t
sur-	name
s @r	n eI m
sur-	names
s @r	n eI m z
sur-	pas-	ses
s @r	p {	s V z
sur-	pas-	sing
s @r	p {	s I N
sur-	pass
s @r	p { s
sur-	passed
s @r	p { s t
sur-	re-	but-	tal
s @r	V	b V	t V l
sur-	rea-	li-	sm
s @r	i:	l I	z V m
sur-	rea-	li-	sms
s @r	i:	l I	z V m z
sur-	rea-	li-	sm's
s @r	i:	l I	z V m z
sur-	rea-	lis-	tic
s @r	i:	l I s	t I k
sur-	real
s @r	i: l
sur-	ren-	cy
s O@	V n	s i:
sur-	ren-	de-	ring
s @r	e n	d @r	I N
sur-	ren-	der
s @r	e n	d @r
sur-	ren-	dered
s @r	e n	d @r d
sur-	ren-	ders
s @r	e n	d @r z
sur-	rep-	ti-	tious
s @r	V p	t I	S V s
sur-	rep-	ti-	tious-	ly
s @r	V p	t I	S V s	l i:
sur-	rey
s @r	i:
sur-	ro-	ga-	cy
s @r	V	g V	s i:
sur-	ro-	gate
s @r	V	g V t
sur-	ro-	gates
s @r	V	g V t s
sur-	roun-	ded
s @r	aU n	d V d
sur-	roun-	ding
s @r	aU n	d I N
sur-	roun-	dings
s @r	aU n	d I N z
sur-	round
s @r	aU n d
sur-	rounds
s @r	aU n d z
sur-	ry
s @r	i:
sur-	ta-	xes
s @r	t { k	s V z
sur-	tax
s @r	t { k s
sur-	ve-	yor
s @r	v eI	@r
sur-	ve-	yors
s @r	v eI	@r z
sur-	veil
s @r	v eI l
sur-	veil-	lance
s @r	v eI	l V n s
sur-	veil-	ling
s @r	v eI	l I N
sur-	vey
s @r	v eI
sur-	vey-	ing
s @r	v eI	I N
sur-	veyed
s @r	v eI d
sur-	veys
s @r	v eI z
sur-	vey's
s @r	v eI z
sur-	vi-	va-	bi-	li-	ty
s @r	v aI	v V	b I	l V	t i:
sur-	vi-	va-	ble
s @r	v aI	v V	b V l
sur-	vi-	va-	list
s @r	v aI	v V	l V s t
sur-	vi-	va-	lists
s @r	v aI	v V	l V s t s
sur-	vi-	val
s @r	v aI	v V l
sur-	vi-	ving
s @r	v aI	v I N
sur-	vi-	vor
s @r	v aI	v @r
sur-	vi-	vors
s @r	v aI	v @r z
sur-	vi-	vor's
s @r	v aI	v @r z
sur-	vive
s @r	v aI v
sur-	vived
s @r	v aI v d
sur-	vives
s @r	v aI v z
sure
S U@
sure-	ly
S U@	l i:
sures
S U@ z
surf
s @r f
surf-	board
s @r f	b O@ d
surf-	boards
s @r f	b O@ d z
surfed
s @r f t
surf's
s @r f s
surge
s @r dZ
surged
s @r dZ d
surp-	lu-	ses
s @r p	l V	s V z
surp-	lus
s @r p	l V s
surp-	ri-	ses
s @r p	r aI	z V z
surp-	ri-	sing
s @r p	r aI	z I N
surp-	ri-	sing-	ly
s @r p	r aI	z I N	l i:
surp-	rise
s @r p	r aI z
surp-	rised
s @r p	r aI z d
sus
s V s
sus-	cep-	ti-	bi-	li-	ty
s V	s e p	t V	b I	l V	t i:
sus-	cep-	ti-	ble
s V	s e p	t V	b V l
sus-	pec-	ted
s V s	p e k	t V d
sus-	pec-	ting
s V s	p e k	t I N
sus-	pect
s V s	p e k t
sus-	pects
s V s	p e k t s
sus-	pen-	ded
s V s	p e n	d V d
sus-	pen-	der
s V s	p e n	d @r
sus-	pen-	ders
s V s	p e n	d @r z
sus-	pen-	ding
s V s	p e n	d I N
sus-	pen-	sion
s V s	p e n	S V n
sus-	pen-	sions
s V s	p e n	S V n z
sus-	pend
s V s	p e n d
sus-	pends
s V s	p e n d z
sus-	pense
s V s	p e n s
sus-	pense-	ful
s V s	p e n	s f V l
sus-	pi-	cion
s V s	p I	S V n
sus-	pi-	cions
s V s	p I	S V n z
sus-	pi-	cious
s V s	p I	S V s
sus-	pi-	cious-	ly
s V s	p I	S V s	l i:
sus-	que-	han-	na
s u: s	k w e	h {	n V
sus-	que-	han-	na's
s u: s	k w e	h {	n V z
sus-	sex
s V	s I k s
sus-	tai-	na-	bi-	li-	ty
s V s	t eI	n V	b I	l V	t i:
sus-	tai-	na-	ble
s V s	t eI	n V	b V l
sus-	tai-	ning
s V s	t eI	n I N
sus-	tain
s V s	t eI n
sus-	tained
s V s	t eI n d
sus-	tains
s V s	t eI n z
sus-	te-	nance
s V s	t V	n V n s
suss
s V s
suss-	man
s V s	m V n
sut-	cliffe
s V t	k l I f
sut-	phin
s V t	f I n
sut-	ter
s V	t @r
sut-	tle
s V	t V l
sut-	tles
s V	t V l z
sut-	ton
s V	t V n
sut-	ton's
s V	t V n z
suz-	hou
s u: z	h @U
sve-	rige
s v e@	I dZ
svelte
s v e l t
sven
s v e n
sverd-	lovsk
s v @r d	l Q v s k
svet-	la-	na
s v e t	l Q	n V
sviz-	ze-	ra
s v I	z e@	V
svo-	bo-	da
s v @U	b @U	d V
swa-	ger
s w eI	g @r
swa-	ger-	ty
s w {	dZ @r	t i:
swa-	hi-	li
s w Q	h i:	l i:
swa-	mi
s w Q	m i:
swa-	nee
s w Q	n i:
swa-	tow
s w Q	t @U
swa-	zi
s w Q	z i:
swa-	zi-	land
s w Q	z I	l V n d
swab
s w Q b
swabs
s w Q b z
swag-	ge-	ring
s w {	g @r	I N
swag-	ger
s w {	g @r
swails
s w eI l z
swain
s w eI n
swaine
s w eI n
swal-	low
s w Q	l @U
swal-	low-	ing
s w Q	l @U	I N
swal-	lowed
s w Q	l @U d
swal-	lows
s w Q	l @U z
swales
s w eI l z
swam
s w { m
swam-	per
s w Q m	p @r
swam-	pers
s w Q m	p @r z
swam-	ping
s w Q m	p I N
swam-	py
s w Q m	p i:
swamp
s w Q m p
swamped
s w Q m p t
swamps
s w Q m p s
swan
s w Q n
swan-	ky
s w Q N	k i:
swan-	ner
s w Q	n @r
swan-	son
s w Q n	s V n
swan-	ton
s w Q n	t V n
swank
s w { N k
swann
s w Q n
swann's
s w Q n z
swans
s w Q n z
swap
s w Q p
swap-	ping
s w Q	p I N
swape
s w eI p
swapped
s w Q p t
swaps
s w Q p s
swar-	ming
s w O@	m I N
swar-	thout
s w O@	T aU t
swar-	thy
s w O@	D i:
sward
s w Q@ d
swarm
s w O@ m
swarmed
s w O@ m d
swarms
s w O@ m z
swart
s w O@ t
swarth-	more
s w O@ T	m O@
swarts
s w O@ t s
swartz
s w O@ t s
swas-	ti-	ka
s w Q s	t I	k V
swas-	ti-	kas
s w Q s	t I	k V z
swash-	buck-	ling
s w Q S	b V k	l I N
swat
s w Q t
swat-	ches
s w Q	tS V z
swat-	ted
s w Q	t V d
swatch
s w Q tS
swath
s w Q T
swathe
s w Q D
swathed
s w Q D d
sway
s w eI
sway-	ing
s w eI	I N
swayed
s w eI d
swayne
s w eI n
sways
s w eI z
swe-	den
s w i:	d V n
swe-	den's
s w i:	d V n z
swe-	dish
s w i:	d I S
swea-	ring
s w e@	I N
swea-	ted
s w e	t V d
swea-	ter
s w e	t @r
swea-	ters
s w e	t @r z
swea-	ting
s w e	t I N
swea-	ty
s w e	t i:
swear
s w e@
swears
s w e@ z
sweat
s w e t
sweat-	pants
s w e t	p { n t s
sweat-	shirt
s w e t	S @r t
sweat-	shirts
s w e t	S @r t s
sweat-	shop
s w e t	S Q p
sweat-	shops
s w e t	S Q p s
sweat-	suit
s w e t	s u: t
sweats
s w e t s
sweatt
s w i: t
swed
s w e d
swede
s w i: d
swedes
s w i: d z
swee-	den
s w i:	d V n
swee-	ney
s w i:	n i:
swee-	ny
s w i:	n i:
swee-	per
s w i:	p @r
swee-	pers
s w i:	p @r z
swee-	ping
s w i:	p I N
swee-	te-	ner
s w i:	t V	n @r
swee-	te-	ners
s w i:	t V	n @r z
swee-	te-	ning
s w i:	t V	n I N
swee-	ten
s w i:	t V n
swee-	tened
s w i:	t V n d
swee-	tens
s w i:	t V n z
swee-	ter
s w i:	t @r
swee-	test
s w i:	t V s t
swee-	tie
s w i:	t i:
swee-	ting
s w i:	t I N
sweep
s w i: p
sweep-	stake
s w i: p	s t eI k
sweep-	stakes
s w i: p	s t eI k s
sweeps
s w i: p s
sweet
s w i: t
sweet-	heart
s w i: t	h Q@ t
sweet-	hearts
s w i: t	h Q@ t s
sweet-	land
s w i: t	l V n d
sweet-	ly
s w i: t	l i:
sweet-	man
s w i: t	m V n
sweet-	ness
s w i: t	n V s
sweet-	ser
s w i: t	s @r
sweet-	wa-	ter
s w i: t	w Q	t @r
sweets
s w i: t s
swel-	ling
s w e	l I N
swel-	te-	ring
s w e l	t @r	I N
swel-	ter
s w e l	t @r
swell
s w e l
swelled
s w e l d
swells
s w e l z
swen-	son
s w e n	s V n
swept
s w e p t
swerve
s w @r v
swerved
s w @r v d
swi-	gart
s w I	g Q@ t
swi-	hart
s w I	h Q@ t
swi-	ney
s w aI	n i:
swi-	ping
s w aI	p I N
swi-	sher
s w I	S @r
swi-	shes
s w I	S V z
swi-	ve-	ling
s w I	v V	l I N
swi-	vel
s w I	v V l
swi-	vels
s w I	v V l z
swick
s w I k
swif-	ter
s w I f	t @r
swif-	test
s w I f	t V s t
swift
s w I f t
swift-	ly
s w I f	t l i:
swift-	ness
s w I f	t n V s
swifts
s w I f t s
swift's
s w I f t s
swig
s w I g
swil-	ling
s w I	l I N
swill
s w I l
swim
s w I m
swim-	mer
s w I	m @r
swim-	mers
s w I	m @r z
swim-	ming
s w I	m I N
swim-	suit
s w I m	s u: t
swim-	suits
s w I m	s u: t s
swim-	wear
s w I m	w e@
swims
s w I m z
swin-	burne's
s w I n	b @r n z
swin-	d-	ler
s w I n	d V	l @r
swin-	dle
s w I n	d V l
swin-	dled
s w I n	d V l d
swin-	dles
s w I n	d V l z
)"
R"(swin-	ger
s w I	N @r
swin-	gers
s w I	N @r z
swin-	ging
s w I	N I N
swin-	gle
s w I N	g V l
swin-	ney
s w I	n i:
swin-	ton
s w I n	t V n
swind-	lers
s w I n	d l @r z
swind-	ling
s w I n	d l I N
swine
s w aI n
swing
s w I N
swings
s w I N z
swink
s w I N k
swipe
s w aI p
swiped
s w aI p t
swipes
s w aI p s
swir-	ling
s w @r	l I N
swir-	sky
s w @r s	k i:
swire
s w aI r
swirl
s w @r l
swirled
s w @r l d
swirls
s w @r l z
swis-	sair
s w I	s e@
swish
s w I S
swished
s w I S t
swiss
s w I s
swit-	cher
s w I	tS @r
swit-	chers
s w I	tS @r z
swit-	ches
s w I	tS V z
swit-	ching
s w I	tS I N
swit-	zer
s w I t	s @r
swit-	zer-	land
s w I t	s @r	l V n d
swit-	zer-	land's
s w I t	s @r	l V n d z
switch
s w I tS
switch-	blade
s w I tS	b l eI d
switch-	blades
s w I tS	b l eI d z
switch-	board
s w I tS	b O@ d
switch-	boards
s w I tS	b O@ d z
switched
s w I tS t
swol-	len
s w @U	l V n
swoo-	ning
s w u:	n I N
swoo-	ping
s w u:	p I N
swoon
s w u: n
swooned
s w u: n d
swoop
s w u: p
swoope
s w u: p
swooped
s w u: p t
swoops
s w u: p s
swoosh
s w u: S
swooshed
s w u: S t
swope
s w @U p
swor
s w @r
sword
s O@ d
sword-	fi-	sh's
s O@ d	f I	S V z
sword-	fish
s O@ d	f I S
sword-	like
s O@ d	l aI k
sword-	play
s O@ d	p l eI
sword-	plays
s O@ d	p l eI z
swords
s O@ d z
swore
s w O@
sworn
s w O@ n
swum
s w V m
swung
s w V N
sy
s aI
sy-	bert
s I	b @r t
sy-	bil
s I	b I l
sy-	bil-	la
s I	b I	l V
sy-	bille
s I	b I l
sy-	ca-	more
s I	k V	m O@
sy-	co-	phan-	tic
s I	k V	f { n	t I k
sy-	ming-	ton
s I	m I N	t V n
sy-	mon
s I	m V n
sy-	monds
s I	m V n d z
sy-	mons
s I	m V n z
sy-	na-	gogue
s I	n V	g O: g
sy-	na-	gogues
s I	n V	g O: g z
sy-	ner-	gi-	sm
s I	n @r	dZ I	z V m
sy-	ner-	gies
s I	n @r	dZ i: z
sy-	ner-	gis-	tic
s I	n @r	dZ I s	t I k
sy-	ner-	gy
s I	n @r	dZ i:
sy-	ner-	gy's
s I	n @r	dZ i: z
sy-	no-	ny-	mous
s V	n Q	n V	m V s
sy-	no-	ny-	mous-	ly
s V	n Q	n V	m V s	l i:
sy-	no-	nym
s I	n V	n I m
sy-	nod
s I	n V d
sy-	nod's
s I	n V d z
sy-	nop-	sis
s V	n Q p	s V s
sy-	nop-	tics
s V	n Q p	t I k s
sy-	pher
s I	f @r
sy-	phers
s I	f @r z
sy-	phi-	lis
s I	f I	l I s
sy-	phon
s aI	f V n
sy-	ra-	cuse
s I@	V k	j u: z
sy-	ri-	a
s I@	i:	V
sy-	ri-	an
s I@	i:	V n
sy-	ri-	ans
s I@	i:	V n z
sy-	ri-	a's
s I@	i:	V z
sy-	rin-	ges
s @r	I n	dZ V z
sy-	ringe
s @r	I n dZ
sy-	rup
s @r	V p
sy-	rups
s @r	V p s
sy-	ver-	son
s I	v @r	s V n
syd
s I d
syd-	ney
s I d	n i:
syd-	ney's
s I d	n i: z
syed
s aI d
sykes
s aI k s
syl-	la-	bic
s V	l {	b I k
syl-	la-	ble
s I	l V	b V l
syl-	la-	bles
s I	l V	b V l z
syl-	la-	bus
s I	l V	b V s
syl-	mar
s I l	m Q@
syl-	va
s I l	v V
syl-	va-	na
s I l	v {	n V
syl-	va-	ni-	a
s I l	v eI	n i:	V
syl-	va-	nus
s I l	v V	n V s
syl-	van
s I l	v V n
syl-	ves-	ter
s I l	v e s	t @r
syl-	vi-	a
s I l	v i:	V
syl-	vi-	a's
s I l	v i:	V z
syl-	vie
s I l	v i:
syl-	vite
s I l	v aI t
sym
s I m
sym-	bi-	o-	sis
s I m	b aI	@U	s I s
sym-	bi-	o-	tic
s I m	b i:	Q	t I k
sym-	bi-	on
s I m	b i:	V n
sym-	bo-	li-	cal-	ly
s I m	b Q	l I	k V	l i:
sym-	bo-	li-	sm
s I m	b V	l I	z V m
sym-	bo-	li-	zes
s I m	b V	l aI	z V z
sym-	bo-	li-	zing
s I m	b V	l aI	z I N
sym-	bo-	lic
s I m	b Q	l I k
sym-	bo-	lics
s I m	b Q	l I k s
sym-	bo-	lists
s I m	b V	l V s t s
sym-	bo-	lize
s I m	b V	l aI z
sym-	bo-	lized
s I m	b V	l aI z d
sym-	bol
s I m	b V l
sym-	bols
s I m	b V l z
sym-	bol's
s I m	b V l z
sym-	me-	tri-	cal
s V	m e t	r I	k V l
sym-	me-	trical-	ly
s V	m e t	r I k	l i:
sym-	met-	ry
s I	m V t	r i:
sym-	pa-	the-	ti-	cal-	ly
s I m	p V	T e	t I	k V	l i:
sym-	pa-	the-	tic
s I m	p V	T e	t I k
sym-	pa-	thi-	zer
s I m	p V	T aI	z @r
sym-	pa-	thi-	zers
s I m	p V	T aI	z @r z
sym-	pa-	thi-	zes
s I m	p V	T aI	z V z
sym-	pa-	thi-	zing
s I m	p V	T aI	z I N
sym-	pa-	thies
s I m	p V	T i: z
sym-	pa-	thize
s I m	p V	T aI z
sym-	pa-	thized
s I m	p V	T aI z d
sym-	pa-	thy
s I m	p V	T i:
sym-	pho-	nic
s I m	f Q	n I k
sym-	pho-	nies
s I m	f V	n i: z
sym-	pho-	ny
s I m	f V	n i:
sym-	pho-	ny's
s I m	f V	n i: z
sym-	po-	si-	um
s I m	p @U	z i:	V m
sym-	po-	si-	ums
s I m	p @U	z i:	V m z
symp-	to-	ma-	tic
s I m	p t V	m {	t I k
symp-	tom
s I m	p t V m
symp-	toms
s I m	p t V m z
syn
s I n
syn-	co-	pa-	ted
s I N	k V	p eI	t V d
syn-	co-	pa-	tion
s I N	k V	p eI	S V n
syn-	co-	pate
s I N	k V	p eI t
syn-	com
s I N	k Q m
syn-	di-	ca-	ted
s I n	d I	k eI	t I d
syn-	di-	ca-	ting
s I n	d I	k eI	t I N
syn-	di-	ca-	tion
s I n	d I	k eI	S V n
syn-	di-	ca-	tions
s I n	d I	k eI	S V n z
syn-	di-	ca-	tor
s I n	d I	k eI	t @r
syn-	di-	ca-	tors
s I n	d I	k eI	t @r z
syn-	di-	cate
s I n	d I	k eI t
syn-	di-	cates
s I n	d I	k eI t s
syn-	di-	cate's
s I n	d I	k eI t s
syn-	tax
s I n	t { k s
syn-	the-	si-	zer
s I n	T V	s aI	z @r
syn-	the-	si-	zers
s I n	T V	s aI	z @r z
syn-	the-	si-	zing
s I n	T V	s aI	z I N
syn-	the-	sis
s I n	T V	s V s
syn-	the-	size
s I n	T V	s aI z
syn-	the-	sized
s I n	T V	s aI z d
syn-	the-	tic
s I n	T e	t I k
syn-	the-	tical-	ly
s I n	T e	t I k	l i:
syn-	the-	tics
s I n	T e	t I k s
sync
s I N k
synch
s I n tS
synch-	ro
s I N	k r @U
synch-	ro-	nic
s I N	k r Q	n I k
synch-	ro-	nize
s I N	k r V	n aI z
synch-	ro-	nized
s I N	k r V	n aI z d
synd-	rome
s I n	d r @U m
synd-	romes
s I n	d r @U m z
syng-	man
s I N	m V n
sys-	te-	ma-	tic
s I s	t V	m {	t I k
sys-	te-	ma-	tical-	ly
s I s	t V	m {	t I k	l i:
sys-	te-	ma-	tics
s I s	t V	m {	t I k s
sys-	te-	mic
s I s	t e	m I k
sys-	te-	mical-	ly
s V s	t e	m I k	l i:
sys-	tem
s I s	t V m
sys-	tem-	wide
s I s	t V m	w aI d
sys-	tems
s I s	t V m z
sys-	tem's
s I s	t V m z
szeke-	ly
S i: k	l i:
szi-	lard
s I	l @r d
szy-	ma-	now-	ski
S I	m V	n O: f	s k i:
t
th i:
t-	b
th i:	b i:
t-	bi-	li-	si
th V	b I	l i:	s i:
t-	c-	a-	s
th i:	s i:	eI	e s
t-	h
th i:	eI tS
t-	s
th i:	e s
t-	v
th i:	v i:
t.
th i:
ta
th Q
ta-	b-	ler
th eI	b V	l @r
ta-	b-	ling
th eI	b V	l I N
ta-	bas-	co
th V	b { s	k @U
ta-	ber
th eI	b @r
ta-	ber-	na-	cle
th {	b @r	n {	k V l
ta-	bi-	tha
th {	b I	T V
ta-	ble
th eI	b V l
ta-	ble-	cloth
th eI	b V l	k l O: T
ta-	ble-	cloths
th eI	b V l	k l O: T s
ta-	ble-	spoon
th eI	b V l	s p u: n
ta-	ble-	spoons
th eI	b V l	s p u: n z
ta-	ble-	top
th eI	b V l	t Q p
ta-	ble-	ware
th eI	b V l	w e@
ta-	bled
th eI	b V l d
ta-	bles
th eI	b V l z
ta-	ble's
th eI	b V l z
ta-	boo
th {	b u:
ta-	boos
th {	b u: z
ta-	bor
th eI	b @r
ta-	bor's
th eI	b @r z
ta-	bu-	la-	ted
th { b	j V	l eI	t V d
ta-	bu-	la-	ting
th { b	j V	l eI	t I N
ta-	bu-	la-	tion
th { b	j V	l eI	S V n
ta-	bu-	la-	tions
th { b	j V	l eI	S V n z
ta-	bu-	late
th { b	j V	l eI t
ta-	ci-	ta
th Q	tS i:	t V
ta-	ci-	turn
th {	s I	t @r n
ta-	cit
th {	s I t
ta-	cit-	ly
th {	s I t	l i:
ta-	co
th Q	k @U
ta-	co-	ma
th V	k @U	m V
ta-	co-	ma's
th V	k @U	m V z
ta-	cos
th Q	k @U z
ta-	cy
th eI	s i:
ta-	da
th Q	d V
ta-	da-	shi
th Q	d Q	S i:
ta-	ga-	log
th {	g V	l Q g
ta-	ga-	met
th {	g V	m e t
ta-	ger
th eI	g @r
ta-	hi-	ti
th V	h i:	t i:
ta-	hoe
th {	h @U
ta-	i-	ra
th Q	I@	V
ta-	ji-	kis-	tan
th Q	dZ i:	k I s	t { n
ta-	jik
th Q	dZ I k
ta-	ka-	o
th Q	k Q	@U
ta-	ka-	ra
th Q	k Q@	V
ta-	ka-	shi
th Q	k Q	S i:
ta-	ke-	o
th Q	k eI	@U
ta-	ke-	shi
th V	k e	S i:
ta-	ken
th eI	k V n
ta-	ker
th eI	k @r
ta-	kers
th eI	k @r z
ta-	keth
th eI	k V T
ta-	ki
th {	k i:
ta-	king
th eI	k I N
ta-	kings
th eI	k I N z
ta-	ku
th Q	k u:
ta-	la-	ve-	ra
th Q	l Q	v e@	V
ta-	len-	ted
th {	l V n	t V d
ta-	lent
th {	l V n t
ta-	lents
th {	l V n t s
ta-	li-	ban
th {	l I	b { n
ta-	li-	tha
th {	l I	D V
ta-	lis-	man
th {	l I s	m V n
ta-	lon
th {	l V n
ta-	lons
th {	l V n z
ta-	ma
th Q	m V
ta-	ma-	les
th V	m Q	l i: z
ta-	ma-	na-	ha
th Q	m Q	n Q	h V
ta-	ma-	ra
th V	m Q@	V
ta-	ma-	rin
th {	m @r	I n
ta-	ma-	rins
th {	m @r	I n z
ta-	ma-	risk
th {	m @r	I s k
ta-	ma-	risks
th {	m @r	I s k s
ta-	ma-	yo
th Q	m Q	j @U
ta-	mas
th Q	m V z
ta-	mer
th eI	m @r
ta-	mil
th {	m I l
ta-	mils
th {	m I l z
ta-	ming
th eI	m I N
ta-	mo-	xi-	fen
th {	m Q k	s I	f e n
ta-	na-	ka
th Q	n Q	k V
ta-	ney
th eI	n i:
ta-	ni
th Q	n i:
ta-	nia
th Q n	j V
ta-	nis
th {	n I s
ta-	pas
th V	p V s
ta-	pe-	ring
th eI	p @r	I N
ta-	per
th eI	p @r
ta-	pered
th eI	p @r d
ta-	pers
th eI	p @r z
ta-	pest-	ries
th {	p V s	t r i: z
ta-	pest-	ry
th {	p V s	t r i:
ta-	pi-	a
th Q	p i:	V
ta-	ping
th eI	p I N
ta-	pings
th eI	p I N z
ta-	ra
th e@	V
ta-	ra-	hu-	ma-	ra
th Q@	V	h u:	m Q@	V
ta-	ran-	ti-	no
th Q@	Q n	t i:	n @U
ta-	ran-	to
th @r	{ n	t @U
ta-	ran-	to's
th @r	{ n	t @U z
ta-	ran-	tu-	la
th V	r { n	tS u:	l V
ta-	ran-	tu-	las
th V	r { n	tS u:	l V z
ta-	ras
th Q@	V z
ta-	riff
th e@	I f
ta-	riffs
th e@	I f s
ta-	rin
th Q@	i: n
ta-	ro
th e@	@U
ta-	rot
th {	r @U
ta-	rots
th {	r @U z
ta-	ser
th eI	z @r
ta-	sm
th {	s V m
ta-	tar
th {	t @r
ta-	tars
th {	t @r z
ta-	ti-	a-	na
th {	t i:	{	n V
ta-	tu
th Q	t u:
ta-	tum
th eI	t V m
ta-	va-	res
th Q	v Q@	e s
ta-	vel
th Q	v e l
ta-	ver-	na
th Q	v e@	n V
ta-	ver-	ni-	er
th {	v @r	n i:	@r
ta-	vern
th {	v @r n
ta-	verns
th {	v @r n z
ta-	vie
th eI	v i:
ta-	vis
th Q	v I s
ta-	vish
th eI	v I S
ta-	vy
th eI	v i:
ta-	xa-	bi-	li-	ty
th { k	s V	b I	l V	t i:
ta-	xa-	ble
th { k	s V	b V l
ta-	xa-	bles
th { k	s V	b V l z
ta-	xa-	tion
th { k	s eI	S V n
ta-	xer
th { k	s @r
ta-	xers
th { k	s @r z
ta-	xes
th { k	s V z
ta-	xi
th { k	s i:
ta-	xi-	cab
th { k	s i:	k { b
ta-	xi-	cabs
th { k	s i:	k { b z
ta-	xi-	ing
th { k	s i:	I N
ta-	xied
th { k	s i: d
ta-	xing
th { k	s I N
ta-	xis
th { k	s i: z
ta-	xi's
th { k	s i: z
ta-	xol
th { k	s Q l
ta-	x's
th { k	s V z
tab
th { b
tab-	bing
th {	b I N
tab-	by
th {	b i:
tab-	la-	ture
th { b	l V	tS @r
tab-	leau
th V b	l @U
tab-	leaux
th V b	l @U
tab-	let
th { b	l V t
tab-	lets
th { b	l V t s
tab-	loid
th { b	l OI d
tab-	loids
th { b	l OI d z
tabb
th { b
tabs
th { b z
tac
th { k
tac-	ker
th {	k @r
tac-	king
th {	k I N
tac-	kle
th {	k V l
tac-	kled
th {	k V l d
tac-	kles
th {	k V l z
tac-	ky
th {	k i:
tac-	ti-	cal
th { k	t I	k V l
tac-	ti-	cal-	ly
th { k	t I	k V	l i:
tac-	ti-	cian
th { k	t I	S V n
tac-	ti-	cians
th { k	t I	S V n z
tac-	tic
th { k	t I k
tac-	tics
th { k	t I k s
tac-	tile
th { k	t I l
tack
th { k
tack-	ling
th { k	l I N
tacked
th { k t
tacks
th { k s
tact
th { k t
tact-	ful
th { k	t f V l
tact-	ful-	ly
th { k	t f V	l i:
tad
th { d
tad-	de-	o
th Q	d i:	@U
tad-	pole
th { d	p @U l
tad-	poles
th { d	p @U l z
tadd
th { d
tae
th eI
tae-	gu
th eI	g u:
taf-	fe-	ta
th {	f V	t V
taf-	fel
th {	f V l
taf-	fy
th {	f i:
taft
th { f t
taft's
th { f t s
tag
th { g
tag-	gart
th {	g @r t
tag-	gart's
th {	g @r t s
tag-	ging
th {	g I N
tag-	line
th { g	l aI n
tagged
th { g d
tags
th { g z
tai
th aI
tai-	ling
th eI	l I N
tai-	lings
th eI	l I N z
tai-	lo-	ring
th eI	l @r	I N
tai-	lor
th eI	l @r
tai-	lored
th eI	l @r d
tai-	lors
th eI	l @r z
tai-	ma
th aI	m V
tai-	pei
th aI	p eI
tai-	pei's
th aI	p eI z
tai-	sho
th eI	S @U
tai-	wa-	nese
th aI	w Q	n i: z
tai-	wan
th aI	w Q n
tai-	wan's
th aI	w Q n z
tail
th eI l
tail-	gate
th eI l	g eI t
tail-	pipe
th eI l	p aI p
tail-	spin
th eI l	s p I n
tailed
th eI l d
tails
th eI l z
tain-	ted
th eI n	t V d
tain-	ting
th eI n	t I N
taint
th eI n t
taints
th eI n t s
tait
th eI t
taite
th eI t
taj
th Q Z
tak
th { k
tak-	la-	ma-	kan
th { k	l V	m eI	k V n
take
th eI k
take-	o-	ver
th eI	k @U	v @r
take-	o-	vers
th eI	k @U	v @r z
take-	off
th eI	k O: f
take-	offs
th eI	k O: f s
take-	out
th eI	k aU t
takes
th eI k s
tal
th Q l
tal-	bert
th { l	b @r t
tal-	bot
th { l	b V t
tal-	bots
th { l	b V t s
tal-	bot's
th { l	b V t s
tal-	bott
th { l	b V t
tal-	bott's
th { l	b V t s
tal-	cott
th { l	k V t
tal-	cum
th { l	k V m
tal-	ka-	ble
th O:	k V	b V l
tal-	ka-	tive
th O:	k V	t I v
tal-	ker
th O:	k @r
tal-	kers
th O:	k @r z
tal-	kie
th O:	k i:
tal-	kies
th O:	k i: z
tal-	king
th O:	k I N
tal-	ky
th O:	k i:
tal-	la-	de-	ga
th {	l V	d eI	g V
tal-	la-	has-	see
th {	l V	h {	s i:
tal-	la-	has-	see's
th {	l V	h {	s i: z
tal-	lent
th Q	l V n t
tal-	ler
th O:	l @r
tal-	lest
th O:	l V s t
tal-	ley
th {	l i:
tal-	lie
th O:	l i:
tal-	lied
th {	l i: d
tal-	lies
th {	l i: z
tal-	low
th {	l @U
tal-	lu-	la
th Q	l u:	l V
tal-	lu-	lah
th {	l u:	l V
tal-	ly
th {	l i:
tal-	ly-	ho
th {	l i:	h @U
tal-	ly-	ing
th {	l i:	I N
tal-	mage
th { l	m I dZ
tal-	mud
th { l	m V d
talc
th { l k
talcs
th { l k s
tale
th eI l
tales
th eI l z
talk
th O: k
talk-	back
th O: k	b { k
talked
th O: k t
talks
th O: k s
tall
th O: l
tall-	grass
th Q l	g r { s
tall-	madge
th { l	m { dZ
tall-	man
th O: l	m V n
tam
th { m
tam-	bo
th { m	b @U
tam-	bou-	rine
th { m	b @r	i: n
tam-	bu-	rel-	lo
th Q m	b U@	e	l @U
tam-	ma-	ny
th {	m V	n i:
tam-	mie
th {	m i:
tam-	my
th {	m i:
tam-	pa
th { m	p V
tam-	pa's
th { m	p V z
tam-	pax
th { m	p { k s
tam-	pe-	ring
th { m	p @r	I N
tam-	per
th { m	p @r
tam-	pered
th { m	p @r d
tam-	ping
th { m	p I N
tam-	pon
th { m	p Q n
tam-	pons
th { m	p Q n z
tame
th eI m
tamed
th eI m d
tames
th eI m z
tamp
th { m p
tamps
th { m p s
tan
th { n
tan-	dem
th { n	d V m
tan-	dem's
th { n	d V m z
tan-	dy
th { n	d i:
tan-	dy's
th { n	d i: z
tan-	ge-	rine
th { n	dZ @r	i: n
tan-	ge-	rines
th { n	dZ @r	i: n z
tan-	gen-	tial
th { n	dZ e n	tS V l
tan-	gen-	tial-	ly
th { n	dZ e n	tS V	l i:
tan-	gent
th { n	dZ V n t
tan-	ger
th {	N @r
tan-	gi-	ble
th { n	dZ I	b V l
tan-	gi-	bles
th { n	dZ I	b V l z
tan-	giers
th { n	dZ I@ z
tan-	gle
th { N	g V l
tan-	gle-	wood
th { N	g V l	w U d
tan-	gled
th { N	g V l d
tan-	gles
th { N	g V l z
tan-	go
th { N	g @U
tan-	gos
th { N	g @U z
tan-	kard
th { N	k @r d
tan-	ker
th { N	k @r
tan-	kers
th { N	k @r z
tan-	king
th { N	k I N
tan-	nen
th {	n V n
tan-	nen-	baum
th {	n V n	b aU m
tan-	ner
th {	n @r
tan-	nest
th {	n V s t
tan-	ney
th {	n i:
tan-	ning
th {	n I N
tan-	sey
th { n	z i:
tan-	sy
th { n	z i:
tan-	ta-	li-	zes
th { n	t V	l aI	z V z
tan-	ta-	li-	zing
th { n	t V	l aI	z I N
tan-	ta-	li-	zing-	ly
th { n	t V	l aI	z I N	l i:
tan-	ta-	lize
th { n	t V	l aI z
tan-	ta-	lized
th { n	t V	l aI z d
tan-	ta-	lum
th { n	t V	l V m
tan-	ta-	lus
th { n	t V	l V s
tan-	ta-	mount
th { n	t V	m aU n t
tan-	ya
th Q n	j V
tan-	za-	ni-	a
th { n	z eI	n i:	V
tan-	za-	ni-	an
th { n	z eI	n i:	V n
tan-	za-	ni-	a's
th { n	z eI	n i:	V z
tang
th { N
t'ang
th { N
tang-	ling
th { N	g l I N
tangs
th { N z
tank
th { N k
tanked
th { N k t
tanks
th { N k s
tank's
th { N k s
tann
th { n
tann-	hau-	ser
th { n	h aU	z @r
tanned
th { n d
tans
th { n z
tant
th { n t
tant-	ric
th { n	t r I k
tant-	rum
th { n	t r V m
tant-	rums
th { n	t r V m z
tao
th aU
tao-	i-	sm
dh aU	I	z V m
tao-	ist
dh aU	V s t
tao-	ists
dh aU	I s t s
taos
th aU z
tap
th { p
tap-	ley
th { p	l i:
tap-	lin
th { p	l I n
tap-	pan
th {	p V n
tap-	pen
th {	p V n
tap-	per
th {	p @r
tap-	pet
th {	p V t
tap-	ping
th {	p I N
tape
th eI p
taped
th eI p t
tapes
th eI p s
tape's
th eI p s
tapped
th { p t
taps
th { p s
tar
th Q@
tar-	bell
th Q@	b e l
tar-	bet
th Q@	b e t
tar-	box
th Q@	b Q k s
tar-	di-	ness
th Q@	d i:	n V s
tar-	dy
th Q@	d i:
tar-	ge-	ted
th Q@	g V	t V d
tar-	ge-	ting
th Q@	g V	t I N
tar-	get
th Q@	g V t
tar-	gets
th Q@	g V t s
tar-	get's
th Q@	g V t s
tar-	heel
th Q@	h i: l
tar-	heels
th Q@	h i: l z
tar-	king-	ton
th Q@	k I N	t V n
tar-	mac
th Q@	m { k
tar-	macs
th Q@	m { k s
tar-	man
th Q@	m V n
tar-	ni-	shing
th Q@	n I	S I N
tar-	nish
th Q@	n I S
tar-	nished
th Q@	n I S t
tar-	now
th Q@	n @U
tar-	pon
th Q@	p V n
tar-	rance
th Q@	V n s
tar-	rant
th Q@	V n t
tar-	ring
th Q@	I N
tar-	ry
th e@	i:
tar-	ry-	town
th e@	i:	t aU n
tar-	sus
th Q@	s V s
tar-	tag-	li-	a
th Q@	t { g	l i:	V
tar-	tan
th Q@	t V n
tar-	tar
th Q@	t @r
tar-	tars
th Q@	t @r z
tar-	ter
th Q@	t @r
tar-	zan
th Q@	z { n
tar-	zan's
th Q@	z { n z
tarl-	ton
th Q@ l	t V n
tarp
th Q@ p
tarp-	ley
th Q@ p	l i:
tarps
th Q@ p s
tarr
th Q@
tarred
th Q@ d
tart
th Q@ t
tart-	ness
th Q@ t	n V s
tarte
th Q@ t
tarts
th Q@ t s
tas-	ker
th { s	k @r
tas-	king
th { s	k I N
tas-	ma-	ni-	a
th { z	m eI	n i:	V
tas-	ma-	ni-	an
th { z	m eI	n i:	V n
tas-	man
th { z	m V n
tas-	sel
th {	s V l
tas-	seled
th {	s V l d
tas-	so
th {	s @U
tas-	ted
th eI s	t V d
tas-	ter
th eI s	t @r
tas-	ters
th eI s	t @r z
tas-	ter's
th eI s	t @r z
tas-	ti-	er
th eI s	t i:	@r
tas-	ti-	ness
th eI s	t i:	n V s
tas-	ting
th eI s	t I N
tas-	tings
th eI s	t I N z
tas-	ty
th eI s	t i:
tash
th { S
tash-	kent
th { S	k e n t
task
th { s k
task-	force
th { s	k f O@ s
task-	mas-	ter
th { s	k m { s	t @r
tasked
th { s k t
)"
R"(tasks
th { s k s
tass
th { s
taste
th eI s t
taste-	ful
th eI s	t f V l
taste-	ful-	ly
th eI s	t f V	l i:
taste-	less
th eI s	t l V s
tastes
th eI s t s
tat
th { t
tat-	man
th { t	m V n
tat-	ra
th { t	r V
tat-	ter
th {	t @r
tat-	ter-	sall
th {	t @r	s V l
tat-	tered
th {	t @r d
tat-	ters
th {	t @r z
tat-	tle
th {	t V l
tat-	tled
th {	t V l d
tat-	too
th {	t u:
tat-	too-	ing
th {	t u:	I N
tat-	tooed
th {	t u: d
tat-	toos
th {	t u: z
tat-	ty
th {	t i:
tate
th eI t
tate's
th eI t s
tatt-	ler
th { t	l @r
tau-	ru-	ses
th O@	V	s V z
tau-	rus
th O@	V s
taub
th aU b
taube
th O: b
taubes
th aU b z
taught
th O: t
taun-	ted
th O: n	t V d
taun-	ting
th O: n	t I N
taun-	ton
th O: n	t V n
taunt
th O: n t
taunts
th O: n t s
taus-	sig
th aU	s I g
taut
th O: t
taw-	dry
th O: d	r i:
taw-	ney
th O:	n i:
taw-	ny
th Q	n i:
tawes
th O: z
tax
th { k s
tax-	pa-	yer
th { k	s p eI	@r
tax-	pa-	yers
th { k	s p eI	@r z
tax-	pa-	yer's
th { k	s p eI	@r z
tax-	pay-	ing
th { k	s p eI	I N
taxed
th { k s t
tay
th eI
tay-	ler
th eI	l @r
tay-	lor
th eI	l @r
tay-	lors
th eI	l @r z
tay-	lor's
th eI	l @r z
tays
th eI z
tchai-	kov-	sky
tS eI	k Q v	s k i:
tchai-	kov-	sky's
tS eI	k Q v	s k i: z
te
th i:
te-	chie
th e	k i:
te-	chies
th e	k i: z
te-	chy
th e	tS i:
te-	co
th i:	k @U
te-	cum-	seh
th V	k V m	s V
te-	des-	chi
th e	d e s	k i:
te-	des-	co
th e	d e s	k @U
te-	di-	ous
th i:	d i:	V s
te-	di-	ous-	ly
th i:	d i:	V s	l i:
te-	di-	um
th i:	d i:	V m
te-	gu-	ci-	gal-	pa
th e	g u:	s i:	g { l	p V
te-	he-	ran
th e	h @r	Q n
te-	he-	ran's
th e	h @r	Q n z
te-	ja-	no
th eI	j Q	n @U
te-	jon
th e	dZ Q n
te-	la-	mon
th e	l V	m V n
te-	le
th e	l i:
te-	le-	cast
th e	l V	k { s t
te-	le-	casts
th e	l V	k { s t s
te-	le-	com
th e	l V	k Q m
te-	le-	com-	mu-	ni-	ca-	tion
th e	l V	k V m	j u:	n I	k eI	S V n
te-	le-	com-	mu-	ni-	ca-	tions
th e	l V	k V m	j u:	n V	k eI	S V n z
te-	le-	com-	mu-	ter
th e	l V	k V m	j u:	t @r
te-	le-	com-	mu-	ters
th e	l V	k V m	j u:	t @r z
te-	le-	com-	mu-	ting
th e	l V	k V m	j u:	t I N
te-	le-	com-	mute
th e	l V	k V m	j u: t
te-	le-	coms
th e	l V	k Q m z
te-	le-	confe-	ren-	cing
th e	l V	k Q n	f r V n	s I N
te-	le-	confe-	rence
th e	l V	k Q n	f r V n s
te-	le-	dyne
th e	l V	d aI n
te-	le-	dyne's
th e	l V	d aI n z
te-	le-	fun-	ken
th e	l V	f V N	k V n
te-	le-	ge-	nic
th e	l V	dZ e	n I k
te-	le-	gram
th e	l V g	r { m
te-	le-	grams
th e	l V g	r { m z
te-	le-	graph
th e	l V g	r { f
te-	le-	graphed
th e	l V g	r { f t
te-	le-	graph's
th e	l V g	r { f s
te-	le-	ma-	tic
th e	l V	m {	t I k
te-	le-	ma-	tics
th e	l V	m {	t I k s
te-	le-	mar-	ke-	ter
th e	l V	m Q@	k V	t @r
te-	le-	mar-	ke-	ters
th e	l V	m Q@	k V	t @r z
te-	le-	mar-	ke-	ting
th e	l V	m Q@	k V	t I N
te-	le-	me-	di-	cine
th e	l V	m e	d V	s V n
te-	le-	met-	ry
th V	l e	m V t	r i:
te-	le-	o-	lo-	gi-	cal
th i:	l i:	V	l O:	dZ I	k V l
te-	le-	pa-	thic
th e	l V	p {	T V k
te-	le-	pa-	thy
th e	l V	p {	T i:
te-	le-	pho-	nic
th e	l V	f Q	n I k
te-	le-	pho-	nics
th e	l V	f Q	n I k s
te-	le-	pho-	ning
th e	l V	f @U	n I N
te-	le-	pho-	ny
th e	l V	f @U	n i:
te-	le-	pho-	to
th e	l V	f @U	t @U
te-	le-	phone
th e	l V	f @U n
te-	le-	phoned
th e	l V	f @U n d
te-	le-	phones
th e	l V	f @U n z
te-	le-	phone's
th e	l V	f @U n z
te-	le-	pic-	ture
th e	l V	p I k	tS @r
te-	le-	port
th e	l V	p O@ t
te-	le-	port's
th e	l V	p O@ t s
te-	le-	promp-	ter
th e	l V p	r Q m	p t @r
te-	le-	sci-	en-	ces
th e	l V	s aI	V n	s V z
te-	le-	sci-	ence
th e	l V	s aI	V n s
te-	le-	sco-	pic
th e	l V s	k O:	p I k
te-	le-	scope
th e	l V s	k @U p
te-	le-	scopes
th e	l V s	k @U p s
te-	le-	scope's
th e	l V s	k @U p s
te-	le-	script
th e	l V s	k r I p t
te-	le-	si-	s's
th e	l V	s I	s V z
te-	le-	sis
th e	l V	s I s
te-	le-	text
th e	l V	t e k s t
te-	le-	thon
th e	l V	T O: n
te-	le-	tron
th e	l V t	r Q n
te-	le-	type
th e	l V	t aI p
te-	le-	types
th e	l V	t aI p s
te-	le-	van-	ge-	list
th e	l V	v { n	dZ V	l V s t
te-	le-	van-	ge-	lists
th e	l V	v { n	dZ V	l V s t s
te-	le-	vi-	de-	o
th e	l V	v I	d i:	@U
te-	le-	vi-	sing
th e	l V	v aI	z I N
te-	le-	vi-	sion
th e	l V	v I	Z V n
te-	le-	vi-	sions
th e	l V	v I	Z V n z
te-	le-	vi-	sion's
th e	l V	v I	Z V n z
te-	le-	vise
th e	l V	v aI z
te-	le-	vised
th e	l V	v aI z d
te-	le-	xes
th e	l e k	s V s
te-	le-	x's
th e	l e k	s V z
te-	lex
th e	l e k s
te-	lexed
th e	l e s k t
te-	los
th e	l @U s
te-	lu-	gu
th e	l U	g u:
te-	me-	cu-	la
th V	m e k	j V	l V
te-	me-	ri-	ty
th V	m e@	V	t i:
te-	na
th e	n V
te-	na-	ble
th e	n V	b V l
te-	na-	ci-	ty
th V	n {	s V	t i:
te-	na-	cious
th V	n eI	S V s
te-	na-	cious-	ly
th V	n eI	S V s	l i:
te-	nan-	cy
th e	n V n	s i:
te-	nant
th e	n V n t
te-	nants
th e	n V n t s
te-	nant's
th e	n V n t s
te-	ne-	ment
th e	n V	m V n t
te-	ne-	ments
th e	n V	m V n t s
te-	nen-	baum
th e	n V n	b aU m
te-	net
th e	n V t
te-	nets
th e	n V t s
te-	nor
th e	n @r
te-	nore
th e	n O@
te-	nors
th e	n @r z
te-	nuo-	us
th e n	j V	w V s
te-	nure
th e n	j @r
te-	nured
th e n	j @r d
te-	nures
th e n	j @r z
te-	o
th eI	@U
te-	o-	do-	ro
th i:	@U	d O@	@U
te-	pid
th e	p I d
te-	qui-	la
th V	k i:	l V
te-	re-	sa
th @r	i:	s V
te-	re-	sa's
th @r	i:	s V z
te-	re-	si-	ta
th @r	e	s i:	t V
te-	ren-	ce's
th e@	V n	s V z
te-	ren-	tia
th @r	e n	S V
te-	rence
th e@	V n s
te-	res-	sa
th @r	e	s V
te-	rese
th e@	i: z
te-	ri
th e@	i:
te-	ri-	ya-	ki
th e@	I	j Q	k i:
te-	s-	ler
th e	s V	l @r
te-	ta-	nus
th e	t V	n V s
te-	ter
th i:	t @r
te-	ther
th e	D @r
te-	thered
th e	D @r d
te-	thers
th e	D @r z
te-	ton
th i:	t V n
te-	vat-	ron
th e	v V t	r Q n
te-	vis
th e	v I s
te-	well
th e	w e l
te-	xa-	co
th e k	s V	k @U
te-	xa-	co's
th e k	s V	k @U z
te-	xa-	s's
th e k	s V	s V z
te-	xan
th e k	s V n
te-	xans
th e k	s V n z
te-	xar-	ka-	na
th e k	s Q@	k {	n V
te-	xas
th e k	s V s
tea
th i:
tea-	cha-	ble
th i:	tS V	b V l
tea-	cher
th i:	tS @r
tea-	chers
th i:	tS @r z
tea-	cher's
th i:	tS @r z
tea-	ches
th i:	tS V z
tea-	chey
th i:	tS i:
tea-	ching
th i:	tS I N
tea-	chings
th i:	tS I N z
tea-	cup
th i:	k V p
tea-	gar-	den
th i:	g Q@	d V n
tea-	gle
th i:	g V l
tea-	han
th i:	V n
tea-	mer
th i:	m @r
tea-	ming
th i:	m I N
tea-	neck
th i:	n e k
tea-	pot
th i:	p Q t
tea-	ring
th e@	I N
tea-	rle
th O@	V l
tea-	ry
th I@	i:
tea-	ser
th i:	z @r
tea-	ses
th i:	z V z
tea-	sing
th i:	z I N
tea-	spoon
th i: s	p u: n
tea-	spoons
th i: s	p u: n z
tea-	tro
th i: t	r @U
teach
th i: tS
teague
th i: g
teak
th i: k
teak-	wood
th i: k	w U d
teal
th i: l
team
th i: m
team-	mate
th i:	m eI t
team-	mates
th i: m	m eI t s
team-	work
th i: m	w @r k
teamed
th i: m d
teams
th i: m z
team's
th i: m z
teams-	ter
th i: m	s t @r
teams-	ters
th i: m	s t @r z
teams-	ter's
th i: m	s t @r z
tear
th e@
tear-	ful
th I@	f V l
tear-	ful-	ly
th I@	f V	l i:
tears
th e@ z
teas
th i: z
teas-	dale
th i: z	d eI l
tease
th i: z
teased
th i: z d
teat
th i: t
teats
th i: t s
teb-	betts
th e	b e t s
tec
th e k
tec-	la
th e k	l V
tec-	to-	nic
th e k	t Q	n I k
tec-	to-	nics
th e k	t Q	n I k s
tech
th e k
tech-	ni-	ca-	li-	ties
th e k	n I	k {	l I	t i: z
tech-	ni-	ca-	li-	ty
th e k	n I	k {	l I	t i:
tech-	ni-	cal
th e k	n I	k V l
tech-	ni-	cal-	ly
th e k	n I	k V	l i:
tech-	ni-	cals
th e k	n I	k V l z
tech-	ni-	cian
th e k	n I	S V n
tech-	ni-	cians
th e k	n I	S V n z
tech-	ni-	cian's
th e k	n I	S V n z
tech-	ni-	co-	lor
th e k	n I	k V	l @r
tech-	ni-	con
th e k	n I	k Q n
tech-	nic
th e k	n I k
tech-	nics
th e k	n I k s
tech-	nique
th e k	n i: k
tech-	niques
th e k	n i: k s
tech-	no
th e k	n @U
tech-	no-	cra-	tic
th e k	n V k	r {	t I k
tech-	no-	crat
th e k	n V k	r { t
tech-	no-	crats
th e k	n V k	r { t s
tech-	no-	lo-	gi-	cal
th e k	n V	l Q	dZ I	k V l
tech-	no-	lo-	gi-	cal-	ly
th e k	n V	l Q	dZ I	k V	l i:
tech-	no-	lo-	gic
th e k	n V	l Q	dZ I k
tech-	no-	lo-	gies
th e k	n Q	l I	dZ i: z
tech-	no-	lo-	gist
th e k	n Q	l I	dZ I s t
tech-	no-	lo-	gists
th e k	n Q	l I	dZ I s t s
tech-	no-	lo-	gy
th e k	n Q	l I	dZ i:
tech-	no-	lo-	gy's
th e k	n Q	l I	dZ i: z
tech-	no-	phobe
th e k	n @U	f @U b
tech-	no-	phobes
th e k	n @U	f @U b z
techs
th e k s
tech's
th e k s
teck
th e k
ted
th e d
ted-	der
th e	d @r
ted-	die
th e	d i:
ted-	dy
th e	d i:
ted-	dy's
th e	d i: z
ted-	man
th e d	m V n
ted-	mund
th e d	m V n d
ted's
th e d z
tee
th i:
tee-	ing
th i:	I N
tee-	ming
th i:	m I N
tee-	na
th i:	n V
tee-	na-	ger
th i:	n eI	dZ @r
tee-	na-	gers
th i:	n eI	dZ @r z
tee-	na-	ger's
th i:	n eI	dZ @r z
tee-	nage
th i:	n eI dZ
tee-	naged
th i:	n eI dZ d
tee-	nie
th i:	n i:
tee-	ny
th i:	n i:
tee-	te-	ring
th i:	t @r	I N
tee-	ter
th i:	t @r
tee-	tered
th i:	t @r d
tee-	ters
th i:	t @r z
tee-	ter's
th i:	t @r z
tee-	thing
th i:	D I N
teed
th i: d
teel
th i: l
teem
th i: m
teems
th i: m z
teen
th i: n
teen-	a-	ger
th i:	n eI	dZ @r
teen-	age
th i:	n eI dZ
teen-	aged
th i:	n eI dZ d
teen-	sy
th i: n	s i:
teens
th i: n z
teer
th I@
tees
th i: z
teet
th i: t
teeth
th i: T
teethe
th i: D
tef-	lon
th e f	l V n
tefft
th e f t
teh-	ran
th eI	r Q n
tei-	cher
th aI	k @r
teig
th i: g
tek-	tro-	nix
th e k	t r Q	n I k s
tel
th e l
tel-	a-	viv
th e	l Q	v i: v
tel-	co
th e l	k @U
tel-	fer
th e l	f @r
tel-	ford
th e l	f @r d
tel-	ler
th e	l @r
tel-	lers
th e	l @r z
tel-	ler's
th e	l @r z
tel-	lez
th eI	l e z
tel-	ling
th e	l I N
tel-	ling-	ly
th e	l I N	l i:
tel-	lo
th e	l @U
tel-	lu-	ri-	um
th e	l U@	i:	V m
tel-	lu-	ride
th e l	j @r	aI d
tel-	lu-	rides
th e l	j @r	aI d z
tel-	ly
th e	l i:
tel-	star
th e l	s t Q@
tell
th e l
tell-	tale
th e l	t eI l
tell-	tales
th e l	t eI l z
tells
th e l z
tem-	p-	ler
th e m	p V	l @r
tem-	pe
th e m	p i:
tem-	pe-	ra
th e m	p @r	V
tem-	pe-	rance
th e m	p @r	V n s
tem-	pe-	ring
th e m	p @r	I N
tem-	pel
th e m	p V l
tem-	per
th e m	p @r
tem-	pera-	men-	tal
th e m	p r V	m e n	t V l
tem-	pera-	men-	tal-	ly
th e m	p r V	m e n	t V	l i:
tem-	pera-	ment
th e m	p r V	m V n t
tem-	pera-	ments
th e m	p r V	m V n t s
tem-	pera-	ture
th e m	p r V	tS @r
tem-	pered
th e m	p @r d
tem-	pers
th e m	p @r z
tem-	pes-	tu-	ous
th e m	p e s	tS u:	V s
tem-	pest
th e m	p V s t
tem-	ple
th e m	p V l
tem-	ple-	man
th e m	p V l	m V n
tem-	ple-	ton
th e m	p V l	t V n
tem-	ple-	ton's
th e m	p V l	t V n z
tem-	ples
th e m	p V l z
tem-	ple's
th e m	p V l z
tem-	po
th e m	p @U
tem-	po-	ra-	ri-	ly
th e m	p @r	e@	I	l i:
tem-	po-	ra-	ries
th e m	p @r	e@	i: z
tem-	po-	ra-	ry
th e m	p @r	e@	i:
tem-	po-	ral
th e m	p @r	V l
tem-	po-	ral-	ly
th e m	p @r	V	l i:
tem-	po-	ri-	zing
th e m	p @r	aI	z I N
tem-	po-	rize
th e m	p @r	aI z
tem-	pore
th e m	p O@
tem-	pos
th e m	p @U z
temb-	lor
th e m	b l @r
temb-	lors
th e m	b l @r z
temp
th e m p
temp-	lar
th e m	p l @r
temp-	lars
th e m	p l @r z
temp-	late
th e m	p l V t
temp-	let
th e m	p l V t
temp-	ta-	tion
th e m	t eI	S V n
temp-	ta-	tions
th e m	t eI	S V n z
temp-	ted
th e m	p t V d
temp-	ting
th e m	p t I N
tempe-	ra-	tures
th e m	p r V	tS @r z
tempe-	rate
th e m	p r V t
temps
th e m p s
tempt
th e m p t
tempt-	ress
th e m	p t r V s
tempts
th e m p t s
ten
th e n
ten-	de-	ring
th e n	d @r	I N
ten-	ded
th e n	d V d
ten-	den-	cies
th e n	d V n	s i: z
ten-	den-	cy
th e n	d V n	s i:
ten-	den-	tious
th e n	d e n	S V s
ten-	der
th e n	d @r
ten-	der-	loin
th e n	d @r	l OI n
ten-	der-	ly
th e n	d @r	l i:
ten-	der-	ness
th e n	d @r	n V s
ten-	dered
th e n	d @r d
ten-	ders
th e n	d @r z
ten-	ding
th e n	d I N
ten-	don
th e n	d V n
ten-	dons
th e n	d V n z
ten-	fold
th e n	f @U l d
ten-	nant
th e	n V n t
ten-	ne-	co
th e	n V	k @U
ten-	ne-	co's
th e	n V	k @U z
ten-	nent
th e	n V n t
ten-	ner
th e	n @r
ten-	nes-	se-	an
th e	n V	s i:	V n
ten-	nes-	se-	ans
th e	n V	s i:	V n z
ten-	nes-	see
th e	n V	s i:
ten-	nes-	see's
th e	n V	s i: z
ten-	ney
th e	n i:
ten-	ni-	s's
th e	n I	s V z
ten-	nis
th e	n I s
ten-	ny
th e	n i:
ten-	ny-	son
th e	n V	s V n
ten-	pen-	ny
th e n	p e	n i:
ten-	recs
th e n	r e k s
ten-	si-	o-	me-	ter
th e n	s i:	Q	m V	t @r
ten-	sile
th e n	s I l
ten-	sion
th e n	S V n
ten-	sions
th e n	tS V n z
ten-	ta-	cle
th e n	t V	k V l
ten-	ta-	cles
th e n	t V	k V l z
ten-	ta-	tive
th e n	t V	t I v
ten-	ta-	tive-	ly
th e n	t V	t I v	l i:
ten-	ting
th e n	t I N
tench
th e n tS
tend
th e n d
tends
th e n d z
teng
th e N
tens
th e n z
ten's
th e n z
tense
th e n s
tense-	ly
th e n	s l i:
tent
th e n t
tenth
th e n T
tenths
th e n T s
tents
th e n t s
tep-	per
th e	p @r
tepe
th i: p
ter
th @r
ter-	cel
th @r	s V l
ter-	hune
th @r h	j u: n
ter-	kel
th @r	k V l
ter-	man
th @r	m V n
ter-	mer
th @r	m @r
ter-	mers
th @r	m @r z
ter-	mi-	na-	ted
th @r	m I	n eI	t I d
ter-	mi-	na-	ting
th @r	m I	n eI	t I N
ter-	mi-	na-	tion
th @r	m I	n eI	S V n
ter-	mi-	na-	tions
th @r	m I	n eI	S V n z
ter-	mi-	na-	tor
th @r	m I	n eI	t @r
ter-	mi-	nal
th @r	m I	n V l
ter-	mi-	nal-	ly
th @r	m I	n V	l i:
ter-	mi-	nals
th @r	m I	n V l z
ter-	mi-	nate
th @r	m I	n eI t
ter-	mi-	nates
th @r	m I	n eI t s
ter-	mi-	ni
th @r	m I	n aI
ter-	mi-	no-	lo-	gy
th @r	m I	n Q	l V	dZ i:
ter-	mine
th @r	m I n
ter-	ming
th @r	m I N
ter-	mite
th @r	m aI t
ter-	mites
th @r	m aI t s
ter-	ra
th e@	V
ter-	ra-	ces
th e@	V	s V z
ter-	race
th e@	V s
ter-	raced
th e@	V s t
ter-	rain
th @r	eI n
ter-	rains
th @r	eI n z
ter-	ral
th e@	V l
ter-	rance
th e@	V n s
ter-	ra's
th e@	V z
ter-	re
th e@	V
ter-	re-	bon-	ne
th @r	e	b @U	n i:
ter-	rel
th e@	V l
ter-	rell
th e@	V l
ter-	rence
th e@	V n s
ter-	res-	tri-	al
th @r	e s	t r i:	V l
ter-	ri
th e@	i:
ter-	ri-	ble
th e@	I	b V l
ter-	ri-	er
th e@	i:	@r
ter-	ri-	ers
th e@	i:	@r z
ter-	ri-	fic
th @r	I	f I k
ter-	ri-	fical-	ly
th @r	I	f I k	l i:
ter-	ri-	fied
th e@	I	f aI d
ter-	ri-	fies
th e@	I	f aI z
ter-	ri-	fy
th e@	I	f aI
ter-	ri-	fy-	ing
th e@	I	f aI	I N
ter-	ri-	to-	ri-	a-	li-	sm
th e@	I	t O@	i:	V	l I	z V m
ter-	ri-	to-	ri-	al
th e@	I	t O@	i:	V l
ter-	ri-	to-	ri-	al-	ly
th e@	I	t O@	i:	V	l i:
ter-	ri-	to-	ries
th e@	I	t O@	i: z
ter-	ri-	to-	ry
th e@	I	t O@	i:
ter-	ri-	to-	ry's
th e@	I	t O@	i: z
ter-	rib-	ly
th e@	I b	l i:
ter-	rie
th e@	i:
ter-	rill
th e@	I l
ter-	ris
th e@	I s
ter-	ro-	ri-	sm
th e@	@r	I	z V m
ter-	ro-	ri-	zes
th e@	@r	aI	z V z
ter-	ro-	ri-	zing
th e@	@r	aI	z I N
ter-	ro-	ris-	tic
th e@	@r	I s	t I k
ter-	ro-	rist
th e@	@r	I s t
ter-	ro-	rists
th e@	@r	I s t s
ter-	ro-	rize
th e@	@r	aI z
ter-	ro-	rized
th e@	@r	aI z d
ter-	ror
th e@	@r
ter-	rors
th e@	@r z
ter-	ry
th e@	i:
ter-	ry's
th e@	i: z
ter-	ti-	us
th @r	t i:	V s
ter-	tia
th e@	S V
ter-	tia-	ry
th @r	S @r	i:
term
th @r m
termed
th @r m d
terms
th @r m z
term's
th @r m z
ternes
th @r n z
terns
th @r n z
terpst-	ra
th e@ p	s t r V
terse
th @r s
terse-	ly
th @r s	l i:
tes-	la
th e s	l V
tes-	sa
th e	s V
tes-	se-	la-	ted
th e	s V	l eI	t V d
tes-	se-	late
th e	s V	l eI t
tes-	sie
th e	s i:
tes-	sy
th e	s i:
tes-	ta
th e s	t V
tes-	ta-	men-	ta-	ry
th e s	t V	m e n	t @r	i:
tes-	ta-	ment
th e s	t V	m V n t
tes-	ted
th e s	t V d
tes-	ter
th e s	t @r
tes-	ters
th e s	t @r z
tes-	tes
th e s	t i: z
tes-	ti-	cle
th e s	t I	k V l
tes-	ti-	cles
th e s	t I	k V l z
tes-	ti-	cu-	lar
th e s	t I k	j V	l @r
tes-	ti-	fied
th e s	t I	f aI d
tes-	ti-	fies
th e s	t I	f aI z
tes-	ti-	fy
th e s	t I	f aI
tes-	ti-	fy-	ing
th e s	t I	f aI	I N
tes-	ti-	ly
th e s	t I	l i:
tes-	ti-	mo-	ni-	al
th e s	t I	m @U	n i:	V l
tes-	ti-	mo-	ni-	als
th e s	t I	m @U	n i:	V l z
tes-	ti-	mo-	nies
th e s	t V	m @U	n i: z
tes-	ti-	mo-	ny
th e s	t V	m @U	n i:
tes-	ting
th e s	t I N
tes-	ton
th e s	t V n
tes-	tor
th e s	t @r
tes-	tos-	te-	rone
th e s	t Q s	t @r	@U n
tes-	ty
th e s	t i:
tess
th e s
tess-	ler
th e s	l @r
test
th e s t
tests
th e s t s
test's
th e s t s
tet
th e t
tet-	ra
th e t	r V
tet-	ra-	hed-	ral
th e t	r V	h i: d	r V l
tet-	ra-	hed-	ron
th e t	r V	h i: d	r V n
tet-	ra-	me-	rous
th e t	r {	m @r	V s
tet-	ra-	va-	lent
th e t	r V	v eI	l V n t
tet-	rads
th e t	r { d z
tete
th e t
teu-	fel
th OI	f V l
tew
tS u:
tewks-	bu-	ry
th u: k	s b @r	i:
tews
tS u: z
tex
th e k s
tex-	tile
th e k	s t aI l
tex-	tiles
th e k	s t aI l z
tex-	tu-	al
th e k	s tS V	w V l
tex-	ture
th e k	s tS @r
tex-	tured
th e k	s tS @r d
tex-	tures
th e k	s tS @r z
text
th e k s t
text-	book
th e k	s t b U k
text-	books
th e k	s t b U k s
text-	ron
th e k	s t r Q n
text-	ron's
th e k	s t r Q n z
texts
th e k s t s
tha-	cher
T {	k @r
tha-	cke-	ray
T {	k @r	i:
tha-	cker
T {	k @r
)"
R"(tha-	gard
T {	g @r d
tha-	la-	mus
T {	l V	m V s
tha-	las-	sa
T Q	l Q	s V
tha-	ler
T eI	l @r
tha-	li-	do-	mide
T V	l I	d V	m aI d
tha-	lia
T eI l	j V
tha-	lia's
T eI l	j V z
tha-	nos
T Q	n @U s
tha-	t'd
D {	t V d
tha-	t'll
D {	t V l
tha-	wing
T O:	I N
thach
T { tS
thad
T { d
thad-	de-	us
T {	d i:	V s
thai
th aI
thai-	land
th aI	l { n d
thai-	land's
th aI	l { n d z
thain
T eI n
thaine
T eI n
thais
th aI z
thal-	li-	um
T {	l i:	V m
tham
T { m
thames
th e m z
than
D { n
than-	king
T { N	k I N
thane
T eI n
thanh
T { n
thank
T { N k
thank-	ful
T { N	k f V l
thank-	ful-	ly
T { N	k f V	l i:
thank-	less
T { N	k l V s
thanked
T { N k t
thanks
T { N k s
thanks-	gi-	ving
T { N	k s g I	v I N
thar
T Q@
tharp
T Q@ p
that
D { t
that-	che-	ri-	sm
T {	tS @r	I	z V m
that-	che-	rite
T {	tS @r	aI t
that-	cher
T {	tS @r
that-	cher's
T {	tS @r z
that-	ches
T {	tS V z
thatch
T { tS
thatched
T { tS t
that's
D { t s
thaw
T O:
thawed
T O: d
thaws
T O: z
thax-	ter
T { k	s t @r
thax-	ton
T { k	s t V n
thay-	er
T eI	@r
thayne
T eI n
the
D V
the-	a
T i:	V
the-	a-	ter
T i:	V	t @r
the-	a-	ters
T i:	V	t @r z
the-	a-	ter's
T i:	V	t @r z
the-	a-	tre
T i:	V	t @r
the-	a-	tres
T i:	V	t @r z
the-	a-	tre's
T i:	V	t @r z
the-	a-	tri-	ca-	li-	ty
T i:	{ t	r I	k {	l I	t i:
the-	a-	tri-	cal
T i:	{ t	r I	k V l
the-	a-	tri-	cal-	ly
T i:	{ t	r I	k V	l i:
the-	berge
T e	b @r dZ
the-	da
T i:	d V
the-	i-	sm
T i:	I	z V m
the-	ma-	tic
T i:	m {	t I k
the-	ma-	tical-	ly
T V	m {	t I k	l i:
the-	o
T i:	@U
the-	o-	bald
T i:	V	b V l d
the-	o-	cra-	cy
T i:	Q k	r V	s i:
the-	o-	cra-	tic
T i:	V k	r {	t I k
the-	o-	do-	ra
T i:	V	d O@	V
the-	o-	dor
T i:	V	d @r
the-	o-	dore
T i:	V	d O@
the-	o-	la
T i:	V	l V
the-	o-	lo-	gi-	an
T i:	V	l @U	dZ i:	V n
the-	o-	lo-	gi-	cal
T i:	V	l Q	dZ I	k V l
the-	o-	lo-	gians
T i:	V	l @U	dZ V n z
the-	o-	lo-	gical-	ly
T i:	V	l Q	dZ I k	l i:
the-	o-	lo-	gy
T i:	Q	l V	dZ i:
the-	o-	pha-	ni-	a
T i:	V	f {	n i:	V
the-	o-	phi-	la
T eI	V	f i:	l V
the-	o-	re-	ti-	cal
T i:	@r	e	t I	k V l
the-	o-	re-	ti-	cal-	ly
T i:	@r	e	t I	k V	l i:
the-	o-	re-	ti-	cian
T i:	@r	V	t I	S V n
the-	o-	re-	ti-	cians
T i:	@r	V	t I	S V n z
the-	o-	ri-	zes
T i:	@r	aI	z V z
the-	o-	ri-	zing
T i:	@r	aI	z I N
the-	o-	rist
T i:	@r	I s t
the-	o-	rists
T i:	@r	I s t s
the-	o-	rize
T i:	@r	aI z
the-	o-	rized
T i:	@r	aI z d
the-	on
T i:	V n
the-	one
T i:	Q n
the-	o's
T i:	@U z
the-	ra
T e@	V
the-	ra-	peu-	ti-	cal-	ly
T e@	V p	j u:	t I	k V	l i:
the-	ra-	peu-	tic
T e@	V p	j u:	t I k
the-	ra-	peu-	tics
T e@	V p	j u:	t I k s
the-	ra-	pies
T e@	V	p i: z
the-	ra-	pist
T e@	V	p V s t
the-	ra-	pists
T e@	V	p V s t s
the-	ra-	pist's
T e@	V	p V s t s
the-	ra-	py
T e@	V	p i:
the-	re-	sa
th @r	i:	s V
the-	re'll
D e@	V l
the-	rese
T e@	i: s
the-	reu-	pon
D e@	V	p Q n
the-	ri-	ot
T I@	i:	Q t
the-	ron
T e@	V n
the-	roux
T @r	u:
the-	sau-	rus
T V	s O@	V s
the-	ses
T i:	s i: z
the-	sis
T i:	s I s
the-	ta
T eI	t V
the-	tis
T i:	t I s
thea-	ter-	go-	er
T i:	t @r	g @U	@r
thea-	ter-	go-	ers
T i:	t @r	g @U	@r z
thea-	trics
T i: t	r I k s
theall
T i: l
thebes
T i: b z
thec-	la
T e k	l V
thed-	ford
T e d	f @r d
thee
D i:
theft
T e f t
thefts
T e f t s
thei-	ler
T aI	l @r
thein
T aI n
their
D e@
their-	self
D e@	s e l f
theirs
D e@ z
theis
D aI z
theiss
T aI s
thek-	la
T e k	l V
thel-	ma
T e l	m V
thel-	ma's
T e l	m V z
them
D e m
them-	self
D e m	s e l f
them-	selves
D e m	s e l v z
theme
T i: m
themed
T i: m d
themes
T i: m z
then
D e n
thence
D e n s
thence-	forth
D e n	s f O@ T
theo-	rem
T I@	V m
theo-	ries
T I@	i: z
theo-	ry
T I@	i:
theo-	ry's
T I@	i: z
ther-	mae
T @r	m i:
ther-	mal
T @r	m V l
ther-	mits
T @r	m I t s
ther-	mo
T @r	m @U
ther-	mo-	me-	ter
T @r	m Q	m V	t @r
ther-	mo-	me-	ters
T @r	m Q	m V	t @r z
ther-	mo-	nuc-	le-	ar
T @r	m @U	n u: k	l i:	@r
ther-	mo-	plas-	tic
T @r	m V p	l { s	t I k
ther-	mo-	plas-	tics
T @r	m V p	l { s	t I k s
ther-	mo-	set-	ting
T @r	m @U	s e	t I N
ther-	mos
T @r	m V s
ther-	mos-	tat
T @r	m V s	t { t
ther-	mos-	tats
T @r	m V s	t { t s
there
D e@
there-	a-	bouts
D e@	V	b aU t s
there-	af-	ter
D e@	{ f	t @r
there-	by
D e@	b aI
there-	fore
D e@	f O@
there-	in
D e@	I n
there-	of
T e@	V v
there'd
D e@ d
there's
D e@ z
therm
T @r m
thes-	pi-	an
T e s	p i:	V n
these
D i: z
thet-	ford
T e t	f @r d
theu-	rer
T @r	@r
thew
T u:
they
D eI
they'd
D eI d
they'll
D eI l
they're
D e@
they've
D eI v
thi
T i:
thi-	a-	min
T aI	V	m V n
thi-	bault
T V	b @U
thi-	er
T i:	@r
thi-	o-	dig-	ly-	col
T aI	@U	d I g	l I	k Q l
thi-	o-	kol
T aI	V	k O: l
thi-	s'll
D I	s V l
thi-	stle
T I	s V l
thi-	stles
T I	s V l z
thic-	ke-	ner
T I	k V	n @r
thic-	ke-	ning
T I	k V	n I N
thic-	ken
T I	k V n
thic-	kened
T I	k V n d
thic-	kens
T I	k V n z
thic-	ker
T I	k @r
thic-	kest
T I	k V s t
thic-	ket
T I	k V t
thic-	kets
T I	k V t s
thick
T I k
thick-	head
T I k	h e d
thick-	ly
T I k	l i:
thick-	ness
T I k	n V s
thie-	len
T i:	l V n
thie-	ve-	ry
T i:	v @r	i:
thie-	ving
T i:	v I N
thief
T i: f
thief's
T i: f s
thier-	ry
T I@	i:
thieves
T i: v z
thieves'
T i: v z
thigh
T aI
thighs
T aI z
thill
T I l
thim-	ble
T I m	b V l
thin
T I n
thin-	gy
T I	N i:
thin-	ker
T I N	k @r
thin-	kers
T I N	k @r z
thin-	king
T I N	k I N
thin-	ly
T I n	l i:
thin-	ner
T I	n @r
thin-	ness
T I n	n V s
thin-	nest
T I	n V s t
thin-	ning
T I	n I N
thine
D aI n
thing
T I N
things
T I N z
thing's
T I N z
think
T I N k
thinks
T I N k s
thinned
T I n d
thins
T I n z
thir-	teen
T @r	t i: n
thir-	teen's
T @r	t i: n z
thir-	teenth
T @r	t i: n T
thir-	teenths
T @r	t i: n T s
thir-	ti-	eth
T @r	t i:	V T
thir-	ties
T @r	t i: z
thir-	ty
T @r	d i:
thir-	ty-	some-	thing
T @r	t i:	s V m	T I N
thir-	ty's
T @r	d i: z
thir-	za
T @r	z V
third
T @r d
third-	ly
T @r d	l i:
thirds
T @r d z
thirs-	ty
T @r s	t i:
thirst
T @r s t
this
D I s
this-	sen
T I	s V n
tho
D @U
tho-	ma
T @U	m V
tho-	ma-	si-	na
T @U	m Q	s i:	n V
tho-	ma-	si-	ne
T @U	m Q	s i:	n i:
tho-	man
T @U	m V n
tho-	mas
th Q	m V s
tho-	mas-	ville
th Q	m V s	v I l
tho-	ra
T O@	V
tho-	ra-	cic
T O@	{	s I k
tho-	rax
T O@	{ k s
tho-	reau
T @r	@U
tho-	ri-	um
T Q@	i:	V m
tho-	rough
T @r	@U
tho-	rough-	bred
T @r	@U b	r e d
tho-	rough-	breds
T @r	@U b	r e d z
tho-	rough-	fare
T @r	@U	f e@
tho-	rough-	fares
T @r	@U	f e@ z
tho-	rough-	ly
T @r	@U	l i:
tho-	rough-	ness
T @r	@U	n V s
thole
T @U l
thom
th Q m
thom-	sen
T Q m	s V n
thom-	son
th Q m	s V n
thom-	son's
th Q m	s V n z
thome
T @U m
thomp-	son
th Q m	p s V n
thomp-	sons
th Q m	p s V n z
thomp-	son's
th Q m	p s V n z
thon
T Q n
thone
T @U n
thong
T O: N
thor
T O@
thor-	bert
T O@	b @r t
thor-	burn
T O@	b @r n
thor-	di-	a
T O@	d i:	V
thor-	dis
T O@	d I s
thor-	ley
T O@	l i:
thor-	man
T O@	m V n
thor-	ner
T O@	n @r
thor-	ni-	est
T O@	n i:	V s t
thor-	ny
T O@	n i:
thor-	sten
th O@ s	t V n
thor-	vald
T O@	v Q l d
thorn
T O@ n
thorn-	burg
T O@ n	b @r g
thorn-	dike
T O@ n	d I k
thorn-	dyke
T O@ n	d aI k
thorn-	ton
T O@ n	t V n
thorne
T O@ n
thorns
T O@ n z
thorn's
T O@ n z
thorp
T O@ p
thorpe
T O@ p
those
D @U z
thou
D aU
thou-	sand
T aU	z V n d
thou-	sands
T aU	z V n d z
thou-	sandth
T aU	z V n d T
thou-	sandths
T aU	z V n d T s
though
D @U
thought
T O: t
thought-	ful
T O: t	f V l
thought-	ful-	ly
T O: t	f V	l i:
thought-	ful-	ness
T O: t	f V l	n V s
thought-	less
T O: t	l V s
thoughts
T O: t s
thous
D aU z
thra-	sher
T r {	S @r
thra-	shes
T r {	S V z
thra-	shing
T r {	S I N
thrall
T r O: l
thrash
T r { S
thrashed
T r { S t
thre-	sher
T r e	S @r
thre-	shold
T r e	S @U l d
thre-	sholds
T r e S	h @U l d z
threa-	ded
T r e	d V d
threa-	ding
T r e	d I N
threa-	te-	ning
T r e	t V	n I N
threa-	te-	ning-	ly
T r e	t V	n I N	l i:
threa-	ten
T r e	t V n
threa-	tened
T r e	t V n d
threa-	tens
T r e	t V n z
thread
T r e d
thread-	bare
T r e d	b e@
thread-	fin
T r e d	f I n
threads
T r e d z
threat
T r e t
threats
T r e t s
three
T r i:
three-	fold
T r i:	f @U l d
three-	some
T r i:	s V m
threes
T r i: z
three's
T r i: z
threl-	keld
T r e l	k e l d
thresh
T r e S
threw
T r u:
thri-	ving
T r aI	v I N
thrice
T r aI s
thrif-	ti-	er
T r I f	t i:	@r
thrif-	ty
T r I f	t i:
thrift
T r I f t
thrifts
T r I f t s
thrift's
T r I f t s
thril-	ler
T r I	l @r
thril-	lers
T r I	l @r z
thril-	ling
T r I	l I N
thrill
T r I l
thrilled
T r I l d
thrills
T r I l z
thrips
T r I p s
thris-	ting
T r I s	t I N
thrive
T r aI v
thrived
T r aI v d
thrives
T r aI v z
thro-	wa-	way
T r @U	V	w eI
thro-	wer
T r @U	@r
thro-	wers
T r @U	@r z
thro-	wing
T r @U	I N
throa-	ted
T r @U	t V d
throat
T r @U t
throats
T r @U t s
throb
T r Q b
throb-	bing
T r Q	b I N
throes
T r @U z
throm-	bo-	ly-	sis
T r Q m	b @U	l V	s V s
throm-	bo-	ly-	tic
T r Q m	b @U	l I	t I k
throm-	bo-	sis
T r Q m	b @U	s I s
throne
T r @U n
throne-	ber-	ry
T r @U n	b e@	i:
throng
T r O: N
thronged
T r O: N d
throngs
T r O: N z
throop
T r u: p
throt-	t-	ling
T r Q	t V	l I N
throt-	tle
T r Q	t V l
throt-	tled
T r Q	t V l d
throt-	tles
T r Q	t V l z
through
T r u:
through-	out
T r u:	aU t
through-	put
T r u:	p U t
through-	way
T r u:	w eI
throve
T r @U v
throw
T r @U
throw-	back
T r @U	b { k
thrown
T r @U n
throws
T r @U z
thru
T r u:
thru-	shes
T r V	S V z
thru-	way
T r u:	w eI
thrus-	ter
T r V s	t @r
thrus-	ters
T r V s	t @r z
thrus-	ting
T r V s	t I N
thrush
T r V S
thrust
T r V s t
thrusts
T r V s t s
thud
T V d
thug
T V g
thug-	ge-	ry
T V	g @r	i:
thugs
T V g z
thum-	bing
T V	m I N
thum-	per
T V m	p @r
thum-	ping
T V m	p I N
thumb
T V m
thumb-	nail
T V m	n eI l
thumbed
T V m d
thumbs
T V m z
thump
T V m p
thumped
T V m p t
thumps
T V m p s
thun
T V n
thun-	de-	ring
T V n	d @r	I N
thun-	de-	rous
T V n	d @r	V s
thun-	der
T V n	d @r
thun-	der-	bird
T V n	d @r	b @r d
thun-	der-	birds
T V n	d @r	b @r d z
thun-	der-	bolt
T V n	d @r	b O: l t
thun-	der-	sho-	wer
T V n	d @r	S aU	w @r
thun-	der-	sho-	wers
T V n	d @r	S aU	w @r z
thun-	der-	storm
T V n	d @r s	t O@ m
thun-	der-	storms
T V n	d @r s	t O@ m z
thun-	der-	struck
T V n	d @r s	t r V k
thun-	dered
T V n	d @r d
thun-	ders
T V n	d @r z
thunk
T V n k
thur
D @r
thur-	ber
T @r	b @r
thur-	good
T @r	g U d
thur-	low
T @r	l @U
thur-	man
T @r	m V n
thur-	mond
T @r	m V n d
thur-	mond's
T @r	m V n d z
thur-	nau
T @r	n @U
thurm
T @r m
thurn
T @r n
thurs-	by
T @r s	b i:
thurs-	day
T @r z	d eI
thurs-	days
T @r z	d eI z
thurs-	day's
T @r z	d i: z
thurs-	tan
T @r s	t V n
thurs-	ton
T @r s	t V n
thus
D V s
thus-	ly
D V s	l i:
thwar-	ted
T w O@	t V d
thwar-	ting
T w O@	t I N
thwart
T w O@ t
thwarts
T w O@ t s
thwing
T w I N
thy
D aI
thy-	mi-	dine
T I	m I	d i: n
thy-	roid
T aI	r OI d
thyme
T aI m
thys-	sen
th aI	s V n
thys-	sen's
th aI	s V n z
ti
th i:
ti-	a
th i:	V
ti-	a-	nan-	men
th i:	e	n { n	m e n
ti-	a-	ra
th i:	Q@	V
ti-	an-	jin
th i:	{ n	dZ I n
ti-	be-	tan
th V	b e	t V n
ti-	be-	tans
th V	b e	t V n z
ti-	ber
th aI	b @r
ti-	bet
th V	b e t
ti-	bi-	a
th I	b i:	V
ti-	cer
th aI	s @r
ti-	chy
th I	tS i:
ti-	con-	de-	ro-	ga
th aI	k Q n	d @r	@U	g V
ti-	con-	de-	ro-	ga's
th aI	k Q n	d @r	@U	g V z
ti-	dal
th aI	d V l
ti-	ding
th aI	d I N
ti-	dings
th aI	d I N z
ti-	dy
th aI	d i:
ti-	ger
th aI	g @r
ti-	gers
th aI	g @r z
ti-	ger's
th aI	g @r z
ti-	gon
th I	g V n
ti-	jua-	na
th i:	w Q	n V
ti-	mer
th aI	m @r
ti-	mers
th aI	m @r z
ti-	mex
th aI	m e k s
ti-	mi-	di-	ty
th V	m I	d I	t i:
ti-	mi-	so-	a-	ra
th I	m I	s @U	Q@	V
ti-	mid
th I	m I d
ti-	mid-	ly
th I	m I d	l i:
ti-	ming
th aI	m I N
ti-	mo-	rese
th i:	m O@	i: z
ti-	mo-	rous
th I	m @r	V s
ti-	mo-	the-	a
th I	m V	D i:	V
ti-	mo-	thy
th I	m V	T i:
ti-	mon
th aI	m V n
ti-	mor
th i:	m O@
ti-	mor's
th i:	m O@ z
ti-	na
th i:	n V
ti-	na's
th i:	n V z
ti-	ni-	er
th aI	n i:	@r
ti-	ni-	est
th aI	n i:	V s t
ti-	no
th i:	n @U
ti-	ny
th aI	n i:
ti-	poff
th I	p O: f
ti-	ra-	mi-	su
th I@	V	m I	s u:
ti-	ra-	na
th I@	Q	n V
ti-	rade
th aI	r eI d
ti-	rades
th aI	r eI d z
ti-	rane
th I@	eI n
ti-	re
th aI	@r
ti-	re-	less
th aI	@r	l V s
ti-	re-	some
th aI	@r	s V m
ti-	red
th aI	@r d
ti-	red-	ness
th aI	@r d	n V s
ti-	res
th aI	@r z
ti-	ring
th aI	r I N
ti-	ros
th aI	r @U z
ti-	sh's
th I	S V z
ti-	ta
th i:	t V
ti-	ta-	nate
th aI	t V	n eI t
ti-	ta-	ni-	um
th aI	t eI	n i:	V m
ti-	ta-	nia
th V	t Q n	j V
ti-	ta-	nic
th aI	t {	n I k
ti-	tan
th aI	t V n
ti-	tans
th aI	t V n z
ti-	thing
th aI	D I N
ti-	tian
th I	S V n
ti-	til-	la-	ted
th I	t I	l eI	t I d
ti-	til-	la-	ting
th I	t I	l eI	t I N
ti-	til-	la-	tion
th I	t I	l eI	S V n
ti-	til-	late
th I	t I	l eI t
ti-	tle
th aI	t V l
ti-	tle-	hol-	der
th aI	t V l	h @U l	d @r
ti-	tled
th aI	t V l d
ti-	tles
th aI	t V l z
ti-	to
th i:	t @U
ti-	to's
th i:	t @U z
ti-	tu-	lar
th I	tS V	l @r
ti-	tus
th aI	t V s
ti-	tus-	ville
th aI	t V s	v I l
ti-	vo-	li
th I	v V	l i:
tian
th j Q n
tib-	bett
th I	b e t
tib-	betts
th I	b e t s
tib-	bie
th I	b i:
tib-	bitts
th I	b I t s
tib-	by
th I	b i:
tibbs
th I b z
tic
th I k
tic-	k-	lish
th I	k V	l I S
tic-	ke-	ted
th I	k V	t V d
tic-	ke-	ting
th I	k V	t I N
tic-	ker
th I	k @r
tic-	ket
th I	k V t
tic-	ket-	less
th I	k V t	l V s
tic-	ket-	mas-	ter
th I	k V t	m { s	t @r
tic-	ket-	mas-	ter's
th I	k V t	m { s	t @r z
tic-	kets
th I	k V t s
tic-	ket's
th I	k V t s
tic-	king
th I	k I N
tic-	kle
th I	k V l
tic-	kled
th I	k V l d
tic-	kles
th I	k V l z
tice
th aI s
tick
th I k
tick-	nor
th I k	n @r
ticked
th I k t
ticks
th I k s
tics
th I k s
tid-	bit
th I d	b I t
tid-	bits
th I d	b I t s
tid-	dly-	winks
th I d	l V	w I N k s
tid-	well
th I d	w V l
tide
th aI d
tide-	wa-	ter
th aI d	w O:	t @r
tides
th aI d z
tie
th aI
tie-	ing
th aI	I N
tie-	less
th aI	l V s
tie-	nan-	men
th j e	n V n	m e n
tied
th aI d
tiede-	man
th i: d	m V n
tien
th j e n
tier
th i: r
tier-	nan
th I@	n V n
tier-	ney
th I@	n i:
tierce
th i: r s
tiered
th i: r d
tiers
th i: r z
ties
th aI z
tif-	fa-	ny
th I	f V	n i:
tif-	fa-	ny's
th I	f V	n i: z
tif-	fin
th I	f I n
tif-	ton
th I f	t V n
tiff
th I f
tift
th I f t
tig
th I g
tig-	rean
th I g	r i: n
tig-	ris
th aI g	r I s
tigges
th I g z
tigh-	te-	ning
th aI	t V	n I N
tigh-	te-	nings
th aI	t V	n I N z
tigh-	ten
th aI	t V n
tigh-	tened
th aI	t V n d
tigh-	tens
th aI	t V n z
tigh-	ter
th aI	t @r
tigh-	test
th aI	t V s t
tight
th aI t
tight-	fis-	ted
th aI t	f I s	t V d
tight-	ly
th aI t	l i:
tight-	ness
th aI t	n V s
tight-	rope
th aI t	r @U p
tight-	wad
th aI t	w Q d
tights
th aI t s
tike
th aI k
tikes
th aI k s
til
th I l
til-	bu-	ry
th I l	b e@	i:
til-	da
th I l	d V
til-	den
th I l	d V n
til-	ford
th I l	f @r d
til-	le-	ry
th I	l @r	i:
til-	ler
th I	l @r
til-	ley
th I	l i:
til-	lie
th I	l i:
til-	ling
th I	l I N
til-	lot-	son
th I	l V t	s V n
til-	ly
th I	l i:
til-	ney
th I l	n i:
til-	ted
th I l	t V d
til-	ting
th I l	t I N
til-	ton
th I l	t V n
tile
th aI l
tiled
th aI l d
tiles
th aI l z
tilgh-	man
th I l	m V n
till
th I l
till-	man
th I l	m V n
till-	son
th I l	s V n
tilt
th I l t
tilth
th I l T
tilts
th I l t s
tim
th I m
tim-	ber
th I m	b @r
tim-	ber-	land
th I m	b @r	l { n d
tim-	ber-	lands
th I m	b @r	l { n d z
tim-	ber-	line
th I m	b @r	l aI n
tim-	ber-	man
th I m	b @r	m V n
tim-	bers
th I m	b @r z
tim-	bre
th I m	b @r
tim-	buk-	tu
th I m	b V k	t u:
tim-	ken
th I m	k V n
tim-	mer
th I	m @r
tim-	mie
th I	m i:
tim-	mons
th I	m V n z
tim-	my
th I	m i:
tim-	pa-	ni
th I m	p V	n i:
timb-	lin
th I m	b l I n
time
th aI m
time-	frame
th aI m	f r eI m
time-	less
th aI m	l V s
time-	li-	ness
th aI m	l i:	n V s
time-	line
th aI m	l aI n
time-	lines
th aI m	l aI n z
time-	ly
th aI m	l i:
time-	out
th aI	m aU t
time-	piece
th aI m	p i: s
time-	share
th aI m	S e@
time-	ta-	ble
th aI m	t eI	b V l
time-	ta-	bles
th aI m	t eI	b V l z
timed
th aI m d
times
th aI m z
time's
th aI m z
timms
th I m z
timp-	son
th I m	p s V n
tims
th I m z
tim's
th I m z
tin
th I n
tin-	dal
th I n	d V l
tin-	dall
th I n	d V l
tin-	der
th I n	d @r
tin-	der-	box
th I n	d @r	b Q k s
tin-	g-	ler
th I N	g V	l @r
tin-	g-	ling
th I N	g V	l I N
tin-	gen
th I	N V n
tin-	gey
th I N	g i:
tin-	gle
th I N	g V l
tin-	k-	ler
th I N	k V	l @r
tin-	k-	ling
th I N	k V	l I N
tin-	ke-	rer
th I N	k @r	@r
tin-	ke-	rers
th I N	k @r	@r z
tin-	ke-	ring
th I N	k @r	I N
tin-	ker
th I N	k @r
tin-	kered
th I N	k @r d
tin-	ker's
th I N	k @r z
tin-	kle
th I N	k V l
tin-	kled
th I N	k V l d
tin-	ley
th I n	l i:
tin-	man
th I n	m { n
tin-	ny
th I	n i:
tin-	sel
th I n	s V l
)"
R"(tin-	sel-	town
th I n	s V l	t aU n
tin-	ted
th I n	t V d
tin-	type
th I n	t aI p
tinc-	ture
th I N	k tS @r
tinc-	tures
th I N	k tS @r z
tine
th aI n
tines
th aI n z
ting
th I N
ting-	ley
th I N	g l i:
tinge
th I n dZ
tinged
th I N d
tins
th I n z
tins-	ley
th I n	s l i:
tins-	man
th I n	s m V n
tint
th I n t
tints
th I n t s
tip
th I p
tip-	off
th I	p O: f
tip-	pe-	ra-	ry
th I	p @r	e@	i:
tip-	per
th I	p @r
tip-	pers
th I	p @r z
tip-	pet
th I	p V t
tip-	pets
th I	p e t s
tip-	pett
th I	p e t
tip-	ping
th I	p I N
tip-	ple
th I	p V l
tip-	py
th I	p i:
tip-	sy
th I p	s i:
tip-	toe
th I p	t @U
tip-	toe-	ing
th I p	t @U	I N
tip-	toed
th I p	t @U d
tip-	ton
th I p	t V n
tipp
th I p
tipped
th I p t
tips
th I p s
tips-	ter
th I p	s t @r
tir-	rell
th I@	eI l
tire-	less-	ly
th aI r	l V s	l i:
tire-	ma-	ker
th aI r	m eI	k @r
tis
th I z
tis-	dale
th I s	d eI l
tis-	sue
th I s	j u:
tis-	sues
th I s	j u: z
tish
th I S
tit
th I t
tit-	for-	tat
th I t	f O@	t { t
tit-	man
th I t	m V n
tit-	ter
th I	t @r
tit-	tle
th I	t V l
tithe
th aI D
)"