R"(grand-	child-	ren
gh r { n	tS I l	d r V n
grand-	dad-	dy
gh r { n	d {	d i:
grand-	daugh-	ter
gh r { n	d O:	t @r
grand-	daugh-	ters
gh r { n	d O:	t @r z
grand-	daugh-	ter's
gh r { n	d O:	t @r z
grand-	fa-	the-	ring
gh r { n	d f Q	D @r	I N
grand-	fa-	ther
gh r { n	d f Q	D @r
grand-	fa-	ther-	ly
gh r { n	d f Q	D @r	l i:
grand-	fa-	thered
gh r { n	d f Q	D @r d
grand-	fa-	thers
gh r { n	d f Q	D @r z
grand-	fa-	ther's
gh r { n	d f Q	D @r z
grand-	kid
gh r { n	d k I d
grand-	kids
gh r { n	d k I d z
grand-	ly
gh r { n	d l i:
grand-	ma
gh r {	m Q
grand-	mas
gh r { n	d m Q z
grand-	ma's
gh r { n	d m Q z
grand-	mas-	ter
gh r { n	d m { s	t @r
grand-	mo-	ther
gh r { n	d m V	D @r
grand-	mo-	ther-	ly
gh r { n	d m V	D @r	l i:
grand-	mo-	thers
gh r { n	d m V	D @r z
grand-	mo-	ther's
gh r { n	d m V	D @r z
grand-	ne-	phew
gh r { n	d n e f	j u:
grand-	pa
gh r { n	d p Q
grand-	pa-	rent
gh r { n	d p e@	V n t
grand-	pa-	rents
gh r { n	d p e@	V n t s
grand-	son
gh r { n	d s V n
grand-	sons
gh r { n	d s V n z
grand-	son's
gh r { n	d s V n z
grand-	stan-	ding
gh r { n	d s t { n	d I N
grand-	stand
gh r { n	d s t { n d
grand-	view
gh r { n	d v j u:
grande
gh r { n d
grands
gh r { n d z
grand's
gh r { n d z
grange
gh r eI n dZ
grant
gh r { n t
grant-	land
gh r { n	t l V n d
grants
gh r { n t s
grant's
gh r { n t s
grap-	ple
gh r {	p V l
grap-	pled
gh r {	p V l d
grap-	ples
gh r {	p V l z
grape
gh r eI p
grape-	fruit
gh r eI p	f r u: t
grape-	fruits
gh r eI p	f r u: t s
grape-	shot
gh r eI p	S Q t
grape-	vine
gh r eI p	v aI n
grape-	vines
gh r eI p	v aI n z
grapes
gh r eI p s
graph
gh r { f
graphs
gh r { f s
grapp-	ling
gh r { p	l I N
gras
gh r { s
gras-	ping
gh r { s	p I N
gras-	ser
gh r {	s @r
gras-	sers
gh r {	s @r z
gras-	ses
gh r {	s V z
gras-	si
gh r {	s i:
gras-	sy
gh r {	s i:
grasp
gh r { s p
grasped
gh r { s p t
grasps
gh r { s p s
grass
gh r { s
grass-	green
gh r { s	g r i: n
grass-	hop-	per
gh r { s	h Q	p @r
grass-	hop-	pers
gh r { s	h Q	p @r z
grass-	land
gh r { s	l { n d
grass-	lands
gh r { s	l { n d z
grass-	like
gh r { s	l aI k
grass-	man
gh r { s	m V n
grass-	root
gh r { s	r u: t
grass-	roots
gh r { s	r u: t s
grasse
gh r { s
grassed
gh r { s t
grat-	tan
gh r {	t V n
grat-	ton
gh r {	t V n
grate
gh r eI t
grate-	ful
gh r eI t	f V l
grate-	ful-	ly
gh r eI t	f V	l i:
grates
gh r eI t s
gratz
gh r { t s
grave
gh r eI v
grave-	ly
gh r eI v	l i:
grave-	side
gh r eI v	s aI d
grave-	site
gh r eI v	s aI t
grave-	s's
gh r eI v	z V z
grave-	stone
gh r eI v	s t @U n
grave-	stones
gh r eI v	s t @U n z
grave-	yard
gh r eI v	j Q@ d
grave-	yards
gh r eI v	j Q@ d z
graves
gh r eI v z
gray
gh r eI
gray-	beard
gh r eI	b i: r d
gray-	beards
gh r eI	b i: r d z
gray-	bill
gh r eI	b I l
gray-	don
gh r eI	d V n
gray-	ling
gh r eI	l I N
gray-	son
gh r eI	s V n
grays
gh r eI z
gray's
gh r eI z
graze
gh r eI z
grazed
gh r eI z d
gre-	cian
gh r i:	S V n
gre-	co
gh r e	k @U
gre-	del
gh r e	d V l
gre-	ga
gh r i:	g V
gre-	ga-	ri-	ous
gh r V	g e@	i:	V s
gre-	go
gh r e	g @U
gre-	go-	ri-	an
gh r V	g O@	i:	V n
gre-	go-	ri-	o
gh r I	g O@	i:	@U
gre-	go-	ry
gh r e	g @r	i:
gre-	go-	ry's
gh r e	g @r	i: z
gre-	goire
gh r I g	w Q@
gre-	gor
gh r e	g @r
gre-	na-	da
gh r V	n eI	d V
gre-	nade
gh r V	n eI d
gre-	nades
gh r V	n eI d z
gre-	ni-	er
gh r i:	n i:	@r
gre-	no-	ble
gh r V	n @U	b V l
gre-	sham
gh r e	S V m
gre-	sham's
gh r e	S V m z
gre-	ta
gh r i:	t V
gre-	tal
gh r e	t V l
gre-	ta's
gh r i:	t V z
gre-	tel
gh r e	t V l
gre-	thel
gh r e	T V l
grea-	ser
gh r i:	s @r
grea-	sing
gh r i:	s I N
grea-	sy
gh r i:	s i:
grea-	ter
gh r eI	t @r
grea-	test
gh r eI	t V s t
grease
gh r i: s
grease-	wood
gh r i: s	w U d
greased
gh r i: s t
great
gh r eI t
great-	cir-	cle
gh r eI t	s @r	k V l
great-	ly
gh r eI t	l i:
great-	ness
gh r eI t	n V s
greats
gh r eI t s
great's
gh r eI t s
greave
gh r i: v
greaves
gh r i: v z
greb
gh r e b
grebe
gh r i: b
gree-	ce's
gh r i:	s V z
gree-	di-	er
gh r i:	d i:	@r
gree-	di-	est
gh r i:	d i:	V s t
gree-	di-	ly
gh r i:	d I	l i:
gree-	dy
gh r i:	d i:
gree-	ley
gh r i:	l i:
gree-	ley-	ville
gh r i:	l i:	v I l
gree-	ly
gh r i:	l i:
gree-	na-	way
gh r i:	n V	w eI
gree-	ne-	ry
gh r i:	n @r	i:
gree-	ner
gh r i:	n @r
gree-	nest
gh r i:	n V s t
gree-	ning
gh r i:	n I N
gree-	nish
gh r i:	n I S
gree-	nough
gh r i:	n V f
gree-	nup
gh r i:	n V p
gree-	son
gh r i:	s V n
gree-	ted
gh r i:	t V d
gree-	ting
gh r i:	t I N
gree-	tings
gh r i:	t I N z
greece
gh r i: s
greed
gh r i: d
greek
gh r i: k
greeks
gh r i: k s
green
gh r i: n
green-	back
gh r i: n	b { k
green-	backs
gh r i: n	b { k s
green-	back's
gh r i: n	b { k s
green-	belt
gh r i: n	b e l t
green-	berg
gh r i: n	b @r g
green-	berg's
gh r i: n	b @r g z
green-	blatt
gh r i: n	b l V t
green-	burg
gh r i: n	b @r g
green-	bush
gh r i: n	b U S
green-	ca-	stle
gh r i: n	k {	s V l
green-	feld
gh r i: n	f e l d
green-	field
gh r i: n	f i: l d
green-	field's
gh r i: n	f i: l d z
green-	halgh
gh r i: n	h V l g
green-	ham
gh r i:	n V m
green-	hou-	ses
gh r i: n	h aU	s V z
green-	house
gh r i: n	h aU s
green-	land
gh r i: n	l V n d
green-	leaf
gh r i: n	l i: f
green-	lee
gh r i: n	l i:
green-	ly
gh r i: n	l i:
green-	mai-	ler
gh r i: n	m eI	l @r
green-	mail
gh r i: n	m eI l
green-	man
gh r i: n	m V n
green-	ness
gh r i: n	n V s
green-	pea-	ce's
gh r i: n	p i:	s V z
green-	peace
gh r i: n	p i: s
green-	slade
gh r i: n	s l V d
green-	span
gh r i: n	s p { n
green-	span's
gh r i: n	s p { n z
green-	stein
gh r i: n	s t aI n
green-	stone
gh r i: n	s t @U n
green-	vale
gh r i: n	v eI l
green-	ville
gh r i: n	v I l
green-	wald
gh r i: n	w O: l d
green-	wald's
gh r i: n	w O: l d z
green-	way
gh r i: n	w eI
green-	well
gh r i: n	w e l
green-	wi-	ch's
gh r e	n I	tS V z
green-	wich
gh r e	n I tS
green-	wood
gh r i: n	w U d
greene
gh r i: n
greened
gh r i: n d
greene's
gh r i: n z
greens
gh r i: n z
green's
gh r i: n z
greens-	bo-	ro
gh r i: n	z b @r	r @U
greens-	burg
gh r i: n	z b @r g
greer
gh r I@
greet
gh r i: t
greets
gh r i: t s
grefe
gh r i: f
greff
gh r e f
greg
gh r e g
greg-	son
gh r e g	s V n
gregg
gh r e g
greggs
gh r e g z
greg's
gh r e g z
grei-	ner
gh r aI	n @r
greig
gh r i: g
grein
gh r eI n
grem-	lin
gh r e m	l I n
grem-	lins
gh r e m	l I n z
gren
gh r e n
gren-	del
gh r e n	d V l
gren-	del's
gh r e n	d V l z
gren-	fell
gh r e n	f V l
gret-	chen
gh r e	tS V n
gret-	na
gh r e t	n V
gret-	na's
gh r e t	n V z
grete
gh r i: t
gretz-	ky
gh r e t	s k i:
greve
gh r i: v
grew
gh r u:
grey
gh r eI
grey-	hound
gh r eI	h aU n d
grey-	hound's
gh r eI	h aU n d z
grey-	lag
gh r eI	l { g
grey-	stone
gh r eI s	t @U n
grey's
gh r eI z
gri-	ma-	ces
gh r I	m V	s V z
gri-	ma-	cing
gh r I	m V	s I N
gri-	mace
gh r I	m V s
gri-	maced
gh r I	m V s t
gri-	mal-	di
gh r i:	m Q l	d i:
gri-	my
gh r aI	m i:
gri-	ping
gh r aI	p I N
gri-	shil-	da
gh r I	S I l	d V
gri-	stle
gh r I	s V l
gri-	zel-	da
gh r i:	z e l	d V
grib-	ble
gh r I	b V l
grib-	bles
gh r I	b V l z
grice
gh r aI s
grif-	fin's
gh r I	f I n z
grif-	fis
gh r I	f I s
grif-	fith
gh r I	f I T
grif-	fiths
gh r I	f I T s
grif-	fith's
gh r I	f I T s
grif-	fon
gh r I	f V n
grif-	fy
gh r I	f i:
griggs
gh r I g z
gril-	ling
gh r I	l I N
grill
gh r I l
grille
gh r I l
grilled
gh r I l d
grills
gh r I l z
grim
gh r I m
grim-	ly
gh r I m	l i:
grim-	mer
gh r I	m @r
grim-	mest
gh r I	m V s t
grim-	ness
gh r I m	n V s
grim-	shaw
gh r I m	S O:
grime
gh r aI m
grimes
gh r aI m z
grimm
gh r I m
grimme
gh r I m
grimm's
gh r I m z
grims-	ley
gh r I m	z l i:
grin
gh r I n
grin-	der
gh r aI n	d @r
grin-	ders
gh r aI n	d @r z
grin-	ding
gh r aI n	d I N
grin-	dle
gh r I n	d V l
grin-	go
gh r I N	g @U
grin-	gos
gh r I N	g @U z
grin-	nell
gh r I	n e l
grin-	ning
gh r I	n I N
grinch
gh r I n tS
grind
gh r aI n d
grind-	lay
gh r aI n	d l eI
grind-	stone
gh r aI n	d s t @U n
grinds
gh r aI n d z
gring
gh r I N
grinned
gh r I n d
grins
gh r I n z
grip
gh r I p
grip-	ping
gh r I	p I N
gripe
gh r aI p
griped
gh r aI p t
gripes
gh r aI p s
gripped
gh r I p t
grips
gh r I p s
gris-	com
gh r I s	k V m
gris-	ly
gh r I z	l i:
gris-	som
gh r I	s V m
gris-	wold
gh r I s	w @U l d
grise
gh r aI z
grist
gh r I s t
grit
gh r I t
grit-	ter
gh r I	t @r
grit-	ting
gh r I	t I N
grit-	ty
gh r I	t i:
grits
gh r I t s
griz
gh r I z
griz-	zle
gh r I	z V l
griz-	zled
gh r I	z V l d
grizz-	lies
gh r I z	l i: z
grizz-	ly
gh r I z	l i:
gro
gh r @U
gro-	bi-	an
gh r @U	b i:	V n
gro-	ce-	ries
gh r @U	s @r	i: z
gro-	ce-	ry
gh r @U	s @r	i:
gro-	cer
gh r @U	s @r
gro-	cers
gh r @U	s @r z
gro-	cer's
gh r @U	s @r z
gro-	din
gh r @U	d I n
gro-	gan
gh r @U	g V n
gro-	lier
gh r @U l	j @r
gro-	ma
gh r Q	m V
gro-	my-	ko
gh r @U	m i:	k @U
gro-	ping
gh r @U	p I N
gro-	tesque
gh r @U	t e s k
gro-	tesque-	ly
gh r @U	t e s	k l i:
gro-	ton
gh r Q	t V n
gro-	ve-	ling
gh r O:	v V	l I N
gro-	vel
gh r Q	v V l
gro-	ver
gh r @U	v @r
gro-	vers
gh r @U	v @r z
gro-	ver's
gh r @U	v @r z
gro-	wer
gh r @U	@r
gro-	wers
gh r @U	@r z
gro-	wing
gh r @U	I N
groa-	ning
gh r @U	n I N
groan
gh r @U n
groaned
gh r @U n d
groans
gh r @U n z
groat
gh r @U t
grobe
gh r @U b
groes-	beck
gh r @U s	b e k
groff
gh r O: f
grog-	gy
gh r Q	g i:
groh
gh r @U
groin
gh r OI n
groined
gh r OI n d
groins
gh r OI n z
gron-	din
gh r Q n	d I n
gron-	seth
gh r Q n	s e T
grone
gh r @U n
groo-	mer
gh r u:	m @r
groo-	mers
gh r u:	m @r z
groo-	ming
gh r u:	m I N
groo-	ver
gh r u:	v @r
groo-	vi-	est
gh r u:	v i:	V s t
groo-	vy
gh r u:	v i:
groom
gh r u: m
groome
gh r u: m
groomed
gh r u: m d
grooms
gh r u: m z
groos
gh r u: z
groot
gh r u: t
groove
gh r u: v
grooves
gh r u: v z
grop-	per
gh r Q	p @r
grope
gh r @U p
groped
gh r @U p t
gros
gh r @U s
gros-	beak
gh r @U s	b i: k
gros-	beaks
gh r @U s	b i: k s
gros-	ser
gh r @U	s @r
gros-	ses
gh r @U	s V z
gros-	si
gh r @U	s i:
gros-	sing
gh r @U	s I N
gros-	so
gh r @U	s @U
grose
gh r @U z
gross
gh r @U s
gross-	ly
gh r @U s	l i:
gross-	man
gh r @U s	m V n
gross-	man's
gh r @U s	m V n z
grosse
gh r Q s
grossed
gh r @U s t
grosve-	nor
gh r @U v	n @r
grosz
gh r @U s
grot-	to
gh r Q	t @U
grote
gh r @U t
grou-	cho
gh r aU	tS @U
grou-	per
gh r u:	p @r
grou-	pers
gh r u:	p @r z
grou-	pie
gh r u:	p i:
grou-	pies
gh r u:	p i: z
grou-	ping
gh r u:	p I N
grou-	pings
gh r u:	p I N z
grou-	ses
gh r aU	s V z
grou-	sing
gh r aU	s I N
grou-	ting
gh r aU	t I N
grouch
gh r aU tS
groun-	ded
gh r aU n	d V d
groun-	ding
gh r aU n	d I N
ground
gh r aU n d
ground-	brea-	king
gh r aU n	d b r eI	k I N
ground-	hog
gh r aU n	d h Q g
ground-	less
gh r aU n	d l V s
ground-	ling
gh r aU n	d l I N
ground-	nut
gh r aU n	d n V t
ground-	nuts
gh r aU n	d n V t s
ground-	skee-	per
gh r aU n	d s k i:	p @r
ground-	skee-	pers
gh r aU n	d s k i:	p @r z
ground-	swell
gh r aU n	d s w e l
ground-	wa-	ter
gh r aU n	d w Q	t @r
ground-	work
gh r aU n	d w @r k
grounds
gh r aU n d z
group
gh r u: p
group-	ware
gh r u: p	w e@
grouped
gh r u: p t
groups
gh r u: p s
group's
gh r u: p s
grouse
gh r aU s
groused
gh r aU s t
grout
gh r aU t
grove
gh r @U v
grove-	man
gh r @U v	m V n
groves
gh r @U v z
grove's
gh r @U v z
grow
gh r @U
grow-	ling
gh r @U	l I N
grow-	nup
gh r @U	n V p
grow-	nups
gh r @U	n V p s
growl
gh r aU l
growled
gh r aU l d
growls
gh r aU l z
grown
gh r @U n
grown-	up
gh r @U	n V p
grows
gh r @U z
growth
gh r @U T
growths
gh r @U T s
groz-	ny
gh r @U z	n i:
groz-	ny's
gh r @U z	n i: z
gru-	ber
gh r u:	b @r
gru-	e-	ling
gh r u:	V	l I N
gru-	el
gh r u:	V l
gru-	is
gh r u:	I z
gru-	ne-	wald
gh r V	n V	w O: l d
gru-	nion
gh r V n	j V n
gru-	ver
gh r u:	v @r
grub
gh r V b
grub-	by
gh r V	b i:
grub-	man
gh r V b	m V n
grubb
gh r V b
grubbs
gh r V b z
grube
gh r u: b
grubs
gh r V b z
grud-	ges
gh r V	dZ V z
grud-	ging
gh r V	dZ I N
grud-	ging-	ly
gh r V	dZ I N	l i:
grudge
gh r V dZ
grue-	some
gh r u:	s V m
gruen-	berg
gh r U n	b @r g
gruff
gh r V f
grum
gh r V m
grum-	b-	ling
gh r V m	b V	l I N
grum-	b-	lings
gh r V m	b V	l I N z
grum-	ble
gh r V m	b V l
grum-	bled
gh r V m	b V l d
grum-	bles
gh r V m	b V l z
grum-	man
gh r V	m V n
grum-	man's
gh r V	m V n z
grum-	pi-	er
gh r V m	p i:	@r
grum-	py
gh r V m	p i:
grump
gh r V m p
grun
gh r V n
grun-	berg
gh r V n	b @r g
grun-	dy
gh r V n	d i:
grun-	gy
gh r V n	dZ i:
grun-	ted
gh r V n	t V d
grun-	ting
gh r V n	t I N
grunge
gh r V n dZ
grunt
gh r V n t
grunts
gh r V n t s
grup-	po
gh r u:	p @U
grus-	sing
gh r V	s I N
grush
gh r V S
gruss
gh r V s
gry-	phons
gh r I	f V n z
g's
dZ i: z
gu
gh u:
gu-	ber-	na-	to-	ri-	al
gh u:	b @r	n V	t O@	i:	V l
gu-	ja-	rat
gh j u:	dZ @r	{ t
gu-	la
gh j u:	l V
gu-	lag
gh j u:	l { g
gu-	las
gh j u:	l V z
gu-	lick
gh j u:	l I k
gu-	mi
gh u:	m i:
gu-	re-	vich
gh j u:	r I	v I tS
gu-	ri-	an
gh j U@	i:	V n
gu-	ru
gh u:	r u:
gu-	rus
gh u:	r u: z
gu-	ru's
gh u:	r u: z
gu-	sel-	la
gh j u:	s e	l V
gu-	sher
gh V	S @r
gu-	shers
gh V	S @r z
gu-	shes
gh V	S V z
gu-	shing
gh V	S I N
gu-	ten-	berg
gh u:	t V n	b @r g
gu-	tier-	rez
gh u: t	j e@	e z
gu-	ya-	na
gh aI	Q	n V
gu-	yer
gh aI	@r
gu-	yon
gh aI	V n
gu-	yot
gh aI	V t
gua-	ca-	mo-	le
gh w Q	k V	m @U	l i:
gua-	da-	la-	ja-	ra
gh w Q	d V	l V	h Q@	V
gua-	da-	lupe
gh w Q	d V	l u: p
gua-	dal-	ca-	nal
gh w Q	d V l	k V	n { l
gua-	de-	loupe
gh w Q	d V	l u: p
gua-	na-	co
gh w V	n Q	k @U
gua-	nine
gh w Q	n i: n
gua-	no
gh w Q	n @U
gua-	ra-	ni
gh w Q@	V	n i:
gua-	ran-	tee
gh e@	V n	t i:
gua-	ran-	tee-	ing
gh e@	V n	t i:	I N
gua-	ran-	teed
gh e@	V n	t i: d
gua-	ran-	tees
gh e@	V n	t i: z
gua-	ran-	tee's
gh e@	V n	t i: z
gua-	ran-	ties
gh e@	V n	t i: z
gua-	ran-	tor
gh e@	V n	t O@
gua-	ran-	tors
gh e@	V n	t O@ z
gua-	ran-	ty
gh e@	V n	t i:
gua-	ran-	ty's
gh e@	V n	t i: z
gua-	ri-	ni
gh Q@	i:	n i:
gua-	ri-	no
gh Q@	i:	n @U
gua-	te-	ma-	la
gh w Q	t V	m Q	l V
gua-	te-	ma-	lan
gh w Q	t V	m Q	l V n
gua-	te-	ma-	lans
gh w Q	t V	m Q	l V n z
gua-	te-	ma-	la's
gh w Q	t V	m Q	l V z
gua-	va
gh w Q	v V
gua-	vas
gh w Q	v V z
gua-	ya-	be-	ra
gh w aI	V	b e@	V
guam
gh w Q m
guan-	ta-	na-	mo
gh w Q n	t Q	n V	m @U
guan-	ta-	na-	mo's
gh w Q n	t Q	n V	m @U z
guang-	zhou
gh w { N	z u:
guar-	ded
gh Q@	d V d
guar-	ded-	ly
gh Q@	d V d	l i:
guar-	di-	a
gh w Q@	d i:	V
guar-	di-	an
gh Q@	d i:	V n
guar-	di-	an-	ship
gh Q@	d i:	V n	S I p
guar-	di-	ans
gh Q@	d i:	V n z
guar-	di-	an's
gh Q@	d i:	V n z
guar-	ding
gh Q@	d I N
guar-	ne-	ri
gh Q@	n e@	i:
guar-	nie-	ri
gh Q@	n I@	i:
guard
gh Q@ d
guard-	fish
gh Q@ d	f I S
guard-	rail
gh Q@ d	r eI l
guard-	rails
gh Q@ d	r eI l z
guards
gh Q@ d z
guard's
gh Q@ d z
guards-	man
gh Q@ d	z m { n
guards-	men
gh Q@ d	z m I n
gub-	bins
gh V	b I n z
guc-	ci
gh u:	tS i:
guck
gh V k
gud-	geon
gh V	dZ V n
gude
gh j u: d
gue
gh j u:
gue-	ril-	la
gh @r	I	l V
gue-	ril-	las
gh @r	I	l V z
gue-	rin
gh e@	I n
gue-	va-	ra
gh eI	v Q@	V
guen-	na
gh eI	n V
guen-	ther
gh U n	T @r
guer-	ne-	ville
gh @r	n V	v I l
guer-	ra
gh w e@	V
guer-	rant
gh e@	V n t
guer-	re-	ro
gh @r	e@	@U
guer-	ril-	la
gh @r	I	l V
guer-	ril-	las
gh @r	I	l V z
guern-	sey
gh @r n	z i:
guerre
gh e@
gues-	ser
gh e	s @r
gues-	sers
gh e	s @r z
gues-	ses
gh e	s V z
gues-	sing
gh e	s I N
gues-	ted
gh e s	t V d
guess
gh e s
guess-	ti-	mate
gh e s	t I	m V t
guess-	ti-	mates
gh e s	t I	m V t s
guess-	work
gh e s	w @r k
guessed
gh e s t
guest
gh e s t
guest-	hou-	ses
gh e s	t h aU	s V z
guest-	house
gh e s	t h aU s
guests
gh e s t s
guest's
gh e s t s
guf-	faw
gh V	f O:
guf-	faws
gh V	f O: z
guf-	fey
gh V	f i:
guf-	fin
gh V	f I n
guf-	fy
gh V	f i:
guff
gh V f
gug-	gen-	heim
gh u:	g V n	h aI m
gug-	li-	el-	mo
gh u: g	l i:	e l	m @U
gui-	a-	na
gh i:	Q	n V
gui-	dance
gh aI	d V n s
gui-	ded
gh aI	d V d
gui-	der
gh aI	d @r
gui-	ding
gh aI	d I N
gui-	do
gh w i:	d @U
gui-	dot-	ti
gh i:	d @U	t i:
gui-	tar
gh V	t Q@
guide
gh aI d
guide-	book
gh aI d	b U k
guide-	books
gh aI d	b U k s
guide-	line
gh aI d	l aI n
guide-	lines
gh aI d	l aI n z
guide-	post
gh aI d	p @U s t
guide-	posts
gh aI d	p @U s t s
guides
gh aI d z
guide's
gh aI d z
guil-	bert
gh I l	b @r t
guil-	der
gh I l	d @r
guil-	ders
gh I l	d @r z
guil-	der's
gh I l	d @r z
guil-	ford
gh I l	f @r d
guil-	ford's
gh I l	f @r d z
guil-	laume
gh I	l aU m
guil-	le-	mette
gh I	l V	m e t
guil-	len
gh I	l V n
guil-	ler-	mo
gh w V l	j e@	m @U
guild
gh I l d
)"
R"(guild-	hall
gh I l	d h O: l
guilds
gh I l d z
guild's
gh I l d z
guile
gh aI l
guile-	less
gh aI l	l V s
guiles
gh aI l z
gul
gh V l
gul-	lah
gh V	l V
gul-	let
gh V	l V t
gul-	ley
gh V	l i:
gul-	li-	bi-	li-	ty
gh V	l I	b I	l I	t i:
gul-	li-	ble
gh V	l I	b V l
gul-	li-	ver
gh V	l I	v @r
gul-	lies
gh V	l i: z
gul-	lion
gh V l	j V n
gul-	ly
gh V	l i:
gul-	ping
gh V l	p I N
gul-	yas
gh u: l	j V s
gulch
gh V l tS
gulf
gh V l f
gulf-	port
gh V l	f p O@ t
gulf's
gh V l f s
gull
gh V l
gulls
gh V l z
gull's
gh V l z
gulp
gh V l p
gulped
gh V l p t
gulps
gh V l p s
gum
gh V m
gum-	bel
gh V m	b V l
gum-	bo
gh V m	b @U
gum-	my
gh V	m i:
gum-	shoe
gh V m	S u:
gummed
gh V m d
gump
gh V m p
gump-	tion
gh V m	p S V n
gump's
gh V m p s
gums
gh V m z
gun
gh V n
gun-	boat
gh V n	b @U t
gun-	boats
gh V n	b @U t s
gun-	cot-	ton
gh V n	k Q	t V n
gun-	d-	ry
gh V n	d @r	i:
gun-	der-	son
gh V n	d @r	s V n
gun-	dog
gh V n	d O: g
gun-	dy
gh V n	d i:
gun-	fi-	re
gh V n	f aI	@r
gun-	figh-	ter
gh V n	f aI	t @r
gun-	figh-	ters
gh V n	f aI	t @r z
gun-	figh-	ter's
gh V n	f aI	t @r z
gun-	figh-	ting
gh V n	f aI	t I N
gun-	fight
gh V n	f aI t
gun-	fights
gh V n	f aI t s
gun-	flint
gh V n	f l I n t
gun-	man
gh V n	m V n
gun-	man's
gh V n	m V n z
gun-	men
gh V n	m e n
gun-	nar
gh V	n @r
gun-	ne-	ry
gh V	n @r	i:
gun-	nels
gh V	n V l z
gun-	ner
gh V	n @r
gun-	ners
gh V	n @r z
gun-	ni-	son
gh V	n I	s V n
gun-	ning
gh V	n I N
gun-	ny
gh V	n i:
gun-	ny-	sack
gh V	n i:	s { k
gun-	ny-	sacks
gh V	n i:	s { k s
gun-	point
gh V n	p OI n t
gun-	pow-	der
gh V n	p aU	d @r
gun-	run-	ner
gh V n	r V	n @r
gun-	ship
gh V n	S I p
gun-	ships
gh V n	S I p s
gun-	shot
gh V n	S Q t
gun-	shots
gh V n	S Q t s
gun-	slin-	ger
gh V n	s l I	N @r
gun-	slin-	gers
gh V n	s l I	N @r z
gun-	ter
gh V n	t @r
gun-	ther
gh V n	T @r
gun-	tur
gh V n	t @r
gung
gh V N
gunn
gh V n
gunned
gh V n d
gunn's
gh V n z
guns
gh V n z
gun's
gh V n z
gup-	pies
gh V	p i: z
gup-	py
gh V	p i:
gup-	ta
gh U p	t V
gur-	g-	ling
gh @r	g V	l I N
gur-	gle
gh @r	g V l
gur-	ley
gh @r	l i:
gur-	nards
gh @r	n @r d z
gur-	nee
gh @r	n i:
gur-	ney
gh @r	n i:
gur-	ney's
gh @r	n i: z
gur-	ry
gh @r	i:
gurr
gh @r
gurt-	ner
gh @r t	n @r
gus
gh V s
gus-	sie
gh V	s i:
gus-	sied
gh V	s i: d
gus-	sy
gh V	s i:
gus-	ta-	ve
gh u: s	t Q	v i:
gus-	ta-	vo
gh V s	t Q	v @U
gus-	taf
gh u: s	t Q f
gus-	taf-	son
gh V s	t V f	s V n
gus-	tafs-	son
gh u: s	t Q f	s V n
gus-	tav
gh U s	t Q f
gus-	ted
gh V s	t V d
gus-	tin
gh V s	t I n
gus-	ting
gh V s	t I N
gus-	to
gh V s	t @U
gus-	ton
gh V s	t V n
gus-	tus
gh V s	t V s
gus-	ty
gh V s	t i:
gush
gh V S
gushed
gh V S t
guss
gh V s
guss-	man
gh V s	m V n
gust
gh V s t
gusts
gh V s t s
gut
gh V t
gut-	less
gh V t	l e s
gut-	sy
gh V t	s i:
gut-	te-	ring
gh V	t @r	I N
gut-	ted
gh V	t V d
gut-	ten-	berg
gh V	t V n	b @r g
gut-	ter
gh V	t @r
gut-	ter-	man
gh V	t @r	m V n
gut-	tered
gh V	t @r d
gut-	ters
gh V	t @r z
gut-	ting
gh V	t I N
gut-	tu-	ral
gh V	t @r	V l
guth-	rie
gh V T	r i:
guth-	rie's
gh V T	r i: z
guts
gh V t s
gutt
gh V t
guy
gh aI
guy-	mon
gh aI	m V n
guy-	ton
gh aI	t V n
guys
gh aI z
guy's
gh aI z
guz-	man
gh V z	m V n
guz-	z-	lers
gh V	z V	l @r z
guz-	z-	ling
gh V	z V	l I N
guz-	zle
gh V	z V l
guz-	zles
gh V	z V l z
guzz-	ler
gh V z	l @r
gwe-	nore
gh w e	n @r
gwen
gh w e n
gwen-	da
gh w e n	d V
gwen-	do-	lyn
gh w e n	d V	l V n
gwen-	nie
gh w e	n i:
gwin
gh w I n
gwin-	ner
gh w I	n @r
gwin-	nett
gh w I	n e t
gwinn
gh w I n
gwyn
gh w I n
gwynn
gh w I n
gwynne
gh w I n
gy-	ne-	co-	lo-	gi-	cal
gh aI	n V	k V	l Q	dZ I	k V l
gy-	ne-	co-	lo-	gic
gh aI	n V	k V	l Q	dZ I k
gy-	ne-	co-	lo-	gist
gh aI	n V	k Q	l V	dZ V s t
gy-	ne-	co-	lo-	gists
gh aI	n V	k Q	l V	dZ V s t s
gy-	ne-	co-	lo-	gy
gh aI	n V	k Q	l V	dZ i:
gy-	ra-	ted
dZ aI	r eI	t V d
gy-	ra-	ting
dZ aI	r eI	t I N
gy-	ra-	tion
dZ aI	r eI	S V n
gy-	ra-	tions
dZ aI	r eI	S V n z
gy-	rate
dZ aI	r eI t
gy-	ro
dZ aI	r @U
gy-	ro-	com-	pass
dZ aI	r @U	k V m	p V s
gy-	ro-	pi-	lot
dZ aI	r @U	p aI	l V t
gy-	ros
dZ aI	r @U z
gy-	ros-	co-	pic
dZ aI	r V s	k Q	p I k
gy-	ros-	cope
dZ aI	r V s	k @U p
gy-	ros-	copes
dZ aI	r V s	k @U p s
gym
dZ I m
gym-	na-	si-	a
dZ I m	n eI	z i:	V
gym-	na-	si-	um
dZ I m	n eI	z i:	V m
gym-	na-	si-	ums
dZ I m	n eI	z i:	V m z
gym-	nas-	tic
dZ I m	n { s	t I k
gym-	nas-	tics
dZ I m	n { s	t I k s
gym-	nast
dZ I m	n V s t
gym-	nasts
dZ I m	n { s t s
gyms
dZ I m z
gym's
dZ I m z
gyn
gh I n
gyp
dZ I p
gyp-	sies
dZ I p	s i: z
gyp-	sum
dZ I p	s V m
gyp-	sum's
dZ I p	s V m z
gyp-	sy
dZ I p	s i:
gypped
dZ I p t
h
eI tS
h-	f-	d-	f
eI	tS e f	d i:	e f
h-	g-	h
eI tS	dZ i:	eI tS
h-	jerpe
h V	dZ @r p
h'-	s
eI	tS V z
h-	ya-	cin-	tha
h aI	V	s I n	T V
h-	ya-	cin-	thi-	a
h aI	V	s I n	T i:	V
h-	ya-	cin-	thie
h aI	V	s I n	T i:
h-	ya-	cinth
h aI	V	s I n T
h-	ya-	cinthe
h aI	V	s I n T
h-	ya-	cinths
h aI	V	s I n T s
h-	ya-	des
h aI	V	d i: z
h-	ya-	lu-	ro-	nic
h aI	V	l @r	Q	n I k
h-	yams
h aI	V m z
h-	yan-	ni-	sport
h aI	{	n I s	p O@ t
h-	yan-	nis
h aI	{	n I s
h-	yatt
h aI	V t
h-	yatt's
h aI	V t s
h.
eI tS
ha
h Q
ha-	be-	as
h {	b i:	V s
ha-	ber
h eI	b @r
ha-	ber-	da-	she-	ry
h {	b @r	d {	S @r	i:
ha-	ber-	man
h eI	b @r	m V n
ha-	bi-	ta-	ble
h {	b I	t V	b V l
ha-	bi-	ta-	tion
h {	b I	t eI	S V n
ha-	bi-	tat
h {	b I	t { t
ha-	bi-	tats
h {	b I	t { t s
ha-	bi-	tat's
h {	b I	t { t s
ha-	bi-	tu-	al
h V	b I	tS u:	V l
ha-	bi-	tu-	al-	ly
h V	b I	tS u:	V	l i:
ha-	bi-	tues
h {	b I	tS u: z
ha-	bib
h V	b i: b
ha-	bit
h {	b I t
ha-	bits
h {	b I t s
ha-	ble
h eI	b V l
ha-	ci-	en-	da
h {	s i:	e n	d V
ha-	da-	way
h Q	d V	w eI
ha-	den
h eI	d V n
ha-	ga-	man
h {	g V	m V n
ha-	gan
h eI	g V n
ha-	gar
h eI	g Q@
ha-	gen
h eI	g V n
ha-	ger
h eI	g @r
ha-	ger-	man
h eI	g @r	m V n
ha-	ger-	stown
h eI	g @r z	t aU n
ha-	gi-	o-	gra-	phy
h {	g i:	Q g	r V	f i:
ha-	good
h {	g U d
ha-	kan
h eI	k V n
ha-	kim
h Q	k i: m
ha-	kim's
h Q	k i: m z
ha-	kon
h {	k V n
ha-	las
h Q	l V z
ha-	ley
h eI	l i:
ha-	ley's
h eI	l i: z
ha-	li-	but
h {	l I	b V t
ha-	li-	fax
h {	l I	f { k s
ha-	li-	ma
h V	l i:	m V
ha-	li-	me-	da
h Q	l i:	m eI	d V
ha-	lide
h {	l aI d
ha-	lite
h {	l aI t
ha-	lo
h eI	l @U
ha-	lo-	ge-	na-	ted
h {	l V	dZ V	n eI	t V d
ha-	lo-	ge-	nate
h {	l V	dZ V	n eI t
ha-	lo-	gen
h {	l V	dZ V n
ha-	lo-	phy-	tic
h {	l V	f I	t I k
ha-	lon
h eI	l Q n
ha-	los
h eI	l @U z
ha-	m-	ler
h {	m V	l @r
ha-	ma
h Q	m V
ha-	ma-	da
h Q	m Q	d V
ha-	mal
h eI	m V l
ha-	man
h eI	m V n
ha-	mann
h Q	m V n
ha-	mas
h Q	m Q s
ha-	mi-	tic
h {	m I	t I k
ha-	mil-	ton
h {	m I l	t V n
ha-	mil-	ton's
h {	m I l	t V n z
ha-	mish
h {	m I S
ha-	mon
h {	m V n
ha-	na
h {	n V
ha-	nan
h eI	n V n
ha-	ney
h eI	n i:
ha-	ni
h {	n i:
ha-	no
h Q	n @U
ha-	no-	ve-	ri-	an
h {	n @U	v I@	i:	V n
ha-	no-	ver
h {	n @U	v @r
ha-	no-	ver's
h {	n @U	v @r z
ha-	noi
h {	n OI
ha-	noi's
h V	n OI z
ha-	nuk-	kahs
h Q	n V	k V z
ha-	nuk-	kah's
h Q	n V	k V z
ha-	nus
h eI	n V s
ha-	ra
h e@	V
ha-	ra-	han
h {	r V	h { n
ha-	ra-	ki-	ri
h Q@	I	k I@	i:
ha-	ra-	re
h @r	Q@	i:
ha-	ral-	son
h {	r V l	s V n
ha-	rald
h Q@	V l d
ha-	rangu-	ing
h @r	{	N I N
ha-	rangue
h @r	{ N
ha-	rangued
h @r	{ N d
ha-	rangues
h @r	{ N z
ha-	ras-	ser
h @r	{	s @r
ha-	ras-	sers
h @r	{	s @r z
ha-	ras-	sing
h @r	{	s I N
ha-	rass
h @r	{ s
ha-	rass-	ment
h @r	{ s	m V n t
ha-	rassed
h @r	{ s t
ha-	rem
h e@	V m
ha-	ri
h Q@	i:
ha-	ring
h e@	I N
ha-	ro
h Q@	@U
ha-	rold
h e@	V l d
ha-	rold-	son
h {	r @U l	d s V n
ha-	rold's
h e@	V l d z
ha-	sn't
h {	z V n t
ha-	ste-	ning
h eI	s V	n I N
ha-	sten
h eI	s V n
ha-	stened
h eI	s V n d
ha-	stens
h eI	s V n z
ha-	ted
h eI	t V d
ha-	ter
h eI	t @r
ha-	ters
h eI	t @r z
ha-	tha-	way
h {	T V	w eI
ha-	tha-	way's
h {	T V	w eI z
ha-	thorne
h {	T @r n
ha-	ting
h eI	t I N
ha-	va-	na
h V	v {	n V
ha-	va-	na's
h V	v {	n V z
ha-	vard
h {	v @r d
ha-	ve-	ner
h {	v i:	n @r
ha-	vel
h {	v V l
ha-	ven
h eI	v V n
ha-	vens
h eI	v V n z
ha-	ven't
h {	v V n t
ha-	ver
h e	v @r
ha-	ver-	ford
h {	v @r	f @r d
ha-	vi-	land
h eI	v i:	l V n d
ha-	vil-	land
h {	v V	l V n d
ha-	ving
h {	v I N
ha-	voc
h {	v V k
ha-	wa-	ii
h V	w aI	i:
ha-	wa-	ii's
h V	w aI	i: z
ha-	waii-	an
h V	w aI	V n
ha-	waii-	ans
h V	w aI	V n z
ha-	wing
h O:	I N
ha-	worth
h {	w @r T
ha-	ya-	shi
h Q	j Q	S i:
ha-	yer
h eI	@r
ha-	zan
h eI	z V n
ha-	zar-	dous
h {	z @r	d V s
ha-	zard
h {	z @r d
ha-	zards
h {	z @r d z
ha-	zel
h eI	z V l
ha-	zel-	nut
h eI	z V l	n V t
ha-	zel-	tine
h eI	z V l	t aI n
ha-	zel-	ton
h eI	z V l	t V n
ha-	zel-	wood
h eI	z V l	w U d
ha-	zel-	wood's
h eI	z V l	w U d z
ha-	zen
h eI	z V n
ha-	zing
h eI	z I N
ha-	zle
h eI	z V l
ha-	zle-	ton
h eI	z V l	t V n
ha-	zy
h eI	z i:
haab
h Q b
haaf
h Q f
haag
h Q g
haak
h Q k
haar
h Q@
haas
h Q s
haase
h Q s
habs-	burg
h { p	s b @r g
hac-	k-	ler
h {	k V	l @r
hac-	kat-	horn
h {	k V	T @r n
hac-	ken-	sack
h {	k V n	s { k
hac-	ker
h {	k @r
hac-	kers
h {	k @r z
hac-	ker's
h {	k @r z
hac-	kett
h {	k e t
hac-	king
h {	k I N
hac-	kle
h {	k V l
hac-	kles
h {	k V l z
hach
h { tS
hack
h { k
hack-	ber-	ry
h { k	b e@	i:
hack-	ma-	tack
h { k	m V	t { k
hack-	man
h { k	m { n
hack-	ney
h { k	n i:
hack-	neyed
h { k	n i: d
hack-	saw
h { k	s O:
hack-	staff
h { k	s t { f
hacked
h { k t
hacks
h { k s
had
h { d
had-	dad
h {	d V d
had-	den
h {	d V n
had-	dock
h {	d V k
had-	don
h {	d V n
hade
h eI d
haen
h i: n
haf-	ni-	a
h { f	n i:	V
haf-	ni-	um
h { f	n i:	V m
haff
h { f
haft
h { f t
hafts
h { f t s
haft's
h { f t s
hag
h { g
hag-	fish
h { g	f I S
hag-	g-	ling
h {	g V	l I N
hag-	ga-	dah
h V	g V	d V
hag-	gar
h {	g @r
hag-	gard
h {	g @r d
hag-	ger-	ty
h {	g @r	t i:
hag-	gle
h {	g V l
hag-	gled
h {	g V l d
hagg
h { g
hagst-	rom
h { g	s t r V m
hague
h eI g
hah
h Q
hahn
h Q n
hahs
h Q s
hai-	dee
h eI	d i:
hai-	fa
h aI	f V
hai-	ku
h aI	k u:
hai-	ley
h eI	l i:
hai-	ling
h eI	l I N
hai-	nan
h eI	n V n
hai-	ri-	ness
h e@	i:	n V s
hai-	ry
h e@	i:
hai-	ti
h eI	t i:
hai-	tian
h eI	S V n
hai-	tians
h eI	S V n z
hai-	ti's
h eI	t i: z
haig
h eI g
haig-	ler
h eI g	l @r
haig's
h eI g z
haik
h eI k
hail
h eI l
hail-	stone
h eI l	s t @U n
hail-	stones
h eI l	s t @U n z
hail-	storm
h eI l	s t O@ m
haile
h eI l
hailed
h eI l d
hailes
h eI l z
hails
h eI l z
haim
h aI m
haimes
h eI m z
hain
h eI n
haines
h eI n z
hains
h eI n z
hair
h e@
hair-	cut
h e@	k V t
hair-	cuts
h e@	k V t s
hair-	do
h e@	d u:
hair-	dos
h e@	d u: z
hair-	dres-	ser
h e@ d	r e	s @r
hair-	dres-	sers
h e@ d	r e	s @r z
hair-	dres-	sing
h e@ d	r e	s I N
hair-	less
h e@	l V s
hair-	line
h e@	l aI n
hair-	spray
h e@ s	p r eI
hair-	style
h e@ s	t aI l
haire
h e@
haired
h e@ d
hairs
h e@ z
hair's
h e@ z
hait
h eI t
haith
h eI T
hajj
h { dZ
hake
h eI k
hakes
h eI k s
hal
h { l
hal-	bert
h { l	b @r t
hal-	bur
h { l	b @r
hal-	ci-	on
h { l	s i:	V n
hal-	cy-	on
h { l	s i:	V n
hal-	cy-	one
h { l	s i:	@U n
hal-	dan
h { l	d V n
hal-	den
h O: l	d V n
hal-	ford
h {	f @r d
hal-	la
h {	l V
hal-	lam
h {	l V m
hal-	lan-	dale
h {	l V n	d eI l
hal-	le-	lu-	jah
h {	l V	l u:	j V
hal-	leck
h {	l I k
hal-	ler
h O:	l @r
hal-	lett
h {	l e t
hal-	ley
h {	l i:
hal-	li-	bur-	ton
h {	l I	b @r	t V n
hal-	li-	day
h {	l I	d eI
hal-	li-	nan
h {	l I	n V n
hal-	lie
h O:	l i:
hal-	ling
h O:	l I N
hal-	lo-	ween
h {	l V	w i: n
hal-	lo-	we'en
h {	l V	w i: n
hal-	lo-	well
h {	l V	w e l
hal-	lock
h {	l V k
hal-	low
h {	l @U
hal-	lowed
h {	l @U d
hal-	lows
h {	l @U z
hal-	lu-	ci-	na-	ted
h V	l u:	s V	n eI	t V d
hal-	lu-	ci-	na-	ting
h V	l u:	s V	n eI	t I N
hal-	lu-	ci-	na-	tion
h V	l u:	s V	n eI	S V n
hal-	lu-	ci-	na-	tions
h V	l u:	s V	n eI	S V n z
hal-	lu-	ci-	na-	to-	ry
h V	l u:	s V	n V	t O@	i:
hal-	lu-	ci-	nate
h V	l u:	s V	n eI t
hal-	lu-	ci-	nates
h V	l u:	s V	n eI t s
hal-	lu-	ci-	no-	ge-	nic
h V	l u:	s V	n V	dZ e	n I k
hal-	ly
h {	l i:
hal-	per
h { l	p @r
hal-	pern
h { l	p @r n
hal-	sey
h { l	s i:
hal-	stead
h { l	s t e d
hal-	sted
h { l	s t V d
hal-	ted
h O: l	t V d
hal-	ter
h O: l	t @r
hal-	ters
h O: l	t @r z
hal-	ting
h O: l	t I N
hal-	ting-	ly
h O: l	t I N	l i:
hal-	tom
h { l	t V m
hal-	ver-	son
h { l	v @r	s V n
hal-	ving
h {	v I N
halde-	man
h Q l	d m V n
halde-	man's
h Q l	d m V n z
hale
h eI l
hales
h eI l z
hale's
h eI l z
half
h { f
half-	a-	cre
h {	f eI	k @r
half-	back
h { f	b { k
half-	dan
h { l	f d V n
half-	hear-	ted
h { f	h Q@	t V d
half-	man
h { f	m V n
half-	time
h { f	t aI m
half-	tone
h { f	t @U n
half-	way
h { f	w eI
half's
h { f s
hall
h O: l
hall-	man
h O: l	m V n
hall-	mark
h Q l	m Q@ k
hall-	marks
h O: l	m Q@ k s
hall-	mark's
h O: l	m Q@ k s
hall-	way
h O: l	w eI
hall-	ways
h O: l	w eI z
hall-	wood
h O: l	w U d
halle
h { l
halls
h O: l z
hall's
h O: l z
halm
h Q m
halm-	stad
h Q l	m s t { d
hal's
h { l z
halt
h O: l t
halts
h O: l t s
halve
h { v
halved
h { v d
halves
h { v z
ham
h { m
ham-	let
h { m	l V t
ham-	lets
h { m	l V t s
ham-	lin
h { m	l I N
ham-	me-	ring
h {	m @r	I N
ham-	mel
h {	m V l
ham-	mer
h {	m @r
ham-	mer-	lock
h {	m @r	l Q k
ham-	mer-	man
h {	m @r	m V n
ham-	mer-	smith
h {	m @r s	m I T
ham-	mer-	stein
h {	m @r s	t i: n
ham-	mer-	stein's
h {	m @r s	t i: n z
ham-	mered
h {	m @r d
ham-	mers
h {	m @r z
ham-	mer's
h {	m @r z
ham-	mett
h {	m e t
ham-	mock
h {	m V k
ham-	mocks
h {	m V k s
ham-	mon
h {	m V n
ham-	mond
h {	m V n d
ham-	ner
h { m	n @r
ham-	pe-	ring
h { m	p @r	I N
ham-	per
h { m	p @r
ham-	pered
h { m	p @r d
ham-	pers
h { m	p @r z
ham-	ster
h { m	s t @r
ham-	sters
h { m	s t @r z
ham-	tra-	mck
h { m	t r {	m I k
hamm
h { m
hamp-	shi-	rites
h { m	p S @r	aI t s
hamp-	shire
h { m	p S @r
hamp-	shire's
h { m	p S @r z
hamp-	stead
h { m	p s t e d
hamp-	ton
h { m	p t V n
hamp-	ton's
h { m	p t V n z
hams
h { m z
hamst-	ring
h { m	s t r I N
hamst-	rings
h { m	s t r I N z
hamst-	rung
h { m	s t r V N
han
h Q n
han-	bu-	ry
h { n	b e@	i:
han-	cock
h { n	k Q k
han-	cock's
h { n	k Q k s
han-	ded
h { n	d V d
han-	ded-	ly
h { n	d V d	l i:
han-	ded-	ness
h { n	d V d	n V s
han-	del
h { n	d V l
han-	del's
h { n	d V l z
han-	der
h { n	d @r
han-	ders
h { n	d @r z
han-	di-	cap
h { n	d i:	k { p
han-	di-	cap-	per
h { n	d i:	k {	p @r
han-	di-	cap-	pers
h { n	d i:	k {	p @r z
han-	di-	cap-	ping
h { n	d i:	k {	p I N
han-	di-	capped
h { n	d i:	k { p t
han-	di-	caps
h { n	d i:	k { p s
han-	di-	craft
h { n	d i: k	r { f t
han-	di-	crafts
h { n	d i: k	r { f t s
han-	di-	er
h { n	d i:	@r
han-	di-	ly
h { n	d I	l i:
han-	di-	work
h { n	d i:	w @r k
han-	ding
h { n	d I N
han-	dle
h { n	d V l
han-	dle-	bar
h { n	d V l	b Q@
han-	dle-	bars
h { n	d V l	b Q@ z
han-	dled
h { n	d V l d
han-	dles
h { n	d V l z
han-	do-	ver
h { n	d @U	v @r
han-	dy
h { n	d i:
han-	dy-	man
h { n	d i:	m { n
han-	dy-	men
h { n	d i:	m e n
han-	ford
h { n	f @r d
han-	gar
h {	N @r
han-	gars
h {	N @r z
han-	ger
h {	N @r
han-	gers
h {	N @r z
han-	ging
h {	N I N
han-	gings
h { N	g I N z
han-	gup
h { N	g V p
han-	gups
h { N	g V p s
han-	ke-	ring
h { N	k @r	I N
han-	kel
h { N	k V l
han-	ker
h { N	k @r
han-	key
h { N	k i:
han-	kin-	son
h { N	k I n	s V n
han-	kins
h { N	k I n z
han-	ky
h { N	k i:
han-	ley
h { n	l i:
han-	ley's
h { n	l i: z
han-	lon
h { n	l V n
han-	na
h {	n V
han-	na-	ford
h {	n V	f @r d
han-	nah
h {	n V
han-	nan
h {	n V n
han-	na's
h {	n V z
han-	nay
h {	n eI
han-	ni
h {	n i:
han-	ni-	bal
h {	n I	b V l
han-	nie
h {	n i:
han-	nis
h {	n I s
han-	non
h {	n V n
han-	ny
h {	n i:
han-	rat-	ty
h { n	r V	t i:
han-	sa
h { n	s V
han-	sard
h { n	s @r d
han-	se-	a-	tic
h { n	s i:	{	t I k
han-	sel
h { n	s V l
han-	sell
h { n	s V l
han-	sen
h { n	s V n
han-	sen's
h { n	s V n z
han-	ser
h Q n	s @r
han-	shaw
h { n	S O:
han-	som
h { n	s V m
han-	son
h { n	s V n
han-	son's
h { n	s V n z
han-	ta-	vi-	rus
h { n	t V	v aI	r V s
han-	uk-	kah
h Q	n V	k V
han-	way
h { n	w eI
hance
h { n s
hand
h { n d
hand-	bag
h { n	d b { g
hand-	bags
h { n	d b { g z
hand-	ball
h { n	d b O: l
hand-	bill
h { n	d b I l
hand-	bills
h { n	d b I l z
hand-	book
h { n	d b U k
hand-	books
h { n	d b U k s
hand-	clasp
h { n	d k l { s p
hand-	craf-	ted
h { n	d k r { f	t V d
hand-	craft
h { n	d k r { f t
hand-	crafts
h { n	d k r { f t s
hand-	cuff
h { n	d k V f
hand-	cuffed
h { n	d k V f t
hand-	cuffs
h { n	d k V f s
hand-	ful
h { n	d f U l
hand-	fuls
h { n	d f U l z
hand-	gun
h { n	d g V n
hand-	guns
h { n	d g V n z
hand-	held
h { n	d h e l d
hand-	hol-	ding
h { n	d h @U l	d I N
hand-	hold
h { n	d h @U l d
)"
R"(hand-	ker-	chief
h { N	k @r	tS I f
hand-	ker-	chiefs
h { N	k @r	tS I f s
hand-	ler
h { n	d l @r
hand-	lers
h { n	d l @r z
hand-	ley
h { n	d l i:
hand-	ling
h { n	d l I N
hand-	loom
h { n	d l u: m
hand-	looms
h { n	d l u: m z
hand-	made
h { n	d m eI d
hand-	out
h { n	d aU t
hand-	outs
h { n	d aU t s
hand-	pick
h { n	d p I k
hand-	picked
h { n	d p I k t
hand-	rail
h { n	d r eI l
hand-	saw
h { n	d s O:
hand-	set
h { n	d s e t
hand-	sets
h { n	d s e t s
hand-	sha-	king
h { n	d S eI	k I N
hand-	shake
h { n	d S eI k
hand-	shakes
h { n	d S eI k s
hand-	some
h { n	s V m
hand-	some-	ly
h { n	s V m	l i:
hand-	stand
h { n	d s t { n d
hand-	stands
h { n	d s t { n d z
hand-	wo-	ven
h { n	d w @U	v V n
hand-	wri-	ting
h { n	d r aI	t I N
hand-	writ-	ten
h { n	d r I	t V n
hands
h { n d z
hang
h { N
hang-	man
h { N	m V n
hang-	o-	ver
h {	N @U	v @r
hang-	o-	vers
h {	N @U	v @r z
hang-	out
h {	N aU t
hang-	outs
h {	N aU t s
hang-	up
h { N	g V p
hanged
h { N d
hangs
h { N z
hank
h { N k
hanks
h { N k s
hank's
h { n k s
hans
h Q n s
han's
h Q n z
hans-	ber-	ry
h { n	s b e@	i:
hans-	ford
h { n	s f @r d
hao
h aU
hap
h { p
hap-	good
h { p	g U d
hap-	ha-	zard
h { p	h {	z @r d
hap-	ha-	zard-	ly
h { p	h {	z @r d	l i:
hap-	less
h { p	l V s
hap-	loid
h { p	l OI d
hap-	pe-	ning
h {	p V	n I N
hap-	pe-	nings
h {	p V	n I N z
hap-	pen
h {	p V n
hap-	pen-	stance
h {	p V n	s t { n s
hap-	pened
h {	p V n d
hap-	pens
h {	p V n z
hap-	pi-	er
h {	p i:	@r
hap-	pi-	est
h {	p i:	V s t
hap-	pi-	ly
h {	p I	l i:
hap-	pi-	ness
h {	p i:	n V s
hap-	py
h {	p i:
happ
h { p
haps-	burg
h { p	s b @r g
haq
h { k
har-	be-	son
h Q@	b V	s V n
har-	bert
h Q@	b @r t
har-	bi-	son
h Q@	b I	s V n
har-	bin
h Q@	b I n
har-	bin-	ger
h Q@	b I n	dZ @r
har-	bin-	gers
h Q@	b I n	dZ @r z
har-	bo-	ring
h Q@	b @r	I N
har-	bor
h Q@	b @r
har-	bor-	side
h Q@	b @r	s aI d
har-	bored
h Q@	b @r d
har-	bors
h Q@	b @r z
har-	bor's
h Q@	b @r z
har-	bour
h Q@	b @r
har-	court
h Q@	k O@ t
har-	court's
h Q@	k @r t s
har-	da-	way
h Q@	d V	w eI
har-	de-	ner
h Q@	d V	n @r
har-	de-	ning
h Q@	d V	n I N
har-	den
h Q@	d V n
har-	dened
h Q@	d V n d
har-	dens
h Q@	d V n z
har-	den's
h Q@	d V n z
har-	der
h Q@	d @r
har-	des-	ty
h Q@	d V s	t i:
har-	dest
h Q@	d V s t
har-	di-	er
h Q@	d i:	@r
har-	die
h Q@	d i:
har-	din
h Q@	d I n
har-	ding
h Q@	d I N
har-	ding's
h Q@	d I N s
har-	dy
h Q@	d i:
har-	dy's
h Q@	d i: z
har-	ford
h Q@	f @r d
har-	greaves
h Q@ g	r i: v z
har-	ken
h Q@	k V n
har-	king
h Q@	k I N
har-	kins
h Q@	k I n z
har-	lan
h Q@	l V n
har-	land
h Q@	l V n d
har-	le
h Q@	V l
har-	le-	quin
h Q@	l V k	w V n
har-	lem
h Q@	l V m
har-	lem's
h Q@	l V m z
har-	ley
h Q@	l i:
har-	ley's
h Q@	l i: z
har-	leys-	ville
h Q@	l i: z	v I l
har-	lin
h Q@	l I n
har-	lin-	gen
h Q@	l I	N V n
har-	ling
h Q@	l I N
har-	lin's
h Q@	l I n z
har-	lot
h Q@	l V t
har-	low
h Q@	l @U
har-	man
h Q@	m V n
har-	mat-	tan
h Q@	m V	t { n
har-	mel
h Q@	m V l
har-	mer
h Q@	m @r
har-	ming
h Q@	m I N
har-	mo-	ni-	a
h Q@	m @U	n i:	V
har-	mo-	ni-	ca
h Q@	m Q	n I	k V
har-	mo-	ni-	ous
h Q@	m @U	n i:	V s
har-	mo-	ni-	ous-	ly
h Q@	m @U	n i:	V s	l i:
har-	mo-	ni-	um
h Q@	m @U	n i:	V m
har-	mo-	ni-	za-	tion
h Q@	m V	n V	z eI	S V n
har-	mo-	ni-	zing
h Q@	m V	n aI	z I N
har-	mo-	nic
h Q@	m Q	n I k
har-	mo-	nics
h Q@	m Q	n I k s
har-	mo-	nie
h Q@	m V	n i:
har-	mo-	nies
h Q@	m V	n i: z
har-	mo-	nize
h Q@	m V	n aI z
har-	mo-	nized
h Q@	m V	n aI z d
har-	mo-	ny
h Q@	m V	n i:
har-	mon
h Q@	m V n
har-	mon's
h Q@	m V n z
har-	nack
h Q@	n V k
har-	nes-	ses
h Q@	n V	s V z
har-	nes-	sing
h Q@	n V	s I N
har-	ness
h Q@	n V s
har-	nessed
h Q@	n V s t
har-	nett
h Q@	n e t
har-	ney
h Q@	n i:
har-	per
h Q@	p @r
har-	pers
h Q@	p @r z
har-	per's
h Q@	p @r z
har-	pin
h Q@	p { n
har-	ping
h Q@	p I N
har-	pist
h Q@	p I s t
har-	pists
h Q@	p I s t s
har-	po
h Q@	p @U
har-	pole
h Q@	p @U l
har-	poon
h Q@	p u: n
har-	poons
h Q@	p u: n z
har-	que-	bus
h Q@ k	w V	b V s
har-	rah
h {	r V
har-	rah's
h e@	V z
har-	rell
h e@	V l
har-	rell's
h {	r V l z
har-	ri-	er
h e@	i:	@r
har-	ri-	et
h e@	i:	V t
har-	ri-	ette
h {	r i:	e t
har-	ri-	man
h e@	I	m V n
har-	ri-	ott
h {	r i:	V t
har-	ri-	son
h e@	I	s V n
har-	ri-	son's
h e@	I	s V n z
har-	ried
h e@	i: d
har-	ries
h e@	i: z
har-	ring-	ton
h e@	I N	t V n
har-	ris
h e@	I s
har-	ris-	burg
h {	r I s	b @r g
har-	ris-	burg's
h {	r I s	b @r g z
har-	ro-	wer
h {	r @U	w @r
har-	ro-	wing
h e@	@U	I N
har-	rod
h e@	V d
har-	rods
h e@	V d z
har-	rod's
h e@	V d z
har-	rold
h e@	V l d
har-	row
h {	r @U
har-	ry
h e@	i:
har-	ry's
h e@	i: z
har-	shaw
h Q@	S O:
har-	sher
h Q@	S @r
har-	shest
h Q@	S V s t
har-	ten
h Q@	t V n
har-	tin
h Q@	t I n
har-	ty
h Q@	t i:
har-	vard
h Q@	v @r d
har-	vard's
h Q@	v @r d z
har-	vel
h Q@	v V l
har-	ves-	ta-	ble
h Q@	v V s	t V	b V l
har-	ves-	ted
h Q@	v V s	t V d
har-	ves-	ter
h Q@	v V s	t @r
har-	ves-	ters
h Q@	v V s	t @r z
har-	ves-	ting
h Q@	v V s	t I N
har-	vest
h Q@	v V s t
har-	vests
h Q@	v V s t s
har-	vey
h Q@	v i:
harb
h Q@ b
hard
h Q@ d
hard-	back
h Q@ d	b { k
hard-	ball
h Q@ d	b O: l
hard-	board
h Q@ d	b O@ d
hard-	co-	ver
h Q@ d	k V	v @r
hard-	core
h Q@ d	k O@
hard-	goods
h Q@ d	g U d z
hard-	hea-	ded
h Q@ d	h e	d V d
hard-	head
h Q@ d	h e d
hard-	li-	ner
h Q@ d	l aI	n @r
hard-	li-	ners
h Q@ d	l aI	n @r z
hard-	line
h Q@ d	l aI n
hard-	ly
h Q@ d	l i:
hard-	man
h Q@ d	m V n
hard-	ness
h Q@ d	n V s
hard-	pressed
h Q@ d	p r e s t
hard-	scrab-	ble
h Q@ d	s k r {	b V l
hard-	ship
h Q@ d	S I p
hard-	ships
h Q@ d	S I p s
hard-	ware
h Q@ d	w e@
hard-	way
h Q@ d	w eI
hard-	wick
h Q@ d	w I k
hard-	wicke
h Q@ d	w I k
hard-	wood
h Q@ d	w U d
hard-	woods
h Q@ d	w U d z
hard-	wor-	king
h Q@ d	w @r	k I N
hards
h Q@ d z
hare
h e@
hare-	brained
h e@ b	r eI n d
hare-	wood
h e@	w U d
hares
h e@ z
hare's
h e@ z
hark
h Q@ k
hark-	ness
h Q@ k	n V s
harks
h Q@ k s
harl
h Q@ l
harm
h Q@ m
harm-	ful
h Q@ m	f V l
harm-	ful-	ness
h Q@ m	f V l	n V s
harm-	less
h Q@ m	l V s
harm-	less-	ly
h Q@ m	l V s	l i:
harmed
h Q@ m d
harms
h Q@ m z
harm's
h Q@ m z
harn
h Q@ n
harned
h Q@ n d
harp
h Q@ p
harp-	si-	chord
h Q@ p	s I	k O@ d
harped
h Q@ p t
harps
h Q@ p s
harps-	ter
h Q@ p	s t @r
harr
h { r
harre
h { r
hars-	tad
h Q@ s	t V d
harsh
h Q@ S
harsh-	ly
h Q@ S	l i:
harsh-	man
h Q@ S	m V n
harsh-	ness
h Q@ S	n V s
hart
h Q@ t
hart-	field
h Q@ t	f i: l d
hart-	ford
h Q@ t	f @r d
hart-	ford's
h Q@ t	f @r d z
hart-	ke
h Q@ t	k i:
hart-	land
h Q@ t	l V n d
hart-	ley
h Q@ t	l i:
hart-	line
h Q@ t	l aI n
hart-	man
h Q@ t	m V n
hart-	mann
h Q@ t	m V n
hart-	nell
h Q@ t	n V l
hart-	nett
h Q@ t	n e t
hart-	shorne
h Q@	tS @r n
hart-	well
h Q@ t	w e l
hart-	wick
h Q@ t	w I k
hart-	wood
h Q@ t	w U d
hart-	zel
h Q@ t	z V l
hart-	zell
h Q@ t	z V l
harte
h Q@ t
harts
h Q@ t s
hart's
h Q@ t s
harts-	field
h Q@ t	s f i: l d
harts-	horn
h Q@ t	s h O@ n
harts-	ville
h Q@ t	s v I l
harv
h Q@ v
harve
h Q@ v
has-	kell
h { s	k V l
has-	kins
h { s	k I n z
has-	lam
h { s	l V m
has-	lett
h { s	l e t
has-	s-	ling
h {	s V	l I N
has-	san
h V	s Q n
has-	sel
h {	s V l
has-	sell
h {	s V l
has-	sett
h {	s e t
has-	sing
h {	s I N
has-	sle
h {	s V l
has-	sled
h {	s V l d
has-	sles
h {	s V l z
has-	ta
h { s	t V
has-	ti-	ly
h eI s	t I	l i:
has-	tie
h eI s	t i:
has-	ting
h eI s	t I N
has-	tings
h eI s	t I N z
has-	ty
h eI s	t i:
has-	well
h { s	w e l
hass-	ler
h { s	l @r
hasse
h Q s
hast
h { s t
haste
h eI s t
hat
h { t
hat-	che-	ries
h {	tS @r	i: z
hat-	che-	ry
h {	tS @r	i:
hat-	chel
h {	tS V l
hat-	cher
h {	tS @r
hat-	ches
h {	tS V z
hat-	chet
h {	tS V t
hat-	chets
h {	tS V t s
hat-	ching
h {	tS I N
hat-	ch's
h {	tS V z
hat-	field
h { t	f i: l d
hat-	field's
h { t	f i: l d z
hat-	ley
h { t	l i:
hat-	ma-	ker
h { t	m eI	k @r
hat-	red
h eI t	r V d
hat-	reds
h eI t	r V d z
hat-	te-	ras
h {	t @r	V s
hat-	te-	ry
h {	t @r	i:
hat-	ter
h {	t @r
hat-	ters-	ley
h {	t @r z	l i:
hat-	tie
h {	t i:
hat-	ton
h {	t V n
hat-	tu-	sas
h V	t u:	s V s
hat-	ty
h {	t i:
hatch
h { tS
hatch-	back
h { tS	b { k
hatched
h { tS t
hate
h eI t
hate-	ful
h eI t	f V l
hates
h eI t s
hath
h { T
hath-	cock
h { T	k V k
hats
h { t s
hat's
h { t s
hatt
h { t
hau
h aU
hau-	gen
h aU	g V n
hau-	ger
h aU	g @r
hau-	ghey
h O:	k i:
hau-	ler
h O:	l @r
hau-	lers
h O:	l @r z
hau-	ling
h O:	l I N
hau-	sa
h aU	s V
hau-	sen
h aU	z V n
hau-	ser
h aU	z @r
hauck
h O: k
hauge
h O: dZ
haugh
h O:
haugh-	ti-	ly
h O:	t I	l i:
haugh-	ton
h O:	t V n
haugh-	ty
h O:	t i:
haught
h O: t
haul
h O: l
hauled
h O: l d
hauls
h O: l z
haun-	ted
h O:	n V d
haun-	ting
h O: n	t I N
haun-	ting-	ly
h O: n	t I N	l i:
haunt
h O: n t
haunts
h O: n t s
haup-	pauge
h aU	p O: dZ
haupt-	mann
h aU p	t m V n
haus-	mann
h aU s	m V n
haus-	ner
h aU s	n @r
hause
h aU s
hauss-	mann
h aU s	m V n
haut
h O: t
haute
h @U t
have
h { v
have-	lock
h { v	l Q k
have-	man
h eI v	m V n
haves
h { v z
haw
h O:
haw-	ken
h O:	k V n
haw-	ker
h O:	k @r
haw-	kers
h O:	k @r z
haw-	key
h O:	k i:
haw-	keye
h O:	k aI
haw-	keye's
h O:	k aI z
haw-	king
h O:	k I N
haw-	kins
h O:	k I n z
haw-	kish
h O:	k I S
haw-	ley
h O:	l i:
haw-	ley's
h O:	l i: z
haw-	thorn
h O:	T O@ n
haw-	thorne
h O:	T O@ n
haw-	thorns
h O:	T O@ n z
hawes
h O: z
hawk
h O: k
hawk-	bill
h O: k	b I l
hawk-	bill's
h O: k	b I l z
hawke
h O: k
hawked
h O: k t
hawke's
h O: k s
hawks
h O: k s
haws
h O: z
hay
h eI
hay-	cock
h eI	k Q k
hay-	den
h eI	d V n
hay-	dn
h aI	d V n
hay-	dn's
h aI	d V n z
hay-	don
h eI	d V n
hay-	field
h eI	f i: l d
hay-	fields
h eI	f i: l d z
hay-	ing
h eI	I N
hay-	ley
h eI	l i:
hay-	loft
h eI	l O: f t
hay-	ma-	ker
h eI	m eI	k @r
hay-	man
h eI	m V n
hay-	mar-	ket
h eI	m Q@	k e t
hay-	ton
h eI	t V n
hay-	ward
h eI	w @r d
hay-	ward's
h eI	w @r d z
hay-	wire
h eI	w aI r
hay-	wood
h eI	w U d
hay-	worth
h eI	w @r T
haye
h eI
hayes
h eI z
hayles
h eI l z
haymes
h eI m z
hayne
h eI n
haynes
h eI n z
hays
h eI z
hays-	tack
h eI s	t { k
hayse
h eI z
haz-	lett
h { z	l e t
haze
h eI z
he
h i:
he-	bel
h e	b V l
he-	ber
h i:	b @r
he-	bert
h e	b @r t
he-	bri-	des
h e b	r I	d i: z
he-	cu-	ba
h e k	j V	b V
he-	do-	ni-	sm
h i:	d V	n I	z V m
he-	do-	nis-	tic
h i:	d V	n I s	t I k
he-	dy
h i:	d i:
he-	er
h i:	@r
he-	gar-	ty
h e	g Q@	t i:
he-	ge-	li-	an
h i:	dZ i:	l i:	V n
he-	ge-	mo-	nic
h e	g V	m Q	n I k
he-	ge-	mo-	ny
h i:	dZ e	m V	n i:
he-	gel
h e	g V l
he-	ger
h i:	g @r
he-	le-	na
h e	l V	n V
he-	le-	na's
h e	l V	n V z
he-	len
h e	l V n
he-	lens
h e	l V n z
he-	len's
h e	l V n z
he-	li-	cal
h e	l I	k V l
he-	li-	con
h e	l I	k Q n
he-	li-	cons
h e	l I	k Q n z
he-	li-	cop-	ter
h e	l I	k Q p	t @r
he-	li-	cop-	ters
h e	l I	k Q p	t @r z
he-	li-	cop-	ter's
h e	l I	k Q p	t @r z
he-	li-	o-	po-	lis
h i:	l i:	Q	p V	l V s
he-	li-	o-	trope
h i:	l i:	V t	r @U p
he-	li-	os
h i:	l i:	Q s
he-	li-	um
h i:	l i:	V m
he-	lice
h e	l I s
he-	ling
h i:	l I N
he-	lix
h i:	l I k s
he-	lo-	ti-	sm
h e	l V	t I	z V m
he-	lot
h e	l V t
he-	lot-	ry
h e	l V t	r i:
he-	lots
h e	l V t s
he-	ma-	tite
h e	m V	t aI t
he-	ma-	to-	lo-	gy
h e	m V	t Q	l I	dZ i:
he-	man
h i:	m V n
he-	mel
h e	m V l
he-	mi-	mor-	phite
h e	m I	m O@	f aI t
he-	mi-	ple-	gi-	a
h e	m I p	l i:	dZ i:	V
he-	ming-	way
h e	m I N	w eI
he-	ming-	way's
h e	m I N	w eI z
he-	mis-	phe-	ric
h e	m I s	f I@	I k
he-	mis-	phere
h e	m I s	f I@
he-	mo-	c-	ya-	nin
h i:	m V	s aI	V	n V n
he-	mo-	dy-	na-	mic
h e	m @U	d aI	n {	m I k
he-	mo-	dy-	na-	mics
h e	m @U	d aI	n {	m I k s
he-	mo-	glo-	bin
h i:	m V g	l @U	b V n
he-	mo-	ly-	tic
h i:	m V	l I	t I k
he-	mo-	phi-	li-	a
h i:	m V	f i:	l i:	V
he-	mo-	phi-	li-	ac
h i:	m V	f I	l i:	{ k
he-	mo-	phi-	li-	acs
h i:	m V	f I	l i:	{ k s
he-	mor-	rha-	gic
h e	m @r	{	g I k
he-	mor-	rha-	ging
h e	m @r	I	dZ I N
he-	mor-	rhage
h e	m @r	I dZ
he-	mor-	rhaged
h e	m @r	I dZ d
he-	morr-	hoid
h e	m @r	OI d
he-	morr-	hoids
h e	m @r	OI d z
he-	n-	rie
h e	n @r	i:
he-	nie
h e	n i:
he-	nle
h e	n V l
he-	pa-	rin
h e	p @r	I n
he-	pa-	ti-	tis
h e	p V	t aI	t V s
he-	pa-	tic
h V	p {	t I k
he-	ra
h I@	V
he-	ral-	ded
h e@	V l	d V d
he-	ral-	dic
h e@	{ l	d I k
he-	ral-	ding
h e@	V l	d I N
he-	rald
h e@	V l d
he-	rald-	ry
h e@	V l	d r i:
he-	ralds
h e@	V l d z
he-	rald's
h e@	V l d z
he-	re-	di-	a
h @r	e	d i:	V
he-	re-	di-	ta-	ry
h @r	e	d I	t e@	i:
he-	re-	di-	ty
h @r	e	d I	t i:
he-	re-	ford
h e@	V	f @r d
he-	re-	sy
h e@	V	s i:
he-	re-	ti-	cal
h @r	e	t I	k V l
he-	re-	tic
h e@	V	t I k
he-	rein
h I@	I n
he-	ri-	ta-	ble
h e@	I	t V	b V l
he-	ri-	ta-	ges
h e@	I	t I	dZ V z
he-	ri-	ta-	ge's
h e@	I	t I	dZ V z
he-	ri-	tage
h e@	I	t V dZ
he-	rin-	ger
h e@	I n	dZ @r
he-	ring
h @r	I N
he-	ring-	ton
h e@	I N	t V n
he-	ro
h I@	@U
he-	ro-	i-	sm
h e@	@U	I	z V m
he-	ro-	ic
h I@	@U	I k
he-	ro-	ical-	ly
h I@	@U	I k	l i:
he-	ro-	ics
h I@	@U	I k s
he-	ro-	in
h e@	@U	I n
he-	ro-	ine
h e@	@U	I n
he-	ro-	ines
h e@	@U	I n z
he-	ro-	in's
h e@	@U	I n z
he-	ro-	ize
h i:	r @U	aI z
he-	ro-	ized
h i:	r @U	aI z d
he-	rod
h e@	V d
he-	roes
h I@	@U z
he-	rold
h e@	V l d
he-	ron
h e@	V n
he-	rons
h e@	V n z
he-	ron's
h e@	V n z
he-	ros
h I@	@U z
he-	ro's
h I@	@U z
he-	s-	ler
h e	s V	l @r
he-	sel-	tine
h e	s V l	t i: n
he-	si-	od
h i:	s i:	V d
he-	si-	ta-	ted
h e	z I	t eI	t V d
he-	si-	ta-	ting
h e	z I	t eI	t I N
he-	si-	ta-	tion
h e	z I	t eI	S V n
he-	si-	ta-	tions
h e	z I	t eI	S V n z
he-	si-	tan-	cy
h e	z I	t V n	s i:
he-	si-	tant
h e	z I	t V n t
he-	si-	tant-	ly
h e	z I	t V n	t l i:
he-	si-	tate
h e	z I	t eI t
he-	si-	tates
h e	z I	t eI t s
he-	te-	ro-	cer-	cal
h e	t @r	@U	s @r	k V l
he-	te-	ro-	do-	xy
h e	t @r	V	d Q k	s i:
he-	te-	ro-	dox
h e	t @r	V	d Q k s
he-	te-	ro-	dyne
h e	t @r	V	d aI n
he-	te-	ro-	ge-	ne-	i-	ty
h e	t @r	V	dZ V	n eI	V	t i:
he-	te-	ro-	ge-	neous
h e	t @r	V	dZ i: n	j V s
he-	te-	ro-	se-	xu-	a-	li-	ty
h e	t @r	@U	s e k	S V	w {	l V	t i:
he-	te-	ro-	se-	xu-	al
h e	t @r	@U	s e k	S V	w V l
he-	te-	ro-	se-	xu-	als
h e	t @r	@U	s e k	S V	w V l z
he-	te-	ro-	sis
h e	t @r	@U	s I s
he-	te-	ro-	tro-	phic
h e	t @r	V t	r Q	f I k
he-	te-	ros-	po-	rous
h e	t @r	Q s	p @r	V s
he-	wer
h j u:	@r
he-	wett
h j u:	e t
he-	wing
h j u:	I N
he-	witt
h j u:	I t
he-	witt's
h j u:	I t s
he-	xa-	go-	nal
h e k	s {	g V	n V l
he-	xa-	gon
h e k	s V	g Q n
he-	xach-	lo-	ro-	phene
h e k	s V k	l O@	V	f i: n
he-	yer
h eI	@r
hea-	dache
h e	d eI k
hea-	daches
h e	d eI k s
hea-	ded
h e	d V d
hea-	der
h e	d @r
hea-	ding
h e	d I N
hea-	dings
h e	d I N z
hea-	dy
h e	d i:
hea-	ler
h i:	l @r
hea-	lers
h i:	l @r z
hea-	ley
h i:	l i:
hea-	ling
h i:	l I N
hea-	ly
h i:	l i:
hea-	ly's
h i:	l i: z
hea-	ney
h i:	n i:
hea-	ping
h i:	p I N
hea-	rer
h I@	@r
hea-	rers
h I@	@r z
hea-	ring
h I@	I N
hea-	rings
h I@	I N z
hea-	ring's
h I@	I N z
hea-	ted
h i:	t V d
hea-	ted-	ly
h i:	t V d	l i:
hea-	ter
h i:	t @r
hea-	ters
h i:	t @r z
hea-	then
h i:	D V n
hea-	ther
h e	D @r
hea-	thers
h e	D @r z
hea-	ther's
h e	D @r z
hea-	ting
h i:	t I N
hea-	ton
h i:	t V n
hea-	ve-	ner
h e	v V	n @r
hea-	ven
h e	v V n
hea-	ven-	ly
h e	v V n	l i:
hea-	vens
h e	v V n z
hea-	ven's
h e	v V n z
hea-	vi-	er
h e	v i:	@r
hea-	vi-	est
h e	v i:	V s t
hea-	vi-	ly
h e	v I	l i:
hea-	vies
h e	v i: z
hea-	ving
h i:	v I N
hea-	vy
h e	v i:
hea-	vy-	han-	ded
h e	v i:	h { n	d V d
hea-	vy-	set
h e	v i:	s e t
hea-	vy-	weight
h e	v i:	w eI t
hea-	vy-	weights
h e	v i:	w eI t s
head
h e d
head-	band
h e d	b { n d
head-	bands
h e d	b { n d z
head-	board
h e d	b O@ d
head-	cheese
h e d	tS i: z
head-	count
h e d	k aU n t
head-	dres-	ses
h e d	d r e	s V z
head-	dress
h e d	r e s
head-	first
h e d	f @r s t
head-	gear
h e d	g I@
head-	hun-	ter
h e d	h V n	t @r
head-	hun-	ters
h e d	h V n	t @r z
head-	less
h e d	l V s
head-	li-	ner
h e d	l aI	n @r
head-	li-	ning
h e d	l aI	n I N
head-	light
h e d	l aI t
head-	lights
h e d	l aI t s
head-	line
h e d	l aI n
head-	lined
h e d	l aI n d
head-	lines
h e d	l aI n z
head-	long
h e d	l O: N
head-	man
h e d	m V n
head-	mas-	ter
h e d	m { s	t @r
head-	mist-	ress
h e d	m I s	t r V s
head-	phone
h e d	f @U n
head-	phones
h e d	f @U n z
head-	quar-	ter
h e d	k w O@	t @r
head-	quar-	tered
h e d	k O@	t @r d
head-	quar-	ters
h e d	k w O@	t @r z
head-	rest
h e d	r e s t
head-	rests
h e d	r e s t s
head-	rick
h e d	r I k
head-	room
h e d	r u: m
head-	set
h e d	s e t
head-	sets
h e d	s e t s
head-	ship
h e d	S I p
head-	start
h e d	s t Q@ t
)"
R"(head-	stone
h e d	s t @U n
head-	stones
h e d	s t @U n z
head-	strong
h e d	s t r O: N
head-	wa-	ter
h e d	w O:	t @r
head-	wa-	ters
h e d	w O:	t @r z
head-	way
h e d	w eI
head-	wind
h e d	w I n d
heads
h e d z
head's
h e d z
heads-	man
h e d	z m V n
heal
h i: l
heal-	thi-	er
h e l	T i:	@r
heal-	thi-	est
h e l	T i:	V s t
heal-	thy
h e l	T i:
heald
h i: l d
healed
h i: l d
heals
h i: l z
health
h e l T
health-	care
h e l	T k e@
health-	ful
h e l	T f V l
health's
h e l T s
heap
h i: p
heaped
h i: p t
heaps
h i: p s
hear
h I@
hear-	say
h I@	s eI
hear-	tache
h Q@	t eI k
hear-	te-	ning
h Q@	t V	n I N
hear-	ted
h Q@	t V d
hear-	ted-	ly
h Q@	t V d	l i:
hear-	ten
h Q@	t V n
hear-	tened
h Q@	t V n d
hear-	ti-	ly
h Q@	t V	l i:
hear-	ty
h Q@	t i:
heard
h @r d
hearn
h @r n
hearne
h @r n
hears
h I@ z
hearse
h @r s
hearst
h @r s t
hearst's
h @r s t s
heart
h Q@ t
heart-	beat
h Q@ t	b i: t
heart-	beats
h Q@ t	b i: t s
heart-	brea-	king
h Q@ t	b r eI	k I N
heart-	break
h Q@ t	b r eI k
heart-	bro-	ken
h Q@ t	b r @U	k V n
heart-	burn
h Q@ t	b @r n
heart-	felt
h Q@ t	f e l t
heart-	land
h Q@ t	l { n d
heart-	less
h Q@ t	l V s
heart-	throb
h Q@ t	T r Q b
heart-	war-	ming
h Q@ t	w O@	m I N
heart-	wise
h Q@ t	w aI z
heart-	wood
h Q@ t	w U d
hearth
h Q@ T
hearths
h Q@ T s
hearts
h Q@ t s
heart's
h Q@ t s
heat
h i: t
heath
h i: T
heath-	cock
h e T	k V k
heath-	cote
h e T	k V t
heath-	man
h i: T	m V n
heath-	row
h i: T	r @U
heath's
h i: T s
heats
h i: t s
heat's
h i: t s
heave
h i: v
heaved
h i: v d
heaves
h i: v z
heb-	ner
h e b	n @r
heb-	rew
h i: b	r u:
heb-	ron
h e b	r V n
hebe
h i: b
hec-	co
h e	k @U
hec-	ker
h e	k @r
hec-	kle
h e	k V l
hec-	kled
h e	k V l d
hec-	ku-	va
h e k	j u:	v V
hec-	la
h e k	l V
hec-	la's
h e k	l V z
hec-	tare
h e k	t Q@
hec-	tares
h e k	t Q@ z
hec-	tic
h e k	t I k
hec-	to-	graph
h e k	t V g	r { f
hec-	to-	ring
h e k	t @r	I N
hec-	tor
h e k	t @r
hec-	tor's
h e k	t @r z
hecht
h e k t
hecht's
h e k t s
heck
h e k
heck-	ler
h e k	l @r
heck-	lers
h e k	l @r z
heck-	ling
h e k	l I N
heck-	man
h e k	m V n
heck's
h e k s
he'd
h i: d
hed-	rick
h e d	r I k
hed-	wi-	ga
h e d	w I	g V
hed-	wig
h e d	w I g
hee
h i:
hee-	ded
h i:	d V d
hee-	ding
h i:	d I N
hee-	nan
h i:	n V n
heed
h i: d
heeds
h i: d z
heel
h i: l
heeled
h i: l d
heels
h i: l z
hef-	lin
h e f	l I n
hef-	ner
h e f	n @r
hef-	ner's
h e f	n @r z
hef-	ter
h e f	t @r
hef-	ti-	er
h e f	t i:	@r
hef-	ti-	est
h e f	t i:	V s t
hef-	ty
h e f	t i:
heff-	ron
h e f	r V n
heft
h e f t
hege
h i: dZ
heh
h e
hei-	del-	berg
h aI	d V l	b @r g
hei-	di
h aI	d i:
hei-	di's
h aI	d i: s
hei-	drick
h aI d	r I k
hei-	fer
h aI	f @r
hei-	fers
h aI	f @r z
hei-	fetz
h aI	f I t s
hei-	gl
h aI	g V l
hei-	mer
h aI	m @r
hei-	ne-	ken
h aI	n V	k V n
hei-	ner
h aI	n @r
hei-	ney
h aI	n i:
hei-	nous
h eI	n V s
hei-	ress
e@	V s
hei-	sel
h aI	s V l
hei-	ser
h aI	s @r
heid
h aI d
heide
h aI d
heidt
h aI d t
heigh-	ten
h aI	t V n
heigh-	ten-	ing
h aI	t V	n I N
heigh-	tened
h aI	t V n d
heigh-	tens
h aI	t V n z
height
h aI t
heighth
h aI T
heights
h aI t s
heil
h aI l
heil-	man
h aI l	m V n
heim
h aI m
heim-	lich
h aI m	l I k
hein
h aI n
hein-	kel
h aI N	k V l
hein-	lein
h aI n	l aI n
hein-	rich
h aI n	r I k
heine
h aI n
heins
h aI n z
heintz
h aI n t s
heinz
h aI n z
heinze
h aI n z
heir
e@
heir-	loom
e@	l u: m
heir-	looms
e@	l u: m z
heirs
e@ z
heis-	kell
h aI s	k V l
heis-	man
h aI s	m V n
heis-	man's
h aI s	m V n z
heis-	ter
h aI s	t @r
heise
h aI s
heist
h aI s t
hek-	ker
h e	k @r
hel-	den-	te-	nor
h e l	d e n	t e	n @r
hel-	der
h e l	d @r
hel-	fand
h e l	f V n d
hel-	ga
h e l	g V
hel-	ge-	son
h e l	g V	s V n
hel-	la-	cious
h e	l eI	S V s
hel-	la-	cious-	ly
h e	l eI	S V s	l i:
hel-	le-	ni-	sm
h e	l V	n I	z V m
hel-	le-	nic
h V	l e	n I k
hel-	le-	nis-	tic
h e	l V	n I s	t I k
hel-	le-	nize
h e	l V	n aI z
hel-	le-	nized
h e	l V	n aI z d
hel-	len
h e	l V n
hel-	ler
h e	l @r
hel-	ler's
h e	l @r z
hel-	ling
h e	l I N
hel-	lish
h e	l I S
hel-	lo
h V	l @U
hel-	lu-	va
h e	l u:	v V
hel-	man
h e l	m V n
hel-	me-	ted
h e l	m V	t V d
hel-	mer
h e l	m @r
hel-	met
h e l	m V t
hel-	mets
h e l	m V t s
hel-	ming
h e l	m I N
hel-	minth
h e l	m I n T
hel-	mont
h e l	m Q n t
hel-	mut
h e l	m V t
hel-	muth
h e l	m u: T
hel-	per
h e l	p @r
hel-	pers
h e l	p @r z
hel-	ping
h e l	p I N
hel-	pings
h e l	p I N z
hel-	sin-	ki
h e l	s I N	k i:
held
h e l d
hele-	ne
h V	l i: n
hell
h e l
he'll
h i: l
hell-	fire
h e l	f aI r
hell-	man
h e l	m V n
hell-	rai-	ser
h e l	r eI	z @r
helle
h e l
hell's
h e l z
helm
h e l m
helms
h e l m z
helms-	man
h e l	m z m { n
help
h e l p
help-	ful
h e l	p f V l
help-	ful-	ly
h e l	p f V	l i:
help-	less
h e l	p l V s
help-	less-	ly
h e l	p l V s	l i:
help-	less-	ness
h e l	p l V s	n V s
help-	rin
h e l	p r I n
helped
h e l p t
helps
h e l p s
hem
h e m
hem-	line
h e m	l aI n
hem-	lines
h e m	l aI n z
hem-	lock
h e m	l Q k
hem-	mer
h e	m @r
hem-	min-	ger
h e	m I	N @r
hem-	ming
h e	m I N
hem-	mings
h e	m I N z
hem-	pel
h e m	p V l
hem-	pen
h e m	p V n
hem-	phill
h e m	p h I l
hemb-	ree
h e m	b r i:
hemmed
h e m d
hemp
h e m p
hemp-	stead
h e m	p s t e d
hems
h e m z
hen-	d-	ren
h e n	d @r	V n
hen-	don
h e n	d @U n
hen-	dy
h e n	d i:
hen-	gel
h e N	g V l
hen-	house
h e n	h aU s
hen-	ley
h e n	l i:
hen-	leys
h e n	l i: z
hen-	ley's
h e n	l i: z
hen-	man
h e n	m V n
hen-	na
h e	n V
hen-	ne-	pin
h e	n V	p I n
hen-	ner
h e	n @r
hen-	nes-	sey
h e	n V	s i:
hen-	nes-	sey's
h e	n V	s i: z
hen-	nes-	sy
h e	n V	s i:
hen-	nig
h e	n I g
hen-	ning
h e	n I N
hen-	peck
h e n	p e k
hen-	pecked
h e n	p e k t
hen-	ri
h e n	r i:
hen-	ri-	et-	ta
h e n	r i:	e	t V
hen-	ri-	ette
h e n	r i:	e t
hen-	ri-	ka
h e n	r I	k V
hen-	ri-	ques
h e n	r i:	k e z
hen-	ricks
h e n	r I k s
hen-	rik
h e n	r I k
hen-	rique
Q n	r i: k
hen-	ry
h e n	r i:
hen-	ry's
h e n	r i: z
hen-	s-	ler
h e n	s V	l @r
hen-	sel
h e n	s V l
hen-	son
h e n	s V n
hend-	ley
h e n	d l i:
hend-	rick
h e n	d r I k
hend-	rick-	son
h e n	d r I k	s V n
hend-	ricks
h e n	d r I k s
hend-	rik
h e n	d r I k
hend-	rix
h e n	d r I k s
hend-	ry
h e n	d r i:
hend-	ry's
h e n	d r i: z
heng
h e N
henke
h e N k
henn
h e n
hennes
h e n z
hens
h e n z
hen's
h e n z
hens-	ley
h e n	z l i:
henze
h e n z
hep
h e p
hep-	burn
h e p	b @r n
hep-	burn's
h e p	b @r n z
hep-	ler
h e p	l @r
hep-	per
h e	p @r
hep-	tath-	lon
h e p	t { T	l Q n
hep-	worth
h e p	w @r T
hepp-	ner
h e p	n @r
her
h @r
her-	ba-	ceous
@r	b eI	S V s
her-	ba-	list
@r	b V	l V s t
her-	ba-	lists
@r	b V	l V s t s
her-	ba-	list's
@r	b V	l V s t s
her-	ba-	ri-	um
h @r	b e@	i:	V m
her-	ba-	ri-	ums
h @r	b e@	i:	V m z
her-	bal
@r	b V l
her-	ber
h @r	b @r
her-	ber-	ger
h @r	b @r	g @r
her-	bert
h @r	b @r t
her-	bert's
h @r	b @r t s
her-	bi-	cide
h @r	b I	s aI d
her-	bi-	cides
@r	b I	s aI d z
her-	bi-	vo-	rous
h @r	b I	v @r	V s
her-	bi-	vore
h @r	b I	v O@
her-	bie
h @r	b i:
her-	ce-	go-	vi-	na
h e@ t	s V	g @U	v i:	n V
her-	ce-	go-	vi-	na's
h e@ t	s V	g @U	v i:	n V z
her-	cu-	le-	an
h @r k	j u:	l i:	V n
her-	cu-	les
h @r k	j V	l i: z
her-	ded
h @r	d V d
her-	der
h e@	d @r
her-	ders
h @r	d @r z
her-	ding
h @r	d I N
her-	ling
h @r	l I N
her-	long
h @r	l O: N
her-	man
h @r	m V n
her-	mann
h @r	m V n
her-	man's
h @r	m V n z
her-	maph-	ro-	di-	tic
h @r	m { f	r V	d I	t I k
her-	maph-	ro-	dite
h @r	m { f	r V	d aI t
her-	me-	ti-	cal-	ly
h @r	m e	t I	k V	l i:
her-	mes
h @r	m i: z
her-	mi-	a
h @r	m i:	V
her-	mi-	na
h @r	m I	n V
her-	mi-	ni-	a
h e@	m i:	n i:	V
her-	mi-	nie
h @r	m I	n i:
her-	mi-	tage
h @r	m I	t V dZ
her-	mie
h @r	m i:
her-	mine
h @r	m I n
her-	mit
h @r	m I t
her-	mits
h @r	m I t s
her-	mo-	sa
h e@	m @U	s V
her-	mo-	sil-	lo
h @r	m V	s I	l @U
her-	mon
h @r	m V n
her-	nan
h @r	n V n
her-	nan-	dez
h @r	n { n	d e z
her-	nan-	do
h @r	n Q n	d @U
her-	ni-	a
h @r	n i:	V
her-	ni-	ate
h @r	n i:	eI t
her-	ni-	ates
h @r	n i:	eI t s
her-	pes
h @r	p i: z
her-	re-	ra
h @r	e@	V
her-	reid
h e@	aI d
her-	ren
h e@	V n
her-	ri-	ott
h e@	i:	Q t
her-	rick
h e@	I k
her-	rin
h e@	I n
her-	ring
h e@	I N
her-	ring-	ton
h e@	I N	t V n
her-	ring-	ton's
h e@	I N	t V n z
her-	rings
h e@	I N z
her-	rle
h e@	V l
her-	rod
h e@	V d
her-	ron
h e@	V n
her-	schel
h @r	S V l
her-	schel's
h @r	S V l z
her-	self
h @r	s e l f
her-	sey
h @r	s i:
her-	shey
h @r	S i:
her-	shey's
h @r	S i: z
her-	son
h @r	s V n
her-	ta
h @r	t V
her-	tel
h @r	t V l
her-	ter
h @r	t @r
her-	tha
h @r	T V
her-	vey
h @r	v eI
her-	wick
h @r	w I k
her-	wig
h @r	w I g
her-	ze-	go-	vi-	na
h e@ t	s V	g @U	v i:	n V
her-	ze-	go-	vi-	na's
h e@ t	s V	g @U	v i:	n V z
her-	zig
h @r	z I g
her-	zog
h @r	z Q g
herb
@r b
herb-	ster
h @r b	s t @r
herbs
@r b z
herb's
@r b z
herbst
h @r b s t
herd
h @r d
herd-	man
h @r d	m V n
herds
h @r d z
herds-	men
h @r d	z m e n
here
h I@
here-	a-	bout
h I@	V	b aU t
here-	a-	bouts
h I@	V	b aU t s
here-	af-	ter
h I@	{ f	t @r
here-	by
h I@	b aI
here-	to-	fore
h I@	t V	f O@
here-	with
h I@	w I T
here's
h I@ z
herl
h @r l
herm
h @r m
herms
h @r m z
hern
h @r n
hern-	don
h @r n	d V n
herne
h @r n
herr
h e@
herr-	mann
h e@	m V n
hers
h @r z
hers-	ko-	witz
h @r s	k V	w I t s
hersch
h @r S
hersh
h @r S
hert
h @r t
hert-	zog
h @r t	z V g
hertz
h e@ t s
herve
h @r v
herz-	berg
h @r z	b @r g
he's
h i: z
hes-	keth
h e s	k e T
hes-	pe-	ra
h eI s	p e@	V
hes-	per
h e s	p @r
hes-	sel
h e	s V l
hes-	se's
h e	s V z
hes-	sian
h e	S V n
hes-	site
h e	s aI t
hes-	tand
h e s	t V n d
hes-	ter
h e s	t @r
hes-	ther
h e s	D @r
hes-	ti-	a
h e s	t i:	V
hes-	ton
h e s	t V n
hess
h e s
hess-	ler
h e s	l @r
hess-	ton
h e s	t V n
hess-	ton's
h e s	t V n z
hesse
h e s
hew
h j u:
hew-	lett
h j u:	l e t
hewe
h j u:
hewes
h j u: z
hewn
h j u: n
hews
h j u: z
hext
h e k s t
hey
h eI
hey-	day
h eI	d eI
hey-	don
h eI	d V n
hey-	ing
h eI	I N
hey-	man
h eI	m V n
hey-	mann
h eI	m V n
hey-	mann's
h eI	m V n z
hey-	man's
h eI	m V n z
hey-	ward
h eI	w @r d
hey-	wood
h eI	w U d
heyde
h eI d
heys
h eI z
heyse
h eI s
hez-	bol-	lah
h e z	b Q	l V
hez-	bol-	lah's
h e z	b Q	l V z
hi
h aI
hi-	a-	le-	ah
h aI	V	l i:	V
hi-	a-	tus
h aI	eI	t V s
hi-	a-	wa-	tha
h aI	V	w Q	T V
hi-	att
h aI	V t
hi-	att's
h aI	V t s
hi-	ba-	chi
h V	b Q	tS i:
hi-	ber-	na-	tion
h aI	b @r	n eI	S V n
hi-	ber-	nate
h aI	b @r	n eI t
hi-	ber-	ni-	a
h aI	b @r	n i:	V
hi-	ber-	ni-	a's
h aI	b @r	n i:	V z
hi-	chens
h I	k V n z
hi-	dal-	go
h V	d { l	g @U
hi-	de-	ous
h I	d i:	V s
hi-	de-	ous-	ly
h I	d i:	V s	l i:
hi-	dea-	way
h aI	d V	w eI
hi-	deout
h aI	d aU t
hi-	deouts
h aI	d aU t s
hi-	der
h aI	d @r
hi-	ding
h aI	d I N
hi-	dy
h aI	d i:
hi-	fi
h aI	f aI
hi-	gin-	bo-	tham
h I	g I n	b V	T V m
hi-	jac-	ker
h aI	dZ {	k @r
hi-	jac-	kers
h aI	dZ {	k @r z
hi-	jac-	king
h aI	dZ {	k I N
hi-	jac-	kings
h aI	dZ {	k I N z
hi-	jack
h aI	dZ { k
hi-	jacked
h aI	dZ { k t
hi-	jinks
h I	dZ I N k s
hi-	ker
h aI	k @r
hi-	kers
h aI	k @r z
hi-	king
h aI	k I N
hi-	la-	ri-	a
h i:	l Q@	i:	V
hi-	la-	ri-	o
h i:	l Q@	i:	@U
hi-	la-	ri-	ous
h V	l e@	i:	V s
hi-	la-	ri-	ous-	ly
h V	l e@	i:	V s	l i:
hi-	la-	ri-	ty
h V	l e@	V	t i:
hi-	la-	ry
h I	l @r	i:
hi-	land
h I	l V n d
hi-	lo
h i:	l @U
hi-	ma-	la-	ya
h I	m V	l aI	V
hi-	ma-	la-	yan
h I	m V	l eI	V n
hi-	ma-	la-	yas
h I	m V	l aI	V s
hi-	ney
h I	n i:
hi-	ra-	i
h I@	Q	i:
hi-	ram
h aI	r V m
hi-	re
h aI	@r
hi-	red
h aI	@r d
hi-	res
h aI	@r z
hi-	ring
h aI	r I N
hi-	rings
h aI	r I N z
hi-	ro
h I@	@U
hi-	ro-	hi-	to
h I@	@U	h i:	t @U
hi-	ro-	hi-	to's
h I@	@U	h i:	t @U z
hi-	ro-	shi
h I@	@U	S i:
hi-	ro-	shi-	ma
h I@	@U	S i:	m V
hi-	ta-	chi
h V	t Q	tS i:
hi-	to-	shi
h V	t @U	S i:
hib-	bard
h I	b @r d
hib-	ben
h I	b V n
hib-	bert
h I	b @r t
hib-	bitts
h I	b I t s
hibbs
h I b z
hic-	cup
h I	k V p
hic-	cups
h I	k V p s
hic-	key
h I	k i:
hic-	ko-	ries
h I	k @r	i: z
hic-	ko-	ry
h I	k @r	i:
hic-	kok
h I	k V k
hic-	kox
h I	k Q k s
hick
h I k
hick-	man
h I k	m V n
hicks
h I k s
hicks-	ville
h I k	s v I l
hid
h I d
hid-	den
h I	d V n
hide
h aI d
hide-	bound
h aI d	b aU n d
hide-	out
h aI	d aU t
hides
h aI d z
hie-	r-	ar-	chy
h aI	@r	Q@	k i:
hie-	rar-	chi-	cal
h aI	r Q@	k I	k V l
hie-	rar-	chies
h aI	r Q@	k i: z
hie-	rog-	ly-	phic
h aI	r @U g	l I	f I k
hie-	rog-	ly-	phics
h aI	r @U g	l I	f I k s
hie-	stand
h i: s	t V n d
hiems
h i: m z
hiett
h aI t
hig-	bee
h I g	b i:
hig-	don
h I g	d V n
hig-	gin-	bo-	tham
h I	g I n	b Q	T V m
hig-	gin-	son
h I	g I n	s V n
hig-	gins
h I	g I n z
hig-	ley
h I g	l i:
higgs
h I g z
high
h aI
high-	boy
h aI	b OI
high-	brow
h aI b	r aU
high-	brows
h aI b	r aU z
high-	er
h aI	@r
high-	est
h aI	V s t
high-	fa-	lu-	tin
h aI	f V	l u:	t V n
high-	field
h aI	f i: l d
high-	fli-	er
h aI f	l aI	@r
high-	fli-	ers
h aI f	l aI	@r z
high-	fly-	ing
h aI f	l aI	I N
high-	lan-	der
h aI	l { n	d @r
high-	lan-	ders
h aI	l { n	d @r z
high-	land
h aI	l V n d
high-	lands
h aI	l V n d z
high-	ligh-	ted
h aI	l aI	t V d
high-	ligh-	ting
h aI	l aI	t I N
high-	light
h aI	l aI t
high-	lights
h aI	l aI t s
high-	ly
h aI	l i:
high-	man
h aI	m V n
high-	ness
h aI	n V s
high-	ri-	ses
h aI	r aI	z V z
high-	rise
h aI	r aI z
high-	school
h aI s	k u: l
high-	smith
h aI s	m I T
high-	speed
h aI s	p i: d
high-	spi-	ri-	ted
h aI s	p I@	I	d I d
high-	spi-	ri-	ted-	ness
h aI s	p I@	I	d I d	n V s
high-	tech
h aI	t e k
high-	to-	wer
h aI	t aU	@r
high-	to-	wer's
h aI	t aU	@r z
high-	way
h aI	w eI
high-	ways
h aI	w eI z
high-	way's
h aI	w eI z
highs
h aI z
hight
h aI t
hike
h aI k
hiked
h aI k t
hikes
h aI k s
hil-	bert
h I l	b @r t
hil-	born
h I l	b @r n
hil-	da
h I l	d V
hil-	de-	bran
h I l	d V b	r V n
hil-	de-	brand
h I l	d V b	r { n d
hil-	de-	brandt
h I l	d V b	r V n t
hil-	de-	gard
h I l	d V	g Q@ d
hil-	de-	garde
h I l	d I	g Q@ d
hil-	die
h aI l	d i:
hil-	dreth
h I l	d r e T
hil-	dy
h I l	d i:
hil-	fi-	ger
h I l	f aI	g @r
hil-	ger
h I l	g @r
hil-	l-	yer
h I	l i:	@r
hil-	la
h I	l V
hil-	la-	ry
h I	l @r	i:
hil-	la-	ry's
h I	l @r	i: z
hil-	lard
h I	l @r d
hil-	lard's
h I	l @r d z
hil-	le-	gass
h I	l I	g V s
hil-	le-	ry
h I	l @r	i:
hil-	lea-	ry
h I	l @r	i:
hil-	lel
h I	l e l
hil-	ler
h I	l @r
hil-	li-	er
h I	l i:	@r
hil-	liard
h I l	j Q@ d
hil-	ling
h I	l I N
hil-	lis
h I	l I s
hil-	lock
h I	l V k
hil-	ly
h I	l i:
hil-	ton
h I l	t V n
hil-	ton's
h I l	t V n z
hild
h I l d
hilde
h I l d
hile
h aI l
hill
h I l
hill-	bil-	lies
h I l	b I	l i: z
hill-	bil-	ly
h I l	b I	l i:
hill-	crest
h I l	k r e s t
hill-	house
h I l	h aU s
hill-	man
h I l	m { n
hill-	side
h I l	s aI d
hill-	sides
h I l	s aI d z
hill-	top
h I l	t Q p
hill-	tops
h I l	t Q p s
hills
h I l z
hill's
h I l z
hills-	bo-	ro
h I l	z b @r	@U
hills-	bo-	rough
h I l	z b @r	@U
hills-	dale
h I l	z d eI l
hills-	man
h I l	s m V n
hilt
h I l t
hilt-	ner
h I l	t n @r
hilts
h I l t s
him
h I m
him-	self
h I m	s e l f
hime
h aI m
himm-	ler
h I m	l @r
hin-	de-	rer
h I n	d @r	@r
hin-	de-	ring
h I n	d @r	I N
hin-	der
h I n	d @r
hin-	dered
h I n	d @r d
hin-	ders
h I n	d @r z
hin-	di
h I n	d i:
hin-	du
h I n	d u:
hin-	du-	i-	sm
h I n	dZ u:	I	z V m
hin-	dus
h I n	d u: z
hin-	dus-	tan
h I n	d u: s	t { n
hin-	ger
h I n	dZ @r
hin-	ges
h I n	dZ V z
hin-	gle
h I N	g V l
hin-	kel
h I N	k V l
hin-	kle
h I N	k V l
hin-	man
h I n	m V n
hin-	ny
h I	n i:
hin-	son
h I n	s V n
hin-	ted
h I n	t V d
hin-	ter-	land
h I n	t @r	l { n d
hin-	ter-	lands
h I n	t @r	l { n d z
hin-	ting
h I n	t I N
hin-	ton
h I n	t V n
hinch
h I n tS
hinck-	ley
h I N	k l i:
hind
h aI n d
hind-	man
h aI n	d m V n
hind-	quar-	ter
h aI n	d w O@	t @r
hind-	quar-	ters
h aI n	d w O@	t @r z
hind-	ran-	ces
h I n	d r V n	s V z
hind-	rance
h I n	d r V n s
hind-	sight
h aI n	d s aI t
hind-	sight's
h aI n	d s aI t s
hinds
h aI n d z
hine
h aI n
hines
h aI n z
hing
h I N
hing-	ham
h I	N V m
hinge
h I n dZ
hinged
h I n dZ d
hink-	ley
h I N	k l i:
hins-	dale
h I n	s d eI l
hint
h I n t
hints
h I n t s
hintze
h I n t z
hinze
h I n z
hip
h I p
hip-	bone
h I p	b @U n
hip-	bones
h I p	b @U n z
hip-	pen
h I	p V n
hip-	per
h I	p @r
hip-	pest
h I	p V s t
hip-	pie
h I	p i:
hip-	pies
h I	p i: z
hip-	ple
h I	p V l
hip-	po
h I	p @U
hip-	po-	cra-	tic
h I	p V k	r {	t I k
hip-	po-	crates
h I	p V k	r eI t s
hip-	po-	ly-	tus
h V	p Q	l V	t V s
hip-	po-	po-	ta-	mu-	ses
h I	p V	p Q	t V	m V	s V z
hip-	po-	po-	ta-	mus
h I	p V	p Q	t V	m V s
hip-	pod-	rome
h I	p V d	r @U m
)"
R"(hip-	pos
h I	p @U z
hips
h I p s
hir-	sch's
h @r	S V z
hirsch
h @r S
hirsch-	feld
h @r S	f e l d
hirsh
h @r S
hirst
h @r s t
his
h I z
his-	pa-	nic
h V s	p {	n I k
his-	pa-	nics
h V s	p {	n I k s
his-	pa-	no
h V s	p Q	n @U
his-	self
h I	s e l f
his-	ses
h I	s V z
his-	sing
h I	s I N
his-	s's
h I	s V z
his-	ta-	mine
h I s	t V	m i: n
his-	tad-	rut
h I s	t V d	r V t
his-	ti-	dine
h I s	t I	d i: n
his-	to-	gram
h I s	t V g	r { m
his-	to-	grams
h I s	t V g	r { m z
his-	to-	lo-	gy
h I s	t Q	l V	dZ i:
his-	to-	ri-	an
h I s	t O@	i:	V n
his-	to-	ri-	ans
h I s	t O@	i:	V n z
his-	to-	ri-	cal
h I s	t O@	I	k V l
his-	to-	ri-	cal-	ly
h I s	t O@	I	k V	l i:
his-	to-	ric
h I s	t O@	I k
his-	to-	ry
h I s	t @r	i:
his-	to-	ry's
h I s	t @r	i: z
hiss
h I s
hissed
h I s t
hist-	ri-	o-	nic
h I s	t r i:	Q	n I k
hist-	ri-	o-	nics
h I s	t r i:	Q	n I k s
hit
h I t
hit-	ches
h I	tS V z
hit-	ching
h I	tS I N
hit-	chins
h I	tS I n z
hit-	her
h I	D @r
hit-	her-	to
h I	D @r	t u:
hit-	ler
h I t	l @r
hit-	ler's
h I t	l @r z
hit-	man
h I t	m { n
hit-	ter
h I	t @r
hit-	ters
h I	t @r z
)"