R"(west-	leigh
w e s	t l aI
west-	ley
w e s	t l i:
west-	ling
w e s	t l I N
west-	lund
w e s	t l V n d
west-	min-	ster
w e s	t m I n	s t @r
west-	more-	land
w e s	t m O@	l V n d
west-	pha-	li-	a
w e s	t f eI	l i:	V
west-	phal
w e s	t f V l
west-	port
w e s	t p O@ t
west-	side
w e s	t s aI d
west-	ward
w e s	t w @r d
west-	wards
w e s	t w @r d z
west-	wood
w e s	t w U d
west-	wood's
w e s	t w U d z
west's
w e s t s
wet
w e t
wet-	her-	by
w e	T @r	b i:
wet-	land
w e t	l { n d
wet-	lands
w e t	l { n d z
wet-	more
w e t	m O@
wet-	ness
w e t	n V s
wet-	suit
w e t	s u: t
wet-	ter
w e	t @r
wet-	test
w e	t V s t
wet-	ting
w e	t I N
wet-	zel
w e t	z V l
we've
w i: v
wex-	ler
w e k	s l @r
wey
w eI
wey-	lin
w eI	l I n
wey-	mouth
w eI	m V T
weyer-	haeu-	ser
w e@	h aU	z @r
weyer-	haeu-	ser's
w e@	h aU	z @r z
weyl
w eI l
wha-	len
w eI	l V n
wha-	ler
w eI	l @r
wha-	lers
w eI	l @r z
wha-	ling
w eI	l I N
wha-	t'd
w V	t V d
wha-	te-	ver
w V	t e	v @r
wha-	t'll
w V	t V l
wha-	t're
w V	t @r
whac-	king
w {	k I N
whac-	ko
w {	k @U
whack
w { k
whacked
w { k t
whacks
w { k s
whale
w eI l
whales
w eI l z
whale's
w eI l z
wham
w { m
wham-	my
w {	m i:
whan
w { n
whang
w { N
whar-	ry
w {	r i:
whar-	ton
w O@	t V n
whar-	ton's
w O@	t V n z
wharf
w O@ f
wharf's
w O@ f s
what
w Q t
what-	ley
w V t	l i:
what-	not
w V t	n Q t
what-	so-	e-	ver
w V t	s @U	e	v @r
whats
w V t s
what's
w V t s
whe-	lan
w e	l V n
whe-	ne-	ver
w e	n e	v @r
whe-	n'll
w e	n V l
whe-	reas
w e@	{ z
whe-	rein
w e@	I n
whe-	reu-	pon
w e@	V	p Q n
whe-	ther
w e	D @r
whea-	ten
w i:	t V n
whea-	ties
w i:	t i: z
whea-	ton
w i:	t V n
wheat
w i: t
wheat-	ley
w i: t	l i:
whee-	lab-	ra-	tor
w i:	l V b	r eI	t @r
whee-	ler
w i:	l @r
whee-	lers
w i:	l @r z
whee-	ler's
w i:	l @r z
whee-	ling
w i:	l I N
whee-	ling's
w i:	l I N z
whee-	lock
w i:	l Q k
whee-	zes
w i:	z V z
whee-	zing
w i:	z I N
wheel
w i: l
wheel-	bar-	row
w i: l	b e@	@U
wheel-	bar-	rows
w i: l	b e@	@U z
wheel-	base
w i: l	b eI s
wheel-	chair
w i: l	tS e@
wheel-	chairs
w i: l	tS e@ z
wheel-	wright
w i: l	r aI t
wheeled
w i: l d
wheels
w i: l z
wheeze
w i: z
when
w e n
whence
w e n s
when's
w e n z
wher-	e-	ver
w e@	e	v @r
wher-	ry
w e@	i:
where
w e@
where-	a-	bouts
w e@	V	b aU t s
where-	by
w e@	b aI
where-	wi-	thal
w e@	w I	D O: l
where'd
w e@ d
where's
w e@ z
whet
w e t
whet-	stone
w e t	s t @U n
whet-	ted
w e	t V d
whew
w u:
whey
w eI
whi-	gham
w I	g V m
whi-	ner
w aI	n @r
whi-	ners
w aI	n @r z
whi-	ning
w aI	n I N
whi-	ny
w aI	n i:
whi-	stle
w I	s V l
whi-	stle-	blo-	wer
w I	s V l	b l @U	@r
whi-	stle-	blo-	wers
w I	s V l	b l @U	@r z
whi-	stled
w I	s V l d
whi-	stles
w I	s V l z
whi-	ta-	ker
w I	t V	k @r
whi-	te-	ning
w aI	t V	n I N
whi-	ted
w aI	t V d
whi-	ten
w aI	t V n
whi-	ter
w aI	t @r
whi-	test
w aI	t V s t
whi-	tey
w aI	t i:
whi-	ther
w I	D @r
whi-	ting
w aI	t I N
whi-	tings
w aI	t I N z
whi-	tish
w aI	t I S
whic-	ker
w I	k @r
which
w I tS
which-	e-	ver
w I	tS e	v @r
whiff
w I f
whig
w I g
whigs
w I g z
while
w aI l
whiles
w aI l z
whilst
w aI l s t
whim
w I m
whim-	pe-	ring
w I m	p @r	I N
whim-	per
w I m	p @r
whim-	si-	cal
w I m	z I	k V l
whim-	sy
w I m	s i:
whims
w I m z
whine
w aI n
whines
w aI n z
whip
w I p
whip-	la-	shes
w I p	l {	S V z
whip-	lash
w I p	l { S
whip-	pa-	ny
w I	p V	n i:
whip-	ping
w I	p I N
whip-	ple
w I	p V l
whip-	ple's
w I	p V l z
whip-	poor-	wills
w I	p @r	w I l z
whip-	saw
w I p	s O:
whip-	saw-	ing
w I p	s O:	I N
whip-	sawed
w I p	s O: d
whipped
w I p t
whips
w I p s
whir-	ley
w @r	l i:
whir-	ling
w @r	l I N
whir-	ring
w @r	I N
whirl
w @r l
whirl-	pool
w @r l	p u: l
whirl-	pools
w @r l	p u: l z
whirl-	pool's
w @r l	p u: l z
whirl-	wind
w @r l	w I n d
whirled
w @r l d
whis-	ker
w I s	k @r
whis-	kers
w I s	k @r z
whis-	key
w I s	k i:
whis-	keys
w I s	k i: z
whis-	ky
w I s	k i:
whis-	pe-	ring
w I s	p @r	I N
whis-	per
w I s	p @r
whis-	pered
w I s	p @r d
whis-	pers
w I s	p @r z
whisk
w I s k
whisked
w I s k t
whisks
w I s k s
whist-	ler
w I s	l @r
whist-	lers
w I s	l @r z
whist-	ling
w I s	l I N
whit
w I t
whit-	bread
w I t	b r e d
whit-	by
w I t	b i:
whit-	cher
w I	tS @r
whit-	comb
w I t	k V m
whit-	field
w I t	f i: l d
whit-	ford
w I t	f @r d
whit-	ley
w I t	l i:
whit-	ling
w I t	l I N
whit-	lock
w I t	l Q k
whit-	low
w I t	l @U
whit-	man
w I t	m V n
whit-	man's
w I t	m V n z
whit-	mer
w I t	m @r
whit-	mire
w I t	m aI r
whit-	more
w I t	m O@
whit-	ney
w I t	n i:
whit-	ney's
w I t	n i: z
whit-	sett
w I t	s e t
whit-	son
w I t	s V n
whit-	ta-	ker
w I	t V	k @r
whit-	ten
w I	t V n
whit-	ti-	er
w I	t i:	@r
whit-	ting-	ton
w I	t I N	t V n
whit-	tle
w I	t V l
whit-	tled
w I	t V l d
whit-	tle's
w I	t V l z
whit-	well
w I t	w e l
whit-	worth
w I t	w @r T
white
w aI t
white-	bread
w aI t	b r e d
white-	field
w aI t	f i: l d
white-	fish
w aI t	f I S
white-	ford
w aI t	f O@ d
white-	hall
w aI t	h O: l
white-	hall's
w aI t	h O: l z
white-	head
w aI t	h e d
white-	head's
w aI t	h e d z
white-	horse
w aI t	h O@ s
white-	house
w aI t	h aU s
white-	hurst
w aI t	h @r s t
white-	hurst's
w aI t	h @r s t
white-	law
w aI t	l O:
white-	ley
w aI t	l i:
white-	ly
w aI t	l i:
white-	ner
w aI t	n @r
white-	ness
w aI t	n V s
white-	side
w aI t	s aI d
white-	stone
w aI t	s t @U n
white-	tail
w aI t	t eI l
white-	wa-	ter
w aI t	w O:	t @r
white-	wa-	ter's
w aI t	w O:	t @r z
white-	wash
w aI t	w Q S
white-	washed
w aI t	w Q S t
whites
w aI t s
white's
w aI t s
whitt
w I t
whitt-	ling
w I t	l I N
whitte-	more
w I t	m O@
whiz
w I z
whiz-	zer
w I	z @r
whiz-	zes
w I	z V z
whiz-	zing
w I	z I N
whizzed
w I z d
who
h u:
who-	du-	nit
h u:	d V	n I t
who-	du-	nits
h u:	d V	n I t s
who-	e-	ver
h u:	e	v @r
who-	e-	ver's
h u:	e	v @r z
who'-	re
h u:	@r
who-	so-	e-	ver
h u:	s @U	e	v @r
whoa
w @U
who'd
h u: d
whol-	ly
h @U	l i:
whole
h @U l
whole-	hear-	ted
h @U l	h Q@	t V d
whole-	hear-	ted-	ly
h @U l	h Q@	t V d	l i:
whole-	ness
h @U l	n V s
whole-	sa-	ler
h @U l	s eI	l @r
whole-	sa-	lers
h @U l	s eI	l @r z
whole-	sa-	ler's
h @U l	s eI	l @r z
whole-	sa-	ling
h @U l	s eI	l I N
whole-	sale
h @U l	s eI l
whole-	sales
h @U l	s eI l z
whole-	some
h @U l	s V m
whole-	some-	ness
h @U l	s V m	n V s
wholes
h @U l z
who'll
h u: l
whom
h u: m
whom-	e-	ver
h u:	m e	v @r
whom-	so-	e-	ver
h u: m	s @U	e	v @r
whoo-	pee
w u:	p i:
whoo-	pie
w u:	p i:
whoo-	ping
w u:	p I N
whoop
w u: p
whooped
w u: p t
whoops
w u: p s
whoosh
w u: S
whop-	per
w Q	p @r
whop-	pers
w Q	p @r z
whop-	ping
w Q	p I N
whor-	ton
h O@	t V n
whore
h O@
whore-	house
h O@	h aU s
whores
h O@ z
whorl
w @r l
whorls
w @r l z
who's
h u: z
whose
h u: z
who've
h u: v
why
w aI
why'd
w aI d
whys
w aI z
why's
w aI z
whyte
w aI t
wi-	att
w aI	V t
wi-	chern
w I	k @r n
wi-	chi-	ta
w I	tS I	t O:
wi-	chi-	ta's
w I	tS I	t O: z
wi-	de-	ner
w I	d i:	n @r
wi-	de-	ning
w aI	d V	n I N
wi-	den
w aI	d V n
wi-	dened
w aI	d V n d
wi-	dens
w aI	d V n z
wi-	der
w aI	d @r
wi-	dest
w aI	d V s t
wi-	do-	wer
w I	d @U	@r
wi-	do-	wers
w I	d @U	@r z
wi-	dow
w I	d @U
wi-	dowed
w I	d @U d
wi-	dows
w I	d @U z
wi-	dow's
w I	d @U z
wi-	leen
w V	l i: n
wi-	len
w aI	l V n
wi-	ley
w aI	l i:
wi-	lin-	ski
v V	l I n	s k i:
wi-	ling
w aI	l I N
wi-	ly
w aI	l i:
wi-	na-	mac
w I	n V	m { k
wi-	na-	mac's
w I	n V	m { k s
wi-	ne-	ries
w aI	n @r	i: z
wi-	ne-	ry
w aI	n @r	i:
wi-	ne-	ry's
w aI	n @r	i: z
wi-	ner
w aI	n @r
wi-	ney
w aI	n i:
wi-	ni-	fred
w I	n I f	r e d
wi-	ning
w aI	n I N
wi-	no
w i:	n @U
wi-	no-	grad
w I	n V g	r { d
wi-	no-	la
v I	n @U	l V
wi-	no-	na
w I	n V	n V
wi-	no-	nah
w I	n V	n V
wi-	noo-	ski
w I	n u: s	k i:
wi-	nos
w i:	n @U s
wi-	per
w aI	p @r
wi-	pers
w aI	p @r z
wi-	ping
w aI	p I N
wi-	re
w aI	@r
wi-	re-	les-	s's
w aI	@r	l V	s V z
wi-	re-	tap
w aI	@r	t { p
wi-	re-	tap-	ping
w aI	@r	t {	p I N
wi-	re-	tapped
w aI	@r	t { p t
wi-	red
w aI	@r d
wi-	res
w aI	@r z
wi-	ring
w aI	r I N
wi-	ry
w I@	i:
wi-	ser
w aI	z @r
wi-	sest
w aI	z V s t
wi-	sher
w I	S @r
wi-	shers
w I	S @r z
wi-	shes
w I	S V z
wi-	shing
w I	S I N
wi-	shy
w I	S i:
wi-	tham
w I	T V m
wi-	the-	ring
w I	D @r	I N
wi-	thee
w I	T i:
wi-	ther
w I	D @r
wi-	ther-	spoon
w I	D @r s	p u: n
wi-	thered
w I	D @r d
wi-	thers
w I	D @r z
wi-	thin
w V	D I n
wi-	xom
w I k	s V m
wi-	zard
w I	z @r d
wi-	zard-	ry
w I	z @r d	r i:
wi-	zards
w I	z @r d z
wi-	zen
w aI	z V n
wi-	zened
w aI	z V n d
wic-	ca
w I	k V
wic-	can
w I	k V n
wic-	ked
w I	k V d
wic-	ked-	ly
w I	k V d	l i:
wic-	ked-	ness
w I	k V d	n V s
wic-	kens
w I	k V n z
wic-	ker
w I	k @r
wic-	ket
w I	k V t
wic-	kets
w I	k V t s
wic-	kett
w I	k e t
wic-	kham
w I	k V m
wice
w aI s
wich
w I tS
wich-	man
w I tS	m V n
wick
w I k
wick-	liffe
w I k	l I f
wick-	man
w I k	m V n
wickes
w I k s
wicks
w I k s
wid-	der
w I	d @r
wid-	dle
w I	d V l
wid-	dled
w I	d V l d
wid-	get
w I	dZ V t
wid-	gets
w I	dZ V t s
wide
w aI d
wide-	bo-	dy
w aI d	b Q	d i:
wide-	ly
w aI d	l i:
wide-	man
w aI d	m V n
wide-	spread
w aI d	s p r e d
width
w I d T
widths
w I d T s
wie-	land
w i:	l V n d
wie-	ner
w i:	n @r
wie-	ners
w i:	n @r z
wie-	sel
w i:	s V l
wie-	sen-	thal
w i:	s V n	T Q l
wied
w i: d
wied-	mann
w i: d	m V n
wiel-	ded
w i: l	d V d
wiel-	ding
w i: l	d I N
wield
w i: l d
wields
w i: l d z
wien
w i: n
wier
w I@
wiers-	ma
v I@ s	m V
wies-	ba-	den
w i: s	b Q	d V n
wiese
w i: z
wife
w aI f
wife's
w aI f s
wig
w I g
wig-	g-	ling
w I	g V	l I N
wig-	g-	ly
w I	g V	l i:
wig-	ger
w I	g @r
wig-	gin
w I	g I n
wig-	gins
w I	g I n z
wig-	gle
w I	g V l
wig-	gles-	worth
w I	g V l	z w @r T
wig-	wam
w I g	w Q m
wight
w aI t
wight-	man
w aI t	m V n
wigs
w I g z
wil
w I l
wil-	ber
w I l	b @r
wil-	ber-	force
w I l	b @r	f O@ s
wil-	bert
w I l	b @r t
wil-	bur
w I l	b @r
wil-	burn
w I l	b @r n
wil-	co-	xon
w I l	k Q k	s V n
wil-	cox
w I l	k Q k s
wil-	den
w aI l	d V n
wil-	der
w aI l	d @r
wil-	der-	muth
w aI l	d @r	m u: T
wil-	der-	ness
w I l	d @r	n V s
wil-	der's
w aI l	d @r z
wil-	dest
w aI l	d V s t
wil-	ding
w aI l	d I N
wil-	don
w aI l	d V n
wil-	ford
w I l	f @r d
wil-	fre-	da
w I l	f r V	d V
wil-	fre-	do
w I l	f eI	d @U
wil-	fred
w I l	f r V d
wil-	frid
w I l	f r I d
wil-	ful-	ly
w I l	f V	l i:
wil-	hel-	mi-	na
w I l	h e l	m i:	n V
wil-	hel-	mine
w I l	h V l	m I n
wil-	helm
w I l	h e l m
wil-	hide
w I l	h aI d
wil-	kens
w I l	k V n z
wil-	ker-	son
w I l	k @r	s V n
wil-	key
w I l	k i:
wil-	ki-	son
w I l	k I	s V n
wil-	kie
w I l	k i:
wil-	kin
w I l	k I n
wil-	kin-	son
w I l	k I n	s V n
wil-	kin-	son's
w I l	k I n	s V n z
wil-	kins
w I l	k I n z
wil-	la
w I	l V
wil-	la-	belle
w I	l V	b e l
wil-	la-	mette
w V	l {	m V t
wil-	la-	mette's
w V	l {	m V t s
wil-	la-	mi-	na
w I	l V	m aI	n V
wil-	lard
w I	l @r d
wil-	lem
w I	l V m
wil-	ler
w I	l @r
wil-	lers
w I	l @r z
wil-	let
w I	l e t
wil-	lets
w I	l e t s
wil-	lett
w I	l e t
wil-	lette
w V	l e t
wil-	ley
w I	l i:
wil-	li
w I	l i:
wil-	li-	ford
w I	l I	f @r d
wil-	liam
w I l	j V m
wil-	liam-	sen
w I l	j V m	s V n
wil-	liam-	son
w I l	j V m	s V n
wil-	liam-	son's
w I l	j V m	s V n z
wil-	liam-	sport
w I l	j V m	s p O@ t
wil-	liam-	stown
w I l	j V m	s t aU n
wil-	liams
w I l	j V m z
wil-	liam's
w I l	j V m z
wil-	liams-	burg
w I l	j V m	z b @r g
wil-	lie
w I	l i:
wil-	lie's
w I	l i: z
wil-	lin-	ger
w I	l I	N @r
wil-	ling
w I	l I N
wil-	ling-	ly
w I	l I N	l i:
wil-	ling-	ness
w I	l I N	n V s
wil-	lis
w I	l I s
wil-	lis-	ton
w I	l I s	t Q n
wil-	lits
w I	l I t s
wil-	lo-	wy
w I	l V	w i:
wil-	lock
w I	l V k
wil-	lough-	by
w I	l V	b i:
wil-	low
w I	l @U
wil-	lows
w I	l @U z
wil-	ly
w I	l i:
wil-	lyard
w I l	j Q@ d
wil-	ma
w I l	m V
wil-	mar
w I l	m @r
wil-	mer
w I l	m @r
wil-	mette
w I l	m e t
wil-	ming-	ton
w I l	m I N	t V n
wil-	more
w I l	m O@
wil-	mot
w I l	m V t
wil-	mott
w I l	m V t
wil-	sey
w I l	s i:
wil-	shire
w I l	S aI r
wil-	son
w I l	s V n
wil-	son's
w I l	s V n z
wil-	ted
w I l	t V d
wil-	ting
w I l	t I N
wil-	ton
w I l	t V n
wild
w aI l d
wild-	card
w aI l	d k Q@ d
wild-	cat
w aI l	d k { t
wild-	cat-	ter
w aI l	d k {	t @r
wild-	cat-	ters
w aI l	d k {	t @r z
wild-	cat-	ting
w aI l	d k {	t I N
wild-	cats
w aI l	d k { t s
wild-	fi-	re
w aI l	d f aI	@r
wild-	fi-	res
w aI l	d f aI	@r z
wild-	flo-	wer
w aI l	d f l aU	@r
wild-	flowers
w aI l	d f l aU r z
wild-	life
w aI l	d l aI f
wild-	ly
w aI l	d l i:
wild-	ness
w aI l	d n V s
wild-	wood
w aI l	d w U d
wild-	woods
w aI l	d w U d z
wilde
w aI l d
wilds
w aI l d z
wile
w aI l
wiles
w aI l z
wilk
w I l k
wilkes
w I l k s
wilkes-	bo-	ro
w I l	k s b @r	@U
will
w I l
will-	cox
w I l	k Q k s
will-	ful
w I l	f V l
will-	ful-	ly
w I l	f V	l i:
will-	kie
w I l	k i:
will-	man
w I l	m V n
will-	ner
w I l	n @r
will-	po-	wer
w I l	p aU	@r
willed
w I l d
willes
w aI l z
willms
w I l m z
wills
w I l z
will's
w I l z
wil's
w I l z
wilt
w I l t
wilt-	sey
w I l	t s i:
wilt-	shire
w I l	tS aI r
wilts
w I l t s
wiltz
w I l t s
wim-	ber-	ley
w I m	b @r	l i:
wim-	ble-	don
w I m	b V l	d V n
wim-	pi-	ness
w I m	p i:	n V s
wim-	py
w I m	p i:
wim-	satt
w I m	s V t
wimp
w I m p
wimps
w I m p s
win
w I n
win-	ber-	ry
w I n	b e@	i:
win-	chell
w I n	tS V l
win-	chell's
w I n	tS V l z
win-	ches-	ter
w I n	tS e s	t @r
win-	cing
w I n	s I N
win-	ded
w I n	d V d
win-	der
w I n	d @r
win-	ders
w I n	d @r z
win-	dham
w I n	d V m
win-	dhoek
w I n	d h @U k
win-	ding
w aI n	d I N
win-	dle
w I n	d V l
win-	dom
w I n	d V m
win-	dow
w I n	d @U
win-	dow-	less
w I n	d @U	l V s
win-	dow-	pane
w I n	d @U	p eI n
win-	dow-	panes
w I n	d @U	p eI n z
win-	dowed
w I n	d @U d
win-	dows
w I n	d @U z
win-	dup
w aI n	d V p
win-	dy
w I n	d i:
win-	field
w I n	f i: l d
win-	fred
w I n	f r V d
win-	free
w I n	f r i:
win-	frey
w I n	f r i:
win-	frid
w I n	f r I d
win-	gate
w I n	g eI t
win-	ger
w I	N @r
win-	gers
w I	N @r z
win-	ging
w I	N I N
win-	go
w i: N	g @U
win-	kel
w I N	k V l
win-	kel-	man
w I N	k V l	m V n
win-	ker
w I N	k @r
win-	king
w I N	k I N
win-	kle
w I N	k V l
win-	kles
w I N	k V l z
win-	na-	ble
w I	n V	b V l
win-	ne-	ba-	go
w I	n V	b eI	g @U
win-	ne-	ba-	go's
w I	n V	b eI	g @U z
win-	ner
w I	n @r
win-	ners
w I	n @r z
win-	ner's
w I	n @r z
win-	net-	ka
w I	n e t	k V
win-	nett
w I	n e t
win-	ni-	peg
w I	n I	p e g
win-	nick
w I	n I k
win-	nie
w I	n i:
win-	nin-	gest
w I	n I	N V s t
win-	ning
w I	n I N
win-	nings
w I	n I N z
win-	no-	wing
w I	n @U	I N
win-	now
w I	n @U
win-	nowed
w I	n @U d
win-	ny
w I	n i:
win-	sett
w I n	s e t
win-	some
w I n	s V m
win-	son
w I n	s V n
win-	sor
w I n	z @r
win-	ston
w I n	s t V n
win-	te-	rize
w I n	t @r	aI z
win-	te-	rized
w I n	t @r	aI z d
win-	ter
w I n	t @r
win-	ter-	bourne
w I n	t @r	b O@ n
win-	ter-	thur
w I n	t @r	T @r
win-	ter-	time
w I n	t @r	t aI m
win-	tered
w I n	t @r d
win-	ters
w I n	t @r z
win-	ter's
w I n	t @r z
win-	ther
w I n	T @r
win-	tle
w I n	t V l
win-	ton
w I n	t V n
win-	try
w I n	t r i:
wince
w I n s
winced
w I n s t
winch
w I n tS
wind
w I n d
wind-	chill
w I n	d tS I l
wind-	fall
w I n	d f O: l
wind-	falls
w I n	d f O: l z
wind-	lass
w I n	d l V s
wind-	mill
w I n	d m I l
wind-	mills
w I n	d m I l z
wind-	shield
w I n	d S i: l d
wind-	shields
w I n	d S i: l d z
wind-	sor
w I n	z @r
wind-	sor's
w I n	z @r z
wind-	storm
w I n	d s t O@ m
wind-	swept
w I n	s w e p t
wind-	ward
w I n	d w @r d
winds
w I n d z
wind's
w I n d z
wine
w aI n
wined
w aI n d
wines
w aI n z
wine's
w aI n z
wing
w I N
wing-	back
w I N	b { k
wing-	like
w I N	l aI k
wing-	man
w I N	m V n
winge
w I n dZ
winged
w I N d
wings
w I N z
wing's
w I N z
wings-	pan
w I N	s p { n
wink
w I N k
wink-	ler
w I N	k l @r
winked
w I N k t
winks
w I N k s
winn
w I n
winne
w I n
wins
w I n z
win's
w I n z
wins-	low
w I n	z l @U
wint
w I n t
winth-	rop
w I n	T r V p
winth-	rop's
w I n	T r V p s
wipe
w aI p
wipe-	out
w aI	p aU t
wiped
w aI p t
wipes
w aI p s
wire-	less
w aI r	l V s
wire-	man
w aI r	m V n
wire-	taps
w aI r	t { p s
wirth
w @r T
wirtz
w @r t s
wis
w I s
wis-	by
w I s	b i:
wis-	con-	sin
w I s	k Q n	s I n
wis-	con-	sin's
w I s	k Q n	s I n z
wis-	dom
w I z	d V m
wis-	ner
w I s	n @r
wis-	py
w I s	p i:
wis-	sel
w I	s V l
wis-	sing
w I	s I N
wise
w aI z
wise-	crac-	king
w aI z	k r {	k I N
wise-	crack
w aI z	k r { k
wise-	cracks
w aI z	k r { k s
wise-	guy
w aI z	g aI
wise-	ly
w aI z	l i:
wise-	man
w aI z	m V n
wised
w aI z d
wish
w I S
wish-	bone
w I S	b @U n
)"
R"(wish-	ful
w I S	f V l
wish-	ful-	ly
w I S	f V	l i:
wished
w I S t
wisp
w I s p
wiss
w I s
wiss-	ler
w I s	l @r
wist
w I s t
wist-	ful
w I s	t f V l
wist-	ful-	ly
w I s	t f V	l i:
wist-	ful-	ness
w I s	t f V l	n V s
wit
w I t
wit-	cher
w I	tS @r
wit-	ches
w I	tS V z
wit-	ching
w I	tS I N
wit-	ch's
w I	tS V z
wit-	chy
w I	tS i:
wit-	kin
w I t	k I n
wit-	less
w I t	l V s
wit-	mer
w I t	m @r
wit-	nes-	ses
w I t	n V	s V z
wit-	nes-	sing
w I t	n V	s I N
wit-	nes-	s's
w I t	n V	s V z
wit-	ness
w I t	n V s
wit-	nessed
w I t	n V s t
wit-	te-	kind
w I	t I	k I n d
wit-	ted
w I	t V d
wit-	ten
w I	t V n
wit-	ten-	berg
w I	t V n	b @r g
wit-	ten-	burg
w I	t V n	b @r g
wit-	ter
w I	t @r
wit-	ters
w I	t @r z
wit-	ter's
w I	t @r z
wit-	ti-	ly
w I	t I	l i:
wit-	ting
w I	t I N
wit-	ting-	ly
w I	t I N	l i:
wit-	ty
w I	t i:
wit-	wa-	ter-	srand
w I t	w O:	t @r s	r { n d
witch
w I tS
witch-	craft
w I tS	k r { f t
witch-	hunt
w I tS	h V n t
with
w I D
with-	dra-	wal
w V D	d r O:	V l
with-	dra-	wals
w I T	d r O:	V l z
with-	dra-	wing
w I T	d r O:	I N
with-	draw
w V D	d r O:
with-	drawn
w I T	d r O: n
with-	draws
w V D	d r O: z
with-	drew
w I T	d r u:
with-	held
w I T	h e l d
with-	hol-	ding
w I T	h @U l	d I N
with-	hold
w I T	h @U l d
with-	holds
w I T	h @U l d z
with-	out
w I	T aU t
with-	stan-	ding
w I T	s t { n	d I N
with-	stand
w I T	s t { n d
with-	stands
w I T	s t { n d z
with-	stood
w I T	s t U d
wits
w I t s
wit's
w I t s
witt
w I t
witt-	man
w I t	m V n
witt-	mann
w I t	m V n
witte
w I t
wives
w aI v z
wives'
w aI v z
wix-	ted
w I k	s t V d
wiz
w I z
wo
w @U
wo-	be-	gon
w @U	b V	g Q n
wo-	burn
w u:	b @r n
wo-	gan
w @U	g V n
wo-	ken
w @U	k V n
wo-	ma-	ni-	zer
w U	m V	n aI	z @r
wo-	ma-	ni-	zing
w U	m V	n aI	z I N
wo-	ma-	nize
w U	m V	n aI z
wo-	mack
w @U	m { k
wo-	man
w U	m V n
wo-	man-	hood
w U	m V n	h U d
wo-	man's
w U	m V n z
wo-	men
w I	m V n
wo-	men's
w I	m V n z
wo-	tan
w @U	t V n
wo-	ven
w @U	v V n
wo-	wing
w aU	I N
wob-	b-	ling
w Q	b V	l I N
wob-	b-	ly
w Q	b V	l i:
wob-	ble
w Q	b V l
wob-	bled
w Q	b V l d
woe
w @U
woe-	be-	gone
w @U	b I	g O: n
woe-	ful
w @U	f V l
woe-	ful-	ly
w @U	f V	l i:
woes
w @U z
woj-	cik
w OI	tS I k
wok
w Q k
woke
w @U k
wol-	cott
w @U l	k V t
wol-	fen-	den
w U l	f e n	d V n
wol-	fer
w U l	f @r
wol-	ford
w @U l	f @r d
wol-	fram
w U l	f r { m
wol-	gast
w @U l	g V s t
wol-	pert
w @U l	p @r t
wol-	sey
w @U l	s i:
wol-	ter
w @U l	t @r
wol-	ve-	rine
w U l	v @r	i: n
wol-	ve-	rine's
w U l	v @r	i: n z
wol-	ver-	ton
w U l	v @r	t V n
wold
w @U l d
wolf
w U l f
wolf-	gang
w U l	f g { N
wolf-	gram
w U l	f g r { m
wolf-	man
w U l	f m V n
wolf-	son
w U l	f s V n
wolfe
w U l f
wolfe's
w U l f s
wolff
w U l f
wolf's
w U l f s
wolfs-	burg
w U l	f s b @r g
wolk
w @U k
woll
w Q l
wols-	ky
v @U l	s k i:
wolves
w U l v z
wom-	bat
w Q m	b { t
wom-	bats
w Q m	b { t s
wom-	ble
w Q m	b V l
wom-	bles
w Q m	b V l z
womb
w u: m
won
w V n
won-	de-	ring
w V n	d @r	I N
won-	der
w V n	d @r
won-	der-	ful
w V n	d @r	f V l
won-	der-	ful-	ly
w V n	d @r	f V	l i:
won-	der-	ful-	ness
w V n	d @r	f V l	n V s
won-	der-	land
w V n	d @r	l { n d
won-	der-	ment
w V n	d @r	m V n t
won-	dered
w V n	d @r d
won-	ders
w V n	d @r z
won-	der's
w V n	d @r z
wond-	rous
w V n	d r V s
wong
w O: N
wong's
w O: N z
wonk
w Q n k
wonks
w Q n k s
wont
w @U n t
won't
w @U n t
woo
w u:
woo-	dall
w U	d O: l
woo-	dard
w U	d @r d
woo-	ded
w U	d V d
woo-	den
w U	d V n
woo-	die
w U	d i:
woo-	ding
w U	d I N
woo-	dy
w U	d i:
woo-	dy's
w U	d i: z
woo-	ing
w u:	I N
woo-	len
w U	l V n
woo-	lens
w U	l V n z
woo-	ly
w U	l i:
woo-	mer
w u:	m @r
woo-	tan
w u:	t V n
woo-	ten
w u:	t V n
woo-	ton
w u:	t V n
woo-	tten
w u:	t V n
woo-	zy
w u:	z i:
wood
w U d
wood-	ber-	ry
w U d	b e@	i:
wood-	bridge
w U d	b r I dZ
wood-	bu-	ry
w U d	b e@	i:
wood-	burn
w U d	b @r n
wood-	car-	ver
w U d	k Q@	v @r
wood-	car-	vers
w U d	k Q@	v @r z
wood-	chip
w U d	tS I p
wood-	chips
w U d	tS I p s
wood-	chuck
w U d	tS V k
wood-	cock
w U d	k Q k
wood-	field
w U d	f i: l d
wood-	ford
w U d	f @r d
wood-	head
w U d	h e d
wood-	house
w U d	h aU s
wood-	hull
w U d	h V l
wood-	land
w U d	l { n d
wood-	lands
w U d	l { n d z
wood-	ley
w U d	l i:
wood-	lot
w U d	l Q t
wood-	man
w U d	m V n
wood-	pec-	ker
w U d	p e	k @r
wood-	pec-	kers
w U d	p e	k @r z
wood-	rick
w U d	r I k
wood-	ring
w U d	r I N
wood-	roof
w U d	r u: f
wood-	row
w U d	r @U
wood-	ruff
w U d	r V f
wood-	shed
w U d	S e d
wood-	side
w U d	s aI d
wood-	son
w U d	s V n
wood-	stock
w U d	s t Q k
wood-	ward
w U d	w O@ d
wood-	ward's
w U d	w @r d z
wood-	wind
w U d	w I n d
wood-	winds
w U d	w I n d z
wood-	wor-	ker
w U d	w @r	k @r
wood-	wor-	kers
w U d	w @r	k @r z
wood-	wor-	king
w U d	w @r	k I N
wood-	work
w U d	w @r k
wood-	worth
w U d	w @r T
wood-	yard
w U d	j Q@ d
woodc-	liff
w U d	k l I f
woods
w U d z
wood's
w U d z
woods-	man
w U d	z m { n
woods-	men
w U d	z m V n
wooed
w u: d
woof
w u: f
woof-	ter
w u: f	t @r
wool
w U l
wool-	dridge
w U l	d r I dZ
wool-	ford
w U l	f @r d
wool-	len
w U	l V n
wool-	ley
w U	l i:
wool-	ly
w U	l i:
wool-	man
w U l	m V n
wool-	sey
w U l	z i:
wool-	son
w U l	s V n
wool-	wine
w U l	w aI n
wool-	worth
w U l	w @r T
wool-	worth's
w U l	w @r T s
woolf
w U l f
wools
w U l z
woos
w u: z
woo's
w u: z
woos-	ter
w u: s	t @r
wop
w Q p
wops
w Q p s
wor
w O@
wor-	ded
w @r	d V d
wor-	den
w @r	d V n
wor-	ding
w @r	d I N
wor-	dy
w @r	d i:
wor-	ka-	ble
w @r	k V	b V l
wor-	ka-	day
w @r	k V	d eI
wor-	ka-	ho-	lic
w @r	k V	h Q	l I k
wor-	ka-	ho-	lics
w @r	k V	h Q	l I k s
wor-	ker
w @r	k @r
wor-	kers
w @r	k @r z
wor-	ker's
w @r	k @r z
wor-	kers'
w @r	k @r z
wor-	king
w @r	k I N
wor-	kings
w @r	k I N z
wor-	land
w @r	l V n d
wor-	ley
w @r	l i:
wor-	rel
w @r	r V l
wor-	rell
w @r	r V l
wor-	ri-	er
w @r	i:	@r
wor-	ri-	ers
w @r	i:	@r z
wor-	ri-	some
w @r	i:	s V m
wor-	ried
w @r	i: d
wor-	ries
w @r	i: z
wor-	ry
w @r	i:
wor-	ry-	ing
w @r	i:	I N
wor-	se-	ning
w @r	s V	n I N
wor-	sen
w @r	s V n
wor-	sened
w @r	s V n d
wor-	sens
w @r	s V n z
wor-	sham
w @r	S V m
wor-	shi-	per
w @r	S I	p @r
wor-	shi-	pers
w @r	S I	p @r z
wor-	ship
w @r	S I p
wor-	ship-	ful
w @r	S I p	f V l
wor-	ship-	ping
w @r	S I	p I N
wor-	shiped
w @r	S I p t
wor-	shipped
w @r	S I p t
wor-	ships
w @r	S I p s
wor-	tham
w @r	T V m
wor-	thi-	er
w @r	D i:	@r
wor-	thi-	est
w @r	D i:	V s t
wor-	thi-	ness
w @r	D i:	n V s
wor-	thies
w @r	D i: z
wor-	thing
w @r	T I N
wor-	thing-	ton
w @r	D I N	t V n
wor-	thy
w @r	D i:
wor-	ton
w @r	t V n
worce-	ster
w U s	t @r
word
w @r d
word-	less
w @r d	l V s
word-	per-	fect
w @r d	p @r	f e k t
word-	smith
w @r d	s m I T
word-	star
w @r d	s t Q@
words
w @r d z
word's
w @r d z
words-	worth
w @r d	z w @r T
wore
w O@
work
w @r k
work-	bench
w @r k	b e n tS
work-	day
w @r k	d eI
work-	days
w @r k	d eI z
work-	fare
w @r k	f e@
work-	force
w @r k	f O@ s
work-	group
w @r k	g r u: p
work-	groups
w @r k	g r u: p s
work-	hor-	ses
w @r k	h O@	s V z
work-	horse
w @r k	h O@ s
work-	load
w @r k	l @U d
work-	loads
w @r k	l @U d z
work-	man
w @r k	m V n
work-	man-	like
w @r k	m { n	l aI k
work-	man-	ship
w @r k	m V n	S I p
work-	man's
w @r k	m V n z
work-	men
w @r k	m e n
work-	men's
w @r k	m V n z
work-	out
w @r	k aU t
work-	outs
w @r	k aU t s
work-	pla-	ces
w @r k	p l eI	s V z
work-	place
w @r k	p l eI s
work-	room
w @r k	r u: m
work-	sheet
w @r k	S i: t
work-	sheets
w @r k	S i: t s
work-	shop
w @r k	S Q p
work-	shops
w @r k	S Q p s
work-	sta-	tion
w @r k	s t eI	S V n
work-	sta-	tions
w @r k	s t eI	S V n z
work-	week
w @r k	w i: k
work-	weeks
w @r k	w i: k s
worked
w @r k t
works
w @r k s
work's
w @r k s
worl-	ders
w @r l	d @r z
world
w @r l d
world-	li-	ness
w @r l	d l i:	n V s
world-	ly
w @r l	d l i:
world-	wide
w @r l	d w aI d
worlds
w @r l d z
world's
w @r l d z
worm
w @r m
worm-	like
w @r m	l aI k
worm-	wood
w @r m	w U d
worms
w @r m z
worm's
w @r m z
worn
w O@ n
wors-	ley
w @r s	l i:
wors-	ted
w @r s	t V d
worse
w @r s
worst
w @r s t
worth
w @r T
worth-	less
w @r T	l V s
worth-	while
w @r T	w aI l
worths
w @r T s
worth's
w @r T s
worts
w @r t s
wot-	ton
w Q	t V n
wouk
w u: k
woul-	dn't
w U	d V n t
woul-	d've
w U	d V v
would
w U d
woulfe
w aU l f
woun-	ded
w u: n	d V d
woun-	ding
w u: n	d I N
wound
w aU n d
wounds
w u: n d z
wove
w @U v
wow
w aU
wowed
w aU d
wows
w aU z
woy
w OI
woz-	ni-	ak
v Q z	n i:	{ k
wra-	pup
r {	p V p
wrac-	king
r {	k I N
wrack
r { k
wracked
r { k t
wran-	g-	ler
r { N	g V	l @r
wran-	g-	lers
r { N	g V	l @r z
wran-	g-	ling
r { N	g V	l I N
wran-	gell
r { N	g V l
wran-	gle
r { N	g V l
wran-	gled
r { N	g V l d
wran-	gles
r { N	g V l z
wrap
r { p
wrap-	per
r {	p @r
wrap-	pers
r {	p @r z
wrap-	ping
r {	p I N
wrapped
r { p t
wraps
r { p s
wrath
r { T
wray
r eI
wre-	st-	ler
r e	s V	l @r
wre-	stle
r e	s V l
wre-	stled
r e	s V l d
wre-	stles
r e	s V l z
wre-	tched
r e	tS V d
wre-	tched-	ly
r e	tS V d	l i:
wrea-	king
r i:	k I N
wreak
r i: k
wreaked
r i: k t
wreaks
r i: k s
wreath
r i: T
wreaths
r i: T s
wrec-	kage
r e	k V dZ
wrec-	ker
r e	k @r
wrec-	king
r e	k I N
wreck
r e k
wrecked
r e k t
wrecks
r e k s
wren
r e n
wren-	ches
r e n	tS V z
wren-	ching
r e n	tS I N
wrench
r e n tS
wrenched
r e n tS t
wres-	ted
r e s	t V d
wres-	ting
r e s	t I N
wres-	tling
r e s	l I N
wrest
r e s t
wrest-	lers
r e s	l @r z
wri-	ter
r aI	t @r
wri-	ters
r aI	t @r z
wri-	ter's
r aI	t @r z
wri-	thing
r aI	D I N
wri-	ting
r aI	t I N
wri-	tings
r aI	t I N z
wrig-	gle
r I	g V l
wrig-	ley
r I g	l i:
wrig-	ley's
r I g	l i: z
wright
r aI t
wright-	son
r aI t	s V n
wrights
r aI t s
wright's
r aI t s
wrin-	ger
r I	N @r
wrin-	ging
r I	N I N
wrin-	k-	ling
r I N	k V	l I N
wrin-	kle
r I N	k V l
wrin-	kled
r I N	k V l d
wrin-	kles
r I N	k V l z
wring
r I N
wrist
r I s t
wrist-	wat-	ches
r I s	t w Q	tS V z
wrist-	watch
r I s	t w Q tS
wrists
r I s t s
writ
r I t
writ-	ten
r I	t V n
write
r aI t
write-	down
r aI t	d aU n
write-	off
r aI	t O: f
write-	offs
r aI	t O: f s
writes
r aI t s
writhe
r I T
writs
r I t s
wroc-	law
r Q k	l O:
wrong
r O: N
wrong-	do-	er
r O: N	d u:	@r
wrong-	do-	ers
r O: N	d u:	@r z
wrong-	do-	ing
r O: N	d u:	I N
wrong-	do-	ings
r O: N	d u:	I N z
wrong-	ful
r O: N	f V l
wrong-	ful-	ly
r O: N	f V	l i:
wrong-	hea-	ded
r O: N	h e	d V d
wrong-	ly
r O: N	l i:
wronged
r O: N d
wrongs
r O: N z
wrote
r @U t
wrought
r O: t
wrung
r V N
wry
r aI
wry-	ly
r aI	l i:
wry-	ness
r aI	n V s
wu
w u:
wu-	han
w u:	V n
wu-	the-	ring
w V	D @r	I N
wulf
w U l f
wun-	der
w V n	d @r
wun-	der-	kind
w V n	d @r	k aI n d
wun-	der-	lich
w V n	d @r	l I k
wur-	lit-	zer
w @r	l I t	s @r
wur-	zel
w @r	z V l
wurs-	ter
w @r s	t @r
wurst
w @r s t
wurtz
w @r t s
wu's
w u: z
wuss
w V s
wy
w eI
wy-	att
w aI	V t
wy-	att's
w aI	V t s
wy-	coff
w I	k O: f
wy-	eth
w aI	e T
wy-	koff
w I	k O: f
wy-	ler
w aI	l @r
wy-	lie
w aI	l i:
wy-	ly
w aI	l i:
wy-	man
w aI	m V n
wy-	mer
w aI	m @r
wy-	more
w aI	m O@
wy-	ner
w aI	n @r
wy-	no-	na
w aI	n @U	n V
wy-	o-	ming
w aI	@U	m I N
wy-	o-	ming's
w aI	@U	m I N z
wyc-	koff
w I	k O: f
wye
w aI
wyke
w aI k
wyl-	ma
w aI l	m V
wylde
w aI l d
wyle
w aI l
wyles
w aI l z
wyn-	dham
w I n	d V m
wyne
w aI n
wynn
w I n
wynne
w I n
wynns
w I n z
wynn's
w I n z
wyss
w I s
x
e k s
x-	ers
e k	s e@ z
x-	ray
e k	s r eI
x-	rays
e k	s r eI z
x'-	s
e k	s V z
xa-	nax
z {	n { k s
xa-	vi-	e-	ra
I g	z eI v	j e@	V
xa-	vier
z eI v	j @r
xan-	tippe
z { n	t I p
xanthe
z { n D
xe-	bec
z e	b V k
xe-	na
z i:	n V
xe-	ni-	a
z i:	n i:	V
xe-	no-	pho-	bi-	a
z e	n V	f @U	b i:	V
xe-	no-	pho-	bic
z e	n V	f Q	b I k
xe-	no-	phon
z e	n V	f V n
xe-	non
z i:	n Q n
xe-	nos
z i:	n @U z
xe-	ri-	scape
z e@	I s	k eI p
xe-	ro-	xes
z I@	Q k	s V z
xe-	ro-	xing
z I@	Q k	s I N
xe-	ro-	x's
z I@	Q k	s V z
xe-	rox
z I@	Q k s
xe-	roxed
z I@	Q k s t
xer-	xes
z @r k	s i: z
xi
S i:
xi-	a-	men
z i:	eI	m V n
xian
z j Q n
xiao-	ping
Z aU	p I N
xiao-	ping's
Z aU	p I N z
xie
z i:
xin-	hu-	a
z I n	h j u:	V
xing
S I N
xu
z u:
xy-	li-	a
z aI	l i:	V
xy-	li-	na
z aI	l I	n V
xy-	lo-	phone
z aI	l V	f @U n
xy-	lon
z aI	l V n
y
w aI
y-	vette
I	v e t
y-	vonne
I	v Q n
y-	vonne's
I	v Q n z
y.
w aI
ya
j Q
ya-	ger
j eI	dZ @r
ya-	gi
j Q	g i:
ya-	hi
j Q	h i:
ya-	hoo
j Q	h u:
ya-	hoos
j Q	h u: z
ya-	ki-	ma
j {	k I	m V
ya-	ma-	ga-	ta
j Q	m Q	g Q	t V
ya-	ma-	ha
j Q	m Q	h Q
ya-	ma-	ni
j Q	m Q	n i:
ya-	ma-	shi-	ta
j Q	m Q	S i:	t V
ya-	ma-	to
j Q	m Q	t @U
ya-	ma-	u-	chi
j Q	m Q	u:	tS i:
ya-	ma-	u-	chi's
j Q	m Q	u:	tS i: z
ya-	no-	ma-	mi
j {	n @U	m {	m i:
ya-	ron
j e@	V n
ya-	su-	o
j Q	s u:	@U
yab-	lon
j { b	l V n
yach-	ter
j Q	t @r
yach-	ters
j Q	t @r z
yach-	ting
j Q	t I N
yach-	ting's
j Q	t I N z
yacht
j Q t
yachts
j Q t s
yachts-	man
j Q t	s m V n
yack
j { k
yae-	ger
j i:	dZ @r
yah
j Q
yah-	weh
j Q	w e
yak
j { k
yal-	ta
j O: l	t V
yale
j eI l
yale's
j eI l z
y'all
j O: l
yam
j { m
yams
j { m z
yan
j { n
yan-	cey
j { n	s i:
yan-	cy
j { n	s i:
yan-	kee
j { N	k i:
yan-	kees
j { N	k i: z
yan-	kee's
j { N	k i: z
yan-	king
j { N	k I N
yan-	tis
j { n	t I s
yang
j { N
yangt-	ze
j { N	k t s i:
yank
j { N k
yanked
j { N k t
yanks
j { N k s
yao
j aU
yao-	bang
j aU	b { N
yap
j { p
yapp
j { p
yaps
j { p s
yar-	bo-	rough
j Q@	b @r	@U
yar-	dage
j Q@	d I dZ
yar-	der
j Q@	d @r
yar-	mul-	ke
j Q@	m V l	k V
yar-	mul-	kes
j Q@	m V l	k V s
yar-	nell
j Q@	n V l
yar-	row
j e@	@U
yar-	wood
j Q@	w U d
yard
j Q@ d
yard-	ley
j Q@ d	l i:
yard-	stick
j Q@ d	s t I k
yard-	sticks
j Q@ d	s t I k s
yards
j Q@ d z
yard's
j Q@ d z
yarn
j Q@ n
yarns
j Q@ n z
yas-	min
j { z	m I n
yas-	mine
j { z	m I n
yates
j eI t s
yau-	pon
j O:	p V n
yau-	pons
j O:	p V n z
yaw
j O:
yaw-	ner
j O:	n @r
yaw-	ning
j O:	n I N
yawn
j O: n
yawned
j O: n d
yawns
j O: n z
yay
j eI
ye
j i:
ye-	hu-	di
j eI	h u:	d i:
ye-	ka-	te-	rin-	burg
j e	k {	t @r	i: n	b V r g
ye-	le-	na
j e	l I	n V
ye-	me-	ni
j e	m V	n i:
ye-	men
j e	m V n
ye-	men's
j e	m V n z
ye-	o
j i:	@U
ye-	re-	van
j e@	V	v V n
ye-	ses
j e	s V z
ye-	shi-	va
j I	S i:	v V
ye-	vette
j I	v e t
yea
j eI
yea-	ger
j eI	g @r
yea-	rend
j I@	e n d
yea-	ton
j i:	t V n
yeah
j {
year
j I@
year-	book
j I@	b U k
year-	books
j I@	b U k s
year-	end
j I@	e n d
year-	gain
j I	g eI n
year-	ling
j I	l I N
year-	lings
j I	l I N z
year-	long
j I@	l O: N
year-	ly
j I@	l i:
year-	ning
j @r	n I N
year-	nings
j @r	n I N z
year-	wood
j I@	w U d
yearn
j @r n
yearned
j @r n d
yearns
j @r n z
years
j I@ z
year's
j I@ z
years'
j I@ z
yeas
j eI z
yeast
j i: s t
yeasts
j i: s t s
yeats
j eI t s
yee
j i:
yeh
j e
yel-	ling
j e	l I N
yel-	lo-	wer
j e	l @U	@r
yel-	lo-	west
j e	l @U	V s t
yel-	lo-	wing
j e	l @U	I N
yel-	lo-	wish
j e	l @U	I S
yel-	low
j e	l @U
yel-	low-	knife
j e	l @U	n aI f
yel-	low-	stone
j e	l @U s	t @U n
yel-	low-	stone's
j e	l @U s	t @U n z
yel-	lows
j e	l @U z
yell
j e l
yelled
j e l d
yells
j e l z
yelt-	sin
j e l	t s I n
yen
j e n
yen-	der
j e n	d @r
yen-	tl
j e n	t V l
yen's
j e n z
yeo-	man
j @U	m V n
yep
j e p
yer-	kes
j @r	k i: z
yer-	xa
j @r k	s V
yes
j e s
yes-	ter-	day
j e s	t @r	d eI
yes-	ter-	days
j e s	t @r	d eI z
yes-	ter-	day's
j e s	t @r	d eI z
yes-	ter-	year
j e s	t @r	j I@
yet
j e t
yet-	ta
j e	t V
yet-	ter
j e	t @r
yett
j e t
yeung
j u: N
yev-	tu-	shen-	ko
j e v	t I	S e N	k @U
yew
j u:
yew's
j u: z
yi
j i:
yid-	dish
j I	d I S
yiel-	ded
j i: l	d V d
yiel-	ding
j i: l	d I N
yield
j i: l d
yields
j i: l d z
yim
j I m
yin
j I n
yip
j I p
yip-	pee
j I	p i:
ynez
j n e z
yo
j @U
yo-	de-	ling
j @U	d V	l I N
yo-	del
j @U	d V l
yo-	der
j @U	d @r
yo-	ga
j @U	g V
yo-	gi
j @U	g i:
yo-	gurt
j @U	g @r t
yo-	ho
j @U	h @U
yo-	kel
j @U	k e l
yo-	ko
j @U	k @U
yo-	ko-	ha-	ma
j @U	k V	h Q	m V
yo-	ko-	ya-	ma
j @U	k @U	j Q	m V
yo-	kum
j @U	k V m
yo-	la
j @U	l V
yo-	lan-	da
j @U	l Q n	d V
yo-	lande
j @U	l V n d
yo-	na
j @U	n V
yo-	se-	mi-	te
j @U	s e	m I	t i:
yo-	shi
j @U	S i:
yo-	shi-	o
j @U	S i:	@U
yo-	yo
j @U	j @U
yo-	yos
j @U	j @U z
yoa-	kum
j @U	k V m
yoe
j @U
yoke
j @U k
yoked
j @U k t
yokes
j @U k s
yolk
j @U k
yolks
j @U k s
yom
j Q m
yon
j Q n
yon-	der
j Q n	d @r
yon-	ker
j Q N	k @r
yon-	kers
j Q N	k @r z
yong
j O: N
yoo
j u:
yor-	ker
j O@	k @r
yor-	kers
j O@	k @r z
yor-	ker's
j O@	k @r z
yore
j O@
york
j O@ k
york-	shire
j O@ k	S @r
york-	town
j O@ k	t aU n
york-	town's
j O@ k	t aU n z
yorke
j O@ k
yorks
j O@ k s
york's
j O@ k s
yost
j @U s t
you
j u:
)"
R"(you'd
j u: d
you'll
j u: l
youn-	ger
j V N	g @r
youn-	gers
j V N	g @r z
youn-	gest
j V N	g V s t
youn-	ker
j V N	k @r
youn-	kers
j V N	k @r z
young
j V N
young-	love
j V N	l V v
young-	man
j V N	m { n
young-	ster
j V N	s t @r
young-	sters
j V N	s t @r z
young-	ster's
j V N	s t @r z
youngs
j V N z
young's
j V N z
youngs-	town
j V N	z t aU n
your
j O@
your-	self
j @r	s e l f
your-	selves
j U@	s e l v z
you're
j U@
yours
j U@ z
youse
j aU s
youth
j u: T
youth-	ful
j u: T	f V l
youths
j u: D z
youth's
j u: T s
you've
j u: v
yow
j aU
yoy
j OI
yp-	si-	lan-	ti
I p	s I	l { n	t i:
yq-	uem
i: k	w V m
y's
w aI z
ytt-	ri-	um
I t	r i:	V m
yu
j u:
yu-	an
j u:	Q n
yu-	an's
j u:	Q n z
yu-	ba
j u:	b V
yu-	ca-	tan
j u:	k V	t { n
yu-	cai-	pa
j u:	k aI	p V
yu-	go
j u:	g @U
yu-	go's
j u:	g @U z
yu-	gos-	la-	vi-	a
j u:	g @U s	l Q	v i:	V
yu-	gos-	la-	vi-	an
j u:	g @U s	l Q	v i:	V n
yu-	gos-	la-	vi-	a's
j u:	g @U s	l Q	v i:	V z
yu-	gos-	lav
j u:	g @U s	l Q v
yu-	gos-	lavs
j u:	g @U s	l { v z
yu-	has
j u:	h V z
yu-	ki-	o
j u:	k i:	@U
yu-	ko
j u:	k @U
yu-	kon
j u:	k Q n
yu-	ma
j u:	m V
yu-	ri
j U@	i:
yuc-	ca
j V	k V
yuc-	ky
j V	k i:
yuck
j V k
yue
j u:
yuille
j u: l
yuk
j V k
yuks
j V k s
yul
j V l
yule
j u: l
yule-	tide
j u: l	t aI d
yum
j V m
yum-	mies
j V	m i: z
yum-	my
j V	m i:
yun
j V n
yun-	ker
j V N	k @r
yung
j V N
yup
j V p
yup-	pi-	fied
j V	p I	f aI d
yup-	pi-	fy
j V	p I	f aI
yup-	pie
j V	p i:
yup-	pies
j V	p i: z
yurt
j U@ t
yu's
j u: z
yves
i: v
z
z i:
za-	ca-	ri-	as
z Q	k Q@	i:	V z
za-	cek
z Q	tS e k
za-	cha-	ri-	ah
z {	k @r	aI	V
za-	cha-	ri-	as
z {	k @r	aI	V s
za-	cha-	ry
z {	k @r	i:
za-	char
z V	k Q@
za-	che-	ry
z {	k @r	i:
za-	chow
z Q	k @U
za-	dar
z eI	d Q@
za-	doc
z Q	d V k
za-	dok
z Q	d V k
za-	greb
z Q g	r e b
za-	greb's
z Q g	r e b z
za-	hir
z V	h I@
za-	i-	ri-	an
z aI	I@	i:	V n
za-	i-	ri-	ans
z aI	I@	i:	V n z
za-	le-	ski
z V	l e s	k i:
za-	man
z eI	m V n
za-	mo-	ra
z V	m O@	V
za-	ne-	ta
z Q	n e	t V
za-	nel-	la
z V	n e	l V
za-	ni-	est
z eI	n i:	V s t
za-	no-	ni
z Q	n @U	n i:
za-	nu
z Q	n u:
za-	nuck
z {	n V k
za-	ny
z eI	n i:
za-	pa-	ta
z Q	p Q	t V
za-	ra
z {	r V
za-	ra-	go-	za
z Q@	Q	g @U	z V
za-	rah
z {	r V
za-	rem-	ski
z @r	e s	k i:
za-	ri-	a
z Q@	i:	V
za-	va-	la
z Q	v Q	l V
zac-	ca-	ri-	a
z Q	k Q@	i:	V
zach
z { k
zack
z { k
zacks
z { k s
zack's
z { k s
zaf-	tig
z { f	t I g
zag
z { g
zagged
z { g d
zags
z { g z
zai-	ba-	tsu
z eI	b { t	s u:
zai-	re
z aI	I@
zai-	re-	an
z aI	I@	V n
zai-	re-	ans
z aI	I@	V n z
zai-	re-	an's
z aI	I@	V n z
zai-	re's
z aI	I@ z
zai-	tech
z eI	t e k
zaid
z eI d
zak
z { k
zal-	man
z Q l	m V n
zam-	bi-	a
z { m	b i:	V
zam-	bi-	an
z { m	b i:	V n
zam-	bi-	a's
z { m	b i:	V z
zam-	bo
z { m	b @U
zam-	boan-	ga
z { m	b @U N	g V
zam-	pi-	no
z Q m	p i:	n @U
zan-	der
z { n	d @r
zan-	ders
z { n	d @r z
zan-	dra
z { n	d r V
zan-	tac
z { n	t { k
zan-	zi-	bar
z { n	z I	b Q@
zandt
z { n t
zane
z eI n
zant
z { n t
zap
z { p
zap-	pa
z {	p V
zap-	pa's
z {	p V z
zap-	ping
z {	p I N
zapped
z { p t
zaps
z { p s
zared
z e@ d
zas-	low
z Q s	l @U
ze
z i:
ze-	bu-	lon
z i:	b V	l V n
ze-	de-	ki-	ah
z e	d V	k aI	V
ze-	dong
z eI	d O: N
ze-	laz-	ny
z V	l Q z	n i:
ze-	los
z i:	l @U z
ze-	lotes
z e	l V t s
ze-	na
z i:	n V
ze-	nai-	da
z V	n eI	d V
ze-	nas
z i:	n V z
ze-	ni-	a
z eI	n i:	V
ze-	nith
z i:	n I T
ze-	nith's
z i:	n I T s
ze-	no
z eI	n @U
ze-	no-	bi-	a
z V	n @U	b i:	V
ze-	ro
z I@	@U
ze-	ro-	ing
z i:	r @U	I N
ze-	roed
z I@	@U d
ze-	roes
z I@	@U z
ze-	ros
z I@	@U z
ze-	ro's
z I@	@U z
ze-	ta
z eI	t V
zea
z i:
zea-	lan-	der
z i:	l V n	d @r
zea-	lan-	ders
z i:	l V n	d @r z
zea-	land
z i:	l V n d
zea-	land's
z i:	l V n d z
zea-	lot
z e	l V t
zea-	lot-	ry
z e	l V t	r i:
zea-	lots
z e	l V t s
zea-	lous
z e	l V s
zea-	lous-	ly
z i:	l V s	l i:
zeal
z i: l
zeb-	ra
z i: b	r V
zeb-	ras
z i: b	r V z
zech
z e k
zed
z e d
zee
z i:
zee-	brug-	ge
z i: b	r u:	g i:
zee-	land
z i:	l V n d
zee-	man
z i:	m V n
zef-	fi-	rel-	li
z e	f I	r e	l i:
zeh-	ner
z e	n @r
zei-	g-	ler
z aI	g V	l @r
zei-	ger
z aI	g @r
zei-	ler
z aI	l @r
zei-	t-	ler
z aI	t V	l @r
zeid-	man
z aI d	m V n
zeiss
z aI s
zeit-	geist
th s aI t	g aI s t
zeke
z i: k
zel
z e l
zel-	da
z e l	d V
zel-	ler-	bach
z e	l @r	b Q k
zel-	ma
z e l	m V
zell
z e l
zell-	ner
z e l	n @r
zelle
z e l
zen
z e n
zen-	da
z e n	d V
zen-	ger
z i: n	dZ @r
zens
z e n z
zent-	ner
z e n	t n @r
zep-	pe-	lin
z e	p V	l V n
zer-	li-	na
z @r	l i:	n V
zest
z e s t
zest-	ful
z e s	t f V l
zeus
z u: s
zhang
Z { N
zhi-	va-	go
Z I	v Q	g @U
zhiv-	kov
Z I v	k Q v
zhou
z u:
zi-	a
z i:	V
zi-	a's
z i:	V z
zi-	ma
z i:	m V
zi-	o-	ni-	sm
z aI	V	n I	z V m
zi-	o-	nist
z aI	V	n I s t
zi-	o-	nists
z aI	V	n I s t s
zi-	on
z aI	V n
zi-	ons
z aI	V n z
zi-	ta
z i:	t V
zi-	ther
z I	D @r
zi-	thers
z I	D @r z
zie-	ger
z i:	g @r
zieg-	ler
z i: g	l @r
ziff
z I f
ziff's
z I f s
zig
z I g
zig-	gu-	rat
z I	g @r	{ t
zig-	gu-	rats
z I	g @r	{ t s
zig-	zag
z I g	z { g
zig-	zag-	ging
z I g	z {	g I N
zig-	zagged
z I g	z { g d
zig-	zags
z I g	z { g z
zil-	ber
z I l	b @r
zil-	la
z I	l V
zil-	lah
z I	l V
zil-	lio-	naire
z I l	j V	n e@
zil-	lion
z I l	j V n
zil-	lions
z I l	j V n z
zil-	vi-	a
z I l	v i:	V
zilch
z I l tS
zill
z I l
zim
z I m
zim-	ba-	list
z I m	b V	l I s t
zim-	bab-	we
z I m	b Q b	w eI
zim-	bab-	we-	an
z I m	b Q b	w i:	V n
zim-	bab-	we's
z I m	b Q b	w eI z
zim-	mer
z I	m @r
zim-	mer-	man
z I	m @r	m V n
zim-	mer-	mann
z I	m @r	m V n
zim-	mers
z I	m @r z
zin-	der
z I n	d @r
zin-	fan-	del
z I n	f V n	d e l
zin-	ga-	le
z I N	g Q	l i:
zin-	ga-	ro
z I N	g Q@	@U
zin-	ger
z I	N @r
zin-	man
z I n	m V n
zin-	ni-	a
z I	n i:	V
zin-	ni-	as
z I	n i:	V z
zinc
z I N k
zinck
z I N k
zine
z aI n
zines
z aI n z
zing
z I N
zingg
z I N g
zink
z I N k
zinke
z I N k
zinn
z I n
zins
z I n z
zip
z I p
zip-	less
z I p	l V s
zip-	pe-	ring
z I	p @r	I N
zip-	per
z I	p @r
zip-	pered
z I	p @r d
zip-	pers
z I	p @r z
zip-	ping
z I	p I N
zip-	po
z I	p @U
zip-	po-	ra
z i:	p O@	V
zip-	py
z I	p i:
zipped
z I p t
zips
z I p s
zir-	co-	ni-	um
z @r	k @U	n i:	V m
zir-	co-	ni-	ums
z @r	k @U	n i:	V m z
zir-	con
z @r	k V n
zir-	cons
z @r	k Q n z
zir-	kle
z @r	k V l
zis-	ka
z I s	k V
ziv
z I v
zlo-	ty
z l O:	t i:
zlo-	tys
z l O:	t i: z
zo-	cor
z @U	k @r
zo-	di-	ac
z @U	d i:	{ k
zo-	e
z @U	i:
zo-	la
z @U	l V
zo-	loft
z Q	l Q f t
zo-	na
z @U	n V
zo-	ning
z @U	n I N
zo-	o-	lo-	gist
z @U	Q	l V	dZ V s t
zo-	o-	lo-	gy
z @U	Q	l V	dZ i:
zo-	ra
z O@	V
zo-	ra-	na
z O@	{	n V
zo-	rah
z O@	V
zo-	ri-	na
z O@	i:	n V
zo-	ri-	ne
z O@	i:	n i:
zo-	vi-	rax
z @U	v I@	{ k s
zob-	rist
z Q b	r I s t
zoel-	ler
z @U	l @r
zoel-	lick
z @U	l I k
zol-	ler
z Q	l @r
zoll
z Q l
zoll-	ner
z Q l	n @r
zom-	bie
z Q m	b i:
zom-	bies
z Q m	b i: z
zone
z @U n
zoned
z @U n d
zones
z @U n z
zoo
z u:
zoo-	lo-	gi-	cal
z u:	l Q	dZ I	k V l
zoo-	ming
z u:	m I N
zoom
z u: m
zoomed
z u: m d
zooms
z u: m z
zoos
z u: z
zoo's
z u: z
zor-	ro
z O@	@U
zorn
z O@ n
zort-	man
z O@ t	m V n
zos-	ter
z Q s	t @r
z's
z i: z
zsa
Z Q
zsa-	zsa
Z Q	Z Q
zu-	ker-	man
z u:	k @r	m V n
zu-	lu
z u:	l u:
zu-	lus
z u:	l u: z
zu-	ni
z u:	n i:
zu-	pan
z u:	p V n
zu-	rek
z U@	e k
zu-	rich
z U@	I k
zu-	rich's
z U@	I k s
zu-	za-	na
z u:	z Q	n V
zuc-	ca-	ro
z u:	k Q@	@U
zuc-	chi-	ni
z u:	k i:	n i:
zuc-	co
z u:	k @U
zuc-	ker
z V	k @r
zuc-	ker-	man
z V	k @r	m V n
zuc-	ker-	man's
z V	k @r	m V n z
zuc-	ker's
z V	k @r z
zug
z V g
zug's
z V g z
zul-	lo
z u:	l @U
zum-	stein
z V m	s t i: n
zum-	walt
z V m	w V l t
zurn
z @r n
zwart
z w O@ t
zweig
z w aI g
zwic-	ky
z w I	k i:
zwick
z w I k
zwie-	bel
z w i:	b V l
zy-	de-	co
z aI	d e	k @U
zy-	gote
z aI	g @U t
zysk
z aI s k
zyu-	ga-	nov
z j u:	g Q	n Q v
zyu-	ga-	nov's
z j u:	g Q	n Q v z
)"