R"(tiz-	zy
th I	z i:
tja-	den
dZ eI	d V n
tlin-	git
th l i: N	g I t
to
th u:
to-	a
th @U	V
to-	ba-	go
th V	b eI	g @U
to-	bac-	co
th V	b {	k @U
to-	bac-	cos
th V	b {	k @U z
to-	bac-	co's
th V	b {	k @U z
to-	back
tS u:	b { k
to-	bey
th @U	b i:
to-	bi-	as
th V	b aI	V s
to-	bie
th @U	b i:
to-	bin
th @U	b I n
to-	bog-	gan
th V	b Q	g V n
to-	bog-	gans
th V	b Q	g V n z
to-	by
th @U	b i:
to-	da
th @U	d V
to-	day
th V	d eI
to-	day'll
th V	d eI l
to-	days
th V	d eI z
to-	day's
th V	d eI z
to-	fu
th @U	f u:
to-	ga
th @U	g V
to-	ge-	ther
th V	g e	D @r
to-	ge-	ther-	ness
th V	g e	D @r	n V s
to-	ge-	thers
th V	g e	D @r z
to-	go
th @U	g @U
to-	ke-	ni-	sm
th @U	k V	n I	z V m
to-	ken
th @U	k V n
to-	kens
th @U	k V n z
to-	ki-	o
th @U	k i:	@U
to-	kos
th @U	k @U s
to-	ky-	o
th @U	k i:	@U
to-	ky-	o's
th @U	k i:	@U z
to-	lan
th @U	l V n
to-	land
th @U	l V n d
to-	lar
th @U	l @r
to-	le-	do
th V	l i:	d @U
to-	le-	ra-	ble
th Q	l @r	V	b V l
to-	le-	ra-	ted
th Q	l @r	eI	t V d
to-	le-	ra-	ting
th Q	l @r	eI	t I N
to-	le-	ra-	tion
th Q	l @r	eI	S V n
to-	le-	ran-	ces
th Q	l @r	V n	s V z
to-	le-	rance
th Q	l @r	V n s
to-	le-	rant
th Q	l @r	V n t
to-	le-	rate
th Q	l @r	eI t
to-	le-	rates
th O:	l @r	eI t s
to-	ler
th @U	l @r
to-	ma
th @U	m V
to-	ma-	hawk
th Q	m V	h O: k
to-	ma-	hawks
th Q	m V	h O: k s
to-	ma-	si-	na
th O:	m V	s i:	n V
to-	ma-	si-	ne
th @U	m Q	s i:	n i:
to-	ma-	so
th @U	m Q	s @U
to-	ma-	to
th V	m eI	t @U
to-	ma-	toes
th V	m eI	t @U z
to-	man
th @U	m V n
to-	mas
th @U	m Q s
to-	mor-	row
th V	m Q@	@U
to-	mor-	rows
th V	m Q@	@U z
to-	mor-	row's
th V	m Q@	@U z
to-	na-	li-	ties
th @U	n {	l I	t i: z
to-	na-	li-	ty
th @U	n {	l I	t i:
to-	na-	wan-	da
th Q	n V	w Q n	d V
to-	nal
th @U	n V l
to-	ner
th @U	n @r
to-	ney
th @U	n i:
to-	ni
th @U	n i:
to-	ni-	a
th @U	n i:	V
to-	ni-	est
th @U	n i:	V s t
to-	nic
th Q	n I k
to-	nics
th Q	n I k s
to-	nie
th @U	n i:
to-	night
th V	n aI t
to-	night's
th V	n aI t s
to-	ning
th @U	n I N
to-	nite
th V	n aI t
to-	ny
th @U	n i:
to-	nys
th @U	n i: z
to-	ny's
th @U	n i: z
to-	pan-	ga
th V	p { n	g V
to-	paz
th @U	p { z
to-	pe-	ka
th V	p i:	k V
to-	pe-	ka's
th V	p i:	k V z
to-	pete
th Q	p i: t
to-	pi-	a-	ry
th @U	p i:	e@	i:
to-	pi-	cal
th Q	p I	k V l
to-	pic
th Q	p I k
to-	pics
th Q	p I k s
to-	po-	gra-	phic
th Q	p V g	r {	f I k
to-	po-	gra-	phy
th V	p Q g	r V	f i:
to-	pol-	ski
th V	p @U l	s k i:
to-	rah
th O@	V
to-	ran
th O@	Q n
to-	rel-	li
th O@	e	l i:
to-	rey
th O@	i:
to-	ri
th O@	i:
to-	ri-	no
th O@	i:	n @U
to-	rie
th O@	i:
to-	ries
th O@	i: z
to-	ro
th O@	@U
to-	ro-	sian
th @r	Q	Z V n
to-	ron-	to
th @r	Q n	t @U
to-	ron-	to's
th @r	Q n	t @U z
to-	ru
th O@	u:
to-	ry
th O@	i:
to-	shi-	ba
th @U	S i:	b V
to-	shi-	ba's
th @U	S i:	b V z
to-	si
th @U	s i:
to-	ta-	li-	ta-	ri-	a-	ni-	sm
th @U	t {	l I	t e@	i:	V	n I	z V m
to-	ta-	li-	ta-	ri-	an
th @U	t {	l I	t e@	i:	V n
to-	ta-	li-	ta-	ri-	ans
th @U	t {	l I	t e@	i:	V n z
to-	ta-	li-	ty
th @U	t {	l I	t i:
to-	ta-	ling
th @U	t V	l I N
to-	tal
th @U	t V l
to-	tal-	ling
th @U	t V	l I N
to-	tal-	ly
th @U	t V	l i:
to-	taled
th @U	t V l d
to-	talled
th @U	t V l d
to-	tals
th @U	t V l z
to-	tal's
th @U	t V l z
to-	ted
th @U	t V d
to-	tem
th @U	t V m
to-	tems
th @U	t V m z
to-	ti
th @U	t i:
to-	ting
th @U	t I N
to-	to
th @U	t @U
to-	var
th @U	v Q@
to-	vey
th @U	v i:
to-	ward
th V	w O@ d
to-	wards
th V	w O@ d z
to-	we-	ling
th aU	V	l I N
to-	we-	ry
th @U	@r	i:
to-	wel
th aU	V l
to-	wels
th aU	V l z
to-	wer
th aU	@r
to-	wer-	ing
th aU	@r	I N
to-	wered
th aU	@r d
to-	wers
th aU	@r z
to-	wer's
th aU	@r z
to-	wing
th @U	I N
to-	xi-	ci-	ty
th Q k	s I	s I	t i:
to-	xi-	co-	lo-	gi-	cal
th Q k	s I	k V	l Q	dZ I	k V l
to-	xi-	co-	lo-	gist
th Q k	s I	k Q	l V	dZ I s t
to-	xi-	co-	lo-	gists
th Q k	s I	k Q	l V	dZ I s t s
to-	xi-	co-	lo-	gy
th Q k	s I	k Q	l V	dZ i:
to-	xic
th Q k	s I k
to-	xics
th Q k	s I k s
to-	xin
th Q k	s I n
to-	xins
th Q k	s I n z
to-	ya-	ma
th @U	j Q	m V
to-	yo
th @U	j @U
to-	yo-	da
th @U	j @U	d V
to-	yo-	ta
th @U	j @U	t V
to-	yo-	tas
th OI	@U	t V z
to-	yo-	ta's
th @U	j @U	t V z
to-	zer
th @U	z @r
toad
th @U d
toads
th @U d z
toas-	ted
th @U s	t V d
toas-	ter
th @U s	t @r
toas-	ters
th @U s	t @r z
toas-	ting
th @U s	t I N
toast
th @U s t
toast-	mas-	ter
th @U s	t m { s	t @r
toasts
th @U s t s
tobe
th @U b
toc-	ci
th @U	tS i:
tock
th Q k
tocque-	ville
th @U k	v I l
tod
th Q d
tod-	dle
th Q	d V l
tod-	hun-	ter
th Q d	h V n	t @r
todd
th Q d
todd-	ler
th Q d	l @r
todd-	lers
th Q d	l @r z
todd-	ling
th Q d	l I N
todd's
th Q d z
todt
th Q d t
toe
th @U
toe-	hold
th @U	h @U l d
toe-	ing
th @U	I N
toe-	nail
th @U	n eI l
toe-	nails
th @U	n eI l z
toed
th @U d
toes
th @U z
tof-	fee
th Q	f i:
toft
th Q f t
tofte
th @U f t
tog-	gle
th Q	g V l
tog-	gled
th Q	g V l d
togg-	ling
th Q g	l I N
togs
th Q g z
toi-	let
th OI	l V t
toi-	let-	ries
th OI	l V t	r i: z
toi-	let-	ry
th OI	l V t	r i:
toi-	lets
th OI	l V t s
toi-	ling
th OI	l I N
toi-	ty
th OI	t i:
toil
th OI l
toiled
th OI l d
toils
th OI l z
tol-	bert
th @U l	b @r t
tol-	land
th Q	l V n d
tol-	land's
th Q	l V n d z
tol-	le-	son
th Q	l V	s V n
tol-	ler
th @U	l @r
tol-	ley
th Q	l i:
tol-	li-	ver
th @U	l I	v @r
tol-	ling
th @U	l I N
tol-	ly
th @U	l i:
tol-	man
th Q l	m V n
told
th @U l d
tole
th @U l
toles
th @U l z
toll
th @U l
toll-	booth
th @U l	b u: T
tolled
th @U l d
tolls
th @U l z
tols-	toy
th @U l	s t OI
tols-	toy's
th @U l	s t OI z
tom
th Q m
tom-	boy
th Q m	b OI
tom-	cat
th Q m	k { t
tom-	kin
th Q m	k I n
tom-	kins
th Q m	k I n z
tom-	lin
th Q m	l I n
tom-	lin-	son
th Q m	l I n	s V n
tom-	mie
th Q	m i:
tom-	my
th Q	m i:
tom-	my's
th Q	m i: z
tomb
th u: m
tomb-	like
th u: m	l aI k
tomb-	stone
th u: m	s t @U n
tomb-	stones
th u: m	s t @U n z
tombs
th u: m z
tome
th @U m
tomes
th @U m z
tomp-	kins
th Q m	p k I n z
toms
th Q m z
tom's
th Q m z
ton
th V n
ton-	jes
th @U n	j e s
ton-	ka
th Q N	k V
ton-	kin
th Q N	k I n
ton-	na-	ges
th V	n V	dZ V z
ton-	nage
th V	n V dZ
ton-	ner
th V	n @r
ton-	sil
th Q n	s I l
ton-	sil-	lec-	to-	mies
th Q n	s I	l e k	t V	m i: z
ton-	sil-	lec-	to-	my
th Q n	s I	l e k	t V	m i:
ton-	sils
th Q n	s I l z
ton-	ya
th Q n	j V
ton-	ya's
th Q n	j V z
tone
th @U n
toned
th @U n d
tones
th @U n z
tong
th O: N
tongs
th Q N z
tongue
th V N
tongued
th V N d
tongues
th V N z
tonk
th O: N k
tonks
th Q N k s
tonn
th Q n
tonne
th V n
tonnes
th V n z
tons
th V n z
too
th u:
too-	good
th u:	g U d
too-	ley
th u:	l i:
too-	ling
th u:	l I N
too-	mer
th u:	m @r
too-	mey
th u:	m i:
too-	thy
th u:	T i:
too-	tle
th u:	t V l
took
th U k
tooke
th U k
tool
th u: l
tool-	box
th u: l	b O: k s
tool-	ma-	ker
th u: l	m eI	k @r
tool-	ma-	kers
th u: l	m eI	k @r z
tool-	room
th u: l	r u: m
toole
th u: l
tooled
th u: l d
tools
th u: l z
toombs
th u: m z
toon
th u: n
toone
th u: n
toot
th u: t
toot-	sie
th u: t	s i:
tooth
th u: T
tooth-	bru-	shes
th u: T	b r V	S V z
tooth-	brush
th u: T	b r V S
tooth-	less
th u: T	l V s
tooth-	like
th u: T	l aI k
tooth-	paste
th u: T	p eI s t
tooth-	pastes
th u: T	p eI s t s
tooth-	pick
th u: T	p I k
tooth-	picks
th u: T	p I k s
toothed
th u: T t
toots
th u: t s
top
th Q p
top-	knot
th Q p	n Q t
top-	less
th Q p	l V s
top-	p-	ling
th Q	p V	l I N
top-	per
th Q	p @r
top-	pers
th Q	p @r z
top-	ping
th Q	p I N
top-	pings
th Q	p I N z
top-	ple
th Q	p V l
top-	pled
th Q	p V l d
top-	ples
th Q	p V l z
top-	soil
th Q p	s OI l
top-	sy
th Q p	s i:
top-	sy-	tur-	vy
th Q p	s i:	t @r	v i:
tope
th @U p
topped
th Q p t
tops
th Q p s
tor
th O@
tor-	bert
th O@	b @r t
tor-	ches
th O@	tS V z
tor-	ching
th O@	tS I N
tor-	ma
th O@	m V
tor-	men-	ta
th O@	m e n	t V
tor-	men-	ted
th O@	m e n	t V d
tor-	men-	ting
th O@	m e n	t I N
tor-	men-	tor
th O@	m e n	t @r
tor-	men-	tors
th O@	m e n	t @r z
tor-	ment
th O@	m e n t
tor-	ments
th O@	m e n t s
tor-	na-	dic
th O@	n eI	d I k
tor-	na-	do
th O@	n eI	d @U
tor-	na-	does
th O@	n eI	d @U z
tor-	na-	dos
th O@	n eI	d @U z
tor-	na-	do's
th O@	n eI	d @U z
tor-	ney
th O@	n i:
tor-	pe-	do
th O@	p i:	d @U
tor-	pe-	do-	ing
th O@	p i:	d @U	I N
tor-	pe-	doed
th O@	p i:	d @U d
tor-	pe-	does
th O@	p i:	d @U z
tor-	pe-	dos
th O@	p i:	d @U z
tor-	pid
th O@	p I d
tor-	por
th O@	p @r
tor-	rance
th O@	V n s
tor-	ras
th O@	V s
tor-	ray
th O@	eI
tor-	re-	on
th O@	i:	V n
tor-	ren-	tial
th O@	e n	tS V l
tor-	rence
th O@	V n s
tor-	rens
th O@	V n z
tor-	rent
th O@	V n t
tor-	rents
th O@	V n t s
tor-	res
th O@	e z
tor-	rey
th O@	i:
tor-	ri-	cel-	li
th O@	I	s e	l i:
tor-	rid
th O@	I d
tor-	ring-	ton
th O@	I N	t V n
tor-	ry
th O@	i:
tor-	so
th O@	s @U
tor-	sos
th O@	s @U z
tor-	til-	la
th O@	t i:	V
tor-	til-	las
th O@	t i:	V z
tor-	toi-	ses
th O@	t V	s V z
tor-	toise
th O@	t V s
tor-	tu-	ous
th O@	tS V	w V s
tor-	tu-	rous
th O@	tS u:	V s
tor-	tur-	ing
th O@	tS @r	I N
tor-	ture
th O@	tS @r
tor-	tured
th O@	tS @r d
tor-	tures
th O@	tS @r z
torch
th O@ tS
torched
th O@ tS t
tore
th O@
torn
th O@ n
torp
th O@ p
torque
th O@ k
torr
th O@
torre
th O@
tort
th O@ t
torte
th O@ t
torts
th O@ t s
tos-	ca
th O: s	k V
tos-	ca-	ni-	ni
th O: s	k V	n i:	n i:
tos-	ca-	ni-	ni's
th V s	k V	n i:	n i: z
tos-	ca-	no
th @U s	k Q	n @U
tos-	ses
th O:	s V z
tos-	sing
th O:	s I N
tos-	ta-	do
th @U s	t Q	d @U
tosch
th O: S
tosh
th Q S
toss
th O: s
tossed
th O: s t
tot
th Q t
tot-	ten
th Q	t V n
tot-	ter
th Q	t @r
tot-	ter-	ing
th Q	t @r	I N
tot-	ty
th Q	t i:
tote
th @U t
totes
th @U t s
toth
th Q T
tots
th Q t s
tou-	a-	reg
th u:	@r	V g
tou-	ches
th V	tS V z
tou-	chet
th u:	S e t
tou-	ching
th V	tS I N
tou-	chy
th V	tS i:
tou-	ga-	loo
th u:	g V	l u:
tou-	ghe-	ning
th V	f V	n I N
tou-	ghen
th V	f V n
tou-	ghened
th V	f V n d
tou-	ghens
th V	f V n z
tou-	gher
th V	f @r
tou-	ghest
th V	f V s t
tou-	louse
th u:	l u: z
tou-	pee
th u:	p eI
tou-	rette
th @r	e t
tou-	rette's
th @r	e t s
tou-	ri-	sm
th U@	I	z V m
tou-	ring
th U@	I N
tou-	rist
th U@	I s t
tou-	rists
th U@	I s t s
tou-	ted
th aU	t V d
tou-	ting
th aU	t I N
touch
th V tS
touch-	down
th V tS	d aU n
touch-	downs
th V tS	d aU n z
touch-	stone
th V tS	s t @U n
touche
th u: S
touched
th V tS t
tough
th V f
tough-	ness
th V f	n V s
toughed
th V f t
toughs
th V f s
tour
th U@
tour-	ma-	line
th U@	m V	l i: n
tour-	na-	ment
th U@	n V	m V n t
tour-	na-	ments
th @r	n V	m V n t s
tour-	na-	ment's
th U@	n V	m V n t s
tour-	ney
th @r	n i:
tour-	neys
th u: r	n i: z
tour-	ni-	quet
th @r	n I	k V t
toured
th U@ d
tours
th U@ z
tour's
th U@ z
tous-	saint
th u:	s { n
tout
th aU t
touts
th aU t s
tow
th @U
tow-	bin
th @U	b I n
tow-	boat
th @U	b @U t
tow-	ner
th aU	n @r
tow-	nie
th aU	n i:
tow-	son
th @U	s V n
towed
th @U d
town
th aU n
town-	hou-	ses
th aU n	h aU	s V z
town-	house
th aU n	h aU s
town-	ley
th aU n	l i:
town-	send
th aU n	z V n d
town-	send's
th aU n	z V n d z
town-	shend
th aU n	S e n d
town-	ship
th aU n	S I p
town-	ships
th aU n	S I p s
town-	ship's
th aU n	S I p s
towne
th aU n
townes
th aU n z
towns
th aU n z
town's
th aU n z
towns-	folk
th aU n	z f @U k
towns-	man
th aU n	z m V n
towns-	peo-	ple
th aU n	z p i:	p V l
tows
th @U z
tows-	ley
th @U s	l i:
toy
th OI
toy-	ing
th OI	I N
toy-	ma-	ker
th OI	m eI	k @r
toye
th OI
toyed
th OI d
toys
th OI z
toy's
th OI z
tra-	bue
th r Q b	w e
tra-	cea-	ble
th r eI	s V	b V l
tra-	cer
th r eI	s @r
tra-	cers
th r eI	s @r z
tra-	ces
th r eI	s V z
tra-	cey
th r eI	s i:
tra-	che-	a
th r eI	k i:	V
tra-	che-	al
th r eI	k i:	V l
tra-	che-	o-	phyte
th r eI	k i:	V	f aI t
tra-	che-	o-	phytes
th r eI	k i:	V	f aI t s
tra-	cie
th r eI	s i:
tra-	cing
th r eI	s I N
tra-	cy
th r eI	s i:
tra-	cy's
th r eI	s i: z
tra-	da-	ble
th r eI	d V	b V l
tra-	dea-	ble
th r eI	d V	b V l
tra-	ded
th r eI	d V d
tra-	der
th r eI	d @r
tra-	ders
th r eI	d @r z
tra-	der's
th r eI	d @r z
tra-	di-	tio-	na-	list
th r V	d I	S V	n V	l V s t
tra-	di-	tio-	nal
th r V	d I	S V	n V l
tra-	di-	tio-	nal-	ly
th r V	d I	S V	n V	l i:
tra-	di-	tion
th r V	d I	S V n
tra-	di-	tions
th r V	d I	S V n z
tra-	ding
th r eI	d I N
tra-	dings
th r eI	d I N z
tra-	ditio-	na-	lists
th r V	d I S	n V	l V s t s
tra-	fal-	gar
th r V	f { l	g @r
tra-	ge-	dies
th r {	dZ V	d i: z
tra-	ge-	dy
th r {	dZ V	d i:
tra-	ger
th r eI	g @r
tra-	gi-	co-	mic
th r {	dZ I	k Q	m I k
tra-	gic
th r {	dZ I k
tra-	gical-	ly
th r {	dZ I k	l i:
tra-	hern
th r {	h @r n
tra-	jan
th r eI	dZ V n
tra-	jan's
th r eI	dZ V n z
tra-	jec-	to-	ry
th r V	dZ e k	t @r	i:
tra-	kas
th r Q	k V z
tra-	mel
th r {	m V l
tra-	mell
th r Q	m eI l
tra-	mon-	ta-	na
th r Q	m @U n	t {	n V
tra-	pa-	ni
th r Q	p Q	n i:
tra-	peze
th r V	p i: z
tra-	shes
th r {	S V z
tra-	shing
th r {	S I N
tra-	shy
th r {	S i:
tra-	vail
th r V	v eI l
tra-	vails
th r V	v eI l z
tra-	ve-	ler
th r {	v V	l @r
tra-	ve-	lers
th r {	v V	l @r z
tra-	ve-	ler's
th r {	v V	l @r z
tra-	ve-	ling
th r {	v V	l I N
tra-	ve-	logue
th r {	v V	l O: g
tra-	vel
th r {	v V l
tra-	vel-	ler
th r {	v V	l @r
tra-	vel-	lers
th r {	v V	l @r z
tra-	vel-	ling
th r {	v V	l I N
tra-	veled
th r {	v V l d
tra-	velled
th r {	v V l d
tra-	vels
th r {	v V l z
tra-	ver
th r eI	v @r
tra-	ver-	sing
th r V	v @r	s I N
tra-	vers
th r {	v @r z
tra-	verse
th r {	v @r s
tra-	versed
th r V	v @r s t
tra-	ves-	ties
th r {	v V s	t i: z
tra-	ves-	ty
th r {	v V s	t i:
tra-	vi-	a-	ta
th r Q	v i:	Q	t V
tra-	vis
th r {	v I s
tra-	vol-	ta
th r V	v @U l	t V
tra-	vol-	ta's
th r V	v @U l	t V z
tra-	week
th r O:	i: k
trac
th r { k
trac-	kage
th r {	k I dZ
trac-	ker
th r {	k @r
trac-	kers
th r {	k @r z
trac-	king
th r {	k I N
trac-	ta-	ble
th r { k	t V	b V l
trac-	tion
th r { k	S V n
trac-	tor
th r { k	t @r
trac-	tors
th r { k	t @r z
trace
th r eI s
traced
th r eI s t
track
th r { k
track-	ball
th r { k	b O: l
track-	balls
th r { k	b O: l z
tracked
th r { k t
tracks
th r { k s
track's
th r { k s
tract
th r { k t
tracts
th r { k t s
trade
th r eI d
trade-	mark
th r eI d	m Q@ k
trade-	marked
th r eI d	m Q@ k t
trade-	marks
th r eI d	m Q@ k s
trade-	off
th r eI	d O: f
trade-	offs
th r eI	d O: f s
trades
th r eI d z
trade's
th r eI d z
trades-	men
th r eI d	z m V n
traer
th r e@
traf-	fic
th r {	f I k
traf-	fic-	ker
th r {	f I	k @r
traf-	fic-	kers
th r {	f I	k @r z
traf-	fic-	king
th r {	f I	k I N
traf-	fic's
th r {	f I k s
traf-	ford
th r {	f @r d
trai-	ler
th r eI	l @r
trai-	lers
th r eI	l @r z
trai-	ling
th r eI	l I N
trai-	na-	ble
th r eI	n V	b V l
trai-	nee
th r eI	n i:
trai-	nees
th r eI	n i: z
trai-	ner
th r eI	n @r
trai-	ners
th r eI	n @r z
trai-	ning
th r eI	n I N
trai-	nor
th r eI	n @r
trai-	to-	rous
th r eI	t @r	V s
trai-	tor
th r eI	t @r
trai-	tors
th r eI	t @r z
trail
th r eI l
trail-	bla-	zer
th r eI l	b l eI	z @r
trail-	bla-	zers
th r eI l	b l eI	z @r z
trail-	head
th r eI l	h e d
trail-	ways
th r eI l	w eI z
trailed
th r eI l d
trails
th r eI l z
train
th r eI n
train-	men
th r eI n	m V n
trained
th r eI n d
trains
th r eI n z
traip-	sing
th r eI p	s I N
traipse
th r eI p s
trait
th r eI t
traits
th r eI t s
tram
th r { m
tram-	mel
th r {	m V l
tram-	ping
th r { m	p I N
tram-	ple
th r { m	p V l
tram-	pled
th r { m	p V l d
tram-	ples
th r { m	p V l z
tram-	po-	line
th r { m	p V	l i: n
tramp
th r { m p
tramp-	ling
th r { m	p l I N
tramps
th r { m p z
trams
th r { m z
tran
th r { n
tran-	ches
th r { n	tS e z
tran-	qui-	li-	ty
th r { N	k w I	l I	t i:
tran-	qui-	li-	zer
th r { N	k w I	l aI	z @r
tran-	qui-	li-	zers
th r { N	k w I	l aI	z @r z
tran-	qui-	li-	zing
th r { N	k w I	l aI	z I N
tran-	qui-	lize
th r { N	k w I	l aI z
tran-	quil
th r { N	k w I l
tran-	sac-	ted
th r { n	s { k	t V d
tran-	sac-	tion
th r { n	z { k	S V n
tran-	sac-	tions
th r { n	z { k	S V n z
tran-	sac-	tion's
th r { n	z { k	S V n z
tran-	sact
th r { n	z { k t
tran-	sec-	ted
th r { n	s e k	t V d
tran-	sec-	tion
th r { n	s e k	S V n
tran-	sect
th r { n	s e k t
tran-	si-	ence
th r { n	z i:	V n s
tran-	si-	ents
th r { n	z i:	V n t s
tran-	si-	tio-	nal
th r { n	s I	S V	n V l
tran-	si-	tio-	ning
th r { n	z I	S V	n I N
tran-	si-	tion
th r { n	z I	S V n
tran-	si-	tions
th r { n	z I	S V n z
tran-	si-	to-	ry
th r { n	z I	t O@	i:
tran-	sient
th r { n	Z V n t
tran-	sil-	lu-	mi-	na-	tion
th r { n	z I	l u:	m I	n eI	S V n
tran-	sis-	tor
th r { n	z I s	t @r
tran-	sis-	tors
th r { n	z I s	t @r z
tran-	sit
th r { n	z I t
tran-	som
th r { n	s V m
)"
R"(tran-	soms
th r { n	s V m z
tran-	syl-	va-	ni-	a
th r { n	z i: l	v eI	n i:	V
tran-	ter
th r { n	t @r
trance
th r { n s
tranche
th r { n tS
trang
th r { N
trans
th r { n z
trans-	a-	las-	ka
th r { n	z V	l { s	k V
trans-	a-	me-	ri-	can
th r { n	z V	m e@	I	k V n
trans-	at-	lan-	tic
th r { n	z V t	l { n	t I k
trans-	cen-	ded
th r { n	s e n	d V d
trans-	cen-	den-	tal
th r { n	s V n	d e n	t V l
trans-	cen-	dence
th r { n	s e n	d V n s
trans-	cen-	dent
th r { n	s e n	d V n t
trans-	cen-	ding
th r { n	s e n	d I N
trans-	cend
th r { n	s e n d
trans-	cends
th r { n	s e n d z
trans-	chan-	nel
th r V n	s tS {	n V l
trans-	con-	ti-	nen-	tal
th r { n	z k Q n	t I	n e n	t V l
trans-	du-	cer
th r { n	s d u:	s @r
trans-	du-	cers
th r { n	s d u:	s @r z
trans-	fe-	ra-	bi-	li-	ty
th r { n	s f @r	V	b I	l V	t i:
trans-	fe-	ra-	ble
th r { n	s f @r	V	b V l
trans-	fe-	rence
th r { n	s f @r	V n s
trans-	fer
th r { n	s f @r
trans-	fer-	ra-	ble
th r { n	s f @r	V	b V l
trans-	fer-	ring
th r { n	s f @r	I N
trans-	fered
th r { n	s f @r d
trans-	ferred
th r { n	s f @r d
trans-	fers
th r { n	s f @r z
trans-	fix
th r { n	s f I k s
trans-	fixed
th r { n	s f I k s t
trans-	for-	ma-	tio-	nal
th r { n	s f @r	m eI	S V	n V l
trans-	for-	ma-	tion
th r { n	s f @r	m eI	S V n
trans-	for-	ma-	tions
th r { n	s f @r	m eI	S V n z
trans-	for-	mer
th r { n	s f O@	m @r
trans-	for-	mers
th r { n	s f O@	m @r z
trans-	for-	ming
th r { n	s f O@	m I N
trans-	form
th r { n	s f O@ m
trans-	formed
th r { n	s f O@ m d
trans-	forms
th r { n	s f O@ m z
trans-	fu-	sion
th r { n	s f j u:	Z V n
trans-	fu-	sions
th r { n	s f j u:	Z V n z
trans-	fuse
th r { n	s f j u: z
trans-	fused
th r { n	s f j u: z d
trans-	ge-	nic
th r { n	z dZ e	n I k
trans-	gres-	sion
th r { n	z g r e	S V n
trans-	gres-	sions
th r { n	z g r e	S V n z
trans-	gres-	sor
th r { n	z g r e	s @r
trans-	gress
th r { n	z g r e s
trans-	gressed
th r { n	z g r e s t
trans-	kei
th r { n	z k eI
trans-	la-	ted
th r { n	z l eI	t V d
trans-	la-	ting
th r { n	z l eI	t I N
trans-	la-	tion
th r { n	z l eI	S V n
trans-	la-	tions
th r { n	z l eI	S V n z
trans-	la-	tor
th r { n	s l eI	t @r
trans-	la-	tors
th r { n	s l eI	t @r z
trans-	late
th r { n	z l eI t
trans-	lates
th r { n	z l eI t s
trans-	lu-	cent
th r { n	s l u:	s V n t
trans-	mis-	sion
th r { n	s m I	S V n
trans-	mis-	sions
th r { n	z m I	S V n z
trans-	mit
th r { n	z m I t
trans-	mit-	ta-	ble
th r { n	z m I	t V	b V l
trans-	mit-	tal
th r { n	s m I	t V l
trans-	mit-	ted
th r { n	s m I	t V d
trans-	mit-	ter
th r { n	s m I	t @r
trans-	mit-	ters
th r { n	s m I	t @r z
trans-	mit-	ting
th r { n	s m I	t I N
trans-	mits
th r { n	z m I t s
trans-	na-	tio-	nal
th r { n	s n {	S V	n V l
trans-	o-	ce-	a-	nic
th r { n	z @U	S i:	{	n I k
trans-	pa-	ci-	fic
th r { n	s p V	s I	f I k
trans-	pa-	ren-	cies
th r { n	s p e@	V n	s i: z
trans-	pa-	ren-	cy
th r { n	s p e@	V n	s i:
trans-	pa-	rent
th r { n	s p e@	V n t
trans-	pa-	rent-	ly
th r { n	s p e@	V n	t l i:
trans-	pi-	r-	ing
th r { n	s p aI	@r	I N
trans-	pi-	re
th r { n	s p aI	@r
trans-	pi-	red
th r { n	s p aI	@r d
trans-	pi-	res
th r { n	s p aI	@r z
trans-	plan-	ta-	tion
th r { n	z p l { n	t eI	S V n
trans-	plan-	ted
th r { n	s p l { n	t V d
trans-	plan-	ting
th r { n	s p l { n	t I N
trans-	plant
th r { n	s p l { n t
trans-	plants
th r { n	s p l { n t s
trans-	pon-	der
th r { n	s p Q n	d @r
trans-	pon-	ders
th r { n	s p Q n	d @r z
trans-	por-	ta-	ble
th r { n	s p O@	t V	b V l
trans-	por-	ta-	tion
th r { n	s p @r	t eI	S V n
trans-	por-	ta-	tion's
th r { n	s p @r	t eI	S V n z
trans-	por-	ted
th r { n	s p O@	t V d
trans-	por-	ter
th r { n	s p O@	t @r
trans-	por-	ters
th r { n	s p O@	t @r z
trans-	por-	ting
th r { n	s p O@	t I N
trans-	port
th r { n	s p O@ t
trans-	ports
th r { n	s p O@ t s
trans-	pose
th r { n	s p @U z
trans-	posed
th r { n	s p @U z d
trans-	se-	xu-	al
th r { n	s e k	S j u:	V l
trans-	se-	xu-	als
th r { n	s e k	S j u:	V l z
trans-	vaal
th r { n	z v Q l
trans-	verse
th r { n	z v @r s
trans-	ves-	tite
th r { n	z v e s	t aI t
trans-	ves-	tites
th r { n	z v e s	t aI t s
transc-	ri-	ber
th r { n	s k r aI	b @r
transc-	ri-	bers
th r { n	s k r aI	b @r z
transc-	ri-	bing
th r { n	s k r aI	b I N
transc-	ribe
th r { n	s k r aI b
transc-	ribed
th r { n	s k r aI b d
transc-	ribes
th r { n	s k r aI b z
transc-	rip-	tion
th r { n	s k r I p	S V n
transc-	rip-	tions
th r { n	s k r I p	S V n z
transc-	ript
th r { n	s k r I p t
transc-	ripts
th r { n	s k r I p t s
trant
th r { n t
trap
th r { p
trap-	pers
th r {	p @r z
trap-	ping
th r {	p I N
trap-	pings
th r {	p I N z
trap-	pist
th r {	p I s t
trappe
th r { p
trapped
th r { p t
traps
th r { p s
trash
th r { S
trashed
th r { S t
trask
th r { s k
trau-	ma
th r O:	m V
trau-	ma-	tic
th r O:	m {	t I k
trau-	ma-	tize
th r O:	m V	t aI z
trau-	ma-	tized
th r O:	m V	t aI z d
trau-	mas
th r O:	m V z
traut-	man
th r aU t	m V n
traw-	ler
th r O:	l @r
traw-	lers
th r O:	l @r z
tray
th r eI
trays
th r eI z
tre-	ble
th r e	b V l
tre-	bled
th r e	b V l d
tre-	go
th r e	g @U
tre-	harne
th r e	h Q@ n
tre-	la
th r e	l V
tre-	loar
th r e	l O@
tre-	main
th r e	m aI n
tre-	maine
th r V	m eI n
tre-	mayne
th r e	m eI n
tre-	men-	dous
th r V	m e n	d V s
tre-	men-	dous-	ly
th r V	m e n	d V s	l i:
tre-	mens
th r e	m V n z
tre-	mont
th r e	m V n t
tre-	mor
th r e	m @r
tre-	mors
th r e	m @r z
tre-	mu-	lous
th r e m	j V	l V s
tre-	mu-	lous-	ly
th r e m	j V	l V s	l i:
tre-	na-	ry
th r e	n e@	i:
tre-	pi-	da-	tion
th r e	p I	d eI	S V n
tre-	stle
th r e	s V l
tre-	ti-	noin
th r e	t I	n OI n
tre-	ve-	lyan
th r V	v e l	j V n
tre-	vi-	no
th r V	v i:	n @U
tre-	vi-	so
th r e	v i:	s @U
tre-	vor
th r e	v @r
trea-	che-	rous
th r e	tS @r	V s
trea-	che-	ry
th r e	tS @r	i:
trea-	cy
th r eI	s i:
trea-	ding
th r e	d I N
trea-	son
th r i:	z V n
trea-	su-	rer
th r e	Z @r	@r
trea-	su-	rers
th r e	Z @r	@r z
trea-	su-	rer's
th r e	Z @r	@r z
trea-	su-	ries
th r e	Z @r	i: z
trea-	su-	ry
th r e	Z @r	i:
trea-	su-	ry's
th r e	Z @r	i: z
trea-	sure
th r e	Z @r
trea-	sured
th r e	Z @r d
trea-	sures
th r e	Z @r z
trea-	ta-	ble
th r i:	t V	b V l
trea-	ted
th r i:	t V d
trea-	ter
th r i:	t @r
trea-	ters
th r i:	t @r z
trea-	ti-	ses
th r i:	t I	s V z
trea-	ties
th r i:	t i: z
trea-	ting
th r i:	t I N
trea-	tise
th r i:	t I s
trea-	ty
th r i:	t i:
trea-	ty's
th r i:	t i: z
tread
th r e d
tread-	mill
th r e d	m I l
tread-	mills
th r e d	m I l z
tread-	way
th r e d	w eI
tread-	well
th r e d	w e l
tread-	wheel
th r e d	w i: l
treads
th r e d z
treat
th r i: t
treat-	ment
th r i: t	m V n t
treat-	ments
th r i: t	m V n t s
treats
th r i: t s
treb-	lin-	ka
th r e b	l I N	k @r
tree
th r i:
tree-	less
th r i:	l V s
tree-	top
th r i:	t O: p
tree-	tops
th r i:	t O: p s
treece
th r i: s
treen
th r i: n
trees
th r i: z
trei-	ber
th r aI	b @r
trek
th r e k
trek-	king
th r e	k I N
trekked
th r e k t
treks
th r e k s
trel-	la
th r e	l V
trel-	lis
th r e	l I s
trem-	b-	ling
th r e m	b V	l I N
trem-	ble
th r e m	b V l
trem-	bled
th r e m	b V l d
tremb-	ly
th r e m	b l i:
tren-	chant
th r e n	tS V n t
tren-	chard
th r e N	k @r d
tren-	cher
th r e n	tS @r
tren-	ches
th r e n	tS V z
tren-	ded
th r e n	d V d
tren-	di-	er
th r e n	d i:	@r
tren-	di-	est
th r e n	d i:	V s t
tren-	ding
th r e n	d I N
tren-	dy
th r e n	d i:
tren-	ton
th r e n	t V n
tren-	ton's
th r e n	t V n z
trench
th r e n tS
trend
th r e n d
trend-	set-	ter
th r e n	d s e	t @r
trends
th r e n d z
trent
th r e n t
trente-	et-	qua-	ran-	te
th r eI n	t eI k	w Q@	e n	t eI
trent's
th r e n t s
tres-	cott
th r e s	k V t
tres-	pas-	sing
th r e s	p {	s I N
tres-	pass
th r e s	p { s
tres-	sel
th r e	s V l
tres-	ses
th r e	s V z
tress
th r e s
trest
th r e s t
trew
th r u:
trey
th r eI
tri
th r aI
tri-	ad
th r aI	{ d
tri-	ads
th r aI	{ d z
tri-	ad's
th r aI	{ d z
tri-	age
th r aI	I dZ
tri-	al
th r aI	V l
tri-	als
th r aI	V l z
tri-	al's
th r aI	V l z
tri-	an-	gle
th r aI	{ N	g V l
tri-	an-	gles
th r aI	{ N	g V l z
tri-	an-	gle's
th r aI	{ N	g V l z
tri-	an-	gu-	la-	tion
th r aI	{ N	g j u:	l eI	S V n
tri-	an-	gu-	lar
th r aI	{ N	g j V	l @r
tri-	ath-	lon
th r aI	{ T	l V n
tri-	ba-	lism
th r aI	b V	l I z m
tri-	bal
th r aI	b V l
tri-	bo-	rough
th r aI	b @r	@U
tri-	bu-	la-	tion
th r I b	j V	l eI	S V n
tri-	bu-	la-	tions
th r I b	j V	l eI	S V n z
tri-	bu-	nal
th r V b	j u:	n V l
tri-	bu-	nals
th r aI b	j u:	n V l z
tri-	bu-	ta-	ries
th r I b	j V	t e@	i: z
tri-	bu-	ta-	ry
th r I b	j V	t e@	i:
tri-	bune
th r I b	j u: n
tri-	bune's
th r I b	j u: n z
tri-	bute
th r I b	j u: t
tri-	butes
th r I b	j u: t s
tri-	ce-	ra-	tops
th r aI	s e@	V	t O: p s
tri-	ceps
th r aI	s e p s
tri-	cia
th r I	S V
tri-	cia's
th r I	S V z
tri-	cus-	pid
th r aI	k V s	p I d
tri-	cy-	cle
th r I	s I	k V l
tri-	dent
th r aI	d V n t
tri-	en-	ni-	al
th r aI	e	n i:	V l
tri-	er
th r aI	@r
tri-	fle
th r aI	f V l
tri-	fles
th r aI	f V l z
tri-	go
th r i:	g @U
tri-	la-	te-	ral
th r aI	l {	t @r	V l
tri-	lo-	gy
th r I	l V	dZ i:
tri-	mes-	ter
th r aI	m e s	t @r
tri-	ni-	dad
th r I	n I	d { d
tri-	ni-	ty
th r I	n I	t i:
tri-	ni-	ty's
th r I	n I	t i: z
tri-	o
th r i:	@U
tri-	omphe
th r i:	@U m f
tri-	o's
th r i:	@U z
tri-	p-	ling
th r I	p V	l I N
tri-	par-	tite
th r aI	p Q@	t aI t
tri-	ple
th r I	p V l
tri-	pled
th r I	p V l d
tri-	ples
th r I	p V l z
tri-	po-	li
th r I	p V	l i:
tri-	po-	li's
th r I	p V	l i: z
tri-	pod
th r aI	p Q d
tri-	pods
th r aI	p Q d z
tri-	remes
th r aI	r i: m z
tri-	sha
th r I	S V
tri-	sha's
th r I	S V z
tri-	state
th r aI s	t eI t
tri-	ti-	um
th r I	t i:	V m
tri-	ton
th r aI	t V n
tri-	ton's
th r aI	t V n z
tri-	um-	phal
th r i:	V m	f V l
tri-	um-	phant
th r aI	V m	f V n t
tri-	um-	phant-	ly
th r aI	V m	f V n	t l i:
tri-	um-	vi-	rate
th r aI	V m	v @r	V t
tri-	umph
th r aI	V m f
tri-	umphed
th r aI	V m f t
tri-	umphs
th r aI	V m f s
tri-	vette
th r I	v e t
tri-	vi-	a
th r I	v i:	V
tri-	vi-	a-	li-	ty
th r I	v i:	{	l I	t i:
tri-	vi-	a-	li-	zes
th r I	v i:	V	l aI	z V z
tri-	vi-	a-	li-	zing
th r I	v i:	V	l aI	z I N
tri-	vi-	a-	lize
th r I	v i:	V	l aI z
tri-	vi-	a-	lized
th r I	v i:	V	l aI z d
tri-	vi-	al
th r I	v i:	V l
tri-	xie
th r I k	s i:
tri-	xy
th r I k	s i:
trib
th r I b
trib-	bett
th r I	b e t
trib-	ble
th r I	b V l
trib-	bles
th r I	b V l z
tribe
th r aI b
tribes
th r aI b z
tribe's
th r aI b z
tribes-	man
th r aI b	z m { n
tribes-	men
th r aI b	z m e n
tric-	ke-	ry
th r I	k @r	i:
tric-	ki-	er
th r I	k i:	@r
tric-	ki-	est
th r I	k i:	V s t
tric-	king
th r I	k I N
tric-	kle
th r I	k V l
tric-	kled
th r I	k V l d
tric-	kles
th r I	k V l z
tric-	ky
th r I	k i:
trice
th r aI s
trick
th r I k
trick-	ling
th r I k	l I N
tricked
th r I k t
tricks
th r I k s
tricks-	ter
th r I k	s t @r
tricks-	ters
th r I k	s t @r z
tried
th r aI d
tries
th r aI z
trieste
th r i: s t
trif-	ling
th r aI f	l I N
trig
th r I g
trig-	ge-	ring
th r I	g @r	I N
trig-	ger
th r I	g @r
trig-	gered
th r I	g @r d
trig-	gers
th r I	g @r z
trig-	ly-	ce-	ride
th r aI g	l I	s @r	aI d
trig-	ly-	ce-	rides
th r aI g	l I	s @r	aI d z
tril-	by
th r I l	b i:
tril-	ling
th r I	l I N
tril-	lion
th r I l	j V n
tril-	lions
th r I l	j V n z
tril-	lo
th r I	l @U
trill
th r I l
trim
th r I m
trim-	ble
th r I m	b V l
trim-	mer
th r I	m @r
trim-	mers
th r I	m @r z
trim-	ming
th r I	m I N
trim-	mings
th r I	m I N z
trimmed
th r I m d
trims
th r I m z
trin-	co-	ma-	lee
th r I N	k @U	m V	l i:
trin-	ket
th r I N	k V t
trin-	kets
th r I N	k V t s
trin-	kle
th r I N	k V l
trine
th r aI n
trip
th r I p
trip-	let
th r I p	l V t
trip-	lets
th r I p	l V t s
trip-	lett
th r I p	l e t
trip-	li-	cate
th r I p	l I	k V t
trip-	per
th r I	p @r
trip-	pers
th r I	p @r z
trip-	ping
th r I	p I N
trip-	ple
th r I	p V l
trip-	tych
th r I p	t I k
tripe
th r aI p
tripp
th r I p
trippe
th r I p
tripped
th r I p t
trips
th r I p s
trip's
th r I p s
tris-	ta
th r I s	t V
tris-	tan
th r I s	t { n
trish
th r I S
trist-	ram
th r I s	t r V m
trite
th r aI t
trites
th r aI t s
tro-	ia
th r @U	j V
tro-	jan
th r @U	dZ V n
tro-	jans
th r @U	dZ V n z
tro-	phies
th r @U	f i: z
tro-	phy
th r @U	f i:
tro-	pi-	ca-	na
th r Q	p I	k {	n V
tro-	pi-	ca-	na's
th r Q	p I	k {	n V z
tro-	pi-	cal
th r Q	p I	k V l
tro-	pic
th r Q	p I k
tro-	pics
th r Q	p I k s
tro-	po-	pause
th r Q	p V	p O: z
tro-	va-	to
th r @U	v Q	t @U
tro-	va-	tore
th r @U	v V	t O@
tro-	wel
th r aU	w e l
tro-	xell
th r Q k	s V l
tro-	ya-	nos
th r OI	Q	n @U s
troc-	ki
th r Q	k i:
troche
th r Q tS
trod
th r Q d
troi-	ka
th r OI	k V
trois
th w Q
trol-	ley
th r Q	l i:
trol-	leys
th r Q	l i: z
trol-	ling
th r @U	l I N
troll
th r @U l
trom-	bo-	nist
th r Q m	b @U	n I s t
trom-	bone
th r Q m	b @U n
trom-	bones
th r Q m	b @U n z
tromp
th r Q m p
tron
th r Q n
trone
th r @U n
troo-	per
th r u:	p @r
troo-	pers
th r u:	p @r z
troo-	per's
th r u:	p @r z
troo-	ping
th r u:	p I N
troon
th r u: n
troop
th r u: p
trooped
th r u: p t
troops
th r u: p s
troop's
th r u: p s
tros-	per
th r Q s	p @r
trot
th r Q t
trot-	sky
th r Q t	s k i:
trot-	ted
th r Q	t V d
trot-	ter
th r Q	t @r
trot-	ting
th r Q	t I N
troth
th r @U T
trots
th r Q t s
trou-	b-	ling
th r V	b V	l I N
trou-	ba-	dour
th r u:	b V	d O@
trou-	ble
th r V	b V l
trou-	ble-	ma-	ker
th r V	b V l	m eI	k @r
trou-	ble-	ma-	kers
th r V	b V l	m eI	k @r z
trou-	ble-	shoo-	ter
th r V	b V l	S u:	t @r
trou-	ble-	some
th r V	b V l	s V m
trou-	bled
th r V	b V l d
trou-	bles
th r V	b V l z
trou-	ser
th r aU	z @r
trou-	sers
th r aU	z @r z
trough
th r O: f
troughs
th r O: f s
troun-	cing
th r aU n	s I N
trounce
th r aU n s
trounced
th r aU n s t
troup
th r u: p
troupe
th r u: p
troupes
th r u: p s
troupe's
th r u: p s
trout
th r aU t
trout-	man
th r aU t	m V n
trout's
th r aU t s
trove
th r @U v
trow
th r @U
trow-	bridge
th r @U b	r I dZ
troy
th r OI
tru-	an-	cy
th r u:	V n	s i:
tru-	ant
th r u:	V n t
tru-	cu-	lent
th r V k	j V	l V n t
tru-	da
th r u:	d V
tru-	deau
th r u:	d @U
tru-	die
th r u:	d i:
tru-	dy
th r u:	d i:
tru-	er
th r u:	@r
tru-	est
th r u:	V s t
tru-	i-	sm
th r u:	I	z V m
tru-	jil-	lo
th r u:	h i:	@U
tru-	ly
th r u:	l i:
tru-	man
th r u:	m V n
tru-	man's
th r u:	m V n z
tru-	ro
th r u:	r @U
tru-	scott
th r V s	k V t
truc-	kee
th r V	k i:
truc-	ker
th r V	k @r
truc-	kers
th r V	k @r z
truc-	king
th r V	k I N
truce
th r u: s
truck
th r V k
truck-	load
th r V k	l @U d
truck-	loads
th r V k	l @U d z
trucked
th r V k t
trucks
th r V k s
truck's
th r V k s
trud-	gen
th r V	dZ V n
trud-	ges
th r V	dZ V z
trud-	ging
th r V	dZ I N
trude
th r u: d
trudge
th r V dZ
trudged
th r V dZ d
true
th r u:
true-	love
th r u:	l V v
true-	man
th r U	m V n
trueb-	lood
th r u: b	l V d
trues-	dale
th r u: z	d eI l
truf-	faut
th r u:	f @U
truf-	faut's
th r u:	f @U z
truf-	fle
th r V	f V l
truf-	fles
th r V	f V l z
truitt
th r u: t
trull
th r V l
trum-	bull
th r V m	b V l
trum-	pe-	ted
th r V m	p V	t V d
trum-	pe-	ter
th r V m	p V	t @r
trum-	pe-	ting
th r V m	p V	t I N
trum-	pet
th r V m	p V t
trum-	pets
th r V m	p V t s
trump
th r V m p
trumped
th r V m p t
trumps
th r V m p s
trump's
th r V m p s
trun-	ca-	ted
th r V N	k eI	t V d
trun-	cate
th r V N	k eI t
trun-	cheon
th r V n	tS V n
trun-	cheons
th r V n	tS V n z
trun-	dle
th r V n	d V l
trun-	dled
th r V n	d V l d
trunk
th r V N k
trunks
th r V N k s
truong
th r O: N
trus-	sell
th r V	s V l
trus-	ses
th r V	s V z
trus-	ted
th r V s	t V d
trus-	tee
th r V s	t i:
trus-	tee-	ship
th r V s	t i:	S I p
trus-	tees
th r V s	t i: z
trus-	tee's
th r V s	t i: z
trus-	ting
th r V s	t I N
trus-	ty
th r V s	t i:
truss
th r V s
trust
th r V s t
trust-	wor-	thi-	ness
th r V s	t w @r	D i:	n V s
trust-	wor-	thy
th r V s	t w @r	D i:
trusts
th r V s t s
trust's
th r V s t s
truth
th r u: T
truth-	ful
th r u: T	f V l
truth-	ful-	ly
th r u: T	f V	l i:
truth-	ful-	ness
th r u: T	f V l	n V s
truths
th r u: T s
try
th r aI
try-	ing
th r aI	I N
try-	on
th r aI	Q n
try-	out
th r aI	aU t
try-	outs
th r aI	aU t s
try-	phe-	na
th r I	f V	n V
tryg-	ve
th r I g	v i:
tryst
th r aI s t
t's
th i: z
tsai
th s aI
tsai's
th s aI z
tsar
z Q@
tse
th s i:
tseng
th s e N
tset-	se
th s i: t	s i:
tsing-	tao
s I N	t aU
tso
th s @U
tsu-	da
th s u:	d V
tsu-	i
th s u:	i:
tsu-	na-	mi
th s u:	n Q	m i:
tu
th u:
tu-	ba
th u:	b V
)"
R"(tu-	bal
th u:	b V l
tu-	ber-	cu-	lo-	sis
th V	b @r k	j V	l @U	s I s
tu-	bing
th u:	b I N
tu-	bu-	lar
th u: b	j V	l @r
tu-	bule
th u: b	j u: l
tu-	cu-	man
th u: k	j u:	m V n
tu-	dor
th u:	d @r
tu-	dor's
th j u:	d @r z
tu-	fa
th u:	f V
tu-	i-	tion
th j u:	I	S V n
tu-	i-	tions
th u:	I	S V n z
tu-	la
th u:	l V
tu-	lane
th u:	l eI n
tu-	lip
th u:	l I p
tu-	lips
th u:	l I p s
tu-	me-	scent
th u:	m e	s V n t
tu-	mor
th u:	m @r
tu-	mors
th u:	m @r z
tu-	mul-	tu-	ous
th u:	m V l	tS u:	V s
tu-	mult
th u:	m V l t
tu-	na
th u:	n V
tu-	na-	ble
th u:	n V	b V l
tu-	nas
th u:	n V z
tu-	ner
th u:	n @r
tu-	ni-	ca
th u:	n I	k V
tu-	ni-	ca's
th u:	n I	k V z
tu-	ni-	cate
th u:	n I	k V t
tu-	ni-	sia
th u:	n i:	Z V
tu-	ni-	sian
th u:	n i:	Z V n
tu-	nic
th u:	n I k
tu-	ning
th u:	n I N
tu-	nis
th u:	n I s
tu-	pe-	lo
th j u:	p V	l @U
tu-	ran-	dot
th @r	{ n	d V t
tu-	renne
th j u:	r e n
tu-	ri
th U@	i:
tu-	rin
th j U@	I n
tu-	ring
th U@	I N
tu-	shes
th U	S V z
tu-	te-	lage
th j u:	t V	l I dZ
tu-	to-	ri-	al
th u:	t O@	i:	V l
tu-	to-	ri-	als
th u:	t O@	i:	V l z
tu-	to-	ring
th u:	t @r	I N
tu-	tor
th u:	t @r
tu-	tored
th u:	t @r d
tu-	tors
th u:	t @r z
tu-	tu
th u:	t u:
tu-	xe-	do
th V k	s i:	d @U
tu-	xe-	dos
th V k	s i:	d @U z
tub
th V b
tub-	by
th V	b i:
tub-	man
th V b	m V n
tubb
th V b
tube
th u: b
tubes
th u: b z
tubs
th V b z
tuc-	ker
th V	k @r
tuc-	ker-	man
th V	k @r	m V n
tuc-	ker's
th V	k @r z
tuc-	king
th V	k I N
tuc-	son
th u:	s Q n
tuch-	man
th V k	m V n
tuck
th V k
tucked
th V k t
tucks
th V k s
tue
th u:
tuel
th u: l
tues-	day
th u: z	d i:
tues-	days
th u: z	d eI z
tues-	day's
th u: z	d i: z
tuf-	ted
th V f	t V d
tuff
th V f
tuft
th V f t
tufts
th V f t s
tug
th V g
tug-	boat
th V g	b @U t
tug-	boats
th V g	b @U t s
tug-	ging
th V	g I N
tug-	man
th V g	m V n
tugged
th V g d
tugs
th V g z
tul-	ley
th u:	l i:
tul-	li-	a
th V	l i:	V
tul-	li-	o
th u:	l i:	@U
tul-	li-	us
th V	l i:	V s
tul-	los
th V	l @U z
tul-	ly
th V	l i:
tul-	sa
th V l	s V
tull
th V l
tum-	b-	ling
th V m	b V	l I N
tum-	ble
th V m	b V l
tum-	bled
th V m	b V l d
tum-	bles
th V m	b V l z
tum-	mies
th V	m i: z
tum-	my
th V	m i:
tumb-	ler
th V m	b l @r
tumb-	lers
th V m	b l @r z
tumb-	ler's
th V m	b l @r z
tums
th V m z
tun-	gate
th u:	N eI t
tun-	ku
th V N	k u:
tun-	ne-	ling
th V	n V	l I N
tun-	nel
th V	n V l
tun-	nell
th V	n V l
tun-	nels
th V	n V l z
tun-	ney
th V	n i:
tun-	ny
th V	n i:
tund-	ra
th V n	d r V
tune
th u: n
tune-	ful
th u: n	f V l
tune-	up
th u:	n V p
tuned
th u: n d
tunes
th u: n z
tung
th V N
tung's
th V N z
tungs-	ten
th V N	s t V n
tup-	per-	ware
th V	p @r	w e@
tur-	ban
th @r	b V n
tur-	bans
th @r	b V n z
tur-	bi-	di-	ty
th @r	b I	d I	t i:
tur-	bine
th @r	b aI n
tur-	bines
th @r	b aI n z
tur-	bo
th @r	b @U
tur-	bo-	char-	ges
th @r	b @U	tS Q@	dZ V z
tur-	bo-	char-	ging
th @r	b @U	tS Q@	dZ I N
tur-	bo-	charge
th @r	b @U	tS Q@ dZ
tur-	bo-	charged
th @r	b @U	tS Q@ dZ d
tur-	bo-	fan
th @r	b @U	f { n
tur-	bo-	jet
th @r	b @U	dZ e t
tur-	bo-	prop
th @r	b @U p	r Q p
tur-	bo-	props
th @r	b @U p	r Q p s
tur-	bos
th @r	b @U z
tur-	bot
th @r	b @U
tur-	bu-	lence
th @r b	j V	l V n s
tur-	bu-	lent
th @r b	j V	l V n t
tur-	co
th @r	k @U
tur-	gid
th @r	dZ I d
tur-	key
th @r	k i:
tur-	keys
th @r	k i: z
tur-	key's
th @r	k i: z
tur-	kic
th @r	k I k
tur-	kish
th @r	k I S
tur-	ley
th @r	l i:
tur-	mel
th @r	m V l
tur-	moil
th @r	m OI l
tur-	ner
th @r	n @r
tur-	ner's
th @r	n @r z
tur-	ney
th @r	n i:
tur-	ning
th @r	n I N
tur-	nip
th @r	n I p
tur-	nips
th @r	n I p s
tur-	pen-	tine
th @r	p V n	t aI n
tur-	pi-	tude
th @r	p I	t u: d
tur-	pin
th @r	p I n
tur-	quoise
th @r k	w OI z
tur-	rell
th O@	V l
tur-	ret
th @r	V t
tur-	rets
th @r	V t s
tur-	tle
th @r	t V l
tur-	tle-	neck
th @r	t V l	n e k
tur-	tle-	necks
th @r	t V l	n e k s
tur-	tles
th @r	t V l z
tur-	tle's
th @r	t V l z
tur-	ton
th @r	t V n
tur-	vy
th @r	v i:
turbe-	ville
th @r b	v I l
ture
th U@
turf
th @r f
turk
th @r k
turk-	me-	nis-	tan
th @r k	m e	n I s	t { n
turk-	men
th @r k	m e n
turks
th @r k s
turn
th @r n
turn-	a-	bout
th @r	n V	b aU t
turn-	a-	round
th @r	n @r	aU n d
turn-	a-	rounds
th @r	n @r	aU n d z
turn-	bull
th @r n	b U l
turn-	coat
th @r n	k @U t
turn-	down
th @r n	d aU n
turn-	key
th @r n	k i:
turn-	o-	ver
th @r	n @U	v @r
turn-	o-	vers
th @r	n @U	v @r z
turn-	off
th @r	n O: f
turn-	out
th @r	n aU t
turn-	outs
th @r	n aU t s
turn-	pike
th @r n	p aI k
turn-	pikes
th @r n	p aI k s
turn-	stile
th @r n	s t aI l
turn-	stiles
th @r n	s t aI l z
turn-	ta-	ble
th @r n	t eI	b V l
turn-	ta-	bles
th @r n	t eI	b V l z
turned
th @r n d
turns
th @r n z
tus-	ca-	loo-	sa
th V s	k V	l u:	s V
tus-	ca-	loo-	sa's
th V s	k V	l u:	s V z
tus-	ca-	ny
th V s	k V	n i:
tus-	can
th V s	k V n
tus-	ke-	gee
th V s	k V	g i:
tus-	saud's
th u:	s @U z
tus-	sle
th V	s V l
tus-	sled
th V	s V l d
tus-	sles
th V	s V l z
tus-	tin
th V s	t I n
tush
th U S
tusk
th V s k
tusks
th V s k s
tut
th V t
tut-	si
th u: t	s i:
tut-	sis
th u: t	s i: z
tut-	ti
th u:	t i:
tut-	tle
th V	t V l
tut-	wi-	ler
th V t	w aI	l @r
tutt
th V t
tux
th V k s
tuz-	la
th u: z	l V
tuz-	la's
th u: z	l V z
twad-	dell
th w Q	d e l
twad-	dle
th w Q	d V l
twain
th w eI n
twain's
th w eI n z
twan-	gy
th w Q n	dZ i:
twang
th w Q N
twas
th w V z
twea-	king
th w i:	k I N
tweak
th w i: k
tweaked
th w i: k t
tweaks
th w i: k s
twee-	dle
th w i:	d V l
twee-	dy
th w i:	d i:
twee-	zer
th w i:	z @r
twee-	zers
th w i:	z @r z
tweed
th w i: d
tweet
th w i: t
twelfth
th w e l f T
twelve
th w e l v
twen-	ti-	eth
th w e n	t i:	V T
twen-	ties
th w e n	t i: z
twen-	ty
th w e n	t i:
twen-	ty's
th w e n	t i: z
twi-	light
th w aI	l aI t
twi-	ning
th w aI	n I N
twice
th w aI s
twid-	dle
th w I	d V l
twidd-	ling
th w I d	l I N
twig
th w I g
twig-	gy
th w I	g i:
twigged
th w I g d
twigs
th w I g z
twill
th w I l
twin
th w I n
twin-	jet
th w I n	dZ e t
twin-	jets
th w I n	dZ e t s
twin-	k-	ling
th w I N	k V	l I N
twin-	kie
th w I N	k i:
twin-	kies
th w I N	k i: z
twin-	kle
th w I N	k V l
twin-	kles
th w I N	k V l z
twine
th w aI n
twined
th w aI n d
twinge
th w I n dZ
twins
th w I n z
twins-	burg
th w I n	z b @r g
twir-	ler
th w @r	l @r
twir-	ling
th w @r	l I N
twirl
th w @r l
twirled
th w @r l d
twirls
th w @r l z
twis-	ted
th w I s	t V d
twis-	ter
th w I s	t @r
twis-	ters
th w I s	t @r z
twis-	ting
th w I s	t I N
twis-	ty
th w I s	t i:
twist
th w I s t
twists
th w I s t s
twit-	ches
th w I	tS V z
twit-	ching
th w I	tS I N
twit-	ty
th w I	t i:
twitch
th w I tS
twitched
th w I tS t
twite
th w aI t
two
th u:
two-	fold
th u:	f @U l d
two-	some
th u:	s V m
two-	thirds
th u:	T @r d z
twomb-	ly
th w u: m	b l i:
twos
th u: z
two's
th u: z
twy-	ford
th w aI	f @r d
twy-	la
th w aI	l V
ty
th aI
ty-	balt
th I	b V l t
ty-	coon
th aI	k u: n
ty-	coons
th aI	k u: n z
ty-	coon's
th aI	k u: n z
ty-	er
th aI	@r
ty-	ing
th aI	I N
ty-	le-	nol
th aI	l V	n O: l
ty-	ler
th aI	l @r
ty-	ler's
th aI	l @r z
ty-	nan
th aI	n V n
ty-	ner
th aI	n @r
ty-	pea-	ble
th aI	p V	b V l
ty-	pi-	cal
th I	p I	k V l
ty-	pi-	fied
th I	p I	f aI d
ty-	pi-	fies
th I	p I	f aI z
ty-	pi-	fy
th I	p I	f aI
ty-	pical-	ly
th I	p I k	l i:
ty-	ping
th aI	p I N
ty-	pings
th aI	p I N z
ty-	pist
th aI	p I s t
ty-	pists
th aI	p I s t s
ty-	po
th aI	p @U
ty-	po-	gra-	phi-	cal
th aI	p V g	r {	f I	k V l
ty-	po-	gra-	phy
th V	p Q g	r V	f i:
ty-	ra
th aI	r V
ty-	ran-	ni-	cal
th @r	{	n I	k V l
ty-	ran-	nies
th I@	V	n i: z
ty-	ran-	no-	sau-	rus
th I@	{	n V	s O@	V s
ty-	ran-	ny
th I@	V	n i:
ty-	rant
th aI	r V n t
ty-	rants
th aI	r V n t s
ty-	ree
th aI	r i:
ty-	rone
th aI	r @U n
ty-	son
th aI	s V n
ty-	son's
th aI	s V n z
tye
th aI
tyke
th aI k
tym-	pa-	nic
th I m	p {	n I k
tym-	pa-	num
th I m	p V	n V m
tyn-	dall
th I n	d V l
tyne
th aI n
tynes
th aI n z
typ-	hoid
th aI	f OI d
typ-	hoon
th aI	f u: n
typ-	hoons
th aI	f u: n z
typ-	hus
th aI	f V s
type
th aI p
type-	cas-	ting
th aI p	k { s	t I N
type-	cast
th aI p	k { s t
type-	fa-	ces
th aI p	f eI	s V z
type-	face
th aI p	f eI s
type-	set
th aI p	s e t
type-	set-	ting
th aI p	s e	t I N
type-	wri-	ter
th aI p	r aI	t @r
type-	wri-	ters
th aI p	r aI	t @r z
type-	wri-	ting
th aI p	r aI	t I N
type-	writ-	ten
th aI p	r I	t V n
typed
th aI p t
types
th aI p s
tyr-	rell
th aI	r e l
tyr-	rhe-	ni-	an
th @r	i:	n i:	V n
tyre
th aI r
u
j u:
u-	art
j u:	Q@ t
u-	bi-	qui-	tous
j u:	b I k	w I	t V s
u-	bi-	qui-	ty
j u:	b I k	w I	t i:
u-	chi-	da
u:	k i:	d V
u-	dale
j u:	d eI l
u-	dall
j u:	d V l
u-	dell
V	d V l
u-	delle
V	d e l
u-	do
u:	d @U
u-	gan-	da
j u:	g { n	d V
u-	gan-	dan
j u:	g { n	d V n
u-	gan-	da's
j u:	g { n	d V z
u-	kase
j u:	k eI z
u-	ku-	le-	le
j u:	k V	l eI	l i:
u-	la
j u:	l V
u-	lys-	ses
j u:	l I	s i: z
u-	ma
j u:	m V
u-	na
u:	n V
u-	na-	ba-	shed-	ly
V	n V	b {	S V d	l i:
u-	na-	ba-	ted
V	n V	b eI	t V d
u-	na-	bashed
V	n V	b { S t
u-	na-	ble
V	n eI	b V l
u-	na-	bridged
V	n V b	r I dZ d
u-	na-	dorn
V	n V	d O@ n
u-	na-	dorned
V	n V	d O@ n d
u-	na-	dul-	te-	ra-	ted
V	n V	d V l	t @r	eI	t V d
u-	na-	fraid
V	n V f	r eI d
u-	na-	li-	e-	na-	ble
V	n eI	l i:	e	n V	b V l
u-	na-	men-	ded
V	n V	m e n	d V d
u-	na-	mor-	tized
V	n {	m @r	t aI z d
u-	na-	ni-	mi-	ty
j u:	n V	n I	m V	t i:
u-	na-	ni-	mous
j u:	n {	n I	m V s
u-	na-	ni-	mous-	ly
j u:	n {	n I	m V s	l i:
u-	na-	po-	lo-	ge-	tic
V	n V	p Q	l V	dZ e	t I k
u-	na-	sha-	med-	ly
V	n V	S eI	m V d	l i:
u-	na-	shamed
V	n V	S eI m d
u-	na-	vai-	la-	bi-	li-	ty
V	n V	v eI	l V	b I	l V	t i:
u-	na-	vai-	la-	ble
V	n V	v eI	l V	b V l
u-	na-	vai-	ling
V	n V	v eI	l I N
u-	na-	voi-	da-	ble
V	n V	v OI	d V	b V l
u-	na-	voi-	dab-	ly
V	n V	v OI	d V b	l i:
u-	na-	ware
V	n V	w e@
u-	na-	wares
V	n V	w e@ z
u-	nac-	cep-	ta-	ble
V	n { k	s e p	t V	b V l
u-	nac-	cep-	tab-	ly
V	n { k	s e p	t V b	l i:
u-	nac-	com-	pa-	nied
V	n V	k V m	p V	n i: d
u-	nac-	coun-	ta-	ble
V	n V	k aU n	t V	b V l
u-	nac-	coun-	tab-	ly
V	n V	k aU n	t V b	l i:
u-	nac-	coun-	ted
V	n V	k aU n	t V d
u-	nac-	cre-	di-	ted
V	n V k	r e	d I	t V d
u-	nac-	cus-	tomed
V	n V	k V s	t V m d
u-	nad-	dressed
V	n V d	r e s t
u-	nad-	jus-	ted
V	n V	dZ V s	t V d
u-	nad-	just
V	n V	dZ V s t
u-	naf-	fec-	ted
V	n V	f e k	t V d
u-	naf-	fi-	li-	a-	ted
V	n V	f I	l i:	eI	t V d
u-	naf-	for-	da-	ble
V	n V	f O@	d V	b V l
u-	nai-	ded
V	n eI	d V d
u-	nal-	lo-	ca-	ted
V	n {	l V	k eI	t V d
u-	nal-	lo-	wa-	ble
V	n V	l aU	V	b V l
u-	nal-	loyed
V	n {	l OI d
u-	nal-	te-	ra-	ble
V	n O: l	t @r	V	b V l
u-	nal-	te-	rab-	ly
V	n O: l	t @r	V b	l i:
u-	nal-	tered
V	n O: l	t @r d
u-	nam-	bi-	gu-	ous
V	n { m	b I g	j V	w V s
u-	nam-	bi-	gu-	ous-	ly
V	n { m	b I g	j u:	V s	l i:
u-	nan-	nounced
V	n V	n aU n s t
u-	nan-	swe-	ra-	ble
V	n { n	s @r	V	b V l
u-	nan-	swered
V	n { n	s @r d
u-	nan-	ti-	ci-	pa-	ted
V	n { n	t I	s I	p eI	t I d
u-	nap-	pe-	ti-	zing
V	n {	p V	t aI	z I N
u-	nap-	pea-	ling
V	n V	p i:	l I N
u-	nap-	pre-	ci-	a-	ted
V	n V p	r i:	S i:	eI	t V d
u-	nap-	proved
V	n V p	r u: v d
u-	narm
V	n Q@ m
u-	narmed
V	n Q@ m d
u-	nas-	sai-	la-	ble
V	n V	s eI	l V	b V l
u-	nas-	sis-	ted
V	n V	s I s	t V d
u-	nas-	su-	ming
V	n V	s u:	m I N
u-	nat-	tach
V	n V	t { tS
u-	nat-	tached
V	n V	t { tS t
u-	nat-	tai-	na-	ble
V	n V	t eI	n V	b V l
u-	nat-	ten-	ded
V	n V	t e n	d V d
u-	nat-	trac-	tive
V	n V t	r { k	t I v
u-	nau-	di-	ted
V	n O:	d V	t V d
u-	nau-	then-	tic
V	n O:	T e n	t I k
u-	nau-	tho-	rized
V	n O:	T @r	aI z d
u-	ne-	qual
V	n i: k	w V l
u-	ne-	qualed
V	n i: k	w V l d
u-	ne-	qui-	vo-	cab-	ly
V	n I k	w I	v V	k V b	l i:
u-	ne-	qui-	vo-	cal
V	n I k	w I	v V	k V l
u-	ne-	qui-	vo-	cal-	ly
V	n i: k	w I	v V	k V	l i:
u-	ne-	thi-	cal
V	n e	T I	k V l
u-	ne-	thical-	ly
V	n e	T I k	l i:
u-	nea-	si-	ly
V	n i:	z V	l i:
u-	nea-	si-	ness
V	n i:	z i:	n V s
u-	nea-	sy
V	n i:	z i:
u-	near-	thing
V	n @r	T I N
u-	nearned
V	n @r n d
u-	nearth
V	n @r T
u-	nearth-	ly
V	n @r T	l i:
u-	nease
V	n i: z
u-	nes-	co
j u:	n e s	k @U
u-	ni
j u:	n i:
u-	ni-	cef
j u:	n I	s e f
u-	ni-	cel-	lu-	lar
j u:	n I	s e l	j V	l @r
u-	ni-	corn
j u:	n I	k O@ n
u-	ni-	cy-	cle
j u:	n I	s aI	k V l
u-	ni-	cy-	cles
j u:	n I	s aI	k V l z
u-	ni-	fi-	ca-	tion
j u:	n I	f I	k eI	S V n
u-	ni-	fied
j u:	n I	f aI d
u-	ni-	for-	mi-	ty
j u:	n I	f O@	m I	t i:
u-	ni-	form
j u:	n I	f O@ m
u-	ni-	form-	ly
j u:	n I	f O@ m	l i:
u-	ni-	formed
j u:	n I	f O@ m d
u-	ni-	forms
j u:	n I	f O@ m z
u-	ni-	fy
j u:	n I	f aI
u-	ni-	fy-	ing
j u:	n I	f aI	I N
u-	ni-	la-	te-	ra-	li-	sm
j u:	n I	l {	t @r	V	l I	z V m
u-	ni-	la-	te-	ral
j u:	n I	l {	t @r	V l
u-	ni-	la-	te-	ral-	ly
j u:	n I	l {	t @r	V	l i:
u-	ni-	le-	ver
j u:	n I	l i:	v @r
u-	ni-	le-	ver's
j u:	n I	l i:	v @r z
u-	ni-	ma-	gi-	na-	ble
V	n I	m {	dZ I	n V	b V l
u-	ni-	ma-	gi-	na-	tive
V	n I	m {	dZ I	n V	t I v
u-	ni-	ma-	gined
V	n I	m {	dZ I n d
u-	ni-	ro-	yal
j u:	n I@	OI	V l
u-	ni-	sex
j u:	n I	s e k s
u-	ni-	son
j u:	n I	s V n
u-	ni-	sons
j u:	n I	s V n z
u-	ni-	sys
j u:	n I	s I s
u-	ni-	ta-	ri-	an
j u:	n I	t e@	i:	V n
u-	ni-	ta-	ry
j u:	n I	t e@	i:
u-	ni-	tas
j u:	n aI	t V s
u-	ni-	ted
j u:	n aI	t V d
u-	ni-	ted's
j u:	n aI	t V d z
u-	ni-	thol-	der
j u:	n I t	h @U l	d @r
u-	ni-	thol-	ders
j u:	n I t	h @U l	d @r z
u-	ni-	ting
j u:	n aI	t I N
u-	ni-	ty
j u:	n I	t i:
u-	ni-	ver-	sa-	li-	ty
j u:	n I	v @r	s {	l I	t i:
u-	ni-	ver-	sal
j u:	n I	v @r	s V l
u-	ni-	ver-	sal-	ly
j u:	n I	v @r	s V	l i:
u-	ni-	ver-	ses
j u:	n I	v @r	s V z
u-	ni-	ver-	si-	ties
j u:	n I	v @r	s I	t i: z
u-	ni-	ver-	si-	ty
j u:	n I	v @r	s I	t i:
u-	ni-	ver-	si-	ty's
j u:	n I	v @r	s I	t i: z
u-	ni-	verse
j u:	n I	v @r s
u-	nim-	paired
V	n I m	p e@ d
u-	nim-	pe-	ded
V	n I m	p i:	d V d
u-	nim-	pea-	cha-	ble
V	n I m	p i:	tS V	b V l
u-	nim-	por-	tant
V	n I m	p O@	t V n t
u-	nim-	pres-	sive
V	n I m	p r e	s I v
u-	nim-	pressed
V	n I m	p r e s t
u-	nim-	proved
V	n I m	p r u: v d
u-	nin-	cor-	po-	ra-	ted
V	n I n	k O@	p @r	eI	t V d
u-	nin-	dic-	ted
V	n I n	d aI	t V d
u-	nin-	fec-	ted
V	n I n	f e k	t V d
u-	nin-	for-	ma-	tive
V	n I n	f O@	m V	t I v
u-	nin-	formed
V	n I n	f O@ m d
u-	nin-	ha-	bi-	ta-	ble
V	n I n	h {	b V	t V	b V l
u-	nin-	ha-	bi-	ted
V	n I n	h {	b I	t I d
u-	nin-	hi-	bi-	ted
V	n I n	h I	b I	t I d
u-	nio-	ni-	sm
j u: n	j V	n I	z V m
u-	nio-	ni-	za-	tion
j u: n	j V	n I	z eI	S V n
u-	nio-	ni-	zing
j u: n	j V	n aI	z I N
u-	nio-	nist
j u: n	j V	n I s t
u-	nio-	nists
j u: n	j V	n I s t s
u-	nio-	nize
j u: n	j V	n aI z
u-	nio-	nized
j u: n	j V	n aI z d
u-	nion
j u: n	j V n
u-	nion-	dale
j u: n	j V n	d eI l
u-	nions
j u: n	j V n z
u-	nion's
j u: n	j V n z
u-	nique
j u:	n i: k
u-	nique-	ly
j u:	n i: k	l i:
u-	nique-	ness
j u:	n i: k	n V s
u-	nis-	sued
V	n I	S u: d
u-	nit
j u:	n I t
u-	nite
j u:	n aI t
u-	nites
j u:	n aI t s
u-	nits
j u:	n I t s
u-	nit's
j u:	n I t s
u-	nix
j u:	n I k s
u-	no
V	n @U
u-	nob-	tai-	na-	ble
V	n V b	t eI	n V	b V l
u-	nob-	tru-	sive
V	n V b	t r u:	s I v
u-	nobs-	truc-	ted
V	n V b	s t r V k	t V d
u-	nu-	sa-	ble
V n	j u:	z V	b V l
u-	num
j u:	n V m
u-	pham
V	p V m
u-	phea-	val
V p	h i:	v V l
u-	phea-	vals
V p	h i:	v V l z
u-	pon
V	p Q n
u-	ra-	ni-	um
j @r	eI	n i:	V m
u-	ra-	nus
j u:	r V	n V s
u-	ral
j U@	V l
u-	rals
j U@	V l z
u-	re-	a
j @r	i:	V
u-	re-	mi-	a
j @r	i:	m i:	V
u-	re-	na
@r	eI	n V
u-	re-	thane
j @r	V	T eI n
u-	reth-	ra
j @r	i: T	r V
u-	rey
j @r	i:
u-	ri
j @r	i:
u-	ri-	an
j @r	i:	V n
u-	ri-	as
j @r	i:	V z
u-	ri-	na-	ly-	sis
j @r	I	n {	l I	s I s
u-	ri-	na-	ry
j @r	I	n e@	i:
u-	ri-	na-	ting
j @r	I	n eI	t I N
u-	ri-	nate
j @r	I	n eI t
u-	ric
j @r	I k
u-	rich
j @r	I k
u-	rine
j @r	I n
u-	ri's
j @r	i: z
u-	ro-	ki-	nase
j @r	V	k V	n eI z
u-	ro-	lo-	gist
j @r	Q	l V	dZ V s t
u-	ro-	lo-	gists
j @r	Q	l V	dZ V s t s
u-	ro-	lo-	gy
j @r	Q	l V	dZ i:
u-	ru-	gua-	yan
j @r	V g	w eI	V n
u-	ru-	guay
j @r	V g	w eI
u-	ru-	guay's
j @r	V g	w eI z
u-	ry
j u:	r i:
u-	s-	a
j u:	e	s eI
u-	s-	s
j u:	e	s e s
u-	sa-	ble
j u:	z V	b V l
u-	sa-	ges
j u:	s V	dZ V z
u-	sage
j u:	s V dZ
u-	ser
j u:	z @r
u-	sers
j u:	z @r z
u-	ser's
j u:	z @r z
u-	ses
j u:	s V z
u-	she-	ring
V	S @r	I N
u-	sher
V	S @r
u-	shered
V	S @r d
u-	shers
V	S @r z
u-	sing
j u:	z I N
u-	su-	al
j u:	Z V	w V l
u-	su-	al-	ly
j u:	Z V	w V	l i:
u-	su-	ry
j u:	Z @r	i:
u-	sur-	pa-	tion
j u:	s @r	p eI	S V n
u-	sur-	ping
j u:	s @r	p I N
u-	surp
j u:	s @r p
u-	surped
j u:	s @r p t
u-	surps
j u:	s @r p s
u-	ta-	ma-	ro
j u:	t V	m Q@	@U
u-	tah
j u:	t O:
)"
R"(u-	tah's
j u:	t Q z
u-	te-	rine
j u:	t @r	I n
u-	te-	ro
j u:	t @r	@U
u-	te-	rus
j u:	t @r	V s
u-	ten-	sil
j u:	t e n	s I l
u-	ten-	sils
j u:	t e n	s I l z
u-	ther
j u:	T @r
u-	ti-	ca
j u:	t I	k V
u-	ti-	li-	ta-	ri-	an
j u:	t I	l I	t e@	i:	V n
u-	ti-	li-	ties
j u:	t I	l I	t i: z
u-	ti-	li-	ty
j u:	t I	l I	t i:
u-	ti-	li-	ty's
j u:	t I	l I	t i: z
u-	ti-	li-	za-	tion
j u:	t I	l I	z eI	S V n
u-	ti-	li-	zes
j u:	t I	l aI	z V z
u-	ti-	li-	zing
j u:	t I	l aI	z I N
u-	ti-	lize
j u:	t I	l aI z
u-	ti-	lized
j u:	t I	l aI z d
u-	to-	pi-	a
j u:	t @U	p i:	V
u-	to-	pi-	an
j u:	t @U	p i:	V n
u-	to-	pi-	ans
j u:	t @U	p i:	V n z
u-	to-	pi-	as
j u:	t @U	p i:	V z
u-	va
j u:	v V
u-	zi
u:	z i:
u-	zis
u:	z i: z
u.
I k
ud-	din
V	d I n
ude
u: d
ueh-	ling
U	l I N
ug-	li-	er
V g	l i:	@r
ug-	li-	est
V g	l i:	V s t
ug-	li-	ness
V g	l i:	n V s
ug-	ly
V g	l i:
ug-	ric
j u: g	r I k
ugh
V g
uh
V
uh-	huh
V	h V
uh-	land
u:	l V n d
uhde
V d
uhh
V
uk-	rai-	ni-	an
j u: k	r eI	n i:	V n
uk-	rai-	ni-	ans
j u: k	r eI	n i:	V n z
uk-	raine
j u: k	r eI n
uk-	raine's
j u: k	r eI n z
ul
V l
ul-	bricht
V l	b r I k t
ul-	cer
V l	s @r
ul-	cers
V l	s @r z
ul-	land
V	l V n d
ul-	man
V l	m V n
ul-	mer
V l	m @r
ul-	mus
V l	m V s
ul-	ri-	ca
V l	r I	k V
ul-	ric
V l	r I k
ul-	rich
V l	r I tS
ul-	rick
V l	r I k
ul-	san
V l	s V n
ul-	te-	ri-	or
V l	t I@	i:	@r
ul-	ti-	ma
V l	t I	m V
ul-	ti-	ma-	tum
V l	t I	m eI	t V m
ul-	ti-	ma-	tums
V l	t I	m eI	t V m z
ul-	ti-	mate
V l	t I	m V t
ul-	ti-	mate-	ly
V l	t I	m V t	l i:
ul-	va
u: l	v V
ull-	man
V l	m V n
ulm
V l m
uls-	ter
V l	s t @r
ult-	ra
V l	t r V
ult-	ra-	con-	ser-	va-	tive
V l	t r V	k V n	s @r	v V	t I v
ult-	ra-	mo-	dern
V l	t r V	m Q	d @r n
ult-	ra-	na-	tio-	na-	list
V l	t r V	n {	S V	n V	l V s t
ult-	ra-	na-	tio-	na-	lists
V l	t r V	n {	S V	n V	l V s t s
ult-	ra-	so-	nic
V l	t r V	s Q	n I k
ult-	ra-	sound
V l	t r V	s aU n d
ult-	ra-	vi-	o-	let
V l	t r V	v aI	V	l V t
um
V m
um-	bar-	ger
V m	b Q@	g @r
um-	bel
V m	b V l
um-	ber-	to
V m	b e@	t @U
um-	bi-	li-	cal
V m	b I	l I	k V l
um-	ble
V m	b V l
um-	land
V m	l V n d
um-	pi-	re
V m	p aI	@r
um-	pi-	res
V m	p aI	@r z
umb-	ra
V m	b r V
umb-	rage
V m	b r I dZ
umb-	rel-	la
V m	b r e	l V
umb-	rel-	las
V m	b r e	l V z
umm
V m
ump-	teen
V m	p t i: n
ump-	teenth
V m	p t i: n T
un
V n
un-	a-	me-	ri-	can
V	n V	m e@	I	k V n
un-	ba-	lance
V n	b {	l V n s
un-	ba-	lanced
V n	b {	l V n s t
un-	be-	co-	ming
V n	b I	k V	m I N
un-	be-	lie-	va-	ble
V n	b V	l i:	v V	b V l
un-	be-	lie-	vab-	ly
V n	b V	l i:	v V b	l i:
un-	be-	lie-	ving
V n	b V	l i:	v I N
un-	bea-	ra-	ble
V n	b e@	V	b V l
un-	bea-	rab-	ly
V n	b e@	V b	l i:
un-	bea-	ta-	ble
V n	b i:	t V	b V l
un-	bea-	ten
V n	b i:	t V n
un-	bek-	nown
V n	b i:	n @U n
un-	bek-	nownst
V n	b i:	n @U n s t
un-	ben-	ding
V n	b e n	d I N
un-	bend
V n	b e n d
un-	bi-	ased
V n	b aI	V s t
un-	ble-	mished
V n	b l e	m I S t
un-	bol-	ted
V n	b @U l	t V d
un-	bolt
V n	b @U l t
un-	born
V n	b O@ n
un-	boun-	ded
V n	b aU n	d V d
un-	bound
V n	b aU n d
un-	bowed
V n	b @U d
un-	bran-	ded
V n	b r { n	d V d
un-	bri-	dled
V n	b r aI	d V l d
un-	bro-	ken
V n	b r @U	k V n
un-	buil-	da-	ble
V n	b I l	d V	b V l
un-	built
V n	b I l t
un-	bun-	dle
V n	b V n	d V l
un-	bund-	ling
V n	b V n	d l I N
un-	bur-	den
V n	b @r	d V n
un-	bur-	dened
V n	b @r	d V n d
un-	burned
V n	b @r n d
un-	but-	ton
V n	b V	t V n
un-	but-	toned
V n	b V	t V n d
un-	ca-	pi-	ta-	lized
V n	k {	p V	t V	l aI z d
un-	ca-	ring
V n	k e@	I N
un-	called
V n	k O: l d
un-	can-	ni-	ly
V n	k {	n V	l i:
un-	can-	ny
V n	k {	n i:
un-	ce-	re-	mo-	ni-	ous
V n	s e@	V	m @U	n i:	V s
un-	ce-	re-	mo-	ni-	ous-	ly
V n	s e@	V	m @U	n i:	V s	l i:
un-	cea-	sing
V n	s i:	s I N
un-	cen-	sored
V n	s e n	s @r d
un-	cer-	tain
V n	s @r	t V n
un-	cer-	tain-	ly
V n	s @r	t V n	l i:
un-	cer-	tain-	ties
V n	s @r	t V n	t i: z
un-	cer-	tain-	ty
V n	s @r	t V n	t i:
un-	cha-	rac-	te-	ris-	tic
V n	k e@	I k	t @r	I s	t I k
un-	cha-	rac-	te-	ris-	tical-	ly
V n	k e@	I k	t @r	I s	t I k	l i:
un-	chal-	lenged
V n	tS {	l V n dZ d
un-	chan-	ging
V n	tS eI n	dZ I N
un-	changed
V n	tS eI n dZ d
un-	char-	ted
V n	tS Q@	t V d
un-	char-	tered
V n	tS Q@	t @r d
un-	checked
V n	tS e k t
un-	ci-	vi-	lized
V n	s I	v V	l aI z d
un-	ci-	vil
V n	s I	v V l
un-	claimed
V n	k l eI m d
un-	clamp
V n	k l { m p
un-	clamps
V n	k l { m p s
un-	clas-	si-	fied
V n	k l {	s V	f aI d
un-	clas-	si-	fy
V n	k l {	s V	f aI
un-	cle
V N	k V l
un-	cle's
V N	k V l z
un-	co-	o-	pe-	ra-	tive
V n	k @U	Q	p @r	V	t I v
un-	co-	or-	di-	na-	ted
V n	k @U	O@	d V	n eI	t V d
un-	co-	ve-	ring
V n	k V	v @r	I N
un-	co-	ver
V n	k V	v @r
un-	co-	vered
V n	k V	v @r d
un-	co-	vers
V n	k V	v @r z
un-	coa-	ted
V n	k @U	t V d
un-	coat
V n	k @U t
un-	coil
V n	k OI l
un-	coiled
V n	k OI l d
un-	col-	lec-	ta-	ble
V n	k V	l e k	t V	b V l
un-	col-	lec-	ted
V n	k V	l e k	t V d
un-	col-	lec-	ti-	ble
V n	k V	l e k	t V	b V l
un-	com-	for-	ta-	ble
V n	k V m	f @r	t V	b V l
un-	com-	mit-	ted
V n	k V	m I	t V d
un-	com-	mon
V n	k Q	m V n
un-	com-	mon-	ly
V n	k Q	m V n	l i:
un-	com-	pe-	ti-	tive
V n	k V m	p e	t V	t I v
un-	com-	pen-	sa-	ted
V n	k Q m	p V n	s eI	t V d
un-	comfor-	tab-	ly
V n	k V m	f t V b	l i:
un-	comp-	le-	ted
V n	k V m	p l i:	t V d
un-	comp-	lete
V n	k V m	p l i: t
un-	comp-	li-	ca-	ted
V n	k Q m	p l V	k eI	t V d
un-	comp-	ro-	mi-	sing
V n	k Q m	p r V	m aI	z I N
un-	con-	cealed
V n	k V n	s i: l d
un-	con-	cern
V n	k V n	s @r n
un-	con-	cerned
V n	k V n	s @r n d
un-	con-	di-	tio-	nal
V n	k V n	d I	S V	n V l
un-	con-	di-	tio-	nal-	ly
V n	k V n	d I	S V	n V	l i:
un-	con-	fined
V n	k V n	f aI n d
un-	con-	firmed
V n	k V n	f @r m d
un-	con-	nec-	ted
V n	k V	n e k	t V d
un-	con-	scio-	na-	ble
V n	k Q n	S V	n V	b V l
un-	con-	scious
V n	k Q n	S V s
un-	con-	scious-	ly
V n	k Q n	S V s	l i:
un-	con-	scious-	ness
V n	k Q n	S V s	n e s
un-	con-	so-	li-	da-	ted
V n	k V n	s Q	l V	d eI	t V d
un-	con-	sti-	tu-	tio-	nal
V n	k Q n	s t I	t u:	S V	n V l
un-	con-	sti-	tu-	tio-	nal-	ly
V n	k Q n	s t I	t u:	S V	n V	l i:
un-	con-	ta-	mi-	na-	ted
V n	k V n	t {	m V	n eI	t V d
un-	con-	tes-	ted
V n	k V n	t e s	t V d
un-	con-	tra-	dic-	ted
V n	k O: n	t r V	d I k	t V d
un-	con-	tro-	ver-	sial
V n	k Q n	t r V	v @r	S V l
un-	con-	trol-	la-	ble
V n	k V n	t r @U	l V	b V l
un-	con-	trol-	lab-	ly
V n	k V n	t r @U	l V b	l i:
un-	con-	trolled
V n	k V n	t r @U l d
un-	con-	ven-	tio-	nal
V n	k V n	v e n	S V	n V l
un-	con-	ver-	ted
V n	k V n	v @r	t V d
un-	con-	vin-	cing
V n	k V n	v I n	s I N
un-	con-	vinced
V n	k V n	v I n s t
un-	cool
V n	k u: l
un-	cor-	rec-	ted
V n	k @r	e k	t V d
un-	cor-	ro-	bo-	ra-	ted
V n	k @r	Q	b @r	eI	t V d
un-	cork
V n	k O@ k
un-	corked
V n	k O@ k t
un-	corks
V n	k O@ k s
un-	cou-	ple
V n	k V	p V l
un-	coun-	ted
V n	k aU n	t V d
un-	couth
V n	k u: T
un-	cri-	ti-	cal
V n	k r I	t I	k V l
un-	cri-	ti-	cal-	ly
V n	k r I	t I	k V	l i:
un-	cured
V n	k j @r d
un-	cut
V n	k V t
un-	da-	maged
V n	d {	m V dZ d
un-	da-	ted
V n	d eI	t V d
un-	daun-	ted
V n	d O: n	t V d
un-	de-	ci-	ded
V n	d V	s aI	d V d
un-	de-	ci-	deds
V n	d V	s aI	d V d z
un-	de-	fea-	ted
V n	d V	f i:	t V d
un-	de-	fined
V n	d V	f aI n d
un-	de-	li-	vered
V n	d V	l I	v @r d
un-	de-	mo-	cra-	tic
V n	d e	m V k	r {	t I k
un-	de-	ni-	a-	ble
V n	d V	n aI	V	b V l
un-	de-	ni-	ab-	ly
V n	d V	n aI	V b	l i:
un-	de-	rarm
V n	d @r	Q@ m
un-	de-	ser-	ving
V n	d V	z @r	v I N
un-	de-	served
V n	d V	z @r v d
un-	de-	si-	ra-	ble
V n	d V	z aI	r V	b V l
un-	de-	tec-	ta-	ble
V n	d V	t e k	t V	b V l
un-	de-	tec-	ted
V n	d V	t e k	t V d
un-	de-	ter-	mi-	ning
V n	d V	t @r	m I	n I N
un-	de-	ter-	mined
V n	d V	t @r	m V n d
un-	de-	terred
V n	d V	t @r d
un-	de-	ve-	loped
V n	d V	v e	l V p t
un-	dec-	lared
V n	d V k	l e@ d
un-	der
V n	d @r
un-	der-	a-	chie-	ver
V n	d @r	V	tS i:	v @r
un-	der-	a-	chie-	vers
V n	d @r	V	tS i:	v @r z
un-	der-	age
V n	d @r	eI dZ
un-	der-	bel-	ly
V n	d @r	b e	l i:
un-	der-	bid
V n	d @r	b I d
un-	der-	brush
V n	d @r b	r V S
un-	der-	ca-	pi-	ta-	lize
V n	d @r	k {	p V	t V	l aI z
un-	der-	ca-	pi-	ta-	lized
V n	d @r	k {	p V	t V	l aI z d
un-	der-	car-	riage
V n	d @r	k {	r I dZ
un-	der-	class
V n	d @r k	l { s
un-	der-	class-	men
V n	d @r k	l { s	m e n
un-	der-	co-	ver
V n	d @r	k V	v @r
un-	der-	coat
V n	d @r	k @U t
un-	der-	cook
V n	d @r	k U k
un-	der-	cooked
V n	d @r	k U k t
un-	der-	coun-	ted
V n	d @r	k aU n	t V d
un-	der-	count
V n	d @r	k aU n t
un-	der-	cur-	rent
V n	d @r	k @r	V n t
un-	der-	cur-	rents
V n	d @r	k @r	V n t s
un-	der-	cut
V n	d @r	k V t
un-	der-	cut-	ting
V n	d @r	k V	t I N
un-	der-	cuts
V n	d @r	k V t s
un-	der-	de-	ve-	lop
V n	d @r	d I	v e	l V p
un-	der-	de-	ve-	lop-	ment
V n	d @r	d V	v e	l V p	m V n t
un-	der-	de-	ve-	loped
V n	d @r	d I	v e	l V p t
un-	der-	dog
V n	d @r	d O: g
un-	der-	dogs
V n	d @r	d O: g z
un-	der-	down
V n	d @r	d aU n
un-	der-	emp-	loy-	ment
V n	d @r	V m	p l OI	m V n t
un-	der-	emp-	loyed
V n	d @r	V m	p l OI d
un-	der-	es-	ti-	ma-	ted
V n	d @r	e s	t I	m eI	t I d
un-	der-	es-	ti-	ma-	ting
V n	d @r	e s	t I	m eI	t I N
un-	der-	es-	ti-	mate
V n	d @r	e s	t I	m eI t
un-	der-	es-	ti-	mates
V n	d @r	e s	t I	m eI t s
un-	der-	fi-	nance
V n	d @r	f V	n { n s
un-	der-	fi-	nanced
V n	d @r	f V	n { n s t
un-	der-	foot
V n	d @r	f U t
un-	der-	fun-	ded
V n	d @r	f V n	d V d
un-	der-	fun-	ding
V n	d @r	f V n	d I N
un-	der-	fund
V n	d @r	f V n d
un-	der-	gar-	ment
V n	d @r	g Q@	m V n t
un-	der-	gar-	ments
V n	d @r	g Q@	m V n t s
un-	der-	go
V n	d @r	g @U
un-	der-	go-	ing
V n	d @r	g @U	I N
un-	der-	goes
V n	d @r	g @U z
un-	der-	gone
V n	d @r	g O: n
un-	der-	gra-	du-	ate
V n	d @r g	r {	dZ V	w V t
un-	der-	gra-	du-	ates
V n	d @r g	r {	dZ V	w V t s
un-	der-	grad
V n	d @r g	r { d
un-	der-	ground
V n	d @r g	r aU n d
un-	der-	growth
V n	d @r g	r @U T
un-	der-	han-	ded
V n	d @r	h { n	d V d
un-	der-	hill
V n	d @r	h I l
un-	der-	in-	sure
V n	d @r	I n	S O@
un-	der-	in-	sured
V n	d @r	I n	S O@ d
un-	der-	li-	ning
V n	d @r	l aI	n I N
un-	der-	lie
V n	d @r	l aI
un-	der-	lies
V n	d @r	l aI z
un-	der-	line
V n	d @r	l aI n
un-	der-	lined
V n	d @r	l aI n d
un-	der-	lines
V n	d @r	l aI n z
un-	der-	ling
V n	d @r	l I N
un-	der-	lings
V n	d @r	l I N z
un-	der-	ly
V n	d @r	l aI
un-	der-	ly-	ing
V n	d @r	l aI	I N
un-	der-	man
V n	d @r	m { n
un-	der-	manned
V n	d @r	m { n d
un-	der-	mi-	ning
V n	d @r	m aI	n I N
un-	der-	mine
V n	d @r	m aI n
un-	der-	mined
V n	d @r	m aI n d
un-	der-	mines
V n	d @r	m aI n z
un-	der-	neath
V n	d @r	n i: T
un-	der-	nou-	rish
V n	d @r	n @r	I S
un-	der-	nou-	rished
V n	d @r	n @r	I S t
un-	der-	paid
V n	d @r	p eI d
un-	der-	pants
V n	d @r	p { n t s
un-	der-	pass
V n	d @r	p { s
un-	der-	pay
V n	d @r	p eI
un-	der-	pay-	ing
V n	d @r	p eI	I N
un-	der-	pay-	ment
V n	d @r	p eI	m V n t
un-	der-	pay-	ments
V n	d @r	p eI	m V n t s
un-	der-	per-	for-	mance
V n	d @r	p @r	f O@	m V n s
un-	der-	per-	for-	mer
V n	d @r	p @r	f O@	m @r
un-	der-	per-	for-	ming
V n	d @r	p @r	f O@	m I N
un-	der-	per-	form
V n	d @r	p @r	f O@ m
un-	der-	per-	formed
V n	d @r	p @r	f O@ m d
un-	der-	pin
V n	d @r	p I n
un-	der-	pin-	ning
V n	d @r	p I	n I N
un-	der-	pin-	nings
V n	d @r	p I	n I N z
un-	der-	pinned
V n	d @r	p I n d
un-	der-	play
V n	d @r p	l eI
un-	der-	played
V n	d @r p	l eI d
un-	der-	po-	wer
V n	d @r	p aU	@r
un-	der-	po-	wered
V n	d @r	p aU	@r d
un-	der-	pri-	cing
V n	d @r p	r aI	s I N
un-	der-	price
V n	d @r p	r aI s
un-	der-	priced
V n	d @r p	r aI s t
un-	der-	ra-	ted
V n	d @r	r eI	t V d
un-	der-	rate
V n	d @r	r eI t
un-	der-	re-	por-	ted
V n	d @r	r V	p O@	t V d
un-	der-	re-	por-	ting
V n	d @r	r V	p O@	t I N
un-	der-	re-	port
V n	d @r	r V	p O@ t
un-	der-	re-	pre-	sen-	ted
V n	d @r	r e p	r V	z e n	t V d
un-	der-	re-	pre-	sent
V n	d @r	r e p	r V	z e n t
un-	der-	sco-	ring
V n	d @r s	k O@	I N
un-	der-	score
V n	d @r s	k O@
un-	der-	scored
V n	d @r s	k O@ d
un-	der-	scores
V n	d @r s	k O@ z
un-	der-	sea
V n	d @r	s i:
un-	der-	seas
V n	d @r	s i: z
un-	der-	sec-	re-	ta-	ry
V n	d @r	s e k	r V	t e@	i:
un-	der-	sel-	ling
V n	d @r	s e	l I N
un-	der-	sell
V n	d @r	s e l
un-	der-	serve
V n	d @r	s @r v
un-	der-	served
V n	d @r	s @r v d
un-	der-	shirt
V n	d @r	S @r t
un-	der-	shirts
V n	d @r	S @r t s
un-	der-	side
V n	d @r	s aI d
un-	der-	sized
V n	d @r	s aI z d
un-	der-	sold
V n	d @r	s @U l d
un-	der-	spin
V n	d @r s	p I n
un-	der-	sta-	ted
V n	d @r s	t eI	t V d
un-	der-	sta-	ting
V n	d @r s	t eI	t I N
un-	der-	staff
V n	d @r s	t { f
un-	der-	staffed
V n	d @r s	t { f t
un-	der-	stan-	da-	ble
V n	d @r s	t { n	d V	b V l
un-	der-	stan-	dab-	ly
V n	d @r s	t { n	d V b	l i:
un-	der-	stan-	ding
V n	d @r s	t { n	d I N
un-	der-	stan-	dings
V n	d @r s	t { n	d I N z
un-	der-	stand
V n	d @r s	t { n d
un-	der-	stands
V n	d @r s	t { n d z
un-	der-	state
V n	d @r s	t eI t
un-	der-	state-	ment
V n	d @r s	t eI t	m V n t
un-	der-	states
V n	d @r s	t eI t s
un-	der-	sto-	ry
V n	d @r s	t O@	i:
un-	der-	stood
V n	d @r s	t U d
un-	der-	stu-	dy
V n	d @r s	t V	d i:
un-	der-	sub-	scribed
V n	d @r	s V b	s k r aI b d
un-	der-	ta-	ken
V n	d @r	t eI	k V n
un-	der-	ta-	ker
V n	d @r	t eI	k @r
un-	der-	ta-	king
V n	d @r	t eI	k I N
un-	der-	ta-	kings
V n	d @r	t eI	k I N z
un-	der-	take
V n	d @r	t eI k
un-	der-	takes
V n	d @r	t eI k s
un-	der-	tone
V n	d @r	t @U n
un-	der-	tones
V n	d @r	t @U n z
un-	der-	took
V n	d @r	t U k
un-	der-	tow
V n	d @r	t @U
un-	der-	tows
V n	d @r	t @U z
un-	der-	u-	ti-	lize
V n	d @r	j u:	t I	l aI z
un-	der-	u-	ti-	lized
V n	d @r	j u:	t I	l aI z d
un-	der-	use
V n	d @r	j u: z
un-	der-	used
V n	d @r	j u: z d
un-	der-	va-	lu-	a-	tion
V n	d @r	v { l	j u:	eI	S V n
un-	der-	va-	lu-	ing
V n	d @r	v { l	j u:	I N
un-	der-	va-	lue
V n	d @r	v { l	j u:
un-	der-	va-	lued
V n	d @r	v { l	j u: d
un-	der-	va-	lues
V n	d @r	v { l	j u: z
un-	der-	wa-	ter
V n	d @r	w O:	t @r
un-	der-	way
V n	d @r	w eI
un-	der-	wear
V n	d @r	w e@
un-	der-	weigh-	ted
V n	d @r	w eI	t V d
un-	der-	weight
V n	d @r	w eI t
un-	der-	went
V n	d @r	w e n t
un-	der-	wood
V n	d @r	w U d
un-	der-	woods
V n	d @r	w U d z
un-	der-	world
V n	d @r	w @r l d
un-	der-	wri-	ter
V n	d @r	r aI	t @r
un-	der-	wri-	ters
V n	d @r	r aI	t @r z
un-	der-	wri-	ter's
V n	d @r	r aI	t @r z
un-	der-	wri-	ting
V n	d @r	r aI	t I N
un-	der-	wri-	tings
V n	d @r	r aI	t I N z
un-	der-	writ-	ten
V n	d @r	r I	t V n
un-	der-	write
V n	d @r	r aI t
un-	der-	writes
V n	d @r	r aI t s
un-	der-	wrote
V n	d @r	r @U t
un-	di-	ag-	nosed
V n	d aI	{ g	n @U s t
un-	di-	lu-	ted
V n	d I	l u:	t I d
un-	di-	lute
V n	d I	l u: t
un-	di-	mi-	nished
V n	d I	m I	n I S t
un-	di-	ver-	si-	fied
V n	d I	v @r	s I	f aI d
un-	di-	vi-	ded
V n	d V	v aI	d V d
un-	did
V n	d I d
un-	dif-	fe-	ren-	ti-	a-	ted
V n	d I	f @r	e n	S i:	eI	t V d
un-	dig-	ni-	fied
V n	d I g	n V	f aI d
un-	dine
V n	d i: n
un-	dip-	lo-	ma-	tic
V n	d I p	l V	m {	t I k
un-	dip-	lo-	ma-	tical-	ly
V n	d I p	l V	m {	t I k	l i:
un-	dis-	cip-	lined
V n	d I	s V p	l I n d
un-	dis-	closed
V n	d I s	k l @U z d
un-	dis-	co-	vered
V n	d I s	k V	v @r d
un-	dis-	guised
V n	d I s	g aI z d
un-	dis-	pu-	ted
V n	d I s	p j u:	t V d
un-	dis-	tin-	guished
V n	d I s	t I N	g w I S t
un-	dis-	tri-	bu-	ted
V n	d I s	t r I b	j u:	t V d
un-	dis-	turbed
V n	d I s	t @r b d
un-	do
V n	d u:
un-	do-	cu-	men-	ted
V n	d Q k	j V	m e n	t V d
un-	do-	ing
V n	d u:	I N
un-	doc-	king
V n	d Q	k I N
un-	dock
V n	d Q k
un-	done
V n	d V n
un-	doub-	ted
V n	d aU	t V d
un-	doub-	ted-	ly
V n	d aU	t V d	l i:
un-	dreamed
V n	d r i: m d
un-	dress
V n	d r e s
un-	dressed
V n	d r e s t
un-	du-	la-	ting
V n	dZ V	l eI	t I N
un-	du-	late
V n	dZ V	l eI t
un-	du-	ly
V n	d u:	l i:
un-	due
V n	d u:
un-	dy-	ing
V n	d aI	I N
un-	e-	co-	no-	mi-	cal
V	n e	k V	n Q	m I	k V l
un-	e-	co-	no-	mic
V	n e	k V	n Q	m I k
un-	e-	di-	ted
V	n e	d V	t V d
un-	e-	du-	ca-	ted
V	n e	dZ U	k eI	t V d
un-	e-	lec-	ta-	ble
V	n V	l e k	t V	b V l
un-	e-	lec-	ted
V	n V	l e k	t V d
un-	e-	mo-	tio-	nal
V	n i:	m @U	S V	n V l
un-	e-	ven
V	n i:	v V n
un-	e-	ven-	ly
V	n i:	v V n	l i:
un-	e-	vent-	ful
V	n i:	v e n	t f V l
un-	emp-	loy
V	n V m	p l OI
un-	emp-	loy-	a-	ble
V	n V m	p l OI	V	b V l
un-	emp-	loy-	ment
V	n V m	p l OI	m V n t
un-	emp-	loyed
V	n e m	p l OI d
un-	en-	cum-	ber
V	n e n	k V m	b @r
un-	en-	cum-	bered
V	n e n	k V m	b @r d
un-	en-	ding
V	n e n	d I N
)"
R"(un-	en-	for-	cea-	ble
V	n e n	f O@	s V	b V l
un-	en-	forced
V	n e n	f O@ s t
un-	en-	ligh-	tened
V	n e n	l aI	t V n d
un-	en-	thu-	si-	as-	tic
V	n V n	T u:	z i:	{ s	t I k
un-	en-	u-	me-	ra-	ted
V	n V	n u:	m @r	eI	t V d
un-	en-	vi-	a-	ble
V	n e n	v i:	V	b V l
un-	ex-	ci-	ting
V	n I k	s aI	t I N
un-	ex-	er-	cised
V	n e k	s @r	s aI z d
un-	ex-	pec-	ted
V	n I k	s p e k	t V d
un-	ex-	pec-	ted-	ly
V	n I k	s p e k	t V d	l i:
un-	ex-	pi-	red
V	n I k	s p aI	@r d
un-	ex-	plai-	na-	ble
V	n I k	s p l eI	n V	b V l
un-	ex-	plained
V	n I k	s p l eI n d
un-	ex-	plo-	ded
V	n I k	s p l @U	d V d
un-	ex-	ploi-	ted
V	n I k	s p l OI	t V d
un-	ex-	plored
V	n I k	s p l O@ d
un-	fa-	mi-	lia-	ri-	ties
V n	f V	m I l	j e@	V	t i: z
un-	fa-	mi-	lia-	ri-	ty
V n	f V	m I l	j e@	V	t i:
un-	fa-	mi-	liar
V n	f V	m I l	j @r
un-	fa-	shio-	na-	ble
V n	f {	S V	n V	b V l
un-	fa-	tho-	ma-	ble
V n	f {	T V	m V	b V l
un-	fa-	vo-	ra-	ble
V n	f eI	v @r	V	b V l
un-	fa-	vo-	rab-	ly
V n	f eI	v @r	V b	l i:
un-	fai-	ling
V n	f eI	l I N
un-	fai-	ling-	ly
V n	f eI	l I N	l i:
un-	fair
V n	f e@
)"