R"(pep-	tide
ph e p	t aI d
pep-	tides
ph e p	t aI d z
per
ph @r
per-	ce-	val
ph @r	s eI	v { l
per-	cei-	ving
ph @r	s i:	v I N
per-	ceive
ph @r	s i: v
per-	ceived
ph @r	s i: v d
per-	ceives
ph @r	s i: v z
per-	cen-	ta-	ges
ph @r	s e n	t I	dZ V z
per-	cen-	tage
ph @r	s e n	t I dZ
per-	cen-	tile
ph @r	s e n	t aI l
per-	cen-	tiles
ph @r	s e n	t aI l z
per-	cent
ph @r	s e n t
per-	cents
ph @r	s e n t s
per-	cep-	ti-	ble
ph @r	s e p	t I	b V l
per-	cep-	tion
ph @r	s e p	S V n
per-	cep-	tions
ph @r	s e p	S V n z
per-	cep-	tive
ph @r	s e p	t I v
per-	cep-	tu-	al
ph @r	s e p	tS V	w V l
per-	ches
ph @r	tS V z
per-	ci-	pi-	ent
ph @r	s I	p i:	V n t
per-	ci-	val
ph @r	s I	v V l
per-	co-	la-	ting
ph @r	k V	l eI	t I N
per-	co-	la-	tor
ph @r	k V	l eI	t @r
per-	co-	late
ph @r	k V	l eI t
per-	cu-	ta-	ne-	ous
ph @r k	j u:	t eI	n i:	V s
per-	cus-	sio-	nist
ph @r	k V	S V	n I s t
per-	cus-	sion
ph @r	k V	S V n
per-	cus-	sive
ph @r	k V	s I v
per-	cy
ph @r	s i:
per-	cy's
ph @r	s i: z
per-	di-	ta
ph @r	d i:	t V
per-	due
ph @r	d u:
per-	fec-	ta
ph @r	f e k	t V
per-	fec-	ted
ph @r	f e k	t V d
per-	fec-	ting
ph @r	f e k	t I N
per-	fec-	tio-	ni-	sm
ph @r	f e k	S V	n I	z V m
per-	fec-	tio-	nist
ph @r	f e k	S V	n I s t
per-	fec-	tion
ph @r	f e k	S V n
per-	fect
ph @r	f e k t
per-	fect-	ly
ph @r	f V k	t l i:
per-	fi-	dy
ph @r	f I	d i:
per-	fo-	ra-	ted
ph @r	f @r	eI	t V d
per-	fo-	ra-	tion
ph @r	f @r	eI	S V n
per-	fo-	ra-	tions
ph @r	f @r	eI	S V n z
per-	fo-	rate
ph @r	f @r	eI t
per-	for-	man-	ces
ph @r	f O@	m V n	s V z
per-	for-	mance
ph @r	f O@	m V n s
per-	for-	mer
ph @r	f O@	m @r
per-	for-	mers
ph @r	f O@	m @r z
per-	for-	ming
ph @r	f O@	m I N
per-	force
ph @r	f O@ s
per-	form
ph @r	f O@ m
per-	formed
ph @r	f O@ m d
per-	forms
ph @r	f O@ m z
per-	fume
ph @r f	j u: m
per-	fumed
ph @r f	j u: m d
per-	fumes
ph @r f	j u: m z
per-	func-	to-	ry
ph @r	f V N	k t @r	i:
per-	ga-	mon
ph @r	g V	m V n
per-	go-	la
ph @r	g @U	l V
per-	ham
ph @r	h V m
per-	haps
ph @r	h { p s
per-	ju-	rer
ph @r	dZ @r	@r
per-	ju-	ring
ph @r	dZ @r	I N
per-	ju-	ry
ph @r	dZ @r	i:
per-	jure
ph @r	dZ @r
per-	jured
ph @r	dZ @r d
per-	kin
ph @r	k I n
per-	king
ph @r	k I N
per-	kins
ph @r	k I n z
per-	ky
ph @r	k i:
per-	la
ph @r	l V
per-	ley
ph @r	l i:
per-	lis
ph @r	l I s
per-	lite
ph @r	l aI t
per-	ma-	nence
ph @r	m V	n V n s
per-	ma-	nent
ph @r	m V	n V n t
per-	ma-	nent-	ly
ph @r	m V	n V n	t l i:
per-	me-	a-	bi-	li-	ty
ph @r	m i:	V	b I	l V	t i:
per-	me-	a-	ble
ph @r	m i:	V	b V l
per-	me-	a-	ted
ph @r	m i:	eI	t V d
per-	me-	a-	ting
ph @r	m i:	eI	t I N
per-	me-	ate
ph @r	m i:	eI t
per-	me-	ates
ph @r	m i:	eI t s
per-	mi-	an
ph @r	m i:	V n
per-	mis-	si-	ble
ph @r	m I	s I	b V l
per-	mis-	sion
ph @r	m I	S V n
per-	mis-	sions
ph @r	m I	S V n z
per-	mis-	sive
ph @r	m I	s I v
per-	mis-	sive-	ness
ph @r	m I	s I v	n V s
per-	mit
ph @r	m I t
per-	mit-	ted
ph @r	m I	t V d
per-	mit-	ting
ph @r	m I	t I N
per-	mits
ph @r	m I t s
per-	mu-	ta-	tion
ph @r m	j u:	t eI	S V n
per-	mu-	ta-	tions
ph @r m	j u:	t eI	S V n z
per-	mute
ph @r m	j u: t
per-	nell
ph @r	n V l
per-	ni-	cious
ph @r	n I	S V s
per-	nod
ph e@	n @U
per-	nod's
ph @r	n Q d z
per-	pe-	tu-	a-	ted
ph @r	p e	tS V	w eI	t V d
per-	pe-	tu-	a-	ting
ph @r	p e	tS V	w eI	t I N
per-	pe-	tu-	a-	tion
ph @r	p e	tS V	w eI	S V n
per-	pe-	tu-	al
ph @r	p e	tS u:	V l
per-	pe-	tu-	al-	ly
ph @r	p e	tS u:	V	l i:
per-	pe-	tu-	als
ph @r	p e	tS u:	V l z
per-	pe-	tu-	ate
ph @r	p e	tS V	w eI t
per-	pe-	tu-	ates
ph @r	p e	tS V	w eI t s
per-	pe-	tu-	i-	ty
ph @r	p V t	j u:	V	t i:
per-	pen-	di-	cu-	lar
ph @r	p V n	d I k	j V	l @r
per-	pet-	ra-	ted
ph @r	p V t	r eI	t V d
per-	pet-	ra-	ting
ph @r	p V t	r eI	t I N
per-	pet-	ra-	tor
ph @r	p V t	r eI	t @r
per-	pet-	ra-	tors
ph @r	p V t	r eI	t @r z
per-	pet-	ra-	tor's
ph @r	p V t	r eI	t @r z
per-	pet-	rate
ph @r	p V t	r eI t
per-	ple-	xes
ph @r p	l e k	s V z
per-	ple-	xi-	ty
ph @r p	l e k	s I	t i:
per-	ple-	xing
ph @r p	l e k	s I N
per-	plex
ph @r p	l e k s
per-	plexed
ph @r p	l e k s t
per-	qui-	site
ph @r k	w I	z I t
per-	qui-	sites
ph @r k	w I	z I t s
per-	rault
ph e@	O: l t
per-	reault
ph @r	r @U
per-	ren
ph @r	r V n
per-	ret
ph @r	r e t
per-	ret-	ta
ph @r	r e	t V
per-	ri
ph @r	r i:
per-	ri-	er
ph e@	i:	@r
per-	ri-	ne
ph @r	r i:	n i:
per-	rin
ph e@	I n
per-	rins
ph e@	I n z
per-	ron
ph e@	V n
per-	ry
ph e@	i:
per-	ry-	man
ph @r	r i:	m V n
per-	ry's
ph e@	i: z
per-	se
ph @r	s eI
per-	se-	cu-	ted
ph @r	s V k	j u:	t V d
per-	se-	cu-	ting
ph @r	s I k	j u:	t I N
per-	se-	cu-	tion
ph @r	s V k	j u:	S V n
per-	se-	cu-	tions
ph @r	s V k	j u:	S V n s
per-	se-	cu-	tor
ph @r	s V k	j u:	t @r
per-	se-	cu-	tors
ph @r	s V k	j u:	t @r z
per-	se-	cute
ph @r	s V k	j u: t
per-	se-	po-	lis
ph @r	s e	p V	l V s
per-	se-	us
ph @r	s i:	V s
per-	se-	ve-	rance
ph @r	s V	v I@	V n s
per-	se-	vere
ph @r	s V	v I@
per-	se-	vered
ph @r	s V	v I@ d
per-	ses
ph @r	s V z
per-	shing
ph @r	S I N
per-	shing's
ph @r	S I N z
per-	si-	co
ph @r	s i:	k @U
per-	sia
ph @r	Z V
per-	sian
ph @r	Z V n
per-	sians
ph @r	Z V n z
per-	sing
ph @r	s I N
per-	sis
ph @r	s I s
per-	sis-	ted
ph @r	s I s	t V d
per-	sis-	tence
ph @r	s I s	t V n s
per-	sis-	tent
ph @r	s I s	t V n t
per-	sis-	tent-	ly
ph @r	s I s	t V n	t l i:
per-	sis-	ting
ph @r	s I s	t I N
per-	sist
ph @r	s I s t
per-	sists
ph @r	s I s t s
per-	so-	na
ph @r	s @U	n V
per-	so-	na-	ble
ph @r	s V	n V	b V l
per-	so-	na-	li-	ties
ph @r	s V	n {	l V	t i: z
per-	so-	na-	li-	ty
ph @r	s V	n {	l V	t i:
per-	so-	na-	li-	za-	tion
ph @r	s V	n V	l V	z eI	S V n
per-	so-	na-	li-	zes
ph @r	s V	n V	l aI	z V z
per-	so-	na-	li-	zing
ph @r	s V	n V	l aI	z I N
per-	so-	na-	lize
ph @r	s V	n V	l aI z
per-	so-	na-	lized
ph @r	s V	n V	l aI z d
per-	so-	nab-	ly
ph @r	s V	n V b	l i:
per-	so-	nae
ph @r	s @U	n eI
per-	so-	nal
ph @r	s V	n V l
per-	so-	nal-	ly
ph @r	s V	n V	l i:
per-	so-	nals
ph @r	s V	n V l z
per-	so-	ni-	fi-	ca-	tion
ph @r	s Q	n I	f I	k eI	S V n
per-	so-	ni-	fied
ph @r	s Q	n I	f aI d
per-	so-	ni-	fies
ph @r	s Q	n I	f aI z
per-	so-	ni-	fy
ph @r	s Q	n I	f aI
per-	son
ph @r	s V n
per-	son-	nel
ph @r	s V	n e l
per-	sons
ph @r	s V n z
per-	son's
ph @r	s V n z
per-	spec-	tive
ph @r s	p e k	t I v
per-	spec-	tives
ph @r s	p e k	t I v z
per-	spi-	ra-	tion
ph @r s	p @r	eI	S V n
per-	sua-	da-	ble
ph @r s	w eI	d V	b V l
per-	sua-	ded
ph @r s	w eI	d V d
per-	sua-	ding
ph @r s	w eI	d I N
per-	sua-	sion
ph @r s	w eI	Z V n
per-	sua-	sions
ph @r s	w eI	Z V n z
per-	sua-	sive
ph @r s	w eI	s I v
per-	sua-	sive-	ly
ph @r s	w eI	s I v	l i:
per-	sua-	sive-	ness
ph @r s	w eI	s I v	n V s
per-	suade
ph @r s	w eI d
per-	suades
ph @r s	w eI d z
per-	tai-	ning
ph @r	t eI	n I N
per-	tain
ph @r	t eI n
per-	tained
ph @r	t eI n d
per-	tains
ph @r	t eI n z
per-	ti-	nent
ph @r	t I	n e n t
per-	tur-	ba-	tion
ph @r	t @r	b eI	S V n
per-	tur-	ba-	tions
ph @r	t @r	b eI	S V n z
per-	turb
ph @r	t @r b
per-	turbed
ph @r	t @r b d
per-	turbs
ph @r	t @r b z
per-	tus-	sis
ph @r	t V	s I s
per-	u-	sing
ph @r	u:	z I N
per-	u-	vi-	an
ph @r	u:	v i:	V n
per-	u-	vi-	ans
ph @r	u:	v i:	V n z
per-	us-	se
ph @r	u:	s i:
per-	use
ph @r	u: z
per-	used
ph @r	u: z d
per-	uz-	zi
ph @r	u: t	s i:
per-	va-	ded
ph @r	v eI	d V d
per-	va-	ding
ph @r	v eI	d I N
per-	va-	sive
ph @r	v eI	s I v
per-	va-	sive-	ness
ph @r	v eI	s I v	n V s
per-	vade
ph @r	v eI d
per-	vades
ph @r	v eI d z
per-	ver-	si-	ty
ph @r	v @r	s I	t i:
per-	ver-	sion
ph @r	v @r	Z V n
per-	ver-	ted
ph @r	v @r	t V d
per-	ver-	ting
ph @r	v @r	t I N
per-	verse
ph @r	v @r s
per-	verse-	ly
ph @r	v @r s	l i:
per-	vert
ph @r	v @r t
per-	verts
ph @r	v @r t s
perc
ph @r k
perce
ph @r s
perch
ph @r tS
perch-	lo-	rate
ph @r k	l O@	eI t
perch-	lo-	ric
ph @r k	l O@	I k
perched
ph @r tS t
pere
ph @r
perk
ph @r k
perked
ph @r k t
perks
ph @r k s
perl
ph @r l
perl-	man
ph @r l	m V n
perle
ph @r l
perls
ph @r l z
pers
ph @r s
pers-	pi-	ring
ph @r s	p aI	r I N
pers-	pire
ph @r s	p aI r
pers-	son
ph @r	s V n
pert
ph @r t
perth
ph @r T
pes-	si-	mi-	sm
ph e	s I	m I	z V m
pes-	si-	mis-	tic
ph e	s I	m I s	t I k
pes-	si-	mist
ph e	s I	m V s t
pes-	si-	mists
ph e	s I	m I s t s
pes-	ta-	na
ph e s	t {	n V
pes-	te-	ring
ph e s	t @r	I N
pes-	ter
ph e s	t @r
pes-	tered
ph e s	t @r d
pes-	ti-	cide
ph e s	t I	s aI d
pes-	ti-	cides
ph e s	t I	s aI d z
pes-	ti-	lence
ph e s	t I	l V n s
pest
ph e s t
pests
ph e s t s
pet
ph e t
pet-	ra
ph e t	r V
pet-	rac-	ca
ph e t	r Q	k V
pet-	rar-	ca
ph e t	r Q@	k V
pet-	ras
ph e t	r V z
pet-	re-	a
ph e t	r i:	V
pet-	rels
ph e t	r V l z
pet-	rey
ph e t	r i:
pet-	ri
ph e t	r i:
pet-	ri-	fied
ph e t	r I	f aI d
pet-	ri-	fy
ph e t	r I	f aI
pet-	ri-	na
ph e t	r i:	n V
pet-	rick
ph e t	r I k
pet-	rie
ph e t	r i:
pet-	rie's
ph e t	r i: z
pet-	ril-	lo
ph e t	r I	l @U
pet-	ro
ph e t	r @U
pet-	ro-	che-	mi-	cal
ph e t	r @U	k e	m I	k V l
pet-	ro-	che-	mi-	cals
ph e t	r @U	k e	m I	k V l z
pet-	ro-	dol-	lar
ph e t	r @U	d Q	l @r
pet-	ro-	dol-	lars
ph e t	r @U	d Q	l @r z
pet-	ro-	le-	um
ph V t	r @U	l i:	V m
pet-	ro-	le-	um's
ph V t	r @U	l i:	V m z
pet-	ro-	li-	a
ph V t	r @U	l i:	V
pet-	ro-	lo-	gy
ph V t	r Q	l V	dZ i:
pet-	ro-	nel-	la
ph e t	r @U	n e	l V
pet-	ro-	ni-	a
ph e t	r @U	n i:	V
pet-	ro-	nil-	la
ph e t	r V	n I	l V
pet-	ro-	sa
ph e t	r @U	z V
pet-	ro-	vich
ph e t	r V	v I tS
pet-	rol
ph e t	r @U l
pet-	ros
ph e t	r @U z
pet-	ta
ph e	t V
pet-	ted
ph e	t V d
pet-	ter
ph e	t @r
pet-	ti
ph e	t i:
pet-	ti-	coat
ph e	t i:	k @U t
pet-	ti-	coats
ph e	t i:	k @U t s
pet-	ti-	grew
ph e	t I g	r u:
pet-	ti-	ness
ph e	t i:	n V s
pet-	ties
ph e	t i: z
pet-	ting
ph e	t I N
pet-	tis
ph e	t I s
pet-	tit
ph e	t I t
pet-	tus
ph e	t V s
pet-	ty
ph e	t i:
pete
ph i: t
pete's
ph i: t s
pets
ph e t s
pet's
ph e t s
peu-	geot
ph j u:	Z @U
pew
ph j u:
pew-	ter
ph j u:	t @r
pews
ph j u: z
pey-	ton
ph eI	t V n
pfaff
f { f
pfef-	fer
f e	f @r
pfei-	fer
f aI	f @r
pfen-	nig
f e	n I g
pfen-	nigs
f e	n I g z
pfen-	ning
f e	n I N
pfi-	ster
f I s	t @r
pfi-	zer
f aI	z @r
pfi-	zer's
f aI	z @r z
pfund
f V n d
pha-	go-	cyte
f {	g V	s aI t
pha-	go-	cytes
f {	g V	s aI t s
pha-	lanx
f eI	l { N k s
pha-	ra-	o-	nic
f e@	V	Q	n I k
pha-	raoh
f e@	@U
pha-	raohs
f e@	@U z
pha-	ri-	sa-	i-	sm
f {	r I	s eI	I	z V m
pha-	ro
f Q@	@U
pha-	roah
f eI	r @U
pha-	ros
f e@	@U z
pha-	rynx
f e@	I N k s
pha-	seout
f eI	z aU t
pha-	ses
f eI	z V z
pha-	sing
f eI	z I N
phal-	lic
f {	l I k
phan-	ta-	sm
f { n	t {	z V m
phan-	tas-	ma-	go-	ri-	a
f { n	t { z	m V	g O@	i:	V
phan-	tom
f { n	t V m
phan-	toms
f { n	t V m z
phar
f Q@
phar-	ma-	ceu-	ti-	cal
f Q@	m V	s u:	t I	k V l
phar-	ma-	ceu-	ti-	cals
f Q@	m V	s u:	t I	k V l z
phar-	ma-	cies
f Q@	m V	s i: z
phar-	ma-	cist
f Q@	m V	s V s t
phar-	ma-	cists
f Q@	m V	s V s t s
phar-	ma-	co-	lo-	gi-	cal
f Q@	m V	k V	l Q	dZ I	k V l
phar-	ma-	co-	lo-	gist
f Q@	m V	k Q	l V	dZ I s t
phar-	ma-	co-	lo-	gy
f Q@	m V	k Q	l V	dZ i:
phar-	ma-	cy
f Q@	m V	s i:
phares
f e@ z
pharr
f Q@
phase
f eI z
phased
f eI z d
phe-	be
f i:	b i:
phe-	dra
f e d	r V
phe-	lan
f e	l V n
phe-	nix
f e	n I k s
phe-	no-	lic
f V	n Q	l I k
phe-	no-	me-	na
f V	n Q	m V	n V
phe-	no-	me-	nal
f V	n Q	m V	n V l
phe-	no-	me-	nal-	ly
f V	n Q	m V	n V	l i:
phe-	no-	me-	non
f V	n Q	m V	n Q n
phe-	no-	ty-	pic
f i:	n V	t I	p I k
phe-	no-	type
f i:	n V	t aI p
phe-	no-	types
f i:	n V	t aI p s
phe-	nol
f i:	n Q l
phe-	nolph-	tha-	lein
f i:	n Q l	f T eI	l V n
phe-	nom
f e	n V m
phe-	ro-	mone
f e@	V	m @U n
phe-	ro-	mones
f e@	V	m @U n z
phea-	sant
f e	z V n t
phea-	sants
f e	z V n t s
phelp-	s's
f e l	p s V z
phelps
f e l p s
phew
f j u:
phi
f aI
phi-	la-	del-	phi-	a
f I	l V	d e l	f i:	V
phi-	la-	del-	phi-	an
f I	l V	d e l	f i:	V n
phi-	la-	del-	phi-	ans
f I	l V	d e l	f i:	V n z
phi-	la-	del-	phi-	a's
f I	l V	d e l	f i:	V z
phi-	la-	na
f V	l {	n V
phi-	lan-	de-	ring
f aI	l { n	d @r	I N
phi-	lanth-	ro-	pic
f I	l V n	T r Q	p I k
phi-	lanth-	ro-	pies
f V	l { n	T r V	p i: z
phi-	lanth-	ro-	pist
f V	l { n	T r V	p V s t
phi-	lanth-	ro-	pists
f V	l { n	T r V	p V s t s
phi-	lanth-	ro-	py
f V	l { n	T r V	p i:
phi-	li-	bert
f I	l I	b @r t
phi-	li-	na
f V	l i:	n V
phi-	lip
f I	l I p
phi-	lip-	pa
f I	l I	p V
phi-	lip-	pe
f I	l i:	p eI
phi-	lip-	pi
f I	l I	p i:
phi-	lip-	pic
f I	l I	p I k
phi-	lip-	pine
f I	l I s	t i: n
phi-	lipp
f I	l I p
phi-	lip's
f I	l I p s
phi-	lis-	tines
f I	l I s	t i: n z
phi-	llipp
f I	l I p
phi-	llippe
f I	l I p
phi-	lo
f i:	l @U
phi-	lo-	dend-	ron
f I	l V	d e n	d r V n
phi-	lo-	me-	la
f I	l V	m i:	l V
phi-	lo-	me-	na
f I	l V	m i:	n V
phi-	lo-	so-	pher
f V	l Q	s V	f @r
phi-	lo-	so-	phers
f V	l Q	s V	f @r z
phi-	lo-	so-	phi-	cal
f I	l V	s Q	f I	k V l
phi-	lo-	so-	phi-	cal-	ly
f I	l V	s Q	f I	k V	l i:
phi-	lo-	so-	phic
f I	l V	s Q	f I k
phi-	lo-	so-	phies
f V	l Q	s V	f i: z
phi-	lo-	so-	phy
f V	l Q	s V	f i:
phi-	ne-	as
f I	n i:	V s
phil
f I l
phil-	bert
f I l	b @r t
phil-	bin
f I l	b I n
phil-	brook
f I l	b r U k
phil-	by
f I l	b i:
phil-	har-	mo-	nic
f I l	h Q@	m Q	n I k
phil-	lie
f I	l i:
phil-	lies
f I	l i: z
phil-	lip
f I	l I p
phil-	lip-	pi
f V	l i:	p i:
phil-	lipe
f V	l i: p
phil-	lips
f I	l I p s
phil-	lip's
f I	l I p s
phil-	lis
f I	l I s
phil-	ly
f I	l i:
phil-	pot
f I l	p V t
phil's
f I l z
phip-	pen
f I	p V n
phipps
f I p s
phle-	bi-	tis
f l V	b aI	t I s
phlo-	go-	pite
f l Q	g V	p aI t
phnom
f n Q m
pho-	bi-	a
f @U	b i:	V
pho-	bi-	as
f @U	b i:	V z
pho-	bic
f @U	b I k
pho-	bos
f @U	b @U s
pho-	ne-	tic
f V	n e	t I k
pho-	ne-	tical-	ly
f V	n e	t I k	l i:
pho-	ne-	tics
f V	n e	t I k s
pho-	ney
f @U	n i:
pho-	nic
f Q	n I k
pho-	nics
f Q	n I k s
pho-	ning
f @U	n I N
pho-	no-	graph
f @U	n V g	r { f
pho-	ny
f @U	n i:
pho-	to
f @U	t @U
pho-	to-	che-	mi-	cal
f @U	t @U	k e	m I	k V l
pho-	to-	co-	pi-	er
f @U	t @U	k Q	p i:	@r
pho-	to-	co-	pi-	ers
f @U	t @U	k Q	p i:	@r z
pho-	to-	co-	pied
f @U	t @U	k Q	p i: d
pho-	to-	co-	pies
f @U	t @U	k Q	p i: z
pho-	to-	co-	py
f @U	t @U	k Q	p i:
pho-	to-	co-	py-	ing
f @U	t @U	k Q	p i:	I N
pho-	to-	con-	duc-	tive
f @U	t @U	k V n	d V k	t I v
pho-	to-	dy-	na-	mic
f @U	t @U	d aI	n {	m I k
pho-	to-	e-	lect-	ric
f @U	t @U	V	l e k	t r I k
pho-	to-	fi-	ni-	sher
f @U	t @U	f I	n I	S @r
pho-	to-	fi-	ni-	shers
f @U	t @U	f I	n I	S @r z
pho-	to-	fi-	ni-	shing
f @U	t @U	f I	n I	S I N
pho-	to-	ge-	nic
f @U	t V	dZ e	n I k
pho-	to-	gra-	pher
f V	t Q g	r V	f @r
pho-	to-	gra-	phers
f V	t Q g	r V	f @r z
pho-	to-	gra-	pher's
f V	t Q g	r V	f @r z
pho-	to-	gra-	phic
f @U	t V g	r {	f I k
pho-	to-	gra-	phing
f @U	t V g	r {	f I N
pho-	to-	gra-	phy
f V	t Q g	r V	f i:
pho-	to-	graph
f @U	t V g	r { f
pho-	to-	graphed
f @U	t V g	r { f t
pho-	to-	graphs
f @U	t V g	r { f s
pho-	to-	jour-	na-	list
f @U	t @U	dZ @r	n V	l V s t
pho-	to-	me-	ter
f V	t Q	m V	t @r
pho-	to-	pho-	re-	sis
f @U	t @U	f @r	i:	s I s
pho-	to-	ref-	rac-	tive
f @U	t @U	r V f	r { k	t I v
pho-	to-	syn-	the-	sis
f @U	t @U	s I n	T V	s V s
pho-	to-	ta-	xis
f @U	t V	t { k	s V s
pho-	to-	vol-	ta-	ic
f @U	t V	v @U l	t eI	I k
pho-	to-	vol-	ta-	ics
f @U	t @U	v @U l	t eI	I k s
pho-	ton
f @U	t Q n
pho-	tons
f @U	t Q n z
pho-	tos
f @U	t @U z
pho-	to's
f @U	t @U z
phoe-	be
f i:	b i:
phoe-	bus
f i:	b V s
phoe-	ni-	cia
f V	n i:	S V
phoe-	ni-	cian
f V	n i:	S V n
phoe-	ni-	cians
f V	n i:	S V n z
phoe-	ni-	x's
f i:	n I k	s V z
phoe-	nix
f i:	n I k s
phone
f @U n
phoned
f @U n d
phones
f @U n z
phone's
f @U n z
phos-	pha-	tic
f Q s	f {	t I k
phos-	phate
f Q s	f eI t
phos-	phates
f Q s	f eI t s
phos-	pho-	re-	scence
f Q s	f @r	e	s V n s
phos-	pho-	ric
f Q s	f @r	I k
phos-	pho-	rite
f Q s	f @r	aI t
phos-	pho-	rites
f Q s	f @r	aI t s
phos-	pho-	rous
f Q s	f @r	V s
phos-	pho-	rus
f Q s	f @r	V s
phos-	phor
f Q s	f O@
phos-	phors
f Q s	f O@ z
phot-	ro-	nic
f @U t	r Q	n I k
phra-	se-	o-	lo-	gy
f r eI	z i:	O:	l O:	dZ i:
phra-	ses
f r eI	z V z
phra-	sing
f r eI	z I N
phrase
f r eI z
phrased
f r eI z d
phry-	gi-	an
f r I	dZ i:	V n
phu
f u:
phut
f V t
phy-	la
f aI	l V
phy-	lis
f aI	l V s
phy-	lo-	ge-	ny
f aI	l Q	dZ V	n i:
phy-	lum
f aI	l V m
phy-	si-	cal
f I	z I	k V l
phy-	si-	cal-	ly
f I	z I	k V	l i:
phy-	si-	cals
f I	z I	k V l z
phy-	si-	cian
f V	z I	S V n
phy-	si-	cians
f V	z I	S V n z
phy-	si-	cian's
f V	z I	S V n z
phy-	si-	cist
f I	z I	s I s t
phy-	si-	cists
f I	z I	s I s t s
phy-	si-	o
f I	z i:	@U
phy-	si-	o-	lo-	gi-	cal
f I	z i:	V	l Q	dZ I	k V l
)"
R"(phy-	si-	o-	lo-	gical-	ly
f I	z i:	V	l Q	dZ I k	l i:
phy-	si-	o-	lo-	gist
f I	z i:	Q	l V	dZ V s t
phy-	si-	o-	lo-	gy
f I	z i:	Q	l V	dZ i:
phy-	sics
f I	z I k s
phy-	sique
f V	z i: k
phy-	to-	ge-	o-	gra-	phy
f aI	t @U	dZ i:	Q g	r V	f i:
phy-	to-	plank-	ton
f aI	t @U p	l { N	t V n
phyl-	lis
f I	l I s
phyl-	lys
f I	l i: z
phyle
f aI l
pi
ph aI
pi-	a
ph i:	V
pi-	a-	get
ph i:	V	Z eI
pi-	a-	nist
ph i:	{	n I s t
pi-	a-	nists
ph i:	{	n I s t s
pi-	a-	nist's
ph i:	{	n I s t s
pi-	a-	no
ph i:	{	n @U
pi-	a-	nos
ph i:	{	n @U z
pi-	a-	no's
ph i:	{	n @U z
pi-	an-	ka
ph i:	Q N	k V
pi-	az-	za
ph i:	{	z V
pi-	ca
ph aI	k V
pi-	ca-	ro
ph i:	k Q@	@U
pi-	ca-	yune
ph I	k i:	j u: n
pi-	can-	te
ph i:	k Q n	t eI
pi-	card
ph I	k Q@ d
pi-	cas
ph aI	k V z
pi-	cas-	so
ph I	k Q	s @U
pi-	cas-	so's
ph I	k Q	s @U z
pi-	cher
ph I	tS @r
pi-	co
ph i:	k @U
pi-	con
ph I	k V n
pi-	e-	ties
ph aI	V	t i: z
pi-	e-	ty
ph aI	V	t i:
pi-	et
ph aI	V t
pi-	et-	ro
ph i:	e t	r @U
pi-	geon
ph I	dZ V n
pi-	geon-	hole
ph I	dZ V n	h @U l
pi-	geon-	holed
ph I	dZ V n	h @U l d
pi-	geons
ph I	dZ V n z
pi-	geon's
ph I	dZ V n z
pi-	ker
ph aI	k @r
pi-	kul
ph I	k V l
pi-	la-	tus
ph i:	l eI	t V s
pi-	lar
ph aI	l @r
pi-	las-	ter
ph V	l { s	t @r
pi-	las-	ters
ph V	l { s	t @r z
pi-	leup
ph aI	l V p
pi-	ling
ph aI	l I N
pi-	lings
ph aI	l I N z
pi-	lo-	ted
ph aI	l V	t V d
pi-	lo-	ting
ph aI	l V	t I N
pi-	lon
ph i:	l O: n
pi-	lot
ph aI	l V t
pi-	lot-	less
ph aI	l V t	l V s
pi-	lots
ph aI	l V t s
pi-	lot's
ph aI	l V t s
pi-	ma
ph i:	m V
pi-	me-	son
ph aI	m eI	z Q n
pi-	men-	tel
ph I	m V n	t V l
pi-	na
ph i:	n V
pi-	na-	tu-	bo
ph I	n V	t u:	b @U
pi-	nard
ph I	n @r d
pi-	ne-	al
ph aI	n i:	V l
pi-	ne-	da
ph i:	n e	d V
pi-	ne-	ro
ph I	n e@	@U
pi-	neap-	ple
ph aI	n {	p V l
pi-	neap-	ples
ph aI	n {	p V l z
pi-	nel-	li
ph I	n e	l i:
pi-	ner
ph aI	n @r
pi-	net-	ta
ph V	n e	t V
pi-	net-	ta's
ph V	n e	t V z
pi-	nette
ph I	n e t
pi-	ni
ph i:	n i:
pi-	ning
ph aI	n I N
pi-	nion
ph I n	j V n
pi-	no
ph i:	n @U
pi-	no-	chet
ph I	n I	S eI
pi-	no-	chet's
ph I	n I	S eI z
pi-	no-	la
ph V	n @U	l V
pi-	noc-	chi-	o
ph V	n @U	k i:	@U
pi-	not
ph I	n V t
pi-	ny
ph aI	n i:
pi-	o
ph aI	@U
pi-	o-	nee-	ring
ph aI	V	n I@	I N
pi-	o-	neer
ph aI	V	n I@
pi-	o-	neered
ph aI	V	n I@ d
pi-	o-	neers
ph aI	V	n I@ z
pi-	o-	neer's
ph aI	V	n I@ z
pi-	on
ph aI	Q n
pi-	ous
ph aI	V s
pi-	ous-	ly
ph aI	V s	l i:
pi-	per
ph aI	p @r
pi-	quant
ph i:	k V n t
pi-	quette
ph I	k e t
pi-	ra-	cy
ph aI	r V	s i:
pi-	ra-	ted
ph aI	r V	t V d
pi-	ra-	ting
ph aI	r V	t I N
pi-	ran-	del-	lo
ph I@	V n	d e	l @U
pi-	ran-	ha
ph I@	{ n	h V
pi-	rate
ph aI	r V t
pi-	rates
ph aI	r V t s
pi-	rate's
ph aI	r V t s
pi-	ro
ph I@	@U
pi-	rog
ph @r	Q g
pi-	rou-	ette
ph I@	u:	e t
pi-	rou-	ettes
ph I@	u:	e t s
pi-	sa
ph i:	s V
pi-	sa-	no
ph i:	s Q	n @U
pi-	ta
ph i:	t V
pi-	thy
ph I	T i:
pi-	ti-	a-	ble
ph I	t i:	V	b V l
pi-	ti-	ful
ph I	t I	f V l
pi-	ti-	ful-	ly
ph I	t I	f V	l i:
pi-	ti-	less
ph I	t i:	l V s
pi-	tied
ph I	t i: d
pi-	tu-	i-	ta-	ry
ph V	t u:	V	t e@	i:
pi-	ty
ph I	t i:
pi-	ty-	ing
ph I	t i:	I N
pi-	us
ph aI	V s
pi-	vo-	tal
ph I	v V	t V l
pi-	vo-	ted
ph I	v V	t V d
pi-	vot
ph I	v V t
pi-	xel
ph I k	s V l
pi-	xels
ph I k	s V l z
pi-	xie
ph I k	s i:
pi-	zar-	ro
ph V	z Q@	@U
pi-	zazz
ph V	z { z
pic
ph I k
pic-	ca-	dil-	ly
ph I	k V	d I	l i:
pic-	co
ph I	k @U
pic-	co-	lo
ph I	k V	l @U
pic-	k-	ler
ph I	k V	l @r
pic-	kar
ph I	k Q@
pic-	kard
ph I	k Q@ d
pic-	ke-	rel
ph I	k @r	V l
pic-	ke-	ring
ph I	k @r	I N
pic-	ke-	ted
ph I	k V	t V d
pic-	ke-	ter
ph I	k V	t @r
pic-	ke-	ters
ph I	k V	t @r z
pic-	ke-	ting
ph I	k V	t I N
pic-	kel
ph I	k V l
pic-	ken-	s's
ph I	k V n	z V z
pic-	kens
ph I	k V n z
pic-	ker
ph I	k @r
pic-	kers
ph I	k @r z
pic-	ket
ph I	k V t
pic-	kets
ph I	k V t s
pic-	kett
ph I	k e t
pic-	kett's
ph I	k e t s
pic-	ki-	er
ph I	k i:	@r
pic-	king
ph I	k I N
pic-	kings
ph I	k I N z
pic-	kle
ph I	k V l
pic-	kled
ph I	k V l d
pic-	kles
ph I	k V l z
pic-	kup
ph I	k V p
pic-	kups
ph I	k V p s
pic-	ky
ph I	k i:
pic-	nic
ph I k	n I k
pic-	nics
ph I k	n I k s
pic-	tet
ph I k	t e t
pic-	to-	ri-	al
ph I k	t O@	i:	V l
pic-	tu-	resque
ph I k	tS @r	e s k
pic-	tu-	ring
ph I k	tS @r	I N
pic-	ture
ph I k	tS @r
pic-	tured
ph I k	tS @r d
pic-	tures
ph I k	tS @r z
pic-	ture's
ph I k	tS @r z
pick
ph I k
pick-	ford
ph I k	f @r d
pick-	ling
ph I k	l I N
pick-	ney
ph I k	n i:
pick-	poc-	ket
ph I k	p Q	k V t
pick-	poc-	kets
ph I k	p Q	k V t s
pick-	rell
ph I k	r V l
pick-	up
ph I	k V p
pick-	wick
ph I k	w I k
picked
ph I k t
picks
ph I k s
picts
ph I k t s
pid-	d-	ling
ph I	d V	l I N
pid-	dle
ph I	d V l
pid-	dles
ph I	d V l z
pid-	dock
ph I	d V k
pid-	geon
ph I d	dZ I n
pie
ph aI
pie-	bald
ph aI	b O: l d
pie-	ces
ph i:	s V z
pie-	cing
ph i:	s I N
pie-	rette
ph I@	e t
pie-	ro
ph i:	r @U
pie-	ter
ph i:	t @r
pie-	ter-	ma-	ritz-	burg
ph i:	t @r	m e@	I t	s b @r g
pie-	ti-	sm
ph i:	t I	z V m
piece
ph i: s
piece-	meal
ph i: s	m i: l
piece-	work
ph i: s	w @r k
pieced
ph i: s t
pied
ph aI d
pied-	mont
ph i: d	m Q n t
pied-	mont's
ph i: d	m Q n t s
pied-	ra
ph i: d	r V
pier
ph I@
pier-	ce's
ph I@	s V z
pier-	cing
ph I@	s I N
pier-	cy
ph I@	k i:
pier-	pont
ph I@	p Q n t
pier-	re
ph i:	e@
pier-	re-	pont
ph I@	eI	p @U n t
pier-	re's
ph i:	e@ z
pier-	ro
ph I@	@U
pier-	ron
ph I@	O: n
pier-	son
ph I@	s V n
pierce
ph I@ s
pierced
ph I@ s t
piers
ph I@ z
pies
ph aI z
pig
ph I g
pig-	gott
ph I	g V t
pig-	gy
ph I	g i:
pig-	gy-	bac-	king
ph I	g i:	b {	k I N
pig-	gy-	back
ph I	g i:	b { k
pig-	gy-	backed
ph I	g i:	b { k t
pig-	let
ph I g	l V t
pig-	lets
ph I g	l V t s
pig-	man
ph I g	m V n
pig-	men-	ta-	tion
ph I g	m V n	t eI	S V n
pig-	ment
ph I g	m V n t
pig-	ments
ph I g	m V n t s
pig-	my
ph I g	m i:
pig-	skin
ph I g	s k I n
pigg
ph I g
pigs
ph I g z
pig's
ph I g z
pik
ph I k
pike
ph aI k
pikes
ph aI k s
pil
ph I l
pil-	cher
ph I l	tS @r
pil-	fe-	rage
ph I l	f @r	I dZ
pil-	fe-	ring
ph I l	f @r	I N
pil-	ger
ph I l	g @r
pil-	gri-	ma-	ges
ph I l	g r I	m I	dZ V z
pil-	gri-	mage
ph I l	g r I	m I dZ
pil-	grim
ph I l	g r I m
pil-	grims
ph I l	g r I m z
pil-	grim's
ph I l	g r I m z
pil-	king-	ton
ph I l	k I N	t V n
pil-	la-	ger
ph I	l I	dZ @r
pil-	la-	gers
ph I	l I	dZ @r z
pil-	la-	ger's
ph I	l I	dZ @r z
pil-	la-	ges
ph I	l I	dZ V z
pil-	la-	ging
ph I	l I	dZ I N
pil-	lage
ph I	l I dZ
pil-	laged
ph I	l I dZ d
pil-	lar
ph I	l @r
pil-	lared
ph I	l @r d
pil-	lars
ph I	l @r z
pil-	ler
ph I	l @r
pil-	ling
ph I	l I N
pil-	lion
ph I l	j V n
pil-	lo-	ried
ph I	l @r	i: d
pil-	lo-	ry
ph I	l @r	i:
pil-	low
ph I	l @U
pil-	lows
ph I	l @U z
pilch
ph I l tS
pile
ph aI l
pile-	up
ph aI	l V p
piled
ph aI l d
piles
ph aI l z
pill
ph I l
pills
ph I l z
pill's
ph I l z
pills-	bu-	ry
ph I l	z b e@	i:
pills-	bu-	ry's
ph I l	z b e@	i: z
pilt-	down
ph I l	t d aU n
pim-	ping
ph I m	p I N
pim-	ple
ph I m	p V l
pim-	ples
ph I m	p V l z
pimp
ph I m p
pimps
ph I m p s
pin
ph I n
pin-	ball
ph I n	b O: l
pin-	cer-	like
ph I n	s @r	l aI k
pin-	cers
ph I n	s @r z
pin-	cher
ph I n	tS @r
pin-	chers
ph I n	tS @r z
pin-	ching
ph I n	tS I N
pin-	cus
ph I N	k V s
pin-	da-	ric
ph I n	d {	r I k
pin-	der
ph aI n	d @r
pin-	gree
ph I N	g r i:
pin-	hole
ph I n	h @U l
pin-	holes
ph I n	h @U l z
pin-	ker
ph I N	k @r
pin-	ker-	ton
ph I N	k @r	t V n
pin-	ker-	ton's
ph I N	k @r	t V n z
pin-	kest
ph I N	k I s t
pin-	kie
ph I N	k i:
pin-	kish
ph I N	k I S
pin-	kos
ph I N	k @U z
pin-	ky
ph I N	k i:
pin-	na-	cle
ph I	n V	k V l
pin-	na-	cle's
ph I	n I	k V l z
pin-	ner
ph I	n @r
pin-	ning
ph I	n I N
pin-	nock
ph I	n V k
pin-	poin-	ted
ph I n	p OI n	t V d
pin-	poin-	ting
ph I n	p OI n	t I N
pin-	point
ph I n	p OI n t
pin-	points
ph I n	p OI n t s
pin-	prick
ph I n	p r I k
pin-	sky
ph I n	s k i:
pin-	son
ph I n	s V n
pin-	stripe
ph I n	s t r aI p
pin-	striped
ph I n	s t r aI p t
pin-	stripes
ph I n	s t r aI p s
pin-	ta
ph I n	t V
pin-	ter
ph aI n	t @r
pin-	to
ph I n	t @U
pin-	zon
ph I n	z O: n
pinc-	kard
ph I N	k @r d
pinch
ph I n tS
pinched
ph I n tS t
pinck-	ney
ph I N	k n i:
pind-	ling
ph I n	d l I N
pine
ph aI n
pines
ph aI n z
ping
ph I N
ping-	pong
ph I N	p O: N
pink
ph I N k
pink-	ham
ph I N	k h V m
pinks
ph I N k s
pinned
ph I n d
pins
ph I n z
pint
ph aI n t
pint-	size
ph aI n	t s aI z
pint-	sized
ph aI n	t s aI z d
pints
ph aI n t s
pip
ph I p
pipe
ph aI p
pipe-	fi-	shes
ph aI p	f I	S V z
pipe-	fish
ph aI p	f I S
pipe-	line
ph aI p	l aI n
pipe-	lines
ph aI p	l aI n z
pipe-	line's
ph aI p	l aI n z
piped
ph aI p t
pips
ph I p s
pique
ph i: k
piqued
ph i: k t
pis-	ca-	ta-	way
ph I s	k {	t V	w eI
pis-	ces
ph aI	s i: z
pis-	ta-	chi-	o
ph V s	t {	S i:	@U
pis-	ta-	chi-	os
ph V s	t {	S i:	@U z
pis-	til
ph I s	t I l
pis-	tol
ph I s	t V l
pis-	tole
ph I s	t @U l
pis-	tols
ph I s	t V l z
pis-	ton
ph I s	t V n
pis-	tons
ph I s	t V n z
piss
ph I s
pissed
ph I s t
pit
ph I t
pit-	cher
ph I	tS @r
pit-	chers
ph I	tS @r z
pit-	ches
ph I	tS V z
pit-	ching
ph I	tS I N
pit-	fall
ph I t	f O: l
pit-	falls
ph I t	f O: l z
pit-	kin
ph I t	k I n
pit-	man
ph I t	m V n
pit-	ney
ph I t	n i:
pit-	tance
ph I	t V n s
pit-	tard
ph I	t @r d
pit-	ted
ph I	t V d
pit-	ting
ph I	t I N
pit-	zer
ph I t	z @r
pitch
ph I tS
pitch-	blende
ph I tS	b l e n d
pitch-	ford
ph I tS	f @r d
pitch-	fork
ph I tS	f O@ k
pitch-	forks
ph I tS	f O@ k s
pitch-	man
ph I tS	m V n
pitch-	men
ph I tS	m e n
pitched
ph I tS t
pith
ph I T
pits
ph I t s
pitt
ph I t
pitt-	man
ph I t	m V n
pitts
ph I t s
pitt's
ph I t s
pitts-	bo-	ro
ph I t	s b @r	@U
pitts-	bur-	gher
ph I t	s b @r	g @r
pitts-	bur-	ghers
ph I t	s b @r	g @r z
pitts-	burg
ph I t	s b @r g
pitts-	burgh
ph I t	s b @r g
pitts-	burgh's
ph I t	s b @r g z
pitts-	field
ph I t	s f i: l d
pitts-	ford
ph I t	s f @r d
pitts-	ton
ph I t	s t V n
pix
ph I k s
pix-	ley
ph I k	s l i:
piz-	za
ph i: t	s V
piz-	zas
ph i: t	s V z
piz-	za's
ph i: t	s V z
piz-	zazz
ph I	z { z
piz-	ze-	ri-	a
ph i: t	s @r	i:	V
piz-	ze-	ri-	as
ph i: t	s @r	i:	V z
pla
ph l Q
pla-	ca-	ting
ph l eI	k eI	t I N
pla-	card
ph l {	k @r d
pla-	cards
ph l {	k @r d z
pla-	cate
ph l eI	k eI t
pla-	ce-	bo
ph l V	s i:	b @U
pla-	ce-	bos
ph l V	s i:	b @U z
pla-	cen-	ta
ph l V	s e n	t V
pla-	cen-	tia
ph l V	s e n	S V
pla-	cer
ph l {	s @r
pla-	ces
ph l eI	s V z
pla-	ce's
ph l eI	s V z
pla-	ci-	da
ph l Q	tS i:	d V
pla-	ci-	do
ph l Q	tS I	d @U
pla-	cid
ph l {	s I d
pla-	cid-	ly
ph l {	s I d	l i:
pla-	cing
ph l eI	s I N
pla-	coid
ph l {	k OI d
pla-	gi-	a-	rize
ph l eI	dZ i:	@r	aI z
pla-	gi-	a-	rized
ph l eI	dZ i:	@r	aI z d
pla-	gi-	o-	clase
ph l eI	dZ i:	V k	l eI s
pla-	gia-	ri-	sm
ph l eI	dZ @r	I	z V m
pla-	guing
ph l eI	g I N
pla-	is-	ted
ph l Q	V s	t I d
pla-	na-	ri-	an
ph l V	n e@	i:	V n
pla-	nar
ph l eI	n @r
pla-	ne-	ta-	ri-	um
ph l {	n V	t e@	i:	V m
pla-	ne-	ta-	ry
ph l {	n V	t e@	i:
pla-	ner
ph l eI	n @r
pla-	ners
ph l eI	n @r z
pla-	net
ph l {	n V t
pla-	nets
ph l {	n V t s
pla-	net's
ph l {	n V t s
pla-	no
ph l eI	n @U
pla-	ta
ph l Q	t V
pla-	teau
ph l {	t @U
pla-	teau-	ing
ph l V	t @U	I N
pla-	teaued
ph l {	t @U d
pla-	ted
ph l eI	t V d
pla-	ten
ph l {	t V n
pla-	ter
ph l eI	t @r
pla-	ting
ph l eI	t I N
pla-	to
ph l eI	t @U
pla-	to-	nic
ph l V	t Q	n I k
pla-	to-	nist
ph l eI	t V	n V s t
pla-	to-	nists
ph l eI	t V	n V s t s
pla-	toon
ph l V	t u: n
pla-	toons
ph l V	t u: n z
pla-	to's
ph l eI	t @U z
pla-	ty
ph l eI	t i:
pla-	ty-	pus
ph l {	t V	p U s
pla-	ya
ph l aI	V
pla-	yer
ph l eI	@r
pla-	yers
ph l eI	@r z
pla-	yer's
ph l eI	@r z
pla-	za
ph l Q	z V
pla-	zas
ph l Q	z V z
pla-	za's
ph l Q	z V z
place
ph l eI s
place-	ment
ph l eI s	m V n t
place-	ments
ph l eI s	m V n t s
placed
ph l eI s t
plack
ph l { k
plack's
ph l { k s
plague
ph l eI g
plagued
ph l eI g d
plagues
ph l eI g z
plai-	ner
ph l eI	n @r
plai-	sance
ph l eI	s V n s
plaid
ph l { d
plain
ph l eI n
plain-	clothes
ph l eI n	k l @U z
plain-	field
ph l eI n	f i: l d
plain-	ly
ph l eI n	l i:
plain-	song
ph l eI n	s O: N
plain-	tiff
ph l eI n	t I f
plain-	tiffs
ph l eI n	t I f s
plain-	tiff's
ph l eI n	t I f s
plain-	tive
ph l eI n	t I v
plain-	tive-	ly
ph l eI n	t aI v	l i:
plain-	view
ph l eI n	v j u:
plaines
ph l eI n z
plains
ph l eI n z
plan
ph l { n
plan-	king
ph l { N	k I N
plan-	ner
ph l {	n @r
plan-	ners
ph l {	n @r z
plan-	ner's
ph l {	n @r z
plan-	ning
ph l {	n I N
plan-	ta-	tion
ph l { n	t eI	S V n
plan-	ta-	tions
ph l { n	t eI	S V n z
plan-	tain
ph l { n	t V n
plan-	tains
ph l { n	t V n z
plan-	ted
ph l { n	t V d
plan-	ter
ph l { n	t @r
plan-	ters
ph l { n	t @r z
plan-	ting
ph l { n	t I N
plan-	tings
ph l { n	t I N z
planck
ph l { N k
plane
ph l eI n
plane-	load
ph l eI n	l @U d
plane-	loads
ph l eI n	l @U d z
planed
ph l eI n d
planes
ph l eI n z
plane's
ph l eI n z
plank
ph l { N k
plank-	to-	nic
ph l { N	k t Q	n I k
plank-	ton
ph l { N	k t V n
planks
ph l { N k s
planned
ph l { n d
plans
ph l { n z
plan's
ph l { n z
plant
ph l { n t
plant-	like
ph l { n	t l aI k
plante
ph l { n t
plants
ph l { n t s
plant's
ph l { n t s
plaque
ph l { k
plaques
ph l { k s
plas-	ma
ph l { z	m V
plas-	mi-	no-	gen
ph l { z	m I	n V	dZ V n
plas-	mo-	di-	a
ph l { z	m @U	d i:	V
plas-	mo-	di-	um
ph l { z	m @U	d i:	V m
plas-	te-	rer
ph l { s	t @r	@r
plas-	te-	ring
ph l { s	t @r	I N
plas-	ter
ph l { s	t @r
plas-	ter-	board
ph l { s	t @r	b O@ d
plas-	ter-	work
ph l { s	t @r	w @r k
plas-	tered
ph l { s	t @r d
plas-	ters
ph l { s	t @r z
plas-	ti-	ci-	zer
ph l { s	t I	s aI	z @r
plas-	ti-	cine
ph l { s	t I	s i: n
plas-	tic
ph l { s	t I k
plas-	tics
ph l { s	t I k s
plass
ph l { s
plat-	form
ph l { t	f O@ m
plat-	forms
ph l { t	f O@ m z
plat-	form's
ph l { t	f O@ m z
plat-	ten
ph l {	t V n
plat-	ter
ph l {	t @r
plat-	ters
ph l {	t @r z
plate
ph l eI t
plate-	let
ph l eI t	l V t
plate-	lets
ph l eI t	l V t s
plate-	like
ph l eI t	l aI k
plates
ph l eI t s
plath
ph l { T
platt
ph l { t
platte
ph l { t
plau-	dit
ph l O:	d I t
plau-	dits
ph l O:	d I t s
plau-	si-	bi-	li-	ty
ph l O:	z I	b I	l I	t i:
plau-	si-	ble
ph l O:	z I	b V l
plau-	sib-	ly
ph l O:	z I b	l i:
play
ph l eI
play-	back
ph l eI	b { k
play-	book
ph l eI	b U k
play-	boy
ph l eI	b OI
play-	boy's
ph l eI	b OI z
play-	ful
ph l eI	f V l
play-	ful-	ly
ph l eI	f V	l i:
play-	ful-	ness
ph l eI	f V l	n V s
play-	ground
ph l eI g	r aU n d
play-	grounds
ph l eI g	r aU n d z
play-	house
ph l eI	h aU s
play-	ing
ph l eI	I N
play-	mate
ph l eI	m eI t
play-	mates
ph l eI	m eI t s
play-	off
ph l eI	O: f
play-	offs
ph l eI	O: f s
play-	pen
ph l eI	p e n
play-	room
ph l eI	r u: m
play-	sta-	tion
ph l eI s	t eI	S V n
play-	tex
ph l eI	t e k s
play-	thing
ph l eI	T I N
play-	things
ph l eI	T I N z
play-	wright
ph l eI	r aI t
play-	wrights
ph l eI	r aI t s
played
ph l eI d
plays
ph l eI z
ple-	bei-	an
ph l V	b i:	V n
ple-	bei-	ans
ph l V	b i:	V n z
ple-	bis-	cite
ph l e	b I	s aI t
ple-	na-	ry
ph l e	n @r	i:
ple-	num
ph l e	n V m
ple-	num's
ph l e	n V m z
ple-	tho-	ra
ph l e	T @r	V
ple-	xi-	glas
ph l e k	s I g	l { s
ple-	xi-	glass
ph l e k	s I g	l { s
ple-	xus
ph l e k	s V s
plea
ph l i:
plea-	ded
ph l i:	d V d
plea-	ding
ph l i:	d I N
plea-	dings
ph l i:	d I N z
plea-	san-	ton
ph l e	z V n	t V n
plea-	sant
ph l e	z V n t
plea-	sant-	ly
ph l e	z V n	t l i:
plea-	sant-	ries
ph l e	z V n	t r i: z
plea-	sant-	ry
ph l e	z V n	t r i:
plea-	sant-	ville
ph l e	z V n	t v I l
plea-	sants
ph l e	z V n t s
plea-	ser
ph l i:	z @r
plea-	ses
ph l i:	z V z
plea-	sing
ph l i:	z I N
plea-	sing-	ly
ph l i:	z I N	l i:
plea-	su-	ra-	ble
ph l e	Z @r	V	b V l
plea-	sure
ph l e	Z @r
plea-	sures
ph l e	Z @r z
plead
ph l i: d
pleads
ph l i: d z
pleas
ph l i: z
please
ph l i: z
pleased
ph l i: z d
pleat
ph l i: t
pleats
ph l i: t s
pled
ph l e d
pled-	ger
ph l e	dZ @r
pled-	ges
ph l e	dZ V z
pled-	ging
ph l e	dZ I N
pledge
ph l e dZ
pledged
ph l e dZ d
plei-	a-	des
ph l i:	V	d i: z
plei-	ad
ph l i:	V d
plei-	ads
ph l i:	V d z
plei-	sto-	cene
ph l aI s	t V	s i: n
plein
ph l i: n
plen-	ti-	ful
ph l e n	t I	f V l
plen-	ty
ph l e n	t i:
ples-	sis
ph l e	s I s
pleu-	ri-	sy
ph l U@	I	s i:
plew
ph l u:
plex
ph l e k s
pli-	a-	ble
ph l aI	V	b V l
pli-	ant
ph l aI	V n t
pli-	er
ph l aI	@r
pli-	ers
ph l aI	@r z
pli-	ni-	us
ph l I	n i:	V s
pli-	ny
ph l I	n i:
pli-	o-	cene
ph l aI	V	s i: n
plied
ph l aI d
plies
ph l aI z
plight
ph l aI t
)"
R"(plin-	king
ph l I N	k I N
plink
ph l I N k
plinth
ph l I n T
plo-	vers
ph l V	v @r z
plo-	wing
ph l aU	I N
ploch
ph l Q k
plock
ph l Q k
plod
ph l Q d
plod-	ded
ph l Q	d V d
plod-	ding
ph l Q	d I N
plop
ph l Q p
plopped
ph l Q p t
ploss
ph l O: s
plot
ph l Q t
plot-	kin
ph l Q t	k I n
plot-	ted
ph l Q	t V d
plot-	ter
ph l Q	t @r
plot-	ters
ph l Q	t @r z
plot-	ting
ph l Q	t I N
plots
ph l Q t s
plott
ph l Q t
plotz
ph l Q t s
plough
ph l aU
ploughed
ph l aU d
plow
ph l aU
plow-	man
ph l aU	m V n
plow-	man's
ph l aU	m V n z
plow-	right
ph l aU	r aI t
plow-	share
ph l aU	S eI r
plow-	shares
ph l aU	S eI r z
plowed
ph l aU d
plows
ph l aU z
ploy
ph l OI
ploys
ph l OI z
plu-	ma-	ges
ph l u:	m V	dZ V z
plu-	mage
ph l u:	m V dZ
plu-	mer
ph l u:	m @r
plu-	ra-	li-	sm
ph l U@	V	l I	z V m
plu-	ra-	li-	ty
ph l @r	{	l I	t i:
plu-	ra-	lis-	tic
ph l U@	V	l I s	t I k
plu-	ral
ph l U@	V l
plu-	ri-	bus
ph l U@	I	b V s
plu-	ses
ph l V	s V z
plu-	to
ph l u:	t @U
plu-	to-	ni-	an
ph l u:	t @U	n i:	V n
plu-	to-	ni-	um
ph l u:	t @U	n i:	V m
plu-	to-	nic
ph l u:	t Q	n I k
plu-	toc-	rat
ph l u:	t V k	r { t
plu-	toc-	rats
ph l u:	t V k	r { t s
plu-	to's
ph l u:	t @U z
plu-	vi-	al
ph l u:	v i:	V l
pluc-	ker
ph l V	k @r
pluc-	king
ph l V	k I N
pluc-	ky
ph l V	k i:
pluck
ph l V k
plucked
ph l V k t
plucks
ph l V k s
pluff
ph l V f
plug
ph l V g
plug-	ging
ph l V	g I N
plugged
ph l V g d
plugs
ph l V g z
plum
ph l V m
plum-	ber
ph l V	m @r
plum-	bers
ph l V	m @r z
plum-	bing
ph l V	m I N
plum-	me-	ted
ph l V	m V	t V d
plum-	me-	ting
ph l V	m V	t I N
plum-	mer
ph l V	m @r
plum-	met
ph l V	m V t
plum-	mets
ph l V	m V t s
plumb
ph l V m
plumbed
ph l V m d
plume
ph l u: m
plumes
ph l u: m z
plump
ph l V m p
plumped
ph l V m p t
plums
ph l V m z
plum's
ph l V m z
plun-	de-	ring
ph l V n	d @r	I N
plun-	der
ph l V n	d @r
plun-	dered
ph l V n	d @r d
plun-	ger
ph l V n	dZ @r
plun-	ger's
ph l V n	dZ @r z
plun-	ges
ph l V n	dZ V z
plun-	ging
ph l V n	dZ I N
plun-	ker
ph l V N	k @r
plun-	kers
ph l V N	k @r z
plun-	kett
ph l V N	k e t
plun-	king
ph l V N	k I N
plunge
ph l V n dZ
plunged
ph l V n dZ d
plunk
ph l V N k
plunked
ph l V N k t
plus
ph l V s
plush
ph l V S
ply
ph l aI
ply-	ing
ph l aI	I N
ply-	mouth
ph l I	m V T
ply-	mouth's
ph l I	m V T s
ply-	wood
ph l aI	w U d
plymp-	ton
ph l I m	p t V n
pneu-	ma-	tic
n u:	m {	t I k
pneu-	ma-	tics
n U	m {	t I k s
pneu-	mo-	cys-	tis
n u:	m @U	s I s	t I s
pneu-	mo-	nia
n u:	m @U n	j V
pneu-	mo-	nic
n u:	m Q	n I k
po
ph @U
po-	co
ph @U	k @U
po-	co-	no
ph @U	k V	n @U
po-	co-	nos
ph @U	k V	n @U z
po-	cus
ph @U	k V s
po-	des-	ta
ph @U	d e s	t V
po-	di-	at-	rist
ph V	d aI	V t	r I s t
po-	di-	um
ph @U	d i:	V m
po-	di-	ums
ph @U	d i:	V m z
po-	dunk
ph @U	t V N k
po-	e-	tic
ph @U	e	t I k
po-	e-	tical-	ly
ph @U	e	t I k	l i:
po-	e-	try
ph @U	V t	r i:
po-	em
ph @U	V m
po-	ems
ph @U	V m z
po-	et
ph @U	V t
po-	ets
ph @U	V t s
po-	et's
ph @U	V t s
po-	go
ph @U	g @U
po-	hang
ph @U	h { N
po-	ker
ph @U	k @r
po-	key
ph @U	k i:
po-	king
ph @U	k I N
po-	kor-	ny
ph V	k O@	n i:
po-	ky
ph @U	k i:
po-	la-	ri-	me-	ter
ph @U	l @r	I	m V	t @r
po-	la-	ri-	ty
ph @U	l e@	I	t i:
po-	la-	ri-	za-	tion
ph @U	l @r	V	z eI	S V n
po-	la-	ri-	zer
ph @U	l @r	aI	z @r
po-	la-	ri-	zes
ph @U	l @r	aI	z V z
po-	la-	ri-	zing
ph @U	l @r	aI	z I N
po-	la-	ris
ph @U	l e@	I s
po-	la-	ris-	cope
ph @U	l e@	I s	k @U p
po-	la-	rize
ph @U	l @r	aI z
po-	la-	rized
ph @U	l @r	aI z d
po-	la-	ro-	gra-	phy
ph @U	l @r	Q g	r V	f i:
po-	la-	roid
ph @U	l @r	OI d
po-	la-	roids
ph @U	l @r	OI d z
po-	la-	roid's
ph @U	l @r	OI d z
po-	lack
ph @U	l { k
po-	lak
ph @U	l V k
po-	lan-	ski
ph V	l { n	s k i:
po-	land
ph @U	l V n d
po-	land's
ph @U	l V n d z
po-	lar
ph @U	l @r
po-	le-	mi-	cal
ph V	l e	m V	k V l
po-	le-	mi-	cist
ph V	l e	m V	s V s t
po-	le-	mic
ph V	l e	m I k
po-	le-	mics
ph @U	l e	m I k s
po-	ley
ph @U	l i:
po-	li
ph @U	l i:
po-	li-	ces
ph V	l i:	s V z
po-	li-	ce's
ph V	l i:	s V z
po-	li-	cies
ph Q	l I	s i: z
po-	li-	cing
ph V	l i:	s I N
po-	li-	cy
ph Q	l I	s i:
po-	li-	cy-	hol-	der
ph Q	l I	s i:	h @U l	d @r
po-	li-	cy-	hol-	ders
ph Q	l I	s i:	h @U l	d @r z
po-	li-	cy-	hol-	der's
ph Q	l I	s i:	h @U l	d @r z
po-	li-	cy-	ma-	ker
ph Q	l I	s i:	m eI	k @r
po-	li-	cy-	ma-	kers
ph Q	l I	s i:	m eI	k @r z
po-	li-	cy-	ma-	king
ph Q	l I	s i:	m eI	k I N
po-	li-	cy's
ph Q	l I	s i: z
po-	li-	o
ph @U	l i:	@U
po-	li-	shing
ph Q	l I	S I N
po-	li-	ti
ph @U	l i:	t i:
po-	li-	ti-	cal
ph V	l I	t I	k V l
po-	li-	ti-	cal-	ly
ph V	l I	t I	k V	l i:
po-	li-	ti-	ci-	za-	tion
ph V	l I	t I	s V	z eI	S V n
po-	li-	ti-	ci-	zing
ph V	l I	t I	s aI	z I N
po-	li-	ti-	cian
ph Q	l I	t I	S V n
po-	li-	ti-	cians
ph Q	l I	t I	S V n z
po-	li-	ti-	cian's
ph Q	l I	t I	S V n z
po-	li-	ti-	cize
ph V	l I	t I	s aI z
po-	li-	ti-	cized
ph V	l I	t I	s aI z d
po-	li-	ti-	co
ph V	l I	t I	k @U
po-	li-	ti-	cos
ph V	l I	t I	k @U z
po-	li-	tic
ph Q	l I	t I k
po-	li-	tic-	king
ph Q	l I	t I	k I N
po-	li-	tics
ph Q	l I	t I k s
po-	li-	to
ph @U	l i:	t @U
po-	li-	ty
ph Q	l I	t i:
po-	lice
ph V	l i: s
po-	lice-	man
ph V	l i: s	m V n
po-	lice-	man's
ph V	l i: s	m V n z
po-	lice-	men
ph V	l i: s	m e n
po-	lice-	wo-	man
ph V	l i: s	w U	m V n
po-	lice-	wo-	men
ph V	l i: s	w I	m e n
po-	liced
ph V	l i: s t
po-	lin-	ski
ph V	l I n	s k i:
po-	ling
ph @U	l I N
po-	lis
ph @U	l I s
po-	lish
ph Q	l I S
po-	lished
ph Q	l I S t
po-	lit-	bu-	ro
ph Q	l I t	b j U@	@U
po-	lit-	bu-	ro's
ph Q	l I t	b j U@	@U z
po-	lite
ph V	l aI t
po-	lite-	ly
ph V	l aI t	l i:
po-	lite-	ness
ph V	l aI t	n V s
po-	lo
ph @U	l @U
po-	lo-	naise
ph Q	l V	n eI z
po-	lo-	ni-	um
ph V	l @U	n i:	V m
po-	lo's
ph @U	l @U z
po-	ly
ph Q	l i:
po-	ly-	a-	mide
ph Q	l i:	{	m aI d
po-	ly-	an-	drous
ph Q	l i:	{ n	d r V s
po-	ly-	and-	ry
ph Q	l i:	{ n	d r i:
po-	ly-	bu-	ty-	lene
ph Q	l i: b	j u:	t V	l i: n
po-	ly-	car-	pic
ph Q	l I	k Q@	p I k
po-	ly-	chlo-	ri-	na-	ted
ph Q	l i: k	l O@	I	n eI	t I d
po-	ly-	chrome
ph Q	l I k	r @U m
po-	ly-	e-	thy-	lene
ph Q	l i:	e	T V	l i: n
po-	ly-	es-	ter
ph Q	l i:	e s	t @r
po-	ly-	es-	ters
ph Q	l i:	e s	t @r z
po-	ly-	ga-	mous
ph V	l I	g V	m V s
po-	ly-	ga-	my
ph V	l I	g V	m i:
po-	ly-	glot
ph Q	l i: g	l Q t
po-	ly-	go-	nal
ph V	l I	g V	n V l
po-	ly-	gon
ph Q	l I	g Q n
po-	ly-	gram
ph Q	l i: g	r { m
po-	ly-	gram's
ph Q	l I g	r { m z
po-	ly-	graph
ph Q	l I g	r { f
po-	ly-	graphs
ph Q	l i: g	r { f s
po-	ly-	gy-	nous
ph V	l I	dZ V	n V s
po-	ly-	gy-	ny
ph V	l I	dZ V	n i:
po-	ly-	hed-	ron
ph Q	l i:	h i: d	r V n
po-	ly-	hed-	rons
ph Q	l i:	h i: d	r V n z
po-	ly-	mor-	phi-	sm
ph Q	l i:	m O@	f I	z V m
po-	ly-	mor-	phic
ph Q	l i:	m O@	f I k
po-	ly-	morph
ph Q	l i:	m O@ f
po-	ly-	ne-	sia
ph Q	l V	n i:	Z V
po-	ly-	ne-	sian
ph Q	l V	n i:	Z V n
po-	ly-	no-	mi-	al
ph Q	l V	n @U	m i:	V l
po-	ly-	phase
ph Q	l V	f eI z
po-	ly-	pho-	nic
ph Q	l V	f Q	n I k
po-	ly-	pho-	ny
ph V	l I	f V	n i:
po-	ly-	pro-	py-	lene
ph Q	l i: p	r @U	p V	l i: n
po-	ly-	sac-	cha-	ride
ph Q	l V	s {	k @r	aI d
po-	ly-	sac-	cha-	rides
ph Q	l V	s {	k @r	aI d z
po-	ly-	si-	li-	con
ph Q	l i:	s I	l I	k Q n
po-	ly-	sty-	rene
ph Q	l V s	t aI	r i: n
po-	ly-	tech-	nic
ph Q	l i:	t e k	n I k
po-	ly-	the-	i-	sm
ph Q	l V	T i:	I	z V m
po-	ly-	the-	is-	tic
ph Q	l V	T i:	I s	t I k
po-	ly-	u-	re-	thane
ph Q	l i:	U@	V	T eI n
po-	ly-	vi-	nyl
ph Q	l i:	v aI	n V l
po-	lyp
ph Q	l V p
po-	lyps
ph Q	l V p s
po-	ly's
ph Q	l i: z
po-	me-	ra-	ni-	a
ph Q	m @r	eI	n i:	V
po-	me-	ra-	ni-	an
ph Q	m @r	eI	n i:	V n
po-	me-	roy
ph Q	m @r	OI
po-	mo-	lo-	gy
ph @U	m Q	l V	dZ i:
po-	mo-	na
ph @U	m @U	n V
po-	nied
ph @U	n i: d
po-	nies
ph @U	n i: z
po-	ny
ph @U	n i:
po-	ny-	tail
ph @U	n i:	t eI l
po-	pek
ph @U	p I k
po-	pel-	ka
ph V	p e l	k V
po-	peye
ph Q	p aI
po-	peyes
ph O:	p aI z
po-	peye's
ph Q	p aI z
po-	poff
ph Q	p O: f
po-	pov
ph @U	p V v
po-	pu-	la-	ri-	ty
ph Q p	j V	l e@	V	t i:
po-	pu-	la-	ri-	za-	tion
ph Q p	j V	l @r	V	z eI	S V n
po-	pu-	la-	ri-	zer
ph Q p	j V	l @r	aI	z @r
po-	pu-	la-	ri-	zing
ph Q p	j V	l @r	aI	z I N
po-	pu-	la-	rize
ph Q p	j V	l @r	aI z
po-	pu-	la-	rized
ph Q p	j V	l @r	aI z d
po-	pu-	la-	ted
ph Q p	j V	l eI	t V d
po-	pu-	la-	ting
ph Q p	j V	l eI	t I N
po-	pu-	la-	tion
ph Q p	j V	l eI	S V n
po-	pu-	la-	tions
ph Q p	j V	l eI	S V n z
po-	pu-	lace
ph Q p	j V	l V s
po-	pu-	lar
ph Q p	j V	l @r
po-	pu-	lar-	ly
ph Q p	j V	l @r	l i:
po-	pu-	late
ph Q p	j V	l eI t
po-	pu-	li-	sm
ph Q p	j V	l I	z V m
po-	pu-	list
ph Q p	j V	l V s t
po-	pu-	lists
ph Q p	j V	l V s t s
po-	pu-	lous
ph Q p	j V	l V s
po-	ring
ph O@	I N
po-	rous
ph O@	V s
po-	si-	ti-	vi-	sm
ph Q	z I	t I	v I	z V m
po-	si-	tion
ph V	z I	S V n
po-	si-	tions
ph V	z I	S V n z
po-	si-	tive
ph Q	z I	t I v
po-	si-	tive-	ly
ph Q	z I	t I v	l i:
po-	si-	tives
ph Q	z I	t I v z
po-	si-	tron
ph Q	z I t	r Q n
po-	si-	trons
ph Q	z I t	r Q n z
po-	sits
ph Q	z I t s
po-	ta-	ble
ph @U	t V	b V l
po-	ta-	to
ph V	t eI	t @U
po-	ta-	toes
ph V	t eI	t @U z
po-	tas-	si-	um
ph V	t {	s i:	V m
po-	tash
ph Q	t { S
po-	teet
ph Q	t i: t
po-	tem-	kin
ph V	t e m	k I n
po-	ten-	cy
ph @U	t V n	s i:
po-	ten-	tate
ph @U	t V n	t eI t
po-	ten-	tates
ph @U	t V n	t eI t s
po-	ten-	tial
ph V	t e n	S V l
po-	ten-	tial-	ly
ph V	t e n	S V	l i:
po-	ten-	tials
ph V	t e n	tS V l z
po-	tent
ph @U	t V n t
po-	thole
ph Q t	h @U l
po-	tholed
ph Q t	h @U l d
po-	tholes
ph Q t	h @U l z
po-	tion
ph @U	S V n
po-	tions
ph @U	S V n z
po-	to-	mac
ph V	t @U	m V k
po-	ver-	ty
ph Q	v @r	t i:
po-	we-	ring
ph aU	@r	I N
po-	well
ph aU	V l
po-	well's
ph @U	V l z
po-	wer
ph aU	@r
po-	wer-	boat
ph aU	@r	b @U t
po-	wer-	ful
ph aU	@r	f V l
po-	wer-	hou-	ses
ph aU	@r	h aU	s V z
po-	wer-	house
ph aU	@r	h aU s
po-	wer-	less
ph aU	@r	l V s
po-	wer-	less-	ness
ph aU	@r	l V s	n V s
po-	wered
ph aU	@r d
po-	werful-	ly
ph aU	@r f	l i:
po-	wers
ph aU	@r z
po-	wer's
ph aU	@r z
poc-	ke-	ted
ph Q	k V	t V d
poc-	ke-	ting
ph Q	k V	t I N
poc-	ket
ph Q	k V t
poc-	ket-	book
ph Q	k V t	b U k
poc-	ket-	books
ph Q	k V t	b U k s
poc-	ket-	ful
ph Q	k V t	f U l
poc-	kets
ph Q	k V t s
poche
ph Q tS
pock
ph Q k
pock-	mark
ph Q k	m Q@ k
pock-	marked
ph Q k	m Q@ k t
pocked
ph Q k t
pocks
ph Q k s
pod
ph Q d
pod-	ho-	retz
ph Q d	h @r	e t s
podge
ph Q dZ
pods
ph Q d z
pod's
ph Q d z
poe
ph @U
poe's
ph @U z
pog-	rom
ph V g	r Q m
pog-	roms
ph V g	r Q m z
pogue
ph @U g
poh
ph @U
poh-	jo-	la
ph @U	dZ @U	l V
poi-	so-	ning
ph OI	z V	n I N
poi-	so-	nings
ph OI	z V	n I N z
poi-	so-	nous
ph OI	z V	n V s
poi-	son
ph OI	z V n
poi-	soned
ph OI	z V n d
poi-	sons
ph OI	z V n z
poi-	tier
ph OI t	j @r
poig-	nan-	cy
ph OI n	j V n	s i:
poig-	nant
ph OI n	j V n t
poig-	nant-	ly
ph OI n	j V n	t l i:
poin-	dex-	ter
ph OI n	d e k	s t @r
poin-	set-	ti-	a
ph OI n	s e	t i:	V
poin-	set-	ti-	as
ph OI n	s e	t i:	V z
poin-	ted
ph OI n	t V d
poin-	ted-	ly
ph OI n	t V d	l i:
poin-	ter
ph OI n	t @r
poin-	ters
ph OI n	t @r z
poin-	ting
ph OI n	t I N
poin-	ty
ph OI n	t i:
point
ph OI n t
point-	less
ph OI n	t l V s
pointe
ph OI n t
points
ph OI n t s
point's
ph OI n t s
pois-	son
ph OI z	s V n
poise
ph OI z
poised
ph OI z d
poke
ph @U k
poke-	weed
ph @U k	w i: d
poked
ph @U k t
pokes
ph @U k s
pol
ph O: l
pol-	der
ph @U l	d @r
pol-	je
ph @U l	dZ i:
pol-	ka
ph @U l	k V
pol-	kas
ph @U l	k V z
pol-	lack
ph Q	l V k
pol-	lack's
ph Q	l V k s
pol-	lak
ph Q	l V k
pol-	lan
ph Q	l V n
pol-	lard
ph Q	l @r d
pol-	lard's
ph Q	l @r d z
pol-	len
ph Q	l V n
pol-	lens
ph Q	l V n z
pol-	let
ph Q	l e t
pol-	li-	na-	ted
ph Q	l I	n eI	t I d
pol-	li-	na-	tion
ph Q	l I	n eI	S V n
pol-	li-	nate
ph Q	l I	n eI t
pol-	li-	nates
ph Q	l I	n eI t s
pol-	li-	ni
ph V	l i:	n i:
pol-	li-	ni-	a
ph Q	l I	n i:	V
pol-	li-	o
ph Q	l i:	@U
pol-	ling
ph @U	l I N
pol-	litt
ph Q	l I t
pol-	lo
ph Q	l @U
pol-	lock
ph Q	l V k
pol-	loi
ph Q	l OI
pol-	lok
ph Q	l V k
pol-	lu-	tant
ph V	l u:	t V n t
pol-	lu-	tants
ph V	l u:	t V n t s
pol-	lu-	ted
ph V	l u:	t V d
pol-	lu-	ter
ph V	l u:	t @r
pol-	lu-	ters
ph V	l u:	t @r z
pol-	lu-	ting
ph V	l u:	t I N
pol-	lu-	tion
ph V	l u:	S V n
pol-	lute
ph V	l u: t
pol-	lutes
ph V	l u: t s
pol-	lux
ph Q	l V k s
pol-	ly
ph Q	l i:
pol-	ly-	an-	na
ph Q	l i:	{	n V
pol-	ly's
ph Q	l i: z
pol-	son
ph @U l	s V n
pol-	ster
ph @U l	s t @r
pol-	ter-	geist
ph @U l	t @r	g aI s t
pol-	ter-	geists
ph @U l	t @r	g aI s t s
pole
ph @U l
pole-	cat
ph @U l	k { t
pole-	cats
ph @U l	k { t s
pole-	ward
ph @U l	w @r d
poles
ph @U l z
polk
ph @U k
polk's
ph @U k s
poll
ph @U l
poll-	man
ph @U l	m V n
poll-	ster
ph @U l	s t @r
poll-	sters
ph @U l	s t @r z
polled
ph @U l d
polls
ph @U l z
poll's
ph @U l z
pols
ph @U l z
pom
ph O: m
pom-	bo
ph Q m	b @U
pom-	mel
ph Q	m V l
pom-	mer
ph Q	m @r
pom-	pa
ph Q m	p V
pom-	pa-	no
ph Q m	p V	n @U
pom-	pey
ph Q m	p i:
pom-	pi-	dou
ph Q m	p I	d u:
pom-	po-	si-	ty
ph Q m	p Q	s I	t i:
pom-	pon
ph Q m	p Q n
pom-	pons
ph Q m	p Q n z
pom-	pous
ph Q m	p V s
pom-	pous-	ness
ph Q m	p V s	n V s
pom-	roy
ph Q m	r OI
pomp
ph Q m p
pon
ph Q n
pon-	ce
ph @U n	s eI
pon-	cho
ph Q n	tS @U
pon-	chos
ph Q n	tS @U z
pon-	de-	ring
ph Q n	d @r	I N
pon-	de-	ro-	sa
ph Q n	d @r	@U	s V
pon-	de-	ro-	sa's
ph Q n	d @r	@U	s V z
pon-	de-	rous
ph Q n	d @r	V s
pon-	der
ph Q n	d @r
pon-	dered
ph Q n	d @r d
pon-	ders
ph Q n	d @r z
pon-	tes
ph @U n	t e s
pon-	ti-	ac
ph Q n	t i:	{ k
pon-	ti-	acs
ph Q n	t i:	{ k s
pon-	ti-	ac's
ph Q n	t i:	{ k s
pon-	ti-	fi-	ca-	ted
ph Q n	t I	f I	k eI	t I d
pon-	ti-	fi-	ca-	ting
ph Q n	t I	f I	k eI	t I N
pon-	ti-	fi-	ca-	tion
ph Q n	t I	f I	k eI	S V n
pon-	ti-	fi-	ca-	tions
ph Q n	t I	f I	k eI	S V n z
pon-	ti-	fi-	cal
ph Q n	t I	f I	k V l
pon-	ti-	fi-	cate
ph Q n	t I	f I	k eI t
pon-	ti-	fi-	cates
ph Q n	t I	f I	k eI t s
pon-	ti-	us
ph Q n	t i:	V s
pon-	tiff
ph Q n	t I f
pon-	tiff's
ph Q n	t I f s
pon-	to
ph Q n	t @U
pon-	ton
ph Q n	t V n
pon-	toon
ph Q n	t u: n
pon-	toons
ph Q n	t u: n z
pon-	zi
ph Q n	z i:
pon-	zo
ph Q n	z @U
pond
ph Q n d
ponds
ph Q n d z
pond's
ph Q n d z
pong
ph O: N
pons
ph Q n z
pont
ph Q n t
ponte
ph Q n t
ponts
ph Q n t s
pont's
ph Q n t s
poo
ph u:
poo-	ches
ph u:	tS V z
poo-	dle
ph u:	d V l
poo-	dles
ph u:	d V l z
poo-	ler
ph u:	l @r
poo-	ley
ph u:	l i:
poo-	ling
ph u:	l I N
poo-	per
ph u:	p @r
poo-	rer
ph U@	@r
poo-	rest
ph U@	V s t
pooch
ph u: tS
poof
ph u: f
pooh
ph u:
poohed
ph u: d
pool
ph u: l
pool-	side
ph u: l	s aI d
poole
ph u: l
pooled
ph u: l d
pools
ph u: l z
pool's
ph u: l z
poon
ph u: n
poop
ph u: p
pooped
ph u: p t
poops
ph u: p s
poor
ph U@
poor-	house
ph U@	h aU s
poor-	ly
ph U@	l i:
poor-	spi-	ri-	ted
ph U@ s	p I@	I	t I d
poore
ph U@
pop
ph Q p
pop-	corn
ph Q p	k O@ n
pop-	lar
ph Q p	l @r
pop-	lin
ph Q p	l I n
pop-	pa
ph Q	p V
pop-	per
ph Q	p @r
pop-	pers
ph Q	p @r z
pop-	pies
ph Q	p i: z
pop-	ping
ph Q	p I N
pop-	pins
ph Q	p I n z
pop-	ple
ph Q	p V l
pop-	py
ph Q	p i:
pop-	py-	cock
ph Q	p i:	k O: k
pop-	py's
ph Q	p i: z
pop-	si-	cle
ph Q p	s I	k V l
pope
ph @U p
pope-	joy
ph @U p	dZ OI
pope-	joy's
ph @U p	dZ OI z
popes
ph @U p z
pope's
ph @U p s
popp
ph Q p
popped
ph Q p t
pops
ph Q p s
pop's
ph Q p s
por
ph O@
por-	ce-	lain
ph O@	s V	l V n
por-	ce-	lains
ph O@	s V	l V n z
por-	ches
ph O@	tS V z
por-	cu-	pine
ph O@ k	j V	p aI n
por-	cu-	pines
ph O@ k	j V	p aI n z
por-	ges
ph O@	dZ V z
por-	gy
ph O@	g i:
por-	ky
ph O@	k i:
por-	no
ph O@	n @U
por-	no-	gra-	pher
ph O@	n Q g	r V	f @r
por-	no-	gra-	phers
ph O@	n Q g	r V	f @r z
por-	no-	gra-	phic
ph O@	n V g	r {	f I k
por-	no-	gra-	phy
ph O@	n Q g	r V	f i:
por-	phy-	ri-	tic
ph O@	f @r	I	t I k
por-	phy-	ry
ph O@	f @r	i:
por-	poi-	ses
ph O@	p V	s V z
por-	poise
ph O@	p V s
por-	ridge
ph O@	I dZ
por-	ro
ph O@	@U
por-	sche
ph O@	S V
por-	sches
ph O@	S V z
por-	sche's
ph O@	S V z
por-	ta
ph O@	t V
por-	ta-	bi-	li-	ty
ph O@	t V	b I	l V	t i:
por-	ta-	ble
ph O@	t V	b V l
por-	ta-	bles
ph O@	t V	b V l z
por-	tage
ph O@	t V dZ
por-	tal
ph O@	t V l
por-	tals
ph O@	t V l z
por-	te-	ous
ph O@	t i:	V s
por-	te-	ra-	ges
ph O@	t @r	I	dZ V z
por-	ted
ph O@	t V d
por-	ten-	ding
ph O@	t e n	d I N
por-	ten-	tous
ph O@	t e n	t V s
por-	tend
ph O@	t e n d
por-	tends
ph O@	t e n d z
por-	tent
ph O@	t e n t
por-	tents
ph O@	t e n t s
por-	ter
ph O@	t @r
por-	ters
ph O@	t @r z
por-	ter's
ph O@	t @r z
por-	ti-	co
ph O@	t I	k @U
por-	ti-	er
ph O@	t i:	@r
por-	tia
ph O@	S V
por-	ting
ph O@	t I N
)"
R"(por-	tion
ph O@	S V n
por-	tions
ph O@	S V n z
por-	to
ph O@	t @U
por-	tu-	gal
ph O@	tS V	g V l
por-	tu-	gal's
ph O@	tS V	g V l z
por-	tu-	guese
ph O@	tS V	g i: z
porch
ph O@ tS
pore
ph O@
pored
ph O@ d
pores
ph O@ z
pork
ph O@ k
porn
ph O@ n
porr
ph O@
port
ph O@ t
port-	fo-	li-	o
ph O@ t	f @U	l i:	@U
port-	fo-	li-	os
ph O@ t	f @U	l i:	@U z
port-	fo-	li-	o's
ph O@ t	f @U	l i:	@U z
port-	land
ph O@ t	l V n d
port-	land's
ph O@ t	l V n d z
port-	ly
ph O@ t	l i:
port-	man
ph O@ t	m V n
port-	ra-	yal
ph O@ t	r eI	V l
port-	ra-	yals
ph O@ t	r eI	V l z
port-	rait
ph O@ t	r V t
port-	raits
ph O@ t	r V t s
port-	ray
ph O@ t	r eI
port-	ray-	ing
ph O@ t	r eI	I N
port-	rayed
ph O@ t	r eI d
port-	rays
ph O@ t	r eI z
porte
ph O@ t
ports
ph O@ t s
port's
ph O@ t s
ports-	mouth
ph O@ t	s m V T
pos-	ner
ph @U z	n @r
pos-	ner's
ph @U z	n @r z
pos-	se
ph Q	s i:
pos-	ses
ph Q	s i: z
pos-	ses-	ses
ph V	z e	s V z
pos-	ses-	sing
ph V	z e	s I N
pos-	ses-	sion
ph V	z e	S V n
pos-	ses-	sions
ph V	z e	S V n z
pos-	ses-	sive
ph V	z e	s I v
pos-	ses-	sive-	ness
ph V	z e	s I v	n V s
pos-	ses-	sor
ph V	z e	s @r
pos-	sess
ph V	z e s
pos-	sessed
ph V	z e s t
pos-	si-	bi-	li-	ties
ph Q	s I	b I	l I	t i: z
pos-	si-	bi-	li-	ty
ph Q	s I	b I	l I	t i:
pos-	si-	ble
ph Q	s I	b V l
pos-	sib-	ly
ph Q	s I b	l i:
pos-	sum
ph Q	s V m
pos-	sums
ph Q	s V m z
pos-	tage
ph @U s	t V dZ
pos-	tal
ph @U s	t V l
pos-	te-	ri-	or
ph O: s	t I@	i:	e@
pos-	te-	ri-	ty
ph Q s	t e@	I	t i:
pos-	ted
ph @U s	t V d
pos-	tel
ph Q s	t V l
pos-	ter
ph @U s	t @r
pos-	ters
ph @U s	t @r z
pos-	ting
ph @U s	t I N
pos-	tings
ph @U s	t I N z
pos-	ton
ph @U s	t V n
pos-	tu-	late
ph Q s	tS V	l eI t
pos-	tu-	lates
ph Q s	tS V	l eI t s
pos-	tu-	ring
ph Q s	tS @r	I N
pos-	tu-	rings
ph Q s	tS @r	I N z
pos-	ture
ph Q s	tS @r
pos-	tures
ph Q s	tS @r z
poss
ph O: s
post
ph @U s t
post-	at-	tack
ph @U s	t V	t { k
post-	card
ph @U s	t k Q@ d
post-	cards
ph @U s	t k Q@ d z
post-	crash
ph @U s	t k r { S
post-	date
ph @U s	t d eI t
post-	doc-	to-	ral
ph @U s	t d Q k	t @r	V l
post-	game
ph @U s	t g eI m
post-	hole
ph @U s	t h @U l
post-	holes
ph @U s	t h @U l z
post-	hu-	mous
ph Q s	tS U	m V s
post-	hu-	mous-	ly
ph Q s	tS U	m V s	l i:
post-	man
ph @U s	t m V n
post-	mark
ph @U s	t m Q@ k
post-	marked
ph @U s	t m Q@ k t
post-	mas-	ter
ph @U s	t m { s	t @r
post-	mas-	ters
ph @U s	t m { s	t @r z
post-	mo-	dern
ph @U s	t m Q	d @r n
post-	mor-	tem
ph @U s	t m O@	t e m
post-	na-	tal
ph @U s	t n eI	t V l
post-	po-	ning
ph @U s	t p @U	n I N
post-	pone
ph @U s	t p @U n
post-	pone-	ment
ph @U s	t p @U n	m V n t
post-	pone-	ments
ph @U s	t p @U n	m V n t s
post-	poned
ph @U s	t p @U n d
post-	pones
ph @U s	t p @U n z
post-	re-	ti-	re-	ment
ph @U s	t r i:	t aI	@r	m V n t
post-	script
ph @U s	k r I p t
post-	scripts
ph @U s	k r I p t s
post-	trau-	ma-	tic
ph @U s	t t r O:	m {	t I k
post-	war
ph @U s	t w O@
posts
ph @U s t s
post's
ph @U s t s
pot
ph Q t
pot-	latch
ph Q t	l { tS
pot-	luck
ph Q t	l V k
pot-	pie
ph Q t	p aI
pot-	pour-	ri
ph @U	p U@	i:
pot-	shot
ph Q	tS Q t
pot-	shots
ph Q	tS Q t s
pot-	te-	ry
ph Q	t @r	i:
pot-	ted
ph Q	t V d
pot-	ter
ph Q	t @r
pot-	ters
ph Q	t @r z
pot-	ter's
ph Q	t @r z
pot-	tin-	ger
ph Q	t I	N @r
pot-	tle
ph Q	t V l
pot-	ty
ph Q	t i:
pote
ph @U t
poth
ph Q T
pots
ph Q t s
pots-	dam
ph Q t	s d { m
pott
ph Q t
potts
ph Q t s
pou
ph u:
pou-	cher
ph aU	tS @r
pou-	ches
ph aU	tS V z
pou-	lenc
ph u:	l V N k
pou-	lenc's
ph u:	l V N k s
pou-	ring
ph O@	I N
pou-	ted
ph aU	t V d
pou-	ter
ph aU	t @r
pou-	ting
ph aU	t I N
pou-	ty
ph aU	t i:
pouch
ph aU tS
pough-	keep-	sie
ph V	k I p	s i:
pough-	keep-	sie's
ph V	k I p	s i: z
poul
ph u: l
poul-	ter
ph @U l	t @r
poul-	ti-	ces
ph @U l	t I	s V z
poul-	tice
ph @U l	t I s
poul-	try
ph @U l	t r i:
poun-	cey
ph aU n	s i:
poun-	cing
ph aU n	s I N
poun-	cy
ph u: N	k i:
poun-	dage
ph aU n	d I dZ
poun-	ded
ph aU n	d V d
poun-	der
ph aU n	d @r
poun-	ders
ph aU n	d @r z
poun-	ding
ph aU n	d I N
pounce
ph aU n s
pounced
ph aU n s t
pound
ph aU n d
pound-	stone
ph aU n	d s t @U n
pounds
ph aU n d z
pound's
ph aU n d z
pour
ph O@
poured
ph O@ d
pours
ph O@ z
pous-	sin
ph u:	s I n
pout
ph aU t
pouts
ph aU t s
pow
ph aU
pow-	de-	ring
ph aU	d @r	I N
pow-	de-	ry
ph aU	d @r	i:
pow-	der
ph aU	d @r
pow-	der-	ly
ph aU	d @r	l i:
pow-	dered
ph aU	d @r d
pow-	ders
ph aU	d @r z
pow-	nall
ph aU	n V l
pow-	ter
ph aU	t @r
pow-	wow
ph aU	w aU
powe
ph aU
power-	train
ph aU r	t r eI n
pows
ph @U z
pox
ph Q k s
poy-	nor
ph OI	n @r
poz-	nan
ph Q z	n V n
pr-	zy-	wa-	ra
ph @r	z V	v Q@	V
pra-	da
ph r Q	d V
pra-	desh
ph r V	d e S
pra-	do
ph r Q	d @U
pra-	kash
ph r Q	k Q S
pra-	sad
ph r {	s V d
pra-	ter
ph r eI	t @r
pra-	ther
ph r {	D @r
pra-	to
ph r Q	t @U
pra-	xis
ph r { k	s I s
pra-	ying
ph r eI	I N
prac-	ti-	ca-	ble
ph r { k	t I	k V	b V l
prac-	ti-	ca-	li-	ty
ph r { k	t I	k {	l I	t i:
prac-	ti-	cal
ph r { k	t I	k V l
prac-	ti-	ces
ph r { k	t I	s V z
prac-	ti-	cing
ph r { k	t I	s I N
prac-	ti-	tio-	ner
ph r { k	t I	S V	n @r
prac-	tical-	ly
ph r { k	t I k	l i:
prac-	tice
ph r { k	t I s
prac-	ticed
ph r { k	t I s t
prac-	titio-	ners
ph r { k	t I S	n @r z
prai-	rie
ph r e@	i:
prai-	ries
ph r eI	r i: z
prai-	rie's
ph r e@	i: z
prai-	ses
ph r eI	z V z
prai-	sing
ph r eI	z I N
praise
ph r eI z
praise-	wor-	thy
ph r eI z	w @r	D i:
praised
ph r eI z d
pran-	ces
ph r { n	s V z
pran-	cing
ph r { n	s I N
prance
ph r { n s
prank
ph r { N k
prank-	ster
ph r { N	k s t @r
pranks
ph r { N k s
prat-	fall
ph r { t	f O: l
prat-	falls
ph r { t	f O: l z
prat-	tle
ph r {	t V l
prats
ph r { t s
pratt
ph r { t
pratt-	ville
ph r { t	v I l
pratte
ph r { t
pratt's
ph r { t s
prav-	da
ph r { v	d V
prav-	da's
ph r { v	d V z
prawn
ph r O: n
prawns
ph r O: n z
pray
ph r eI
prayed
ph r eI d
prayer
ph r e@
prayer-	ful
ph r e@	f V l
prayers
ph r e@ z
prays
ph r eI z
pre
ph r i:
pre-	a-	do-	le-	scence
ph r i:	{	d V	l e	s V s
pre-	a-	do-	le-	scent
ph r i:	{	d V	l e	s V n t
pre-	am-	ble
ph r i:	{ m	b V l
pre-	ar-	range
ph r i:	@r	eI n dZ
pre-	ar-	ranged
ph r i:	@r	eI n dZ d
pre-	ble
ph r e	b V l
pre-	ca-	ri-	ous
ph r i:	k e@	i:	V s
pre-	ca-	ri-	ous-	ly
ph r I	k e@	i:	V s	l i:
pre-	cam-	bri-	an
ph r i:	k { m	b r i:	V n
pre-	can-	ce-	rous
ph r i:	k { n	s @r	V s
pre-	cast
ph r i:	k { s t
pre-	cau-	tio-	na-	ry
ph r I	k O:	S V	n e@	i:
pre-	cau-	tion
ph r i:	k O:	S V n
pre-	cau-	tions
ph r i:	k O:	S V n z
pre-	ce-	ded
ph r V	s i:	d I d
pre-	ce-	dence
ph r e	s I	d e n s
pre-	ce-	dent
ph r e	s I	d e n t
pre-	ce-	dents
ph r e	s I	d e n t s
pre-	ce-	ding
ph r i:	s i:	d I N
pre-	cede
ph r V	s i: d
pre-	cedes
ph r V	s i: d z
pre-	cee-	ding
ph r V	s i:	d I N
pre-	cept
ph r i:	s e p t
pre-	cepts
ph r i:	s e p t s
pre-	ces-	sion
ph r i:	s e	S V n
pre-	ci-	pi-	ta-	ted
ph r V	s I	p I	t eI	t I d
pre-	ci-	pi-	ta-	ting
ph r V	s I	p I	t eI	t I N
pre-	ci-	pi-	ta-	tion
ph r V	s I	p I	t eI	S V n
pre-	ci-	pi-	tate
ph r V	s I	p I	t eI t
pre-	ci-	pi-	tous
ph r V	s I	p I	t V s
pre-	ci-	pi-	tous-	ly
ph r i:	s I	p I	t V s	l i:
pre-	ci-	pice
ph r e	s I	p I s
pre-	ci-	sion
ph r i:	s I	Z V n
pre-	cinct
ph r i:	s I N k t
pre-	cincts
ph r i:	s I N k t s
pre-	cious
ph r e	S V s
pre-	cis
ph r eI	s i:
pre-	cise
ph r V	s aI s
pre-	cise-	ly
ph r V	s aI s	l i:
pre-	cli-	ni-	cal
ph r i: k	l I	n I	k V l
pre-	clu-	ded
ph r I k	l u:	d V d
pre-	clu-	ding
ph r I k	l u:	d I N
pre-	clu-	sion
ph r I k	l u:	Z V n
pre-	clude
ph r I k	l u: d
pre-	cludes
ph r I k	l u: d z
pre-	co-	cious
ph r I	k @U	S V s
pre-	con-	ceive
ph r i:	k V n	s i: v
pre-	con-	ceived
ph r i:	k V n	s i: v d
pre-	con-	cep-	tion
ph r i:	k V n	s e p	S V n
pre-	con-	cep-	tions
ph r i:	k V n	s e p	S V n z
pre-	con-	di-	tion
ph r i:	k V n	d I	S V n
pre-	con-	di-	tions
ph r i:	k V n	d I	S V n z
pre-	cook
ph r i:	k U k
pre-	cooked
ph r i:	k U k t
pre-	crash
ph r i: k	r { S
pre-	de-	ces-	sor
ph r e	d V	s e	s @r
pre-	de-	ces-	sors
ph r e	d V	s e	s @r z
pre-	de-	ces-	sor's
ph r e	d V	s e	s @r z
pre-	de-	ter-	mine
ph r i:	d i:	t @r	m I n
pre-	de-	ter-	mined
ph r i:	d i:	t @r	m I n d
pre-	des-	ti-	na-	tion
ph r i:	d e s	t I	n eI	S V n
pre-	des-	tine
ph r i:	d e s	t I n
pre-	des-	tined
ph r i:	d e s	t I n d
pre-	di-	ca-	ment
ph r V	d I	k V	m V n t
pre-	di-	ca-	ments
ph r V	d I	k V	m V n t s
pre-	di-	ca-	ted
ph r e	d I	k eI	t I d
pre-	di-	cate
ph r e	d I	k eI t
pre-	di-	cates
ph r e	d I	k eI t s
pre-	di-	lec-	tion
ph r e	d I	l e k	S V n
pre-	di-	lec-	tions
ph r e	d I	l e k	S V n z
pre-	dic-	ta-	bi-	li-	ty
ph r V	d I k	t V	b I	l V	t i:
pre-	dic-	ta-	ble
ph r V	d I k	t V	b V l
pre-	dic-	tab-	ly
ph r V	d I k	t V b	l i:
pre-	dic-	ted
ph r V	d I k	t V d
pre-	dic-	ting
ph r V	d I k	t I N
pre-	dic-	tion
ph r i:	d I k	S V n
pre-	dic-	tions
ph r i:	d I k	S V n z
pre-	dic-	tive
ph r V	d I k	t I v
pre-	dic-	tor
ph r V	d I k	t @r
pre-	dic-	tors
ph r V	d I k	t @r z
pre-	dict
ph r V	d I k t
pre-	dicts
ph r V	d I k t s
pre-	dis-	po-	si-	tion
ph r i:	d I s	p V	z I	S V n
pre-	dis-	po-	si-	tions
ph r i:	d I s	p V	z I	S V n z
pre-	dis-	po-	sing
ph r i:	d I s	p @U	z I N
pre-	dis-	pose
ph r i:	d I s	p @U z
pre-	dis-	posed
ph r i:	d I s	p @U z d
pre-	do-	mi-	na-	ted
ph r V	d Q	m V	n eI	t V d
pre-	do-	mi-	na-	ting
ph r V	d Q	m V	n eI	t I N
pre-	do-	mi-	nance
ph r V	d Q	m V	n V n s
pre-	do-	mi-	nant
ph r V	d Q	m V	n V n t
pre-	do-	mi-	nant-	ly
ph r V	d Q	m V	n V n	t l i:
pre-	do-	mi-	nate
ph r V	d Q	m V	n eI t
pre-	do-	mi-	nates
ph r V	d Q	m V	n eI t s
pre-	e-	lec-	tion
ph r i:	V	l e k	S V n
pre-	e-	mi-	nence
ph r i:	e	m I	n e n s
pre-	e-	mi-	nent
ph r i:	e	m I	n e n t
pre-	e-	xis-	ted
ph r i:	I g	z I s	t V d
pre-	e-	xis-	ting
ph r i:	I g	z I s	t I N
pre-	e-	xist
ph r i:	I g	z I s t
pre-	e-	xists
ph r i:	I g	z I s t s
pre-	emp-	ted
ph r i:	e m	p t V d
pre-	emp-	ting
ph r i:	e m	p t I N
pre-	emp-	tion
ph r i:	e m	p S V n
pre-	emp-	tive
ph r i:	e m	p t I v
pre-	emp-	tive-	ly
ph r i:	e m	p t I v	l i:
pre-	empt
ph r i:	e m p t
pre-	fab
ph r i:	f { b
pre-	fab-	ri-	ca-	ted
ph r i:	f { b	r I	k eI	t V d
pre-	fab-	ri-	ca-	tion
ph r i:	f { b	r I	k eI	S V n
pre-	fab-	ri-	cate
ph r i:	f { b	r I	k eI t
pre-	fabs
ph r i:	f { b z
pre-	face
ph r e	f V s
pre-	faced
ph r e	f V s t
pre-	fe-	ra-	ble
ph r e	f @r	V	b V l
pre-	fe-	rab-	ly
ph r e	f @r	V b	l i:
pre-	fe-	ren-	ces
ph r e	f @r	V n	s V z
pre-	fe-	ren-	tial
ph r e	f @r	e n	tS V l
pre-	fe-	ren-	tial-	ly
ph r e	f @r	e n	tS V	l i:
pre-	fe-	rence
ph r e	f @r	V n s
pre-	fec-	tu-	ral
ph r i:	f e k	tS @r	V l
pre-	fec-	ture
ph r i:	f e k	tS @r
pre-	fect
ph r i:	f e k t
pre-	fer
ph r V	f @r
pre-	fer-	ring
ph r V	f @r	I N
pre-	fered
ph r V	f @r d
pre-	ferred
ph r V	f @r d
pre-	fers
ph r V	f @r z
pre-	fix
ph r i:	f I k s
pre-	fron-	tal
ph r i: f	r V n	t V l
pre-	his-	to-	ric
ph r i:	h I s	t O@	I k
pre-	ho-	li-	day
ph r i:	h O:	l I	d eI
pre-	ig-	ni-	tion
ph r i:	V g	n I	S V n
pre-	ju-	di-	ces
ph r e	dZ V	d V	s V z
pre-	ju-	di-	cial
ph r e	dZ V	d V	S V l
pre-	ju-	di-	cing
ph r e	dZ V	d V	s I N
pre-	ju-	dice
ph r e	dZ V	d V s
pre-	ju-	diced
ph r e	dZ V	d V s t
pre-	judg-	ment
ph r i:	dZ V dZ	m V n t
pre-	judge
ph r i:	dZ V dZ
pre-	judged
ph r i:	dZ V dZ d
pre-	kin-	der-	gar-	ten
ph r i:	k I n	d @r	g Q	d V n
pre-	late
ph r e	l V t
pre-	lates
ph r e	l V t s
pre-	li-	mi-	na-	ri-	ly
ph r V	l I	m I	n e@	V	l i:
pre-	li-	mi-	na-	ries
ph r V	l I	m I	n e@	i: z
pre-	li-	mi-	na-	ry
ph r V	l I	m I	n e@	i:
pre-	lim
ph r V	l I m
pre-	lims
ph r i:	l I m z
pre-	lude
ph r eI	l u: d
pre-	ludes
ph r eI	l u: d z
pre-	ma-	ri-	tal
ph r i:	m e@	I	t V l
pre-	ma-	rin
ph r e	m @r	I n
pre-	ma-	ture
ph r i:	m V	tS U@
pre-	ma-	ture-	ly
ph r i:	m V	tS U@	l i:
pre-	mar-	ket
ph r i:	m Q@	k V t
pre-	mi-	ses
ph r e	m I	s V z
pre-	mi-	um
ph r i:	m i:	V m
pre-	mi-	ums
ph r i:	m i:	V m z
pre-	mie-	ring
ph r e	m I@	I N
pre-	mier
ph r e	m I@
pre-	mier-	ship
ph r e	m I@	S I p
pre-	miere
ph r e	m I@
pre-	miered
ph r e	m I@ d
pre-	mieres
ph r e	m I@ z
pre-	miers
ph r e	m I@ z
pre-	mier's
ph r e	m I@ z
pre-	mise
ph r e	m I s
pre-	mised
ph r e	m I s t
pre-	mo-	dern
ph r i:	m O:	d @r n
pre-	mo-	ni-	tion
ph r e	m V	n I	S V n
pre-	mo-	ni-	to-	ry
ph r V	m V	n V	t @r	i:
pre-	na-	tal
ph r i:	n eI	t V l
pre-	nup-	tial
ph r i:	n V p	S V l
pre-	oc-	cu-	pa-	tion
ph r i:	Q k	j V	p eI	S V n
pre-	oc-	cu-	pa-	tions
ph r i:	Q k	j V	p eI	S V n z
pre-	oc-	cu-	pied
ph r i:	Q k	j V	p aI d
pre-	oc-	cu-	pies
ph r i:	Q k	j V	p aI z
pre-	oc-	cu-	py
ph r i:	Q k	j V	p aI
pre-	or-	dain
ph r i:	O@	d eI n
pre-	or-	dained
ph r i:	O@	d eI n d
pre-	pa-	ra-	tion
ph r e	p @r	eI	S V n
pre-	pa-	ra-	tions
ph r e	p @r	eI	S V n z
pre-	pa-	ra-	to-	ry
ph r e	p e@	V	t O@	i:
pre-	pa-	red-	ness
ph r i:	p e@	V d	n V s
pre-	pa-	rer
ph r i:	p e@	@r
pre-	pa-	rers
ph r i:	p e@	@r z
pre-	pa-	ring
ph r i:	p e@	I N
pre-	pac-	kage
ph r i:	p {	k V dZ
pre-	pac-	kaged
ph r i:	p {	k V dZ d
pre-	paid
ph r i:	p eI d
pre-	pare
ph r i:	p e@
pre-	pared
ph r i:	p e@ d
pre-	pares
ph r i:	p e@ z
pre-	pay
ph r i:	p eI
pre-	pay-	ing
ph r i:	p eI	I N
pre-	pay-	ment
ph r i:	p eI	m V n t
pre-	pay-	ments
ph r i:	p eI	m V n t s
pre-	plan-	ning
ph r i: p	l {	n I N
pre-	ponde-	rance
ph r i:	p Q n	d r V n s
pre-	pos-	te-	rous
ph r V	p Q s	t @r	V s
pre-	re-	cor-	ded
ph r i:	r i:	k O@	d V d
pre-	re-	cord
ph r i:	r i:	k O@ d
pre-	re-	qui-	site
ph r i:	r e k	w I	z I t
pre-	re-	qui-	sites
ph r i:	r e k	w I	z I t s
pre-	ro-	ga-	tive
ph r I@	Q	g V	t I v
pre-	ro-	ga-	tives
ph r I@	Q	g V	t I v z
pre-	sa-	ges
ph r e	s I	dZ V z
pre-	sa-	ging
ph r e	s I	dZ I N
pre-	sage
ph r e	s I dZ
pre-	saged
ph r e	s I dZ d
pre-	sale
ph r i:	s eI l
pre-	schoo-	ler
ph r i: s	k u:	l @r
pre-	schoo-	lers
ph r i: s	k u:	l @r z
pre-	school
ph r i: s	k u: l
pre-	schools
ph r i: s	k u: l z
pre-	sci-	ence
ph r i:	S i:	V n s
pre-	sci-	ent
ph r e	s i:	V n t
pre-	scott
ph r e s	k Q t
pre-	scri-	ber
ph r i: s	k r aI	b @r
pre-	scri-	bers
ph r i: s	k r aI	b @r z
pre-	scri-	bing
ph r i: s	k r aI	b I N
pre-	scribe
ph r V s	k r aI b
pre-	scribed
ph r i: s	k r aI b d
pre-	scribes
ph r i: s	k r aI b z
pre-	scrip-	tion
ph r V s	k r I p	S V n
pre-	scrip-	tions
ph r V s	k r I p	S V n z
pre-	sen-	ces
ph r e	z V n	s V z
pre-	sen-	ta-	ble
ph r V	z e n	t V	b V l
pre-	sen-	ta-	tion
ph r e	z V n	t eI	S V n
pre-	sen-	ta-	tions
ph r e	z V n	t eI	S V n z
pre-	sen-	ted
ph r i:	z e n	t V d
pre-	sen-	ter
ph r e	z V n	t @r
pre-	sen-	ters
ph r e	z V n	t @r z
pre-	sen-	ting
ph r V	z e n	t I N
pre-	sence
ph r e	z V n s
pre-	sent
ph r e	z V n t
pre-	sent-	ly
ph r e	z V n	t l i:
pre-	sent-	ment
ph r i:	z e n	t m V n t
pre-	sents
ph r e	z V n t s
pre-	ser-	va-	tio-	nist
ph r e	z @r	v eI	S V	n I s t
pre-	ser-	va-	tio-	nists
ph r e	z @r	v eI	S V	n I s t s
pre-	ser-	va-	tion
ph r e	z @r	v eI	S V n
pre-	ser-	va-	tive
ph r i:	z @r	v V	t I v
pre-	ser-	va-	tives
ph r V	z @r	v V	t I v z
pre-	ser-	ver
ph r i:	z @r	v @r
pre-	ser-	vers
ph r i:	z @r	v @r z
pre-	ser-	ving
ph r V	z @r	v I N
pre-	serve
ph r V	z @r v
pre-	served
ph r V	z @r v d
pre-	serves
ph r V	z @r v z
pre-	set
ph r i:	s e t
pre-	si-	ded
ph r V	z aI	d V d
pre-	si-	den-	cies
ph r e	z I	d e n	s i: z
pre-	si-	den-	cy
ph r e	z I	d e n	s i:
pre-	si-	den-	cy's
ph r e	z I	d e n	s i: z
pre-	si-	den-	tial
ph r e	z I	d e n	tS V l
pre-	si-	den-	tial-	ly
ph r e	s I	d e n	tS V	l i:
pre-	si-	dent
ph r e	z I	d e n t
pre-	si-	dents
ph r e	z I	d e n t s
pre-	si-	dent's
ph r e	z I	d e n t s
pre-	si-	dents'
ph r e	z I	d e n t s
pre-	si-	di-	o
ph r V	s I	d i:	@U
pre-	si-	di-	um
ph r V	s I	d i:	V m
pre-	si-	ding
ph r V	z aI	d I N
pre-	side
ph r V	z aI d
pre-	sides
ph r V	z aI d z
pre-	su-	mab-	ly
ph r V	z u:	m V b	l i:
pre-	su-	ming
ph r V	z u:	m I N
pre-	sume
ph r V	z u: m
pre-	sumed
ph r V	z u: m d
pre-	sumes
ph r V	z u: m z
pre-	sump-	tion
ph r V	z V m	p S V n
pre-	sump-	tions
ph r V	z V m	p S V n z
pre-	sump-	tive
ph r i:	z V m	p t I v
pre-	sump-	tu-	ous
ph r V	z V m	p tS V	w V s
pre-	sup-	po-	ses
ph r i:	s V	p @U	z V z
pre-	sup-	po-	si-	tion
ph r i:	s V	p V	z I	S V n
pre-	sup-	pose
ph r i:	s V	p @U z
pre-	tax
ph r i:	t { k s
pre-	teen
ph r i:	t i: n
pre-	teens
ph r i:	t i: n z
pre-	ten-	ded
ph r i:	t e n	d V d
pre-	ten-	der
ph r i:	t e n	d @r
pre-	ten-	ders
ph r i:	t e n	d @r z
pre-	ten-	ding
ph r i:	t e n	d I N
)"
R"(pre-	ten-	ses
ph r i:	t e n	s V z
pre-	ten-	sion
ph r i:	t e n	S V n
pre-	ten-	sions
ph r V	t e n	S V n z
pre-	ten-	tious
ph r i:	t e n	S V s
pre-	tend
ph r i:	t e n d
pre-	tends
ph r i:	t e n d z
pre-	tense
ph r i:	t e n s
pre-	term
ph r i:	t @r m
pre-	tri-	al
ph r i: t	r aI	V l
pre-	va-	lence
ph r e	v V	l V n s
pre-	va-	lent
ph r e	v V	l V n t
pre-	vai-	ling
ph r I	v eI	l I N
pre-	vail
ph r I	v eI l
pre-	vailed
ph r I	v eI l d
pre-	vails
ph r I	v eI l z
pre-	ven-	ta-	ble
ph r I	v e n	t V	b V l
pre-	ven-	ta-	tive
ph r i:	v e n	t V	t I v
pre-	ven-	ta-	tives
ph r i:	v e n	t V	t I v z
pre-	ven-	ted
ph r I	v e n	t V d
pre-	ven-	ting
ph r I	v e n	t I N
pre-	ven-	tion
ph r i:	v e n	S V n
pre-	ven-	tive
ph r I	v e n	t I v
pre-	vent
ph r I	v e n t
pre-	vents
ph r I	v e n t s
pre-	vi-	ous
ph r i:	v i:	V s
pre-	vi-	ous-	ly
ph r i:	v i:	V s	l i:
pre-	view
ph r i: v	j u:
pre-	view-	ing
ph r i: v	j u:	I N
pre-	viewed
ph r i: v	j u: d
pre-	views
ph r i: v	j u: z
pre-	vin
ph r e	v I n
pre-	vost
ph r eI	v @U s t
pre-	war
ph r i:	w O@
pre-	wett
ph r u:	e t
)"