R"(eu-	phra-	tes
j u: f	r eI	t i: z
eu-	ra-	sia
j U@	eI	Z V
eu-	ra-	sian
j U@	eI	Z V n
eu-	re-	ka
j U@	i:	k V
eu-	ro
j u:	r @U
eu-	ro-	bond
j u:	r @U	b Q n d
eu-	ro-	bonds
j u:	r @U	b Q n d z
eu-	ro-	dol-	lar
j u:	r @U	d Q	l @r
eu-	ro-	dol-	lars
j u:	r @U	d Q	l @r z
eu-	ro-	figh-	ter
j u:	r @U	f aI	t @r
eu-	ro-	mar-	ket
j u:	r @U	m Q@	k V t
eu-	ro-	mar-	kets
j u:	r @U	m Q@	k V t s
eu-	ro-	pa
j U@	@U	p V
eu-	ro-	pe-	an
j U@	V	p i:	V n
eu-	ro-	pe-	ans
j U@	V	p i:	V n z
eu-	ro-	phile
j U@	@U	f aI l
eu-	ro-	philes
j U@	@U	f aI l z
eu-	ro-	pi-	um
j U@	@U	p i:	V m
eu-	ro-	tun-	nel
j u:	r @U	t V	n V l
eu-	ro-	tun-	nel's
j U@	@U	t V	n V l z
eu-	roc-	rat
j u:	r V k	r { t
eu-	roc-	rats
j u:	r V k	r { t s
eu-	rope
j U@	V p
eu-	rope's
j U@	V p s
eu-	ros-	ter-	ling
j u:	r @U s	t @r	l I N
eu-	se-	bi-	o
j u:	s i:	b i:	@U
eu-	sta-	chi-	an
j u: s	t eI	k i:	V n
eu-	sta-	cia
j u: s	t Q	tS V
eu-	stace
j u: s	t V s
eu-	tha-	na-	sia
j u:	T V	n eI	Z V
eu-	tha-	na-	sia's
j u:	T V	n eI	Z V z
eu-	tha-	nize
j u:	T V	n aI z
euc-	le-	a
j u: k	l i:	V
euc-	lid
j u: k	l I d
eure
@r
eus-	tis
j u: s	t I s
ev
e v
eve
i: v
eve-	ning
i: v	n I N
eve-	nings
i: v	n I N z
eve-	ning's
i: v	n I N z
eve-	ry-	bo-	dy
e v	r i:	b Q	d i:
eve-	ry-	bo-	dy's
e v	r i:	b Q	d i: z
eve-	ry-	day
e v	r i:	d eI
eve-	ry-	man
e v	r i:	m V n
eve-	ry-	man's
e v	r i:	m V n z
eve-	ry-	one
e v	r i:	w V n
eve-	ry-	one's
e v	r i:	w V n z
eve-	ry-	place
e v	r i: p	l eI s
eve-	ry-	thing
e v	r i:	T I N
eve-	ry-	where
e v	r i:	w e@
eves
i: v z
ewe
j u:
ewes
j u: z
ex
e k s
ex-	boy-	friend
e k	s b OI f	r e n d
ex-	ca-	li-	bur
e k	s k {	l I	b @r
ex-	ca-	va-	ted
e k	s k V	v eI	t V d
ex-	ca-	va-	ting
e k	s k V	v eI	t I N
ex-	ca-	va-	tion
e k	s k V	v eI	S V n
ex-	ca-	va-	tions
e k	s k V	v eI	S V n z
ex-	ca-	va-	tor
e k	s k V	v eI	t @r
ex-	ca-	va-	tors
e k	s k V	v eI	t @r z
ex-	ca-	vate
e k	s k V	v eI t
ex-	ced-	rin
e k	s e d	r I n
ex-	cee-	ded
I k	s i:	d V d
ex-	cee-	ding
I k	s i:	d I N
ex-	cee-	ding-	ly
I k	s i:	d I N	l i:
ex-	ceed
I k	s i: d
ex-	ceeds
I k	s i: d z
ex-	cel
I k	s e l
ex-	cel-	lence
e k	s V	l V n s
ex-	cel-	lent
e k	s V	l V n t
ex-	cel-	lent-	ly
e k	s V	l V n	t l i:
ex-	cel-	ling
I k	s e	l I N
ex-	cel-	si-	or
I k	s e l	s i:	@r
ex-	celled
I k	s e l d
ex-	cels
I k	s e l z
ex-	cep-	ted
I k	s e p	t V d
ex-	cep-	ting
e k	s e p	t I N
ex-	cep-	tio-	nal
I k	s e p	S V	n V l
ex-	cep-	tio-	nal-	ly
I k	s e p	S V	n V	l i:
ex-	cep-	tion
I k	s e p	S V n
ex-	cep-	tions
I k	s e p	S V n z
ex-	cept
I k	s e p t
ex-	cerp-	ted
e k	s @r p	t I d
ex-	cerpt
e k	s @r p t
ex-	cerpts
e k	s @r p t s
ex-	ces-	ses
e k	s e	s V z
ex-	ces-	sive
I k	s e	s I v
ex-	ces-	sive-	ly
I k	s e	s I v	l i:
ex-	cess
e k	s e s
ex-	chan-	gea-	ble
I k	s tS eI n	dZ V	b V l
ex-	chan-	ger
I k	s tS eI n	dZ @r
ex-	chan-	gers
I k	s tS eI n	dZ @r z
ex-	chan-	ges
I k	s tS eI n	dZ V z
ex-	chan-	ging
I k	s tS eI n	dZ I N
ex-	change
I k	s tS eI n dZ
ex-	changed
I k	s tS eI n dZ d
ex-	che-	quer
e k	s tS e	k @r
ex-	ci-	mer
e k	s I	m @r
ex-	ci-	ses
e k	s aI	z V z
ex-	ci-	sion
I k	s I	Z V n
ex-	ci-	ta-	ble
I k	s aI	t V	b V l
ex-	ci-	ta-	tion
e k	s aI	t eI	S V n
ex-	ci-	ted
I k	s aI	t V d
ex-	ci-	ted-	ly
I k	s aI	t V d	l i:
ex-	ci-	ting
I k	s aI	t I N
ex-	cise
e k	s aI s
ex-	cised
e k	s aI z d
ex-	cite
I k	s aI t
ex-	cite-	ment
I k	s aI t	m V n t
ex-	cites
I k	s aI t s
ex-	co-	ri-	a-	ted
e k	s k O@	i:	eI	t V d
ex-	co-	ri-	a-	ting
e k	s k O@	i:	eI	t I N
ex-	co-	ri-	a-	tion
e k	s k O@	i:	eI	S V n
ex-	co-	ri-	ate
e k	s k O@	i:	eI t
ex-	com-	mu-	ni-	ca-	ted
e k	s k V m	j u:	n V	k eI	t V d
ex-	com-	mu-	ni-	ca-	tion
e k	s k V m	j u:	n V	k eI	S V n
ex-	com-	mu-	ni-	cate
e k	s k V m	j u:	n V	k eI t
ex-	cu-	sa-	ble
I k	s k j u:	z V	b V l
ex-	cu-	ses
I k	s k j u:	s V z
ex-	cu-	sing
I k	s k j u:	z I N
ex-	cul-	pa-	to-	ry
e k	s k V l	p V	t O@	i:
ex-	cul-	pate
e k	s k V l	p eI t
ex-	cur-	sion
I k	s k @r	Z V n
ex-	cur-	sions
I k	s k @r	Z V n z
ex-	cuse
I k	s k j u: s
ex-	cused
I k	s k j u: z d
ex-	fo-	li-	a-	tion
e k	s f @U	l i:	eI	S V n
ex-	fo-	li-	ate
e k	s f @U	l i:	eI t
ex-	ha-	la-	tion
e k	s h V	l eI	S V n
ex-	hale
e k	s h eI l
ex-	line
e k	s l aI n
ex-	pan-	da-	ble
I k	s p { n	d V	b V l
ex-	pan-	ded
I k	s p { n	d V d
ex-	pan-	ding
I k	s p { n	d I N
ex-	pan-	ses
I k	s p { n	s V z
ex-	pan-	sio-	na-	ry
I k	s p { n	S V	n e@	i:
ex-	pan-	sio-	ni-	sm
I k	s p { n	tS V	n I	z V m
ex-	pan-	sio-	nist
I k	s p { n	tS V	n I s t
ex-	pan-	sion
I k	s p { n	S V n
ex-	pan-	sions
I k	s p { n	S V n z
ex-	pan-	sion's
I k	s p { n	tS V n z
ex-	pan-	sive
I k	s p { n	s I v
ex-	pand
I k	s p { n d
ex-	pands
I k	s p { n d z
ex-	panse
I k	s p { n s
ex-	pat-	ri-	a-	tion
e k	s p eI t	r i:	eI	S V n
ex-	pat-	ri-	ate
e k	s p eI t	r i:	eI t
ex-	pat-	ri-	ates
e k	s p eI t	r i:	eI t s
ex-	pe-	di-	en-	cy
I k	s p i:	d i:	V n	s i:
ex-	pe-	di-	ence
I k	s p i:	d i:	V n s
ex-	pe-	di-	ent
I k	s p i:	d i:	V n t
ex-	pe-	di-	ted
e k	s p V	d aI	t V d
ex-	pe-	di-	ting
e k	s p V	d aI	t I N
ex-	pe-	di-	tio-	na-	ry
e k	s p V	d I	S V	n e@	i:
ex-	pe-	di-	tion
e k	s p V	d I	S V n
ex-	pe-	di-	tions
e k	s p V	d I	S V n z
ex-	pe-	di-	tious
e k	s p V	d I	S V s
ex-	pe-	di-	tious-	ly
e k	s p V	d I	S V s	l i:
ex-	pe-	dite
e k	s p V	d aI t
ex-	pe-	ri-	en-	ces
I k	s p I@	i:	V n	s V z
ex-	pe-	ri-	en-	cing
I k	s p I@	i:	V n	s I N
ex-	pe-	ri-	en-	tial
e k	s p e@	i:	e n	S V l
ex-	pe-	ri-	ence
I k	s p I@	i:	V n s
ex-	pe-	ri-	enced
I k	s p I@	i:	V n s t
ex-	pe-	ri-	men-	ta-	list
I k	s p e@	I	m e n	t V	l I s t
ex-	pe-	ri-	men-	ta-	tion
I k	s p e@	I	m e n	t eI	S V n
ex-	pe-	ri-	men-	tal
I k	s p e@	I	m e n	t V l
ex-	pe-	ri-	men-	tal-	ly
I k	s p e@	I	m e n	t V	l i:
ex-	pe-	ri-	men-	ted
I k	s p e@	I	m e n	t I d
ex-	pe-	ri-	men-	ter
I k	s p e@	I	m e n	t @r
ex-	pe-	ri-	men-	ters
I k	s p e@	I	m e n	t @r z
ex-	pe-	ri-	men-	ting
e k	s p e@	I	m e n	t I N
ex-	pe-	ri-	ment
I k	s p e@	I	m e n t
ex-	pe-	ri-	ments
I k	s p e@	I	m e n t s
ex-	pe-	ri-	ment's
I k	s p e@	I	m e n t s
ex-	pec-	ta-	tion
e k	s p e k	t eI	S V n
ex-	pec-	ta-	tions
e k	s p e k	t eI	S V n z
ex-	pec-	tan-	cies
I k	s p e k	t V n	s i: z
ex-	pec-	tan-	cy
I k	s p e k	t V n	s i:
ex-	pec-	tant
I k	s p e k	t V n t
ex-	pec-	ted
I k	s p e k	t V d
ex-	pec-	ting
I k	s p e k	t I N
ex-	pec-	to-	rant
I k	s p e k	t @r	V n t
ex-	pect
I k	s p e k t
ex-	pects
I k	s p e k t s
ex-	pel
I k	s p e l
ex-	pel-	ling
I k	s p e	l I N
ex-	pelled
I k	s p e l d
ex-	pen-	da-	ble
I k	s p e n	d V	b V l
ex-	pen-	ded
I k	s p e n	d V d
ex-	pen-	di-	ture
I k	s p e n	d I	tS @r
ex-	pen-	di-	tures
I k	s p e n	d I	tS @r z
ex-	pen-	ding
e k	s p e n	d I N
ex-	pen-	ses
I k	s p e n	s V z
ex-	pen-	sing
I k	s p e n	s I N
ex-	pen-	sive
I k	s p e n	s I v
ex-	pen-	sive-	ly
e k	s p e n	s I v	l i:
ex-	pend
I k	s p e n d
ex-	pense
I k	s p e n s
ex-	per-	tise
e k	s p @r	t i: z
ex-	pert
e k	s p @r t
ex-	pert-	ly
e k	s p @r t	l i:
ex-	perts
e k	s p @r t s
ex-	pert's
e k	s p @r t s
ex-	pi-	ate
e k	s p i:	eI t
ex-	pi-	ra-	tion
e k	s p @r	eI	S V n
ex-	pi-	ra-	tions
e k	s p @r	eI	S V n z
ex-	pi-	ra-	to-	ry
I k	s p aI	r V	t O@	i:
ex-	pi-	res
I k	s p aI	@r z
ex-	pi-	ring
I k	s p aI	r I N
ex-	pi-	ry
e k	s p aI	r i:
ex-	pire
I k	s p aI r
ex-	pired
I k	s p aI r d
ex-	plain
I k	s p l eI n
ex-	po
e k	s p @U
ex-	po-	nen-	tial
e k	s p @U	n e n	tS V l
ex-	po-	nen-	tial-	ly
e k	s p @U	n e n	S V	l i:
ex-	po-	nent
e k	s p @U	n V n t
ex-	po-	nents
I k	s p @U	n V n t s
ex-	po-	ses
I k	s p @U	z V z
ex-	po-	si-	tion
e k	s p V	z I	S V n
ex-	po-	si-	tions
e k	s p V	z I	S V n z
ex-	po-	sing
I k	s p @U	z I N
ex-	po-	sure
I k	s p @U	Z @r
ex-	po-	sures
I k	s p @U	Z @r z
ex-	por-	ta-	ble
e k	s p O@	t V	b V l
ex-	por-	ted
I k	s p O@	t V d
ex-	por-	ter
I k	s p O@	t @r
ex-	por-	ters
I k	s p O@	t @r z
ex-	por-	ting
I k	s p O@	t I N
ex-	port
e k	s p O@ t
ex-	ports
e k	s p O@ t s
ex-	pos
e k	s p @U z
ex-	pose
I k	s p @U z
ex-	posed
I k	s p @U z d
ex-	poun-	ded
I k	s p aU n	d V d
ex-	poun-	ding
I k	s p aU n	d I N
ex-	pound
I k	s p aU n d
ex-	pounds
I k	s p aU n d z
ex-	pres-	ses
I k	s p r e	s V z
ex-	pres-	sing
I k	s p r e	s I N
ex-	pres-	sio-	ni-	sm
I k	s p r e	S V	n I	z V m
ex-	pres-	sio-	nis-	tic
I k	s p r e	S V	n I s	t I k
ex-	pres-	sio-	nist
I k	s p r e	S V	n I s t
ex-	pres-	sion
I k	s p r e	S V n
ex-	pres-	sion-	less
I k	s p r e	S V n	l V s
ex-	press
I k	s p r e s
ex-	pressed
I k	s p r e s t
ex-	pul-	sion
I k	s p V l	S V n
ex-	pul-	sions
I k	s p V l	S V n z
ex-	punge
I k	s p V n dZ
ex-	punged
I k	s p V n dZ d
ex-	qui-	site
e k	s k w I	z I t
ex-	qui-	site-	ly
e k	s k w I	z I t	l i:
ex-	tant
e k	s t V n t
ex-	te-	nu-	a-	ting
I k	s t e n	j u:	eI	t I N
ex-	te-	nu-	ate
I k	s t e n	j u:	eI t
ex-	te-	ri-	or
I k	s t I@	i:	@r
ex-	te-	ri-	ors
e k	s t I@	i:	@r z
ex-	ten-	da-	ble
e k	s t e n	d V	b V l
ex-	ten-	ded
I k	s t e n	d V d
ex-	ten-	der
e k	s t e n	d @r
ex-	ten-	ders
e k	s t e n	d @r z
ex-	ten-	di-	ble
e k	s t e n	d I	b V l
ex-	ten-	ding
I k	s t e n	d I N
ex-	ten-	sion
I k	s t e n	S V n
ex-	ten-	sions
I k	s t e n	S V n z
ex-	ten-	sive
I k	s t e n	s I v
ex-	ten-	sive-	ly
I k	s t e n	s I v	l i:
ex-	tend
I k	s t e n d
ex-	tends
I k	s t e n d z
ex-	tent
I k	s t e n t
ex-	ter-	mi-	na-	ted
I k	s t @r	m I	n eI	t V d
ex-	ter-	mi-	na-	ting
I k	s t @r	m I	n eI	t I N
ex-	ter-	mi-	na-	tion
I k	s t @r	m I	n eI	S V n
ex-	ter-	mi-	na-	tor
I k	s t @r	m I	n eI	t @r
ex-	ter-	mi-	na-	tors
I k	s t @r	m I	n eI	t @r z
ex-	ter-	mi-	nate
I k	s t @r	m I	n eI t
ex-	ter-	mi-	nates
I k	s t @r	m I	n eI t s
ex-	ter-	nal
I k	s t @r	n V l
ex-	ter-	nal-	ly
I k	s t @r	n V	l i:
ex-	tin-	gui-	sher
I k	s t I N	g w I	S @r
ex-	tin-	gui-	shers
I k	s t I N	g w I	S @r z
ex-	tin-	gui-	shing
I k	s t I N	g w I	S I N
ex-	tin-	guish
I k	s t I N	g w I S
ex-	tin-	guish-	ment
I k	s t I N	g w I S	m V n t
ex-	tin-	guished
I k	s t I N	g w I S t
ex-	tinc-	tion
I k	s t I N	k S V n
ex-	tinct
I k	s t I N k t
ex-	tir-	pate
e k	s t @r	p eI t
ex-	tol
I k	s t @U l
ex-	tol-	ling
I k	s t @U	l I N
ex-	tolled
I k	s t @U l d
ex-	tols
I k	s t @U l z
ex-	ton
e k	s t V n
ex-	tor-	ted
I k	s t O@	t V d
ex-	tor-	ting
I k	s t O@	t I N
ex-	tor-	tio-	nate
I k	s t O@	S V	n V t
ex-	tor-	tion
I k	s t O@	S V n
ex-	tort
I k	s t O@ t
ex-	xon
e k	s Q n
ex-	xon's
e k	s Q n z
exc-	la-	ma-	tion
e k	s k l V	m eI	S V n
exc-	la-	ma-	tion-	point
e k	s k l V	m eI	S V n	p OI n t
exc-	la-	ma-	tions
e k	s k l V	m eI	S V n z
exc-	lai-	ming
I k	s k l eI	m I N
exc-	laim
I k	s k l eI m
exc-	laimed
I k	s k l eI m d
exc-	laims
I k	s k l eI m z
exc-	lu-	da-	ble
I k	s k l u:	d V	b V l
exc-	lu-	ded
I k	s k l u:	d V d
exc-	lu-	ding
I k	s k l u:	d I N
exc-	lu-	si-	vi-	ty
e k	s k l u:	s I	v I	t i:
exc-	lu-	sio-	na-	ry
I k	s k l u:	Z V	n e@	i:
exc-	lu-	sion
I k	s k l u:	Z V n
exc-	lu-	sions
I k	s k l u:	Z V n z
exc-	lu-	sive
I k	s k l u:	s I v
exc-	lu-	sive-	ly
I k	s k l u:	s I v	l i:
exc-	lu-	sives
I k	s k l u:	s I v z
exc-	lude
I k	s k l u: d
exc-	ludes
I k	s k l u: d z
exc-	re-	ment
e k	s k r V	m V n t
exc-	re-	tion
I k	s k r i:	S V n
exc-	re-	to-	ry
e k	s k r V	t O@	i:
exc-	rete
I k	s k r i: t
exc-	ru-	ci-	a-	ting
I k	s k r u:	S i:	eI	t I N
exc-	ru-	ci-	a-	ting-	ly
e k	s k r u:	s i:	eI	t I N	l i:
excel-	len-	cies
e k	s l V n	s i: z
excel-	len-	cy
e k	s l V n	s i:
exp-	la-	na-	tion
e k	s p l V	n eI	S V n
exp-	la-	na-	tions
e k	s p l V	n eI	S V n z
exp-	la-	na-	to-	ry
I k	s p l {	n V	t O@	i:
exp-	lai-	na-	ble
I k	s p l eI	n V	b V l
exp-	lai-	ning
I k	s p l eI	n I N
exp-	lained
I k	s p l eI n d
exp-	lains
I k	s p l eI n z
exp-	le-	tive
e k	s p l V	t I v
exp-	le-	tives
e k	s p l V	t I v z
exp-	li-	ca-	tion
e k	s p l I	k eI	S V n
exp-	li-	cit
I k	s p l I	s I t
exp-	li-	cit-	ly
I k	s p l I	s I t	l i:
exp-	lo-	ded
I k	s p l @U	d V d
exp-	lo-	ding
I k	s p l @U	d I N
exp-	lo-	ra-	tion
e k	s p l @r	eI	S V n
exp-	lo-	ra-	tions
e k	s p l @r	eI	S V n z
exp-	lo-	ra-	tion's
e k	s p l @r	eI	S V n z
exp-	lo-	ra-	to-	ry
I k	s p l O@	V	t O@	i:
exp-	lo-	rer
I k	s p l O@	@r
exp-	lo-	rers
I k	s p l O@	@r z
exp-	lo-	ring
I k	s p l O@	I N
exp-	lo-	sion
I k	s p l @U	Z V n
exp-	lo-	sions
I k	s p l @U	Z V n z
exp-	lo-	sive
I k	s p l @U	s I v
exp-	lo-	sive-	ly
e k	s p l @U	s I v	l i:
exp-	lo-	sives
I k	s p l @U	s I v z
exp-	lode
I k	s p l @U d
exp-	lodes
I k	s p l @U d z
exp-	loi-	ta-	tion
e k	s p l OI	t eI	S V n
exp-	loi-	ta-	tive
e k	s p l OI	t V	t I v
exp-	loi-	ted
e k	s p l OI	t V d
exp-	loi-	ting
e k	s p l OI	t I N
exp-	loi-	tive
I k	s p l OI	t I v
exp-	loit
e k	s p l OI t
exp-	loits
e k	s p l OI t s
exp-	lore
I k	s p l O@
exp-	lored
I k	s p l O@ d
exp-	lores
I k	s p l O@ z
exp-	res-	si-	vi-	ty
e k	s p r e	s I	v I	t i:
exp-	res-	sions
I k	s p r e	S V n z
exp-	res-	sive
I k	s p r e	s I v
exp-	res-	so
I k	s p e	s @U
exp-	ress-	ly
e k	s p r e s	l i:
exp-	ress-	way
I k	s p r e s	w eI
exp-	rop-	ri-	a-	ted
e k	s p r @U p	r i:	eI	t V d
exp-	rop-	ri-	a-	tion
e k	s p r @U p	r i:	eI	S V n
exp-	rop-	ri-	a-	tions
e k	s p r @U p	r i:	eI	S V n z
exp-	rop-	ri-	ate
e k	s p r @U p	r i:	eI t
ext-	ra
e k	s t r V
ext-	ra-	cel-	lu-	lar-	ly
e k	s t r V	s e l	j V	l @r	l i:
ext-	ra-	cur-	ri-	cu-	lar
e k	s t r V	k @r	I k	j V	l @r
ext-	ra-	di-	ted
e k	s t r V	d aI	t V d
ext-	ra-	di-	ting
e k	s t r V	d aI	t I N
ext-	ra-	di-	tion
e k	s t r V	d I	S V n
ext-	ra-	dite
e k	s t r V	d aI t
ext-	ra-	ga-	lac-	tic
e k	s t r V	g V	l { k	t I k
ext-	ra-	le-	gal
e k	s t r V	l i:	g V l
ext-	ra-	ma-	ri-	tal
e k	s t r V	m e@	V	t V l
ext-	ra-	ne-	ous
e k	s t r eI	n i:	V s
ext-	ra-	or-	di-	naire
e k	s t r V	O@	d V	n e@
ext-	ra-	po-	la-	ted
I k	s t r {	p V	l eI	t V d
ext-	ra-	po-	la-	ting
I k	s t r {	p V	l eI	t I N
ext-	ra-	po-	la-	tion
I k	s t r {	p V	l eI	S V n
ext-	ra-	po-	late
I k	s t r {	p V	l eI t
ext-	ra-	va-	gan-	za
I k	s t r {	v V	g { n	z V
ext-	ra-	va-	gan-	zas
I k	s t r {	v V	g { n	z V z
ext-	ra-	va-	gance
I k	s t r {	v V	g V n s
ext-	ra-	va-	gant
I k	s t r {	v V	g V n t
ext-	ra-	va-	gant-	ly
e k	s t r {	v V	g V n	t l i:
ext-	rac-	ted
I k	s t r { k	t V d
ext-	rac-	ting
I k	s t r { k	t I N
ext-	rac-	tion
I k	s t r { k	S V n
ext-	rac-	tions
I k	s t r { k	S V n z
ext-	ract
I k	s t r { k t
ext-	racts
I k	s t r { k t s
ext-	re-	mi-	sm
e k	s t r e	m I	z V m
ext-	re-	mi-	ties
I k	s t r e	m I	t i: z
ext-	re-	mi-	ty
I k	s t r e	m I	t i:
ext-	re-	mist
I k	s t r i:	m I s t
ext-	re-	mists
I k	s t r i:	m I s t s
ext-	reme
I k	s t r i: m
ext-	reme-	ly
I k	s t r i: m	l i:
ext-	remes
I k	s t r i: m z
ext-	ri-	ca-	ted
e k	s t r I	k eI	t I d
ext-	ri-	cate
e k	s t r I	k eI t
ext-	rin-	sic
e k	s t r I n	s I k
ext-	ro-	ver-	ted
e k	s t r V	v @r	t V d
ext-	ro-	vert
e k	s t r V	v @r t
ext-	ru-	ded
I k	s t r u:	d V d
ext-	ru-	ding
I k	s t r u:	d I N
ext-	ru-	sion
I k	s t r u:	Z V n
ext-	rude
I k	s t r u: d
extra-	or-	di-	na-	ri-	ly
I k	s t r O@	d I	n e@	I	l i:
extra-	or-	di-	na-	ry
I k	s t r O@	d I	n e@	i:
ey-	die
eI	d i:
ey-	er
aI	@r
ey-	rie
e@	i:
eyde
eI d
eye
aI
eye-	ball
aI	b O: l
eye-	balls
aI	b O: l z
eye-	brow
aI b	r aU
eye-	brows
aI b	r aU z
eye-	drop
aI d	r Q p
eye-	drop-	per
aI d	r Q	p @r
eye-	drops
aI d	r Q p s
eye-	glas-	ses
aI g	l {	s V z
eye-	glass
aI g	l { s
eye-	ing
aI	I N
eye-	la-	shes
aI	l {	S V z
eye-	lash
aI	l { S
eye-	less
aI	l V s
eye-	let
aI	l V t
eye-	lets
aI	l V t s
eye-	li-	ner
aI	l aI	n @r
eye-	lid
aI	l I d
eye-	lids
aI	l I d z
eye-	like
aI	l aI k
eye-	piece
aI	p i: s
eye-	shade
aI	S eI d
eye-	sight
aI	s aI t
eye-	sore
aI	s O@
eye-	spot
aI s	p Q t
eye-	stone
aI s	t @U n
eye-	strain
aI s	t r eI n
eye-	wear
aI	w e@
eye-	wit-	nes-	ses
aI	w I t	n V	s V z
eye-	wit-	ness
aI	w I t	n V s
eyed
aI d
eyes
aI z
eye's
aI z
eyre
e@
ez-	ra
e z	r V
ez-	zo
e	z @U
f
e f
f-	m
e	f e m
f.
e f
fa-	ber
f eI	b @r
fa-	ber-	ge
f {	b @r	dZ eI
fa-	bi-	a-	no
f Q	b i:	Q	n @U
fa-	bi-	an
f eI	b i:	V n
fa-	bi-	o
f Q	b i:	@U
fa-	bien
f {	b i: n
fa-	ble
f eI	b V l
fa-	bled
f eI	b V l d
fa-	bles
f eI	b V l z
fa-	bre
f eI	b @r
fa-	bu-	lous
f { b	j V	l V s
fa-	bu-	lous-	ly
f { b	j u:	l V s	l i:
fa-	cade
f V	s Q d
fa-	cades
f V	s Q d z
fa-	ce-	ted
f {	s V	t V d
fa-	ce-	tious
f V	s i:	S V s
fa-	ce-	tious-	ly
f V	s i:	S V s	l i:
fa-	cer
f eI	s @r
fa-	ces
f eI	s V z
fa-	cet
f {	s V t
fa-	cets
f {	s V t s
fa-	cet's
f {	s V t s
fa-	ci-	li-	ta-	ted
f V	s I	l V	t eI	t V d
fa-	ci-	li-	ta-	ting
f V	s I	l V	t eI	t I N
)"
R"(fa-	ci-	li-	ta-	tion
f V	s I	l V	t eI	S V n
fa-	ci-	li-	ta-	tor
f V	s I	l V	t eI	t @r
fa-	ci-	li-	ta-	tors
f V	s I	l V	t eI	t @r z
fa-	ci-	li-	ta-	tor's
f V	s I	l V	t eI	t @r z
fa-	ci-	li-	tate
f V	s I	l V	t eI t
fa-	ci-	li-	tates
f V	s I	l V	t eI t s
fa-	ci-	li-	ties
f V	s I	l V	t i: z
fa-	ci-	li-	ty
f V	s I	l V	t i:
fa-	ci-	li-	ty's
f V	s I	l V	t i: z
fa-	cial
f eI	S V l
fa-	cials
f eI	S V l z
fa-	cie
f eI	s i:
fa-	cile
f {	s I l
fa-	cing
f eI	s I N
fa-	cings
f eI	s I N z
fa-	cul-	ta-	tive
f {	k V l	t eI	t I v
fa-	cul-	ties
f {	k V l	t i: z
fa-	cul-	ty
f {	k V l	t i:
fa-	ded
f eI	d V d
fa-	den
f eI	d V n
fa-	der
f eI	d @r
fa-	ding
f eI	d I N
fa-	gan
f eI	g V n
fa-	gen
f {	g V n
fa-	ger
f eI	g @r
fa-	gin
f eI	g I n
fa-	hey
f {	h i:
fa-	hy
f eI	h i:
fa-	jar-	do
f Q	j Q@	d @U
fa-	ji-	ta
f V	dZ i:	t V
fa-	ji-	tas
f V	dZ i:	t V z
fa-	ker
f eI	k @r
fa-	kers
f eI	k @r z
fa-	king
f eI	k I N
fa-	la-	fel
f V	l Q	f V l
fa-	ma
f Q	m V
fa-	mi-	li-	ari-	ty
f V	m I l	j e@	V	t i:
fa-	mi-	li-	arize
f V	m I l	j @r	aI z
fa-	mi-	li-	arized
f V	m I l	j @r	aI z d
fa-	mi-	lial
f V	m I l	j V l
fa-	mi-	liar
f V	m I l	j @r
fa-	mi-	lies
f {	m I	l i: z
fa-	mi-	ly
f {	m I	l i:
fa-	mi-	ly's
f {	m I	l i: z
fa-	mig-	li-	et-	ti
f V	m I g	l i:	e	t i:
fa-	mine
f {	m I n
fa-	mines
f {	m I n z
fa-	mous
f eI	m V s
fa-	mous-	ly
f eI	m V s	l i:
fa-	na-	ti-	cal
f V	n {	t I	k V l
fa-	na-	ti-	cal-	ly
f V	n {	t I	k V	l i:
fa-	na-	ti-	ci-	sm
f V	n {	t V	s I	z V m
fa-	na-	tic
f V	n {	t I k
fa-	na-	tics
f V	n {	t I k s
fa-	neu-	il
f { n	j u:	I l
fa-	ra-	day
f {	r V	d eI
fa-	ra-	day's
f {	r V	d eI z
fa-	ra-	way
f Q@	V	w eI
fa-	rah
f e@	V
fa-	ro
f e@	@U
fa-	rouk
f V	r u: k
fa-	sa-	no
f Q	s Q	n @U
fa-	shio-	na-	ble
f {	S V	n V	b V l
fa-	shio-	nab-	ly
f {	S V	n V b	l i:
fa-	shio-	ning
f {	S V	n I N
fa-	shion
f {	S V n
fa-	shioned
f {	S V n d
fa-	shions
f {	S V n z
fa-	shion's
f {	S V n z
fa-	so
f Q	s @U
fa-	ste-	ners
f {	s V	n @r z
fa-	ste-	ning
f {	s V	n I N
fa-	ste-	nings
f {	s V	n I N z
fa-	ta
f Q	t V
fa-	ta-	li-	sm
f eI	t V	l I	z V m
fa-	ta-	li-	ties
f V	t {	l V	t i: z
fa-	ta-	li-	ty
f V	t {	l V	t i:
fa-	ta-	lis-	tic
f eI	t V	l I s	t I k
fa-	ta-	list
f eI	t V	l I s t
fa-	ta-	lists
f eI	t V	l V s t s
fa-	tah
f Q	t V
fa-	tal
f eI	t V l
fa-	tal-	ly
f eI	t V	l i:
fa-	ted
f eI	t V d
fa-	the-	ring
f Q	D @r	I N
fa-	ther
f Q	D @r
fa-	ther-	hood
f Q	D @r	h U d
fa-	ther-	land
f Q	D @r	l { n d
fa-	ther-	less
f Q	D @r	l V s
fa-	ther-	ly
f Q	D @r	l i:
fa-	thered
f Q	D @r d
fa-	thers
f Q	D @r z
fa-	ther's
f Q	D @r z
fa-	tho-	ma-	ble
f {	D V	m V	b V l
fa-	thom
f {	D V m
fa-	thoms
f {	D V m z
fa-	ti-	ma
f {	T I	m V
fa-	ti-	mah
f {	T I	m V
fa-	tigu-	ing
f V	t i:	g I N
fa-	tigue
f V	t i: g
fa-	tigued
f V	t i: g d
fa-	tigues
f V	t i: g z
fa-	tu-	ous
f {	tS V	w V s
fa-	va
f Q	v V
fa-	va-	ta
f Q	v Q	t V
fa-	ve-	la
f Q	v e	l V
fa-	ver
f eI	v @r
fa-	vo-	ra-	bi-	li-	ty
f {	v @r	V	b I	l V	t i:
fa-	vo-	ra-	ble
f eI	v @r	V	b V l
fa-	vo-	rab-	ly
f eI	v @r	V b	l i:
fa-	vo-	ri-	ti-	sm
f eI	v @r	I	t I	z V m
fa-	vo-	ring
f eI	v @r	I N
fa-	vo-	rite
f eI	v @r	I t
fa-	vo-	rites
f eI	v @r	I t s
fa-	vor
f eI	v @r
fa-	vored
f eI	v @r d
fa-	vors
f eI	v @r z
fa-	xes
f { k	s V z
fa-	xing
f { k	s I N
fa-	xon
f { k	s V n
fa-	yanne
f eI	V n
fa-	yette
f eI	e t
fa-	yette-	ville
f eI	e t	v I l
fab
f { b
fab-	ri
f { b	r i:
fab-	ri-	ca-	ted
f { b	r I	k eI	t I d
fab-	ri-	ca-	ting
f { b	r I	k eI	t I N
fab-	ri-	ca-	tion
f { b	r I	k eI	S V n
fab-	ri-	ca-	tions
f { b	r I	k eI	S V n z
fab-	ri-	ca-	tor
f { b	r I	k eI	t @r
fab-	ri-	ca-	tors
f { b	r I	k eI	t @r z
fab-	ri-	cant
f { b	r I	k V n t
fab-	ri-	cate
f { b	r I	k eI t
fab-	ri-	cates
f { b	r I	k eI t s
fab-	ric
f { b	r I k
fab-	rics
f { b	r I k s
fab-	ron
f { b	r V n
fac
f { k
fac-	si-	mi-	le
f { k	s I	m I	l i:
fac-	si-	mi-	les
f { k	s I	m I	l i: z
fac-	ti-	tious
f { k	t I	S V s
fac-	tio-	na-	li-	sm
f { k	S V	n V	l I	z V m
fac-	tio-	nal
f { k	S V	n V l
fac-	tion
f { k	S V n
fac-	tions
f { k	S V n z
fac-	to
f { k	t @U
fac-	to-	ries
f { k	t @r	i: z
fac-	to-	ring
f { k	t @r	I N
fac-	to-	ry
f { k	t @r	i:
fac-	to-	ry's
f { k	t @r	i: z
fac-	tor
f { k	t @r
fac-	tored
f { k	t @r d
fac-	tors
f { k	t @r z
fac-	tu-	al
f { k	tS u:	V l
fac-	tu-	al-	ly
f { k	tS u:	V	l i:
face
f eI s
face-	down
f eI s	d aU n
face-	less
f eI s	l V s
face-	lift
f eI s	l I f t
faced
f eI s t
fack-	ler
f { k	l @r
fact
f { k t
facts
f { k t s
fad
f { d
fad-	den
f {	d V n
fad-	dish
f {	d I S
fade
f eI d
fades
f eI d z
fads
f { d z
fae
f aI
fag
f { g
fag-	got
f {	g V t
fags
f { g z
fah-	ren-	heit
f e@	V n	h aI t
fahd
f Q d
fahne-	stock
f Q n	s t Q k
fahr
f Q@
fahs
f { s
fai-	ling
f eI	l I N
fai-	lings
f eI	l I N z
fai-	lure
f eI l	j @r
fai-	lures
f eI l	j @r z
fai-	rer
f e@	@r
fai-	rest
f e@	V s t
fai-	ries
f e@	i: z
fai-	ry
f e@	i:
fai-	ry-	land
f e@	i:	l { n d
fai-	ry-	tale
f e@	i:	t eI l
fai-	ry-	tales
f e@	i:	t eI l z
fai-	sal
f eI	z V l
fai-	son
f eI	z V n
fail
f eI l
fail-	safe
f eI l	s eI f
failed
f eI l d
fails
f eI l z
fain
f eI n
fain-	ted
f eI n	t V d
fain-	ter
f eI n	t @r
fain-	test
f eI n	t V s t
fain-	thear-	ted
f eI n	t h Q@	t V d
fain-	ting
f eI n	t I N
faint
f eI n t
faint-	ly
f eI n	t l i:
faint-	ness
f eI n	t n V s
fair
f e@
fair-	bank
f e@	b V N k
fair-	banks
f e@	b V N k s
fair-	burn
f e@	b @r n
fair-	child
f e@	tS aI l d
fair-	child's
f e@	tS aI l d z
fair-	fax
f e@	f { k s
fair-	field
f e@	f i: l d
fair-	ground
f e@ g	r aU n d
fair-	grounds
f e@ g	r aU n d z
fair-	lawn
f e@	l O: n
fair-	leigh
f e@	l eI
fair-	less
f e@	l V s
fair-	ley
f e@	l i:
fair-	lie
f e@	l i:
fair-	ly
f e@	l i:
fair-	man
f aI r	m V n
fair-	mont
f e@	m Q n t
fair-	ness
f e@	n V s
fair-	view
f e@ v	j u:
fair-	way
f e@	w eI
fair-	ways
f e@	w eI z
fair-	wea-	ther
f e@	w e	D @r
faire
f e@
faires
f e@ z
fairs
f e@ z
fair's
f e@ z
fait
f eI t
faith
f eI T
faith-	ful
f eI T	f V l
faith-	ful-	ly
f eI T	f V	l i:
faith-	fuls
f eI T	f V l z
faiths
f eI T s
fake
f eI k
faked
f eI k t
fakes
f eI k s
fal-	co
f { l	k @U
fal-	co-	ne
f Q l	k @U	n i:
fal-	co-	ner
f { l	k V	n @r
fal-	co-	ners
f { l	k V	n @r z
fal-	co-	net
f { l	k V	n e t
fal-	co-	nets
f { l	k V	n e t s
fal-	con
f { l	k V n
fal-	con-	ry
f { l	k V n	r i:
fal-	cons
f { l	k V n z
fal-	do
f Q l	d @U
fal-	la
f {	l V
fal-	la-	cies
f {	l V	s i: z
fal-	la-	cious
f V	l eI	S V s
fal-	la-	cious-	ly
f V	l eI	S V s	l i:
fal-	la-	cy
f {	l V	s i:
fal-	len
f Q	l V n
fal-	ler
f O:	l @r
fal-	li-	bi-	li-	ty
f {	l V	b I	l I	t i:
fal-	li-	ble
f {	l I	b V l
fal-	ling
f Q	l I N
fal-	lo-	pi-	an
f V	l @U	p i:	V n
fal-	lon
f {	l V n
fal-	low
f {	l @U
fal-	lows
f {	l @U z
fal-	mouth
f { l	m V T
fal-	set-	to
f O: l	s e	t @U
fal-	set-	tos
f O: l	s e	t @U z
fal-	si-	fi-	ca-	tion
f { l	s I	f I	k eI	S V n
fal-	si-	fied
f O: l	s I	f aI d
fal-	si-	fy
f O: l	s I	f aI
fal-	si-	fy-	ing
f O: l	s I	f aI	I N
fal-	si-	ty
f O: l	s I	t i:
fal-	staff
f O: l	s t { f
fal-	staff's
f O: l	s t { f s
fal-	te-	ring
f O: l	t @r	I N
fal-	ter
f O: l	t @r
fal-	tered
f Q l	t @r d
fal-	ters
f O: l	t @r z
fal-	well
f O: l	w e l
fal-	well's
f O: l	w e l z
falk
f O: k
falk-	land
f O: k	l V n d
falk-	lands
f O: k	l V n d z
falk-	ner
f O: k	n @r
fall
f Q l
fall-	back
f O: l	b { k
fall-	off
f O:	l O: f
fall-	out
f O:	l aU t
fall-	outs
f O:	l aU t s
falls
f O: l z
fall's
f Q l z
false
f O: l s
false-	hood
f { l	s h U d
false-	hoods
f { l	s h U d z
false-	ly
f O: l	s l i:
fame
f eI m
famed
f eI m d
fan
f { n
fan-	cher
f { n	tS @r
fan-	chon
f { n	tS V n
fan-	ci-	er
f { n	s i:	@r
fan-	ci-	ers
f { n	s i:	@r z
fan-	ci-	est
f { n	s i:	V s t
fan-	ci-	ful
f { n	s I	f V l
fan-	cied
f { n	s i: d
fan-	cies
f { n	s i: z
fan-	cy
f { n	s i:
fan-	dan-	go
f { n	d { N	g @U
fan-	fare
f { n	f e@
fan-	ger
f {	N @r
fan-	gle
f { N	g V l
fan-	gled
f { N	g V l d
fan-	like
f { n	l aI k
fan-	nie
f {	n i:
fan-	nin
f {	n I n
fan-	ning
f {	n I N
fan-	ning's
f {	n I N z
fan-	non
f {	n V n
fan-	ny
f {	n i:
fan-	ta-	si-	zes
f { n	t V	s aI	z V z
fan-	ta-	si-	zing
f { n	t V	s aI	z I N
fan-	ta-	sia
f { n	t eI	Z V
fan-	ta-	sies
f { n	t V	s i: z
fan-	ta-	size
f { n	t V	s aI z
fan-	ta-	sized
f { n	t V	s aI z d
fan-	ta-	sy
f { n	t V	s i:
fan-	ta-	sy-	land
f { n	t V	s i:	l { n d
fan-	tail
f { n	t eI l
fan-	tas-	tic
f { n	t { s	t I k
fan-	tas-	tical-	ly
f { n	t { s	t I k	l i:
fane
f eI n
fang
f { N
fangs
f { N z
fanned
f { n d
fans
f { n z
fan's
f { n z
fant
f { n t
fao
f aU
far
f Q@
far-	ber
f Q@	b @r
far-	ci-	cal
f Q@	s I	k V l
far-	mer
f Q@	m @r
far-	mers
f Q@	m @r z
far-	mer's
f Q@	m @r z
far-	mers'
f Q@	m @r z
far-	ming
f Q@	m I N
far-	ming-	dale
f Q@	m I N	d eI l
far-	ming-	ton
f Q@	m I N	t V n
far-	ming's
f Q@	m I N z
far-	nam
f Q@	n V m
far-	ner
f Q@	n @r
far-	quhar
f Q@ k	w @r
far-	ra
f Q@	V
far-	ra-	gut
f e@	V	g V t
far-	ra-	khan
f Q@	V	k Q n
far-	ra-	khan's
f Q@	V	k Q n z
far-	rah
f e@	V
far-	rand
f {	r V n d
far-	rant
f Q@	V n t
far-	rar
f @r	Q@
far-	rel
f e@	V l
far-	rell
f e@	e l
far-	rell's
f e@	e l z
far-	ren
f e@	V n
far-	rens
f {	r V n z
far-	ri-	er
f e@	i:	@r
far-	ring-	ton
f e@	I N	t V n
far-	ris
f e@	I s
far-	rish
f {	r I S
far-	ro
f Q@	@U
far-	ro-	wing
f {	r @U	I N
far-	ron
f e@	V n
far-	row
f e@	@U
far-	row's
f e@	@U z
far-	si
f Q@	s i:
far-	sigh-	ted
f Q@	s aI	t V d
far-	sigh-	ted-	ness
f Q@	s aI	t V d	n V s
far-	son
f Q@	s V n
far-	ther
f Q@	D @r
far-	thest
f Q@	D V s t
far-	thin-	gale
f Q@	D I N	g eI l
far-	thing
f Q@	D I N
far-	ver
f Q@	v @r
far-	well
f Q@	w e l
farce
f Q@ s
fare
f e@
fared
f e@ d
farm
f Q@ m
farm-	hand
f Q@ m	h { n d
farm-	hands
f Q@ m	h { n d z
farm-	hou-	ses
f Q@ m	h aU	s V z
farm-	house
f Q@ m	h aU s
farm-	land
f Q@ m	l { n d
farm-	lands
f Q@ m	l { n d z
farm-	stead
f Q@ m	s t e d
farm-	wor-	ker
f Q@ m	w @r	k @r
farm-	wor-	kers
f Q@ m	w @r	k @r z
farm-	yard
f Q@ m	j Q@ d
farmed
f Q@ m d
farms
f Q@ m z
farm's
f Q@ m z
farn-	bo-	rough
f Q@ n	b @r	@U
farn-	ham
f Q@	n V m
farns-	worth
f Q@ n	s w @r T
farr
f Q@
far's
f Q@ z
fas-	ching
f {	S I N
fas-	ci-	na-	ted
f {	s I	n eI	t I d
fas-	ci-	na-	ting
f {	s I	n eI	t I N
fas-	ci-	na-	tion
f {	s I	n eI	S V n
fas-	ci-	nate
f {	s I	n eI t
fas-	ci-	nates
f {	s I	n eI t s
fas-	ci-	sm
f {	S I	z V m
fas-	cist
f {	S I s t
fas-	cists
f {	S I s t s
fas-	nacht
f { s	n V k t
fas-	te-	ner
f {	s V	n @r
fas-	ted
f { s	t V d
fas-	ten
f {	s V n
fas-	tened
f {	s V n d
fas-	ter
f { s	t @r
fas-	test
f { s	t V s t
fas-	ti-	di-	ous
f { s	t I	d i:	V s
fas-	ting
f { s	t I N
fass
f { s
fast
f { s t
fast-	ball
f { s	t b O: l
fast-	food
f { s	t f u: d
fast-	ness
f { s	t n V s
fasts
f { s t s
fat
f { t
fat-	te-	ning
f {	t V	n I N
fat-	ten
f {	t V n
fat-	tened
f {	t V n d
fat-	ter
f {	t @r
fat-	test
f {	t V s t
fat-	ties
f {	t i: z
fat-	ty
f {	t i:
fat-	wa
f Q t	w Q
fate
f eI t
fate-	ful
f eI t	f V l
fates
f eI t s
fath
f { T
fats
f { t s
fau-	bert
f aU	b @r t
fau-	bi-	on
f aU	b i:	V n
fau-	cet
f O:	s V t
fau-	cets
f O:	s V t s
fau-	cett
f O:	s e t
fau-	cher
f aU	k @r
fau-	na
f O:	n V
fau-	nal
f Q	n V l
fau-	ver
f aU	v @r
faul-	ted
f O: l	t V d
faul-	ting
f O: l	t I N
faul-	ty
f O: l	t i:
faulds
f O: l d z
faulk-	ner
f O: k	n @r
faulk-	ner's
f O: k	n @r z
fault
f O: l t
faults
f O: l t s
faunt-	ler-	oy
f O: n	t l @r	OI
faure
f O@
faus
f O: z
faus-	ta
f O: s	t V
faus-	ti-	na
f O: s	t i:	n V
faus-	ti-	no
f O: s	t i:	n @U
faus-	tian
f O: s	tS V n
faus-	tine
f aU s	t i: n
faus-	to
f O: s	t @U
faus-	tus
f O: s	t V s
faust
f aU s t
faux
f O: k s
faw
f O:
faw-	cett
f O:	s e t
faw-	ley
f O:	l i:
faw-	ning
f O:	n I N
fawkes
f O: k s
fawn
f O: n
fax
f { k s
faxed
f { k s t
fay
f eI
faye
f eI
fayed
f eI d
fayme
f eI m
fayne
f eI n
fay's
f eI z
faze
f eI z
fazed
f eI z d
fe
f eI
fe-	al-	ty
f i:	V l	t i:
fe-	cal
f i:	k V l
fe-	ces
f i:	s i: z
fe-	dak
f e	d V k
fe-	de-	ra-	li-	sm
f e	d @r	V	l I	z V m
fe-	de-	ra-	li-	zing
f e	d @r	V	l aI	z I N
fe-	de-	ra-	list
f e	d @r	V	l V s t
fe-	de-	ra-	lists
f e	d @r	V	l V s t s
fe-	de-	ra-	lize
f e	d @r	V	l aI z
fe-	de-	ra-	lized
f e	d @r	V	l aI z d
fe-	de-	ra-	ted
f e	d @r	eI	t V d
fe-	de-	ra-	tion
f e	d @r	eI	S V n
fe-	de-	ra-	tions
f e	d @r	eI	S V n z
fe-	de-	ra-	tion's
f e	d @r	eI	S V n z
fe-	de-	ra-	tive
f e	d @r	V	t I v
fe-	de-	ral
f e	d @r	V l
fe-	de-	ral-	ly
f e	d @r	V	l i:
fe-	de-	rals
f e	d @r	V l z
fe-	de-	rate
f e	d @r	eI t
fe-	de-	ri-	ca
f e	d @r	i:	k V
fe-	de-	ri-	co
f e	d @r	i:	k @U
fe-	dex
f e	d e k s
fe-	do-	ra
f V	d O@	V
fe-	dor
f e	d @r
fe-	li-	ci-	tous
f V	l I	s V	t V s
fe-	li-	ci-	ty
f V	l I	s V	t i:
fe-	li-	cia
f V	l i:	S V
fe-	li-	cia's
f V	l i:	S V z
fe-	lice
f V	l i: s
fe-	line
f i:	l aI n
fe-	lines
f i:	l aI n z
fe-	lipe
f V	l i: p
fe-	lis
f e	l I s
fe-	lix
f i:	l I k s
fe-	lo-	ni-	ous
f e	l @U	n i:	V s
fe-	lo-	nies
f e	l V	n i: z
fe-	lo-	ny
f e	l V	n i:
fe-	lon
f e	l V n
fe-	lons
f e	l V n z
fe-	luc-	ca
f V	l V	k V
fe-	male
f i:	m eI l
fe-	males
f i:	m eI l z
fe-	male's
f i:	m eI l z
fe-	ne-	lon
f e	n V	l Q n
fe-	nel-	la
f e	n e	l V
fe-	ni-	an
f i:	n i:	V n
fe-	nu-	greek
f e	n u: g	r i: k
fe-	o-	do-	ra
f i:	V	d O@	V
fe-	o-	dor
f i:	V	d @r
fe-	o-	la
f i:	Q	l V
fe-	ra
f e@	V
fe-	ral
f e@	V l
fe-	renc
f @r	e n s
fe-	ri-	a
f e@	i:	V
fe-	ro-	ci-	ty
f @r	Q	s I	t i:
fe-	ro-	cious
f @r	@U	S V s
fe-	ro-	cious-	ly
f @r	@U	S V s	l i:
fe-	rul-	lo
f @r	u:	l @U
fe-	tal
f i:	t V l
fe-	ted
f eI	t V d
fe-	ti-	shi-	sm
f e	t I	S I	z V m
fe-	ti-	shist
f e	t I	S I s t
fe-	ti-	shists
f e	t I	S I s t s
fe-	tid
f e	t I d
fe-	tish
f e	t I S
fe-	tu-	ses
f i:	t V	s V z
fe-	tus
f i:	t V s
fe-	ve-	rish
f i:	v @r	I S
fe-	ve-	rish-	ly
f e	v @r	I S	l i:
fe-	ver
f i:	v @r
fe-	ver-	few
f i:	v @r f	j u:
fe-	ver-	fews
f i:	v @r f	j u: z
fe-	vered
f i:	v @r d
fe-	vers
f i:	v @r z
fe-	wer
f j u:	@r
fe-	west
f j u:	V s t
fea-	ring
f I@	I N
fea-	si-	bi-	li-	ty
f i:	z I	b I	l I	t i:
fea-	si-	ble
f i:	z I	b V l
fea-	sib-	ly
f i:	z I b	l i:
fea-	the-	ring
f e	D @r	I N
fea-	the-	ry
f e	D @r	i:
fea-	ther
f e	D @r
fea-	ther-	bed
f e	D @r	b e d
fea-	ther-	bed-	ding
f e	D @r	b e	d I N
fea-	ther-	less
f e	D @r	l V s
fea-	ther-	weight
f e	D @r	w eI t
fea-	thered
f e	D @r d
fea-	thers
f e	D @r z
fea-	thers-	tone
f e	D @r s	t @U n
fea-	tu-	ring
f i:	tS @r	I N
fea-	ture
f i:	tS @r
fea-	ture-	less
f i:	tS @r	l V s
fea-	tured
f i:	tS @r d
fea-	tures
f i:	tS @r z
fear
f I@
fear-	ful
f I@	f V l
fear-	less
f I@	l V s
fear-	some
f I@	s V m
feared
f I@ d
fears
f I@ z
feas-	ted
f i: s	t V d
feas-	ter
f i: s	t @r
feas-	ting
f i: s	t I N
feast
f i: s t
feasts
f i: s t s
feat
f i: t
feats
f i: t s
feb-	res
f e b	r V s
feb-	ru-	a-	ry
f e b	j V	w e@	i:
feb-	ru-	a-	ry's
f e b	j V	w e@	i: z
fech-	ner
f e k	n @r
fech-	ter
f e k	t @r
fecht
f e k t
feck
f e k
feck-	less
f e k	l V s
fed
f e d
fed-	der-	s's
f e	d @r	z V z
fed-	ders
f e	d @r z
feds
f e d z
fed's
f e d z
fee
f i:
fee-	der
f i:	d @r
fee-	ders
f i:	d @r z
fee-	ding
f i:	d I N
fee-	dings
f i:	d I N z
fee-	ler
f i:	l @r
fee-	lers
f i:	l @r z
fee-	ley
f i:	l i:
fee-	ling
f i:	l I N
fee-	lings
f i:	l I N z
fee-	ly
f i:	l i:
fee-	ney
f i:	n i:
feeb-	le
f i:	b V l
feeb-	ly
f i: b	l i:
feed
f i: d
feed-	back
f i: d	b { k
feed-	lot
f i: d	l Q t
feed-	lots
f i: d	l Q t s
feed-	stock
f i: d	s t Q k
feed-	stocks
f i: d	s t Q k s
feeds
f i: d z
feel
f i: l
feels
f i: l z
fees
f i: z
feese
f i: z
feet
f i: t
fei-	ghan
f eI	g V n
fei-	gin
f aI	g I n
feig-	ning
f eI	n I N
feign
f eI n
feigned
f eI n d
feil
f i: l
fein
f aI n
fein-	berg
f aI n	b @r g
fein-	gold
f aI N	g @U l d
fein-	stein
f aI n	s t aI n
fein-	stein's
f aI n	s t aI n z
fein's
f aI n z
feint
f eI n t
feis
f aI s
feis-	ty
f aI s	t i:
feist
f aI s t
fel-	da
f e l	d V
fel-	dene
f e l	d i: n
fel-	der
f e l	d @r
fel-	la
f e	l V
fel-	las
f e	l V s
fel-	ler
f e	l @r
fel-	lers
f e	l @r z
fel-	li-	ni
f V	l i:	n i:
fel-	ling
f e	l I N
fel-	low
f e	l @U
fel-	low-	ship
f e	l @U	S I p
fel-	low-	ships
f e	l @U	S I p s
fel-	lows
f e	l @U z
fel-	low's
f e	l @U z
fel-	ten
f e l	t V n
fel-	ter
f e l	t @r
fel-	ton
f e l	t V n
fel-	ty
f e l	t i:
felch
f e l tS
feld
f e l d
feld-	man
f e l	d m V n
feld-	man's
f e l	d m V n z
feld-	spar
f e l	d s p Q@
feld-	spars
f e l	d s p Q@ z
feld-	stein
f e l	d s t aI n
feld-	stein's
f e l	d s t i: n z
feldt
f e l t
fell
f e l
fell-	ner
f e l	n @r
felled
f e l d
)"
R"(fells
f e l z
fels
f e l z
felske
f e l s k
felt
f e l t
felt-	man
f e l	t m V n
felts
f e l t s
fen-	ces
f e n	s V z
fen-	cing
f e n	s I N
fen-	ded
f e n	d V d
fen-	der
f e n	d @r
fen-	ders
f e n	d @r z
fen-	ding
f e n	d I N
fen-	nel
f e	n V l
fen-	nel-	ly
f e	n V	l i:
fen-	nell
f e	n V l
fen-	ner
f e	n @r
fen-	nes-	sy
f e	n V	s i:
fen-	ni-	more
f e	n I	m O@
fen-	ter
f e n	t @r
fen-	ton
f e n	t V n
fen-	wick
f e n	w I k
fence
f e n s
fend
f e n d
fends
f e n d z
fenn
f e n
fens-	ter
f e n	s t @r
fent
f e n t
fent-	ress
f e n	t r V s
fer
f @r
fer-	ber
f @r	b @r
fer-	di-	nan-	da
f @r	d i:	n Q n	d V
fer-	di-	nand
f @r	d I	n { n d
fer-	die
f @r	d i:
fer-	gu-	son
f @r	g V	s V n
fer-	gu-	son's
f @r	g V	s V n z
fer-	gus
f @r	g V s
fer-	men-	ta-	tion
f @r	m V n	t eI	S V n
fer-	men-	ted
f @r	m e n	t V d
fer-	men-	ting
f @r	m e n	t I N
fer-	ment
f @r	m e n t
fer-	ments
f @r	m e n t s
fer-	mi
f @r	m i:
fer-	mi-	um
f e@	m i:	V m
fer-	min
f @r	m I n
fer-	nald
f @r	n Q l d
fer-	nan-	da
f @r	n { n	d V
fer-	nan-	des
f @r	n Q n	d e s
fer-	nan-	dez
f @r	n { n	d e z
fer-	nan-	di-	na
f @r	n V n	d i:	n V
fer-	nan-	do
f @r	n { n	d @U
fer-	nand
f @r	n { n d
fer-	ne-	ry
f @r	n @r	i:
fer-	ra-	ra
f @r	Q@	V
fer-	ra-	ri
f @r	Q@	i:
fer-	ra-	ro
f @r	Q@	@U
fer-	ran-	ti
f e@	{ n	t i:
fer-	rand
f e@	V n d
fer-	re-	ro
f e@	e@	@U
fer-	re-	ted
f e@	V	t V d
fer-	re-	ting
f e@	V	t I N
fer-	ree
f @r	i:
fer-	rei-	ra
f e@	eI	r V
fer-	rei-	ro
f e@	e@	@U
fer-	rel
f e@	e l
fer-	rell
f e@	e l
fer-	ren
f e@	V n
fer-	rer
f e@	@r
fer-	ret
f e@	V t
fer-	ret-	ti
f @r	e	t i:
fer-	rets
f e@	V t s
fer-	ri
f e@	i:
fer-	ri-	er
f e@	i:	@r
fer-	ri-	ter
f e@	aI	t @r
fer-	rick
f e@	I k
fer-	ried
f e@	i: d
fer-	ries
f e@	i: z
fer-	rig-	no
f @r	i: g	n @U
fer-	ris
f e@	I s
fer-	rite
f e@	aI t
fer-	ro
f e@	@U
fer-	ro-	mag-	ne-	ti-	sm
f e@	@U	m { g	n V	t I	z V m
fer-	ro-	mag-	ne-	tic
f e@	@U	m { g	n e	t I k
fer-	ro-	mag-	net
f e@	@U	m { g	n V t
fer-	ro-	nic-	kel
f e@	V	n I	k V l
fer-	ro-	type
f e@	V	t aI p
fer-	roch-	rome
f e@	V k	r @U m
fer-	ron
f e@	V n
fer-	rous
f e@	V s
fer-	ry
f e@	i:
fer-	ry-	boat
f e@	i:	b @U t
fer-	ry-	boats
f e@	i:	b @U t s
fer-	ry-	ing
f e@	i:	I N
fer-	ry-	man
f e@	i:	m V n
fer-	ry's
f e@	i: z
fer-	ti-	li-	ty
f @r	t I	l I	t i:
fer-	ti-	li-	za-	tion
f @r	t I	l aI	z eI	S V n
fer-	ti-	li-	zer
f @r	t I	l aI	z @r
fer-	ti-	li-	zers
f @r	t I	l aI	z @r z
fer-	ti-	li-	zes
f @r	t I	l aI	z V z
fer-	ti-	li-	zing
f @r	t I	l aI	z I N
fer-	ti-	lize
f @r	t I	l aI z
fer-	ti-	lized
f @r	t I	l aI z d
fer-	tile
f @r	t I l
fer-	vent
f @r	v V n t
fer-	vent-	ly
f @r	v V n	t l i:
fer-	vid
f @r	v I d
fer-	vor
f @r	v @r
ferd
f @r d
ferm
f @r m
fern
f @r n
fern-	dale
f @r n	d eI l
fern-	like
f @r n	l aI k
ferns
f @r n z
fe's
f eI z
fes-	cue
f e s	k j u:
fes-	sen-	den
f e	s V n	d V n
fes-	ta
f e s	t V
fes-	te-	ring
f e s	t @r	I N
fes-	ter
f e s	t @r
fes-	tered
f e s	t @r d
fes-	ti-	val
f e s	t I	v V l
fes-	ti-	vals
f e s	t I	v V l z
fes-	ti-	val's
f e s	t I	v V l z
fes-	ti-	vi-	ties
f e s	t I	v I	t i: z
fes-	ti-	vi-	ty
f e s	t I	v I	t i:
fes-	tive
f e s	t I v
fes-	toon
f e s	t u: n
fes-	tooned
f e s	t u: n d
fes-	tus
f e s	t V s
fess
f e s
fessed
f e s t
fest
f e s t
fests
f e s t s
fet-	ches
f e	tS V z
fet-	ching
f e	tS I N
fet-	ter
f e	t @r
fet-	tered
f e	t @r d
fet-	ters
f e	t @r z
fet-	ting
f e	t I N
fet-	tuc-	ci-	ne
f e	t V	tS i:	n i:
fetch
f e tS
fetched
f e tS t
fete
f eI t
fett
f e t
fettes
f e t s
feu-	da-	li-	sm
f j u:	d V	l I	z V m
feu-	da-	lis-	tic
f j u:	d V	l I s	t I k
feu-	dal
f j u:	d V l
feu-	ded
f j u:	d V d
feu-	ding
f j u:	d I N
feucht
f OI k t
feud
f j u: d
feuds
f j u: d z
few
f j u:
fey
f eI
feyn-	man
f eI n	m V n
fez
f e z
fi
f aI
fi-	an-	ce
f i:	Q n	s eI
fi-	an-	cee
f i:	{ n	s i:
fi-	an-	na
f i:	{	n V
fi-	as-	co
f i:	{ s	k @U
fi-	as-	cos
f i:	{ s	k @U z
fi-	at
f aI	{ t
fi-	at's
f i:	{ t s
fi-	be-	rop-	tic
f aI	b @r	Q p	t I k
fi-	ber
f aI	b @r
fi-	ber-	board
f aI	b @r	b O@ d
fi-	ber-	glas
f aI	b @r g	l { s
fi-	ber-	glass
f aI	b @r g	l { s
fi-	bers
f aI	b @r z
fi-	ber's
f aI	b @r z
fi-	bre
f aI	b @r
fi-	bre-	board
f aI	b @r	b O@ d
fi-	bu-	la
f I b	j V	l V
fi-	chus
f I	tS V s
fi-	co
f i:	k @U
fi-	dal-	go
f i:	d Q l	g @U
fi-	de-	li-	ties
f V	d e	l I	t i: z
fi-	de-	li-	ty
f V	d e	l I	t i:
fi-	de-	li-	ty's
f V	d e	l I	t i: z
fi-	de-	lia
f V	d i: l	j V
fi-	del
f V	d e l
fi-	del's
f V	d e l z
fi-	do
f aI	d @U
fi-	du-	ci-	a-	ries
f V	d u:	S i:	e@	i: z
fi-	du-	ci-	a-	ry
f V	d u:	S i:	e@	i:
fi-	e-	ry
f aI	@r	i:
fi-	es-	ta
f i:	e s	t V
fi-	est
f i:	V s t
fi-	fer
f aI	f @r
fi-	fi
f i:	f i:
fi-	field
f I	f i: l d
fi-	ga-	ro
f I	g @r	@U
fi-	gone
f I	g V n
fi-	gure
f I g	j @r
fi-	la-	ment
f I	l V	m V n t
fi-	la-	ments
f I	l V	m V n t s
fi-	ler
f aI	l @r
fi-	lers
f aI	l @r z
fi-	let
f V	l eI
fi-	lets
f V	l eI z
fi-	li-	al
f I	l i:	V l
fi-	li-	bus-	te-	ring
f I	l I	b V s	t @r	I N
fi-	li-	bus-	ter
f I	l I	b V s	t @r
fi-	li-	bus-	tered
f I	l I	b V s	t @r d
fi-	li-	bus-	ters
f I	l I	b V s	t @r z
fi-	li-	gree
f I	l I g	r i:
fi-	li-	grees
f I	l I g	r i: z
fi-	li-	pi-	no
f I	l I	p i:	n @U
fi-	li-	pi-	nos
f I	l I	p i:	n @U z
fi-	ling
f aI	l I N
fi-	lings
f aI	l I N z
fi-	lion
f I l	j V n
fi-	lip
f I	l I p
fi-	lip-	pi
f V	l I	p i:
fi-	lip-	po
f V	l i:	p @U
fi-	lo
f i:	l @U
fi-	lo-	fax
f I	l @U	f { k s
fi-	lo-	me-	na
f I	l V	m i:	n V
fi-	lo-	sa
f i:	l @U	s V
fi-	ma
f i:	m V
fi-	na
f aI	n V
fi-	na-	gle
f V	n eI	g V l
fi-	na-	le
f V	n {	l i:
fi-	na-	li-	ty
f aI	n {	l I	t i:
fi-	na-	li-	zing
f aI	n V	l aI	z I N
fi-	na-	list
f aI	n V	l V s t
fi-	na-	lists
f aI	n V	l V s t s
fi-	na-	lize
f aI	n V	l aI z
fi-	na-	lized
f aI	n V	l aI z d
fi-	nag-	ler
f V	n eI g	l @r
fi-	nal
f aI	n V l
fi-	nal-	ly
f aI	n V	l i:
fi-	nals
f aI	n V l z
fi-	nan-	cer
f aI	n { n	s @r
fi-	nan-	ces
f V	n { n	s V z
fi-	nan-	cial
f V	n { n	S V l
fi-	nan-	cial-	ly
f V	n { n	S V	l i:
fi-	nan-	cier
f I	n V n	s I@
fi-	nan-	ciere
f I	n { n	s I@
fi-	nan-	ciers
f I	n V n	s I@ z
fi-	nan-	cing
f V	n { n	s I N
fi-	nan-	cings
f V	n { n	s I N z
fi-	nance
f V	n { n s
fi-	nanced
f V	n { n s t
fi-	ne-	gan
f I	n I	g { n
fi-	ne-	ry
f aI	n @r	i:
fi-	nel-	la
f V	n e	l V
fi-	ner
f aI	n @r
fi-	nesse
f V	n e s
fi-	nessed
f V	n e s t
fi-	nest
f aI	n V s t
fi-	ni
f i:	n i:
fi-	ni-	cky
f I	n I	k i:
fi-	ni-	sher
f I	n I	S @r
fi-	ni-	shers
f I	n I	S @r z
fi-	ni-	shes
f I	n I	S V z
fi-	ni-	shing
f I	n I	S I N
fi-	ning
f aI	n I N
fi-	nish
f I	n I S
fi-	nished
f I	n I S t
fi-	nite
f aI	n aI t
fi-	no
f i:	n @U
fi-	noc-	chi-	o
f i:	n @U	k i:	@U
fi-	o-	na
f i:	@U	n V
fi-	o-	re
f i:	O@	i:
fi-	o-	rel-	lo
f i:	O@	e	l @U
fi-	o-	ren-	za
f i:	O@	e n	z V
fi-	o-	ret-	ti
f i:	O@	e	t i:
fi-	o-	ri
f i:	O@	i:
fi-	re
f aI	@r
fi-	re-	arm
f aI	@r	Q@ m
fi-	re-	arms
f aI	@r	Q@ m z
fi-	re-	ball
f aI	@r	b O: l
fi-	re-	balls
f aI	@r	b O: l z
fi-	re-	bird
f aI	@r	b @r d
fi-	re-	birds
f aI	@r	b @r d z
fi-	re-	bomb
f aI	@r	b Q m
fi-	re-	bomb-	ing
f aI	@r	b Q	m I N
fi-	re-	brand
f aI	@r b	r { n d
fi-	re-	brands
f aI	@r b	r { n d z
fi-	re-	brick
f aI	@r b	r I k
fi-	re-	bug
f aI	@r	b V g
fi-	re-	bush
f aI	@r	b U S
fi-	re-	crac-	ker
f aI	@r k	r {	k @r
fi-	re-	crac-	kers
f aI	@r k	r {	k @r z
fi-	re-	damp
f aI	@r	d { m p
fi-	re-	figh-	ters
f aI	@r	f aI	t @r z
fi-	re-	flies
f aI	@r f	l aI z
fi-	re-	fly
f aI	@r f	l aI
fi-	re-	hou-	ses
f aI	@r	h aU	s V z
fi-	re-	house
f aI	@r	h aU s
fi-	re-	pla-	ces
f aI	@r p	l eI	s V z
fi-	re-	place
f aI	@r p	l eI s
fi-	re-	proo-	fing
f aI	@r p	r u:	f I N
fi-	re-	proof
f aI	@r p	r u: f
fi-	re-	side
f aI	@r	s aI d
fi-	re-	weed
f aI	@r	w i: d
fi-	re-	wood
f aI	@r	w U d
fi-	red
f aI	@r d
fi-	res
f aI	@r z
fi-	re's
f aI	@r z
fi-	ring
f aI	r I N
fi-	rings
f aI	r I N z
fi-	she-	ries
f I	S @r	i: z
fi-	she-	ry
f I	S @r	i:
fi-	sher
f I	S @r
fi-	sher-	man
f I	S @r	m { n
fi-	sher-	man's
f I	S @r	m V n z
fi-	sher-	men
f I	S @r	m e n
fi-	shers
f I	S @r z
fi-	sher's
f I	S @r z
fi-	shes
f I	S V z
fi-	shing
f I	S I N
fi-	sh's
f I	S V z
fi-	shy
f I	S i:
fi-	thi-	an
f I	T i:	V n
fi-	u-	ma-	ra
f i:	u:	m Q@	V
fi-	xa-	ble
f I k	s V	b V l
fi-	xa-	ted
f I k	s eI	t V d
fi-	xa-	tion
f I k	s eI	S V n
fi-	xa-	tive
f I k	s V	t I v
fi-	xa-	tives
f I k	s V	t I v z
fi-	xate
f I k	s eI t
fi-	xer
f I k	s @r
fi-	xes
f I k	s V z
fi-	xing
f I k	s I N
fi-	xings
f I k	s I N z
fib-	ril-	la-	tion
f I b	r I	l eI	S V n
fib-	rin
f aI b	r I n
fib-	ro-	sis
f aI b	r @U	s I s
fib-	roid
f aI b	r OI d
fib-	roids
f aI b	r OI d z
fib-	rous
f aI b	r V s
fic-	kle
f I	k V l
fic-	kle-	ness
f I	k V l	n V s
fic-	ti-	tious
f I k	t I	S V s
fic-	tio-	na-	lize
f I k	S V	n V	l aI z
fic-	tio-	na-	lized
f I k	S V	n V	l aI z d
fic-	tio-	nal
f I k	S V	n V l
fic-	tion
f I k	S V n
fic-	tions
f I k	S V n z
fick-	ling
f I k	l I N
fid-	d-	ler
f I	d V	l @r
fid-	d-	lers
f I	d V	l @r z
fid-	d-	ler's
f I	d V	l @r z
fid-	dle
f I	d V l
fid-	dled
f I	d V l d
fid-	dles
f I	d V l z
fid-	ge-	ting
f I	dZ V	t I N
fid-	get
f I	dZ V t
fidd-	ling
f I d	l I N
fide
f aI d
fides
f aI d z
fied-	ler
f i: d	l @r
fied-	ler's
f i: d	l @r z
fief
f i: f
fief-	dom
f i: f	d V m
fief-	doms
f i: f	d V m z
fiel
f i: l
fiel-	ded
f i: l	d V d
fiel-	den
f i: l	d V n
fiel-	der
f i: l	d @r
fiel-	ders
f i: l	d @r z
fiel-	der's
f i: l	d @r z
fiel-	ding
f i: l	d I N
field
f i: l d
field-	work
f i: l	d w @r k
fields
f i: l d z
field's
f i: l d z
fien-	dish
f i: n	d I S
fiend
f i: n d
fiends
f i: n d z
fier
f I@
fier-	cer
f I@	s @r
fier-	cest
f I@	s V s t
fierce
f I@ s
fierce-	ly
f I@ s	l i:
fif-	teen
f I f	t i: n
fif-	teens
f I f	t i: n z
fif-	teen's
f I f	t i: n z
fif-	teenth
f I f	t i: n T
fif-	ti-	eth
f I f	t i:	V T
fif-	ties
f I f	t i: z
fif-	ty
f I f	t i:
fif-	ty's
f I f	t i: z
fife
f aI f
fifth
f I f T
fifths
f I f T s
fig
f I g
fig-	ment
f I g	m V n t
fig-	ments
f I g	m V n t s
figge
f I g
figh-	ter
f aI	t @r
figh-	ters
f aI	t @r z
figh-	ter's
f aI	t @r z
figh-	ting
f aI	t I N
figh-	tings
f aI	t I N z
fight
f aI t
fights
f aI t s
fil-	bert
f I l	b @r t
fil-	berts
f I l	b @r t s
fil-	bert's
f I l	b @r t s
fil-	la
f I	l V
fil-	le-	ted
f I	l V	t V d
fil-	ler
f I	l @r
fil-	lers
f I	l @r z
fil-	let
f V	l eI
fil-	lets
f I	l V t s
fil-	ley
f I	l i:
fil-	lies
f I	l i: z
fil-	ling
f I	l I N
fil-	lings
f I	l I N z
fil-	lip
f I	l I p
fil-	ly
f I	l i:
fil-	mer
f I l	m @r
fil-	ming
f I l	m I N
fil-	more
f I l	m O@
fil-	te-	ring
f I l	t @r	I N
fil-	ter
f I l	t @r
fil-	tered
f I l	t @r d
fil-	ters
f I l	t @r z
fil-	thy
f I l	T i:
filch
f I l tS
filched
f I l tS t
file
f aI l
filed
f aI l d
files
f aI l z
fill
f I l
fill-	more
f I l	m O@
filled
f I l d
fills
f I l z
film
f I l m
film-	ma-	ker
f I l	m eI	k @r
film-	ma-	kers
f I l	m eI	k @r z
film-	ma-	king
f I l	m eI	k I N
filmed
f I l m d
films
f I l m z
film's
f I l m z
filt-	ra-	tion
f V l	t r eI	S V n
filth
f I l T
fin
f I n
fin-	ches
f I n	tS V z
fin-	der
f aI n	d @r
fin-	ders
f aI n	d @r z
fin-	der's
f aI n	d @r z
fin-	ding
f aI n	d I N
fin-	dings
f aI n	d I N z
fin-	ge-	ring
f I N	g @r	I N
fin-	ger
f I N	g @r
fin-	ger-	board
f I N	g @r	b O@ d
fin-	ger-	nail
f I N	g @r	n eI l
fin-	ger-	nails
f I N	g @r	n eI l z
fin-	ger-	pain-	ted
f I N	g @r	p eI n	t V d
fin-	ger-	paint
f I N	g @r	p eI n t
fin-	ger-	prin-	ted
f I N	g @r p	r I n	t V d
fin-	ger-	prin-	ting
f I N	g @r p	r I n	t I N
fin-	ger-	print
f I N	g @r p	r I n t
fin-	ger-	prints
f I N	g @r p	r I n t s
fin-	ger-	tip
f I N	g @r	t I p
fin-	ger-	tips
f I N	g @r	t I p s
fin-	gered
f I N	g @r d
fin-	gers
f I N	g @r z
fin-	kel
f I N	k V l
fin-	kel-	stein
f I N	k V l	s t i: n
fin-	kel-	stein's
f I N	k V l	s t i: n z
fin-	lan-	di-	za-	tion
f I n	l { n	d I	z eI	S V n
fin-	land
f I n	l { n d
fin-	land's
f I n	l V n d z
fin-	lay
f I n	l i:
fin-	lay-	son
f I n	l i:	s V n
fin-	ley
f I n	l i:
fin-	ley's
f I n	l i: z
fin-	nan
f I	n V n
fin-	ne-	gan
f I	n V	g V n
fin-	ney
f I	n i:
fin-	ni-	gan
f I	n I	g V n
fin-	nick
f I	n I k
fin-	nie
f I	n i:
fin-	ning
f I	n I N
fin-	nish
f I	n I S
fin-	stad
f I n	s t V d
finch
f I n tS
find
f aI n d
find-	lay
f I n	d l i:
find-	ley
f I n	d l i:
finds
f aI n d z
fine
f aI n
fine-	berg
f aI n	b @r g
fine-	ly
f aI n	l i:
fine-	man
f aI n	m V n
fined
f aI n d
fines
f aI n z
fink
f I N k
finks
f I N k s
fink's
f I N k s
finn
f I n
finns
f I n z
finn's
f I n z
fins
f I n z
fip-	ple
f I	p V l
fir
f @r
fir-	kins
f @r	k I n z
fir-	ma
f @r	m V
fir-	man
f @r	m V n
fir-	mans
f @r	m V n z
fir-	mer
f @r	m @r
fir-	mest
f @r	m V s t
fir-	min
f @r	m I n
fir-	ming
f @r	m I N
fire-	baugh
f aI r	b O:
fire-	bombed
f aI r	b Q m d
fire-	bombs
f aI r	b Q m z
fire-	figh-	ter
f aI r	f aI	t @r
fire-	figh-	ting
f aI r	f aI	t I N
fire-	fight
f aI r	f aI t
fire-	fights
f aI r	f aI t s
fire-	man
f aI r	m V n
fire-	man's
f aI r	m V n z
fire-	men
f aI r	m V n
fire-	po-	wer
f aI r	p aU	@r
fire-	stone
f aI r	s t @U n
fire-	stone's
f aI r	s t @U n z
fire-	storm
f aI r	s t O@ m
fire-	wall
f aI r	w Q l
fire-	work
f aI r	w @r k
fire-	works
f aI r	w @r k s
firm
f @r m
firm-	ly
f @r m	l i:
firm-	ness
f @r m	n V s
firmed
f @r m d
firms
f @r m z
firm's
f @r m z
firs
f @r z
first
f @r s t
first-	born
f @r s	t b O@ n
first-	hand
f @r s	t h { n d
first-	ly
f @r s	t l i:
firsts
f @r s t s
firth
f @r T
fis-	cal
f I s	k V l
fis-	cal-	ly
f I s	k V	l i:
fis-	cher
f I	S @r
fis-	cher's
f I	S @r z
fis-	cus
f I s	k V s
fis-	sile
f I	s V l
fis-	sio-	na-	ble
f I	S V	n V	b V l
fis-	sion
f I	S V n
fis-	sure
f I	S @r
fis-	sured
f I	S @r d
fis-	sures
f I	S @r z
fis-	ted
f I s	t V d
fis-	ter
f I s	t @r
fis-	ti-	cuff
f I s	t I	k V f
fis-	ti-	cuffs
f I s	t I	k V f s
fisc
f I s k
fisch
f I S
fisch-	bein
f I S	b aI n
fish
f I S
fish-	back
f I S	b { k
fish-	bein
f I S	b aI n
fish-	bowl
f I S	b @U l
fish-	ea-	ter
f I	S i:	t @r
fish-	kill
f I S	k I l
fish-	man
f I S	m { n
fish-	mon-	ger
f I S	m Q N	g @r
fished
f I S t
fisk
f I s k
fiske
f I s k
fiske's
f I s k s
fisk's
f I s k s
fist
f I s t
fist-	ful
f I s	t f V l
fists
f I s t s
fit
f I t
fit-	ful
f I t	f V l
fit-	ful-	ly
f I t	f V	l i:
fit-	ness
f I t	n V s
fit-	ted
f I	t V d
fit-	ter
f I	t @r
fit-	test
f I	t V s t
fit-	ti-	pal-	di
f I	t I	p Q l	d i:
fit-	ting
f I	t I N
fit-	ting-	ly
f I	t I N	l i:
fit-	tings
f I	t I N z
fit-	ton
f I	t V n
fitch
f I tS
fitch-	burg
f I tS	b @r g
fits
f I t s
fitt
f I t
fitts
f I t s
fitz
f I t s
fitz-	ge-	rald
f I t	s dZ e@	V l d
fitz-	ge-	rald's
f I t	s dZ e@	V l d z
fitz-	hugh
f I t	s h j u:
fitz-	pat-	rick
f I t	s p { t	r I k
fitz-	roy
f I t	s r OI
fitz-	sim-	mons
f I t	s I	m V n z
fitz-	wil-	liam
f I t	s w I l	j V m
five
f aI v
five-	fold
f aI v	f @U l d
fives
f aI v z
five's
f aI v z
fix
f I k s
fix-	ture
f I k	s tS @r
fix-	tures
f I k	s tS @r z
fixed
f I k s t
fiz-	z-	ling
f I	z V	l I N
fiz-	zle
f I	z V l
fiz-	zled
f I	z V l d
fiz-	zles
f I	z V l z
fizz
f I z
fjeld
f j e l d
fjord
f j O@ d
fjords
f j O@ d z
fla-	gel-	la
f l V	dZ e	l V
fla-	gel-	la-	ted
f l {	dZ V	l eI	t V d
fla-	gel-	late
f l {	dZ V	l eI t
fla-	gel-	lum
f l V	dZ e	l V m
fla-	geo-	let
f l {	dZ V	l e t
fla-	mer
f l eI	m @r
fla-	mi-	ni-	an
f l V	m I	n i:	V n
fla-	min-	go
f l V	m I N	g @U
fla-	min-	gos
f l V	m I N	g @U z
fla-	ming
f l eI	m I N
fla-	na-	gan
f l {	n V	g V n
fla-	ni-	gan
f l {	n I	g V n
fla-	ni-	gan's
f l {	n I	g V n z
fla-	ring
f l e@	I N
fla-	sher
f l {	S @r
fla-	shers
f l {	S @r z
fla-	sher's
f l {	S @r z
fla-	shes
f l {	S V z
fla-	shi-	er
f l {	S i:	@r
fla-	shing
f l {	S I N
fla-	sh's
f l {	S V z
fla-	shy
f l {	S i:
fla-	thead
f l { t	h e d
fla-	theads
f l { t	h e d z
fla-	tu-	lent
f l {	tS V	l V n t
fla-	vi-	a
f l {	v i:	V
fla-	vi-	o
f l Q	v i:	@U
fla-	vi-	us
f l eI	v i:	V s
fla-	vin
f l eI	v I n
fla-	vo-	ring
f l eI	v @r	I N
fla-	vo-	rings
f l eI	v @r	I N z
fla-	vo-	rist
f l eI	v @r	I s t
fla-	vo-	rists
f l eI	v @r	I s t s
fla-	vor
f l eI	v @r
fla-	vor-	ful
f l eI	v @r	f V l
fla-	vored
f l eI	v @r d
fla-	vors
f l eI	v @r z
flab
f l { b
flab-	ber-	gas-	ted
f l {	b @r	g { s	t V d
flab-	ber-	gast
f l {	b @r	g { s t
flab-	by
f l {	b i:
flac-	cid
f l { k	s I d
flack
f l { k
flag
f l { g
flag-	ging
f l {	g I N
flag-	ler
f l { g	l @r
flag-	pole
f l { g	p @U l
flag-	poles
f l { g	p @U l z
flag-	rant
f l eI g	r V n t
flag-	rant-	ly
f l eI g	r V n	t l i:
flag-	ship
f l { g	S I p
flag-	ships
f l { g	S I p s
)"
R"(flag-	staff
f l { g	s t { f
flag-	stone
f l { g	s t @U n
flagg
f l { g
flagged
f l { g d
flags
f l { g z
flaher-	ty
f l e@	t i:
flai-	ling
f l eI	l I N
flail
f l eI l
flakes
f l eI k s
flam-	ma-	bi-	li-	ty
f l {	m V	b I	l V	t i:
flam-	ma-	ble
f l {	m V	b V l
flames
f l eI m z
flamm
f l { m
flan
f l { n
flan-	ders
f l { n	d @r z
flan-	ges
f l { n	dZ V z
flan-	king
f l { N	k I N
flan-	na
f l {	n V
flan-	ne-	ry
f l {	n @r	i:
flan-	nel
f l {	n V l
flan-	neled
f l {	n V l d
flan-	nels
f l {	n V l z
flange
f l { n dZ
flank
f l { N k
flanked
f l { N k t
flanks
f l { N k s
flann
f l { n
flap
f l { p
flap-	per
f l {	p @r
flap-	pers
f l {	p @r z
flap-	ping
f l {	p I N
flapped
f l { p t
flaps
f l { p s
flare
f l e@
flared
f l e@ d
flares
f l e@ z
flash
f l { S
flash-	back
f l { S	b { k
flash-	backs
f l { S	b { k s
flash-	bulb
f l { S	b V l b
flash-	light
f l { S	l aI t
flash-	lights
f l { S	l aI t s
flash-	point
f l { S	p OI n t
flash-	points
f l { S	p OI n t s
flashed
f l { S t
flask
f l { s k
flasks
f l { s k s
flat
f l { t
flat-	bed
f l { t	b e d
flat-	boat
f l { t	b @U t
flat-	fi-	shes
f l { t	f I	S V z
flat-	fish
f l { t	f I S
flat-	land
f l { t	l { n d
flat-	lands
f l { t	l { n d z
flat-	ly
f l { t	l i:
flat-	ness
f l { t	n V s
flat-	te-	ning
f l {	t V	n I N
flat-	te-	ring
f l {	t @r	I N
flat-	te-	ry
f l {	t @r	i:
flat-	ten
f l {	t V n
flat-	tened
f l {	t V n d
flat-	ter
f l {	t @r
flat-	tered
f l {	t @r d
flat-	tish
f l {	t I S
flat-	ware
f l { t	w e@
flat-	worm
f l { t	w @r m
flats
f l { t s
flatt
f l { t
flau-	bert
f l aU	b @r t
flaun-	ted
f l O: n	t V d
flaun-	ting
f l O: n	t I N
flaunt
f l O: n t
flaunts
f l O: n t s
flaw
f l O:
flaw-	less
f l O:	l V s
flaw-	less-	ly
f l O:	l V s	l i:
flawed
f l O: d
flawn
f l O: n
flaws
f l O: z
flax
f l { k s
flax-	man
f l { k	s m V n
flax-	seed
f l { k	s i: d
flay
f l eI
flayed
f l eI d
fle-	der-	maus
f l e	d @r	m aU s
fle-	ming
f l e	m I N
fle-	ming-	ton
f l e	m I N	t V n
fle-	mings
f l e	m I N z
fle-	ming's
f l e	m I N z
fle-	mish
f l e	m I S
fle-	sher
f l e	S @r
fle-	shy
f l e	S i:
fle-	ta
f l i:	t V
fle-	wel-	ling
f l u:	e	l I N
fle-	xes
f l e k	s V z
fle-	xi-	bi-	li-	ty
f l e k	s I	b I	l I	t i:
fle-	xi-	ble
f l e k	s I	b V l
fle-	xib-	ly
f l e k	s I b	l i:
fle-	xing
f l e k	s I N
fle-	xion
f l e k	S V n
flea
f l i:
fleas
f l i: z
fleck
f l e k
flecks
f l e k s
fled
f l e d
fled-	ging
f l e	dZ I N
fledg-	ling
f l e dZ	l I N
fledge
f l e dZ
fledged
f l e dZ d
flee
f l i:
flee-	cy
f l i:	s i:
flee-	ing
f l i:	I N
flee-	man
f l i:	m V n
flee-	ting
f l i:	t I N
flee-	ting-	ly
f l i:	t I N	l i:
fleece
f l i: s
fleeced
f l i: s t
fleer
f l I@
flees
f l i: z
fleet
f l i: t
fleet-	wood
f l i: t	w U d
fleets
f l i: t s
fleet's
f l i: t s
flei-	scher
f l aI	S @r
flei-	sher
f l aI	S @r
fleisch-	man
f l aI S	m V n
flem-	ming
f l e	m I N
flesh
f l e S
fleshed
f l e S t
flet-	cher
f l e	tS @r
fleu-	rette
f l @r	e t
fleu-	ry
f l U@	i:
fleur
f l @r
flew
f l u:
flex
f l e k s
flex-	time
f l e k	s t aI m
flexed
f l e k s t
fli-	er
f l aI	@r
fli-	ers
f l aI	@r z
flic-	ke-	ring
f l I	k @r	I N
flic-	ker
f l I	k @r
flic-	kered
f l I	k @r d
flic-	kers
f l I	k @r z
flic-	king
f l I	k I N
flick
f l I k
flicks
f l I k s
flied
f l aI d
flies
f l aI z
fligh-	ty
f l aI	t i:
flight
f l aI t
flight-	less
f l aI t	l V s
flights
f l aI t s
flight's
f l aI t s
flim-	flam
f l I m	f l { m
flim-	si-	est
f l I m	z i:	V s t
flim-	sy
f l I m	z i:
flin-	ching
f l I n	tS I N
flin-	ders
f l I n	d @r z
flin-	ging
f l I	N I N
flin-	ty
f l I n	t i:
flinch
f l I n tS
flinched
f l I n tS t
fling
f l I N
flings
f l I N z
flinn
f l I n
flint
f l I n t
flint-	lock
f l I n	t l Q k
flint-	locks
f l I n	t l Q k s
flint-	stone
f l I n	t s t @U n
flint-	stones
f l I n	t s t @U n z
flints
f l I n t s
flint's
f l I n t s
flip
f l I p
flip-	pant
f l I	p V n t
flip-	per
f l I	p @r
flip-	pers
f l I	p @r z
flip-	pin
f l I	p I n
flip-	ping
f l I	p I N
flipped
f l I p t
flips
f l I p s
flir-	ta-	tion
f l @r	t eI	S V n
flir-	ta-	tions
f l @r	t eI	S V n z
flir-	ta-	tious
f l @r	t eI	S V s
flir-	ted
f l @r	t V d
flir-	ting
f l @r	t I N
flirt
f l @r t
flirts
f l @r t s
flit
f l I t
flit-	ting
f l I	t I N
flo
f l @U
flo-	ra
f l O@	V
flo-	ral
f l O@	V l
flo-	ral-	ly
f l O@	V	l i:
flo-	rance
f l O@	V n s
flo-	ren-	ce's
f l O@	V n	s V z
flo-	ren-	ti-	na
f l O@	e n	t i:	n V
flo-	ren-	tine
f l O@	V n	t i: n
flo-	rence
f l O@	V n s
flo-	res
f l O@	e z
flo-	rey
f l O@	i:
flo-	ri
f l O@	i:
flo-	ri-	a
f l O@	i:	V
flo-	ri-	an
f l O@	i:	V n
flo-	ri-	da
f l O@	I	d V
flo-	ri-	da's
f l O@	I	d V z
flo-	ri-	di-	an
f l O@	I	d i:	V n
flo-	ri-	di-	ans
f l O@	I	d i:	V n z
flo-	ri-	ne
f l O@	i:	n i:
flo-	ri-	o
f l O@	i:	@U
flo-	ri-	o's
f l O@	i:	@U z
flo-	rid
f l O@	I d
flo-	rin
f l O@	I n
flo-	rin-	da
f l O@	i: n	d V
flo-	ris
f l O@	I s
flo-	rist
f l Q@	I s t
flo-	rists
f l O@	I s t s
flo-	ro
f l O@	@U
flo-	ry
f l O@	i:
flo-	ta-	tion
f l @U	t eI	S V n
flo-	til-	la
f l @U	t I	l V
flo-	tow
f l Q	t aU
flo-	ur
f l aU	@r
flo-	urs
f l aU	@r z
flo-	we-	ring
f l aU	@r	I N
flo-	we-	ry
f l aU	@r	i:
flo-	wer
f l aU	@r
flo-	wer-	pot
f l aU	@r	p Q t
flo-	wered
f l aU	@r d
flo-	wers
f l aU	@r z
flo-	wing
f l @U	I N
floa-	ted
f l @U	t V d
floa-	ter
f l @U	t @r
floa-	ters
f l @U	t @r z
floa-	ting
f l @U	t I N
float
f l @U t
floats
f l @U t s
floc
f l Q k
floc-	king
f l Q	k I N
flock
f l Q k
flocked
f l Q k t
flocks
f l Q k s
floe
f l @U
flog
f l Q g
flog-	ging
f l Q	g I N
flom
f l Q m
floo-	ded
f l V	d V d
floo-	ding
f l V	d I N
floo-	ring
f l O@	I N
flood
f l V d
flood-	gate
f l V d	g eI t
flood-	gates
f l V d	g eI t s
flood-	light
f l V d	l aI t
flood-	lights
f l V d	l aI t s
flood-	plain
f l V d	p l eI n
flood-	wa-	ter
f l V d	w O:	t @r
flood-	wa-	ters
f l V d	w O:	t @r z
floods
f l V d z
flook
f l U k
floor
f l O@
floor-	board
f l O@	b O@ d
floor-	boards
f l O@	b O@ d z
floored
f l O@ d
floors
f l O@ z
flop
f l Q p
flop-	ping
f l Q	p I N
flop-	py
f l Q	p i:
flop-	ti-	cal
f l Q p	t I	k V l
flopped
f l Q p t
flops
f l Q p s
flor
f l O@
flor-	rie
f l O@	i:
flor-	ry
f l O@	i:
flor-	sheim
f l O@	S aI m
flore
f l O@
flos-	sie
f l O:	s i:
floss
f l Q s
flot-	sam
f l Q t	s V m
flou-	ri-	shes
f l @r	I	S V z
flou-	ri-	shing
f l @r	I	S I N
flou-	rish
f l @r	I S
flou-	rished
f l @r	I S t
flou-	ted
f l aU	t V d
flou-	ting
f l aU	t I N
floun-	ces
f l aU n	s V z
floun-	de-	ring
f l aU n	d @r	I N
floun-	der
f l aU n	d @r
floun-	dered
f l aU n	d @r d
floun-	ders
f l aU n	d @r z
flounce
f l aU n s
flout
f l aU t
flow
f l @U
flowe
f l @U
flowed
f l @U d
flown
f l @U n
flows
f l @U z
floy
f l OI
floyd
f l OI d
flu
f l u:
flu-	en-	cy
f l u:	V n	s i:
flu-	ent
f l u:	V n t
flu-	ent-	ly
f l u:	V n	t l i:
flu-	i-	di-	ty
f l u:	I	d I	t i:
flu-	id
f l u:	I d
flu-	ids
f l u:	I d z
flu-	ker
f l u:	k @r
flu-	or's
f l u:	@r z
flu-	shes
f l V	S V z
flu-	shing
f l V	S I N
flu-	tist
f l u:	t I s t
flu-	ty
f l u:	t i:
flu-	vi-	al
f l u:	v i:	V l
flu-	xio-	nal
f l V k	S V	n V l
flubs
f l V b z
fluc-	tu-	a-	ted
f l V k	tS V	w eI	t V d
fluc-	tu-	a-	ting
f l V k	tS V	w eI	t I N
fluc-	tu-	a-	tion
f l V k	tS u:	eI	S V n
fluc-	tu-	a-	tions
f l V k	tS u:	eI	S V n z
fluc-	tu-	ate
f l V k	tS V	w eI t
fluc-	tu-	ates
f l V k	tS u:	eI t s
flue
f l u:
fluf-	fi-	er
f l V	f i:	@r
fluf-	fy
f l V	f i:
fluff
f l V f
fluffed
f l V f t
fluffs
f l V f s
fluke
f l u: k
flukes
f l u: k s
fluo-	ri-	da-	tion
f l U@	I	d eI	S V n
fluo-	ride
f l U@	aI d
fluo-	rides
f l U@	aI d z
fluo-	rine
f l U@	i: n
fluo-	rite
f l U@	aI t
fluo-	ro-	car-	bon
f l U@	@U	k Q@	b V n
fluo-	ro-	car-	bons
f l U@	@U	k Q@	b V n z
fluo-	ro-	me-	ter
f l U@	Q	m V	t @r
fluors-	par
f l U@ s	p Q@
flur-	ried
f l @r	i: d
flur-	ries
f l @r	i: z
flur-	ry
f l @r	i:
flus
f l u: z
flus-	ter
f l V s	t @r
flus-	tered
f l V s	t @r d
flush
f l V S
flushed
f l V S t
flut-	te-	ring
f l V	t @r	I N
flut-	ter
f l V	t @r
flut-	tered
f l V	t @r d
flut-	ters
f l V	t @r z
flute
f l u: t
flutes
f l u: t s
flux
f l V k s
fly
f l aI
fly-	by
f l aI	b aI
fly-	cat-	cher
f l aI	k {	tS @r
fly-	er
f l aI	@r
fly-	ers
f l aI	@r z
fly-	ing
f l aI	I N
fly-	pa-	per
f l aI	p eI	p @r
fly-	way
f l aI	w eI
fly-	wheel
f l aI	w i: l
flynn
f l I n
flyt-	rap
f l aI t	r { p
fo-	cal
f @U	k V l
fo-	cu-	ses
f @U	k V	s V z
fo-	cu-	sing
f @U	k V	s I N
fo-	cus
f @U	k V s
fo-	cused
f @U	k V s t
fo-	cussed
f @U	k V s t
fo-	gar-	ty
f Q	g Q@	t i:
fo-	gel
f @U	g V l
fo-	gle
f @U	g V l
fo-	gy
f @U	g i:
fo-	ia
f @U	j V
fo-	ley
f @U	l i:
fo-	ley's
f @U	l i: z
fo-	li-	a-	tion
f @U	l i:	eI	S V n
fo-	li-	ate
f @U	l i:	eI t
fo-	liage
f @U	l I dZ
fo-	lic
f Q	l I k
fo-	men-	ted
f @U	m e n	t V d
fo-	men-	ting
f @U	m e n	t I N
fo-	men-	to
f @U	m e n	t @U
fo-	ment
f @U	m e n t
fo-	ra
f O@	V
fo-	ra-	ges
f O@	V	dZ V z
fo-	ra-	ging
f O@	I	dZ I N
fo-	ra-	ker
f O@	V	k @r
fo-	ra-	men
f @r	eI	m V n
fo-	rage
f O@	I dZ
fo-	ray
f O@	eI
fo-	rays
f O@	eI z
fo-	rbad
f @r	b { d
fo-	rbade
f @r	b eI d
fo-	rearm
f O@	Q@ m
fo-	reig-	ner
f O@	I	n @r
fo-	reig-	ners
f Q@	I	n @r z
fo-	reign
f O@	I n
fo-	res-	ted
f O@	V s	t V d
fo-	res-	ter
f O@	V s	t @r
fo-	res-	ters
f O@	V s	t @r z
fo-	rest
f O@	V s t
fo-	rest-	ry
f O@	V s	t r i:
fo-	rest-	ville
f O@	e s	t v I l
fo-	rests
f O@	V s t s
fo-	rest's
f O@	V s t s
fo-	rex
f O@	e k s
fo-	rint
f O@	I n t
fo-	rints
f O@	I n t s
fo-	rum
f O@	V m
fo-	rums
f O@	V m z
fo-	rum's
f O@	V m z
fo-	sa-	max
f Q	s V	m { k s
fo-	xes
f Q k	s V z
fo-	x's
f Q k	s V z
fo-	xy
f Q k	s i:
fo-	yer
f OI	@r
foa-	ling
f @U	l I N
foa-	ming
f @U	m I N
foa-	my
f @U	m i:
foal
f @U l
foam
f @U m
foams
f @U m z
fob
f O: b
fod-	der
f Q	d @r
foe
f @U
foes
f @U z
fog
f Q g
fog-	gi-	est
f Q	g i:	V s t
fog-	gy
f Q	g i:
fogg
f Q g
foi-	ble
f OI	b V l
foi-	bles
f OI	b V l z
foi-	ling
f OI	l I N
foie
f OI
foil
f OI l
foiled
f OI l d
foils
f OI l z
fois-	ted
f OI s	t V d
fois-	ter
f OI s	t @r
foist
f OI s t
fok-	ker
f Q	k @r
fol-	ded
f @U l	d V d
fol-	den
f @U l	d V n
fol-	der
f @U l	d @r
fol-	ders
f @U l	d @r z
fol-	ding
f @U l	d I N
fol-	ger
f @U l	dZ @r
fol-	gers
f @U l	dZ @r z
fol-	ger's
f @U l	dZ @r z
fol-	kish
f @U	k I S
fol-	lett
f Q	l V t
fol-	lette
f Q	l e t
fol-	li-	cle
f Q	l I	k V l
fol-	li-	cles
f Q	l I	k V l z
fol-	lies
f Q	l i: z
fol-	lis
f Q	l I s
fol-	lo-	wer
f Q	l @U	@r
fol-	lo-	wers
f Q	l @U	@r z
fol-	lo-	wing
f Q	l @U	I N
fol-	lo-	wings
f Q	l @U	I N z
fol-	low
f Q	l @U
fol-	low-	up
f Q	l @U	V p
fol-	lowed
f Q	l @U d
fol-	lows
f Q	l @U z
fol-	ly
f Q	l i:
fol-	som
f @U l	s V m
fold
f @U l d
folds
f @U l d z
folk
f @U k
folk-	lore
f @U k	l O@
folk-	rock
f @U k	r Q k
folk-	sy
f @U k	s i:
folk-	tale
f @U k	t eI l
folk-	way
f @U k	w eI
folk-	ways
f @U k	w eI z
folks
f @U k s
foll-	mer
f Q l	m @r
fon-	d-	ling
f Q n	d V	l I N
fon-	da
f Q n	d V
fon-	da's
f Q n	d V z
fon-	der
f Q n	d @r
fon-	dest
f Q n	d V s t
fon-	dle
f O: n	d V l
fon-	dled
f O: n	d V l d
fon-	due
f Q n	d j u:
fon-	dues
f Q n	d u: z
fon-	se-	ca
f @U n	s e	k V
fon-	ta-	na
f O: n	t {	n V
fon-	taine
f O: n	t eI n
fon-	tes
f @U n	t e s
fon-	ville
f @U n	v I l
fond
f Q n d
fond-	ly
f Q n	d l i:
fond-	ness
f Q n	d n V s
fone
f @U n
fong
f O: N
fons
f Q n z
font
f Q n t
fonts
f Q n t s
foo
f u:
foo-	le-	ry
f u:	l @r	i:
foo-	ling
f u:	l I N
foo-	lish
f u:	l I S
foo-	lish-	ly
f u:	l I S	l i:
foo-	lish-	ness
f u:	l I S	n V s
foo-	tage
f U	t I dZ
foo-	ted
f U	t V d
foo-	ter
f U	t @r
foo-	ting
f U	t I N
food
f u: d
food-	stuff
f u: d	s t V f
food-	stuffs
f u: d	s t V f s
food-	ways
f u: d	w eI z
foods
f u: d z
food's
f u: d z
fool
f u: l
fool-	har-	dy
f u: l	h Q@	d i:
fool-	proof
f u: l	p r u: f
fooled
f u: l d
fools
f u: l z
fool's
f u: l z
foos
f u: z
foot
f U t
foot-	ball
f U t	b O: l
foot-	balls
f U t	b O: l z
foot-	ball's
f U t	b O: l z
foot-	fall
f U t	f O: l
foot-	hill
f U t	h I l
foot-	hills
f U t	h I l z
foot-	hold
f U t	h @U l d
foot-	holds
f U t	h @U l d z
foot-	light
f U t	l aI t
foot-	lights
f U t	l aI t s
foot-	loose
f U t	l u: s
foot-	man
f U t	m V n
foot-	no-	ted
f U t	n @U	t V d
foot-	no-	ting
f U t	n @U	t I N
foot-	note
f U t	n @U t
foot-	notes
f U t	n @U t s
foot-	path
f U t	p { T
foot-	print
f U t	p r I n t
foot-	prints
f U t	p r I n t s
foot-	race
f U t	r eI s
foot-	step
f U t	s t e p
foot-	steps
f U t	s t e p s
foot-	wall
f U t	w O: l
foot-	wear
f U t	w e@
foot-	work
f U t	w @r k
foote
f U t
foote's
f U t s
fop
f O: p
for
f O@
for-	bea-	rance
f O@	b e@	V n s
for-	bid
f @r	b I d
for-	bid-	den
f O@	b I	d V n
for-	bid-	ding
f @r	b I	d I N
for-	bids
f @r	b I d z
for-	ceps
f O@	s e p s
for-	ces
f O@	s V z
for-	ce's
f O@	s V z
for-	ci-	ble
f O@	s I	b V l
for-	ci-	er
f O@	k i:	@r
for-	cib-	ly
f O@	s I b	l i:
for-	cing
f O@	s I N
for-	dham
f O@	d V m
for-	dyce
f O@	d aI s
for-	e-	ver
f @r	e	v @r
for-	fei-	ta-	ble
f O@	f I	t V	b V l
for-	fei-	ted
f O@	f I	t I d
for-	fei-	ting
f O@	f I	t I N
for-	fei-	ture
f O@	f I	tS @r
for-	fei-	tures
f O@	f I	tS @r z
for-	feit
f O@	f I t
for-	gave
f @r	g eI v
for-	ge-	ries
f O@	dZ @r	i: z
for-	ge-	ry
f O@	dZ @r	i:
for-	ger
f O@	dZ @r
for-	gers
f O@	dZ @r z
for-	ges
f O@	dZ V z
for-	get
f @r	g e t
for-	get-	ful
f O@	g e t	f V l
for-	get-	ta-	ble
f O@	g e	t V	b V l
for-	get-	ting
f @r	g e	t I N
for-	gets
f @r	g e t s
for-	gette
f @r	Z e t
for-	gi-	va-	ble
f O@	g I	v V	b V l
for-	gi-	ven
f @r	g I	v V n
for-	gi-	ving
f @r	g I	v I N
for-	gie
f O@	dZ i:
for-	ging
f O@	dZ I N
for-	gings
f O:	dZ I N z
for-	give
f @r	g I v
for-	give-	ness
f @r	g I v	n V s
for-	gives
f @r	g I v z
for-	go
f O@	g @U
for-	go-	ing
f O@	g @U	I N
for-	goes
f O@	g @U z
for-	gone
f O@	g Q n
for-	got
f @r	g Q t
for-	got-	ten
f @r	g Q	t V n
for-	ker
f O@	k @r
for-	key
f O@	k i:
for-	king
f O@	k I N
for-	lorn
f @r	l O@ n
for-	ma
f O@	m V
for-	ma-	li-	sm
f O@	m V	l I	z V m
for-	ma-	li-	ties
f O@	m {	l I	t i: z
for-	ma-	li-	ty
f O@	m {	l I	t i:
for-	ma-	li-	za-	tion
f O@	m V	l I	z eI	S V n
for-	ma-	li-	zes
f O@	m V	l aI	z V z
for-	ma-	li-	zing
f O@	m V	l aI	z I N
for-	ma-	list
f O@	m V	l V s t
for-	ma-	lize
f O@	m V	l aI z
for-	ma-	lized
f O@	m V	l aI z d
for-	ma-	tion
f O@	m eI	S V n
for-	ma-	tions
f O@	m eI	S V n z
for-	ma-	tive
f O@	m V	t I v
for-	mal
f O@	m V l
for-	mal-	de-	hyde
f O@	m { l	d V	h aI d
for-	mal-	ly
f O@	m V	l i:
for-	man
f O@	m { n
for-	mant
f O@	m V n t
for-	mants
f O@	m V n t s
for-	mat
f O@	m { t
for-	mats
f O@	m { t s
for-	mer
f O@	m @r
for-	mer-	ly
f O@	m @r	l i:
for-	mi-	ca
f O@	m aI	k V
for-	mi-	ca's
f O@	m aI	k V z
for-	mi-	da-	ble
f O@	m I	d V	b V l
for-	mi-	dab-	ly
f O@	m I	d V b	l i:
for-	mic
f O@	m I k
for-	ming
f O@	m I N
for-	mo-	sa
f O@	m @U	s V
for-	mo-	so
f O@	m @U	s @U
for-	mu-	la
f O@ m	j V	l V
for-	mu-	la-	ic
f O@ m	j V	l eI	I k
for-	mu-	la-	ry
f O@ m	j V	l e@	i:
for-	mu-	la-	ted
f O@ m	j V	l eI	t V d
for-	mu-	la-	ting
f O@ m	j V	l eI	t I N
for-	mu-	la-	tion
f O@ m	j u:	l eI	S V n
for-	mu-	la-	tions
f O@ m	j u:	l eI	S V n z
for-	mu-	las
f O@ m	j V	l V z
for-	mu-	late
f O@ m	j V	l eI t
for-	mu-	lates
f O@ m	j V	l eI t s
for-	ney
f O@	n i:
for-	rer
f O:	@r r
for-	res-	tal
f O@	V s	t V l
for-	res-	ter
f O@	V s	t @r
for-	rest
f O@	V s t
for-	sa-	ken
f O@	s eI	k V n
for-	sa-	king
f O@	s eI	k I N
for-	sake
f O@	s eI k
for-	see
f @r	s i:
for-	see-	a-	ble
f O@	s i:	V	b V l
for-	sook
f O@	s U k
for-	sy-	thi-	a
f O@	s I	T i:	V
for-	sy-	thi-	as
f O@	s I	T i:	V z
for-	syth
f O@	s aI T
for-	sythe
f O@	s aI D
for-	tas
f O@	t V s
for-	te
f O@	t eI
for-	tes
f O@	t eI z
for-	ti-	er
f O@	t i:	@r
for-	ti-	er's
f O@	t i:	@r z
for-	ti-	eth
f O@	t i:	V T
for-	ti-	fi-	ca-	tion
f O@	t I	f I	k eI	S V n
for-	ti-	fi-	ca-	tions
f O@	t I	f I	k eI	S V n z
for-	ti-	fi-	er
f O@	t I	f aI	@r
for-	ti-	fi-	ers
f O@	t I	f aI	@r z
for-	ti-	fied
f O@	t I	f aI d
for-	ti-	fy
f O@	t I	f aI
for-	ti-	fy-	ing
f O@	t I	f aI	I N
for-	ti-	tude
f O@	t I	t u: d
for-	ties
f O@	t i: z
for-	tin
f O@	t I n
for-	tis
f O@	t I s
for-	tres-	ses
f O@ t	r V	s V z
for-	tress
f O@ t	r V s
for-	tu-	i-	tous
f O@	t u:	I	t V s
for-	tu-	na
f O@	t u:	n V
for-	tu-	na-	to
f O@	t u:	n Q	t @U
for-	tu-	nate
f O@	tS V	n V t
for-	tu-	nate-	ly
f O@	tS V	n V t	l i:
for-	tune
f O@	tS V n
for-	tunes
f O@	tS V n z
for-	tune's
f O@	tS V n z
for-	ty
f O@	t i:
for-	ty's
f O@	t i: z
)"
R"(for-	war-	ded
f O@	w @r	d V d
for-	war-	der
f O@	w @r	d @r
for-	war-	ders
f O@	w @r	d @r z
for-	war-	ding
f O@	w @r	d I N
for-	ward
f O@	w @r d
for-	wards
f O@	w @r d z
forbe-	s's
f O@ b	z V z
forbes
f O@ b z
force
f O@ s
force-	ful
f O@ s	f V l
force-	ful-	ly
f O@ s	f V	l i:
force-	ful-	ness
f O@ s	f V l	n V s
forced
f O@ s t
ford
f O@ d
fords
f O@ d z
ford's
f O@ d z
fore
f O@
fore-	bear
f O@	b e@
fore-	bears
f O@	b e@ z
fore-	bo-	ding
f O@	b @U	d I N
fore-	bode
f O@	b @U d
fore-	brain
f O@ b	r eI n
fore-	cas-	ted
f O@	k { s	t V d
fore-	cas-	ter
f O@	k { s	t @r
fore-	cas-	ters
f O@	k { s	t @r z
fore-	cas-	ting
f O@	k { s	t I N
fore-	cast
f O@	k { s t
fore-	casts
f O@	k { s t s
fore-	clo-	ses
f O@ k	l @U	z V z
fore-	clo-	sing
f O@ k	l @U	z I N
fore-	clo-	sure
f O@ k	l @U	Z @r
fore-	clo-	sures
f O@ k	l @U	Z @r z
fore-	close
f O@ k	l @U z
fore-	closed
f O@ k	l @U z d
fore-	fa-	ther
f O@	f Q	D @r
fore-	fa-	thers
f O@	f Q	D @r z
fore-	fin-	ger
f O@	f I N	g @r
fore-	fin-	gers
f O@	f I N	g @r z
fore-	foot
f O@	f U t
)"