R"(sond-	hei-	mer
s Q n	d h aI	m @r
sond-	heim
s Q n	d h aI m
sond-	heim's
s Q n	d h aI m z
sond-	ra
s Q n	d r V
sones
s @U n z
song
s O: N
song-	bird
s O: N	b @r d
song-	birds
s O: N	b @r d z
song-	wri-	ter
s O: N	r aI	t @r
song-	wri-	ters
s O: N	r aI	t @r z
song-	wri-	ting
s O: N	r aI	t I N
songs
s O: N z
song's
s O: N z
sonne
s Q n
sons
s V n z
son's
s V n z
soo
s u:
soo-	ner
s u:	n @r
soo-	ners
s u:	n @r z
soo-	ner's
s u:	n @r z
soo-	nest
s u:	n V s t
soo-	ter
s U	t @r
soo-	thing
s u:	D I N
soo-	thing-	ly
s u:	D I N	l i:
soo-	ty
s u:	t i:
soon
s u: n
soong
s u: N
soot
s U t
sooth-	sa-	yer
s u: T	s eI	@r
sooth-	sa-	yers
s u: T	s eI	@r z
soothe
s u: D
soothed
s u: D d
soothes
s u: D z
soots
s U t s
sop
s Q p
sop-	ping
s Q	p I N
sop-	ra-	no
s V p	r Q	n @U
sop-	ra-	nos
s V p	r {	n @U z
sope
s @U p
soph-	ro-	ni-	a
s @U f	r @U	n i:	V
sopho-	more
s Q f	m O@
sopho-	mores
s Q f	m O@ z
sops
s Q p s
sor
s O@
sor-	bet
s O@	b eI
sor-	bo
s O@	b @U
sor-	bonne
s O@	b Q n
sor-	bus
s O@	b V s
sor-	ce-	rer
s O@	s @r	@r
sor-	ce-	rers
s O@	s @r	@r z
sor-	ce-	ry
s O@	s @r	i:
sor-	cha
s O@	k V
sor-	ci
s O@	tS i:
sor-	did
s O@	d I d
sor-	ghum
s O@	g V m
sor-	kin
s O@	k I n
sor-	rel
s O@	V l
sor-	rels
s O@	V l z
sor-	row
s Q@	@U
sor-	row-	ful
s Q@	@U	f V l
sor-	rows
s Q@	@U z
sor-	ry
s Q@	i:
sor-	ted
s O@	t V d
sor-	ter
s O@	t @r
sor-	ters
s O@	t @r z
sor-	tie
s O@	t i:
sor-	ties
s O@	t i: z
sor-	ting
s O@	t I N
sorce
s O@ s
sore
s O@
sore-	ly
s O@	l i:
sores
s O@ z
sorge
s O@ dZ
sort
s O@ t
sorts
s O@ t s
so's
s @U z
sos-	na
s @U s	n V
soss
s O: s
sou-	der
s aU	d @r
sou-	li-	er
s u:	l i:	@r
sou-	py
s u:	p i:
sou-	red
s aU	@r d
sou-	ris
s u:	r I s
sou-	sa
s u:	z V
sou-	sa-	phone
s u:	z V	f @U n
sou-	sa's
s u:	z V z
sou-	tar
s u:	t Q@
sou-	ter
s u:	t @r
sou-	thamp-	ton
s aU T	h { m	p t V n
sou-	thard
s aU	T @r d
sou-	ther
s V	D @r
sou-	ther-	land
s V	D @r	l V n d
sou-	ther-	ly
s V	D @r	l i:
sou-	ther-	ner
s V	D @r	n @r
sou-	ther-	ners
s V	D @r	n @r z
sou-	thern
s V	D @r n
sou-	thern-	most
s V	D @r n	m @U s t
sou-	thers
s V	D @r z
sou-	ve-	nir
s u:	v V	n I@
sou-	ve-	nirs
s u:	v V	n I@ z
sou-	za
s u:	z V
souf-	fle
s u: f	l eI
sought
s O: t
souk
s u: k
soul
s @U l
soul-	ful
s @U l	f V l
soul-	less
s @U l	l V s
soule
s aU l
souls
s @U l z
soun-	ded
s aU n	d V d
soun-	der
s aU n	d @r
soun-	dest
s aU n	d V s t
soun-	ding
s aU n	d I N
soun-	dings
s aU n	d I N z
sound
s aU n d
sound-	bite
s aU n	d b aI t
sound-	bites
s aU n	d b aI t s
sound-	ly
s aU n	d l i:
sound-	ness
s aU n	d n V s
sound-	track
s aU n	d t r { k
sound-	tracks
s aU n	d t r { k s
sounds
s aU n d z
sound's
s aU n d z
soup
s u: p
souped
s u: p t
soups
s u: p s
soup's
s u: p s
sour-	ces
s O@	s V z
sour-	cing
s O@	s I N
source
s O@ s
source-	book
s O@ s	b U k
sous
s u: z
south
s aU T
south-	bound
s aU T	b aU n d
south-	down
s aU T	d aU n
south-	down's
s aU T	d aU n z
south-	eas-	tern
s aU	T i: s	t @r n
south-	east
s aU	T i: s t
south-	east's
s aU	T i: s t s
south-	field
s aU T	f i: l d
south-	gate
s aU T	g eI t
south-	land
s aU T	l { n d
south-	land's
s aU T	l { n d z
south-	port
s aU T	p O@ t
south-	ward
s aU T	w @r d
south-	wes-	tern
s aU T	w e s	t @r n
south-	west
s aU T	w e s t
south-	west's
s aU T	w e s t s
south-	wood
s aU T	w U d
south-	worth
s aU T	w @r T
souths
s aU T s
south's
s aU T s
sov-	ran
s Q v	r V n
sov-	rans
s Q v	r V n z
sov-	ran's
s Q v	r V n z
sove-	reign
s Q v	r V n
sove-	reign-	ty
s Q v	r V n	t i:
sove-	reigns
s Q v	r V n z
sow
s aU
sow-	der
s @U	d @r
sowed
s aU d
sowle
s @U l
sowles
s @U l z
sown
s @U n
sows
s @U z
sox
s Q k s
soy
s OI
soy-	bean
s OI	b i: n
soy-	beans
s OI	b i: n z
spa
s p Q
spa-	cer
s p eI	s @r
spa-	cers
s p eI	s @r z
spa-	ces
s p eI	s V z
spa-	cey
s p eI	s i:
spa-	cing
s p eI	s I N
spa-	cious
s p eI	S V s
spa-	da
s p Q	d V
spa-	der
s p eI	d @r
spa-	ghet-	ti
s p V	g e	t i:
spa-	niard
s p { n	j @r d
spa-	niards
s p { n	j @r d z
spa-	niel
s p { n	j V l
spa-	niol
s p { n	j V l
spa-	nish
s p {	n I S
spa-	nos
s p eI	n @U z
spa-	ring
s p e@	I N
spa-	ring-	ly
s p e@	I N	l i:
spa-	sm
s p {	z V m
spa-	sms
s p {	z V m z
spa-	tial
s p eI	S V l
spa-	to-	la
s p Q	t @U	l V
spa-	tu-	la
s p {	tS U	l V
space
s p eI s
space-	band
s p eI s	b { n d
space-	bands
s p eI s	b { n d z
space-	craft
s p eI s	k r { f t
space-	craft's
s p eI s	k r { f t s
space-	port
s p eI s	p O@ t
space-	ship
s p eI s	S I p
space-	ships
s p eI s	S I p s
space-	suit
s p eI	s u: t
space-	suits
s p eI	s u: t s
space-	wal-	king
s p eI s	w Q	k I N
space-	walk
s p eI s	w Q k
space-	walks
s p eI s	w Q k s
spaced
s p eI s t
spack
s p { k
spade
s p eI d
spade-	work
s p eI d	w @r k
spades
s p eI d z
spaf-	ford
s p {	f @r d
spag-	nu-	o-	lo
s p Q g	n j u:	@U	l @U
spahn
s p Q n
spaid
s p eI d
spain
s p eI n
spain's
s p eI n z
spak
s p { k
spake
s p eI k
spal-	ding
s p O: l	d I N
spal-	la
s p {	l V
spall
s p O: l
spam
s p { m
span
s p { n
span-	dex
s p { n	d V k s
span-	g-	ler
s p { N	g V	l @r
span-	gle
s p { N	g V l
span-	gled
s p { N	g V l d
span-	king
s p { N	k I N
span-	ky
s p { n	k i:
span-	ner
s p {	n @r
span-	ning
s p {	n I N
spang
s p { N
spank
s p { N k
spanked
s p { N k t
spann
s p { n
spanned
s p { n d
spans
s p { n z
span's
s p { n z
spar
s p Q@
spar-	ger
s p Q@	dZ @r
spar-	king
s p Q@	k I N
spar-	kle
s p Q@	k V l
spar-	kled
s p Q@	k V l d
spar-	kles
s p Q@	k V l z
spar-	ky
s p Q@	k i:
spar-	ling
s p Q@	l I N
spar-	ring
s p Q@	I N
spar-	row
s p e@	@U
spar-	rows
s p e@	@U z
spar-	ta
s p Q@	t V
spar-	ta-	cus
s p Q@	t V	k V s
spar-	tan
s p Q@	t V n
spar-	tan-	burg
s p Q@	t V n	b @r g
sparc
s p Q@ k
spare
s p e@
spared
s p e@ d
spares
s p e@ z
spark
s p Q@ k
spark-	ling
s p Q@ k	l I N
spark-	ly
s p Q@ k	l i:
spark-	man
s p Q@ k	m V n
sparked
s p Q@ k t
sparkes
s p Q@ k s
sparks
s p Q@ k s
sparr
s p { r
sparred
s p Q@ d
sparse
s p Q@ s
sparse-	ly
s p Q@ s	l i:
spas
s p Q z
spat
s p { t
spat-	te-	ring
s p {	t @r	I N
spat-	ter
s p {	t @r
spat-	tered
s p {	t @r d
spat-	ters
s p {	t @r z
spate
s p eI t
spates
s p eI t s
spath
s p { T
spats
s p { t s
spatz
s p { t s
spaul-	ding
s p O: l	d I N
spaw
s p O:
spaw-	ning
s p Q	n I N
spawn
s p Q n
spawned
s p O: n d
spawns
s p Q n z
spayd
s p eI d
spe-	ci-	a-	li-	ty
s p e	S i:	{	l I	t i:
spe-	ci-	fi-	ca-	tion
s p e	s I	f I	k eI	S V n
spe-	ci-	fi-	ca-	tions
s p e	s I	f I	k eI	S V n z
spe-	ci-	fi-	ci-	ty
s p e	s I	f I	s I	t i:
spe-	ci-	fic
s p V	s I	f I k
spe-	ci-	fical-	ly
s p V	s I	f I k	l i:
spe-	ci-	fics
s p V	s I	f I k s
spe-	ci-	fied
s p e	s I	f aI d
spe-	ci-	fies
s p e	s I	f aI z
spe-	ci-	fy
s p e	s I	f aI
spe-	ci-	fy-	ing
s p e	s I	f aI	I N
spe-	ci-	men
s p e	s I	m V n
spe-	ci-	mens
s p e	s I	m V n z
spe-	cia-	li-	za-	tion
s p e	S V	l I	z eI	S V n
spe-	cia-	li-	zes
s p e	S V	l aI	z V z
spe-	cia-	li-	zing
s p e	S V	l aI	z I N
spe-	cia-	list
s p e	S V	l I s t
spe-	cia-	lists
s p e	S V	l I s t s
spe-	cia-	lize
s p e	S V	l aI z
spe-	cia-	lized
s p e	S V	l aI z d
spe-	cial
s p e	S V l
spe-	cial-	ly
s p e	S V	l i:
spe-	cial-	ties
s p e	S V l	t i: z
spe-	cial-	ty
s p e	S V l	t i:
spe-	ciali-	ties
s p e	S V l	t i: z
spe-	cials
s p e	S V l z
spe-	cies
s p i:	S i: z
spe-	cious
s p i:	S V s
spe-	cu-	la-	ted
s p e k	j V	l eI	t V d
spe-	cu-	la-	ting
s p e k	j V	l eI	t I N
spe-	cu-	la-	tion
s p e k	j V	l eI	S V n
spe-	cu-	la-	tions
s p e k	j V	l eI	S V n z
spe-	cu-	la-	tive
s p e k	j V	l V	t I v
spe-	cu-	la-	tor
s p e k	j V	l eI	t @r
spe-	cu-	la-	tors
s p e k	j V	l eI	t @r z
spe-	cu-	late
s p e k	j V	l eI t
spe-	cu-	lates
s p e k	j V	l eI t s
spe-	ran-	za
s p @r	Q n	z V
spe-	ro
s p e@	@U
spea-	ker
s p i:	k @r
spea-	ker-	ship
s p i:	k @r	S I p
spea-	kers
s p i:	k @r z
spea-	ker's
s p i:	k @r z
spea-	king
s p i:	k I N
spea-	ring
s p I@	I N
speak
s p i: k
speaks
s p i: k s
spear
s p I@
spear-	hea-	ded
s p I@	h e	d V d
spear-	hea-	ding
s p I@	h e	d I N
spear-	head
s p I@	h e d
spear-	man
s p I@	m V n
spears
s p I@ z
spec
s p e k
spec-	kle
s p e	k V l
spec-	kled
s p e	k V l d
spec-	ta-	cle
s p e k	t V	k V l
spec-	ta-	cles
s p e k	t V	k V l z
spec-	ta-	cu-	lar
s p e k	t { k	j V	l @r
spec-	ta-	cu-	lar-	ly
s p e k	t { k	j V	l @r	l i:
spec-	ta-	tor
s p e k	t eI	t @r
spec-	ta-	tors
s p e k	t eI	t @r z
spec-	ter
s p e k	t @r
spec-	ter's
s p e k	t @r z
spec-	tor
s p e k	t @r
spec-	tra
s p e k	t r V
spec-	tra's
s p e k	t r V z
spec-	tre
s p e k	t @r
spec-	tro-	graph
s p e k	t r V g	r { f
spec-	tro-	me-	ter
s p e k	t r Q	m V	t @r
spec-	tro-	met-	ry
s p e k	t r Q	m V t	r i:
spec-	tro-	sco-	py
s p e k	t r Q s	k V	p i:
spec-	trum
s p e k	t r V m
spec-	trums
s p e k	t r V m z
spec-	trum's
s p e k	t r V m z
specht
s p e k t
speck
s p e k
specks
s p e k s
specs
s p e k s
sped
s p e d
spee-	ches
s p i:	tS V z
spee-	ded
s p i:	d V d
spee-	der
s p i:	d @r
spee-	ders
s p i:	d @r z
spee-	di-	er
s p i:	d i:	@r
spee-	di-	ly
s p i:	d I	l i:
spee-	ding
s p i:	d I N
spee-	do-	me-	ter
s p i:	d Q	m V	t @r
spee-	dy
s p i:	d i:
speece
s p i: s
speech
s p i: tS
speech-	less
s p i: tS	l V s
speech-	wri-	ter
s p i: tS	r aI	t @r
speech-	wri-	ters
s p i: tS	r aI	t @r z
speed
s p i: d
speed-	boat
s p i: d	b @U t
speed-	boats
s p i: d	b @U t s
speed-	ska-	ting
s p i: d	s k eI	t I N
speed-	up
s p i:	d V p
speed-	way
s p i: d	w eI
speeds
s p i: d z
speer
s p I@
spei-	cher
s p aI	k @r
speight
s p eI t
speir
s p I@
speirs
s p I@ z
spel-	ler
s p e	l @r
spel-	lers
s p e	l @r z
spel-	ling
s p e	l I N
spel-	lings
s p e	l I N z
spel-	ling's
s p e	l I N z
spel-	man
s p e l	m V n
spell
s p e l
spell-	bin-	ding
s p e l	b aI n	d I N
spell-	bound
s p e l	b aU n d
spell-	man
s p e l	m V n
spelled
s p e l d
spells
s p e l z
speltz
s p e l t s
spen-	cer
s p e n	s @r
spen-	cer's
s p e n	s @r z
spen-	da-	ble
s p e n	d V	b V l
spen-	der
s p e n	d @r
spen-	ders
s p e n	d @r z
spen-	ding
s p e n	d I N
spen-	g-	ler
s p I	N V	l @r
spen-	ser
s p e n	s @r
spen-	ser's
s p e n	s @r z
spence
s p e n s
spend
s p e n d
spend-	thrift
s p e n	d T r I f t
spends
s p e n d z
spent
s p e n t
sper-	ling
s p @r	l I N
sper-	ry
s p e@	i:
sperm
s p @r m
sperms
s p @r m z
spets-	naz
s p e t	s n { z
spew
s p j u:
spew-	ing
s p j u:	I N
spewed
s p j u: d
spews
s p j u: z
spey
s p eI
spey-	er
s p eI	@r
sphe-	ri-	cal
s f e@	I	k V l
sphe-	roid
s f I@	OI d
sphere
s f I@
spheres
s f I@ z
sphinx
s f I N k s
spi-	cer
s p aI	s @r
spi-	ces
s p aI	s V z
spi-	cey
s p aI	s i:
spi-	cing
s p aI	s I N
spi-	cy
s p aI	s i:
spi-	der
s p aI	d @r
spi-	der-	man
s p aI	d @r	m { n
spi-	ders
s p aI	d @r z
spi-	e-	ring
s p aI	@r	I N
spi-	er
s p aI	@r
spi-	ers
s p aI	@r z
spi-	got
s p I	g V t
spi-	gots
s p I	g V t s
spi-	ker
s p aI	k @r
spi-	king
s p aI	k I N
spi-	ky
s p aI	k i:
spi-	na
s p i:	n V
spi-	nach
s p I	n V tS
spi-	nal
s p aI	n V l
spi-	no-	sa
s p i:	n @U	s V
spi-	no-	za
s p V	n @U	z V
spi-	noff
s p I	n O: f
spi-	noffs
s p I	n O: f s
spi-	ny
s p aI	n i:
spi-	ra
s p I@	V
spi-	ra-	ling
s p aI	r V	l I N
spi-	ral
s p aI	r V l
spi-	ral-	ling
s p aI	r V	l I N
spi-	raled
s p aI	r V l d
spi-	rals
s p aI	r V l z
spi-	ri-	ted
s p I@	I	t I d
spi-	ri-	ted-	ness
s p I@	I	t I d	n V s
spi-	ri-	to
s p I@	i:	t @U
spi-	ri-	tu-	a-	li-	ty
s p I@	I	tS V	w {	l I	t i:
spi-	ri-	tu-	a-	lism
s p I@	I	tS V	w V	l I z m
spi-	ri-	tu-	a-	list
s p I@	I	tS V	w V	l I s t
spi-	ri-	tu-	a-	lists
s p I@	I	tS V	w V	l I s t s
spi-	ri-	tu-	al
s p I@	I	tS V	w V l
spi-	ri-	tu-	al-	ly
s p I@	I	tS V	w V	l i:
spi-	ri-	tu-	als
s p I@	I	tS V	w V l z
spi-	rit
s p I@	I t
spi-	rits
s p I@	I t s
spi-	ro
s p I@	@U
spi-	vey
s p I	v i:
spic
s p I k
spic-	kard
s p I	k @r d
spice
s p aI s
spice-	land
s p aI s	l { n d
spiced
s p aI s t
spie
s p i:
spie-	gel
s p i:	g V l
spie-	gel-	man
s p i:	g V l	m V n
spie-	ler
s p i:	l @r
spied
s p aI d
spiel
s p i: l
spiel-	berg
s p i: l	b @r g
spiel-	berg's
s p i: l	b @r g z
spiel-	man
s p i: l	m V n
spies
s p aI z
spif-	fing
s p I	f I N
spif-	fy
s p I	f i:
spight
s p aI t
spike
s p aI k
spiked
s p aI k t
spikes
s p aI k s
spil-	lage
s p I	l I dZ
spil-	lane
s p I	l V n
spil-	ler
s p I	l @r
spil-	lers
s p I	l @r z
spil-	ling
s p I	l I N
spil-	lo-	ver
s p I	l @U	v @r
spill
s p I l
spill-	way
s p I l	w eI
spilled
s p I l d
spills
s p I l z
spilt
s p I l t
spin
s p I n
spin-	d-	ler
s p I n	d V	l @r
spin-	dle
s p I n	d V l
spin-	ner
s p I	n @r
spin-	ners
s p I	n @r z
spin-	ner's
s p I	n @r z
spin-	ney
s p I	n i:
spin-	ning
s p I	n I N
spin-	off
s p I	n O: f
spin-	ster
s p I n	s t @r
spine
s p aI n
spine-	less
s p aI n	l V s
spines
s p aI n z
spink
s p I N k
spinks
s p I N k s
spins
s p I n z
spire
s p aI r
spires
s p aI r z
spit
s p I t
spit-	ball
s p I t	b O: l
spit-	ball's
s p I t	b O: l z
spit-	ting
s p I	t I N
spit-	tle
s p I	t V l
spit-	zer
s p I t	z @r
spite
s p aI t
spite-	ful
s p aI t	f V l
spits
s p I t s
spitz
s p I t s
spla-	shes
s p l {	S V z
spla-	shing
s p l {	S I N
spla-	shy
s p l {	S i:
splash
s p l { S
splashed
s p l { S t
splat
s p l { t
splat-	ter
s p l {	t @r
splat-	tered
s p l {	t @r d
sple-	nic
s p l e	n I k
spleen
s p l i: n
splen-	did
s p l e n	d I d
splen-	did-	ly
s p l e n	d I d	l i:
splen-	dor
s p l e n	d @r
spli-	ces
s p l aI	s V z
spli-	cing
s p l aI	s I N
splice
s p l aI s
spliced
s p l aI s t
splin-	te-	ring
s p l I n	t @r	I N
splin-	te-	ry
s p l I n	t @r	i:
splin-	ter
s p l I n	t @r
splin-	tered
s p l I n	t @r d
splint
s p l I n t
splints
s p l I n t s
split
s p l I t
split-	ting
s p l I	t I N
splits
s p l I t s
splur-	ging
s p l @r	dZ I N
splurge
s p l @r dZ
splurged
s p l @r dZ d
spo-	kane
s p @U	k { n
spo-	ken
s p @U	k V n
spo-	ra-	dic
s p @r	{	d I k
spo-	ra-	dical-	ly
s p @r	{	d I k	l i:
spo-	rer
s p O@	@r
spo-	sa-	to
s p @U	s Q	t @U
spock
s p Q k
spof-	ford
s p Q	f @r d
spohr
s p Q@
spoi-	lage
s p OI	l V dZ
spoi-	ler
s p OI	l @r
spoi-	lers
s p OI	l @r z
spoi-	ling
s p OI	l I N
spoil
s p OI l
spoiled
s p OI l d
spoils
s p OI l z
spoke
s p @U k
spokes
s p @U k s
spokes-	man
s p @U k	s m V n
spokes-	men
s p @U k	s m e n
spokes-	peo-	ple
s p @U k	s p i:	p V l
spokes-	per-	son
s p @U k	s p @r	s V n
spokes-	per-	sons
s p @U k	s p @r	s V n z
spokes-	wo-	man
s p @U k	s w U	m V n
spokes-	wo-	men
s p @U k	s w I	m e n
spon-	ges
s p V n	dZ V z
spon-	gy
s p V n	dZ i:
spon-	so-	ring
s p Q n	s @r	I N
spon-	sor
s p Q n	s @r
spon-	sor-	ship
s p Q n	s @r	S I p
spon-	sor-	ships
s p Q n	s @r	S I p s
spon-	sored
s p Q n	s @r d
spon-	sors
s p Q n	s @r z
spon-	sor's
s p Q n	s @r z
spon-	ta-	ne-	i-	ty
s p Q n	t V	n i:	V	t i:
spon-	ta-	ne-	ous
s p Q n	t eI	n i:	V s
spon-	ta-	ne-	ous-	ly
s p Q n	t eI	n i:	V s	l i:
spong
s p O: N
sponge
s p V n dZ
sponged
s p V n dZ d
spoo-	fing
s p u:	f I N
spoo-	ky
s p u:	k i:
spoo-	ner
s p u:	n @r
spoof
s p u: f
spoofed
s p u: f t
spoofs
s p u: f s
spook
s p u: k
spooked
s p u: k t
spooks
s p u: k s
spool
s p u: l
spoon
s p u: n
spoon-	ful
s p u: n	f U l
spoons
s p u: n z
spoor
s p U@
spoor's
s p U@ z
spor-	ted
s p O@	t V d
spor-	ti-	er
s p O@	t i:	@r
spor-	ting
s p O@	t I N
spor-	ting-	ly
s p O@	t I N	l i:
spor-	ty
s p O@	t i:
spore
s p O@
spores
s p O@ z
sporo-	phyte
s p O@	f aI t
sporo-	phytes
s p O@	f aI t s
sport
s p O@ t
sports
s p O@ t s
sport's
s p O@ t s
sports-	cas-	ter
s p O@ t	s k { s	t @r
sports-	cas-	ters
s p O@ t	s k { s	t @r z
sports-	man
s p O@ t	s m V n
sports-	man-	ship
s p O@ t	s m V n	S I p
sports-	men
s p O@ t	s m e n
sports-	wear
s p O@ t	s w e@
sports-	wri-	ter
s p O@ t	s r aI	t @r
sports-	wri-	ters
s p O@ t	s r aI	t @r z
spot
s p Q t
spot-	less
s p Q t	l V s
spot-	ligh-	ted
s p Q t	l aI	t V d
spot-	ligh-	ting
s p Q t	l aI	t I N
spot-	light
s p Q t	l aI t
spot-	lights
s p Q t	l aI t s
spot-	ted
s p Q	t V d
spot-	ter
s p Q	t @r
spot-	ters
s p Q	t @r z
spot-	ting
s p Q	t I N
spot-	ty
s p Q	t i:
spots
s p Q t s
spou-	sal
s p aU	z V l
spou-	ses
s p aU	s V z
spou-	se's
s p aU	s V z
spou-	ted
s p aU	t V d
spou-	ting
s p aU	t I N
spouse
s p aU s
spout
s p aU t
spra-	yer
s p r eI	@r
spra-	yers
s p r eI	@r z
spra-	ying
s p r eI	I N
sprac-	k-	len
s p r {	k V	l V n
sprague
s p r eI g
sprague's
s p r eI g z
sprain
s p r eI n
sprained
s p r eI n d
sprains
s p r eI n z
sprang
s p r { N
spratt
s p r { t
spraw-	ling
s p r O:	l I N
sprawl
s p r O: l
sprawled
s p r O: l d
sprawls
s p r O: l z
spray
s p r eI
)"
R"(sprayed
s p r eI d
sprays
s p r eI z
sprea-	der
s p r e	d @r
sprea-	ding
s p r e	d I N
spread
s p r e d
spread-	sheet
s p r e d	S i: t
spread-	sheets
s p r e d	S i: t s
spreads
s p r e d z
spree
s p r i:
sprees
s p r i: z
spreng
s p r e N
sprigg
s p r I g
sprigged
s p r I g d
spright-	ly
s p r aI t	l i:
sprin-	ger
s p r I	N @r
sprin-	ger-	ville
s p r I	N @r	v I l
sprin-	ging
s p r I	N I N
sprin-	kle
s p r I N	k V l
sprin-	kled
s p r I N	k V l d
sprin-	kles
s p r I N	k V l z
sprin-	ted
s p r I n	t V d
sprin-	ter
s p r I n	t @r
sprin-	ters
s p r I n	t @r z
sprin-	ting
s p r I n	t I N
spring
s p r I N
spring-	board
s p r I N	b O@ d
spring-	dale
s p r I N	d eI l
spring-	field
s p r I N	f i: l d
spring-	field's
s p r I N	f i: l d z
spring-	steen
s p r I N	s t i: n
spring-	steen's
s p r I N	s t i: n z
spring-	time
s p r I N	t aI m
springs
s p r I N z
spring's
s p r I N z
sprink-	ler
s p r I N	k l @r
sprink-	lers
s p r I N	k l @r z
sprink-	ling
s p r I N	k l I N
sprint
s p r I n t
sprints
s p r I n t s
sprint's
s p r I n t s
sprite
s p r aI t
sproat
s p r @U t
sproc-	ket
s p r Q	k V t
sprong
s p r O: N
sprott
s p r Q t
sprou-	ted
s p r aU	t V d
sprou-	ting
s p r aU	t I N
sproul
s p r aU l
sprout
s p r aU t
sprouts
s p r aU t s
spru-	cing
s p r u:	s I N
spruce
s p r u: s
spruced
s p r u: s t
sprung
s p r V N
spry
s p r aI
spu-	ri-	ous
s p j U@	i:	V s
spud
s p V d
spuds
s p V d z
spud's
s p V d z
spun
s p V n
spun-	ky
s p V N	k i:
spunk
s p V N k
spur
s p @r
spur-	geon
s p @r	dZ V n
spur-	ling
s p @r	l I N
spur-	lock
s p @r	l Q k
spur-	ning
s p @r	n I N
spur-	ri-	er
s p @r	i:	@r
spur-	ring
s p @r	I N
spur-	ted
s p @r	t V d
spur-	ting
s p @r	t I N
spurge
s p @r dZ
spurn
s p @r n
spurned
s p @r n d
spurns
s p @r n z
spurred
s p @r d
spurs
s p @r z
spurt
s p @r t
spurts
s p @r t s
sput-	nik
s p V t	n I k
sput-	niks
s p V t	n I k s
sput-	te-	ring
s p V	t @r	I N
sput-	ter
s p V	t @r
sput-	tered
s p V	t @r d
sput-	ters
s p V	t @r z
spy
s p aI
spy-	glass
s p aI g	l { s
spy-	ing
s p aI	I N
squa-	dron
s k w Q d	r V n
squa-	drons
s k w Q d	r V n z
squa-	lid
s k w Q	l I d
squa-	lor
s k w Q	l @r
squa-	ring
s k w e@	I N
squa-	shing
s k w Q	S I N
squa-	shy
s k w Q	S i:
squab-	b-	ling
s k w Q	b V	l I N
squab-	ble
s k w Q	b V l
squab-	bled
s k w Q	b V l d
squab-	bles
s k w Q	b V l z
squad
s k w Q d
squads
s k w Q d z
squad's
s k w Q d z
squall
s k w O: l
squalls
s k w O: l z
squan-	de-	ring
s k w Q n	d @r	I N
squan-	der
s k w Q n	d @r
squan-	dered
s k w Q n	d @r d
square
s k w e@
square-	ly
s k w e@	l i:
squared
s k w e@ d
squares
s k w e@ z
squash
s k w Q S
squashed
s k w Q S t
squat
s k w Q t
squat-	ter
s k w Q	t @r
squat-	ters
s k w Q	t @r z
squat-	ting
s k w Q	t I N
squats
s k w Q t s
squaw-	king
s k w O:	k I N
squawk
s k w O: k
squawks
s k w O: k s
squea-	ker
s k w i:	k @r
squea-	kers
s k w i:	k @r z
squea-	king
s k w i:	k I N
squea-	ky
s k w i:	k i:
squea-	ling
s k w i:	l I N
squea-	mish
s k w i:	m I S
squea-	mish-	ness
s k w i:	m I S	n V s
squeak
s k w i: k
squeaked
s k w i: k t
squeaks
s k w i: k s
squeal
s k w i: l
squeals
s k w i: l z
squee-	gee
s k w i:	dZ i:
squee-	zes
s k w i:	z V z
squee-	zing
s k w i:	z I N
squeeze
s k w i: z
squeezed
s k w i: z d
squel-	ching
s k w e l	tS I N
squelch
s k w e l tS
squelched
s k w e l tS t
squi-	er
s k w aI	@r
squi-	ers
s k w aI	@r z
squi-	res
s k w aI	@r z
squi-	shy
s k w I	S i:
squibb
s k w I b
squibb's
s k w I b z
squid
s k w I d
squig-	gle
s k w I	g V l
squig-	gles
s k w I	g V l z
squin-	ting
s k w I n	t I N
squint
s k w I n t
squir-	ming
s k w @r	m I N
squir-	rel
s k w @r	V l
squir-	reled
s k w @r	V l d
squir-	rels
s k w @r	V l z
squir-	ted
s k w @r	t V d
squir-	ting
s k w @r	t I N
squire
s k w aI r
squirm
s k w @r m
squirms
s k w @r m z
squirt
s k w @r t
squirts
s k w @r t s
sram
S r { m
sri
S r i:
sri-	lan-	ka
s r i:	l { N	k V
sri-	na-	gar
s r i:	n V	g Q@
st
s t r i: t
sta
s t V
sta-	b-	ler
s t eI	b V	l @r
sta-	b-	lest
s t eI	b V	l V s t
sta-	bi-	li-	ty
s t V	b I	l I	t i:
sta-	bi-	li-	za-	tion
s t eI	b I	l I	z eI	S V n
sta-	bi-	li-	zer
s t eI	b I	l aI	z @r
sta-	bi-	li-	zers
s t eI	b I	l aI	z @r z
sta-	bi-	li-	zes
s t eI	b I	l aI	z V z
sta-	bi-	li-	zing
s t eI	b I	l aI	z I N
sta-	bi-	lize
s t eI	b I	l aI z
sta-	bi-	lized
s t eI	b I	l aI z d
sta-	bile
s t eI	b I l
sta-	ble
s t eI	b V l
sta-	bles
s t eI	b V l z
sta-	cey
s t eI	s i:
sta-	cia
s t Q	tS V
sta-	cie
s t {	k i:
sta-	cy
s t eI	s i:
sta-	der
s t eI	d @r
sta-	di-	a
s t eI	d i:	V
sta-	di-	um
s t eI	d i:	V m
sta-	di-	ums
s t eI	d i:	V m z
sta-	di-	um's
s t eI	d i:	V m z
sta-	ger
s t eI	dZ @r
sta-	ges
s t eI	dZ V z
sta-	ging
s t eI	dZ I N
sta-	ker
s t eI	k @r
sta-	king
s t eI	k I N
sta-	ley
s t eI	l i:
sta-	ley's
s t eI	l i: z
sta-	li-	ni-	sm
s t Q	l I	n I	z V m
sta-	li-	ni-	za-	tion
s t Q	l I	n I	z eI	S V n
sta-	li-	nist
s t Q	l I	n I s t
sta-	li-	nists
s t Q	l I	n I s t s
sta-	li-	nize
s t {	l I	n aI z
sta-	lin
s t Q	l I n
sta-	lin-	grad
s t Q	l I n	g r { d
sta-	lin's
s t Q	l I n z
sta-	mi-	na
s t {	m I	n V
sta-	nek
s t {	n I k
sta-	nis-	las
s t V	n I s	l V s
sta-	nis-	law
s t {	n I s	l O:
sta-	p-	ler
s t eI	p V	l @r
sta-	p-	lers
s t eI	p V	l @r z
sta-	p-	ling
s t eI	p V	l I N
sta-	ple
s t eI	p V l
sta-	ple-	ton
s t eI	p V l	t V n
sta-	pled
s t eI	p V l d
sta-	ples
s t eI	p V l z
sta-	rer
s t e@	@r
sta-	ring
s t e@	I N
sta-	ry
s t e@	i:
sta-	shing
s t {	S I N
sta-	ted
s t eI	t V d
sta-	ten
s t {	t V n
sta-	ter
s t eI	t @r
sta-	ters
s t eI	t @r z
sta-	ter's
s t eI	t @r z
sta-	tes-	man-	like
s t V	t e s	m V n	l aI k
sta-	tham
s t {	T V m
sta-	ti-	sm
s t eI	t I	z V m
sta-	tic
s t {	t I k
sta-	ting
s t eI	t I N
sta-	tio-	na-	ry
s t eI	S V	n e@	i:
sta-	tio-	ne-	ry
s t eI	S V	n e@	i:
sta-	tio-	ner
s t eI	S V	n @r
sta-	tio-	ners
s t eI	S V	n @r z
sta-	tio-	ning
s t eI	S V	n I N
sta-	tion
s t eI	S V n
sta-	tioned
s t eI	S V n d
sta-	tions
s t eI	S V n z
sta-	tion's
s t eI	S V n z
sta-	tis-	ti-	cal
s t V	t I s	t I	k V l
sta-	tis-	ti-	cal-	ly
s t V	t I s	t I	k V	l i:
sta-	tis-	ti-	cian
s t {	t I s	t I	S V n
sta-	tis-	ti-	cians
s t {	t I s	t I	S V n z
sta-	tis-	tic
s t V	t I s	t I k
sta-	tis-	tics
s t V	t I s	t I k s
sta-	tist
s t eI	t I s t
sta-	tists
s t eI	t I s t s
sta-	tu-	a-	ry
s t {	tS u:	e@	i:
sta-	tu-	esque
s t {	tS u:	e s k
sta-	tu-	ette
s t {	tS u:	e t
sta-	tu-	ettes
s t {	tS u:	e t s
sta-	tu-	to-	ri-	ly
s t {	tS V	t O@	V	l i:
sta-	tu-	to-	ry
s t {	tS V	t O@	i:
sta-	tue
s t {	tS u:
sta-	tues
s t {	tS u: z
sta-	ture
s t {	tS @r
sta-	tus
s t {	t V s
sta-	tute
s t {	tS u: t
sta-	tutes
s t {	tS u: t s
sta-	tute's
s t {	tS u: t s
sta-	ver
s t eI	v @r
sta-	ving
s t eI	v I N
sta-	yer
s t eI	@r
sta-	ying
s t eI	I N
staab
s t Q b
staal
s t Q l
stab
s t { b
stab-	bing
s t {	b I N
stab-	bings
s t {	b I N z
stabbed
s t { b d
stabs
s t { b z
stac-	ca-	to
s t V	k Q	t @U
stac-	ker
s t {	k @r
stac-	king
s t {	k I N
stack
s t { k
stacked
s t { k t
stacks
s t { k s
stade
s t eI d
stadt
s t { d t
staf-	fa
s t Q	f V
staf-	fer
s t {	f @r
staf-	fers
s t {	f @r z
staf-	fing
s t {	f I N
staf-	ford
s t {	f @r d
staf-	ford-	shire
s t {	f @r d	S @r
staf-	ford-	shire's
s t {	f @r d	S @r z
staf-	ford's
s t {	f @r d z
staff
s t { f
staffed
s t { f t
staffs
s t { f s
staff's
s t { f s
stag
s t { g
stag-	fla-	tion
s t { g	f l eI	S V n
stag-	ge-	ring
s t {	g @r	I N
stag-	ger
s t {	g @r
stag-	gered
s t {	g @r d
stag-	gers
s t {	g @r z
stag-	na-	ted
s t { g	n eI	t V d
stag-	na-	ting
s t { g	n eI	t I N
stag-	na-	tion
s t { g	n eI	S V n
stag-	nant
s t { g	n V n t
stag-	nate
s t { g	n eI t
stage
s t eI dZ
stage-	coach
s t eI dZ	k @U tS
stage-	craft
s t eI dZ	k r { f t
stage-	hand
s t eI dZ	h { n d
stage-	hands
s t eI dZ	h { n d z
staged
s t eI dZ d
stagg
s t { g
stahl
s t Q l
stai-	ning
s t eI	n I N
staid
s t eI d
stain
s t eI n
stain-	less
s t eI n	l V s
stained
s t eI n d
staines
s t eI n z
stains
s t eI n z
stair
s t e@
stair-	ca-	ses
s t e@	k eI	s V z
stair-	case
s t e@	k eI s
stair-	way
s t e@	w eI
stair-	ways
s t e@	w eI z
stair-	well
s t e@	w e l
stair-	wells
s t e@	w e l z
stairs
s t e@ z
stake
s t eI k
stake-	hol-	der
s t eI k	h @U l	d @r
stake-	hol-	ders
s t eI k	h @U l	d @r z
stake-	out
s t eI	k aU t
stake-	outs
s t eI	k aU t s
staked
s t eI k t
stakes
s t eI k s
stake's
s t eI k s
stal-	der
s t O: l	d @r
stal-	ker
s t O:	k @r
stal-	kers
s t O:	k @r z
stal-	king
s t O:	k I N
stal-	ky
s t O:	k i:
stal-	lard
s t {	l @r d
stal-	ler
s t O:	l @r
stal-	ling
s t O:	l I N
stal-	lings
s t O:	l I N z
stal-	lion
s t { l	j V n
stal-	lions
s t { l	j V n z
stal-	lone
s t V	l @U n
stal-	lone's
s t V	l @U n z
stal-	wart
s t O: l	w @r t
stal-	warts
s t O: l	w @r t s
stale
s t eI l
stale-	ma-	ted
s t eI l	m eI	t V d
stale-	mate
s t eI l	m eI t
stalk
s t O: k
stalked
s t O: k t
stalks
s t O: k s
stall
s t O: l
stall-	man
s t O: l	m V n
stall-	worth
s t O: l	w @r T
stalled
s t O: l d
stalls
s t O: l z
stam
s t { m
stam-	baugh
s t { m	b O:
stam-	ford
s t { m	f @r d
stam-	mer
s t {	m @r
stam-	pe-	ded
s t { m	p i:	d V d
stam-	pe-	ding
s t { m	p i:	d I N
stam-	pede
s t { m	p i: d
stam-	per
s t { m	p @r
stam-	ping
s t { m	p I N
stam-	pings
s t { m	p I N z
stamp
s t { m p
stamped
s t { m p t
stamps
s t { m p s
stan
s t { n
stan-	ber-	ry
s t { n	b e@	i:
stan-	ces
s t { n	s V z
stan-	ching
s t { n	tS I N
stan-	dar-	di-	za-	tion
s t { n	d @r	d I	z eI	S V n
stan-	dar-	di-	zing
s t { n	d @r	d aI	z I N
stan-	dar-	dize
s t { n	d @r	d aI z
stan-	dar-	dized
s t { n	d @r	d aI z d
stan-	dard
s t { n	d @r d
stan-	dard-	bea-	rer
s t { n	d @r d	b e@	@r
stan-	dard-	bea-	rers
s t { n	d @r d	b e@	@r z
stan-	dards
s t { n	d @r d z
stan-	dard's
s t { n	d @r d z
stan-	den
s t { n	d V n
stan-	der
s t { n	d @r
stan-	ding
s t { n	d I N
stan-	dings
s t { n	d I N z
stan-	dish
s t { n	d I S
stan-	field
s t { n	f i: l d
stan-	fill
s t { n	f I l
stan-	ford
s t { n	f @r d
stan-	ford's
s t { n	f @r d z
stan-	hope
s t {	n V p
stan-	leigh
s t { n	l V
stan-	ley
s t { n	l i:
stan-	ley-	town
s t { n	l i:	t aU n
stan-	ley's
s t { n	l i: z
stan-	ly
s t { n	l i:
stan-	nard
s t {	n @r d
stan-	ton
s t { n	t V n
stan-	way
s t { n	w eI
stan-	wood
s t { n	w U d
stan-	za
s t { n	z V
stan-	zas
s t { n	z V z
stance
s t { n s
stanch
s t { n tS
stanch-	field
s t { n	tS f i: l d
stanched
s t { n tS t
stand
s t { n d
stand-	by
s t { n	d b aI
stand-	bys
s t { n	d b aI z
stand-	ley
s t { n	d l i:
stand-	off
s t { n	d O: f
stand-	offs
s t { n	d O: f s
stand-	out
s t { n	d aU t
stand-	outs
s t { n	d aU t s
stand-	point
s t { n	d p OI n t
stand-	points
s t { n	d p OI n t s
stand-	still
s t { n	d s t I l
stand-	up
s t { n	d V p
stands
s t { n d z
stang
s t { N
stank
s t { N k
stan's
s t { n z
star
s t Q@
star-	bird
s t Q@	b @r d
star-	board
s t Q@	b @r d
star-	boards
s t Q@	b @r r d z
star-	buck
s t Q@	b V k
star-	bucks
s t Q@	b V k s
star-	buck's
s t Q@	b V k s
star-	cher
s t Q@	tS @r
star-	ches
s t Q@	tS V z
star-	chy
s t Q@	tS i:
star-	craft
s t Q@ k	r { f t
star-	dom
s t Q@	d V m
star-	dust
s t Q@	d V s t
star-	fish
s t Q@	f I S
star-	ga-	zer
s t Q@	g eI	z @r
star-	ga-	zers
s t Q@	g eI	z @r z
star-	gate
s t Q@	g eI t
star-	ker
s t Q@	k @r
star-	key
s t Q@	k i:
star-	let
s t Q@	l V t
star-	lets
s t Q@	l V t s
star-	light
s t Q@	l aI t
star-	like
s t Q@	l aI k
star-	lin
s t Q@	l I n
star-	ling
s t Q@	l I N
star-	lit
s t Q@	l I t
star-	ring
s t Q@	I N
star-	ry
s t Q@	i:
star-	ship
s t Q@	S I p
star-	struck
s t Q@ s	t r V k
star-	ted
s t Q@	t V d
star-	ter
s t Q@	t @r
star-	ters
s t Q@	t @r z
star-	ting
s t Q@	t I N
star-	tle
s t Q@	t V l
star-	tled
s t Q@	t V l d
star-	tles
s t Q@	t V l z
star-	va-	tion
s t Q@	v eI	S V n
star-	ving
s t Q@	v I N
starch
s t Q@ tS
starch-	like
s t Q@ tS	l aI k
starched
s t Q@ tS t
stare
s t e@
stared
s t e@ d
stares
s t e@ z
stark
s t Q@ k
stark-	ly
s t Q@ k	l i:
stark-	ness
s t Q@ k	n V s
stark-	wea-	ther
s t Q@ k	w e	D @r
starke
s t Q@ k
starks
s t Q@ k s
stark's
s t Q@ k s
starn
s t Q@ n
starns
s t Q@ n z
starr
s t Q@
starred
s t Q@ d
starrs
s t Q@ z
starr's
s t Q@ z
stars
s t Q@ z
star's
s t Q@ z
start
s t Q@ t
start-	ling
s t Q@ t	l I N
start-	ling-	ly
s t Q@ t	l I N	l i:
start-	up
s t Q@	t V p
start-	ups
s t Q@	t V p s
starts
s t Q@ t s
starve
s t Q@ v
starved
s t Q@ v d
stas-	ny
s t { s	n i:
stas-	sen
s t {	s V n
stash
s t { S
stashed
s t { S t
stat
s t { t
stat-	ler
s t { t	l @r
state
s t eI t
state-	craft
s t eI t	k r { f t
state-	hood
s t eI t	h U d
state-	hou-	ses
s t eI t	h aU	s V z
state-	house
s t eI t	h aU s
state-	less
s t eI t	l V s
state-	ly
s t eI t	l i:
state-	ment
s t eI t	m V n t
state-	ments
s t eI t	m V n t s
state-	ment's
s t eI t	m V n t s
state-	side
s t eI t	s aI d
state-	wide
s t eI t	w aI d
states
s t eI t s
state's
s t eI t s
states'
s t eI t s
states-	man
s t eI t	s m V n
states-	man-	ship
s t eI t	s m V n	S I p
states-	man's
s t eI t	s m V n z
states-	men
s t eI t	s m e n
stats
s t { t s
statz
s t { t s
stau-	der
s t aU	d @r
stau-	din-	ger
s t aU	d I	N @r
stau-	ter
s t aU	t @r
stauf-	fer
s t O:	f @r
stauf-	fer's
s t O:	f @r z
staun-	chest
s t O: n	tS V s t
staun-	ton
s t O: n	t V n
staunch
s t O: n tS
staunch-	ly
s t O: n	tS l i:
staup
s t O: p
stav-	ro-	pou-	los
s t V v	r Q	p V	l V s
stav-	ros
s t V v	r @U z
stave
s t eI v
staved
s t eI v d
staves
s t eI v z
stay
s t eI
stay-	o-	ver
s t eI	@U	v @r
stay-	ton
s t eI	t V n
stayed
s t eI d
stays
s t eI z
ste-	ber
s t i:	b @r
ste-	cher
s t e	k @r
ste-	fa
s t e	f V
ste-	fa-	nie
s t e	f V	n i:
ste-	fa-	no
s t e	f V	n @U
ste-	fan
s t e	f Q n
ste-	ger
s t i:	g @r
ste-	go-	sau-	rus
s t e	g V	s O@	V s
ste-	no
s t e	n @U
ste-	no-	gra-	pher
s t e	n V g	r V	f @r
ste-	no-	gra-	phic
s t e	n V g	r {	f I k
ste-	pha
s t e	f V
ste-	pha-	na
s t e	f Q	n V
ste-	pha-	ni
s t e	f V	n i:
ste-	pha-	ni-	a
s t V	f {	n i:	V
ste-	pha-	nie
s t e	f V	n i:
ste-	pha-	ny
s t e	f V	n i:
ste-	phan
s t e	f V n
ste-	phane
s t e	f Q n
ste-	phen
s t i:	v V n
ste-	phen-	son
s t i:	v V n	s V n
ste-	phen-	ville
s t i:	v V n	v I l
ste-	phens
s t i:	v V n z
ste-	phen's
s t i:	v V n z
ste-	re-	o
s t e@	i:	@U
ste-	re-	o-	gra-	phic
s t e@	i:	V g	r {	f I k
ste-	re-	o-	mi-	cro-	scope
s t e@	i:	@U	m aI k	r V s	k @U p
ste-	re-	o-	ty-	pi-	cal
s t e@	i:	@U	t I	p I	k V l
ste-	re-	o-	ty-	ping
s t e@	i:	V	t aI	p I N
ste-	re-	o-	type
s t e@	i:	V	t aI p
ste-	re-	o-	typed
s t e@	i:	V	t aI p t
ste-	re-	o-	types
s t e@	i:	V	t aI p s
ste-	re-	os
s t e@	i:	@U z
ste-	ri-	li-	ty
s t @r	I	l I	t i:
ste-	ri-	li-	za-	tion
s t e@	I	l I	z eI	S V n
ste-	ri-	li-	za-	tions
s t e@	I	l I	z eI	S V n z
ste-	ri-	li-	zer
s t e@	I	l aI	z @r
ste-	ri-	li-	zers
s t e@	I	l aI	z @r z
ste-	ri-	li-	zes
s t e@	I	l aI	z V z
ste-	ri-	li-	zing
s t e@	I	l aI	z I N
ste-	ri-	lize
s t e@	I	l aI z
ste-	ri-	lized
s t e@	I	l aI z d
ste-	rile
s t e@	I l
ste-	roid
s t @r	OI d
ste-	roids
s t e@	OI d z
ste-	tho-	scope
s t e	T V s	k @U p
ste-	tho-	scopes
s t e	T V s	k @U p s
ste-	va-	na
s t I	v {	n V
ste-	ve-	do-	ring
s t i:	v V	d O@	I N
ste-	ve-	dore
s t i:	v V	d O@
ste-	ve-	na
s t e	v V	n V
ste-	ven
s t i:	v V n
ste-	ven-	son
s t i:	v V n	s V n
ste-	vens
s t i:	v V n z
ste-	ven's
s t i:	v V n z
ste-	vie
s t i:	v i:
ste-	war-	des-	ses
s t u:	@r	d V	s V z
ste-	war-	dess
s t u:	@r	d V s
ste-	ward
s t u:	@r d
ste-	ward-	ship
s t u:	@r d	S I p
ste-	wards
s t u:	@r d z
ste-	wart
s t u:	@r t
ste-	wart's
s t u:	@r t s
ste-	wing
s t u:	I N
ste-	yer
s t eI	@r
stea-	di-	er
s t e	d i:	@r
stea-	di-	ly
s t e	d I	l i:
stea-	di-	ness
s t e	d i:	n V s
stea-	died
s t e	d i: d
stea-	dy
s t e	d i:
stea-	ler
s t i:	l @r
stea-	ling
s t i:	l I N
stea-	mer
s t i:	m @r
stea-	mers
s t i:	m @r z
stea-	mi-	ly
s t i:	m I	l i:
stea-	ming
s t i:	m I N
stea-	my
s t i:	m i:
stea-	ric
s t i:	r I k
stead
s t e d
stead-	fast
s t e d	f { s t
stead-	fast-	ly
s t e d	f { s	t l i:
stead-	fast-	ness
s t e d	f { s	t n V s
stead-	man
s t e d	m V n
steak
s t eI k
steak-	hou-	ses
s t eI k	h aU	s V z
steak-	house
s t eI k	h aU s
steaks
s t eI k s
steal
s t i: l
steals
s t i: l z
stealth
s t e l T
steam
s t i: m
steam-	boat
s t i: m	b @U t
steam-	boats
s t i: m	b @U t s
steam-	rol-	ler
s t i: m	r @U	l @r
steam-	rol-	lered
s t i: m	r @U	l @r d
)"
R"(steam-	ship
s t i: m	S I p
steamed
s t i: m d
steams
s t i: m z
stear
s t I@
stearn
s t @r n
stearne
s t @r n
stearns
s t @r n z
stears
s t i: r z
steb-	bins
s t e	b I n z
stech
s t e k
steck
s t e k
sted-	man
s t e d	m V n
stee-	ler
s t i:	l @r
stee-	lers
s t i:	l @r z
stee-	ly
s t i:	l i:
stee-	pened
s t i:	p V n d
stee-	per
s t i:	p @r
stee-	pest
s t i:	p V s t
stee-	ple
s t i:	p V l
stee-	ple-	chase
s t i:	p V l	tS eI s
stee-	ring
s t I@	I N
stee-	ver
s t i:	v @r
steed
s t i: d
steed-	man
s t i: d	m V n
steed's
s t i: d z
steel
s t i: l
steel-	head
s t i: l	h e d
steel-	ma-	ker
s t i: l	m eI	k @r
steel-	ma-	kers
s t i: l	m eI	k @r z
steel-	ma-	ker's
s t i: l	m eI	k @r z
steel-	ma-	king
s t i: l	m eI	k I N
steel-	man
s t i: l	m V n
steel-	wor-	ker
s t i: l	w @r	k @r
steel-	wor-	kers
s t i: l	w @r	k @r z
steel-	works
s t i: l	w @r k s
steele
s t i: l
steels
s t i: l z
steel's
s t i: l z
steen
s t i: n
steep
s t i: p
steep-	ly
s t i: p	l i:
steep-	ness
s t i: p	n V s
steeped
s t i: p t
steer
s t I@
steere
s t I@
steered
s t I@ d
steers
s t I@ z
steeves
s t i: v z
stef-	fan
s t e	f V n
stef-	fen
s t e	f V n
stef-	fens
s t e	f V n z
stef-	fi
s t e	f i:
stef-	fie
s t e	f i:
stef-	fy
s t e	f i:
steg-	man
s t e g	m V n
stei-	chen
s t aI	k V n
stei-	er
s t aI	@r
stei-	ger
s t aI	g @r
stei-	nem
s t aI	n V m
stei-	ner
s t aI	n @r
stei-	ner's
s t aI	n @r z
steil
s t i: l
stein
s t aI n
stein-	beck
s t aI n	b e k
stein-	beck's
s t aI n	b e k s
stein-	ber-	ger
s t aI n	b @r	g @r
stein-	berg
s t aI n	b @r g
stein-	berg's
s t aI n	b @r g z
stein-	bock
s t aI n	b Q k
stein-	man
s t aI n	m V n
stein-	metz
s t aI n	m e t s
stein-	way
s t aI n	w eI
stein-	way's
s t aI n	w eI z
steinke
s t aI N k
stein's
s t aI n z
stel-	la
s t e	l V
stel-	lar
s t e	l @r
stel-	la's
s t e	l V z
stel-	len-	bosch
s t e	l V n	b O: S
stel-	ler
s t e	l @r
stel-	ling
s t e	l I N
stel-	mach
s t e l	m V k
stell
s t e l
stelle
s t e l
stem
s t e m
stem-	like
s t e m	l aI k
stem-	mer
s t e	m @r
stem-	ming
s t e	m I N
stem-	pel
s t e m	p V l
stem-	pien
s t e m	p i: n
stem-	ple
s t e m	p V l
stemmed
s t e m d
stems
s t e m z
sten
s t e n
sten-	ci-	ling
s t e n	s I	l I N
sten-	cil
s t e n	s I l
sten-	ciled
s t e n	s I l d
sten-	dal
s t e n	d V l
sten-	gel
s t e N	g V l
sten-	ger
s t e n	dZ @r
sten-	tor
s t e n	t @r
sten-	tors
s t e n	t @r z
stench
s t e n tS
stent
s t e n t
step
s t e p
step-	child
s t e p	tS aI l d
step-	child-	ren
s t e p	tS I l	d r V n
step-	daugh-	ter
s t e p	d O:	t @r
step-	daugh-	ters
s t e p	d O:	t @r z
step-	fa-	ther
s t e p	f Q	D @r
step-	lad-	der
s t e p	l {	d @r
step-	lad-	ders
s t e p	l {	d @r z
step-	mo-	ther
s t e p	m V	D @r
step-	ney
s t e p	n i:
step-	pen-	wolf
s t e	p V n	w U l f
step-	per
s t e	p @r
step-	pers
s t e	p @r z
step-	ping
s t e	p I N
step-	pings-	tone
s t e	p I N	s t @U n
step-	sis-	ter
s t e p	s I s	t @r
step-	sis-	ters
s t e p	s I s	t @r z
step-	son
s t e p	s V n
step-	toe
s t e p	t @U
steppe
s t e p
stepped
s t e p t
steppes
s t e p s
steps
s t e p s
ster-	ling
s t @r	l I N
ster-	ling's
s t @r	l I N z
ster-	ner
s t @r	n @r
ster-	nest
s t @r	n V s t
ster-	rett
s t e@	e t
sterk
s t @r k
stern
s t @r n
stern-	berg
s t @r n	b @r g
stern-	ly
s t @r n	l i:
stern-	ness
s t @r n	n V s
stern-	post
s t @r n	p @U s t
stern-	posts
s t @r n	p @U s t s
sterne
s t @r n
sterns
s t @r n z
stern's
s t @r n z
stet
s t e t
stet-	son
s t e t	s V n
steu-	ben
s t j u:	b V n
steu-	ben-	ville
s t u:	b V n	v I l
steve
s t i: v
steve's
s t i: v z
stew
s t u:
stewed
s t u: d
stews
s t u: z
stew's
s t u: z
sti-	er
s t aI	@r
sti-	fle
s t aI	f V l
sti-	fled
s t aI	f V l d
sti-	fles
s t aI	f V l z
sti-	let-	to
s t V	l e	t @U
sti-	let-	tos
s t V	l e	t @U z
sti-	mu-	la-	ted
s t I m	j V	l eI	t V d
sti-	mu-	la-	ting
s t I m	j V	l eI	t I N
sti-	mu-	la-	tion
s t I m	j V	l eI	S V n
sti-	mu-	la-	tive
s t I m	j V	l eI	t I v
sti-	mu-	la-	tor
s t I m	j V	l eI	t @r
sti-	mu-	la-	tors
s t I m	j V	l eI	t @r z
sti-	mu-	lant
s t I m	j V	l V n t
sti-	mu-	lants
s t I m	j V	l V n t s
sti-	mu-	late
s t I m	j V	l eI t
sti-	mu-	lates
s t I m	j V	l eI t s
sti-	mu-	li
s t I m	j V	l aI
sti-	mu-	lus
s t I m	j V	l V s
sti-	pend
s t aI	p V n d
sti-	pends
s t aI	p V n d z
sti-	pu-	la-	ted
s t I p	j V	l eI	t V d
sti-	pu-	la-	ting
s t I p	j V	l eI	t I N
sti-	pu-	la-	tion
s t I p	j V	l eI	S V n
sti-	pu-	la-	tions
s t I p	j V	l eI	S V n z
sti-	pu-	late
s t I p	j V	l eI t
sti-	pu-	lates
s t I p	j V	l eI t s
sti-	ver
s t aI	v @r
sti-	vers
s t aI	v @r z
stic-	k-	ler
s t I	k V	l @r
stic-	kel
s t I	k V l
stic-	ker
s t I	k @r
stic-	kers
s t I	k @r z
stic-	ki-	er
s t I	k i:	@r
stic-	ki-	est
s t I	k i:	V s t
stic-	king
s t I	k I N
stic-	kle
s t I	k V l
stic-	kles
s t I	k V l z
stic-	ky
s t I	k i:
stich
s t I tS
stich-	ter
s t I k	t @r
stick
s t I k
stick-	ball
s t I k	b O: l
stick-	ney
s t I k	n i:
stick-	tight
s t I k	t aI t
stick-	tights
s t I k	t aI t s
sticks
s t I k s
stid-	ham
s t I d	h V m
stieg-	ler
s t i: g	l @r
stieg-	litz
s t i: g	l I t s
stieve
s t i: v
stif-	fe-	ner
s t I	f V	n @r
stif-	fe-	ning
s t I	f V	n I N
stif-	fen
s t I	f V n
stif-	fened
s t I	f V n d
stif-	fens
s t I	f V n z
stif-	fer
s t I	f @r
stif-	fest
s t I	f V s t
stif-	ling
s t aI f	l I N
stiff
s t I f
stiff-	ler
s t I f	l @r
stiff-	ly
s t I f	l i:
stiff-	ness
s t I f	n V s
stiffed
s t I f t
stiffs
s t I f s
stig
s t I g
stig-	ler
s t I g	l @r
stig-	ma
s t I g	m V
stig-	ma-	ti-	sm
s t I g	m V	t I	z V m
stig-	ma-	ti-	zing
s t I g	m V	t aI	z I N
stig-	ma-	tize
s t I g	m V	t aI z
stig-	ma-	tized
s t I g	m V	t aI z d
stil-	ler
s t I	l @r
stil-	ler's
s t I	l @r z
stil-	lings
s t I	l I N z
stil-	lion
s t I l	j V n
stil-	ted
s t I l	t V d
stil-	well
s t I l	w e l
stile
s t aI l
stiles
s t aI l z
still
s t I l
still-	born
s t I l	b O@ n
still-	man
s t I l	m V n
still-	ness
s t I l	n V s
still-	son
s t I l	s V n
still-	wa-	ter
s t I l	w O:	t @r
still-	well
s t I l	w e l
still-	well's
s t I l	w e l z
stilled
s t I l d
stills
s t I l z
stilt
s t I l t
stilts
s t I l t s
stim-	pert
s t I m	p @r t
stim-	son
s t I m	s V n
stin-	ger
s t I	N @r
stin-	gers
s t I	N @r z
stin-	gi-	er
s t I n	dZ i:	@r
stin-	gi-	ness
s t I n	dZ i:	n V s
stin-	ging
s t I	N I N
stin-	gy
s t I n	dZ i:
stin-	kers
s t I N	k @r z
stin-	king
s t I N	k I N
stin-	ky
s t I N	k i:
stin-	nett
s t I	n I t
stin-	son
s t I n	s V n
stine
s t aI n
sting
s t I N
stings
s t I N z
stink
s t I N k
stink-	bug
s t I N	k b V g
stink-	bugs
s t I N	k b V g z
stinks
s t I N k s
stint
s t I n t
stints
s t I n t s
stipe
s t aI p
stipes
s t aI p s
stir
s t @r
stir-	ling
s t @r	l I N
stir-	ling's
s t @r	l I N z
stir-	ring
s t @r	I N
stir-	rings
s t @r	I N z
stir-	rup
s t @r	V p
stir-	rups
s t @r	V p s
stires
s t aI r z
stirred
s t @r d
stirs
s t @r z
stit-	ches
s t I	tS V z
stit-	ching
s t I	tS I N
stit-	zer
s t I t	z @r
stitch
s t I tS
stitched
s t I tS t
stites
s t aI t s
stith
s t I T
sto-	ga
s t @U	g V
sto-	i-	ci-	sm
s t @U	I	s I	z V m
sto-	ic
s t @U	I k
sto-	ical-	ly
s t @U	I k	l i:
sto-	ics
s t @U	I k s
sto-	ker
s t @U	k @r
sto-	king
s t @U	k I N
sto-	len
s t @U	l V n
sto-	lich-	na-	ya
s t @U	l I k	n aI	V
sto-	lid
s t Q	l I d
sto-	ma-	ta
s t @U	m V	t V
sto-	mach
s t V	m V k
sto-	machs
s t V	m V k s
sto-	ner
s t @U	n @r
sto-	ney
s t @U	n i:
sto-	ning
s t @U	n I N
sto-	ny
s t @U	n i:
sto-	pa
s t @U	p V
sto-	rage
s t O@	V dZ
sto-	rer
s t O@	@r
sto-	rer's
s t O@	@r z
sto-	rey
s t O@	i:
sto-	ried
s t O@	i: d
sto-	ries
s t O@	i: z
sto-	ring
s t O@	I N
sto-	ry
s t O@	i:
sto-	ry-	board
s t O@	i:	b O@ d
sto-	ry-	book
s t O@	i:	b U k
sto-	ry-	books
s t O@	i:	b U k s
sto-	ry-	line
s t O@	i:	l aI n
sto-	ry-	lines
s t O@	i:	l aI n z
sto-	ry-	tel-	ler
s t O@	i:	t e	l @r
sto-	ry-	tel-	lers
s t O@	i:	t e	l @r z
sto-	ry-	tel-	ling
s t O@	i:	t e	l I N
sto-	ry's
s t O@	i: z
sto-	vall
s t @U	v Q l
sto-	ver
s t @U	v @r
sto-	well
s t Q	w e l
sto-	wer
s t @U	@r
sto-	wers
s t @U	@r z
stoc-	ker
s t Q	k @r
stoc-	kett
s t Q	k e t
stoc-	kin-	ger
s t Q	k I	N @r
stoc-	king
s t Q	k I N
stoc-	kings
s t Q	k I N z
stoc-	ky
s t Q	k i:
stock
s t Q k
stock-	bridge
s t Q k	b r I dZ
stock-	bro-	ke-	ra-	ges
s t Q k	b r @U	k @r	I	dZ V z
stock-	bro-	ke-	rage
s t Q k	b r @U	k @r	I dZ
stock-	bro-	ker
s t Q k	b r @U	k @r
stock-	bro-	kers
s t Q k	b r @U	k @r z
stock-	bro-	ker's
s t Q k	b r @U	k @r z
stock-	bro-	king
s t Q k	b r @U	k I N
stock-	dale
s t Q k	d eI l
stock-	dale's
s t Q k	d eI l z
stock-	hau-	sen
s t Q k	h aU	z V n
stock-	hol-	der
s t Q k	h @U l	d @r
stock-	hol-	ders
s t Q k	h @U l	d @r z
stock-	hol-	ding
s t Q k	h @U l	d I N
stock-	hol-	dings
s t Q k	h @U l	d I N z
stock-	holm
s t Q k	h @U l m
stock-	holm's
s t Q k	h @U l m z
stock-	man
s t Q k	m V n
stock-	man's
s t Q k	m { n z
stock-	pi-	ling
s t Q k	p aI	l I N
stock-	pile
s t Q k	p aI l
stock-	piled
s t Q k	p aI l d
stock-	piles
s t Q k	p aI l z
stock-	room
s t Q k	r u: m
stock-	still
s t Q k	s t I l
stock-	ton
s t Q k	t V n
stock-	well
s t Q k	w e l
stock-	yard
s t Q k	j Q@ d
stock-	yards
s t Q k	j Q@ d z
stocked
s t Q k t
stocks
s t Q k s
stock's
s t Q k s
stod-	dard
s t Q	d @r d
stod-	dard's
s t Q	d @r d z
stod-	gy
s t Q	dZ i:
stoe-	ber
s t @U	b @r
stoec-	ker
s t @U	k @r
stof-	fel
s t Q	f V l
stoff
s t O: f
stoke
s t @U k
stoke-	ly
s t @U k	l i:
stoked
s t @U k t
stokes
s t @U k s
stol
s t @U l
stol-	len
s t Q	l V n
stol-	ler
s t @U	l @r
stol-	lings
s t @U	l I N z
stole
s t @U l
stoll
s t @U l
stom-	ping
s t Q m	p I N
stomp
s t Q m p
stomped
s t Q m p t
stone
s t @U n
stone-	cut-	ter
s t @U n	k V	t @r
stone-	cut-	ters
s t @U n	k V	t @r z
stone-	ham
s t @U	n V m
stone-	henge
s t @U n	h e n dZ
stone-	man
s t @U n	m V n
stone-	wal-	ling
s t @U n	w O:	l I N
stone-	wall
s t @U n	w O: l
stone-	walled
s t @U n	w O: l d
stone-	ware
s t @U n	w e@
stoned
s t @U n d
stones
s t @U n z
stone's
s t @U n z
stong
s t O: N
stoo-	ges
s t u:	dZ V z
stoo-	ping
s t u:	p I N
stood
s t U d
stooge
s t u: dZ
stool
s t u: l
stools
s t u: l z
stoop
s t u: p
stooped
s t u: p t
stoops
s t u: p s
stop
s t Q p
stop-	gap
s t Q p	g { p
stop-	light
s t Q p	l aI t
stop-	lights
s t Q p	l aI t s
stop-	o-	ver
s t Q	p @U	v @r
stop-	o-	vers
s t Q	p @U	v @r z
stop-	pa-	ges
s t Q	p I	dZ V z
stop-	page
s t Q	p I dZ
stop-	pel
s t Q	p V l
stop-	per
s t Q	p @r
stop-	pers
s t Q	p @r z
stop-	ping
s t Q	p I N
stop-	wat-	ches
s t Q p	w Q	tS V z
stop-	watch
s t Q p	w Q tS
stopped
s t Q p t
stops
s t Q p s
stor-	fer
s t O@	f @r
stor-	mer
s t O@	m @r
stor-	mi-	est
s t O@	m i:	V s t
stor-	ming
s t O@	m I N
stor-	mont
s t O@	m @U n t
stor-	my
s t O@	m i:
stor-	ting
s t O@	t I N
store
s t O@
store-	front
s t O@ f	r Q n t
store-	fronts
s t O@ f	r Q n t s
store-	hou-	ses
s t O@	h aU	z V z
store-	hou-	se's
s t O@	h aU	s V z
store-	house
s t O@	h aU s
store-	kee-	per
s t O@	k i:	p @r
store-	kee-	pers
s t O@	k i:	p @r z
store-	room
s t O@	r u: m
stored
s t O@ d
stores
s t O@ z
store's
s t O@ z
stork
s t O@ k
storm
s t O@ m
stormed
s t O@ m d
storms
s t O@ m z
storm's
s t O@ m z
storr
s t O@
storrs
s t O@ z
stortz
s t O@ t s
storz
s t O@ z
stott
s t Q t
stouf-	fer
s t V	f @r
stough-	ton
s t @U	t V n
stoup
s t u: p
stout
s t aU t
stout-	ly
s t aU t	l i:
stout-	ness
s t aU t	n V s
stove
s t @U v
stoves
s t @U v z
stow
s t @U
stowe
s t @U
stowed
s t @U d
stoy
s t OI
stra-	der
s t r eI	d @r
stra-	di-	va-	ri-	us
s t r {	d I	v e@	i:	V s
stra-	fing
s t r eI	f I N
stra-	na-	han
s t r {	n V	h { n
stra-	ta
s t r {	t V
stra-	ta-	gems
s t r {	t V	dZ V m z
stra-	tas
s t r {	t V z
stra-	te-	gem
s t r {	t I	dZ e m
stra-	te-	gi-	cal
s t r V	t i:	dZ I	k V l
stra-	te-	gi-	zing
s t r {	t V	dZ aI	z I N
stra-	te-	gic
s t r V	t i:	dZ I k
stra-	te-	gical-	ly
s t r V	t i:	dZ I k	l i:
stra-	te-	gies
s t r {	t V	dZ i: z
stra-	te-	gist
s t r {	t I	dZ I s t
stra-	te-	gists
s t r {	t I	dZ I s t s
stra-	te-	gize
s t r {	t V	dZ aI z
stra-	te-	gy
s t r {	t V	dZ i:
stra-	te-	gy's
s t r {	t V	dZ i: z
stra-	ti-	fied
s t r {	t I	f aI d
stra-	ti-	fy
s t r {	t I	f aI
stra-	ti-	gra-	phic
s t r {	t I g	r {	f I k
stra-	tos-	phe-	ric
s t r {	t V s	f I@	I k
stra-	tos-	phere
s t r {	t V s	f I@
stra-	tu-	s's
s t r {	t V	s V z
stra-	tum
s t r {	t V m
stra-	tus
s t r {	t V s
stra-	vin-	sky
s t r V	v I n	s k i:
stra-	vin-	sky's
s t r V	v I n	s k i: z
stra-	yer
s t r eI	@r
strack
s t r { k
strad-	dle
s t r {	d V l
strad-	dled
s t r {	d V l d
strad-	dles
s t r {	d V l z
stradd-	ling
s t r { d	l I N
strafe
s t r eI f
strag-	gle
s t r {	g V l
strag-	gled
s t r {	g V l d
stragg-	ler
s t r { g	l @r
stragg-	lers
s t r { g	l @r z
strai-	ning
s t r eI	n I N
straigh-	ta-	way
s t r eI	t V	w eI
straigh-	te-	ning
s t r eI	t V	n I N
straigh-	tedge
s t r eI	t e dZ
straigh-	ten
s t r eI	t V n
straigh-	tened
s t r eI	t V n d
straigh-	tens
s t r eI	t V n z
straigh-	ter
s t r eI	t @r
straight
s t r eI t
straights
s t r eI t s
strain
s t r eI n
strained
s t r eI n d
strains
s t r eI n z
strait
s t r eI t
strait-	jac-	ket
s t r eI t	dZ {	k V t
straits
s t r eI t s
stram
s t r { m
stran-	ded
s t r { n	d V d
stran-	ding
s t r { n	d I N
stran-	g-	ling
s t r { N	g V	l I N
stran-	ger
s t r eI n	dZ @r
stran-	gers
s t r eI n	dZ @r z
stran-	ger's
s t r eI n	dZ @r z
stran-	gest
s t r eI n	dZ V s t
stran-	gle
s t r { N	g V l
stran-	gle-	hold
s t r { N	g V l	h @U l d
stran-	gled
s t r { N	g V l d
stran-	gu-	la-	tion
s t r { N	g j V	l eI	S V n
stran-	gu-	la-	tions
s t r { N	g j V	l eI	S V n z
stran-	gu-	late
s t r { N	g j V	l eI t
strand
s t r { n d
strand-	line
s t r { n	d l aI n
strand-	lines
s t r { n	d l aI n z
strands
s t r { n d z
strang
s t r { N
strang-	ler
s t r { N	g l @r
strange
s t r eI n dZ
strange-	ly
s t r eI n	dZ l i:
strange-	ness
s t r eI n	dZ n V s
strap
s t r { p
strap-	ping
s t r {	p I N
strapped
s t r { p t
straps
s t r { p s
stras-	berg
s t r { s	b @r g
stras-	bourg
s t r { s	b O@ g
stras-	burg
s t r { s	b @r g
strass-	burg
s t r { s	b @r g
strat-	ford
s t r { t	f @r d
strat-	ton
s t r {	t V n
strate
s t r eI t
straub
s t r aU b
straugh-	ter
s t r O:	t @r
straughn
s t r O: n
straus
s t r aU s
strauss
s t r aU s
straw
s t r O:
straw-	ber-	ries
s t r O:	b e@	i: z
straw-	ber-	ry
s t r O:	b e@	i:
strawn
s t r O: n
straws
s t r O: z
stray
s t r eI
stray-	ing
s t r eI	I N
strayed
s t r eI d
strays
s t r eI z
stre-	nu-	ous
s t r e n	j u:	V s
stre-	nu-	ous-	ly
s t r e n	j u:	V s	l i:
strea-	ker
s t r i:	k @r
strea-	king
s t r i:	k I N
strea-	mer
s t r i:	m @r
strea-	mers
s t r i:	m @r z
strea-	ming
s t r i:	m I N
streak
s t r i: k
streaked
s t r i: k t
streaks
s t r i: k s
stream
s t r i: m
stream-	li-	ning
s t r i: m	l aI	n I N
stream-	line
s t r i: m	l aI n
stream-	lined
s t r i: m	l aI n d
streamed
s t r i: m d
streams
s t r i: m z
streck
s t r e k
stree-	ter
s t r i:	t @r
stree-	ters
s t r i:	t @r z
stree-	ty
s t r i:	t i:
streep
s t r i: p
street
s t r i: t
street-	car
s t r i: t	k Q@
street-	man
s t r i: t	m V n
street-	wise
s t r i: t	w aI z
streets
s t r i: t s
street's
s t r i: t s
strei-	sand
s t r aI	z V n d
strei-	sand's
s t r aI	z V n d z
streight
s t r eI t
streit
s t r aI t
streng
s t r e N
streng-	the-	ning
s t r e N	T V	n I N
streng-	then
s t r e N	T V n
streng-	thened
s t r e N	T V n d
streng-	thens
s t r e N	T V n z
strength
s t r e N k T
strengths
s t r e N k T s
strep
s t r e p
strep-	to-	coc-	cus
s t r e p	t V	k O:	k V s
strep-	to-	ki-	nase
s t r e p	t V	k aI	n eI s
streps
s t r e p s
stres-	ses
s t r e	s V z
stres-	sing
s t r e	s I N
stres-	sor
s t r e	s @r
stres-	sors
s t r e	s @r z
stress
s t r e s
stress-	ful
s t r e s	f V l
stressed
s t r e s t
stret-	cher
s t r e	tS @r
stret-	chers
s t r e	tS @r z
stret-	ches
s t r e	tS V z
stret-	ching
s t r e	tS I N
stret-	to
s t r e	t @U
stretch
s t r e tS
stretched
s t r e tS t
strew
s t r u:
strewn
s t r u: n
strey
s t r eI
stri-	den-	cy
s t r aI	d V n	s i:
stri-	dent
s t r aI	d V n t
stri-	dent-	ly
s t r aI	d V n	t l i:
stri-	der
s t r aI	d @r
stri-	ding
s t r aI	d I N
stri-	ker
s t r aI	k @r
stri-	kers
s t r aI	k @r z
stri-	king
s t r aI	k I N
stri-	king-	ly
s t r aI	k I N	l i:
stri-	per
s t r aI	p @r
stri-	pers
s t r aI	p @r z
stri-	ven
s t r I	v V n
stri-	ving
s t r aI	v I N
)"
R"(stri-	vings
s t r aI	v I N z
stric-	ken
s t r I	k V n
stric-	ker
s t r I	k @r
stric-	ter
s t r I k	t @r
stric-	test
s t r I k	t V s t
stric-	ture
s t r I k	tS @r
stric-	tures
s t r I k	tS @r z
strick
s t r I k
strick-	land
s t r I k	l V n d
strick-	ler
s t r I k	l @r
strick-	ling
s t r I k	l I N
strict
s t r I k t
strict-	ly
s t r I k	t l i:
stride
s t r aI d
strides
s t r aI d z
strife
s t r aI f
strifes
s t r aI f s
strike
s t r aI k
strike-	brea-	ker
s t r aI k	b r eI	k @r
strike-	brea-	kers
s t r aI k	b r eI	k @r z
strike-	out
s t r aI	k aU t
strike-	outs
s t r aI	k aU t s
strikes
s t r aI k s
strin-	gen-	cy
s t r I n	dZ V n	s i:
strin-	gent
s t r I n	dZ V n t
strin-	gent-	ly
s t r I n	dZ V n	t l i:
strin-	ger
s t r I	N @r
strin-	gers
s t r I	N @r z
strin-	ging
s t r I	N I N
strin-	gy
s t r I	N i:
strine
s t r aI n
string
s t r I N
stringed
s t r I N d
strings
s t r I N z
strip
s t r I p
strip-	ling
s t r I p	l I N
strip-	per
s t r I	p @r
strip-	pers
s t r I	p @r z
strip-	ping
s t r I	p I N
strip-	tease
s t r I p	t i: z
stripe
s t r aI p
striped
s t r aI p t
stripes
s t r aI p s
stripped
s t r I p t
strips
s t r I p s
strip's
s t r I p s
strive
s t r aI v
strives
s t r aI v z
stro-	ga-	noff
s t r @U	g V	n O: f
stro-	king
s t r @U	k I N
stro-	ma
s t r @U	m V
stro-	ther
s t r Q	D @r
strobe
s t r @U b
strode
s t r @U d
stroess-	ner
s t r @U s	n @r
stroh
s t r @U
strohl
s t r @U l
stroke
s t r @U k
stroked
s t r @U k t
strokes
s t r @U k s
strol-	ler
s t r @U	l @r
strol-	lers
s t r @U	l @r z
strol-	ling
s t r @U	l I N
stroll
s t r @U l
strolled
s t r @U l d
strolls
s t r @U l z
strom
s t r Q m
strom-	berg
s t r Q m	b @r g
strom-	bo-	li
s t r Q m	b @U	l i:
strom-	bo-	li's
s t r Q m	b @U	l i: z
strome
s t r @U m
stron-	ger
s t r O:	N @r
stron-	gest
s t r O: N	g V s t
stron-	ti-	um
s t r Q n	t i:	V m
strong
s t r O: N
strong-	hold
s t r O: N	h @U l d
strong-	holds
s t r O: N	h @U l d z
strong-	ly
s t r O: N	l i:
strong-	man
s t r O: N	m { n
stroot
s t r u: t
stroud
s t r aU d
stroup
s t r u: p
strout
s t r aU t
strove
s t r @U v
strow
s t r @U
stru-	thers
s t r V	D @r z
strub
s t r V b
struc-	tu-	ral
s t r V k	tS @r	V l
struc-	tu-	ral-	ly
s t r V k	tS @r	V	l i:
struc-	tu-	ring
s t r V k	tS @r	I N
struc-	ture
s t r V k	tS @r
struc-	tured
s t r V k	tS @r d
struc-	tures
s t r V k	tS @r z
struc-	ture's
s t r V k	tS @r z
struck
s t r V k
strug-	g-	ling
s t r V	g V	l I N
strug-	gle
s t r V	g V l
strug-	gled
s t r V	g V l d
strug-	gles
s t r V	g V l z
strum
s t r V m
strum-	ming
s t r V	m I N
strums
s t r V m z
strung
s t r V N
strunk
s t r V N k
strunk's
s t r V N k s
strut
s t r V t
strut-	ting
s t r V	t I N
struts
s t r V t s
struve
s t r u: v
stry-	ker
s t r aI	k @r
strych-	nine
s t r I k	n aI n
stu
s t u:
stu-	art
s t u:	@r t
stu-	arts
s t u:	@r t s
stu-	art's
s t u:	@r t s
stu-	ber
s t u:	b @r
stu-	de-	ba-	ker
s t u:	d V	b eI	k @r
stu-	dent
s t u:	d V n t
stu-	dents
s t u:	d V n t s
stu-	dent's
s t u:	d V n t s
stu-	di-	o
s t u:	d i:	@U
stu-	di-	os
s t u:	d i:	@U z
stu-	di-	o's
s t u:	d i:	@U z
stu-	di-	ous
s t u:	d i:	V s
stu-	di-	ous-	ly
s t u:	d i:	V s	l i:
stu-	died
s t V	d i: d
stu-	dies
s t V	d i: z
stu-	dy
s t V	d i:
stu-	dy-	ing
s t V	d i:	I N
stu-	dy's
s t V	d i: z
stu-	ka
s t u:	k V
stu-	pa
s t u:	p V
stu-	pen-	dous
s t u:	p e n	d V s
stu-	pi-	dest
s t u:	p I	d e s t
stu-	pi-	di-	ty
s t u:	p I	d I	t i:
stu-	pid
s t u:	p I d
stu-	pid-	ly
s t u:	p I d	l i:
stu-	por
s t u:	p @r
stub
s t V b
stub-	ble
s t V	b V l
stub-	ble-	field
s t V	b V l	f i: l d
stub-	born
s t V	b @r n
stub-	born-	ly
s t V	b @r n	l i:
stub-	born-	ness
s t V	b @r n	n V s
stub-	by
s t V	b i:
stubbed
s t V b d
stubbs
s t V b z
stubs
s t V b z
stuc-	co
s t V	k @U
stuc-	ker
s t V	k @r
stuc-	key
s t V	k i:
stuck
s t V k
stud
s t V d
stud-	dard
s t V	d @r d
stud-	ded
s t V	d V d
stud-	ley
s t V d	l i:
stude
s t u: d
studs
s t V d z
stuf-	fer
s t V	f @r
stuf-	fing
s t V	f I N
stuf-	fy
s t V	f i:
stuff
s t V f
stuffed
s t V f t
stuffs
s t V f s
stul-	ler
s t V	l @r
stul-	ti-	fy
s t V l	t I	f aI
stul-	ti-	fy-	ing
s t V l	t I	f aI	I N
stull
s t V l
stultz
s t V l t s
stum
s t V m
stum-	b-	ling
s t V m	b V	l I N
stum-	ble
s t V m	b V l
stum-	bled
s t V m	b V l d
stum-	bles
s t V m	b V l z
stum-	page
s t V m	p I dZ
stum-	ping
s t V m	p I N
stumm
s t V m
stump
s t V m p
stumped
s t V m p t
stumps
s t V m p s
stun
s t V n
stun-	ning
s t V	n I N
stun-	ning-	ly
s t V	n I N	l i:
stun-	ted
s t V n	t V d
stung
s t V N
stunk
s t V N k
stunned
s t V n d
stunt
s t V n t
stunts
s t V n t s
stupp
s t V p
stur-	bridge
s t @r b	r I dZ
stur-	di-	er
s t @r	d i:	@r
stur-	di-	ness
s t @r	d i:	n V s
stur-	di-	vant
s t @r	d I	v V n t
stur-	dy
s t @r	d i:
stur-	geon
s t @r	dZ V n
stur-	geons
s t @r	dZ V n z
stur-	ges
s t @r	dZ V z
stur-	gis
s t @r	dZ I s
stur-	kie
s t @r	k i:
stur-	mer
s t @r	m @r
stur-	rock
s t O@	V k
stur-	te-	vant
s t @r	t V	v V n t
sturm
s t @r m
stut-	te-	ring
s t V	t @r	I N
stut-	ter
s t V	t @r
stut-	ters
s t V	t @r z
stuts-	man
s t V t	s m V n
stutt-	gart
s t V t	g @r t
stutz-	man
s t V t	s m V n
stuy-	ve-	sant
s t aI	v V	s V n t
sty
s t aI
sty-	ling
s t aI	l I N
sty-	lis-	tic
s t aI	l I s	t I k
sty-	lis-	tical-	ly
s t aI	l I s	t I k	l i:
sty-	lish
s t aI	l I S
sty-	lish-	ly
s t aI	l I S	l i:
sty-	list
s t aI	l I s t
sty-	lists
s t aI	l I s t s
sty-	lites
s t I	l aI t s
sty-	lize
s t aI	l aI z
sty-	lized
s t aI	l aI z d
sty-	lus
s t aI	l V s
sty-	mie
s t aI	m i:
sty-	mied
s t aI	m i: d
sty-	mies
s t aI	m i: z
sty-	rene
s t aI	r i: n
sty-	ro-	foam
s t aI	r V	f @U m
sty-	ron
s t aI	r O: n
style
s t aI l
styled
s t aI l d
styles
s t aI l z
styx
s t I k s
su
s u:
su-	ba
s u:	b V
su-	ba-	cute
s V	b V k	j u: t
su-	ba-	ru
s u:	b @r	u:
su-	ber
s u:	b @r
su-	bic
s u:	b I k
su-	bur-	ba-	ni-	za-	tion
s V	b @r	b V	n V	z eI	S V n
su-	bur-	ba-	nite
s V	b @r	b V	n aI t
su-	bur-	ba-	nites
s V	b @r	b V	n aI t s
su-	bur-	ba-	nize
s V	b @r	b V	n aI z
su-	bur-	ban
s V	b @r	b V n
su-	bur-	bans
s V	b @r	b V n z
su-	bur-	bi-	a
s V	b @r	b i:	V
su-	burb
s V	b @r b
su-	burbs
s V	b @r b z
su-	burb's
s V	b @r b z
su-	cre
s u:	k @r
su-	da-	fed
s u:	d V	f e d
su-	da-	nese
s u:	d V	n i: z
su-	dan
s u:	d { n
su-	dan's
s u:	d { n z
su-	e-	z's
s u:	e	z V z
su-	ey
s u:	i:
su-	ez
s u:	e z
su-	ga-	ry
S U	g @r	i:
su-	gar
S U	g @r
su-	gared
S U	g @r d
su-	gars
S U	g @r z
su-	gar's
S U	g @r z
su-	gi-	ha-	ra
s u:	g i:	h Q@	V
su-	har-	to
s u:	h Q@	t @U
su-	har-	to's
s u:	h Q@	t @U z
su-	i
s u:	i:
su-	i-	ci-	dal
s u:	I	s aI	d V l
su-	i-	cide
s u:	I	s aI d
su-	i-	cides
s u:	I	s aI d z
su-	ing
s u:	I N
su-	kar-	no
s u:	k Q@	n @U
su-	kar-	no's
s u:	k Q@	n @U z
su-	key
s u:	k i:
su-	ki
s u:	k i:
su-	ki-	ya-	ki
s u:	k i:	Q	k i:
su-	la-	we-	si
s u:	l V	w e	s i:
su-	mac
s u:	m { k
su-	mat-	ra
s u:	m Q t	r V
su-	mat-	ran
s u:	m Q t	r V n
su-	me-	ri-	a
s V	m @r	i:	V
su-	mer-	lin
s V	m @r	l I n
su-	mo
s u:	m @U
su-	ni-	a
s u:	n i:	V
su-	nil
s u:	n I l
su-	nup
s V	n V p
su-	ny
s u:	n i:
su-	pe-	ri-	o-	ri-	ty
s u:	p I@	i:	O@	I	t i:
su-	pe-	ri-	or
s u:	p I@	i:	@r
su-	pe-	ri-	ors
s u:	p I@	i:	@r z
su-	pe-	ri-	or's
s u:	p i:	r i:	@r z
su-	pe-	ro-	xide
s u:	p @r	Q k	s aI d
su-	per
s u:	p @r
su-	per-	bowl
s u:	p @r	b @U l
su-	per-	bowl's
s u:	p @r	b @U l z
su-	per-	cen-	ter
s u:	p @r	s e n	t @r
su-	per-	cen-	ters
s u:	p @r	s e n	t @r s
su-	per-	charge
s u:	p @r	tS Q@ dZ
su-	per-	charged
s u:	p @r	tS Q@ dZ d
su-	per-	ci-	li-	ous
s u:	p @r	s I	l i:	V s
su-	per-	col-	li-	der
s u:	p @r	k V	l aI	d @r
su-	per-	com-	pu-	ter
s u:	p @r	k V m	p j u:	t @r
su-	per-	com-	pu-	ters
s u:	p @r	k V m	p j u:	t @r z
su-	per-	com-	pu-	ting
s u:	p @r	k V m	p j u:	t I N
su-	per-	con-	duc-	ti-	vi-	ty
s u:	p @r	k Q n	d V k	t I	v I	t i:
su-	per-	con-	duc-	ting
s u:	p @r	k V n	d V k	t I N
su-	per-	con-	duc-	tive
s u:	p @r	k V n	d V k	t I v
su-	per-	con-	duc-	tor
s u:	p @r	k V n	d V k	t @r
su-	per-	con-	duc-	tors
s u:	p @r	k V n	d V k	t @r z
su-	per-	cool
s u:	p @r	k u: l
su-	per-	cooled
s u:	p @r	k u: l d
su-	per-	de-	le-	gate
s u:	p @r	d e	l V	g V t
su-	per-	de-	le-	gates
s u:	p @r	d e	l V	g V t s
su-	per-	fami-	ly
s u:	p @r	f { m	l i:
su-	per-	fan
s u:	p @r	f { n
su-	per-	fast
s u:	p @r	f { s t
su-	per-	fi-	cial
s u:	p @r	f I	S V l
su-	per-	fi-	cial-	ly
s u:	p @r	f I	S V l	l i:
su-	per-	flu-	i-	di-	ty
s u:	p @r f	l u:	I	d I	t i:
su-	per-	fluous
s u:	p @r f	l w V s
su-	per-	fund
s u:	p @r	f V n d
su-	per-	gi-	ant
s u:	p @r	dZ aI	V n t
su-	per-	gi-	ants
s u:	p @r	dZ aI	V n t s
su-	per-	he-	ro
s u:	p @r	h i:	r @U
su-	per-	he-	roes
s u:	p @r	h i:	r @U z
su-	per-	he-	te-	ro-	dyne
s u:	p @r	h e	t @r	V	d aI n
su-	per-	hea-	ted
s u:	p @r	h i:	t V d
su-	per-	high-	way
s u:	p @r	h aI	w eI
su-	per-	high-	ways
s u:	p @r	h aI	w eI z
su-	per-	hu-	man
s u:	p @r h	j u:	m V n
su-	per-	im-	pose
s u:	p @r	I m	p @U z
su-	per-	im-	posed
s u:	p @r	I m	p @U z d
su-	per-	in-	ten-	dant
s u:	p @r	I n	t e n	d V n t
su-	per-	in-	ten-	dent
s u:	p @r	I n	t e n	d V n t
su-	per-	in-	ten-	dents
s u:	p @r	I n	t e n	d V n t s
su-	per-	in-	ten-	dent's
s u:	p @r	I n	t e n	d V n t s
su-	per-	la-	tive
s U	p @r	l V	t I v
su-	per-	la-	tives
s U	p @r	l V	t I v z
su-	per-	ma-	jo-	ri-	ty
s u:	p @r	m V	dZ O@	V	t i:
su-	per-	man
s u:	p @r	m { n
su-	per-	man's
s u:	p @r	m { n z
su-	per-	mar-	ket
s u:	p @r	m Q@	k I t
su-	per-	mar-	kets
s u:	p @r	m Q@	k V t s
su-	per-	mar-	ket's
s u:	p @r	m Q@	k V t s
su-	per-	mi-	ni-	com-	pu-	ter
s u:	p @r	m I	n i:	k V m	p j u:	t @r
su-	per-	mi-	ni-	com-	pu-	ters
s u:	p @r	m I	n i:	k V m	p j u:	t @r z
su-	per-	mo-	del
s u:	p @r	m Q	d V l
su-	per-	mo-	dels
s u:	p @r	m Q	d V l z
su-	per-	na-	tu-	ra-	li-	sm
s u:	p @r	n {	tS @r	V	l I	z V m
su-	per-	na-	tu-	ral
s u:	p @r	n {	tS @r	V l
su-	per-	no-	va
s u:	p @r	n @U	v V
su-	per-	po-	wer
s u:	p @r	p aU	@r
su-	per-	po-	wers
s u:	p @r	p aU	@r z
su-	per-	pre-	mi-	um
s u:	p @r p	r i:	m i:	V m
su-	per-	re-	gio-	nal
s u:	p @r	r i:	dZ V	n V l
su-	per-	sa-	ver
s u:	p @r	s eI	v @r
su-	per-	se-	ded
s u:	p @r	s i:	d V d
su-	per-	se-	ding
s u:	p @r	s i:	d I N
su-	per-	sec-	ret
s u:	p @r	s i: k	r V t
su-	per-	sede
s u:	p @r	s i: d
su-	per-	sedes
s u:	p @r	s i: d z
su-	per-	so-	nic
s u:	p @r	s Q	n I k
su-	per-	sta-	tion
s u:	p @r s	t eI	S V n
su-	per-	star
s u:	p @r s	t Q@
su-	per-	stars
s u:	p @r s	t Q@ z
su-	per-	sti-	tion
s u:	p @r s	t I	S V n
su-	per-	sti-	tions
s u:	p @r s	t I	S V n z
su-	per-	sti-	tious
s u:	p @r s	t I	S V s
su-	per-	store
s u:	p @r s	t O@
su-	per-	stores
s u:	p @r s	t O@ z
su-	per-	struc-	ture
s u:	p @r s	t r V k	tS @r
su-	per-	struc-	tures
s u:	p @r s	t r V k	tS @r z
su-	per-	tan-	ker
s u:	p @r	t { N	k @r
su-	per-	vi-	ses
s u:	p @r	v aI	z V z
su-	per-	vi-	sing
s u:	p @r	v aI	z I N
su-	per-	vi-	sion
s u:	p @r	v I	Z V n
su-	per-	vi-	so-	ry
s u:	p @r	v aI	z @r	i:
su-	per-	vi-	sor
s u:	p @r	v aI	z @r
su-	per-	vi-	sors
s u:	p @r	v aI	z @r z
su-	per-	vise
s u:	p @r	v aI z
su-	per-	vised
s u:	p @r	v aI z d
su-	per-	wo-	man
s u:	p @r	w U	m V n
su-	per-	wo-	men
s u:	p @r	w I	m e n
su-	perb
s U	p @r b
su-	perb-	ly
s u:	p @r b	l i:
su-	pers
s u:	p @r z
su-	pine
s V	p aI n
su-	ra
s U@	V
su-	rat
s @r	Q t
su-	rat's
s @r	Q t s
su-	re-	ty
S U@	V	t i:
su-	rer
S U@	@r
su-	rest
S U@	V s t
su-	rette
s @r	e t
su-	ri-	nam
s U@	I	n Q m
su-	ri-	name
s @r	I	n Q m
su-	sa
s u:	s V
su-	sa-	na
s u:	s Q	n V
su-	san
s u:	z V n
su-	san-	na
s u:	z {	n V
su-	san-	nah
s u:	s {	n V
su-	sann
s u:	z { n
su-	sanne
s u:	z { n
su-	san's
s u:	z V n z
su-	sette
s u:	z e t
su-	shi
s u:	S i:
su-	si
s u:	s i:
su-	sie
s u:	z i:
su-	sie's
s u:	z i: z
su-	su-	mu
s u:	s u:	m u:
su-	sy
s u:	z i:
su-	ter
s u:	t @r
su-	ther
s V	D @r
su-	ther-	land
s V	D @r	l V n d
su-	ther-	lin
s V	T @r	l I n
su-	to
s u:	t @U
su-	tor
s u:	t @r
su-	ture
s u:	tS @r
su-	tures
s u:	tS @r z
su-	va
s u:	v V
su-	zan-	na
s u:	z {	n V
su-	zanne
s u:	z { n
su-	zette
s u:	z e t
su-	zie
s V	z i:
su-	zu-	ki
s V	z u:	k i:
su-	zy
s u:	z i:
su-	zy's
s u:	z i: z
sua-	rez
s w Q@	e z
sua-	sion
s w eI	Z V n
suave
s w Q v
sub
s V b
sub-	a-	to-	mic
s V	b V	t Q	m I k
sub-	as-	semb-	lies
s V	b V	s e m	b l i: z
sub-	as-	semb-	ly
s V	b V	s e m	b l i:
sub-	bing
s V	b I N
sub-	chap-	ter
s V b	tS { p	t @r
sub-	com-	man-	der
s V b	k V	m { n	d @r
sub-	com-	man-	ders
s V b	k V	m { n	d @r z
sub-	com-	man-	der's
s V b	k V	m { n	d @r z
sub-	com-	mit-	tee
s V b	k V	m I	t i:
sub-	com-	mit-	tees
s V b	k V	m I	t i: z
sub-	com-	mit-	tee's
s V b	k V	m I	t i: z
sub-	com-	pact
s V b	k Q m	p { k t
sub-	com-	pacts
s V b	k Q m	p { k t s
sub-	con-	scious
s V b	k Q n	S V s
sub-	con-	scious-	ly
s V b	k Q n	S V s	l i:
sub-	con-	ti-	nent
s V b	k Q n	t V	n V n t
sub-	con-	ti-	nents
s V b	k Q n	t V	n V n t s
sub-	cont-	rac-	ted
s V b	k Q n	t r { k	t V d
sub-	cont-	rac-	ting
s V b	k V n	t r { k	t I N
sub-	cont-	rac-	tor
s V b	k Q n	t r { k	t @r
sub-	cont-	rac-	tors
s V b	k Q n	t r { k	t @r z
sub-	cont-	ract
s V b	k Q n	t r { k t
sub-	cont-	racts
s V b	k Q n	t r { k t s
sub-	cul-	ture
s V b	k V l	tS @r
sub-	cul-	tures
s V b	k V l	tS @r z
sub-	di-	vi-	ded
s V b	d I	v aI	d I d
sub-	di-	vi-	sion
s V b	d I	v I	Z V n
sub-	di-	vi-	sions
s V b	d I	v I	Z V n z
sub-	di-	vide
s V b	d I	v aI d
sub-	du-	ing
s V b	d u:	I N
sub-	due
s V b	d u:
sub-	dued
s V b	d u: d
sub-	fa-	mi-	lies
s V b	f {	m I	l i: z
sub-	fa-	mi-	ly
s V b	f {	m I	l i:
sub-	group
s V b	g r u: p
sub-	groups
s V b	g r u: p s
sub-	hu-	man
s V b	h j u:	m V n
sub-	jec-	ted
s V b	dZ e k	t V d
sub-	jec-	ti-	vi-	ty
s V b	dZ e k	t I	v V	t i:
sub-	jec-	ting
s V b	dZ e k	t I N
sub-	jec-	tive
s V b	dZ e k	t I v
sub-	ject
s V b	dZ e k t
sub-	jects
s V b	dZ I k t s
sub-	ject's
s V b	dZ I k t s
sub-	ju-	ga-	ted
s V b	dZ V	g eI	t V d
sub-	ju-	gate
s V b	dZ V	g eI t
sub-	king-	dom
s V b	k I N	d V m
sub-	lea-	sing
s V b	l i:	s I N
sub-	lease
s V b	l i: s
sub-	let
s V b	l e t
sub-	lett
s u: b	l e t
sub-	li-	mi-	nal
s V b	l I	m V	n V l
sub-	li-	mi-	nal-	ly
s V b	l I	m V	n V	l i:
sub-	lime
s V b	l aI m
sub-	lu-	xa-	tion
s V b	l V k	s eI	S V n
sub-	lu-	xa-	tions
s V b	l V k	s eI	S V n z
sub-	ma-	chine
s V b	m I	S i: n
sub-	ma-	rine
s V b	m @r	i: n
sub-	ma-	rines
s V b	m @r	i: n z
sub-	ma-	rine's
s V b	m @r	i: n z
sub-	mer-	gence
s V b	m @r	dZ V n s
sub-	mer-	si-	ble
s V b	m @r	s V	b V l
sub-	mer-	sion
s V b	m @r	Z V n
sub-	merge
s V b	m @r dZ
sub-	merged
s V b	m @r dZ d
sub-	merse
s V b	m @r s
sub-	mersed
s V b	m @r s t
sub-	mi-	ni-	mum
s V b	m I	n V	m V m
sub-	mis-	sion
s V b	m I	S V n
sub-	mis-	sions
s V b	m I	S V n z
sub-	mis-	sive
s V b	m I	s I v
sub-	mit
s V b	m I t
sub-	mit-	ted
s V b	m I	t V d
sub-	mit-	ting
s V b	m I	t I N
sub-	mits
s V b	m I t s
sub-	note-	book
s V b	n @U t	b U k
sub-	or-	di-	na-	ted
s V	b O@	d V	n eI	t V d
sub-	or-	di-	na-	ting
s V	b O@	d V	n eI	t I N
sub-	or-	di-	na-	tion
s V	b O@	d V	n eI	S V n
sub-	or-	di-	nate
s V	b O@	d V	n eI t
sub-	or-	di-	nates
s V	b O@	d V	n eI t s
sub-	par
s V b	p Q@
sub-	poe-	na
s V	p i:	n V
sub-	poe-	na-	ing
s V	p i:	n V	I N
sub-	poe-	naed
s V	p i:	n V d
sub-	poe-	nas
s V	p i:	n V z
sub-	prin-	ci-	pal
s V b	p r I n	s V	p V l
sub-	prin-	ci-	pals
s V b	p r I n	s V	p V l z
sub-	sa-	ha-	ran
s V b	s V	h e@	V n
sub-	se-	quent
s V b	s V k	w V n t
sub-	se-	quent-	ly
s V b	s V k	w V n	t l i:
sub-	sec-	tion
s V b	s e k	S V n
sub-	ser-	vi-	ence
s V b	s @r	v i:	V n s
sub-	ser-	vi-	ent
s V b	s @r	v i:	V n t
sub-	set
s V b	s e t
sub-	si-	ded
s V b	s aI	d V d
sub-	si-	dence
s V b	s aI	d V n s
sub-	si-	di-	a-	ries
s V b	s I	d i:	e@	i: z
sub-	si-	di-	a-	ry
s V b	s I	d i:	e@	i:
sub-	si-	di-	a-	ry's
s V b	s I	d i:	e@	i: z
sub-	si-	di-	za-	tion
s V b	s I	d I	z eI	S V n
sub-	si-	di-	zes
s V b	s I	d aI	z V z
sub-	si-	di-	zing
s V b	s I	d aI	z I N
sub-	si-	dies
s V b	s I	d i: z
sub-	si-	ding
s V b	s aI	d I N
sub-	si-	dize
s V b	s I	d aI z
sub-	si-	dized
s V b	s I	d aI z d
sub-	si-	dy
s V b	s I	d i:
sub-	side
s V b	s aI d
sub-	sides
s V b	s aI d z
sub-	sis-	tence
s V b	s I s	t e n s
sub-	sist
s V b	s I s t
sub-	soil
s V b	s OI l
sub-	sur-	face
s V b	s @r	f V s
sub-	sys-	tem
s V b	s I s	t V m
sub-	sys-	tems
s V b	s I s	t V m z
sub-	t-	ler
s V	t V	l @r
sub-	t-	ly
s V	t V	l i:
sub-	ter-	fuge
s V b	t @r f	j u: dZ
)"
R"(sub-	ter-	ra-	ne-	an
s V b	t @r	eI	n i:	V n
sub-	text
s V b	t e k s t
sub-	ti-	tle
s V b	t aI	t V l
sub-	ti-	tled
s V b	t aI	t V l d
sub-	ti-	tles
s V b	t aI	t V l z
sub-	tle
s V	t V l
sub-	tle-	ties
s V	t V l	t i: z
sub-	tle-	ty
s V	t V l	t i:
sub-	type
s V b	t aI p
sub-	ver-	sion
s V b	v @r	Z V n
sub-	ver-	sive
s V b	v @r	s I v
sub-	ver-	sives
s V b	v @r	s I v z
sub-	ver-	ted
s V b	v @r	t V d
sub-	ver-	ting
s V b	v @r	t I N
sub-	vert
s V b	v @r t
sub-	verts
s V b	v @r t s
sub-	way
s V b	w eI
sub-	ways
s V b	w eI z
sub-	ze-	ro
s V b	z I@	@U
subbed
s V b d
subp-	lot
s V b	p l Q t
subp-	lots
s V b	p l Q t s
subs
s V b z
sub's
s V b z
subs-	cri-	ber
s V b	s k r aI	b @r
subs-	cri-	bers
s V b	s k r aI	b @r z
subs-	cri-	ber's
s V b	s k r aI	b @r z
subs-	cri-	bing
s V b	s k r aI	b I N
subs-	cribe
s V b	s k r aI b
subs-	cribed
s V b	s k r aI b d
subs-	cribes
s V b	s k r aI b z
subs-	crip-	tion
s V b	s k r I p	S V n
subs-	crip-	tions
s V b	s k r I p	S V n z
subs-	ta-	tion
s V b	s t eI	S V n
)"