R"(un-	fair-	ly
V n	f e@	l i:
un-	fair-	ness
V n	f e@	n V s
un-	faith-	ful
V n	f eI T	f V l
un-	fazed
V n	f eI z d
un-	fea-	si-	ble
V n	f i:	z V	b V l
un-	fee-	ling
V n	f i:	l I N
un-	fenced
V n	f e n s t
un-	fet-	tered
V n	f e	t @r d
un-	fi-	nished
V n	f I	n I S t
un-	fil-	tered
V n	f I l	t @r d
un-	filled
V n	f I l d
un-	fit
V n	f I t
un-	flag-	ging
V n	f l {	g I N
un-	flap-	pa-	ble
V n	f l {	p V	b V l
un-	flat-	te-	ring
V n	f l {	t @r	I N
un-	flin-	ching
V n	f l I n	tS I N
un-	fo-	cused
V n	f @U	k V s t
un-	fol-	ded
V n	f @U l	d V d
un-	fol-	ding
V n	f @U l	d I N
un-	fold
V n	f @U l d
un-	folds
V n	f @U l d z
un-	for-	get-	ta-	ble
V n	f @r	g e	t V	b V l
un-	for-	gi-	va-	ble
V n	f O@	g I	v V	b V l
un-	for-	gi-	ven
V n	f O@	g I	v V n
un-	for-	gi-	ving
V n	f @r	g I	v I N
un-	for-	tu-	nate
V n	f O@	tS V	n V t
un-	for-	tu-	nate-	ly
V n	f O@	tS V	n V t	l i:
un-	for-	tu-	nates
V n	f O@	tS V	n V t s
un-	fore-	see-	a-	ble
V n	f O@	s i:	V	b V l
un-	fore-	seen
V n	f O@	s i: n
un-	formed
V n	f O@ m d
un-	foun-	ded
V n	f aU n	d V d
un-	friend-	ly
V n	f r e n	d l i:
un-	fro-	zen
V n	f r @U	z V n
un-	ful-	filled
V n	f U l	f I l d
un-	fun-	ded
V n	f V n	d V d
un-	fun-	ni-	ly
V n	f V	n V	l i:
un-	fur-	ling
V n	f @r	l I N
un-	furl
V n	f @r l
un-	furled
V n	f @r l d
un-	ga-	ro
u: N	g Q@	@U
un-	gain-	ly
V n	g eI n	l i:
un-	ger
V N	g @r
un-	gla-	mo-	rous
V n	g l {	m @r	V s
un-	go-	ver-	na-	ble
V n	g V	v @r	n V	b V l
un-	god-	ly
V n	g O: d	l i:
un-	grate-	ful
V n	g r eI t	f V l
un-	guar-	ded
V n	g Q@	d V d
un-	ham-	pered
V n	h { m	p @r d
un-	hap-	pi-	ly
V n	h {	p V	l i:
un-	hap-	pi-	ness
V n	h {	p i:	n V s
un-	hap-	py
V n	h {	p i:
un-	harmed
V n	h Q@ m d
un-	he-	ral-	ded
V n	h e@	V l	d V d
un-	he-	si-	ta-	ting-	ly
V n	h e	z V	t eI	t I N	l i:
un-	heal-	thy
V n	h e l	T i:
un-	health-	ful
V n	h e l	T f V l
un-	heard
V n	h @r d
un-	hedged
V n	h e dZ d
un-	hee-	ded
V n	h i:	d V d
un-	help-	ful
V n	h e l	p f V l
un-	hi-	ndered
V n	h I n	d @r d
un-	hinge
V n	h I n dZ
un-	hinged
V n	h I n dZ d
un-	hitch
V n	h I tS
un-	ho-	ly
V n	h @U	l i:
un-	hook
V n	h U k
un-	horsed
V n	h O@ s t
un-	hur-	ried
V n	h @r	i: d
un-	hurt
V n	h @r t
un-	i-	den-	ti-	fied
V	n aI	d e n	t I	f aI d
un-	i-	ni-	ti-	a-	ted
V	n I	n I	S i:	eI	t V d
un-	in-	jured
V	n I n	dZ @r d
un-	in-	su-	ra-	ble
V	n I n	S U@	V	b V l
un-	in-	sured
V	n I n	S U@ d
un-	in-	tel-	li-	gi-	ble
V	n I n	t e	l I	dZ I	b V l
un-	in-	ten-	ded
V	n I n	t e n	d V d
un-	in-	ten-	tio-	nal
V	n I n	t e n	S V	n V l
un-	in-	ten-	tio-	nal-	ly
V	n I n	t e n	S V	n V	l i:
un-	in-	ter-	rup-	ted
V	n I n	t @r	V p	t V d
un-	in-	ter-	rup-	ti-	ble
V	n I n	t @r	V p	t V	b V l
un-	in-	vi-	ted
V	n I n	v aI	t V d
un-	in-	vi-	ting
V	n I n	v aI	t I N
un-	in-	volved
V	n I n	v O: l v d
un-	ins-	pi-	red
V	n I n	s p aI	@r d
un-	ins-	pi-	ring
V	n I n	s p aI	r I N
un-	inte-	res-	ted
V	n I n	t r V s	t V d
un-	inte-	res-	ting
V	n I n	t r V s	t I N
un-	jus-	ti-	fi-	a-	ble
V n	dZ V s	t I	f aI	V	b V l
un-	jus-	ti-	fi-	ab-	ly
V n	dZ V s	t I	f aI	V b	l i:
un-	jus-	ti-	fied
V n	dZ V s	t V	f aI d
un-	just
V n	dZ V s t
un-	just-	ly
V n	dZ V s	t l i:
un-	kempt
V n	k e m p t
un-	kin-	dest
V n	k aI n	d V s t
un-	kind
V n	k aI n d
un-	kno-	wa-	ble
V n	n @U	V	b V l
un-	kno-	wing
V n	n @U	I N
un-	kno-	wing-	ly
V n	n @U	I N	l i:
un-	known
V n	n @U n
un-	knowns
V	n @U n z
un-	la-	beled
V n	l eI	b V l d
un-	land
V n	l V n d
un-	law-	ful
V n	l O:	f V l
un-	law-	ful-	ly
V n	l O:	f V	l i:
un-	lea-	ded
V n	l e	d V d
un-	lea-	shes
V n	l i:	S V z
un-	lea-	shing
V n	l i:	S I N
un-	leash
V n	l i: S
un-	leashed
V n	l i: S t
un-	less
V n	l e s
un-	li-	censed
V n	l aI	s V n s t
un-	li-	mi-	ted
V n	l I	m V	t V d
un-	li-	va-	ble
V n	l I	v V	b V l
un-	like
V n	l aI k
un-	like-	ly
V n	l aI k	l i:
un-	lined
V n	l aI n d
un-	lis-	ted
V n	l I s	t V d
un-	loa-	ded
V n	l @U	d V d
un-	loa-	ding
V n	l @U	d I N
un-	load
V n	l @U d
un-	loads
V n	l @U d z
un-	loc-	king
V n	l Q	k I N
un-	lock
V n	l Q k
un-	locked
V n	l Q k t
un-	loved
V n	l V v d
un-	luc-	ky
V n	l V	k i:
un-	ma-	na-	gea-	ble
V n	m {	n I	dZ V	b V l
un-	ma-	naged
V n	m {	n I dZ d
un-	made
V n	m eI d
un-	manned
V n	m { n d
un-	mar-	ried
V n	m e@	i: d
un-	marked
V n	m Q@ k t
un-	mask
V n	m { s k
un-	masked
V n	m { s k t
un-	matched
V n	m { tS t
un-	men-	tio-	na-	ble
V n	m e n	S V	n V	b V l
un-	men-	tioned
V n	m e n	tS V n d
un-	met
V n	m e t
un-	mi-	ti-	ga-	ted
V n	m I	t V	g eI	t V d
un-	mis-	ta-	ka-	ble
V n	m I s	t eI	k V	b V l
un-	mis-	ta-	kab-	ly
V n	m I s	t eI	k V b	l i:
un-	mixed
V n	m I k s t
un-	mo-	les-	ted
V n	m V	l e s	t V d
un-	moved
V n	m u: v d
un-	na-	tu-	ral
V n	n {	tS @r	V l
un-	na-	tu-	ral-	ly
V n	n {	tS @r	V	l i:
un-	named
V n	n eI m d
un-	ne-	ces-	sa-	ri-	ly
V n	n e	s V	s e@	V	l i:
un-	ne-	ces-	sa-	ry
V n	n e	s V	s e@	i:
un-	nee-	ded
V n	n i:	d V d
un-	ner-	ving
V	n @r	v I N
un-	nerve
V	n @r v
un-	nerved
V n	n @r v d
un-	no-	ticed
V n	n @U	t V s t
un-	o-	pened
V	n @U	p V n d
un-	oc-	cu-	pied
V	n Q k	j V	p aI d
un-	of-	fi-	cial
V	n V	f I	S V l
un-	of-	fi-	cial-	ly
V	n V	f I	S V	l i:
un-	op-	posed
V	n V	p @U z d
un-	or-	ga-	nized
V	n O@	g V	n aI z d
un-	or-	tho-	dox
V	n O@	T V	d Q k s
un-	pa-	la-	ta-	ble
V n	p {	l V	t V	b V l
un-	pa-	ral-	leled
V n	p e@	V	l e l d
un-	pa-	tri-	o-	tic
V n	p eI t	r i:	Q	t I k
un-	pac-	king
V n	p {	k I N
un-	pack
V n	p { k
un-	packed
V n	p { k t
un-	paid
V n	p eI d
un-	pain-	ted
V n	p eI n	t V d
un-	pay-	a-	ble
V n	p eI	V	b V l
un-	per-	turbed
V n	p @r	t @r b d
un-	placed
V n	p l eI s t
un-	planned
V n	p l { n d
un-	plea-	sant
V n	p l e	z V n t
un-	plea-	sant-	ly
V n	p l e	z V n	t l i:
un-	plea-	sant-	ness
V n	p l e	z V n	t n V s
un-	plug
V n	p l V g
un-	plugged
V n	p l V g d
un-	po-	pu-	la-	ri-	ty
V n	p Q p	j V	l e@	V	t i:
un-	po-	pu-	lar
V n	p Q p	j V	l @r
un-	pre-	ce-	den-	ted
V n	p r e	s V	d e n	t V d
un-	pre-	ce-	den-	ted-	ly
V n	p r e	s V	d e n	t V d	l i:
un-	pre-	dic-	ta-	bi-	li-	ty
V n	p r V	d I k	t V	b I	l V	t i:
un-	pre-	dic-	ta-	ble
V n	p r V	d I k	t V	b V l
un-	pre-	dic-	tab-	ly
V n	p r V	d I k	t V b	l i:
un-	pre-	pared
V n	p r i:	p e@ d
un-	pre-	served
V n	p r V	z @r v d
un-	pre-	ten-	tious
V n	p r i:	t e n	S V s
un-	pres-	su-	rized
V n	p r e	S @r	aI z d
un-	prin-	ci-	pled
V n	p r I n	s V	p V l d
un-	prin-	ta-	ble
V n	p r I n	t V	b V l
un-	pro-	cessed
V n	p r O:	s e s t
un-	pro-	duc-	tive
V n	p r V	d V k	t I v
un-	pro-	fes-	sio-	nal
V n	p r V	f e	S V	n V l
un-	pro-	fi-	ta-	bi-	li-	ty
V n	p r Q	f V	t V	b I	l V	t i:
un-	pro-	fi-	ta-	ble
V n	p r Q	f V	t V	b V l
un-	pro-	mi-	sing
V n	p r O:	m I	s I N
un-	pro-	tec-	ted
V n	p r V	t e k	t V d
un-	pro-	ven
V n	p r u:	v V n
un-	pro-	voked
V n	p r V	v @U k t
un-	proved
V n	p r u: v d
un-	pu-	nished
V n	p V	n I S t
un-	pub-	li-	cized
V n	p V b	l V	s aI z d
un-	pub-	lished
V n	p V b	l I S t
un-	qua-	li-	fied
V n	k w Q	l V	f aI d
un-	ques-	tio-	na-	ble
V n	k w e s	tS V	n V	b V l
un-	ques-	tio-	nab-	ly
V n	k w e s	tS V	n V b	l i:
un-	ques-	tio-	ning
V n	k w e s	tS V	n I N
un-	ques-	tioned
V n	k w e s	tS V n d
un-	quote
V n	k w @U t
un-	ra-	ted
V n	r eI	t V d
un-	ra-	ti-	fied
V n	r {	t V	f aI d
un-	ra-	ve-	ling
V n	r {	v V	l I N
un-	ra-	vel
V n	r {	v V l
un-	ra-	veled
V n	r {	v V l d
un-	ra-	vels
V n	r {	v V l z
un-	re-	a-	li-	ty
V n	r i:	{	l I	t i:
un-	re-	a-	lis-	tical-	ly
V n	r i:	V	l I s	t I k	l i:
un-	re-	a-	lized
V n	r i:	V	l aI z d
un-	re-	cep-	tive
V n	r V	s e p	t I v
un-	re-	cog-	ni-	za-	ble
V n	r e	k V g	n aI	z V	b V l
un-	re-	cog-	nized
V n	r e	k V g	n aI z d
un-	re-	con-	ciled
V n	r e	k V n	s aI l d
un-	re-	con-	struc-	ted
V n	r i:	k V n	s t r V k	t V d
un-	re-	cor-	ded
V n	r I	k O@	d V d
un-	re-	deemed
V n	r i:	d i: m d
un-	re-	fined
V n	r i:	f aI n d
un-	re-	fu-	ted
V n	r i: f	j u:	t V d
un-	re-	gis-	tered
V n	r e	dZ V s	t @r d
un-	re-	gu-	la-	ted
V n	r e g	j V	l eI	t V d
un-	re-	hearsed
V n	r i:	h @r s t
un-	re-	la-	ted
V n	r V	l eI	t V d
un-	re-	leased
V n	r V	l i: s t
un-	re-	len-	ting
V n	r i:	l e n	t I N
un-	re-	li-	a-	bi-	li-	ty
V n	r i:	l aI	V	b I	l V	t i:
un-	re-	li-	a-	ble
V n	r V	l aI	V	b V l
un-	re-	lieved
V n	r i:	l i: v d
un-	re-	mar-	ka-	ble
V n	r V	m Q@	k V	b V l
un-	re-	marked
V n	r V	m Q@ k t
un-	re-	mit-	ted
V n	r V	m I	t V d
un-	re-	mit-	ting
V n	r V	m I	t I N
un-	re-	pen-	tant
V n	r V	p e n	t V n t
un-	re-	por-	ted
V n	r i:	p O@	t V d
un-	re-	pre-	sen-	ta-	tive
V n	r e p	r V	z e n	t V	t I v
un-	re-	pre-	sen-	ted
V n	r e p	r V	z e n	t V d
un-	re-	qui-	ted
V n	r i: k	w aI	t V d
un-	re-	solved
V n	r V	z Q l v d
un-	re-	vised
V n	r i:	v aI z d
un-	rea-	cha-	ble
V n	r i:	tS V	b V l
un-	rea-	da-	ble
V n	r i:	d V	b V l
un-	rea-	lis-	tic
V n	r i:	l I s	t I k
un-	rea-	so-	nab-	ly
V n	r i:	z V	n V b	l i:
un-	read
V n	r e d
un-	real
V n	r i: l
un-	reaso-	na-	ble
V n	r i: z	n V	b V l
un-	reaso-	ning
V n	r i: z	n I N
un-	rein
O: n	r aI n
un-	res-	pon-	sive
V n	r i: s	p Q n	s I v
un-	rest
V n	r e s t
un-	rest-	rained
V n	r i: s	t r eI n d
un-	rest-	ric-	ted
V n	r i: s	t r I k	t V d
un-	ri-	valed
V n	r aI	v V l d
un-	ring
V n	r I N
un-	ru-	ly
V n	r u:	l i:
un-	ruf-	fled
V n	r V	f V l d
un-	sa-	la-	ble
V n	s eI	l V	b V l
un-	sa-	lea-	ble
V n	s eI	l V	b V l
un-	sa-	ni-	ta-	ry
V n	s {	n V	t e@	i:
un-	sa-	tis-	fac-	to-	ry
V n	s V	t V s	f { k	t @r	i:
un-	sa-	tis-	fied
V n	s {	t V s	f aI d
un-	sa-	tis-	fy-	ing
V n	s {	t V s	f aI	I N
un-	sa-	tu-	ra-	ted
V n	s {	tS @r	eI	t V d
un-	sa-	vo-	ry
V n	s eI	v @r	i:
un-	safe
V n	s eI f
un-	said
V n	s e d
un-	sanc-	tioned
V n	s { N	k S V n d
un-	scathed
V n	s k eI D d
un-	sche-	duled
V n	s k e	dZ u: l d
un-	sci-	en-	ti-	fic
V n	s aI	V n	t I	f I k
un-	scram-	ble
V n	s k r { m	b V l
un-	scrip-	ted
V n	s k r I p	t V d
un-	scru-	pu-	lous
V n	s k r u: p	j V	l V s
un-	se-	cured
V n	s I k	j U@ d
un-	sea-	so-	nab-	ly
V n	s i:	z V	n V b	l i:
un-	sea-	ted
V n	s i:	t V d
un-	sea-	ting
V n	s i:	t I N
un-	seal
V n	s i: l
un-	sealed
V n	s i: l d
un-	seat
V n	s i: t
un-	seem-	ly
V n	s i: m	l i:
un-	seen
V n	s i: n
un-	sell
O: n	s V l
un-	sen-	ti-	men-	tal
V n	s e n	t V	m e n	t V l
un-	ser-	vi-	cea-	ble
V n	s @r	v I	s V	b V l
un-	set
V n	s e t
un-	set-	t-	ling
V n	s e	t V	l I N
un-	set-	tle
V n	s e	t V l
un-	set-	tled
V n	s e	t V l d
un-	sha-	ka-	ble
V n	S eI	k V	b V l
un-	sha-	kea-	ble
V n	S eI	k V	b V l
un-	sha-	ken
V n	S eI	k V n
un-	sha-	ven
V n	S eI	v V n
un-	shac-	kle
V n	S {	k V l
un-	shac-	kled
V n	S {	k V l d
un-	shar-	pened
V n	S Q@	p V n d
un-	sight-	ly
V n	s aI t	l i:
un-	signed
V n	s aI n d
un-	sin-	ka-	ble
V n	s I N	k V	b V l
un-	skilled
V n	s k I l d
un-	smi-	ling
V n	s m aI	l I N
un-	so-	li-	ci-	ted
V n	s V	l I	s V	t V d
un-	so-	phis-	ti-	ca-	ted
V n	s V	f I s	t I	k eI	t V d
un-	sol-	va-	ble
V n	s Q l	v V	b V l
un-	sold
V n	s @U l d
un-	solved
V n	s Q l v d
un-	sound
V n	s aU n d
un-	spa-	ring
V n	s p e@	I N
un-	spe-	ci-	fied
V n	s p e	s V	f aI d
un-	spea-	ka-	ble
V n	s p i:	k V	b V l
un-	spec-	ta-	cu-	lar
V n	s p e k	t { k	j V	l @r
un-	spent
V n	s p e n t
un-	spo-	ken
V n	s p @U	k V n
un-	spoiled
V n	s p OI l d
un-	sports-	man-	like
V n	s p O@ t	s m V n	l aI k
un-	sta-	ble
V n	s t eI	b V l
un-	sta-	ted
V n	s t eI	t V d
un-	stained
V n	s t eI n d
un-	stea-	dy
V n	s t e	d i:
un-	stin-	ting
V n	s t I n	t I N
un-	stop-	pa-	ble
V n	s t Q	p V	b V l
un-	struc-	tured
V n	s t r V k	S @r d
un-	stuck
V n	s t V k
un-	su-	per-	vised
V n	s u:	p @r	v aI z d
un-	sub-	si-	dized
V n	s V b	s V	d aI z d
un-	sub-	tle
V n	s V	t V l
un-	subs-	cribed
V n	s V b	s k r aI b d
un-	subs-	tan-	ti-	a-	ted
V n	s V b	s t { n	S i:	eI	t V d
un-	suc-	cess-	ful
V n	s V k	s e s	f V l
un-	suc-	cess-	ful-	ly
V n	s V k	s e s	f V	l i:
un-	sui-	ta-	ble
V n	s u:	t V	b V l
un-	sui-	ted
V n	s u:	t V d
un-	sul-	lied
V n	s V	l i: d
un-	sung
V n	s V N
un-	sup-	por-	ta-	ble
V n	s V	p O@	t V	b V l
un-	sup-	por-	ted
V n	s V	p O@	t V d
un-	sur-	passed
V n	s @r	p { s t
un-	sur-	pri-	sing
V n	s @r p	r aI	z I N
un-	sur-	pri-	sing-	ly
V n	s @r p	r aI	z I N	l i:
un-	sure
V n	S U@
un-	sus-	pec-	ted
V n	s V s	p e k	t V d
un-	sus-	pec-	ting
V n	s V s	p e k	t I N
un-	sus-	tai-	na-	ble
V n	s V s	t eI	n V	b V l
un-	sus-	tai-	nab-	ly
V n	s V s	t eI	n V b	l i:
un-	sym-	pa-	the-	tic
V n	s I m	p V	T e	t I k
un-	tain-	ted
V n	t eI n	t V d
un-	tan-	gle
V n	t { N	g V l
un-	tang-	ling
V n	t { N	l I N
un-	tapped
V n	t { p t
un-	taxed
V n	t { k s t
un-	te-	na-	ble
V n	t e	n V	b V l
un-	ten-	dered
V n	t e n	d @r d
un-	ter-	meyer
V n	t @r	m aI r
un-	tes-	ted
V n	t e s	t V d
un-	thin-	ka-	ble
V n	T I N	k V	b V l
un-	thin-	king
V n	T I N	k I N
un-	thin-	king-	ly
V n	T I N	k I N	l i:
un-	ti-	dy
V n	t aI	d i:
un-	tie
V n	t aI
un-	tied
V n	t aI d
un-	til
V n	t I l
un-	time-	ly
V n	t aI m	l i:
un-	to
V n	t u:
un-	to-	ward
V n	t u:	O@ d
un-	told
V n	t @U l d
un-	tou-	cha-	ble
V n	t V	tS V	b V l
un-	tou-	cha-	bles
V n	t V	tS V	b V l z
un-	touched
V n	t V tS t
un-	tra-	cea-	ble
V n	t r eI	s V	b V l
un-	tra-	di-	tio-	nal
V n	t r V	d I	S V	n V l
un-	trained
V n	t r eI n d
un-	tram-	meled
V n	t r {	m V l d
un-	trea-	ta-	ble
V n	t r i:	t V	b V l
un-	trea-	ted
V n	t r i:	t V d
un-	tried
V n	t r aI d
un-	trou-	bled
V n	t r V	b V l d
un-	true
V n	t r u:
un-	trust-	wor-	thy
V n	t r V s	t w @r	D i:
un-	truth
V n	t r u: T
un-	truth-	ful
V n	t r u: T	f V l
un-	truths
V n	t r u: T s
un-	turned
V n	t @r n d
un-	ty-	pi-	cal
V n	t I	p I	k V l
un-	u-	su-	al
V n	j u:	Z V	w V l
un-	u-	su-	al-	ly
V n	j u:	Z V	w V	l i:
un-	used
V n	j u: z d
un-	var-	nished
V n	v Q@	n I S t
un-	ve-	ri-	fi-	a-	ble
V n	v e@	V	f aI	V	b V l
un-	ve-	ri-	fied
V n	v e@	V	f aI d
un-	vei-	ling
V n	v eI	l I N
un-	veil
V n	v eI l
un-	veiled
V n	v eI l d
un-	veils
V n	v eI l z
un-	wa-	ry
V n	w e@	i:
un-	wa-	ve-	ring
V n	w eI	v @r	I N
un-	wan-	ted
V n	w O: n	t V d
un-	war-	ran-	ted
V n	w O@	V n	t V d
un-	washed
V n	w Q S t
un-	wed
V n	w e d
un-	wel-	come
V n	w e l	k V m
un-	wel-	comed
V n	w e l	k V m d
un-	wiel-	di-	ness
V n	w i: l	d i:	n V s
un-	wiel-	dy
V n	w i: l	d i:
un-	wil-	ling
V n	w I	l I N
un-	wil-	ling-	ly
V n	w I	l I N	l i:
un-	wil-	ling-	ness
V n	w I	l I N	n V s
un-	win-	ding
V n	w aI n	d I N
un-	win-	na-	ble
V n	w I	n V	b V l
un-	wind
V n	w aI n d
un-	wise
V n	w aI z
un-	wise-	ly
V n	w aI z	l i:
un-	wit-	ting
V n	w I	t I N
un-	wit-	ting-	ly
V n	w I	t I N	l i:
un-	wor-	ka-	ble
V n	w @r	k V	b V l
un-	wor-	ried
V n	w @r	i: d
un-	wor-	thy
V n	w @r	D i:
un-	wound
V n	w aU n d
un-	wra-	pping
V n	r {	p I N
un-	wrap
V n	r { p
un-	wrapped
V n	r { p t
un-	writ-	ten
V n	r I	t V n
un-	yiel-	ding
V n	j i: l	d I N
un-	zip
V n	z I p
un-	zipped
V n	z I p t
unc-	lean
V n	k l i: n
unc-	lear
V n	k l I@
unc-	les
V N	k V l z
unc-	lut-	tered
V n	k l V	t @r d
unc-	tad
V n	k t { d
unc-	tuous
V N	tS w V s
und
V n d
ung
V N
ung-	lue
V n	g l u:
ung-	lued
V n	g l u: d
uns-	wayed
V n	s w eI d
uns-	wer-	ving
V n	s w @r	v I N
up
V p
up-	beat
V p	b i: t
up-	brai-	ded
V p	b r eI	d V d
up-	braid
V p	b r eI d
up-	brin-	ging
V p	b r I	N I N
up-	co-	ming
V p	k V	m I N
up-	da-	ted
V p	d eI	t V d
up-	da-	ting
V p	d eI	t I N
up-	date
V p	d eI t
up-	dates
V p	d eI t s
up-	dike
V p	d aI k
up-	draft
V p	d r { f t
up-	drafts
V p	d r { f t s
up-	front
V p	f r V n t
up-	gra-	ded
V p	g r eI	d V d
up-	gra-	der
V p	g r eI	d @r
up-	gra-	ding
V p	g r eI	d I N
up-	grade
V p	g r eI d
up-	grades
V p	g r eI d z
up-	held
V p	h e l d
up-	hill
V p	h I l
up-	hol-	ding
V p	h @U l	d I N
up-	hold
V p	h @U l d
up-	holds
V p	h @U l d z
up-	hols-	te-	ry
V	p @U l	s t @r	i:
up-	hols-	ter
V	p @U l	s t @r
up-	hols-	tered
V	p @U l	s t @r d
up-	john
V p	dZ Q n
up-	john's
V p	dZ Q n z
up-	keep
V p	k i: p
up-	land
V p	l V n d
up-	lands
V p	l V n d z
up-	lif-	ted
V p	l I f	t V d
up-	lif-	ting
V p	l I f	t I N
up-	lift
V p	l I f t
up-	man-	ship
V p	m V n	S I p
up-	mar-	ket
V p	m Q@	k V t
up-	per
V	p @r
up-	per-	class
V	p @r k	l { s
up-	per-	most
V	p @r	m @U s t
up-	pers
V	p @r z
up-	pi-	ty
V	p I	t i:
up-	ping
V	p I N
up-	ri-	sing
V p	r aI	z I N
up-	ri-	sings
V p	r aI	z I N z
up-	ri-	ver
V p	r I	v @r
up-	right
V p	r aI t
up-	rights
V p	r aI t s
up-	rise
V p	r aI z
up-	roar
V p	r O@
up-	roo-	ted
V p	r u:	t V d
up-	roo-	ting
V p	r u:	t I N
up-	root
V p	r u: t
up-	scale
V p	s k eI l
up-	set
V p	s e t
up-	set-	ting
V p	s e	t I N
)"
R"(up-	sets
V p	s e t s
up-	shaw
V p	S O:
up-	shot
V p	S Q t
up-	si-	zing
V p	s aI	z I N
up-	side
V p	s aI d
up-	size
V p	s aI z
up-	son
V p	s V n
up-	stage
V p	s t eI dZ
up-	staged
V p	s t eI dZ d
up-	stairs
V p	s t e@ z
up-	stan-	ding
V p	s t { n	d I N
up-	start
V p	s t Q@ t
up-	starts
V p	s t Q@ t s
up-	state
V p	s t eI t
up-	stream
V p	s t r i: m
up-	surge
V p	s @r dZ
up-	swing
V p	s w I N
up-	swings
V p	s w I N z
up-	take
V p	t eI k
up-	tick
V p	t I k
up-	ticks
V p	t I k s
up-	tight
V p	t aI t
up-	ton
V p	t V n
up-	town
V p	t aU n
up-	trend
V p	t r e n d
up-	turn
V p	t @r n
up-	turns
V p	t @r n z
up-	ward
V p	w @r d
up-	ward-	ly
V p	w @r d	l i:
up-	wards
V p	w @r d z
upped
V p t
ups
V p s
ur
@r
ur-	ba-	na
@r	b {	n V
ur-	ba-	ni
@r	b Q	n i:
ur-	ba-	ni-	za-	tion
@r	b V	n V	z eI	S V n
ur-	ba-	nism
@r	b V	n I z m
ur-	ba-	nite
@r	b V	n aI t
ur-	ba-	nites
@r	b V	n aI t s
ur-	ba-	nize
@r	b V	n aI z
ur-	ba-	nized
@r	b V	n aI z d
ur-	ba-	no
@r	b Q	n @U
ur-	bain
@r	b eI n
ur-	ban
@r	b V n
ur-	bane
@r	b eI n
ur-	ban's
@r	b V n z
ur-	bas
@r	b V z
ur-	chin
@r	tS I n
ur-	chins
@r	tS I n z
ur-	du
@r	d u:
ur-	gen-	cy
@r	dZ V n	s i:
ur-	gent
@r	dZ V n t
ur-	gent-	ly
@r	dZ V n	t l i:
ur-	ges
@r	dZ V z
ur-	ging
@r	dZ I N
ur-	gings
@r	dZ I N z
ur-	man
@r	m V n
ur-	quhart
@r	k Q@ t
ur-	sa
@r	s V
ur-	so-	la
@r	s @U	l V
ur-	son
@r	s V n
ur-	su-	la
@r	s V	l V
ur-	sus
@r	s V s
ure
j u: r
urge
@r dZ
urged
@r dZ d
urn
@r n
us
V s
u's
j u: z
us-	ti-	nov
u: s	t I	n Q v
use
j u: s
use-	ful
j u: s	f V l
use-	ful-	ly
j u: s	f V	l i:
use-	ful-	ness
j u: s	f V l	n V s
use-	less
j u: s	l V s
use-	net
j u: z	n e t
used
j u: z d
ut-	ley
V t	l i:
ut-	most
V t	m @U s t
ut-	te-	ran-	ces
V	t @r	V n	s V z
ut-	te-	rance
V	t @r	V n s
ut-	te-	ring
V	t @r	I N
ut-	ter
V	t @r
ut-	ter-	ly
V	t @r	l i:
ut-	tered
V	t @r d
ut-	ters
V	t @r z
uz-	be-	kis-	tan
u: z	b e	k I s	t { n
uz-	bek
u: z	b e k
uz-	beks
u: z	b e k s
v
v i:
v-	s
v @r	s V z
v.
v i:
va-	ca
v {	k V
va-	ca-	ted
v eI	k eI	t V d
va-	ca-	ting
v eI	k eI	t I N
va-	ca-	tio-	ner
v eI	k eI	S V	n @r
va-	ca-	tio-	ners
v eI	k eI	S V	n @r z
va-	ca-	tio-	ning
v eI	k eI	S V	n I N
va-	ca-	tion
v eI	k eI	S V n
va-	ca-	tioned
v eI	k eI	S V n d
va-	ca-	tions
v eI	k eI	S V n z
va-	ca-	ville
v {	k V	v I l
va-	can-	cies
v eI	k V n	s i: z
va-	can-	cy
v eI	k V n	s i:
va-	cant
v eI	k V n t
va-	cate
v eI	k eI t
va-	cil-	la-	ted
v {	s I	l eI	t I d
va-	cil-	la-	ting
v {	s I	l eI	t I N
va-	cil-	la-	tion
v {	s I	l eI	S V n
va-	cil-	late
v {	s I	l eI t
va-	cu-	ous
v { k	j u:	V s
va-	cuu-	ming
v { k	j u:	m I N
va-	cuum
v { k	j u: m
va-	cuums
v { k	j u: m z
va-	das
v Q	d Q z
va-	den
v eI	d V n
va-	der
v eI	d @r
va-	dim
v Q	d i: m
va-	ga-	bond
v {	g V	b Q n d
va-	ga-	bonds
v {	g V	b Q n d z
va-	ga-	ries
v eI	g @r	i: z
va-	ga-	ry
v eI	g @r	i:
va-	gi-	na
v V	dZ aI	n V
va-	gi-	nal
v V	dZ aI	n V l
va-	guer
v eI	g @r
va-	guest
v eI	g I s t
va-	la
v Q	l V
va-	le-	da
v Q	l eI	d V
va-	le-	dic-	to-	ri-	an
v {	l V	d I k	t O@	i:	V n
va-	le-	dic-	to-	ry
v {	l V	d I k	t @r	i:
va-	le-	nt
v Q	l eI	V n t
va-	le-	ra
v V	l e@	V
va-	le-	ri-	a
v V	l i:	r i:	V
va-	le-	ri-	an
v V	l I@	i:	V n
va-	le-	ri-	o
v V	l i:	r i:	@U
va-	le-	rie
v {	l @r	i:
va-	le-	ry
v {	l @r	i:
va-	len-	ci-	a
v V	l e n	s i:	V
va-	len-	ci-	a's
v V	l e n	s i:	V z
va-	len-	ta
v V	l e n	t V
va-	len-	te
v Q	l e n	t i:
va-	len-	ti
v V	l e n	t i:
va-	len-	ti-	na
v {	l V n	t i:	n V
va-	len-	ti-	no
v {	l V n	t i:	n @U
va-	len-	ti-	no's
v {	l V n	t i:	n @U z
va-	len-	tia
v Q	l e n	S V
va-	len-	tin
v Q	l eI n	t i: n
va-	len-	tine
v {	l V n	t aI n
va-	len-	tines
v {	l V n	t aI n z
va-	len-	tine's
v {	l V n	t aI n z
va-	len-	za
v V	l e n	z V
va-	len-	zue-	la
v Q	l e n	z u:	l V
va-	lence
v eI	l V n s
va-	lens
v {	l V n z
va-	let
v {	l eI
va-	li-	da
v Q	l i:	d V
va-	li-	da-	ted
v {	l I	d eI	t I d
va-	li-	da-	ting
v {	l I	d eI	t I N
va-	li-	da-	tion
v {	l I	d eI	S V n
va-	li-	date
v {	l I	d eI t
va-	li-	dates
v {	l I	d eI t s
va-	li-	di-	ty
v V	l I	d I	t i:
va-	li-	um
v eI	l i:	V m
va-	liant
v { l	j V n t
va-	liant-	ly
v { l	j V n	t l i:
va-	lid
v {	l I d
va-	lid-	ly
v {	l I d	l i:
va-	lis
v {	l I s
va-	lo-	nia
v V	l @U n	j V
va-	lois
v { l	w Q
va-	lor
v {	l @r
va-	lu-	a-	tion
v { l	j u:	eI	S V n
va-	lu-	a-	tions
v { l	j u:	eI	S V n z
va-	lu-	ing
v { l	j u:	I N
va-	lua-	bles
v { l	j V	b V l z
va-	lue
v { l	j u:
va-	lue-	less
v { l	j u:	l V s
va-	lued
v { l	j u: d
va-	lues
v { l	j u: z
va-	mos
v Q	m @U z
va-	na-	di-	um
v V	n eI	d i:	V m
va-	nal-	styne
v {	n V l	s t aI n
va-	nat-	ta
v Q	n Q	t V
va-	nes-	sa
v V	n e	s V
va-	net-	ten
v {	n e	t V n
va-	ni-	a
v Q	n i:	V
va-	ni-	er
v {	n i:	@r
va-	ni-	shes
v {	n I	S V z
va-	ni-	shing
v {	n I	S I N
va-	ni-	ties
v {	n V	t i: z
va-	ni-	ty
v {	n I	t i:
va-	nil-	la
v V	n I	l V
va-	nil-	lin
v V	n I	l V n
va-	nish
v {	n I S
va-	nished
v {	n I S t
va-	no
v Q	n @U
va-	nu-	a-	tu
v {	n u:	Q	t u:
va-	pid
v {	p V d
va-	po-	ri-	za-	tion
v eI	p @r	I	z eI	S V n
va-	po-	rize
v eI	p @r	aI z
va-	po-	rized
v eI	p @r	aI z d
va-	por
v eI	p @r
va-	por-	ware
v eI	p @r	w e@
va-	pors
v eI	p @r z
va-	ra
v Q@	V
va-	ra-	dy
v @r	Q	d i:
va-	res
v Q@	e s
va-	ri
v Q@	i:
va-	ri-	a-	bi-	li-	ty
v e@	i:	V	b I	l V	t i:
va-	ri-	a-	ble
v e@	i:	V	b V l
va-	ri-	a-	bles
v e@	i:	V	b V l z
va-	ri-	a-	tion
v e@	i:	eI	S V n
va-	ri-	a-	tions
v e@	i:	eI	S V n z
va-	ri-	an
v e@	i:	V n
va-	ri-	an-	ces
v e@	i:	V n	s V z
va-	ri-	ance
v e@	i:	V n s
va-	ri-	ant
v e@	i:	V n t
va-	ri-	ants
v e@	i:	V n t s
va-	ri-	e-	tals
v @r	aI	V	t V l z
va-	ri-	e-	ties
v @r	aI	V	t i: z
va-	ri-	e-	ty
v @r	aI	V	t i:
va-	ri-	na
v Q@	i:	n V
va-	ri-	ous
v e@	i:	V s
va-	ri-	ous-	ly
v e@	i:	V s	l i:
va-	ri-	ty-	per
v e@	I	t aI	p @r
va-	rick
v e@	I k
va-	rie-	tal
v @r	i:	t V l
va-	ried
v e@	i: d
va-	ries
v e@	i: z
va-	ry
v e@	i:
va-	ry-	ing
v e@	i:	I N
va-	se-	line
v {	s V	l i: n
va-	sec-	to-	mies
v {	z e k	t V	m i: z
va-	sec-	to-	my
v {	z e k	t V	m i:
va-	ses
v eI	s V z
va-	si-	ly
v {	s I	l i:
va-	ti-	can
v {	t I	k V n
va-	ti-	can's
v {	t I	k V n z
va-	xes
v { k	s V z
vaal
v Q l
vac-	ci-	na-	ted
v { k	s I	n eI	t I d
vac-	ci-	na-	tion
v { k	s I	n eI	S V n
vac-	ci-	na-	tions
v { k	s I	n eI	S V n z
vac-	ci-	nate
v { k	s I	n eI t
vac-	ci-	ni-	a
v V	tS i:	n i:	V
vac-	cine
v { k	s i: n
vac-	cines
v { k	s i: n z
vac-	cine's
v { k	s i: n z
vac-	lav
v { k	l Q v
vag-	ran-	cy
v eI g	r V n	s i:
vag-	rant
v eI g	r V n t
vag-	rants
v eI g	r V n t s
vague
v eI g
vague-	ly
v eI g	l i:
vague-	ness
v eI g	n V s
vail
v eI l
vain
v eI n
vain-	ly
v eI n	l i:
val
v { l
val-	da
v Q l	d V
val-	de-	mar
v Q l	d eI	m Q@
val-	des
v { l	d e z
val-	dez
v { l	d e z
val-	di-	vi-	a
v Q l	d i:	v i:	V
val-	dis
v { l	d I s
val-	dos-	ta
v { l	d O: s	t V
val-	hal-	la
v { l	h {	l V
val-	la
v {	l V
val-	lar-	ta
v {	l Q@	t V
val-	le-	jo
v Q	l eI	j @U
val-	le-	ry
v {	l @r	i:
val-	leau
v V	l @U
val-	ley
v {	l i:
val-	leys
v {	l i: z
val-	ley's
v {	l i: z
val-	li
v {	l i:
val-	li-	ant
v Q	l i:	V n t
val-	lie
v O:	l i:
val-	lis
v {	l I s
val-	lo
v {	l @U
val-	mey-	er
v { l	m aI	@r
val-	pa-	rai-	so
v { l	p @r	eI	s @U
val-	vo-	line
v { l	v V	l i: n
vale
v eI l
vales
v eI l z
valle
v eI l
valve
v { l v
valves
v { l v z
vam-	pi-	ric
v { m	p I@	I k
vam-	pire
v { m	p aI r
vam-	pires
v { m	p aI r z
vam-	pire's
v { m	p aI r z
vamp
v { m p
van
v { n
van-	co-	my-	cin
v { n	k @U	m aI	s I n
van-	cou-	ver
v { n	k u:	v @r
van-	cou-	ver's
v { n	k u:	v @r z
van-	court
v V n	k O@ t
van-	da-	li-	sm
v { n	d V	l I	z V m
van-	da-	li-	zing
v { n	d V	l aI	z I N
van-	da-	lize
v { n	d V	l aI z
van-	da-	lized
v { n	d V	l aI z d
van-	dal
v { n	d V l
van-	dals
v { n	d V l z
van-	den
v { n	d V n
van-	den-	berg
v { n	d V n	b @r g
van-	der
v { n	d @r
van-	der-	bilt
v { n	d @r	b I l t
van-	der-	grift
v { n	d @r g	r I f t
van-	der-	grift's
v { n	d @r g	r I f t s
van-	der-	poel
v { n	d @r	p @U l
van-	der-	pool
v { n	d @r	p u: l
van-	der-	velde
v { n	d @r	v e l d
van-	der-	voort
v { n	d @r	v U@ t
van-	di-	ver
v { n	d aI	v @r
van-	dyke
v { n	d aI k
van-	dyne
v { n	d aI n
van-	gogh
v { n	g @U
van-	guard
v { n	g Q@ d
van-	guard's
v { n	g Q@ d z
van-	hook
v { n	h U k
van-	horn
v { n	h O@ n
van-	na
v {	n V
van-	ni
v {	n i:
van-	nie
v {	n i:
van-	ny
v {	n i:
van-	quish
v { N	k w I S
van-	quished
v { N	k w I S t
van-	sant
v Q n	s V n t
van-	ta-	ges
v { n	t I	dZ V z
van-	ta-	ge's
v { n	t I	dZ V z
van-	tage
v { n	t V dZ
van-	tas-	sell
v { n	t {	s V l
van-	wert
v { n	w @r t
van-	wyck
v { n	w I k
van-	ya
v Q n	j V
van-	ya's
v Q n	j V z
van-	zant
v Q n	z V n t
vance
v { n s
vane
v eI n
vanes
v eI n z
vang
v { N
vans
v { n z
vanv-	leck
v { n	v l e k
var-	den
v Q@	d V n
var-	don
v Q@	d O: n
var-	ga
v Q@	g V
var-	gas
v Q@	g V s
var-	ley
v Q@	l i:
var-	mint
v Q@	m I n t
var-	nell
v Q@	n V l
var-	ney
v Q@	n i:
var-	ni-	shes
v Q@	n I	S V z
var-	nish
v Q@	n I S
var-	nished
v Q@	n I S t
var-	si-	ty
v Q@	s I	t i:
var-	vel
v Q@	v e l
vars
v Q@ z
varves
v Q@ v z
vas-	co
v { s	k @U
vas-	cu-	lar
v { s	k j V	l @r
vas-	quez
v { s	k e z
vas-	sal
v {	s V l
vas-	sals
v {	s V l z
vas-	sar
v {	s @r
vas-	ta
v { s	t V
vase
v eI s
vash-	ti
v { S	t i:
vass
v { s
vast
v { s t
vast-	ly
v { s	t l i:
vast-	ness
v { s	t n V s
vat
v { t
vat-	ted
v {	t V d
vat-	ter
v {	t @r
vats
v { t s
vaude-	vil-	lian
v Q d	v I l	j V n
vaude-	ville
v Q d	v I l
vaughan
v O: n
vaughan's
v O: n z
vaughn
v O: n
vaughn's
v O: n z
vaul-	ted
v O: l	t V d
vaul-	ting
v O: l	t I N
vault
v O: l t
vaults
v O: l t s
vaun-	ted
v O: n	t V d
vaux-	hall
v Q k	s h O: l
vax
v { k s
vaz-	quez
v { s	k e z
ve
v i:
ve-	cel-	li-	o
v e	tS e	l i:	@U
ve-	da
v eI	d V
ve-	dette
v V	d e t
ve-	dis
v eI	d I s
ve-	ga
v eI	g V
ve-	gas
v eI	g V s
ve-	ge-	ta-	ri-	a-	ni-	sm
v e	dZ V	t e@	i:	V	n I	z V m
ve-	ge-	ta-	ri-	an
v e	dZ V	t e@	i:	V n
ve-	ge-	ta-	ri-	ans
v e	dZ V	t e@	i:	V n z
ve-	ge-	ta-	tion
v e	dZ V	t eI	S V n
ve-	ge-	ta-	tive
v e	dZ V	t eI	t I v
ve-	ge-	tal
v e	dZ V	t V l
ve-	ge-	tate
v e	dZ V	t eI t
ve-	he-	mence
v i:	V	m V n s
ve-	he-	ment
v i:	V	m V n t
ve-	he-	ment-	ly
v i:	V	m V n	t l i:
ve-	hi-	cle
v i:	h I	k V l
ve-	hi-	cles
v i:	h I	k V l z
ve-	hi-	cle's
v i:	h I	k V l z
ve-	hi-	cu-	lar
v i:	h I k	j V	l @r
ve-	la
v e	l V
ve-	lar-	de
v e	l Q@	d i:
ve-	las-	co
v e	l Q s	k @U
ve-	las-	quez
v e	l { s	k e z
ve-	laz-	quez
v e	l { s	k e z
ve-	lez
v e	l e z
ve-	li-	ka
v e	l I	k V
ve-	lo
v e	l @U
ve-	lo-	ci-	rap-	tor
v V	l O:	s @r	{ p	t @r
ve-	lo-	ci-	ties
v V	l Q	s V	t i: z
ve-	lo-	ci-	ty
v V	l Q	s V	t i:
ve-	na
v i:	n V
ve-	na-	ble
v e	n V	b V l
ve-	na-	bles
v e	n V	b V l z
ve-	na-	li-	ty
v V	n {	l V	t i:
ve-	nal
v i:	n V l
ve-	nan-	go
v e	n { N	g @U
ve-	ne-	ra-	ble
v e	n @r	V	b V l
ve-	ne-	ra-	ted
v e	n @r	eI	t V d
ve-	ne-	rate
v e	n @r	eI t
ve-	ne-	re-	al
v V	n I@	i:	V l
ve-	ne-	tian
v V	n i:	S V n
ve-	ne-	zi-	a
v e	n e	z i:	V
ve-	ne-	zi-	a-	no
v e	n e	z i:	Q	n @U
ve-	ne-	zue-	la
v e	n V z	w eI	l V
ve-	ne-	zue-	lan
v e	n V z	w eI	l V n
ve-	ne-	zue-	lans
v e	n V z	w eI	l V n z
ve-	ne-	zue-	la's
v e	n V z	w eI	l V z
ve-	neer
v V	n I@
ve-	ney
v e	n i:
ve-	ni-	ce's
v e	n I	s e z
ve-	ni-	son
v e	n I	s V n
ve-	ni-	ta
v e	n i:	t V
ve-	nice
v e	n I s
ve-	no
v eI	n @U
ve-	no-	mous
v e	n V	m V s
ve-	nom
v e	n V m
ve-	nous
v i:	n V s
ve-	nu-	ti
v e	n u:	t i:
ve-	nue
v e n	j u:
ve-	nues
v e	n u: z
ve-	nus
v i:	n V s
ve-	ra
v e@	V
ve-	ra-	ci-	ty
v @r	{	s I	t i:
ve-	ran-	da
v @r	{ n	d V
ve-	ran-	das
v @r	{ n	d V z
ve-	re-	na
v @r	eI	n V
ve-	rene
v e@	i: n
ve-	ri-	fi-	a-	ble
v e@	I	f aI	V	b V l
ve-	ri-	fi-	ca-	tion
v e@	I	f I	k eI	S V n
ve-	ri-	fied
v e@	I	f aI d
ve-	ri-	fies
v e@	I	f aI z
ve-	ri-	fy
v e@	I	f aI
ve-	ri-	fy-	ing
v e@	I	f aI	I N
ve-	ri-	na
v @r	i:	n V
ve-	ri-	ne
v @r	i:	n i:
ve-	ri-	si-	mi-	li-	tude
v e@	I	s I	m I	l I	t u: d
ve-	ri-	ta-	ble
v e@	I	t V	b V l
ve-	ri-	ties
v e@	I	t i: z
ve-	ri-	ty
v e@	I	t i:
ve-	ri-	ty's
v e@	I	t i: z
ve-	ro
v e@	@U
ve-	ro-	na
v @r	@U	n V
ve-	ro-	ni-	ca
v @r	Q	n I	k V
ve-	ro-	nique
v e@	Q	n i: k
ve-	ron
v e@	V n
ve-	ry
v e@	i:
ve-	su-	vi-	us
v V	s u:	v i:	V s
ve-	ta
v e	t V
ve-	te-	ran
v e	t @r	V n
ve-	te-	rans
v e	t @r	V n z
ve-	te-	ran's
v e	t @r	V n z
ve-	te-	rans'
v e	t @r	V n z
ve-	to
v i:	t @U
ve-	to-	ing
v i:	t @U	I N
ve-	toed
v i:	t @U d
ve-	toes
v i:	t @U z
ve-	vay
v e	v eI
ve-	xa-	tious
v e k	s eI	S V s
ve-	xing
v e k	s I N
veal
v i: l
veale
v i: l
veals
v i: l z
vec-	tor
v e k	t @r
vec-	tors
v e k	t @r z
ved-	der
v e	d @r
vee
v i:
vee-	ring
v I@	I N
veen
v i: n
veep
v i: p
veer
v I@
veered
v I@ d
veers
v I@ z
vees
v i: z
veg-	gie
v e	dZ i:
veg-	gies
v e	dZ i: z
vege-	ta-	ble
v e dZ	t V	b V l
vege-	ta-	bles
v e dZ	t V	b V l z
vei-	ling
v eI	l I N
veil
v eI l
veiled
v eI l d
veils
v eI l z
vein
v eI n
veins
v eI n z
veit
v i: t
vel-	da
v e l	d V
vel-	la
v e	l V
vel-	ma
v e l	m V
vel-	ve-	ty
v e l	v V	t i:
vel-	vee-	ta
v e l	v i:	t V
vel-	vet
v e l	v V t
velc-	ro
v e l	k r @U
veld-	man
v e l	d m V n
velte
v e l t
ven-	dee
v e n	d i:
ven-	det-	ta
v e n	d e	t V
ven-	ding
v e n	d I N
ven-	dit-	ti
v e n	d i:	t i:
ven-	dor
v e n	d @r
ven-	dors
v e n	d @r z
ven-	dor's
v e n	d @r z
ven-	geance
v e n	dZ V n s
ven-	ner
v e	n @r
ven-	ted
v e n	t V d
ven-	ter
v e n	t @r
ven-	ters
v e n	t @r z
ven-	ti-	la-	ted
v e n	t I	l eI	t I d
ven-	ti-	la-	ting
v e n	t I	l eI	t I N
ven-	ti-	la-	tion
v e n	t I	l eI	S V n
ven-	ti-	la-	tor
v e n	t I	l eI	t @r
ven-	ti-	late
v e n	t I	l eI t
ven-	ting
v e n	t I N
ven-	to
v e n	t @U
ven-	tre
v e n	t @r
ven-	tres
v e n	t @r z
ven-	tress
v e n	t r e s
ven-	tri-	cu-	lar
v e n	t r I k	j u:	l @r
ven-	tu-	ra
v e n	tS @r	V
ven-	tu-	ri
v e n	t U@	i:
ven-	tu-	ring
v e n	tS @r	I N
ven-	ture
v e n	tS @r
ven-	ture-	some
v e n	tS @r	s V m
ven-	tured
v e n	tS @r d
ven-	tures
v e n	tS @r z
venge-	ful
v e n	dZ f V l
venn
v e n
vent
v e n t
vent-	ral
v e n	t r V l
vents
v e n t s
ver-	ba
v e@	b V
ver-	ba-	li-	zing
v @r	b V	l aI	z I N
ver-	ba-	lize
v @r	b V	l aI z
ver-	ba-	tim
v @r	b eI	t I m
ver-	bal
v @r	b V l
ver-	bal-	ly
v @r	b {	l i:
ver-	be-	na
v @r	b i:	n V
ver-	bi-	age
v @r	b i:	I dZ
ver-	bo-	ten
v @r	b @U	t V n
ver-	da
v e@	d V
ver-	dant
v @r	d V n t
ver-	de
v @r	d i:
ver-	des
v @r	d i:
ver-	di
v e@	d i:
ver-	dict
v @r	d I k t
ver-	dicts
v @r	d I k t s
ver-	din
v @r	d I n
ver-	di's
v @r	d i: z
ver-	don
v e@	d O: n
ver-	du-	go
v @r	d u:	g @U
ver-	dun
v @r	d V n
ver-	ges
v @r	dZ V z
ver-	gil
v @r	dZ I l
ver-	ging
v @r	dZ I N
ver-	la
v e@	l V
ver-	lag
v @r	l { g
ver-	meer
v @r	m I@
ver-	mi-	lion
v @r	m I l	j V n
ver-	mil-	lion
v @r	m I l	j V n
ver-	min
v @r	m I n
ver-	mon-	ter
v @r	m Q n	t @r
ver-	mon-	ters
v @r	m Q n	t @r z
ver-	mont
v @r	m Q n t
ver-	mont's
v @r	m Q n t s
ver-	mouth
v @r	m u: T
ver-	na
v @r	n V
ver-	na-	cu-	lar
v @r	n { k	j V	l @r
ver-	nal
v @r	n V l
ver-	ner
v @r	n @r
ver-	ney
v @r	n i:
ver-	ni-	er
v @r	n i:	@r
ver-	ni-	ta
v @r	n i:	t V
ver-	nis
v @r	n I s
ver-	no-	ni-	a
v @r	n @U	n i:	V
ver-	non
v @r	n V n
ver-	non's
v @r	n V n z
ver-	nor
v @r	n @r
ver-	rell
v e@	eI l
ver-	rett
v e@	e t
ver-	ry
v e@	i:
ver-	sa
v @r	s V
ver-	sa-	ce
v @r	s Q	tS eI
ver-	sa-	ti-	li-	ty
v @r	s V	t I	l V	t i:
ver-	sa-	tile
v @r	s V	t V l
ver-	sailles
v e@	s aI
ver-	ser
v @r	s @r
ver-	ses
v @r	s V z
ver-	sion
v @r	Z V n
ver-	sions
v @r	Z V n z
ver-	sus
v @r	s V s
ver-	teb-	ra
v @r	t V b	r V
ver-	teb-	rae
v @r	t V b	r eI
ver-	teb-	ral
v @r	t V b	r V l
ver-	teb-	rate
v @r	t V b	r eI t
ver-	teb-	rates
v @r	t V b	r eI t s
ver-	tex
v @r	t e k s
ver-	ti-	cal
v @r	t I	k V l
ver-	ti-	go
v @r	t I	g @U
ver-	tical-	ly
v @r	t I k	l i:
ver-	trees
v @r t	r i: z
ver-	woerd
v @r	w O@ d
verb
v @r b
verbs
v @r b z
vere
v I@
verge
v @r dZ
vern
v @r n
verne
v @r n
verse
v @r s
versed
v @r s t
vert
v @r t
verve
v @r v
ves-	pa
v eI s	p V
ves-	per
v e s	p @r
ves-	sel
v e	s V l
ves-	sels
v e	s V l z
ves-	sel's
v e	s V l z
ves-	ta
v e s	t V
ves-	tal
v e s	t V l
ves-	ted
v e s	t V d
ves-	ter
v e s	t @r
ves-	ti-	bule
v e s	t I b	j u: l
ves-	ti-	ges
v e s	t I	dZ V z
ves-	ti-	gi-	al
v V s	t I	dZ i:	V l
ves-	tige
v e s	t I dZ
ves-	ting
v e s	t I N
vest
v e s t
vests
v e s t s
vet
v e t
vet-	ted
v e	t V d
vet-	ter
v e	t @r
vet-	ting
v e	t I N
vete-	ri-	na-	ri-	an
v e t	r I	n e@	i:	V n
vete-	ri-	na-	ri-	ans
v e t	r I	n e@	i:	V n z
)"
R"(vete-	ri-	na-	ry
v e t	r I	n e@	i:
vets
v e t s
veuve
v j u: v
vex
v e k s
vexed
v e k s t
vey
v eI
vi
v aI
vi-	a
v aI	V
vi-	a-	bi-	li-	ty
v aI	V	b I	l V	t i:
vi-	a-	ble
v aI	V	b V l
vi-	a-	com
v aI	V	k Q m
vi-	a-	com's
v aI	V	k Q m z
vi-	a-	duct
v aI	V	d V k t
vi-	a-	ducts
v aI	V	d V k t s
vi-	a-	ti-	cal
v aI	{	t I	k V l
vi-	a-	tor
v aI	eI	t @r
vi-	al
v aI	V l
vi-	als
v aI	V l z
vi-	an
v i:	V n
vi-	bhu
v i:	b u:
vi-	bra-	ting
v aI b	r eI	t I N
vi-	bra-	tion
v aI b	r eI	S V n
vi-	bra-	tions
v aI b	r eI	S V n z
vi-	bra-	to
v i: b	r Q	t @U
vi-	bra-	tor
v aI b	r eI	t @r
vi-	bran-	cy
v aI b	r V n	s i:
vi-	brant
v aI b	r V n t
vi-	brate
v aI b	r eI t
vi-	brates
v aI b	r eI t s
vi-	ca-	ri-	ous
v aI	k e@	i:	V s
vi-	ca-	ri-	ous-	ly
v aI	k e@	i:	V s	l i:
vi-	ca-	ry
v I	k @r	i:
vi-	car
v I	k @r
vi-	cars
v I	k @r z
vi-	cen-	te
v i:	tS e n	t i:
vi-	ces
v aI	s V z
vi-	chy
v i:	S i:
vi-	ci-	ni-	ty
v V	s I	n V	t i:
vi-	cious
v I	S V s
vi-	cious-	ly
v I	S V s	l i:
vi-	cious-	ness
v I	S V s	n e s
vi-	cis-	si-	tude
v I	s I	s I	t u: d
vi-	cis-	si-	tudes
v I	s I	s I	t u: d z
vi-	com-	te
v I	k Q m	t i:
vi-	cu-	na
v I k	j u:	n V
vi-	da
v aI	d V
vi-	da-	lia
v V	d eI l	j V
vi-	dal
v aI	d { l
vi-	de-	o
v I	d i:	@U
vi-	de-	o-	cas-	sette
v I	d i:	@U	k {	s e t
vi-	de-	o-	cas-	settes
v I	d i:	@U	k {	s e t s
vi-	de-	o-	confe-	ren-	cing
v i:	d i:	@U	k Q n	f r V n	s I N
vi-	de-	o-	confe-	rence
v i:	d i:	@U	k Q n	f r V n s
vi-	de-	o-	disk
v I	d i:	@U	d I s k
vi-	de-	o-	disks
v I	d i:	@U	d I s k s
vi-	de-	o-	gra-	pher
v V	d i:	O: g	r V	f @r
vi-	de-	o-	phone
v I	d i:	@U	f @U n
vi-	de-	o-	ta-	ping
v I	d i:	@U	t eI	p I N
vi-	de-	o-	tape
v I	d i:	@U	t eI p
vi-	de-	o-	taped
v I	d i:	@U	t eI p t
vi-	de-	o-	tapes
v I	d i:	@U	t eI p s
vi-	de-	o-	tex
v I	d i:	@U	t e k s
vi-	de-	o-	text
v I	d i:	@U	t e k s t
vi-	de-	os
v I	d i:	@U z
vi-	de-	o's
v I	d i:	@U z
vi-	do-	ni-	a
v i:	d @U	n i:	V
vi-	dor
v i:	d O@
vi-	en-	na
v i:	e	n V
vi-	en-	na's
v i:	e	n V z
vi-	en-	nese
v i:	e	n i: s
vi-	et
v i:	e t
vi-	et-	cong
v i:	e t	k O: N
vi-	et-	na-	mese
v i:	e t	n Q	m i: s
vi-	et-	nam
v i:	e t	n Q m
vi-	et-	nam's
v i:	e t	n Q m z
vi-	gen
v I	g V n
vi-	gi-	lan-	te
v I	dZ I	l { n	t i:
vi-	gi-	lan-	tes
v I	dZ I	l { n	t i: z
vi-	gi-	lan-	ti-	sm
v I	dZ I	l { n	t I	z V m
vi-	gi-	lance
v I	dZ I	l V n s
vi-	gi-	lant
v I	dZ I	l V n t
vi-	gil
v I	dZ I l
vi-	gils
v I	dZ I l z
vi-	go
v i:	g @U
vi-	go-	rous
v I	g @r	V s
vi-	go-	rous-	ly
v I	g @r	V s	l i:
vi-	gor
v I	g @r
vi-	gue-	rie
v I	g @r	i:
vi-	king
v aI	k I N
vi-	kings
v aI	k I N z
vi-	king's
v aI	k I N z
vi-	la
v i:	l V
vi-	las
v i:	l Q z
vi-	li-	fi-	ca-	tion
v I	l I	f I	k eI	S V n
vi-	li-	fied
v I	l I	f aI d
vi-	li-	fy
v I	l I	f aI
vi-	na
v i:	n V
vi-	nal
v aI	n V l
vi-	ne-	gar
v I	n V	g @r
vi-	ne-	gars
v I	n I	g @r z
vi-	ner
v aI	n @r
vi-	net
v I	n e t
vi-	ni-	ta
v i:	n i:	t V
vi-	ning
v aI	n I N
vi-	ning's
v aI	n I N z
vi-	nyl
v aI	n V l
vi-	o-	la
v aI	@U	l V
vi-	o-	la-	ted
v aI	V	l eI	t V d
vi-	o-	la-	ting
v aI	V	l eI	t I N
vi-	o-	la-	tion
v aI	V	l eI	S V n
vi-	o-	la-	tions
v aI	V	l eI	S V n z
vi-	o-	la-	tor
v aI	V	l eI	t @r
vi-	o-	la-	tors
v aI	V	l eI	t @r z
vi-	o-	lan-	te
v i:	@U	l Q n	t i:
vi-	o-	las
v i:	@U	l V z
vi-	o-	late
v aI	V	l eI t
vi-	o-	lates
v aI	V	l eI t s
vi-	o-	le-	ta
v i:	@U	l e	t V
vi-	o-	lence
v aI	V	l V n s
vi-	o-	lent
v aI	V	l V n t
vi-	o-	lent-	ly
v aI	V	l V n	t l i:
vi-	o-	let
v aI	V	l V t
vi-	o-	let-	ta
v i:	@U	l e	t V
vi-	o-	lets
v aI	V	l V t s
vi-	o-	lette
v i:	@U	l e t
vi-	o-	li-	nist
v aI	V	l I	n V s t
vi-	o-	li-	nists
v aI	V	l I	n V s t s
vi-	o-	lin
v aI	V	l I n
vi-	o-	lins
v aI	V	l I n z
vi-	o-	list
v i:	@U	l I s t
vi-	ole
v aI	@U l
vi-	per
v aI	p @r
vi-	pers
v aI	p @r z
vi-	pul
v i:	p u: l
vi-	ra-	go
v I@	V	g @U
vi-	ral
v aI	r V l
vi-	ren
v I@	V n
vi-	ri-	dis
v O@	I	d I s
vi-	ri-	li-	ty
v @r	I	l I	t i:
vi-	rile
v I@	I l
vi-	ro-	lo-	gi-	cal
v aI	r V	l Q	dZ I	k V l
vi-	ro-	lo-	gist
v I@	Q	l V	dZ V s t
vi-	ro-	lo-	gists
v I@	Q	l V	dZ V s t s
vi-	ro-	lo-	gy
v I@	Q	l V	dZ i:
vi-	ru-	lence
v I@	V	l V n s
vi-	ru-	lent
v I@	V	l V n t
vi-	ru-	lent-	ly
v I@	V	l V n	t l i:
vi-	ru-	ses
v aI	r V	s V z
vi-	ru-	s's
v aI	r V	s V z
vi-	rus
v aI	r V s
vi-	sa
v i:	z V
vi-	sage
v I	z V dZ
vi-	sas
v i:	z V z
vi-	sa's
v i:	z V z
vi-	si-	bi-	li-	ty
v I	z I	b I	l I	t i:
vi-	si-	ble
v I	z I	b V l
vi-	si-	goth
v I	z I	g Q T
vi-	si-	goths
v I	z I	g Q T s
vi-	si-	ta-	tion
v I	z I	t eI	S V n
vi-	si-	ta-	tions
v I	z I	t eI	S V n z
vi-	si-	ted
v I	z I	t I d
vi-	si-	ting
v I	z I	t I N
vi-	si-	tor
v I	z I	t @r
vi-	si-	tors
v I	z I	t @r z
vi-	si-	tor's
v I	z I	t @r z
vi-	sib-	ly
v I	z I b	l i:
vi-	sio-	na-	ries
v I	Z V	n e@	i: z
vi-	sio-	na-	ry
v I	Z V	n e@	i:
vi-	sion
v I	Z V n
vi-	sions
v I	Z V n z
vi-	sion's
v I	Z V n z
vi-	sit
v I	z I t
vi-	sits
v I	z I t s
vi-	sor
v I	z @r
vi-	sors
v I	z @r z
vi-	su-	al
v I	Z V	w V l
vi-	sua-	li-	za-	tion
v I Z	w V	l V	z eI	S V n
vi-	sua-	li-	zing
v I Z	w V	l aI	z I N
vi-	sua-	lize
v I Z	w V	l aI z
vi-	sua-	lized
v I Z	w V	l aI z d
vi-	sual-	ly
v I Z	w V	l i:
vi-	suals
v I Z	w V l z
vi-	ta
v aI	t V
vi-	ta-	le
v V	t {	l i:
vi-	ta-	li-	ty
v aI	t {	l I	t i:
vi-	ta-	min
v aI	t V	m V n
vi-	ta-	mins
v aI	t V	m V n z
vi-	tae
v aI	t V
vi-	tal
v aI	t V l
vi-	tal-	ly
v aI	t V	l i:
vi-	tek
v I	t e k
vi-	tel-	li
v V	t e	l i:
vi-	ti
v i:	t i:
vi-	ti-	li-	go
v i:	t I	l I	g @U
vi-	tia
v i:	S V
vi-	to
v i:	t @U
vi-	tu-	pe-	ra-	tive
v aI	t u:	p @r	V	t I v
vi-	va
v i:	v V
vi-	va-	cious
v V	v eI	S V s
vi-	val-	di
v I	v Q l	d i:
vi-	vas
v i:	v V z
vi-	ven-	di
v I	v e n	d i:
vi-	vi-	a-	na
v I	v i:	{	n V
vi-	vi-	an
v I	v i:	V n
vi-	vi-	en
v I	v i:	V n
vi-	vi-	enne
v I	v i:	V n
vi-	vi-	pa-	rous
v aI	v I	p @r	V s
vi-	vi-	se-	pul-	ture
v I	v i:	s e	p V l	tS @r
vi-	vid
v I	v I d
vi-	vid-	ly
v I	v I d	l i:
vi-	vid-	ness
v I	v I d	n e s
vi-	vie
v I	v i:
vi-	vo
v i:	v @U
vi-	vyan
v i: v	j Q n
vi-	xen
v I k	s I n
vi-	yel-	la
v I	j e	l V
vibe
v aI b
vibes
v aI b z
vic
v I k
vic-	ke-	ry
v I s	k @r	i:
vic-	kers
v I	k @r z
vic-	key
v I	k i:
vic-	ki
v I	k i:
vic-	kie
v I	k i:
vic-	ky
v I	k i:
vic-	ky's
v I	k i: z
vic-	ti-	mi-	za-	tion
v I k	t I	m I	z eI	S V n
vic-	ti-	mi-	zing
v I k	t I	m aI	z I N
vic-	ti-	mize
v I k	t I	m aI z
vic-	ti-	mized
v I k	t I	m aI z d
vic-	tim
v I k	t I m
vic-	tim-	hood
v I k	t I m	h U d
vic-	tim-	less
v I k	t I m	l e s
vic-	tims
v I k	t I m z
vic-	tim's
v I k	t I m z
vic-	to-	ri-	a
v I k	t O@	i:	V
vic-	to-	ri-	an
v I k	t O@	i:	V n
vic-	to-	ri-	ans
v I k	t O@	i:	V n z
vic-	to-	ri-	as
v I k	t O@	i:	V z
vic-	to-	ri-	a's
v I k	t O@	i:	V z
vic-	to-	ri-	ne
v i: k	t O@	i:	n i:
vic-	to-	ri-	ous
v I k	t O@	i:	V s
vic-	to-	ries
v I k	t @r	i: z
vic-	to-	ry
v I k	t @r	i:
vic-	toire
v I k	t w Q@
vic-	tor
v I k	t @r
vic-	tors
v I k	t @r z
vic-	tor's
v I k	t @r z
vice
v aI s
vice-	pre-	si-	den-	tial
v aI s	p r e	z I	d e n	tS V l
vice-	pre-	si-	dent
v aI s	p r e	z I	d e n t
vice-	pre-	si-	dents
v aI s	p r e	z I	d e n t s
vice-	roy
v aI s	r OI
vick
v I k
vicks-	burg
v I k	s b @r g
vic's
v I k s
vide
v aI d
vie
v aI
vie-	reck
v I@	I k
vie-	wer
v j u:	@r
vie-	wer-	ship
v j u:	@r	S I p
vie-	wers
v j u:	@r z
vie-	wer's
v j u:	@r z
vie-	wing
v j u:	I N
vied
v aI d
viens
v i: n z
vier-	ling
v I@	l I N
vier-	tel
v I@	t e l
viers
v I@ z
vies
v aI z
view
v j u:
view-	fin-	der
v j u:	f aI n	d @r
view-	point
v j u:	p OI n t
view-	points
v j u:	p OI n t s
viewed
v j u: d
views
v j u: z
vig
v I g
vig-	li-	o-	ne
v I g	l i:	@U	n i:
vig-	na
v I g	n V
vig-	nette
v I n	j e t
vig-	nettes
v I n	j e t s
vig-	no-	la
v i: g	n @U	l V
vil-	la
v I	l V
vil-	la-	ger
v I	l I	dZ @r
vil-	la-	gers
v I	l I	dZ @r z
vil-	la-	ges
v I	l I	dZ V z
vil-	la-	ge's
v I	l I	dZ V z
vil-	la-	no-	va
v I	l V	n @U	v V
vil-	la-	no-	van
v I	l V	n @U	v V n
vil-	la-	nue-	va
v i:	l Q n	w e	v V
vil-	la-	ri
v i:	l Q@	i:
vil-	la-	vi-	cen-	ci-	o
v I	l V	v I	s e n	s i:	@U
vil-	lage
v I	l I dZ
vil-	lai-	nous
v I	l I	n V s
vil-	lain
v I	l I n
vil-	lains
v I	l I n z
vil-	lal-	ba
v i:	l Q l	b V
vil-	lar
v I	l @r
vil-	lar-	real
v i:	l Q@	i: l
vil-	lard
v I	l @r d
vil-	lars
v I	l @r z
vil-	las
v I	l V z
vil-	la's
v I	l V z
vil-	le-	neuve
v I	l V	n u: v
vil-	lette
v V	l e t
vil-	li
v I	l i:
vil-	liers
v I l	j @r z
vil-	ma
v I l	m V
vil-	ni-	us
v I l	n i:	V s
vile
v aI l
ville
v I l
vim
v I m
vin
v I n
vin-	ca
v I N	k V
vin-	ce-	lette
v I n	s V	l e t
vin-	cen-	nes
v I n	s e	n V s
vin-	cen-	tia
v i: n	tS e n	S V
vin-	cen-	zo
v I n	s e n	z @U
vin-	cent
v I n	s V n t
vin-	cent's
v I n	s V n t s
vin-	ce's
v I n	s V s
vin-	ci
v I n	s i:
vin-	ci's
v I n	s i: z
vin-	di-	ca-	ted
v I n	d I	k eI	t I d
vin-	di-	ca-	tion
v I n	d I	k eI	S V n
vin-	di-	ca-	tor
v I n	d I	k eI	t @r
vin-	di-	cate
v I n	d I	k eI t
vin-	di-	cates
v I n	d I	k eI t s
vin-	dic-	tive
v I n	d I k	t I v
vin-	dic-	tive-	ness
v I n	d I k	t I v	n e s
vin-	nie
v I	n i:
vin-	ny
v I	n i:
vin-	son
v I n	s V n
vin-	ta-	ges
v I n	t I	dZ V z
vin-	tage
v I n	t I dZ
vin-	ton
v I n	t V n
vince
v I n s
vine
v aI n
vine-	land
v aI n	l V n d
vine-	yard
v I n	j @r d
vine-	yards
v I n	j @r d z
vines
v aI n z
vint
v I n t
vint-	ner
v I n	t n @r
vint-	ners
v I n	t n @r z
vir-	den
v @r	d V n
vir-	ga
v @r	g V
vir-	gi-	li-	o
v @r	dZ I	l i:	@U
vir-	gi-	nal
v @r	dZ I	n V l
vir-	gi-	ni-	ty
v @r	dZ I	n I	t i:
vir-	gi-	nia
v @r	dZ I n	j V
vir-	gi-	nian
v @r	dZ I n	j V n
vir-	gi-	nians
v @r	dZ I n	j V n z
vir-	gi-	nia's
v @r	dZ I n	j V z
vir-	gie
v @r	g i:
vir-	gil
v @r	dZ I l
vir-	gin
v @r	dZ I n
vir-	gins
v @r	dZ I n z
vir-	gin's
v @r	dZ I n z
vir-	go
v @r	g @U
vir-	gy
v @r	dZ i:
vir-	tu-	al
v @r	tS u:	V l
vir-	tu-	al-	ly
v @r	tS u:	V	l i:
vir-	tu-	o-	si-	ty
v @r	tS u:	Q	s I	t i:
vir-	tu-	o-	so
v @r	tS u:	@U	s @U
vir-	tu-	ous
v @r	tS u:	V s
vir-	tue
v @r	tS u:
vir-	tues
v @r	tS u: z
vires
v aI r z
virge
v @r dZ
vis
v I s
vis-	car-	di
v i: s	k Q@	d i:
vis-	ce-	ral
v I	s @r	V l
vis-	ce-	ral-	ly
v I	s @r	V	l i:
vis-	co-	si-	ty
v I s	k Q	s I	t i:
vis-	con-	ti
v i: s	k @U n	t i:
vis-	cous
v I s	k V s
vis-	ta
v I s	t V
vis-	tas
v I s	t V z
vis-	ta's
v I s	t V z
vise
v aI s
vit-	re-	ous
v I t	r i:	V s
vit-	ri-	o-	lic
v I t	r i:	Q	l I k
vit-	ri-	ol
v I t	r i:	V l
vit-	ric
v I t	r I k
vit-	ro
v I t	r @U
vit-	ru-	vi-	us
v V t	r u:	v i:	V s
vit-	ry
v I t	r i:
vit-	tle
v I	t V l
vit-	tles
v I	t V l z
vit-	to-	ri-	a
v I	t O@	i:	V
vit-	to-	ri-	o
v i:	t O@	i:	@U
viv
v I v
vive
v i: v
vives
v aI v z
viz-	ca-	ya
v I z	k aI	V
vla-	di-	mir
v l {	d I	m I@
vla-	di-	vos-	tok
v l {	d I	v O: s	t Q k
vla-	sic
v l {	z I k
vlach
v l { tS
vlad
v l { d
vlad's
v l { d z
vo
v @U
vo-	bis
v @U	b I s
vo-	ca-	bu-	la-	ry
v @U	k { b	j V	l e@	i:
vo-	ca-	list
v @U	k V	l V s t
vo-	ca-	tio-	nal
v @U	k eI	S V	n V l
vo-	ca-	tion
v @U	k eI	S V n
vo-	ca-	tions
v @U	k eI	S V n z
vo-	cal
v @U	k V l
vo-	cal-	ly
v @U	k V	l i:
vo-	cals
v @U	k V l z
vo-	ci-	fe-	rous
v @U	s I	f @r	V s
vo-	ci-	fe-	rous-	ly
v V	s I	f @r	V s	l i:
vo-	da-	fone
v @U	d V	f @U n
vo-	gel
v @U	g V l
vo-	la-	ti-	li-	ty
v Q	l V	t I	l V	t i:
vo-	la-	tile
v Q	l V	t V l
vo-	lan-	te
v @U	l Q n	t eI
vo-	land
v Q	l V n d
vo-	le-	ta
v @U	l e	t V
vo-	li-	tion
v @U	l I	S V n
vo-	lin
v @U	l I n
vo-	lu-	ble
v Q l	j V	b V l
vo-	lu-	mi-	nous
v V	l u:	m V	n V s
vo-	lume
v Q l	j u: m
vo-	lumes
v Q l	j u: m z
vo-	lume's
v Q l	j V m z
vo-	lun-	ta-	ri-	ly
v Q	l V n	t e@	V	l i:
vo-	lun-	ta-	ri-	sm
v Q	l V n	t @r	I	z V m
vo-	lun-	ta-	ry
v Q	l V n	t e@	i:
vo-	lun-	tee-	ri-	sm
v O:	l V n	t I@	I	z V m
vo-	lun-	tee-	ring
v O:	l V n	t I@	I N
vo-	lun-	teer
v Q	l V n	t I@
vo-	lun-	teered
v Q	l V n	t I@ d
vo-	lun-	teers
v Q	l V n	t I@ z
vo-	lup-	tu-	ous
v V	l V p	tS V	w V s
vo-	mi-	ting
v Q	m I	t I N
vo-	mit
v Q	m I t
vo-	na
v @U	n V
vo-	ra-	ci-	ty
v @r	{	s I	t i:
vo-	ra-	cious
v O@	eI	S V s
vo-	taw
v @U	t O:
vo-	ted
v @U	t V d
vo-	ter
v @U	t @r
vo-	ters
v @U	t @r z
vo-	ter's
v @U	t @r z
vo-	ting
v @U	t I N
vo-	wel
v aU	V l
vo-	wels
v aU	V l z
vo-	wing
v aU	I N
vo-	ya-	ger
v OI	V	dZ @r
vo-	ya-	gers
v OI	I	dZ @r z
vo-	ya-	ger's
v OI	I	dZ @r z
vo-	ya-	ges
v OI	V	dZ V z
vo-	yage
v OI	V dZ
vo-	yaged
v OI	V dZ d
vo-	yeu-	ri-	sm
v OI	j u:	r I	z V m
vo-	yeu-	ris-	tic
v OI	j V	r I s	t I k
vo-	yeur
v OI	j u: r
vod-	ka
v Q d	k V
vod-	kas
v Q d	k V z
vogt
v @U t
vogue
v @U g
voi-	ces
v OI	s V z
voi-	ce's
v OI	s V z
voi-	cing
v OI	s I N
voi-	ded
v OI	d V d
voi-	ding
v OI	d I N
voi-	la
v w Q	l Q
voice
v OI s
voice-	less
v OI s	l V s
voice-	o-	ver
v OI	s @U	v @r
voiced
v OI s t
void
v OI d
voids
v OI d z
voiles
v OI l z
voir
v w Q@
vol-	ca-	nic
v Q l	k {	n I k
vol-	ca-	nical-	ly
v Q l	k {	n I k	l i:
vol-	ca-	no
v Q l	k eI	n @U
vol-	ca-	noes
v Q l	k eI	n @U z
vol-	ca-	nos
v Q l	k eI	n @U z
vol-	ca-	no's
v Q l	k eI	n @U z
vol-	ga
v Q l	g V
vol-	gog-	rad
v @U l	g @U g	r { d
vol-	ley
v Q	l i:
vol-	ley-	ball
v Q	l i:	b O: l
vol-	leys
v Q	l i: z
vol-	ney
v @U l	n i:
vol-	ta
v @U l	t V
vol-	ta-	ges
v @U l	t V	dZ V z
vol-	ta-	ge's
v @U l	t I	dZ V z
vol-	ta-	ren
v @U l	t @r	V n
vol-	tage
v @U l	t V dZ
vol-	taire
v @U l	t e@
vol-	vo
v @U l	v @U
vol-	vo's
v @U l	v @U z
vol-	vox
v Q l	v Q k s
volc-	ker
v @U l	k @r
volc-	ker's
v @U l	k @r z
voles
v @U l z
volk
v @U l k
volks-	wa-	gen
v @U l	k s w {	g V n
volks-	wa-	gens
v @U l	k s w {	g V n z
volks-	wa-	gen's
v @U l	k s w {	g V n z
volpe
v @U l p
volt
v @U l t
volts
v @U l t s
voltz
v @U l t s
von
v O: n
von-	ne-	gut
v Q	n V	g V t
von-	nie
v Q	n i:
von-	ny
v Q	n i:
voo-	doo
v u:	d u:
voor-	his
v U@	h I s
vor-	tex
v O@	t e k s
vos
v Q s
voss
v O: s
vote
v @U t
votes
v @U t s
vote's
v @U t s
vou-	cher
v aU	tS @r
vou-	chers
v aU	tS @r z
vou-	ching
v aU	tS I N
vouch
v aU tS
vouched
v aU tS t
vought
v O: t
vow
v aU
vowed
v aU d
vows
v aU z
vox
v Q k s
vree-	land
v r i:	l V n d
vries
v r i: z
vroom
v r u: m
v's
v i: z
vu
v u:
vue
v j u:
vuit-	ton
v u:	t V n
vul-	can
v V l	k V n
vul-	cans
v V l	k V n z
vul-	can's
v V l	k V n z
vul-	ga-	ri-	ty
v V l	g e@	V	t i:
vul-	ga-	ri-	za-	tion
v V l	g @r	I	z eI	S V n
vul-	gar
v V l	g @r
vul-	lo
v u:	l @U
vul-	ne-	ra-	bi-	li-	ties
v V l	n @r	V	b I	l V	t i: z
vul-	ne-	ra-	bi-	li-	ty
v V l	n @r	V	b I	l V	t i:
vul-	ne-	ra-	ble
v V l	n @r	V	b V l
vul-	ture
v V l	tS @r
vul-	tures
v V l	tS @r z
vy-	ing
v aI	I N
wa
w Q
wa-	ba-	sh's
w O:	b {	S V z
wa-	bash
w O:	b { S
wa-	co
w eI	k @U
wa-	da
w Q	d V
wa-	das
w Q	d V z
wa-	ded
w eI	d V d
wa-	der
w eI	d @r
wa-	ders
w eI	d @r z
wa-	ding
w eI	d I N
wa-	fer
w eI	f @r
wa-	fers
w eI	f @r z
wa-	ge-	ner
w {	g V	n @r
wa-	ge-	ring
w eI	dZ @r	I N
wa-	ger
w eI	dZ @r
wa-	gered
w eI	dZ @r d
wa-	gers
w eI	dZ @r z
wa-	ges
w eI	dZ V z
wa-	ging
w eI	dZ I N
wa-	go-	neer
w {	g V	n I@
wa-	go-	neers
w {	g V	n I@ z
wa-	go-	ner
w {	g V	n @r
wa-	gon
w {	g V n
wa-	gons
w {	g V n z
wa-	hoo
w V	h u:
wa-	ken
w eI	k V n
wa-	king
w eI	k I N
wa-	le-	sa
w V	l e	s V
wa-	na-	ma-	ker
w Q	n V	m eI	k @r
wa-	ner
w eI	n @r
wa-	ning
w eI	n I N
wa-	ri-	ly
w e@	I	l i:
wa-	ri-	ness
w e@	i:	n V s
wa-	ring
w e@	I N
wa-	ry
w e@	i:
wa-	satch
w Q	s { tS
wa-	sha-	ble
w Q	S V	b V l
wa-	sher
w Q	S @r
wa-	shers
w Q	S @r z
wa-	shes
w Q	S V z
wa-	shing
w Q	S I N
wa-	shing-	to-	ni-	an
w Q	S I N	t @U	n i:	V n
wa-	shing-	to-	ni-	ans
w Q	S I N	t @U	n i:	V n z
wa-	shing-	ton
w Q	S I N	t V n
wa-	shing-	ton's
w Q	S I N	t V n z
wa-	shoe
w Q	S @U
wa-	shy
w Q	S i:
wa-	sn't
w Q	z V n t
wa-	t-	ling
w O:	t V	l I N
wa-	ta-	na-	be
w Q	t Q	n Q	b eI
wa-	te-	rer
w O:	t @r	@r
wa-	te-	ring
w O:	t @r	I N
wa-	te-	rish-	ness
w O:	t @r	I S	n V s
wa-	te-	ry
w O:	t @r	i:
wa-	ter
w O:	t @r
wa-	ter-	bed
w O:	t @r	b e d
wa-	ter-	beds
w O:	t @r	b e d z
wa-	ter-	borne
w O:	t @r	b O@ n
wa-	ter-	bu-	ry
w O:	t @r	b e@	i:
wa-	ter-	co-	lor
w O:	t @r	k V	l @r
wa-	ter-	co-	lors
w O:	t @r	k V	l @r z
wa-	ter-	cress
w O:	t @r k	r e s
wa-	ter-	fall
w O:	t @r	f O: l
wa-	ter-	falls
w O:	t @r	f O: l z
wa-	ter-	ford
w O:	t @r	f @r d
wa-	ter-	fowl
w O:	t @r	f aU l
wa-	ter-	front
w O:	t @r f	r V n t
wa-	ter-	fronts
w O:	t @r f	r V n t s
wa-	ter-	gate
w Q	t @r	g eI t
wa-	ter-	hou-	se's
w O:	t @r	h aU	s V z
wa-	ter-	house
w O:	t @r	h aU s
wa-	ter-	log
w O:	t @r	l Q g
wa-	ter-	logged
w O:	t @r	l Q g d
wa-	ter-	loo
w O:	t @r	l u:
wa-	ter-	man
w O:	t @r	m V n
wa-	ter-	man's
w O:	t @r	m V n z
wa-	ter-	mark
w O:	t @r	m Q@ k
)"
R"(wa-	ter-	me-	lon
w O:	t @r	m e	l V n
wa-	ter-	me-	lons
w O:	t @r	m e	l V n z
wa-	ter-	men
w O:	t @r	m V n
wa-	ter-	proo-	fing
w O:	t @r p	r u:	f I N
wa-	ter-	proof
w O:	t @r p	r u: f
wa-	ter-	shed
w Q	t @r	S e d
wa-	ter-	sheds
w Q	t @r	S e d z
wa-	ter-	tight
w O:	t @r	t aI t
wa-	ter-	town
w O:	t @r	t aU n
wa-	ter-	ville
w O:	t @r	v I l
wa-	ter-	way
w O:	t @r	w eI
wa-	ter-	ways
w O:	t @r	w eI z
wa-	ter-	work
w O:	t @r	w @r k
wa-	ter-	works
w O:	t @r	w @r k s
wa-	tered
w O:	t @r d
wa-	ters
w O:	t @r z
wa-	ter's
w O:	t @r z
wa-	then
w O:	T V n
wa-	ve-	ring
w eI	v @r	I N
wa-	ver
w eI	v @r
wa-	ver-	ley
w eI	v @r	l i:
wa-	ver-	ly
w eI	v @r	l i:
wa-	vered
w eI	v @r d
wa-	ving
w eI	v I N
wa-	vy
w eI	v i:
wa-	xes
w { k	s V z
wa-	xing
w { k	s I N
wa-	xy
w { k	s i:
wa-	zir
w Q	z I@
wa-	zir's
w Q	z I@ z
waag
w Q g
waal
w Q l
wac-	ker
w {	k @r
wac-	ko
w {	k @U
wac-	kos
w {	k @U z
wac-	ky
w {	k i:
wace
w eI s
wach-	tel
w O:	tS V l
wach-	ter
w O: k	t @r
wack
w { k
wacks
w { k s
wad
w Q d
wad-	ded
w Q	d V d
wad-	dell
w Q	d e l
wad-	die
w Q	d i:
wad-	ding-	ton
w Q	d I N	t V n
wad-	dle
w Q	d V l
wad-	dy
w Q	d i:
wad-	hams
w O:	d V m z
wad-	leigh
w O: d	l i:
wad-	ley
w Q d	l i:
wade
w eI d
wades
w eI d z
wade's
w eI d z
wads
w Q d z
wads-	worth
w Q d	z w @r T
wads-	worth's
w Q d	z w @r T s
waech-	ter
w e k	t @r
waf-	fle
w Q	f V l
waf-	fled
w Q	f V l d
waf-	fles
w Q	f V l z
waf-	ted
w Q f	t V d
waf-	ting
w Q f	t I N
waff-	ling
w Q f	l I N
waft
w Q f t
wag
w { g
wag-	g-	ling
w {	g V	l I N
wag-	ging
w {	g I N
wag-	go-	ner
w {	g V	n @r
wag-	gy
w {	g i:
wag-	ne-	ri-	an
w { g	n e@	i:	V n
wag-	ner
w { g	n @r
wag-	ner's
w { g	n @r z
wag-	staff
w { g	s t { f
wage
w eI dZ
waged
w eI dZ d
wagged
w { g d
wags
w { g z
wah
w Q
wahl
w Q l
wahl-	strom
w Q l	s t r V m
wai-	ki-	ki
w aI	k i:	k i:
wai-	ling
w eI	l I N
wai-	ner
w eI	n @r
wai-	ted
w eI	t V d
wai-	ter
w eI	t @r
wai-	ters
w eI	t @r z
wai-	ter's
w eI	t @r z
wai-	ting
w eI	t I N
wai-	ver
w eI	v @r
wai-	vers
w eI	v @r z
wai-	ving
w eI	v I N
waid
w eI d
waide
w eI d
waif
w eI f
wail
w eI l
wailed
w eI l d
wails
w eI l z
wain
w eI n
wain-	man
w eI n	m V n
wain-	scott
w eI n	s k V t
wain-	wright
w eI n	r aI t
wais
w eI z
waist
w eI s t
waist-	line
w eI s	t l aI n
waists
w eI s t s
wait
w eI t
wait-	res-	ses
w eI t	r V	s V z
wait-	ress
w eI t	r V s
waite
w eI t
waites
w eI t s
waite's
w eI t s
waits
w eI t s
waive
w eI v
waived
w eI v d
waives
w eI v z
waj-	da
v aI	d V
wake
w eI k
wake-	field
w eI k	f i: l d
wake-	man
w eI k	m V n
wake-	up
w eI	k V p
wakes
w eI k s
wal
w O: l
wal-	bridge
w O: l	b r I dZ
wal-	cott
w O: l	k Q t
wal-	de-	mar
v Q l	d V	m Q@
wal-	den
w O: l	d V n
wal-	dheim
w O: l	d h aI m
wal-	dheim's
w O: l	d h aI m z
wal-	do
w Q l	d @U
wal-	don
w O: l	d V n
wal-	dorf
w O: l	d O@ f
wal-	ford
w O: l	f @r d
wal-	green
w O: l	g r i: n
wal-	ker
w O:	k @r
wal-	kers
w O:	k @r z
wal-	ker's
w O:	k @r z
wal-	kie
w O:	k i:
wal-	king
w O:	k I N
wal-	kure
w O: k	j @r
wal-	la
w O:	l V
wal-	la-	ce's
w O:	l V	s V z
wal-	lace
w O:	l V s
wal-	lach
w O:	l V k
wal-	lack
w O:	l V k
wal-	len-	stein
w O:	l V n	s t aI n
wal-	ler
w O:	l @r
wal-	let
w O:	l V t
wal-	lets
w O:	l V t s
wal-	ley
w O:	l i:
wal-	leye
w O:	l aI
wal-	lie
w O:	l i:
wal-	ling
w O:	l I N
wal-	ling-	ford
w O:	l I N	f @r d
wal-	ling-	ton
w O:	l I N	t V n
wal-	lis
w O:	l I s
wal-	lo-	ping
w O:	l V	p I N
wal-	lo-	wing
w Q	l @U	I N
wal-	loch
w O:	l V k
wal-	lop
w Q	l V p
wal-	lops
w Q	l V p s
wal-	low
w Q	l @U
wal-	lowed
w Q	l @U d
wal-	ly
w O:	l i:
wal-	ly's
w O:	l i: z
wal-	nut
w O: l	n V t
wal-	nuts
w O: l	n V t s
wal-	pole
w O: l	p @U l
wal-	rath
w O: l	r V T
wal-	ru-	ses
w Q l	r V	s V z
wal-	rus
w O: l	r V s
wal-	sh's
w O: l	S V z
wal-	ston
w O: l	s t V n
wal-	ter
w O: l	t @r
wal-	ters
w O: l	t @r z
wal-	ter's
w O: l	t @r z
wal-	thall
w O: l	T V l
wal-	tham
w O: l	T V m
wal-	ther
w O: l	T @r
wal-	ton
w O: l	t V n
wal-	ton's
w O: l	t V n z
wal-	worth
w O: l	w @r T
walc-	zak
v Q l	tS { k
wald
w O: l d
wald-	horn
w O: l	d h O@ n
wald-	man
w Q l	d m V n
wald-	ner
w O: l	d n @r
wald-	ron
w O: l	d r V n
wale
w eI l
wales
w eI l z
walk
w Q k
walk-	ley
w O: k	l i:
walk-	man
w O: k	m { n
walk-	on
w O:	k Q n
walk-	out
w O:	k aU t
walk-	outs
w O:	k aU t s
walk-	up
w O:	k V p
walk-	way
w O: k	w eI
walk-	ways
w O: k	w eI z
walke
w O: k
walked
w O: k t
walks
w O: k s
wall
w O: l
wall-	board
w O: l	b O@ d
wall-	flo-	wer
w O: l	f l aU	@r
wall-	man
w O: l	m V n
wall-	pa-	per
w O: l	p eI	p @r
wall-	pa-	per-	ing
w O: l	p eI	p @r	I N
wall-	pa-	pered
w O: l	p eI	p @r d
wall-	pa-	pers
w O: l	p eI	p @r z
wall-	send
w O: l	s e n d
wall-	work
w O: l	w @r k
walled
w O: l d
walls
w O: l z
wall's
w O: l z
walsh
w O: l S
walt
w O: l t
walt-	ner
w O: l	t n @r
walt-	zer
w O: l	t s @r
walt-	zes
w O: l	t s V z
walt-	zing
w O: l	t s I N
walth
w O: l T
waltz
w O: l t s
wam-	ble
w Q m	b V l
wam-	pum
w Q m	p V m
wamp-	ler
w Q m	p l @r
wams-	ley
w Q m	z l i:
wan
w Q n
wan-	da
w Q n	d V
wan-	de-	rer
w Q n	d @r	@r
wan-	de-	rers
w Q n	d @r	@r z
wan-	de-	ring
w Q n	d @r	I N
wan-	de-	rings
w Q n	d @r	I N z
wan-	der
w Q n	d @r
wan-	der-	lust
w Q n	d @r	l V s t
wan-	dered
w Q n	d @r d
wan-	ders
w Q n	d @r z
wan-	die
w Q n	d i:
wan-	dis
w Q n	d I s
wan-	ger
w {	N @r
wan-	gle
w { N	g V l
wan-	gled
w { N	g V l d
wan-	na
w Q	n V
wan-	na-	be
w Q	n V	b i:
wan-	na-	bee
w Q	n V	b i:
wan-	na-	bees
w Q	n V	b i: z
wan-	na-	bes
w Q	n V	b i: z
wan-	ner
w Q	n @r
wan-	ta-	ges
w Q n	t I	dZ V z
wan-	tage
w Q n	t I dZ
wan-	ted
w O: n	t V d
wan-	ting
w Q n	t I N
wan-	ton
w Q n	t V n
wan-	ton-	ly
w Q n	t V n	l i:
wand
w Q n d
wands
w Q n d z
wane
w eI n
waned
w eI n d
wanes
w eI n z
wang
w { N
wang-	ler
w { N	g l @r
wang's
w { N z
wank
w Q N k
wann
w Q n
wans-	ley
w O: n	z l i:
want
w Q n t
wants
w Q n t s
wap-	ping
w Q	p I N
war
w O@
war-	b-	ling
w O@	b V	l I N
war-	bur-	ton
w O@	b @r	t V n
war-	da
w O@	d V
war-	ded
w O@	d V d
war-	dell
w O@	d e l
war-	den
w O@	d V n
war-	dens
w O@	d V n z
war-	den's
w O@	d V n z
war-	der
w O@	d @r
war-	ding
w O@	d I N
war-	dle
w O@	d V l
war-	drobe
w O@ d	r @U b
war-	drobes
w O@ d	r @U b z
war-	drop
w O@ d	r Q p
war-	fare
w O@	f e@
war-	field
w O@	f i: l d
war-	ford
w O@	f @r d
war-	ga
w O@	g V
war-	head
w O@	h e d
war-	heads
w O@	h e d z
war-	hol
w O@	h O: l
war-	hol's
w O: h	r O: l z
war-	ley
w O@	l i:
war-	like
w O@	l aI k
war-	ling
w O@	l I N
war-	lord
w O@	l O@ d
war-	lords
w O@	l O@ d z
war-	man
w O@	m V n
war-	mer
w O@	m @r
war-	mest
w O@	m V s t
war-	min-	ster
w O@	m I n	s t @r
war-	ming
w O@	m I N
war-	mish
w O@	m I S
war-	mon-	ge-	ring
w O@	m Q N	g @r	I N
war-	mon-	ger
w O@	m Q N	g @r
war-	mus
w O@	m V s
war-	ner
w O@	n @r
war-	ners
w O@	n @r z
war-	ner's
w O@	n @r z
war-	ning
w O@	n I N
war-	ning-	ly
w O@	n I N	l i:
war-	nings
w O@	n I N z
war-	nock
w O@	n Q k
war-	path
w O@	p { T
war-	ping
w O@	p I N
war-	ran-	ted
w O@	V n	t V d
war-	ran-	ties
w O@	V n	t i: z
war-	ran-	ty
w O@	V n	t i:
war-	rant
w O@	V n t
war-	rant-	less
w O@	V n	t l V s
war-	rants
w O@	V n t s
war-	ren
w O@	V n
war-	rens
w O@	V n z
war-	ren's
w O@	V n z
war-	ri-	or
w O@	i:	@r
war-	ri-	ors
w O@	i:	@r z
war-	rick
w O@	I k
war-	ring
w O@	I N
war-	ring-	ton
w O@	I N	t V n
war-	saw
w O@	s O:
war-	saws
w O@	s O: z
war-	saw's
w O@	s O: z
war-	ship
w O@	S I p
war-	ships
w O@	S I p s
war-	then
w O@	T V n
war-	time
w O@	t aI m
war-	times
w O@	t aI m z
war-	ton
w O@	t V n
war-	wick
w O@	w I k
war-	wick's
w O@	w I k s
warb-	ler
w O@ b	l @r
warb-	lers
w O@ b	l @r z
ward
w O@ d
ward-	law
w O@ d	l O:
warde
w O@ d
wards
w O@ d z
ward's
w O@ d z
ware
w e@
ware-	hou-	ses
w e@	h aU	z V z
ware-	hou-	sing
w e@	h aU	z I N
ware-	house
w e@	h aU s
ware-	housed
w e@	h aU z d
ware-	ing
w e@	I N
wares
w e@ z
warf
w O@ f
wark
w O@ k
warm
w O@ m
warm-	ly
w O@ m	l i:
warm-	up
w O@	m V p
warmed
w O@ m d
warms
w O@ m z
warmth
w O@ m T
warn
w O@ n
warne
w O@ n
warned
w O@ n d
warns
w O@ n z
warp
w O@ p
warp-	lane
w O@ p	l eI n
warp-	lanes
w O@ p	l eI n z
warped
w O@ p t
warps
w O@ p s
warr
w O@
wars
w O@ z
war's
w O@ z
warst-	ler
w O@ s	t l @r
wart
w O@ t
warth
w O@ T
warts
w O@ t s
was
w Q z
was-	co
w O: s	k @U
was-	ser-	man
w Q	s @r	m V n
was-	ser-	man's
w Q	s @r	m V n z
was-	son
w O:	s V n
was-	ted
w eI s	t V d
was-	ter
w eI s	t @r
was-	ters
w eI s	t @r z
was-	ting
w eI s	t I N
wash
w Q S
wash-	ba-	sin
w Q S	b eI	s I n
wash-	board
w Q S	b O@ d
wash-	burn
w Q S	b @r n
wash-	cloth
w Q S	k l O: T
wash-	ko
v Q S	k @U
wash-	out
w Q	S aU t
wash-	outs
w Q	S aU t s
wash-	room
w Q S	r u: m
wash-	tub
w Q S	t V b
washed
w Q S t
wasp
w Q s p
wasps
w Q s p s
wasp's
w Q s p s
waste
w eI s t
waste-	bas-	ket
w eI s	t b { s	k V t
waste-	bas-	kets
w eI s	t b { s	k V t s
waste-	ful
w eI s	t f V l
waste-	ful-	ness
w eI s	t f V l	n V s
waste-	land
w eI s	t l { n d
waste-	pa-	per
w eI s	t p eI	p @r
waste-	wa-	ter
w eI s	t w O:	t @r
wastes
w eI s t s
wat
w O: t
wat-	cher
w Q	tS @r
wat-	chers
w Q	tS @r z
wat-	ches
w Q	tS V z
wat-	ching
w Q	tS I N
wat-	ford
w O: t	f @r d
wat-	kin
w O: t	k I n
wat-	kins
w Q t	k I n z
wat-	rous
w Q t	r V s
wat-	son
w Q t	s V n
wat-	son-	ville
w Q t	s V n	v I l
wat-	son's
w Q t	s V n z
wat-	tage
w Q	t V dZ
wat-	ten-	berg
w Q	t V n	b @r g
wat-	ters
w Q	t @r z
wat-	tles
w Q	t V l z
wat-	ton
w O:	t V n
watch
w Q tS
watch-	dog
w Q tS	d O: g
watch-	dogs
w Q tS	d O: g z
watch-	ful
w Q tS	f V l
watch-	man
w Q tS	m V n
watch-	word
w Q tS	w @r d
watched
w Q tS t
watt
w Q t
watts
w Q t s
watt's
w Q t s
wau-	ke-	gan
w O:	k i:	g V n
wau-	ke-	sha
w O:	k i:	S V
wau-	sau
w O:	s O:
wau-	ters
w aU	t @r z
waugh
w O:
waugh's
w O: z
wave
w eI v
wave-	length
w eI v	l e N T
wave-	lengths
w eI v	l e N T s
waved
w eI v d
waves
w eI v z
wax
w { k s
wax-	ler
w { k	s l @r
wax-	man
w { k	s m V n
wax-	man's
w { k	s m V n z
waxed
w { k s t
way
w eI
way-	laid
w eI	l eI d
way-	land
w eI	l V n d
way-	lay
w eI	l eI
way-	lon
w eI	l Q n
way-	man
w eI	m V n
way-	side
w eI	s aI d
way-	ward
w eI	w @r d
wayne
w eI n
wayne's
w eI n z
waynes-	bo-	ro
w eI n	z b @r	@U
waynes-	ville
w eI n	z v I l
ways
w eI z
way's
w eI z
we
w i:
we-	ber
w e	b @r
we-	bers
w e	b @r z
we-	ber's
v eI	b @r z
we-	de-	kind
w e	d I	k I n d
we-	del
w e	d V l
we-	do-	wee
w e	d aU	w i:
we-	do-	wee's
w e	d aU	w i: z
we-	nat-	chee
w V	n {	tS i:
we-	no-	na
w e	n V	n V
we-	ren't
w @r	V n t
we-	ver
w i:	v @r
wea-	ke-	ning
w i:	k V	n I N
wea-	ken
w i:	k V n
wea-	kened
w i:	k V n d
wea-	kens
w i:	k V n z
wea-	ker
w i:	k @r
wea-	kest
w i:	k V s t
wea-	ning
w i:	n I N
wea-	pon
w e	p V n
wea-	pon-	ry
w e	p V n	r i:
wea-	pons
w e	p V n z
wea-	pon's
w e	p V n z
wea-	ra-	ble
w e@	V	b V l
wea-	rer
w e@	@r
wea-	rers
w e@	@r z
wea-	ri-	ly
w e@	I	l i:
wea-	ri-	ness
w I@	i:	n V s
wea-	ri-	some
w I@	i:	s V m
wea-	ried
w I@	i: d
wea-	ring
w e@	I N
wea-	ry
w I@	i:
wea-	ry-	ing
w i:	r i:	I N
wea-	sel
w i:	z V l
wea-	sel-	like
w i:	z V l	l aI k
wea-	the-	ring
w e	D @r	I N
wea-	ther
w e	D @r
wea-	ther-	by
w e	D @r	b i:
wea-	ther-	ford
w e	D @r	f @r d
wea-	ther-	head
w e	D @r	h e d
wea-	ther-	ly
w e	D @r	l i:
wea-	ther-	man
w e	D @r	m { n
wea-	ther-	men
w e	D @r	m e n
wea-	ther-	per-	son
w e	T @r	p @r	s V n
wea-	ther-	proof
w e	D @r p	r u: f
wea-	thered
w e	D @r d
wea-	thers
w e	D @r z
wea-	ther's
w e	D @r z
wea-	ver
w i:	v @r
wea-	vers
w i:	v @r z
wea-	ver's
w i:	v @r z
wea-	ving
w i:	v I N
wea-	vings
w i:	v I N z
weak
w i: k
weak-	ling
w i: k	l I N
weak-	ly
w i: k	l i:
weak-	nes-	ses
w i: k	n V	s V z
weak-	ness
w i: k	n V s
weaks
w i: k s
weal-	thi-	er
w e l	T i:	@r
weal-	thi-	est
w e l	T i:	V s t
weal-	thy
w e l	T i:
wealth
w e l T
wealths
w e l T s
wean
w i: n
weaned
w i: n d
wear
w e@
wears
w e@ z
weave
w i: v
weaved
w i: v d
weaves
w i: v z
web
w e b
web-	ber
w e	b @r
web-	ber's
w e	b @r z
web-	bing
w e	b I N
web-	mas-	ter
w e b	m { s	t @r
web-	site
w e b	s aI t
web-	ster
w e b	s t @r
web-	ster's
w e b	s t @r z
webb
w e b
webbed
w e b d
webbs
w e b z
webb's
w e b z
webs
w e b z
wecht
w e k t
weck
w e k
wed
w e d
we'd
w i: d
wed-	ded
w e	d V d
wed-	dell
w e	d V l
wed-	ding
w e	d I N
wed-	dings
w e	d I N z
wed-	ges
w e	dZ V z
wed-	lock
w e d	l Q k
wedg-	wood
w e dZ	w U d
wedge
w e dZ
wedged
w e dZ d
wednes-	day
w e n	z d i:
wednes-	days
w e n	z d eI z
wednes-	day's
w e n	z d i: z
wee
w i:
wee-	ded
w i:	d V d
wee-	ding
w i:	d I N
wee-	dy
w i:	d i:
wee-	ny
w i:	n i:
wee-	ping
w i:	p I N
wee-	py
w i:	p i:
wee-	vil
w i:	v I l
wee-	vils
w i:	v I l z
weed
w i: d
weeds
w i: d z
week
w i: k
week-	day
w i: k	d eI
week-	days
w i: k	d eI z
week-	en-	der
w i:	k e n	d @r
week-	end
w i:	k e n d
week-	ends
w i:	k e n d z
week-	end's
w i:	k e n d z
week-	ley
w i: k	l i:
week-	lies
w i: k	l i: z
week-	long
w i: k	l O: N
week-	ly
w i: k	l i:
weekes
w i: k s
weeks
w i: k s
week's
w i: k s
weeks'
w i: k s
weems
w i: m z
weep
w i: p
weeps
w i: p s
weh-	ner
w e	n @r
weh-	rle
w e@	V l
wehr
w e@
wei
w eI
wei-	bel
w aI	b V l
wei-	de
w aI	d i:
wei-	der
w aI	d @r
wei-	gel
w aI	g V l
wei-	ghing
w eI	I N
wei-	gle
w i:	g V l
wei-	kert
w aI	k @r t
wei-	ler
w aI	l @r
wei-	man
w aI	m V n
wei-	mar
v aI	m Q@
wei-	ner
w aI	n @r
wei-	nert
w aI	n @r t
wei-	rick
w aI	r I k
wei-	ser
w aI	s @r
weid-	man
w aI d	m V n
weid-	ner
w aI d	n @r
weigh
w eI
weigh-	ted
w eI	t V d
weigh-	ting
w eI	t I N
weigh-	tings
w eI	t I N z
weigh-	ty
w eI	t i:
weighed
w eI d
weighs
w eI z
weight
w eI t
weight-	less
w eI t	l V s
weight-	less-	ness
w eI t	l V s	n V s
weight-	lif-	ter
w eI t	l I f	t @r
weight-	lif-	ters
w eI t	l I f	t @r z
weight-	lif-	ting
w eI t	l I f	t I N
weights
w eI t s
weil
w aI l
weill
w aI l
weill's
w aI l z
weil's
w aI l z
wein
w i: n
wein-	ber-	ger
w aI n	b @r	g @r
wein-	ber-	ger's
w aI n	b @r	g @r z
wein-	berg
w aI n	b @r g
wein-	gar-	ten
w aI n	g Q@	t V n
wein-	gart-	ner
w aI N	g Q@ t	n @r
wein-	man
w aI n	m V n
wein-	reb
w aI n	r e b
wein-	rich
w aI n	r I k
wein-	stein
w aI n	s t aI n
wein-	stein's
w aI n	s t aI n z
wein-	stock
w aI n	s t Q k
weir
w i: r
weir-	der
w I@	d @r
weir-	dest
w I@	d V s t
weir-	do
w I@	d @U
weir-	dos
w I@	d @U z
weir-	ton
w I@	t V n
weir-	ton's
w I@	t V n z
weird
w I@ d
weird-	ly
w I@ d	l i:
weird-	ness
w I@ d	n V s
weir's
w i: r z
weis-	berg
w aI s	b @r g
weis-	man
w aI s	m V n
weis-	mann
w aI s	m V n
weis-	sert
w aI	s @r t
weis-	s's
w aI	s V z
weise
w i: s
weiss
w aI s
weiss-	berg
w aI s	b @r g
weiss-	man
w aI s	m V n
weiss-	mann
w aI s	m V n
weit-	man
w aI t	m V n
weitz-	man
w aI t	s m V n
weitz-	man's
w aI t	s m V n z
wel-	by
w e l	b i:
wel-	cher
w e l	tS @r
wel-	co-	ming
w e l	k V	m I N
wel-	come
w e l	k V m
wel-	comed
w e l	k V m d
wel-	comes
w e l	k V m z
wel-	ded
w e l	d V d
wel-	der
w e l	d @r
wel-	ders
w e l	d @r z
wel-	ding
w e l	d I N
wel-	don
w e l	d V n
wel-	don's
w e l	d V n z
wel-	fare
w e l	f e@
wel-	ford
w e l	f @r d
wel-	ker
w e l	k @r
wel-	land
w e	l V n d
wel-	ler
w e	l @r
wel-	ling
w e	l I N
wel-	ling-	ton
w e	l I N	t V n
wel-	ling-	ton's
w e	l I N	t V n z
wel-	ter
w e l	t @r
wel-	ter-	weight
w e l	t @r	w eI t
wel-	ton
w e l	t V n
wel-	ty
w e l	t i:
welch
w e l tS
weld
w e l d
weld-	wood
w e l	d w U d
welds
w e l d z
welk
w e l k
welke
w e l k
well
w e l
we'll
w i: l
well-	be-	ing
w e l	b i:	I N
well-	born
w e l	b O@ n
well-	doer
w e l	d u: r
well-	head
w e l	h e d
well-	man
w e l	m V n
well-	ness
w e l	n V s
well-	point
w e l	p OI n t
well-	spring
w e l	s p r I N
well-	s's
w e l	z V z
welles
w e l z
welles-	ley
w e l	z l i:
wells
w e l z
welsh
w e l tS
welt
w e l t
wemb-	ley
w e m	b l i:
wen
w e n
wen-	ces-	laus
w e n	s V s	l O: s
wen-	ches
w e n	tS V z
wen-	da
w e n	d V
wen-	de-	line
w e n	d V	l aI n
wen-	del
w e n	d V l
wen-	dell
w e n	d V l
wen-	ding
w e n	d I N
wen-	dy
w e n	d i:
wen-	dy's
w e n	d i: z
wen-	ger
w e	N @r
wen-	gert
w e N	g @r t
wen-	zel
w e n	z V l
wend
w e n d
wende
w e n d
wends
w e n d z
wendt
w e n t
wenge
w e n dZ
went
w e n t
went-	worth
w e n	t w @r T
wentz-	ville
w e n	t s v I l
wenz
w e n z
wept
w e p t
wer-	ner
w @r	n @r
wer-	ner's
w @r	n @r z
wer-	nick
w @r	n I k
wer-	thei-	mer
w @r t	h aI	m @r
wer-	theim
w @r t	h aI m
wer-	ther
w @r	D @r
were
w @r
we're
w i: r
were-	wolf
w e@	w U l f
wert
w @r t
wertz
w @r t s
wes
w e s
)"
R"(wes-	co
w e s	k @U
wes-	cott
w e s	k Q t
wes-	ker
w e s	k @r
wes-	ker's
w e s	k @r z
wes-	ley
w e s	l i:
wes-	ley-	an
w e z	l i:	V n
wes-	s-	ling
w e	s V	l I N
wes-	sel
w e	s V l
wes-	sex
w e	s V k s
wes-	son
w e	s V n
wes-	ter
w e s	t @r
wes-	ter-	field
w e s	t @r	f i: l d
wes-	ter-	ly
w e s	t @r	l i:
wes-	ter-	ner
w e s	t @r	n @r
wes-	ter-	ners
w e s	t @r	n @r z
wes-	ter-	ni-	za-	tion
w e s	t @r	n I	z eI	S V n
wes-	ter-	nize
w e s	t @r	n aI z
wes-	ter-	nized
w e s	t @r	n aI z d
wes-	tern
w e s	t @r n
wes-	tern-	most
w e s	t @r n	m @U s t
wes-	terns
w e s	t @r n z
wes-	ting-	hou-	se's
w e s	t I N	h aU	s V z
wes-	ting-	house
w e s	t I N	h aU s
wes-	ton
w e s	t V n
west
w e s t
west-	berg
w e s	t b @r g
west-	bo-	rough
w e s	t b @r	@U
west-	bound
w e s	t b aU n d
west-	brook
w e s	t b r U k
west-	by
w e s	t b i:
west-	ches-	ter
w e s	t tS e s	t @r
west-	ches-	ter's
w e s	t tS e s	t @r z
west-	fahl
w e s	t f Q l
west-	fall
w e s	t f O: l
west-	field
w e s	t f i: l d
west-	hamp-	ton
w e s	t h { m	p t V n
west-	land
w e s	t l V n d
)"