R"(in-	duct
I n	d V k t
in-	dul-	gen-	ces
I n	d V l	dZ V n	s V z
in-	dul-	gence
I n	d V l	dZ V n s
in-	dul-	gent
I n	d V l	dZ V n t
in-	dul-	ges
I n	d V l	dZ V z
in-	dul-	ging
I n	d V l	dZ I N
in-	dulge
I n	d V l dZ
in-	dulged
I n	d V l dZ d
in-	dus
I n	d V s
in-	dus-	tri-	a-	li-	za-	tion
I n	d V s	t r i:	V	l V	z eI	S V n
in-	dus-	tri-	a-	li-	zing
I n	d V s	t r i:	V	l aI	z I N
in-	dus-	tri-	a-	list
I n	d V s	t r i:	V	l V s t
in-	dus-	tri-	a-	lists
I n	d V s	t r i:	V	l V s t s
in-	dus-	tri-	a-	lize
I n	d V s	t r i:	V	l aI z
in-	dus-	tri-	a-	lized
I n	d V s	t r i:	V	l aI z d
in-	dus-	tri-	al
I n	d V s	t r i:	V l
in-	dus-	tri-	al-	ly
I n	d V s	t r i:	V	l i:
in-	dus-	tri-	als
I n	d V s	t r i:	V l z
in-	dus-	tri-	ous
I n	d V s	t r i:	V s
in-	dus-	tries
I n	d V s	t r i: z
in-	dust-	ry
I n	d V s	t r i:
in-	dust-	ry's
I n	d V s	t r i: z
in-	dy
I n	d i:
in-	fa-	mous
I n	f V	m V s
in-	fa-	my
I n	f V	m i:
in-	fa-	tu-	a-	ted
I n	f {	tS u:	eI	t V d
in-	fa-	tu-	a-	ting
I n	f {	tS u:	eI	t I N
in-	fa-	tu-	a-	tion
I n	f {	tS u:	eI	S V n
in-	fa-	tu-	ate
I n	f {	tS u:	eI t
in-	fal-	li-	bi-	li-	ty
I n	f {	l I	b I	l I	t i:
in-	fal-	li-	ble
I n	f {	l I	b V l
in-	fan-	cy
I n	f V n	s i:
in-	fan-	te
I n	f Q n	t eI
in-	fan-	ti-	cide
I n	f { n	t I	s aI d
in-	fan-	tile
I n	f V n	t V l
in-	fant
I n	f V n t
in-	fant-	ry
I n	f V n	t r i:
in-	fant-	ry-	man
I n	f { n	t r i:	m V n
in-	fant-	ry-	men
I n	f { n	t r i:	m e n
in-	fants
I n	f V n t s
in-	fant's
I n	f V n t s
in-	fants'
I n	f V n t s
in-	farc-	tion
I n	f Q@ k	S V n
in-	fe-	ren-	ces
I n	f @r	e n	s V z
in-	fe-	rence
I n	f @r	V n s
in-	fe-	ri-	o-	ri-	ty
I n	f I@	i:	O@	I	t i:
in-	fe-	ri-	or
I n	f I@	i:	@r
in-	fea-	si-	ble
I n	f i:	z I	b V l
in-	fec-	ted
I n	f e k	t V d
in-	fec-	ting
I n	f e k	t I N
in-	fec-	tion
I n	f e k	S V n
in-	fec-	tions
I n	f e k	S V n z
in-	fec-	tious
I n	f e k	S V s
in-	fec-	tive
I n	f e k	t I v
in-	fect
I n	f e k t
in-	fects
I n	f e k t s
in-	fer
I n	f @r
in-	fer-	nal
I n	f @r	n V l
in-	fer-	no
I n	f @r	n @U
in-	fer-	ring
I n	f @r	I N
in-	fer-	ti-	li-	ty
I n	f @r	t I	l I	t i:
in-	fer-	tile
I n	f @r	t I l
in-	ferred
I n	f @r d
in-	fers
I n	f @r z
in-	fes-	ta-	tion
I n	f e s	t eI	S V n
in-	fes-	ta-	tions
I n	f e s	t eI	S V n z
in-	fes-	ted
I n	f e s	t V d
in-	fest
I n	f e s t
in-	fests
I n	f e s t s
in-	fi-	de-	li-	ties
I n	f I	d e	l I	t i: z
in-	fi-	de-	li-	ty
I n	f I	d e	l I	t i:
in-	fi-	del
I n	f I	d e l
in-	fi-	dels
I n	f I	d e l z
in-	fi-	ni-	te-	si-	mal
I n	f I	n I	t e	s I	m V l
in-	fi-	ni-	tive
I n	f I	n I	t I v
in-	fi-	ni-	tum
I n	f I	n I	t V m
in-	fi-	ni-	ty
I n	f I	n I	t i:
in-	fi-	nite
I n	f I	n I t
in-	fi-	nite-	ly
I n	f I	n I t	l i:
in-	fiel-	der
I n	f i: l	d @r
in-	fiel-	ders
I n	f i: l	d @r z
in-	field
I n	f i: l d
in-	figh-	ting
I n	f aI	t I N
in-	filt-	ra-	ted
I n	f I l	t r eI	t V d
in-	filt-	ra-	ting
I n	f I l	t r eI	t I N
in-	filt-	ra-	tion
I n	f I l	t r eI	S V n
in-	filt-	ra-	tor
I n	f I l	t r eI	t @r
in-	filt-	ra-	tors
I n	f I l	t r eI	t @r z
in-	filt-	rate
I n	f I l	t r eI t
in-	fir-	ma-	ry
I n	f @r	m @r	i:
in-	fir-	mi-	ties
I n	f @r	m I	t i: z
in-	fir-	mi-	ty
I n	f @r	m I	t i:
in-	firm
I n	f @r m
in-	firmed
I n	f @r m d
in-	fla-	ming
I n	f l eI	m I N
in-	fla-	ta-	ble
I n	f l eI	t V	b V l
in-	fla-	ted
I n	f l eI	t V d
in-	fla-	ting
I n	f l eI	t I N
in-	fla-	tio-	na-	ry
I n	f l eI	S V	n e@	i:
in-	fla-	tion
I n	f l eI	S V n
in-	fla-	tion's
I n	f l eI	S V n z
in-	fla-	tor
I n	f l eI	t @r
in-	flam-	ma-	ble
I n	f l {	m V	b V l
in-	flam-	ma-	tion
I n	f l V	m eI	S V n
in-	flam-	ma-	to-	ry
I n	f l {	m V	t O@	i:
in-	flame
I n	f l eI m
in-	flamed
I n	f l eI m d
in-	flames
I n	f l eI m z
in-	flate
I n	f l eI t
in-	flates
I n	f l eI t s
in-	fle-	xi-	bi-	li-	ty
I n	f l e k	s I	b I	l I	t i:
in-	fle-	xi-	ble
I n	f l e k	s I	b V l
in-	flec-	ted
I n	f l e k	t V d
in-	flec-	tion
I n	f l e k	S V n
in-	flec-	tions
I n	f l e k	S V n z
in-	flect
I n	f l e k t
in-	flic-	ted
I n	f l I k	t V d
in-	flic-	ting
I n	f l I k	t I N
in-	flic-	tion
I n	f l I k	S V n
in-	flict
I n	f l I k t
in-	flicts
I n	f l I k t s
in-	flight
I n	f l aI t
in-	flow
I n	f l @U
in-	flows
I n	f l @U z
in-	flu-	en-	ces
I n	f l u:	V n	s V z
in-	flu-	en-	cing
I n	f l u:	V n	s I N
in-	flu-	en-	tial
I n	f l u:	e n	tS V l
in-	flu-	en-	za
I n	f l u:	e n	z V
in-	flu-	ence
I n	f l u:	V n s
in-	flu-	enced
I n	f l u:	V n s t
in-	flux
I n	f l V k s
in-	fo
I n	f @U
in-	fo-	mer-	cial
I n	f @U	m @r	S V l
in-	fo-	mer-	cials
I n	f @U	m @r	S V l z
in-	fo-	tain-	ment
I n	f @U	t eI n	m V n t
in-	for-	ma-	li-	ty
I n	f @r	m {	l I	t i:
in-	for-	ma-	tics
I n	f @r	m {	t I k s
in-	for-	ma-	tio-	nal
I n	f @r	m eI	S V	n V l
in-	for-	ma-	tion
I n	f @r	m eI	S V n
in-	for-	ma-	tions
I n	f @r	m eI	S V n z
in-	for-	ma-	tion's
I n	f @r	m eI	S V n z
in-	for-	ma-	tive
I n	f O@	m V	t I v
in-	for-	mal
I n	f O@	m V l
in-	for-	mal-	ly
I n	f O@	m V	l i:
in-	for-	mant
I n	f O@	m V n t
in-	for-	mants
I n	f O@	m V n t s
in-	for-	mer
I n	f O@	m @r
in-	for-	mers
I n	f O@	m @r z
in-	for-	ming
I n	f O@	m I N
in-	form
I n	f O@ m
in-	formed
I n	f O@ m d
in-	forms
I n	f O@ m z
in-	fra
I n	f r V
in-	frac-	tion
I n	f r { k	S V n
in-	frac-	tions
I n	f r { k	S V n z
in-	fre-	quen-	cy
I n	f r i: k	w V n	s i:
in-	fre-	quent
I n	f r i: k	w V n t
in-	fre-	quent-	ly
I n	f r i: k	w V n	t l i:
in-	frin-	ges
I n	f r I n	dZ V z
in-	frin-	ging
I n	f r I n	dZ I N
in-	fringe
I n	f r I n dZ
in-	fringe-	ment
I n	f r I n	dZ m V n t
in-	fringe-	ments
I n	f r I n	dZ m V n t s
in-	fringed
I n	f r I n dZ d
in-	fu-	ri-	a-	ted
I n	f j U@	i:	eI	t V d
in-	fu-	ri-	a-	ting
I n	f j U@	i:	eI	t I N
in-	fu-	ri-	ate
I n	f j U@	i:	eI t
in-	fu-	ri-	ates
I n	f j U@	i:	eI t s
in-	fu-	ses
I n	f j u:	z V z
in-	fu-	sing
I n	f j u:	z I N
in-	fu-	sion
I n	f j u:	Z V n
in-	fu-	sions
I n	f j u:	Z V n z
in-	fuse
I n	f j u: z
in-	fused
I n	f j u: z d
in-	ga
i: N	g V
in-	galls
I N	g O: l z
in-	gar
I N	g @r
in-	ge-	mar
I N	g e	m Q@
in-	ge-	nious
I n	dZ i: n	j V s
in-	ge-	nious-	ly
I n	dZ i: n	j V s	l i:
in-	ge-	nu-	i-	ty
I n	dZ V	n u:	V	t i:
in-	ge-	nu-	ous
I n	dZ e n	j u:	V s
in-	ge-	nue
I n	dZ e n	j u:
in-	ger
I	N @r
in-	ger-	soll
I N	g @r	s O: l
in-	ges-	ted
I n	dZ e s	t V d
in-	ges-	ting
I n	dZ e s	t I N
in-	ges-	tion
I n	dZ e s	tS V n
in-	gest
I n	dZ e s t
in-	gham
I	N V m
in-	gle
I N	g V l
in-	gle-	bert
I N	g V l	b @r t
in-	gle-	nook
I N	g V l	n U k
in-	gle-	wood
I N	g V l	w U d
in-	gles
I N	g V l z
in-	go
I N	g @U
in-	gold
I N	g @U l d
in-	got
I N	g V t
in-	gots
I N	g V t s
in-	gra-	ham
I N	g r V	h { m
in-	grain
I n	g r eI n
in-	grained
I n	g r eI n d
in-	ha-	bi-	ta-	tion
I n	h {	b I	t eI	S V n
in-	ha-	bi-	tant
I n	h {	b I	t V n t
in-	ha-	bi-	tants
I n	h {	b I	t V n t s
in-	ha-	bi-	ted
I n	h {	b I	t I d
in-	ha-	bi-	ting
I n	h {	b I	t I N
in-	ha-	bit
I n	h {	b I t
in-	ha-	bits
I n	h {	b I t s
in-	ha-	la-	tion
I	n V	l eI	S V n
in-	ha-	lant
I n	h eI	l V n t
in-	ha-	lants
I n	h eI	l V n t s
in-	ha-	ler
I n	h eI	l @r
in-	ha-	ling
I n	h eI	l I N
in-	hale
I n	h eI l
in-	haled
I n	h eI l d
in-	he-	rent
I n	h I@	V n t
in-	he-	rent-	ly
I n	h I@	V n	t l i:
in-	he-	ri-	ta-	ble
I n	h e@	I	t V	b V l
in-	he-	rit
I n	h e@	I t
in-	hu-	ma-	ni-	ty
I n	h j u:	m {	n I	t i:
in-	jec-	ta-	ble
I n	dZ e k	t V	b V l
in-	jec-	ted
I n	dZ e k	t V d
in-	jec-	ting
I n	dZ e k	t I N
in-	jec-	tion
I n	dZ e k	S V n
in-	jec-	tions
I n	dZ e k	S V n z
in-	jec-	tor
I n	dZ e k	t @r
in-	jec-	tors
I n	dZ e k	t @r z
in-	ject
I n	dZ e k t
in-	jects
I n	dZ e k t s
in-	ju-	di-	cious
I n	dZ V	d I	S V s
in-	ju-	ri-	ous
I n	dZ U@	i:	V s
in-	ju-	ries
I n	dZ @r	i: z
in-	ju-	ring
I n	dZ @r	I N
in-	ju-	ry
I n	dZ @r	i:
in-	junc-	tion
I n	dZ V N	k S V n
in-	junc-	tions
I n	dZ V N	k S V n z
in-	junc-	tive
I n	dZ V N	k t I v
in-	jure
I n	dZ @r
in-	jured
I n	dZ @r d
in-	jures
I n	dZ @r z
in-	jus-	ti-	ces
I n	dZ V s	t I	s V z
in-	jus-	tice
I n	dZ V s	t I s
in-	ka-	tha
I N	k {	T V
in-	ka-	tha's
I N	k {	T V z
in-	ky
I N	k i:
in-	laid
I n	l eI d
in-	land
I n	l { n d
in-	land's
I n	l V n d z
in-	law
I n	l O:
in-	laws
I n	l O: z
in-	lay
I n	l eI
in-	let
I n	l e t
in-	lets
I n	l e t s
in-	man
I n	m V n
in-	man's
I n	m V n z
in-	mate
I n	m eI t
in-	mates
I n	m eI t s
in-	mate's
I n	m eI t s
in-	nard
I	n @r d
in-	nards
I	n @r d z
in-	nate
I	n eI t
in-	nate-	ly
I	n eI t	l i:
in-	ner
I	n @r
in-	ner-	most
I	n @r	m @U s t
in-	nes
I	n V s
in-	ness
I	n V s
in-	ning
I	n I N
in-	nings
I	n I N z
in-	nis
I	n I s
in-	no-	cence
I	n V	s V n s
in-	no-	cent
I	n V	s V n t
in-	no-	cent-	ly
I	n V	s V n	t l i:
in-	no-	cents
I	n V	s V n t s
in-	no-	cu-	ous
I	n Q k	j u:	V s
in-	no-	mi-	nate
I	n Q	m I	n V t
in-	no-	va-	ted
I	n V	v eI	t V d
in-	no-	va-	ting
I	n V	v eI	t I N
in-	no-	va-	tion
I	n V	v eI	S V n
in-	no-	va-	tions
I	n V	v eI	S V n z
in-	no-	va-	tive
I	n V	v eI	t I v
in-	no-	va-	tor
I	n V	v eI	t @r
in-	no-	va-	tors
I	n V	v eI	t @r z
in-	no-	vate
I	n V	v eI t
in-	nu-	en-	do
I n	j u:	e n	d @U
in-	nu-	en-	does
I n	j u:	e n	d @U z
in-	nu-	en-	dos
I n	j u:	e n	d @U z
in-	nu-	me-	ra-	ble
I	n u:	m @r	V	b V l
in-	pa-	tient
I n	p eI	S e n t
in-	pa-	tients
I n	p eI	S e n t s
in-	put
I n	p U t
in-	puts
I n	p U t s
in-	quest
I n	k w e s t
in-	qui-	r-	ies
I n	k w aI	@r	i: z
in-	qui-	r-	ing
I n	k w aI	@r	I N
in-	qui-	red
I n	k w aI	@r d
in-	qui-	rer
I n	k w aI	r @r
in-	qui-	res
I n	k w aI	@r z
in-	qui-	ry
I n	k w aI	r i:
in-	qui-	si-	tion
I n	k w I	z I	S V n
in-	qui-	si-	tive
I n	k w I	z I	t I v
in-	qui-	si-	tor
I n	k w I	z I	t @r
in-	qui-	si-	tors
I n	k w I	z I	t @r z
in-	quire
I n	k w aI r
in-	road
I n	r @U d
in-	roads
I n	r @U d z
in-	sa-	ni-	ty
I n	s {	n I	t i:
in-	sa-	tia-	ble
I n	s eI	S V	b V l
in-	sane
I n	s eI n
in-	se-	cu-	ri-	ties
I n	s I k	j U@	I	t i: z
in-	se-	cu-	ri-	ty
I n	s I k	j U@	I	t i:
in-	se-	cure
I n	s V k	j @r
in-	se-	mi-	na-	tion
I n	s e	m I	n eI	S V n
in-	se-	mi-	nate
I n	s e	m I	n eI t
in-	se-	pa-	ra-	ble
I n	s e	p @r	V	b V l
in-	se-	pa-	rab-	ly
I n	s e	p @r	V b	l i:
in-	sec-	ti-	cide
I n	s e k	t I	s aI d
in-	sec-	ti-	cides
I n	s e k	t I	s aI d z
in-	sec-	ti-	vo-	rous
I n	s e k	t I	v @r	V s
in-	sect
I n	s e k t
in-	sects
I n	s e k t s
in-	sect's
I n	s e k t s
in-	sen-	si-	ti-	vi-	ty
I n	s e n	s I	t I	v I	t i:
in-	sen-	si-	tive
I n	s e n	s I	t I v
in-	ser-	ted
I n	s @r	t V d
in-	ser-	ting
I n	s @r	t I N
in-	ser-	tion
I n	s @r	S V n
in-	sert
I n	s @r t
in-	serts
I n	s @r t s
in-	set
I n	s e t
in-	shore
I n	S O@
in-	si-	der
I n	s aI	d @r
in-	si-	ders
I n	s aI	d @r z
in-	si-	der's
I n	s aI	d @r z
in-	si-	di-	ous
I n	s I	d i:	V s
in-	si-	nu-	a-	ted
I n	s I n	j u:	eI	t V d
in-	si-	nu-	a-	ting
I n	s I n	j u:	eI	t I N
in-	si-	nu-	a-	tion
I n	s I n	j u:	eI	S V n
in-	si-	nu-	a-	tions
I n	s I n	j u:	eI	S V n z
in-	si-	nu-	ate
I n	s I n	j u:	eI t
in-	si-	nu-	ates
I n	s I n	j u:	eI t s
in-	side
I n	s aI d
in-	sides
I n	s aI d z
in-	sig-	ni-	a
I n	s I g	n i:	V
in-	sig-	ni-	fi-	cance
I n	s I g	n j I	f I	k V n s
in-	sig-	ni-	fi-	cant
I n	s I g	n j I	f I	k V n t
in-	sight
I n	s aI t
in-	sight-	ful
I n	s aI t	f V l
in-	sights
I n	s aI t s
in-	sin-	cere
I n	s I n	s I@
in-	sis-	ted
I n	s I s	t V d
in-	sis-	tence
I n	s I s	t V n s
in-	sis-	tent
I n	s I s	t V n t
in-	sis-	tent-	ly
I n	s I s	t V n	t l i:
in-	sis-	ting
I n	s I s	t I N
in-	sist
I n	s I s t
in-	sists
I n	s I s t s
in-	so-	far
I n	s V	f Q@
in-	so-	lence
I n	s V	l V n s
in-	so-	lent
I n	s V	l V n t
in-	so-	lu-	ble
I n	s Q l	j V	b V l
in-	sol-	ven-	cies
I n	s Q l	v V n	s i: z
in-	sol-	ven-	cy
I n	s Q l	v V n	s i:
in-	sol-	vent
I n	s Q l	v V n t
in-	som-	ni-	a
I n	s Q m	n i:	V
in-	som-	ni-	ac
I n	s Q m	n i:	{ k
in-	spec-	ted
I n	s p e k	t V d
in-	spec-	ting
I n	s p e k	t I N
in-	spec-	tion
I n	s p e k	S V n
in-	spec-	tions
I n	s p e k	S V n z
in-	spec-	to-	rate
I n	s p e k	t @r	V t
in-	spec-	tor
I n	s p e k	t @r
in-	spec-	tors
I n	s p e k	t @r z
in-	spec-	tor's
I n	s p e k	t @r z
in-	spect
I n	s p e k t
in-	su-	bor-	di-	na-	tion
I n	s V	b O@	d V	n eI	S V n
in-	su-	bor-	di-	nate
I n	s V	b O@	d V	n eI t
in-	su-	la-	ri-	ty
I n	s V	l e@	V	t i:
in-	su-	la-	ted
I n	s V	l eI	t V d
in-	su-	la-	ting
I n	s V	l eI	t I N
in-	su-	la-	tion
I n	s V	l eI	S V n
in-	su-	la-	tor
I n	s V	l eI	t @r
in-	su-	la-	tors
I n	s V	l eI	t @r z
in-	su-	lar
I n	s V	l @r
in-	su-	late
I n	s V	l eI t
in-	su-	lin
I n	s V	l V n
in-	su-	ran-	ces
I n	S U@	V n	s V z
in-	su-	ran-	ce's
I n	S U@	V n	s V z
in-	su-	rance
I n	S U@	V n s
in-	su-	ring
I n	S U@	I N
in-	sub-	stan-	ti-	ate
I n	s V b	s t { n	tS i:	eI t
in-	sub-	stan-	tial
I n	s V b	s t { n	tS V l
in-	suf-	fe-	ra-	ble
I n	s V	f @r	V	b V l
in-	suf-	fi-	cient
I n	s V	f I	S V n t
in-	suf-	fi-	cient-	ly
I n	s V	f I	S V n	t l i:
in-	sul-	ted
I n	s V l	t V d
in-	sul-	ting
I n	s V l	t I N
in-	sult
I n	s V l t
in-	sults
I n	s V l t s
in-	sup-	por-	ta-	ble
I n	s V	p O@	t V	b V l
in-	sur-	er
I n	S U@	@r
in-	sur-	ers
I n	S U@	@r z
in-	sur-	er's
I n	S U@	@r z
in-	sur-	gen-	cies
I n	s @r	dZ V n	s i: z
in-	sur-	gen-	cy
I n	s @r	dZ V n	s i:
in-	sur-	gent
I n	s @r	dZ V n t
in-	sur-	gents
I n	s @r	dZ V n t s
in-	sur-	moun-	ta-	ble
I n	s @r	m aU n	t V	b V l
in-	sur-	rec-	tion
I n	s @r	e k	S V n
in-	sure
I n	S U@
in-	sured
I n	S U@ d
in-	sures
I n	S U@ z
in-	tact
I n	t { k t
in-	tag-	lio
I n	t { l	j @U
in-	take
I n	t eI k
in-	tan-	gi-	ble
I n	t { n	dZ V	b V l
in-	tan-	gi-	bles
I n	t { n	dZ V	b V l z
in-	te-	ger
I n	t V	dZ @r
in-	te-	gers
I n	t V	dZ @r z
in-	te-	gu-	ment
I n	t e g	j V	m V n t
in-	te-	ra-	gen-	cy
I n	t @r	eI	dZ V n	s i:
in-	te-	rac-	ted
I n	t @r	{ k	t V d
in-	te-	rac-	ti-	vi-	ty
I n	t @r	{ k	t I	v V	t i:
in-	te-	rac-	ting
I n	t @r	{ k	t I N
in-	te-	rac-	tion
I n	t @r	{ k	S V n
in-	te-	rac-	tions
I n	t @r	{ k	S V n z
in-	te-	rac-	tive
I n	t @r	{ k	t I v
in-	te-	ract
I n	t @r	{ k t
in-	te-	racts
I n	t @r	{ k t s
in-	te-	res-	ting-	ly
I n	t @r	e s	t I N	l i:
in-	te-	ri-	or
I n	t I@	i:	@r
in-	te-	ri-	ors
I n	t I@	i:	@r z
in-	te-	rim
I n	t @r	V m
in-	te-	rof-	fice
I n	t @r	O:	f V s
in-	teg-	ra-	ted
I n	t V g	r eI	t V d
in-	teg-	ra-	ting
I n	t V g	r eI	t I N
in-	teg-	ra-	tion
I n	t V g	r eI	S V n
in-	teg-	ra-	tions
I n	t V g	r eI	S V n z
in-	teg-	ra-	tor
I n	t V g	r eI	t @r
in-	teg-	ra-	tors
I n	t V g	r eI	t @r z
in-	teg-	ral
I n	t V g	r V l
in-	teg-	rate
I n	t V g	r eI t
in-	teg-	rates
I n	t V g	r eI t s
in-	teg-	ri-	ty
I n	t e g	r V	t i:
in-	tel
I n	t e l
in-	tel-	lec-	tu-	a-	li-	sm
I n	t e	l V k	tS u:	V	l I	z V m
in-	tel-	lec-	tu-	al
I n	t V	l e k	tS u:	V l
in-	tel-	lect
I n	t V	l e k t
in-	tel-	lects
I n	t V	l e k t s
in-	tel-	li-	gence
I n	t e	l V	dZ V n s
in-	tem-	pe-	rate
I n	t e m	p @r	V t
in-	ten-	ded
I n	t e n	d V d
in-	ten-	ding
I n	t e n	d I N
in-	ten-	si-	fi-	ca-	tion
I n	t e n	s V	f V	k eI	S V n
in-	ten-	si-	fied
I n	t e n	s V	f aI d
in-	ten-	si-	fies
I n	t e n	s V	f aI z
in-	ten-	si-	fy
I n	t e n	s V	f aI
in-	ten-	si-	fy-	ing
I n	t e n	s V	f aI	I N
in-	ten-	si-	ties
I n	t e n	s V	t i: z
in-	ten-	si-	ty
I n	t e n	s V	t i:
in-	ten-	sive
I n	t e n	s V v
in-	ten-	sive-	ly
I n	t e n	s I v	l i:
in-	ten-	tio-	nal
I n	t e n	S V	n V l
in-	ten-	tio-	nal-	ly
I n	t e n	S V	n V	l i:
in-	ten-	tion
I n	t e n	tS V n
in-	ten-	tioned
I n	t e n	tS V n d
in-	ten-	tions
I n	t e n	tS V n z
in-	tend
I n	t e n d
in-	tends
I n	t e n d z
in-	tense
I n	t e n s
in-	tense-	ly
I n	t e n	s l i:
in-	tent
I n	t e n t
in-	tent-	ly
I n	t e n	t l i:
in-	tents
I n	t e n t s
in-	ter
I n	t @r
in-	ter-	bank
I n	t @r	b { N k
in-	ter-	bred
I n	t @r b	r e d
in-	ter-	ce-	ded
I n	t @r	s i:	d V d
in-	ter-	ce-	ding
I n	t @r	s i:	d I N
in-	ter-	cede
I n	t @r	s i: d
in-	ter-	cel-	lu-	lar
I n	t @r	s e l	j V	l @r
in-	ter-	cep-	ted
I n	t @r	s e p	t V d
in-	ter-	cep-	ting
I n	t @r	s e p	t I N
in-	ter-	cep-	tion
I n	t @r	s e p	S V n
in-	ter-	cep-	tions
I n	t @r	s e p	S V n z
in-	ter-	cep-	tor
I n	t @r	s e p	t @r
in-	ter-	cep-	tors
I n	t @r	s e p	t @r z
in-	ter-	cept
I n	t @r	s e p t
in-	ter-	cepts
I n	t @r	s e p t s
in-	ter-	ces-	sion
I n	t @r	s e	S V n
in-	ter-	chan-	gea-	ble
I n	t @r	tS eI n	dZ V	b V l
in-	ter-	chan-	geab-	ly
I n	t @r	tS eI n	dZ V b	l i:
in-	ter-	chan-	ges
I n	t @r	tS eI n	dZ V z
in-	ter-	change
I n	t @r	tS eI n dZ
in-	ter-	ci-	ty
I n	t @r	s I	t i:
in-	ter-	col-	le-	giate
I n	t @r	k V	l i:	dZ V t
)"
R"(in-	ter-	com
I n	t @r	k Q m
in-	ter-	com-	pa-	ny
I n	t @r	k V m	p V	n i:
in-	ter-	con-	nec-	ted
I n	t @r	k V	n e k	t V d
in-	ter-	con-	nec-	tion
I n	t @r	k V	n e k	S V n
in-	ter-	con-	nec-	tions
I n	t @r	k V	n e k	S V n z
in-	ter-	con-	nect
I n	t @r	k V	n e k t
in-	ter-	con-	ti-	nen-	tal
I n	t @r	k Q n	t V	n e n	t V l
in-	ter-	course
I n	t @r	k O@ s
in-	ter-	cul-	tu-	ral
I n	t @r	k V l	tS @r	V l
in-	ter-	cur-	rent
I n	t @r	k @r	V n t
in-	ter-	de-	pen-	dence
I n	t @r	d V	p e n	d V n s
in-	ter-	de-	pen-	dent
I n	t @r	d V	p e n	d V n t
in-	ter-	dea-	ler
I n	t @r	d i:	l @r
in-	ter-	di-	gi-	tal
I n	t @r	d I	dZ V	t V l
in-	ter-	dic-	ted
I n	t @r	d I k	t V d
in-	ter-	dic-	ting
I n	t @r	d I k	t I N
in-	ter-	dic-	tion
I n	t @r	d I k	S V n
in-	ter-	dict
I n	t @r	d I k t
in-	ter-	dis-	cip-	li-	na-	ry
I n	t @r	d I	s V p	l V	n e@	i:
in-	ter-	fa-	ces
I n	t @r	f eI	s V z
in-	ter-	face
I n	t @r	f eI s
in-	ter-	faith
I n	t @r	f eI T
in-	ter-	fe-	rence
I n	t @r	f I@	V n s
in-	ter-	fe-	ring
I n	t @r	f I@	I N
in-	ter-	fe-	ro-	me-	ter
I n	t @r	f @r	Q	m V	t @r
in-	ter-	fe-	ron
I n	t @r	f I@	Q n
in-	ter-	fe-	rons
I n	t @r	f I@	Q n z
in-	ter-	fere
I n	t @r	f I@
in-	ter-	fered
I n	t @r	f I@ d
in-	ter-	feres
I n	t @r	f I@ z
in-	ter-	ge-	ne-	ra-	tio-	nal
I n	t @r	dZ e	n @r	eI	S V	n V l
in-	ter-	go-	vern-	men-	tal
I n	t @r	g V	v @r n	m e n	t V l
in-	ter-	group
I n	t @r g	r u: p
in-	ter-	jec-	ted
I n	t @r	dZ e k	t V d
in-	ter-	jec-	tion
I n	t @r	dZ e k	S V n
in-	ter-	jec-	tions
I n	t @r	dZ e k	S V n z
in-	ter-	ject
I n	t @r	dZ e k t
in-	ter-	jects
I n	t @r	dZ e k t s
in-	ter-	lace
I n	t @r	l eI s
in-	ter-	laced
I n	t @r	l eI s t
in-	ter-	lake
I n	t @r	l eI k
in-	ter-	lea-	ving
I n	t @r	l i:	v I N
in-	ter-	leaf
I n	t @r	l i: f
in-	ter-	leave
I n	t @r	l i: v
in-	ter-	leu-	kin
I n	t @r	l u:	k V n
in-	ter-	link
I n	t @r	l I N k
in-	ter-	linked
I n	t @r	l I N k t
in-	ter-	lo-	cu-	tor
I n	t @r	l Q k	j V	t @r
in-	ter-	lo-	cu-	tors
I n	t @r	l Q k	j V	t @r z
in-	ter-	lo-	per
I n	t @r	l @U	p @r
in-	ter-	lo-	pers
I n	t @r	l @U	p @r z
in-	ter-	loc-	king
I n	t @r	l Q	k I N
in-	ter-	lock
I n	t @r	l Q k
in-	ter-	locked
I n	t @r	l Q k d
in-	ter-	lude
I n	t @r	l u: d
in-	ter-	ludes
I n	t @r	l u: d z
in-	ter-	mar-	riage
I n	t @r	m e@	I dZ
in-	ter-	mar-	ried
I n	t @r	m {	r i: d
in-	ter-	mar-	ry
I n	t @r	m {	r i:
in-	ter-	me-	di-	a
I n	t @r	m i:	d i:	V
in-	ter-	me-	di-	a-	ries
I n	t @r	m i:	d i:	e@	i: z
in-	ter-	me-	di-	a-	ry
I n	t @r	m i:	d i:	e@	i:
in-	ter-	me-	di-	ate
I n	t @r	m i:	d i:	V t
in-	ter-	me-	di-	ates
I n	t @r	m i:	d i:	V t s
in-	ter-	met
I n	t @r	m e t
in-	ter-	mi-	na-	ble
I n	t @r	m V	n V	b V l
in-	ter-	mi-	nab-	ly
I n	t @r	m V	n V b	l i:
in-	ter-	min-	g-	ling
I n	t @r	m I N	g V	l I N
in-	ter-	min-	gle
I n	t @r	m I N	g V l
in-	ter-	min-	gled
I n	t @r	m I N	g V l d
in-	ter-	mis-	sion
I n	t @r	m I	S V n
in-	ter-	mis-	sions
I n	t @r	m I	S V n z
in-	ter-	mit-	tent
I n	t @r	m I	t V n t
in-	ter-	mit-	tent-	ly
I n	t @r	m I	t V n	t l i:
in-	ter-	mix
I n	t @r	m I k s
in-	ter-	mix-	ing
I n	t @r	m I k	s I N
in-	ter-	mixed
I n	t @r	m I k s t
in-	ter-	mo-	dal
I n	t @r	m @U	d V l
in-	ter-	mo-	le-	cu-	lar
I n	t @r	m V	l e k	j V	l @r
in-	ter-	moun-	tain
I n	t @r	m aU n	t V n
in-	ter-	na-	lize
I n	t @r	n V	l aI z
in-	ter-	na-	lized
I n	t @r	n V	l aI z d
in-	ter-	na-	tio-	na-	le
I n	t @r	n {	S V	n Q	l i:
in-	ter-	na-	tio-	na-	li-	sm
I n	t @r	n {	S V	n V	l I	z V m
in-	ter-	na-	tio-	na-	li-	za-	tion
I n	t @r	n {	S V	n V	l V	z eI	S V n
in-	ter-	na-	tio-	na-	list
I n	t @r	n {	S V	n V	l V s t
in-	ter-	na-	tio-	na-	lists
I n	t @r	n {	S V	n V	l V s t s
in-	ter-	na-	tio-	na-	lize
I n	t @r	n {	S V	n V	l aI z
in-	ter-	na-	tio-	na-	lized
I n	t @r	n {	S V	n V	l aI z d
in-	ter-	na-	tio-	nal
I n	t @r	n {	S V	n V l
in-	ter-	na-	tio-	nal-	ly
I n	t @r	n {	S V	n V	l i:
in-	ter-	na-	tio-	nals
I n	t @r	n {	S V	n V l z
in-	ter-	na-	tio-	nal's
I n	t @r	n {	S V	n V l z
in-	ter-	nal
I n	t @r	n V l
in-	ter-	nal-	ly
I n	t @r	n V	l i:
in-	ter-	ne-	cine
I n	t @r	n V	s i: n
in-	ter-	nee
I n	t @r	n i:
in-	ter-	nees
I n	t @r	n i: z
in-	ter-	net
I n	t @r	n e t
in-	ter-	net's
I n	t @r	n e t s
in-	ter-	nist
I n	t @r	n V s t
in-	ter-	nists
I n	t @r	n V s t s
in-	ter-	per-	so-	nal
I n	t @r	p @r	s V	n V l
in-	ter-	pla-	ne-	ta-	ry
I n	t @r p	l {	n V	t e@	i:
in-	ter-	play
I n	t @r p	l eI
in-	ter-	po-	la-	ted
I	t @r	p V	l eI	t V d
in-	ter-	po-	late
I	t @r	p V	l eI t
in-	ter-	pol
I n	t @r	p @U l
in-	ter-	pose
I n	t @r	p @U z
in-	ter-	ra-	cial
I n	t @r	r eI	S V l
in-	ter-	re-	la-	ted
I n	t @r	r V	l eI	t V d
in-	ter-	re-	la-	tion-	ship
I n	t @r	r i:	l eI	S V n	S I p
in-	ter-	re-	late
I n	t @r	r V	l eI t
in-	ter-	reg-	num
I n	t @r	r e g	n V m
in-	ter-	ro-	ga-	ted
I n	t e@	V	g eI	t V d
in-	ter-	ro-	ga-	ting
I n	t e@	V	g eI	t I N
in-	ter-	ro-	ga-	tion
I n	t e@	V	g eI	S V n
in-	ter-	ro-	ga-	tions
I n	t e@	V	g eI	S V n z
in-	ter-	ro-	ga-	to-	ries
I n	t e@	Q	g V	t O@	i: z
in-	ter-	ro-	ga-	to-	ry
I n	t e@	Q	g V	t O@	i:
in-	ter-	ro-	ga-	tor
I n	t e@	V	g eI	t @r
in-	ter-	ro-	ga-	tors
I n	t e@	V	g eI	t @r z
in-	ter-	ro-	gate
I n	t e@	V	g eI t
in-	ter-	rup-	ted
I n	t @r	V p	t V d
in-	ter-	rup-	ti-	ble
I n	t @r	r V p	t V	b V l
in-	ter-	rup-	ting
I n	t @r	V p	t I N
in-	ter-	rup-	tion
I n	t @r	V p	S V n
in-	ter-	rup-	tions
I n	t @r	V p	S V n z
in-	ter-	rupt
I n	t @r	V p t
in-	ter-	rupts
I n	t @r	V p t s
in-	ter-	scho-	las-	tic
I n	t @r s	k V	l { s	t I k
in-	ter-	sec-	ted
I n	t @r	s e k	t V d
in-	ter-	sec-	ting
I n	t @r	s e k	t I N
in-	ter-	sec-	tion
I n	t @r	s e k	S V n
in-	ter-	sec-	tions
I n	t @r	s e k	S V n z
in-	ter-	sect
I n	t @r	s e k t
in-	ter-	sects
I n	t @r	s e k t s
in-	ter-	seg-	ment
I n	t @r	s e g	m V n t
in-	ter-	sper-	ses
I n	t @r s	p @r	s V z
in-	ter-	sperse
I n	t @r s	p @r s
in-	ter-	spersed
I n	t @r s	p @r s t
in-	ter-	ti-	dal
I n	t @r	t aI	d V l
in-	ter-	ur-	ban
I n	t @r	@r	b V n
in-	ter-	val
I n	t @r	v V l
in-	ter-	vals
I n	t @r	v V l z
in-	ter-	ve-	ning
I n	t @r	v i:	n I N
in-	ter-	ve-	nor
I n	t @r	v i:	n @r
in-	ter-	ve-	nors
I n	t @r	v i:	n @r z
in-	ter-	ven-	tio-	ni-	sm
I n	t @r	v e n	tS V	n I	z V m
in-	ter-	ven-	tio-	nist
I n	t @r	v e n	S V	n V s t
in-	ter-	ven-	tio-	nists
I n	t @r	v e n	tS V	n V s t s
in-	ter-	ven-	tion
I n	t @r	v e n	tS V n
in-	ter-	ven-	tions
I n	t @r	v e n	tS V n z
in-	ter-	vene
I n	t @r	v i: n
in-	ter-	vened
I n	t @r	v i: n d
in-	ter-	venes
I n	t @r	v i: n z
in-	ter-	vie-	wee
I n	t @r v	j u:	i:
in-	ter-	vie-	wees
I n	t @r v	j u:	i: z
in-	ter-	vie-	wer
I n	t @r v	j u:	@r
in-	ter-	vie-	wers
I n	t @r v	j u:	@r z
in-	ter-	view
I n	t @r v	j u:
in-	ter-	view-	ing
I n	t @r v	j u:	I N
in-	ter-	viewed
I n	t @r v	j u: d
in-	ter-	views
I n	t @r v	j u: z
in-	ter-	wea-	ving
I n	t @r	w i:	v I N
in-	ter-	weave
I n	t @r	w i: v
in-	ter-	wo-	ven
I n	t @r	w @U	v V n
in-	term
I n	t @r m
in-	tern
I n	t @r n
in-	tern-	ment
I n	t @r n	m V n t
in-	tern-	ship
I n	t @r n	S I p
in-	tern-	ships
I n	t @r n	S I p s
in-	terned
I n	t @r n d
in-	terns
I n	t @r n z
in-	terp-	re-	ta-	tion
I n	t @r p	r V	t eI	S V n
in-	terp-	re-	ta-	tions
I n	t @r p	r V	t eI	S V n z
in-	terp-	re-	ted
I n	t @r p	r V	t V d
in-	terp-	re-	ter
I n	t @r p	r V	t @r
in-	terp-	re-	ters
I n	t @r p	r V	t @r z
in-	terp-	re-	ting
I n	t @r p	r e	t I N
in-	terp-	re-	tive
I n	t @r p	r V	t I v
in-	terp-	ret
I n	t @r p	r V t
in-	terp-	rets
I n	t @r p	r V t s
in-	terp-	ro-	vin-	cial
I n	t @r p	r V	v I n	S V l
in-	terred
I n	t @r d
in-	tert-	ri-	bal
I n	t @r t	r aI	b V l
in-	tert-	wi-	ning
I n	t @r t	w aI	n I N
in-	tert-	wine
I n	t @r t	w aI n
in-	tert-	wined
I n	t @r t	w aI n d
in-	tes-	ti-	nal
I n	t e s	t I	n V l
in-	tes-	tine
I n	t e s	t I n
in-	tes-	tines
I n	t e s	t I n z
in-	ti
I n	t i:
in-	ti-	fa-	da
I n	t I	f Q	d V
in-	ti-	ma-	cy
I n	t I	m V	s i:
in-	ti-	ma-	ted
I n	t I	m eI	t I d
in-	ti-	ma-	tion
I n	t I	m eI	S V n
in-	ti-	ma-	tions
I n	t I	m eI	S V n z
in-	ti-	mate
I n	t I	m V t
in-	ti-	mate-	ly
I n	t I	m V t	l i:
in-	ti-	mates
I n	t I	m V t s
in-	ti-	mi-	da-	ted
I n	t I	m I	d eI	t I d
in-	ti-	mi-	da-	ting
I n	t I	m I	d eI	t I N
in-	ti-	mi-	da-	tion
I n	t I	m I	d eI	S V n
in-	ti-	mi-	date
I n	t I	m I	d eI t
in-	ti-	mi-	dates
I n	t I	m I	d eI t s
in-	tis
I n	t I s
in-	to
I n	t u:
in-	to-	le-	ra-	ble
I n	t Q	l @r	V	b V l
in-	to-	le-	rab-	ly
I n	t Q	l @r	V b	l i:
in-	to-	le-	rance
I n	t Q	l @r	V n s
in-	to-	le-	rant
I n	t Q	l @r	V n t
in-	to-	na-	tion
I n	t V	n eI	S V n
in-	to-	ning
I n	t @U	n I N
in-	to-	xi-	ca-	ted
I n	t Q k	s I	k eI	t V d
in-	to-	xi-	ca-	ting
I n	t Q k	s I	k eI	t I N
in-	to-	xi-	ca-	tion
I n	t Q k	s I	k eI	S V n
in-	to-	xi-	cate
I n	t Q k	s I	k eI t
in-	tone
I n	t @U n
in-	toned
I n	t @U n d
in-	tones
I n	t @U n z
in-	tou-	rist
I n	t U@	I s t
in-	tu-	i-	tion
I n	t u:	I	S V n
in-	tu-	i-	tive
I n	t u:	I	t I v
in-	tu-	i-	tive-	ly
I n	t u:	I	t I v	l i:
in-	tu-	it
I n	t u:	I t
in-	va-	ded
I n	v eI	d V d
in-	va-	der
I n	v eI	d @r
in-	va-	ders
I n	v eI	d @r z
in-	va-	ding
I n	v eI	d I N
in-	va-	li-	da-	ted
I n	v {	l I	d eI	t I d
in-	va-	li-	da-	ting
I n	v {	l I	d eI	t I N
in-	va-	li-	da-	tion
I n	v {	l I	d eI	S V n
in-	va-	li-	date
I n	v {	l I	d eI t
in-	va-	lid
I n	v V	l V d
in-	va-	lids
I n	v V	l I d z
in-	va-	lua-	ble
I n	v { l	j V	b V l
in-	va-	ri-	ab-	ly
I n	v e@	i:	V b	l i:
in-	va-	ri-	ance
I n	v e@	i:	V n s
in-	va-	ri-	ant
I n	v e@	i:	V n t
in-	va-	sion
I n	v eI	Z V n
in-	va-	sions
I n	v eI	Z V n z
in-	va-	sive
I n	v eI	s I v
in-	vade
I n	v eI d
in-	vades
I n	v eI d z
in-	ve-	te-	rate
I n	v e	t @r	V t
in-	vec-	tive
I n	v e k	t I v
in-	ven-	ted
I n	v e n	t V d
in-	ven-	ting
I n	v e n	t I N
in-	ven-	tion
I n	v e n	S V n
in-	ven-	tions
I n	v e n	S V n z
in-	ven-	tive
I n	v e n	t I v
in-	ven-	tive-	ness
I n	v e n	t I v	n V s
in-	ven-	to-	ried
I n	v V n	t O@	i: d
in-	ven-	to-	ries
I n	v V n	t O@	i: z
in-	ven-	to-	ry
I n	v V n	t O@	i:
in-	ven-	to-	ry's
I n	v V n	t O@	i: z
in-	ven-	tor
I n	v e n	t @r
in-	ven-	tors
I n	v e n	t @r z
in-	vent
I n	v e n t
in-	vents
I n	v e n t s
in-	ver-	ness
I n	v @r	n e s
in-	ver-	sion
I n	v @r	Z V n
in-	ver-	teb-	rate
I n	v @r	t V b	r V t
in-	ver-	teb-	rates
I n	v @r	t V b	r V t s
in-	ver-	ted
I n	v @r	t V d
in-	verse
I n	v @r s
in-	verse-	ly
I n	v @r s	l i:
in-	vert
I n	v @r t
in-	ves-	ta-	ble
I n	v e s	t V	b V l
in-	ves-	ted
I n	v e s	t V d
in-	ves-	ti-	ga-	ted
I n	v e s	t I	g eI	t I d
in-	ves-	ti-	ga-	ting
I n	v e s	t I	g eI	t I N
in-	ves-	ti-	ga-	tio-	nal
I n	v e s	t I	g eI	S V	n V l
in-	ves-	ti-	ga-	tion
I n	v e s	t I	g eI	S V n
in-	ves-	ti-	ga-	tions
I n	v e s	t I	g eI	S V n z
in-	ves-	ti-	ga-	tive
I n	v e s	t I	g eI	t I v
in-	ves-	ti-	ga-	to-	ry
I n	v e s	t I	g V	t O@	i:
in-	ves-	ti-	ga-	tor
I n	v e s	t I	g eI	t @r
in-	ves-	ti-	ga-	tors
I n	v e s	t I	g eI	t @r z
in-	ves-	ti-	ga-	tor's
I n	v e s	t I	g eI	t @r z
in-	ves-	ti-	gate
I n	v e s	t I	g eI t
in-	ves-	ti-	gates
I n	v e s	t I	g eI t s
in-	ves-	ti-	ture
I n	v e s	t V	tS @r
in-	ves-	ting
I n	v e s	t I N
in-	ves-	tor
I n	v e s	t @r
in-	ves-	tors
I n	v e s	t @r z
in-	ves-	tor's
I n	v e s	t @r z
in-	vest
I n	v e s t
in-	vest-	ment
I n	v e s	t m V n t
in-	vest-	ments
I n	v e s	t m V n t s
in-	vest-	ment's
I n	v e s	t m V n t s
in-	vests
I n	v e s t s
in-	vi-	di-	ous
I n	v I	d i:	V s
in-	vi-	go-	ra-	ted
I n	v I	g @r	eI	t V d
in-	vi-	go-	ra-	ting
I n	v I	g @r	eI	t I N
in-	vi-	go-	rate
I n	v I	g @r	eI t
in-	vi-	o-	la-	ble
I n	v aI	V	l V	b V l
in-	vi-	o-	late
I n	v aI	V	l V t
in-	vi-	si-	bi-	li-	ty
I n	v I	z I	b I	l I	t i:
in-	vi-	si-	ble
I n	v I	z I	b V l
in-	vi-	si-	bles
I n	v I	z I	b V l z
in-	vi-	ta-	tio-	nal
I n	v I	t eI	S V	n V l
in-	vi-	ta-	tion
I n	v I	t eI	S V n
in-	vi-	ta-	tions
I n	v I	t eI	S V n z
in-	vi-	ted
I n	v aI	t V d
in-	vi-	ting
I n	v aI	t I N
in-	vin-	ci-	bi-	li-	ty
I n	v I n	s I	b I	l I	t i:
in-	vin-	ci-	ble
I n	v I n	s I	b V l
in-	vite
I n	v aI t
in-	vites
I n	v aI t s
in-	vo-	ca-	tion
I n	v V	k eI	S V n
in-	vo-	king
I n	v @U	k I N
in-	vo-	lun-	ta-	ri-	ly
I n	v Q	l V n	t @r	V	l i:
in-	vo-	lun-	ta-	ry
I n	v Q	l V n	t e@	i:
in-	voi-	ces
I n	v OI	s V z
in-	voi-	cing
I n	v OI	s I N
in-	voice
I n	v OI s
in-	voke
I n	v @U k
in-	voked
I n	v @U k t
in-	vokes
I n	v @U k s
in-	vol-	ving
I n	v Q l	v I N
in-	volve
I n	v Q l v
in-	volve-	ment
I n	v Q l	v m V n t
in-	volve-	ments
I n	v Q l	v m V n t s
in-	volved
I n	v Q l v d
in-	volves
I n	v Q l v z
in-	vul-	ne-	ra-	bi-	li-	ty
I n	v V l	n @r	V	b I	l V	t i:
in-	vul-	ne-	ra-	ble
I n	v V l	n @r	V	b V l
in-	ward
I n	w @r d
in-	ward-	ly
I n	w @r d	l i:
in-	wood
I n	w U d
in.
I n
inc
I N k
inc-	line
I n	k l aI n
inc-	lined
I n	k l aI n d
inc-	lines
I n	k l aI n z
inc-	lo-	sure
I n	k l @U	Z @r
inc-	lu-	ded
I n	k l u:	d V d
inc-	lu-	ding
I n	k l u:	d I N
inc-	lu-	sion
I n	k l u:	Z V n
inc-	lu-	sions
I n	k l u:	Z V n z
inc-	lu-	sive
I n	k l u:	s I v
inc-	lu-	sive-	ness
I n	k l u:	s I v	n V s
inc-	lude
I n	k l u: d
inc-	ludes
I n	k l u: d z
inc.
I N k
inch
I n tS
inched
I n tS t
inf-	ra-	red
I n	f r @r	e d
inf-	ra-	struc-	tu-	ral
I n	f r V s	t r V k	tS @r	V l
inf-	ra-	struc-	ture
I n	f r V s	t r V k	tS @r
inf-	ra-	struc-	tures
I n	f r V s	t r V k	tS @r z
ing
I N
ing-	lis
I N	g l I s
ing-	lo-	ri-	ous
I n	g l O@	i:	V s
ing-	mar
I N	m Q@
ing-	ra-	ti-	a-	ting
I N	g r eI	S i:	eI	t I N
ing-	ra-	ti-	ate
I N	g r eI	S i:	eI t
ing-	ram
I N	g r V m
ing-	re-	di-	ent
I N	g r i:	d i:	V n t
ing-	re-	di-	ents
I N	g r i:	d i:	V n t s
ing-	rid
I N	g r I d
ing-	rum
I N	g r V m
ing-	var
I N	v Q@
inge
I n dZ
ink
I N k
ink-	blot
I N	k b l Q t
ink-	jet
I N	k dZ e t
ink-	ling
I N	k l I N
inks
I N k s
inn
I n
inn-	kee-	per
I n	k i:	p @r
inn-	kee-	pers
I n	k i:	p @r z
inns
I n z
inn's
I n z
ins
I n z
ins-	cribe
I n	s k r aI b
ins-	cribed
I n	s k r aI b d
ins-	crip-	tion
I n	s k r I p	S V n
ins-	crip-	tions
I n	s k r I p	S V n z
ins-	cru-	ta-	ble
I n	s k r u:	t V	b V l
ins-	ko
I n	s k @U
ins-	pects
I n	s p e k t s
ins-	pi-	ra-	tio-	nal
I n	s p @r	eI	S V	n V l
ins-	pi-	ra-	tion
I n	s p @r	eI	S V n
ins-	pi-	ra-	tions
I n	s p @r	eI	S V n z
ins-	pi-	red
I n	s p aI	@r d
ins-	pi-	ring
I n	s p aI	r I N
ins-	pire
I n	s p aI r
ins-	pires
I n	s p aI r z
ins-	ta-	bi-	li-	ties
I n	s t V	b I	l V	t i: z
ins-	ta-	bi-	li-	ty
I n	s t V	b I	l V	t i:
ins-	tal-	la-	tion
I n	s t V	l eI	S V n
ins-	tal-	la-	tions
I n	s t V	l eI	S V n z
ins-	tal-	ler
I n	s t O:	l @r
ins-	tal-	lers
I n	s t O:	l @r z
ins-	tal-	ling
I n	s t O:	l I N
ins-	tall
I n	s t O: l
ins-	tall-	ment
I n	s t O: l	m V n t
ins-	tall-	ments
I n	s t O: l	m V n t s
ins-	talled
I n	s t O: l d
ins-	talls
I n	s t O: l z
ins-	tan-	ces
I n	s t V n	s V z
ins-	tan-	ta-	ne-	ous
I n	s t V n	t {	n i:	V s
ins-	tan-	ta-	ne-	ous-	ly
I n	s t V n	t {	n i:	V s	l i:
ins-	tance
I n	s t V n s
ins-	tant
I n	s t V n t
ins-	tant-	ly
I n	s t V n	t l i:
ins-	tead
I n	s t e d
ins-	ti-	ga-	ted
I n	s t I	g eI	t I d
ins-	ti-	ga-	ting
I n	s t I	g eI	t I N
ins-	ti-	ga-	tion
I n	s t I	g eI	S V n
ins-	ti-	ga-	tor
I n	s t I	g eI	t @r
ins-	ti-	ga-	tors
I n	s t I	g eI	t @r z
ins-	ti-	gate
I n	s t I	g eI t
ins-	ti-	tu-	ted
I n	s t I	t u:	t I d
ins-	ti-	tu-	ting
I n	s t I	t u:	t I N
ins-	ti-	tu-	tio-	na-	li-	za-	tion
I n	s t I	t u:	S V	n V	l I	z eI	S V n
ins-	ti-	tu-	tio-	na-	li-	zes
I n	s t I	t u:	S V	n V	l aI	z V z
ins-	ti-	tu-	tio-	na-	li-	zing
I n	s t I	t u:	S V	n V	l aI	z I N
ins-	ti-	tu-	tio-	na-	list
I n	s t I	t u:	S V	n V	l I s t
ins-	ti-	tu-	tio-	na-	lists
I n	s t I	t u:	S V	n V	l I s t s
ins-	ti-	tu-	tio-	na-	lize
I n	s t I	t u:	S V	n V	l aI z
ins-	ti-	tu-	tio-	na-	lized
I n	s t I	t u:	S V	n V	l aI z d
ins-	ti-	tu-	tio-	nal
I n	s t I	t u:	S V	n V l
ins-	ti-	tu-	tio-	nal-	ly
I n	s t I	t u:	S V	n V	l i:
ins-	ti-	tu-	tion
I n	s t I	t u:	S V n
ins-	ti-	tu-	tions
I n	s t I	t u:	S V n z
ins-	ti-	tu-	tion's
I n	s t I	t u:	S V n z
ins-	ti-	tute
I n	s t I	t u: t
ins-	ti-	tutes
I n	s t I	t u: t s
ins-	til-	ling
I n	s t I	l I N
ins-	till
I n	s t I l
ins-	tilled
I n	s t I l d
ins-	tills
I n	s t I l z
ins-	tinc-	tive
I n	s t I N	k t I v
ins-	tinc-	tive-	ly
I n	s t I N	k t I v	l i:
ins-	tinct
I n	s t I N k t
ins-	tincts
I n	s t I N k t s
inst-	ru-	men-	ta-	li-	ty
I n	s t r U	m e n	t {	l I	t i:
inst-	ru-	men-	ta-	list
I n	s t r U	m e n	t V	l I s t
)"
R"(inst-	ru-	men-	ta-	lists
I n	s t r U	m e n	t V	l I s t s
inst-	ru-	men-	ta-	tion
I n	s t r U	m e n	t eI	S V n
inst-	ru-	men-	tal
I n	s t r U	m e n	t V l
inst-	ru-	men-	tals
I n	s t r U	m e n	t V l z
inst-	ru-	ment
I n	s t r V	m V n t
inst-	ru-	ments
I n	s t r U	m V n t s
inst-	ru-	ment's
I n	s t r V	m V n t s
inst-	ruc-	ted
I n	s t r V k	t I d
inst-	ruc-	ting
I n	s t r V k	t I N
inst-	ruc-	tio-	nal
I n	s t r V k	S V	n V l
inst-	ruc-	tion
I n	s t r V k	S V n
inst-	ruc-	tions
I n	s t r V k	S V n z
inst-	ruc-	tive
I n	s t r V k	t I v
inst-	ruc-	tor
I n	s t r V k	t @r
inst-	ruc-	tors
I n	s t r V k	t @r z
inst-	ruct
I n	s t r V k t
inst-	ructs
I n	s t r V k t s
int-	ra
I n	t r V
int-	ra-	com-	pa-	ny
I n	t r V	k Q m	p V	n i:
int-	ra-	day
I n	t r V	d eI
int-	ra-	mar-	gi-	nal
I n	t r V	m Q@	dZ V	n V l
int-	ra-	mu-	ral
I n	t r V m	j U@	V l
int-	ra-	o-	cu-	lar
I n	t r V	@U k	j u:	l @r
int-	ra-	par-	ty
I n	t r V	p Q@	t i:
int-	ra-	u-	te-	rine
I n	t r V	j u:	t @r	V n
int-	ra-	ve-	nous
I n	t r V	v i:	n V s
int-	ra-	ve-	nous-	ly
I n	t r V	v i:	n V s	l i:
int-	rac-	ra-	ni-	al
I n	t r V k	r eI	n i:	V l
int-	rac-	ta-	ble
I n	t r { k	t V	b V l
int-	ran-	si-	gence
I n	t r { n	s I	dZ V n s
int-	ran-	si-	gent
I n	t r { n	s I	dZ e n t
int-	ras-	tate
I n	t r V s	t eI t
int-	re-	pid
I n	t r e	p I d
int-	ri-	ca-	cies
I n	t r I	k V	s i: z
int-	ri-	ca-	cy
I n	t r I	k V	s i:
int-	ri-	cate
I n	t r I	k e t
int-	ri-	cate-	ly
I n	t r I	k e t	l i:
int-	ri-	guing
I n	t r i:	g I N
int-	ri-	guing-	ly
I n	t r i:	g I N	l i:
int-	rigue
I n	t r i: g
int-	rigued
I n	t r i: g d
int-	rigues
I n	t r i: g z
int-	rin-	si-	cal-	ly
I n	t r I n	s I	k V	l i:
int-	rin-	sic
I n	t r I n	s I k
int-	ro
I n	t r @U
int-	ro-	du-	ces
I n	t r V	d u:	s V z
int-	ro-	du-	cing
I n	t r V	d u:	s I N
int-	ro-	duc-	tion
I n	t r V	d V k	S V n
int-	ro-	duc-	tions
I n	t r V	d V k	S V n z
int-	ro-	duc-	to-	ry
I n	t r V	d V k	t @r	i:
int-	ro-	duce
I n	t r V	d u: s
int-	ro-	duced
I n	t r V	d u: s t
int-	ro-	ver-	ted
I n	t r @U	v @r	t V d
int-	ro-	vert
I n	t r @U	v @r t
int-	ron
I n	t r V n
int-	ros
I n	t r @U z
int-	ros-	pec-	tion
I n	t r V s	p e k	S V n
int-	ros-	pec-	tive
I n	t r V s	p e k	t I v
int-	ros-	pect
I n	t r V s	p e k t
int-	ru-	ded
I n	t r u:	d V d
int-	ru-	der
I n	t r u:	d @r
int-	ru-	ders
I n	t r u:	d @r z
int-	ru-	ding
I n	t r u:	d I N
int-	ru-	sion
I n	t r u:	Z V n
int-	ru-	sions
I n	t r u:	Z V n z
int-	ru-	sive
I n	t r u:	s I v
int-	ru-	sive-	ness
I n	t r u:	s I v	n V s
int-	rude
I n	t r u: d
int-	rudes
I n	t r u: d z
inte-	res-	ted
I n	t r V s	t V d
inte-	res-	ting
I n	t r V s	t I N
inte-	rest
I n	t r V s t
inte-	rests
I n	t r V s t s
ip
I p
iq-	bal
I k	b V l
ir-	by
@r	b i:
ir-	kutsk
@r	k U t s k
ir-	ma
@r	m V
ir-	ma's
@r	m V z
ir-	ra-	di-	a-	ted
I@	eI	d i:	eI	t I d
ir-	ra-	di-	a-	tion
I@	eI	d i:	eI	S V n
ir-	ra-	di-	ate
I@	eI	d i:	eI t
ir-	ra-	tio-	na-	li-	ty
I@	{	S V	n {	l I	t i:
ir-	ra-	tio-	nal
I@	{	S V	n V l
ir-	ra-	tio-	nal-	ly
I@	{	S V	n V	l i:
ir-	re-	con-	ci-	la-	ble
I@	e	k V n	s aI	l V	b V l
ir-	re-	den-	ti-	sm
I@	V	d e n	t I	z V m
ir-	re-	fu-	ta-	ble
I@	V f	j u:	t V	b V l
ir-	re-	gard-	less
I@	V	g Q d	l V s
ir-	re-	gu-	la-	ri-	ties
I@	e g	j V	l e@	V	t i: z
ir-	re-	gu-	la-	ri-	ty
I@	e g	j V	l e@	V	t i:
ir-	re-	gu-	lar
I@	e g	j V	l @r
ir-	re-	gu-	lar-	ly
I@	e g	j V	l @r	l i:
ir-	re-	gu-	lars
I@	e g	j V	l @r z
ir-	re-	le-	van-	cy
I@	e	l V	v V n	s i:
ir-	re-	le-	vance
I@	e	l V	v V n s
ir-	re-	le-	vant
I@	e	l V	v V n t
ir-	re-	me-	di-	a-	ble
I@	V	m i:	d i:	V	b V l
ir-	re-	pa-	ra-	ble
I@	e	p @r	V	b V l
ir-	re-	pa-	rab-	ly
I@	e	p @r	V b	l i:
ir-	re-	pla-	cea-	ble
I@	V p	l eI	s V	b V l
ir-	re-	pres-	si-	ble
I@	V p	r e	s V	b V l
ir-	re-	sis-	ti-	ble
I@	V	z I s	t V	b V l
ir-	re-	sis-	tib-	ly
I@	V	z I s	t V b	l i:
ir-	re-	spec-	tive
I@	V s	p e k	t I v
ir-	re-	ve-	rence
I@	e	v @r	V n s
ir-	re-	ve-	rent
I@	e	v @r	V n t
ir-	re-	ver-	si-	ble
I@	I	v @r	s I	b V l
ir-	re-	ver-	sib-	ly
I@	I	v @r	s I b	l i:
ir-	re-	vo-	ca-	ble
I@	e	v V	k V	b V l
ir-	re-	vo-	cab-	ly
I@	e	v V	k V b	l i:
ir-	res-	pon-	si-	bi-	li-	ty
I@	V s	p Q n	s V	b I	l V	t i:
ir-	res-	pon-	si-	ble
I@	V s	p Q n	s V	b V l
ir-	res-	pon-	sib-	ly
I@	V s	p Q n	s V b	l i:
ir-	ret-	rie-	vab-	ly
I@	V t	r i:	v V b	l i:
ir-	ri-	ga-	ted
I@	I	g eI	t I d
ir-	ri-	ga-	tion
I@	I	g eI	S V n
ir-	ri-	ga-	tor
I@	I	g eI	t @r
ir-	ri-	ga-	tors
I@	I	g eI	t @r z
ir-	ri-	gate
I@	I	g eI t
ir-	ri-	ta-	bi-	li-	ty
I@	I	t V	b I	l I	t i:
ir-	ri-	ta-	ble
I@	I	t V	b V l
ir-	ri-	ta-	ted
I@	I	t eI	t I d
ir-	ri-	ta-	ting
I@	I	t eI	t I N
ir-	ri-	ta-	tion
I@	I	t eI	S V n
ir-	ri-	ta-	tions
I@	I	t eI	S V n z
ir-	ri-	tant
I@	I	t V n t
ir-	ri-	tants
I@	I	t V n t s
ir-	ri-	tate
I@	I	t eI t
ir-	ri-	tates
I@	I	t eI t s
ir-	vin
@r	v I n
ir-	vine
@r	v aI n
ir-	ving
@r	v I N
ir-	ving's
@r	v I N z
ir-	win
@r	w I n
ire
aI r
ire-	land's
aI r	l V n d z
irk
@r k
irk-	some
@r k	s V m
irked
@r k t
irks
@r k s
iron-	ton
aI r	n t V n
irv
@r v
is
I z
i's
aI z
is-	ca-	ri-	ot
I s	k e@	i:	V t
is-	che-	mi-	a
I s	k e	m i:	V
is-	la-	ma-	bad
I s	l {	m V	b { d
is-	la-	ma-	bad's
I s	l {	m V	b { d z
is-	la-	mi-	za-	tion
I z	l Q	m I	z eI	S V n
is-	la-	mic
I z	l Q	m I k
is-	la-	mist
I s	l V	m V s t
is-	la-	mists
I s	l V	m V s t s
is-	lam
I s	l Q m
is-	lam's
I s	l Q m z
is-	lan-	der
aI	l V n	d @r
is-	lan-	ders
aI	l V n	d @r z
is-	lan-	di-	a
aI	l { n	d i:	V
is-	land
aI	l V n d
is-	lands
aI	l V n d z
is-	land's
aI	l V n d z
is-	las
aI	l V z
is-	leen
aI	l i: n
is-	lets
aI	l V t s
is-	lip
aI s	l I p
is-	mael
I s	m eI l
is-	mail
I s	m eI l
is-	ra-	el
I z	r i:	V l
is-	rae-	li
I z	r eI	l i:
is-	rae-	lis
I z	r eI	l i: z
is-	rae-	li's
I z	r eI	l i: z
is-	rae-	lite
I z	r V	l aI t
is-	rae-	lites
I z	r V	l aI t s
is-	rael's
I z	r eI l z
is-	sac
I	s V k
is-	sie
I	s i:
is-	su-	a-	ble
I	S u:	V	b V l
is-	su-	an-	ces
I	S u:	V n	s V z
is-	su-	ance
I	S u:	V n s
is-	su-	er
I	S u:	@r
is-	su-	ers
I	S u:	@r z
is-	su-	er's
I	S u:	@r z
is-	su-	ing
I	S u:	I N
is-	sue
I	S u:
is-	sue-	less
I	S u:	l V s
is-	sued
I	S u: d
is-	sues
I	S u: z
is-	sue's
I	S u: z
is-	sy
I	s i:
is-	tan-	bul
I s	t Q n	b u: l
isch
I S
ise
aI z
ish
I S
ish-	mael
I S	m i: l
ish-	tar
I S	t Q@
isle
aI l
isles
aI l z
isth-	mus
I s	m V s
it
I t
it-	ches
I	tS V z
it-	ching
I	tS I N
it-	chy
I	tS i:
it-	self
V t	s e l f
it-	sy
I t	s i:
it-	zhak
I t	s Q k
itch
I tS
its
I t s
it's
I t s
i've
aI v
ives
aI v z
iz-	ves-	ti-	a
I z	v e s	t i:	V
iz-	zard
I	z @r d
iz-	zy
I	z i:
iz-	zy's
I	z i: z
j
dZ eI
j-	r
dZ u: n	j @r
j.
dZ eI
ja
j Q
ja-	cin-	da
dZ V	s I n	d V
ja-	cin-	ta
dZ V	s I n	t V
ja-	cin-	tha
dZ V	s I n	T V
ja-	cin-	to
dZ V	s I n	t @U
ja-	cinth
dZ {	s I n T
ja-	cinthe
dZ {	s I n T
ja-	co
j Q	k @U
ja-	co-	ba
j Q	k @U	b V
ja-	co-	be-	an
dZ {	k V	b i:	V n
ja-	co-	bi
j Q	k @U	b i:
ja-	co-	bi-	na
j V	k V	b aI	n V
ja-	co-	bin
dZ {	k V	b V n
ja-	co-	bine
dZ {	k V	b aI n
ja-	co-	bite
dZ {	k V	b aI t
ja-	co-	bites
dZ {	k V	b aI t s
ja-	co-	bo
j Q	k @U	b @U
ja-	co-	bus
dZ V	k @U	b V s
ja-	co-	by
dZ V	k @U	b i:
ja-	cob
dZ eI	k V b
ja-	cob-	sen
dZ eI	k V b	s V n
ja-	cob-	son
dZ eI	k V b	s V n
ja-	cob-	son's
dZ eI	k V b	s V n z
ja-	cobs
dZ eI	k V b z
ja-	cob's
dZ eI	k V b z
ja-	cuz-	zi
dZ V k	j u:	z i:
ja-	ded
dZ eI	d V d
ja-	deite
dZ eI	d aI t
ja-	ger
dZ eI	g @r
ja-	giel-	lo
dZ Q	dZ e	l @U
ja-	go
j Q	g @U
ja-	guar
dZ { g	w Q@
ja-	guars
dZ { g	w Q@ z
ja-	guar's
dZ { g	w Q@ z
ja-	kar-	ta
dZ V	k Q@	t V
ja-	kar-	ta's
dZ V	k Q@	t V z
ja-	kie
dZ {	k i:
ja-	kob
dZ {	k V b
ja-	la-	la-	bad
dZ V	l {	l V	b { d
ja-	la-	pe-	no
h {	l V	p i: n	j @U
ja-	lo-	py
dZ V	l Q	p i:
ja-	ma
dZ {	m V
ja-	mai-	ca
dZ V	m eI	k V
ja-	mai-	can
dZ V	m eI	k V n
ja-	mai-	cans
dZ V	m eI	k V n z
ja-	mai-	ca's
dZ V	m eI	k V z
ja-	mal
dZ V	m Q l
ja-	mal's
dZ V	m Q l z
ja-	mar
j Q	m Q@
ja-	mi
dZ eI	m i:
ja-	mi-	la
dZ V	m I	l V
ja-	mi-	son
dZ eI	m V	s V n
ja-	mie
dZ eI	m i:
ja-	mie-	son
dZ eI	m I	s V n
ja-	mie's
dZ eI	m i: z
ja-	na
dZ {	n V
ja-	na-	cek
j {	n V	tS e k
ja-	na-	ta
dZ V	n Q	t V
ja-	nei-	ro
dZ V	n e@	@U
ja-	nek
j {	n e k
ja-	nel
dZ {	n V l
ja-	nel-	la
dZ V	n e	l V
ja-	nelle
Z V	n e l
ja-	net
dZ {	n e t
ja-	net's
dZ {	n e t s
ja-	nette
dZ V	n e t
ja-	ney
dZ eI	n i:
ja-	ni-	na
dZ V	n i:	n V
ja-	ni-	to-	ri-	al
dZ {	n I	t O@	i:	V l
ja-	ni-	tor
dZ {	n I	t @r
ja-	ni-	tors
dZ {	n I	t @r z
ja-	nic-	ki
dZ V	n I	k i:
ja-	nice
dZ {	n I s
ja-	nie
dZ eI	n i:
ja-	nik
j {	n I k
ja-	nine
dZ V	n i: n
ja-	nis
dZ {	n I s
ja-	no-	witz
j {	n V	w I t s
ja-	nos
dZ {	n @U s
ja-	nu-	a-	ry
dZ { n	j u:	e@	i:
ja-	nu-	a-	ry's
dZ { n	j u:	e@	i: z
ja-	nus
dZ eI	n V s
ja-	pa-	nese
dZ {	p V	n i: z
ja-	pan
dZ V	p { n
ja-	pans
dZ V	p { n z
ja-	pan's
dZ V	p { n z
ja-	po-	ni-	ca
dZ V	p Q	n V	k V
ja-	quith
dZ { k	w I T
ja-	ra
dZ Q@	V
ja-	red
dZ e@	V d
ja-	ru-	zel-	ski
dZ e@	V	z e l	s k i:
ja-	son
dZ eI	s V n
ja-	son's
dZ eI	s V n z
ja-	va
dZ Q	v V
ja-	va-	nese
dZ Q	v V	n i: z
ja-	van
dZ V	v Q n
ja-	ve-	lin
dZ {	v V	l I n
ja-	vi-	er
h Q	v i:	e@
jaan
j Q n
jab
dZ { b
jab-	bing
dZ {	b I N
jab-	lon
dZ { b	l V n
jab-	lon-	sky
j V b	l Q n	s k i:
jabbed
dZ { b d
jabs
dZ { b z
jac
dZ { k
jac-	kal
dZ {	k V l
jac-	kass
dZ {	k { s
jac-	ke-	lyn
dZ {	k V	l I n
jac-	ke-	ted
dZ {	k V	t V d
jac-	ket
dZ {	k V t
jac-	kets
dZ {	k V t s
jac-	ki
dZ {	k i:
jac-	kie
dZ {	k i:
jac-	kie's
dZ {	k i: z
jac-	king
dZ {	k I N
jac-	ki's
dZ {	k i: z
jac-	ko
dZ {	k @U
jac-	ky
dZ {	k i:
jac-	ky's
dZ {	k i: z
jac-	lyn
dZ { k	l I n
jac-	que-	line
dZ { k	w V	l I n
jac-	que-	lyn
dZ { k	w V	l I n
jac-	quet
j Q	k eI t
jac-	quet-	ta
dZ Q	k e	t V
jac-	quie
dZ { k	w i:
jack
dZ { k
jack-	ham-	mer
dZ { k	h {	m @r
jack-	ham-	mers
dZ { k	h {	m @r z
jack-	lin
dZ { k	l I n
jack-	man
dZ { k	m V n
jack-	pot
dZ { k	p Q t
jack-	pots
dZ { k	p Q t s
jack-	rab-	bit
dZ { k	r {	b I t
jack-	so-	ni-	an
dZ { k	s @U	n i:	V n
jack-	so-	ni-	ans
dZ { k	s @U	n i:	V n z
jack-	son
dZ { k	s V n
jack-	son-	ville
dZ { k	s V n	v I l
jack-	son-	ville's
dZ { k	s V n	v I l z
jack-	sons
dZ { k	s V n z
jack-	son's
dZ { k	s V n z
jacked
dZ { k t
jacks
dZ { k s
jack's
dZ { k s
jacque
Z eI k
jacques
Z Q k
jad-	win
dZ { d	w I n
jade
dZ eI d
jades
dZ eI d z
jae
dZ eI
jae-	ger
j e	g @r
jae-	gers
j e	g @r z
jae-	nicke
j e	n I k
jae's
dZ eI z
jaf-	fa
dZ {	f V
jaf-	fe
dZ {	f i:
jaff-	na
dZ { f	n V
jaff-	rey
dZ { f	r i:
jag-	ger
dZ {	g @r
jag-	gers
dZ {	g @r z
jag-	ger's
dZ {	g @r z
jagged
dZ { g d
jags
dZ { g z
jahn
dZ { n
jai
dZ aI
jai-	ler
dZ eI	l @r
jai-	lers
dZ eI	l @r z
jai-	ling
dZ eI	l I N
jai-	me
h aI	m i:
jai-	me's
h aI	m i: z
jai-	mie
dZ eI	m i:
jai-	ni-	sm
dZ eI	n I	z V m
jail
dZ eI l
jail-	house
dZ eI l	h aU s
jailed
dZ eI l d
jails
dZ eI l z
jail's
dZ eI l z
jain
dZ aI n
jake
dZ eI k
jakes
dZ eI k s
jake's
dZ eI k s
jal-	bert
dZ { l	b @r t
jam
dZ { m
jam-	mer
dZ {	m @r
jam-	mers
dZ {	m @r z
jam-	ming
dZ {	m I N
jam-	mu
dZ V	m u:
jam-	mu's
dZ V	m u: z
jam-	shed-	pur
dZ { m	S e d	p @r
jamb
dZ { m
jame-	son
dZ eI m	s V n
jame-	s's
dZ eI m	z V z
james
dZ eI m z
james-	town
dZ eI m	z t aU n
jammed
dZ { m d
jams
dZ { m z
jam's
dZ { m z
jan
dZ { n
jan-	gle
dZ { N	g V l
jan-	gled
dZ { N	g V l d
jan-	ka
dZ { N	k V
jan-	na
dZ {	n V
jan-	nock
dZ {	n V k
jan-	se-	ni-	sm
dZ { n	s V	n I	z V m
jan-	se-	nist
dZ { n	s V	n V s t
jan-	se-	nists
dZ { n	s V	n V s t s
jan-	sen
dZ { n	s V n
jan-	son
dZ { n	s V n
jan-	thi-	na
j Q n	T i:	n V
jan.
dZ { n
jane
dZ eI n
janes
dZ eI n z
jane's
dZ eI n z
janes-	ville
dZ eI n	z v I l
jank
dZ { N k
jann
dZ { n
jan's
dZ { n z
jans-	ky
j { n	s k i:
jans-	sen
dZ { n	s V n
jans-	son
dZ { n	s V n
jap
dZ { p
japs
dZ { p s
jaques
dZ { k s
jar
dZ Q@
jar-	din
dZ Q@	d I n
jar-	gon
dZ Q@	g V n
jar-	man
dZ Q@	m V n
jar-	na-	gin
dZ Q@	n V	dZ I n
jar-	ratt
dZ {	r V t
jar-	reau
Z @r	@U
jar-	rell
j Q@	eI l
jar-	rett
dZ e@	V t
jar-	ring
dZ Q@	I N
jar-	vi
dZ Q@	v i:
jar-	vi-	s's
dZ Q@	v I	s V z
jar-	vie
dZ Q@	v i:
jar-	vik
dZ Q@	v I k
jar-	vis
dZ Q@	v I s
jares
Z e@ z
jarred
dZ Q@ d
jars
dZ Q@ z
jas
dZ eI m z
jas-	mi-	na
j V s	m aI	n V
jas-	min
dZ { z	m I n
jas-	mine
dZ { z	m I n
jas-	per
dZ { s	p @r
jas-	pers
dZ { s	p @r z
jas-	per's
dZ { s	p @r z
jass
dZ { s
jauch
dZ O: tS
jaun-	dice
dZ O: n	d I s
jaun-	diced
dZ O: n	d I s t
jaun-	ti-	ly
dZ O: n	t I	l i:
jaun-	ty
dZ O: n	t i:
jaunt
dZ O: n t
jaunts
dZ O: n t s
jaw
dZ O:
jaw-	bo-	ning
dZ O:	b @U	n I N
jaw-	bone
dZ O:	b @U n
jawed
dZ O: d
jay
dZ eI
je-	ho-	vah
dZ V	h @U	v V
je-	ho-	vah's
dZ V	h @U	v V z
je-	kyll
dZ e	k V l
je-	mi-	ma
dZ e	m i:	m V
je-	mi-	son
dZ e	m I	s V n
je-	mie
dZ e	m i:
je-	na
dZ i:	n V
je-	ni-	son
dZ e	n I	s V n
je-	nin
dZ e	n I n
je-	rald
dZ e@	V l d
je-	re
dZ e@	i:
je-	re-	mi-	ah
dZ e@	V	m aI	V
je-	re-	my
dZ e@	V	m i:
je-	reld
dZ e@	V l d
je-	rez
j e@	e z
je-	ri
dZ e@	i:
je-	ri-	cho
dZ e@	I	k @U
je-	ro-	bo-	am
dZ e@	V	b @U	V m
je-	rold
dZ e@	@U l d
je-	rome
dZ @r	@U m
je-	ru-	sa-	lem
dZ @r	u:	s V	l V m
je-	ru-	sa-	lem's
dZ @r	u:	s V	l V m z
je-	su-	it
dZ e	Z u:	I t
je-	su-	its
dZ e	Z u:	I t s
je-	sup
dZ e	s V p
je-	sus
dZ i:	z V s
je-	we-	ler
dZ u:	V	l @r
je-	we-	lers
dZ u:	V	l @r z
je-	wel
dZ u:	V l
je-	wel-	lers
dZ u:	V	l @r z
je-	wel-	ry
dZ u:	V l	r i:
je-	well
dZ u:	e l
je-	wels
dZ u:	V l z
je-	wess
dZ u:	V s
je-	wett
dZ u:	e t
je-	wish
dZ u:	I S
je-	wish-	ness
dZ u:	I S	n V s
jea-	lou-	sy
dZ e	l V	s i:
jea-	na
dZ i:	n V
jea-	nette
dZ V	n e t
jea-	nie
dZ i:	n i:
jea-	nine
dZ V	n i: n
jean
dZ i: n
jean-	nette
dZ V	n e t
jean-	nie
dZ i:	n i:
jeane
dZ i: n
jeane-	rette
dZ i: n	r e t
jeanne
dZ i: n
jeans
dZ i: n z
jean's
dZ i: n z
jeb
dZ e b
jed
dZ e d
jed-	lic-	ka
j V d	l I s	k V
jee
dZ i:
jee-	ring
dZ i:	r I N
jeep
dZ i: p
jeep-	ney
dZ i: p	n i:
jeeps
dZ i: p s
jeep's
dZ i: p s
jeer
dZ I@
jeered
dZ I@ d
jeers
dZ i: r z
jeez
dZ i: z
jef-	fe-	rey
dZ e	f @r	i:
jef-	fe-	ry
dZ e	f @r	i:
jef-	fer-	so-	ni-	an
dZ e	f @r	s @U	n i:	V n
jef-	fer-	so-	ni-	ans
dZ e	f @r	s @U	n i:	V n z
jef-	fer-	son
dZ e	f @r	s V n
jef-	fer-	son's
dZ e	f @r	s V n z
jef-	fers
dZ e	f @r z
jef-	fy
dZ e	f i:
jeff
dZ e f
jeff-	rey
dZ e f	r i:
jeff-	reys
dZ e f	r i: z
jeff-	rey's
dZ e f	r i: z
jeff-	ries
dZ e f	r i: z
jeff-	ry
dZ e f	r i:
jeffs
dZ e f s
jeff's
dZ e f s
jel-	lied
dZ e	l i: d
jel-	lies
dZ e	l i: z
jel-	lo
dZ e	l @U
jel-	lo's
dZ e	l @U z
jel-	ly
dZ e	l i:
jel-	ly-	fish
dZ e	l i:	f I S
jel-	ly's
dZ e	l i: z
jelks
dZ e l k s
jell
dZ e l
jell-	o
dZ e	l @U
jem
dZ e m
jem-	mie
dZ e	m i:
jem's
dZ e m z
jen
dZ e n
jen-	kin
dZ e N	k I n
jen-	kin-	son
dZ e N	k I n	s V n
jen-	kins
dZ e N	k I n z
jen-	ner
dZ e	n @r
jen-	ness
dZ e	n V s
jen-	nette
Z V	n e t
jen-	ni
dZ e	n i:
jen-	ni-	fer
dZ e	n I	f @r
jen-	ni-	fer's
dZ e	n I	f @r z
jen-	nie
dZ e	n i:
jen-	nings
dZ e	n I N z
jen-	ny
dZ e	n i:
jen-	ny's
dZ e	n i: z
jen-	sen
dZ e n	s V n
jen-	son
dZ e n	s V n
jenks
dZ e N k s
jenn
dZ e n
jenne
dZ e n
jenn's
dZ e n z
jens
dZ e n z
jeo-	par-	di-	zes
dZ e	p @r	d aI	z V z
jeo-	par-	di-	zing
dZ e	p @r	d aI	z I N
jeo-	par-	dize
dZ e	p @r	d aI z
jeo-	par-	dized
dZ e	p @r	d aI z d
jeo-	par-	dy
dZ e	p @r	d i:
jep-	son
dZ e p	s V n
jep-	son's
dZ e p	s V n z
jer-	bo-	as
dZ @r	b @U	V z
jer-	king
dZ @r	k I N
jer-	kins
dZ @r	k I n z
jer-	ky
dZ @r	k i:
jer-	maine
dZ @r	m eI n
jer-	man
dZ @r	m V n
jer-	myn
dZ @r	m I n
jer-	ri
dZ e@	i:
jer-	rie
dZ e@	i:
jer-	ro-	me
j e@	@U	m eI
jer-	rold
dZ e@	V l d
jer-	ry
dZ e@	i:
jer-	ry's
dZ e@	i: z
jer-	sey
dZ @r	z i:
jer-	seys
dZ @r	z i: z
jer-	sey's
dZ @r	z i: z
jer-	vis
dZ @r	v I s
jerk
dZ @r k
jerked
dZ @r k t
jerks
dZ @r k s
jes-	per-	sen
dZ e s	p @r	s V n
jes-	sa-	mine
dZ e	s V	m I n
jes-	sa-	myn
dZ e	s V	m I n
jes-	se
dZ e	s i:
jes-	see
dZ e	s i:
jes-	sen
dZ e	s V n
jes-	se's
dZ e	s i: z
jes-	si-	ca
dZ e	s I	k V
jes-	si-	ca's
dZ e	s I	k V z
jes-	sie
dZ e	s i:
jes-	sup
dZ e	s V p
jes-	sy
dZ e	s i:
jes-	ter
dZ e s	t @r
jess
dZ e s
jest
dZ e s t
jests
dZ e s t s
jet
dZ e t
jet-	li-	ner
dZ e t	l aI	n @r
jet-	li-	ners
dZ e t	l aI	n @r z
jet-	li-	ner's
dZ e t	l aI	n @r z
jet-	son
dZ e t	s V n
jet-	sons
dZ e t	s V n z
jet-	ted
dZ e	t V d
jet-	ter
dZ e	t @r
jet-	ti-	so-	ning
dZ e	t I	s V	n I N
jet-	ti-	son
dZ e	t I	s V n
jet-	ti-	soned
dZ e	t I	s V n d
jet-	ting
dZ e	t I N
jet-	ton
dZ e	t V n
jet-	ty
dZ e	t i:
jeth-	ro
dZ e T	r @U
jets
dZ e t s
jet's
dZ e t s
jets-	tream
dZ e t	s t r i: m
)"
R"(jets-	treams
dZ e t	s t r i: m z
jew
dZ u:
jew-	fi-	shes
dZ u:	f I	S V z
jew-	fish
dZ u:	f I S
jew-	ry
dZ u:	r i:
jews
dZ u: z
jews'
dZ u: z
jfet
dZ f e t
ji
dZ i:
ji-	had
dZ i:	h { d
ji-	ma
dZ i:	m V
ji-	me-	nez
h I	m e	n e z
ji-	ving
dZ aI	v I N
jib
dZ I b
jibe
dZ aI b
jibes
dZ aI b z
jif-	fy
dZ I	f i:
jig
dZ I g
jig-	g-	ling
dZ I	g V	l I N
jig-	gle
dZ I	g V l
jig-	saw
dZ I g	s O:
jigs
dZ I g z
jil-	li-	an
dZ I	l i:	V n
jil-	lion
dZ I l	j V n
jil-	lions
dZ I l	j V n z
jil-	ted
dZ I l	t V d
jill
dZ I l
jilt
dZ I l t
jim
dZ I m
jim-	mie
dZ I	m i:
jim-	mied
dZ I	m i: d
jim-	my
dZ I	m i:
jim-	my's
dZ I	m i: z
jim's
dZ I m z
jin
dZ I n
jin-	gle
dZ I N	g V l
jin-	gles
dZ I N	g V l z
jin-	go-	i-	sm
dZ I N	g @U	I	z V m
jin-	go-	is-	tic
dZ I N	g @U	I s	t I k
jing
dZ I N
jinks
dZ I N k s
jinx
dZ I N k s
jir-	ga
dZ @r	g V
jit-	ney
dZ I t	n i:
jit-	te-	ry
dZ I	t @r	i:
jit-	ter-	bug
dZ I	t @r	b V g
jit-	ter-	bug-	ging
dZ I	t @r	b V	g I N
jit-	ters
dZ I	t @r z
jive
dZ aI v
jo
dZ @U
jo-	a-	chim
j @U	Q	k I m
jo-	a-	chim's
j @U	Q	k I m z
jo-	an-	na
dZ @U	{	n V
jo-	ann
dZ @U	{ n
jo-	anne
dZ @U	{ n
jo-	bi-	na
j @U	b i:	n V
jo-	by-	na
j V	b i:	n V
jo-	chum
dZ Q	k V m
jo-	cu-	lar
dZ Q k	j V	l @r
jo-	di
dZ @U	d i:
jo-	die
dZ @U	d i:
jo-	doin
Z V	d OI n
jo-	dy
dZ @U	d i:
jo-	el
dZ @U	V l
jo-	elle
dZ @U	e l
jo-	el's
dZ @U	V l z
jo-	ette
Z @U	e t
jo-	ey
dZ @U	i:
jo-	ey's
dZ @U	i: z
jo-	han
j @U	h Q n
jo-	han-	na
dZ V	h {	n V
jo-	han-	nes
dZ @U	h {	n V s
jo-	han-	nes-	burg
dZ @U	h {	n V s	b @r g
jo-	han-	nes-	burg's
dZ @U	h {	n V s	b @r g z
jo-	han-	nes-	sen
dZ @U	h {	n V	s V n
jo-	han-	sen
dZ @U	h { n	s V n
jo-	han-	son
dZ @U	h { n	s V n
jo-	hann
j @U	h Q n
jo-	ker
dZ @U	k @r
jo-	kers
dZ @U	k @r z
jo-	king
dZ @U	k I N
jo-	king-	ly
dZ @U	k I N	l i:
jo-	lene
dZ @U	l i: n
jo-	let-	ta
dZ @U	l e	t V
jo-	li-	et
dZ @U	l i:	e t
jo-	ry
dZ O@	i:
jo-	se
h @U	z eI
jo-	se-	pha
dZ @U	s e	f V
jo-	se-	phi-	na
dZ Q	s V	f aI	n V
jo-	se-	phine
dZ @U	s V	f i: n
jo-	se-	phus
dZ @U	s i:	f V s
jo-	sef
dZ @U	s V f
jo-	seph
dZ @U	s V f
jo-	seph-	son
dZ @U	s V f	s V n
jo-	sephs
dZ @U	s V f s
jo-	seph's
dZ @U	z V f s
jo-	ser
dZ @U	z @r
jo-	ser's
dZ @U	z @r z
jo-	se's
h @U	z eI z
jo-	sey
dZ @U	z i:
jo-	shi
dZ @U	S i:
jo-	shu-	a
dZ Q	S u:	V
jo-	si-	ah
dZ @U	s aI	V
jo-	sie
dZ @U	z i:
jo-	st-	ling
dZ Q	s V	l I N
jo-	stle
dZ Q	s V l
jo-	stled
dZ Q	s V l d
jo-	va-	no-	vich
dZ @U	v {	n V	v I tS
jo-	vi
dZ @U	v i:
jo-	vi-	al
dZ @U	v i:	V l
jo-	vi-	an
dZ @U	v i:	V n
jo-	vi-	ta
j V	v aI	t V
jo-	wett
dZ aU	e t
jo-	yous
dZ OI	V s
jo-	zef
dZ @U	z V f
joa-	o
dZ @U	@U
joa-	quin
w Q	k i: n
joan
dZ @U n
job
dZ Q b
job-	ber
dZ Q	b @r
job-	bers
dZ Q	b @r z
job-	less
dZ Q b	l V s
job-	less-	ness
dZ Q b	l V s	n V s
job-	son
dZ Q b	s V n
jobe
dZ @U b
jobes
dZ @U b z
jobs
dZ Q b z
job's
dZ Q b z
joc-	key
dZ Q	k i:
joc-	key-	ing
dZ Q	k i:	I N
joc-	keys
dZ Q	k i: z
joce-	lin
dZ O: s	l I n
joce-	line
dZ O: s	l I n
joce-	lyn
dZ O: s	l I n
joce-	lyne
dZ O: s	l I n
jock
dZ Q k
jocks
dZ Q k s
joe
dZ @U
joerg
dZ O@ g
joes
dZ @U z
joe's
dZ @U z
jog
dZ Q g
jog-	ger
dZ Q	g @r
jog-	gers
dZ Q	g @r z
jog-	ging
dZ Q	g I N
jogged
dZ Q g d
jogs
dZ Q g z
joh
dZ @U
joh-	na-	thon
dZ Q	n V	T V n
joh-	na-	thon's
dZ Q	n V	T V n z
joh-	nie
dZ Q	n i:
joh-	nnie
dZ Q	n i:
joh-	nnie's
dZ Q	n i: z
joh-	ny
dZ Q	n i:
john
dZ Q n
john-	ny
dZ Q	n i:
john-	ny's
dZ Q	n i: z
john-	sen
dZ Q n	s V n
john-	sen's
dZ Q n	s V n z
john-	son
dZ Q n	s V n
john-	son's
dZ Q n	s V n z
johns
dZ Q n z
john's
dZ Q n z
johns-	ton
dZ Q n	s t V n
johns-	tone
dZ Q n	s t @U n
johns-	ton's
dZ Q n	s t V n z
johns-	town
dZ Q n	z t aU n
joi-	ne-	ry
dZ OI	n @r	i:
joi-	ner
dZ OI	n @r
joi-	ning
dZ OI	n I N
joice
dZ OI s
joie
Z w Q
join
dZ OI n
join-	ted
dZ OI n	t V d
joined
dZ OI n d
joins
dZ OI n z
joint
dZ OI n t
joint-	ly
dZ OI n	t l i:
joint-	ness
dZ OI n	t n V s
joints
dZ OI n t s
joist
dZ OI s t
joists
dZ OI s t s
joke
dZ @U k
joke-	book
dZ @U k	b U k
joked
dZ @U k t
jokes
dZ @U k s
jol-	la
h OI	j V
jol-	ley
dZ Q	l i:
jol-	lies
dZ Q	l i: z
jol-	ly
dZ Q	l i:
jol-	ly-	ing
dZ Q	l i:	I N
jol-	son
dZ @U l	s V n
joles
dZ @U l z
jolt
dZ @U l t
joost
dZ u: s t
jop-	lin
dZ Q p	l I n
jor-	da-	na
j O@	d {	n V
jor-	da-	ni-	an
dZ O@	d eI	n i:	V n
jor-	da-	ni-	ans
dZ O@	d eI	n i:	V n z
jor-	dan
dZ O@	d V n
jor-	dans
dZ O@	d V n z
jor-	dan's
dZ O@	d V n z
jor-	den
dZ O@	d V n
jor-	ge
h O@	h eI
jor-	gen-	sen
dZ O@	g V n	s V n
jor-	gen-	son
dZ O@	g V n	s V n
jos
dZ @U z
jos-	lyn
dZ O: s	l I n
jos-	se-	lyn
dZ Q	s V	l V n
josh
dZ Q S
joss
dZ O: s
jot
dZ Q t
jot-	ted
dZ Q	t V d
jou-	bert
j aU	b @r t
joule
dZ u: l
joules
dZ u: l z
jour
dZ aU r
jour-	dan
Z U@	d { n
jour-	n-	alis-	ti-	cal-	ly
dZ @r	n V	l I s	t I	k V	l i:
jour-	na-	lese
dZ @r	n V	l i: z
jour-	na-	li-	sm
dZ @r	n V	l I	z V m
jour-	na-	li-	sm's
dZ @r	n V	l I	z V m z
jour-	na-	lis-	tic
dZ @r	n V	l I s	t I k
jour-	na-	list
dZ @r	n V	l V s t
jour-	na-	lists
dZ @r	n V	l V s t s
jour-	na-	list's
dZ @r	n V	l V s t s
jour-	nal
dZ @r	n V l
jour-	nals
dZ @r	n V l z
jour-	nal's
dZ @r	n V l z
jour-	ney
dZ @r	n i:
jour-	ney-	ing
dZ @r	n i:	I N
jour-	ney-	man
dZ @r	n i:	m { n
jour-	ney-	man's
dZ @r	n i:	m V n z
jour-	neyed
dZ @r	n i: d
jour-	neys
dZ @r	n i: z
jous-	ting
dZ aU s	t I N
joust
dZ aU s t
jow-	ly
dZ aU	l i:
jowl
dZ aU l
jowls
dZ aU l z
joy
dZ OI
joy-	ce's
dZ OI	s V z
joy-	ful
dZ OI	f V l
joy-	ful-	ly
dZ OI	f V	l i:
joy-	ing
dZ OI	I N
joy-	ner
dZ OI	n @r
joy-	ri-	ding
dZ OI	r aI	d I N
joy-	ride
dZ OI	r aI d
joy-	stick
dZ OI s	t I k
joyce
dZ OI s
joye
dZ OI
joys
dZ OI z
joy's
dZ OI z
j's
dZ eI z
ju
dZ u:
ju-	ba
dZ u:	b V
ju-	bi-	la-	tion
dZ u:	b I	l eI	S V n
ju-	bi-	lant
dZ u:	b I	l V n t
ju-	bi-	lee
dZ u:	b I	l i:
ju-	da-	i-	sm
dZ u:	d eI	I	z V m
ju-	da-	i-	sm's
dZ u:	d eI	I	z V m z
ju-	dah
dZ u:	d V
ju-	das
dZ u:	d V s
ju-	de-	a
dZ u:	d i:	V
ju-	di-	cate
dZ u:	d I	k eI t
ju-	di-	ci-	a-	ry
dZ u:	d I	S i:	e@	i:
ju-	di-	cial
dZ u:	d I	S V l
ju-	di-	cial-	ly
dZ u:	d I	S V	l i:
ju-	di-	cious
dZ u:	d I	S V s
ju-	di-	cious-	ly
dZ u:	d I	S V s	l i:
ju-	di-	tha
dZ u:	d I	T V
ju-	dice
dZ u:	d I s
ju-	die
dZ V	d i:
ju-	dith
dZ u:	d I T
ju-	do
dZ u:	d @U
ju-	dy
dZ u:	d i:
ju-	dy's
dZ u:	d i: z
ju-	gu-	lar
dZ u: g	j V	l @r
ju-	i-	cier
dZ u:	I s	j @r
ju-	ji-	tsu
dZ u:	dZ I t	s u:
ju-	ju
dZ u:	dZ u:
ju-	lep
dZ u:	l V p
ju-	leps
dZ u:	l V p s
ju-	li
dZ u:	l i:
ju-	li-	a-	na
dZ u:	l i:	{	n V
ju-	li-	a-	no
dZ u:	l i:	Q	n @U
ju-	li-	an
dZ u:	l i:	V n
ju-	li-	ann
dZ u:	l i:	{ n
ju-	li-	anne
dZ u:	l i:	e n
ju-	li-	en
dZ u:	l i:	V n
ju-	li-	et
dZ u:	l i:	e t
ju-	li-	et-	ta
dZ u:	l i:	e	t V
ju-	li-	ette
dZ u:	l i:	e t
ju-	li-	na
j u:	l i:	n V
ju-	li-	o
dZ u:	l i:	@U
ju-	lia
dZ u: l	j V
ju-	lia's
dZ u: l	j V z
ju-	lie
dZ u:	l i:
ju-	lie-	ta
j u:	l i:	t V
ju-	lie's
dZ u:	l i: z
ju-	line
dZ u:	l aI n
ju-	lius
dZ u: l	j V s
ju-	ly
dZ u:	l aI
ju-	ly's
dZ u:	l aI z
ju-	neau
dZ u:	n @U
ju-	nette
dZ u:	n e t
ju-	ni-	a
j u:	n i:	V
ju-	ni-	a-	ta
j u:	n i:	Q	t V
ju-	ni-	per
dZ u:	n I	p @r
ju-	ni-	pers
dZ u:	n I	p @r z
ju-	ni-	us
dZ u:	n i:	V s
ju-	nior
dZ u: n	j @r
ju-	niors
dZ u: n	j @r z
ju-	nior's
dZ u: n	j @r z
ju-	no
dZ u:	n @U
ju-	no's
dZ u:	n @U z
ju-	not
dZ u:	n V t
ju-	pi-	ter
dZ u:	p I	t @r
ju-	pi-	ter's
dZ u:	p I	t @r z
ju-	ras
dZ U@	V z
ju-	ras-	sic
dZ U@	{	s I k
ju-	ries
dZ U@	i: z
ju-	ris
dZ U@	I s
ju-	ris-	dic-	tio-	nal
dZ U@	I s	d I k	S V	n V l
ju-	ris-	dic-	tion
dZ U@	I s	d I k	S V n
ju-	ris-	dic-	tions
dZ U@	I s	d I k	S V n z
ju-	ris-	pru-	den-	tial
dZ U@	I s	p r u:	d e n	S V l
ju-	ris-	pru-	dence
dZ U@	I s	p r u:	d V n s
ju-	rist
dZ U@	I s t
ju-	rists
dZ U@	I s t s
ju-	ror
dZ U@	@r
ju-	rors
dZ U@	@r z
ju-	ror's
dZ U@	@r z
ju-	ry
dZ U@	i:
ju-	ry's
dZ U@	i: z
ju-	ve-	nile
dZ u:	v V	n V l
ju-	ve-	niles
dZ u:	v V	n V l z
ju-	ve-	nile's
dZ u:	v V	n V l z
jua-	na
w Q	n V
jua-	ni-	ta
w Q	n i:	t V
jua-	rez
w Q@	e z
juan
w Q n
jud-	ges
dZ V	dZ V z
jud-	ge's
dZ V	dZ V z
jud-	ges'
dZ V	dZ V z
jud-	ging
dZ V	dZ I N
jud-	sen
dZ V d	s V n
jud-	son
dZ V d	s V n
judd
dZ V d
jude
dZ u: d
jude's
dZ u: d z
judg-	men-	tal
dZ V dZ	m e n	t V l
judg-	ment
dZ V dZ	m V n t
judg-	ments
dZ V dZ	m V n t s
judge
dZ V dZ
judge-	men-	tal
dZ V dZ	m e n	t V l
judge-	ment
dZ V dZ	m V n t
judge-	ments
dZ V dZ	m V n t s
judge-	ship
dZ V dZ	S I p
judge-	ships
dZ V dZ	S I p s
judged
dZ V dZ d
jug
dZ V g
jug-	g-	ler
dZ V	g V	l @r
jug-	g-	lers
dZ V	g V	l @r z
jug-	g-	ling
dZ V	g V	l I N
jug-	ger-	naut
dZ V	g @r	n O: t
jug-	gle
dZ V	g V l
jug-	gled
dZ V	g V l d
jug-	gles
dZ V	g V l z
jugs
dZ V g z
jui-	ces
dZ u:	s V z
jui-	ci-	est
dZ u:	s i:	V s t
jui-	cy
dZ u:	s i:
juice
dZ u: s
juil-	li-	ard
dZ u:	l i:	Q@ d
juke
dZ u: k
juke-	bo-	xes
dZ u: k	b Q k	s V z
juke-	box
dZ u: k	b Q k s
jukes
dZ u: k s
jul-	li-	ard
dZ u:	l i:	Q@ d
jule
dZ u: l
jules
dZ u: l z
jum-	ble
dZ V m	b V l
jum-	bled
dZ V m	b V l d
jum-	bo
dZ V m	b @U
jum-	bos
dZ V m	b @U z
jum-	per
dZ V m	p @r
jum-	pers
dZ V m	p @r z
jum-	ping
dZ V m	p I N
jum-	py
dZ V m	p i:
jump
dZ V m p
jump-	start
dZ V m	p s t Q@ t
jump-	suit
dZ V m	p s u: t
jumped
dZ V m p t
jumps
dZ V m p s
jun
dZ V n
jun-	co
dZ V N	k @U
jun-	ger
dZ V	N @r
jun-	gle
dZ V N	g V l
jun-	gles
dZ V N	g V l z
jun-	ji
dZ V n	dZ i:
jun-	ker
dZ V N	k @r
jun-	ket
dZ V N	k V t
jun-	kets
dZ V N	k V t s
jun-	ki-	er
dZ V N	k i:	@r
jun-	ki-	est
dZ V N	k i:	V s t
jun-	kie
dZ V N	k i:
jun-	kies
dZ V N	k i: z
jun-	king
dZ V N	k I N
jun-	ky
dZ V N	k i:
jun-	ta
h U n	t V
junc-	tion
dZ V N	k S V n
junc-	ture
dZ V N	k tS @r
junc-	tures
dZ V N	k tS @r z
june
dZ u: n
junes
dZ u: n z
june's
dZ u: n z
jung
j U N
jung's
j U N z
junk
dZ V N k
junk-	yard
dZ V N	k j Q@ d
junk-	yards
dZ V N	k j Q@ d z
junked
dZ V N k t
jur-	gen
dZ @r	g V n
jure
dZ U@
jus-	ta
dZ V s	t V
jus-	ten
dZ V s	t V n
jus-	ter
dZ V s	t @r
jus-	ti-	ces
dZ V s	t I	s V z
jus-	ti-	ce's
dZ V s	t I	s V z
jus-	ti-	fi-	a-	ble
dZ V s	t I	f aI	V	b V l
jus-	ti-	fi-	ab-	ly
dZ V s	t I	f aI	V b	l i:
jus-	ti-	fi-	ca-	tion
dZ V s	t I	f I	k eI	S V n
jus-	ti-	fi-	ca-	tions
dZ V s	t I	f I	k eI	S V n z
jus-	ti-	fied
dZ V s	t I	f aI d
jus-	ti-	fies
dZ V s	t I	f aI z
jus-	ti-	fy
dZ V s	t I	f aI
jus-	ti-	fy-	ing
dZ V s	t I	f aI	I N
jus-	ti-	na
j u: s	t i:	n V
jus-	ti-	no
dZ V s	t i:	n @U
jus-	tice
dZ V s	t I s
jus-	tin
dZ V s	t I n
jus-	tine
dZ V s	t i: n
jus-	tin's
dZ V s	t I n z
jus-	tis
j u: s	t I s
jus-	to
dZ V s	t @U
jus-	tus
dZ V s	t V s
just
dZ V s t
just-	ly
dZ V s	t l i:
jut
dZ V t
jut-	land
dZ V t	l V n d
jut-	ting
dZ V	t I N
jute
dZ u: t
juts
dZ V t s
juve
dZ u: v
jux-	ta-	po-	si-	tion
dZ V k	s t V	p V	z I	S V n
jux-	ta-	po-	si-	tions
dZ V k	s t V	p V	z I	S V n z
jux-	ta-	pose
dZ V k	s t V	p @U z
jux-	ta-	posed
dZ V k	s t V	p @U z d
jynx
dZ I N k s
k
kh eI
k-	cal
kh eI	k Q l
k-	k-	k
kh eI	k eI	k eI
k-	mart
kh eI	m Q@ t
k-	mart's
kh eI	m Q@ t s
k-	n-	i-	n
kh eI	e	n aI	e n
k-	nie-	vel
kh V	n i:	v V l
k-	vetch
kh V	v e tS
k.
kh eI
ka
kh Q
ka-	bel
kh {	b V l
ka-	boom
kh V	b u: m
ka-	bu-	ki
kh V	b u:	k i:
ka-	bul
kh Q	b U l
ka-	dar
kh {	d @r
ka-	den
kh eI	d V n
ka-	dish
kh eI	d I S
ka-	ga-	wa
kh V	g Q	w V
ka-	hu-	na
kh V	h u:	n V
ka-	lan
kh eI	l V n
ka-	lash-	ni-	kov
kh V	l { S	n I	k Q v
ka-	lei-	dos-	cope
kh V	l aI	d V s	k @U p
ka-	li-	kow
kh {	l I	k @U
ka-	li-	na
kh V	l aI	n V
ka-	li-	ning-	rad
kh V	l I	n I N	g r { d
ka-	lil
kh {	l I l
ka-	lin
kh {	l I n
ka-	lis
kh {	l I s
ka-	lisz
kh Q	l I S
ka-	lo
kh eI	l @U
ka-	ma
kh Q	m V
ka-	mal
kh eI	m V l
ka-	me-	ha-	me-	ha
kh V	m eI	V	m eI	V
ka-	me-	ha-	me-	ha's
kh V	m eI	V	m eI	V z
ka-	mi-	ka-	ze
kh Q	m I	k Q	z i:
ka-	min
kh {	m I n
ka-	na
kh {	n V
ka-	na-	wa
kh Q	n Q	w V
ka-	na-	za-	wa
kh Q	n Q	z Q	w V
ka-	nak
kh {	n V k
ka-	naw-	ha
kh V	n O:	h V
ka-	ni-	a
kh Q	n i:	V
ka-	no
kh Q	n @U
ka-	oh-	si-	ung
kh eI	@U	s i:	V N
ka-	po-	si
kh V	p @U	s i:
ka-	po-	si's
kh V	p @U	s i: z
ka-	poor
kh V	p u: r
ka-	por
kh eI	p @r
ka-	pur
kh {	p @r
ka-	ra
kh e@	V
ka-	ra-	chi
kh Q@	Q	tS i:
ka-	ra-	jan
kh e@	V	dZ V n
ka-	ra-	mi
kh @r	Q	m i:
ka-	ra-	o-	ke
kh e@	i:	@U	k i:
ka-	ra-	te
kh @r	Q	t i:
ka-	ras
kh Q@	V z
ka-	rat
kh e@	V t
ka-	re-	li-	an
kh @r	i:	l i:	V n
ka-	re-	ni-	na
kh e@	e	n i:	n V
ka-	reem
kh @r	i: m
ka-	reem's
kh @r	i: m z
ka-	rel
kh e@	V l
ka-	ren
kh e@	V n
ka-	ren's
kh e@	V n z
ka-	ri
kh e@	i:
ka-	rim
kh @r	i: m
ka-	rin
kh e@	I n
ka-	ro-	li-	na
kh e@	V	l aI	n V
ka-	ro-	line
kh e@	V	l aI n
ka-	ro-	ly
kh @r	@U	l i:
ka-	ro-	lyn
kh {	r V	l V n
ka-	rol
kh e@	O: l
ka-	ron
kh e@	V n
ka-	ros
kh Q@	@U s
ka-	run
kh @r	u: n
ka-	ry
kh e@	i:
ka-	ryn
kh {	r I n
ka-	ser
kh eI	z @r
ka-	sey
kh {	s i:
ka-	tey
kh eI	t i:
ka-	tha
kh {	T V
ka-	tha-	ri-	na
kh {	T e@	i:	n V
ka-	the-	rine
kh {	T @r	I n
ka-	thi
kh {	T i:
ka-	thie
kh {	T i:
ka-	thy
kh {	T i:
ka-	thy's
kh {	T i: z
ka-	ti
kh eI	t i:
ka-	tie
kh eI	t i:
ka-	to
kh eI	t @U
ka-	to's
kh eI	t @U z
ka-	ty
kh eI	t i:
ka-	ty-	did
kh eI	t i:	d I d
ka-	tya
kh Q t	j V
ka-	tyu-	sha
kh V t	j u:	S V
ka-	va-	nagh
kh {	v V	n O:
ka-	va-	naugh
kh {	v V	n O:
ka-	wa-	gu-	chi
kh Q	w Q	g u:	tS i:
ka-	wa-	i
kh Q	w Q	i:
ka-	wa-	sa-	ki
kh Q	w Q	s Q	k i:
ka-	ya
kh Q	j V
ka-	ya-	king
kh aI	{	k I N
ka-	yak
kh aI	{ k
ka-	yaks
kh aI	{ k s
ka-	yo
kh eI	@U
ka-	zakh
kh {	z { k
ka-	zakh-	stan
kh Q	z Q k	s t Q n
ka-	zakhs
kh {	z { k s
ka-	zan
kh eI	z V n
ka-	zis
kh {	z I s
ka-	zoo
kh V	z u:
kaas
kh Q z
kab-	ba-	lah
kh V	b Q	l V
kacz-	marc-	zyk
kh Q tS	m @r	tS I k
kade
kh eI d
kaf-	ka
kh Q f	k V
kaf-	ka-	esque
kh Q f	k V	e s k
kaf-	ka's
kh Q f	k V z
kah-	ler
kh Q	l @r
kahl
kh Q l
kahle
kh Q l
kahn
kh Q n
kahn's
kh Q n z
kai
kh aI
kail
kh eI l
kaim
kh eI m
kain
kh eI n
kaine
kh eI n
kal-	goor-	lie
kh { l	g u: r	l i:
kal-	ka
kh { l	k V
kal-	kas-	ka
kh { l	k Q s	k V
kal-	man
kh { l	m V n
kal-	mar
kh { l	m @r
kalb
kh { l b
kale
kh eI l
kalk
kh O: k
kall
kh O: l
kall-	man
kh O: l	m V n
kam
kh { m
kam-	chat-	ka
kh { m	tS { t	k V
kam-	me-	rer
kh {	m @r	@r
kam-	pa-	la
kh V m	p Q	l V
kamp
kh { m p
kamp-	mann
kh { m	p m V n
kampf
kh { m p f
kamp's
kh { m p s
kan
kh { n
kan-	da-	har
kh { n	d V	h Q@
kan-	ga-	roo
kh { N	g @r	u:
kan-	ga-	roos
kh { N	g @r	u: z
kan-	gas
kh { N	g V z
kan-	ji
kh { n	dZ i:
kan-	ka-	kee
kh { N	k I	k i:
kan-	nan
kh Q	n V n
kan-	san
kh { n	z V n
kan-	sans
kh { n	z V n z
kan-	sas
kh { n	z V s
kan-	ter
kh { n	t @r
kan-	ter's
kh { n	t @r z
kan-	ti-	an
kh { n	t i:	V n
kan-	tor
kh { n	t @r
kan-	tor's
kh { n	t @r z
kane
kh eI n
kane's
kh eI n z
kang
kh { N
kant
kh { n t
kant-	ner
kh { n	t n @r
kao
kh aU
kao-	lin
kh aU	l I n
kap-	lan
kh { p	l V n
kap-	lan's
kh { p	l V n z
kap-	pa
kh {	p V
kap-	pel
kh {	p V l
kap-	ton
kh { p	t V n
kapp
kh { p
kar-	la
kh Q@	l V
kar-	len
kh Q@	l V n
kar-	lik
kh Q@	l I k
kar-	lin
kh Q@	l I n
kar-	low
kh Q@	l @U
kar-	ma
kh Q@	m V
kar-	man
kh Q@	m V n
kar-	ney
kh Q@	n i:
kar-	pov
kh Q@	p Q v
kar-	ren
kh {	r V n
kar-	rer
kh Q@	@r
kar-	ry
kh e@	i:
kar-	ter
kh Q@	t @r
karch
kh Q@ k
karl
kh Q@ l
karl's
kh Q@ l z
karls-	ruhe
kh Q@ l	z r u:
karn
kh Q@ n
karnes
kh Q@ n z
karns
kh Q@ n z
karp
kh Q@ p
karr
kh Q@
kars-	ten
kh Q@ s	t V n
karst
kh Q@ s t
kas-	ka
kh Q s	k V
kas-	pa-	rov
kh { s	p @r	Q v
kas-	par
kh { s	p @r
kas-	per
kh { s	p @r
kas-	sa
kh {	s V
kas-	sab
kh {	s V b
kas-	sel
kh {	s V l
kas-	sem
kh {	s V m
kas-	son
kh {	s V n
kase
kh eI z
kash-	mi-	ri
kh { S	m i:	r i:
kash-	mir
kh { S	m I@
kass
kh { s
kast
kh { s t
kast-	ner
kh { s	t n @r
kat
kh { t
kat-	man-	du
kh { t	m { n	d u:
kat-	ri-	na
kh V t	r i:	n V
kat-	zen
kh { t	z V n
kate
kh eI t
kate's
kh eI t s
kath
kh { T
kath-	leen
kh { T	l i: n
kath-	leen's
kh { T	l i: n z
kath-	lene
kh { T	l i: n
kath-	ryn
kh { T	r I n
katha-	rine
kh { T	r I n
kats
kh { t s
katt
kh { t
katz
kh { t s
katz-	man
kh { t	s m V n
kau-	ai
kh aU	aI
kauf-	man
kh O: f	m V n
kauf-	mann
kh O: f	m V n
kauf-	man's
kh O: f	m V n z
kauff-	man
kh O: f	m V n
kauff-	mann
kh O: f	m V n
kaun-	da
kh O: n	d V
kaup-	pi
kh O:	p i:
kay
kh eI
kay-	la
kh eI	l V
kay-	lor
kh eI	l @r
kaye
kh eI
kayes
kh eI z
kayne
kh eI n
kays
kh eI z
kay's
kh eI z
ke-	dar
kh i:	d @r
ke-	fau-	ver
kh e	f aU	v @r
ke-	hoe
kh e	h @U
ke-	is-	ter
kh i:	I s	t @r
ke-	mal
kh V	m Q l
ke-	me-	ny
kh e	m V	n i:
ke-	naf
kh e	n { f
ke-	ni-	son
kh e	n I	s V n
ke-	nil-	worth
kh e	n I l	w @r T
ke-	no
kh i:	n @U
ke-	no-	sha
kh V	n @U	S V
)"
R"(ke-	o
kh i:	@U
ke-	o-	kuk
kh i:	@U	k V k
ke-	ogh
kh i:	@U
ke-	ra
kh e@	V
ke-	ra-	la
kh e@	Q	l V
ke-	ra-	tin
kh e@	V	t I n
ke-	ra-	to-	to-	my
kh e@	V	t O:	t V	m i:
ke-	rekes
kh e@	I k s
ke-	rin
kh e@	I n
ke-	ro-	sene
kh e@	V	s i: n
ke-	rou-	ac
kh e@	u:	{ k
ke-	to
kh eI	t @U
ke-	tone
kh i:	t @U n
ke-	van
kh e	v V n
ke-	ven
kh i:	v V n
ke-	ver
kh e	v @r
ke-	vin
kh e	v I n
ke-	vin's
kh e	v I n z
ke-	vor-	ki-	an
kh V	v O@	k i:	V n
ke-	vor-	ki-	an's
kh V	v O@	k i:	V n z
kea
kh i:
kea-	ley
kh i:	l i:
kea-	ry
kh I@	i:
kea-	ting
kh i:	t I N
kea-	ting's
kh i:	t I N z
kea-	ton
kh i:	t V n
keach
kh i: tS
kean
kh i: n
keane
kh i: n
kean's
kh i: n z
kear-	ney
kh @r	n i:
kear-	ney's
kh @r	n i: z
kear-	ny
kh @r	n i:
kear-	sarge
kh i: r	s Q@ dZ
kearn
kh @r n
kearns
kh @r n z
keas
kh i: z
keats
kh i: t s
keck
kh e k
keds
kh e d z
kee
kh i:
kee-	fer
kh i:	f @r
kee-	gan
kh i:	g V n
kee-	ler
kh i:	l @r
kee-	ley
kh i:	l i:
kee-	lin
kh i:	l I n
kee-	ling
kh i:	l I N
kee-	ly
kh i:	l i:
kee-	na
kh i:	n V
kee-	nan
kh i:	n V n
kee-	ner
kh i:	n @r
kee-	nest
kh i:	n V s t
kee-	per
kh i:	p @r
)"