R"(pre-	yer
ph r eI	@r
pre-	ying
ph r eI	I N
prea-	cher
ph r i:	tS @r
prea-	chers
ph r i:	tS @r z
prea-	cher's
ph r i:	tS @r z
prea-	ches
ph r i:	tS V z
prea-	ching
ph r i:	tS I N
prea-	chy
ph r i:	tS i:
preach
ph r i: tS
preached
ph r i: tS t
preak-	ness
ph r i: k	n V s
preb-	ble
ph r e	b V l
pree
ph r i:
pree-	ning
ph r i:	n I N
preen
ph r i: n
preened
ph r i: n d
preg-	nan-	cies
ph r e g	n V n	s i: z
preg-	nan-	cy
ph r e g	n V n	s i:
preg-	nant
ph r e g	n V n t
prei-	ser
ph r aI	s @r
prem
ph r e m
pren-	der-	gast
ph r e n	d @r	g { s t
pren-	sa
ph r e n	s V
pren-	tice
ph r e n	t I s
pren-	tiss
ph r e n	t I s
prep
ph r e p
prep-	pie
ph r e	p i:
prep-	ping
ph r e	p I N
prep-	py
ph r e	p i:
prepped
ph r e p t
pres
ph r e z
pres-	by-	te-	ri-	an
ph r e s	b V	t I@	i:	V n
pres-	by-	te-	ri-	ans
ph r e s	b V	t I@	i:	V n z
pres-	ley
ph r e s	l i:
pres-	ley's
ph r e s	l i: z
pres-	plit
ph r i: s	p l I t
pres-	sel
ph r e	s V l
pres-	ser
ph r e	s @r
pres-	ser's
ph r e	s @r z
pres-	ses
ph r e	s V z
pres-	sey
ph r e	s i:
pres-	sing
ph r e	s I N
pres-	s's
ph r e	s V z
pres-	su-	ri-	za-	tion
ph r e	S @r	I	z eI	S V n
pres-	su-	ri-	zes
ph r e	S @r	aI	z V z
pres-	su-	ring
ph r e	S @r	I N
pres-	su-	rize
ph r e	S @r	aI z
pres-	su-	rized
ph r e	S @r	aI z d
pres-	sure
ph r e	S @r
pres-	sured
ph r e	S @r d
pres-	sures
ph r e	S @r z
pres-	sure's
ph r e	S @r z
pres-	ti-	gious
ph r e s	t I	dZ V s
pres-	tige
ph r e s	t i: Z
pres-	to
ph r e s	t @U
pres-	ton
ph r e s	t V n
pres-	ton's
ph r e s	t V n z
press
ph r e s
press-	board
ph r e s	b O@ d
press-	bur-	ger
ph r e s	b @r	g @r
press-	ly
ph r e s	l i:
press-	man
ph r e s	m V n
pressed
ph r e s t
prest
ph r e s t
prest-	wich
ph r e s	t w I tS
pret
ph r e t
pret-	ti-	er
ph r I	t i:	@r
pret-	ti-	est
ph r I	t i:	V s t
pret-	ties
ph r I	t i: z
pret-	ty
ph r I	t i:
pret-	zel
ph r e t	z V l
pret-	zels
ph r e t	z V l z
preuss
ph r u: s
prew
ph r u:
prew-	itt
ph r u:	I t
prey
ph r eI
preyed
ph r eI d
preys
ph r eI z
pri
ph r aI
pri-	am
ph r aI	{ m
pri-	am's
ph r aI	{ m z
pri-	cer
ph r aI	s @r
pri-	ces
ph r aI	s V z
pri-	ce's
ph r aI	s V z
pri-	cey
ph r aI	s i:
pri-	chard
ph r I	tS @r d
pri-	ci-	er
ph r aI	s i:	@r
pri-	ci-	est
ph r aI	s i:	V s t
pri-	cing
ph r aI	s I N
pri-	ded
ph r aI	d V d
pri-	er
ph r aI	@r
pri-	ma
ph r i:	m V
pri-	ma-	cy
ph r aI	m V	s i:
pri-	ma-	ri-	ly
ph r aI	m e@	I	l i:
pri-	ma-	ries
ph r aI	m e@	i: z
pri-	ma-	ry
ph r aI	m e@	i:
pri-	ma-	ve-	ra
ph r i:	m Q	v e@	V
pri-	mal
ph r aI	m V l
pri-	mate
ph r aI	m eI t
pri-	mates
ph r aI	m eI t s
pri-	me-	val
ph r aI	m i:	v V l
pri-	mer
ph r aI	m @r
pri-	mers
ph r aI	m @r z
pri-	mi-	ti-	vis-	tic
ph r I	m I	t I	v I s	t I k
pri-	mi-	tive
ph r I	m I	t I v
pri-	ming
ph r aI	m I N
pri-	mo
ph r i:	m @U
pri-	mor-	di-	al
ph r I	m O@	d i:	V l
pri-	mo's
ph r i:	m @U z
pri-	mus
ph r aI	m V s
pri-	nos
ph r i:	n @U s
pri-	o-	ri-	ti-	zes
ph r aI	O@	I	t aI	z V z
pri-	o-	ri-	ti-	zing
ph r aI	O@	I	t aI	z I N
pri-	o-	ri-	ties
ph r aI	O@	I	t i: z
pri-	o-	ri-	tize
ph r aI	O@	I	t aI z
pri-	o-	ri-	tized
ph r aI	O@	I	t aI z d
pri-	o-	ri-	ty
ph r aI	O@	I	t i:
pri-	o-	ry
ph r aI	@r	i:
pri-	or
ph r aI	@r
pri-	ors
ph r aI	@r z
pri-	sm
ph r I	z V m
pri-	so-	ner
ph r I	z V	n @r
pri-	so-	ners
ph r I	z V	n @r z
pri-	so-	ner's
ph r I	z V	n @r z
pri-	son
ph r I	z V n
pri-	soned
ph r I	z V n d
pri-	sons
ph r I	z V n z
pri-	son's
ph r I	z V n z
pri-	va-	cies
ph r aI	v V	s i: z
pri-	va-	cy
ph r aI	v V	s i:
pri-	va-	ti-	sa-	tion
ph r aI	v V	t I	z eI	S V n
pri-	va-	ti-	za-	tion
ph r aI	v V	t I	z eI	S V n
pri-	va-	ti-	za-	tions
ph r aI	v V	t I	z eI	S V n z
pri-	va-	ti-	zing
ph r aI	v V	t aI	z I N
pri-	va-	tion
ph r aI	v eI	S V n
pri-	va-	tions
ph r aI	v eI	S V n z
pri-	va-	tize
ph r I	v V	t aI z
pri-	va-	tized
ph r aI	v V	t aI z d
pri-	vate
ph r aI	v V t
pri-	vate-	ly
ph r aI	v V t	l i:
pri-	vates
ph r aI	v V t s
pri-	vi-	leges
ph r I v	l e	dZ V z
pri-	vy
ph r I	v i:
pri-	zes
ph r aI	z V z
prib-	ble
ph r I	b V l
pric-	kle-	back
ph r I	k V l	b { k
price
ph r aI s
price-	less
ph r aI s	l V s
priced
ph r aI s t
prick
ph r I k
prick-	ly
ph r I k	l i:
pricked
ph r I k t
pricks
ph r I k s
prid-	dy
ph r I	d i:
pride
ph r aI d
prides
ph r aI d z
prie-	ur
ph r i:	@r
priebe
ph r i: b
pried
ph r aI d
pries
ph r aI z
pries-	tess
ph r i: s	t V s
priest
ph r i: s t
priest-	hood
ph r i: s	t h U d
priest-	ley
ph r i: s	t l i:
priest-	ly
ph r i: s	t l i:
priests
ph r i: s t s
priest's
ph r i: s t s
prig
ph r I g
prill
ph r I l
prim
ph r I m
prim-	ly
ph r I m	l i:
prim-	mer
ph r I	m @r
prim-	ro-	ses
ph r I m	r @U	z V z
prim-	rose
ph r I m	r @U z
prime
ph r aI m
prime-	time
ph r aI m	t aI m
primed
ph r aI m d
primes
ph r aI m z
prime's
ph r aI m z
primp
ph r I m p
prin-	ces
ph r I n	s V z
prin-	ce's
ph r I n	s V z
prin-	ces-	ses
ph r I n	s e	s V z
prin-	ces-	s's
ph r I n	s e	s V z
prin-	cess
ph r I n	s e s
prin-	ci-	pa-	li-	ties
ph r I n	s I	p {	l V	t i: z
prin-	ci-	pa-	li-	ty
ph r I n	s I	p {	l V	t i:
prin-	ci-	pal
ph r I n	s I	p V l
prin-	ci-	pals
ph r I n	s I	p V l z
prin-	ci-	pal's
ph r I n	s I	p V l z
prin-	ci-	pe
ph r i: n	tS i:	p i:
prin-	ci-	pi-	a
ph r I n	s I	p i:	V
prin-	ci-	ple
ph r I n	s I	p V l
prin-	ci-	pled
ph r I n	s I	p V l d
prin-	ci-	ples
ph r I n	s I	p V l z
prin-	cipal-	ly
ph r I n	s I p	l i:
prin-	gle
ph r I N	g V l
prin-	ta-	ble
ph r I n	t V	b V l
prin-	ted
ph r I n	t V d
prin-	temps
ph r I n	t e m p s
prin-	ter
ph r I n	t @r
prin-	ters
ph r I n	t @r z
prin-	ter's
ph r I n	t @r z
prin-	ting
ph r I n	t I N
prin-	tings
ph r I n	t I N z
prin-	ting's
ph r I n	t I N z
prince
ph r I n s
prince-	ly
ph r I n	s l i:
prince-	ton
ph r I n	s t V n
prince-	ton's
ph r I n	s t V n z
prince-	ville
ph r I n	s v I l
prine
ph r aI n
print
ph r I n t
print-	ma-	ker
ph r I n	t m eI	k @r
print-	ma-	kers
ph r I n	t m eI	k @r z
print-	out
ph r I n	t aU t
print-	outs
ph r I n	t aU t s
prints
ph r I n t s
prinz
ph r I n z
pris
ph r I s
pris-	cil-	la
ph r V	s I	l V
pris-	ma-	tic
ph r I z	m {	t I k
pris-	sie
ph r I	s i:
pris-	sy
ph r I	s i:
pris-	tine
ph r I s	t i: n
prit-	chard
ph r I	tS @r d
prit-	chett
ph r I	tS e t
privi-	lege
ph r I v	l V dZ
privi-	leged
ph r I v	l V dZ d
prix
ph r i:
prize
ph r aI z
prized
ph r aI z d
pro
ph r @U
pro-	ac-	tive
ph r @U	{ k	t I v
pro-	ac-	tive-	ly
ph r @U	{ k	t I v	l i:
pro-	ba-	bi-	li-	ties
ph r Q	b V	b I	l V	t i: z
pro-	ba-	bi-	li-	ty
ph r Q	b V	b I	l V	t i:
pro-	ba-	ble
ph r Q	b V	b V l
pro-	ba-	tio-	na-	ry
ph r @U	b eI	S V	n e@	i:
pro-	ba-	tio-	ner
ph r @U	b eI	S V	n @r
pro-	ba-	tio-	ners
ph r @U	b eI	S V	n @r z
pro-	ba-	tion
ph r @U	b eI	S V n
pro-	ba-	tive
ph r @U	b eI	t I v
pro-	bab-	ly
ph r Q	b V b	l i:
pro-	bate
ph r @U	b eI t
pro-	be-	ne-	cid
ph r Q	b e	n V	s V d
pro-	bi-	ty
ph r @U	b I	t i:
pro-	bing
ph r @U	b I N
pro-	bo-	scis
ph r @U	b Q	s I s
pro-	caine
ph r @U	k eI n
pro-	ce-	du-	ral
ph r V	s i:	dZ @r	V l
pro-	ce-	du-	ral-	ly
ph r V	s i:	dZ @r	V	l i:
pro-	ce-	dure
ph r V	s i:	dZ @r
pro-	ce-	dures
ph r V	s i:	dZ @r z
pro-	cee-	ded
ph r V	s i:	d V d
pro-	cee-	ding
ph r V	s i:	d I N
pro-	cee-	dings
ph r @U	s i:	d I N z
pro-	ceed
ph r V	s i: d
pro-	ceeds
ph r V	s i: d z
pro-	ces-	ses
ph r Q	s e	s V z
pro-	ces-	sing
ph r Q	s e	s I N
pro-	ces-	sio-	nal
ph r V	s e	S V	n V l
pro-	ces-	sion
ph r V	s e	S V n
pro-	ces-	sions
ph r @U	s e	S V n z
pro-	ces-	sor
ph r Q	s e	s @r
pro-	ces-	sors
ph r Q	s e	s @r z
pro-	ces-	sor's
ph r Q	s e	s @r z
pro-	cess
ph r Q	s e s
pro-	cessed
ph r Q	s e s t
pro-	con-	sul
ph r @U	k Q n	s V l
pro-	cra-	sti-	na-	ting
ph r V k	r { s	t V	n eI	t I N
pro-	cra-	sti-	na-	tion
ph r V k	r { s	t V	n eI	S V n
pro-	cra-	sti-	nate
ph r V k	r { s	t V	n eI t
pro-	cre-	a-	tion
ph r @U k	r i:	eI	S V n
pro-	cre-	ate
ph r @U k	r i:	eI t
pro-	cre-	ates
ph r @U k	r i:	eI t s
pro-	cu-	rer
ph r @U k	j U@	@r
pro-	cu-	ring
ph r @U k	j U@	I N
pro-	cure
ph r @U k	j U@
pro-	cure-	ment
ph r @U k	j U@	m V n t
pro-	cure-	ments
ph r @U k	j U@	m V n t s
pro-	cured
ph r @U k	j U@ d
pro-	di-	gal
ph r Q	d I	g V l
pro-	di-	gies
ph r Q	d I	dZ i: z
pro-	di-	gious
ph r V	d I	dZ V s
pro-	di-	gious-	ly
ph r @U	d I	dZ V s	l i:
pro-	di-	gy
ph r Q	d I	dZ i:
pro-	di-	gy's
ph r Q	d I	dZ i: z
pro-	duc-	ti-	vi-	ty
ph r @U	d V k	t I	v V	t i:
pro-	duc-	tion
ph r V	d V k	S V n
pro-	ducts
ph r Q	d V k t s
pro-	duct's
ph r Q	d V k t s
pro-	fa-	na-	tion
ph r O:	f V	n eI	S V n
pro-	fa-	ni-	ty
ph r @U	f {	n I	t i:
pro-	fane
ph r @U	f eI n
pro-	fes-	ses
ph r V	f e	s V z
pro-	fes-	sing
ph r V	f e	s I N
pro-	fes-	sio-	na-	li-	sm
ph r V	f e	S V	n V	l I	z V m
pro-	fes-	sio-	na-	lize
ph r V	f e	S V	n V	l aI z
pro-	fes-	sio-	na-	lized
ph r V	f e	S V	n V	l aI z d
pro-	fes-	sio-	nal
ph r V	f e	S V	n V l
pro-	fes-	sio-	nal-	ly
ph r V	f e	S V	n V	l i:
pro-	fes-	sio-	nals
ph r V	f e	S V	n V l z
pro-	fes-	sion
ph r V	f e	S V n
pro-	fes-	sions
ph r V	f e	S V n z
pro-	fes-	sion's
ph r V	f e	S V n z
pro-	fes-	so-	ri-	al
ph r @U	f V	s O@	i:	V l
pro-	fes-	sor
ph r V	f e	s @r
pro-	fes-	sor-	ship
ph r V	f e	s @r	S I p
pro-	fes-	sors
ph r V	f e	s @r z
pro-	fes-	sor's
ph r V	f e	s @r z
pro-	fess
ph r V	f e s
pro-	fessed
ph r V	f e s t
pro-	fi-	cien-	cy
ph r V	f I	S V n	s i:
pro-	fi-	cient
ph r Q	f I	S V n t
pro-	fi-	ling
ph r @U	f aI	l I N
pro-	fi-	ta-	bi-	li-	ty
ph r Q	f I	t V	b I	l I	t i:
pro-	fi-	ta-	ble
ph r Q	f I	t V	b V l
pro-	fi-	tab-	ly
ph r Q	f I	t V b	l i:
pro-	fi-	ted
ph r Q	f I	t I d
pro-	fi-	tee-	ring
ph r Q	f I	t I@	I N
pro-	fi-	teer
ph r Q	f I	t I@
pro-	fi-	teers
ph r Q	f I	t I@ z
pro-	fi-	ting
ph r Q	f I	t I N
pro-	file
ph r @U	f aI l
pro-	filed
ph r @U	f aI l d
pro-	files
ph r @U	f aI l z
pro-	fit
ph r Q	f I t
pro-	fit-	ta-	king
ph r Q	f I t	t eI	k I N
pro-	fits
ph r Q	f I t s
pro-	fli-	ga-	cy
ph r O: f	l I	g {	s i:
pro-	fli-	gate
ph r O: f	l I	g eI t
pro-	found
ph r @U	f aU n d
pro-	found-	ly
ph r @U	f aU n	d l i:
pro-	fu-	sion
ph r V f	j u:	Z V n
pro-	fuse
ph r V f	j u: s
pro-	fuse-	ly
ph r V f	j u: s	l i:
pro-	ge-	ni-	tor
ph r @U	dZ e	n I	t @r
pro-	ge-	ny
ph r Q	dZ V	n i:
pro-	ges-	te-	rone
ph r @U	dZ e s	t @r	@U n
pro-	ges-	tin
ph r @U	dZ e s	t I n
pro-	gra-	ming
ph r @U g	r {	m I N
pro-	gram
ph r @U g	r { m
pro-	gram-	ma-	ble
ph r @U g	r {	m V	b V l
pro-	gram-	ma-	tic
ph r Q g	r V	m {	t I k
pro-	gram-	mer
ph r @U g	r {	m @r
pro-	gram-	mers
ph r @U g	r {	m @r z
pro-	gram-	ming
ph r @U g	r {	m I N
pro-	gramme
ph r @U g	r { m
pro-	grammed
ph r @U g	r { m d
pro-	grams
ph r @U g	r { m z
pro-	gram's
ph r @U g	r { m z
pro-	gres-	ses
ph r Q g	r e	s V z
pro-	gres-	si-	vi-	ty
ph r Q g	r e	s I	v V	t i:
pro-	gres-	sing
ph r V g	r e	s I N
pro-	gres-	sion
ph r V g	r e	S V n
pro-	gres-	sive
ph r V g	r e	s I v
pro-	gres-	sive-	ly
ph r Q g	r e	s I v	l i:
pro-	gres-	sives
ph r Q g	r e	s I v z
pro-	gress
ph r Q g	r e s
pro-	gressed
ph r V g	r e s t
pro-	hi-	bi-	ted
ph r @U	h I	b I	t I d
pro-	hi-	bi-	ting
ph r @U	h I	b I	t I N
pro-	hi-	bi-	tion
ph r @U	I	b I	S V n
pro-	hi-	bi-	tions
ph r @U	I	b I	S V n z
pro-	hi-	bi-	tion's
ph r @U	I	b I	S V n z
pro-	hi-	bi-	tive
ph r @U	h I	b I	t I v
pro-	hi-	bi-	tive-	ly
ph r @U	h I	b I	t I v	l i:
pro-	hi-	bi-	to-	ry
ph r @U	h I	b I	t O@	i:
pro-	hi-	bit
ph r @U	h I	b I t
pro-	hi-	bits
ph r @U	h I	b I t s
pro-	jec-	ted
ph r V	dZ e k	t V d
pro-	jec-	tile
ph r V	dZ e k	t V l
pro-	jec-	tiles
ph r V	dZ e k	t V l z
pro-	jec-	ting
ph r V	dZ e k	t I N
pro-	jec-	tion
ph r V	dZ e k	S V n
pro-	jec-	tions
ph r V	dZ e k	S V n z
pro-	jec-	tive
ph r V	dZ e k	t I v
pro-	jec-	tor
ph r V	dZ e k	t @r
pro-	jec-	tors
ph r V	dZ e k	t @r z
pro-	ject
ph r Q	dZ e k t
pro-	jects
ph r Q	dZ e k t s
pro-	ject's
ph r Q	dZ e k t s
pro-	ko-	fiev
ph r Q	k @U	f i: v
pro-	lac-	tin
ph r @U	l { k	t I n
pro-	le-	ta-	ri-	an
ph r @U	l V	t e@	i:	V n
pro-	le-	ta-	ri-	at
ph r @U	l V	t e@	i:	V t
pro-	ler
ph r @U	l @r
pro-	li-	fe-	ra-	ted
ph r V	l I	f @r	eI	t V d
pro-	li-	fe-	ra-	ting
ph r @U	l I	f @r	eI	t I N
pro-	li-	fe-	ra-	tion
ph r @U	l I	f @r	eI	S V n
pro-	li-	fe-	rate
ph r @U	l I	f @r	eI t
pro-	li-	fic
ph r @U	l I	f I k
pro-	li-	fical-	ly
ph r @U	l I	f I k	l i:
pro-	log
ph r @U	l Q g
pro-	logue
ph r @U	l Q g
pro-	lon-	ging
ph r @U	l O:	N I N
pro-	long
ph r V	l O: N
pro-	longed
ph r V	l O: N d
pro-	longs
ph r V	l O: N z
pro-	me-	nade
ph r Q	m V	n eI d
pro-	me-	thi-	um
ph r V	m i:	T i:	V m
pro-	mi-	nen-	ces
ph r Q	m I	n e n	s V z
pro-	mi-	nence
ph r Q	m I	n e n s
pro-	mi-	nent
ph r Q	m I	n e n t
pro-	mi-	nent-	ly
ph r Q	m I	n e n	t l i:
pro-	mi-	ses
ph r Q	m I	s V z
pro-	mi-	sing
ph r Q	m I	s I N
pro-	mis-	cu-	i-	ty
ph r @U	m I s	k j u:	V	t i:
pro-	mis-	cuous
ph r @U	m I s	k w V s
pro-	mis-	so-	ry
ph r Q	m I	s O@	i:
pro-	mise
ph r Q	m I s
pro-	mised
ph r Q	m I s t
pro-	mo
ph r @U	m @U
pro-	mo-	ted
ph r V	m @U	t V d
pro-	mo-	ter
ph r V	m @U	t @r
pro-	mo-	ters
ph r V	m @U	t @r z
pro-	mo-	ting
ph r V	m @U	t I N
pro-	mo-	tio-	nal
ph r V	m @U	S V	n V l
pro-	mo-	tion
ph r V	m @U	S V n
pro-	mo-	tions
ph r V	m @U	S V n z
pro-	mos
ph r @U	m @U z
pro-	mote
ph r V	m @U t
pro-	motes
ph r V	m @U t s
pro-	mul-	ga-	ted
ph r Q	m V l	g eI	t V d
pro-	mul-	ga-	ting
ph r Q	m V l	g eI	t I N
pro-	mul-	gate
ph r @U	m V l	g eI t
pro-	noun
ph r @U	n aU n
pro-	noun-	ces
ph r V	n aU n	s V z
pro-	noun-	cing
ph r V	n aU n	s I N
pro-	nounce
ph r V	n aU n s
pro-	nounce-	ment
ph r V	n aU n	s m V n t
pro-	nounce-	ments
ph r V	n aU n	s m V n t s
pro-	nounced
ph r V	n aU n s t
pro-	nouns
ph r @U	n aU n z
pro-	nun-	ci-	a-	tion
ph r @U	n V n	s i:	eI	S V n
pro-	nun-	ci-	a-	tions
ph r @U	n V n	s i:	eI	S V n z
pro-	pa-	ga-	ted
ph r Q	p V	g eI	t V d
pro-	pa-	ga-	ting
ph r Q	p V	g eI	t I N
pro-	pa-	ga-	tion
ph r Q	p V	g eI	S V n
pro-	pa-	gan-	da
ph r Q	p V	g { n	d V
pro-	pa-	gan-	dis-	tic
ph r Q	p V	g V n	d I s	t I k
pro-	pa-	gan-	dist
ph r Q	p V	g { n	d V s t
pro-	pa-	gan-	dists
ph r Q	p V	g { n	d V s t s
pro-	pa-	gan-	dize
ph r Q	p V	g { n	d aI z
pro-	pa-	gate
ph r Q	p V	g eI t
pro-	pane
ph r @U	p eI n
pro-	pel
ph r V	p e l
pro-	pel-	lant
ph r V	p e	l V n t
pro-	pel-	lants
ph r @U	p e	l V n t s
pro-	pel-	ler
ph r V	p e	l @r
pro-	pel-	lers
ph r V	p e	l @r z
pro-	pel-	ling
ph r V	p e	l I N
pro-	pelled
ph r V	p e l d
pro-	pels
ph r V	p e l z
pro-	pen-	si-	ties
ph r V	p e n	s V	t i: z
pro-	pen-	si-	ty
ph r V	p e n	s V	t i:
pro-	per
ph r Q	p @r
pro-	per-	ly
ph r Q	p @r	l i:
pro-	per-	ties
ph r Q	p @r	t i: z
pro-	per-	ty
ph r Q	p @r	t i:
pro-	per-	ty's
ph r Q	p @r	t i: z
pro-	phe-	cies
ph r Q	f V	s i: z
pro-	phe-	cy
ph r Q	f V	s i:
pro-	phe-	sied
ph r Q	f V	s aI d
pro-	phe-	sies
ph r Q	f V	s aI z
pro-	phe-	tess
ph r Q	f V	t V s
pro-	phe-	tic
ph r V	f e	t I k
pro-	phet
ph r Q	f V t
pro-	phets
ph r Q	f V t s
pro-	phy-	lac-	tic
ph r Q	f V	l { k	t I k
pro-	pi-	o-	nic
ph r @U	p i:	Q	n I k
pro-	pi-	tious
ph r V	p I	S V s
pro-	po-	nent
ph r V	p @U	n V n t
pro-	po-	nents
ph r V	p @U	n V n t s
pro-	po-	sal
ph r V	p @U	z V l
pro-	po-	sals
ph r V	p @U	z V l z
pro-	po-	sal's
ph r V	p @U	z V l z
pro-	po-	ses
ph r V	p @U	z V z
pro-	po-	si-	tion
ph r Q	p V	z I	S V n
pro-	po-	si-	tioned
ph r Q	p V	z I	S V n d
pro-	po-	si-	tions
ph r Q	p V	z I	S V n z
pro-	po-	sing
ph r V	p @U	z I N
pro-	por-	tio-	na-	li-	ty
ph r V	p O@	S V	n {	l V	t i:
pro-	por-	tio-	nal
ph r V	p O@	S V	n V l
pro-	por-	tio-	nal-	ly
ph r V	p O@	S V	n V	l i:
pro-	por-	tio-	nate
ph r V	p O@	S V	n V t
pro-	por-	tio-	nate-	ly
ph r V	p O@	S V	n V t	l i:
pro-	por-	tion
ph r V	p O@	S V n
pro-	por-	tioned
ph r V	p O@	S V n d
pro-	por-	tions
ph r V	p O@	S V n z
pro-	pose
ph r V	p @U z
pro-	posed
ph r V	p @U z d
pro-	poun-	ded
ph r V	p aU n	d V d
pro-	pound
ph r V	p aU n d
pro-	pri-	e-	ta-	ries
ph r V p	r aI	V	t e@	i: z
pro-	pri-	e-	ta-	ry
ph r V p	r aI	V	t e@	i:
pro-	pri-	e-	tor
ph r V p	r aI	V	t @r
pro-	pri-	e-	tor-	ship
ph r V p	r aI	V	t @r	S I p
pro-	pri-	e-	tor-	ships
ph r V p	r aI	V	t @r	S I p s
pro-	pri-	e-	tors
ph r V p	r aI	V	t @r z
pro-	pri-	e-	tor's
ph r V p	r aI	V	t @r z
pro-	pri-	e-	ty
ph r V p	r aI	V	t i:
pro-	pul-	sion
ph r V	p V l	S V n
pro-	py-	lene
ph r @U	p V	l i: n
pro-	ra-	ted
ph r @U	r eI	t V d
pro-	ra-	tion
ph r @U	r eI	S V n
pro-	rate
ph r @U	r eI t
pro-	sa-	ic
ph r @U	z eI	I k
pro-	scribe
ph r @U s	k r aI b
pro-	scribed
ph r @U s	k r aI b d
)"
R"(pro-	scribes
ph r @U s	k r aI b z
pro-	scrip-	tion
ph r @U s	k r I p	S V n
pro-	se-	cu-	ta-	ble
ph r Q	s I k	j u:	t V	b V l
pro-	se-	cu-	ted
ph r Q	s I k	j u:	t V d
pro-	se-	cu-	ting
ph r Q	s I k	j u:	t I N
pro-	se-	cu-	tion
ph r Q	s V k	j u:	S V n
pro-	se-	cu-	tions
ph r Q	s V k	j u:	S V n z
pro-	se-	cu-	tion's
ph r Q	s V k	j u:	S V n z
pro-	se-	cu-	to-	ri-	al
ph r Q	s I k	j u:	t O@	i:	V l
pro-	se-	cu-	tor
ph r Q	s I k	j u:	t @r
pro-	se-	cu-	tors
ph r Q	s I k	j u:	t @r z
pro-	se-	cu-	tor's
ph r Q	s I k	j u:	t @r z
pro-	se-	cute
ph r Q	s V k	j u: t
pro-	se-	cutes
ph r Q	s I k	j u: t s
pro-	se-	ly-	ti-	zing
ph r Q	s V	l V	t aI	z I N
pro-	se-	ly-	tize
ph r Q	s V	l V	t aI z
pro-	se-	ly-	tized
ph r Q	s V	l V	t aI z d
pro-	sek
ph r @U	s e k
pro-	ser-	pi-	na
ph r @U	s @r	p I	n V
pro-	so-	dy
ph r Q	s V	d i:
pro-	ta-	go-	nist
ph r @U	t {	g V	n V s t
pro-	ta-	go-	nists
ph r @U	t {	g V	n V s t s
pro-	te-	an
ph r @U	t i:	V n
pro-	te-	ase
ph r @U	t i:	eI z
pro-	te-	ge
ph r @U	t I	Z eI
pro-	te-	ges
ph r @U	t I	Z eI z
pro-	tec-	ted
ph r V	t e k	t V d
pro-	tec-	ting
ph r V	t e k	t I N
pro-	tec-	tio-	ni-	sm
ph r V	t e k	S V	n I	z V m
pro-	tec-	tio-	nist
ph r V	t e k	S V	n I s t
pro-	tec-	tio-	nists
ph r V	t e k	S V	n I s t s
pro-	tec-	tion
ph r V	t e k	S V n
pro-	tec-	tions
ph r V	t e k	S V n z
pro-	tec-	tive
ph r V	t e k	t I v
pro-	tec-	tive-	ly
ph r V	t e k	t I v	l i:
pro-	tec-	to-	rate
ph r V	t e k	t @r	V t
pro-	tec-	tor
ph r V	t e k	t @r
pro-	tec-	tors
ph r V	t e k	t @r z
pro-	tect
ph r V	t e k t
pro-	tects
ph r V	t e k t s
pro-	tein
ph r @U	t i: n
pro-	teins
ph r @U	t i: n z
pro-	tes-	ta-	tion
ph r @U	t e s	t eI	S V n
pro-	tes-	ta-	tions
ph r @U	t e s	t eI	S V n z
pro-	tes-	tan-	ti-	sm
ph r Q	t V s	t V n	t I	z V m
pro-	tes-	tant
ph r Q	t V s	t V n t
pro-	tes-	tants
ph r Q	t V s	t V n t s
pro-	tes-	ted
ph r V	t e s	t V d
pro-	tes-	ter
ph r @U	t e s	t @r
pro-	tes-	ters
ph r @U	t e s	t @r z
pro-	tes-	ting
ph r V	t e s	t I N
pro-	tes-	tors
ph r @U	t e s	t @r z
pro-	test
ph r @U	t e s t
pro-	tests
ph r @U	t e s t s
pro-	thal-	lus
ph r @U	T {	l V s
pro-	tho-	rax
ph r @U	T O@	{ k s
pro-	ti-	um
ph r @U	t i:	V m
pro-	to
ph r @U	t V
pro-	to-	col
ph r @U	t V	k Q l
pro-	to-	cols
ph r @U	t V	k Q l z
pro-	to-	his-	to-	ry
ph r @U	t @U	h I s	t @r	i:
pro-	to-	ty-	pi-	cal
ph r @U	t V	t I	p I	k V l
pro-	to-	type
ph r @U	t V	t aI p
pro-	to-	types
ph r @U	t V	t aI p s
pro-	to-	zo-	a
ph r @U	t V	z @U	V
pro-	to-	zo-	an
ph r @U	t V	z @U	V n
pro-	to-	zo-	ans
ph r @U	t V	z @U	V n z
pro-	ton
ph r @U	t Q n
pro-	tons
ph r @U	t Q n z
pro-	ton's
ph r @U	t Q n z
pro-	trac-	ted
ph r @U t	r { k	t V d
pro-	tract
ph r @U t	r { k t
pro-	tru-	ding
ph r @U t	r u:	d I N
pro-	trude
ph r @U t	r u: d
pro-	tu-	be-	ran-	ces
ph r @U	t u:	b @r	V n	s V z
pro-	tu-	be-	rance
ph r @U	t u:	b @r	V n s
pro-	va-	ble
ph r u:	v V	b V l
pro-	vant
ph r @U	v V n t
pro-	ve-	nance
ph r Q	v V	n V n s
pro-	ve-	ra
ph r @U	v e@	V
pro-	ven
ph r u:	v V n
pro-	vence
ph r @U	v V n s
pro-	ver-	bi-	al
ph r V	v @r	b i:	V l
pro-	verb
ph r Q	v @r b
pro-	verbs
ph r Q	v @r b z
pro-	vi-	ded
ph r V	v aI	d V d
pro-	vi-	den-	ce's
ph r Q	v I	d e n	s V z
pro-	vi-	den-	tial
ph r Q	v I	d e n	tS V l
pro-	vi-	dence
ph r Q	v I	d e n s
pro-	vi-	dent
ph r Q	v I	d e n t
pro-	vi-	der
ph r V	v aI	d @r
pro-	vi-	ders
ph r V	v aI	d @r z
pro-	vi-	ding
ph r V	v aI	d I N
pro-	vi-	ne
ph r @U	v i:	n i:
pro-	vi-	sio-	nal
ph r V	v I	Z V	n V l
pro-	vi-	sio-	nal-	ly
ph r V	v I	Z V	n V	l i:
pro-	vi-	sio-	ning
ph r V	v I	Z V	n I N
pro-	vi-	sion
ph r V	v I	Z V n
pro-	vi-	sions
ph r V	v I	Z V n z
pro-	vi-	so
ph r V	v aI	z @U
pro-	vide
ph r V	v aI d
pro-	vides
ph r V	v aI d z
pro-	vin-	ces
ph r Q	v I n	s V z
pro-	vin-	ce's
ph r Q	v I n	s V z
pro-	vin-	cia-	li-	sm
ph r V	v I n	tS V	l I	z V m
pro-	vin-	cial
ph r V	v I n	S V l
pro-	vin-	cial-	ly
ph r V	v I n	S V	l i:
pro-	vince
ph r Q	v I n s
pro-	vince-	town
ph r Q	v I n	s t aU n
pro-	ving
ph r u:	v I N
pro-	vo
ph r @U	v @U
pro-	vo-	ca-	tion
ph r Q	v V	k eI	S V n
pro-	vo-	ca-	tions
ph r Q	v V	k eI	S V n z
pro-	vo-	ca-	tive
ph r @U	v Q	k V	t I v
pro-	vo-	ca-	tive-	ly
ph r @U	v Q	k V	t I v	l i:
pro-	vo-	king
ph r V	v @U	k I N
pro-	voke
ph r V	v @U k
pro-	voked
ph r V	v @U k t
pro-	vokes
ph r V	v @U k s
pro-	vost
ph r @U	v @U s t
pro-	vosts
ph r @U	v @U s t s
pro-	wess
ph r aU	V s
pro-	xi-	mal
ph r Q k	s I	m V l
pro-	xi-	mate
ph r Q k	s I	m V t
pro-	xi-	mi-	ty
ph r Q k	s I	m I	t i:
pro-	xies
ph r Q k	s i: z
pro-	xy
ph r Q k	s i:
pro-	zac
ph r @U	z { k
prob
ph r Q b
prob-	le-	ma-	ti-	cal
ph r Q b	l V	m {	t I	k V l
prob-	le-	ma-	tic
ph r Q b	l V	m {	t I k
prob-	lem
ph r Q b	l V m
prob-	lems
ph r Q b	l V m z
prob-	lem's
ph r Q b	l V m z
probe
ph r @U b
probed
ph r @U b d
probes
ph r @U b z
proc-	la-	ma-	tion
ph r Q k	l V	m eI	S V n
proc-	la-	ma-	tions
ph r Q k	l V	m eI	S V n z
proc-	lai-	ming
ph r @U k	l eI	m I N
proc-	laim
ph r @U k	l eI m
proc-	laimed
ph r @U k	l eI m d
proc-	laims
ph r @U k	l eI m z
proc-	li-	vi-	ties
ph r @U k	l I	v I	t i: z
proc-	li-	vi-	ty
ph r @U k	l I	v I	t i:
proc-	ter
ph r Q k	t @r
proc-	tor
ph r Q k	t @r
proc-	tors
ph r Q k	t @r z
proc-	tor's
ph r Q k	t @r z
prod
ph r Q d
prod-	ded
ph r Q	d V d
prod-	ding
ph r Q	d I N
prof-	fe-	ring
ph r Q	f @r	I N
prof-	fer
ph r Q	f @r
prof-	fered
ph r Q	f @r d
prof-	fitt
ph r Q	f I t
prof.
ph r O: f
profs
ph r Q f s
prog-	no-	ses
ph r Q g	n @U	s i: z
prog-	no-	sis
ph r Q g	n @U	s I s
prog-	nos-	ti-	ca-	ted
ph r Q g	n Q s	t I	k eI	t I d
prog-	nos-	ti-	ca-	ting
ph r Q g	n Q s	t I	k eI	t I N
prog-	nos-	ti-	ca-	tion
ph r Q g	n Q s	t I	k eI	S V n
prog-	nos-	ti-	ca-	tions
ph r Q g	n Q s	t I	k eI	S V n z
prog-	nos-	ti-	ca-	tive
ph r Q g	n Q s	t I	k eI	t I v
prog-	nos-	ti-	cate
ph r Q g	n Q s	t I	k eI t
prog-	nos-	ti-	cates
ph r Q g	n Q s	t I	k eI t s
prom
ph r Q m
promp-	ted
ph r Q m	p t V d
promp-	ting
ph r Q m	p t I N
prompt
ph r Q m p t
prompt-	ly
ph r Q m	p t l i:
prompts
ph r Q m p t s
proms
ph r Q m z
pron-	to
ph r Q n	t @U
prone
ph r @U n
prong
ph r O: N
prong-	horn
ph r O: N	h O@ n
pronged
ph r O: N d
prongs
ph r O: N z
proo-	fing
ph r u:	f I N
proof
ph r u: f
proof-	rea-	ding
ph r u: f	r i:	d I N
proof-	read
ph r u: f	r i: d
proofed
ph r u: f t
proofs
ph r u: f s
prop
ph r Q p
prop-	per
ph r Q	p @r
prop-	ping
ph r Q	p I N
propped
ph r Q p t
props
ph r Q p s
pros
ph r @U z
pro's
ph r @U z
pros-	ser
ph r O:	s @r
pros-	ta-	tec-	to-	my
ph r Q s	t eI	t e k	t V	m i:
pros-	ta-	tic
ph r @U s	t {	t I k
pros-	tag-	lan-	din
ph r @U s	t { g	l { n	d I n
pros-	tag-	lan-	dins
ph r @U s	t { g	l { n	d I n z
pros-	tate
ph r Q s	t eI t
pros-	the-	ses
ph r Q s	T i:	s i: z
pros-	the-	sis
ph r O: s	T e	s I s
pros-	the-	tic
ph r Q s	T e	t I k
pros-	the-	tics
ph r Q s	T e	t I k s
pros-	ti-	tu-	tion
ph r Q s	t I	t u:	S V n
pros-	ti-	tute
ph r Q s	t I	t u: t
pros-	ti-	tutes
ph r Q s	t I	t u: t s
prose
ph r @U z
pross
ph r O: s
prost
ph r Q s t
prost-	ra-	tion
ph r Q s	t r eI	S V n
prost-	rate
ph r Q s	t r eI t
prou-	der
ph r aU	d @r
prou-	dest
ph r aU	d V s t
prou-	ty
ph r aU	t i:
proud
ph r aU d
proud-	foot
ph r aU d	f U t
proud-	foot's
ph r aU d	f U t s
proud-	ly
ph r aU d	l i:
proulx
ph r aU l k s
proust
ph r aU s t
prout
ph r aU t
prove
ph r u: v
proved
ph r u: v d
proves
ph r u: v z
prow
ph r aU
prow-	ler
ph r aU	l @r
prow-	ling
ph r aU	l I N
prowl
ph r aU l
prows
ph r aU z
prox-	mire
ph r Q k	s m aI r
pru
ph r u:
pru-	de-	ry
ph r u:	d @r	i:
pru-	den
ph r u:	d V n
pru-	den-	tial
ph r u:	d e n	tS V l
pru-	den-	tial's
ph r u:	d e n	tS V l z
pru-	dence
ph r u:	d V n s
pru-	dent
ph r u:	d V n t
pru-	dent-	ly
ph r u:	d V n	t l i:
pru-	dish
ph r u:	d I S
pru-	itt
ph r u:	I t
pru-	nel-	la
ph r u:	n e	l V
pru-	ner
ph r u:	n @r
pru-	ning
ph r u:	n I N
pru-	ri-	ent
ph r U@	i:	V n t
prud-	hoe
ph r V d	h @U
prud-	homme
ph r V d	h V m
prude
ph r u: d
prue
ph r u:
pruett
ph r u: t
prune
ph r u: n
pruned
ph r u: n d
prunes
ph r u: n z
prus
ph r V s
pru's
ph r u: z
prus-	sia
ph r V	S V
prus-	sian
ph r V	S V n
pruss
ph r V s
pry
ph r aI
pry-	er
ph r aI	@r
pry-	ing
ph r aI	I N
pry-	or
ph r aI	@r
pry-	or's
ph r aI	@r z
pryce
ph r aI s
prynne
ph r I n
p's
ph i: z
psal-	ter
s O: l	t @r
psal-	ters
s O: l	t @r z
psalm
s Q l m
psalms
s Q l m z
pseu-	do
s u:	d @U
pseu-	do-	mo-	nas
s u:	d V	m @U	n V z
pseu-	do-	nym
s u:	d V	n I m
pseu-	do-	nyms
s u:	d V	n I m z
pseu-	do-	po-	di-	al
s u:	d V	p @U	d i:	V l
pseu-	do-	sci-	en-	ti-	fic
s u:	d @U	s aI	V n	t I	f I k
pseu-	do-	sci-	ence
s u:	d @U	s aI	V n s
psi
s aI
psi-	lo-	cy-	bin
s aI	l V	s aI	b V n
pso-	ri-	a-	sis
s @r	aI	V	s V s
psy-	che
s aI	k i:
psy-	che-	de-	lic
s aI	k V	d e	l I k
psy-	ches
s aI	k i: z
psy-	chi-	at-	ric
s aI	k i:	{ t	r I k
psy-	chi-	at-	rist
s V	k aI	V t	r V s t
psy-	chi-	at-	rists
s V	k aI	V t	r V s t s
psy-	chi-	at-	rist's
s V	k aI	V t	r V s t s
psy-	chi-	at-	ry
s aI	k aI	V t	r i:
psy-	chi-	cal
s aI	k I	k V l
psy-	chic
s aI	k I k
psy-	chics
s aI	k I k s
psy-	cho
s aI	k @U
psy-	cho-	a-	na-	ly-	sis
s aI	k @U	V	n {	l V	s V s
psy-	cho-	a-	na-	ly-	tic
s aI	k @U	{	n V	l I	t I k
psy-	cho-	a-	na-	lyst
s aI	k @U	{	n V	l V s t
psy-	cho-	bab-	ble
s aI	k @U	b {	b V l
psy-	cho-	dy-	na-	mic
s aI	k @U	d aI	n {	m I k
psy-	cho-	ge-	nic
s aI	k @U	dZ e	n I k
psy-	cho-	ki-	ne-	sis
s aI	k @U	k I	n i:	s I s
psy-	cho-	lo-	gi-	cal
s aI	k V	l Q	dZ I	k V l
psy-	cho-	lo-	gical-	ly
s aI	k V	l Q	dZ I k	l i:
psy-	cho-	lo-	gist
s aI	k Q	l V	dZ V s t
psy-	cho-	lo-	gists
s aI	k Q	l V	dZ V s t s
psy-	cho-	lo-	gy
s aI	k Q	l V	dZ i:
psy-	cho-	pa-	thic
s aI	k V	p {	T I k
psy-	cho-	pa-	thy
s aI	k Q	p V	T i:
psy-	cho-	path
s aI	k @U	p { T
psy-	cho-	paths
s aI	k @U	p { T s
psy-	cho-	sis
s aI	k @U	s I s
psy-	cho-	so-	ma-	tic
s aI	k @U	s V	m {	t I k
psy-	cho-	the-	ra-	peu-	tic
s aI	k @U	T e@	V p	j u:	t I k
psy-	cho-	the-	ra-	pist
s aI	k V	T e@	V	p V s t
psy-	cho-	the-	ra-	pists
s aI	k V	T e@	V	p V s t s
psy-	cho-	the-	ra-	py
s aI	k @U	T e@	V	p i:
psy-	cho-	tic
s aI	k Q	t I k
psych
s aI k
psyched
s aI k t
psyl-	li-	um
s I	l i:	V m
pto-	le-	ma-	ic
th Q	l V	m eI	I k
pto-	le-	my
th Q	l V	m i:
pto-	maine
th @U	m eI n
pto-	maines
th @U	m eI n z
pty
th aI
pu
ph u:
pu-	ber-	ty
ph j u:	b @r	t i:
pu-	bic
ph j u:	b I k
pu-	fahl
ph j u:	f Q l
pu-	get
ph j u:	dZ V t
pu-	la-	ski
ph j u:	l { s	k i:
pu-	lit-	zer
ph U	l I t	s @r
pu-	ma
ph u:	m V
pu-	ma's
ph j u:	m V z
pu-	mice
ph V	m I s
pu-	ni-	sha-	ble
ph V	n I	S V	b V l
pu-	ni-	shes
ph V	n I	S V z
pu-	ni-	shing
ph V	n I	S I N
pu-	ni-	tive
ph j u:	n I	t I v
pu-	nic
ph j u:	n I k
pu-	nish
ph V	n I S
pu-	nish-	ment
ph V	n I S	m V n t
pu-	nish-	ments
ph V	n I S	m V n t s
pu-	nished
ph V	n I S t
pu-	ny
ph j u:	n i:
pu-	pa
ph j u:	p V
pu-	pil
ph j u:	p I l
pu-	pils
ph j u:	p I l z
pu-	ra
ph U@	V
pu-	ree
ph j U@	eI
pu-	rer
ph j U@	@r
pu-	rest
ph j U@	V s t
pu-	rex
ph j U@	e k s
pu-	ri
ph U@	i:
pu-	ri-	fi-	ca-	tion
ph j U@	I	f I	k eI	S V n
pu-	ri-	fi-	er
ph j U@	I	f aI	@r
pu-	ri-	fi-	ers
ph j U@	I	f aI	@r z
pu-	ri-	fied
ph j U@	I	f aI d
pu-	ri-	fy
ph j U@	I	f aI
pu-	ri-	fy-	ing
ph j U@	I	f aI	I N
pu-	ri-	na
ph j U@	I	n V
pu-	ri-	ta-	ni-	cal
ph j U@	I	t {	n I	k V l
pu-	ri-	ta-	ni-	sm
ph j U@	I	t V	n I	z V m
pu-	ri-	ta-	ni-	sms
ph j U@	I	t V	n I	z V m z
pu-	ri-	tan
ph j U@	I	t V n
pu-	ri-	tans
ph j U@	I	t V n z
pu-	ri-	ty
ph j U@	I	t i:
pu-	rim
ph U@	I m
pu-	ring-	ton
ph j U@	I N	t V n
pu-	ris
ph j U@	I s
pu-	ris-	tic
ph j U@	I s	t I k
pu-	rist
ph j U@	I s t
pu-	rists
ph j U@	I s t s
pu-	san
ph u:	s Q n
pu-	sey
ph j u:	z i:
pu-	sher
ph U	S @r
pu-	shers
ph U	S @r z
pu-	shes
ph U	S V z
pu-	shing
ph U	S I N
pu-	shy
ph U	S i:
pu-	ta-	tive
ph j u:	t V	t I v
pu-	zo
ph u:	z @U
pub
ph V b
pub-	li-	ca-	tion
ph V b	l I	k eI	S V n
pub-	li-	ca-	tions
ph V b	l I	k eI	S V n z
pub-	li-	ca-	tion's
ph V b	l I	k eI	S V n z
pub-	li-	ci-	ty
ph V b	l I	s I	t i:
pub-	li-	ci-	zing
ph V b	l I	s aI	z I N
pub-	li-	cist
ph V b	l I	s I s t
pub-	li-	cists
ph V b	l I	s I s t s
pub-	li-	cize
ph V b	l I	s aI z
pub-	li-	cized
ph V b	l I	s aI z d
pub-	li-	sher
ph V b	l I	S @r
pub-	li-	shers
ph V b	l I	S @r z
pub-	li-	sher's
ph V b	l I	S @r z
pub-	li-	shes
ph V b	l I	S V z
pub-	li-	shing
ph V b	l I	S I N
pub-	li-	shings
ph V b	l I	S I N z
pub-	li-	shing's
ph V b	l I	S I N z
pub-	lic
ph V b	l I k
pub-	lic-	ly
ph V b	l I k	l i:
pub-	lical-	ly
ph V b	l I k	l i:
pub-	lics
ph V b	l I k s
pub-	lic's
ph V b	l I k s
pub-	lish
ph V b	l I S
pub-	lished
ph V b	l I S t
pubs
ph V b z
puc-	ci-	ni
ph u:	tS i:	n i:
puc-	ker
ph V	k @r
puc-	kett
ph V	k e t
puc-	kish
ph V	k I S
puck
ph V k
pud-	ding
ph U	d I N
pud-	dings
ph U	d I N z
pud-	dle
ph V	d V l
pud-	dles
ph V	d V l z
pud-	gy
ph V	dZ i:
pue-	bla
ph w eI b	l V
pue-	blo
ph w e b	l @U
pue-	rile
ph j u:	r i: l
puente
ph u: n t
puer-	to
ph w e@	t @U
puett
ph u: t
puf-	fe-	ry
ph V	f @r	i:
puf-	fer
ph V	f @r
puf-	fer's
ph V	f @r z
puf-	fin
ph V	f I n
puf-	fing
ph V	f I N
puf-	fins
ph V	f I n z
puf-	fy
ph V	f i:
puff
ph V f
puffed
ph V f t
puffs
ph V f s
pug-	li-	a
ph V g	l i:	V
pug-	na-	cious
ph V g	n {	S V s
pug-	wash
ph V g	w Q S
pugh
ph j u:
pughs
ph j u: z
puke
ph j u: k
pukes
ph j u: k s
pul-	len
ph U	l V n
pul-	ler
ph U	l @r
pul-	ley
ph U	l i:
pul-	leys
ph U	l i: z
pul-	ling
ph U	l I N
pul-	mo-	na-	ry
ph U l	m V	n e@	i:
pul-	mo-	zyme
ph U l	m @U	z aI m
pul-	ping
ph V l	p I N
pul-	pit
ph U l	p I t
pul-	pits
ph U l	p I t s
pul-	sa-	ting
ph V l	s eI	t I N
pul-	sar
ph U l	s @r
pul-	sar's
ph U l	s @r z
pul-	ses
ph V l	s V z
pul-	si-	fer
ph V l	s I	f @r
pul-	sing
ph V l	s I N
pull
ph U l
pull-	back
ph U l	b { k
pull-	backs
ph U l	b { k s
pull-	in
ph U	l I n
pull-	man
ph U l	m V n
pull-	man's
ph U l	m V n z
pull-	out
ph U	l aU t
pull-	outs
ph U	l aU t s
pulled
ph U l d
pulls
ph U l z
pulp
ph V l p
pulp-	wood
ph V l	p w U d
puls
ph U l z
pulse
ph V l s
pum-	me-	ling
ph V	m V	l I N
pum-	mel
ph V	m V l
pum-	meled
ph V	m V l d
pum-	per-	nic-	kel
ph V m	p @r	n I	k V l
pum-	ping
ph V m	p I N
pump
ph V m p
pump-	kin
ph V m	p k I n
pump-	kins
ph V m	p k I n z
pumped
ph V m p t
pumps
ph V m p s
pun
ph V n
pun-	ches
ph V n	tS V z
pun-	ching
ph V n	tS I N
pun-	chy
ph V n	tS i:
pun-	dit
ph V n	d I t
pun-	dit-	ry
ph V n	d I t	r i:
pun-	dits
ph V n	d I t s
pun-	gent
ph V n	dZ V n t
pun-	gent-	ly
ph V n	dZ V n	t l i:
pun-	jab
ph V n	dZ Q b
pun-	jab's
ph V n	dZ Q b z
pun-	kin
ph V N	k I n
pun-	ky
ph V N	k i:
pun-	ta
ph U n	t @r
pun-	ter
ph V n	t @r
pun-	to
ph u: n	t @U
punc-	tate
ph V n	k t eI t
punc-	ti-	li-	ous
ph V N	k t I	l i:	V s
punc-	tu-	a-	li-	ty
ph V N	k tS u:	{	l I	t i:
punc-	tu-	a-	ted
ph V N	k tS u:	eI	t V d
punc-	tu-	a-	ting
ph V N	k tS u:	eI	d I N
punc-	tu-	a-	tion
ph V N	k tS u:	eI	S V n
punc-	tu-	ate
ph V N	k tS u:	eI t
punc-	tu-	ring
ph V N	k tS @r	I N
punc-	ture
ph V N	k tS @r
punc-	tured
ph V N	k tS @r d
punc-	tures
ph V N	k tS @r z
punch
ph V n tS
punch-	line
ph V n	tS l aI n
punched
ph V n tS t
pung
ph V N
punk
ph V N k
punks
ph V N k s
puns
ph V n z
punt
ph V n t
punts
ph V n t s
pup
ph V p
pup-	pe-	teer
ph V	p V	t i: r
pup-	pe-	teers
ph V	p V	t i: r z
pup-	pet
ph V	p V t
pup-	pet-	ry
ph V	p V t	r i:
pup-	pets
ph V	p V t s
pup-	pies
ph V	p i: z
pup-	py
ph V	p i:
pups
ph V p s
pur
ph @r
pur-	cell
ph @r	s e l
pur-	cha-	ser
ph @r	tS V	s @r
pur-	cha-	sers
ph @r	tS V	s @r z
pur-	cha-	ser's
ph @r	tS V	s @r z
pur-	cha-	ses
ph @r	tS V	s V z
pur-	chase
ph @r	tS V s
pur-	chased
ph @r	tS V s t
pur-	din
ph @r	d I n
pur-	don
ph @r	d V n
pur-	due
ph @r	d u:
pur-	dum
ph @r	d V m
pur-	dy
ph @r	d i:
pur-	ga-	to-	ry
ph @r	g V	t O@	i:
pur-	ges
ph @r	dZ V z
pur-	ging
ph @r	dZ I N
pur-	loin
ph @r	l OI n
pur-	loined
ph @r	l OI n d
pur-	ple
ph @r	p V l
pur-	ples
ph @r	p V l z
pur-	po-	ses
ph @r	p V	s V z
pur-	por-	ted
ph @r	p O@	t V d
pur-	por-	ted-	ly
ph @r	p O@	t V d	l i:
pur-	por-	ting
ph @r	p O@	t I N
pur-	port
ph @r	p O@ t
pur-	ports
ph @r	p O@ t s
pur-	pose
ph @r	p V s
pur-	pose-	ful
ph @r	p V s	f V l
pur-	pose-	ful-	ly
ph @r	p V s	f V	l i:
pur-	pose-	less
ph @r	p V s	l V s
pur-	pose-	ly
ph @r	p V s	l i:
pur-	ring
ph @r	I N
pur-	ser
ph @r	s @r
pur-	ses
ph @r	s V z
pur-	su-	ant
ph @r	s u:	V n t
pur-	su-	er
ph @r	s u:	@r
pur-	su-	ers
ph @r	s u:	@r z
pur-	su-	ing
ph @r	s u:	I N
pur-	sue
ph @r	s u:
)"
R"(pur-	sued
ph @r	s u: d
pur-	sues
ph @r	s u: z
pur-	suit
ph @r	s u: t
pur-	suits
ph @r	s u: t s
pur-	ve-	yor
ph @r	v eI	@r
pur-	ve-	yors
ph @r	v eI	@r z
pur-	vey
ph @r	v eI
pur-	view
ph @r v	j u:
pur-	vis
ph @r	v I s
pur-	year
ph @r	j I@
pure
ph j U@
pure-	ly
ph j U@	l i:
pureb-	red
ph j U@ b	r e d
pureb-	reds
ph j U@ b	r e d z
purge
ph @r dZ
purged
ph @r dZ d
purp-	lish
ph @r p	l I S
purr
ph @r
purrs
ph @r z
purs-	ley
ph @r s	l i:
purse
ph @r s
pursed
ph @r s t
pus
ph V s
pus-	ses
ph U	s V z
pus-	sy
ph U	s i:
pus-	sy-	cat
ph U	s i:	k { t
push
ph U S
push-	kin
ph U S	k I n
push-	o-	ver
ph U	S @U	v @r
push-	up
ph U	S V p
push-	ups
ph U	S V p s
pushed
ph U S t
puss
ph U s
put
ph U t
put-	down
ph U t	d aU n
put-	nam
ph V t	n V m
put-	nam's
ph V t	n V m z
put-	ney
ph V t	n i:
put-	on
ph U	t Q n
put-	ons
ph U	t Q n z
put-	rid
ph j u: t	r I d
put-	te-	rer
ph V	t @r	@r
put-	te-	ring
ph V	t @r	I N
put-	ted
ph V	t V d
put-	ter
ph V	t @r
put-	ters
ph V	t @r z
put-	ting
ph V	t I N
put-	ty
ph V	t i:
puts
ph U t s
putsch
ph U tS
putt
ph V t
putt-	nam
ph V t	n V m
putt-	nam's
ph V t	n V m z
putts
ph V t s
putz
ph V t s
puz-	z-	ling
ph V	z V	l I N
puz-	zle
ph V	z V l
puz-	zle-	ment
ph V	z V l	m V n t
puz-	zled
ph V	z V l d
puz-	zles
ph V	z V l z
puzz-	ler
ph V z	l @r
py-	att
ph aI	V t
py-	lo-	ri
ph aI	l O@	i:
py-	lon
ph aI	l Q n
py-	lons
ph aI	l Q n z
py-	los
ph aI	l @U s
py-	ra-	mi-	dal
ph @r	{	m I	d V l
py-	ra-	mid
ph I@	V	m V d
py-	ra-	mids
ph I@	V	m I d z
py-	re-	na
ph I@	i:	n V
py-	re-	nees
ph I@	V	i: z
py-	rite
ph aI	r aI t
py-	ro
ph aI	r @U
py-	ro-	tech-	nic
ph aI	r @U	t e k	n I k
py-	ro-	tech-	nics
ph aI	r @U	t e k	n I k s
py-	ro-	xene
ph aI	r Q k	s i: n
py-	thi-	a
ph I	T i:	V
py-	thon
ph aI	T Q n
py-	thon's
ph aI	T Q n z
py-	xis
ph I k	s I s
pye
ph aI
pyg-	ma-	lion
ph I g	m eI l	j V n
pyg-	mies
ph I g	m i: z
pyg-	my
ph I g	m i:
pyke
ph aI k
pyle
ph aI l
pyne
ph aI n
pynes
ph aI n z
pyong-	yang
ph j O: N	j { N
pyong-	yang's
ph j O: N	j { N z
pyr-	rhic
ph I@	I k
q
kh j u:
q.
kh j u:
qa-	tar
kh V	t Q@
qan-	tas
kh Q n	t V s
qi
kh i:
qing-	dao
tS I N	d aU
qom
kh Q m
q's
kh j u: z
qu
kh u:
qua
kh w Q
qua-	ker
kh w eI	k @r
qua-	kers
kh w eI	k @r z
qua-	ker's
kh w eI	k @r z
qua-	king
kh w eI	k I N
qua-	li-	fi-	ca-	tion
kh w Q	l I	f I	k eI	S V n
qua-	li-	fi-	ca-	tions
kh w Q	l I	f I	k eI	S V n z
qua-	li-	fi-	er
kh w Q	l I	f aI	@r
qua-	li-	fi-	ers
kh w Q	l I	f aI	@r z
qua-	li-	fied
kh w Q	l I	f aI d
qua-	li-	fies
kh w Q	l I	f aI z
qua-	li-	fy
kh w Q	l I	f aI
qua-	li-	fy-	ing
kh w Q	l I	f aI	I N
qua-	li-	ta-	tive
kh w Q	l I	t eI	t I v
qua-	li-	ta-	tive-	ly
kh w Q	l I	t eI	t I v	l i:
qua-	li-	ties
kh w Q	l I	t i: z
qua-	li-	ty
kh w Q	l I	t i:
qua-	ran-	te
kh w @r	Q n	t eI
qua-	ran-	ti-	ning
kh w O@	V n	t i:	n I N
qua-	ran-	tine
kh w O@	V n	t i: n
qua-	ran-	tined
kh w O@	V n	t i: n d
qua-	ran-	tines
kh w O@	V n	t i: n z
qua-	sar
kh w eI	z Q@
qua-	shing
kh w O:	S I N
qua-	si
kh w Q	s i:
qua-	si-	mo-	do
kh {	z i:	m @U	d @U
qua-	ter-	na-	ry
kh w Q	t @r	n e@	i:
quac-	ke-	ry
kh w {	k @r	i:
quac-	ken-	bush
kh w {	k V n	b U S
quack
kh w { k
quacks
kh w { k s
quad
kh w Q d
quad-	ra
kh w { d	r V
quad-	rant
kh w Q d	r V n t
quad-	ren-	ni-	al
kh w Q d	r e	n i:	V l
quad-	ri-	ceps
kh w Q d	r I	s e p s
quad-	rip-	le-	gic
kh w Q d	r I p	l i:	dZ I k
quad-	ru-	p-	ling
kh w Q d	r u:	p V	l I N
quad-	ru-	ple
kh w Q d	r u:	p V l
quad-	ru-	pled
kh w Q d	r u:	p V l d
quads
kh w Q d z
quag-	mi-	re
kh w { g	m aI	@r
quai
kh i:
quail
kh w eI l
quails
kh w eI l z
quain-	tance
kh w eI n	t V n s
quaint
kh w eI n t
quaint-	ly
kh w eI n	t l i:
quake
kh w eI k
quakes
kh w eI k s
qual
kh w Q l
quale
kh w eI l
qualms
kh w Q m z
quam
kh w Q m
quan
kh w O: n
quan-	da-	ries
kh w Q n	d @r	i: z
quan-	da-	ry
kh w Q n	d @r	i:
quan-	ti-	co
kh w Q n	t I	k @U
quan-	ti-	fi-	a-	ble
kh w Q n	t I	f aI	V	b e l
quan-	ti-	fi-	ca-	tion
kh w Q n	t I	f I	k eI	S V n
quan-	ti-	fied
kh w Q n	t I	f aI d
quan-	ti-	fy
kh w Q n	t I	f aI
quan-	ti-	fy-	ing
kh w Q n	t I	f aI	I N
quan-	ti-	ta-	tive
kh w Q n	t I	t eI	t I v
quan-	ti-	ta-	tive-	ly
kh w Q n	t I	t eI	t I v	l i:
quan-	ti-	ties
kh w Q n	t I	t i: z
quan-	ti-	ty
kh w Q n	t I	t i:
quan-	tum
kh w Q n	t V m
quan-	tum's
kh w Q n	t V m z
quant
kh w { n t
quar-	re-	ling
kh w Q@	V	l I N
quar-	rel
kh w O@	V l
quar-	rel-	some
kh w O@	V l	s V m
quar-	reled
kh w O@	V l d
quar-	rels
kh w O@	V l z
quar-	ries
kh w O@	i: z
quar-	ry
kh w O@	i:
quar-	ry-	ing
kh w O@	i:	I N
quar-	ter
kh w O@	t @r
quar-	ter-	bac-	king
kh w O@	t @r	b {	k I N
quar-	ter-	back
kh w O@	t @r	b { k
quar-	ter-	backs
kh w O@	t @r	b { k s
quar-	ter-	deck
kh w O@	t @r	d e k
quar-	ter-	ly
kh w O@	t @r	l i:
quar-	ter-	man
kh w O@	t @r	m V n
quar-	ter-	mas-	ter
kh w O@	t @r	m { s	t @r
quar-	ters
kh w O@	t @r z
quar-	ter's
kh w O@	t @r z
quar-	tet
kh w O@	t e t
quar-	tets
kh w O@	t e t s
quar-	tet's
kh w O@	t e t s
quar-	tile
kh w O@	t I l
quar-	to
kh w O@	t @U
quark
kh w Q@ k
quarks
kh w Q@ k s
quarles
kh w O@ l z
quart
kh w O@ t
quarts
kh w O@ t s
quartz
kh w O@ t s
quas-	si-	a
kh w Q	S i:	V
quash
kh w O: S
quashed
kh w O: S t
quave
kh w eI v
quay
kh i:
quayle
kh w eI l
quayle's
kh w eI l z
que
kh j u:
que-	be-	cois
kh w e	b e k	w Q
que-	bec
kh w V	b e k
que-	bec-	ker
kh w V	b e	k @r
que-	bec-	kers
kh w V	b e	k @r z
que-	bec's
kh w V	b e k s
que-	chee
kh w e	tS i:
que-	moy
kh w V	m OI
que-	ri-	da
kh w e@	i:	d V
que-	ried
kh w I@	i: d
que-	ries
kh w I@	i: z
que-	ru-	lous
kh w e@	V	l V s
que-	ry
kh w i:	r i:
que-	sa-	da
kh w eI	s Q	d V
quea-	si-	ness
kh w i:	z i:	n V s
quea-	sy
kh w i:	z i:
quee-	na
kh w i:	n V
quee-	nie
kh w i:	n i:
quee-	rer
kh w I@	@r
queen
kh w i: n
queen-	fi-	sh's
kh w i: n	f I	S V z
queen-	fish
kh w i: n	f I S
queens
kh w i: n z
queen's
kh w i: n z
queens-	ber-	ry
kh w i: n	z b e@	i:
queens-	land
kh w i: n	z l { n d
queer
kh w I@
queers
kh w I@ z
quel-	ling
kh w e	l I N
quell
kh w e l
quelled
kh w e l d
quen-	by
kh w e n	b i:
quen-	cher
kh w e n	tS @r
quen-	chers
kh w e n	tS @r z
quen-	ching
kh w e n	tS I N
quen-	tin
kh w e n	t I n
quench
kh w e n tS
querns
kh w @r n z
ques
kh j u: z
ques-	nel
kh w eI s	n e l
ques-	tio-	na-	ble
kh w e s	tS V	n V	b V l
ques-	tio-	ner
kh w e s	tS V	n @r
ques-	tio-	ners
kh w e s	tS V	n @r z
ques-	tio-	ning
kh w e s	tS V	n I N
ques-	tio-	nings
kh w e s	tS V	n I N z
ques-	tion
kh w e s	tS V n
ques-	tion-	mark
kh w e s	tS V n	m Q@ k
ques-	tion-	naire
kh w e s	tS V	n e@
ques-	tion-	naires
kh w e s	tS V	n e@ z
ques-	tioned
kh w e s	tS V n d
ques-	tions
kh w e s	tS V n z
ques-	tion's
kh w e s	tS V n z
quest
kh w e s t
quests
kh w e s t s
queu-	ing
kh j u:	I N
queue
kh j u:
queues
kh j u: z
qui
kh w i:
qui-	e-	scent
kh w aI	e	s V n t
qui-	e-	ted
kh w aI	V	t V d
qui-	e-	ter
kh w aI	V	t @r
qui-	e-	test
kh w aI	V	t V s t
qui-	e-	ting
kh w aI	V	t I N
qui-	e-	tist
kh w aI	V	t V s t
qui-	et
kh w aI	V t
qui-	et-	ly
kh w aI	V t	l i:
qui-	et-	ness
kh w aI	V t	n V s
qui-	ets
kh w aI	V t s
qui-	les
kh w i:	l e s
qui-	na
kh w i:	n V
qui-	nine
kh w aI	n aI n
qui-	non
kh w I	n V n
qui-	nones
kh w V	n @U n z
qui-	ring
kh w aI	r I N
qui-	to
kh w i:	t @U
qui-	to's
kh w i:	t @U z
qui-	ve-	ring
kh w I	v @r	I N
qui-	ver
kh w I	v @r
qui-	xo-	te
kh i:	h @U	t i:
qui-	xo-	tic
kh w I k	s Q	t I k
quib-	b-	ling
kh w I	b V	l I N
quib-	ble
kh w I	b V l
quib-	bles
kh w I	b V l z
quic-	ke-	ning
kh w I	k V	n I N
quic-	kel
kh w I	k V l
quic-	ken
kh w I	k V n
quic-	kened
kh w I	k V n d
quic-	kens
kh w I	k V n z
quic-	ker
kh w I	k @r
quic-	kest
kh w I	k V s t
quic-	kie
kh w I	k i:
quiche
kh i: S
quick
kh w I k
quick-	ly
kh w I k	l i:
quick-	ness
kh w I k	n V s
quick-	sand
kh w I k	s { n d
quick-	sands
kh w I k	s { n d z
quick-	sil-	ver
kh w I k	s I l	v @r
quid
kh w I d
quig-	ley
kh w I g	l i:
quil-	lan
kh w I	l V n
quil-	ling
kh w I	l I N
quil-	lon
kh w I	l V n
quil-	ted
kh w I l	t V d
quil-	ter
kh w I l	t @r
quil-	ters
kh w I l	t @r z
quil-	ting
kh w I l	t I N
quill
kh w I l
quill-	man
kh w i: l	m { n
quilmes
kh w I l m z
quilt
kh w I l t
quilts
kh w I l t s
quim-	by
kh w I m	b i:
quin
kh w I n
quin-	by
kh w I n	b i:
quin-	cey
kh w I n	s i:
quin-	cy
kh w I n	s i:
quin-	cy's
kh w I n	s i: z
quin-	lan
kh w I n	l V n
quin-	ta
kh w I n	t V
quin-	ta-	na
kh w i: n	t {	n V
quin-	tal
kh w I n	t V l
quin-	te-	ro
kh w i: n	t e@	@U
quin-	ter
kh w I n	t @r
quin-	tes-	sen-	tial
kh w I n	t V	s e n	S V l
quin-	tes-	sen-	tial-	ly
kh w I n	t V	s e n	tS V	l i:
quin-	tes-	sence
kh w I n	t e	s V n s
quin-	tet
kh w I n	t e t
quin-	ti-	na
kh w i: n	t i:	n V
quin-	tile
kh w I n	t I l
quin-	tin
kh w I n	t I n
quin-	to
kh w I n	t @U
quin-	ton
kh w I n	t O: n
quin-	tu-	ple
kh w I n	t u:	p V l
quin-	tu-	pled
kh w I n	t j u:	p V l d
quin-	tup-	let
kh w I n	t V p	l V t
quin-	tup-	lets
kh w I n	t V p	l V t s
quince
kh w I n s
quine
kh w aI n
quinn
kh w I n
quinn's
kh w I n z
quint
kh w I n t
quints
kh w I n t s
quip
kh w I p
quipped
kh w I p t
quips
kh w I p s
quir-	ky
kh w @r	k i:
quire
kh w aI r
quirk
kh w @r k
quirks
kh w @r k s
quis-	ling
kh w I z	l I N
quist
kh w I s t
quist's
kh w I s t s
quit
kh w I t
quit-	ter
kh w I	t @r
quit-	ters
kh w I	t @r z
quit-	ting
kh w I	t I N
quite
kh w aI t
quits
kh w I t s
quiz
kh w I z
quiz-	zes
kh w I	z V z
quiz-	zi-	cal
kh w I	z I	k V l
quiz-	zing
kh w I	z I N
quizzed
kh w I z d
quo
kh w @U
quo-	rum
kh w O@	V m
quo-	rums
kh w O@	V m z
quo-	ta
kh w @U	t V
quo-	ta-	ble
kh w @U	t V	b V l
quo-	ta-	tion
kh w @U	t eI	S V n
quo-	ta-	tions
kh w @U	t eI	S V n z
quo-	tas
kh w @U	t V z
quo-	ted
kh w @U	t V d
quo-	tient
kh w @U	S V n t
quo-	ting
kh w @U	t I N
quote
kh w @U t
quotes
kh w @U t s
r
Q@
r-	b
Q@	b i:
r-	e-	va-	lu-	a-	tions
r i:	I	v { l	j u:	eI	S V n z
r-	p-	m
Q@	p i:	e m
r-	wan-	da
r V	w Q n	d V
r-	wan-	dan
r V	w Q n	d V n
r-	wan-	dans
r V	w Q n	d V n z
r-	wan-	da's
r V	w Q n	d V z
r-	wan-	dese
r V	w Q	d i: z
r.
Q@
ra
r Q
ra-	bi
r Q	b i:
ra-	bi-	no-	witz
r V	b I	n V	w I t s
ra-	bid
r {	b I d
ra-	bies
r eI	b i: z
ra-	bin
r Q	b i: n
ra-	bin's
r Q	b i: n z
ra-	ca-	mier
r {	k V	m aI r
ra-	cemes
r eI	s i: m z
ra-	cer
r eI	s @r
ra-	cers
r eI	s @r z
ra-	ces
r eI	s V z
ra-	ce's
r eI	s V z
ra-	cette
r V	s e t
ra-	chel
r eI	tS V l
ra-	chelle
r V	S e l
ra-	chel's
r eI	tS V l z
ra-	ci-	ness
r eI	s i:	n V s
ra-	ci-	sm
r eI	s I	z V m
ra-	cia-	li-	sm
r eI	S V	l I	z V m
ra-	cial
r eI	S V l
ra-	cial-	ly
r eI	S V	l i:
ra-	cine
r V	s i: n
ra-	cing
r eI	s I N
ra-	cist
r eI	s I s t
ra-	cists
r eI	s I s t s
ra-	di-	a-	ted
r eI	d i:	eI	t V d
ra-	di-	a-	ting
r eI	d i:	eI	t I N
ra-	di-	a-	tion
r eI	d i:	eI	S V n
ra-	di-	a-	tion's
r eI	d i:	eI	S V n z
ra-	di-	a-	tor
r eI	d i:	eI	t @r
ra-	di-	a-	tors
r eI	d i:	eI	t @r z
ra-	di-	al-	ly
r eI	d i:	V	l i:
ra-	di-	als
r eI	d i:	V l z
ra-	di-	ance
r eI	d i:	V n s
ra-	di-	ant
r eI	d i:	V n t
ra-	di-	ate
r eI	d i:	eI t
ra-	di-	ates
r eI	d i:	eI t s
ra-	di-	ca-	li-	sm
r {	d I	k V	l I	z V m
ra-	di-	ca-	li-	za-	tion
r {	d I	k V	l V	z eI	S V n
ra-	di-	ca-	lize
r {	d I	k V	l aI z
ra-	di-	ca-	lized
r {	d I	k V	l aI z d
ra-	di-	cal
r {	d I	k V l
ra-	di-	cals
r {	d I	k V l z
ra-	di-	o
r eI	d i:	@U
ra-	di-	o-	ac-	ti-	vi-	ty
r eI	d i:	@U	{ k	t I	v I	t i:
ra-	di-	o-	ac-	tive
r eI	d i:	@U	{ k	t I v
ra-	di-	o-	gra-	phy
r eI	d i:	Q g	r V	f i:
ra-	di-	o-	lo-	gi-	cal
r eI	d i:	V	l Q	dZ I	k V l
ra-	di-	o-	lo-	gist
r eI	d i:	Q	l V	dZ V s t
ra-	di-	o-	lo-	gists
r eI	d i:	Q	l V	dZ V s t s
ra-	di-	o-	lo-	gy
r eI	d i:	Q	l V	dZ i:
ra-	di-	o-	man
r eI	d i:	@U	m { n
ra-	di-	oed
r eI	d i:	@U d
ra-	di-	os
r eI	d i:	@U z
ra-	di-	o's
r eI	d i:	@U z
ra-	di-	shes
r {	d I	S V z
ra-	di-	um
r eI	d i:	V m
ra-	di-	us
r eI	d i:	V s
ra-	dical-	ly
r {	d I k	l i:
ra-	dis-	son
r {	d I	s V n
ra-	dish
r {	d I S
ra-	don
r eI	d Q n
ra-	du
r Q	d u:
ra-	fa-	el
r Q	f aI	e l
ra-	fale
r V	f eI l
ra-	fi
r {	f i:
ra-	gan
r eI	g V n
ra-	gas
r Q	g V z
ra-	gen
r {	g V n
ra-	ger
r eI	g @r
ra-	ges
r eI	dZ V z
ra-	ging
r eI	dZ I N
ra-	gle
r eI	g V l
ra-	go
r Q	g @U
ra-	gu-	sa
r Q	g u:	s V
ra-	guc-	ci
r Q	g u:	tS i:
ra-	hal
r V	h Q l
ra-	i
r Q	i:
ra-	in-	ger
r Q	I	N @r
ra-	jew-	ski
r aI	e f	s k i:
ra-	jiv
r Q	dZ i: v
ra-	ker
r eI	k @r
ra-	kers
r eI	k @r z
ra-	king
r eI	k I N
ra-	kish
r eI	k I S
ra-	leigh
r O:	l i:
ra-	leigh's
r O:	l i: z
ra-	ma
r Q	m V
ra-	ma-	da
r V	m Q	d V
ra-	ma-	dan
r {	m V	d V n
ra-	ma-	da's
r V	m Q	d V z
ra-	mage
r {	m I dZ
ra-	man
r eI	m V n
ra-	mat
r {	m { t
ra-	me-	ses
r {	m V	s i: z
ra-	mer
r eI	m @r
ra-	mes-	ses
r {	m V	s V z
ra-	mey
r {	m i:
ra-	mi
r Q	m i:
ra-	mi-	fi-	ca-	tion
r {	m I	f I	k eI	S V n
ra-	mi-	fi-	ca-	tions
r {	m I	f I	k eI	S V n z
ra-	mi-	fy
r {	m I	f aI
ra-	mi-	rez
r V	m I@	e z
ra-	mi-	ro
r V	m I@	@U
ra-	mo
r eI	m @U
ra-	mo-	na
r V	m @U	n V
ra-	mon
r V	m @U n
ra-	mon-	da
r V	m Q n	d V
ra-	mos
r Q	m @U s
ra-	mus
r eI	m V s
ra-	na
r {	n V
ra-	nee
r {	n i:
ra-	ney
r eI	n i:
ra-	ni
r Q	n i:
ra-	ni-	a
r Q	n i:	V
ra-	oul
r Q	u: l
ra-	pa-	cious
r V	p {	S V s
ra-	per
r eI	p @r
ra-	pers
r eI	p @r z
ra-	pha-	el
r Q	f aI	e l
ra-	phae-	la
r {	f eI	l V
ra-	pi-	di-	ty
r V	p I	d V	t i:
ra-	pi-	er
r eI	p i:	@r
ra-	pid
r {	p I d
ra-	pid-	ly
r {	p I d	l i:
ra-	pids
r {	p I d z
ra-	ping
r eI	p I N
ra-	pist
r eI	p I s t
ra-	pists
r eI	p I s t s
ra-	pist's
r eI	p I s t s
ra-	quel
r V	k e l
ra-	ra
r Q@	V
ra-	re-	fied
r e@	V	f aI d
ra-	re-	fy
r e@	V	f aI
ra-	rer
r e@	@r
ra-	rest
r e@	V s t
ra-	ri-	tan
r e@	I	t V n
ra-	ri-	ties
r e@	I	t i: z
ra-	ri-	ty
r e@	I	t i:
ra-	ser
r eI	z @r
ra-	shes
r {	S V z
ra-	shid
r V	S i: d
ra-	si-	a
r Q	s i:	V
ra-	ta
r {	t V
ra-	ted
r eI	t V d
ra-	ter
r eI	t @r
ra-	ters
r eI	t @r z
ra-	ther
r {	D @r
ra-	ther's
r {	D @r z
ra-	ti-	fi-	ca-	tion
r {	t I	f I	k eI	S V n
ra-	ti-	fied
r {	t I	f aI d
ra-	ti-	fies
r {	t I	f aI z
ra-	ti-	fy
r {	t I	f aI
ra-	ti-	fy-	ing
r {	t I	f aI	I N
ra-	ti-	o
r eI	S i:	@U
ra-	ti-	os
r eI	S i:	@U z
ra-	ting
r eI	t I N
ra-	tings
r eI	t I N z
ra-	tio-	na-	li-	ty
r {	S V	n {	l I	t i:
ra-	tio-	na-	li-	za-	tion
r {	S V	n V	l I	z eI	S V n
ra-	tio-	na-	li-	za-	tions
r {	S V	n V	l I	z eI	S V n z
ra-	tio-	na-	li-	zing
r {	S V	n V	l aI	z I N
ra-	tio-	na-	lize
r {	S V	n V	l aI z
ra-	tio-	na-	lized
r {	S V	n V	l aI z d
ra-	tio-	nal
r {	S V	n V l
ra-	tio-	nal-	ly
r {	S V	n V	l i:
ra-	tio-	nale
r {	S V	n { l
ra-	tio-	nales
r {	S V	n { l z
ra-	tio-	ning
r {	S V	n I N
ra-	tion
r {	S V n
ra-	tioned
r {	S V n d
ra-	tions
r {	S V n z
ra-	ton
r V	t @U n
ra-	tu
r Q	t u:
ra-	va-	ges
r {	v I	dZ V z
ra-	va-	ging
r {	v I	dZ I N
ra-	vage
r {	v I dZ
ra-	vaged
r {	v I dZ d
ra-	ve-	ling
r {	v V	l I N
ra-	ve-	nel
r {	v V	n e l
ra-	ve-	nous
r {	v V	n V s
ra-	vel
r {	v V l
ra-	veled
r {	v V l d
ra-	vel's
r V	v e l z
ra-	ven
r eI	v V n
ra-	ven-	na
r V	v e	n V
ra-	vens
r eI	v V n z
ra-	vens-	wood
r eI	v V n	z w U d
ra-	ver
r eI	v @r
ra-	vi
r Q	v i:
ra-	vi-	o-	li
r {	v i:	@U	l i:
ra-	vi-	shing
r {	v I	S I N
ra-	vin
r {	v I n
ra-	vine
r V	v i: n
ra-	vines
r V	v i: n z
ra-	ving
r eI	v I N
ra-	vi's
r Q	v i: s
ra-	wal-	pin-	di
r {	w O: l	p I n	d i:
ra-	ya
r eI	V
ra-	yon
r eI	V n
ra-	zing
r eI	z I N
ra-	zor
r eI	z @r
ra-	zor-	back
r eI	z @r	b { k
ra-	zor-	backs
r eI	z @r	b { k s
ra-	zor-	back's
r eI	z @r	b { k s
ra-	zors
r eI	z @r z
ra-	zor's
r eI	z @r z
raab
r Q b
raab's
r Q b z
raad
r Q d
raap
r Q p
raasch
r Q S
rab
r { b
rab-	bi
r {	b aI
rab-	bi-	ni-	cal
r V	b I	n I	k V l
rab-	bis
r {	b aI z
rab-	bit
r {	b I t
rab-	bit-	like
r {	b I t	l aI k
rab-	bits
r {	b I t s
rab-	ble
r {	b V l
rab-	kin
r { b	k I n
rabe
r eI b
rac-	coon
r {	k u: n
rac-	coons
r {	k u: n z
rac-	ke-	tee-	ring
r {	k V	t I@	I N
rac-	ke-	teer
r {	k V	t I@
rac-	ke-	teers
r {	k V	t I@ z
rac-	ker
r {	k @r
rac-	kers
r {	k @r z
rac-	ket
r {	k V t
rac-	kets
r {	k V t s
rac-	king
r {	k I N
race
r eI s
race-	hor-	ses
r eI s	h O@	s V z
race-	horse
r eI s	h O@ s
race-	track
r eI s	t r { k
race-	tracks
r eI s	t r { k s
race-	way
r eI s	w eI
raced
r eI s t
rach
r { tS
rach-	ma-	ni-	noff
r { k	m {	n I	n O: f
rack
r { k
racked
r { k t
rad-	ke
r eI d	k i:
rad-	ley
r { d	l i:
rad-	loff
r { d	l O: f
rad-	man
r { d	m V n
rad-	mil-	la
r { d	m I	l V
rad-	nor
r { d	n @r
rae
r eI
rae-	burn
r eI	b @r n
raf
r { f
raf-	fer-	ty
r {	f @r	t i:
raf-	fish
r {	f I S
raf-	fle
r {	f V l
raf-	fles
r {	f V l z
)"
R"(raf-	fo
r {	f @U
raf-	san-	ja-	ni
r { f	s V n	dZ Q	n i:
raf-	ted
r { f	t V d
raf-	ter
r { f	t @r
raf-	ters
r { f	t @r z
raf-	ting
r { f	t I N
rafe
r eI f
raff
r { f
raft
r { f t
rafts
r { f t s
rag
r { g
rag-	ge-	dy
r {	g V	d i:
rag-	ged
r {	g V d
rag-	land
r { g	l V n d
rag-	lin
r { g	l I n
rag-	men
r { g	m V n
rag-	tag
r { g	t { g
rag-	time
r { g	t aI m
rag-	weed
r { g	w i: d
rage
r eI dZ
raged
r eI dZ d
rags
r { g z
rags-	dale
r { g	z d eI l
rah
r Q
rah-	man
r Q	m V n
rah-	man's
r Q	m V n z
rah-	way
r Q	w eI
rahm
r { m
rai-	a
r Q	j V
rai-	ded
r eI	d V d
rai-	der
r eI	d @r
rai-	ders
r eI	d @r z
rai-	der's
r eI	d @r z
rai-	ding
r eI	d I N
rai-	ford
r eI	f @r d
rai-	ling
r eI	l I N
rai-	lings
r eI	l I N z
rai-	mon-	di
r V	m @U n	d i:
rai-	mon-	do
r eI	m Q n	d @U
rai-	na
r eI	n V
rai-	ner
r eI	n @r
rai-	ni-	est
r eI	n i:	V s t
rai-	nie
r eI	n i:
rai-	nier
r eI	n I@
rai-	ning
r eI	n I N
rai-	ny
r eI	n i:
rai-	ser
r eI	z @r
rai-	sers
r eI	z @r z
rai-	ses
r eI	z V z
rai-	sin
r eI	z I n
rai-	sing
r eI	z I N
rai-	sins
r eI	z I n z
rai-	son
r eI	s Q n
raid
r eI d
raids
r eI d z
rail
r eI l
rail-	car
r eI l	k Q@
rail-	cars
r eI l	k Q@ z
rail-	roa-	ded
r eI l	r @U	d V d
rail-	roa-	ding
r eI l	r @U	d I N
rail-	road
r eI l	r @U d
rail-	roads
r eI l	r @U d z
rail-	road's
r eI l	r @U d z
rail-	way
r eI l	w eI
rail-	ways
r eI l	w eI z
rail-	way's
r eI l	w eI z
raile
r eI l
railed
r eI l d
rails
r eI l z
rail's
r eI l z
rain
r eI n
rain-	bow
r eI n	b @U
rain-	bows
r eI n	b @U z
rain-	coat
r eI n	k @U t
rain-	coats
r eI n	k @U t s
rain-	coat's
r eI n	k @U t s
rain-	drop
r eI n	d r Q p
rain-	drops
r eI n	d r Q p s
rain-	fall
r eI n	f O: l
rain-	falls
r eI n	f O: l z
rain-	fo-	rest
r aI n	f O@	V s t
rain-	fo-	rests
r aI n	f O@	V s t s
rain-	ma-	ker
r eI n	m eI	k @r
rain-	storm
r eI n	s t O@ m
rain-	storms
r eI n	s t O@ m z
rain-	wa-	ter
r eI n	w O:	t @r
raine
r eI n
rained
r eI n d
raines
r eI n z
rains
r eI n z
raise
r eI z
raised
r eI z d
rait
r eI t
raj
r Q Z
rake
r eI k
raked
r eI k t
rakes
r eI k s
ral-	lied
r {	l i: d
ral-	lies
r {	l i: z
ral-	ly
r {	l i:
ral-	ly-	ing
r {	l i:	I N
ral-	ston
r O: l	s t V n
ral-	ston's
r Q l	s t V n z
rales
r eI l z
ralf
r Q l f
rall
r O: l
ralls
r O: l z
ralph
r { l f
ralphs
r { l f s
ralph's
r { l f s
ram
r { m
ram-	berg
r { m	b @r g
ram-	bert
r { m	b @r t
ram-	ble
r { m	b V l
ram-	bled
r { m	b V l d
ram-	bo
r { m	b @U
ram-	bow
r { m	b @U
ram-	bunc-	tious
r { m	b V N	k S V s
ram-	mel
r {	m V l
ram-	mer
r {	m @r
ram-	ming
r {	m I N
ram-	pa-	ges
r { m	p eI	dZ V z
ram-	pa-	ging
r { m	p eI	dZ I N
ram-	page
r { m	p eI dZ
ram-	paged
r { m	p eI dZ d
ram-	pant
r { m	p V n t
ram-	parts
r { m	p Q@ t s
ram-	ping
r { m	p I N
ram-	rod
r { m	r Q d
ram-	say
r { m	z i:
ram-	ses
r { m	s i: z
ram-	seur
r V m	s @r
ram-	sey
r { m	z i:
ram-	sey's
r { m	z i: z
ram-	shac-	kle
r { m	S {	k V l
ramb-	ler
r { m	b l @r
ramb-	lers
r { m	b l @r z
ramb-	ling
r { m	b l I N
rammed
r { m d
ramp
r { m p
ramps
r { m p s
rams
r { m z
rams-	dell
r { m	s d V l
rams-	den
r { m	s d V n
rams-	tein
r { m	s t aI n
ran
r { n
ran-	ce's
r { n	s V z
ran-	cher
r { n	tS @r
ran-	chers
r { n	tS @r z
ran-	ches
r { n	tS V z
ran-	ching
r { n	tS I N
ran-	cho
r { n	tS @U
ran-	ch's
r { n	tS V z
ran-	cid
r { n	s I d
ran-	co-	rous
r { N	k @r	V s
ran-	co-	rous-	ness
r { N	k @r	V s	n V s
ran-	cor
r { N	k @r
ran-	da
r Q n	d V
ran-	dal
r { n	d V l
ran-	dall
r { n	d V l
ran-	da's
r Q n	d V z
ran-	del
r { n	d V l
ran-	dell
r { n	d e l
ran-	der
r { n	d @r
ran-	di
r { n	d i:
ran-	dle
r { n	d V l
ran-	dle-	man
r { n	d V l	m V n
ran-	do-	mize
r { n	d V	m aI z
ran-	do-	mized
r { n	d V	m aI z d
ran-	dolf
r { n	d @U l f
ran-	dolph
r { n	d Q l f
ran-	dom
r { n	d V m
ran-	dom-	ly
r { n	d V m	l i:
ran-	dom-	ness
r { n	d V m	n V s
ran-	dy
r { n	d i:
ran-	dy's
r { n	d i: z
ran-	gel
r { n	dZ e l
ran-	ger
r eI n	dZ @r
ran-	gers
r eI n	dZ @r z
ran-	ger's
r eI n	dZ @r z
ran-	ges
r eI n	dZ V z
ran-	ging
r eI n	dZ I N
ran-	goon
r { N	g u: n
ran-	goon's
r { N	g u: n z
ran-	gy
r eI n	dZ i:
ran-	ker
r { N	k @r
ran-	kers
r { N	k @r z
ran-	kin
r { N	k I n
ran-	kine
r { N	k aI n
ran-	king
r { N	k I N
ran-	kings
r { N	k I N z
ran-	kle
r { N	k V l
ran-	kled
r { N	k V l d
ran-	kles
r { N	k V l z
ran-	sac-	king
r { n	s {	k I N
ran-	sack
r { n	s { k
ran-	sacked
r { n	s { k t
ran-	som
r { n	s V m
ran-	some
r { n	s V m
ran-	soms
r { n	s V m z
ran-	som's
r { n	s V m z
ran-	son
r { n	s V n
ran-	ted
r { n	t V d
ran-	ting
r { n	t I N
ran-	toul
r { n	t u: l
rance
r { n s
ranch
r { n tS
ranch-	land
r { n	tS l V n d
rand
r { n d
rand-	lett
r { n	d l e t
rands
r { n d z
rand's
r { n d z
rang
r { N
range
r eI n dZ
ranged
r eI n dZ d
ranh
r { n
rank
r { N k
rank-	ling
r { N	k l I N
ranke
r { N k
ranked
r { N k t
ranks
r { N k s
rann
r { n
rant
r { n t
rao
r aU
rao's
r aU z
rap
r { p
rap-	pel-	ling
r V	p e	l I N
rap-	per
r {	p @r
rap-	pers
r {	p @r z
rap-	ping
r {	p I N
rap-	port
r {	p O@
rap-	proche-	ment
r { p	r @U S	m Q n
rap-	to-	ri-	al
r { p	t O@	i:	V l
rap-	tor
r { p	t @r
rap-	tors
r { p	t @r z
rap-	tu-	rous
r { p	tS @r	V s
rap-	ture
r { p	tS @r
rape
r eI p
rape-	seed
r eI p	s i: d
raped
r eI p t
rapes
r eI p s
rapp
r { p
rappe
r { p
rapped
r { p t
raps
r { p s
rapt
r { p t
rapt-	ly
r { p	t l i:
rare
r e@
rare-	ly
r e@	l i:
rare-	ness
r e@	n V s
ras
r { s
ras-	cal
r { s	k V l
ras-	cals
r { s	k V l z
ras-	kin
r { s	k I n
ras-	mus-	sen
r { s	m V	s V n
ras-	pu-	tin
r V s	p j u:	t I n
ras-	pu-	tin's
r { s	p j u:	t I n z
ras-	py
r { s	p i:
ras-	ter
r { s	t @r
ras-	tus
r { s	t V s
rase
r eI z
rash
r { S
rask
r { s k
rasp
r { s p
rasp-	ber-	ries
r { z	b e@	i: z
rasp-	ber-	ry
r { z	b e@	i:
rasped
r { s p t
rasps
r { s p s
rast
r { s t
rat
r { t
rat-	a-	tat
r {	t V	t { t
rat-	che-	ted
r { t	tS V	t V d
rat-	che-	ting
r {	tS V	t I N
rat-	chet
r { t	tS V t
rat-	liff
r { t	l I f
rat-	t-	ler
r {	t V	l @r
rat-	tan
r {	t { n
rat-	ti-	gan
r {	t I	g V n
rat-	ti-	gan's
r {	t I	g V n z
rat-	tle
r {	t V l
rat-	tled
r {	t V l d
rat-	tles
r {	t V l z
rat-	tles-	nake
r {	t V l	s n eI k
rat-	tles-	nakes
r {	t V l	s n eI k s
rat-	ty
r {	t i:
ratc-	liff
r { t	k l I f
ratc-	liffe
r { t	k l I f
rate
r eI t
rate-	pa-	yer
r eI t	p eI	@r
rate-	pa-	yers
r eI t	p eI	@r z
rates
r eI t s
rate's
r eI t s
rath
r { T
rath-	bone
r { T	b @U n
rath-	skel-	ler
r { T	s k e	l @r
rathe
r eI D
rats
r { t s
ratt-	ling
r { t	l I N
ratt-	ray
r { t	r eI
rau-	cous
r O:	k V s
rau-	scher
r aU	S @r
rauch
r O: tS
raul
r O: l
raun
r O: n
raun-	chy
r O: n	tS i:
rausch
r aU S
rave
r eI v
raved
r eI v d
raves
r eI v z
raw
r Q
raw-	don
r O:	d V n
raw-	hide
r O:	h aI d
raw-	ley
r O:	l i:
raw-	lin-	son
r O:	l I n	s V n
raw-	lings
r O:	l I N z
raw-	lins
r O:	l I n z
raw-	ness
r O:	n V s
raw-	son
r O:	s V n
rawl
r O: l
rax
r { k s
ray
r eI
ray-	burn
r eI	b @r n
ray-	burn's
r eI	b @r n z
ray-	ford
r eI	f @r d
ray-	mond
r eI	m V n d
ray-	mun-	do
r eI	m V n	d @U
ray-	mund
r eI	m V n d
ray-	nard
r eI	n @r d
ray-	ner
r eI	n @r
ray-	nor
r eI	n @r
ray-	the-	on
r eI	T i:	Q n
ray-	the-	on's
r eI	T i:	Q n z
raye
r eI
rayed
r eI d
rayle
r eI l
rayne
r eI n
raynes
r eI n z
rays
r eI z
ray's
r eI z
raz-	zle
r {	z V l
raze
r eI z
razed
r eI z d
razz-	ma-	tazz
r { z	m V	t { z
re
r eI
re-	a-	cquire
r i:	V k	w aI r
re-	a-	cquired
r i:	V k	w aI r d
re-	a-	gent
r i:	eI	dZ V n t
re-	a-	gents
r i:	eI	dZ V n t s
re-	a-	li-	ties
r i:	{	l I	t i: z
re-	a-	li-	ty
r i:	{	l I	t i:
re-	a-	li-	za-	ble
r i:	V	l aI	z V	b V l
re-	a-	li-	zes
r i:	V	l aI	z V z
re-	a-	lig-	ning
r i:	V	l aI	n I N
re-	a-	lign
r i:	V	l aI n
re-	a-	lign-	ment
r i:	V	l aI n	m V n t
re-	a-	lign-	ments
r i:	V	l aI n	m V n t s
re-	a-	ligned
r i:	V	l aI n d
re-	a-	lis-	tic
r i:	V	l I s	t I k
re-	a-	lis-	tical-	ly
r i:	V	l I s	t I k	l i:
re-	a-	na-	ly-	ses
r i:	{	n V	l aI	z V z
re-	a-	na-	ly-	sing
r i:	{	n V	l aI	z I N
re-	a-	na-	lyse
r i:	{	n V	l aI z
re-	a-	na-	lysed
r i:	{	n V	l aI z d
re-	a-	wa-	ke-	ning
r i:	V	w eI	k V	n I N
re-	a-	wa-	ken
r i:	V	w eI	k V n
re-	a-	wa-	kened
r i:	V	w eI	k V n d
re-	ab-	sorb
r i:	V b	z O@ b
re-	ab-	sorbed
r i:	V b	z O@ b d
re-	ac-	ted
r i:	{ k	t V d
re-	ac-	ti-	va-	ted
r i:	{ k	t I	v eI	t I d
re-	ac-	ti-	va-	ting
r i:	{ k	t I	v eI	t I N
re-	ac-	ti-	vate
r i:	{ k	t I	v eI t
re-	ac-	ti-	vi-	ty
r i:	{ k	t I	v I	t i:
re-	ac-	ting
r i:	{ k	t I N
re-	ac-	tio-	na-	ries
r i:	{ k	S V	n e@	i: z
re-	ac-	tio-	na-	ry
r i:	{ k	S V	n e@	i:
re-	ac-	tion
r i:	{ k	S V n
re-	ac-	tions
r i:	{ k	S V n z
re-	ac-	tive
r i:	{ k	t I v
re-	ac-	tor
r i:	{ k	t @r
re-	ac-	tors
r i:	{ k	t @r z
re-	ac-	tor's
r i:	{ k	t @r z
re-	act
r i:	{ k t
re-	acts
r i:	{ k t s
re-	ad-	jus-	ted
r i:	V	dZ V s	t V d
re-	ad-	jus-	ting
r i:	V	dZ V s	t I N
re-	ad-	just
r i:	V	dZ V s t
re-	ad-	just-	ment
r i:	V	dZ V s	t m V n t
re-	ad-	just-	ments
r i:	V	dZ V s	t m V n t s
re-	ad-	mit
r i:	V d	m I t
re-	ad-	mit-	ted
r i:	V d	m I	t V d
re-	af-	fi-	li-	a-	tion
r i:	V	f I	l i:	eI	S V n
re-	af-	fir-	ma-	tion
r i:	{	f @r	m eI	S V n
re-	af-	fir-	ming
r i:	V	f @r	m I N
re-	af-	firm
r i:	V	f @r m
re-	af-	firmed
r i:	V	f @r m d
re-	af-	firms
r i:	V	f @r m z
re-	al-	lo-	ca-	ted
r i:	{	l V	k eI	t V d
re-	al-	lo-	ca-	ting
r i:	{	l V	k eI	t I N
re-	al-	lo-	ca-	tion
r i:	{	l V	k eI	S V n
re-	al-	lo-	cate
r i:	{	l V	k eI t
re-	al-	lo-	wance
r i:	V	l aU	V n s
re-	al-	tor
r i:	V l	t @r
re-	al-	tors
r i:	V l	t @r z
re-	al-	tor's
r i:	V l	t @r z
re-	al-	ty
r i:	V l	t i:
re-	al-	ty's
r i:	V l	t i: z
re-	ap-	pea-	rance
r i:	V	p I@	V n s
re-	ap-	pear
r i:	V	p I@
re-	ap-	peared
r i:	V	p I@ d
re-	ap-	pears
r i:	V	p I@ z
re-	ap-	poin-	ted
r i:	V	p OI n	t V d
re-	ap-	point
r i:	V	p OI n t
re-	ap-	point-	ment
r i:	V	p OI n	t m V n t
re-	ap-	por-	tion-	ment
r i:	V	p O@	S V n	m V n t
re-	ap-	prai-	sal
r i:	V p	r eI	z V l
re-	ap-	praise
r i:	V p	r eI z
re-	ap-	praised
r i:	V p	r eI z d
re-	app-	ly
r i:	V p	l i:
re-	ar-	ma-	ment
r i:	Q@	m V	m V n t
re-	ar-	ming
r i:	Q@	m I N
re-	ar-	ran-	ging
r i:	@r	eI n	dZ I N
re-	ar-	range
r i:	@r	eI n dZ
re-	ar-	range-	ment
r i:	@r	eI n	dZ m V n t
re-	ar-	ranged
r i:	@r	eI n dZ d
re-	ar-	res-	ted
r i:	@r	e s	t V d
re-	ar-	rest
r i:	@r	e s t
re-	arm
r i:	Q@ m
re-	as-	sem-	ble
r i:	V	s e m	b V l
re-	as-	sem-	bled
r i:	V	s e m	b V l d
re-	as-	semb-	ly
r i:	V	s e m	b l i:
re-	as-	ser-	ted
r i:	V	s @r	t V d
re-	as-	ser-	ting
r i:	V	s @r	t I N
re-	as-	ser-	tion
r i:	V	s @r	S V n
re-	as-	sert
r i:	V	s @r t
re-	as-	serts
r i:	V	s @r t s
re-	as-	ses-	sing
r i:	V	s e	s I N
re-	as-	sess
r i:	V	s e s
re-	as-	sess-	ment
r i:	V	s e s	m V n t
re-	as-	sessed
r i:	V	s e s t
re-	as-	sig-	ning
r i:	V	s aI	n I N
re-	as-	sign
r i:	V	s aI n
re-	as-	sign-	ment
r i:	V	s aI n	m V n t
re-	as-	sign-	ments
r i:	V	s aI n	m V n t s
re-	as-	signed
r i:	V	s aI n d
re-	as-	su-	ran-	ces
r i:	V	S U@	V n	s V z
re-	as-	su-	rance
r i:	V	S U@	V n s
re-	as-	su-	ring
r i:	V	S U@	I N
re-	as-	su-	ring-	ly
r i:	V	S U@	I N	l i:
re-	as-	sume
r i:	V	s u: m
re-	as-	sumed
r i:	V	s u: m d
re-	as-	sure
r i:	V	S U@
re-	as-	sured
r i:	V	S U@ d
re-	as-	sures
r i:	V	S U@ z
re-	at-	tach
r i:	V	t { tS
re-	at-	tached
r i:	V	t { tS t
re-	au-	tho-	ri-	za-	tion
r i:	O:	T @r	I	z eI	S V n
re-	au-	tho-	ri-	zing
r i:	O:	T @r	aI	z I N
re-	au-	tho-	rize
r i:	O:	T @r	aI z
re-	au-	tho-	rized
r i:	O:	T @r	aI z d
re-	ba
r i:	b V
re-	ba-	lan-	cing
r i:	b {	l V n	s I N
re-	ba-	ted
r i:	b eI	t V d
re-	back
r i:	b { k
re-	bar
r i:	b Q@
re-	bate
r i:	b eI t
re-	bates
r i:	b eI t s
re-	be-	ka
r V	b i:	k V
re-	bec-	ca
r V	b e	k V
re-	bec-	ca's
r V	b e	k V z
re-	beck
r i:	b e k
re-	bel
r e	b V l
re-	bel-	li-	ous-	ness
r V	b e	l i:	V s	n V s
re-	bel-	ling
r V	b e	l I N
re-	bel-	lion
r V	b e l	j V n
re-	bel-	lions
r V	b e l	j V n z
re-	bel-	lion's
r V	b e l	j V n z
re-	bel-	lious
r V	b e l	j V s
re-	belled
r V	b e l d
re-	bels
r e	b V l z
re-	bel's
r e	b V l z
re-	bid
r i:	b I d
re-	birth
r i:	b @r T
re-	births
r i:	b @r T s
re-	board
r i:	b O@ d
re-	book
r i:	b U k
re-	booked
r i:	b U k t
re-	born
r i:	b O@ n
re-	boun-	ded
r i:	b aU n	d V d
re-	boun-	ding
r i:	b aU n	d I N
re-	bound
r i:	b aU n d
re-	bounds
r i:	b aU n d z
re-	broad-	cast
r i: b	r O: d	k { s t
re-	bu-	king
r i: b	j u:	k I N
re-	buck
r e	b V k
re-	buf-	fing
r i:	b V	f I N
re-	buff
r V	b V f
re-	buffed
r V	b V f t
re-	buffs
r i:	b V f s
re-	buil-	der
r i:	b I l	d @r
re-	buil-	ding
r i:	b I l	d I N
re-	build
r i:	b I l d
re-	builds
r i:	b I l d z
re-	built
r i:	b I l t
re-	buke
r i: b	j u: k
re-	buked
r V b	j u: k t
re-	bukes
r i: b	j u: k s
re-	bus
r i:	b V s
re-	but
r V	b V t
re-	but-	tal
r V	b V	t V l
re-	but-	tals
r V	b V	t V l z
re-	but-	ted
r V	b V	t V d
re-	but-	ting
r V	b V	t I N
re-	ca-	pi-	ta-	li-	za-	tion
r i:	k {	p I	t V	l I	z eI	S V n
re-	ca-	pi-	ta-	li-	za-	tions
r i:	k {	p I	t V	l I	z eI	S V n z
re-	ca-	pi-	ta-	li-	zing
r i:	k {	p I	t V	l aI	z I N
re-	ca-	pi-	ta-	lize
r i:	k {	p I	t V	l aI z
re-	ca-	pi-	ta-	lized
r i:	k {	p I	t V	l aI z d
re-	ca-	pi-	tu-	late
r i:	k V	p I	tS V	l eI t
re-	ca-	pi-	tu-	lates
r i:	k V	p I	tS V	l eI t s
re-	cal-	cit-	rance
r I	k { l	s V t	r V n s
re-	cal-	cit-	rant
r I	k { l	s I t	r V n t
re-	cal-	cu-	la-	ted
r i:	k { l	k j V	l eI	t I d
re-	cal-	cu-	la-	ting
r i:	k { l	k j V	l eI	t I N
re-	cal-	cu-	la-	tion
r i:	k { l	k j V	l eI	S V n
re-	cal-	cu-	late
r i:	k { l	k j V	l eI t
re-	cal-	ling
r I	k O:	l I N
re-	call
r i:	k O: l
re-	called
r I	k O: l d
re-	calls
r i:	k O: l z
re-	can-	ta-	tion
r e	k V n	t eI	S V n
re-	can-	ted
r i:	k { n	t V d
re-	can-	ting
r V	k { n	t I N
re-	cant
r i:	k { n t
re-	cap
r i:	k { p
re-	cap-	ping
r i:	k {	p I N
re-	cap-	tu-	ring
r i:	k { p	tS @r	I N
re-	cap-	ture
r i:	k { p	tS @r
re-	cap-	tured
r i:	k { p	tS @r d
re-	capped
r i:	k { p t
re-	caps
r i:	k { p s
re-	cas-	ting
r i:	k { s	t I N
re-	cast
r i:	k { s t
re-	ce-	ded
r V	s i:	d V d
re-	ce-	ding
r V	s i:	d I N
re-	cede
r V	s i: d
re-	cedes
r i:	s i: d z
re-	cei-	va-	ble
r V	s i:	v V	b V l
re-	cei-	va-	bles
r V	s i:	v V	b V l z
re-	cei-	ver
r V	s i:	v @r
re-	cei-	ver-	ship
r V	s i:	v @r	S I p
re-	cei-	ver-	ships
r V	s i:	v @r	S I p s
re-	cei-	vers
r V	s i:	v @r z
re-	cei-	ving
r V	s i:	v I N
re-	ceipt
r V	s i: t
re-	ceipts
r V	s i: t s
re-	ceive
r V	s i: v
re-	ceived
r V	s i: v d
re-	ceives
r V	s i: v z
re-	cent
r i:	s V n t
re-	cent-	ly
r i:	s V n	t l i:
re-	cep-	ta-	cle
r V	s e p	t V	k V l
re-	cep-	ta-	cles
r V	s e p	t I	k V l z
re-	cep-	ti-	vi-	ty
r i:	s e p	t I	v I	t i:
re-	cep-	tio-	nist
r V	s e p	S V	n I s t
re-	cep-	tio-	nists
r V	s e p	S V	n I s t s
re-	cep-	tion
r V	s e p	S V n
re-	cep-	tions
r V	s e p	S V n z
re-	cep-	tive
r V	s e p	t I v
re-	cep-	tor
r i:	s e p	t @r
re-	cep-	tors
r V	s e p	t @r z
re-	cer-	ti-	fi-	ca-	tion
r i:	s @r	t I	f I	k eI	S V n
re-	cer-	ti-	fied
r i:	s @r	t I	f aI d
re-	cer-	ti-	fy
r i:	s @r	t I	f aI
re-	cer-	ti-	fy-	ing
r i:	s @r	t I	f aI	I N
re-	ces-	ses
r i:	s e	s V z
re-	ces-	sing
r i:	s e	s I N
re-	ces-	sio-	na-	ry
r i:	s e	S V	n e@	i:
re-	ces-	sion
r V	s e	S V n
re-	ces-	sions
r V	s e	S V n z
re-	ces-	sion's
r i:	s e	S V n z
re-	ces-	sive
r V	s e	s I v
re-	cess
r V	s e s
re-	cessed
r V	s e s t
re-	char-	gea-	ble
r i:	tS Q@	dZ V	b V l
re-	char-	ging
r i:	tS Q@	dZ I N
re-	charge
r i:	tS Q@ dZ
re-	charged
r i:	tS Q@ dZ d
re-	check
r i:	tS e k
re-	checked
r i:	tS e k t
re-	ci-	di-	vi-	sm
r V	s I	d I	v I	z V m
re-	ci-	di-	vist
r V	s I	d I	v I s t
re-	ci-	di-	vists
r V	s I	d I	v I s t s
re-	ci-	pe
r e	s I	p i:
re-	ci-	pes
r e	s I	p i: z
re-	ci-	pe's
r e	s I	p i: z
re-	ci-	pi-	ent
r V	s I	p i:	e n t
re-	ci-	pi-	ents
r V	s I	p i:	e n t s
re-	ci-	pi-	ent's
r V	s I	p i:	e n t s
re-	ci-	pro-	ca-	ted
r V	s I p	r V	k eI	t V d
re-	ci-	pro-	ca-	ting
r V	s I p	r V	k eI	t I N
re-	ci-	pro-	cal
r V	s I p	r V	k V l
re-	ci-	pro-	cant
r i:	s I p	r V	k V n t
re-	ci-	pro-	cants
r i:	s I p	r V	k V n t s
re-	ci-	pro-	cate
r V	s I p	r V	k eI t
re-	ci-	pro-	ci-	ty
r e	s I p	r Q	s I	t i:
re-	ci-	sion
r V	s I	Z V n
re-	ci-	sions
r V	s I	Z V n z
re-	ci-	ta-	tion
r e	s I	t eI	S V n
re-	ci-	ta-	tions
r e	s I	t eI	S V n z
re-	ci-	ta-	tives
r e	s I	t V	t i: v z
re-	ci-	tal
r V	s aI	t V l
re-	ci-	tals
r V	s aI	t V l z
re-	ci-	ted
r V	s aI	t V d
re-	ci-	ting
r i:	s aI	t I N
)"
R"(re-	cis-	sion
r V	s I	S V n
re-	cite
r V	s aI t
re-	cites
r i:	s aI t s
re-	clas-	si-	fi-	ca-	tion
r i: k	l {	s I	f I	k eI	S V n
re-	clas-	si-	fied
r i: k	l {	s I	f aI d
re-	clas-	si-	fy
r i: k	l {	s I	f aI
re-	clas-	si-	fy-	ing
r i: k	l {	s I	f aI	I N
re-	cli-	ner
r I k	l aI	n @r
re-	cli-	ning
r I k	l aI	n I N
re-	clu-	sive
r I k	l u:	s I v
re-	cluse
r I k	l u: s
re-	co-	ve-	ra-	ble
r I	k V	v @r	V	b V l
re-	co-	ve-	ries
r I	k V	v @r	i: z
re-	co-	ve-	ring
r V	k V	v @r	I N
re-	co-	ve-	ry's
r I	k V	v @r	i: z
re-	co-	ver
r I	k V	v @r
re-	co-	vered
r V	k V	v @r d
re-	co-	vers
r I	k V	v @r z
re-	cog-	ni-	tion
r e	k V g	n I	S V n
re-	cog-	ni-	tion's
r e	k I g	n I	S V n z
re-	cog-	ni-	za-	ble
r e	k V g	n aI	z V	b V l
re-	cog-	ni-	zab-	ly
r e	k V g	n aI	z V b	l i:
re-	cog-	ni-	zance
r I	k Q	n I	z V n s
re-	cog-	ni-	zes
r e	k V g	n aI	z V z
re-	cog-	ni-	zing
r e	k V g	n aI	z I N
re-	cog-	nize
r e	k V g	n aI z
re-	cog-	nized
r e	k V g	n aI z d
re-	coil
r i:	k OI l
re-	coiled
r i:	k OI l d
re-	coils
r i:	k OI l z
re-	col-	lec-	ted
r e	k V	l e k	t V d
)"