R"(der-	leth
dh @r	l e T
der-	ma
dh @r	m V
der-	ma-	to-	lo-	gi-	cal
dh @r	m V	t V	l Q	dZ I	k V l
der-	ma-	to-	lo-	gist
dh @r	m V	t Q	l V	dZ V s t
der-	ma-	to-	lo-	gists
dh @r	m V	t Q	l V	dZ V s t s
der-	ma-	to-	lo-	gy
dh @r	m V	t Q	l V	dZ i:
der-	mal
dh @r	m V l
der-	man
dh @r	m V n
der-	mis
dh @r	m I s
der-	mot
dh @r	m V t
der-	mott
dh @r	m V t
der-	ner
dh @r	n @r
der-	rick
dh e@	I k
der-	rin-	ger
dh e@	I n	dZ @r
der-	ry
dh e@	i:
der-	vish
dh @r	v I S
der-	ward
dh @r	w @r d
der-	win
dh @r	w I n
derk
dh @r k
dern
dh @r n
derr
dh e@
des
dh e
des-	cartes
dh eI	k Q@ t
des-	cen-	dant
dh V	s e n	d V n t
des-	cen-	dants
dh V	s e n	d V n t s
des-	cen-	ded
dh V	s e n	d V d
des-	cen-	dent
dh V	s e n	d V n t
des-	cen-	dents
dh V	s e n	d V n t s
des-	cen-	ding
dh V	s e n	d I N
des-	cend
dh V	s e n d
des-	cends
dh V	s e n d z
des-	cent
dh V	s e n t
des-	cents
dh V	s e n t s
des-	champs
dh e	S V m p s
des-	cri-	ba-	ble
dh V s	k r aI	b V	b V l
des-	cri-	bing
dh V s	k r aI	b I N
des-	cribe
dh V s	k r aI b
des-	cribed
dh V s	k r aI b d
des-	cribes
dh V s	k r aI b z
des-	crip-	tion
dh V s	k r I p	S V n
des-	crip-	tions
dh V s	k r I p	S V n z
des-	crip-	tive
dh V s	k r I p	t I v
des-	ma
dh i: s	m V
des-	man
dh e s	m V n
des-	met
dh e s	m e t
des-	mids
dh e s	m I d z
des-	mo-	na
dh e s	m @U	n V
des-	mond
dh e z	m V n d
des-	pe-	ra-	do
dh e s	p @r	Q	d @U
des-	pe-	ra-	does
dh e s	p @r	Q	d @U z
des-	pe-	ra-	tion
dh e s	p @r	eI	S V n
des-	pe-	rate-	ly
dh e s	p @r	V t	l i:
des-	pi-	ca-	ble
dh I s	p I	k V	b V l
des-	pi-	ses
dh I s	p aI	z V z
des-	pise
dh I s	p aI z
des-	pised
dh I s	p aI z d
des-	pite
dh I s	p aI t
des-	po-	ti-	sm
dh e s	p V	t I	z V m
des-	po-	tic
dh I s	p Q	t I k
des-	pon-	den-	cy
dh I s	p Q n	d V n	s i:
des-	pon-	dent
dh I s	p Q n	d V n t
des-	pot
dh e s	p V t
des-	sert
dh I	z @r t
des-	serts
dh I	z @r t s
des-	ta-	bi-	li-	za-	tion
dh i: s	t eI	b I	l I	z eI	S V n
des-	ta-	bi-	li-	zing
dh i: s	t eI	b I	l aI	z I N
des-	ta-	bi-	lize
dh i: s	t eI	b I	l aI z
des-	ta-	bi-	lized
dh i: s	t eI	b I	l aI z d
d'es-	taing
dh V s	t eI N
des-	ti-	na-	tion
dh e s	t I	n eI	S V n
des-	ti-	na-	tions
dh e s	t I	n eI	S V n z
des-	ti-	nies
dh e s	t I	n i: z
des-	ti-	ny
dh e s	t I	n i:
des-	ti-	tu-	tion
dh e s	t I	t u:	S V n
des-	ti-	tute
dh e s	t I	t u: t
des-	tin
dh e s	t I n
des-	tined
dh e s	t I n d
desh-	ler
dh e S	l @r
desk
dh e s k
desk-	top
dh e s	k t Q p
desk-	tops
dh e s	k t Q p s
desks
dh e s k s
despe-	rate
dh e s	p r V t
dest
dh e s t
dest-	ro-	yer
dh V s	t r OI	@r
dest-	ro-	yers
dh V s	t r OI	@r z
dest-	roy
dh V s	t r OI
dest-	roy-	ing
dh V s	t r OI	I N
dest-	royed
dh V s	t r OI d
dest-	roys
dh V s	t r OI z
dest-	ruc-	ted
dh V s	t r V k	t V d
dest-	ruc-	ting
dh V s	t r V k	t I N
dest-	ruc-	tion
dh V s	t r V k	S V n
dest-	ruc-	tive
dh V s	t r V k	t I v
dest-	ruc-	tive-	ness
dh V s	t r V k	t I v	n V s
dest-	ruct
dh V s	t r V k t
dest-	ructs
dh V s	t r V k t s
det-	rac-	ted
dh V t	r { k	t V d
det-	rac-	ting
dh V t	r { k	t I N
det-	rac-	tor
dh i: t	r { k	t @r
det-	rac-	tors
dh i: t	r { k	t @r z
det-	ract
dh V t	r { k t
det-	racts
dh V t	r { k t s
det-	ri-	men-	tal
dh e t	r I	m e n	t V l
det-	ri-	ment
dh e t	r I	m V n t
det-	ri-	tus
dh V t	r aI	t V s
det-	roi-	ters
dh V t	r OI	t @r z
det-	roit
dh V t	r OI t
det-	roit's
dh V t	r OI t s
deth-	rone
dh i: T	r @U n
deth-	roned
dh i: T	r @U n d
dett-	mer
dh e t	m @r
deu-	te-	ri-	um
dh u:	t i:	r i:	V m
deu-	te-	rons
dh u:	t @r	Q n z
deuce
dh u: s
deut-	scher
dh OI	tS @r
deutsch
dh OI tS
deutsch-	land
dh OI tS	l { n d
deutsche
dh OI tS
deux
dh u:
dev
dh e v
dev-	lin
dh e v	l I n
devil-	s
dh e	v I l z
dew
dh u:
dew-	ber-	ry
dh u:	b e@	i:
dewc-	law
dh u: k	l O:
dews
dh u: z
dex
dh e k s
dex-	te-	ri-	ty
dh e k	s t e@	I	t i:
dex-	ter
dh e k	s t @r
dex-	ter's
dh e k	s t @r z
dex-	tra
dh e k	s t r V
dex-	tran
dh e k	s t r { n
dex-	tro
dh e k	s t r @U
dex-	trose
dh e k	s t r @U s
dex-	trous
dh e k	s t r V s
dey
dh eI
dha-	bi
dh Q	b i:
dha-	ka
dh Q	k V
dhah-	ran
dh V	r Q n
dhar-	ma
dh Q@	m V
dhole
dh @U l
dhows
dh aU z
di
dh i:
di-	a
dh i:	V
di-	a-	ba-	sic
dh aI	V	b eI	s I k
di-	a-	base
dh aI	V	b eI s
di-	a-	be-	tes
dh aI	V	b i:	t i: z
di-	a-	be-	tic
dh aI	V	b e	t I k
di-	a-	be-	tics
dh aI	V	b e	t I k s
di-	a-	blo
dh aI	{ b	l @U
di-	a-	bo-	li-	cal
dh aI	V	b Q	l I	k V l
di-	a-	co-	nate
dh aI	{	k V	n V t
di-	a-	cri-	ti-	cal
dh aI	V k	r I	t V	k V l
di-	a-	cri-	tic
dh aI	V k	r I	t V k
di-	a-	dem
dh aI	V	d e m
di-	a-	go-	nal
dh aI	{	g V	n V l
di-	a-	go-	nal-	ly
dh aI	{	g V	n V	l i:
di-	a-	go-	nals
dh aI	{	g V	n V l z
di-	a-	gra-	ming
dh aI	V g	r {	m I N
di-	a-	gram
dh aI	V g	r { m
di-	a-	gram-	ma-	tic
dh aI	V g	r V	m {	t I k
di-	a-	grammed
dh aI	V g	r { m d
di-	a-	grams
dh aI	V g	r { m z
di-	a-	lec-	ti-	cal
dh aI	V	l e k	t I	k V l
di-	a-	lec-	tic
dh aI	V	l e k	t I k
di-	a-	lect
dh aI	V	l e k t
di-	a-	lects
dh aI	V	l e k t s
di-	a-	ling
dh aI	V	l I N
di-	a-	log
dh aI	V	l O: g
di-	a-	logue
dh aI	V	l O: g
di-	a-	logues
dh aI	V	l O: g z
di-	a-	ly-	sis
dh aI	{	l V	s V s
di-	a-	mag-	ne-	ti-	sm
dh aI	V	m { g	n V	t I	z V m
di-	a-	mag-	ne-	tic
dh aI	V	m { g	n e	t I k
di-	a-	man-	ta
dh aI	V	m { n	t V
di-	a-	man-	te
dh aI	V	m Q n	t i:
di-	a-	mant
dh aI	V	m V n t
di-	a-	me-	ter
dh aI	{	m V	t @r
di-	a-	met-	ri-	cal-	ly
dh aI	V	m e t	r I	k V	l i:
di-	a-	na
dh aI	{	n V
di-	a-	na's
dh aI	{	n V z
di-	a-	ne-	tics
dh aI	V	n e	t I k s
di-	a-	pers
dh aI	V	p @r z
di-	a-	pho-	ni-	a
dh aI	V	f @U	n i:	V
di-	a-	ries
dh aI	@r	i: z
di-	a-	ry
dh aI	@r	i:
di-	a-	to-	mic
dh aI	V	t Q	m I k
di-	a-	to-	nic
dh aI	V	t Q	n I k
di-	a-	toms
dh aI	V	t Q m z
di-	a-	tribe
dh aI	V t	r aI b
di-	a-	tribes
dh aI	V t	r aI b z
di-	a-	zo
dh aI	{	z @U
di-	ag-	no-	ses
dh aI	V g	n @U	s i: z
di-	ag-	no-	sing
dh aI	V g	n @U	s I N
di-	ag-	no-	sis
dh aI	V g	n @U	s V s
di-	ag-	nos-	tic
dh aI	V g	n Q s	t I k
di-	ag-	nos-	tics
dh aI	V g	n Q s	t I k s
di-	ag-	nose
dh aI	V g	n @U s
di-	ag-	nosed
dh aI	V g	n @U s t
di-	al
dh aI	V l
di-	al-	tone
dh aI	V l	t @U n
di-	aled
dh aI	V l d
di-	als
dh aI	V l z
di-	al's
dh aI	V l z
di-	an
dh aI	V n
di-	an-	na
dh aI	{	n V
di-	an-	tha
dh aI	{ n	T V
di-	an-	the
dh aI	{ n	D i:
di-	ane
dh aI	{ n
di-	ane's
dh aI	{ n z
di-	anne
dh aI	{ n
di-	ap-	sid
dh aI	{ p	s I d
di-	aph-	ragm
dh aI	V f	r { m
di-	ar-	rhe-	a
dh aI	@r	i:	V
di-	arr-	hoe-	a
dh aI	@r	i:	V
di-	as
dh aI	V z
di-	at-	her-	my
dh aI	V	T @r	m i:
di-	az
dh i:	{ z
di-	boll
dh I	b V l
di-	cap-	ri-	o
dh I	k { p	r i:	@U
di-	cen-	zo
dh I	s e n	z @U
di-	cey
dh aI	s i:
di-	cho-	to-	my
dh aI	k Q	t V	m i:
di-	ci-	er
dh aI	s i:	@r
di-	cots
dh aI	k Q t s
di-	dac-	tic
dh aI	d { k	t I k
di-	di
dh i:	d i:
di-	di-	er
dh I	d i:	@r
di-	di-	ni-	um
dh V	d I	n i:	V m
di-	dn't
dh I	d V n t
di-	do
dh aI	d @U
di-	e-	go
dh i:	eI	g @U
di-	e-	go's
dh i:	eI	g @U z
di-	e-	ta-	ry
dh aI	V	t e@	i:
di-	e-	te-	tic
dh aI	V	t e	t I k
di-	e-	ters
dh aI	V	t @r z
di-	e-	ti-	tian
dh aI	V	t I	S V n
di-	e-	ti-	tians
dh aI	V	t I	S V n z
di-	e-	ti-	tian's
dh aI	V	t I	S V n z
di-	e-	ting
dh aI	V	t I N
di-	er
dh i:	@r
di-	et
dh aI	V t
di-	ets
dh aI	V t s
di-	et's
dh aI	V t s
di-	ge-	no-	va
dh i:	dZ e	n @U	v V
di-	ges-	ted
dh aI	dZ e s	t V d
di-	ges-	ter
dh aI	dZ e s	t @r
di-	ges-	ti-	ble
dh aI	dZ e s	t I	b V l
di-	ges-	ting
dh aI	dZ e s	t I N
di-	ges-	tion
dh aI	dZ e s	tS V n
di-	ges-	tive
dh aI	dZ e s	t I v
di-	gest
dh aI	dZ e s t
di-	gests
dh V	dZ e s t s
di-	gest's
dh aI	dZ e s t s
di-	gi-	ta-	lis
dh I	dZ I	t {	l V s
di-	gi-	tal
dh I	dZ I	t V l
di-	gi-	tal-	ly
dh I	dZ I	t V	l i:
di-	gi-	ti-	zing
dh I	dZ I	t aI	z I N
di-	gi-	tize
dh I	dZ I	t aI z
di-	gi-	tized
dh I	dZ I	t aI z d
di-	gior-	gi-	o
dh I	dZ O@	dZ i:	@U
di-	git
dh I	dZ I t
di-	gits
dh I	dZ I t s
di-	jon
dh i:	Z Q n
di-	la-	pi-	da-	ted
dh V	l {	p V	d eI	t V d
di-	la-	pi-	date
dh V	l {	p V	d eI t
di-	la-	ta-	tion
dh I	l V	t eI	S V n
di-	la-	ted
dh aI	l eI	t V d
di-	la-	tion
dh aI	l eI	S V n
di-	la-	to-	ry
dh I	l V	t O@	i:
di-	late
dh aI	l eI t
di-	lem-	ma
dh V	l e	m V
di-	lem-	mas
dh V	l e	m V z
di-	li-	gence
dh I	l I	dZ V n s
di-	li-	gent
dh I	l I	dZ V n t
di-	li-	gent-	ly
dh I	l I	dZ V n	t l i:
di-	li-	thi-	um
dh aI	l I	T i:	V m
di-	lu-	ted
dh aI	l u:	t V d
di-	lu-	ting
dh aI	l u:	t I N
di-	lu-	tion
dh aI	l u:	S V n
di-	lu-	tive
dh V	l u:	t I v
di-	lute
dh aI	l u: t
di-	lutes
dh aI	l u: t s
di-	ma-	ri-	a
dh I	m Q@	i:	V
di-	mag-	gi-	o
dh V	m {	dZ i:	@U
di-	men-	sio-	na-	li-	ty
dh I	m e n	S V	n {	l I	t i:
di-	men-	sio-	nal
dh I	m e n	S V	n V l
di-	men-	sion
dh I	m e n	S V n
di-	men-	sioned
dh V	m e n	tS V n d
di-	men-	sions
dh I	m e n	S V n z
di-	mer
dh aI	m @r
di-	mi-	ni-	shes
dh V	m I	n I	S V z
di-	mi-	ni-	shing
dh V	m I	n I	S I N
di-	mi-	nish
dh V	m I	n I S
di-	mi-	nish-	ment
dh V	m I	n I S	m V n t
di-	mi-	nished
dh V	m I	n I S t
di-	mi-	nu-	tion
dh I	m I	n u:	S V n
di-	mi-	nu-	tive
dh V	m I n	j V	t I v
di-	mit-	ri
dh I	m i: t	r i:
di-	mock
dh I	m V k
di-	mond
dh aI	m V n d
di-	mor-	phi-	sm
dh aI	m O@	f I	z V m
di-	mor-	phic
dh aI	m O@	f I k
di-	na
dh i:	n V
di-	nah
dh aI	n V
di-	nan
dh I	n V n
di-	nar
dh I	n Q@
di-	nars
dh aI	n @r z
di-	ner
dh aI	n @r
di-	ners
dh aI	n @r z
di-	nesh
dh I	n e S
di-	no-	saur
dh aI	n V	s O@
di-	no-	saurs
dh aI	n V	s O@ z
di-	o-	ce-	san
dh aI	Q	s V	s V n
di-	o-	cese
dh aI	V	s i: z
di-	o-	ceses
dh aI	V	s i: z
di-	o-	ni-	si-	o
dh aI	V	n I	s i:	@U
di-	o-	ny-	si-	us
dh aI	V	n I	s i:	V s
di-	o-	rite
dh aI	@r	aI t
di-	o-	xide
dh aI	Q k	s aI d
di-	o-	xides
dh aI	Q k	s aI d z
di-	o-	xin
dh aI	Q k	s I n
di-	o-	xins
dh aI	Q k	s I n z
di-	ode
dh aI	@U d
di-	odes
dh aI	@U d z
di-	on
dh aI	V n
di-	one
dh i:	Q n
di-	onne
dh i:	Q n
di-	or
dh i:	O@
di-	os
dh i:	@U s
di-	pole
dh aI	p @U l
di-	rec-	ted
dh I@	e k	t V d
di-	rec-	ting
dh @r	e k	t I N
di-	rec-	tio-	nal
dh @r	e k	S V	n V l
di-	rec-	tion
dh @r	e k	S V n
di-	rec-	tion-	less
dh @r	e k	S V n	l e s
di-	rec-	tions
dh @r	e k	S V n z
di-	rec-	tive
dh @r	e k	t I v
di-	rec-	tives
dh aI	r e k	t I v z
di-	rec-	tly
dh @r	e k	t l i:
di-	rec-	to-	ral
dh @r	e k	t @r	V l
di-	rec-	to-	rate
dh @r	e k	t @r	V t
di-	rec-	to-	ri-	al
dh @r	e k	t O@	i:	V l
di-	rec-	to-	ries
dh aI	r e k	t @r	i: z
di-	rec-	to-	ry
dh @r	e k	t @r	i:
di-	rec-	tor
dh @r	e k	t @r
di-	rec-	tor-	ship
dh @r	e k	t @r	S I p
di-	rec-	tor-	ships
dh @r	e k	t @r	S I p s
di-	rec-	tors
dh @r	e k	t @r z
di-	rec-	tor's
dh aI	r e k	t @r z
di-	rect
dh @r	e k t
di-	rect-	ness
dh @r	e k	t n V s
di-	rects
dh @r	e k t s
di-	rest
dh aI	r V s t
di-	sa
dh I	s V
di-	sa-	b-	ling
dh I	s eI	b V	l I N
di-	sa-	bi-	li-	ties
dh I	s V	b I	l V	t i: z
di-	sa-	bi-	li-	ty
dh I	s V	b I	l V	t i:
di-	sa-	ble
dh I	s eI	b V l
di-	sa-	bled
dh I	s eI	b V l d
di-	sa-	bles
dh I	s eI	b V l z
di-	sa-	bu-	ses
dh I	s V b	j u:	s V z
di-	sa-	buse
dh I	s V b	j u: s
di-	sa-	bused
dh I	s V b	j u: z d
di-	sa-	vow
dh I	s V	v aU
di-	sa-	vow-	ing
dh I	s V	v aU	I N
di-	sa-	vowed
dh I	s V	v aU d
di-	sad-	van-	ta-	geous
dh I	s { d	v { n	t eI	dZ V s
di-	sad-	van-	ta-	ges
dh I	s V d	v { n	t I	dZ V z
di-	sad-	van-	tage
dh I	s V d	v { n	t I dZ
di-	sad-	van-	taged
dh I	s V d	v { n	t I dZ d
di-	saf-	fec-	ted
dh I	s V	f e k	t V d
di-	saf-	fec-	tion
dh I	s V	f e k	S V n
di-	saf-	fect
dh I	s V	f e k t
di-	sag-	ree
dh I	s V g	r i:
di-	sag-	ree-	a-	ble
dh I	s V g	r i:	V	b V l
di-	sag-	ree-	ing
dh I	s V g	r i:	I N
di-	sag-	ree-	ment
dh I	s V g	r i:	m V n t
di-	sag-	ree-	ments
dh I	s V g	r i:	m V n t s
di-	sag-	reed
dh I	s V g	r i: d
di-	sag-	rees
dh I	s V g	r i: z
di-	sal-	lo-	wan-	ces
dh I	s V	l aU	V n	s V z
di-	sal-	lo-	wance
dh I	s V	l aU	V n s
di-	sal-	low
dh I	s V	l aU
di-	sal-	low-	ing
dh I	s V	l aU	I N
di-	sal-	lowed
dh I	s V	l aU d
di-	sap-	pea-	ran-	ces
dh I	s V	p I@	V n	s V z
di-	sap-	pea-	rance
dh I	s V	p I@	V n s
di-	sap-	pea-	ring
dh I	s V	p I@	I N
di-	sap-	pear
dh I	s V	p I@
di-	sap-	peared
dh I	s V	p I@ d
di-	sap-	pears
dh I	s V	p I@ z
di-	sap-	poin-	ted
dh I	s V	p OI n	t V d
di-	sap-	poin-	ting
dh I	s V	p OI n	t I N
di-	sap-	poin-	ting-	ly
dh I	s V	p OI n	t I N	l i:
di-	sap-	point
dh I	s V	p OI n t
di-	sap-	point-	ment
dh I	s V	p OI n	t m V n t
di-	sap-	point-	ments
dh I	s V	p OI n	t m V n t s
di-	sap-	points
dh I	s V	p OI n t s
di-	sap-	pro-	val
dh I	s V p	r u:	v V l
di-	sap-	pro-	ving
dh I	s V p	r u:	v I N
di-	sap-	prove
dh I	s V p	r u: v
di-	sap-	proved
dh I	s V p	r u: v d
di-	sap-	proves
dh I	s V p	r u: v z
di-	sar-	ma-	ment
dh I	s Q@	m V	m V n t
di-	sar-	ming
dh I	s Q@	m I N
di-	sar-	ming-	ly
dh I	s Q@	m I N	l i:
di-	sar-	ray
dh I	s @r	eI
di-	sarm
dh I	s Q@ m
di-	sarmed
dh I	s Q@ m d
di-	sas-	sem-	ble
dh I	s V	s e m	b V l
di-	sas-	sem-	bled
dh I	s V	s e m	b V l d
di-	sas-	so-	ci-	a-	ted
dh I	s V	s @U	S i:	eI	t V d
di-	sas-	so-	ci-	ate
dh I	s V	s @U	S i:	eI t
di-	sas-	ter
dh I	z { s	t @r
di-	sas-	ters
dh I	z { s	t @r z
di-	sast-	rous
dh I	z { s	t r V s
di-	sast-	rous-	ly
dh I	z { s	t r V s	l i:
di-	se-	qui-	li-	bri-	um
dh I	s i: k	w I	l I b	r i:	V m
di-	sea-	ses
dh I	z i:	z V z
di-	sea-	se's
dh I	z i:	z V z
di-	sease
dh I	z i: z
di-	seased
dh I	z i: z d
di-	sem-	bar-	ka-	tion
dh I	s e m	b Q@	k eI	S V n
di-	sem-	bark
dh I	s e m	b Q@ k
di-	sem-	bo-	died
dh I	s V	b Q	d i: d
di-	sem-	bo-	dy
dh I	s V	b Q	d i:
di-	sen-	chan-	ted
dh I	s V n	tS { n	t V d
di-	sen-	chant
dh I	s V n	tS { n t
di-	sen-	chant-	ment
dh I	s V n	tS { n	t m V n t
di-	sen-	fran-	chise
dh I	s V n	f r { n	tS aI z
di-	sen-	fran-	chise-	ment
dh I	s V n	f r { n	tS aI z	m V n t
di-	sen-	fran-	chised
dh I	s V n	f r { n	tS aI z d
di-	sen-	ga-	ging
dh I	s V n	g eI	dZ I N
di-	sen-	gage
dh I	s V n	g eI dZ
di-	sen-	gage-	ment
dh I	s V n	g eI dZ	m V n t
di-	sen-	gaged
dh I	s V n	g eI dZ d
di-	sen-	tan-	gle
dh I	s V n	t { N	g V l
di-	ses-	tab-	lish-	ment
dh I	s V s	t { b	l I S	m V n t
di-	sha-	roon
dh I	S @r	u: n
di-	she-	vel
dh I	S e	v V l
di-	she-	veled
dh I	S e	v V l d
di-	shear-	te-	ning
dh I s	h Q@	t V	n I N
di-	shear-	ten
dh I s	h Q@	t V n
di-	shear-	tened
dh I s	h Q@	t V n d
di-	sher
dh I	S @r
di-	shes
dh I	S V z
di-	shing
dh I	S I N
di-	sil-	lu-	sio-	ning
dh I	s I	l u:	Z V	n I N
di-	sil-	lu-	sion
dh I	s I	l u:	Z V n
di-	sil-	lu-	sion-	ment
dh I	s I	l u:	Z V n	m V n t
di-	sil-	lu-	sioned
dh I	s I	l u:	Z V n d
di-	sin-	cen-	tive
dh I	s I n	s e n	t I v
di-	sin-	cen-	tives
dh I	s I n	s e n	t I v z
di-	sin-	fec-	tant
dh I	s I n	f e k	t V n t
di-	sin-	fec-	tants
dh I	s I n	f e k	t V n t s
di-	sin-	fec-	tion
dh I	s I n	f e k	S V n
di-	sin-	fect
dh I	s I n	f e k t
di-	sin-	fla-	tio-	na-	ry
dh I	s V n	f l eI	S V	n e@	i:
di-	sin-	fla-	tion
dh I	s I n	f l eI	S V n
di-	sin-	flate
dh I	s I n	f l eI t
di-	sin-	for-	ma-	tion
dh I	s I n	f @r	m eI	S V n
di-	sin-	form
dh I	s I n	f O@ m
di-	sin-	ge-	nu-	ous
dh I	s I n	dZ e n	j u:	V s
di-	sin-	ge-	nu-	ous-	ness
dh I	s I n	dZ e n	j u:	V s	n V s
di-	sin-	te-	rest
dh I	s I n	t @r	V s t
di-	sin-	teg-	ra-	ted
dh I	s I n	t V g	r eI	t V d
di-	sin-	teg-	ra-	ting
dh I	s I n	t V g	r eI	t I N
di-	sin-	teg-	ra-	tion
dh I	s I n	t V g	r eI	S V n
di-	sin-	teg-	rate
dh I	s I n	t V g	r eI t
di-	sin-	teg-	rates
dh I	s I n	t V g	r eI t s
di-	sin-	vest-	ment
dh I	s I n	v e s	t m V n t
di-	sin-	vi-	ted
dh I	s I n	v aI	t V d
di-	sin-	vite
dh I	s I n	v aI t
di-	sinc-	li-	na-	tion
dh I	s I n	k l I	n eI	S V n
di-	sinc-	line
dh I	s I n	k l aI n
di-	sinc-	lined
dh I	s I n	k l aI n d
di-	sinte-	res-	ted
dh I	s I n	t r V s	t V d
di-	so-	ri-	en-	ta-	tion
dh I	s O@	i:	V n	t eI	S V n
di-	so-	ri-	en-	ted
dh I	s O@	i:	e n	t V d
di-	so-	ri-	en-	ting
dh I	s O@	i:	e n	t I N
di-	so-	ri-	ent
dh I	s O@	i:	e n t
di-	sor-	der
dh I	s O@	d @r
di-	sor-	der-	ly
dh I	s O@	d @r	l i:
di-	sor-	dered
dh I	s O@	d @r d
di-	sor-	ders
dh I	s O@	d @r z
di-	sor-	ga-	ni-	za-	tion
dh I	s O@	g V	n V	z eI	S V n
di-	sor-	ga-	nize
dh I	s O@	g V	n aI z
di-	sor-	ga-	nized
dh I	s O@	g V	n aI z d
di-	sown
dh I	s @U n
di-	sowned
dh I	s @U n d
di-	suse
dh I s	j u: s
di-	the-	ring
dh I	D @r	I N
di-	ther
dh I	D @r
di-	thers
dh I	D @r z
di-	thy-	ramb
dh I	T @r	{ m
di-	u-	re-	tic
dh aI	u:	r e	t I k
di-	u-	re-	tics
dh aI	u:	r e	t I k s
di-	ur-	nal
dh aI	@r	n V l
di-	ur-	nal-	ly
dh aI	@r	n V	l i:
di-	va
dh i:	v V
di-	va-	lent
dh aI	v eI	l V n t
di-	van
dh I	v { n
di-	vas
dh i:	v V z
di-	ver
dh aI	v @r
di-	ver-	gen-	ces
dh aI	v @r	dZ V n	s V z
)"
R"(di-	ver-	gence
dh aI	v @r	dZ V n s
di-	ver-	gent
dh aI	v @r	dZ V n t
di-	ver-	ges
dh aI	v @r	dZ V z
di-	ver-	ging
dh aI	v @r	dZ I N
di-	ver-	si-	fi-	ca-	tion
dh aI	v @r	s V	f I	k eI	S V n
di-	ver-	si-	fi-	ca-	tions
dh aI	v @r	s V	f I	k eI	S V n z
di-	ver-	si-	fied
dh aI	v @r	s I	f aI d
di-	ver-	si-	fy
dh aI	v @r	s I	f aI
di-	ver-	si-	fy-	ing
dh aI	v @r	s I	f aI	I N
di-	ver-	si-	ty
dh I	v @r	s I	t i:
di-	ver-	sio-	na-	ry
dh aI	v @r	Z V	n e@	i:
di-	ver-	sion
dh aI	v @r	Z V n
di-	ver-	sions
dh I	v @r	Z V n z
di-	ver-	ted
dh aI	v @r	t V d
di-	ver-	ti-	cu-	la
dh aI	v @r	t I k	j V	l V
di-	ver-	ti-	cu-	lum
dh aI	v @r	t I k	j V	l V m
di-	ver-	ti-	men-	to
dh I	v @r	t I	m e n	t @U
di-	ver-	ting
dh aI	v @r	t I N
di-	verge
dh I	v @r dZ
di-	verged
dh aI	v @r dZ d
di-	vers
dh aI	v @r z
di-	ver's
dh aI	v @r z
di-	verse
dh aI	v @r s
di-	vert
dh aI	v @r t
di-	verts
dh aI	v @r t s
di-	ves-	ted
dh aI	v e s	t V d
di-	ves-	ti-	ture
dh I	v e s	t I	tS @r
di-	ves-	ti-	tures
dh I	v e s	t I	tS @r z
di-	ves-	ting
dh aI	v e s	t I N
di-	vest
dh aI	v e s t
di-	vest-	ment
dh aI	v e s	t m V n t
di-	vest-	ments
dh aI	v e s	t m V n t s
di-	vests
dh aI	v e s t s
di-	vi
dh i:	v i:
di-	vi-	ded
dh I	v aI	d V d
di-	vi-	dend
dh I	v I	d e n d
di-	vi-	dends
dh I	v I	d e n d z
di-	vi-	dend's
dh I	v I	d e n d z
di-	vi-	der
dh I	v aI	d @r
di-	vi-	ding
dh I	v aI	d I N
di-	vi-	na-	tion
dh I	v I	n eI	S V n
di-	vi-	ni-	ties
dh I	v I	n I	t i: z
di-	vi-	ni-	ty
dh I	v I	n I	t i:
di-	vi-	ning
dh V	v aI	n I N
di-	vi-	si-	ble
dh I	v I	z I	b V l
di-	vi-	sio-	nal
dh I	v I	Z V	n V l
di-	vi-	sion
dh I	v I	Z V n
di-	vi-	sions
dh I	v I	Z V n z
di-	vi-	sion's
dh I	v I	Z V n z
di-	vi-	sive
dh I	v aI	s I v
di-	vi-	sive-	ness
dh I	v aI	s I v	n V s
di-	vi-	sor
dh I	v aI	z @r
di-	vide
dh I	v aI d
di-	vides
dh I	v aI d z
di-	vine
dh I	v aI n
di-	vine-	ly
dh I	v aI n	l i:
di-	ving
dh aI	v I N
di-	vis
dh i:	v I s
d'i-	voire
dh i: v	w Q@
di-	vor-	cee
dh V	v O@	s i:
di-	vor-	ces
dh I	v O@	s V z
di-	vor-	cing
dh I	v O@	s I N
di-	vorce
dh I	v O@ s
di-	vorced
dh I	v O@ s t
di-	vul-	ging
dh I	v V l	dZ I N
di-	vulge
dh I	v V l dZ
di-	vulged
dh I	v V l dZ d
di-	xie
dh I k	s i:
di-	xie-	land
dh I k	s i:	l { n d
di-	xon
dh I k	s V n
di-	xon's
dh I k	s V n z
di-	xy
dh I k	s i:
dia-	hann
dh aI	{ n
dia-	mond
dh aI	m V n d
dia-	monds
dh aI	m V n d z
dia-	mond's
dh aI	m V n d z
dia-	pe-	ring
dh aI	p @r	I N
dia-	per
dh aI	p @r
dib-	ble
dh I	b V l
dib-	bled
dh I	b V l d
dib-	la-	si
dh V b	l Q	s i:
dibb
dh I b
dibs
dh I b z
dic
dh I k
dic-	ke-	ring
dh I	k @r	I N
dic-	ken-	si-	an
dh I	k e n	z i:	V n
dic-	ken-	son
dh I	k V n	s V n
dic-	ken-	s's
dh I	k V n	z V z
dic-	kens
dh I	k V n z
dic-	ker
dh I	k @r
dic-	ker-	son
dh I	k @r	s V n
dic-	kered
dh I	k @r d
dic-	key
dh I	k i:
dic-	key's
dh I	k i: z
dic-	kie
dh I	k i:
dic-	kin-	son
dh I	k I n	s V n
dic-	ky
dh I	k i:
dic-	ta
dh I k	t V
dic-	ta-	phone
dh I k	t V	f @U n
dic-	ta-	ted
dh I k	t eI	t V d
dic-	ta-	ting
dh I k	t eI	t I N
dic-	ta-	tion
dh I k	t eI	S V n
dic-	ta-	to-	ri-	al
dh I k	t V	t O@	i:	V l
dic-	ta-	tor
dh I k	t eI	t @r
dic-	ta-	tor-	ship
dh I k	t eI	t @r	S I p
dic-	ta-	tor-	ships
dh I k	t eI	t @r	S I p s
dic-	ta-	tors
dh I k	t eI	t @r z
dic-	tate
dh I k	t eI t
dic-	tates
dh I k	t eI t s
dic-	tio-	na-	ries
dh I k	S V	n e@	i: z
dic-	tio-	na-	ry
dh I k	S V	n e@	i:
dic-	tion
dh I k	S V n
dic-	tum
dh I k	t V m
dice
dh aI s
diced
dh aI s t
dich-	ro-	ic
dh aI k	r @U	I k
dich-	ro-	mate
dh aI k	r @U	m eI t
dich-	ter
dh I k	t @r
dick
dh I k
dick-	man
dh I k	m V n
dick-	son
dh I k	s V n
dicks
dh I k s
dick's
dh I k s
did
dh I d
did-	dy
dh I	d i:
didd-	ley
dh I d	l i:
die
dh aI
die-	bold
dh aI	b @U l d
die-	hard
dh aI	h Q@ d
die-	hards
dh aI	h Q@ d z
die-	ner
dh i:	n @r
die-	nes
dh i:	n e z
die-	rolf
dh I@	@U l f
die-	sel
dh i:	s V l
die-	sels
dh i:	z V l z
die-	ses
dh aI	z V z
die-	te-	rich
dh i:	t @r	I k
die-	ter
dh i:	t @r
died
dh aI d
diehl
dh i: l
diel
dh i: l
diem
dh i: m
dierks
dh i: r k s
dies
dh aI z
diet-	rich
dh i: t	r I k
dietsche
dh i: tS
dietz
dh i: t s
dif-	fe-	ren-	ces
dh I	f @r	V n	s V z
dif-	fe-	ren-	ti-	a-	ted
dh I	f @r	e n	tS i:	eI	t I d
dif-	fe-	ren-	ti-	a-	ting
dh I	f @r	e n	tS i:	eI	t I N
dif-	fe-	ren-	ti-	a-	tion
dh I	f @r	e n	S i:	eI	S V n
dif-	fe-	ren-	ti-	ate
dh I	f @r	e n	S i:	eI t
dif-	fe-	ren-	ti-	ates
dh I	f @r	e n	S i:	eI t s
dif-	fe-	ren-	tial
dh I	f @r	e n	tS V l
dif-	fe-	ren-	tials
dh I	f @r	e n	tS V l z
dif-	fe-	rence
dh I	f @r	V n s
dif-	fe-	rent
dh I	f @r	V n t
dif-	fe-	ring
dh I	f @r	I N
dif-	fer
dh I	f @r
dif-	fered
dh I	f @r d
dif-	fers
dh I	f @r z
dif-	fi-	cul-	ties
dh I	f I	k V l	t i: z
dif-	fi-	cul-	ty
dh I	f I	k V l	t i:
dif-	fi-	cult
dh I	f I	k V l t
dif-	fi-	cult-	ly
dh I	f I	k V l	t l i:
dif-	fu-	ses
dh V f	j u:	z V z
dif-	fu-	sing
dh V f	j u:	z I N
dif-	fu-	sion
dh V f	j u:	Z V n
dif-	fuse
dh V f	j u: s
dif-	fused
dh V f	j u: z d
diff
dh I f
diff-	rac-	tion
dh V f	r { k	S V n
diff-	ract
dh V f	r { k t
diffe-	rent-	ly
dh I f	r V n	t l i:
dig
dh I g
dig-	by
dh I g	b i:
dig-	ger
dh I	g @r
dig-	gers
dh I	g @r z
dig-	ging
dh I	g I N
dig-	gins
dh I	g I n z
dig-	ni-	fied
dh I g	n I	f aI d
dig-	ni-	fy
dh I g	n I	f aI
dig-	ni-	ta-	ries
dh I g	n I	t e@	i: z
dig-	ni-	ta-	ry
dh I g	n I	t e@	i:
dig-	ni-	ty
dh I g	n I	t i:
dig-	res-	sing
dh aI g	r e	s I N
dig-	res-	sion
dh aI g	r e	S V n
dig-	res-	sions
dh aI g	r e	S V n z
dig-	ress
dh aI g	r e s
dig-	ressed
dh aI g	r e s t
diggs
dh I g z
digs
dh I g z
dike
dh aI k
dikes
dh aI k s
dil-	lard
dh I	l @r d
dil-	lard's
dh I	l @r d z
dil-	ler
dh I	l @r
dil-	ler's
dh I	l @r z
dil-	ley
dh I	l i:
dil-	lie
dh I	l i:
dil-	lin-	ger
dh I	l I	N @r
dil-	ling
dh I	l I N
dil-	ling-	ham
dh I	l I N	h { m
dil-	lon
dh I	l V n
dil-	lon's
dh I	l V n z
dil-	ly
dh I	l i:
dil-	ti-	a-	zem
dh I l	t i:	V	z e m
dil-	worth
dh I l	w @r T
dilks
dh I l k s
dill
dh I l
dille
dh I l
dills
dh I l z
dim
dh I m
dim-	ly
dh I m	l i:
dim-	mer
dh I	m @r
dim-	mers
dh I	m @r z
dim-	mick
dh I	m I k
dim-	ming
dh I	m I N
dim-	mitt
dh I	m I t
dim-	ple
dh I m	p V l
dim-	pled
dh I m	p V l d
dime
dh aI m
dimes
dh aI m z
dime's
dh aI m z
dimmed
dh I m d
dims
dh I m z
din
dh I n
din-	gee
dh I N	g i:
din-	gell
dh I N	g V l
din-	gell's
dh I N	g V l z
din-	ger
dh I	N @r
din-	ges
dh I n	dZ V z
din-	gess
dh I N	g I s
din-	ghy
dh I	N i:
din-	gle
dh I N	g V l
din-	go
dh I N	g @U
din-	gus
dh I N	g V s
din-	ner
dh I	n @r
din-	wid-	die
dh I n	w I	d i:
dine
dh aI n
dined
dh aI n d
dines
dh aI n z
ding
dh I N
ding-	man
dh I N	m V n
ding-	wall
dh I N	g w V l
dings
dh I N z
dins-	dale
dh I n	z d eI l
dins-	more
dh i: n	s m O@
dinse
dh I n s
dint
dh I n t
dip
dh I p
dip-	lo-	ma
dh V p	l @U	m V
dip-	lo-	ma-	cy
dh V p	l @U	m V	s i:
dip-	lo-	ma-	tic
dh I p	l V	m {	t I k
dip-	lo-	ma-	tical-	ly
dh I p	l V	m {	t I k	l i:
dip-	lo-	mas
dh V p	l @U	m V z
dip-	lo-	mat
dh I p	l V	m { t
dip-	lo-	mats
dh I p	l V	m { t s
dip-	lo-	mat's
dh I p	l V	m { t s
dip-	per
dh I	p @r
dip-	pers
dh I	p @r z
dip-	ping
dh I	p I N
dip-	pold
dh I	p @U l d
dip-	py
dh I	p i:
dip-	stick
dh I p	s t I k
diph-	the-	ri-	a
dh I f	T I@	i:	V
dipped
dh I p t
dips
dh I p s
dir-	hams
dh @r	V m z
dir-	ti-	er
dh @r	t i:	@r
dir-	ti-	est
dh @r	t i:	V s t
dir-	ty
dh @r	t i:
dire
dh aI r
dirge
dh @r dZ
dirk
dh @r k
dirkes
dh @r k s
dirks
dh @r k s
dirt
dh @r t
dirt's
dh @r t s
dis
dh I s
di's
dh aI z
dis-	ban-	ded
dh I s	b { n	d V d
dis-	ban-	ding
dh I s	b { n	d I N
dis-	band
dh I s	b { n d
dis-	bar
dh I s	b Q@
dis-	bar-	ment
dh I s	b Q@	m V n t
dis-	barred
dh I s	b Q@ d
dis-	be-	lie-	ving
dh I s	b V	l i:	v I N
dis-	be-	lief
dh I s	b V	l i: f
dis-	be-	lieve
dh I s	b V	l i: v
dis-	bur-	sing
dh I s	b @r	s I N
dis-	burse
dh I s	b @r s
dis-	burse-	ment
dh I s	b @r s	m V n t
dis-	burse-	ments
dh I s	b @r s	m V n t s
dis-	bursed
dh I s	b @r s t
dis-	car-	ded
dh I s	k Q@	d V d
dis-	car-	ding
dh I s	k Q@	d I N
dis-	card
dh I s	k Q@ d
dis-	cards
dh I s	k Q@ d z
dis-	cer-	ni-	ble
dh I	s @r	n I	b V l
dis-	cer-	ning
dh I	s @r	n I N
dis-	cern
dh I	s @r n
dis-	cern-	ment
dh I	s @r n	m V n t
dis-	cerned
dh I	s @r n d
dis-	char-	ges
dh I s	tS Q@	dZ V z
dis-	char-	ging
dh I s	tS Q@	dZ I N
dis-	charge
dh I s	tS Q@ dZ
dis-	charged
dh I s	tS Q@ dZ d
dis-	ci-	ple
dh V	s aI	p V l
dis-	ci-	ples
dh V	s aI	p V l z
dis-	cip-	li-	na-	ri-	an
dh I	s I p	l I	n e@	i:	V n
dis-	cip-	li-	na-	ri-	ans
dh I	s I p	l I	n e@	i:	V n z
dis-	cip-	li-	na-	ry
dh I	s I p	l I	n e@	i:
dis-	cip-	li-	ning
dh I	s I p	l I	n I N
dis-	cip-	line
dh I	s I p	l I n
dis-	cip-	lined
dh I	s I p	l I n d
dis-	cip-	lines
dh I	s I p	l I n z
dis-	co
dh I s	k @U
dis-	co-	lo-	ra-	tion
dh I s	k V	l @r	eI	S V n
dis-	co-	lo-	ra-	tions
dh I s	k V	l @r	eI	S V n z
dis-	co-	lor
dh I s	k V	l @r
dis-	co-	lored
dh I s	k V	l @r d
dis-	co-	lors
dh I s	k V	l @r z
dis-	co-	theque
dh I s	k @U	t e k
dis-	cog-	ra-	phy
dh V s	k O: g	r V	f i:
dis-	com-	fort
dh I s	k V m	f @r t
dis-	con-	cer-	ting
dh I s	k V n	s @r	t I N
dis-	con-	cert
dh I s	k V n	s @r t
dis-	con-	certs
dh I s	k V n	s @r t s
dis-	con-	nec-	ted
dh I s	k V	n e k	t V d
dis-	con-	nec-	ting
dh I s	k V	n e k	t I N
dis-	con-	nec-	tion
dh I s	k V	n e k	S V n
dis-	con-	nect
dh I s	k V	n e k t
dis-	con-	ten-	ted
dh I s	k V n	t e n	t V d
dis-	con-	tent
dh I s	k V n	t e n t
dis-	con-	tents
dh I s	k V n	t e n t s
dis-	con-	ti-	nu-	a-	tion
dh I s	k V n	t I n	j u:	eI	S V n
dis-	con-	ti-	nu-	ance
dh I s	k V n	t I n	j u:	V n s
dis-	con-	ti-	nu-	i-	ty
dh I s	k Q n	t I	n u:	I	t i:
dis-	con-	ti-	nu-	ing
dh I s	k V n	t I n	j u:	I N
dis-	con-	ti-	nue
dh I s	k V n	t I n	j u:
dis-	con-	ti-	nued
dh I s	k V n	t I n	j u: d
dis-	cor-	dant
dh I s	k O@	d V n t
dis-	cord
dh I s	k O@ d
dis-	cos
dh I s	k @U z
dis-	cou-	ra-	ges
dh I s	k @r	I	dZ V z
dis-	cou-	ra-	ging
dh I s	k @r	V	dZ I N
dis-	cou-	rage
dh I s	k @r	I dZ
dis-	cou-	rage-	ment
dh I s	k @r	I dZ	m V n t
dis-	cou-	raged
dh I s	k @r	V dZ d
dis-	coun-	ta-	ble
dh I s	k aU n	t V	b V l
dis-	coun-	ted
dh I s	k aU n	t V d
dis-	coun-	ter
dh I s	k aU n	t @r
dis-	coun-	ters
dh I s	k aU n	t @r z
dis-	coun-	ting
dh I s	k aU n	t I N
dis-	count
dh I s	k aU n t
dis-	counts
dh I s	k aU n t s
dis-	cour-	ses
dh I s	k O@	s V z
dis-	course
dh I s	k O@ s
dis-	cur-	sive
dh I s	k @r	s I v
dis-	cus
dh I s	k V s
dis-	cus-	ses
dh I s	k V	s V z
dis-	cus-	sing
dh I s	k V	s I N
dis-	cus-	sion
dh I s	k V	S V n
dis-	cus-	sions
dh I s	k V	S V n z
dis-	cuss
dh I s	k V s
dis-	cussed
dh I s	k V s t
dis-	dai-	ning
dh I s	d eI	n I N
dis-	dain
dh I s	d eI n
dis-	dain-	ful
dh I s	d eI n	f V l
dis-	dained
dh I s	d eI n d
dis-	dains
dh I s	d eI n z
dis-	fa-	vo-	ring
dh I s	f eI	v @r	I N
dis-	fa-	vor
dh I s	f eI	v @r
dis-	fi-	gu-	ring
dh I s	f I g	j @r	I N
dis-	fi-	gure
dh I s	f I g	j @r
dis-	fi-	gure-	ment
dh I s	f I g	j @r	m e n t
dis-	fi-	gured
dh I s	f I g	j @r d
dis-	gorge
dh I s	g O@ dZ
dis-	gorge-	ment
dh I s	g O@ dZ	m V n t
dis-	gorged
dh I s	g O@ dZ d
dis-	gui-	ses
dh I s	g aI	z V z
dis-	gui-	sing
dh I s	g aI	z I N
dis-	guise
dh I s	g aI z
dis-	guised
dh I s	g aI z d
dis-	gus-	ted
dh I s	g V s	t V d
dis-	gus-	ting
dh I s	g V s	t I N
dis-	gust
dh I s	g V s t
dis-	gusts
dh I s	g V s t s
dis-	har-	mo-	ny
dh I s	h Q@	m V	n i:
dis-	ho-	nes-	ty
dh I	s Q	n V s	t i:
dis-	ho-	nest
dh I	s Q	n V s t
dis-	ho-	nest-	ly
dh I	s O:	n V s	t l i:
dis-	ho-	no-	ra-	ble
dh I	s Q	n @r	V	b V l
dis-	ho-	nor
dh I	s Q	n @r
dis-	ho-	nored
dh I	s Q	n @r d
dis-	join-	ted
dh I s	dZ OI n	t V d
dis-	joint
dh I s	dZ OI n t
dis-	kette
dh I s	k e t
dis-	kettes
dh I s	k e t s
dis-	kin
dh I s	k I n
dis-	li-	king
dh I s	l aI	k I N
dis-	like
dh I s	l aI k
dis-	liked
dh I s	l aI k t
dis-	likes
dh I s	l aI k s
dis-	lo-	ca-	ted
dh I s	l @U	k eI	t V d
dis-	lo-	ca-	tion
dh I s	l @U	k eI	S V n
dis-	lo-	ca-	tions
dh I s	l @U	k eI	S V n z
dis-	lo-	cate
dh I s	l @U	k eI t
dis-	lo-	yal
dh I s	l OI	V l
dis-	lo-	yal-	ty
dh I s	l OI	V l	t i:
dis-	lod-	ging
dh I s	l Q	dZ I N
dis-	lodge
dh I s	l Q dZ
dis-	lodged
dh I s	l Q dZ d
dis-	mal
dh I z	m V l
dis-	mal-	ly
dh I z	m V	l i:
dis-	man-	t-	ling
dh I s	m { n	t V	l I N
dis-	man-	tle
dh I s	m { n	t V l
dis-	man-	tle-	ment
dh I s	m { n	t V l	m V n t
dis-	man-	tled
dh I s	m { n	t V l d
dis-	man-	tles
dh I s	m { n	t V l z
dis-	may
dh I s	m eI
dis-	may-	ing
dh I s	m eI	I N
dis-	mayed
dh I s	m eI d
dis-	mays
dh I s	m eI z
dis-	mem-	be-	ring
dh I s	m e m	b @r	I N
dis-	mem-	ber
dh I s	m e m	b @r
dis-	mem-	ber-	ment
dh I s	m e m	b @r	m V n t
dis-	mem-	bered
dh I s	m e m	b @r d
dis-	mis-	sal
dh I s	m I	s V l
dis-	mis-	sals
dh I s	m I	s V l z
dis-	mis-	ses
dh I s	m I	s V z
dis-	mis-	sing
dh I s	m I	s I N
dis-	mis-	sive
dh I s	m I	s I v
dis-	miss
dh I s	m I s
dis-	missed
dh I s	m I s t
dis-	ney
dh I z	n i:
dis-	ney-	land
dh I z	n i:	l { n d
dis-	ney's
dh I z	n i: z
dis-	o-	be-	di-	ence
dh I	s V	b i:	d i:	V n s
dis-	o-	be-	di-	ent
dh I	s V	b i:	d i:	V n t
dis-	o-	be-	ying
dh I	s @U	b eI	I N
dis-	o-	bey
dh I	s V	b eI
dis-	o-	beyed
dh I	s @U	b eI d
dis-	pa-	ra-	ges
dh I s	p e@	I	dZ V z
dis-	pa-	ra-	ging
dh I s	p e@	I	dZ I N
dis-	pa-	ra-	ging-	ly
dh I s	p e@	I	dZ I N	l i:
dis-	pa-	rage
dh I s	p e@	I dZ
dis-	pa-	raged
dh I s	p e@	I dZ d
dis-	pa-	rate
dh I s	p @r	V t
dis-	pa-	ri-	ties
dh I s	p e@	I	t i: z
dis-	pa-	ri-	ty
dh I s	p e@	I	t i:
dis-	pair
dh I s	p e@
dis-	pas-	sio-	nate
dh I s	p {	S V	n V t
dis-	pas-	sio-	nate-	ly
dh I s	p {	S V	n V t	l i:
dis-	pat-	cher
dh I s	p {	tS @r
dis-	pat-	chers
dh I s	p {	tS @r z
dis-	pat-	cher's
dh I s	p {	tS @r z
dis-	pat-	ches
dh I s	p {	tS V z
dis-	pat-	ching
dh I s	p {	tS I N
dis-	patch
dh I s	p { tS
dis-	patched
dh I s	p { tS t
dis-	pel
dh I s	p e l
dis-	pel-	ling
dh I s	p e	l I N
dis-	pell
dh I s	p e l
dis-	pelled
dh I s	p e l d
dis-	pels
dh I s	p e l z
dis-	pen-	sa-	ble
dh I s	p e n	s V	b V l
dis-	pen-	sa-	ry
dh I s	p e n	s @r	i:
dis-	pen-	sa-	tion
dh I s	p V n	s eI	S V n
dis-	pen-	ser
dh I s	p e n	s @r
dis-	pen-	sers
dh I s	p e n	s @r z
dis-	pen-	ses
dh I s	p e n	s V z
dis-	pen-	sing
dh I s	p e n	s I N
dis-	pense
dh I s	p e n s
dis-	pensed
dh I s	p e n s t
dis-	per-	sal
dh I s	p @r	s V l
dis-	per-	sant
dh I s	p @r	s V n t
dis-	per-	sants
dh I s	p @r	s V n t s
dis-	per-	sing
dh I s	p @r	s I N
dis-	per-	sion
dh I s	p @r	Z V n
dis-	per-	sive
dh I s	p @r	s I v
dis-	perse
dh I s	p @r s
dis-	persed
dh I s	p @r s t
dis-	pi-	ri-	ted
dh I s	p I@	I	t V d
dis-	pi-	ri-	ting
dh I s	p I@	I	t I N
dis-	pla-	ces
dh I s	p l eI	s V z
dis-	pla-	cing
dh I s	p l eI	s I N
dis-	place
dh I s	p l eI s
dis-	place-	ment
dh I s	p l eI s	m V n t
dis-	place-	ments
dh I s	p l eI s	m V n t s
dis-	placed
dh I s	p l eI s t
dis-	play
dh I s	p l eI
dis-	play-	ing
dh I s	p l eI	I N
dis-	played
dh I s	p l eI d
dis-	plays
dh I s	p l eI z
dis-	plea-	sure
dh I s	p l e	Z @r
dis-	please
dh I s	p l i: z
dis-	pleased
dh I s	p l i: z d
dis-	po-	sa-	ble
dh I s	p @U	z V	b V l
dis-	po-	sa-	bles
dh I s	p @U	z V	b V l z
dis-	po-	sal
dh I s	p @U	z V l
dis-	po-	sals
dh I s	p @U	z V l z
dis-	po-	ser
dh I s	p @U	z @r
dis-	po-	ses
dh I s	p @U	z V z
dis-	po-	si-	tion
dh I s	p V	z I	S V n
dis-	po-	si-	tions
dh I s	p V	z I	S V n z
dis-	po-	si-	tive
dh I s	p Q	z I	t I v
dis-	po-	sing
dh I s	p @U	z I N
dis-	pos-	sess
dh I s	p V	z e s
dis-	pos-	sessed
dh I s	p V	z e s t
dis-	pose
dh I s	p @U z
dis-	posed
dh I s	p @U z d
dis-	pu-	ta-	tion
dh I s	p j u:	t eI	S V n
dis-	pu-	ted
dh I s	p j u:	t V d
dis-	pu-	ting
dh I s	p j u:	t I N
dis-	pute
dh I s	p j u: t
dis-	putes
dh I s	p j u: t s
dis-	qua-	li-	fi-	ca-	tion
dh I s	k w Q	l I	f I	k eI	S V n
dis-	qua-	li-	fied
dh I s	k w Q	l I	f aI d
dis-	qua-	li-	fies
dh I s	k w Q	l I	f aI z
dis-	qua-	li-	fy
dh I s	k w Q	l I	f aI
dis-	qua-	li-	fy-	ing
dh I s	k w Q	l I	f aI	I N
dis-	qui-	e-	ting
dh I s	k w aI	V	t I N
dis-	qui-	et
dh I s	k w aI	V t
dis-	rae-	li
dh I z	r eI	l i:
dis-	re-	gar-	ded
dh I s	r I	g Q@	d V d
dis-	re-	gar-	ding
dh I s	r I	g Q@	d I N
dis-	re-	gard
dh I s	r I	g Q@ d
dis-	re-	gards
dh I s	r I	g Q@ d z
dis-	re-	pair
dh I s	r V	p e@
dis-	re-	pu-	ta-	ble
dh I s	r e p	j V	t V	b V l
dis-	re-	pute
dh I s	r V p	j u: t
dis-	res-	pec-	ted
dh I s	r V s	p e k	t V d
dis-	res-	pec-	ting
dh I s	r V s	p e k	t I N
dis-	res-	pect
dh I s	r V s	p e k t
)"
R"(dis-	res-	pect-	ful
dh I s	r V s	p e k	t f V l
dis-	res-	pects
dh I s	r V s	p e k t s
dis-	se-	mi-	na-	ted
dh I	s e	m I	n eI	t I d
dis-	se-	mi-	na-	ting
dh I	s e	m I	n eI	t I N
dis-	se-	mi-	na-	tion
dh I	s e	m I	n eI	S V n
dis-	se-	mi-	nate
dh I	s e	m V	n eI t
dis-	sec-	ted
dh aI	s e k	t V d
dis-	sec-	ting
dh aI	s e k	t I N
dis-	sec-	tion
dh aI	s e k	S V n
dis-	sec-	tions
dh aI	s e k	S V n z
dis-	sect
dh aI	s e k t
dis-	sects
dh aI	s e k t s
dis-	sem-	ble
dh I	s e m	b V l
dis-	semb-	ling
dh I	s e m	b l I N
dis-	sen-	sion
dh I	s e n	S V n
dis-	sen-	ted
dh I	s e n	t V d
dis-	sen-	ter
dh I	s e n	t @r
dis-	sen-	ters
dh I	s e n	t @r z
dis-	sen-	ting
dh I	s e n	t I N
dis-	sent
dh I	s e n t
dis-	sents
dh I	s e n t s
dis-	ser-	ta-	tion
dh I	s @r	t eI	S V n
dis-	ser-	vice
dh I s	s @r	v I s
dis-	si-	dence
dh I	s I	d V n s
dis-	si-	dent
dh I	s I	d V n t
dis-	si-	dents
dh I	s I	d V n t s
dis-	si-	mi-	la-	ri-	ty
dh I s	s I	m I	l {	r I	t i:
dis-	si-	mi-	lar
dh I s	s I	m V	l @r
dis-	si-	pa-	ted
dh I	s I	p eI	t I d
dis-	si-	pa-	ting
dh I	s I	p eI	t I N
dis-	si-	pa-	tion
dh I	s I	p eI	S V n
dis-	si-	pa-	tive
dh I	s I	p eI	t I v
dis-	si-	pate
dh I	s I	p eI t
dis-	si-	pates
dh I	s I	p eI t s
dis-	so-	ci-	a-	tion
dh I	s @U	s i:	eI	S V n
dis-	so-	ci-	ate
dh I	s @U	s i:	eI t
dis-	so-	lu-	tion
dh I	s V	l u:	S V n
dis-	so-	nance
dh I	s V	n V n s
dis-	so-	nant
dh I	s V	n V n t
dis-	sol-	ver
dh I	z Q l	v @r
dis-	sol-	vers
dh I	z Q l	v @r z
dis-	sol-	ving
dh I	z O: l	v I N
dis-	solve
dh I	z Q l v
dis-	solved
dh I	z Q l v d
dis-	solves
dh I	z Q l v z
dis-	sua-	ded
dh I s	w eI	d V d
dis-	suade
dh I s	w eI d
dis-	sym-	met-	ric
dh I	s V	m e t	r I k
dis-	sym-	met-	ry
dh I	s I	m V t	r i:
dis-	tad
dh I s	t V d
dis-	tal
dh I s	t V l
dis-	tan-	ces
dh I s	t V n	s V z
dis-	tan-	cing
dh I s	t V n	s I N
dis-	tance
dh I s	t V n s
dis-	tanced
dh I s	t V n s t
dis-	tant
dh I s	t V n t
dis-	taste
dh I s	t eI s t
dis-	taste-	ful
dh I s	t eI s	t f V l
dis-	tem-	per
dh I s	t e m	p @r
dis-	ten-	ded
dh I s	t e n	d V d
dis-	tend
dh I s	t e n d
dis-	til
dh I s	t I l
dis-	til-	la-	tion
dh I s	t I	l eI	S V n
dis-	til-	late
dh I s	t I	l eI t
dis-	til-	lates
dh I s	t I	l eI t s
dis-	til-	le-	ries
dh I s	t I	l @r	i: z
dis-	til-	le-	ry
dh I s	t I	l @r	i:
dis-	til-	ler
dh I s	t I	l @r
dis-	til-	lers
dh I s	t I	l @r z
dis-	til-	ler's
dh I s	t I	l @r z
dis-	til-	ling
dh I s	t I	l I N
dis-	till
dh I s	t I l
dis-	tilled
dh I s	t I l d
dis-	tills
dh I s	t I l z
dis-	tin-	gui-	sha-	ble
dh I s	t I N	g w I	S V	b V l
dis-	tin-	gui-	shes
dh I s	t I N	g w I	S V z
dis-	tin-	gui-	shing
dh I s	t I N	g w I	S I N
dis-	tin-	guish
dh I s	t I N	g w I S
dis-	tin-	guished
dh I s	t I N	g w I S t
dis-	tinc-	tion
dh I s	t I N	k S V n
dis-	tinc-	tions
dh I s	t I N	k S V n z
dis-	tinc-	tive
dh I s	t I N	k t I v
dis-	tinc-	tive-	ly
dh I s	t I N	k t I v	l i:
dis-	tinc-	tive-	ness
dh I s	t I N	k t I v	n V s
dis-	tinct
dh I s	t I N k t
dis-	tinct-	ly
dh I s	t I N	k t l i:
dis-	tor-	ted
dh I s	t O@	t V d
dis-	tor-	ting
dh I s	t O@	t I N
dis-	tor-	tion
dh I s	t O@	S V n
dis-	tor-	tions
dh I s	t O@	S V n z
dis-	tort
dh I s	t O@ t
dis-	torts
dh I s	t O@ t s
dis-	tur-	ban-	ces
dh I s	t @r	b V n	s V z
dis-	tur-	bance
dh I s	t @r	b V n s
dis-	tur-	bing
dh I s	t @r	b I N
dis-	tur-	bing-	ly
dh I s	t @r	b I N	l i:
dis-	turb
dh I s	t @r b
dis-	turbed
dh I s	t @r b d
dis-	turbs
dh I s	t @r b z
dis-	u-	ni-	ty
dh I s	j u:	n I	t i:
dis-	u-	nion
dh I s	j u: n	j V n
disc
dh I s k
disc-	lai-	mer
dh I s	k l eI	m @r
disc-	lai-	mers
dh I s	k l eI	m @r z
disc-	lai-	ming
dh I s	k l eI	m I N
disc-	laim
dh I s	k l eI m
disc-	laimed
dh I s	k l eI m d
disc-	laims
dh I s	k l eI m z
disc-	lo-	ses
dh I s	k l @U	z V z
disc-	lo-	sing
dh I s	k l @U	z I N
disc-	lo-	sure
dh I s	k l @U	Z @r
disc-	lo-	sures
dh I s	k l @U	Z @r z
disc-	lose
dh I s	k l @U z
disc-	losed
dh I s	k l @U z d
disc-	re-	tio-	na-	ry
dh I s	k r e	S V	n e@	i:
disc-	re-	tion
dh I s	k r e	S V n
disc-	rete
dh I s	k r i: t
disc-	ri-	mi-	na-	ted
dh I s	k r I	m I	n eI	t V d
disc-	ri-	mi-	na-	ting
dh I s	k r I	m I	n eI	t I N
disc-	ri-	mi-	na-	tion
dh I s	k r I	m I	n eI	S V n
disc-	ri-	mi-	na-	to-	ry
dh I s	k r I	m I	n V	t O@	i:
disc-	ri-	mi-	nate
dh I s	k r I	m I	n eI t
disc-	ri-	mi-	nates
dh I s	k r I	m I	n eI t s
discs
dh I s k s
disg-	race
dh I s	g r eI s
disg-	race-	ful
dh I s	g r eI s	f V l
disg-	raced
dh I s	g r eI s t
disg-	run-	t-	ling
dh I s	g r V n	t V	l I N
disg-	run-	tle
dh I s	g r V n	t V l
disg-	run-	tle-	ment
dh I s	g r V n	t V l	m V n t
disg-	run-	tled
dh I s	g r V n	t V l d
dish
dh I S
dish-	wa-	sher
dh I S	w Q	S @r
dish-	wa-	shers
dh I S	w Q	S @r z
dish-	wa-	shing
dh I S	w Q	S I N
dished
dh I S t
disk
dh I s k
disk-	less
dh I s	k l V s
disks
dh I s k s
disp-	ro-	por-	tio-	nate
dh I s	p r V	p O@	S V	n V t
disp-	ro-	por-	tio-	nate-	ly
dh I s	p r V	p O@	S V	n V t	l i:
disp-	ro-	ven
dh I s	p r u:	v V n
disp-	rove
dh I s	p r u: v
disp-	roved
dh I s	p r u: v d
disp-	roves
dh I s	p r u: v z
dist-	rac-	ted
dh I s	t r { k	t V d
dist-	rac-	ting
dh I s	t r { k	t I N
dist-	rac-	tion
dh I s	t r { k	S V n
dist-	rac-	tions
dh I s	t r { k	S V n z
dist-	ract
dh I s	t r { k t
dist-	racts
dh I s	t r { k t s
dist-	raught
dh I s	t r O: t
dist-	res-	ses
dh I s	t r e	s V z
dist-	res-	sing
dh I s	t r e	s I N
dist-	res-	sing-	ly
dh I s	t r e	s I N	l i:
dist-	ress
dh I s	t r e s
dist-	ressed
dh I s	t r e s t
dist-	ri-	bu-	ted
dh I s	t r I b	j V	t V d
dist-	ri-	bu-	ting
dh I s	t r I b	j u:	t I N
dist-	ri-	bu-	tion
dh I s	t r I b	j u:	S V n
dist-	ri-	bu-	tions
dh I s	t r I b	j u:	S V n z
dist-	ri-	bu-	tive
dh I s	t r I b	j u:	t I v
dist-	ri-	bu-	tor
dh I s	t r I b	j V	t @r
dist-	ri-	bu-	tor-	ship
dh I s	t r I b	j u:	t @r	S I p
dist-	ri-	bu-	tor-	ships
dh I s	t r I b	j u:	t @r	S I p s
dist-	ri-	bu-	tors
dh I s	t r I b	j V	t @r z
dist-	ri-	bu-	tor's
dh I s	t r I b	j u:	t @r z
dist-	ri-	bute
dh I s	t r I b	j u: t
dist-	ri-	butes
dh I s	t r I b	j u: t s
dist-	ric-	ting
dh I s	t r I k	t I N
dist-	rict
dh I s	t r I k t
dist-	ricts
dh I s	t r I k t s
dist-	rict's
dh I s	t r I k t s
dist-	rus-	ted
dh I s	t r V s	t V d
dist-	rust
dh I s	t r V s t
dist-	rust-	ful
dh I s	t r V s	t f V l
dist-	rusts
dh I s	t r V s t s
dit-	ches
dh I	tS V z
dit-	ching
dh I	tS I N
dit-	mars
dh I t	m @r z
dit-	more
dh I t	m O@
dit-	sy
dh I t	s i:
dit-	ter
dh I	t @r
dit-	ties
dh I	t i: z
dit-	to
dh I	t @U
dit-	ton
dh I	t V n
dit-	ty
dh I	t i:
dit-	zel
dh I t	z V l
ditch
dh I tS
ditched
dh I tS t
ditt-	man
dh I t	m V n
ditt-	mer
dh I t	m @r
div-	vied
dh I	v i: d
div-	vy
dh I	v i:
dive
dh aI v
dived
dh aI v d
dives
dh aI v z
dix
dh I k s
diz-	zi-	ness
dh I	z i:	n V s
diz-	zy
dh I	z i:
diz-	zy-	ing
dh I	z i:	I N
dja-	kar-	ta
dZ V	k Q@	t V
dja-	kar-	ta's
dZ V	k Q@	t V z
dji-	bou-	ti
dZ I	b u:	t i:
do
dh u:
do-	a-	ble
dh u:	V	b V l
do-	ber-	man
dh @U	b @r	m V n
do-	bie
dh Q	b i:
do-	bies
dh @U	b i: z
do-	ble
dh @U	b V l
do-	bos
dh @U	b @U z
do-	by
dh @U	b i:
do-	cent
dh @U	s V n t
do-	cents
dh @U	s V n t s
do-	cher-	ty
dh Q	tS @r	t i:
do-	ci-	la
dh Q	s I	l V
do-	ci-	li-	ty
dh Q	s I	l I	t i:
do-	cile
dh Q	s V l
do-	cu-	dra-	ma
dh @U	k V d	r {	m V
do-	cu-	men-	ta-	ries
dh Q k	j V	m e n	t @r	i: z
do-	cu-	men-	ta-	ry
dh Q k	j V	m e n	t @r	i:
do-	cu-	men-	ta-	tion
dh Q k	j V	m e n	t eI	S V n
do-	cu-	men-	ted
dh Q k	j V	m e n	t V d
do-	cu-	men-	ting
dh Q k	j V	m V n	t I N
do-	cu-	ment
dh Q k	j V	m e n t
do-	cu-	ments
dh Q k	j V	m V n t s
do-	do
dh @U	d @U
do-	dos
dh @U	d @U z
do-	do's
dh @U	d @U z
do-	lan
dh @U	l V n
do-	land
dh u:	l V n d
do-	ley
dh @U	l i:
do-	lin
dh @U	l I n
do-	ling
dh @U	l I N
do-	lo-	mite
dh @U	l V	m aI t
do-	lo-	mites
dh @U	l V	m aI t s
do-	lo-	mite's
dh @U	l V	m aI t s
do-	lo-	res
dh V	l O@	V s
do-	lo-	ri-	ta
dh @U	l O@	i:	t V
do-	main
dh @U	m eI n
do-	maine
dh @U	m eI n
do-	mains
dh @U	m eI n z
do-	me-	nech
dh Q	m e	n I k
do-	me-	ni-	co
dh @U	m eI	n i:	k @U
do-	me-	nick
dh Q	m e	n I k
do-	mer
dh @U	m @r
do-	mes-	ti-	ca-	ted
dh V	m e s	t V	k eI	t V d
do-	mes-	ti-	ca-	ting
dh V	m e s	t V	k eI	t I N
do-	mes-	ti-	ca-	tion
dh V	m e s	t V	k eI	S V n
do-	mes-	ti-	cate
dh V	m e s	t V	k eI t
do-	mes-	ti-	ci-	ty
dh @U	m e s	t I	s I	t i:
do-	mes-	tic
dh V	m e s	t I k
do-	mes-	tical-	ly
dh V	m e s	t I k	l i:
do-	mes-	tics
dh V	m e s	t I k s
do-	mi-	cal
dh Q	m I	k V l
do-	mi-	na
dh @U	m i:	n V
do-	mi-	na-	ted
dh Q	m I	n eI	t I d
do-	mi-	na-	ting
dh Q	m I	n eI	t I N
do-	mi-	na-	tion
dh Q	m I	n eI	S V n
do-	mi-	nance
dh Q	m I	n V n s
do-	mi-	nant
dh Q	m I	n V n t
do-	mi-	nate
dh Q	m I	n eI t
do-	mi-	nates
dh Q	m I	n eI t s
do-	mi-	ne
dh @U	m i:	n i:
do-	mi-	nee
dh @U	m I	n eI
do-	mi-	nee-	ring
dh Q	m I	n I@	I N
do-	mi-	neer
dh Q	m I	n I@
do-	mi-	ni
dh Q	m I	n i:
do-	mi-	ni-	ca
dh V	m I	n I	k V
do-	mi-	ni-	can
dh V	m I	n V	k V n
do-	mi-	ni-	cans
dh @U	m I	n I	k V n z
do-	mi-	nic
dh Q	m I	n I k
do-	mi-	nick
dh Q	m V	n I k
do-	mi-	nic's
dh Q	m I	n I k s
do-	mi-	nik
dh V	m I	n I k
do-	mi-	nion
dh V	m I n	j V n
do-	mi-	nion's
dh V	m I n	j V n z
do-	mi-	nique
dh O:	m I	n i: k
do-	mi-	no
dh Q	m I	n @U
do-	mi-	noes
dh Q	m I	n @U z
do-	mi-	nos
dh Q	m I	n @U z
do-	mi-	no's
dh Q	m I	n @U z
do-	mi-	nus
dh @U	m i:	n V s
do-	mi-	ny
dh V	m aI	n i:
do-	min-	go
dh @U	m I N	g @U
do-	min-	guez
dh V	m I	N e z
do-	na
dh @U	n V
do-	na-	ghue
dh Q	n V	h u:
do-	na-	hoe
dh Q	n V	h @U
do-	na-	hue
dh Q	n V h	j u:
do-	na-	ta
dh V	n Q	t V
do-	na-	ted
dh @U	n eI	t V d
do-	na-	tel-	li
dh @U	n Q	t e	l i:
do-	na-	ti
dh @U	n Q	t i:
do-	na-	ting
dh @U	n eI	t I N
do-	na-	tion
dh @U	n eI	S V n
do-	na-	tions
dh @U	n eI	S V n z
do-	na-	tists
dh Q	n V	t V s t s
do-	na-	to
dh V	n Q	t @U
do-	nal-	da
dh @U	n Q l	d V
do-	nald
dh Q	n V l d
do-	nald-	son
dh Q	n V l	d s V n
do-	nald-	son's
dh Q	n V l	d s V n z
do-	nald's
dh Q	n V l d z
do-	nar
dh Q	n @r
do-	nat
dh @U	n V t
do-	nate
dh @U	n eI t
do-	nates
dh @U	n eI t s
do-	nath
dh Q	n V T
do-	ne-	gan
dh Q	n I	g { n
do-	nel-	la
dh @U	n e	l V
do-	nel-	son
dh Q	n V l	s V n
do-	ner
dh O:	n @r
do-	ney
dh Q	n i:
do-	ni-	a
dh @U	n i:	V
do-	ni-	ca
dh Q	n I	k V
do-	ni-	zet-	ti
dh Q	n I	z e	t i:
do-	ni-	zet-	ti's
dh Q	n I	z e	t i: z
do-	nis
dh @U	n I s
do-	no-	ghue
dh Q	n V h	j u:
do-	no-	ghue's
dh Q	n V h	j u: z
do-	no-	ho
dh Q	n V	h @U
do-	no-	hue
dh Q	n V h	j u:
do-	no-	hue's
dh Q	n V h	j u: z
do-	no-	van
dh Q	n V	v V n
do-	no-	van's
dh Q	n V	v V n z
do-	nor
dh @U	n @r
do-	nors
dh @U	n @r z
do-	nor's
dh @U	n @r z
do-	nut
dh @U	n V t
do-	nuts
dh @U	n V t s
do-	pa
dh @U	p V
do-	pa-	mine
dh Q	p V	m aI n
do-	pey
dh @U	p i:
do-	ra
dh O@	V
do-	ra-	do
dh O@	Q	d @U
do-	ra-	lin
dh O@	Q	l i: n
do-	ra-	lynne
dh O@	V	l aI n
do-	ra-	ville
dh O@	V	v I l
do-	ran
dh O@	{ n
do-	re-	li-	a
dh O@	e	l i:	V
do-	re-	na
dh O@	e	n V
do-	reen
dh O@	i: n
do-	rene
dh O@	i: n
do-	rette
dh @r	e t
do-	rey
dh O@	i:
do-	ri
dh O@	i:
do-	ri-	a
dh O@	i:	V
do-	ri-	an
dh O@	i:	V n
do-	ri-	ans
dh O@	i:	V n z
do-	ri-	ne
dh O@	i:	n i:
do-	ri-	on
dh O@	i:	O: n
do-	ri-	tos
dh O@	i:	t @U z
do-	ric
dh O@	I k
do-	rice
dh O@	I s
do-	rie
dh O@	i:
do-	rin
dh O@	I n
do-	rin-	da
dh O@	i: n	d V
do-	ris
dh O@	I s
do-	rise
dh O@	aI z
do-	ro
dh O@	@U
do-	ro-	te-	a
dh O@	V	t eI	V
do-	ro-	the-	a
dh O@	V	T i:	V
do-	ro-	thy
dh O@	V	T i:
do-	ro-	thy's
dh O@	V	T i: z
do-	ry
dh O@	i:
do-	sa-	ges
dh @U	s V	dZ V z
do-	sage
dh @U	s V dZ
do-	ser
dh @U	s @r
do-	ses
dh @U	s V z
do-	si-	a
dh @U	s i:	V
do-	si-	me-	ters
dh @U	s I	m V	t @r z
do-	sing
dh @U	s I N
do-	than
dh Q	T V n
do-	ting
dh @U	t I N
do-	to
dh @U	t @U
do-	ty
dh @U	t i:
do-	ur
dh aU	@r
do-	wel
dh aU	V l
do-	well
dh Q	w e l
do-	wels
dh aU	V l z
do-	wie
dh aU	i:
do-	xie
dh Q k	s i:
do-	xo-	lo-	gies
dh Q k	s Q	l V	dZ i: z
do-	xo-	lo-	gy
dh Q k	s Q	l V	dZ i:
do-	xy
dh Q k	s i:
do-	yen
dh OI	I n
do-	yon
dh OI	V n
do-	zen
dh V	z V n
do-	zens
dh V	z V n z
do-	zes
dh @U	z V z
do-	zi-	er
dh @U	z i:	@r
do-	zing
dh @U	z I N
doak
dh @U k
doan-	na
dh @U	n V
doane
dh @U n
dob
dh Q b
dob-	bie
dh Q	b i:
dob-	bin
dh Q	b I n
dob-	bins
dh Q	b I n z
dob-	ry-	nin
dh V b	r i:	n V n
dob-	son
dh Q b	s V n
dob-	sons
dh Q b	s V n z
dob-	son's
dh Q b	s V n z
dobb
dh Q b
dobbs
dh Q b z
doc
dh Q k
doc-	ken
dh Q	k V n
doc-	ker
dh Q	k @r
doc-	kers
dh Q	k @r z
doc-	ket
dh Q	k V t
doc-	kets
dh Q	k V t s
doc-	king
dh Q	k I N
doc-	to-	ral
dh Q k	t @r	V l
doc-	to-	rate
dh Q k	t @r	V t
doc-	to-	rates
dh Q k	t @r	V t s
doc-	to-	ring
dh Q k	t @r	I N
doc-	tor
dh Q k	t @r
doc-	tored
dh Q k	t @r d
doc-	tors
dh Q k	t @r z
doc-	tor's
dh Q k	t @r z
doc-	tors'
dh Q k	t @r z
doc-	tri-	naire
dh Q k	t r I	n e@
doc-	tri-	nal
dh Q k	t r I	n V l
doc-	trine
dh Q k	t r I n
doc-	trine's
dh Q k	t r I n z
dock
dh Q k
dock-	land
dh Q k	l V n d
dock-	lands
dh Q k	l V n d z
dock-	side
dh Q k	s aI d
dock-	wor-	ker
dh Q k	w @r	k @r
dock-	wor-	kers
dh Q k	w @r	k @r z
dock-	yard
dh Q k	j Q@ d
docked
dh Q k t
docks
dh Q k s
dock's
dh Q k s
doct-	rines
dh Q k	t r I n z
dod-	de-	ring
dh Q	d @r	I N
dod-	ger
dh Q	dZ @r
dod-	gers
dh Q	dZ @r z
dod-	ger's
dh Q	dZ @r z
dod-	ges
dh Q	dZ V z
dod-	ge's
dh Q	dZ V z
dod-	ging
dh Q	dZ I N
dod-	son
dh Q d	s V n
dodd
dh Q d
dodds
dh Q d z
dodd's
dh Q d z
dodge
dh Q dZ
dodged
dh Q dZ d
dods-	worth
dh Q d	s w @r T
doe
dh @U
doe-	rs
dh u:	@r z
doe-	sn't
dh V	z V n t
doer
dh u: r
does
dh V z
doe's
dh @U z
d'oeuvre
dh @r v
d'oeuvres
dh @r v z
dof-	fing
dh O:	f I N
doff
dh O: f
doffs
dh O: f s
dog
dh Q g
dog-	bane
dh O: g	b eI n
dog-	ber-	ry
dh O: g	b e@	i:
dog-	fight
dh Q g	f aI t
dog-	fights
dh O: g	f aI t s
dog-	fish
dh O: g	f I S
dog-	ge-	rel
dh Q	g @r	V l
dog-	ged-	ly
dh O:	g V d	l i:
dog-	gett
dh Q	g I t
dog-	gie
dh O:	g i:
dog-	gies
dh O:	g i: z
dog-	ging
dh O:	g I N
dog-	gone
dh O:	g O: n
dog-	gy
dh O:	g i:
dog-	gy's
dh O:	g i: z
dog-	house
dh O: g	h aU s
dog-	like
dh O: g	l aI k
dog-	ma
dh Q g	m V
dog-	ma-	ti-	sm
dh Q g	m V	t I	z V m
dog-	ma-	tic
dh Q g	m {	t I k
dog-	ma-	tical-	ly
dh Q g	m {	t I k	l i:
doge
dh @U dZ
dogged
dh O: g d
doke
dh @U k
dol
dh Q l
dol-	by
dh @U l	b i:
dol-	ce
dh @U l	tS eI
dol-	lar
dh Q	l @r
dol-	lars
dh Q	l @r z
dol-	lar's
dh Q	l @r z
dol-	ley
dh Q	l i:
dol-	li-	ver
dh Q	l I	v @r
dol-	lie
dh Q	l i:
dol-	lin-	ger
dh Q	l I	N @r
dol-	loff
dh Q	l O: f
dol-	lop
dh Q	l V p
dol-	ly
dh Q	l i:
dol-	ly's
dh Q	l i: z
dol-	man
dh Q l	m V n
dol-	phin
dh Q l	f I n
dol-	phins
dh Q l	f I n z
dol-	ton
dh @U l	t V n
dold-	rum
dh @U l	d r V m
dold-	rums
dh @U l	d r V m z
dole
dh @U l
dole-	ful
dh @U l	f V l
doled
dh @U l d
doles
dh @U l z
dole's
dh @U l z
dolf
dh @U l f
doll
dh Q l
doll-	hou-	ses
dh Q l	h aU	s V z
doll-	house
dh Q l	h aU s
dolled
dh Q l d
dolls
dh Q l z
doll's
dh Q l z
dolph
dh @U l f
dols
dh Q l z
dom
dh Q m
domb-	row-	ski
dh V m	b r O: f	s k i:
dome
dh @U m
domed
dh @U m d
domes
dh @U m z
dome's
dh @U m z
don
dh Q n
don-	key
dh Q N	k i:
don-	keys
dh Q N	k i: z
don-	na
dh Q	n V
don-	nas
dh Q	n V z
don-	na's
dh Q	n V z
don-	nel-	ly
dh Q	n V	l i:
don-	nel-	ly's
dh Q	n V	l i: z
don-	nell
dh Q	n V l
don-	ner
dh Q	n @r
don-	nie
dh Q	n i:
don-	ning
dh Q	n I N
don-	ny
dh Q	n i:
don-	ny-	brook
dh Q	n i: b	r U k
done
dh V n
dong
dh O: N
donn
dh Q n
donne
dh V n
donned
dh Q n d
dons
dh Q n z
don's
dh Q n z
don't
dh @U n t
don'ts
dh @U n t s
doo
dh u:
doo-	dad
dh u:	d { d
doo-	dads
dh u:	d { d z
doo-	dle
dh u:	d V l
doo-	dles
dh u:	d V l z
doo-	dy
dh u:	d i:
doo-	ley
dh u:	l i:
doo-	lit-	tle
dh u:	l I	t V l
doo-	ming
dh u:	m I N
doo-	zy
dh u:	z i:
doom
dh u: m
doom-	sa-	yer
dh u: m	s eI	@r
doom-	sa-	yers
dh u: m	s eI	@r z
doom-	sa-	ying
dh u: m	s eI	I N
doomed
dh u: m d
dooms
dh u: m z
dooms-	day
dh u: m	z d eI
doones-	bu-	ry
dh u: n	z b e@	i:
door
dh O@
door-	bell
dh O@	b e l
door-	kee-	per
dh O@	k i:	p @r
door-	knob
dh u: r	n Q b
door-	knobs
dh u: r	n Q b z
door-	man
dh O@	m { n
door-	mat
dh O@	m { t
door-	mats
dh O@	m { t s
door-	nail
dh O@	n eI l
door-	sill
dh O@	s I l
door-	step
dh O@ s	t e p
door-	steps
dh O@ s	t e p s
door-	way
dh O@	w eI
door-	ways
dh O@	w eI z
doorn
dh O@ n
doors
dh O@ z
door's
dh O@ z
dope
dh @U p
doped
dh @U p t
dopp
dh Q p
dopp-	ler
dh Q p	l @r
d'or
dh O@
dor-	cas
dh O@	k V s
dor-	ches-	ter
dh O@	tS e s	t @r
dor-	man
dh O@	m V n
dor-	man-	cy
dh O@	m V n	s i:
)"
R"(dor-	mant
dh O@	m V n t
dor-	mer
dh O@	m @r
dor-	mi-	to-	ries
dh O@	m I	t O@	i: z
dor-	mi-	to-	ry
dh O@	m I	t O@	i:
dor-	mouse
dh O@	m aU s
dor-	nier
dh O@	n I@
dor-	rance
dh O@	V n s
dor-	rie
dh O@	i:
dor-	ris
dh O@	I s
dor-	sa
dh O@	s V
dor-	sal
dh O@	s V l
dor-	sal-	ly
dh O@	s V	l i:
d'or-	say
dh O@	s eI
dor-	set
dh O@	s e t
dor-	sey
dh O@	s i:
dor-	si
dh O@	s i:
dor-	the-	a
dh O@	D i:	V
dor-	thy
dh O@	T i:
dor-	ton
dh O@	t V n
dore
dh O@
dorf-	man
dh O@ f	m V n
dorm
dh O@ m
dorms
dh O@ m z
dorn
dh O@ n
dorr
dh O@
dort
dh O@ t
dort-	mund
dh O@ t	m V n d
dos
dh O: s
do's
dh u: z
dos-	cher
dh O:	S @r
dos-	sier
dh O: s	j eI
dos-	siers
dh O: s	j eI z
dos-	toev-	ski
dh O: s	t @U v	s k i:
dos-	toev-	sky
dh O: s	t @U v	s k i:
dos-	well
dh Q s	w e l
dose
dh @U s
dosh
dh Q S
doss
dh O: s
dost
dh Q s t
dot
dh Q t
dot-	son
dh Q t	s V n
dot-	ted
dh Q	t V d
dot-	ter
dh Q	t @r
dot-	tie
dh Q	t i:
dot-	ting
dh Q	t I N
dot-	ty
dh Q	t i:
dote
dh @U t
doth
dh O: T
dots
dh Q t s
dott
dh Q t
dou-	b-	ling
dh V	b V	l I N
dou-	ble
dh V	b V l
dou-	ble-	day
dh V	b V l	d eI
dou-	ble-	speak
dh V	b V l	s p i: k
dou-	ble-	think
dh V	b V l	T I N k
dou-	ble-	tree
dh V	b V l	t r i:
dou-	bled
dh V	b V l d
dou-	bles
dh V	b V l z
dou-	cet
dh u:	s e t
dou-	cette
dh u:	s e t
dou-	gal
dh u:	g V l
dou-	gall
dh aU	g V l
dou-	ghy
dh @U	i:
dou-	gie
dh u:	g i:
dou-	gie's
dh u:	g i: z
dou-	gl
dh u:	g V l
dou-	ma
dh @U	m V
doub
dh aU b
doub-	ly
dh V b	l i:
doub-	ted
dh aU	t V d
doub-	ter
dh aU	t @r
doub-	ters
dh aU	t @r z
doub-	ting
dh aU	t I N
doubt
dh aU t
doubt-	ful
dh aU t	f V l
doubt-	less
dh aU t	l V s
doubts
dh aU t s
douds
dh aU d z
doug
dh V g
doug-	her-	ty
dh @U	@r	t i:
doug-	la-	ss
dh V g	l V	s V z
doug-	la-	s's
dh V g	l V	s V z
doug-	las
dh V g	l V s
dough
dh @U
dough-	boy
dh @U	b OI
dough-	man
dh @U	m V n
dough-	nut
dh @U	n V t
dough-	nuts
dh @U	n V t s
dough-	ty
dh O:	t i:
doug's
dh V g z
doul-	ton
dh @U l	t V n
dow-	ding
dh aU	d I N
dow-	dy
dh aU	d i:
dow-	land
dh aU	l V n d
dow-	len
dh aU	l V n
dow-	less
dh aU	l V s
dow-	ling
dh aU	l I N
dow-	ner
dh aU	n @r
dow-	ners
dh aU	n @r z
dow-	ney
dh aU	n i:
dow-	ney's
dh aU	n i: z
dow-	nie
dh aU	n i:
dow-	ning
dh aU	n I N
dow-	ning-	town
dh aU	n I N	t aU n
dow-	ny
dh aU	n i:
dow-	ry
dh aU	r i:
dow-	sing
dh aU	s I N
dowds
dh aU d z
dower
dh aU r
dowers
dh aU r z
down
dh aU n
down-	beat
dh aU n	b i: t
down-	cast
dh aU n	k { s t
down-	draft
dh aU n	d r { f t
down-	fall
dh aU n	f O: l
down-	gra-	ded
dh aU n	g r eI	d V d
down-	gra-	ding
dh aU n	g r eI	d I N
down-	grade
dh aU n	g r eI d
down-	grades
dh aU n	g r eI d z
down-	hill
dh aU n	h I l
down-	loa-	ded
dh aU n	l @U	d V d
down-	loa-	ding
dh aU n	l @U	d I N
down-	load
dh aU n	l @U d
down-	pay-	ment
dh aU n	p eI	m V n t
down-	play
dh aU n	p l eI
down-	play-	ing
dh aU n	p l eI	I N
down-	played
dh aU n	p l eI d
down-	plays
dh aU n	p l eI z
down-	pour
dh aU n	p O@
down-	pours
dh aU n	p O@ z
down-	range
dh aU n	r eI n dZ
down-	ri-	ver
dh aU n	r I	v @r
down-	right
dh aU n	r aI t
down-	scale
dh aU n	s k eI l
down-	si-	zing
dh aU n	s aI	z I N
down-	side
dh aU n	s aI d
down-	sides
dh aU n	s aI d z
down-	size
dh aU n	s aI z
down-	sized
dh aU n	s aI z d
down-	stage
dh aU n	s t eI dZ
down-	stairs
dh aU n	s t e@ z
down-	state
dh aU n	s t eI t
down-	stream
dh aU n	s t r i: m
down-	swing
dh aU n	s w I N
down-	time
dh aU n	t aI m
down-	town
dh aU n	t aU n
down-	towns
dh aU n	t aU n z
down-	trend
dh aU n	t r e n d
down-	trod-	den
dh aU n	t r Q	d V n
down-	turn
dh aU n	t @r n
down-	turns
dh aU n	t @r n z
down-	ward
dh aU n	w @r d
down-	ward-	ly
dh aU n	w @r d	l i:
down-	wards
dh aU n	w @r d z
down-	wind
dh aU n	w I n d
downe
dh aU n
downed
dh aU n d
downes
dh aU n z
downs
dh aU n z
down's
dh aU n z
dow's
dh aU z
dowse
dh aU s
doyle
dh OI l
doyle's
dh OI l z
doze
dh @U z
dozed
dh @U z d
dr
dh r aI v
dr.
dh r aI v
dra-	co
dh r eI	k @U
dra-	co-	ni-	an
dh r eI	k @U	n i:	V n
dra-	cu-	la
dh r { k	j u:	l V
dra-	go
dh r Q	g @U
dra-	gon
dh r {	g V n
dra-	gon-	head
dh r {	g V n	h e d
dra-	gone
dh r V	g @U n
dra-	gons
dh r {	g V n z
dra-	gon's
dh r {	g V n z
dra-	ma
dh r Q	m V
dra-	ma-	mine
dh r {	m V	m i: n
dra-	ma-	ti-	za-	tion
dh r {	m V	t V	z eI	S V n
dra-	ma-	ti-	za-	tions
dh r {	m V	t V	z eI	S V n z
dra-	ma-	ti-	zes
dh r {	m V	t aI	z V z
dra-	ma-	ti-	zing
dh r {	m V	t aI	z I N
dra-	ma-	tic
dh r V	m {	t I k
dra-	ma-	tical-	ly
dh r V	m {	t I k	l i:
dra-	ma-	tist
dh r Q	m V	t I s t
dra-	ma-	tize
dh r Q	m V	t aI z
dra-	ma-	tized
dh r {	m V	t aI z d
dra-	mas
dh r Q	m V z
dra-	pe-	ries
dh r eI	p @r	i: z
dra-	pe-	ry
dh r eI	p @r	i:
dra-	per
dh r eI	p @r
dra-	ping
dh r eI	p I N
dra-	wing
dh r O:	I N
dra-	wings
dh r O:	I N z
drab
dh r { b
drab-	ble
dh r {	b V l
drabbed
dh r { b d
drabs
dh r { b z
drach-	ma
dh r { k	m V
drach-	mas
dh r Q k	m V z
draf-	ted
dh r { f	t V d
draf-	tee
dh r { f	t i:
draf-	tees
dh r { f	t i: z
draf-	ter
dh r { f	t @r
draf-	ters
dh r { f	t @r z
draf-	ting
dh r { f	t I N
draf-	ty
dh r { f	t i:
draft
dh r { f t
drafts
dh r { f t s
draft's
dh r { f t s
drafts-	man
dh r { f	t s m V n
drafts-	man-	ship
dh r { f	t s m V n	S I p
drafts-	men
dh r { f	t s m V n
drag
dh r { g
drag-	ging
dh r {	g I N
drag-	gy
dh r {	g i:
drag-	line
dh r { g	l aI n
drag-	net
dh r { g	n e t
drag-	nets
dh r { g	n e t s
dragged
dh r { g d
drags
dh r { g z
drai-	nage
dh r eI	n V dZ
drai-	ner
dh r eI	n @r
drai-	ners
dh r eI	n @r z
drai-	ning
dh r eI	n I N
drain
dh r eI n
draine
dh r eI n
drained
dh r eI n d
drains
dh r eI n z
drake
dh r eI k
drakes
dh r eI k s
dram
dh r { m
drams
dh r { m z
drang
dh r { N
drank
dh r { N k
drape
dh r eI p
draped
dh r eI p t
drapes
dh r eI p s
dras-	tic
dh r { s	t I k
dras-	tical-	ly
dh r { s	t I k	l i:
draught
dh r { f t
draughts
dh r { f t s
draw
dh r O:
draw-	back
dh r O:	b { k
draw-	backs
dh r O:	b { k s
draw-	bridge
dh r O: b	r I dZ
draw-	down
dh r O:	d aU n
draw-	downs
dh r O:	d aU n z
drawer
dh r O@
drawers
dh r O@ z
drawl
dh r O: l
drawled
dh r O: l d
drawls
dh r O: l z
drawn
dh r O: n
draws
dh r O: z
dray
dh r eI
dray-	ton
dh r eI	t V n
dray-	ton's
dh r eI	t V n z
dre-	scher
dh r e	S @r
dre-	wett
dh r u:	V t
dre-	xel
dh r e k	s V l
dre-	xel's
dh r e k	s V l z
dre-	yer
dh r eI	@r
drea-	ded
dh r e	d V d
drea-	ding
dh r e	d I N
drea-	mer
dh r i:	m @r
drea-	mers
dh r i:	m @r z
drea-	ming
dh r i:	m I N
drea-	my
dh r i:	m i:
drea-	ri-	ness
dh r i:	r i:	n V s
drea-	ry
dh r I@	i:
dread
dh r e d
dread-	ful
dh r e d	f V l
dread-	ful-	ly
dh r e d	f V	l i:
dread-	nought
dh r e d	n O: t
dreads
dh r e d z
dream
dh r i: m
dream-	land
dh r i: m	l { n d
dream-	like
dh r i: m	l aI k
dream-	world
dh r i: m	w @r l d
dreamed
dh r i: m d
dreams
dh r i: m z
dreamt
dh r e m t
dred
dh r e d
dred-	ges
dh r e	dZ V z
dred-	ging
dh r e	dZ I N
dredge
dh r e dZ
dredged
dh r e dZ d
drees
dh r i: z
dregs
dh r e g z
dreher
dh r e@
drei-	ling
dh r aI	l I N
dren-	ching
dh r e n	tS I N
dren-	nen
dh r e	n V n
drench
dh r e n tS
drenched
dh r e n tS t
dres-	den
dh r e z	d V n
dres-	sage
dh r e	s Q Z
dres-	sel
dh r e	s V l
dres-	sen
dh r e	s V n
dres-	ser
dh r e	s @r
dres-	sers
dh r e	s @r z
dres-	ser's
dh r e	s @r z
dres-	ses
dh r e	s V z
dres-	si-	er
dh r e	s i:	@r
dres-	sing
dh r e	s I N
dres-	sings
dh r e	s I N z
dres-	sy
dh r e	s i:
dress
dh r e s
dress-	ler
dh r e s	l @r
dress-	ma-	ker
dh r e s	m eI	k @r
dress-	ma-	kers
dh r e s	m eI	k @r z
dress-	ma-	king
dh r e s	m eI	k I N
dressed
dh r e s t
drew
dh r u:
drews
dh r u: z
drex-	ler
dh r e k	s l @r
drey
dh r eI
drey-	fu-	s's
dh r eI	f V	s V z
drey-	fus
dh r aI	f V s
drey-	fuss
dh r eI	f V s
dri-	er
dh r aI	@r
dri-	est
dh r aI	V s t
dri-	na
dh i:	n V
dri-	na's
dh i:	n V z
dri-	va-	ble
dh r aI	v V	b V l
dri-	vel
dh r I	v V l
dri-	ven
dh r I	v V n
dri-	ver
dh r aI	v @r
dri-	ver-	less
dh r aI	v @r	l V s
dri-	vers
dh r aI	v @r z
dri-	ver's
dh r aI	v @r z
dri-	ving
dh r aI	v I N
drib-	b-	ling
dh r I	b V	l I N
drib-	ble
dh r I	b V l
drib-	bled
dh r I	b V l d
dribbed
dh r I b d
dribs
dh r I b z
dried
dh r aI d
dries
dh r aI z
drif-	ted
dh r I f	t V d
drif-	ter
dh r I f	t @r
drif-	ters
dh r I f	t @r z
drif-	ting
dh r I f	t I N
drift
dh r I f t
drift-	net
dh r I f	t n e t
drift-	wood
dh r I f	t w U d
drifts
dh r I f t s
driggs
dh r I g z
dril-	ler
dh r I	l @r
dril-	lers
dh r I	l @r z
dril-	ling
dh r I	l I N
dril-	ling's
dh r I	l I N z
drill
dh r I l
drill-	bit
dh r I l	b I t
drilled
dh r I l d
drills
dh r I l z
drin-	ka-	ble
dh r I n	k V	b V l
drin-	ker
dh r I N	k @r
drin-	kers
dh r I N	k @r z
drin-	ker's
dh r I N	k @r z
drin-	king
dh r I N	k I N
drink
dh r I N k
drink-	wa-	ter
dh r I N	k w O:	t @r
drinks
dh r I N k s
drip
dh r I p
drip-	ping
dh r I	p I N
dripped
dh r I p t
dripps
dh r I p s
drips
dh r I p s
dris-	coll
dh r I s	k V l
dris-	kill
dh r I s	k I l
drive
dh r aI v
drive-	way
dh r aI v	w eI
drive-	ways
dh r aI v	w eI z
drives
dh r aI v z
driz-	z-	ling
dh r I	z V	l I N
driz-	zle
dh r I	z V l
drizz-	ly
dh r I z	l i:
dro-	let
dh r @U	l e t
dro-	me-	da-	ry
dh r Q	m V	d e@	i:
dro-	mo-	ma-	ni-	a
dh r @U	m @U	m eI	n i:	V
dro-	mon
dh r @U	m V n
dro-	net
dh r @U	n e t
dro-	ning
dh r @U	n I N
dro-	ver
dh r @U	v @r
drogue
dh r @U g
droll
dh r @U l
drone
dh r @U n
droned
dh r @U n d
drones
dh r @U n z
droo-	ling
dh r u:	l I N
droo-	ping
dh r u:	p I N
droo-	py
dh r u:	p i:
drool
dh r u: l
droop
dh r u: p
drooped
dh r u: p t
drop
dh r Q p
drop-	let
dh r Q p	l V t
drop-	lets
dh r Q p	l V t s
drop-	off
dh r Q	p O: f
drop-	out
dh r Q	p aU t
drop-	outs
dh r Q	p aU t s
drop-	per
dh r Q	p @r
drop-	pers
dh r Q	p @r z
drop-	ping
dh r Q	p I N
drop-	pings
dh r Q	p I N z
drop-	sy
dh r Q p	s i:
dropped
dh r Q p t
drops
dh r Q p s
dross
dh r O: s
drought
dh r aU t
droughts
dh r aU t s
drought's
dh r aU t s
drove
dh r @U v
droves
dh r @U v z
drow-	ning
dh r aU	n I N
drow-	nings
dh r aU	n I N z
drow-	si-	ness
dh r aU	z i:	n V s
drow-	sy
dh r aU	z i:
drown
dh r aU n
drowned
dh r aU n d
drowns
dh r aU n z
dru
dh r u:
dru-	cie
dh r V	k i:
dru-	el-	la
dh r u:	e	l V
dru-	i-	di-	sm
dh r u:	I	d I	z V m
dru-	id
dh r u:	I d
dru-	ids
dh r u:	I d z
drub
dh r V b
drub-	bing
dh r V	b I N
drubbed
dh r V b d
druce
dh r u: s
drud-	ge-	ry
dh r V	dZ @r	i:
drudge
dh r V dZ
drug
dh r V g
drug-	ging
dh r V	g I N
drug-	gist
dh r V	g I s t
drug-	gists
dh r V	g I s t s
drug-	gist's
dh r V	g I s t s
drug-	ma-	ker
dh r V g	m eI	k @r
drug-	ma-	kers
dh r V g	m eI	k @r z
drugged
dh r V g d
drugs
dh r V g z
drug's
dh r V g z
drugs-	tore
dh r V g	s t O@
drugs-	tores
dh r V g	s t O@ z
drum
dh r V m
drum-	beat
dh r V m	b i: t
drum-	head
dh r V m	h e d
drum-	lin's
dh r V m	l I n z
drum-	mer
dh r V	m @r
drum-	mers
dh r V	m @r z
drum-	ming
dh r V	m I N
drum-	mond
dh r V	m V n d
drum-	monds
dh r V	m V n d z
drummed
dh r V m d
dry-	clean
dh r aI k	l i: n
dry-	den
dh r aI	d V n
dry-	er
dh r aI	@r
dry-	ers
dh r aI	@r z
dry-	ing
dh r aI	I N
dry-	ly
dh r aI	l i:
dry-	ness
dh r aI	n V s
dry-	point
dh r aI	p OI n t
dry-	wall
dh r aI	w Q l
drye
dh r aI
drys-	dale
dh r aI z	d eI l
d's
dh i: z
du
dh u:
du-	a-	li-	sm
dh u:	V	l I	z V m
du-	a-	li-	sms
dh u:	V	l I	z V m z
du-	a-	li-	ty
dh u:	{	l I	t i:
du-	a-	lis-	tic
dh u:	V	l I s	t I k
du-	a-	list
dh u:	V	l I s t
du-	al
dh u:	V l
du-	als
dh u:	V l z
du-	bach
dh V	b Q k
du-	bai
dh u:	b aI
du-	bi-	ous
dh u:	b i:	V s
du-	bin-	sky
dh V	b I n	s k i:
du-	bois
dh u:	b OI s
du-	bose
dh u:	b @U z
du-	buque
dh V b	j u: k
du-	buque's
dh V b	j u: k s
du-	by
dh u:	b i:
du-	cal
dh u:	k V l
du-	champ
dh u:	S Q m p
du-	champ's
dh u:	S Q m p s
du-	chenne
dh u:	S e n
du-	chess
dh V	tS V s
du-	chy
dh V	tS i:
du-	com-	mun
dh u:	k Q	m V n
du-	e-	list
dh u:	V	l I s t
du-	e-	na
dh u:	e	n V
du-	e-	nas
dh u:	e	n V s
du-	el
dh u:	V l
du-	eled
dh u:	V l d
du-	els
dh u:	V l z
du-	er
dh u:	@r
du-	et
dh u:	e t
du-	ets
dh u:	e t s
du-	fur
dh V	f @r
du-	gal
dh u:	dZ V l
du-	gald
dh V	g V l d
du-	gan
dh V	g V n
du-	gas
dh u:	g V z
du-	gout
dh V	g aU t
du-	gouts
dh V	g aU t s
du-	ha-	mel
dh u:	h {	m V l
du-	ka-	ki-	s's
dh u:	k Q	k I	s V z
du-	ka-	kis
dh u:	k Q	k I s
du-	king
dh u:	k I N
du-	la-	ney
dh j u:	l V	n i:
du-	lac
dh V	l { k
du-	luth
dh V	l u: T
du-	ly
dh u:	l i:
du-	ma
dh u:	m V
du-	mas
dh u:	m V z
du-	mond
dh V	m Q n d
du-	mont
dh u:	m Q n t
du-	na
dh u:	n V
du-	na-	way
dh V	n V	w eI
du-	naj
dh u:	n V dZ
du-	ne-	din
dh u:	n V	d I n
du-	nite
dh u:	n aI t
du-	o
dh u:	@U
du-	o-	de-	nal
dh u:	Q	d V	n V l
du-	o-	de-	num
dh u:	Q	d V	n V m
du-	o-	po-	ly
dh u:	@U	p Q	l i:
du-	ong
dh u:	@U N
du-	per
dh u:	p @r
du-	pin
dh V	p { n
du-	pont
dh u:	p Q n t
du-	pont's
dh u:	p Q n t s
du-	pu-	is
dh V	p u:	I z
du-	puy
dh V	p aI
du-	quesne
dh u:	k eI n
du-	quette
dh V	k e t
du-	ra
dh U@	V
du-	ra-	bi-	li-	ty
dh @r	V	b I	l V	t i:
du-	ra-	ble
dh U@	V	b V l
du-	ra-	bles
dh U@	V	b V l z
du-	ra-	cell
dh U@	V	s e l
du-	ra-	tion
dh U@	eI	S V n
du-	ra-	tions
dh U@	eI	S V n z
du-	ran
dh @r	{ n
du-	ran-	go
dh @r	{ N	g @U
du-	ran-	te
dh U@	Q n	t i:
du-	ran's
dh @r	{ n s
du-	rant
dh U@	V n t
du-	rant's
dh @r	{ n t s
du-	ree
dh U@	i:
du-	rene
dh j u:	r i: n
du-	rer
dh U@	@r
du-	ress
dh U@	e s
du-	ri-	o
dh U@	i:	@U
du-	ri-	ron
dh u:	r I@	V n
du-	ring
dh U@	I N
du-	ro
dh U@	@U
du-	ro-	cher
dh j u:	r V	k @r
du-	rum
dh U@	V m
du-	rye-	a
dh U@	i:	V
du-	sen-	bu-	ry
dh u:	s V n	b e@	i:
du-	thie
dh V	T i:
du-	ti-	ful
dh u:	t i:	f V l
du-	ti-	ful-	ly
dh u:	t i:	f V	l i:
du-	ties
dh u:	t i: z
du-	toit
dh u:	t OI t
du-	ty
dh u:	t i:
du-	va-	lier
dh u:	v { l	j @r
du-	val
dh u:	v { l
du-	vall
dh u:	v Q l
duan
dh w { n
duane
dh w eI n
duar-	te
dh w Q@	t eI
duar-	te's
dh w Q@	t eI z
dub
dh V b
dub-	ber-	ly
dh V	b @r	l i:
dub-	bing
dh V	b I N
dub-	cek
dh V b	tS e k
dub-	lin
dh V b	l I n
dub-	lin's
dh V b	l I n z
dub-	rov-	nik
dh u: b	r Q v	n I k
dub-	rov-	nik's
dh u: b	r Q v	n I k z
dubbed
dh V b d
dubs
dh V b z
duc
dh V k
duc-	ker
dh V	k @r
duc-	king
dh V	k I N
duc-	los
dh V k	l @U z
duc-	ti-	li-	ty
dh V k	t I	l I	t i:
duc-	tile
dh V k	t I l
duce
dh u: s
duck
dh V k
duck-	ling
dh V k	l I N
duck-	lings
dh V k	l I N z
duck-	weed
dh V k	w i: d
ducked
dh V k t
ducks
dh V k s
duck's
dh V k s
duct
dh V k t
duct-	less
dh V k	t l V s
ducts
dh V k t s
dud
dh V d
dud-	dy
dh V	d i:
dud-	geon
dh V	dZ V n
dud-	ley
dh V d	l i:
dud-	man
dh V d	m V n
dude
dh u: d
dudes
dh j u: d z
duds
dh V d z
due
dh u:
due-	ling
dh u:	l I N
dues
dh u: z
duf-	fel
dh V	f V l
duf-	fer
dh V	f @r
duf-	fie
dh V	f i:
duf-	field
dh V	f i: l d
duf-	fy
dh V	f i:
duff
dh V f
dug
dh V g
dug-	gan
dh V	g V n
dug-	ger
dh V	g @r
duh
dh V
duhr
dh @r
duis-	burg
dh u: s	b @r g
duke
dh u: k
duke-	dom
dh u: k	d V m
dukes
dh u: k s
duke's
dh u: k s
dul-	ce-	a
dh V l	s i:	V
dul-	cet
dh V l	s V t
dul-	ci-	belle
dh V l	s I	b V l
dul-	ci-	mer
dh V l	s I	m @r
dul-	ci-	ne-	a
dh V l	s I	n i:	V
dul-	cia-	na
dh u: l	tS {	n V
dul-	cie
dh V l	k i:
dul-	cine
dh V l	s I n
dul-	ler
dh V	l @r
dul-	les
dh V	l V s
dul-	lest
dh V	l V s t
dul-	ling
dh V	l I N
dul-	wich
dh V l	w I tS
dulce
dh V l s
dule
dh u: l
dull
dh V l
dull-	ness
dh V l	n V s
dulled
dh V l d
dum
dh V m
dum-	ber
dh V	m @r
dum-	best
dh V	m V s t
dum-	bing
dh V	m I N
dum-	bo
dh V m	b @U
dum-	mies
dh V	m i: z
dum-	my
dh V	m i:
dum-	per
dh V m	p @r
dum-	ping
dh V m	p I N
dum-	py
dh V m	p i:
dumb
dh V m
dumb-	bell
dh V m	b e l
dumb-	bells
dh V m	b e l z
dumb-	foun-	ded
dh V m	f aU n	d V d
dumb-	found
dh V m	f aU n d
dumb-	struck
dh V m	s t r V k
dumm
dh V m
dump
dh V m p
dump-	ling
dh V m	p l I N
dump-	lings
dh V m	p l I N z
dump-	ster
dh V m	p s t @r
dump-	sters
dh V m	p s t @r z
dump-	truck
dh V m	p t r V k
dump-	ty
dh V m	p t i:
dumped
dh V m p t
dumps
dh V m p s
dun
dh V n
dun-	bar
dh V n	b Q@
dun-	can
dh V N	k V n
dun-	combe
dh V N	k V m
dun-	das
dh V n	d V z
dun-	dee
dh V n	d i:
dun-	gan
dh V N	g V n
dun-	geon
dh V n	dZ V n
dun-	geons
dh V n	dZ V n z
dun-	ham
dh V	n V m
dun-	kel
dh V N	k V l
dun-	ker
dh V N	k @r
dun-	kin
dh V N	k I n
dun-	kirk
dh V n	k @r k
dun-	kle
dh V N	k V l
dun-	la-	vy
dh V n	l V	v i:
dun-	lap
dh V n	l { p
dun-	le-	vy
dh u: n	l I	v i:
dun-	lop
dh V n	l Q p
dun-	nell
dh V	n V l
dun-	ni-	gan
dh V	n I	g V n
dun-	ning
dh V	n I N
dun-	son
dh V n	s V n
dun-	ton
dh V n	t V n
)"
R"(dun-	woo-	dy
dh V n	w U	d i:
dunc
dh V N k
dune
dh u: n
dunes
dh u: n z
dung
dh V N
dunk
dh V N k
dunked
dh V N k t
dunks
dh V N k s
dunn
dh V n
dunne
dh V n
dunned
dh V n d
duns
dh V n z
dun's
dh V n z
duns-	tan
dh V n	s t V n
duns-	ter
dh V n	s t @r
duns-	ton
dh V n	s t V n
dunst
dh V n s t
dup-	les-	sis
dh u: p	l e	s I s
dup-	lex
dh u: p	l e k s
dup-	li-	ca-	ted
dh u: p	l I	k eI	t I d
dup-	li-	ca-	ting
dh u: p	l I	k eI	t I N
dup-	li-	ca-	tion
dh j u: p	l I	k eI	S V n
dup-	li-	ca-	tions
dh u: p	l I	k eI	S V n z
dup-	li-	ca-	tive
dh u: p	l I	k V	t I v
dup-	li-	cate
dh u: p	l I	k V t
dup-	li-	cates
dh j u: p	l I	k eI t s
dup-	li-	ci-	tous
dh u: p	l I	s I	t V s
dup-	li-	ci-	ty
dh u: p	l I	s I	t i:
dup-	re
dh V	p @r
dup-	ree
dh V p	r i:
dupe
dh u: p
duped
dh u: p t
dupes
dh u: p s
duque
dh u: k
dur-	ban
dh @r	b V n
dur-	bin
dh @r	b I n
dur-	gan
dh @r	g V n
dur-	ham
dh @r	V m
dur-	kee
dh @r	k i:
dur-	kin
dh @r	k I n
dur-	ning
dh @r	n I N
dur-	rell
dh O@	V l
dur-	rett
dh O@	V t
dur-	ward
dh @r	w @r d
dur-	win
dh @r	w I n
durk-	heim
dh @r k	h aI m
)"