R"(me-	di-	an
m i:	d i:	V n
me-	di-	a's
m i:	d i:	V z
me-	di-	ate
m i:	d i:	eI t
me-	di-	ca-	ted
m e	d I	k eI	t V d
me-	di-	ca-	tion
m e	d I	k eI	S V n
me-	di-	ca-	tions
m e	d I	k eI	S V n z
me-	di-	caid
m e	d I	k eI d
me-	di-	cal
m e	d I	k V l
me-	di-	care
m e	d I	k e@
me-	di-	care's
m e	d I	k e@ z
me-	di-	cate
m e	d I	k eI t
me-	di-	ci
m e	d i:	s i:
me-	di-	ci-	nal
m V	d I	s V	n V l
me-	di-	ci-	nal-	ly
m V	d I	s V	n V	l i:
me-	di-	cine
m e	d I	s I n
me-	di-	cines
m e	d I	s I n z
me-	di-	cine's
m e	d I	s I n z
me-	di-	co
m e	d I	k @U
me-	di-	gap
m e	d I	g { p
me-	di-	na
m V	d aI	n V
me-	di-	o
m i:	d i:	@U
me-	di-	o-	cre
m i:	d i:	@U	k @r
me-	di-	oc-	ri-	ty
m i:	d i:	Q k	r I	t i:
me-	di-	ta-	ting
m e	d I	t eI	t I N
me-	di-	ta-	tion
m e	d I	t eI	S V n
me-	di-	ta-	tions
m e	d I	t eI	S V n z
me-	di-	ta-	tive
m e	d I	t eI	t I v
me-	di-	tate
m e	d I	t eI t
me-	di-	ter-	ra-	ne-	an
m e	d I	t @r	eI	n i:	V n
me-	di-	um
m i:	d i:	V m
me-	di-	ums
m i:	d i:	V m z
me-	dic
m e	d I k
me-	dical-	ly
m e	d I k	l i:
me-	dics
m e	d I k s
me-	dic's
m e	d I k s
me-	die-	val
m V	d i:	v V l
me-	din
m eI	d i: n
me-	do-	ra
m eI	d O@	V
me-	du-	sa
m V	d u:	s V
me-	du-	sas
m V	d u:	s V z
me-	dul-	la
m V	d V	l V
me-	er
m i:	@r
me-	ers
m i:	@r z
me-	ga
m e	g V
me-	ga-	bit
m e	g V	b I t
me-	ga-	buck
m e	g V	b V k
me-	ga-	bucks
m e	g V	b V k s
me-	ga-	byte
m e	g V	b aI t
me-	ga-	bytes
m e	g V	b aI t s
me-	ga-	deal
m e	g V	d i: l
me-	ga-	deals
m e	g V	d i: l z
me-	ga-	death
m e	g V	d e T
me-	ga-	hertz
m e	g V	h @r t s
me-	ga-	lo-	ma-	ni-	a
m e	g V	l @U	m eI	n i:	V
me-	ga-	lo-	ma-	ni-	ac
m e	g V	l @U	m eI	n i:	{ k
me-	ga-	lo-	po-	lis
m e	g V	l Q	p V	l V s
me-	ga-	phone
m e	g V	f @U n
me-	ga-	phones
m e	g V	f @U n z
me-	ga-	plex
m e	g V p	l e k s
me-	ga-	store
m e	g V s	t O@
me-	ga-	stores
m e	g V s	t O@ z
me-	ga-	tons
m e	g V	t V n z
me-	ga-	watt
m e	g V	w Q t
me-	ga-	watts
m e	g V	w Q t s
me-	gan
m eI	g V n
me-	gan's
m eI	g V n z
me-	ghan
m e	g V n
me-	he-	ta-	bel
m V	h e	t V	b V l
me-	hi-	ta-	bel
m e	h I	t V	b V l
me-	hul
m e	h U l
me-	kong
m eI	k Q N
me-	la-	med
m e	l V	m e d
me-	la-	mine
m e	l V	m i: n
me-	la-	ne-	sian
m e	l V	n i:	Z V n
me-	la-	ne-	sians
m e	l V	n i:	Z V n z
me-	la-	nie
m e	l V	n i:
me-	la-	nin
m e	l V	n I n
me-	la-	no-	ma
m e	l V	n @U	m V
me-	la-	ny
m e	l V	n i:
me-	la-	to-	nin
m e	l V	t @U	n V n
me-	la-	to-	nin's
m e	l V	t @U	n V n z
me-	lan-	cho-	lic
m e	l V n	k Q	l I k
me-	lan-	cho-	ly
m e	l V n	k Q	l i:
me-	lan-	tha
m V	l { n	D V
me-	lange
m e	l { N
me-	lee
m eI	l eI
me-	len-	dez
m V	l e n	d e z
me-	les-	sa
m e	l e	s V
me-	li
m e	l i:
me-	li-	a
m e	l i:	V
me-	li-	cent
m e	l I	s e n t
me-	li-	na
m e	l i:	n V
me-	li-	sent
m e	l I	s e n t
me-	li-	ta
m e	l i:	t V
me-	lin-	da
m V	l I n	d V
me-	line
m e	l aI n
me-	lis-	sa
m V	l I	s V
me-	lis-	sa's
m V	l I	s V z
me-	lisse
m e	l I s
me-	lit-	ta
m e	l i:	t V
me-	llo-	wing
m e	l @U	I N
me-	lo
m e	l @U
me-	lo-	di-	ous
m V	l @U	d i:	V s
me-	lo-	dic
m V	l Q	d I k
me-	lo-	dies
m e	l V	d i: z
me-	lo-	dra-	ma
m e	l V d	r Q	m V
me-	lo-	dra-	ma-	tic
m e	l V d	r V	m {	t I k
me-	lo-	dra-	mas
m e	l V d	r Q	m V z
me-	lo-	dy
m e	l V	d i:
me-	lo-	ne
m e	l @U	n i:
me-	lon
m e	l V n
me-	lons
m e	l V n z
me-	mel
m e	m V l
me-	men-	to
m V	m e n	t @U
me-	men-	tos
m V	m e n	t @U z
me-	mo
m e	m @U
me-	mo-	ra-	bi-	lia
m e	m @r	V	b i: l	j V
me-	mo-	ra-	ble
m e	m @r	V	b V l
me-	mo-	rab-	ly
m e	m @r	V b	l i:
me-	mo-	ran-	da
m e	m @r	{ n	d V
me-	mo-	ran-	dum
m e	m @r	{ n	d V m
me-	mo-	ran-	dums
m e	m @r	{ n	d V m z
me-	mo-	rex
m e	m O@	e k s
me-	mo-	ri-	a-	lize
m V	m O@	i:	V	l aI z
me-	mo-	ri-	a-	lized
m V	m O@	i:	V	l aI z d
me-	mo-	ri-	al
m V	m O@	i:	V l
me-	mo-	ri-	als
m V	m O@	i:	V l z
me-	mo-	ri-	zing
m e	m @r	aI	z I N
me-	mo-	ries
m e	m @r	i: z
me-	mo-	rize
m e	m @r	aI z
me-	mo-	rized
m e	m @r	aI z d
me-	mo-	ry
m e	m @r	i:
me-	moir
m e m	w Q@
me-	moirs
m e m	w Q@ z
me-	mos
m e	m @U z
me-	mo's
m e	m @U z
me-	na
m i:	n V
me-	na-	cing
m e	n V	s I N
me-	na-	cing-	ly
m e	n V	s I N	l i:
me-	na-	ge-	rie
m V	n {	dZ @r	i:
me-	nace
m e	n V s
me-	nard
m V	n Q@ d
me-	nen-	dez
m e	n e n	d e z
me-	ni-	al
m i:	n i:	V l
me-	ni-	fee
m e	n I	f i:
me-	nin-	gi-	tis
m e	n I n	dZ aI	t I s
me-	no
m eI	n @U
me-	no-	pau-	sal
m e	n V	p aU	z V l
me-	no-	pause
m e	n V	p aU s
me-	no-	rah
m V	n O@	V
me-	no-	rahs
m V	n O@	V z
me-	no-	rah's
m V	n O@	V z
me-	non
m eI	n O: n
me-	nu
m e n	j u:
me-	nu-	hin
m V	n u:	h I n
me-	nus
m e n	j u: z
me-	o
m i:	@U
me-	ow
m i:	aU
me-	quon
m e k	w V n
me-	re-	dith
m e@	V	d I T
me-	rest
m e@	V s t
me-	ri-	da
m @r	i:	d V
me-	ri-	den
m e@	I	d e n
me-	ri-	deth
m e@	I	d I T
me-	ri-	di-	an
m @r	I	d i:	V n
me-	ri-	di-	an's
m @r	I	d i:	V n z
me-	ri-	dith
m e@	I	d I T
me-	ri-	no
m @r	i:	n @U
me-	ri-	on
m e@	i:	V n
me-	ri-	ted
m e@	I	t I d
me-	ri-	to-	ri-	ous
m e@	I	t O@	i:	V s
me-	ri-	toc-	ra-	cy
m e@	I	t O: k	r V	s i:
me-	ri-	we-	ther
m e@	I	w e	D @r
me-	riel
m I@	i: l
me-	ris
m e@	I s
me-	rit
m e@	I t
me-	rit-	less
m e@	I t	l e s
me-	rits
m e@	I t s
me-	row
m e@	@U
me-	ryl
m e@	V l
me-	sa
m eI	s V
me-	sa's
m eI	s V z
me-	sen-	te-	ric
m e	s V n	t e@	I k
me-	ser-	vey
m e	z @r	v eI
me-	shes
m e	S V z
me-	shing
m e	S I N
me-	sick
m e	s I k
me-	so-	der-	mal
m e	z V	d @r	m V l
me-	so-	li-	thic
m e	z V	l I	T I k
me-	so-	po-	ta-	mi-	a
m e	s V	p V	t eI	m i:	V
me-	so-	po-	ta-	mi-	an
m e	s V	p V	t eI	m i:	V n
me-	so-	po-	ta-	mi-	ans
m e	s V	p V	t eI	m i:	V n z
me-	so-	the-	li-	o-	ma
m e	s V	T i:	l i:	@U	m V
me-	so-	tho-	rax
m e	z V	T O@	{ k s
me-	so-	zo-	ic
m e	s V	z @U	I k
me-	son
m eI	z Q n
me-	sons
m i:	z Q n z
me-	ta
m i:	t V
me-	ta-	bo-	li-	sm
m V	t {	b V	l I	z V m
me-	ta-	bo-	li-	sms
m V	t {	b V	l I	z V m z
me-	ta-	bo-	lic
m e	t V	b Q	l I k
me-	ta-	bo-	lize
m V	t {	b V	l aI z
me-	ta-	car-	pal
m e	t V	k Q@	p V l
me-	ta-	car-	pals
m e	t V	k Q@	p V l z
me-	ta-	mor-	phic
m e	t V	m O@	f I k
me-	ta-	mor-	pho-	sis
m e	t V	m O@	f V	s V s
me-	ta-	mor-	phose
m e	t V	m O@	f @U z
me-	ta-	mu-	cil
m e	t V m	j u:	s V l
me-	ta-	mu-	cil's
m e	t V m	j u:	s V l z
me-	ta-	pho-	ri-	cal
m e	t V	f O@	I	k V l
me-	ta-	pho-	rical-	ly
m e	t V	f O@	I k	l i:
me-	ta-	phor
m e	t V	f O@
me-	ta-	phors
m e	t V	f O@ z
me-	ta-	phy-	si-	cal
m e	t V	f I	z I	k V l
me-	ta-	phy-	sics
m e	t V	f I	z I k s
me-	ta-	tho-	rax
m e	t V	T O@	{ k s
me-	ta-	xas
m V	t { k	s V s
me-	tai-	rie
m V	t e@	i:
me-	tal
m e	t V l
me-	tal-	li-	ca
m V	t {	l I	k V
me-	tal-	lic
m V	t {	l I k
me-	tal-	lur-	gi-	cal
m e	t V	l @r	dZ I	k V l
me-	tal-	lur-	gy
m e	t V	l @r	dZ i:
me-	tal-	wor-	ker
m e	t V l	w @r	k @r
me-	tal-	wor-	kers
m e	t V l	w @r	k @r z
me-	tal-	wor-	king
m e	t V l	w @r	k I N
me-	tal-	work
m e	t V l	w @r k
me-	tall
m e	t O: l
me-	tals
m e	t V l z
me-	tal's
m e	t V l z
me-	tas-	ta-	size
m V	t { s	t V	s aI z
me-	tas-	ta-	sized
m V	t { s	t V	s aI z d
me-	te-	o-	ric
m i:	t i:	O@	I k
me-	te-	o-	rite
m i:	t i:	O@	aI t
me-	te-	o-	ro-	lo-	gi-	cal
m i:	t i:	O@	V	l Q	dZ V	k V l
me-	te-	o-	ro-	lo-	gist
m i:	t i:	@r	Q	l V	dZ V s t
me-	te-	o-	ro-	lo-	gists
m i:	t i:	@r	Q	l V	dZ V s t s
me-	te-	o-	ro-	lo-	gy
m i:	t i:	@r	Q	l V	dZ i:
me-	te-	or
m i:	t i:	@r
me-	te-	ors
m i:	t i:	@r z
me-	te-	ring
m i:	t @r	I N
me-	ted
m i:	t V d
me-	ter
m i:	t @r
me-	tered
m i:	t @r d
me-	ters
m i:	t @r z
me-	tha-	done
m e	T V	d @U n
me-	tha-	nol
m e	T V	n Q l
me-	tham-	phe-	ta-	mine
m e	T { m	f e	t V	m i: n
me-	thane
m e	T eI n
me-	tho-	di-	cal
m V	T Q	d V	k V l
me-	tho-	di-	cal-	ly
m V	T Q	d I	k V	l i:
me-	tho-	di-	sm
m e	T V	d I	z V m
me-	tho-	di-	sms
m e	T V	d I	z V m z
me-	tho-	dist
m e	T V	d V s t
me-	tho-	do-	lo-	gi-	cal
m e	T V	d V	l Q	dZ I	k V l
me-	tho-	do-	lo-	gies
m e	T @U	d Q	l V	dZ i: z
me-	tho-	do-	lo-	gy
m e	T V	d Q	l V	dZ i:
me-	tho-	tre-	xate
m e	T @U t	r e k	s eI t
me-	thod
m e	T V d
me-	thods
m e	T V d z
me-	thu-	se-	lah
m V T	j u:	z V	l V
me-	thy-	lene
m e	T V	l i: n
me-	thyl
m e	T V l
me-	va-	cor
m e	v V	k O@
me-	xi-	ca-	li
m e k	s I	k Q	l i:
me-	xi-	ca-	na
m e k	s I	k {	n V
me-	xi-	ca-	no
m e k	s I	k Q	n @U
me-	xi-	can
m e k	s I	k V n
me-	xi-	cans
m e k	s I	k V n z
me-	xi-	co
m e k	s I	k @U
me-	xi-	co's
m e k	s I	k @U z
me-	yers
m aI	@r z
me-	zo
m e	z @U
mea
m i:
mea-	der
m i:	d @r
mea-	dor
m i:	d @r
mea-	dow
m e	d @U
mea-	dow-	land
m e	d @U	l { n d
mea-	dow-	lands
m e	d @U	l { n d z
mea-	dow-	lark
m e	d @U	l Q@ k
mea-	dows
m e	d @U z
mea-	ger
m i:	g @r
mea-	ler
m i:	l @r
mea-	ling
m i:	l I N
mea-	ly
m i:	l i:
mea-	ner
m i:	n @r
mea-	nest
m i:	n V s t
mea-	ning
m i:	n I N
mea-	ning-	ful
m i:	n I N	f V l
mea-	ning-	ful-	ly
m i:	n I N	f V	l i:
mea-	ning-	less
m i:	n I N	l V s
mea-	nings
m i:	n I N z
mea-	ny
m i:	n i:
mea-	ra
m i:	r V
mea-	sles
m i:	z V l z
mea-	su-	ra-	ble
m e	Z @r	V	b V l
mea-	su-	rab-	ly
m e	Z @r	V b	l i:
mea-	su-	ring
m e	Z @r	I N
mea-	sure
m e	Z @r
mea-	sure-	ment
m e	Z @r	m V n t
mea-	sure-	ments
m e	Z @r	m V n t s
mea-	sured
m e	Z @r d
mea-	sures
m e	Z @r z
mea-	sure's
m e	Z @r z
mea-	ti-	er
m i:	t i:	@r
mea-	ty
m i:	t i:
mead
m i: d
meade
m i: d
meads
m i: d z
mead's
m i: d z
meagher
m Q@
meal
m i: l
meal-	time
m i: l	t aI m
meals
m i: l z
meal's
m i: l z
mean
m i: n
mean-	ness
m i: n	n V s
mean-	time
m i: n	t aI m
mean-	while
m i: n	w aI l
means
m i: n z
meant
m e n t
mear
m I@
meares
m i: r z
mears
m I@ z
meas-	ly
m i: z	l i:
mease
m i: z
meat
m i: t
meat-	ball
m i: t	b O: l
meat-	balls
m i: t	b O: l z
meat-	ea-	ting
m i:	t i:	t I N
meat-	less
m i: t	l V s
meat-	loaf
m i: t	l @U f
meat-	pac-	ker
m i: t	p {	k @r
meat-	pac-	kers
m i: t	p {	k @r z
meat-	pac-	king
m i: t	p {	k I N
meath
m i: T
meats
m i: t s
meave
m i: v
mec-	ca
m e	k V
mec-	ca's
m e	k V z
mech
m e k
mech-	ling
m e k	l I N
meck
m e k
meck-	len-	burg
m e k	l V n	b @r g
med
m e d
med-	d-	ling
m e	d V	l I N
med-	dle
m e	d V l
med-	dle-	some
m e	d V l	s V m
med-	fly
m e d	f l i:
med-	ford
m e d	f @r d
med-	lar
m e d	l @r
med-	ley
m e d	l i:
med-	lin
m e d	l I n
med-	win
m e d	w I n
medes
m i: d z
mee
m i:
mee-	han
m i:	V n
mee-	ker
m i:	k @r
mee-	ting
m i:	t I N
mee-	tings
m i:	t I N z
mee-	ting's
m i:	t I N z
meece
m i: s
meech
m i: tS
meek
m i: k
meek-	ly
m i: k	l i:
meeks
m i: k s
meese
m i: s
meet
m i: t
meets
m i: t s
meg
m e g
meggs
m e g z
meh-	ta
m e	t V
meh-	ta's
m e	t V z
mei
m aI
mei-	er
m aI	@r
mei-	er's
m aI	@r z
mel
m e l
mel-	ba
m e l	b V
mel-	bourne
m e l	b @r n
mel-	burn
m e l	b @r n
mel-	cher
m e l	tS @r
mel-	chi-	or
m eI l	tS i:	@r
mel-	ded
m e l	d V d
mel-	der
m e l	d @r
mel-	ding
m e l	d I N
mel-	don
m e l	d V n
mel-	gar
m eI l	g Q@
mel-	la
m e	l V
mel-	la-	ril
m e	l @r	I l
mel-	len
m e	l V n
mel-	ler
m e	l @r
mel-	li
m e	l i:
mel-	li-	cent
m eI	l i:	s V n t
mel-	lie
m e	l i:
mel-	ling
m e	l I N
mel-	lo
m e	l @U
mel-	lon
m e	l V n
mel-	lon's
m e	l V n z
mel-	lott
m e	l V t
mel-	low
m e	l @U
mel-	lowed
m e	l @U d
mel-	ly
m e	l i:
mel-	nick
m e l	n I k
mel-	quist
m e l	k w I s t
mel-	rose
m e l	r @U z
mel-	ted
m e l	t V d
mel-	ting
m e l	t I N
mel-	ton
m e l	t V n
mel-	va
m e l	v V
mel-	vi-	na
m e l	v i:	n V
mel-	vie
m e l	v i:
mel-	ville
m e l	v I l
mel-	vin
m e l	v I n
mel-	vyn
m e l	v I n
meld
m e l d
mele
m i: l
mell
m e l
mell-	man
m e l	m V n
mel's
m e l z
melt
m e l t
melt-	down
m e l	t d aU n
melt-	wa-	ter
m e l	t w Q	t @r
melts
m e l t s
mem-	ber
m e m	b @r
mem-	ber-	ship
m e m	b @r	S I p
mem-	ber-	ships
m e m	b @r	S I p s
mem-	bered
m e m	b @r d
mem-	bers
m e m	b @r z
mem-	ber's
m e m	b @r z
mem-	bra-	nous
m e m	b r V	n V s
mem-	brane
m e m	b r eI n
mem-	branes
m e m	b r eI n z
mem-	non
m e m	n Q n
mem-	phis
m e m	f I s
men
m e n
men-	cher
m e n	tS @r
men-	cken
m e N	k V n
men-	da-	ci-	ty
m e n	d {	s I	t i:
men-	ded
m e n	d V d
men-	del
m e n	d V l
men-	del-	sohn
m e n	d V l	s V n
men-	del-	son
m e n	d V l	s V n
men-	del's
m e n	d V l z
men-	dels-	sohn
m e n	d V l	s V n
men-	den-	hall
m e n	d V n	h O: l
men-	des
m eI n	d e s
men-	dez
m e n	d e z
men-	ding
m e n	d I N
men-	do-	ci-	no
m e n	d V	s i:	n @U
men-	do-	ta
m e n	d @U	t V
men-	do-	za
m e n	d @U	z V
men-	ges
m e n	dZ V z
men-	gis-	tu
m e N	g i: s	t u:
men-	ha-	den
m e n	h eI	d V n
men-	ken
m e N	k V n
men-	lo
m e n	l @U
men-	nen
m e	n V n
men-	nin-	ger
m e	n I	N @r
men-	no-	nite
m e	n V	n aI t
men-	no-	nites
m e	n V	n aI t s
men-	sing
m e n	s I N
men-	ta-	li-	ty
m e n	t {	l I	t i:
men-	tal
m e n	t V l
men-	tal-	ly
m e n	t V	l i:
men-	tho-	la-	tum
m e n	T V	l eI	t V m
men-	thol
m e n	T O: l
men-	tio-	ning
m e n	S V	n I N
men-	tion
m e n	S V n
men-	tioned
m e n	S V n d
men-	tions
m e n	S V n z
men-	to
m e n	t @U
men-	to-	ring
m e n	t @r	I N
men-	ton
m e n	t V n
men-	tor
m e n	t O@
men-	tored
m e n	t @r d
men-	tors
m e n	t @r z
men-	tor's
m e n	t O@ z
men-	zie
m e n	z i:
men-	zies
m e n	z i: z
mend
m e n d
mende
m e n d
meng
m e N
menge
m e n dZ
mens
m e n z
men's
m e n z
mens-	tru-	a-	tion
m e n	s t r u:	eI	S V n
mens-	tru-	al
m e n	s t r u:	V l
mens-	wear
m e n	z w eI r
mensch
m e n S
mer
m e@
mer-	ca-	do
m @r	k Q	d @U
mer-	ca-	tor
m @r	k eI	t @r
mer-	can-	ti-	li-	sm
m @r	k { n	t I	l I	z V m
mer-	can-	ti-	list
m @r	k { n	t I	l I s t
mer-	can-	tile
m @r	k V n	t aI l
mer-	ce-	des
m @r	s eI	d i: z
mer-	ce-	na-	ry
m @r	s V	n e@	i:
mer-	cer
m @r	s @r
mer-	chan-	di-	ser
m @r	tS V n	d aI	z @r
mer-	chan-	di-	sers
m @r	tS V n	d aI	z @r z
mer-	chan-	di-	sing
m @r	tS V n	d aI	z I N
mer-	chan-	dise
m @r	tS V n	d aI z
mer-	chant
m @r	tS V n t
mer-	chant-	men
m @r	tS V n	t m e n
mer-	chants
m @r	tS V n t s
mer-	chant's
m @r	tS V n t s
mer-	ci-	er
m @r	s i:	@r
mer-	ci-	ful
m @r	s I	f V l
mer-	ci-	ful-	ly
m @r	s I	f V	l i:
mer-	ci-	less
m @r	s I	l e s
mer-	ci-	less-	ly
m @r	s I	l e s	l i:
mer-	cies
m @r	s i: z
mer-	cu-	ri
m @r	k U@	i:
mer-	cu-	ri-	al
m @r k	j U@	i:	V l
mer-	cu-	ric
m @r k	j U@	I k
mer-	cu-	ry
m @r k	j @r	i:
mer-	cu-	ry's
m @r k	j @r	i: z
mer-	cy
m @r	s i:
mer-	ger
m @r	dZ @r
mer-	gers
m @r	dZ @r z
mer-	ger's
m @r	dZ @r z
mer-	ges
m @r	dZ V z
mer-	ging
m @r	dZ I N
mer-	kel
m @r	k V l
mer-	kin
m @r	k I n
mer-	kle
m @r	k V l
mer-	li-	na
m @r	l i:	n V
mer-	lin
m @r	l I n
mer-	rell
m e@	V l
mer-	ri-	am
m e@	i:	V m
mer-	ri-	er
m e@	i:	@r
mer-	ri-	field
m e@	I	f i: l d
mer-	ri-	ly
m e@	I	l i:
mer-	ri-	mac
m e@	I	m { k
mer-	ri-	mack
m e@	I	m { k
mer-	ri-	man
m e@	I	m V n
mer-	ri-	ott
m e@	i:	V t
mer-	rick
m e@	I k
mer-	rie
m e@	i:
mer-	rill
m e@	I l
mer-	rill's
m e@	I l z
mer-	ritt
m e@	e t
mer-	row
m e@	@U
mer-	ry
m e@	i:
mer-	ry-	go-	round
m e@	i:	g @U	r aU n d
mer-	ry-	man
m e@	i:	m V n
mer-	shon
m @r	S V n
mer-	ta
m e@	t V
mer-	tens
m @r	t V n z
mer-	ton
m @r	t V n
mer-	vin
m @r	v I n
mer-	vyn
m @r	v I n
mer-	vyn's
m @r	v I n z
mer-	win
m @r	w I n
mer-	wyn
m @r	w I n
merc
m @r k
merce
m @r s
merck
m @r k
merck's
m @r k s
merc's
m @r k s
mere
m I@
mere-	ly
m I@	l i:
merge
m @r dZ
merged
m @r dZ d
merk
m @r k
merk-	ley
m @r k	l i:
merl
m @r l
merle
m @r l
mers
m @r z
merv
m @r v
mes-	ca-	le-	ro
m e s	k V	l e@	@U
mes-	ca-	line
m e s	k V	l i: n
mes-	me-	ri-	sm
m e s	m @r	I	z V m
mes-	me-	ri-	zing
m e z	m @r	aI	z I N
mes-	me-	rize
m e z	m @r	aI z
mes-	me-	rized
m e z	m @r	aI z d
mes-	mer
m e z	m @r
mes-	quite
m e s	k i: t
mes-	sa-	ges
m e	s V	dZ V z
mes-	sa-	ging
m e	s I	dZ I N
mes-	sage
m e	s V dZ
mes-	sen-	ger
m e	s V n	dZ @r
mes-	sen-	gers
m e	s V n	dZ @r z
mes-	ser
m e	s @r
mes-	sersch-	midt
m e	s @r S	m I t
mes-	sersch-	mitt
m e	s @r S	m I t
mes-	ses
m e	s V z
mes-	si-	a-	nic
m e	s i:	{	n I k
mes-	si-	aen
m e	s i:	eI n
mes-	si-	aen's
m e	s i:	eI n z
mes-	si-	ah
m V	s aI	V
mes-	si-	ahs
m V	s aI	V z
mes-	si-	er
m e	s i:	@r
mes-	si-	na
m V	s i:	n V
mes-	sing
m e	s I N
mes-	srs
m e	s @r z
mes-	srs.
m e	s @r z
mes-	sy
m e	s i:
mes-	ter
m e s	t @r
mes-	ti-	zo
m e s	t i:	z @U
mesh
m e S
meshed
m e S t
mess
m e s
mess-	man
m e s	m V n
messed
m e s t
mest
m e s t
met
m e t
met-	calf
m e t	k { f
met-	calfe
m e t	k V l f
met-	ra
m e t	r V
met-	ri-	cal
m e t	r I	k V l
met-	ri-	cal-	ly
m e t	r I	k V	l i:
met-	ric
m e t	r I k
met-	rics
m e t	r I k s
met-	ro
m e t	r @U
met-	ro-	plex
m e t	r @U p	l e k s
met-	ro-	po-	li-	tan
m e t	r V	p Q	l V	t V n
met-	ro-	po-	li-	tans
m e t	r V	p Q	l V	t V n z
met-	ro-	po-	lis
m V t	r Q	p V	l V s
met-	ro's
m e t	r @U z
met-	ter
m e	t @r
met-	ter-	nich
m e	t @r	n I tS
)"
R"(met-	tle
m e	t V l
mete
m i: t
meth
m e T
mets
m e t s
metts
m e t s
metz
m e t s
metz-	gar
m e t	s g @r
metz-	ger
m e t	s g @r
metz-	ger's
m e t	s g @r z
metz-	ler
m e t	s l @r
metze
m e t z
meu-	ni-	er
m OI	n i:	@r
meu-	rer
m @r	@r
meu-	ser
m OI	s @r
meuse
m j u: z
mew
m j u:
mex
m e k s
mey-	er
m aI	@r
mey-	er-	beer
m aI	@r	b I@
mey-	er's
m aI	@r z
mez-	za-	nine
m e	z V	n i: n
mez-	zo
m e	z @U
mi
m i:
mi-	a
m i:	V
mi-	a-	mi
m aI	{	m i:
mi-	a-	mi's
m aI	{	m i: z
mi-	as-	ma
m i:	{ z	m V
mi-	ca
m aI	k V
mi-	ca-	no-	py
m I	k {	n V	p i:
mi-	cae-	la
m i:	k eI	l V
mi-	cah
m aI	k V
mi-	chae-	la
m aI	k e	l V
mi-	chae-	li-	na
m aI	k V	l i:	n V
mi-	chae-	line
m aI	k V	l aI n
mi-	chael
m aI	k V l
mi-	chael-	la
m aI	k e	l V
mi-	chael-	son
m aI	k V l	s V n
mi-	chaels
m aI	k V l z
mi-	chael's
m aI	k V l z
mi-	chal
m I	tS V l
mi-	chaud
m I	S @U
mi-	chaux
m I	S @U
mi-	che-	lan-	ge-	lo
m aI	k V	l { n	dZ V	l @U
mi-	che-	lan-	ge-	lo's
m aI	k V	l { n	dZ V	l @U z
mi-	che-	li-	na
m I	k V	l i:	n V
mi-	che-	lin
m I	S V	l I n
mi-	che-	line
m I	S V	l V n
mi-	che-	lob
m I	k V	l @U b
mi-	cheal
m aI	k V l
mi-	chel
m I	S e l
mi-	chel-	sen
m aI	k V l	s V n
mi-	chel-	son
m aI	k V l	s V n
mi-	chele
m I	S e l
mi-	chell
m I	tS V l
mi-	chelle
m I	S e l
mi-	chel's
m I	S e l z
mi-	chi-	gan
m I	S I	g V n
mi-	chi-	gan's
m I	S I	g V n z
mi-	chie
m I	tS i:
mi-	choa-	can
m I	tS @U	k V n
mi-	chon
m I	tS V n
mi-	dair
m I	d e@
mi-	das
m aI	d V s
mi-	deast
m I	d i: s t
mi-	gra-	ted
m aI g	r eI	t V d
mi-	gra-	ting
m aI g	r eI	t I N
mi-	gra-	tion
m aI g	r eI	S V n
mi-	gra-	tions
m aI g	r eI	S V n z
mi-	gra-	to-	ry
m aI g	r V	t O@	i:
mi-	graine
m aI g	r eI n
mi-	graines
m aI g	r eI n z
mi-	grant
m aI g	r V n t
mi-	grants
m aI g	r V n t s
mi-	grate
m aI g	r eI t
mi-	guel
m I	g e l
mi-	ka
m i:	k V
mi-	ka-	do
m I	k Q	d @U
mi-	kae-	la
m i:	k eI	l V
mi-	kael
m V	k eI l
mi-	kal
m i:	k V l
mi-	kel
m I	k V l
mi-	key
m aI	k i:
mi-	khail
m I	k eI l
mi-	ko
m aI	k @U
mi-	kol
m I	k O: l
mi-	la-	no
m i:	l Q	n @U
mi-	lam
m I	l V m
mi-	lan
m V	l Q n
mi-	lan's
m I	l Q n z
mi-	laz-	zo
m i:	l Q	z @U
mi-	leage
m aI	l V dZ
mi-	ler
m aI	l @r
mi-	lew-	ski
m V	l e f	s k i:
mi-	ley
m aI	l i:
mi-	li-	cent
m I	l I	s e n t
mi-	li-	ta-	ri-	ly
m I	l I	t e@	I	l i:
mi-	li-	ta-	ri-	sm
m I	l I	t @r	I	z V m
mi-	li-	ta-	ries
m I	l I	t e@	i: z
mi-	li-	ta-	ris-	tic
m I	l I	t @r	I s	t I k
mi-	li-	ta-	rists
m I	l I	t @r	I s t s
mi-	li-	ta-	rize
m I	l I	t @r	aI z
mi-	li-	ta-	rized
m I	l I	t @r	aI z d
mi-	li-	ta-	ry
m I	l I	t e@	i:
mi-	li-	tan-	cy
m I	l I	t V n	s i:
mi-	li-	tant
m I	l I	t V n t
mi-	li-	tant-	ly
m I	l I	t V n	t l i:
mi-	li-	tants
m I	l I	t V n t s
mi-	li-	tate
m I	l I	t eI t
mi-	li-	tia
m V	l I	S V
mi-	li-	tia-	men
m V	l I	S V	m e n
mi-	li-	tias
m V	l I	S V z
mi-	li-	tia's
m V	l I	S V z
mi-	lieu
m I l	j U
mi-	lis-	sent
m I	l I	s e n t
mi-	lo
m aI	l @U
mi-	lo-	se-	vi-	c's
m I	l @U	s V	v I	tS V z
mi-	lo-	se-	vic
m I	l @U	s V	v I k
mi-	lone
m I	l @U n
mi-	los
m i:	l @U z
mi-	me-	o-	graph
m I	m i:	V g	r { f
mi-	mi
m i:	m i:
mi-	mi-	cry
m I	m I k	r i:
mi-	mic
m I	m I k
mi-	mic-	king
m I	m I	k I N
mi-	micked
m I	m I k t
mi-	mics
m I	m I k s
mi-	mi's
m i:	m i: z
mi-	mo-	sa
m V	m @U	s V
mi-	na
m i:	n V
mi-	na-	ret
m I	n @r	e t
mi-	na-	rets
m I	n @r	e t s
mi-	nar
m aI	n @r
mi-	nas
m i:	n V s
mi-	ne-	o-	la
m I	n i:	@U	l V
mi-	ne-	ra-	li-	za-	tion
m I	n @r	V	l V	z eI	S V n
mi-	ne-	ra-	lize
m I	n @r	V	l aI z
mi-	ne-	ra-	lo-	gi-	cal-	ly
m I	n @r	V	l Q	dZ I	k V	l i:
mi-	ne-	ra-	lo-	gist
m I	n @r	{	l V	dZ V s t
mi-	ne-	ra-	lo-	gy
m I	n @r	Q	l V	dZ i:
mi-	ne-	ral
m I	n @r	V l
mi-	ne-	rals
m I	n @r	V l z
mi-	ne-	ral's
m I	n @r	V l z
mi-	neow-	ner
m aI	n @U	n @r
mi-	ner
m aI	n @r
mi-	ner-	va
m I	n @r	v V
mi-	ners
m aI	n @r z
mi-	ner's
m aI	n @r z
mi-	nette
m I	n e t
mi-	ni
m I	n i:
mi-	ni-	a-	tu-	ri-	za-	tion
m I	n i:	V	tS @r	V	z eI	S V n
mi-	ni-	a-	ture
m I	n i:	V	tS U@
mi-	ni-	a-	tures
m I	n i:	V	tS @r z
mi-	ni-	bu-	ses
m I	n i:	b V	s V z
mi-	ni-	bus
m I	n i:	b V s
mi-	ni-	car
m I	n i:	k Q@
mi-	ni-	cars
m I	n i:	k Q@ z
mi-	ni-	com-	pu-	ter
m I	n i:	k V m	p j u:	t @r
mi-	ni-	com-	pu-	ters
m I	n i:	k V m	p j u:	t @r z
mi-	ni-	er
m I	n i:	@r
mi-	ni-	lab
m I	n i:	l { b
mi-	ni-	labs
m I	n i:	l { b z
mi-	ni-	ma-	li-	sm
m I	n I	m V	l I	z V m
mi-	ni-	ma-	list
m I	n I	m V	l I s t
mi-	ni-	mal
m I	n I	m V l
mi-	ni-	mal-	ly
m I	n I	m V	l i:
mi-	ni-	mi-	zes
m I	n I	m aI	z V z
mi-	ni-	mi-	zing
m I	n I	m aI	z I N
mi-	ni-	mill
m I	n i:	m Q l
mi-	ni-	mills
m I	n i:	m I l z
mi-	ni-	mize
m I	n I	m aI z
mi-	ni-	mized
m I	n I	m aI z d
mi-	ni-	mum
m I	n I	m V m
mi-	ni-	mums
m I	n I	m V m z
mi-	ni-	scule
m I	n I s	k j u: l
mi-	ni-	se-	ries
m I	n i:	s i:	r i: z
mi-	ni-	skirt
m I	n i: s	k @r t
mi-	ni-	skirts
m I	n i: s	k @r t s
mi-	ni-	ste-	ri-	al
m I	n I s	t i:	r i:	V l
mi-	ni-	ster
m I	n I s	t @r
mi-	ni-	ster-	ship
m I	n I s	t @r	S I p
mi-	ni-	stering
m I	n I s	t r I N
mi-	ni-	sters
m I	n I s	t @r z
mi-	ni-	ster's
m I	n I s	t @r z
mi-	ni-	tel
m I	n I	t e l
mi-	ni-	um
m I	n i:	V m
mi-	ni-	van
m I	n i:	v { n
mi-	ni-	vans
m I	n i:	v { n z
mi-	nia-	tu-	rize
m I	n I	tS @r	aI z
mi-	nia-	tu-	rized
m I	n I	tS @r	aI z d
mi-	niard
m I n	j @r d
mi-	ning
m aI	n I N
mi-	ning's
m aI	n I N z
mi-	nion
m I n	j V n
mi-	nions
m I n	j V n z
mi-	nis
m I	n i: z
mi-	nish
m I	n I S
mi-	nist-	ra-	tion
m I	n I s	t r eI	S V n
mi-	nist-	ra-	tions
m I	n I s	t r eI	S V n z
mi-	nist-	ries
m I	n I s	t r i: z
mi-	nist-	ry
m I	n I s	t r i:
mi-	nist-	ry's
m I	n I s	t r i: z
mi-	no
m i:	n @U
mi-	no-	an
m V	n @U	V n
mi-	no-	ri-	ties
m aI	n O@	I	t i: z
mi-	no-	ri-	ty
m aI	n O@	I	t i:
mi-	no-	ring
m aI	n @r	I N
mi-	no-	rite
m I	n @r	aI t
mi-	no-	ru
m I	n O@	u:
mi-	no-	xi-	dil
m V	n Q k	s V	d V l
mi-	nol-	ta
m I	n Q l	t V
mi-	nor
m aI	n @r
mi-	nor-	ca
m V	n O@	k V
mi-	nored
m aI	n @r d
mi-	nors
m aI	n @r z
mi-	not
m I	n V t
mi-	now
m I	n @U
mi-	nu-	et
m I n	j V	w e t
mi-	nu-	ses
m aI	n V	s V z
mi-	nu-	ti-	a
m V	n u:	S i:	V
mi-	nu-	ti-	ae
m V	n u:	S i:	V
mi-	nus
m aI	n V s
mi-	nus-	cule
m I	n V s	k j u: l
mi-	nute
m I	n V t
mi-	nute-	ly
m I	n V t	l i:
mi-	nute-	man
m I	n V t	m { n
mi-	nute-	men
m I	n V t	m e n
mi-	nutes
m I	n V t s
mi-	nute's
m I	n V t s
mi-	o-	cene
m aI	V	s i: n
mi-	ra
m I@	V
mi-	ra-	bel
m I@	Q	b e l
mi-	ra-	bel-	la
m I@	Q	b e	l V
mi-	ra-	belle
m O@	V	b V l
mi-	ra-	bile
m I@	Q	b V l
mi-	ra-	cle
m I@	V	k V l
mi-	ra-	cles
m I@	V	k V l z
mi-	ra-	cu-	lous
m @r	{ k	j V	l V s
mi-	ra-	cu-	lous-	ly
m @r	{ k	j V	l V s	l i:
mi-	ra-	ges
m @r	Q	Z V z
mi-	ra-	mar
m I@	V	m Q@
mi-	rage
m @r	Q Z
mi-	rak
m I@	{ k
mi-	ran-	da
m @r	{ n	d V
mi-	ran-	da's
m @r	{ n	d V z
mi-	rel-	la
m I@	e	l V
mi-	relle
m @r	e l
mi-	sad-	ven-	ture
m I	s V d	v e n	tS @r
mi-	sad-	ven-	tures
m I	s V d	v e n	tS @r z
mi-	sal-	lo-	ca-	ted
m I	s {	l V	k eI	t V d
mi-	sal-	lo-	ca-	tion
m I	s {	l V	k eI	S V n
mi-	sal-	lo-	cate
m I	s {	l V	k eI t
mi-	santh-	rope
m I	s V n	T r @U p
mi-	sap-	pli-	ca-	tion
m I	s { p	l I	k eI	S V n
mi-	sap-	plied
m I	s V p	l aI d
mi-	sap-	ply
m I	s V p	l aI
mi-	sap-	ply-	ing
m I	s V p	l aI	I N
mi-	sap-	pre-	hen-	sion
m I	s { p	r i:	h e n	S V n
mi-	sap-	pro-	pri-	a-	ted
m I	s V p	r @U p	r i:	eI	t V d
mi-	sap-	pro-	pri-	a-	ting
m I	s V p	r @U p	r i:	eI	t I N
mi-	sap-	pro-	pri-	a-	tion
m I	s V p	r @U p	r i:	eI	S V n
mi-	sap-	pro-	pri-	ate
m I	s V p	r @U p	r i:	eI t
mi-	sci-	bi-	li-	ty
m I	s I	b I	l I	t i:
mi-	sci-	ble
m I	s I	b V l
mi-	se-	ra-	ble
m I	z @r	V	b V l
mi-	se-	ra-	bles
m I	z @r	V	b V l z
mi-	se-	ra-	tion
m I	z @r	eI	S V n
mi-	se-	rab-	ly
m I	z @r	V b	l i:
mi-	se-	ries
m I	z @r	i: z
mi-	se-	ry
m I	z @r	i:
mi-	sen-	hei-	mer
m I	s V n	h aI	m @r
mi-	ser
m aI	z @r
mi-	ser-	ly
m aI	z @r	l i:
mi-	ses
m aI	z V z
mi-	sha
m I	S V
mi-	sha-	wa-	ka
m I	S V	w O:	k V
mi-	shan-	dle
m I s	h { n	d V l
mi-	shan-	dled
m I s	h { n	d V l d
mi-	shand-	ling
m I s	h { n	d l I N
mi-	shap
m I s	h { p
mi-	shaps
m I s	h { p s
mi-	shear
m I s	h i: r
mi-	sheard
m I s	h @r d
mi-	si-	den-	ti-	fi-	ca-	tion
m I	s aI	d e n	t I	f I	k eI	S V n
mi-	si-	den-	ti-	fied
m I	s aI	d e n	t I	f aI d
mi-	si-	den-	ti-	fy
m I	s aI	d e n	t I	f aI
mi-	so-	gy-	nist
m I	z V	dZ V	n V s t
mi-	so-	gy-	ny
m I	z V	dZ V	n i:
mi-	so-	gyne
m I	z V	dZ V n
mi-	stle-	toe
m I	s V l	t @U
mi-	su-	ses
m I s	j u:	z V z
mi-	su-	sing
m I s	j u:	z I N
mi-	suse
m I s	j u: z
mi-	sused
m I s	j u: z d
mi-	ta
m i:	t V
mi-	te-	ring
m aI	t @r	I N
mi-	ter
m aI	t @r
mi-	ti
m I	t i:
mi-	ti-	ga-	ted
m I	t I	g eI	t I d
mi-	ti-	ga-	ting
m I	t I	g eI	t I N
mi-	ti-	ga-	tion
m I	t I	g eI	S V n
mi-	ti-	gate
m I	t I	g eI t
mi-	ti-	gates
m I	t I	g eI t s
mi-	tsu-	bi-	shi
m I t	s u:	b i:	S i:
mi-	tsu-	bi-	shi's
m I t	s u:	b i:	S i: z
mi-	xer
m I k	s @r
mi-	xers
m I k	s @r z
mi-	xes
m I k	s V z
mi-	xing
m I k	s I N
mi-	zar
m aI	z Q@
mi-	zar's
m aI	z Q@ z
mi-	zen
m aI	z V n
mi-	ze's
m aI	z V z
mib
m I b
mic
m I k
mic-	kel-	son
m I	k V l	s V n
mic-	key
m I	k i:
mic-	key's
m I	k i: z
mic-	ki
m I	k i:
mic-	kie
m I	k i:
mic-	kie-	wicz
m I	k I	v I tS
mic-	kle
m I	k V l
mic-	kles
m I	k V l z
mic-	ky
m I	k i:
mic-	ro
m aI k	r @U
mic-	ro-	bi-	al
m aI k	r @U	b i:	V l
mic-	ro-	bi-	o-	lo-	gist
m aI k	r @U	b i:	Q	l V	dZ V s t
mic-	ro-	bi-	o-	lo-	gy
m aI k	r @U	b aI	Q	l V	dZ i:
mic-	ro-	bre-	we-	ries
m aI k	r @U b	r u:	@r	i: z
mic-	ro-	bre-	we-	ry
m aI k	r @U b	r u:	@r	i:
mic-	ro-	chip
m aI k	r @U	tS I p
mic-	ro-	chips
m aI k	r @U	tS I p s
mic-	ro-	cir-	cuit
m aI k	r @U	s @r	k I t
mic-	ro-	cir-	cuits
m aI k	r @U	s @r	k I t s
mic-	ro-	cli-	mate
m aI k	r @U k	l aI	m V t
mic-	ro-	cli-	mates
m aI k	r @U k	l aI	m V t s
mic-	ro-	co-	sm
m aI k	r V	k Q	z V m
mic-	ro-	code
m aI k	r @U	k @U d
mic-	ro-	com-	pu-	ter
m aI k	r @U	k V m	p j u:	t @r
mic-	ro-	com-	pu-	ters
m aI k	r @U	k V m	p j u:	t @r z
mic-	ro-	dyne
m aI k	r @U	d aI n
mic-	ro-	e-	co-	no-	mic
m aI k	r @U	e	k V	n Q	m I k
mic-	ro-	e-	co-	no-	mics
m aI k	r @U	e	k V	n Q	m I k s
mic-	ro-	e-	lec-	tro-	nic
m aI k	r @U	V	l e k	t r Q	n I k
mic-	ro-	e-	lec-	tro-	nics
m aI k	r @U	V	l e k	t r Q	n I k s
mic-	ro-	fiche
m aI k	r @U	f i: tS
mic-	ro-	film
m aI k	r V	f I l m
mic-	ro-	fos-	sil
m aI k	r @U	f Q	s I l
mic-	ro-	fos-	sils
m aI k	r @U	f Q	s I l z
mic-	ro-	gra-	phic
m aI k	r @U g	r {	f I k
mic-	ro-	gra-	phics
m aI k	r @U g	r {	f I k s
mic-	ro-	gram
m aI k	r @U g	r { m
mic-	ro-	grams
m aI k	r @U g	r { m z
mic-	ro-	li-	ter
m aI k	r @U	l i:	t @r
mic-	ro-	li-	ters
m aI k	r @U	l i:	t @r z
mic-	ro-	ma-	na-	ging
m aI k	r @U	m {	n I	dZ I N
mic-	ro-	ma-	nage
m aI k	r @U	m {	n I dZ
mic-	ro-	ma-	nage-	ment
m aI k	r @U	m {	n I dZ	m V n t
mic-	ro-	me-	ter
m aI k	r Q	m V	t @r
mic-	ro-	ne-	sia
m aI k	r @U	n i:	Z V
mic-	ro-	or-	ga-	ni-	sm
m aI k	r @U	O@	g V	n I	z V m
mic-	ro-	or-	ga-	ni-	sms
m aI k	r @U	O@	g V	n I	z V m z
mic-	ro-	pa-	le-	on-	to-	lo-	gy
m aI k	r @U	p eI	l i:	V n	t Q	l V	dZ i:
mic-	ro-	phone
m aI k	r V	f @U n
mic-	ro-	phones
m aI k	r @U	f @U n z
mic-	ro-	po-	lis
m aI k	r O:	p V	l I s
mic-	ro-	pro-	ces-	sor
m aI k	r @U p	r Q	s e	s @r
mic-	ro-	pro-	ces-	sors
m aI k	r @U p	r Q	s e	s @r z
mic-	ro-	sco-	pic
m aI k	r V s	k Q	p I k
mic-	ro-	sco-	pical-	ly
m aI k	r V s	k Q	p I k	l i:
mic-	ro-	sco-	py
m aI k	r V s	k V	p i:
mic-	ro-	scope
m aI k	r V s	k @U p
mic-	ro-	scopes
m aI k	r V s	k @U p s
mic-	ro-	soft
m aI k	r @U	s O: f t
mic-	ro-	soft's
m aI k	r @U	s O: f t s
mic-	ro-	sys-	tems
m aI k	r @U	s I s	t V m z
mic-	ro-	tu-	bules
m aI k	r @U	t u: b	j u: l z
mic-	ro-	vax
m aI k	r @U	v { k s
mic-	ro-	wa-	va-	ble
m aI k	r @U	w eI	v V	b V l
mic-	ro-	wave
m aI k	r V	w eI v
mic-	ro-	waved
m aI k	r @U	w eI v d
mic-	ro-	waves
m aI k	r @U	w eI v z
mic-	robe
m aI k	r @U b
mic-	robes
m aI k	r @U b z
mic-	ron
m aI k	r Q n
mic-	rons
m aI k	r Q n z
mic-	ron's
m aI k	r Q n z
mic-	ros
m aI k	r @U z
mic-	ro's
m aI k	r @U z
mice
m aI s
mich
m I tS
miche-	ner
m I tS	n @r
miche-	ner's
m I tS	n @r z
mick
m I k
mick-	ler
m I k	l @r
mid
m I d
mid-	af-	ter-	noon
m I	d { f	t @r	n u: n
mid-	course
m I d	k O@ s
mid-	d-	ling
m I	d V	l I N
mid-	day
m I d	d eI
mid-	den-	dorf
m I	d V n	d O@ f
mid-	dle
m I	d V l
mid-	dle-	brook
m I	d V l	b r U k
mid-	dle-	bu-	ry
m I	d V l	b e@	i:
mid-	dle-	burg
m I	d V l	b @r g
mid-	dle-	class
m I	d V l	k l { s
mid-	dle-	man
m I	d V l	m { n
mid-	dle-	men
m I	d V l	m e n
mid-	dle-	sex
m I	d V l	s e k s
mid-	dle-	sworth
m I	d V l	z w @r T
mid-	dle-	ton
m I	d V l	t V n
mid-	dle-	town
m I	d V l	t aU n
mid-	dle-	weight
m I	d V l	w eI t
mid-	eas-	tern
m I	d i: s	t @r n
mid-	le-	vel
m I d	l V	v V l
mid-	life
m I d	l aI f
mid-	line
m I d	l aI n
mid-	mor-	ning
m I d	m O@	n I N
mid-	night
m I d	n aI t
mid-	point
m I d	p OI n t
mid-	range
m I d	r eI n dZ
mid-	rib
m I d	r I b
mid-	sea-	son
m I d	s i:	z V n
mid-	sec-	tion
m I d	s e k	S V n
mid-	ship-	man
m I d	S I p	m V n
mid-	ship-	man's
m I d	S I p	m V n z
mid-	ship-	men
m I d	S I p	m e n
mid-	size
m I d	s aI z
mid-	sized
m I d	s aI z d
mid-	stream
m I d	s t r i: m
mid-	sum-	mer
m I d	s V	m @r
mid-	term
m I d	t @r m
mid-	terms
m I d	t @r m z
mid-	town
m I d	t aU n
mid-	way
m I d	w eI
mid-	way's
m I d	w eI z
mid-	week
m I d	w i: k
mid-	wes-	ter-	ner
m I d	w e s	t @r	n @r
mid-	wes-	ter-	ners
m V d	w e s	t @r	n @r z
mid-	wes-	tern
m V d	w e s	t @r n
mid-	west
m I d	w e s t
mid-	west's
m I d	w e s t s
mid-	wi-	fe-	ry
m I d	w aI	f @r	i:
mid-	wife
m I d	w aI f
mid-	win-	ter
m I d	w I n	t @r
mid-	win-	ter's
m I d	w I n	t @r z
mid-	wives
m I d	w aI v z
mid-	year
m I d	j I@
midst
m I d s t
mien
m i: n
mies
m aI z
miff-	lin
m I f	l I n
miffed
m I f t
mig
m I g
mig-	non
m I g	n V n
mig-	nons
m I g	n V n z
migh-	ti-	er
m aI	t i:	@r
migh-	ti-	est
m aI	t i:	V s t
migh-	ti-	ly
m aI	t I	l i:
migh-	tn't
m aI	t V n t
migh-	ty
m aI	t i:
might
m aI t
might-	have-	been
m aI	t V v	b I n
migs
m I g z
mik-	va
m I k	v V
mike
m aI k
mikes
m aI k s
mike's
m aI k s
mil
m I l
mil-	bank
m I l	b { N k
mil-	burn
m I l	b @r n
mil-	d-	rid
m I l	d @r	I d
mil-	der
m aI l	d @r
mil-	dest
m aI l	d V s t
mil-	dew
m I l	d u:
mil-	dews
m I l	d u: z
mil-	dred
m I l	d r V d
mil-	ford
m I l	f @r d
mil-	hous
m I l	h aU s
mil-	ken
m I l	k V n
mil-	ken's
m I l	k V n z
mil-	king
m I l	k I N
mil-	ko
m I l	k @U
mil-	ky
m I l	k i:
mil-	lage
m I	l I dZ
mil-	lan
m I	l V n
mil-	lar
m I	l @r
mil-	lard
m I	l @r d
mil-	lard's
m I	l @r d z
mil-	lay
m I	l eI
mil-	len
m I	l V n
mil-	len-	ni-	a
m V	l e	n i:	V
mil-	len-	ni-	al
m V	l e	n i:	V l
mil-	len-	ni-	um
m V	l e	n i:	V m
mil-	len-	ni-	ums
m V	l e	n i:	V m z
mil-	ler
m I	l @r
mil-	lers
m I	l @r z
mil-	ler's
m I	l @r z
mil-	let
m I	l V t
mil-	lets
m I	l V t s
mil-	li
m I	l i:
mil-	li-	bar
m I	l I	b Q@
mil-	li-	can
m I	l I	k V n
mil-	li-	cent
m I	l I	s e n t
mil-	li-	gal
m I	l I	g V l
mil-	li-	gan
m I	l I	g V n
mil-	li-	gram
m I	l I g	r { m
mil-	li-	grams
m I	l I g	r { m z
mil-	li-	kan
m I	l I	k V n
mil-	li-	ken
m I	l I	k V n
mil-	li-	li-	ter
m I	l I	l i:	t @r
mil-	li-	li-	ters
m I	l I	l i:	t @r z
mil-	li-	me-	ter
m I	l I	m i:	t @r
mil-	li-	me-	ters
m I	l I	m i:	t @r z
mil-	li-	ner
m I	l I	n @r
mil-	li-	se-	cond
m I	l I	s e	k V n d
mil-	li-	se-	conds
m I	l I	s e	k V n d z
mil-	li-	sent
m I	l I	s e n t
mil-	lie
m I	l i:
mil-	ling
m I	l I N
mil-	ling-	ton
m I	l I N	t V n
mil-	lio-	naire
m I l	j V	n e@
mil-	lio-	naires
m I l	j V	n e@ z
mil-	lio-	naire's
m I l	j V	n e@ z
mil-	lion
m I l	j V n
mil-	lions
m I l	j V n z
mil-	lionth
m I l	j V n T
mil-	lionths
m I l	j V n t T s
mil-	lis
m I	l I s
mil-	lon
m I	l V n
mil-	ly
m I	l i:
mil-	man
m I l	m V n
mil-	ner
m I l	n @r
mil-	pi-	tas
m I l	p i:	t V s
mil-	roy
m I l	r OI
mil-	son
m I l	s V n
mil-	stein
m I l	s t aI n
mil-	tie
m I	t i:
mil-	to-	nic
m I l	t Q	n I k
mil-	ton
m I l	t V n
mil-	wau-	kee
m I l	w O:	k i:
mil-	wau-	kee's
m I l	w O:	k i: z
milch
m I l tS
mild
m aI l d
mild-	ly
m aI l	d l i:
mile
m aI l
mile-	stone
m aI l	s t @U n
mile-	stones
m aI l	s t @U n z
miles
m aI l z
milk
m I l k
milk-	man
m I l	k m { n
milk-	shake
m I l	k S eI k
milk-	weed
m I l	k w i: d
milked
m I l k t
milks
m I l k s
mill
m I l
mill-	burn
m I l	b @r n
mill-	house
m I l	h aU s
mill-	man
m I l	m V n
mill-	sap
m I l	s { p
mill-	stone
m I l	s t @U n
mill-	ward
m I l	w @r d
mill-	wood
m I l	w U d
mille
m I l
milled
m I l d
mills
m I l z
mill's
m I l z
)"
R"(milne
m I l n
milnes
m I l n z
mils
m I l z
milt
m I l t
mim
m I m
mime
m aI m
mims
m I m z
min
m I n
min-	cer
m I n	s @r
min-	cing
m I n	s I N
min-	cy
m I n	s i:
min-	da
m I n	d V
min-	da-	nao
m I n	d V	n aU
min-	ded
m aI n	d V d
min-	ded-	ly
m aI n	d V d	l i:
min-	ded-	ness
m aI n	d V d	n V s
min-	del
m I n	d V l
min-	den
m aI n	d V n
min-	der
m aI n	d @r
min-	ding
m aI n	d I N
min-	dy
m I n	d i:
min-	g-	ling
m I N	g V	l I N
min-	ges
m I n	dZ V z
min-	gle
m I N	g V l
min-	gled
m I N	g V l d
min-	gles
m I N	g V l z
min-	go
m i: N	g @U
min-	gus
m I N	g V s
min-	na
m I	n V
min-	ne-	a-	po-	li-	s's
m I	n i:	{	p V	l V	s V z
min-	ne-	a-	po-	lis
m I	n i:	{	p V	l V s
min-	ne-	so-	ta
m I	n V	s @U	t V
min-	ne-	so-	tan
m I	n V	s @U	t V n
min-	ne-	so-	tans
m I	n V	s @U	t V n z
min-	ne-	so-	ta's
m I	n V	s @U	t V z
min-	ne-	ton-	ka
m I	n V	t O: N	k V
min-	nel-	li
m I	n e	l i:
min-	nick
m I	n I k
min-	nie
m I	n i:
min-	nie's
m I	n i: z
min-	nis
m I	n I s
min-	now
m I	n @U
min-	nows
m I	n @U z
min-	ny
m I	n i:
min-	ta
m I n	t V
min-	tage
m I n	t V dZ
min-	ted
m I n	t V d
min-	ter
m I n	t @r
min-	ti-	er
m I n	t i:	@r
min-	ting
m I n	t I N
min-	to
m I n	t @U
min-	ton
m I n	t V n
min-	turn
m I n	t @r n
mince
m I n s
mince-	meat
m I n	s m i: t
minced
m I n s t
minch
m I n tS
mind
m aI n d
mind-	bogg-	ling
m aI n	d b O: g	l I N
mind-	ful
m aI n	d f V l
mind-	less
m aI n	d l V s
mind-	less-	ly
m aI n	d l V s	l i:
mind-	set
m aI n	d s e t
minds
m aI n d z
mind's
m aI n d z
mine
m aI n
mine-	field
m aI n	f i: l d
mine-	fields
m aI n	f i: l d z
mine-	swee-	per
m aI n	s w i:	p @r
mine-	swee-	pers
m aI n	s w i:	p @r z
mine-	wor-	ker
m aI n	w @r	k @r
mine-	wor-	kers
m aI n	w @r	k @r z
mined
m aI n d
mines
m aI n z
mine's
m aI n z
ming
m I N
minge
m I n dZ
mings
m I N z
minh
m I n
mink
m I N k
minke
m I N k
minks
m I N k s
mins-	ky
m I n	s k i:
mins-	ter
m I n	s t @r
minsk
m I n s k
minst-	rel
m I n	s t r V l
minst-	rels
m I n	s t r V l z
mint
m I n t
mints
m I n t s
mint's
m I n t s
mintz
m I n t s
mips
m I p s
mir
m I@
mir-	ror
m I@	@r
mire
m aI r
mired
m aI r d
mis
m I s
mis-	be-	got-	ten
m I s	b V	g Q	t V n
mis-	be-	ha-	ving
m I s	b V	h eI	v I N
mis-	be-	ha-	vior
m I s	b V	h eI v	j @r
mis-	be-	have
m I s	b V	h eI v
mis-	be-	haved
m I s	b V	h eI v d
mis-	cal-	cu-	la-	ted
m I s	k { l	k j V	l eI	t V d
mis-	cal-	cu-	la-	tion
m I s	k { l	k j V	l eI	S V n
mis-	cal-	cu-	la-	tions
m I s	k { l	k j V	l eI	S V n z
mis-	cal-	cu-	late
m I s	k { l	k j V	l eI t
mis-	car-	ria-	ges
m I s	k e@	I	dZ V z
mis-	car-	riage
m I s	k e@	I dZ
mis-	cast
m I s	k { s t
mis-	cel-	la-	ne-	ous
m I	s V	l eI	n i:	V s
mis-	cel-	la-	ny
m I	s V	l eI	n i:
mis-	cha
m I	S V
mis-	cha-	rac-	te-	ri-	za-	tion
m I s	k {	r V k	t @r	V	z eI	S V n
mis-	cha-	rac-	te-	rize
m I s	k {	r V k	t @r	aI z
mis-	cha-	rac-	te-	rized
m I s	k {	r V k	t @r	aI z d
mis-	char-	ges
m I s	tS Q@	dZ V z
mis-	char-	ging
m I s	tS Q@	dZ I N
mis-	charge
m I s	tS Q@ dZ
mis-	charged
m I s	tS Q@ dZ d
mis-	chie-	vous
m I s	tS I	v V s
mis-	chief
m I s	tS I f
mis-	com-	mu-	ni-	ca-	tion
m I s	k V m	j u:	n I	k eI	S V n
mis-	con-	ceive
m I s	k V n	s i: v
mis-	con-	ceived
m I s	k V n	s i: v d
mis-	con-	cep-	tion
m I s	k V n	s e p	S V n
mis-	con-	cep-	tions
m I s	k V n	s e p	S V n z
mis-	con-	duct
m I s	k Q n	d V k t
mis-	con-	strue
m I s	k V n	s t r u:
mis-	con-	strued
m I s	k V n	s t r u: d
mis-	count
m I s	k aU n t
mis-	cre-	a-	tion
m I s	k r i:	eI	S V n
mis-	cre-	a-	tions
m I s	k r i:	eI	S V n z
mis-	cre-	ant
m I s	k r i:	V n t
mis-	cre-	ants
m I s	k r i:	V n t s
mis-	cue
m I s	k j u:
mis-	cues
m I s	k j u: z
mis-	de-	mea-	nor
m I s	d V	m i:	n @r
mis-	de-	mea-	nors
m I s	d V	m i:	n @r z
mis-	deed
m I s	d i: d
mis-	deeds
m I s	d i: d z
mis-	di-	ag-	no-	ses
m I s	d aI	I g	n @U	s i: z
mis-	di-	ag-	no-	sis
m I s	d aI	I g	n @U	s I s
mis-	di-	ag-	nose
m I s	d aI	I g	n @U s
mis-	di-	ag-	nosed
m I s	d aI	I g	n @U s t
mis-	di-	rec-	ted
m I s	d I@	e k	t V d
mis-	di-	rect
m I s	d I@	e k t
mis-	fi-	re
m I s	f aI	@r
mis-	fit
m I s	f I t
mis-	fits
m I s	f I t s
mis-	for-	tune
m I s	f O@	tS V n
mis-	for-	tunes
m I s	f O@	tS V n z
mis-	gi-	ving
m I s	g I	v I N
mis-	gi-	vings
m I s	g I	v I N z
mis-	give
m I s	g I v
mis-	go-	vern-	ment
m I s	g V	v @r n	m V n t
mis-	gui-	ded
m I s	g aI	d V d
mis-	guide
m I s	g aI d
mis-	im-	pres-	sion
m I	s I m	p r e	S V n
mis-	in-	for-	ma-	tion
m I	s I n	f @r	m eI	S V n
mis-	in-	for-	ming
m I	s I n	f O@	m I N
mis-	in-	form
m I	s I n	f O@ m
mis-	in-	formed
m I	s I n	f O@ m d
mis-	in-	ter-	pre-	ta-	tion
m I	s I n	t @r p	r V	t eI	S V n
mis-	in-	ter-	pre-	ted
m I	s I n	t @r p	r V	t V d
mis-	in-	ter-	pre-	ting
m I	s I n	t @r p	r V	t I N
mis-	in-	ter-	pret
m I	s I n	t @r p	r e t
mis-	jud-	ges
m I s	dZ V	dZ V z
mis-	judg-	ment
m I s	dZ V dZ	m V n t
mis-	judg-	ments
m I s	dZ V dZ	m V n t s
mis-	judge
m I s	dZ V dZ
mis-	judged
m I s	dZ V dZ d
mis-	ki-	to
m I s	k i:	t @U
mis-	ki-	tos
m I s	k i:	t @U s
mis-	la-	be-	ling
m I s	l eI	b V	l I N
mis-	la-	bel
m I s	l eI	b V l
mis-	la-	beled
m I s	l eI	b V l d
mis-	laid
m I s	l eI d
mis-	lea-	ding
m I s	l i:	d I N
mis-	lea-	ding-	ly
m I s	l i:	d I N	l i:
mis-	lead
m I s	l i: d
mis-	leads
m I s	l i: d z
mis-	led
m I s	l e d
mis-	ma-	na-	ges
m I s	m {	n I	dZ V z
mis-	ma-	na-	ging
m I s	m {	n I	dZ I N
mis-	ma-	nage
m I s	m {	n I dZ
mis-	ma-	nage-	ment
m I s	m {	n I dZ	m V n t
mis-	ma-	naged
m I s	m {	n I dZ d
mis-	mat-	ches
m I s	m {	tS V z
mis-	match
m I s	m { tS
mis-	matched
m I s	m { tS t
mis-	no-	mer
m I s	n @U	m @r
mis-	per-	ceive
m I s	p @r	s i: v
mis-	per-	ceives
m I s	p @r	s i: v z
mis-	per-	cep-	tion
m I s	p @r	s e p	S V n
mis-	per-	cep-	tions
m I s	p @r	s e p	S V n z
mis-	place
m I s	p l eI s
mis-	placed
m I s	p l eI s t
mis-	pri-	sion
m I s	p r I	Z V n
mis-	price
m I s	p r aI s
mis-	priced
m I s	p r aI s t
mis-	print
m I s	p r I n t
mis-	pro-	nounce
m I s	p r V	n aU n s
mis-	pro-	nounced
m I s	p r V	n aU n s t
mis-	quo-	ted
m I s	k w @U	t V d
mis-	quote
m I s	k w @U t
mis-	re-	mem-	ber
m I s	r i:	m e m	b @r
mis-	re-	mem-	bered
m I s	r i:	m e m	b @r d
mis-	re-	por-	ted
m I s	r V	p O@	t V d
mis-	re-	port
m I s	r V	p O@ t
mis-	re-	pre-	sen-	ta-	tion
m I s	r e p	r V	z e n	t eI	S V n
mis-	re-	pre-	sen-	ta-	tions
m I s	r e p	r V	z e n	t eI	S V n z
mis-	re-	pre-	sen-	ted
m I s	r e p	r V	z e n	t V d
mis-	re-	pre-	sen-	ting
m I s	r e p	r V	z e n	t I N
mis-	re-	pre-	sent
m I s	r e p	r V	z e n t
mis-	re-	pre-	sents
m I s	r e p	r V	z e n t s
mis-	rea-	ding
m I s	r i:	d I N
mis-	read
m I s	r i: d
mis-	rule
m I s	r u: l
mis-	sal
m I	s V l
mis-	sel
m I	s V l
mis-	ses
m I	s V z
mis-	sha-	pen
m I s	S eI	p V n
mis-	sie
m I	s i:
mis-	sile
m I	s V l
mis-	siles
m I	s V l z
mis-	sile's
m I	s V l z
mis-	sing
m I	s I N
mis-	sio-	na-	ries
m I	S V	n e@	i: z
mis-	sio-	na-	ry
m I	S V	n e@	i:
mis-	sion
m I	S V n
mis-	sions
m I	S V n z
mis-	sion's
m I	S V n z
mis-	sis-	sau-	ga
m I	s I	s O:	g V
mis-	sis-	sip-	pi
m I	s I	s I	p i:
mis-	sis-	sip-	pi-	an
m I	s I	s I	p i:	V n
mis-	sis-	sip-	pi-	ans
m I	s I	s I	p i:	V n z
mis-	sis-	sip-	pi's
m I	s I	s I	p i: z
mis-	sive
m I	s I v
mis-	sou-	la
m I	z u:	l V
mis-	sou-	ri
m V	z U@	i:
mis-	sou-	ri's
m V	z U@	i: z
mis-	speak
m I s	s p i: k
mis-	spel-	ling
m I s	s p e	l I N
mis-	spell
m I s	s p e l
mis-	spelled
m I s	s p e l d
mis-	ta-	king
m I s	t eI	k I N
mis-	takes
m I s	t eI k s
mis-	ter
m I s	t @r
mis-	ters
m I s	t @r z
mis-	tic
m I s	t I k
mis-	took
m I s	t U k
mis-	ty
m I s	t i:
mis-	un-	der-	stan-	ding
m I	s V n	d @r s	t { n	d I N
mis-	un-	der-	stan-	dings
m I	s V n	d @r s	t { n	d I N z
mis-	un-	der-	stand
m I	s V n	d @r s	t { n d
mis-	un-	der-	stands
m I	s V n	d @r s	t { n d z
mis-	un-	der-	stood
m I	s V n	d @r s	t U d
misch
m I S
mish-	mash
m I S	m { S
miss
m I s
missed
m I s t
mist-	ral
m I s	t r V l
mist-	rea-	ted
m I s	t r i:	t V d
mist-	rea-	ting
m I s	t r i:	t I N
mist-	reat
m I s	t r i: t
mist-	reat-	ment
m I s	t r i: t	m V n t
mist-	reats
m I s	t r i: t s
mist-	res-	ses
m I s	t r V	s V z
mist-	ress
m I s	t r V s
mist-	ri-	al
m I s	t r aI	V l
mist-	ri-	als
m I s	t r aI	V l z
mist-	rus-	ted
m I s	t r V s	t V d
mist-	rust
m I s	t r V s t
mist-	rust-	ful
m I s	t r V s	t f V l
mist-	ry
m I s	t r i:
mists
m I s t s
mit-	chel
m I	tS V l
mit-	chell
m I	tS V l
mit-	chell's
m I	tS V l z
mit-	chum
m I	tS V m
mit-	man
m I t	m V n
mit-	ra
m I t	r V
mit-	ral
m aI t	r V l
mit-	re
m I t	r i:
mit-	te-	leu-	ro-	pa
m I	t e	l u:	r @U	p V
mit-	ten
m I	t V n
mit-	tens
m I	t V n z
mit-	ter-	rand
m i:	t @r	O: n d
mit-	ter-	rand's
m i:	t @r	{ n d z
mit-	zi
m I t	s i:
mitch
m I tS
mite
m aI t
mites
m aI t s
mith-	ri-	date
m I T	r I	d eI t
mith-	ri-	dates
m I T	r I	d eI t s
mitt
m I t
mitts
m I t s
mitz-	vah
m I t	s v V
mix
m I k s
mix-	ture
m I k	s tS @r
mix-	tures
m I k	s tS @r z
mix-	up
m I k	s V p
mixed
m I k s t
miz-	ra-	hi
m i: z	r Q	h i:
mize
m aI z
mne-	mo-	nic
n V	m Q	n I k
mne-	mo-	nics
n V	m Q	n I k s
mo
m @U
mo-	ab
m @U	{ b
mo-	ber-	ly
m @U	b @r	l i:
mo-	berg
m @U	b @r g
mo-	bi-	li-	a
m @U	b i:	l i:	V
mo-	bi-	li-	ty
m @U	b I	l I	t i:
mo-	bi-	li-	za-	tion
m @U	b I	l I	z eI	S V n
mo-	bi-	li-	za-	tions
m @U	b I	l I	z eI	S V n z
mo-	bi-	li-	zer
m @U	b I	l aI	z @r
mo-	bi-	li-	zers
m @U	b I	l aI	z @r z
mo-	bi-	li-	zing
m @U	b I	l aI	z I N
mo-	bi-	lize
m @U	b I	l aI z
mo-	bi-	lized
m @U	b I	l aI z d
mo-	bi-	us
m @U	b i:	V s
mo-	bil
m @U	b I l
mo-	bile
m @U	b I l
mo-	biles
m @U	b I l z
mo-	bile's
m @U	b I l z
mo-	bil's
m @U	b I l z
mo-	bu-	tu
m @U b	j u:	t u:
mo-	bu-	tu's
m @U b	j u:	t u: z
mo-	by
m @U	b i:
mo-	ca
m @U	k V
mo-	cha
m @U	k V
mo-	chel
m Q	k V l
mo-	da-	li-	ties
m V	d {	l V	t i: z
mo-	da-	li-	ty
m V	d {	l V	t i:
mo-	dal
m @U	d V l
mo-	de-	ling
m Q	d V	l I N
mo-	de-	na
m @U	d e	n V
mo-	de-	ra-	ted
m Q	d @r	eI	t V d
mo-	de-	ra-	ting
m Q	d @r	eI	t I N
mo-	de-	ra-	tion
m Q	d @r	eI	S V n
mo-	de-	ra-	tor
m Q	d @r	eI	t @r
mo-	de-	ra-	tors
m Q	d @r	eI	t @r z
mo-	de-	rate
m Q	d @r	V t
mo-	de-	rate-	ly
m Q	d @r	V t	l i:
mo-	de-	rates
m Q	d @r	V t s
mo-	del
m Q	d V l
mo-	deled
m Q	d V l d
mo-	dels
m Q	d V l z
mo-	del's
m Q	d V l z
mo-	dem
m @U	d V m
mo-	dems
m @U	d V m z
mo-	der
m @U	d @r
mo-	der-	ni-	sm
m Q	d @r	n I	z V m
mo-	der-	ni-	ty
m Q	d @r	n I	t i:
mo-	der-	ni-	za-	tion
m Q	d @r	n I	z eI	S V n
mo-	der-	ni-	zing
m Q	d @r	n aI	z I N
mo-	der-	nist
m Q	d @r	n I s t
mo-	der-	nists
m Q	d @r	n I s t s
mo-	der-	nize
m Q	d @r	n aI z
mo-	der-	nized
m Q	d @r	n aI z d
mo-	dern
m Q	d @r n
mo-	derns
m Q	d @r n z
mo-	des-	ta
m @U	d e s	t V
mo-	des-	ti-	ne
m @U	d e s	t i:	n i:
mo-	des-	tia
m @U	d e s	t j V
mo-	des-	to
m @U	d e s	t @U
mo-	des-	ty
m Q	d V s	t i:
mo-	dest
m Q	d V s t
mo-	dest-	ly
m Q	d V s	t l i:
mo-	di
m @U	d i:
mo-	di-	ca
m @U	d i:	k V
mo-	di-	cum
m Q	d I	k V m
mo-	di-	fi-	ca-	tion
m Q	d I	f I	k eI	S V n
mo-	di-	fi-	ca-	tions
m Q	d I	f I	k eI	S V n z
mo-	di-	fied
m Q	d I	f aI d
mo-	di-	fies
m Q	d I	f aI z
mo-	di-	fy
m Q	d I	f aI
mo-	di-	fy-	ing
m Q	d I	f aI	I N
mo-	di-	gli-	a-	ni
m @U	d I g	l i:	Q	n i:
mo-	du-	la-	ted
m O: dZ	j u:	l eI	t V d
mo-	du-	la-	tion
m Q	dZ V	l eI	S V n
mo-	du-	la-	tor
m Q	dZ V	l eI	t @r
mo-	du-	lar
m Q	dZ V	l @r
mo-	du-	late
m O: dZ	j u:	l eI t
mo-	dule
m Q	dZ u: l
mo-	dules
m Q	dZ u: l z
mo-	dus
m @U	d V s
mo-	dy
m @U	d i:
mo-	et
m @U	e t
mo-	ga-	di-	shu
m @U	g V	d i:	S u:
mo-	gan
m @U	g V n
mo-	gul
m @U	g V l
mo-	guls
m @U	g V l z
mo-	ha-	med
m @U	h Q	m e d
mo-	hair
m @U	h e@
mo-	ham-	mad
m @U	h Q	m e d
mo-	ham-	med
m @U	h {	m V d
mo-	har
m @U	h @r
mo-	hawk
m @U	h O: k
mo-	hawks
m @U	h O: k s
mo-	hi-	can
m @U	h i:	k V n
mo-	hi-	cans
m @U	h i:	k V n z
mo-	ja-	ve
m @U	h Q	v i:
mo-	jo
m @U	dZ @U
mo-	la
m @U	l V
mo-	las-	ses
m V	l {	s V z
mo-	le-	cu-	lar
m V	l e k	j V	l @r
mo-	le-	cule
m Q	l V k	j u: l
mo-	le-	cules
m Q	l V k	j u: l z
mo-	ler
m @U	l @r
mo-	les-	ta-	tion
m @U	l e s	t eI	S V n
mo-	les-	ted
m V	l e s	t V d
mo-	les-	ter
m V	l e s	t @r
mo-	les-	ters
m V	l e s	t @r z
mo-	les-	ting
m V	l e s	t I N
mo-	lest
m V	l e s t
mo-	lests
m V	l e s t s
mo-	li-	na
m V	l i:	n V
mo-	li-	no
m @U	l i:	n @U
mo-	liere
m @U l	j e@
mo-	line
m @U	l i: n
mo-	lo-	kai
m Q	l V	k aI
mo-	lo-	tov
m O:	l V	t Q f
mo-	ly
m @U	l i:
mo-	lyb-	de-	num
m V	l I b	d e	n V m
mo-	men-	ta-	ri-	ly
m @U	m V n	t e@	V	l i:
mo-	men-	ta-	ry
m @U	m V n	t e@	i:
mo-	men-	tous
m @U	m e n	t V s
mo-	men-	tum
m @U	m e n	t V m
mo-	ment
m @U	m V n t
mo-	ments
m @U	m V n t s
mo-	ment's
m @U	m V n t s
mo-	na
m @U	n V
mo-	na-	co
m Q	n V	k @U
mo-	na-	ghan
m Q	n V	h { n
mo-	na-	han
m Q	n V	h { n
mo-	nad
m @U	n { d
mo-	nad-	nock
m Q	n { d	n Q k
mo-	nar-	chies
m Q	n Q@	k i: z
mo-	nar-	chist
m Q	n Q@	k I s t
mo-	nar-	chists
m Q	n Q@	k I s t s
mo-	narch
m Q	n Q@ k
mo-	ne-	ta-	ri-	ly
m Q	n V	t @r	V	l i:
mo-	ne-	ta-	ri-	sm
m Q	n V	t @r	I	z V m
mo-	ne-	ta-	rist
m Q	n V	t @r	I s t
mo-	ne-	ta-	rists
m Q	n V	t @r	I s t s
mo-	ne-	ta-	ry
m Q	n V	t e@	i:
mo-	nell
m Q	n V l
mo-	nes-	sen
m @U	n V	s V n
mo-	net
m @U	n eI
mo-	net's
m @U	n eI z
mo-	nett
m Q	n e t
mo-	nette
m V	n e t
mo-	ney
m V	n i:
mo-	ney-	less
m V	n i:	l V s
mo-	ney-	ma-	ker
m V	n i:	m eI	k @r
mo-	ney-	ma-	kers
m V	n i:	m eI	k @r z
mo-	ney-	ma-	king
m V	n i:	m eI	k I N
mo-	neyed
m V	n i: d
mo-	neys
m V	n i: z
mo-	ney's
m V	n i: z
mo-	ni-	ca
m Q	n I	k V
mo-	ni-	ca's
m Q	n I	k V z
mo-	ni-	co
m @U	n i:	k @U
mo-	ni-	er
m @U	n i:	@r
mo-	ni-	ker
m Q	n I	k @r
mo-	ni-	kers
m Q	n I	k @r z
mo-	ni-	sm
m Q	n I	z V m
mo-	ni-	sms
m Q	n I	z V m z
mo-	ni-	to-	ring
m Q	n I	t @r	I N
mo-	ni-	tor
m Q	n I	t @r
mo-	ni-	tored
m Q	n I	t @r d
mo-	ni-	tors
m Q	n I	t @r z
mo-	nied
m V	n i: d
mo-	nies
m V	n i: z
mo-	nique
m @U	n i: k
mo-	niz
m Q	n I z
mo-	no
m @U	n @U
mo-	no-	car-	pic
m Q	n V	k Q@	p I k
mo-	no-	cle
m Q	n V	k V l
mo-	no-	cli-	nic
m Q	n V k	l I	n I k
mo-	no-	clo-	nal
m Q	n V k	l @U	n V l
mo-	no-	ga-	mous
m V	n Q	g V	m V s
mo-	no-	ga-	my
m V	n Q	g V	m i:
mo-	no-	gram
m Q	n V g	r { m
mo-	no-	grammed
m Q	n V g	r { m d
mo-	no-	graph
m Q	n V g	r { f
mo-	no-	hull
m Q	n V	h V l
mo-	no-	li-	thic
m Q	n V	l I	T I k
mo-	no-	lin-	gual
m Q	n V	l I N	g w V l
mo-	no-	lith
m Q	n V	l I T
mo-	no-	liths
m Q	n V	l I T s
mo-	no-	logue
m Q	n V	l O: g
mo-	no-	logues
m Q	n V	l O: g z
mo-	no-	mer
m Q	n V	m @r
mo-	no-	mers
m Q	n V	m @r z
mo-	no-	nu-	cle-	ar
m Q	n V	n u: k	l i:	@r
mo-	no-	pho-	nic
m Q	n V	f Q	n I k
mo-	no-	plane
m Q	n V p	l eI n
mo-	no-	planes
m Q	n V p	l eI n z
mo-	no-	po-	li-	za-	tion
m V	n Q	p V	l V	z eI	S V n
mo-	no-	po-	li-	zes
m V	n Q	p V	l aI	z V z
mo-	no-	po-	li-	zing
m V	n Q	p V	l aI	z I N
mo-	no-	po-	lies
m V	n Q	p V	l i: z
mo-	no-	po-	lis-	tic
m V	n Q	p V	l I s	t I k
mo-	no-	po-	list
m V	n Q	p V	l V s t
mo-	no-	po-	lize
m V	n Q	p V	l aI z
mo-	no-	po-	lized
m V	n Q	p V	l aI z d
mo-	no-	po-	ly
m V	n Q	p V	l i:
mo-	no-	pole
m Q	n V	p @U l
mo-	no-	poles
m Q	n V	p @U l z
mo-	no-	rail
m Q	n @r	eI l
mo-	no-	rails
m Q	n @r	eI l z
mo-	no-	sac-	cha-	ride
m Q	n V	s {	k @r	aI d
mo-	no-	the-	i-	sm
m Q	n V	T i:	I	z V m
mo-	no-	to-	nous
m V	n Q	t V	n V s
mo-	no-	to-	ny
m V	n Q	t V	n i:
mo-	no-	tone
m Q	n V	t @U n
mo-	no-	type
m Q	n V	t aI p
mo-	no-	va-	lent
m Q	n V	v eI	l V n t
mo-	no-	xide
m V	n Q k	s aI d
mo-	noch-	ro-	ma-	tic
m Q	n V k	r @U	m {	t I k
mo-	noch-	rome
m Q	n V k	r @U m
mo-	non-	ga-	he-	la
m V	n O: N	g V	h eI	l V
mo-	nu-	men-	tal
m Q n	j V	m e n	t V l
mo-	nu-	men-	tal-	ly
m Q n	j V	m e n	t V	l i:
mo-	nu-	ment
m Q n	j u:	m V n t
mo-	nu-	ments
m Q n	j V	m V n t s
mo-	ny
m @U	n i:
mo-	ping
m @U	p I N
mo-	pus
m @U	p V s
mo-	ra
m O@	V
mo-	ra-	ga
m O@	Q	g V
mo-	ra-	li-	sm
m O@	V	l I	z V m
mo-	ra-	li-	ty
m @r	{	l I	t i:
mo-	ra-	li-	zing
m O@	V	l aI	z I N
mo-	ra-	lis-	tic
m O@	V	l I s	t I k
mo-	ra-	list
m O@	V	l I s t
mo-	ra-	lists
m O@	V	l V s t s
mo-	ra-	lize
m O@	V	l aI z
mo-	ra-	to-	ri-	a
m O@	V	t O@	i:	V
mo-	ra-	to-	ri-	um
m O@	V	t O@	i:	V m
mo-	ra-	to-	ri-	ums
m O@	V	t O@	i:	V m z
mo-	ra-	vi-	an
m @r	eI	v i:	V n
mo-	rai-	nal
m @r	eI	n V l
mo-	raine
m @r	eI n
mo-	ral
m O@	V l
mo-	ral-	ly
m O@	V	l i:
mo-	rale
m @r	{ l
mo-	rales
m @r	{ l z
mo-	rals
m O@	V l z
mo-	ran
m @r	{ n
mo-	ran-	di
m O@	Q n	d i:
mo-	ras-	ses
m @r	{	s V z
mo-	rass
m @r	{ s
mo-	ray
m @r	eI
mo-	rays
m @r	eI z
mo-	re-	a
m O@	i:	V
)"
R"(mo-	re-	na
m O@	eI	n V
mo-	re-	no
m O@	i:	n @U
mo-	re-	ton
m O@	V	t Q n
mo-	reau
m @r	@U
mo-	reen
m O@	i: n
mo-	rel
m @r	e l
mo-	rel-	la
m O@	e	l V
mo-	rel-	lo
m @r	e	l @U
mo-	rell
m O@	V l
mo-	res
m O@	eI z
mo-	res-	co
m O@	e s	k @U
mo-	rey
m O@	i:
mo-	ri
m O@	i:
mo-	ri-	a
m O@	i:	V
mo-	ri-	ar-	ty
m O@	i:	Q@	t i:
mo-	ri-	bund
m O@	I	b V n d
mo-	ri-	ni
m O@	i:	n i:
mo-	ri-	son
m O@	I	s V n
mo-	ri-	ta
m O@	i:	t V
mo-	ric
m O@	I k
mo-	rice
m O@	I s
mo-	rin
m O@	I n
mo-	ritz
m O@	I t s
mo-	ro
m O@	@U
mo-	ro-	nes
m O@	@U	n e s
mo-	ro-	ni
m @r	@U	n i:
mo-	roc-	can
m @r	Q	k V n
mo-	roc-	cans
m @r	Q	k V n z
mo-	roc-	co
m @r	Q	k @U
mo-	ron
m O@	Q n
mo-	ros
m O@	@U z
mo-	rose
m @r	@U s
mo-	sa-	i-	cal
m @U	z eI	I	k V l
mo-	sa-	ic
m @U	z eI	I k
mo-	sa-	ics
m @U	z eI	I k s
mo-	sel
m @U	s V l
mo-	selle
m @U	z e l
mo-	ser
m @U	z @r
mo-	ses
m @U	z V s
mo-	sey
m @U	z i:
mo-	she
m @U	S e
mo-	sher
m @U	Z @r
mo-	she's
m @U	S e z
mo-	sier
m @U	Z @r
mo-	sul
m @U	s V l
mo-	ta
m @U	t V
mo-	tel
m @U	t e l
mo-	tels
m @U	t e l z
mo-	ten
m @U	t V n
mo-	the-	ring
m V	D @r	I N
mo-	ther
m V	D @r
mo-	ther-	hood
m V	D @r	h U d
mo-	ther-	land
m V	D @r	l { n d
mo-	ther-	less
m V	D @r	l V s
mo-	ther-	ly
m V	D @r	l i:
mo-	thers
m V	D @r z
mo-	ther's
m V	D @r z
mo-	thers-	in-	law
m V	D @r	z I n	l O:
mo-	ti-	li-	ty
m @U	t I	l I	t i:
mo-	ti-	va-	ted
m @U	t I	v eI	t V d
mo-	ti-	va-	ting
m @U	t I	v eI	t I N
mo-	ti-	va-	tio-	nal
m @U	t I	v eI	S V	n V l
mo-	ti-	va-	tion
m @U	t I	v eI	S V n
mo-	ti-	va-	tions
m @U	t I	v eI	S V n z
mo-	ti-	va-	tor
m @U	t I	v eI	t @r
mo-	ti-	vate
m @U	t I	v eI t
mo-	ti-	vates
m @U	t I	v eI t s
mo-	tif
m @U	t i: f
mo-	tifs
m @U	t i: f s
mo-	tile
m @U	t I l
mo-	tio-	ning
m @U	S V	n I N
mo-	tion
m @U	S V n
mo-	tion-	less
m @U	S V n	l e s
mo-	tioned
m @U	S V n d
mo-	tions
m @U	S V n z
mo-	tive
m @U	t I v
mo-	tives
m @U	t I v z
mo-	to
m @U	t @U
mo-	to-	ring
m @U	t @r	I N
mo-	to-	rist
m @U	t @r	I s t
mo-	to-	rists
m @U	t @r	I s t s
mo-	to-	rize
m @U	t @r	aI z
mo-	to-	rized
m @U	t @r	aI z d
mo-	to-	ro-	la
m @U	t @r	@U	l V
mo-	to-	ro-	la's
m @U	t @r	@U	l V z
mo-	ton
m @U	t @U n
mo-	tor
m @U	t @r
mo-	tor-	bike
m @U	t @r	b aI k
mo-	tor-	bikes
m @U	t @r	b aI k s
mo-	tor-	boat
m @U	t @r	b @U t
mo-	tor-	cade
m @U	t @r	k eI d
mo-	tor-	cades
m @U	t @r	k eI d z
mo-	tor-	car
m @U	t @r	k Q@
mo-	tor-	cars
m @U	t @r	k Q@ z
mo-	tor-	cy-	c-	list
m @U	t @r	s aI	k V	l V s t
mo-	tor-	cy-	c-	lists
m @U	t @r	s aI	k V	l V s t s
mo-	tor-	cy-	cle
m @U	t @r	s aI	k V l
mo-	tor-	cy-	cles
m @U	t @r	s aI	k V l z
mo-	tors
m @U	t @r z
mo-	tor's
m @U	t @r z
mo-	town
m @U	t aU n
mo-	town's
m @U	t aU n z
mo-	ty-	ka
m Q	t aI	k V
mo-	va-	ble
m u:	v V	b V l
mo-	ver
m u:	v @r
mo-	vers
m u:	v @r z
mo-	vie
m u:	v i:
mo-	vie-	go-	er
m u:	v i:	g @U	@r
mo-	vie-	go-	ers
m u:	v i:	g @U	@r z
mo-	vie-	go-	ing
m u:	v i:	g @U	I N
mo-	vie-	ma-	ker
m u:	v i:	m eI	k @r
mo-	vie-	ma-	kers
m u:	v i:	m eI	k @r z
mo-	vie-	ma-	king
m u:	v i:	m eI	k I N
mo-	vies
m u:	v i: z
mo-	vie's
m u:	v i: z
mo-	ving
m u:	v I N
mo-	ving-	ly
m u:	v I N	l i:
mo-	wer
m @U	@r
mo-	wers
m @U	@r z
mo-	wing
m aU	I N
mo-	xie
m Q k	s i:
mo-	ya
m OI	V
mo-	yer
m OI	@r
mo-	yers
m OI	@r z
mo-	yer's
m OI	@r z
mo-	zam-	bi-	can
m @U	z { m	b i:	k V n
mo-	zam-	bi-	cans
m @U	z { m	b i:	k V n z
mo-	zam-	bique
m @U	z { m	b i: k
mo-	zar-	te-	an
m @U	z Q@	t i:	V n
mo-	zart
m @U	z Q@ t
mo-	zart's
m @U	z Q@ t s
mo-	zelle
m V	z e l
moa-	ning
m @U	n I N
moan
m @U n
moaned
m @U n d
moans
m @U n z
moat
m @U t
moats
m @U t s
mob
m Q b
mob-	ley
m @U b	l i:
mob-	ster
m Q b	s t @r
mob-	sters
m Q b	s t @r z
mob-	ster's
m Q b	s t @r z
mobbed
m Q b d
mobs
m Q b z
mob's
m Q b z
moc-	ca-	sin
m Q	k V	s I n
moc-	ca-	sins
m Q	k V	s I n z
moc-	ke-	ry
m Q	k @r	i:
moc-	king
m Q	k I N
moc-	king-	bird
m Q	k I N	b @r d
moch
m Q k
mock
m Q k
mocked
m Q k t
mocks
m Q k s
mod
m O: d
mode
m @U d
modes
m @U d z
moe
m @U
moe-	bi-	us
m @U	b i:	V s
moen
m @U n
moes
m @U z
mof-	fat
m Q	f V t
mof-	fett
m Q	f e t
mof-	fit
m Q	f I t
mof-	fitt
m Q	f I t
mohl
m @U l
mohn
m Q n
mohr
m O@
mohs
m Q s
moi
m w Q
moi-	na
m OI	n V
moi-	ra
m OI	r V
moi-	ses
m OI	z V z
moi-	she
m @U	S e
moines
m OI n z
moir
m OI r
mois-	ten
m OI	s V n
mois-	tened
m OI	s V n d
mois-	tu-	ri-	zer
m OI s	tS @r	aI	z @r
mois-	ture
m OI s	tS @r
moise
m OI z
moist
m OI s t
mok
m Q k
mokes
m @U k s
mol
m O: l
mol-	da-	ble
m @U l	d V	b V l
mol-	da-	vi-	a
m @U l	d eI	v i:	V
mol-	da-	vi-	an
m @U l	d eI	v i:	V n
mol-	ded
m @U l	d V d
mol-	der
m @U l	d @r
mol-	ders
m @U l	d @r z
mol-	ding
m @U l	d I N
mol-	dings
m @U l	d I N z
mol-	do-	va
m @U l	d @U	v V
mol-	do-	van
m @U l	d @U	v Q n
mol-	dy
m @U l	d i:
mol-	let
m Q	l e t
mol-	li-	fied
m Q	l I	f aI d
mol-	li-	fy
m Q	l I	f aI
mol-	lie
m Q	l i:
mol-	loy
m Q	l OI
mol-	lusk
m Q	l V s k
mol-	lusks
m Q	l V s k s
mol-	ly
m Q	l i:
mol-	ly-	cod-	dle
m Q	l i:	k Q	d V l
mol-	ly's
m Q	l i: z
mol-	nar
m @U l	n @r
mol-	ten
m @U l	t V n
mol-	ter
m @U l	t @r
mol-	ting
m @U l	t I N
mol-	ton
m @U l	t V n
mold
m @U l d
molds
m @U l d z
mole
m @U l
mole-	hill
m @U l	h I l
mole-	like
m @U l	l aI k
moles
m @U l z
moll
m Q l
molle
m Q l
molt
m @U l t
mom
m Q m
mom-	ba-	sa
m Q m	b Q	s V
mom-	ma
m Q	m V
mom-	mies
m Q	m i: z
mom-	my
m Q	m i:
mom-	my's
m Q	m i: z
moms
m Q m z
mom's
m Q m z
mon
m @U n
mon-	day
m V n	d i:
mon-	days
m V n	d i: z
mon-	day's
m V n	d i: z
mon-	do
m Q n	d @U
mon-	dri-	an
m Q n	d r i:	V n
mon-	fort
m Q n	f @r t
mon-	ge-	ring
m V N	g @r	I N
mon-	geau
m V N	g @U
mon-	ger
m V N	g @r
mon-	gers
m V N	g @r z
mon-	go-	li-	a
m Q N	g @U	l i:	V
mon-	go-	li-	an
m Q N	g @U	l i:	V n
mon-	go-	loid
m Q N	g V	l OI d
mon-	gol
m Q N	g V l
mon-	gols
m Q N	g V l z
mon-	goo-	ses
m Q N	g u:	s V z
mon-	goose
m Q N	g u: s
mon-	key
m V N	k i:
mon-	key-	ing
m V N	k i:	I N
mon-	key-	like
m V N	k i:	l aI k
mon-	keys
m V N	k i: z
mon-	mouth
m Q n	m V T
mon-	mouth's
m Q n	m V T s
mon-	real
m Q n	r V l
mon-	ro
m Q n	r @U
mon-	ro-	vi-	a
m Q n	r @U	v i:	V
mon-	roe
m V n	r @U
mon-	roe-	ville
m Q n	r @U	v I l
mon-	roe's
m V n	r @U z
mon-	roy
m Q n	r OI
mon-	san-	to
m Q n	s { n	t @U
mon-	san-	to's
m Q n	s { n	t @U z
mon-	sey
m Q n	z i:
mon-	sieur
m V s	j @r
mon-	sieurs
m V s	j @r z
mon-	sig-	nor
m Q n	s i: n	j @r
mon-	sig-	nors
m Q n	s i: n	j @r z
mon-	son
m Q n	s V n
mon-	soo-	nal
m Q n	s u:	n V l
mon-	soon
m Q n	s u: n
mon-	soons
m Q n	s u: n z
mon-	sour
m Q n	s @r
mon-	ster
m Q n	s t @r
mon-	sters
m Q n	s t @r z
mon-	stro-	si-	ty
m Q n	s t r Q	s I	t i:
mon-	strous
m Q n	s t r V s
mon-	ta-	gu
m Q n	t V g	j u:
mon-	ta-	gue
m Q n	t V g	j u:
mon-	ta-	gu's
m Q n	t V g	j u: z
mon-	ta-	na
m Q n	t {	n V
mon-	ta-	na-	ri
m @U n	t Q	n Q@	i:
mon-	ta-	nan
m Q n	t {	n V n
mon-	ta-	nans
m Q n	t {	n V n z
mon-	ta-	na's
m Q n	t {	n V z
mon-	ta-	nez
m @U n	t Q	n e z
mon-	tag-	na
m @U n	t Q g	n V
mon-	tage
m Q n	t Q Z
mon-	tagne
m V n	t eI n j
mon-	tal-	vo
m @U n	t Q l	v @U
mon-	te
m Q n	t i:
mon-	te-	fi-	o-	re
m Q n	t V	f i:	O@	i:
mon-	te-	go
m O: n	t i:	g @U
mon-	te-	neg-	ran
m Q n	t V	n eI g	r V n
mon-	te-	neg-	ro
m Q n	t V	n eI g	r @U
mon-	te-	neg-	ro's
m Q n	t V	n eI g	r @U z
mon-	te-	rey
m Q n	t @r	eI
mon-	te-	ro
m Q n	t e@	@U
mon-	te-	vi-	de-	o
m Q n	t V	v I	d i:	@U
mon-	te-	zu-	ma
m Q n	t V	z u:	m V
mon-	ter-	rey
m Q n	t @r	eI
mon-	tes
m Q n	t i: z
mon-	te's
m Q n	t i: z
mon-	tes-	so-	ri
m Q n	t V	s O@	i:
mon-	ti
m Q n	t i:
mon-	ti-	cel-	lo
m Q n	t I	s e	l @U
mon-	to-	ya
m Q n	t OI	V
mon-	ty
m O: n	t i:
mon-	zo-	nite
m Q n	z V	n aI t
monde
m Q n d
mone
m @U n
mong
m O: N
monge
m Q n dZ
monk
m V N k
monks
m V N k s
monk's
m V N k s
mont
m Q n t
mont-	clair
m Q n	t k l e@
mont-	ford
m V n	t f O@ d
mont-	fort
m Q n	t f @r t
mont-	gome-	ry
m Q n	t g V m	r i:
mont-	gome-	ry's
m Q n	t g V m	r i: z
mont-	joy
m Q n	t dZ OI
mont-	pe-	li-	er
m Q n	t p i:	l i:	@r
mont-	pe-	li-	er's
m Q n	t p i:	l i:	@r z
mont-	re-	al
m V n	t r i:	O: l
mont-	re-	al's
m Q n	t r i:	Q l z
mont-	rose
m Q n	t r @U z
mont-	ross
m @U n	t r @U s
month
m V n T
month-	long
m V n	T l O: N
month-	ly
m V n	T l i:
months
m V n T s
month's
m V n T s
monts
m Q n t s
moo-	dy
m u:	d i:
moo-	dy's
m u:	d i: z
moo-	ers
m u:	@r z
moo-	ney
m u:	n i:
moo-	nie
m u:	n i:
moo-	nies
m u:	n i: z
mood
m u: d
moods
m u: d z
moog
m u: g
mook
m U k
moon
m u: n
moon-	beam
m u: n	b i: m
moon-	ligh-	ting
m u: n	l aI	t I N
moon-	light
m u: n	l aI t
moon-	like
m u: n	l aI k
moon-	lit
m u: n	l I t
moon-	shine
m u: n	S aI n
moon-	stone
m u: n	s t @U n
moon-	struck
m u: n	s t r V k
moons
m u: n z
moon's
m u: n z
moose-	head
m u: s	h e d
moot
m u: t
moots
m u: t s
mop
m Q p
mop-	board
m Q p	b O@ d
mop-	ping
m Q	p I N
mope
m @U p
mopped
m Q p t
mops
m Q p s
mor
m O@
mor-	bi-	di-	ty
m O@	b I	d I	t i:
mor-	bid
m O@	b I d
mor-	dant
m O@	d V n t
mor-	de-	cai
m O@	d V	k aI
mor-	ga
m O@	g V
mor-	ga-	na
m O@	g {	n V
mor-	gan
m O@	g V n
mor-	gan-	town
m O@	g V n	t aU n
mor-	gans
m O@	g V n z
mor-	gan's
m O@	g V n z
mor-	gen
m O@	g V n
mor-	gen-	stern
m O@	g V n	s t @r n
mor-	gen-	tha-	ler
m O@	g V n	T V	l @r
mor-	gen-	thau
m O@	g V n	T aU
mor-	gun
m O@	g V n
mor-	land
m O@	l V n d
mor-	ley
m O@	l i:
mor-	mo-	ni-	sm
m O@	m V	n I	z V m
mor-	mon
m O@	m V n
mor-	mons
m O@	m V n z
mor-	na
m O@	n V
mor-	ning
m O@	n I N
mor-	ning-	star
m O@	n I N	s t Q@
mor-	nings
m O@	n I N z
mor-	ning's
m O@	n I N z
mor-	phew
m O@ f	j u:
mor-	phin
m O@	f I n
mor-	phine
m O@	f i: n
mor-	phing
m O@	f I N
mor-	pho-	ge-	ne-	sis
m O@	f V	dZ e	n V	s V s
mor-	pho-	lo-	gi-	cal
m O@	f V	l Q	dZ I	k V l
mor-	pho-	lo-	gy
m O@	f Q	l V	dZ i:
mor-	ra
m O@	V
mor-	rell
m O@	e l
mor-	ri-	son
m O@	I	s V n
mor-	ri-	son's
m O@	I	s V n z
mor-	ri-	s's
m O@	I	s V z
mor-	rie
m O@	i:
mor-	rill
m O@	i: l
mor-	ris
m O@	I s
mor-	ris-	sey
m O@	I	s i:
mor-	ris-	town
m O@	I s	t aU n
mor-	ris-	ville
m O@	I s	v I l
mor-	ris-	ville's
m O@	I s	v I l z
mor-	ro
m O@	@U
mor-	row
m Q@	@U
mor-	ry
m O@	i:
mor-	sel
m O@	s V l
mor-	sels
m O@	s V l z
mor-	ta-	li-	ty
m O@	t {	l I	t i:
mor-	tal
m O@	t V l
mor-	tal-	ly
m O@	t V	l i:
mor-	tals
m O@	t V l z
mor-	tar
m O@	t @r
mor-	tars
m O@	t @r z
mor-	tem
m O@	t V m
mor-	ten
m O@	t V n
mor-	ten-	sen
m O@	t V n	s V n
mor-	ti-	cian
m O@	t I	S V n
mor-	ti-	er
m O@	t i:	@r
mor-	ti-	fied
m O@	t I	f aI d
mor-	ti-	fy
m O@	t I	f aI
mor-	ti-	mer
m O@	t I	m @r
mor-	tie
m O@	t i:
mor-	tis
m O@	t I s
mor-	ton
m O@	t V n
mor-	ton's
m O@	t V n z
mor-	tu-	a-	ry
m O@	tS u:	e@	i:
mor-	ty
m O@	t i:
mor-	ven
m O@	v V n
mord
m O@ d
more
m O@
more-	head
m O@	h e d
more-	house
m O@	h aU s
more-	land
m O@	l V n d
more-	o-	ver
m O@	@U	v @r
morgue
m O@ g
morgues
m O@ g z
morph
m O@ f
morphs
m O@ f s
mor's
m O@ z
morse
m O@ s
mort
m O@ t
mort-	ga-	ges
m O@	g V	dZ V z
mort-	ga-	ge's
m O@	g I	dZ V z
mort-	ga-	ging
m O@	g I	dZ I N
mort-	gage
m O@	g I dZ
mort-	gaged
m O@	g I dZ d
mos-	ca
m @U s	k V
mos-	cow
m Q s	k @U
mos-	cow's
m O: s	k aU z
mos-	kow
m Q s	k @U
mos-	lem
m Q z	l V m
mos-	lems
m Q z	l V m z
mos-	ley
m @U z	l i:
mos-	qui-	to
m V s	k i:	t @U
mos-	qui-	toes
m V s	k i:	t @U z
mos-	qui-	tos
m V s	k i:	t @U z
mos-	sad
m @U	s { d
mos-	ser
m O:	s @r
mos-	ses
m O:	s V z
mos-	so
m @U	s @U
mose
m @U z
mose-	ley
m @U z	l i:
mosh
m O: S
mosk
m O: s k
mosque
m Q s k
mosques
m Q s k s
moss
m O: s
moss-	berg
m O: s	b @r g
moss-	like
m O: s	l aI k
moss-	man
m O: s	m V n
most
m @U s t
most-	ly
m @U s	t l i:
mosz-	kow-	ski
m Q s	k aU s	k i:
mot-	ley
m Q t	l i:
mot-	rin
m Q t	r I n
mot-	t-	ling
m Q	t V	l I N
mot-	tled
m Q	t V l d
mot-	to
m Q	t @U
mot-	tos
m Q	t @U z
mote
m @U t
motes
m @U t s
moth
m O: T
moth-	bal-	ling
m O: T	b O:	l I N
moth-	ball
m O: T	b O: l
moth-	balled
m O: T	b O: l d
moth-	balls
m O: T	b O: l z
moths
m O: T s
mots
m Q t s
mott
m Q t
motte
m Q t
motts
m Q t s
mott's
m Q t s
mou-	dy
m aU	d i:
mou-	lin
m u:	l { n
mou-	ser
m aU	z @r
mou-	sers
m aU	z @r z
mou-	thing
m aU	D I N
mou-	thy
m aU	T i:
moul
m aU l
moul-	den
m @U l	d V n
moul-	der
m @U l	d @r
moul-	ding
m @U l	d I N
moul-	dings
m @U l	d I N z
moul-	dy
m @U l	d i:
moul-	ton
m @U l	t V n
moul-	trie
m @U l	t r i:
mould
m @U l d
moulds
m @U l d z
moun-	tai-	neer
m aU n	t I	n I@
moun-	tai-	nous
m aU n	t I	n V s
moun-	tain
m aU n	t @ n
moun-	tain-	side
m aU n	t @ n	s aI d
moun-	tain-	sides
m aU n	t @ n	s aI d z
moun-	tain-	top
m aU n	t @ n	t Q p
moun-	tain-	tops
m aU n	t @ n	t Q p s
moun-	tains
m aU n	t @ n z
moun-	tain's
m aU n	t @ n z
moun-	ted
m aU n	t V d
moun-	ties
m aU n	t i: z
moun-	ting
m aU n	t I N
mound
m aU n d
mounds
m aU n d z
mount
m aU n t
mount-	ford
m u: n	t f O@ d
mount-	joy
m aU n	t dZ OI
mounts
m aU n t s
mour-	ner
m O@	n @r
mour-	ners
m O@	n @r z
mour-	ning
m O@	n I N
mourn
m O@ n
mourn-	ful
m O@ n	f V l
mourned
m O@ n d
mourns
m O@ n z
mous-	tache
m V s	t { S
mouse
m aU s
mouse-	hole
m aU s	h @U l
mouset-	rap
m aU s	t r { p
mousse
m u: s
mouth
m aU T
mouth-	ful
m aU T	f U l
mouth-	part
m aU T	p Q@ t
mouth-	parts
m aU T	p Q@ t s
mouth-	pie-	ces
m aU T	p i:	s V z
mouth-	piece
m aU T	p i: s
mouth-	wash
m aU T	w Q S
mouthed
m aU D d
mouths
m aU D z
move
m u: v
move-	ment
m u: v	m V n t
move-	ments
m u: v	m V n t s
move-	ment's
m u: v	m V n t s
moved
m u: v d
moves
m u: v z
mow
m @U
mow-	bray
m @U b	r eI
mowed
m @U d
mows
m aU z
moy
m OI
moy-	na
m OI	n V
moy-	na-	han
m OI	n V	h { n
moyl
m OI l
moyle
m OI l
ms
m I z
m's
e m z
mt
m aU n t
mu
m u:
mu-	ba-	rak
m u:	b Q@	I k
mu-	ba-	rak's
m u:	b Q@	I k s
mu-	co-	sa
m j u:	k @U	s V
mu-	co-	sal
m j u:	k @U	s V l
mu-	cous
m j u:	k V s
mu-	cus
m j u:	k V s
mu-	ga-	be
m u:	g Q	b eI
mu-	ga-	be's
m u:	g Q	b eI z
mu-	ham-	mad
m U	h Q	m V d
mu-	ham-	mad's
m U	h Q	m V d z
mu-	har-	ram
m V	h {	r V m
mu-	i
m u:	I
mu-	ja-	he-	deen
m u:	dZ V	h e	d i: n
mu-	ja-	hi-	deen
m u:	dZ V	h e	d i: n
mu-	lat-	to
m V	l Q	t @U
mu-	na-	fo
m u:	n Q	f @U
mu-	ni
m j u:	n i:
mu-	ni-	ci-	pa-	li-	ties
m j u:	n I	s I	p {	l I	t i: z
mu-	ni-	ci-	pa-	li-	ty
m j u:	n I	s I	p {	l I	t i:
mu-	ni-	ci-	pal
m j u:	n I	s I	p V l
mu-	ni-	ci-	pal-	ly
m j u:	n I	s I	p V	l i:
mu-	ni-	ci-	pals
m j u:	n I	s I	p V l z
mu-	ni-	tion
m j u:	n I	S V n
mu-	ni-	tions
m j u:	n I	S V n z
mu-	nich
m j u:	n I k
mu-	nich's
m j u:	n I k s
mu-	nis
m j u:	n I s
mu-	noz
m u: n	j @U z
mu-	ra
m U@	V
mu-	ral
m j U@	V l
mu-	rals
m j U@	V l z
mu-	sa
m j u:	s V
mu-	sc-	ling
m V	s V	l I N
mu-	scle
m V	s V l
mu-	scled
m V	s V l d
mu-	scles
m V	s V l z
mu-	se-	um
m j u:	z i:	V m
mu-	se-	ums
m j u:	z i:	V m z
mu-	se-	um's
m j u:	z i:	V m z
mu-	see
m j u:	z i:
mu-	ses
m j u:	z V z
mu-	sha
m j u:	S V
mu-	sher
m V	S @r
mu-	shers
m V	S @r z
mu-	shy
m V	S i:
mu-	si-	al
m j u:	z i:	V l
mu-	si-	ca
m j u:	z I	k V
mu-	si-	ca-	li-	ty
m j u:	z I	k {	l I	t i:
mu-	si-	cal
m j u:	z I	k V l
mu-	si-	cals
m j u:	z I	k V l z
mu-	si-	cian
m j u:	z I	S V n
mu-	si-	cian-	ship
m j u:	z I	S V n	S I p
mu-	si-	cians
m j u:	z I	S V n z
mu-	si-	cian's
m j u:	z I	S V n z
mu-	si-	co-	lo-	gist
m j u:	z I	k Q	l V	dZ V s t
mu-	sic
m j u:	z I k
mu-	sical-	ly
m j u:	z I k	l i:
mu-	sick
m j u:	s I k
mu-	sic's
m j u:	z I k s
mu-	sil
m u:	z I l
mu-	sing
m j u:	z I N
mu-	sings
m j u:	z I N z
mu-	stn't
m V	s V n t
mu-	ta-	gen
m j u:	t V	dZ e n
mu-	ta-	gens
m j u:	t V	dZ e n z
mu-	ta-	ted
m j u:	t eI	t V d
mu-	ta-	ting
m j u:	t eI	t I N
mu-	ta-	tion
m j u:	t eI	S V n
mu-	ta-	tions
m j u:	t eI	S V n z
mu-	tant
m j u:	t V n t
mu-	tants
m j u:	t V n t s
mu-	tate
m j u:	t eI t
mu-	ted
m j u:	t V d
mu-	ti
m u:	t i:
mu-	ti-	la-	ted
m j u:	t I	l eI	t I d
mu-	ti-	la-	ting
m j u:	t I	l eI	t I N
mu-	ti-	la-	tion
m j u:	t I	l eI	S V n
mu-	ti-	la-	tions
m j u:	t I	l eI	S V n z
mu-	ti-	late
m j u:	t I	l eI t
mu-	ti-	neer
m j u:	t I	n I@
mu-	ti-	neers
m j u:	t I	n I@ z
mu-	ti-	nied
m j u:	t I	n i: d
mu-	ti-	nies
m j u:	t I	n i: z
mu-	ti-	nous
m j u:	t I	n V s
mu-	ti-	ny
m j u:	t I	n i:
mu-	ting
m j u:	t I N
mu-	tu-	a-	li-	sm
m j u:	tS V	w V	l I	z V m
mu-	tu-	a-	li-	ty
m j u:	tS V	w {	l V	t i:
mu-	tu-	al
m j u:	tS V	w V l
mu-	tu-	al-	ly
m j u:	tS u:	V	l i:
mu-	zak
m j u:	z { k
mu-	zi-	o
m j u:	z i:	@U
muc-	king
m V	k I N
muc-	kle
m V	k V l
muc-	ky
m V	k i:
much
m V tS
muck
m V k
muck-	ra-	ker
m V k	r eI	k @r
muck-	ra-	king
m V k	r eI	k I N
muck-	rake
m V k	r eI k
mud
m V d
mud-	d-	ling
m V	d V	l I N
)"
R"(mud-	di-	er
m V	d i:	@r
mud-	died
m V	d i: d
mud-	dle
m V	d V l
mud-	dle-	hea-	ded
m V	d V l	h e	d V d
mud-	dled
m V	d V l d
mud-	dles
m V	d V l z
mud-	dy
m V	d i:
mud-	dy-	ing
m V	d i:	I N
mud-	ra
m V d	r V
mud-	slide
m V d	s l aI d
mud-	slides
m V d	s l aI d z
mud-	slin-	ging
m V d	s l I	N I N
mudd
m V d
mudge
m V dZ
muds
m V d z
muel-	ler
m j u:	l @r
muen-	chen
m j u: n	tS V n
muen-	ster
m j u: n	s t @r
muf-	fin
m V	f I n
muf-	fins
m V	f I n z
muf-	fle
m V	f V l
muf-	fled
m V	f V l d
muf-	fy
m V	f i:
muff
m V f
muff-	ler
m V f	l @r
muff-	lers
m V f	l @r z
muffs
m V f s
mug
m V g
mug-	ger
m V	g @r
mug-	gers
m V	g @r z
mug-	ging
m V	g I N
mug-	gings
m V	g I N z
mug-	gy
m V	g i:
mugged
m V g d
mugs
m V g z
muir
m j U@
muir-	head
m j U@	h e d
muk-	luk
m V k	l V k
mul-	ber-	ry
m V l	b e@	i:
mul-	ca-	hy
m V l	k eI	h i:
mul-	ches
m V l	tS V z
mul-	ching
m V l	tS I N
mul-	der
m V l	d @r
mul-	doon
m V l	d u: n
mul-	drow
m V l	d r aU
mul-	ford
m V l	f @r d
mul-	hall
m V l	h V l
mul-	house
m V l	h aU s
mul-	lah
m V	l V
)"