R"(com-	memo-	ra-	tive
kh V	m e m	r V	t I v
com-	men-	ces
kh V	m e n	s V z
com-	men-	cing
kh V	m e n	s I N
com-	men-	da-	ble
kh V	m e n	d V	b V l
com-	men-	da-	tion
kh Q	m V n	d eI	S V n
com-	men-	ded
kh V	m e n	d V d
com-	men-	ding
kh V	m e n	d I N
com-	men-	su-	rate
kh V	m e n	s @r	V t
com-	men-	su-	rate-	ly
kh V	m e n	s @r	V t	l i:
com-	men-	ta-	ries
kh Q	m V n	t e@	i: z
com-	men-	ta-	ry
kh Q	m V n	t e@	i:
com-	men-	ta-	tor
kh Q	m V n	t eI	t @r
com-	men-	ta-	tors
kh Q	m V n	t eI	t @r z
com-	men-	ta-	tor's
kh Q	m V n	t eI	t @r z
com-	men-	ted
kh Q	m e n	t V d
com-	men-	ter
kh Q	m e n	t @r
com-	men-	ters
kh Q	m e n	t @r z
com-	men-	ting
kh Q	m e n	t I N
com-	mence
kh V	m e n s
com-	mence-	ment
kh V	m e n	s m V n t
com-	menced
kh V	m e n s t
com-	mend
kh V	m e n d
com-	mends
kh V	m e n d z
com-	ment
kh Q	m e n t
com-	ments
kh Q	m e n t s
com-	mer-	ce's
kh Q	m @r	s V z
com-	mer-	cia-	li-	sm
kh V	m @r	S V	l I	z V m
com-	mer-	cia-	li-	za-	tion
kh V	m @r	S V	l V	z eI	S V n
com-	mer-	cia-	li-	zing
kh V	m @r	S V	l aI	z I N
com-	mer-	cia-	lize
kh V	m @r	S V	l aI z
com-	mer-	cia-	lized
kh V	m @r	S V	l aI z d
com-	mer-	cial
kh V	m @r	S V l
com-	mer-	cial-	ly
kh V	m @r	S V	l i:
com-	mer-	cials
kh V	m @r	S V l z
com-	merce
kh Q	m @r s
com-	mi-	se-	rate
kh V	m I	s @r	eI t
com-	mie
kh Q	m i:
com-	mies
kh Q	m i: z
com-	min-	g-	ling
kh Q	m I N	g V	l I N
com-	min-	gle
kh V	m I N	g V l
com-	min-	gled
kh Q	m I N	g V l d
com-	mis-	sa-	ries
kh Q	m I	s e@	i: z
com-	mis-	sa-	ry
kh Q	m I	s e@	i:
com-	mis-	sar
kh Q	m I	s Q@
com-	mis-	sars
kh Q	m I	s Q z
com-	mis-	sio-	ner
kh V	m I	S V	n @r
com-	mis-	sio-	ners
kh V	m I	S V	n @r z
com-	mis-	sio-	ner's
kh V	m I	S V	n @r z
com-	mis-	sio-	ning
kh V	m I	S V	n I N
com-	mis-	sion
kh V	m I	S V n
com-	mis-	sioned
kh V	m I	S V n d
com-	mis-	sions
kh V	m I	S V n z
com-	mis-	sion's
kh V	m I	S V n z
com-	mit
kh V	m I t
com-	mit-	ment
kh V	m I t	m V n t
com-	mit-	ments
kh V	m I t	m V n t s
com-	mit-	tal
kh V	m I	t V l
com-	mit-	ted
kh V	m I	t V d
com-	mit-	tee
kh V	m I	t i:
com-	mit-	tee-	man
kh V	m I	t i:	m V n
com-	mit-	tees
kh V	m I	t i: z
com-	mit-	tee's
kh V	m I	t i: z
com-	mit-	ting
kh V	m I	t I N
com-	mits
kh V	m I t s
com-	mo-	di-	ous
kh V	m @U	d i:	V s
com-	mo-	di-	ties
kh V	m Q	d V	t i: z
com-	mo-	di-	ty
kh V	m Q	d V	t i:
com-	mo-	di-	ty's
kh V	m Q	d V	t i: z
com-	mo-	dore
kh Q	m V	d O@
com-	mo-	dore's
kh Q	m V	d O@ z
com-	mo-	na-	li-	ties
kh Q	m V	n {	l V	t i: z
com-	mo-	na-	li-	ty
kh Q	m V	n {	l V	t i:
com-	mo-	ner
kh Q	m V	n @r
com-	mo-	ners
kh Q	m V	n @r z
com-	mo-	tion
kh V	m @U	S V n
com-	mode
kh V	m @U d
com-	mon
kh Q	m V n
com-	mon-	ly
kh Q	m V n	l i:
com-	mon-	place
kh Q	m V n	p l eI s
com-	mon-	sen-	si-	cal
kh Q	m V n	s e n	s V	k V l
com-	mon-	sense
kh Q	m V n	s e n s
com-	mon-	wealth
kh Q	m V n	w e l T
com-	mons
kh Q	m V n z
com-	mu-	nal
kh V m	j u:	n V l
com-	mu-	ni-	ca-	ble
kh V m	j u:	n V	k V	b V l
com-	mu-	ni-	ca-	ted
kh V m	j u:	n V	k eI	t V d
com-	mu-	ni-	ca-	ting
kh V m	j u:	n V	k eI	t I N
com-	mu-	ni-	ca-	tion
kh V m	j u:	n V	k eI	S V n
com-	mu-	ni-	ca-	tions
kh V m	j u:	n V	k eI	S V n z
com-	mu-	ni-	ca-	tion's
kh V m	j u:	n I	k eI	S V n z
com-	mu-	ni-	ca-	tive
kh V m	j u:	n V	k V	t I v
com-	mu-	ni-	ca-	tor
kh V m	j u:	n V	k eI	t @r
com-	mu-	ni-	ca-	tors
kh V m	j u:	n V	k eI	t @r z
com-	mu-	ni-	cate
kh V m	j u:	n V	k eI t
com-	mu-	ni-	cates
kh V m	j u:	n I	k eI t s
com-	mu-	ni-	que
kh V m	j u:	n V	k eI
com-	mu-	ni-	ques
kh V m	j u:	n I	k eI z
com-	mu-	ni-	sm
kh Q m	j U	n I	z V m
com-	mu-	ni-	sm's
kh Q m	j U	n I	z V m z
com-	mu-	ni-	ties
kh V m	j u:	n I	t i: z
com-	mu-	ni-	ty
kh V m	j u:	n I	t i:
com-	mu-	ni-	ty-	wide
kh V m	j u:	n I	t i:	w aI d
com-	mu-	ni-	ty's
kh V m	j u:	n I	t i: z
com-	mu-	ni-	za-	tion
kh Q m	j V	n I	z eI	S V n
com-	mu-	nion
kh V m	j u: n	j V n
com-	mu-	nist
kh Q m	j U	n I s t
com-	mu-	nists
kh Q m	j U	n I s t s
com-	mu-	nist's
kh Q m	j U	n I s t s
com-	mu-	nize
kh Q m	j V	n aI z
com-	mu-	ted
kh V m	j u:	t V d
com-	mu-	ter
kh V m	j u:	t @r
com-	mu-	ters
kh V m	j u:	t @r z
com-	mu-	ting
kh V m	j u:	t I N
com-	mune
kh Q m	j u: n
com-	munes
kh Q m	j u: n z
com-	mute
kh V m	j u: t
com-	mutes
kh V m	j u: t s
com-	pa-	ni-	a
kh V m	p eI	n i:	V
com-	pa-	nies
kh V m	p V	n i: z
com-	pa-	nion
kh V m	p { n	j V n
com-	pa-	nion-	ship
kh V m	p { n	j V n	S I p
com-	pa-	nion-	way
kh V m	p { n	j V n	w eI
com-	pa-	nions
kh V m	p { n	j V n z
com-	pa-	ny
kh V m	p V	n i:
com-	pa-	ny's
kh V m	p V	n i: z
com-	pa-	ra-	bi-	li-	ty
kh Q m	p @r	V	b I	l V	t i:
com-	pa-	ra-	ble
kh Q m	p @r	V	b V l
com-	pa-	ra-	bly
kh Q m	p @r	V b	l i:
com-	pa-	ra-	tive
kh V m	p e@	V	t I v
com-	pa-	ra-	tive-	ly
kh V m	p e@	V	t I v	l i:
com-	pa-	ra-	tor
kh V m	p @r	V	t @r
com-	pa-	ri-	son
kh V m	p e@	V	s V n
com-	pa-	ri-	sons
kh V m	p e@	V	s V n z
com-	pa-	ring
kh V m	p e@	I N
com-	pa-	ti-	bi-	li-	ty
kh V m	p {	t V	b I	l V	t i:
com-	pa-	ti-	ble
kh V m	p {	t V	b V l
com-	pa-	ti-	bles
kh V m	p {	t V	b V l z
com-	paq
kh Q m	p { k
com-	paq's
kh Q m	p { k s
com-	pare
kh V m	p e@
com-	pared
kh V m	p e@ d
com-	pares
kh V m	p e@ z
com-	part-	men-	ta-	lize
kh V m	p Q@ t	m e n	t V	l aI z
com-	part-	men-	ta-	lized
kh Q m	p Q@ t	m e n	t V	l aI z d
com-	part-	men-	tal
kh V m	p Q@ t	m e n	t V l
com-	part-	ment
kh V m	p Q@ t	m V n t
com-	part-	ments
kh V m	p Q@ t	m V n t s
com-	pas-	sio-	nate
kh V m	p {	S V	n V t
com-	pas-	sio-	nate-	ly
kh V m	p {	S V	n V t	l i:
com-	pas-	sion
kh V m	p {	S V n
com-	pass
kh V m	p V s
com-	pat-	ri-	ot
kh V m	p eI t	r i:	V t
com-	pat-	ri-	ots
kh V m	p eI t	r i:	V t s
com-	pe-	ted
kh V m	p i:	t V d
com-	pe-	ten-	cies
kh Q m	p V	t V n	s i: z
com-	pe-	ten-	cy
kh Q m	p V	t V n	s i:
com-	pe-	tence
kh Q m	p V	t V n s
com-	pe-	tent
kh Q m	p V	t V n t
com-	pe-	tent-	ly
kh Q m	p V	t V n	t l i:
com-	pe-	ti-	tion
kh Q m	p V	t I	S V n
com-	pe-	ti-	tions
kh Q m	p V	t I	S V n z
com-	pe-	ti-	tion's
kh Q m	p V	t I	S V n z
com-	pe-	ti-	tive
kh V m	p e	t V	t I v
com-	pe-	ti-	tive-	ly
kh V m	p e	t V	t I v	l i:
com-	pe-	ti-	tive-	ness
kh V m	p e	t V	t I v	n V s
com-	pe-	ti-	tor
kh V m	p e	t V	t @r
com-	pe-	ti-	tors
kh V m	p e	t V	t @r z
com-	pe-	ti-	tor's
kh V m	p e	t V	t @r z
com-	pe-	ting
kh V m	p i:	t I N
com-	pel
kh V m	p e l
com-	pel-	ling
kh V m	p e	l I N
com-	pel-	ling-	ly
kh V m	p e	l I N	l i:
com-	pelled
kh V m	p e l d
com-	pels
kh V m	p e l z
com-	pen-	di-	um
kh V m	p e n	d i:	V m
com-	pen-	sa-	ble
kh V m	p e n	s V	b V l
com-	pen-	sa-	ted
kh Q m	p V n	s eI	t V d
com-	pen-	sa-	ting
kh Q m	p V n	s eI	t I N
com-	pen-	sa-	tion
kh Q m	p V n	s eI	S V n
com-	pen-	sa-	tions
kh Q m	p V n	s eI	S V n z
com-	pen-	sa-	to-	ry
kh V m	p e n	s V	t O@	i:
com-	pen-	sate
kh Q m	p V n	s eI t
com-	pen-	sates
kh Q m	p V n	s eI t s
com-	pete
kh V m	p i: t
com-	petes
kh V m	p i: t s
com-	pi-	la-	tion
kh Q m	p I	l eI	S V n
com-	pi-	la-	tions
kh Q m	p I	l eI	S V n z
com-	pi-	ler
kh V m	p aI	l @r
com-	pi-	lers
kh V m	p aI	l @r z
com-	pi-	ling
kh V m	p aI	l I N
com-	pile
kh V m	p aI l
com-	piled
kh V m	p aI l d
com-	piles
kh V m	p aI l z
com-	pla-	cen-	cy
kh V m	p l eI	s V n	s i:
com-	pla-	cent
kh V m	p l eI	s V n t
com-	pla-	cent-	ly
kh V m	p l eI	s V n	t l i:
com-	plai-	nant
kh V m	p l eI	n V n t
com-	plai-	nants
kh V m	p l eI	n V n t s
com-	plai-	ner
kh V m	p l eI	n @r
com-	plai-	ners
kh Q m	p l eI	n @r z
com-	plai-	ning
kh V m	p l eI	n I N
com-	plai-	sant
kh V m	p l eI	s V n t
com-	plain
kh V m	p l eI n
com-	plained
kh V m	p l eI n d
com-	plains
kh V m	p l eI n z
com-	plaint
kh V m	p l eI n t
com-	plaints
kh V m	p l eI n t s
com-	po
kh Q m	p @U
com-	po-	nent
kh V m	p @U	n V n t
com-	po-	nents
kh V m	p @U	n V n t s
com-	po-	ser
kh V m	p @U	z @r
com-	po-	sers
kh V m	p @U	z @r z
com-	po-	ser's
kh V m	p @U	z @r z
com-	po-	ses
kh V m	p @U	z V z
com-	po-	si-	tio-	nal
kh Q m	p V	z I	S V	n V l
com-	po-	si-	tion
kh Q m	p V	z I	S V n
com-	po-	si-	tions
kh Q m	p V	z I	S V n z
com-	po-	sing
kh V m	p @U	z I N
com-	po-	site
kh V m	p Q	z I t
com-	po-	sites
kh V m	p Q	z I t s
com-	po-	sure
kh V m	p @U	Z @r
com-	port
kh V m	p O@ t
com-	port-	ment
kh V m	p O@ t	m V n t
com-	pos-	ting
kh Q m	p @U s	t I N
com-	pose
kh V m	p @U z
com-	posed
kh V m	p @U z d
com-	post
kh Q m	p @U s t
com-	pote
kh Q m	p @U t
com-	poun-	ded
kh V m	p aU n	d V d
com-	poun-	ding
kh V m	p aU n	d I N
com-	pound
kh Q m	p aU n d
com-	pounds
kh Q m	p aU n d z
com-	pre-	hen-	ded
kh Q m	p r V	h e n	d V d
com-	pre-	hen-	ding
kh Q m	p r V	h e n	d I N
com-	pre-	hen-	si-	bi-	li-	ty
kh Q m	p r i:	h e n	s I	b I	l I	t i:
com-	pre-	hen-	si-	ble
kh Q m	p r i:	h e n	s I	b V l
com-	pre-	hen-	sion
kh Q m	p r i:	h e n	S V n
com-	pre-	hen-	sive
kh Q m	p r i:	h e n	s I v
com-	pre-	hen-	sive-	ly
kh Q m	p r V	h e n	s I v	l i:
com-	pre-	hend
kh Q m	p r i:	h e n d
com-	pres-	ses
kh Q m	p r e	s V z
com-	pres-	sing
kh V m	p r e	s I N
com-	pres-	sion
kh V m	p r e	S V n
com-	pres-	sor
kh V m	p r e	s @r
com-	pres-	sors
kh V m	p r e	s @r z
com-	press
kh Q m	p r e s
com-	pressed
kh V m	p r e s t
com-	pri-	ses
kh V m	p r aI	z V z
com-	pri-	sing
kh V m	p r aI	z I N
com-	print
kh Q m	p r I n t
com-	prise
kh V m	p r aI z
com-	prised
kh V m	p r aI z d
com-	pro-	mi-	ser
kh Q m	p r V	m aI	z @r
com-	pro-	mi-	ses
kh Q m	p r V	m aI	z V z
com-	pro-	mi-	sing
kh Q m	p r V	m aI	z I N
com-	pro-	mise
kh Q m	p r V	m aI z
com-	pro-	mised
kh Q m	p r V	m aI z d
com-	pu-	serve
kh Q m	p j u:	s @r v
com-	pu-	serve's
kh Q m	p j u:	s @r v z
com-	pu-	ta-	tio-	nal
kh Q m	p j u:	t eI	S V	n V l
com-	pu-	ta-	tion
kh Q m	p j V	t eI	S V n
com-	pu-	ta-	tions
kh Q m	p j u:	t eI	S V n z
com-	pu-	te-	ri-	za-	tion
kh V m	p j u:	t @r	V	z eI	S V n
com-	pu-	te-	ri-	zing
kh V m	p j u:	t @r	aI	z I N
com-	pu-	te-	rize
kh V m	p j u:	t @r	aI z
com-	pu-	te-	rized
kh V m	p j u:	t @r	aI z d
com-	pu-	ted
kh V m	p j u:	t V d
com-	pu-	ter
kh V m	p j u:	t @r
com-	pu-	ter-	like
kh V m	p j u:	t @r	l aI k
com-	pu-	ters
kh V m	p j u:	t @r z
com-	pu-	ter's
kh V m	p j u:	t @r z
com-	pu-	ting
kh V m	p j u:	t I N
com-	pul-	sion
kh V m	p V l	S V n
com-	pul-	sions
kh V m	p U l	S V n z
com-	pul-	sive
kh V m	p V l	s I v
com-	pul-	sive-	ly
kh V m	p V l	s I v	l i:
com-	pul-	so-	ry
kh V m	p V l	s @r	i:
com-	punc-	tion
kh V m	p V N	k S V n
com-	pute
kh V m	p j u: t
com-	putes
kh V m	p j u: t s
com-	rade
kh Q m	r { d
com-	rades
kh Q m	r { d z
com-	sat
kh Q m	s { t
com-	sat's
kh Q m	s { t s
com-	stock
kh Q m	s t Q k
comb
kh @U m
combe
kh @U m
combed
kh @U m d
combes
kh @U m z
combs
kh @U m z
come
kh V m
come-	back
kh V m	b { k
come-	backs
kh V m	b { k s
come-	down
kh V m	d aU n
come-	ly
kh V m	l i:
come-	on
kh V	m Q n
comes
kh V m z
comf-	rey
kh V m	f r i:
comp
kh Q m p
comp-	le-	men-	ted
kh Q m	p l V	m e n	t V d
comp-	le-	men-	ting
kh Q m	p l V	m e n	t I N
comp-	le-	ment
kh Q m	p l V	m V n t
comp-	le-	menta-	ry
kh Q m	p l V	m e n	t r i:
comp-	le-	ments
kh Q m	p l V	m V n t s
comp-	le-	ted
kh V m	p l i:	t V d
comp-	le-	ting
kh V m	p l i:	t I N
comp-	le-	tion
kh V m	p l i:	S V n
comp-	le-	tions
kh V m	p l i:	S V n z
comp-	le-	xes
kh Q m	p l e k	s V z
comp-	le-	xi-	ties
kh V m	p l e k	s V	t i: z
comp-	le-	xi-	ty
kh V m	p l e k	s V	t i:
comp-	le-	xion
kh V m	p e k	S V n
comp-	le-	xions
kh V m	p e k	S V n z
comp-	lete
kh V m	p l i: t
comp-	lete-	ly
kh V m	p l i: t	l i:
comp-	lete-	ness
kh V m	p l i: t	n V s
comp-	letes
kh V m	p l i: t s
comp-	lex
kh Q m	p l e k s
comp-	li-	ance
kh V m	p l aI	V n s
comp-	li-	ant
kh V m	p l aI	V n t
comp-	li-	ca-	ted
kh Q m	p l I	k eI	t I d
comp-	li-	ca-	ting
kh Q m	p l I	k eI	t I N
comp-	li-	ca-	tion
kh Q m	p l I	k eI	S V n
comp-	li-	ca-	tions
kh Q m	p l V	k eI	S V n z
comp-	li-	cate
kh Q m	p l I	k eI t
comp-	li-	cates
kh Q m	p l I	k eI t s
comp-	li-	ci-	ty
kh V m	p l I	s V	t i:
comp-	li-	cit
kh V m	p l I	s V t
comp-	li-	men-	ta-	ry
kh Q m	p l I	m e n	t @r	i:
comp-	li-	men-	ted
kh Q m	p l I	m e n	t V d
comp-	li-	men-	ting
kh Q m	p l I	m e n	t I N
comp-	li-	ment
kh Q m	p l I	m e n t
comp-	li-	ments
kh Q m	p l I	m e n t s
comp-	lied
kh V m	p l aI d
comp-	lies
kh V m	p l aI z
comp-	ly
kh V m	p l aI
comp-	ly-	ing
kh V m	p l aI	I N
comp-	ton
kh Q m	p t V n
comp-	ton's
kh Q m	p t V n z
comp-	trol-	ler
kh V n	t r @U	l @r
comp-	trol-	ler's
kh V n	t r @U	l @r z
coms
kh Q m z
com's
kh Q m z
con
kh Q n
con-	ca-	te-	na-	tion
kh V n	k {	t V	n eI	S V n
con-	ca-	te-	nate
kh V n	k {	t V	n eI t
con-	can-	non
kh V n	k {	n V n
con-	cave
kh Q n	k eI v
con-	ce-	ded
kh V n	s i:	d V d
con-	ce-	ding
kh V n	s i:	d I N
con-	cea-	ling
kh V n	s i:	l I N
con-	ceal
kh V n	s i: l
con-	ceal-	ment
kh V n	s i: l	m V n t
con-	cealed
kh V n	s i: l d
con-	ceals
kh V n	s i: l z
con-	cede
kh V n	s i: d
con-	cedes
kh V n	s i: d z
con-	cei-	ted
kh V n	s i:	t V d
con-	cei-	va-	ble
kh V n	s i:	v V	b V l
con-	cei-	vab-	ly
kh V n	s i:	v V b	l i:
con-	cei-	ving
kh V n	s i:	v I N
con-	ceit
kh V n	s i: t
con-	ceive
kh V n	s i: v
con-	ceived
kh V n	s i: v d
con-	cent-	ra-	ted
kh O: n	s V n	t r eI	t V d
con-	cent-	ra-	ting
kh Q n	s V n	t r eI	t I N
con-	cent-	ra-	tion
kh Q n	s V n	t r eI	S V n
con-	cent-	ra-	tions
kh Q n	s V n	t r eI	S V n z
con-	cent-	rate
kh Q n	s V n	t r eI t
con-	cent-	rates
kh Q n	s V n	t r eI t s
con-	cent-	ric
kh V n	s e n	t r I k
con-	cep-	ci-	on
kh V n	s e p	s i:	@U n
con-	cep-	tion
kh V n	s e p	S V n
con-	cep-	tions
kh V n	s e p	S V n z
con-	cep-	tu-	al
kh V n	s e p	tS u:	V l
con-	cep-	tu-	al-	ly
kh V n	s e p	tS u:	V	l i:
con-	cep-	tua-	li-	za-	tion
kh V n	s e p	tS w V	l V	z eI	S V n
con-	cept
kh Q n	s e p t
con-	cepts
kh Q n	s e p t s
con-	cer-	ted
kh V n	s @r	t V d
con-	cer-	ti
kh V n	tS e@	t i:
con-	cer-	ti-	na
kh Q n	s @r	t i:	n V
con-	cer-	to
kh V n	tS e@	t @U
con-	cer-	tos
kh V n	tS e@	t @U z
con-	cern
kh V n	s @r n
con-	cern-	ing
kh V n	s @r	n I N
con-	cerned
kh V n	s @r n d
con-	cerns
kh V n	s @r n z
con-	cert
kh Q n	s @r t
con-	cert-	mas-	ter
kh Q n	s @r t	m { s	t @r
con-	certs
kh Q n	s @r t s
con-	ces-	sio-	na-	ry
kh V n	s e	S V	n e@	i:
con-	ces-	sio-	naire
kh V n	s e	S V	n e@
con-	ces-	sio-	nal
kh V n	s e	S V	n V l
con-	ces-	sion
kh V n	s e	S V n
con-	ces-	sions
kh V n	s e	S V n z
con-	cha
kh Q n	tS V
con-	chi-	ta
kh V n	tS i:	t V
con-	ci-	erge
kh Q n	s i:	e@ Z
con-	ci-	li-	a-	tion
kh V n	s I	l i:	eI	S V n
con-	ci-	li-	a-	to-	ry
kh V n	s I	l i:	V	t O@	i:
con-	ci-	li-	a-	tor
kh V n	s i:	l i:	eI	t @r
con-	ci-	li-	a-	tor's
kh V n	s I	l i:	eI	t @r z
con-	cise
kh V n	s aI s
con-	cise-	ly
kh V n	s aI s	l i:
con-	co-	mi-	tant
kh Q n	k Q	m I	t V n t
con-	co-	mi-	tant-	ly
kh Q n	k Q	m I	t V n	t l i:
con-	coc-	ted
kh V n	k Q k	t V d
con-	coc-	ting
kh V n	k Q k	t I N
con-	coc-	tion
kh V n	k Q k	S V n
con-	coc-	tions
kh V n	k Q k	S V n z
con-	coct
kh V n	k Q k t
con-	cord
kh Q n	k O@ d
con-	corde
kh Q n	k O@ d
con-	cord's
kh Q n	k O@ d z
con-	cour-	ses
kh Q n	k O@	s V z
con-	course
kh Q n	k O@ s
con-	crete
kh V n	k r i: t
con-	crete-	ly
kh Q n	k r i: t	l i:
con-	cu-	bi-	nage
kh Q n	k j u:	b I	n V dZ
con-	cu-	bine
kh Q n	k j V	b aI n
con-	cu-	bines
kh Q n	k j V	b aI n z
con-	cur
kh V n	k @r
con-	cur-	rence
kh V n	k @r	V n s
con-	cur-	rent
kh V n	k @r	V n t
con-	cur-	rent-	ly
kh V n	k @r	V n	t l i:
con-	cur-	ring
kh V n	k @r	I N
con-	curred
kh V n	k @r d
con-	curs
kh V n	k @r z
con-	cus-	sion
kh V n	k V	S V n
con-	cus-	sions
kh V n	k V	S V n z
con-	de-	scen-	ding
kh Q n	d V	s e n	d I N
con-	de-	scen-	sion
kh Q n	d V	s e n	S V n
con-	de-	scend
kh Q n	d V	s e n d
con-	dem-	na-	tion
kh Q n	d V m	n eI	S V n
con-	dem-	na-	tions
kh Q n	d V m	n eI	S V n z
con-	dem-	ning
kh V n	d e	m I N
con-	demn
kh V n	d e m
con-	demned
kh V n	d e m d
con-	demns
kh V n	d e m z
con-	den-	sa-	tion
kh Q n	d V n	s eI	S V n
con-	den-	sate
kh Q n	d V n	s eI t
con-	den-	sates
kh Q n	d V n	s eI t s
con-	den-	ser
kh V n	d e n	s @r
con-	den-	sing
kh V n	d e n	s I N
con-	dense
kh V n	d e n s
con-	densed
kh V n	d e n s t
con-	der
kh Q n	d @r
con-	di-	ment
kh Q n	d I	m V n t
con-	di-	ments
kh Q n	d I	m V n t s
con-	di-	tio-	na-	li-	ty
kh V n	d I	S V	n {	l V	t i:
con-	di-	tio-	nal
kh V n	d I	S V	n V l
con-	di-	tio-	nal-	ly
kh V n	d I	S V	n V	l i:
con-	di-	tio-	ner
kh V n	d I	S V	n @r
con-	di-	tio-	ners
kh V n	d I	S V	n @r z
con-	di-	tio-	ning
kh V n	d I	S V	n I N
)"
R"(con-	di-	tion
kh V n	d I	S V n
con-	di-	tioned
kh V n	d I	S V n d
con-	di-	tions
kh V n	d I	S V n z
con-	die
kh Q n	d i:
con-	dit
kh Q n	d I t
con-	do
kh Q n	d @U
con-	do-	len-	ces
kh V n	d @U	l V n	s V z
con-	do-	lence
kh V n	d @U	l V n s
con-	do-	mi-	ni-	um
kh Q n	d V	m I	n i:	V m
con-	do-	mi-	ni-	ums
kh Q n	d V	m I	n i:	V m z
con-	do-	ning
kh V n	d @U	n I N
con-	dom
kh Q n	d V m
con-	doms
kh Q n	d V m z
con-	don
kh Q n	d V n
con-	done
kh V n	d @U n
con-	doned
kh V n	d @U n d
con-	dones
kh V n	d @U n z
con-	dor
kh Q n	d @r
con-	dors
kh Q n	d @r z
con-	dos
kh Q n	d @U z
con-	du-	cive
kh V n	d u:	s I v
con-	du-	it
kh Q n	d u:	I t
con-	du-	its
kh Q n	d u:	I t s
con-	duc-	ted
kh V n	d V k	t V d
con-	duc-	ti-	vi-	ty
kh Q n	d V k	t I	v I	t i:
con-	duc-	ting
kh V n	d V k	t I N
con-	duc-	tion
kh V n	d V k	S V n
con-	duc-	tive
kh V n	d V k	t I v
con-	duc-	tor
kh V n	d V k	t @r
con-	duc-	tors
kh V n	d V k	t @r z
con-	duct
kh V n	d V k t
con-	ducts
kh V n	d V k t s
con-	fa-	bu-	la-	tion
kh V n	f { b	j V	l eI	S V n
con-	fe-	de-	ra-	cy
kh V n	f e	d @r	V	s i:
con-	fe-	de-	ra-	cy's
kh V n	f e	d @r	V	s i: z
con-	fe-	de-	ra-	tion
kh V n	f e	d @r	eI	S V n
con-	fe-	de-	rate
kh V n	f e	d @r	V t
con-	fe-	ree
kh Q n	f @r	i:
con-	fe-	rees
kh Q n	f @r	i: z
con-	fe-	ren-	ces
kh Q n	f @r	V n	s V z
con-	fe-	ren-	ce's
kh Q n	f @r	V n	s V z
con-	fe-	rence
kh Q n	f @r	V n s
con-	fec-	tio-	na-	ries
kh V n	f e k	S V	n e@	i: z
con-	fec-	tio-	na-	ry
kh V n	f e k	S V	n e@	i:
con-	fec-	tio-	ne-	ry
kh V n	f e k	S V	n e@	i:
con-	fec-	tio-	ner
kh V n	f e k	S V	n @r
con-	fec-	tio-	ners
kh V n	f e k	S V	n @r z
con-	fec-	tion
kh V n	f e k	S V n
con-	fec-	tions
kh V n	f e k	S V n z
con-	fect
kh V n	f e k t
con-	fer
kh V n	f @r
con-	fer-	ring
kh V n	f @r	I N
con-	ferred
kh V n	f @r d
con-	fers
kh V n	f @r z
con-	fes-	ses
kh V n	f e	s V z
con-	fes-	sing
kh V n	f e	s I N
con-	fes-	sio-	nal
kh V n	f e	S V	n V l
con-	fes-	sio-	nals
kh V n	f e	S V	n V l z
con-	fes-	sion
kh V n	f e	S V n
con-	fes-	sions
kh V n	f e	S V n z
con-	fess
kh V n	f e s
con-	fessed
kh V n	f e s t
con-	fet-	ti
kh V n	f e	t i:
con-	fi-	dant
kh Q n	f I	d Q n t
con-	fi-	dante
kh Q n	f I	d { n t
con-	fi-	dants
kh Q n	f I	d { n t s
con-	fi-	ded
kh V n	f aI	d V d
con-	fi-	den-	ces
kh Q n	f I	d V n	s V z
con-	fi-	den-	ce's
kh Q n	f I	d V n	s V z
con-	fi-	den-	ti-	a-	li-	ty
kh Q n	f I	d e n	S i:	{	l I	t i:
con-	fi-	den-	tial
kh Q n	f I	d e n	S V l
con-	fi-	den-	tial-	ly
kh Q n	f I	d e n	S V	l i:
con-	fi-	dence
kh Q n	f I	d V n s
con-	fi-	dent
kh Q n	f I	d V n t
con-	fi-	dent-	ly
kh Q n	f I	d V n	t l i:
con-	fi-	ding
kh V n	f aI	d I N
con-	fide
kh V n	f aI d
con-	fides
kh V n	f aI d z
con-	fine-	ment
kh V n	f aI n	m V n t
con-	firms
kh V n	f @r m z
con-	fis-	ca-	ted
kh Q n	f I s	k eI	t I d
con-	fis-	ca-	ting
kh Q n	f I s	k eI	t I N
con-	fis-	ca-	tion
kh Q n	f I s	k eI	S V n
con-	fis-	ca-	to-	ry
kh V n	f I s	k V	t O@	i:
con-	fis-	cate
kh Q n	f I s	k eI t
con-	for-	ma-	tio-	nal
kh Q n	f @r	m eI	S V	n V l
con-	for-	mance
kh V n	f O@	m V n s
con-	for-	mi-	ty
kh V n	f O@	m V	t i:
con-	for-	ming
kh V n	f O@	m I N
con-	for-	mist
kh V n	f O@	m I s t
con-	for-	mists
kh V n	f O@	m V s t s
con-	form
kh V n	f O@ m
con-	formed
kh V n	f O@ m d
con-	forms
kh V n	f O@ m z
con-	foun-	ded
kh V n	f aU n	d V d
con-	foun-	ding
kh V n	f aU n	d I N
con-	found
kh Q n	f aU n d
con-	founds
kh V n	f aU n d z
con-	fron-	ta-	tio-	nal
kh Q n	f r V n	t eI	S V	n V l
con-	fron-	ta-	tion
kh Q n	f r V n	t eI	S V n
con-	fron-	ta-	tions
kh Q n	f r V n	t eI	S V n z
con-	fron-	ted
kh V n	f r V n	t V d
con-	fron-	ting
kh V n	f r V n	t I N
con-	front
kh V n	f r V n t
con-	fronts
kh V n	f r V n t s
con-	fu-	cia-	ni-	sm
kh V n	f j u:	S V	n I	z V m
con-	fu-	cian
kh V n	f j u:	S V n
con-	fu-	cius
kh V n	f j u:	S V s
con-	fu-	ses
kh V n	f j u:	z V z
con-	fu-	sing
kh V n	f j u:	z I N
con-	fu-	sing-	ly
kh V n	f j u:	z I N	l i:
con-	fu-	sion
kh V n	f j u:	Z V n
con-	fu-	sions
kh V n	f j u:	Z V n z
con-	fuse
kh V n	f j u: z
con-	fused
kh V n	f j u: z d
con-	ga
kh O: N	g V
con-	ge-	ni-	a-	li-	ty
kh V n	dZ i:	n i:	{	l V	t i:
con-	ge-	ni-	tal
kh V n	dZ e	n V	t V l
con-	ge-	nial
kh V n	dZ i: n	j V l
con-	geal
kh V n	dZ i: l
con-	gealed
kh V n	dZ i: l d
con-	ger
kh O:	N @r
con-	ges-	ted
kh V n	dZ e s	t V d
con-	ges-	tion
kh V n	dZ e s	tS V n
con-	ges-	tive
kh V n	dZ e s	t I v
con-	gest
kh V n	dZ e s t
con-	go
kh Q N	g @U
con-	jec-	ture
kh V n	dZ e k	tS @r
con-	jec-	tures
kh V n	dZ e k	tS @r z
con-	join
kh Q n	dZ OI n
con-	joined
kh Q n	dZ OI n d
con-	ju-	ga-	ted
kh Q n	dZ V	g eI	t V d
con-	ju-	ga-	tion
kh Q n	dZ V	g eI	S V n
con-	ju-	ga-	tions
kh Q n	dZ V	g eI	S V n z
con-	ju-	gal
kh Q n	dZ V	g V l
con-	ju-	gate
kh Q n	dZ V	g eI t
con-	ju-	gates
kh Q n	dZ V	g eI t s
con-	ju-	ring
kh Q n	dZ @r	I N
con-	ju-	ror
kh Q n	dZ @r	@r
con-	junc-	ti-	va
kh Q n	dZ V N	k t aI	v V
con-	junc-	tion
kh V n	dZ V N	k S V n
con-	junc-	tions
kh V n	dZ V N	k S V n z
con-	jure
kh Q n	dZ @r
con-	jured
kh Q n	dZ @r d
con-	jures
kh Q n	dZ @r z
con-	lan
kh Q n	l V n
con-	lee
kh Q n	l i:
con-	ley
kh Q n	l i:
con-	lin
kh Q n	l I n
con-	lon
kh Q n	l V n
con-	nal-	ly
kh Q	n V	l i:
con-	nal-	ly's
kh Q	n V	l i: z
con-	naught
kh Q	n O: t
con-	ne-	ry
kh Q	n @r	i:
con-	ne-	ry's
kh Q	n @r	i: z
con-	nec-	ted
kh V	n e k	t V d
con-	nec-	ter
kh V	n e k	t @r
con-	nec-	ti-	cut
kh V	n e	t V	k V t
con-	nec-	ti-	cut's
kh V	n e	t V	k V t s
con-	nec-	ti-	vi-	ty
kh V	n e k	t I	v V	t i:
con-	nec-	ting
kh V	n e k	t I N
con-	nec-	tion
kh V	n e k	S V n
con-	nec-	tions
kh V	n e k	S V n z
con-	nec-	tive
kh V	n e k	t I v
con-	nec-	tor
kh V	n e k	t @r
con-	nec-	tors
kh V	n e k	t @r z
con-	nect
kh V	n e k t
con-	nects
kh V	n e k t s
con-	nel-	ley
kh Q	n V	l i:
con-	nel-	ly
kh Q	n V	l i:
con-	nel-	ly's
kh Q	n V	l i: z
con-	nell
kh Q	n V l
con-	ner
kh Q	n @r
con-	ners
kh Q	n @r z
con-	ner's
kh Q	n @r z
con-	nett
kh Q	n e t
con-	ni-	vance
kh V	n aI	v V n s
con-	ni-	ving
kh V	n aI	v I N
con-	nie
kh O:	n i:
con-	nie's
kh O:	n i: z
con-	ning
kh Q	n I N
con-	nip-	tion
kh V	n I p	S V n
con-	nive
kh V	n aI v
con-	no-	ta-	tio-	nal
kh Q	n V	t eI	S V	n V l
con-	no-	ta-	tion
kh Q	n V	t eI	S V n
con-	no-	ta-	tions
kh Q	n V	t eI	S V n z
con-	nois-	seur
kh Q	n V	s @r
con-	nois-	seurs
kh Q	n V	s @r z
con-	nol-	ly
kh O:	n V	l i:
con-	nor
kh Q	n @r
con-	nors
kh Q	n @r z
con-	note
kh V	n @U t
con-	notes
kh V	n @U t s
con-	ny
kh Q	n i:
con-	que-	ring
kh Q N	k @r	I N
con-	que-	ror
kh Q N	k @r	@r
con-	que-	rors
kh Q N	k @r	@r z
con-	que-	ror's
kh Q N	k @r	@r z
con-	quer
kh Q N	k @r
con-	quered
kh Q N	k @r d
con-	quers
kh Q N	k @r z
con-	quest
kh Q N	k w e s t
con-	quests
kh Q n	k w e s t s
con-	quest's
kh Q N	k w e s t s
con-	rad
kh Q n	r { d
con-	rad's
kh Q n	r { d z
con-	rail
kh Q n	r eI l
con-	rail's
kh Q n	r eI l z
con-	ran
kh Q n	r V n
con-	rath
kh Q n	r V T
con-	rey
kh Q n	r i:
con-	roe
kh Q n	r @U
con-	roy
kh O: n	r OI
con-	sci-	en-	tious
kh Q n	S i:	e n	S V s
con-	sci-	en-	tious-	ly
kh Q n	tS i:	e n	tS V s	l i:
con-	scien-	ces
kh Q n	S V n	s V z
con-	science
kh Q n	S V n s
con-	scious
kh Q n	S V s
con-	scious-	ly
kh Q n	S V s	l i:
con-	scious-	ness
kh Q n	S V s	n V s
con-	se-	cu-	tive
kh V n	s e k	j V	t I v
con-	se-	cu-	tive-	ly
kh V n	s e k	j V	t I v	l i:
con-	se-	quen-	ces
kh Q n	s V k	w e n	s V z
con-	se-	quen-	tial
kh Q n	s V k	w e n	tS V l
con-	se-	quence
kh Q n	s V k	w V n s
con-	se-	quent
kh Q n	s V k	w V n t
con-	se-	quent-	ly
kh Q n	s V k	w V n	t l i:
con-	sec-	ra-	ted
kh Q n	s V k	r eI	t V d
con-	sec-	ra-	tion
kh Q n	s V k	r eI	S V n
con-	sec-	ra-	tions
kh Q n	s V k	r eI	S V n z
con-	sec-	rate
kh Q n	s V k	r eI t
con-	sen-	su-	al
kh V n	s e n	s u:	V l
con-	sen-	sus
kh V n	s e n	s V s
con-	sen-	ted
kh V n	s e n	t V d
con-	sen-	ting
kh V n	s e n	t I N
con-	sent
kh V n	s e n t
con-	sents
kh V n	s e n t s
con-	ser-	va-	ti-	sm
kh V n	s @r	v V	t I	z V m
con-	ser-	va-	tio-	nist
kh Q n	s @r	v eI	S V	n I s t
con-	ser-	va-	tio-	nists
kh Q n	s @r	v eI	S V	n I s t s
con-	ser-	va-	tion
kh Q n	s @r	v eI	S V n
con-	ser-	va-	tive
kh V n	s @r	v V	t I v
con-	ser-	va-	tive-	ly
kh V n	s @r	v V	t I v	l i:
con-	ser-	va-	tives
kh V n	s @r	v V	t I v z
con-	ser-	va-	to-	ries
kh V n	s @r	v V	t O@	i: z
con-	ser-	va-	to-	ry
kh V n	s @r	v V	t O@	i:
con-	ser-	va-	tor
kh V n	s @r	v V	t @r
con-	ser-	va-	tor-	ship
kh V n	s @r	v V	t @r	S I p
con-	ser-	va-	tors
kh V n	s @r	v V	t @r z
con-	ser-	van-	cy
kh V n	s @r	v V n	s i:
con-	ser-	van-	cy's
kh V n	s @r	v V n	s i: z
con-	ser-	ving
kh V n	s @r	v I N
con-	serve
kh V n	s @r v
con-	served
kh V n	s @r v d
con-	sho-	hoc-	ken
kh Q n	S V	h Q	k V n
con-	si-	de-	ra-	ble
kh V n	s I	d @r	V	b V l
con-	si-	de-	ra-	tion
kh V n	s I	d @r	eI	S V n
con-	si-	de-	ra-	tions
kh V n	s I	d @r	eI	S V n z
con-	si-	de-	rab-	ly
kh V n	s I	d @r	V b	l i:
con-	si-	de-	rate
kh V n	s I	d @r	V t
con-	si-	de-	ring
kh V n	s I	d @r	I N
con-	si-	der
kh V n	s I	d @r
con-	si-	dered
kh V n	s I	d @r d
con-	si-	ders
kh V n	s I	d @r z
con-	sign
kh V n	s aI n
con-	sign-	ment
kh V n	s aI n	m V n t
con-	signed
kh V n	s aI n d
con-	sis-	ted
kh V n	s I s	t V d
con-	sis-	ten-	cy
kh V n	s I s	t V n	s i:
con-	sis-	tence
kh V n	s I s	t V n s
con-	sis-	tent
kh V n	s I s	t V n t
con-	sis-	tent-	ly
kh V n	s I s	t V n	t l i:
con-	sis-	ting
kh V n	s I s	t I N
con-	sist
kh V n	s I s t
con-	sists
kh V n	s I s t s
con-	so-	la-	ta
kh Q n	s @U	l Q	t V
con-	so-	la-	tion
kh Q n	s V	l eI	S V n
con-	so-	la-	tions
kh Q n	s V	l eI	S V n z
con-	so-	li-	da-	ted
kh V n	s Q	l V	d eI	t V d
con-	so-	li-	da-	ting
kh V n	s Q	l V	d eI	t I N
con-	so-	li-	da-	tion
kh V n	s Q	l V	d eI	S V n
con-	so-	li-	da-	tions
kh V n	s Q	l V	d eI	S V n z
con-	so-	li-	da-	tor
kh V n	s Q	l V	d eI	t @r
con-	so-	li-	da-	tors
kh V n	s Q	l V	d eI	t @r z
con-	so-	li-	date
kh V n	s Q	l V	d eI t
con-	so-	li-	dates
kh V n	s Q	l V	d eI t s
con-	so-	ling
kh V n	s @U	l I N
con-	so-	nan-	tal
kh Q n	s V	n Q n	t V l
con-	so-	nant
kh Q n	s V	n V n t
con-	so-	nants
kh Q n	s V	n V n t s
con-	sol
kh Q n	s Q l
con-	sole
kh Q n	s @U l
con-	soled
kh V n	s @U l d
con-	soles
kh V n	s @U l z
con-	sol's
kh Q n	s Q l z
con-	sor-	ti-	um
kh V n	s O@	S i:	V m
con-	sor-	ti-	ums
kh V n	s O@	S i:	V m z
con-	sor-	ti-	um's
kh V n	s O@	S i:	V m z
con-	sor-	tia
kh V n	s O@	S V
con-	sor-	ting
kh V n	s O@	t I N
con-	sort
kh V n	s O@ t
con-	su-	lar
kh Q n	s V	l @r
con-	su-	late
kh Q n	s V	l V t
con-	su-	lates
kh Q n	s V	l V t s
con-	su-	ma-	ble
kh V n	s u:	m V	b V l
con-	su-	me-	ri-	sm
kh V n	s u:	m @r	I	z V m
con-	su-	me-	rist
kh V n	s u:	m @r	I s t
con-	su-	me-	rists
kh V n	s u:	m @r	I s t s
con-	su-	mer
kh V n	s u:	m @r
con-	su-	mers
kh V n	s u:	m @r z
con-	su-	mer's
kh V n	s u:	m @r z
con-	su-	ming
kh V n	s u:	m I N
con-	sue-	la
kh V n	s w eI	l V
con-	sul
kh Q n	s V l
con-	sul-	ship
kh Q n	s V l	S I p
con-	sul-	ta-	tion
kh Q n	s V l	t eI	S V n
con-	sul-	ta-	tions
kh Q n	s V l	t eI	S V n z
con-	sul-	ta-	tive
kh V n	s V l	t V	t I v
con-	sul-	tan-	cy
kh V n	s V l	t V n	s i:
con-	sul-	tant
kh V n	s V l	t V n t
con-	sul-	tants
kh V n	s V l	t V n t s
con-	sul-	tant's
kh V n	s V l	t V n t s
con-	sul-	ted
kh V n	s V l	t V d
con-	sul-	ting
kh V n	s V l	t I N
con-	sult
kh V n	s V l t
con-	sults
kh V n	s V l t s
con-	sum-	ma-	ted
kh Q n	s V	m eI	t V d
con-	sum-	ma-	ting
kh Q n	s V	m eI	t I N
con-	sum-	ma-	tion
kh Q n	s V	m eI	S V n
con-	sum-	mate
kh Q n	s V	m V t
con-	sume
kh V n	s u: m
con-	sumed
kh V n	s u: m d
con-	sumes
kh V n	s u: m z
con-	sump-	tion
kh V n	s V m	p S V n
con-	ta-	gion
kh V n	t eI	dZ V n
con-	ta-	gious
kh V n	t eI	dZ V s
con-	ta-	gious-	ness
kh V n	t eI	dZ V s	n V s
con-	ta-	mi-	na-	ted
kh V n	t {	m V	n eI	t V d
con-	ta-	mi-	na-	ting
kh V n	t {	m V	n eI	t I N
con-	ta-	mi-	na-	tion
kh V n	t {	m V	n eI	S V n
con-	ta-	mi-	nant
kh V n	t {	m V	n V n t
con-	ta-	mi-	nants
kh V n	t {	m V	n V n t s
con-	ta-	mi-	nate
kh V n	t {	m V	n eI t
con-	ta-	mi-	nates
kh V n	t {	m V	n eI t s
con-	tac
kh Q n	t { k
con-	tac-	ted
kh Q n	t { k	t V d
con-	tac-	ting
kh Q n	t { k	t I N
con-	tact
kh Q n	t { k t
con-	tacts
kh Q n	t { k t s
con-	tai-	ne-	rize
kh V n	t eI	n @r	aI z
con-	tai-	ne-	rized
kh V n	t eI	n @r	aI z d
con-	tai-	ner
kh V n	t eI	n @r
con-	tai-	ner-	board
kh V n	t eI	n @r	b O@ d
con-	tai-	ners
kh V n	t eI	n @r z
con-	tai-	ner's
kh V n	t eI	n @r z
con-	tai-	ning
kh V n	t eI	n I N
con-	tain
kh V n	t eI n
con-	tain-	ment
kh V n	t eI n	m V n t
con-	tained
kh V n	t eI n d
con-	tains
kh V n	t eI n z
con-	tem-	po
kh Q n	t e m	p @U
con-	tem-	po-	ra-	ne-	ous
kh V n	t e m	p @r	eI	n i:	V s
con-	tem-	po-	ra-	ne-	ous-	ly
kh V n	t e m	p @r	eI	n i:	V s	l i:
con-	tem-	po-	ra-	ries
kh V n	t e m	p @r	e@	i: z
con-	tem-	po-	ra-	ry
kh V n	t e m	p @r	e@	i:
con-	temp-	la-	ted
kh Q n	t V m	p l eI	t V d
con-	temp-	la-	ting
kh Q n	t V m	p l eI	t I N
con-	temp-	la-	tion
kh Q n	t V m	p l eI	S V n
con-	temp-	la-	tive
kh V n	t e m	p l V	t I v
con-	temp-	late
kh Q n	t V m	p l eI t
con-	temp-	lates
kh Q n	t V m	p l eI t s
con-	temp-	ti-	ble
kh V n	t e m	p t V	b V l
con-	temp-	tu-	ous
kh V n	t e m	p tS u:	V s
con-	temp-	tuous-	ly
kh V n	t e m	p tS w V s	l i:
con-	tempt
kh V n	t e m p t
con-	ten-	ded
kh V n	t e n	d V d
con-	ten-	der
kh V n	t e n	d @r
con-	ten-	ders
kh V n	t e n	d @r z
con-	ten-	ding
kh V n	t e n	d I N
con-	ten-	ted
kh V n	t e n	t V d
con-	ten-	ted-	ly
kh V n	t e n	t V d	l i:
con-	ten-	tion
kh V n	t e n	S V n
con-	ten-	tions
kh V n	t e n	S V n z
con-	ten-	tious
kh V n	t e n	S V s
con-	ten-	tious-	ness
kh V n	t e n	S V s	n V s
con-	tend
kh V n	t e n d
con-	tends
kh V n	t e n d z
con-	tent
kh Q n	t e n t
con-	tent-	ment
kh V n	t e n	t m V n t
con-	tents
kh Q n	t e n t s
con-	ti
kh Q n	t i:
con-	ti-	gu-	ous
kh V n	t I g	j u:	V s
con-	ti-	nen-	tal
kh Q n	t I	n e n	t V l
con-	ti-	nen-	tal-	ly
kh Q n	t I	n e n	t V	l i:
con-	ti-	nen-	tals
kh Q n	t V	n e n	t V l z
con-	ti-	nent
kh Q n	t I	n V n t
con-	ti-	nents
kh Q n	t I	n V n t s
con-	ti-	nent's
kh Q n	t I	n V n t s
con-	ti-	nu-	a-	tion
kh V n	t I n	j u:	eI	S V n
con-	ti-	nu-	al
kh V n	t I n	j u:	V l
con-	ti-	nu-	al-	ly
kh V n	t I n	j u:	V	l i:
con-	ti-	nu-	an-	ces
kh V n	t I n	j u:	V n	s V z
con-	ti-	nu-	ance
kh V n	t I n	j u:	V n s
con-	ti-	nu-	i-	ty
kh Q n	t I	n u:	I	t i:
con-	ti-	nu-	ing
kh V n	t I n	j u:	I N
con-	ti-	nu-	ous
kh V n	t I n	j u:	V s
con-	ti-	nu-	ous-	ly
kh V n	t I n	j u:	V s	l i:
con-	ti-	nu-	um
kh V n	t I n	j u:	V m
con-	ti-	nue
kh V n	t I n	j u:
con-	ti-	nued
kh V n	t I n	j u: d
con-	ti-	nues
kh V n	t I n	j u: z
con-	tin-	gen-	cies
kh V n	t I n	dZ V n	s i: z
con-	tin-	gen-	cy
kh V n	t I n	dZ V n	s i:
con-	tin-	gent
kh V n	t I n	dZ V n t
con-	tin-	gents
kh V n	t I n	dZ V n t s
con-	tor-	ted
kh V n	t O@	t V d
con-	tor-	tio-	nist
kh V n	t O@	S V	n V s t
con-	tor-	tion
kh V n	t O@	S V n
con-	tor-	tions
kh V n	t O@	S V n z
con-	tort
kh V n	t O@ t
con-	torts
kh V n	t O@ t s
con-	tos
kh Q n	t @U z
con-	tour
kh Q n	t U@
con-	toured
kh Q n	t U@ d
con-	tours
kh Q n	t U@ z
con-	tu-	sion
kh V n	t u:	Z V n
con-	tu-	sions
kh V n	t u:	Z V n z
con-	und-	rum
kh V	n V n	d r V m
con-	va-	le-	scence
kh Q n	v V	l e	s V n s
con-	va-	le-	scent
kh Q n	v V	l e	s V n t
con-	va-	lesce
kh Q n	v V	l e s
con-	vair
kh Q n	v e@
con-	ve-	nien-	ces
kh V n	v i: n	j V n	s V z
con-	ve-	nience
kh V n	v i: n	j V n s
con-	ve-	nient
kh V n	v i: n	j V n t
con-	ve-	nient-	ly
kh V n	v i: n	j V n	t l i:
con-	ve-	ning
kh V n	v i:	n I N
con-	ve-	ry
kh Q n	v @r	i:
con-	ve-	yance
kh V n	v eI	V n s
con-	ve-	yer
kh V n	v eI	@r
con-	ve-	ying
kh V n	v eI	I N
con-	ve-	yor
kh V n	v eI	@r
con-	vec-	tion
kh V n	v e k	S V n
con-	ven-	tio-	nal
kh V n	v e n	S V	n V l
con-	ven-	tio-	nal-	ly
kh V n	v e n	S V	n V	l i:
con-	ven-	tio-	neer
kh V n	v e n	S V	n I@
con-	ven-	tio-	neers
kh V n	v e n	S V	n I@ z
con-	ven-	tion
kh V n	v e n	S V n
con-	ven-	tions
kh V n	v e n	S V n z
con-	ven-	tion's
kh V n	v e n	S V n z
con-	vene
kh V n	v i: n
con-	vened
kh V n	v i: n d
con-	venes
kh V n	v i: n z
con-	vent
kh Q n	v V n t
con-	ver-	gence
kh V n	v @r	dZ V n s
con-	ver-	gent
kh V n	v @r	dZ V n t
con-	ver-	ging
kh V n	v @r	dZ I N
con-	ver-	sa-	tio-	na-	list
kh Q n	v @r	s eI	S V	n V	l I s t
)"
R"(con-	ver-	sa-	tio-	nal
kh Q n	v @r	s eI	S V	n V l
con-	ver-	sa-	tion
kh Q n	v @r	s eI	S V n
con-	ver-	sa-	tions
kh Q n	v @r	s eI	S V n z
con-	ver-	sant
kh V n	v @r	s V n t
con-	ver-	ses
kh Q n	v @r	s V z
con-	ver-	sing
kh V n	v @r	s I N
con-	ver-	sion
kh V n	v @r	Z V n
con-	ver-	sions
kh V n	v @r	Z V n z
con-	ver-	sion's
kh V n	v @r	Z V n z
con-	ver-	ted
kh V n	v @r	t V d
con-	ver-	ter
kh V n	v @r	t @r
con-	ver-	ters
kh V n	v @r	t @r z
con-	ver-	ti-	bi-	li-	ty
kh Q n	v @r	t I	b I	l I	t i:
con-	ver-	ti-	ble
kh V n	v @r	t V	b V l
con-	ver-	ti-	bles
kh V n	v @r	t V	b V l z
con-	ver-	ting
kh V n	v @r	t I N
con-	verge
kh V n	v @r dZ
con-	verged
kh V n	v @r dZ d
con-	verse
kh Q n	v @r s
con-	verse-	ly
kh Q n	v @r s	l i:
con-	versed
kh V n	v @r s t
con-	vert
kh Q n	v @r t
con-	verts
kh Q n	v @r t s
con-	vex
kh V n	v e k s
con-	vey
kh V n	v eI
con-	veyed
kh V n	v eI d
con-	veys
kh V n	v eI z
con-	vi-	vi-	al
kh V n	v I	v i:	V l
con-	vic-	ted
kh V n	v I k	t V d
con-	vic-	ting
kh V n	v I k	t I N
con-	vic-	tion
kh V n	v I k	S V n
con-	vic-	tions
kh V n	v I k	S V n z
con-	vict
kh Q n	v I k t
con-	victs
kh Q n	v I k t s
con-	vin-	ces
kh V n	v I n	s V z
con-	vin-	cing
kh V n	v I n	s I N
con-	vin-	cing-	ly
kh V n	v I n	s I N	l i:
con-	vince
kh V n	v I n s
con-	vinced
kh V n	v I n s t
con-	vo-	ca-	tion
kh Q n	v V	k eI	S V n
con-	vo-	lu-	ted
kh Q n	v V	l u:	t V d
con-	vo-	lu-	tion
kh Q n	v V	l u:	S V n
con-	vo-	lute
kh Q n	v V	l u: t
con-	voy
kh Q n	v OI
con-	voys
kh Q n	v OI z
con-	vul-	sion
kh V n	v V l	S V n
con-	vul-	sions
kh V n	v V l	S V n z
con-	vul-	sive
kh V n	v V l	s I v
con-	way
kh Q n	w eI
con-	yers
kh Q n	j @r z
conc-	lave
kh Q n	k l eI v
conc-	lu-	ded
kh V n	k l u:	d V d
conc-	lu-	ding
kh V n	k l u:	d I N
conc-	lu-	sion
kh V n	k l u:	Z V n
conc-	lu-	sions
kh V n	k l u:	Z V n z
conc-	lu-	sive
kh V n	k l u:	s I v
conc-	lu-	sive-	ly
kh V n	k l u:	s I v	l i:
conc-	lude
kh V n	k l u: d
conc-	ludes
kh V n	k l u: d z
conch
kh Q n tS
conde
kh Q n d
cone
kh @U n
cone-	flo-	wer
kh @U n	f l aU	@r
cone-	head
kh @U n	h e d
cones
kh @U n z
cone's
kh @U n z
conf-	lag-	ra-	tion
kh Q n	f l V g	r eI	S V n
conf-	late
kh V n	f l eI t
conf-	lates
kh V n	f l eI t s
conf-	lic-	ted
kh V n	f l I k	t V d
conf-	lic-	ting
kh V n	f l I k	t I N
conf-	lict
kh Q n	f l I k t
conf-	licts
kh V n	f l I k t s
conf-	lu-	ence
kh Q n	f l u:	V n s
conf-	lu-	ent
kh Q n	f l u:	V n t
confe-	ren-	cing
kh Q n	f r V n	s I N
cong
kh O: N
cong-	don
kh Q N	d V n
cong-	lo-	me-	ra-	tion
kh V n	g l Q	m @r	eI	S V n
cong-	lo-	me-	rate
kh V n	g l Q	m @r	V t
cong-	lo-	me-	rates
kh V n	g l Q	m @r	V t s
cong-	lo-	me-	rate's
kh V n	g l Q	m @r	V t s
cong-	ra-	tu-	la-	ted
kh V n	g r {	tS V	l eI	t V d
cong-	ra-	tu-	la-	ting
kh V n	g r {	tS V	l eI	t I N
cong-	ra-	tu-	la-	tion
kh V n	g r {	tS V	l eI	S V n
cong-	ra-	tu-	la-	tions
kh V n	g r {	tS V	l eI	S V n z
cong-	ra-	tu-	la-	to-	ry
kh V n	g r {	tS V	l V	t O@	i:
cong-	ra-	tu-	late
kh V n	g r {	tS V	l eI t
cong-	re-	ga-	ted
kh Q N	g r V	g eI	t V d
cong-	re-	ga-	tio-	nal
kh Q N	g r V	g eI	S V	n V l
cong-	re-	ga-	tion
kh Q N	g r V	g eI	S V n
cong-	re-	ga-	tions
kh Q N	g r V	g eI	S V n z
cong-	re-	ga-	tion's
kh Q N	g r V	g eI	S V n z
cong-	re-	gate
kh Q N	g r V	g eI t
cong-	res-	ses
kh Q N	g r V	s V z
cong-	res-	sio-	nal
kh V n	g r e	S V	n V l
cong-	res-	sio-	nal-	ly
kh V n	g r e	S V	n V	l i:
cong-	res-	s's
kh Q N	g r V	s V z
cong-	ress
kh Q N	g r V s
cong-	ress-	man
kh Q N	g r V s	m V n
cong-	ress-	man's
kh Q N	g r V s	m V n z
cong-	ress-	men
kh Q N	g r V s	m e n
cong-	ress-	peo-	ple
kh Q N	g r V s	p i:	p V l
cong-	ress-	per-	son
kh Q N	g r V s	p @r	s V n
cong-	ress-	per-	sons
kh Q N	g r V s	p @r	s V n z
cong-	ress-	wo-	man
kh Q N	g r V s	w U	m V n
cong-	ress-	wo-	man's
kh Q N	g r V s	w U	m V n z
cong-	ress-	wo-	men
kh Q N	g r V s	w I	m e n
cong-	ru-	ence
kh O: n	g r u:	V n s
cong-	ru-	i-	ty
kh V n	g r u:	V	t i:
conk
kh Q N k
conk-	lin
kh Q N	k l I n
conn
kh Q n
conn.
kh Q n
conned
kh Q n d
cons
kh Q n z
cons-	crip-	ted
kh V n	s k r I p	t V d
cons-	crip-	tion
kh V n	s k r I p	S V n
cons-	cript
kh Q n	s k r I p t
cons-	cripts
kh Q n	s k r I p t s
cons-	pi-	cu-	ous
kh V n	s p I k	j u:	V s
cons-	pi-	cu-	ous-	ly
kh V n	s p I k	j u:	V s	l i:
cons-	pi-	ra-	cies
kh V n	s p I@	V	s i: z
cons-	pi-	ra-	cy
kh V n	s p I@	V	s i:
cons-	pi-	ra-	to-	ri-	al
kh V n	s p I@	V	t O@	i:	V l
cons-	pi-	ra-	to-	ri-	al-	ly
kh V n	s p I@	V	t O@	i:	V	l i:
cons-	pi-	ra-	tor
kh V n	s p I@	V	t @r
cons-	pi-	ra-	tors
kh V n	s p I@	V	t @r z
cons-	pi-	re
kh V n	s p aI	@r
cons-	pi-	red
kh V n	s p aI	@r d
cons-	pi-	ring
kh V n	s p aI	r I N
cons-	ta-	ble
kh Q n	s t V	b V l
cons-	ta-	bles
kh Q n	s t V	b V l z
cons-	ta-	bu-	la-	ry
kh V n	s t { b	j V	l e@	i:
cons-	tan-	cy
kh Q n	s t V n	s i:
cons-	tan-	ta
kh Q n	s t Q n	t V
cons-	tan-	ti-	na
kh Q n	s t Q n	t i:	n V
cons-	tan-	ti-	no
kh Q n	s t V n	t i:	n @U
cons-	tan-	ti-	no-	ple
kh Q n	s t { n	t I	n @U	p V l
cons-	tan-	tin
kh V n	s t { n	t I n
cons-	tan-	tine
kh Q n	s t V n	t i: n
cons-	tance
kh Q n	s t V n s
cons-	tant
kh Q n	s t V n t
cons-	tant-	ly
kh Q n	s t V n	t l i:
cons-	tants
kh Q n	s t V n t s
cons-	tant's
kh Q n	s t V n t s
cons-	tel-	la-	tion
kh Q n	s t V	l eI	S V n
cons-	tel-	la-	tions
kh Q n	s t V	l eI	S V n z
cons-	tel-	la-	tion's
kh Q n	s t V	l eI	S V n z
cons-	ter-	na-	tion
kh Q n	s t @r	n eI	S V n
cons-	ti-	pa-	ted
kh Q n	s t I	p eI	t I d
cons-	ti-	pa-	tion
kh Q n	s t I	p eI	S V n
cons-	ti-	pate
kh Q n	s t I	p eI t
cons-	ti-	tu-	en-	cies
kh V n	s t I	tS u:	V n	s i: z
cons-	ti-	tu-	en-	cy
kh V n	s t I	tS u:	V n	s i:
cons-	ti-	tu-	ent
kh V n	s t I	tS u:	V n t
cons-	ti-	tu-	ents
kh V n	s t I	tS u:	V n t s
cons-	ti-	tu-	ted
kh Q n	s t I	t u:	t I d
cons-	ti-	tu-	ting
kh Q n	s t I	t u:	t I N
cons-	ti-	tu-	tio-	na-	li-	ty
kh Q n	s t I	t u:	S V	n {	l I	t i:
cons-	ti-	tu-	tio-	nal
kh Q n	s t I	t u:	S V	n V l
cons-	ti-	tu-	tio-	nal-	ly
kh Q n	s t I	t u:	S V	n V	l i:
cons-	ti-	tu-	tio-	nist
kh Q n	s t I	t u:	S V	n I s t
cons-	ti-	tu-	tio-	nists
kh Q n	s t I	t u:	S V	n I s t s
cons-	ti-	tu-	tion
kh Q n	s t I	t u:	S V n
cons-	ti-	tu-	tions
kh Q n	s t I	t u:	S V n z
cons-	ti-	tu-	tion's
kh Q n	s t I	t u:	S V n z
cons-	ti-	tute
kh Q n	s t I	t u: t
cons-	ti-	tutes
kh Q n	s t I	t u: t s
const-	rai-	ning
kh V n	s t r eI	n I N
const-	rain
kh V n	s t r eI n
const-	rained
kh V n	s t r eI n d
const-	rains
kh V n	s t r eI n z
const-	raint
kh V n	s t r eI n t
const-	raints
kh V n	s t r eI n t s
const-	ric-	ted
kh V n	s t r I k	t V d
const-	ric-	ting
kh V n	s t r I k	t I N
const-	ric-	tion
kh V n	s t r I k	S V n
const-	ric-	tions
kh V n	s t r I k	S V n z
const-	ric-	tor
kh V n	s t r I k	t @r
const-	ric-	tors
kh V n	s t r I k	t @r z
const-	rict
kh V n	s t r I k t
const-	ruc-	ted
kh V n	s t r V k	t V d
const-	ruc-	ting
kh V n	s t r V k	t I N
const-	ruc-	tio-	nist
kh V n	s t r V k	S V	n I s t
const-	ruc-	tion
kh V n	s t r V k	S V n
const-	ruc-	tions
kh V n	s t r V k	S V n z
const-	ruc-	tive
kh V n	s t r V k	t I v
const-	ruc-	tive-	ly
kh V n	s t r V k	t I v	l i:
const-	ruc-	tor
kh V n	s t r V k	t @r
const-	ruc-	tors
kh V n	s t r V k	t @r z
const-	ruct
kh V n	s t r V k t
const-	ructs
kh V n	s t r V k t s
const-	rue
kh V n	s t r u:
const-	rued
kh V n	s t r u: d
cont-	ra
kh Q n	t r V
cont-	ra-	band
kh Q n	t r V	b { n d
cont-	ra-	bas-	soon
kh Q n	t r V	b {	s u: n
cont-	ra-	cep-	tion
kh Q n	t r V	s e p	S V n
cont-	ra-	cep-	tive
kh Q n	t r V	s e p	t I v
cont-	ra-	cep-	tives
kh Q n	t r V	s e p	t I v z
cont-	ra-	dic-	ted
kh Q n	t r V	d I k	t V d
cont-	ra-	dic-	ting
kh Q n	t r V	d I k	t I N
cont-	ra-	dic-	tion
kh Q n	t r V	d I k	S V n
cont-	ra-	dic-	tions
kh Q n	t r V	d I k	S V n z
cont-	ra-	dic-	to-	ri-	ly
kh Q n	t r V	d I k	t @r	V	l i:
cont-	ra-	dic-	to-	ry
kh Q n	t r V	d I k	t @r	i:
cont-	ra-	dict
kh Q n	t r V	d I k t
cont-	ra-	dicts
kh Q n	t r V	d I k t s
cont-	ra-	ri-	an
kh Q n	t r e@	i:	V n
cont-	ra-	ri-	ans
kh V n	t r e@	i:	V n z
cont-	ra-	ri-	ness
kh Q n	t r e@	i:	n V s
cont-	ra-	ry
kh Q n	t r e@	i:
cont-	ra-	ven-	tion
kh Q n	t r V	v e n	tS V n
cont-	ra-	vene
kh Q n	t r V	v i: n
cont-	rac-	ted
kh Q n	t r { k	t V d
cont-	rac-	ting
kh Q n	t r { k	t I N
cont-	rac-	tio-	na-	ry
kh V n	t r { k	S V	n e@	i:
cont-	rac-	tion
kh V n	t r { k	S V n
cont-	rac-	tions
kh V n	t r { k	S V n z
cont-	rac-	tor
kh Q n	t r { k	t @r
cont-	rac-	tors
kh Q n	t r { k	t @r z
cont-	rac-	tor's
kh Q n	t r { k	t @r z
cont-	rac-	tu-	al
kh V n	t r { k	tS u:	V l
cont-	rac-	tu-	al-	ly
kh V n	t r { k	tS u:	V	l i:
cont-	ract
kh Q n	t r { k t
cont-	racts
kh Q n	t r { k t s
cont-	rap-	tion
kh V n	t r { p	S V n
cont-	rap-	tions
kh V n	t r { p	S V n z
cont-	ras
kh Q n	t r V z
cont-	ras-	ted
kh V n	t r { s	t V d
cont-	ras-	ting
kh V n	t r { s	t I N
cont-	rast
kh Q n	t r { s t
cont-	rasts
kh Q n	t r { s t s
cont-	re-	ras
kh Q n	t r e@	Q z
cont-	re-	temps
kh Q n	t r V	t e m p s
cont-	ri-	bu-	ted
kh V n	t r I b	j u:	t V d
cont-	ri-	bu-	ting
kh V n	t r I b	j u:	t I N
cont-	ri-	bu-	tion
kh Q n	t r I b	j u:	S V n
cont-	ri-	bu-	tions
kh Q n	t r I b	j u:	S V n z
cont-	ri-	bu-	to-	ry
kh V n	t r I b	j V	t O@	i:
cont-	ri-	bu-	tor
kh V n	t r I b	j V	t @r
cont-	ri-	bu-	tors
kh V n	t r I b	j V	t @r z
cont-	ri-	bute
kh V n	t r I b	j u: t
cont-	ri-	butes
kh V n	t r I b	j u: t s
cont-	ri-	tion
kh V n	t r I	S V n
cont-	ri-	van-	ces
kh V n	t r aI	v V n	s V z
cont-	ri-	vance
kh V n	t r aI	v V n s
cont-	rite
kh V n	t r aI t
cont-	rive
kh V n	t r aI v
cont-	rived
kh V n	t r aI v d
cont-	ro-	ver-	sial
kh Q n	t r V	v @r	S V l
cont-	ro-	ver-	sies
kh Q n	t r V	v @r	s i: z
cont-	ro-	ver-	sy
kh Q n	t r V	v @r	s i:
cont-	rol
kh V n	t r @U l
cont-	rol-	la-	ble
kh V n	t r @U	l V	b V l
cont-	rol-	ler
kh V n	t r @U	l @r
cont-	rol-	lers
kh V n	t r @U	l @r z
cont-	rol-	ler's
kh V n	t r @U	l @r z
cont-	rol-	ling
kh V n	t r @U	l I N
cont-	rolled
kh V n	t r @U l d
cont-	rols
kh V n	t r @U l z
cont-	rol's
kh V n	t r @U l z
conte
kh O: n t
coo
kh u:
coo-	ing
kh u:	I N
coo-	ker
kh U	k @r
coo-	kers
kh U	k @r z
coo-	kie
kh U	k i:
coo-	kies
kh U	k i: z
coo-	king
kh U	k I N
coo-	lant
kh u:	l V n t
coo-	lants
kh u:	l V n t s
coo-	ler
kh u:	l @r
coo-	lers
kh u:	l @r z
coo-	lest
kh u:	l V s t
coo-	ley
kh u:	l i:
coo-	ley's
kh u:	l i: z
coo-	lid-	ge's
kh u:	l I	dZ V z
coo-	lidge
kh u:	l I dZ
coo-	ling
kh u:	l I N
coo-	nan
kh u:	n V n
coo-	ner
kh u:	n @r
coo-	pe-	ra-	tive-	ly
kh @U	Q p	r V	t I v	l i:
coo-	pe-	ra-	tives
kh @U	Q p	r V	t I v z
coo-	pe-	rage
kh u:	p @r	V dZ
coo-	per
kh u:	p @r
coo-	per-	man
kh u:	p @r	m { n
coo-	per-	smith
kh u:	p @r s	m I T
coo-	per-	stein
kh u:	p @r s	t aI n
coo-	pers
kh u:	p @r z
coo-	per's
kh u:	p @r z
coo-	pers-	town
kh u:	p @r z	t aU n
coo-	sa
kh u:	s V
coo-	ter
kh u:	t @r
cook
kh U k
cook-	book
kh U k	b U k
cook-	books
kh U k	b U k s
cook-	book's
kh U k	b U k s
cook-	out
kh U	k aU t
cook-	outs
kh U	k aU t s
cook-	son
kh U k	s V n
cook-	ware
kh U k	w e@
cooke
kh U k
cooked
kh U k t
cooks
kh U k s
cook's
kh U k s
cool
kh u: l
cool-	ly
kh u:	l i:
cool-	ness
kh u: l	n V s
cooled
kh u: l d
cools
kh u: l z
coombe
kh u: m b
coombes
kh u: m b z
coombs
kh u: m z
coon
kh u: n
coons
kh u: n z
cooped
kh u: p t
coor-	s's
kh u: r	z V z
coors
kh u: r z
coos
kh u: s
coot
kh u: t
coots
kh u: t s
cop
kh Q p
cop-	land
kh Q p	l V n d
cop-	ley
kh Q p	l i:
cop-	ley's
kh Q p	l i: z
cop-	lin
kh Q p	l I n
cop-	pa
kh @U	p V
cop-	pe-	ry
kh Q	p @r	i:
cop-	per
kh Q	p @r
cop-	per-	field
kh Q	p @r	f i: l d
cop-	per-	field's
kh Q	p @r	f i: l d z
cop-	per-	head
kh Q	p @r	h e d
cop-	per-	heads
kh Q	p @r	h e d z
cop-	per-	smith
kh Q	p @r s	m I T
cop-	pers
kh Q	p @r z
cop-	per's
kh Q	p @r z
cop-	pin
kh Q	p I n
cop-	pin-	ger
kh Q	p I	N @r
cop-	ping
kh Q	p I N
cop-	pins
kh Q	p I n z
cop-	ple
kh Q	p V l
cop-	po-	la
kh @U	p @U	l V
cop-	po-	la's
kh @U	p @U	l V z
cop-	pock
kh Q	p V k
cop-	ra
kh @U p	r V
cop-	ro-	ces-	sor
kh @U p	r Q	s e	s @r
cop-	ro-	ces-	sors
kh @U p	r Q	s e	s @r z
cop-	tic
kh Q p	t I k
cope
kh @U p
cope-	land
kh @U p	l V n d
cope-	land's
kh @U p	l V n d z
cope-	man
kh @U p	m V n
coped
kh @U p t
copes
kh @U p s
copp
kh Q p
copped
kh Q p t
copps
kh Q p s
cops
kh Q p s
cor
kh O@
cor-	ban
kh O@	b V n
cor-	beil
kh O@	b aI l
cor-	bel
kh O@	b V l
cor-	belled
kh O@	b V l d
cor-	bet
kh O@	b e t
cor-	bett
kh O@	b e t
cor-	bin
kh O@	b I n
cor-	bu-	sier
kh O@ b	j u: s	j @r
cor-	by
kh O@	b i:
cor-	co-	ran
kh O@	k @r	V n
cor-	da
kh O@	d V
cor-	dage
kh O@	d I dZ
cor-	day
kh O@	d eI
cor-	ded
kh O@	d V d
cor-	dell
kh O@	d e l
cor-	der
kh O@	d @r
cor-	di-	er
kh O@	d i:	@r
cor-	dial
kh O@	dZ V l
cor-	dial-	ly
kh O@	dZ V	l i:
cor-	die
kh O@	d i:
cor-	gi
kh O@	g i:
cor-	ker
kh O@	k @r
cor-	king
kh O@	k I N
cor-	ky
kh O@	k i:
cor-	le-	one
kh O@	l i:	@U n
cor-	ley
kh O@	l i:
cor-	liss
kh O@	l I s
cor-	mac
kh O@	m V k
cor-	mack
kh O@	m V k
cor-	mi-	er
kh O@	m i:	@r
cor-	mick
kh O@	m I k
cor-	mo-	rant
kh O@	m @r	V n t
cor-	mo-	rants
kh O@	m @r	V n t s
cor-	nall
kh O@	n V l
cor-	ne-	a
kh O@	n i:	V
cor-	ne-	as
kh O@	n i:	V z
cor-	ne-	la
kh @r	n e	l V
cor-	ne-	lia
kh O@	n i: l	j V
cor-	ne-	lius
kh O@	n i: l	j V s
cor-	ne-	ring
kh O@	n @r	I N
cor-	neal
kh O@	n i: l
cor-	nel
kh O@	n V l
cor-	nell
kh O@	n e l
cor-	nelle
kh @r	n e l
cor-	nell's
kh O@	n e l z
cor-	ner
kh O@	n @r
cor-	ner-	back
kh O@	n @r	b { k
cor-	nered
kh O@	n @r d
cor-	ners
kh O@	n @r z
cor-	ners-	tone
kh O@	n @r s	t @U n
cor-	ners-	tones
kh O@	n @r s	t @U n z
cor-	net
kh O@	n e t
cor-	net-	tist
kh O@	n e	t I s t
cor-	nett
kh O@	n e t
cor-	nette
kh @r	n e t
cor-	ney
kh O@	n i:
cor-	ni-	a
kh O@	n i:	V
cor-	niche
kh O@	n I S
cor-	nie
kh O@	n i:
cor-	ning
kh O@	n I N
cor-	ning's
kh O@	n I N z
cor-	nish
kh O@	n I S
cor-	nu-	co-	pi-	a
kh O@	n V	k @U	p i:	V
cor-	ny
kh O@	n i:
cor-	po-	ra
kh O@	p @r	V
cor-	po-	ra-	ti-	sm
kh O@	p @r	V	t I	z V m
cor-	po-	ra-	tion
kh O@	p @r	eI	S V n
cor-	po-	ra-	tions
kh O@	p @r	eI	S V n z
cor-	po-	ra-	tion's
kh O@	p @r	eI	S V n z
cor-	po-	ra-	tist
kh O@	p @r	V	t I s t
cor-	po-	ral
kh O@	p @r	V l
cor-	po-	rate
kh O@	p @r	V t
cor-	po-	rates
kh O@	p @r	V t s
cor-	pus
kh O@	p V s
cor-	ra-	do
kh @r	Q	d @U
cor-	ra-	les
kh @r	Q	l e s
cor-	ral
kh @r	{ l
cor-	ral-	ling
kh @r	{	l I N
cor-	ralled
kh @r	{ l d
cor-	re-	a
kh O@	i:	V
cor-	re-	gi-	dor
kh @r	e	g I	d O@
cor-	re-	la-	ted
kh O@	V	l eI	t V d
cor-	re-	la-	ting
kh O@	V	l eI	t I N
cor-	re-	la-	tion
kh O@	V	l eI	S V n
cor-	re-	la-	tions
kh O@	V	l eI	S V n z
cor-	re-	late
kh O@	V	l eI t
cor-	re-	lates
kh O@	V	l V t s
cor-	rec-	ted
kh @r	e k	t V d
cor-	rec-	ting
kh @r	e k	t I N
cor-	rec-	tio-	nal
kh @r	e k	S V	n V l
cor-	rec-	tion
kh @r	e k	S V n
cor-	rec-	tions
kh @r	e k	S V n z
cor-	rec-	tive
kh @r	e k	t I v
cor-	rect
kh @r	e k t
cor-	rect-	ly
kh @r	e k	t l i:
cor-	rect-	ness
kh @r	e k	t n V s
cor-	rects
kh @r	e k t s
cor-	rell
kh @r	eI l
cor-	ren-	te
kh @r	e n	t i:
cor-	res-	pon-	ded
kh O@	V s	p Q n	d V d
cor-	res-	pon-	dence
kh O@	V s	p Q n	d V n s
cor-	res-	pon-	dent
kh O@	V s	p Q n	d V n t
cor-	res-	pon-	dents
kh O@	V s	p Q n	d V n t s
cor-	res-	pon-	ding
kh O@	V s	p Q n	d I N
cor-	res-	pon-	ding-	ly
kh O@	V s	p Q n	d I N	l i:
cor-	res-	pond
kh O@	V s	p Q n d
cor-	res-	ponds
kh O@	V s	p Q n d z
cor-	ri-	dor
kh O@	I	d @r
cor-	ri-	dors
kh O@	I	d @r z
cor-	ri-	gan
kh O@	I	g V n
cor-	ri-	gan's
kh O@	I	g V n z
cor-	ri-	na
kh @r	i:	n V
cor-	rie
kh O@	i:
cor-	ro-	bo-	ra-	ted
kh @r	Q	b @r	eI	t V d
cor-	ro-	bo-	ra-	ting
kh @r	Q	b @r	eI	t I N
cor-	ro-	bo-	ra-	tion
kh @r	O:	b @r	eI	S V n
cor-	ro-	bo-	ra-	tive
kh @r	Q	b @r	V	t I v
cor-	ro-	bo-	rate
kh @r	Q	b @r	eI t
cor-	ro-	bo-	rates
kh @r	O:	b @r	eI t s
cor-	ro-	ded
kh @r	@U	d V d
cor-	ro-	sion
kh @r	@U	Z V n
cor-	ro-	sive
kh @r	@U	s I v
cor-	rode
kh @r	@U d
cor-	rodes
kh @r	@U d z
cor-	ron
kh @r	O: n
cor-	ru-	ga-	ted
kh O@	V	g eI	t V d
cor-	ru-	gate
kh O@	V	g eI t
cor-	rup-	ted
kh @r	V p	t V d
cor-	rup-	ting
kh @r	V p	t I N
cor-	rup-	tion
kh @r	V p	S V n
cor-	rup-	tions
kh @r	V p	S V n z
cor-	rup-	tive
kh @r	V p	t I v
cor-	rupt
kh @r	V p t
cor-	rupts
kh @r	V p t s
cor-	ry
kh O@	i:
cor-	sage
kh O@	s Q Z
cor-	sair
kh O@	s e@
cor-	ser
kh O@	s @r
cor-	set
kh O@	s V t
cor-	set-	ti
kh @r	s e	t i:
cor-	si-	ca
kh O@	s I	k V
)"
R"(cor-	si-	can
kh O@	s I	k V n
cor-	sig-	li-	a
kh @r	s i: g	l i:	V
cor-	so
kh O@	s @U
cor-	son
kh O@	s V n
cor-	te-	se
kh @r	t eI	z i:
cor-	tel-	you
kh O@	t e l	j u:
cor-	tex
kh O@	t e k s
cor-	tez
kh O@	t e z
cor-	ti
kh O@	t i:
cor-	ti-	cal
kh O@	t I	k V l
cor-	ti-	cos-	te-	roid
kh O@	t I	k @U s	t e@	OI d
cor-	ti-	cos-	te-	roids
kh O@	t I	k @U s	t e@	OI d z
cor-	ti-	na
kh @r	t i:	n V
cor-	ti-	nas
kh O@	t i:	n V z
cor-	ti-	sone
kh O@	t I	z @U n
cor-	tin
kh O@	t I n
cor-	tine
kh O@	t i: n
cor-	val-	lis
kh O@	v {	l I s
cor-	vette
kh O@	v e t
cor-	vettes
kh O@	v e t s
cor-	vin
kh O@	v I n
cor-	vo
kh O@	v @U
cor-	vus
kh O@	v V s
cor-	win
kh O@	w I n
cord
kh O@ d
cores
kh O@ z
cork
kh O@ k
cork-	wood
kh O@ k	w U d
corks
kh O@ k s
corksc-	rew
kh O@ k	s k r u:
corn
kh O@ n
corn-	bread
kh O@ n	b r e d
corn-	cob
kh O@ n	k Q b
corn-	field
kh O@ n	f i: l d
corn-	fields
kh O@ n	f i: l d z
corn-	flo-	wer
kh O@ n	f l aU	@r
corn-	flo-	wers
kh O@ n	f l aU	@r z
corn-	hus-	king
kh O@ n	h V s	k I N
corn-	husk
kh O@ n	h V s k
corn-	meal
kh O@ n	m i: l
corn-	wal-	lis
kh O@ n	w O:	l I s
corn-	wall
kh O@ n	w O: l
corn-	wall's
kh O@ n	w O: l z
corn-	well
kh O@ n	w e l
cornc-	rib
kh O@ n	k r I b
corns
kh O@ n z
corns-	talk
kh O@ n	s t O: k
corns-	talks
kh O@ n	s t O: k s
corns-	tarch
kh O@ n	s t Q@ tS
corp
kh O@ p
corp-	ses
kh O@ p	s V z
corp.
kh O@ p
corps
kh O@
corps-	man
kh O@	m V n
corpse
kh O@ p s
corr
kh O@
corse
kh O@ s
cort
kh O@ t
cort-	land
kh O@ t	l V n d
cortes
kh O@ t s
cos
kh O: s
cos-	by
kh O: z	b i:
cos-	by's
kh O: z	b i: z
cos-	grove
kh Q s	g r V v
cos-	ma
kh @U z	m V
cos-	me-	tic
kh Q z	m e	t I k
cos-	me-	tical-	ly
kh O: z	m e	t I k	l i:
cos-	me-	tics
kh Q z	m e	t I k s
cos-	me-	to-	lo-	gy
kh Q z	m V	t Q	l V	dZ i:
cos-	mic
kh Q z	m I k
cos-	mo
kh O: z	m @U
cos-	mo-	lo-	gy
kh O: z	m O:	l V	dZ i:
cos-	mo-	naut
kh O: z	m V	n O: t
cos-	mo-	nauts
kh O: z	m V	n O: t s
cos-	mo-	po-	li-	tan
kh Q z	m V	p Q	l V	t V n
cos-	mos
kh Q z	m @U s
cos-	mo's
kh Q z	m @U z
cos-	pon-	sor
kh @U s	p O: n	s @r
cos-	pon-	sors
kh @U s	p O: n	s @r z
cos-	sack
kh O:	s V k
cos-	sacks
kh Q	s { k s
cos-	set
kh Q	s V t
cos-	sette
kh V	s e t
cos-	ta
kh O: s	t V
cos-	tain
kh @U s	t eI n
cos-	tan-	za
kh @U s	t Q n	z V
cos-	tar
kh @U s	t Q@
cos-	tars
kh @U s	t Q@ z
cos-	ted
kh Q s	t V d
cos-	tel-	lo
kh O: s	t e	l @U
cos-	tel-	lo's
kh O: s	t e	l @U z
cos-	ten
kh O: s	t V n
cos-	ter
kh O: s	t @r
cos-	ti-	gan
kh Q s	t I	g { n
cos-	til-	la
kh @U s	t I	l V
cos-	tin
kh Q s	t I n
cos-	ting
kh O: s	t I N
cos-	tu-	mer
kh Q s	t u:	m @r
cos-	tu-	mers
kh Q s	t u:	m @r z
cos-	tume
kh Q s	t u: m
cos-	tumed
kh O: s	t u: m d
cos-	tumes
kh Q s	t u: m z
cose
kh @U z
cosme
kh @U z m
coss
kh O: s
cost
kh Q s t
cost-	co
kh O: s	t k @U
cost-	cut-	ting
kh O: s	t k V	t I N
cost-	li-	er
kh O: s	t l i:	@r
cost-	li-	est
kh O: s	t l i:	I s t
cost-	ly
kh Q s	t l i:
cost-	ner
kh Q s	t n @r
cost-	ner's
kh Q s	t n @r z
coste
kh @U s t
costs
kh Q s t s
cot
kh Q t
cot-	ta
kh Q	t V
cot-	ta-	ges
kh Q	t I	dZ V z
cot-	tage
kh Q	t V dZ
cot-	ter
kh Q	t @r
cot-	ti-	er
kh Q	t i:	@r
cot-	tle
kh Q	t V l
cot-	ton
kh Q	t V n
cot-	ton-	mouth
kh Q	t V n	m aU T
cot-	ton-	seed
kh Q	t V n	s i: d
cot-	ton-	wood
kh Q	t V n	w U d
cot-	ton-	woods
kh Q	t V n	w U d z
cot-	toned
kh Q	t V n d
cot-	tons
kh Q	t V n z
cot-	ton's
kh Q	t V n z
cot-	ty
kh Q	t i:
cote
kh @U t
cots
kh Q t s
cott
kh Q t
cott-	rell
kh Q t	r e l
cou
kh u:
cou-	ches
kh aU	tS V z
cou-	ders-	port
kh aU	d @r z	p O@ t
cou-	gar
kh u:	g @r
cou-	gars
kh u:	g @r z
cou-	ghing
kh Q	f I N
cou-	lee
kh u:	l i:
cou-	lom-	be
kh aU	l @U m	b i:
cou-	per
kh u:	@r
cou-	ple
kh V	p V l
cou-	pled
kh V	p V l d
cou-	ples
kh V	p V l z
cou-	po-	ning
kh u:	p Q	n I N
cou-	pon
kh u:	p O: n
cou-	pons
kh u:	p O: n z
cou-	ra-	geous
kh @r	eI	dZ V s
cou-	ra-	geous-	ly
kh @r	eI	dZ V s	l i:
cou-	rage
kh @r	V dZ
cou-	rant
kh U@	V n t
cou-	ri-	er
kh @r	i:	@r
cou-	ri-	ers
kh @r	i:	@r z
cou-	ri-	er's
kh @r	i:	@r z
cou-	sin
kh V	z I n
cou-	sins
kh V	z I n z
cou-	sin's
kh V	z I n z
cou-	sy
kh u:	z i:
cou-	tu-	ri-	er
kh u:	t U@	i:	@r
cou-	ture
kh u:	t U@
couch
kh aU tS
couch-	man
kh u: S	m { n
couched
kh aU tS t
cough
kh Q f
cough-	lin
kh O: g	l I n
coughed
kh Q f t
coughs
kh O: f s
coul-	dn't
kh U	d V n t
coul-	d've
kh U	d V v
coul-	son
kh aU l	s V n
coul-	ter
kh @U l	t @r
coul-	thard
kh u: l	T Q@ d
could
kh U d
coun-	ci-	lor
kh aU n	s V	l @r
coun-	ci-	lors
kh aU n	s V	l @r z
coun-	cil
kh aU n	s V l
coun-	cil-	man
kh aU n	s V l	m V n
coun-	cil-	men
kh aU n	s V l	m e n
coun-	cil-	wo-	man
kh aU n	s V l	w U	m V n
coun-	cil-	wo-	men
kh aU n	s V l	w I	m V n
coun-	cils
kh aU n	s V l z
coun-	cil's
kh aU n	s V l z
coun-	se-	ling
kh aU n	s V	l I N
coun-	se-	lor
kh aU n	s V	l @r
coun-	se-	lors
kh aU n	s V	l @r z
coun-	sel
kh aU n	s V l
coun-	sel-	lor
kh aU n	s V	l @r
coun-	sel-	lors
kh aU n	s V	l @r z
coun-	seled
kh aU n	s V l d
coun-	sels
kh aU n	s V l z
coun-	sel's
kh aU n	s V l z
coun-	ta-	ble
kh aU n	t V	b V l
coun-	te-	nan-	ces
kh aU n	t V	n V n	s V z
coun-	te-	nance
kh aU n	t V	n V n s
coun-	te-	nanced
kh aU n	t V	n V n s t
coun-	te-	rac-	ted
kh aU n	t @r	{ k	t V d
coun-	te-	rac-	ting
kh aU n	t @r	{ k	t I N
coun-	te-	ract
kh aU n	t @r	{ k t
coun-	te-	rat-	tack
kh aU n	t @r	V	t { k
coun-	te-	rat-	tacked
kh aU n	t @r	V	t { k t
coun-	te-	rat-	tacks
kh aU n	t @r	V	t { k s
coun-	te-	rof-	fen-	sive
kh aU n	t @r	O:	f e n	s I v
coun-	te-	rof-	fer
kh aU n	t @r	O:	f @r
coun-	te-	rof-	fers
kh aU n	t @r	O:	f @r z
coun-	ted
kh aU n	t V d
coun-	ter
kh aU n	t @r
coun-	ter-	ba-	lance
kh aU n	t @r	b {	l V n s
coun-	ter-	ba-	lanced
kh aU n	t @r	b {	l V n s t
coun-	ter-	bid
kh aU n	t @r	b I d
coun-	ter-	chal-	lenge
kh aU n	t @r	tS {	l V n dZ
coun-	ter-	char-	ges
kh aU n	t @r	tS Q@	dZ V z
coun-	ter-	charge
kh aU n	t @r	tS Q@ dZ
coun-	ter-	cul-	tu-	ral
kh aU n	t @r	k V l	tS @r	V l
coun-	ter-	cul-	ture
kh aU n	t @r	k V l	tS @r
coun-	ter-	es-	pi-	o-	nage
kh aU n	t @r	e s	p i:	V	n Q dZ
coun-	ter-	fei-	ted
kh aU n	t @r	f I	t V d
coun-	ter-	fei-	ter
kh aU n	t @r	f I	t @r
coun-	ter-	fei-	ters
kh aU n	t @r	f I	t @r z
coun-	ter-	fei-	ting
kh aU n	t @r	f I	t I N
coun-	ter-	feit
kh aU n	t @r	f I t
coun-	ter-	feits
kh aU n	t @r	f I t s
coun-	ter-	force
kh aU n	t @r	f O@ s
coun-	ter-	in-	sur-	gen-	cy
kh aU n	t @r	I n	s @r	dZ V n	s i:
coun-	ter-	in-	tel-	li-	gence
kh aU n	t @r	I n	t e	l I	dZ V n s
coun-	ter-	ing
kh aU n	t @r	I N
coun-	ter-	life
kh aU n	t @r	l aI f
coun-	ter-	man
kh aU n	t @r	m { n
coun-	ter-	mea-	sure
kh aU n	t @r	m e	Z @r
coun-	ter-	mea-	sures
kh aU n	t @r	m e	Z @r z
coun-	ter-	move
kh aU n	t @r	m u: v
coun-	ter-	moves
kh aU n	t @r	m u: v z
coun-	ter-	part
kh aU n	t @r	p Q@ t
coun-	ter-	parts
kh aU n	t @r	p Q@ t s
coun-	ter-	point
kh aU n	t @r	p OI n t
coun-	ter-	pro-	duc-	tive
kh aU n	t @r p	r V	d V k	t I v
coun-	ter-	pro-	po-	sal
kh aU n	t @r p	r V	p @U	z V l
coun-	ter-	pro-	po-	sals
kh aU n	t @r p	r V	p @U	z V l z
coun-	ter-	punch
kh aU n	t @r	p V n tS
coun-	ter-	re-	vo-	lu-	tio-	na-	ry
kh aU n	t @r	r e	v V	l u:	S V	n e@	i:
coun-	ter-	re-	vo-	lu-	tion
kh aU n	t @r	r e	v V	l u:	S V n
coun-	ter-	sue
kh aU n	t @r	s u:
coun-	ter-	sued
kh aU n	t @r	s u: d
coun-	ter-	suit
kh aU n	t @r	s u: t
coun-	ter-	te-	nor
kh aU n	t @r	t e	n @r
coun-	ter-	ter-	ro-	ri-	sm
kh aU n	t @r	t e@	@r	I	z V m
coun-	ter-	ter-	ro-	rist
kh aU n	t @r	t e@	@r	I s t
coun-	ter-	top
kh aU n	t @r	t Q p
coun-	ter-	trade
kh aU n	t @r t	r eI d
coun-	ter-	vai-	ling
kh aU n	t @r	v eI	l I N
coun-	ter-	weight
kh aU n	t @r	w eI t
coun-	terc-	laim
kh aU n	t @r k	l eI m
coun-	terc-	laims
kh aU n	t @r k	l eI m z
coun-	terc-	lock-	wise
kh aU	t @r k	l O: k	w aI z
coun-	tered
kh aU n	t @r d
coun-	ters
kh aU n	t @r z
coun-	tess
kh aU n	t V s
coun-	ties
kh aU n	t i: z
coun-	ting
kh aU n	t I N
coun-	ty
kh aU n	t i:
coun-	ty's
kh aU n	t i: z
counce
kh aU n s
count
kh aU n t
count-	down
kh aU n	t d aU n
count-	downs
kh aU n	t d aU n z
count-	less
kh aU n	t l V s
count-	ries
kh V n	t r i: z
count-	ry
kh V n	t r i:
count-	ry-	folk
kh V n	t r i:	f @U k
count-	ry-	man
kh V n	t r i:	m V n
count-	ry-	men
kh V n	t r i:	m e n
count-	ry-	side
kh V n	t r i:	s aI d
count-	ry-	wide
kh V n	t r i:	w aI d
count-	ry's
kh V n	t r i: z
counts
kh aU n t s
coup
kh u:
coup-	land
kh u: p	l V n d
coup-	ler
kh V p	l @r
coup-	lers
kh V p	l @r z
coup-	le's
kh V	p V l z
coup-	ling
kh V p	l I N
coup-	lings
kh V p	l I N z
coupe
kh u: p
coupes
kh u: p s
coups
kh u: z
cour-	ser
kh O@	s @r
cour-	ses
kh O@	s V z
cour-	se's
kh O@	s V z
cour-	sey
kh O@	s i:
cour-	sing
kh O@	s I N
cour-	te-	nay
kh @r	t V	n eI
cour-	te-	ous
kh @r	t i:	V s
cour-	te-	sies
kh @r	t V	s i: z
cour-	te-	sy
kh @r	t V	s i:
cour-	ted
kh O@	t V d
cour-	ter
kh O@	t @r
cour-	ti-	er
kh O@	t i:	@r
cour-	ti-	ers
kh O@	t i:	@r z
cour-	ting
kh O@	t I N
cour-	tois
kh O@ t	w Q
course
kh O@ s
court
kh O@ t
court-	hou-	ses
kh O@ t	h aU	s V z
court-	house
kh O@ t	h aU s
court-	land
kh O@ t	l { n d
court-	ly
kh O@ t	l i:
court-	ney
kh O@ t	n i:
court-	room
kh O@ t	r u: m
court-	rooms
kh O@ t	r u: m z
court-	ship
kh O@	tS I p
court-	yard
kh O@ t	j Q@ d
court-	yards
kh O@ t	j Q@ d z
courts
kh O@ t s
court's
kh O@ t s
cous-	teau
kh u: s	t @U
cove
kh @U v
coves
kh @U v z
cow
kh aU
cow-	bell
kh aU	b e l
cow-	bells
kh aU	b e l z
cow-	boy
kh aU	b OI
cow-	boys
kh aU	b OI z
cow-	boy's
kh aU	b OI z
cow-	den
kh aU	d V n
cow-	gill
kh aU	g I l
cow-	girl
kh aU	g @r l
cow-	girls
kh aU	g @r l z
cow-	herd
kh aU	h @r d
cow-	les
kh aU	V l z
cow-	ley
kh aU	l i:
cow-	ling
kh aU	l I N
cow-	lings
kh aU	l I N z
cow-	ling's
kh aU	l I N z
cow-	man
kh aU	m V n
cow-	per
kh aU	p @r
cow-	ries
kh aU	r i: z
cowd-	rey
kh aU d	r i:
cowed
kh aU d
cowl
kh aU l
cows
kh aU z
cow's
kh aU z
cows-	lip
kh aU s	l I p
cox
kh Q k s
cox-	well
kh Q k	s w e l
coy
kh OI
coy-	ly
kh OI	l i:
coyle
kh OI l
cr-	a-	ry
kh @r	e@	i:
cr-	yan
kh r aI	V n
cra-	d-	ling
kh r eI	d V	l I N
cra-	dle
kh r eI	d V l
cra-	dles
kh r eI	d V l z
cra-	dock
kh r {	d V k
cra-	ker
kh r eI	k @r
cra-	mer
kh r eI	m @r
cra-	mer's
kh r eI	m @r z
cra-	ner
kh r eI	n @r
cra-	ney
kh r eI	n i:
cra-	po
kh r Q	p @U
cra-	shes
kh r {	S V z
cra-	shing
kh r {	S I N
cra-	ter
kh r eI	t @r
cra-	tered
kh r eI	t @r d
cra-	ters
kh r eI	t @r z
cra-	ting
kh r eI	t I N
cra-	ton
kh r {	t V n
cra-	ven
kh r eI	v V n
cra-	vens
kh r eI	v V n z
cra-	ven's
kh r eI	v V n z
cra-	ver
kh r eI	v @r
cra-	ving
kh r eI	v I N
cra-	vings
kh r eI	v I N z
cra-	yon
kh r eI	Q n
cra-	yons
kh r eI	Q n z
cra-	zi-	er
kh r eI	z i:	@r
cra-	zi-	est
kh r eI	z i:	V s t
cra-	zi-	ly
kh r eI	z I	l i:
cra-	zi-	ness
kh r eI	z i:	n V s
cra-	zies
kh r eI	z i: z
cra-	zy
kh r eI	z i:
crab-	meat
kh r { b	m i: t
crab-	tree
kh r { b	t r i:
crabs
kh r { b z
crac-	ker
kh r {	k @r
crac-	ker-	jack
kh r {	k @r	dZ { k
crac-	kers
kh r {	k @r z
crac-	king
kh r {	k I N
crac-	kle
kh r {	k V l
crac-	kled
kh r {	k V l d
crac-	kles
kh r {	k V l z
crack
kh r { k
crack-	down
kh r { k	d aU n
crack-	downs
kh r { k	d aU n z
crack-	ling
kh r { k	l I N
crack-	pot
kh r { k	p Q t
crack-	pots
kh r { k	p Q t s
cracked
kh r { k t
cracks
kh r { k s
crad-	dock
kh r {	d V k
craf-	ted
kh r { f	t V d
craf-	ting
kh r { f	t I N
craf-	ton
kh r { f	t V n
craf-	ty
kh r { f	t i:
craft
kh r { f t
crafts
kh r { f t s
craft's
kh r { f t s
crafts-	man
kh r { f	t s m V n
crafts-	man-	ship
kh r { f	t s m V n	S I p
crafts-	men
kh r { f	t s m V n
crafts-	peo-	ple
kh r { f	t s p i:	p V l
crag-	gy
kh r {	g i:
crai-	gie
kh r eI	g i:
craig
kh r eI g
craig's
kh r eI g z
crain
kh r eI n
crain's
kh r eI n z
cram
kh r { m
cram-	mer
kh r {	m @r
cram-	ming
kh r {	m I N
cram-	ping
kh r { m	p I N
crames
kh r eI m z
crammed
kh r { m d
cramp
kh r { m p
cramped
kh r { m p t
cramps
kh r { m p s
crams
kh r { m z
cran-	ber-	ries
kh r { n	b e@	i: z
cran-	ber-	ry
kh r { n	b e@	i:
cran-	dall
kh r { n	d V l
cran-	dall's
kh r { n	d V l z
cran-	dell
kh r { n	d V l
cran-	field
kh r { n	f i: l d
cran-	ford
kh r { n	f @r d
cran-	king
kh r { N	k I N
cran-	ky
kh r { N	k i:
cran-	mer
kh r { n	m @r
cran-	nies
kh r {	n i: z
cran-	ny
kh r {	n i:
cran-	shaw
kh r { n	S O:
crance
kh r { n s
crane
kh r eI n
craned
kh r eI n d
cranes
kh r eI n z
crane's
kh r eI n z
cranes-	bill
kh r eI n	z b I l
cranes-	bills
kh r eI n	z b I l z
crank
kh r { N k
crank-	shaft
kh r { N	k S { f t
crank-	shafts
kh r { N	k S { f t s
cranked
kh r { N k t
cranks
kh r { N k s
crans
kh r { n z
crans-	ton
kh r { n	s t V n
crans-	ton's
kh r { n	s t V n z
crap
kh r { p
crap-	pie
kh r {	p i:
crap-	shoot
kh r { p	S u: t
craps
kh r { p s
crash
kh r { S
crashed
kh r { S t
crass
kh r { s
crate
kh r eI t
crates
kh r eI t s
crave
kh r eI v
craved
kh r eI v d
craves
kh r eI v z
craw
kh r O:
craw-	fish
kh r O:	f I S
craw-	ford
kh r O:	f @r d
craw-	ford's
kh r O:	f @r d z
craw-	fords-	ville
kh r O:	f @r d	z v I l
craw-	ley
kh r O:	l i:
craw-	ling
kh r O:	l I N
craw-	ly
kh r O:	l i:
crawl
kh r O: l
crawled
kh r O: l d
crawls
kh r O: l z
cray
kh r eI
cray-	fish
kh r eI	f I S
crayne
kh r eI n
crays
kh r eI z
cray's
kh r eI z
craze
kh r eI z
crazed
kh r eI z d
cre-	a-	ted
kh r i:	eI	t V d
cre-	a-	ti-	vi-	ty
kh r i:	eI	t I	v I	t i:
cre-	a-	ting
kh r i:	eI	t I N
cre-	a-	tio-	ni-	sm
kh r i:	eI	S V	n I	z V m
cre-	a-	tion
kh r i:	eI	S V n
cre-	a-	tions
kh r i:	eI	S V n z
cre-	a-	tive
kh r i:	eI	t I v
cre-	a-	tive-	ly
kh r i:	eI	t I v	l i:
cre-	a-	tive-	ness
kh r i:	eI	t I v	n V s
cre-	a-	tor
kh r i:	eI	t @r
cre-	a-	tors
kh r i:	eI	t @r z
cre-	ate
kh r i:	eI t
cre-	ates
kh r i:	eI t s
cre-	den-	tial
kh r V	d e n	tS V l
cre-	den-	tialed
kh r V	d e n	tS V l d
cre-	den-	tials
kh r V	d e n	S V l z
cre-	dence
kh r i:	d V n s
cre-	di-	bi-	li-	ty
kh r e	d V	b I	l I	t i:
cre-	di-	ble
kh r e	d I	b V l
cre-	di-	ta-	ble
kh r e	d I	t V	b V l
cre-	di-	ta-	bly
kh r e	d I	t V b	l i:
cre-	di-	ted
kh r e	d I	t V d
cre-	di-	ting
kh r e	d I	t I N
cre-	di-	tor
kh r e	d I	t @r
cre-	di-	tors
kh r e	d I	t @r z
cre-	dib-	ly
kh r e	d I b	l i:
cre-	dit
kh r e	d I t
cre-	dit-	wor-	thi-	ness
kh r e	d I t	w @r	D i:	n V s
cre-	dit-	wor-	thy
kh r e	d I t	w @r	D i:
cre-	dits
kh r e	d I t s
cre-	dit's
kh r e	d I t s
cre-	do
kh r eI	d @U
cre-	du-	li-	ty
kh r V	d u:	l I	t i:
cre-	ma-	ted
kh r i:	m eI	t V d
cre-	ma-	tion
kh r i:	m eI	S V n
cre-	ma-	to-	ri-	a
kh r i:	m V	t O@	i:	V
cre-	ma-	to-	ri-	um
kh r i:	m V	t O@	i:	V m
cre-	mate
kh r i:	m eI t
cre-	mer
kh r i:	m @r
cre-	ne-	la-	ted
kh r e	n V	l eI	t V d
cre-	ne-	late
kh r e	n V	l eI t
cre-	o-	lize
kh r i:	@U	l aI z
cre-	o-	lized
kh r i:	@U	l aI z d
cre-	o-	sote
kh r i:	V	s @U t
cre-	ole
kh r i:	@U l
cre-	oles
kh r i:	@U l z
cre-	scen-	do
kh r I	S e n	d @U
cre-	scent
kh r e	s V n t
cre-	spi
kh r e s	p i:
cre-	ta-	ceous
kh r V	t eI	S V s
cre-	vi-	ces
kh r e	v V	s V z
cre-	vice
kh r e	v V s
cre-	wel
kh r u:	V l
crea
kh r i:
crea-	king
kh r i:	k I N
crea-	ky
kh r i:	k i:
crea-	me-	ry
kh r i:	m @r	i:
crea-	mer
kh r i:	m @r
crea-	mi-	er
kh r i:	m i:	@r
crea-	mi-	est
kh r i:	m i:	V s t
crea-	my
kh r i:	m i:
crea-	ses
kh r i:	s V z
crea-	sy
kh r i:	s i:
crea-	ture
kh r i:	tS @r
crea-	tures
kh r i:	tS @r z
creach
kh r i: tS
creagh
kh r i: g
creak
kh r i: k
creaked
kh r i: k t
cream
kh r i: m
creamed
kh r i: m d
creams
kh r i: m z
crean
kh r i: n
crease
kh r i: s
creath
kh r e T
cree
kh r i:
cree-	don
kh r i:	d V n
cree-	pi-	ness
kh r i:	p i:	n V s
cree-	ping
kh r i:	p I N
cree-	py
kh r i:	p i:
creed
kh r i: d
creeds
kh r i: d z
creek
kh r i: k
creeks
kh r i: k s
creek's
kh r i: k s
creel
kh r i: l
creep
kh r i: p
creeps
kh r i: p s
crees
kh r i: z
creigh-	ton
kh r eI	t V n
creme
kh r i: m
cren-	shaw
kh r e n	S O:
crepe
kh r eI p
crepes
kh r eI p s
crept
kh r e p t
cres-	po
kh r e s	p @U
cres-	ses
kh r e	s V z
cres-	sey
kh r e	s i:
cres-	son
kh r e	s V n
cres-	sy
kh r e	s i:
cres-	ted
kh r e s	t V d
cres-	ting
kh r e s	t I N
cres-	well
kh r e s	w e l
cress
kh r e s
cress-	ler
kh r e s	l @r
crest
kh r e s t
crest-	fal-	len
kh r e s	t f O:	l V n
crests
kh r e s t s
crete
kh r i: t
crew
kh r u:
crew-	man
kh r u:	m V n
crew-	men
kh r u:	m e n
crewe
kh r u:
crewes
kh r u: z
crews
kh r u: z
crew's
kh r u: z
cri-	er
kh r aI	@r
cri-	me-	a
kh r aI	m i:	V
cri-	mean
kh r V	m i: n
)"
R"(cri-	mi-	na-	li-	ty
kh r I	m I	n {	l I	t i:
cri-	mi-	na-	li-	za-	tion
kh r I	m I	n V	l I	z eI	S V n
cri-	mi-	na-	li-	zing
kh r I	m I	n V	l aI	z I N
cri-	mi-	na-	lis-	tics
kh r I	m I	n V	l I s	t I k s
cri-	mi-	na-	list
kh r I	m I	n V	l I s t
cri-	mi-	na-	lists
kh r I	m I	n V	l I s t s
cri-	mi-	na-	list's
kh r I	m I	n V	l I s t s
cri-	mi-	na-	lize
kh r I	m I	n V	l aI z
cri-	mi-	na-	lized
kh r I	m I	n V	l aI z d
cri-	mi-	nal
kh r I	m I	n V l
cri-	mi-	nal-	ly
kh r I	m I	n V	l i:
cri-	mi-	nals
kh r I	m I	n V l z
cri-	mi-	nal's
kh r I	m I	n V l z
cri-	mi-	no-	lo-	gist
kh r I	m I	n Q	l V	dZ I s t
cri-	mi-	no-	lo-	gists
kh r I	m I	n Q	l V	dZ I s t s
cri-	mi-	no-	lo-	gy
kh r I	m I	n Q	l V	dZ i:
cri-	ses
kh r aI	s i: z
cri-	sis
kh r aI	s I s
cri-	ti-	cal-	ly
kh r I	t I	k V	l i:
cri-	ti-	ci-	sm
kh r I	t I	s I	z V m
cri-	ti-	ci-	sms
kh r I	t I	s I	z V m z
cri-	ti-	ci-	zes
kh r I	t I	s aI	z V z
cri-	ti-	ci-	zing
kh r I	t I	s aI	z I N
cri-	ti-	cize
kh r I	t I	s aI z
cri-	ti-	cized
kh r I	t I	s aI z d
cri-	ti-	quing
kh r V	t i:	k I N
cri-	tics
kh r I	t I k s
cri-	tic's
kh r I	t I k s
)"