R"(re-	col-	lec-	ting
r e	k V	l e k	t I N
re-	col-	lec-	tion
r e	k V	l e k	S V n
re-	col-	lec-	tions
r e	k V	l e k	S V n z
re-	col-	lect
r e	k V	l e k t
re-	col-	lects
r e	k V	l e k t s
re-	com-	bi-	nant
r I	k Q m	b I	n V n t
re-	com-	bine
r i:	k V m	b aI n
re-	com-	men-	da-	tion
r e	k V	m V n	d eI	S V n
re-	com-	men-	da-	tions
r e	k V	m V n	d eI	S V n z
re-	com-	men-	ded
r e	k V	m e n	d V d
re-	com-	men-	ding
r e	k V	m e n	d I N
re-	com-	mend
r e	k V	m e n d
re-	com-	mends
r e	k V	m e n d z
re-	com-	mit
r I	k Q	m I t
re-	com-	pense
r e	k V m	p e n s
re-	con
r i:	k O: n
re-	con-	ci-	li-	a-	tion
r e	k V n	s I	l i:	eI	S V n
re-	con-	ci-	li-	a-	tions
r e	k V n	s I	l i:	eI	S V n z
re-	con-	ci-	ling
r e	k V n	s aI	l I N
re-	con-	cile
r e	k V n	s aI l
re-	con-	ciled
r e	k V n	s aI l d
re-	con-	ciles
r e	k V n	s aI l z
re-	con-	di-	tio-	ning
r i:	k V n	d I	S V	n I N
re-	con-	di-	tion
r i:	k V n	d I	S V n
re-	con-	di-	tioned
r i:	k V n	d I	S V n d
re-	con-	dite
r e	k V n	d aI t
re-	con-	fi-	gu-	ra-	tion
r i:	k V n	f I g	j @r	eI	S V n
re-	con-	fi-	gure
r i:	k V n	f I g	j @r
re-	con-	fi-	gured
r i:	k V n	f I g	j @r d
re-	con-	fir-	ma-	tion
r i:	k Q n	f @r	m eI	S V n
re-	con-	firm
r i:	k V n	f @r m
re-	con-	firmed
r i:	k V n	f @r m d
re-	con-	nais-	sance
r i:	k Q	n V	s V n s
re-	con-	nec-	ted
r i:	k V	n e k	t V d
re-	con-	nec-	ting
r i:	k V	n e k	t I N
re-	con-	nect
r i:	k V	n e k t
re-	con-	nects
r i:	k V	n e k t s
re-	con-	quer
r i:	k O: N	k @r
re-	con-	quered
r i:	k O: N	k @r d
re-	con-	si-	de-	ra-	tion
r i:	k V n	s I	d @r	eI	S V n
re-	con-	si-	de-	ring
r i:	k V n	s I	d @r	I N
re-	con-	si-	der
r i:	k V n	s I	d @r
re-	con-	si-	dered
r i:	k V n	s I	d @r d
re-	con-	sti-	tu-	ted
r i:	k Q n	s t I	t u:	t I d
re-	con-	sti-	tu-	ting
r i:	k Q n	s t I	t u:	t I N
re-	con-	sti-	tute
r i:	k Q n	s t I	t u: t
re-	con-	struc-	ted
r i:	k V n	s t r V k	t V d
re-	con-	struc-	ting
r i:	k V n	s t r V k	t I N
re-	con-	struc-	tion
r i:	k V n	s t r V k	S V n
re-	con-	struc-	tions
r i:	k V n	s t r V k	S V n z
re-	con-	struc-	tive
r i:	k V n	s t r V k	t I v
re-	con-	struct
r i:	k V n	s t r V k t
re-	con-	vene
r i:	k V n	v i: n
re-	con-	vened
r i:	k V n	v i: n d
re-	con-	venes
r i:	k V n	v i: n z
re-	cor-	da-	ble
r I	k O@	d V	b V l
re-	cor-	ded
r V	k O@	d V d
re-	cor-	der
r I	k O@	d @r
re-	cor-	ders
r I	k O@	d @r z
re-	cor-	ding
r V	k O@	d I N
re-	cor-	dings
r I	k O@	d I N z
re-	cord
r V	k O@ d
re-	cords
r V	k O@ d z
re-	cord's
r e	k @r d z
re-	cou-	ping
r I	k u:	p I N
re-	coun-	ted
r I	k aU n	t V d
re-	coun-	ting
r I	k aU n	t I N
re-	count
r I	k aU n t
re-	counts
r i:	k aU n t s
re-	coup
r I	k u: p
re-	couped
r I	k u: p t
re-	coups
r I	k u: p s
re-	course
r i:	k O@ s
re-	cove-	ry
r I	k V v	r i:
re-	cre-	a-	ted
r e k	r i:	eI	t V d
re-	cre-	a-	ting
r e k	r i:	eI	t I N
re-	cre-	a-	tio-	nal
r e k	r i:	eI	S V	n V l
re-	cre-	a-	tion
r e k	r i:	eI	S V n
re-	cre-	ate
r e k	r i:	eI t
re-	cre-	ates
r e k	r i:	eI t s
re-	cri-	mi-	na-	tion
r I k	r I	m I	n eI	S V n
re-	cri-	mi-	na-	tions
r I k	r I	m I	n eI	S V n z
re-	cri-	mi-	nate
r I k	r I	m I	n eI t
re-	cu-	pe-	ra-	ting
r I	k u:	p @r	eI	t I N
re-	cu-	pe-	ra-	tion
r I	k u:	p @r	eI	S V n
re-	cu-	pe-	ra-	tive
r I	k u:	p @r	V	t I v
re-	cu-	pe-	rate
r I	k u:	p @r	eI t
re-	cu-	sal
r I k	j u:	z V l
re-	cu-	sing
r I k	j u:	z I N
re-	cur
r I	k @r
re-	cur-	rence
r I	k @r	V n s
re-	cur-	rent
r I	k @r	V n t
re-	cur-	ring
r I	k @r	I N
re-	curred
r i:	k @r d
re-	cuse
r I k	j u: z
re-	cused
r I k	j u: z d
re-	cy-	c-	ling
r i:	s aI	k V	l I N
re-	cy-	cle
r i:	s aI	k V l
re-	cy-	cled
r i:	s aI	k V l d
re-	cy-	cles
r i:	s aI	k V l z
re-	cyc-	la-	ble
r i:	s aI k	l V	b V l
re-	cyc-	la-	bles
r i:	s aI k	l V	b V l z
re-	cyc-	ler
r i:	s aI k	l @r
re-	cyc-	lers
r i:	s aI k	l @r z
re-	dac-	ted
r V	d { k	t V d
re-	dac-	ting
r V	d { k	t I N
re-	dact
r V	d { k t
re-	de-	co-	ra-	ted
r i:	d e	k @r	eI	t V d
re-	de-	co-	ra-	ting
r i:	d e	k @r	eI	t I N
re-	de-	co-	ra-	tion
r i:	d e	k @r	eI	S V n
re-	de-	co-	rate
r i:	d e	k @r	eI t
re-	de-	di-	ca-	tion
r i:	d e	d I	k eI	S V n
re-	de-	di-	cate
r i:	d e	d I	k eI t
re-	de-	fi-	ni-	tion
r i:	d e	f V	n I	S V n
re-	de-	fi-	ning
r i:	d V	f aI	n I N
re-	de-	fine
r i:	d V	f aI n
re-	de-	fined
r i:	d V	f aI n d
re-	de-	fines
r i:	d V	f aI n z
re-	de-	plo-	ying
r i:	d V p	l OI	I N
re-	de-	ploy
r i:	d V p	l OI
re-	de-	ploy-	ment
r i:	d V p	l OI	m V n t
re-	de-	ploy-	ments
r i:	d V p	l OI	m V n t s
re-	de-	ployed
r i:	d V p	l OI d
re-	de-	po-	si-	tion
r i:	d e	p V	z I	S V n
re-	de-	sig-	ning
r i:	d V	z aI	n I N
re-	de-	sign
r i:	d V	z aI n
re-	de-	signed
r i:	d V	z aI n d
re-	de-	ve-	lop
r i:	d I	v e	l V p
re-	de-	ve-	lop-	ment
r i:	d I	v e	l V p	m V n t
re-	dee-	ma-	ble
r V	d i:	m V	b V l
re-	dee-	ming
r V	d i:	m I N
re-	deem
r V	d i: m
re-	deemed
r V	d i: m d
re-	deems
r V	d i: m z
re-	demp-	tion
r V	d e m	p S V n
re-	demp-	tions
r V	d e m	p S V n z
re-	demp-	tive
r V	d e m	p t I v
re-	di-	al
r i:	d aI	V l
re-	di-	rec-	ted
r i:	d @r	e k	t V d
re-	di-	rec-	ting
r i:	d @r	e k	t I N
re-	di-	rec-	tion
r i:	d @r	e k	S V n
re-	di-	rect
r i:	d @r	e k t
re-	did
r i:	d I d
re-	dif-	fu-	sion
r i:	d I f	j u:	Z V n
re-	ding
r i:	d I N
re-	dis-	co-	ve-	ring
r i:	d I s	k V	v @r	I N
re-	dis-	co-	ver
r i:	d I s	k V	v @r
re-	dis-	co-	vered
r i:	d I s	k V	v @r d
re-	dis-	cove-	ry
r i:	d I s	k V v	r i:
re-	dis-	play
r i:	d I s	p l eI
re-	dis-	tri-	bu-	ted
r i:	d I s	t r I b	j u:	t I d
re-	dis-	tri-	bu-	ting
r i:	d I s	t r I b	j u:	t I N
re-	dis-	tri-	bu-	tion
r i:	d I s	t r I b	j u:	S V n
re-	dis-	tri-	bu-	tive
r i:	d I s	t r I b	j u:	t I v
re-	dis-	tri-	bute
r i:	d I s	t r I b	j u: t
re-	dis-	tric-	ting
r i:	d I s	t r I k	t I N
re-	do
r i:	d u:
re-	do-	ing
r i:	d u:	I N
re-	don-	do
r V	d Q n	d @U
re-	done
r i:	d V n
re-	dou-	b-	ling
r i:	d V	b V	l I N
re-	dou-	ble
r i:	d V	b V l
re-	dou-	bled
r i:	d V	b V l d
re-	doub-	ta-	ble
r V	d aU	t V	b V l
re-	doubt
r V	d aU t
re-	dound
r V	d aU n d
re-	dress
r V d	r e s
re-	du-	ces
r V	d u:	s V z
re-	du-	ci-	ble
r V	d u:	s V	b V l
re-	du-	cing
r V	d u:	s I N
re-	duc-	tion
r V	d V k	S V n
re-	duc-	tions
r i:	d V k	S V n z
re-	duce
r V	d u: s
re-	duced
r V	d u: s t
re-	dun-	dan-	cies
r V	d V n	d V n	s i: z
re-	dun-	dan-	cy
r V	d V n	d V n	s i:
re-	dun-	dant
r V	d V n	d V n t
re-	e-	du-	ca-	tion
r i:	e d	j V	k eI	S V n
re-	e-	du-	cate
r i:	e	dZ V	k eI t
re-	e-	lec-	ted
r i:	V	l e k	t V d
re-	e-	lec-	ting
r i:	V	l e k	t I N
re-	e-	lec-	tion
r i:	V	l e k	S V n
re-	e-	lect
r i:	V	l e k t
re-	e-	mer-	gence
r i:	V	m @r	dZ V n s
re-	e-	merge
r i:	V	m @r dZ
re-	e-	merged
r i:	V	m @r dZ d
re-	e-	nac-	ted
r i:	V	n { k	t V d
re-	e-	nact
r i:	V	n { k t
re-	e-	nact-	ment
r i:	V	n { k	t m V n t
re-	e-	nact-	ments
r i:	V	n { k	t m V n t s
re-	e-	nacts
r i:	V	n { k t s
re-	e-	va-	lu-	a-	ted
r i:	V	v { l	j u:	eI	t V d
re-	e-	va-	lu-	a-	ting
r i:	V	v { l	j u:	eI	t I N
re-	e-	va-	lu-	a-	tion
r i:	V	v { l	j u:	eI	S V n
re-	e-	va-	lu-	ate
r i:	V	v {	l u:	eI t
re-	e-	xa-	mi-	na-	tion
r i:	I g	z {	m I	n eI	S V n
re-	e-	xa-	mi-	ning
r i:	I g	z {	m I	n I N
re-	e-	xa-	mine
r i:	e g	z {	m I n
re-	e-	xa-	mined
r i:	I g	z {	m I n d
re-	em-	pha-	size
r i:	e m	f V	s aI z
re-	em-	ploy-	ment
r i:	V m	p l OI	m V n t
re-	en-	gi-	nee-	ring
r i:	e n	dZ I	n I@	I N
re-	en-	gi-	neer
r i:	e n	dZ I	n I@
re-	en-	te-	ring
r i:	I n	t @r	I N
re-	en-	ter
r i:	I n	t @r
re-	en-	tered
r i:	I n	t @r d
re-	ent-	ry
r i:	I n	t r i:
re-	es-	tab-	li-	shing
r i:	V s	t { b	l I	S I N
re-	es-	tab-	lish
r i:	V s	t { b	l I S
re-	es-	tab-	lished
r i:	V s	t { b	l I S t
re-	ex-	port
r i:	e k	s p O@ t
re-	ex-	ports
r i:	e k	s p O@ t s
re-	fe-	ree
r e	f @r	i:
re-	fe-	rees
r e	f @r	i: z
re-	fe-	ree's
r e	f @r	i: z
re-	fe-	ren-	ces
r e	f @r	V n	s V z
re-	fe-	ren-	cing
r e	f @r	V n	s I N
re-	fe-	ren-	da
r e	f @r	e n	d V
re-	fe-	ren-	dum
r e	f @r	e n	d V m
re-	fe-	ren-	dums
r e	f @r	e n	d V m z
re-	fe-	rence
r e	f @r	V n s
re-	fe-	renced
r e	f @r	V n s t
re-	fer
r V	f @r
re-	fer-	ral
r V	f @r	V l
re-	fer-	rals
r V	f @r	V l z
re-	fer-	ring
r V	f @r	I N
re-	ferred
r V	f @r d
re-	fers
r V	f @r z
re-	fi-	nan-	ces
r i:	f I	n { n	s V z
re-	fi-	nan-	cing
r i:	f I	n { n	s I N
re-	fi-	nan-	cings
r i:	f I	n { n	s I N z
re-	fi-	nance
r i:	f I	n { n s
re-	fi-	nanced
r i:	f I	n { n s t
re-	fi-	ne-	ries
r V	f aI	n @r	i: z
re-	fi-	ne-	ry
r V	f aI	n @r	i:
re-	fi-	ne-	ry's
r V	f aI	n @r	i: z
re-	fi-	ner
r V	f aI	n @r
re-	fi-	ners
r V	f aI	n @r z
re-	fi-	ni-	shing
r i:	f I	n I	S I N
re-	fi-	ning
r V	f aI	n I N
re-	fi-	nish
r i:	f I	n I S
re-	fi-	nished
r i:	f I	n I S t
re-	file
r i:	f aI l
re-	filed
r i:	f aI l d
re-	fill
r i:	f I l
re-	filled
r i:	f I l d
re-	fills
r i:	f I l z
re-	fine
r V	f aI n
re-	fine-	ment
r V	f aI n	m V n t
re-	fine-	ments
r V	f aI n	m V n t s
re-	fined
r V	f aI n d
re-	fines
r V	f aI n z
re-	fit
r i:	f I t
re-	fit-	ted
r i:	f I	t V d
re-	fit-	ting
r i:	f I	t I N
re-	fo-	cu-	ses
r i:	f @U	k V	s V z
re-	fo-	cu-	sing
r i:	f @U	k V	s I N
re-	fo-	cus
r i:	f @U	k V s
re-	fo-	cused
r i:	f @U	k V s t
re-	fo-	res-	ta-	tion
r i:	f O@	V s	t eI	S V n
re-	fo-	rest
r i:	f O@	V s t
re-	for-	ma-	tion
r e	f @r	m eI	S V n
re-	for-	ma-	to-	ries
r V	f O@	m V	t O@	i: z
re-	for-	ma-	to-	ry
r V	f O@	m V	t O@	i:
re-	for-	mer
r V	f O@	m @r
re-	for-	mers
r V	f O@	m @r z
re-	for-	ming
r V	f O@	m I N
re-	for-	mist
r V	f O@	m I s t
re-	for-	mists
r V	f O@	m I s t s
re-	for-	mu-	la-	ted
r i:	f O@ m	j V	l eI	t V d
re-	for-	mu-	late
r i:	f O@ m	j V	l eI t
re-	form
r V	f O@ m
re-	formed
r V	f O@ m d
re-	forms
r V	f O@ m z
re-	frac-	tive
r V f	r { k	t I v
re-	frac-	to-	ries
r V f	r { k	t @r	i: z
re-	frac-	to-	ry
r V f	r { k	t @r	i:
re-	frac-	tor
r V f	r { k	t @r
re-	frac-	tors
r V f	r { k	t @r z
re-	frai-	ning
r V f	r eI	n I N
re-	frain
r V f	r eI n
re-	frained
r V f	r eI n d
re-	frains
r V f	r eI n z
re-	fre-	sher
r V f	r e	S @r
re-	fre-	shes
r V f	r e	S V z
re-	fre-	shing
r V f	r e	S I N
re-	fre-	shing-	ly
r i: f	r e	S I N	l i:
re-	fresh
r V f	r e S
re-	fresh-	ment
r V f	r e S	m V n t
re-	fresh-	ments
r V f	r e S	m V n t s
re-	freshed
r i: f	r e S t
re-	fri-	ge-	ra-	ted
r V f	r I	dZ @r	eI	t V d
re-	fri-	ge-	ra-	tion
r V f	r I	dZ @r	eI	S V n
re-	fri-	ge-	ra-	tor
r V f	r I	dZ @r	eI	t @r
re-	fri-	ge-	ra-	tors
r V f	r I	dZ @r	eI	t @r z
re-	fri-	ge-	rant
r V f	r I	dZ @r	V n t
re-	fri-	ge-	rants
r V f	r I	dZ @r	V n t s
re-	fri-	ge-	rate
r V f	r I	dZ @r	eI t
re-	fu-	e-	ling
r i: f	j u:	V	l I N
re-	fu-	el
r i: f	j u:	V l
re-	fu-	eled
r i: f	j u:	V l d
re-	fu-	gee
r e f	j u:	dZ i:
re-	fu-	gees
r e f	j u:	dZ i: z
re-	fu-	ges
r e f	j u:	dZ V z
re-	fu-	ge's
r e f	j u:	dZ V z
re-	fu-	sal
r V f	j u:	z V l
re-	fu-	sals
r V f	j u:	z V l z
re-	fu-	ses
r V f	j u:	z V z
re-	fu-	sing
r V f	j u:	z I N
re-	fu-	ta-	tion
r e f	j u:	t eI	S V n
re-	fu-	ted
r V f	j u:	t V d
re-	fu-	ting
r V f	j u:	t I N
re-	fuge
r e f	j u: dZ
re-	fun-	da-	ble
r V	f V n	d V	b V l
re-	fun-	ded
r V	f V n	d V d
re-	fun-	ding
r V	f V n	d I N
re-	fund
r V	f V n d
re-	funds
r V	f V n d z
re-	fur-	bi-	shing
r i:	f @r	b I	S I N
re-	fur-	bish
r i:	f @r	b I S
re-	fur-	bish-	ment
r i:	f @r	b I S	m V n t
re-	fur-	bished
r i:	f @r	b I S t
re-	fuse
r V f	j u: z
re-	fuse-	nik
r V f	j u: z	n I k
re-	fuse-	niks
r V f	j u: z	n I k s
re-	fused
r V f	j u: z d
re-	fute
r V f	j u: t
re-	futes
r V f	j u: t s
re-	ga-	la-	do
r eI	g Q	l Q	d @U
re-	ga-	lia
r I	g eI l	j V
re-	ga-	ling
r I	g eI	l I N
re-	gai-	ning
r V	g eI	n I N
re-	gain
r V	g eI n
re-	gained
r i:	g eI n d
re-	gains
r i:	g eI n z
re-	gal
r i:	g V l
re-	gal-	ly
r i:	g V	l i:
re-	galed
r I	g eI l d
re-	gan
r i:	g V n
re-	gan's
r i:	g V n z
re-	gar-	ded
r V	g Q@	d V d
re-	gar-	ding
r V	g Q@	d I N
re-	gard
r V	g Q@ d
re-	gard-	less
r V	g Q@ d	l V s
re-	gards
r I	g Q@ d z
re-	gat-	ta
r I	g Q	t V
re-	gat-	tas
r V	g Q	t V z
re-	ge-	ne-	ra-	ted
r i:	dZ e	n @r	eI	t V d
re-	ge-	ne-	ra-	ting
r i:	dZ e	n @r	eI	t I N
re-	ge-	ne-	ra-	tion
r i:	dZ e	n @r	eI	S V n
re-	ge-	ne-	rate
r i:	dZ e	n @r	eI t
re-	gel
r e	g V l
re-	gen
r e	g V n
re-	gen-	cy
r i:	dZ V n	s i:
re-	gen-	cy's
r i:	dZ V n	s i: z
re-	gens-	burg
r i:	g V n	z b @r g
re-	gent
r i:	dZ V n t
re-	gents
r i:	dZ V n t s
re-	ger
r i:	g @r
re-	gi-	men
r e	dZ I	m e n
re-	gi-	men-	ta-	tion
r e	dZ I	m e n	t eI	S V n
re-	gi-	men-	tal
r e	dZ I	m e n	t V l
re-	gi-	men-	ted
r e	dZ I	m e n	t I d
re-	gi-	mens
r e	dZ I	m e n z
re-	gi-	ment
r e	dZ I	m e n t
re-	gi-	ments
r e	dZ I	m V n t s
re-	gi-	na
r I	dZ i:	n V
re-	gi-	nald
r e	dZ I	n V l d
re-	gi-	nald's
r e	dZ I	n V l d z
re-	gime
r V	Z i: m
re-	gimes
r V	Z i: m z
re-	gime's
r eI	Z i: m z
re-	gio-	na-	lize
r i:	dZ V	n V	l aI z
re-	gio-	na-	lized
r i:	dZ V	n V	l aI z d
re-	gio-	nal
r i:	dZ V	n V l
re-	gio-	nal-	ly
r i:	dZ V	n V	l i:
re-	gio-	nals
r i:	dZ V	n V l z
re-	gion
r i:	dZ V n
re-	gions
r i:	dZ V n z
re-	gion's
r i:	dZ V n z
re-	gis
r i:	dZ I s
re-	gis-	te-	ring
r e	dZ I s	t @r	I N
re-	gis-	ter
r e	dZ I s	t @r
re-	gis-	tered
r e	dZ I s	t @r d
re-	gis-	ters
r e	dZ I s	t @r z
re-	gis-	ter's
r e	dZ I s	t @r z
re-	gis-	trant
r e	dZ I s	t r V n t
re-	gis-	trants
r e	dZ I s	t r V n t s
re-	gis-	tries
r e	dZ I s	t r i: z
re-	gis-	try
r e	dZ I s	t r i:
re-	gist-	ra-	tion
r e	dZ I s	t r eI	S V n
re-	gist-	ra-	tions
r e	dZ I s	t r eI	S V n z
re-	gist-	rar
r e	dZ I s	t r Q@
re-	gist-	rars
r e	dZ I s	t r Q@ z
re-	go
r e	g @U
re-	gres-	sion
r V g	r e	S V n
re-	gres-	sions
r V g	r e	S V n z
re-	gres-	sive
r V g	r e	s I v
re-	gress
r i: g	r e s
re-	grou-	ping
r i: g	r u:	p I N
re-	group
r i: g	r u: p
re-	grouped
r i: g	r u: p t
re-	gu-	la
r e	g u:	l V
re-	gu-	la-	ri-	ty
r e g	j V	l e@	V	t i:
re-	gu-	la-	ted
r e g	j V	l eI	t V d
re-	gu-	la-	ting
r e g	j V	l eI	t I N
re-	gu-	la-	tion
r e g	j V	l eI	S V n
re-	gu-	la-	tions
r e g	j V	l eI	S V n z
re-	gu-	la-	tive
r e g	j V	l eI	t I v
re-	gu-	la-	to-	ry
r e g	j V	l V	t O@	i:
re-	gu-	la-	tor
r e g	j V	l eI	t @r
re-	gu-	la-	tors
r e g	j V	l eI	t @r z
re-	gu-	la-	tor's
r e g	j V	l eI	t @r z
re-	gu-	lar
r e g	j V	l @r
re-	gu-	lar-	ly
r e g	j V	l @r	l i:
re-	gu-	lars
r e g	j V	l @r z
re-	gu-	late
r e g	j V	l eI t
re-	gu-	lates
r e g	j V	l eI t s
re-	ha-	bi-	li-	ta-	ted
r i:	h V	b I	l V	t eI	t V d
re-	ha-	bi-	li-	ta-	ting
r i:	h V	b I	l V	t eI	t I N
re-	ha-	bi-	li-	ta-	tion
r i:	h V	b I	l V	t eI	S V n
re-	ha-	bi-	li-	ta-	tions
r i:	h V	b I	l V	t eI	S V n z
re-	ha-	bi-	li-	ta-	tive
r i:	h V	b I	l V	t eI	t I v
re-	ha-	bi-	li-	ta-	tor
r i:	h V	b I	l V	t eI	t @r
re-	ha-	bi-	li-	ta-	tors
r i:	h V	b I	l V	t eI	t @r z
re-	ha-	bi-	li-	tate
r i:	h V	b I	l V	t eI t
re-	ha-	shing
r i:	h {	S I N
re-	hab
r i:	h { b
re-	hash
r i:	h { S
re-	hea-	ring
r i:	h I@	I N
re-	hea-	rings
r i:	h I@	I N z
re-	hear
r i:	h I@
re-	hear-	sal
r V	h @r	s V l
re-	hear-	sals
r V	h @r	s V l z
re-	hear-	ses
r i:	h @r	s V z
re-	hear-	sing
r V	h @r	s I N
re-	hearse
r i:	h @r s
re-	hearsed
r i:	h @r s t
re-	hi-	red
r i:	h aI	@r d
re-	hi-	ring
r i:	h aI	r I N
re-	hire
r i:	h aI r
re-	hyd-	ra-	tion
r i:	h aI d	r eI	S V n
re-	hyd-	rate
r i:	h aI d	r eI t
re-	i-	na
r eI	i:	n V
re-	i-	te-	ra-	ted
r i:	I	t @r	eI	t V d
re-	i-	te-	ra-	ting
r i:	I	t @r	eI	t I N
re-	i-	te-	ra-	tion
r i:	I	t @r	eI	S V n
re-	i-	te-	rate
r i:	I	t @r	eI t
re-	i-	te-	rates
r i:	I	t @r	eI s
re-	ig-	ni-	ted
r i:	I g	n aI	t V d
re-	ig-	ni-	ting
r i:	I g	n aI	t I N
re-	ig-	nite
r i:	I g	n aI t
re-	im-	bur-	ses
r i:	I m	b @r	s V z
re-	im-	bur-	sing
r i:	I m	b @r	s I N
re-	im-	burse
r i:	I m	b @r s
re-	im-	burse-	ment
r i:	I m	b @r s	m e n t
re-	im-	burse-	ments
r i:	I m	b @r s	m e n t s
re-	im-	bursed
r i:	I m	b @r s t
re-	im-	po-	si-	tion
r i:	I m	p V	z I	S V n
re-	im-	po-	sing
r i:	I m	p @U	z I N
re-	im-	pose
r i:	I m	p @U z
re-	im-	posed
r i:	I m	p @U z d
re-	in-	car-	na-	ted
r i:	I n	k Q@	n eI	t V d
re-	in-	car-	na-	tion
r i:	I n	k Q@	n eI	S V n
re-	in-	car-	nate
r i:	I n	k Q@	n eI t
re-	in-	cor-	po-	ra-	ting
r i:	I n	k O@	p @r	eI	t I N
re-	in-	cor-	po-	ra-	tion
r i:	I n	k O@	p @r	eI	S V n
re-	in-	cor-	po-	rate
r i:	I n	k O@	p @r	eI t
re-	in-	dus-	tri-	a-	lize
r i:	I n	d V s	t r i:	Q	l aI z
re-	in-	for-	ces
r i:	I n	f O@	s V z
re-	in-	for-	cing
r i:	I n	f O@	s I N
re-	in-	force
r i:	I n	f O@ s
)"
R"(re-	in-	force-	ment
r i:	I n	f O@ s	m e n t
re-	in-	force-	ments
r i:	I n	f O@ s	m e n t s
re-	in-	forced
r i:	I n	f O@ s t
re-	in-	spec-	tion
r i:	I n	s p e k	S V n
re-	in-	spec-	tions
r i:	I n	s p e k	S V n s
re-	in-	spect
r i:	I n	s p e k t
re-	in-	sta-	ted
r i:	I n	s t eI	t V d
re-	in-	sta-	ting
r i:	I n	s t eI	t I N
re-	in-	stall
r i:	I n	s t Q l
re-	in-	stalled
r i:	I n	s t Q l d
re-	in-	stalls
r i:	I n	s t Q l z
re-	in-	state
r i:	I n	s t eI t
re-	in-	state-	ment
r i:	I n	s t eI t	m V n t
re-	in-	sti-	tu-	ted
r i:	I n	s t I	t u:	t I d
re-	in-	sti-	tu-	ting
r i:	I n	s t I	t u:	t I N
re-	in-	sti-	tute
r i:	I n	s t I	t u: t
re-	in-	su-	rance
r i:	I n	S U@	V n s
re-	in-	su-	rer
r i:	I n	S U@	@r
re-	in-	su-	rers
r i:	I n	S U@	@r z
re-	in-	sure
r i:	I n	S U@
re-	in-	sured
r i:	I n	S U@ d
re-	in-	teg-	ra-	ted
r i:	I n	t V g	r eI	t V d
re-	in-	teg-	ra-	tion
r i:	I n	t V g	r eI	S V n
re-	in-	teg-	rate
r i:	I n	t V g	r eI t
re-	in-	ter-	pre-	ta-	tion
r i:	I n	t @r p	r V	t eI	S V n
re-	in-	ter-	pre-	ted
r i:	I n	t @r p	r V	t V d
re-	in-	ter-	pre-	ting
r i:	I n	t @r p	r V	t I N
re-	in-	ter-	pret
r i:	I n	t @r p	r V t
re-	in-	tro-	du-	ces
r i:	I n	t r V	d u:	s V z
re-	in-	tro-	du-	cing
r i:	I n	t r V	d u:	s I N
re-	in-	tro-	duc-	tion
r i:	I n	t r V	d V k	S V n
re-	in-	tro-	duce
r i:	I n	t r V	d u: s
re-	in-	tro-	duced
r i:	I n	t r V	d u: s t
re-	in-	ven-	ted
r i:	I n	v e n	t V d
re-	in-	ven-	ting
r i:	I n	v e n	t I N
re-	in-	ven-	tion
r i:	I n	v e n	S V n
re-	in-	vent
r i:	I n	v e n t
re-	in-	ves-	ted
r i:	I n	v e s	t I d
re-	in-	ves-	ting
r i:	I n	v e s	t I N
re-	in-	vest
r i:	I n	v e s t
re-	in-	vest-	ment
r i:	I n	v e s	t m V n t
re-	in-	vests
r i:	I n	v e s t s
re-	in-	vi-	go-	ra-	ted
r i:	I n	v I	g @r	eI	t I d
re-	in-	vi-	go-	ra-	ting
r i:	I n	v I	g @r	eI	t I N
re-	in-	vi-	go-	ra-	tion
r i:	I n	v I	g @r	eI	S V n
re-	in-	vi-	go-	rate
r i:	I n	v I	g @r	eI t
re-	in-	vi-	ted
r i:	I n	v aI	t I d
re-	in-	vite
r i:	I n	v aI t
re-	int-	ro-	duc-	tion
r i:	I n	t r V	d V k	S V n
re-	is-	su-	ing
r i:	I	S u:	I N
re-	is-	sue
r i:	I	S u:
re-	is-	sued
r i:	I	S u: d
re-	is-	ter
r i:	I s	t @r
re-	ist
r i:	I s t
re-	jec-	ted
r I	dZ e k	t V d
re-	jec-	ting
r I	dZ e k	t I N
re-	jec-	tio-	nist
r I	dZ e k	S V	n I s t
re-	jec-	tio-	nists
r I	dZ e k	S V	n I s t s
re-	jec-	tion
r I	dZ e k	S V n
re-	jec-	tions
r I	dZ e k	S V n z
re-	ject
r I	dZ e k t
re-	jects
r I	dZ e k t s
re-	jig-	ge-	ring
r i:	dZ I	g @r	I N
re-	joi-	cing
r I	dZ OI	s I N
re-	joi-	ning
r i:	dZ OI	n I N
re-	joice
r I	dZ OI s
re-	joiced
r I	dZ OI s t
re-	join
r i:	dZ OI n
re-	join-	der
r I	dZ OI n	d @r
re-	joined
r i:	dZ OI n d
re-	joins
r i:	dZ OI n z
re-	ju-	ve-	na-	ted
r I	dZ u:	v V	n eI	t V d
re-	ju-	ve-	na-	ting
r i:	dZ u:	v V	n eI	t I N
re-	ju-	ve-	na-	tion
r I	dZ u:	v V	n eI	S V n
re-	ju-	ve-	nate
r I	dZ u:	v V	n eI t
re-	ju-	ve-	nates
r I	dZ u:	v V	n eI t s
re-	kin-	dle
r i:	k I n	d V l
re-	kin-	dled
r i:	k I n	d V l d
re-	kind-	ling
r i:	k I n	d l I N
re-	la-	bel
r i:	l eI	b V l
re-	la-	ted
r V	l eI	t V d
re-	la-	ti-	vi-	sm
r e	l V	t I	v I	z V m
re-	la-	ti-	vi-	ty
r e	l V	t I	v V	t i:
re-	la-	ti-	vis-	tic
r e	l V	t I	v I s	t I k
re-	la-	ting
r V	l eI	t I N
re-	la-	tio-	nal
r i:	l eI	S V	n V l
re-	la-	tion
r i:	l eI	S V n
re-	la-	tion-	ship
r i:	l eI	S V n	S I p
re-	la-	tion-	ships
r i:	l eI	S V n	S I p s
re-	la-	tions
r i:	l eI	S V n z
re-	la-	tive
r e	l V	t I v
re-	la-	tive-	ly
r e	l V	t I v	l i:
re-	la-	tives
r e	l V	t I v z
re-	la-	xa-	tion
r i:	l { k	s eI	S V n
re-	la-	xes
r V	l { k	s V z
re-	la-	xing
r V	l { k	s I N
re-	lap-	ses
r i:	l { p	s V z
re-	lap-	sing
r V	l { p	s I N
re-	lapse
r i:	l { p s
re-	lapsed
r i:	l { p s t
re-	late
r V	l eI t
re-	lates
r V	l eI t s
re-	launch
r i:	l O: n tS
re-	lax
r V	l { k s
re-	laxed
r V	l { k s t
re-	lay
r i:	l eI
re-	lay-	ing
r i:	l eI	I N
re-	layed
r i:	l eI d
re-	lays
r i:	l eI z
re-	le-	ga-	ted
r e	l V	g eI	t V d
re-	le-	ga-	ting
r e	l V	g eI	t I N
re-	le-	gate
r e	l V	g eI t
re-	le-	van-	cy
r e	l V	v V n	s i:
re-	le-	vance
r e	l V	v V n s
re-	le-	vant
r e	l V	v V n t
re-	lea-	ses
r V	l i:	s V z
re-	lea-	sing
r i:	l i:	s I N
re-	lear-	ning
r i:	l e@	n I N
re-	learn
r i:	l e@ n
re-	lease
r i:	l i: s
re-	leased
r i:	l i: s t
re-	len-	ding
r i:	l e n	d I N
re-	len-	ted
r V	l e n	t V d
re-	len-	ting
r V	l e n	t I N
re-	lend
r i:	l e n d
re-	lent
r V	l e n t
re-	lent-	less
r V	l e n	t l V s
re-	lent-	less-	ly
r V	l e n	t l V s	l i:
re-	li-	a-	bi-	li-	ty
r i:	l aI	V	b I	l V	t i:
re-	li-	a-	ble
r V	l aI	V	b V l
re-	li-	ab-	ly
r V	l aI	V b	l i:
re-	li-	an-	ce's
r V	l aI	V n	s V z
re-	li-	ance
r V	l aI	V n s
re-	li-	ant
r V	l aI	V n t
re-	li-	gi-	o-	si-	ty
r V	l I	dZ i:	Q	s V	t i:
re-	li-	gio-	nist
r i:	l I	dZ V	n I s t
re-	li-	gion
r V	l I	dZ V n
re-	li-	gions
r i:	l I	dZ V n z
re-	li-	gion's
r V	l I	dZ V n z
re-	li-	gious
r V	l I	dZ V s
re-	li-	gious-	ly
r V	l I	dZ V s	l i:
re-	li-	shes
r e	l I	S V z
re-	li-	shing
r e	l I	S I N
re-	li-	ving
r i:	l I	v I N
re-	lic
r e	l I k
re-	lics
r e	l I k s
re-	lie-	ver
r i:	l i:	v @r
re-	lie-	vers
r i:	l i:	v @r z
re-	lie-	ving
r V	l i:	v I N
re-	lied
r V	l aI d
re-	lief
r V	l i: f
re-	liefs
r i:	l i: f s
re-	lies
r V	l aI z
re-	lieve
r V	l i: v
re-	lieved
r V	l i: v d
re-	lieves
r i:	l i: v z
re-	lin-	qui-	shes
r V	l I N	k w I	S V z
re-	lin-	qui-	shing
r i:	l I N	k w I	S I N
re-	lin-	quish
r V	l I N	k w I S
re-	lin-	quished
r V	l I N	k w I S t
re-	lish
r e	l I S
re-	lished
r e	l I S t
re-	live
r i:	l I v
re-	lived
r i:	l I v d
re-	lo-	ca-	ted
r i:	l @U	k eI	t V d
re-	lo-	ca-	ting
r i:	l @U	k eI	t I N
re-	lo-	ca-	tion
r i:	l @U	k eI	S V n
re-	lo-	ca-	tions
r i:	l @U	k eI	S V n z
re-	lo-	cate
r i:	l @U	k eI t
re-	loa-	ded
r i:	l @U	d V d
re-	load
r i:	l @U d
re-	loads
r i:	l @U d z
re-	luc-	tance
r V	l V k	t V n s
re-	luc-	tant
r V	l V k	t V n t
re-	luc-	tant-	ly
r V	l V k	t V n	t l i:
re-	ly
r V	l aI
re-	ly-	ing
r i:	l aI	I N
re-	ma-	king
r i:	m eI	k I N
re-	ma-	nu-	fac-	ture
r i:	m { n	j u:	f { k	tS @r
re-	ma-	nu-	fac-	tured
r i:	m { n	j u:	f { k	tS @r d
re-	made
r i:	m eI d
re-	mai-	ning
r V	m eI	n I N
re-	main
r V	m eI n
re-	main-	der
r V	m eI n	d @r
re-	mained
r V	m eI n d
re-	mains
r V	m eI n z
re-	make
r i:	m eI k
re-	makes
r i:	m eI k s
re-	man-	ded
r I	m { n	d V d
re-	mand
r I	m { n d
re-	mar-	ka-	ble
r V	m Q@	k V	b V l
re-	mar-	kab-	ly
r V	m Q@	k V b	l i:
re-	mar-	ke-	ted
r i:	m Q@	k V	t V d
re-	mar-	ke-	ting
r i:	m Q@	k V	t I N
re-	mar-	ket
r i:	m Q@	k V t
re-	mar-	king
r V	m Q@	k I N
re-	mar-	riage
r i:	m e@	I dZ
re-	mar-	ried
r i:	m e@	i: d
re-	mar-	ry
r i:	m e@	i:
re-	mar-	ry-	ing
r i:	m e@	i:	I N
re-	mark
r V	m Q@ k
re-	marked
r V	m Q@ k t
re-	marks
r V	m Q@ k s
re-	match
r i:	m { tS
re-	me-	di-	a-	tion
r V	m i:	d i:	eI	S V n
re-	me-	di-	al
r V	m i:	d i:	V l
re-	me-	di-	ate
r i:	m i:	d i:	V t
re-	me-	died
r e	m V	d i: d
re-	me-	dies
r e	m V	d i: z
re-	me-	dy
r e	m V	d i:
re-	me-	dy-	ing
r e	m V	d i:	I N
re-	mem-	be-	ring
r I	m e m	b @r	I N
re-	mem-	ber
r I	m e m	b @r
re-	mem-	bered
r I	m e m	b @r d
re-	mem-	bers
r I	m e m	b @r z
re-	memb-	ran-	ces
r I	m e m	b r V n	s V z
re-	memb-	rance
r I:	m e m	b r V n s
re-	mer
r i:	m @r
re-	mi
r e	m i:
re-	mi-	ni-	scen-	ces
r e	m I	n I	s e n	s V z
re-	mi-	ni-	scence
r e	m I	n I	s e n s
re-	mi-	ni-	scent
r e	m V	n I	s e n t
re-	mi-	ni-	sces
r e	m V	n I	s e z
re-	mi-	ni-	scing
r e	m V	n I	s I N
re-	mi-	nisce
r e	m I	n I s
re-	mi-	nisced
r e	m I	n I s t
re-	min-	ded
r i:	m aI n	d V d
re-	min-	der
r i:	m aI n	d @r
re-	min-	ders
r i:	m aI n	d @r z
re-	min-	ding
r i:	m aI n	d I N
re-	mind
r i:	m aI n d
re-	minds
r i:	m aI n d z
re-	ming-	ton
r e	m I N	t V n
re-	mis-	sion
r i:	m I	S V n
re-	mis-	sions
r i:	m I	S V n z
re-	miss
r i:	m I s
re-	mit
r i:	m I t
re-	mit-	tan-	ces
r i:	m I	t V n	s V z
re-	mit-	tance
r i:	m I	t V n s
re-	mit-	ted
r i:	m I	t V d
re-	mo
r e	m @U
re-	mo-	de-	ling
r V	m Q	d V	l I N
re-	mo-	del
r i:	m Q	d V l
re-	mo-	deled
r i:	m Q	d V l d
re-	mo-	test
r V	m @U	t V s t
re-	mo-	va-	ble
r V	m u:	v V	b V l
re-	mo-	val
r V	m u:	v V l
re-	mo-	vals
r V	m u:	v V l z
re-	mo-	ver
r V	m u:	v @r
re-	mo-	ving
r i:	m u:	v I N
re-	mol-	ded
r i:	m @U l	d V d
re-	mold
r i:	m @U l d
re-	morse
r V	m O@ s
re-	morse-	ful
r V	m O@ s	f V l
re-	morse-	less
r V	m O@ s	l V s
re-	mote
r V	m @U t
re-	mote-	ly
r i:	m @U t	l i:
re-	mote-	ness
r i:	m @U t	n V s
re-	moul-	ded
r i:	m @U l	d V d
re-	move
r i:	m u: v
re-	moved
r i:	m u: v d
re-	moves
r i:	m u: v z
re-	mu-	ne-	ra-	tion
r V m	j u:	n @r	eI	S V n
re-	mu-	ne-	ra-	tive
r i: m	j u:	n @r	V	t I v
re-	mu-	ne-	rate
r V m	j u:	n @r	eI t
re-	mus
r i:	m V s
re-	my
r e	m i:
re-	na
r i:	n V
re-	na-	ming
r i:	n eI	m I N
re-	na-	ta
r V	n Q	t V
re-	na-	te
r V	n Q	t V
re-	na-	tio-	na-	li-	za-	tion
r i:	n {	S V	n V	l I	z eI	S V n
re-	na-	tio-	na-	lize
r i:	n {	S V	n V	l aI z
re-	na-	to
r e	n Q	t @U
re-	nais-	san-	ce's
r e	n V	s Q n	s V z
re-	nais-	sance
r e	n V	s Q n s
re-	nal
r i:	n V l
re-	nal-	do
r e	n Q l	d @U
re-	name
r i:	n eI m
re-	named
r i:	n eI m d
re-	nard
r V	n Q@ d
re-	naud
r V	n @U
re-	nault
r V	n @U
re-	nault's
r V	n O: l t s
re-	ne
r V	n eI
re-	ne-	gade
r e	n V	g eI d
re-	ne-	gades
r e	n V	g eI d z
re-	ne-	ging
r V	n I	g I N
re-	ne-	go-	ti-	a-	ted
r i:	n I	g @U	S i:	eI	t V d
re-	ne-	go-	ti-	a-	ting
r i:	n I	g @U	S i:	eI	t I N
re-	ne-	go-	ti-	a-	tion
r i:	n I	g @U	S i:	eI	S V n
re-	ne-	go-	ti-	a-	tions
r i:	n I	g @U	S i:	eI	S V n z
re-	ne-	go-	ti-	ate
r i:	n I	g @U	S i:	eI t
re-	ne-	wa-	ble
r i:	n u:	V	b V l
re-	ne-	wal
r V	n u:	V l
re-	ne-	wals
r V	n u:	V l z
re-	ne-	wing
r V	n u:	I N
re-	nee
r V	n eI
re-	nege
r V	n I g
re-	neged
r V	n I g d
re-	new
r V	n u:
re-	newed
r V	n u: d
re-	news
r V	n u: z
re-	ni-	ta
r e	n i:	t V
re-	nick
r e	n I k
re-	nin
r i:	n I n
re-	no
r i:	n @U
re-	no-	mi-	na-	ted
r i:	n Q	m I	n eI	t I d
re-	no-	mi-	na-	tion
r i:	n Q	m I	n eI	S V n
re-	no-	mi-	nate
r i:	n O:	m I	n eI t
re-	no-	va-	ted
r e	n V	v eI	t V d
re-	no-	va-	ting
r e	n V	v eI	t I N
re-	no-	va-	tion
r e	n V	v eI	S V n
re-	no-	va-	tions
r e	n V	v eI	S V n z
re-	no-	va-	tor
r e	n V	v eI	t @r
re-	no-	va-	tors
r e	n V	v eI	t @r z
re-	no-	vate
r e	n V	v eI t
re-	noir
r e n	w Q@
re-	no's
r i:	n @U z
re-	noun-	ces
r I	n aU n	s V z
re-	noun-	cing
r I	n aU n	s I N
re-	nounce
r I	n aU n s
re-	nounced
r I	n aU n s t
re-	nown
r V	n aU n
re-	nowned
r V	n aU n d
re-	nun-	ci-	a-	tion
r V	n V n	s i:	eI	S V n
re-	nun-	ci-	ate
r V	n V n	s i:	eI t
re-	ny
r i:	n i:
re-	o
r i:	@U
re-	o-	pe-	ning
r i:	@U	p V	n I N
re-	o-	pen
r i:	@U	p V n
re-	o-	pened
r i:	@U	p V n d
re-	o-	pens
r i:	@U	p V n z
re-	o-	ri-	ent
r i:	O@	i:	e n t
re-	oc-	cu-	py
r i:	O: k	j u:	p aI
re-	oc-	cur
r i:	V	k @r
re-	of-	fe-	ring
r i:	O:	f @r	I N
re-	of-	fen-	ded
r i:	O:	f e n	d V d
re-	of-	fend
r i:	O:	f e n d
re-	of-	fer
r i:	O:	f @r
re-	of-	fered
r i:	O:	f @r d
re-	or-	de-	ring
r i:	O@	d @r	I N
re-	or-	der
r i:	O@	d @r
re-	or-	ga-	ni-	za-	tion
r i:	O@	g V	n V	z eI	S V n
re-	or-	ga-	ni-	za-	tions
r i:	O@	g V	n V	z eI	S V n z
re-	or-	ga-	ni-	zes
r i:	O@	g V	n aI	z V z
re-	or-	ga-	ni-	zing
r i:	O@	g V	n aI	z I N
re-	or-	ga-	nize
r i:	O@	g V	n aI z
re-	or-	ga-	nized
r i:	O@	g V	n aI z d
re-	pa-	ra-	tion
r e	p @r	eI	S V n
re-	pa-	ra-	tions
r e	p @r	eI	S V n z
re-	pac-	ka-	ges
r i:	p {	k I	dZ V z
re-	pac-	ka-	ging
r i:	p {	k I	dZ I N
re-	pac-	kage
r i:	p {	k I dZ
re-	pac-	kaged
r i:	p {	k I dZ d
re-	pack
r i:	p { k
re-	packed
r i:	p { k t
re-	pai-	ra-	ble
r V	p e@	V	b V l
re-	pai-	ring
r V	p e@	I N
re-	paid
r i:	p eI d
re-	pain-	ted
r i:	p eI n	t V d
re-	pain-	ting
r i:	p eI n	t I N
re-	paint
r i:	p eI n t
re-	pair
r V	p e@
re-	pair-	man
r V	p e@	m { n
re-	pair-	men
r V	p e@	m e n
re-	paired
r V	p e@ d
re-	pairs
r V	p e@ z
re-	par-	tee
r e	p @r	t i:
re-	pass
r i:	p { s
re-	pat-	ri-	a-	ted
r i:	p eI t	r i:	eI	t V d
re-	pat-	ri-	a-	ting
r i:	p eI t	r i:	eI	t I N
re-	pat-	ri-	a-	tion
r i:	p eI t	r i:	eI	S V n
re-	pat-	ri-	ate
r i:	p eI t	r i:	eI t
re-	pay
r i:	p eI
re-	pay-	a-	ble
r i:	p eI	V	b V l
re-	pay-	ing
r i:	p eI	I N
re-	pay-	ment
r i:	p eI	m V n t
re-	pay-	ments
r i:	p eI	m V n t s
re-	pays
r i:	p eI z
re-	pe-	ti-	tion
r e	p V	t I	S V n
re-	pe-	ti-	tions
r e	p V	t I	S V n z
re-	pe-	ti-	tious
r e	p V	t I	S V s
re-	pe-	ti-	tive
r V	p e	t V	t I v
re-	pea-	ling
r i:	p i:	l I N
re-	pea-	ta-	ble
r V	p i:	t V	b V l
re-	pea-	ted
r V	p i:	t V d
re-	pea-	ted-	ly
r V	p i:	t V d	l i:
re-	pea-	ter
r V	p i:	t @r
re-	pea-	ters
r V	p i:	t @r z
re-	pea-	ting
r V	p i:	t I N
re-	peal
r V	p i: l
re-	pealed
r V	p i: l d
re-	peals
r i:	p i: l z
re-	peat
r V	p i: t
re-	peats
r V	p i: t s
re-	pel
r V	p e l
re-	pel-	lent
r V	p e	l V n t
re-	pel-	ling
r V	p e	l I N
re-	pelled
r V	p e l d
re-	pels
r V	p e l z
re-	pen-	tance
r V	p e n	t V n s
re-	pen-	tant
r V	p e n	t V n t
re-	pen-	ted
r V	p e n	t V d
re-	pent
r V	p e n t
re-	per-	cus-	sion
r i:	p @r	k V	S V n
re-	per-	cus-	sions
r i:	p @r	k V	S V n z
re-	per-	to-	ry
r e	p @r	t O@	i:
re-	per-	toire
r e	p @r t	w Q@
re-	play
r i: p	l eI
re-	play-	ing
r i: p	l eI	I N
re-	played
r i: p	l eI d
re-	plays
r i: p	l eI z
re-	ple-	ni-	shing
r i: p	l e	n I	S I N
re-	ple-	nish
r i: p	l e	n I S
re-	ple-	nished
r i: p	l e	n I S t
re-	po
r i:	p @U
re-	po-	si-	tio-	ning
r i:	p V	z I	S V	n I N
re-	po-	si-	tion
r i:	p V	z I	S V n
re-	po-	si-	tioned
r i:	p V	z I	S V n d
re-	po-	si-	to-	ries
r i:	p Q	z I	t O@	i: z
re-	po-	si-	to-	ry
r i:	p Q	z I	t O@	i:
re-	por-	ta-	ble
r V	p O@	t V	b V l
re-	por-	tage
r V	p O@	t I dZ
re-	por-	ted
r i:	p O@	t V d
re-	por-	ted-	ly
r V	p O@	t V d	l i:
re-	por-	ter
r V	p O@	t @r
re-	por-	ters
r V	p O@	t @r z
re-	por-	ter's
r V	p O@	t @r z
re-	por-	ting
r i:	p O@	t I N
re-	por-	to-	ri-	al
r e	p @r	t O@	i:	V l
re-	port
r i:	p O@ t
re-	ports
r V	p O@ t s
re-	port's
r i:	p O@ t s
re-	pos
r i:	p @U z
re-	pos-	ses-	sion
r i:	p V	z e	S V n
re-	pos-	ses-	sions
r i:	p V	z e	S V n z
re-	pos-	sess
r i:	p V	z e s
re-	pos-	sessed
r i:	p V	z e s t
re-	pose
r i:	p @U z
re-	pre-	sent
r e p	r V	z e n t
re-	press
r i: p	r e s
re-	pu-	di-	a-	ted
r i: p	j u:	d i:	eI	t V d
re-	pu-	di-	a-	ting
r i: p	j u:	d i:	eI	t I N
re-	pu-	di-	a-	tion
r V p	j u:	d i:	eI	S V n
re-	pu-	di-	ate
r i: p	j u:	d i:	eI t
re-	pu-	di-	ates
r i: p	j u:	d i:	eI t s
re-	pu-	ta-	ble
r e p	j V	t V	b V l
re-	pu-	ta-	tion
r e p	j V	t eI	S V n
re-	pu-	ta-	tions
r e p	j V	t eI	S V n z
re-	pu-	ted
r V p	j u:	t V d
re-	pu-	ted-	ly
r V p	j u:	t V d	l i:
re-	pub-	li-	ca-	ni-	sm
r V	p V b	l I	k V	n I	z V m
re-	pub-	li-	can
r i:	p V b	l I	k V n
re-	pub-	li-	cans
r V	p V b	l I	k V n z
re-	pub-	li-	can's
r i:	p V b	l I	k V n z
re-	pub-	lic
r i:	p V b	l I k
re-	pub-	lics
r i:	p V b	l I k s
re-	pub-	lic's
r i:	p V b	l I k s
re-	pug-	nant
r V	p V g	n V n t
re-	pul-	sing
r i:	p V l	s I N
re-	pul-	sive
r i:	p V l	s I v
re-	pulse
r i:	p V l s
re-	pulsed
r i:	p V l s t
re-	pur-	cha-	ses
r i:	p @r	tS V	s V z
re-	pur-	cha-	sing
r i:	p @r	tS V	s I N
re-	pur-	chase
r i:	p @r	tS V s
re-	pur-	chased
r i:	p @r	tS V s t
re-	pute
r i: p	j u: t
re-	qua-	li-	fy
r i: k	w Q	l I	f aI
re-	ques-	ted
r I k	w e s	t V d
re-	ques-	ter
r I k	w e s	t @r
re-	ques-	ting
r I k	w e s	t I N
re-	quest
r I k	w e s t
re-	quests
r I k	w e s t s
re-	qui-	em
r e k	w i:	V m
re-	qui-	r-	ing
r i: k	w aI	@r	I N
re-	qui-	re
r i: k	w aI	@r
re-	qui-	red
r i: k	w aI	@r d
re-	qui-	res
r i: k	w aI	@r z
re-	qui-	si-	tion
r e k	w I	z I	S V n
re-	qui-	si-	tioned
r e k	w I	z I	S V n d
re-	qui-	site
r e k	w I	z I t
re-	qui-	sites
r e k	w I	z I t s
re-	quire-	ment
r I k	w aI r	m V n t
re-	quire-	ments
r I k	w aI r	m V n t s
re-	re-	gu-	la-	tion
r i:	r e g	j V	l eI	S V n
re-	re-	gu-	late
r i:	r e g	j V	l eI t
re-	rea-	ding
r i:	r i:	d I N
re-	read
r i:	r i: d
re-	rou-	ted
r i:	r u:	t V d
re-	rou-	ting
r i:	r u:	t I N
re-	route
r i:	r u: t
re-	run
r i:	r V n
re-	run-	ning
r i:	r V	n I N
re-	runs
r i:	r V n z
re-	sale
r i:	s eI l
re-	sales
r i:	s eI l z
re-	scin-	ded
r V	s I n	d V d
re-	scin-	ding
r V	s I n	d I N
re-	scind
r V	s I n d
re-	scis-	sion
r V	s I	Z V n
re-	scis-	sions
r V	s I	Z V n z
re-	se-	da
r e	s eI	d V
re-	se-	ting
r i:	s e	t I N
re-	sea-	la-	ble
r i:	s i:	l V	b V l
re-	seal
r i:	s i: l
)"
R"(re-	sealed
r i:	s i: l d
re-	seals
r i:	s i: l z
re-	sear-	cher
r i:	s @r	tS @r
re-	sear-	chers
r i:	s @r	tS @r z
re-	sear-	ches
r i:	s @r	tS V z
re-	sear-	ching
r i:	s @r	tS I N
re-	sear-	ch's
r i:	s @r	tS V z
re-	search
r i:	s @r tS
re-	seed
r i:	s i: d
re-	sel-	ler
r i:	s e	l @r
re-	sel-	lers
r i:	s e	l @r z
re-	sel-	ling
r i:	s e	l I N
re-	sell
r i:	s e l
re-	sells
r i:	s e l z
re-	sem-	b-	ling
r V	z e m	b V	l I N
re-	sem-	ble
r V	z e m	b V l
re-	sem-	bled
r V	z e m	b V l d
re-	sem-	bles
r V	z e m	b V l z
re-	semb-	lan-	ces
r i:	z e m	b l V n	s V z
re-	semb-	lance
r V	z e m	b l V n s
re-	sen-	ted
r i:	z e n	t V d
re-	sen-	ting
r V	z e n	t I N
re-	sent
r V	z e n t
re-	sent-	ful
r V	z e n	t f V l
re-	sent-	ment
r V	z e n	t m V n t
re-	sent-	ments
r V	z e n	t m V n t s
re-	sents
r V	z e n t s
re-	ser-	va-	tio-	nist
r e	z @r	v eI	S V	n I s t
re-	ser-	va-	tio-	nists
r e	z @r	v eI	S V	n I s t s
re-	ser-	va-	tion
r e	z @r	v eI	S V n
re-	ser-	va-	tions
r e	z @r	v eI	S V n z
re-	ser-	ving
r V	z @r	v I N
re-	ser-	vist
r V	z @r	v V s t
re-	ser-	vists
r V	z @r	v V s t s
re-	ser-	voir
r e	z V v	w Q@
re-	ser-	voirs
r e	z @r v	w Q@ z
re-	serve
r V	z @r v
re-	served
r V	z @r v d
re-	serves
r V	z @r v z
re-	set
r i:	s e t
re-	set-	ta-	ble
r i:	s e	t V	b V l
re-	set-	tle
r i:	s e	t V l
re-	set-	tle-	ment
r i:	s e	t V l	m V n t
re-	set-	tled
r i:	s e	t V l d
re-	sets
r i:	s e t s
re-	sha-	ping
r i:	S eI	p I N
re-	shape
r i:	S eI p
re-	shaped
r i:	S eI p t
re-	shot
r i:	S O: t
re-	shuf-	f-	ling
r i:	S V	f V	l I N
re-	shuf-	fle
r i:	S V	f V l
re-	shuf-	fled
r i:	S V	f V l d
re-	si-	ded
r V	z aI	d V d
re-	si-	den-	ces
r e	z I	d e n	s V z
re-	si-	den-	cies
r e	s I	d e n	s i: z
re-	si-	den-	cy
r e	z I	d e n	s i:
re-	si-	den-	tial
r e	z I	d e n	tS V l
re-	si-	dence
r e	z I	d e n s
re-	si-	dent
r e	z I	d e n t
re-	si-	dents
r e	z I	d e n t s
re-	si-	dent's
r e	z I	d e n t s
re-	si-	ding
r V	z aI	d I N
re-	si-	du-	al
r V	z I	dZ u:	V l
re-	si-	du-	als
r V	z I	dZ u:	V l z
re-	si-	due
r e	z I	d u:
re-	si-	dues
r e	z I	d u: z
re-	si-	li-	ence
r V	z I	l i:	V n s
re-	si-	lien-	cy
r V	z I l	j V n	s i:
re-	si-	lient
r V	z I l	j V n t
re-	side
r V	z aI d
re-	sides
r V	z aI d z
re-	sig-	na-	tion
r e	z I g	n eI	S V n
re-	sig-	na-	tions
r e	z I g	n eI	S V n z
re-	sig-	nee
r e	z I g	n i:
re-	sig-	ning
r V	z aI	n I N
re-	sign
r V	z aI n
re-	signed
r V	z aI n d
re-	signs
r V	z aI n z
re-	sin
r e	z I n
re-	sins
r e	z I n z
re-	sis-	tance
r V	z I s	t V n s
re-	sis-	tant
r V	z I s	t V n t
re-	sis-	ted
r V	z I s	t V d
re-	sis-	tence
r V	z I s	t V n s
re-	sis-	ting
r V	z I s	t I N
re-	sis-	tive-	ness
r I	z I s	t I v	n V s
re-	sis-	tors
r V	z I s	t @r z
re-	sist
r V	z I s t
re-	sists
r V	z I s t s
re-	so
r I	z @U
re-	so-	lu-	tion
r e	z V	l u:	S V n
re-	so-	lu-	tions
r e	z V	l u:	S V n z
re-	so-	lu-	tion's
r e	z V	l u:	S V n z
re-	so-	lute
r e	z V	l u: t
re-	so-	lute-	ly
r e	z V	l u: t	l i:
re-	so-	na-	ted
r e	z V	n eI	t V d
re-	so-	na-	ting
r e	z V	n eI	t I N
re-	so-	nance
r e	z V	n V n s
re-	so-	nant
r e	z V	n V n t
re-	so-	nate
r e	z V	n eI t
re-	so-	nates
r e	z V	n eI t s
re-	sol-	ving
r i:	z Q l	v I N
re-	sold
r i:	s @U l d
re-	solve
r i:	z Q l v
re-	solved
r i:	z Q l v d
re-	solves
r i:	z Q l v z
re-	sor-	ted
r V	z O@	t V d
re-	sor-	ting
r V	z O@	t I N
re-	sort
r V	z O@ t
re-	sorts
r V	z O@ t s
re-	soun-	ding
r i:	s aU n	d I N
re-	soun-	ding-	ly
r V	z aU n	d I N	l i:
re-	sound
r i:	s aU n d
re-	sour-	ces
r i:	s O@	s V z
re-	source
r i:	s O@ s
re-	source-	ful
r i:	s O@ s	f V l
re-	source-	ful-	ness
r i:	s O@ s	f V l	n V s
re-	speak
r i: s	p i: k
re-	sta-	ted
r i: s	t eI	t V d
re-	sta-	ting
r i: s	t eI	t I N
re-	star-	ted
r i: s	t Q@	t V d
re-	star-	ting
r i: s	t Q@	t I N
re-	start
r i: s	t Q@ t
re-	state
r i: s	t eI t
re-	state-	ment
r i: s	t eI t	m V n t
re-	state-	ments
r i: s	t eI t	m V n t s
re-	states
r i: s	t eI t s
re-	stau-	ra-	teur
r e s	t @r	V	t @r
re-	stau-	ra-	teurs
r e s	t @r	V	t @r z
re-	stau-	rant
r e s	t @r	Q n t
re-	stau-	rants
r e s	t @r	Q n t s
re-	stau-	rant's
r e s	t @r	Q n t s
re-	strain
r i: s	t r eI n
re-	style
r i: s	t aI l
re-	styled
r i: s	t aI l d
re-	su-	ming
r V	z u:	m I N
re-	sub-	mit
r i:	s V b	m I t
re-	sub-	mit-	ted
r i:	s V b	m I	t V d
re-	sub-	mit-	ting
r i:	s V b	m I	t I N
re-	sul-	tant
r i:	z V l	t V n t
re-	sul-	ted
r V	z V l	t V d
re-	sul-	ting
r V	z V l	t I N
re-	sult
r V	z V l t
re-	sults
r V	z V l t s
re-	sume
r V	z u: m
re-	sumed
r V	z u: m d
re-	sumes
r V	z u: m z
re-	sump-	tion
r V	z V m	p S V n
re-	supp-	ly
r i:	s V p	l aI
re-	sur-	fa-	cing
r i:	s @r	f V	s I N
re-	sur-	face
r i:	s @r	f V s
re-	sur-	faced
r i:	s @r	f V s t
re-	sur-	gen-	cy
r V	s @r	dZ V n	s i:
re-	sur-	gence
r i:	s @r	dZ V n s
re-	sur-	gent
r V	s @r	dZ V n t
re-	sur-	ging
r i:	s @r	dZ I N
re-	sur-	rec-	ted
r e	z @r	e k	t V d
re-	sur-	rec-	ting
r e	z @r	e k	t I N
re-	sur-	rec-	tion
r e	z @r	e k	S V n
re-	sur-	rect
r e	z @r	e k t
re-	sus-	ci-	ta-	ted
r V	s V	s I	t eI	t I d
re-	sus-	ci-	ta-	ting
r V	s V	s I	t eI	t I N
re-	sus-	ci-	ta-	tion
r V	s V	s I	t eI	S V n
re-	sus-	ci-	tate
r V	s V	s V	t eI t
re-	ta
r e	t V
re-	ta-	ken
r i:	t eI	k V n
re-	ta-	king
r i:	t eI	k I N
re-	ta-	li-	a-	ted
r V	t {	l i:	eI	t V d
re-	ta-	li-	a-	ting
r V	t {	l i:	eI	t I N
re-	ta-	li-	a-	tion
r i:	t {	l i:	eI	S V n
re-	ta-	li-	ate
r V	t {	l i:	eI t
re-	ta-	lia-	to-	ry
r i:	t { l	j V	t O@	i:
re-	tai-	ler
r i:	t eI	l @r
re-	tai-	lers
r i:	t eI	l @r z
re-	tai-	ler's
r i:	t eI	l @r z
re-	tai-	ling
r i:	t eI	l I N
re-	tai-	ner
r V	t eI	n @r
re-	tai-	ners
r V	t eI	n @r z
re-	tai-	ning
r V	t eI	n I N
re-	tail
r i:	t eI l
re-	tailed
r i:	t eI l d
re-	tails
r i:	t eI l z
re-	tain
r V	t eI n
re-	tained
r V	t eI n d
re-	tains
r V	t eI n z
re-	take
r i:	t eI k
re-	tar-	da-	tion
r i:	t Q@	d eI	S V n
re-	tar-	dant
r i:	t Q@	d V n t
re-	tar-	ded
r V	t Q@	d V d
re-	tar-	ding
r V	t Q@	d I N
re-	tard
r V	t Q@ d
re-	tards
r V	t Q@ d z
re-	tel-	ling
r i:	t e	l I N
re-	tell
r i:	t e l
re-	ten-	tion
r i:	t e n	S V n
re-	tes-	ted
r i:	t e s	t V d
re-	tes-	ting
r i:	t e s	t I N
re-	test
r i:	t e s t
re-	tests
r i:	t e s t s
re-	thin-	king
r i:	T I N	k I N
re-	think
r i:	T I N k
re-	thought
r i:	T O: t
re-	ti-	cence
r e	t I	s V n s
re-	ti-	cent
r e	t I	s V n t
re-	ti-	na
r e	t I	n V
re-	ti-	nal
r e	t I	n V l
re-	ti-	no-	blas-	to-	ma
r e	t I	n @U b	l { s	t @U	m V
re-	ti-	noid
r e	t I	n OI d
re-	ti-	noids
r e	t I	n OI d z
re-	ti-	nue
r e	t I	n u:
re-	ti-	re-	ment
r i:	t aI	@r	m V n t
re-	ti-	ree
r i:	t aI	r i:
re-	ti-	rees
r i:	t aI	r i: z
re-	ti-	ree's
r V	t aI	r i: z
re-	ti-	ring
r V	t aI	r I N
re-	tin
r e	t I n
re-	tire
r V	t aI r
re-	tire-	ments
r V	t aI r	m V n t s
re-	tired
r V	t aI r d
re-	tires
r V	t aI r z
re-	too-	ling
r i:	t u:	l I N
re-	took
r i:	t U k
re-	tool
r i:	t u: l
re-	tooled
r i:	t u: l d
re-	tor-	ted
r i:	t O@	t V d
re-	tort
r i:	t O@ t
re-	torts
r V	t O@ t s
re-	tou-	ching
r i:	t V	tS I N
re-	tra-	cing
r i: t	r eI	s I N
re-	trace
r i: t	r eI s
re-	traced
r i: t	r eI s t
re-	trea-	ding
r i: t	r e	d I N
re-	tread
r i: t	r e d
re-	treat
r i: t	r i: t
re-	tur-	na-	ble
r i:	t @r	n V	b V l
re-	tur-	nee
r V	t @r	n i:
re-	tur-	nees
r V	t @r	n i: z
re-	tur-	ning
r V	t @r	n I N
re-	turn
r V	t @r n
re-	turned
r V	t @r n d
re-	turns
r V	t @r n z
re-	u-	ni-	fi-	ca-	tion
r i:	u:	n I	f I	k eI	S V n
re-	u-	ni-	fied
r i:	u:	n I	f aI d
re-	u-	ni-	fy
r i:	u:	n I	f aI
re-	u-	ni-	ted
r i:	u:	n aI	t V d
re-	u-	ni-	ting
r i:	u:	n aI	t I N
re-	u-	nion
r i:	u: n	j V n
re-	u-	nions
r i:	u: n	j V n z
re-	u-	nite
r i:	u:	n aI t
re-	u-	nites
r i:	u:	n aI t s
re-	u-	sa-	ble
r i:	u:	z V	b V l
re-	u-	sing
r i:	j u:	z I N
re-	use
r i:	j u: s
re-	used
r i:	u: z d
re-	va
r eI	v V
re-	va-	lu-	a-	tion
r i:	v { l	j u:	eI	S V n
re-	va-	lu-	ing
r i:	v { l	j u:	I N
re-	va-	lue
r i:	v { l	j u:
re-	va-	lued
r i:	v { l	j u: d
re-	vam-	ping
r i:	v { m	p I N
re-	vamp
r i:	v { m p
re-	vamped
r i:	v { m p t
re-	vamps
r i:	v { m p s
re-	ve-	la-	tion
r e	v V	l eI	S V n
re-	ve-	la-	tions
r e	v V	l eI	S V n z
re-	ve-	la-	to-	ry
r I	v e	l V	t O@	i:
re-	ve-	ler
r e	v V	l @r
re-	ve-	lers
r e	v V	l @r z
re-	ve-	ling
r e	v V	l I N
re-	ve-	nue
r e	v V	n u:
re-	ve-	nues
r e	v V	n u: z
re-	ve-	ren-	tial
r e	v @r	e n	tS V l
re-	ve-	rence
r e	v @r	V n s
re-	ve-	rend
r e	v @r	V n d
re-	ve-	rent
r e	v @r	V n t
re-	ve-	rent-	ly
r e	v @r	V n	t l i:
re-	ve-	rie
r e	v @r	i:
re-	ve-	ries
r e	v @r	i: z
re-	vea-	ling
r I	v i:	l I N
re-	veal
r I	v i: l
re-	vealed
r I	v i: l d
re-	veals
r I	v i: l z
re-	vel
r e	v V l
re-	vel-	ry
r e	v V l	r i:
re-	veled
r e	v V l d
re-	vell
r eI	v eI l
re-	vels
r e	v V l z
re-	venge
r i:	v e n dZ
re-	ver-	be-	ra-	ted
r I	v @r	b @r	eI	t V d
re-	ver-	be-	ra-	ting
r I	v @r	b @r	eI	t I N
re-	ver-	be-	ra-	tion
r i:	v @r	b @r	eI	S V n
re-	ver-	be-	ra-	tions
r I	v @r	b @r	eI	S V n z
re-	ver-	be-	rate
r I	v @r	b @r	eI t
re-	ver-	be-	rates
r I	v @r	b @r	eI t s
re-	ver-	sal
r I	v @r	s V l
re-	ver-	sals
r I	v @r	s V l z
re-	ver-	ser
r I	v @r	s @r
re-	ver-	sers
r I	v @r	s @r z
re-	ver-	ses
r I	v @r	s V z
re-	ver-	si-	ble
r I	v @r	s I	b V l
re-	ver-	sing
r I	v @r	s I N
re-	ver-	sion
r I	v @r	Z V n
re-	ver-	ted
r I	v @r	t V d
re-	ver-	ting
r I	v @r	t I N
re-	verb
r i:	v @r b
re-	verbed
r i:	v @r b d
re-	vere
r I	v I@
re-	vered
r I	v I@ d
re-	verse
r I	v @r s
re-	versed
r I	v @r s t
re-	vert
r I	v @r t
re-	verts
r I	v @r t s
re-	vi-	ses
r I	v aI	z V z
re-	vi-	si-	ted
r i:	v I	z I	t I d
re-	vi-	si-	ting
r i:	v I	z I	t I N
re-	vi-	sing
r I	v aI	z I N
re-	vi-	sio-	ni-	sm
r i:	v I	Z V	n I	z V m
re-	vi-	sio-	nist
r i:	v I	Z V	n I s t
re-	vi-	sio-	nists
r i:	v I	Z V	n I s t s
re-	vi-	sion
r i:	v I	Z V n
re-	vi-	sions
r i:	v I	Z V n z
re-	vi-	sit
r i:	v I	z I t
re-	vi-	sits
r i:	v I	z I t s
re-	vi-	ta-	li-	za-	tion
r i:	v aI	t V	l V	z eI	S V n
re-	vi-	ta-	li-	zing
r i:	v aI	t V	l aI	z I N
re-	vi-	ta-	lize
r i:	v aI	t V	l aI z
re-	vi-	ta-	lized
r i:	v aI	t V	l aI z d
re-	vi-	va-	list
r i:	v aI	v V	l I s t
re-	vi-	val
r I	v aI	v V l
re-	vi-	vals
r i:	v aI	v V l z
re-	vi-	ving
r I	v aI	v I N
re-	vie-	wer
r i: v	j u:	@r
re-	vie-	wers
r i: v	j u:	@r z
re-	vie-	wing
r i: v	j u:	I N
re-	view
r i: v	j u:
re-	viewed
r i: v	j u: d
re-	views
r i: v	j u: z
re-	vile
r i:	v aI l
re-	viled
r i:	v aI l d
re-	vise
r I	v aI z
re-	vised
r I	v aI z d
re-	vive
r I	v aI v
re-	vived
r I	v aI v d
re-	vives
r i:	v aI v z
re-	vo-	ca-	ble
r e	v V	k V	b V l
re-	vo-	ca-	tion
r e	v V	k eI	S V n
re-	vo-	ca-	tions
r e	v V	k eI	S V n z
re-	vo-	king
r I	v @U	k I N
re-	vo-	lu-	tio-	na-	ries
r e	v V	l u:	S V	n e@	i: z
re-	vo-	lu-	tio-	na-	ry
r e	v V	l u:	S V	n e@	i:
re-	vo-	lu-	tio-	ni-	zing
r e	v V	l u:	S V	n aI	z I N
re-	vo-	lu-	tio-	nist
r e	v V	l u:	S V	n V s t
re-	vo-	lu-	tio-	nists
r e	v V	l u:	S V	n V s t s
re-	vo-	lu-	tio-	nize
r e	v V	l u:	S V	n aI z
re-	vo-	lu-	tio-	nized
r e	v V	l u:	S V	n aI z d
re-	vo-	lu-	tion
r e	v V	l u:	S V n
re-	vo-	lu-	tions
r e	v V	l u:	S V n z
re-	vo-	lu-	tion's
r e	v V	l u:	S V n z
re-	voir
r I v	w Q@
re-	voke
r I	v @U k
re-	voked
r I	v @U k t
re-	vol-	ted
r I	v @U l	t V d
re-	vol-	ting
r i:	v @U l	t I N
re-	vol-	ver
r I	v Q l	v @r
re-	vol-	vers
r I	v Q l	v @r z
re-	vol-	ving
r i:	v Q l	v I N
re-	volt
r I	v @U l t
re-	volts
r i:	v @U l t s
re-	volve
r i:	v Q l v
re-	volved
r i:	v Q l v d
re-	volves
r i:	v Q l v z
re-	vue
r I v	j u:
re-	vues
r I v	j u: z
re-	vul-	sion
r I	v V l	S V n
re-	war-	ded
r V	w O@	d V d
re-	war-	ding
r V	w O@	d I N
re-	ward
r V	w O@ d
re-	wards
r V	w O@ d z
re-	wey
r u:	i:
re-	wi-	r-	ing
r i:	w aI	@r	I N
re-	wi-	re
r i:	w aI	@r
re-	wi-	red
r i:	w aI	@r d
re-	wind
r i:	w aI n d
re-	wor-	king
r i:	w @r	k I N
re-	word
r i:	w @r d
re-	work
r i:	w @r k
re-	worked
r i:	w @r k t
re-	wri-	ting
r i:	r aI	t I N
re-	writ-	ten
r i:	r I	t V n
re-	write
r i:	r aI t
re-	writes
r i:	r aI t s
re-	xa-	na
r I g	z {	n V
re-	yes
r eI	I s
re-	zo-	ning
r i:	z @U	n I N
rea
r i:
rea-	cha-	ble
r i:	tS V	b V l
rea-	ches
r i:	tS V z
rea-	ching
r i:	tS I N
rea-	da-	bi-	li-	ty
r i:	d V	b I	l V	t i:
rea-	da-	ble
r i:	d V	b V l
rea-	der
r i:	d @r
rea-	der-	ship
r i:	d @r	S I p
rea-	ders
r i:	d @r z
rea-	der's
r i:	d @r z
rea-	di-	er
r e	d i:	@r
rea-	di-	ly
r e	d I	l i:
rea-	di-	ness
r e	d i:	n V s
rea-	died
r e	d i: d
rea-	dies
r e	d i: z
rea-	ding
r e	d I N
rea-	dings
r e	d I N z
rea-	dus
r e	d V s
rea-	dy
r e	d i:
rea-	dy-	ing
r e	d i:	I N
rea-	ga-	ni-	sm
r eI	g V	n I	z V m
rea-	ga-	nite
r eI	g V	n aI t
rea-	ga-	nites
r eI	g V	n aI t s
rea-	ga-	no-	mics
r eI	g V	n Q	m I k s
rea-	gan
r eI	g V n
rea-	gan's
r eI	g V n z
rea-	gen
r i:	g V n
rea-	li-	sm
r i:	l I	z V m
rea-	li-	za-	tion
r i:	l V	z eI	S V n
rea-	li-	za-	tions
r i:	l V	z eI	S V n z
rea-	li-	zing
r i:	l aI	z I N
rea-	list
r i:	l I s t
rea-	lists
r i:	l I s t s
rea-	lize
r i:	l aI z
rea-	lized
r i:	l aI z d
rea-	mer
r i:	m @r
rea-	mers
r i:	m @r z
rea-	mer's
r i:	m @r z
rea-	my
r i:	m i:
rea-	per
r i:	p @r
rea-	ping
r i:	p I N
rea-	ring
r I@	I N
rea-	so-	na-	ble
r i:	z V	n V	b V l
rea-	so-	na-	ble-	ness
r i:	z V	n V	b V l	n V s
rea-	so-	nab-	ly
r i:	z V	n V b	l i:
rea-	so-	ner
r i:	z V	n @r
rea-	so-	ner's
r i:	z V	n @r z
rea-	so-	ning
r i:	z V	n I N
rea-	son
r i:	z V n
rea-	soned
r i:	z V n d
rea-	sons
r i:	z V n z
rea-	ver
r i:	v @r
reach
r i: tS
reached
r i: tS t
read
r e d
read-	out
r i:	d aU t
reade
r e d
reads
r i: d z
read's
r i: d z
real
r i: l
real-	es-	tate
r i:	l V s	t eI t
real-	ly
r I	l i:
real-	po-	li-	tik
r i: l	p O:	l I	t I k
realm
r e l m
realms
r e l m z
ream
r i: m
reames
r i: m z
reams
r i: m z
reap
r i: p
reaped
r i: p t
reaps
r i: p s
rear
r I@
rear-	don
r I@	d V n
rear-	view
r I@ v	j u:
reared
r I@ d
rears
r I@ z
reave
r i: v
reaves
r i: v z
reb-	be
r i:	b V
reb-	be's
r i:	b V z
rec
r e k
rec-	ko-	ning
r e	k V	n I N
rec-	kon
r e	k V n
rec-	koned
r e	k V n d
rec-	kons
r e	k V n z
rec-	la-	ma-	tion
r e k	l V	m eI	S V n
rec-	lai-	mer
r i: k	l eI	m @r
rec-	lai-	mer's
r i: k	l eI	m @r z
rec-	lai-	ming
r i: k	l eI	m I N
rec-	laim
r i: k	l eI m
rec-	laimed
r i: k	l eI m d
rec-	ross
r i: k	r O: s
rec-	rui-	ted
r I k	r u:	t V d
rec-	rui-	ter
r I k	r u:	t @r
rec-	rui-	ters
r I k	r u:	t @r z
rec-	rui-	ting
r V k	r u:	t I N
rec-	ruit
r V k	r u: t
rec-	ruit-	ment
r V k	r u: t	m V n t
rec-	ruits
r V k	r u: t s
rec-	ruit's
r i: k	r u: t s
rec-	tal
r e k	t V l
rec-	tan-	gle
r e k	t { N	g V l
rec-	tan-	gles
r e k	t { N	g V l z
rec-	tan-	gu-	lar
r e k	t { N	g j V	l @r
rec-	ti-	fi-	ca-	tion
r e k	t I	f I	k eI	S V n
rec-	ti-	fi-	er
r e k	t I	f aI	@r
rec-	ti-	fi-	ers
r e k	t I	f aI	@r z
rec-	ti-	fied
r e k	t I	f aI d
rec-	ti-	fy
r e k	t I	f aI
rec-	ti-	fy-	ing
r e k	t I	f aI	I N
rec-	ti-	tude
r e k	t I	t u: d
rec-	to-	ry
r e k	t @r	i:
rec-	tor
r e k	t @r
rec-	tum
r e k	t V m
rech
r e k
rech-	ris-	ten
r i: k	r I	s V n
rech-	ris-	tened
r i: k	r I	s V n d
reck
r e k
reck-	less
r e k	l V s
reck-	less-	ly
r e k	l V s	l i:
reck-	less-	ness
r e k	l V s	n V s
red
r e d
red-	bird
r e d	b @r d
red-	bud
r e d	b V d
red-	coat
r e d	k @U t
red-	coats
r e d	k @U t s
red-	dell
r e	d V l
red-	den
r e	d V n
red-	der
r e	d @r
red-	dest
r e	d V s t
red-	dick
r e	d I k
red-	din
r e	d I n
red-	ding
r e	d I N
red-	dish
r e	d I S
red-	dy
r e	d i:
red-	field
r e d	f i: l d
red-	fish
r e d	f I S
red-	ford
r e d	f @r d
red-	ford's
r e d	f @r d z
red-	grave
r e d	g r eI v
red-	han-	ded
r e d	h { n	d V d
red-	hea-	ded
r e d	h e	d V d
red-	head
r e d	h e d
red-	heads
r e d	h e d z
red-	li-	ning
r e d	l aI	n I N
red-	man
r e d	m { n
red-	mon
r e d	m V n
red-	mond
r e d	m V n d
red-	mund
r e d	m V n d
red-	neck
r e d	n e k
red-	necks
r e d	n e k s
red-	ness
r e d	n V s
red-	poll
r e d	p @U l
red-	polls
r e d	p @U l z
red-	raf-	ted
r i: d	r { f	t V d
red-	raft
r i: d	r { f t
red-	raw
r i: d	r O:
red-	raw-	ing
r i: d	r O:	I N
red-	rawn
r i: d	r O: n
red-	res-	sing
r i: d	r e	s I N
red-	ress
r V d	r e s
red-	skin
r e d	s k I n
red-	skins
r e d	s k I n z
red-	stone
r e d	s t @U n
red-	stone's
r e d	s t @U n z
red-	wine
r e d	w aI n
red-	wood
r e d	w U d
red-	woods
r e d	w U d z
redd
r e d
reds
r e d z
ree
r i:
ree-	bok
r i:	b Q k
ree-	boks
r i:	b Q k s
ree-	bok's
r i:	b Q k s
)"
R"(ree-	der
r i:	d @r
ree-	ders
r i:	d @r z
ree-	dy
r i:	d i:
ree-	king
r i:	k I N
ree-	ling
r i:	l I N
ree-	se's
r i:	s V z
reece
r i: s
reed
r i: d
reeds
r i: d z
reed's
r i: d z
reef
r i: f
reefs
r i: f s
reek
r i: k
reeks
r i: k s
reel
r i: l
reeled
r i: l d
reels
r i: l z
reen
r i: n
rees
r i: z
reese
r i: s
reeve
r i: v
reeves
r i: v z
ref
r e f
ref-	la-	tion
r i: f	l eI	S V n
ref-	lag
r i: f	l { g
ref-	lag-	ging
r i: f	l {	g I N
ref-	lagged
r i: f	l { g d
ref-	late
r i: f	l eI t
ref-	le-	xes
r i: f	l e k	s V z
ref-	le-	xi-	vi-	ty
r i: f	l e k	s I	v I	t i:
ref-	le-	xive
r V f	l e k	s I v
ref-	le-	xive-	ly
r i: f	l e k	s I v	l i:
ref-	lec-	ted
r V f	l e k	t V d
ref-	lec-	ting
r V f	l e k	t I N
ref-	lec-	tion
r V f	l e k	S V n
ref-	lec-	tions
r V f	l e k	S V n z
ref-	lec-	tive
r V f	l e k	t I v
ref-	lect
r V f	l e k t
ref-	lects
r V f	l e k t s
ref-	lex
r i: f	l e k s
reg
r e g
reg-	gae
r e	g eI
reg-	gi-	o
r e	dZ i:	@U
reg-	gie
r e	dZ i:
reg-	gy
r e	g i:
reg-	ret
r I g	r e t
reg-	ret-	ful
r I g	r e t	f V l
reg-	ret-	ful-	ly
r I g	r e t	f V	l i:
reg-	ret-	ta-	ble
r I g	r e	t V	b V l
reg-	ret-	tab-	ly
r I g	r e	t V b	l i:
reg-	ret-	ted
r I g	r e	t V d
reg-	ret-	ting
r I g	r e	t I N
reg-	rets
r I g	r e t s
regs
r e g z
reh
r e
rehm
r e m
rehn-	quist
r e n	k w I s t
rei-	chel
r aI	k V l
rei-	chen-	bach
r aI	k V n	b Q k
rei-	chen-	berg
r aI	k V n	b @r g
rei-	chert
r aI	k @r t
rei-	der
r i:	d @r
rei-	fel
r aI	f V l
rei-	ki
r eI	k i:
rei-	mer
r aI	m @r
rei-	nal-	do
r eI	n Q l	d @U
rei-	necke
r aI	n I k
rei-	ner
r aI	n @r
rei-	ners
r aI	n @r z
rei-	ner's
r aI	n @r z
rei-	nert
r aI	n @r t
rei-	nert-	son
r aI	n @r t	s V n
rei-	ning
r eI	n I N
rei-	ser
r aI	s @r
rei-	sin-	ger
r aI	s I n	dZ @r
rei-	ter
r aI	t @r
reich
r aI k
reiche
r aI k
reich's
r aI k s
reid
r i: d
reid's
r i: d z
reif
r i: f
reig-	ning
r eI	n I N
reign
r eI n
reigned
r eI n d
reigns
r eI n z
reil
r eI l
reil-	ly
r aI	l i:
reil-	ly's
r aI	l i: z
reim
r i: m
rein
r eI n
rein-	deer
r eI n	d I@
rein-	hard
r aI n	h Q@ d
rein-	hardt
r aI n	h Q@ t
rein-	hart
r aI n	h Q@ t
rein-	hart's
r aI n	h Q@ t s
rein-	hold
r aI n	h @U l t
rein-	king
r aI N	k I N
rein-	wald
r aI n	w O: l d
reine
r eI n
reined
r eI n d
reinke
r eI N k
reins
r eI n z
reis
r i: z
reis-	man
r aI s	m V n
reis-	ner
r aI s	n @r
reisch
r aI S
reiss
r aI s
reit
r aI t
reit-	man
r aI t	m V n
reith
r i: T
rel-	la
r e	l V
rem
r e m
rem-	bert
r e m	b @r t
rem-	brandt
r e m	b r { n t
rem-	nant
r e m	n V n t
rem-	nants
r e m	n V n t s
rem-	sen
r e m	s V n
rempe
r e m p
ren
r e n
ren-	de-	ring
r e n	d @r	I N
ren-	de-	rings
r e n	d @r	I N z
ren-	der
r e n	d @r
ren-	dered
r e n	d @r d
ren-	ders
r e n	d @r z
ren-	dez-	vous
r Q n	d I	v u:
ren-	di-	tion
r e n	d I	S V n
ren-	di-	tions
r e n	d I	S V n z
ren-	ding
r e n	d I N
ren-	fred
r e n	f @r d
ren-	frew
r e n	f r u:
ren-	min-	bi
r e n	m I n	b i:
ren-	ner
r e	n @r
ren-	net
r e	n V t
ren-	nie
r e	n i:
ren-	ny
r e	n i:
ren-	ta-	ble
r e n	t V	b V l
ren-	tal
r e n	t V l
ren-	tals
r e n	t V l z
ren-	ted
r e n	t V d
ren-	ter
r e n	t @r
ren-	ters
r e n	t @r z
ren-	ting
r e n	t I N
ren-	ton
r e n	t V n
ren-	wick
r e n	w I k
renk
r e N k
renn
r e n
renne
r e n
rens
r e n z
rens-	se-	laer
r e n	s V	l I@
rent
r e n t
rents
r e n t s
rentsch
r e n tS
rentsch-	ler
r e n	tS l @r
rentz
r e n t s
rep
r e p
rep-	la-	cea-	ble
r i: p	l eI	s V	b V l
rep-	la-	ces
r V p	l eI	s V z
rep-	la-	cing
r V p	l eI	s I N
rep-	lace
r i: p	l eI s
rep-	lace-	ment
r V p	l eI s	m V n t
rep-	lace-	ments
r i: p	l eI s	m V n t s
rep-	laced
r i: p	l eI s t
rep-	lan-	ted
r i: p	l { n	t V d
rep-	lan-	ting
r i: p	l { n	t I N
rep-	lant
r i: p	l { n t
rep-	le-	nish-	ment
r V p	l e	n I S	m V n t
rep-	lete
r i: p	l i: t
rep-	li-	ca
r e p	l I	k V
rep-	li-	ca-	ted
r e p	l I	k eI	t I d
rep-	li-	ca-	ting
r e p	l I	k eI	t I N
rep-	li-	ca-	tion
r e p	l I	k eI	S V n
rep-	li-	cas
r e p	l I	k V z
rep-	li-	case
r e p	l I	k eI z
rep-	li-	cate
r e p	l I	k eI t
rep-	li-	cates
r e p	l I	k eI t s
rep-	lied
r V p	l aI d
rep-	lies
r V p	l aI z
rep-	ly
r V p	l aI
rep-	ly-	ing
r V p	l aI	I N
rep-	re-	hen-	si-	ble
r e p	r V	h e n	s V	b V l
rep-	re-	sen-	ta-	tio-	nal
r e p	r V	z V n	t eI	S V	n V l
rep-	re-	sen-	ta-	tion
r e p	r V	z e n	t eI	S V n
rep-	re-	sen-	ta-	tions
r e p	r V	z V n	t eI	S V n z
rep-	re-	sen-	ta-	tive
r e p	r V	z e n	t V	t I v
rep-	re-	sen-	ta-	tives
r e p	r V	z e n	t V	t I v z
rep-	re-	sen-	ta-	tive's
r e p	r V	z e n	t V	t I v z
rep-	re-	sen-	ted
r e p	r V	z e n	t V d
rep-	re-	sen-	ting
r e p	r V	z e n	t I N
rep-	re-	sent
r e p	r V	z e n t
rep-	re-	sents
r e p	r V	z e n t s
rep-	res-	sing
r i: p	r e	s I N
rep-	res-	sion
r i: p	r e	S V n
rep-	res-	sions
r i: p	r e	S V n z
rep-	res-	sive
r i: p	r e	s I v
rep-	ress
r i: p	r e s
rep-	ressed
r i: p	r e s t
rep-	ri-	cing
r i: p	r aI	s I N
rep-	ri-	man-	ded
r e p	r I	m { n	d I d
rep-	ri-	mand
r e p	r I	m { n d
rep-	ri-	mands
r e p	r I	m { n d z
rep-	ri-	sal
r i: p	r aI	z V l
rep-	ri-	sals
r V p	r aI	z V l z
rep-	rice
r i: p	r aI s
rep-	riced
r i: p	r aI s t
rep-	rieve
r i: p	r i: v
rep-	rin-	ted
r i: p	r I n	t V d
rep-	rin-	ting
r i: p	r I n	t I N
rep-	rint
r i: p	r I n t
rep-	rints
r i: p	r I n t s
rep-	rise
r V p	r aI z
rep-	ro-	bate
r e p	r O:	b eI t
rep-	ro-	ces-	sing
r i: p	r O:	s e	s I N
rep-	ro-	cess
r i: p	r O:	s e s
rep-	ro-	cessed
r i: p	r O:	s e s t
rep-	ro-	du-	ces
r i: p	r V	d u:	s V z
rep-	ro-	du-	cing
r i: p	r V	d u:	s I N
rep-	ro-	duc-	tion
r i: p	r V	d V k	S V n
rep-	ro-	duc-	tions
r i: p	r V	d V k	S V n z
rep-	ro-	duc-	tive
r i: p	r V	d V k	t I v
rep-	ro-	duce
r i: p	r V	d u: s
rep-	ro-	duced
r i: p	r V	d u: s t
rep-	ro-	gra-	phic
r e p	r @U g	r {	f I k
rep-	ro-	gra-	phics
r e p	r @U g	r {	f I k s
rep-	ro-	gram
r i: p	r @U g	r { m
rep-	ro-	gram-	ming
r i: p	r @U g	r {	m I N
rep-	ro-	grammed
r i: p	r @U g	r { m d
rep-	ro-	grams
r i: p	r @U g	r { m z
rep-	roach
r i: p	r @U tS
rep-	tile
r e p	t aI l
rep-	tiles
r e p	t aI l z
rep.
r e p
reph-	rase
r i: f	r eI z
repp
r e p
reps
r e p s
rep's
r e p s
res
r eI z
re's
r eI z
res-	che-	du-	ling
r i: s	k e	dZ u:	l I N
res-	che-	du-	lings
r i: S	k e	dZ u:	l I N z
res-	che-	dule
r i: s	k e	dZ u: l
res-	che-	duled
r i: s	k e	dZ u: l d
res-	cu-	er
r e s	k j u:	@r
res-	cu-	ers
r e s	k j u:	@r z
res-	cu-	ing
r e s	k j u:	I N
res-	cue
r e s	k j u:
res-	cued
r e s	k j u: d
res-	cues
r e s	k j u: z
res-	nais
r e s	n eI
res-	nik
r e s	n I k
res-	pec-	ta-	bi-	li-	ty
r i: s	p e k	t V	b I	l V	t i:
res-	pec-	ta-	ble
r V s	p e k	t V	b V l
res-	pec-	tab-	ly
r i: s	p e k	t V b	l i:
res-	pec-	ted
r V s	p e k	t V d
res-	pec-	ting
r i: s	p e k	t I N
res-	pec-	tive
r V s	p e k	t I v
res-	pec-	tive-	ly
r V s	p e k	t I v	l i:
res-	pect
r V s	p e k t
res-	pect-	ful
r V s	p e k	t f V l
res-	pect-	ful-	ly
r V s	p e k	t f V	l i:
res-	pects
r V s	p e k t s
res-	pi-	ra-	tion
r e s	p @r	eI	S V n
res-	pi-	ra-	to-	ry
r e s	p @r	V	t O@	i:
res-	pi-	ra-	tor
r e s	p @r	eI	t @r
res-	pi-	ra-	tors
r e s	p @r	eI	t @r z
res-	pite
r e s	p I t
res-	plen-	dent
r i: s	p l e n	d V n t
res-	pon-	ded
r V s	p Q n	d V d
res-	pon-	dent
r V s	p Q n	d V n t
res-	pon-	dents
r V s	p Q n	d V n t s
res-	pon-	der
r V s	p Q n	d @r
res-	pon-	ders
r V s	p Q n	d @r z
res-	pon-	ding
r V s	p Q n	d I N
res-	pon-	ses
r V s	p Q n	s V z
res-	pon-	si-	bi-	li-	ties
r i: s	p Q n	s I	b I	l I	t i: z
res-	pon-	si-	bi-	li-	ty
r i: s	p Q n	s I	b I	l I	t i:
res-	pon-	si-	ble
r i: s	p Q n	s I	b V l
res-	pon-	sib-	ly
r V s	p Q n	s V b	l i:
res-	pon-	sive
r V s	p Q n	s I v
res-	pon-	sive-	ness
r V s	p Q n	s I v	n V s
res-	pond
r V s	p Q n d
res-	ponds
r V s	p Q n d z
res-	ponse
r V s	p Q n s
res-	tage
r i: s	t eI dZ
res-	taged
r i: s	t eI dZ d
res-	ted
r e s	t V d
res-	ter
r e s	t @r
res-	ti-	tu-	tion
r e s	t I	t u:	S V n
res-	ti-	tute
r e s	t I	t u: t
res-	ti-	vo
r e s	t i:	v @U
res-	ting
r e s	t I N
res-	tive
r e s	t I v
res-	tive-	ness
r e s	t I v	n V s
res-	to-	ra-	tion
r e s	t @r	eI	S V n
res-	to-	ra-	tions
r e s	t @r	eI	S V n z
res-	to-	ra-	tive
r V s	t O@	V	t I v
res-	to-	rer
r V s	t O@	@r
res-	to-	ring
r V s	t O@	I N
res-	toc-	king
r i: s	t Q	k I N
res-	tock
r i: s	t Q k
res-	tocked
r i: s	t Q k t
res-	ton
r e s	t V n
res-	tore
r V s	t O@
res-	tored
r V s	t O@ d
res-	tores
r V s	t O@ z
resh
r e S
reske
r e s k
ress
r e s
ress-	ler
r e s	l @r
rest
r e s t
rest-	ful
r e s	t f V l
rest-	less
r e s	t l V s
rest-	less-	ly
r e s	t l V s	l i:
rest-	less-	ness
r e s	t l V s	n V s
rest-	rai-	ning
r i: s	t r eI	n I N
rest-	rain
r i: s	t r eI n
rest-	rained
r i: s	t r eI n d
rest-	rains
r i: s	t r eI n z
rest-	raint
r V s	t r eI n t
rest-	raints
r V s	t r eI n t s
rest-	ric-	ted
r i: s	t r I k	t V d
rest-	ric-	ting
r i: s	t r I k	t I N
rest-	ric-	tion
r i: s	t r I k	S V n
rest-	ric-	tions
r i: s	t r I k	S V n z
rest-	ric-	tive
r i: s	t r I k	t I v
rest-	ric-	tive-	ness
r V s	t r I k	t I v	n V s
rest-	rict
r i: s	t r I k t
rest-	ricts
r i: s	t r I k t s
rest-	room
r e s	t r u: m
rest-	rooms
r e s	t r u: m z
rest-	ruc-	tu-	ring
r i: s	t r V k	tS @r	I N
rest-	ruc-	tu-	rings
r i: s	t r V k	tS @r	I N z
rest-	ruc-	ture
r i: s	t r V k	tS @r
rest-	ruc-	tured
r i: s	t r V k	tS @r d
rest-	ruc-	tures
r i: s	t r V k	tS @r z
rests
r e s t s
ret
r e t
ret-	ra-	cing
r i: t	r eI	s I N
ret-	rac-	ta-	ble
r i: t	r { k	t V	b V l
ret-	rac-	ted
r i: t	r { k	t V d
ret-	rac-	ting
r i: t	r { k	t I N
ret-	rac-	tion
r i: t	r { k	S V n
ret-	race
r i: t	r eI s
ret-	race-	ment
r i: t	r eI s	m V n t
ret-	raced
r i: t	r eI s t
ret-	ract
r i: t	r { k t
ret-	racts
r i: t	r { k t s
ret-	rai-	ning
r i: t	r eI	n I N
ret-	rain
r i: t	r eI n
ret-	rained
r i: t	r eI n d
ret-	rans-	mis-	sion
r i: t	r { n	z m I	S V n
ret-	rea-	ding
r i: t	r e	d I N
ret-	rea-	ted
r i: t	r i:	t V d
ret-	rea-	ting
r i: t	r i:	t I N
ret-	read
r i: t	r e d
ret-	reads
r i: t	r e d z
ret-	reat
r i: t	r i: t
ret-	reats
r i: t	r i: t s
ret-	ren-	ching
r i: t	r e n	tS I N
ret-	rench
r i: t	r e n tS
ret-	rench-	ment
r i: t	r e n	tS m V n t
ret-	rench-	ments
r i: t	r e n	tS m V n t s
ret-	renched
r i: t	r e n tS t
ret-	ri-	al
r i: t	r aI	V l
ret-	ri-	bu-	tion
r e t	r I b	j u:	S V n
ret-	rie-	val
r V t	r i:	v V l
ret-	rie-	ver
r i: t	r i:	v @r
ret-	rie-	vers
r i: t	r i:	v @r z
ret-	rie-	ving
r i: t	r i:	v I N
ret-	ried
r i: t	r aI d
ret-	rieve
r V t	r i: v
ret-	rieved
r i: t	r i: v d
ret-	rieves
r V t	r i: v z
ret-	ro
r e t	r @U
ret-	ro-	ac-	ti-	vi-	ty
r e t	r @U	{ k	t I	v I	t i:
ret-	ro-	ac-	tive
r e t	r @U	{ k	t I v
ret-	ro-	ac-	tive-	ly
r e t	r @U	{ k	t I v	l i:
ret-	ro-	fit
r e t	r @U	f I t
ret-	ro-	fit-	ted
r e t	r @U	f I	t V d
ret-	ro-	fit-	ting
r e t	r @U	f I	t I N
ret-	ro-	fits
r e t	r @U	f I t s
ret-	ro-	grade
r e t	r V g	r eI d
ret-	ro-	vi-	ru-	ses
r e t	r @U	v aI	r V	s V z
ret-	ro-	vi-	rus
r e t	r @U	v aI	r V s
ret-	ro-	vir
r e t	r @U	v I@
ret-	ros-	pec-	tive
r e t	r V s	p e k	t I v
ret-	ros-	pec-	tive-	ly
r e t	r @U s	p e k	t I v	l i:
ret-	ros-	pect
r e t	r V s	p e k t
ret-	ry
r i: t	r aI
ret-	ry-	ing
r i: t	r aI	I N
ret-	ter
r e	t @r
ret-	tig
r e	t I g
rett-	ke
r e t	k i:
reu-	ben
r u:	b V n
reu-	ter
r OI	t @r
reu-	ters
r OI	t @r z
reu-	ter's
r OI	t @r z
reu-	ther
r OI	D @r
reut-	ter
r OI	t @r
rev
r e v
rev-	lon
r e v	l Q n
rev-	lon's
r e v	l Q n z
rev-	ving
r e	v I N
revs
r e v z
revved
r e v d
rew
r u:
rew-	rote
r i:	r @U t
rex
r e k s
rex-	ford
r e k	s f @r d
rex-	roth
r e k	s r Q T
rey
r eI
rey-	na
r eI	n V
rey-	nal-	do
r eI	n Q l	d @U
rey-	nard
r eI	n @r d
rey-	naud
r eI	n O: d
rey-	no-	sa
r i:	n @U	s V
rey-	nold
r e	n V l d
rey-	nolds
r e	n V l d z
reyk-	ja-	vik
r e k	j V	v I k
rha
r Q
rhame
r eI m
rhap-	so-	di-	zes
r { p	s V	d aI	z V z
rhap-	so-	dic
r { p	s Q	d I k
rhap-	so-	dize
r { p	s V	d aI z
rhap-	so-	dy
r { p	s V	d i:
rhe-	a
r i:	V
rhe-	sus
r i:	s V s
rhe-	ta
r i:	t V
rhe-	to-	ri-	cal
r V	t O@	I	k V l
rhe-	to-	ri-	cian
r e	t @r	I	S V n
rhe-	to-	ri-	cians
r e	t @r	I	S V n z
rhe-	to-	ric
r e	t @r	I k
rhe-	to-	rical-	ly
r V	t O@	I k	l i:
rhee
r i:
rhein
r aI n
rhein-	gold
r aI n	g @U l d
rhett
r e t
rheu-	ma-	ti-	sm
r u:	m V	t I	z V m
rheu-	ma-	tic
r u:	m {	t I k
rheu-	ma-	to-	lo-	gist
r u:	m V	t Q	l V	dZ V s t
rheu-	ma-	to-	lo-	gy
r u:	m V	t Q	l V	dZ i:
rheu-	ma-	toid
r u:	m V	t OI d
rhi-	no
r aI	n @U
rhi-	no-	ce-	ros
r aI	n Q	s @r	V s
rhi-	nos
r aI	n @U z
rhi-	zoi-	dal
r aI	z OI	d V l
rhi-	zoid
r aI	z OI d
rhi-	zome
r aI	z @U m
rhi-	zomes
r aI	z @U m z
rhine
r aI n
rhine-	hart
r aI n	h Q@ t
rhine-	land
r aI n	l { n d
rhine-	stone
r aI n	s t @U n
rhine-	stones
r aI n	s t @U n z
rhines
r aI n z
rho
r @U
rho-	da
r @U	d V
rho-	danthe
r @U	d { n T
rho-	de-	sia
r @U	d i:	Z V
rho-	de-	sian
r @U	d i:	Z V n
rho-	den
r @U	d V n
rho-	di-	a
r @U	d i:	V
rho-	di-	um
r @U	d i:	V m
rho-	dies
r @U	d i: z
rho-	do-	dend-	ron
r @U	d V	d e n	d r V n
rho-	dop-	sin
r @U	d Q p	s I n
rho-	dus
r @U	d V s
rho-	dy
r @U	d i:
rhoades
r @U d z
rhoads
r @U d z
rhode
r @U d
rhodes
r @U d z
rhon-	da
r Q n	d V
rhone
r @U n
rhu-	barb
r u:	b Q@ b
rhy-	mer
r aI	m @r
rhy-	ming
r aI	m I N
rhy-	ner
r aI	n @r
rhy-	thm
r I	D V m
rhy-	thms
r I	D V m z
rhyme
r aI m
rhymed
r aI m d
rhymes
r aI m z
rhyne
r aI n
rhynes
r aI n z
rhyth-	mic
r I D	m I k
rhyth-	mical-	ly
r I D	m I k	l i:
ri-	a
r i:	V
ri-	al
r aI	V l
ri-	ba
r i:	b V
ri-	ba-	vi-	rin
r V	b {	v @r	I n
ri-	bald
r aI	b Q l d
ri-	bald-	ry
r aI	b Q l	d r i:
ri-	bas
r aI	b V z
ri-	bau-	do
r i:	b O:	d @U
ri-	be-	ra
r i:	b e@	V
ri-	bi-	coff
r I	b I	k O: f
ri-	ca
r i:	k V
ri-	can
r i:	k V n
ri-	cans
r I	k V n z
ri-	car-	do
r I	k Q@	d @U
ri-	card
r I	k Q@ d
ri-	ca's
r i:	k V z
ri-	ce's
r aI	s V z
ri-	chard
r I	tS @r d
ri-	chard-	son
r I	tS @r d	s V n
ri-	chard-	son's
r I	tS @r d	s V n z
ri-	chards
r I	tS @r d z
ri-	chard's
r I	tS @r d z
ri-	chart
r I k	h Q@ t
ri-	che-	lieu
r I	S V	l u:
ri-	cher
r I	tS @r
ri-	chert
r I	k @r t
ri-	ches
r I	tS V z
ri-	chest
r I	tS V s t
ri-	chey
r I	tS i:
ri-	chie
r I	tS i:
ri-	ch's
r I	tS V z
ri-	co
r i:	k @U
ri-	co-	che-	ting
r I	k V	S eI	I N
ri-	co-	chet
r I	k V	S eI
ri-	co-	cheted
r I	k V	S eI d
ri-	co's
r i:	k @U z
ri-	da-	ble
r aI	d V	b V l
ri-	deau
r V	d @U
ri-	den
r aI	d V n
ri-	der
r aI	d @r
ri-	der-	ship
r aI	d @r	S I p
ri-	ders
r aI	d @r z
ri-	der's
r aI	d @r z
ri-	di-	cu-	ling
r I	d I k	j u:	l I N
ri-	di-	cu-	lous
r I	d I k	j V	l V s
ri-	di-	cu-	lous-	ly
r I	d I k	j V	l V s	l i:
ri-	di-	cule
r I	d I k	j u: l
ri-	di-	culed
r I	d I k	j u: l d
ri-	di-	cules
r I	d I k	j u: l z
ri-	din-	ger
r aI	d I	N @r
ri-	ding
r aI	d I N
ri-	dings
r aI	d I N z
ri-	eth
r aI	V T
ri-	fle
r aI	f V l
ri-	fle-	man
r aI	f V l	m V n
ri-	fle-	ry
r aI	f V l	r i:
ri-	fled
r aI	f V l d
ri-	fles
r aI	f V l z
ri-	ga
r i:	g V
ri-	ga-	to-	ni
r I	g V	t @U	n i:
ri-	gel
r aI	dZ V l
ri-	gi-	di-	ties
r I	dZ I	d I	t i: z
ri-	gi-	di-	ty
r I	dZ I	d I	t i:
ri-	gid
r I	dZ I d
ri-	gid-	ly
r I	dZ I d	l i:
ri-	go-	let-	to
r I	g V	l e	t @U
ri-	go-	rous
r I	g @r	V s
ri-	go-	rous-	ly
r I	g @r	V s	l i:
ri-	gor
r I	g @r
ri-	gors
r I	g @r z
ri-	gueur
r I g	j u: r
ri-	ha
r aI	h V
ri-	jn
r i:	V n
ri-	ker
r aI	k @r
ri-	ker's
r aI	k @r z
ri-	ley
r aI	l i:
ri-	ley's
r aI	l i: z
ri-	ma
r i:	m V
ri-	mer
r aI	m @r
ri-	na
r i:	n V
ri-	nal-	do
r V	n Q l	d @U
ri-	nard
r I	n @r d
ri-	ner
r aI	n @r
ri-	ni
r i:	n i:
ri-	o
r i:	@U
ri-	o-	jas
r i:	@U	j Q z
ri-	o-	ted
r aI	V	t V d
ri-	o-	ter
r aI	V	t @r
ri-	o-	ters
r aI	V	t @r z
ri-	o-	ting
r aI	V	t I N
ri-	o-	tous
r aI	V	t V s
ri-	on
r aI	V n
ri-	os
r i:	@U s
ri-	ot
r aI	V t
ri-	ots
r aI	V t s
ri-	pa
r i:	p V
ri-	pe-	ning
r aI	p V	n I N
ri-	pen
r aI	p V n
ri-	pened
r aI	p V n d
ri-	poste
r V	p @U s t
ri-	postes
r V	p O: s t s
ri-	sa
r i:	s V
ri-	sen
r I	z V n
ri-	ser
r aI	z @r
ri-	ses
r aI	z V z
ri-	sing
r aI	z I N
ri-	son
r I	s V n
ri-	ta
r i:	t V
ri-	ta-	lin
r I	t V	l I n
ri-	ta's
r i:	t V z
ri-	tu-	a-	lis-	ti-	cal-	ly
r I	tS u:	V	l I s	t I	k V	l i:
ri-	tu-	a-	lis-	tic
r I	tS u:	V	l I s	t I k
ri-	tu-	al
r I	tS u:	V l
ri-	tu-	als
r I	tS u:	V l z
ri-	va
r i:	v V
ri-	va-	ling
r aI	v V	l I N
ri-	val
r aI	v V l
ri-	val-	ries
r aI	v V l	r i: z
ri-	val-	ry
r aI	v V l	r i:
ri-	valed
r aI	v V l d
ri-	vals
r aI	v V l z
ri-	val's
r aI	v V l z
ri-	vard
r I	v @r d
ri-	vas
r i:	v Q z
)"
R"(ri-	ve-	ra
r I	v e@	V
ri-	ve-	ted
r I	v V	t V d
ri-	ve-	ting
r I	v V	t I N
ri-	ven
r I	v V n
ri-	ver
r I	v @r
ri-	ver-	bank
r I	v @r	b { N k
ri-	ver-	bed
r I	v @r	b e d
ri-	ver-	boat
r I	v @r	b @U t
ri-	ver-	boats
r I	v @r	b @U t s
ri-	ver-	dale
r I	v @r	d eI l
ri-	ver-	front
r I	v @r f	r V n t
ri-	ver-	head
r I	v @r	h e d
ri-	ver-	side
r I	v @r	s aI d
ri-	ver-	way
r I	v @r	w eI
ri-	vers
r I	v @r z
ri-	ver's
r I	v @r z
ri-	vet
r I	v V t
ri-	vets
r I	v V t s
ri-	vi-	e-	ra
r I	v i:	e@	V
ri-	vi-	ere
r I	v i:	e@
ri-	yadh
r i:	{ d
ri-	yals
r i:	j Q l z
rials
r aI l z
rib
r I b
rib-	bing
r I	b I N
rib-	ble
r I	b V l
rib-	bon
r I	b V n
rib-	bons
r I	b V n z
ribbed
r I b d
ribs
r I b z
ric
r I k
ric-	ca
r i:	k V
ric-	car-	do
r I	k Q@	d @U
ric-	ci
r i:	tS i:
ric-	ci-	o
r i:	tS i:	@U
ric-	kard
r I	k @r d
ric-	kards
r I	k @r d z
ric-	ke-	ty
r I	k V	t i:
ric-	ker
r I	k @r
ric-	kers
r I	k @r z
ric-	kert
r I	k @r t
ric-	kets
r I	k V t s
ric-	ketts
r I	k V t s
ric-	key
r I	k i:
ric-	ki
r I	k i:
ric-	kie
r I	k i:
ric-	kles
r I	k V l z
ric-	ky
r I	k i:
)"