R"(se-	ro-	lo-	gy
s e@	Q	l V	dZ i:
se-	ro-	to-	nin
s @r	V	t @U	n I n
se-	rum
s I@	V m
se-	sa-	me
s e	s V	m i:
se-	thi
s e	T i:
se-	ti
s e	t i:
se-	to
s e	t @U
se-	ton
s i:	t V n
se-	ve-	rance
s e	v @r	V n s
se-	ve-	rest
s V	v I@	V s t
se-	ve-	ri-	ni
s e	v @r	i:	n i:
se-	ve-	ri-	ty
s I	v e@	V	t i:
se-	ve-	rin
s e	v @r	I n
se-	ve-	ring
s e	v @r	I N
se-	ven
s e	v V n
se-	ven-	fold
s e	v V n	f @U l d
se-	ven-	teen
s e	v V n	t i: n
se-	ven-	teens
s e	v V n	t i: n z
se-	ven-	teenth
s e	v V n	t i: n T
se-	ven-	ti-	eth
s e	v V n	t i:	V T
se-	ven-	ties
s e	v V n	t i: z
se-	ven-	ty
s e	v V n	t i:
se-	ven-	ty's
s e	v V n	t i: z
se-	vens
s e	v V n z
se-	ven's
s e	v V n z
se-	venth
s e	v V n T
se-	venths
s e	v V n T s
se-	ver
s e	v @r
se-	ver-	son
s e	v @r	s V n
se-	vere
s V	v I@
se-	vere-	ly
s V	v I@	l i:
se-	vered
s e	v @r d
se-	vern
s e	v @r n
se-	vers
s e	v @r z
se-	vier
s e v	j @r
se-	vil-	la
s e	v I	l V
se-	ville
s V	v I l
se-	vin
s e	v I n
se-	wage
s u:	I dZ
se-	ward
s u:	@r d
se-	we-	rage
s u:	@r	I dZ
se-	well
s u:	V l
se-	wer
s u:	@r
se-	wers
s u:	@r z
se-	wing
s @U	I N
se-	xes
s e k	s V z
se-	xi-	er
s e k	s i:	@r
se-	xi-	est
s e k	s i:	V s t
se-	xi-	sm
s e k	s I	z V m
se-	xist
s e k	s I s t
se-	xy
s e k	s i:
sea
s i:
sea-	beach
s i:	b i: tS
sea-	bed
s i:	b e d
sea-	bee
s i:	b i:
sea-	bees
s i:	b i: z
sea-	ber-	ry
s i:	b e@	i:
sea-	board
s i:	b O@ d
sea-	borne
s i:	b O@ n
sea-	brook
s i: b	r U k
sea-	brook's
s i: b	r U k s
sea-	bu-	ry
s i:	b e@	i:
sea-	coast
s i:	k @U s t
sea-	drift
s i: d	r I f t
sea-	fa-	rer
s i:	f e@	@r
sea-	fa-	rers
s i:	f e@	@r z
sea-	food
s i:	f u: d
sea-	foods
s i:	f u: d z
sea-	ford
s i:	f @r d
sea-	front
s i: f	r V n t
sea-	gate
s i:	g eI t
sea-	gate's
s i:	g eI t s
sea-	go-	ing
s i:	g @U	I N
sea-	gram
s i: g	r V m
sea-	gram's
s i: g	r V m z
sea-	grave
s i: g	r eI v
sea-	graves
s i: g	r eI v z
sea-	gull
s i:	g V l
sea-	gulls
s i:	g V l z
sea-	hawk
s i:	h O: k
sea-	hawks
s i:	h O: k s
sea-	lant
s i:	l V n t
sea-	lants
s i:	l V n t s
sea-	ler
s i:	l @r
sea-	lift
s i:	l I f t
sea-	ling
s i:	l I N
sea-	ly
s i:	l i:
sea-	man
s i:	m V n
sea-	man's
s i:	m V n z
sea-	men
s i:	m V n
sea-	mus
S eI	m V s
sea-	my
s i:	m i:
sea-	nor
s i:	n @r
sea-	port
s i:	p O@ t
sea-	ports
s i:	p O@ t s
sea-	ring
s I@	I N
sea-	shell
s i:	S e l
sea-	shells
s i:	S e l z
sea-	shore
s i:	S O@
sea-	sick
s i:	s I k
sea-	side
s i:	s aI d
sea-	so-	na-	ble
s i:	z V	n V	b V l
sea-	so-	na-	li-	ty
s i:	z V	n {	l V	t i:
sea-	so-	nal
s i:	z V	n V l
sea-	so-	nal-	ly
s i:	z V	n V	l i:
sea-	so-	ning
s i:	z V	n I N
sea-	so-	nings
s i:	z V	n I N z
sea-	son
s i:	z V n
sea-	soned
s i:	z V n d
sea-	sons
s i:	z V n z
sea-	son's
s i:	z V n z
sea-	strand
s i: s	t r { n d
sea-	ted
s i:	t V d
sea-	ter
s i:	t @r
sea-	ting
s i:	t I N
sea-	tings
s i:	t I N z
sea-	to
s i:	t @U
sea-	ton
s i:	t V n
sea-	train
s i: t	r eI n
sea-	ver
s i:	v @r
sea-	vey
s i:	v i:
sea-	wa-	ter
s i:	w Q	t @r
sea-	ward
s i:	w @r d
sea-	way
s i:	w eI
sea-	weed
s i:	w i: d
sea-	weeds
s i:	w i: d z
sea-	wor-	thy
s i:	w O@	D i:
seal
s i: l
seale
s i: l
sealed
s i: l d
seals
s i: l z
seal's
s i: l z
seam
s i: m
seam-	less
s i: m	l V s
seam-	less-	ly
s i: m	l V s	l i:
seam-	ster
s i: m	s t @r
seams
s i: m z
seams-	tres-	ses
s i: m	s t r V	s V z
seams-	tress
s i: m	s t r V s
sean
S O: n
sean's
S O: n z
sear
s I@
sear-	cher
s @r	tS @r
sear-	chers
s @r	tS @r z
sear-	ches
s @r	tS V z
sear-	ching
s @r	tS I N
sear-	s's
s I@	z V z
search
s @r tS
search-	light
s @r tS	l aI t
search-	lights
s @r tS	l aI t s
searched
s @r tS t
seared
s I@ d
searle
s @r l
searles
s @r l z
searle's
s @r l z
sears
s I@ z
seas
s i: z
sea's
s i: z
sease
s i: z
seat
s i: t
seat-	belt
s i: t	b e l t
seat-	belts
s i: t	b e l t s
seats
s i: t s
seat's
s i: t s
seb-	ring
s i: b	r I N
sec
s e k
sec-	kel
s e	k V l
sec-	lu-	ded
s I k	l u:	d V d
sec-	lu-	sion
s I k	l u:	Z V n
sec-	lude
s I k	l u: d
sec-	re-	ta-	ri-	al
s e k	r V	t e@	i:	V l
sec-	re-	ta-	ri-	at
s e k	r V	t e@	i:	V t
sec-	re-	ta-	ries
s e k	r V	t e@	i: z
sec-	re-	ta-	ry
s e k	r V	t e@	i:
sec-	re-	ta-	ry's
s e k	r V	t e@	i: z
sec-	re-	ted
s V k	r i:	t V d
sec-	re-	tion
s V k	r i:	S V n
sec-	re-	tions
s V k	r i:	S V n z
sec-	re-	tive
s i: k	r V	t I v
sec-	re-	tive-	ness
s i: k	r V	t I v	n V s
sec-	ret
s i: k	r V t
sec-	ret-	ly
s i: k	r V t	l i:
sec-	rete
s I k	r i: t
sec-	rets
s i: k	r V t s
sec-	ta-	ri-	a-	ni-	sm
s e k	t e@	i:	V	n I	z V m
sec-	ta-	ri-	an
s e k	t e@	i:	V n
sec-	tio-	nal
s e k	S V	n V l
sec-	tio-	ning
s e k	S V	n I N
sec-	tion
s e k	S V n
sec-	tioned
s e k	S V n d
sec-	tions
s e k	S V n z
sec-	tion's
s e k	S V n z
sec-	to-	ral
s e k	t @r	V l
sec-	tor
s e k	t @r
sec-	tors
s e k	t @r z
sec-	tor's
s e k	t @r z
seck
s e k
sect
s e k t
sects
s e k t s
sect's
s e k t s
sed-	ber-	ry
s e d	b e@	i:
sed-	don
s e	d V n
sedg-	wick
s e dZ	w I k
sedge
s e dZ
sedge-	wick
s e dZ	w I k
see
s i:
see-	beck
s i:	b e k
see-	ded
s i:	d V d
see-	ding
s i:	d I N
see-	dy
s i:	d i:
see-	ger
s i:	g @r
see-	ing
s i:	I N
see-	ker
s i:	k @r
see-	kers
s i:	k @r z
see-	ker's
s i:	k @r z
see-	king
s i:	k I N
see-	konk
s i:	k Q N k
see-	ley
s i:	l i:
see-	ling
s i:	l I N
see-	ly
s i:	l i:
see-	ma
s i:	m Q
see-	ming
s i:	m I N
see-	ming-	ly
s i:	m I N	l i:
see-	page
s i:	p I dZ
see-	ping
s i:	p I N
see-	saw
s i:	s O:
see-	saw-	ing
s i:	s O:	I N
see-	sawed
s i:	s O: d
see-	thing
s i:	T I N
seed
s i: d
seed-	ea-	ter
s i:	d i:	t @r
seed-	ea-	ters
s i:	d i:	t @r z
seed-	ling
s i: d	l I N
seed-	lings
s i: d	l I N z
seed-	pod
s i: d	p Q d
seeds
s i: d z
seeds-	man
s i: d	z m V n
seek
s i: k
seeks
s i: k s
seel
s i: l
seem
s i: m
seemed
s i: m d
seems
s i: m z
seen
s i: n
seep
s i: p
seeped
s i: p t
seeps
s i: p s
seer
s i: r
seers
s i: r z
sees
s i: z
seethe
s i: D
sef-	ton
s e f	t V n
seg-	men-	ta-	tion
s e g	m V n	t eI	S V n
seg-	men-	ted
s e g	m e n	t V d
seg-	ment
s e g	m V n t
seg-	ments
s e g	m V n t s
seg-	ment's
s e g	m V n t s
seg-	ner
s e g	n @r
segue
s e g
sei-	ber
s aI	b @r
sei-	bert
s aI	b @r t
sei-	bold
s aI	b @U l d
sei-	del
s aI	d V l
sei-	den
s aI	d V n
sei-	fert
s aI	f @r t
sei-	g-	ler
s aI	g V	l @r
sei-	gel
s aI	g V l
sei-	ko
s eI	k @U
sei-	ne
s eI	n i:
sei-	ser
s aI	s @r
sei-	ter
s aI	t @r
sei-	zes
s i:	z V z
sei-	zing
s i:	z I N
sei-	zure
s i:	Z @r
sei-	zures
s i:	Z @r z
seid
s aI d
seid-	ler
s aI d	l @r
seif
s i: f
seig-	ni-	o-	rage
s i: g	n i:	@r	I dZ
seige
s i: dZ
seil
s aI l
seils
s aI l z
sein-	feld
s aI n	f e l d
sein-	feld's
s aI n	f e l d z
seis
s i: s
seis-	mic
s aI z	m I k
seis-	mo-	lo-	gist
s aI z	m Q	l V	dZ V s t
seis-	mo-	lo-	gists
s aI z	m Q	l V	dZ V s t s
seis-	mo-	lo-	gy
s aI z	m Q	l V	dZ i:
seitz
s aI t s
seize
s i: z
seized
s i: z d
sejm
s eI m
sel-	by
s e l	b i:
sel-	da
s e l	d V
sel-	den
s e l	d V n
sel-	dom
s e l	d V m
sel-	don
s e l	d V n
sel-	fish
s e l	f I S
sel-	fish-	ness
s e l	f I S	n V s
sel-	kirk
s e l	k @r k
sel-	kirk's
s e l	k @r k s
sel-	la
s e	l V
sel-	lar-	s's
s e	l @r	z V z
sel-	lars
s e	l @r z
sel-	ler
s e	l @r
sel-	lers
s e	l @r z
sel-	ler's
s e	l @r z
sel-	lers'
s e	l @r z
sel-	ling
s e	l I N
sel-	ma
s e l	m V
sel-	mer
s e l	m @r
sel-	va
s eI l	v V
sel-	vage
s e l	v I dZ
sel-	way
s e l	w eI
sel-	win
s e l	w I n
sel-	wyn
s e l	w I n
self
s e l f
self-	ag-	gran-	di-	zing
s e l	f V g	r { n	d aI	z I N
self-	ag-	gran-	dize-	ment
s e l	f { g	r V n	d aI z	m V n t
self-	con-	fi-	dence
s e l	f k Q n	f I	d e n s
self-	con-	fi-	dent
s e l	f k Q n	f I	d e n t
self-	con-	sis-	tent
s e l	f k V n	s I s	t V n t
self-	con-	tained
s e l	f k V n	t eI n d
self-	cong-	ra-	tu-	la-	tion
s e l	f k V n	g r {	tS V	l eI	S V n
self-	cont-	rol
s e l	f k V n	t r @U l
self-	de-	cei-	ving
s e l	f d i:	s i:	v I N
self-	de-	cep-	tion
s e l	f d V	s e p	S V n
self-	de-	ter-	mi-	na-	tion
s e l	f d V	t @r	m V	n eI	S V n
self-	dep-	re-	ca-	ting
s e l	f d e p	r V	k eI	t I N
self-	en-	rich-	ment
s e l	f V n	r I tS	m V n t
self-	go-	ver-	ning
s e l	f g V	v @r	n I N
self-	go-	vern-	ment
s e l	f g V	v @r n	m V n t
self-	help
s e l	f h e l p
self-	imp-	rove-	ment
s e l	f I m	p r u: v	m V n t
self-	less
s e l	f l V s
self-	less-	ness
s e l	f l V s	n V s
self-	per-	pe-	tu-	a-	ting
s e l	f p @r	p e	tS u:	eI	t I N
self-	per-	pe-	tu-	a-	tion
s e l	f p @r	p e	tS u:	eI	S V n
self-	port-	rait
s e l	f p O@ t	r eI t
self-	pro-	fessed
s e l	f p r V	f e s t
self-	ridge
s e l	f r I dZ
self-	sub-	sis-	tence
s e l	f s V b	s I s	t V n s
self-	suf-	fi-	cien-	cy
s e l	f s V	f I	S V n	s i:
self-	suf-	fi-	cient
s e l	f s V	f I	S V n t
self-	tor-	ment
s e l	f t O@	m e n t
selfs
s e l f s
self's
s e l f s
sell
s e l
sell-	off
s e	l O: f
sell-	offs
s e	l O: f s
sell-	out
s e	l aU t
sell-	outs
s e	l aU t s
selle
s e l
sells
s e l z
selt-	zer
s e l	t s @r
selves
s e l v z
selz
s e l z
sem-	blance
s e m	b l V n s
sem-	mel
s e	m V l
sem-	ple
s e m	p V l
sem-	tex
s e m	t e k s
semmes
s e m z
sen
s e n
sen-	dak
s e n	d { k
sen-	der
s e n	d @r
sen-	ders
s e n	d @r z
sen-	ding
s e n	d I N
sen-	na
s e	n V
sen-	net
s e	n V t
sen-	nett
s e	n e t
sen-	sa-	tio-	na-	li-	sm
s e n	s eI	S V	n V	l I	z V m
sen-	sa-	tio-	na-	li-	zes
s e n	s eI	S V	n V	l aI	z V z
sen-	sa-	tio-	na-	li-	zing
s e n	s eI	S V	n V	l aI	z I N
sen-	sa-	tio-	na-	lis-	tic
s e n	s eI	S V	n V	l I s	t I k
sen-	sa-	tio-	na-	list
s e n	s eI	S V	n V	l I s t
sen-	sa-	tio-	na-	lize
s e n	s eI	S V	n V	l aI z
sen-	sa-	tio-	na-	lized
s e n	s eI	S V	n V	l aI z d
sen-	sa-	tio-	nal
s e n	s eI	S V	n V l
sen-	sa-	tion
s e n	s eI	S V n
sen-	sa-	tions
s e n	s eI	S V n z
sen-	ses
s e n	s V z
sen-	si-	bi-	li-	ties
s e n	s I	b I	l I	t i: z
sen-	si-	bi-	li-	ty
s e n	s I	b I	l I	t i:
sen-	si-	ble
s e n	s I	b V l
sen-	si-	ti-	vi-	ties
s e n	s I	t I	v I	t i: z
sen-	si-	ti-	vi-	ty
s e n	s I	t I	v I	t i:
sen-	si-	tive
s e n	s I	t I v
sen-	si-	tive-	ly
s e n	s I	t I v	l i:
sen-	si-	tive-	ness
s e n	s I	t I v	n e s
sen-	si-	tize
s e n	s I	t aI z
sen-	si-	tized
s e n	s I	t aI z d
sen-	sib-	ly
s e n	s I b	l i:
sen-	sing
s e n	s I N
sen-	so-	ry
s e n	s @r	i:
sen-	sor
s e n	s @r
sen-	sors
s e n	s @r z
sen-	sor's
s e n	s @r z
sen-	su-	a-	li-	ty
s e n	tS V	w {	l V	t i:
sen-	su-	al
s e n	tS V	w V l
sen-	su-	ous
s e n	tS V	w V s
sen-	ten-	ces
s e n	t V n	s V z
sen-	ten-	cing
s e n	t V n	s I N
sen-	tence
s e n	t V n s
sen-	tenced
s e n	t V n s t
sen-	ti-	men-	ta-	li-	ty
s e n	t I	m e n	t {	l I	t i:
sen-	ti-	men-	tal
s e n	t I	m e n	t V l
sen-	ti-	ment
s e n	t I	m e n t
sen-	ti-	ments
s e n	t I	m e n t s
sen-	ti-	nel
s e n	t I	n e l
sen-	ti-	nels
s e n	t I	n e l z
send
s e n d
sends
s e n d z
senn
s e n
sens
s e n z
sense
s e n s
sense-	less
s e n	s l V s
sensed
s e n s t
sent
s e n t
sent-	ries
s e n	t r i: z
sent-	ry
s e n	t r i:
seoul
s @U l
seoul's
s @U l z
sep
s e p
sep-	pa-	la
s e	p Q	l V
sep-	sis
s e p	s I s
sep-	ta
s e p	t V
sep-	tem-	ber
s e p	t e m	b @r
sep-	tem-	ber's
s e p	t e m	b @r z
sep-	ti-	ma
s e p	t i:	m V
sep-	tic
s e p	t I k
sep-	tu-	a-	ge-	na-	ri-	an
s e p	tS u:	V	dZ V	n e@	i:	V n
sept
s e p t
ser-	bi-	a
s @r	b i:	V
ser-	bi-	an
s @r	b i:	V n
ser-	bi-	ans
s @r	b i:	V n z
ser-	bi-	a's
s @r	b i:	V z
ser-	geant
s Q@	dZ V n t
ser-	geants
s Q@	dZ V n t s
ser-	gei
s @r	g eI
ser-	gent
s @r	dZ V n t
ser-	gi-	o
s @r	dZ i:	@U
ser-	gi-	us
s @r	dZ i:	V s
ser-	le
s O@	V l
ser-	mon
s @r	m V n
ser-	mons
s @r	m V n z
ser-	pen-	tine
s @r	p V n	t aI n
ser-	pent
s @r	p V n t
ser-	pents
s @r	p V n t s
ser-	pent's
s @r	p V n t s
ser-	ra
s e@	V
ser-	ra-	no
s @r	Q	n @U
ser-	ra-	no's
s @r	Q	n @U z
ser-	ra-	ted
s e@	eI	t V d
ser-	ra's
s e@	V z
ser-	rate
s e@	eI t
ser-	res
s e@	e s
ser-	vais
s @r	v eI
ser-	vant
s @r	v V n t
ser-	vants
s @r	v V n t s
ser-	ver
s @r	v @r
ser-	vers
s @r	v @r z
ser-	vi-	cea-	ble
s @r	v V	s V	b V l
ser-	vi-	cer
s @r	v V	s @r
ser-	vi-	ces
s @r	v V	s V z
ser-	vi-	ce's
s @r	v V	s V z
ser-	vi-	cing
s @r	v V	s I N
ser-	vi-	tude
s @r	v V	t u: d
ser-	vice
s @r	v V s
ser-	vice-	man
s @r	v V s	m { n
ser-	vice-	men
s @r	v V s	m e n
ser-	viced
s @r	v V s t
ser-	vile
s @r	v V l
ser-	ving
s @r	v I N
ser-	vings
s @r	v I N z
ser-	vo
s @r	v @U
serb
s @r b
serbs
s @r b z
serb's
s @r b z
sere
s I@
seres
s i: r z
serf
s @r f
serfs
s @r f s
serge
s @r dZ
serr
s e@
serv
s @r v
serve
s @r v
served
s @r v d
serves
s @r v z
ses-	sa
s e	s V
ses-	sion
s e	S V n
ses-	sions
s e	S V n z
ses-	sion's
s e	S V n z
sess-	ler
s e s	l @r
set
s e t
set-	back
s e t	b { k
set-	backs
s e t	b { k s
set-	t-	ler
s e	t V	l @r
set-	t-	ling
s e	t V	l I N
set-	ter
s e	t @r
set-	ters
s e	t @r z
set-	ting
s e	t I N
set-	tings
s e	t I N z
set-	tle
s e	t V l
set-	tle-	ment
s e	t V l	m V n t
set-	tle-	ments
s e	t V l	m V n t s
set-	tle-	ment's
s e	t V l	m V n t s
set-	tled
s e	t V l d
set-	tles
s e	t V l z
set-	up
s e	t V p
set-	ups
s e	t V p s
seth
s e T
seth's
s e T s
sets
s e t s
sett-	lers
s e t	l @r z
seuss
s u: s
sev-	ru-	ga
s e v	r u:	g V
seve-	ral
s e v	r V l
seve-	ral-	ly
s e v	r V	l i:
sew
s @U
sewed
s @U d
sewn
s @U n
sex
s e k s
sex-	less
s e k	s l V s
sex-	tet
s e k	s t e t
sex-	ton
s e k	s t V n
sex-	tup-	let
s e k	s t V p	l V t
sex-	tup-	lets
s e k	s t V p	l V t s
sex-	tus
s e k	s t V s
sex-	u-	a-	li-	ty
s e k	S u:	{	l V	t i:
sex-	u-	al
s e k	S u:	V l
sex-	u-	al-	ly
s e k	S u:	V	l i:
sexed
s e k s t
sey-	fert
s eI	f @r t
sey-	ler
s eI	l @r
sey-	mour
s i:	m O@
sey-	mour's
s i:	m O@ z
sfor-	za
s f O@	z V
sha
S Q
sha-	ded
S eI	d V d
sha-	der
S eI	d @r
sha-	ding
S eI	d I N
sha-	dings
S eI	d I N z
sha-	do-	wy
S {	d @U	i:
sha-	dow
S {	d @U
sha-	dow-	ing
S {	d @U	I N
sha-	dow-	land
S {	d @U	l { n d
sha-	dow-	lands
S {	d @U	l { n d z
sha-	dowed
S {	d @U d
sha-	dows
S {	d @U z
sha-	dy
S eI	d i:
sha-	er
S eI	@r
sha-	fer
S eI	f @r
sha-	heen
S V	h i: n
sha-	hin
S {	h I n
sha-	ka
S Q	k V
sha-	ken
S eI	k V n
sha-	ker
S eI	k @r
sha-	kers
S eI	k @r z
sha-	ki-	er
S eI	k i:	@r
sha-	ki-	est
S eI	k i:	V s t
sha-	ki-	ness
S eI	k i:	n V s
sha-	king
S eI	k I N
sha-	ky
S eI	k i:
sha-	lom
S V	l @U m
sha-	man
S eI	m V n
sha-	mans
S eI	m V n z
sha-	mas
S {	m V s
sha-	ming
S eI	m I N
sha-	mir
S V	m I@
sha-	mus
S eI	m V s
sha-	na
S {	n V
sha-	na-	han
S {	n V	h { n
sha-	ner
S eI	n @r
sha-	pi-	ro
S V	p I@	@U
sha-	pi-	ro's
S V	p I@	@U z
sha-	ping
S eI	p I N
sha-	ra
S Q@	V
sha-	rer
S e@	@r
sha-	ri
S Q@	i:
sha-	ri-	a
S e@	i:	V
sha-	rif
S @r	i: f
sha-	ring
S e@	I N
sha-	ron
S e@	V n
sha-	ron's
S e@	V n z
sha-	ryl
S e@	V l
sha-	ven
S eI	v V n
sha-	ver
S eI	v @r
sha-	vers
S eI	v @r z
sha-	ving
S eI	v I N
sha-	vings
S eI	v I N z
shab-	by
S {	b i:
shac-	kle
S {	k V l
shac-	kle-	ton
S {	k V l	t V n
shac-	kled
S {	k V l d
shac-	kles
S {	k V l z
shack
S { k
shacks
S { k s
shad
S { d
shad-	bush
S { d	b U S
shad-	dock
S {	d V k
shad-	well
S { d	w e l
shade
S eI d
shades
S eI d z
shad's
S { d z
shae-	fer
S eI	f @r
shaef-	fer
S e	f @r
shaf-	fer
S eI	f @r
shaf-	ted
S { f	t V d
shaf-	ting
S { f	t I N
shaff
S { f
shaft
S { f t
shafts
S { f t s
shag
S { g
shag-	gy
S {	g i:
shah
S Q
shah's
S Q z
shaikh
S eI k
shaine
S eI n
shake
S eI k
shake-	down
S eI k	d aU n
shake-	downs
S eI k	d aU n z
shake-	out
S eI	k aU t
shake-	spear-	e-	an
S eI k	s p I@	i:	V n
shake-	speare
S eI k	s p i: r
shake-	up
S eI	k V p
shake-	ups
S eI	k V p s
shakes
S eI k s
shal-	lo-	wer
S {	l @U	@r
shal-	low
S {	l @U
shal-	low-	ness
S {	l @U	n V s
shale
S eI l
shales
S eI l z
shall
S { l
shalt
S { l t
sham
S { m
sham-	baugh
S { m	b O:
sham-	ble
S { m	b V l
sham-	bles
S { m	b V l z
sham-	poo
S { m	p u:
sham-	pooed
S { m	p u: d
sham-	poos
S { m	p u: z
sham-	rock
S { m	r Q k
sham-	rock's
S { m	r Q k s
shame
S eI m
shame-	ful
S eI m	f V l
shame-	less
S eI m	l V s
shame-	less-	ly
S eI m	l V s	l i:
shamed
S eI m d
shames
S eI m z
shan
S { n
shan-	dong
S Q n	d @U N
shan-	dy
S { n	d i:
shan-	ghai
S { N	h aI
shan-	ghai's
S { N	h aI z
shan-	ker
S { N	k @r
shan-	ley
S { n	l i:
shan-	non
S {	n V n
shan-	non's
S {	n V n z
shan-	ti
S { n	t i:
shan-	ties
S { n	t i: z
shan-	ty
S { n	t i:
shan-	ty-	town
S { n	t i:	t aU n
shan-	ty-	towns
S { n	t i:	t aU n z
shand
S { n d
shands
S { n d z
shane
S eI n
shank
S { N k
shanks
S { N k s
shap
S { p
shap-	ley
S { p	l i:
shape
S eI p
shape-	less
S eI p	l V s
shape-	ly
S eI p	l i:
shaped
S eI p t
shapes
S eI p s
)"
R"(shar-	king
S Q@	k I N
shar-	la
S Q@	l V
shar-	leen
S Q@	l i: n
shar-	lene
S Q@	l i: n
shar-	line
S Q@	l aI n
shar-	ma
S Q@	m V
shar-	man
S Q@	m V n
shar-	ma's
S Q@	m V z
shar-	pe-	ning
S Q@	p V	n I N
shar-	pen
S Q@	p V n
shar-	pened
S Q@	p V n d
shar-	pens
S Q@	p V n z
shar-	per
S Q@	p @r
shar-	pest
S Q@	p V s t
shar-	pie
S Q@	p i:
shar-	ples
S Q@	p V l z
shar-	py
S Q@	p i:
shar-	py's
S Q@	p i: z
shar-	ron
S {	r V n
shar-	row
S {	r @U
shar-	ry
S Q@	i:
shard
S Q@ d
shards
S Q@ d z
share
S e@
share-	crop-	per
S e@ k	r Q	p @r
share-	crop-	pers
S e@ k	r Q	p @r z
share-	hol-	der
S e@	h @U l	d @r
share-	hol-	ders
S e@	h @U l	d @r z
share-	hol-	der's
S e@	h @U l	d @r z
share-	hol-	ding
S e@	h @U l	d I N
share-	hol-	dings
S e@	h @U l	d I N z
share-	ow-	ner
S e@	@U	n @r
share-	ware
S e@	w e@
shared
S e@ d
shares
S e@ z
share's
S e@ z
shark
S Q@ k
shark-	like
S Q@ k	l aI k
sharks
S Q@ k s
sharp
S Q@ p
sharp-	ly
S Q@ p	l i:
sharp-	ness
S Q@ p	n V s
sharp-	shoo-	ter
S Q@ p	S u:	t @r
sharp-	shoo-	ters
S Q@ p	S u:	t @r z
sharpe
S Q@ p
sharps
S Q@ p s
sharp's
S Q@ p s
shas-	ta
S { s	t V
shas-	ta's
S { s	t V z
shash-	lik
S { S	l I k
shat-	ner
S { t	n @r
shat-	te-	ring
S {	t @r	I N
shat-	ter
S {	t @r
shat-	ter-	proof
S {	t @r p	r u: f
shat-	tered
S {	t @r d
shat-	ters
S {	t @r z
shat-	tuck
S {	t V k
shat-	zer
S eI t	z @r
shau-	na
S O:	n V
shaugh-	nes-	sy
S O:	n V	s i:
shaul
S O: l
shaun
S O: n
shave
S eI v
shaved
S eI v d
shaves
S eI v z
shaw
S O:
shaw-	ley
S O:	l i:
shaw-	mut
S O:	m V t
shaw-	mut's
S O:	m V t s
shaw-	na
S O:	n V
shaw-	nee
S O:	n i:
shawl
S O: l
shawls
S O: l z
shawn
S O: n
shawn's
S O: n z
shaw's
S O: z
shay
S eI
shayne
S eI n
shays
S eI z
shcha-	ran-	sky
S @r	{ n	s k i:
shched-	rin
S e d	r I n
she
S i:
she-	ba
S i:	b V
she-	boy-	gan
S V	b OI	g V n
she-	kel
S e	k V l
she-	kels
S e	k V l z
she-	ley
S i:	l i:
she-	line
S e	l aI n
she-	na
S i:	n V
she-	na-	ni-	gan
S V	n {	n I	g V n
she-	na-	ni-	gans
S V	n {	n I	g V n z
she-	nan-	do-	ah
S e	n V n	d @U	V
she-	pard
S e	p @r d
she-	pard's
S e	p @r d z
she-	pher-	ded
S e	p @r	d V d
she-	pher-	ding
S e	p @r	d I N
she-	pherd
S e	p @r d
she-	pherds
S e	p @r d z
she-	pherd's
S e	p @r d z
she-	pley
S e p	l i:
she-	ra-	ton
S e@	V	t V n
she-	ra-	ton's
S e@	V	t V n z
she-	rard
S e@	@r d
she-	ree
S @r	i:
she-	rer
S I@	@r
she-	ri
S e@	i:
she-	ri-	dan
S e@	I	d V n
she-	riff
S e@	I f
she-	riffs
S e@	I f s
she-	riff's
S e@	I f s
she-	rod
S e@	V d
she-	ryl
S e@	V l
she-	vard-	nad-	ze
S e	v @r d	n Q d	z i:
she-	vard-	nad-	ze's
S e	v @r d	n Q d	z i: z
shea
S eI
shea-	rer
S I@	@r
shea-	ring
S I@	I N
shea-	thing
S i:	D I N
sheaf
S i: f
shear
S I@
shear-	man
S i: r	m V n
sheard
S I@ d
sheared
S I@ d
shearn
S I@ n
shears
S i: r z
shear's
S i: r z
shea's
S eI z
sheath
S i: T
sheath-	bill
S i: T	b I l
sheath-	bills
S i: T	b I l z
sheathe
S i: D
sheathed
S i: D d
sheaves
S i: v z
shed
S e d
she'd
S i: d
shed-	ding
S e	d I N
shedd
S e d
sheds
S e d z
shee-	dy
S i:	d i:
shee-	han
S i:	V n
shee-	han's
S i:	V n z
shee-	la
S i:	l V
shee-	lah
S i:	l V
shee-	ler
S i:	l @r
shee-	ly
S i:	l i:
shee-	na
S i:	n V
shee-	pish
S i:	p I S
shee-	pish-	ly
S i:	p I S	l i:
shee-	ran
S I@	V n
shee-	rer
S i:	r @r
shee-	ting
S i:	t I N
sheen
S i: n
sheep
S i: p
sheep-	skin
S i: p	s k I n
sheep's
S i: p s
sheer
S I@
sheesh
S i: S
sheet
S i: t
sheets
S i: t s
shef-	field
S e	f i: l d
sheff
S e f
shei-	la
S i:	l V
shei-	lah
S i:	l V
shei-	la's
S i:	l V z
sheik
S i: k
sheik-	dom
S i: k	d V m
sheik-	doms
S i: k	d V m z
sheikh
S i: k
sheiks
S i: k s
sheik's
S i: k s
shel-	burne
S e l	b @r n
shel-	by
S e l	b i:
shel-	by-	ville
S e l	b i:	v I l
shel-	by's
S e l	b i: z
shel-	dahl
S e l	d Q l
shel-	den
S e l	d V n
shel-	don
S e l	d V n
shel-	ler
S e	l @r
shel-	ley
S e	l i:
shel-	ley's
S e	l i: z
shel-	ling
S e	l I N
shel-	lings
S e	l I N z
shel-	ly
S e	l i:
shel-	man
S e l	m V n
shel-	te-	ring
S e l	t @r	I N
shel-	ter
S e l	t @r
shel-	tered
S e l	t @r d
shel-	ters
S e l	t @r z
shel-	ton
S e l	t V n
shel-	ton's
S e l	t V n z
shel-	ving
S e l	v I N
shelf
S e l f
shell
S e l
she'll
S i: l
shell-	fish
S e l	f I S
shell-	man
S e l	m V n
shell-	shock
S e l	S Q k
shell-	shocked
S e l	S Q k t
shelled
S e l d
shells
S e l z
shell's
S e l z
shelve
S e l v
shelved
S e l v d
shelves
S e l v z
shen
S e n
shen-	yang
S e n	j { N
sheng
S e N
shep
S e p
shep-	pard
S e	p @r d
shep-	perd
S e	p @r d
shepp
S e p
sher
S @r
sher-	bert
S @r	b @r t
sher-	bet
S @r	b V t
sher-	borne
S @r	b @r n
sher-	burn
S @r	b @r n
sher-	burne
S @r	b @r n
sher-	field
S @r	f i: l d
sher-	ley
S @r	l i:
sher-	lock
S @r	l Q k
sher-	lock's
S @r	l Q k s
sher-	man
S @r	m V n
sher-	man's
S @r	m V n z
sher-	rard
S e@	@r d
sher-	rer
S e@	@r
sher-	ri
S e@	i:
sher-	rie
S e@	i:
sher-	rill
S e@	I l
sher-	ri's
S e@	i: z
sher-	rod
S e@	V d
sher-	ry
S e@	i:
sher-	ry's
S e@	i: z
sher-	win
S @r	w I n
sher-	wood
S @r	w U d
sher-	wood's
S @r	w U d z
shere
S I@
sherr
S e@
sherr's
S e@ z
she's
S i: z
shet-	land
S e t	l V n d
sheth
S e T
shev-	lin
S e v	l I n
shew
S u:
shew-	chuk
S u:	tS V k
shew-	ma-	ker
S u:	m eI	k @r
shi
S i:
shi-	a
S i:	V
shi-	as
S i:	V z
shi-	d-	ler
S aI	d V	l @r
shi-	er
S aI	@r
shi-	ite
S i:	aI t
shi-	ites
S i:	aI t s
shi-	loh
S aI	l @U
shi-	ner
S aI	n @r
shi-	ning
S aI	n I N
shi-	ny
S aI	n i:
shi-	ra
S I@	V
shi-	rah
S I@	V
shi-	re-	man
S I@	eI	m V n
shi-	ro-	ma
S I@	@U	m V
shi-	va
S i:	v V
shi-	ve-	ring
S I	v @r	I N
shi-	ver
S I	v @r
shi-	vered
S I	v @r d
shi-	vers
S I	v @r z
shi-	zuo-	ka
S i: z	w @U	k V
shib-	bo-	leth
S I	b V	l e T
shick
S I k
shied
S aI d
shieh
S i:
shiel
S i: l
shiel-	ded
S i: l	d V d
shiel-	ding
S i: l	d I N
shield
S i: l d
shields
S i: l d z
shield's
S i: l d z
shiels
S i: l z
shies
S aI z
shif-	lett
S I f	l e t
shif-	ted
S I f	t V d
shif-	ter
S I f	t @r
shif-	ting
S I f	t I N
shif-	ty
S I f	t i:
shiff
S I f
shift
S I f t
shift-	less
S I f	t l V s
shifts
S I f t s
shih
S i:
shil-	ler
S I	l @r
shil-	ling
S I	l I N
shil-	ling-	ton
S I	l I N	t V n
shil-	lings
S I	l I N z
shill
S I l
shim
S I m
shim-	kus
S I m	k V s
shim-	me-	ring
S I	m @r	I N
shim-	mer
S I	m @r
shim-	mered
S I	m @r d
shim-	mers
S I	m @r z
shim-	my
S I	m i:
shin
S I n
shin-	bone
S I n	b @U n
shin-	dig
S I n	d I g
shin-	dle
S I n	d V l
shin-	gle
S I N	g V l
shin-	gle-	ton
S I N	g V l	t V n
shin-	gles
S I N	g V l z
shin-	to
S I n	t @U
shine
S aI n
shined
S aI n d
shines
S aI n z
shing
S I N
shing-	ler
S I N	l @r
ship
S I p
ship-	board
S I p	b O@ d
ship-	buil-	der
S I p	b I l	d @r
ship-	buil-	ders
S I p	b I l	d @r z
ship-	buil-	ding
S I p	b I l	d I N
ship-	buil-	dings
S I p	b I l	d I N z
ship-	ley
S I p	l i:
ship-	load
S I p	l @U d
ship-	loads
S I p	l @U d z
ship-	man
S I p	m V n
ship-	mate
S I p	m eI t
ship-	mates
S I p	m eI t s
ship-	ment
S I p	m V n t
ship-	ments
S I p	m V n t s
ship-	ow-	ner
S I	p @U	n @r
ship-	ow-	ners
S I	p @U	n @r z
ship-	pee
S I	p i:
ship-	per
S I	p @r
ship-	pers
S I	p @r z
ship-	per's
S I	p @r z
ship-	ping
S I	p I N
ship-	py
S I	p i:
ship-	shape
S I p	S eI p
ship-	wreck
S I p	r e k
ship-	wright
S I p	r aI t
ship-	wrights
S I p	r aI t s
ship-	yard
S I p	j Q@ d
ship-	yards
S I p	j Q@ d z
ship-	yard's
S I p	j Q@ d z
shipp
S I p
shipped
S I p t
shipp's
S I p s
ships
S I p s
ship's
S I p s
shir
S @r
shir-	king
S @r	k I N
shir-	lee
S @r	l i:
shir-	leen
S @r	l i: n
shir-	lene
S @r	l i: n
shir-	ley
S @r	l i:
shir-	ley's
S @r	l i: z
shir-	lie
S @r	l i:
shire
S aI r
shires
S aI r z
shirk
S @r k
shirked
S @r k t
shirl
S @r l
shirr
S @r
shirt
S @r t
shirt-	sleeve
S @r t	s l i: v
shirts
S @r t s
shit
S i: t
shive
S aI v
shive-	ly
S aI v	l i:
shives
S aI v z
sho-	gun
S @U	g V n
sho-	ji
S @U	dZ i:
sho-	lem
S @U	l V m
sho-	r
S i:	@r
sho-	ring
S O@	I N
sho-	sho-	ne
S @U	S @U	n i:
sho-	val
S @U	v { l
sho-	vel
S V	v V l
sho-	veled
S V	v V l d
sho-	vels
S V	v V l z
sho-	ver
S V	v @r
sho-	ving
S V	v I N
sho-	wa
S @U	V
sho-	we-	ring
S aU	@r	I N
sho-	well
S Q	w e l
sho-	wer
S aU	@r
sho-	wered
S aU	@r d
sho-	wers
S aU	@r z
sho-	wi-	est
S @U	i:	V s t
sho-	wing
S @U	I N
sho-	wings
S @U	I N z
sho-	wy
S @U	i:
shoals
S @U l z
shoc-	ker
S Q	k @r
shoc-	king
S Q	k I N
shoc-	king-	ly
S Q	k I N	l i:
shock
S Q k
shock-	ley
S Q k	l i:
shock-	wave
S Q k	w eI v
shocked
S Q k t
shocks
S Q k s
shod
S Q d
shod-	dy
S Q	d i:
shoe
S u:
shoe-	box
S @U	b Q k s
shoe-	horn
S u:	h O@ n
shoe-	horned
S u:	h O@ n d
shoe-	la-	ces
S u:	l eI	s V z
shoe-	lace
S u:	l eI s
shoe-	ma-	ker
S u:	m eI	k @r
shoe-	ma-	kers
S u:	m eI	k @r z
shoe-	make
S u:	m eI k
shoe-	shine
S u:	S aI n
shoe-	string
S u: s	t r I N
shoes
S u: z
shoe's
S u: z
sholes
S @U l z
shone
S Q n
shoo
S u:
shoo-	fly
S u: f	l aI
shoo-	ter
S u:	t @r
shoo-	ters
S u:	t @r z
shoo-	ting
S u:	t I N
shoo-	tings
S u:	t I N z
shooed
S u: d
shook
S U k
shoop
S u: p
shoot
S u: t
shoot-	down
S u: t	d aU n
shoot-	out
S u:	t aU t
shoot-	outs
S u:	t aU t s
shoots
S u: t s
shop
S Q p
shop-	kee-	per
S Q p	k i:	p @r
shop-	kee-	pers
S Q p	k i:	p @r z
shop-	lif-	ter
S Q p	l I f	t @r
shop-	lif-	ters
S Q p	l I f	t @r z
shop-	lif-	ting
S Q p	l I f	t I N
shop-	lift
S Q p	l I f t
shop-	per
S Q	p @r
shop-	pers
S Q	p @r z
shop-	per's
S Q	p @r z
shop-	ping
S Q	p I N
shop-	ping's
S Q	p I N z
shop-	worn
S Q p	w O@ n
shope
S @U p
shoppe
S Q p
shopped
S Q p t
shoppes
S Q p s
shops
S Q p s
shop's
S Q p s
shor-	ta-	ges
S O@	t V	dZ V z
shor-	tage
S O@	t V dZ
shor-	te-	ning
S O@	t V	n I N
shor-	ted
S O@	t V d
shor-	ten
S O@	t V n
shor-	tened
S O@	t V n d
shor-	tens
S O@	t V n z
shor-	ter
S O@	t @r
shor-	ter's
S O@	t @r z
shor-	test
S O@	t V s t
shor-	ting
S O@	t I N
shor-	ty
S O@	t i:
shore
S O@
shore-	bird
S O@	b @r d
shore-	ham
S O@	V m
shore-	line
S O@	l aI n
shore-	ward
S O@	w @r d
shored
S O@ d
shores
S O@ z
shore's
S O@ z
shorn
S O@ n
short
S O@ t
short-	cake
S O@ t	k eI k
short-	chan-	ging
S O@ t	tS eI n	dZ I N
short-	change
S O@ t	tS eI n dZ
short-	changed
S O@ t	tS eI n dZ d
short-	co-	ming
S O@ t	k V	m I N
short-	co-	mings
S O@ t	k V	m I N z
short-	cut
S O@ t	k V t
short-	cuts
S O@ t	k V t s
short-	fall
S O@ t	f O: l
short-	falls
S O@ t	f O: l z
short-	grass
S O@ t	g r { s
short-	hair
S O@ t	h e@
short-	haired
S O@ t	h e@ d
short-	hand
S O@ t	h { n d
short-	lived
S O@ t	l I v d
short-	ly
S O@ t	l i:
short-	ness
S O@ t	n V s
short-	sigh-	ted
S O@ t	s aI	t V d
short-	sigh-	ted-	ness
S O@ t	s aI	t V d	n V s
short-	stop
S O@ t	s t Q p
short-	term
S O@ t	t @r m
short-	wave
S O@ t	w eI v
short-	win-	ded
S O@ t	w I n	d V d
shorts
S O@ t s
shos-	ta-	ko-	vich
S O: s	t V	k @U	v I tS
shot
S Q t
shot-	gun
S Q t	g V n
shot-	guns
S Q t	g V n z
shot-	well
S Q t	w e l
shots
S Q t s
shott
S Q t
shotts
S Q t s
shou-	ted
S aU	t V d
shou-	ting
S aU	t I N
shough
S aU
shoul-	de-	ring
S @U l	d @r	I N
shoul-	der
S @U l	d @r
shoul-	dered
S @U l	d @r d
shoul-	ders
S @U l	d @r z
shoul-	dn't
S U	d V n t
should
S U d
shoup
S u: p
shouse
s h aU s
shout
S aU t
shouts
S aU t s
shove
S V v
shove-	ling
S V v	l I N
shoved
S V v d
shoves
S V v z
show
S @U
show-	biz
S @U	b I z
show-	boat
S @U	b @U t
show-	boat's
S @U	b @U t s
show-	ca-	ses
S @U	k eI	s V z
show-	ca-	sing
S @U	k eI	s I N
show-	case
S @U	k eI s
show-	cased
S @U	k eI s t
show-	down
S @U	d aU n
show-	downs
S @U	d aU n z
show-	girl
S @U	g @r l
show-	girls
S @U	g @r l z
show-	man
S @U	m V n
show-	man-	ship
S @U	m V n	S I p
show-	piece
S @U	p i: s
show-	place
S @U p	l eI s
show-	room
S @U	r U m
show-	rooms
S @U	r u: m z
show-	time
S @U	t aI m
showed
S @U d
shown
S @U n
shows
S @U z
shrank
S r { N k
shrap-	nel
S r { p	n V l
shred
S r e d
shred-	ded
S r e	d V d
shred-	der
S r e	d @r
shred-	ders
S r e	d @r z
shred-	ding
S r e	d I N
shreds
S r e d z
shreeve
S r i: v
shreve
S r i: v
shreve-	port
S r i: v	p O@ t
shrew-	dest
S r u:	d V s t
shrewd
S r u: d
shrewd-	ly
S r u: d	l i:
shrewd-	ness
S r u: d	n V s
shrews-	bu-	ry
S r u: z	b e@	i:
shri
S r i:
shri-	ner
S r aI	n @r
shri-	ners
S r aI	n @r z
shri-	ve-	ling
S r I	v V	l I N
shri-	vel
S r I	v V l
shri-	veled
S r I	v V l d
shri-	ver
S r aI	v @r
shrie-	king
S r i:	k I N
shriek
S r i: k
shrieked
S r i: k t
shrieks
S r i: k s
shrift
S r I f t
shrill
S r I l
shrim-	per
S r I m	p @r
shrim-	pers
S r I m	p @r z
shrimp
S r I m p
shrin-	kage
S r I N	k I dZ
shrin-	king
S r I N	k I N
shrine
S r aI n
shrines
S r aI n z
shrink
S r I N k
shrinks
S r I N k s
shroff
S r O: f
shrop-	shire
S r Q p	S aI r
shrou-	ded
S r aU	d V d
shrou-	ding
S r aU	d I N
shroud
S r aU d
shrouds
S r aU d z
shrub
S r V b
shrub-	be-	ry
S r V	b @r	i:
shrub-	by
S r V	b i:
shrub-	like
S r V b	l aI k
shrubs
S r V b z
shrug
S r V g
shrug-	ging
S r V	g I N
shrugged
S r V g d
shrugs
S r V g z
shrun-	ken
S r V N	k V n
shrunk
S r V N k
shtick
S t I k
shu
S u:
shu-	bert
S u:	b @r t
shu-	gart
S V	g Q@ t
shu-	la
S u:	l V
shu-	ler
S u:	l @r
shu-	man
S u:	m V n
shu-	mard
S u:	m @r d
shu-	ping
S u:	p I N
shuc-	king
S V	k I N
shuck
S V k
shucked
S V k t
shucks
S V k s
shud-	de-	ring
S V	d @r	I N
shud-	der
S V	d @r
shud-	dered
S V	d @r d
shud-	ders
S V	d @r z
shue
S u:
shuf-	f-	ler
S V	f V	l @r
shuf-	f-	lers
S V	f V	l @r z
shuf-	fle
S V	f V l
shuf-	fled
S V	f V l d
shuf-	fles
S V	f V l z
shuff
S V f
shuff-	ling
S V f	l I N
shul-	man
S U l	m V n
shull
S V l
shult-	z's
S U l	t s I z
shultz
S U l t s
shum
S V m
shum-	way
S V m	w eI
shun
S V n
shun-	ning
S V	n I N
shun-	ted
S V n	t V d
shun-	ting
S V n	t I N
shunk
S V N k
shunned
S V n d
shuns
S V n z
shunt
S V n t
shure
S U@
shut
S V t
shut-	down
S V t	d aU n
shut-	downs
S V t	d aU n z
shut-	out
S V	t aU t
shut-	t-	ling
S V	t V	l I N
shut-	te-	ring
S V	t @r	I N
shut-	ter
S V	t @r
shut-	tered
S V	t @r d
shut-	ters
S V	t @r z
shut-	ting
S V	t I N
shut-	tle
S V	t V l
shut-	tled
S V	t V l d
shut-	tles
S V	t V l z
shut-	tle's
S V	t V l z
shute
S u: t
shutes
S u: t s
shuts
S V t s
shy
S aI
shy-	ing
S aI	I N
shy-	lock
S aI	l Q k
shy-	ly
S aI	l i:
shy-	ness
S aI	n V s
shy-	ster
S aI s	t @r
shy-	sters
S aI s	t @r z
si
s i:
si-	a-	mese
s aI	V	m i: z
si-	am
s aI	{ m
si-	be-	ri-	a
s aI	b I@	i:	V
si-	be-	ri-	an
s aI	b I@	i:	V n
si-	belle
s I	b e l
si-	bil-	la
s I	b I	l V
si-	ble
s aI	b V l
si-	byl
s I	b V l
si-	ca
s i:	k V
si-	card
s I	k @r d
si-	chuan
s I tS	w Q n
si-	ci-	li-	a-	no
s i:	tS i:	l i:	Q	n @U
si-	ci-	li-	an
s I	s I	l i:	V n
si-	ci-	lia
s I	s I l	j V
si-	ci-	ly
s I	s I	l i:
si-	d-	ler
s aI	d V	l @r
si-	de-	ro-	gra-	pher
s aI	d @r	O: g	r V	f @r
si-	dearm
s aI	d Q@ m
si-	dearms
s aI	d Q@ m z
si-	ded
s aI	d V d
si-	dell
s aI	d V l
si-	der
s aI	d @r
si-	ders
s aI	d @r z
si-	dhu
s I d	h u:
si-	ding
s aI	d I N
si-	dle
s aI	d V l
si-	do-	ni-	a
s i:	d @U	n i:	V
si-	don
s aI	d V n
si-	en-	na
s i:	e	n V
si-	en-	na's
s i:	e	n V z
si-	er-	ra
s i:	e@	V
si-	er-	ras
s i:	e@	V z
si-	er-	ra's
s i:	e@	V z
si-	g-	ler
s aI	g V	l @r
si-	gel
s I	g V l
si-	ghing
s aI	I N
si-	gour-	ney
s I	g O@	n i:
si-	grid
s I g	r I d
si-	gurd
s I	g @r d
si-	ha-	nouk
s i:	V	n U k
si-	kor-	ski
s I	k O@ s	k i:
si-	kor-	sky
s I	k O@ s	k i:
si-	las
s aI	l V s
si-	le-	sia
s V	l i:	z V
si-	len-	ces
s aI	l V n	s V z
si-	len-	cing
s aI	l V n	s I N
si-	lence
s aI	l V n s
si-	lenced
s aI	l V n s t
si-	lent
s aI	l V n t
si-	lent-	ly
s aI	l V n	t l i:
si-	ler
s aI	l @r
si-	lex
s I	l V k s
si-	li-	ca
s I	l I	k V
si-	li-	cate
s I	l I	k V t
si-	li-	cates
s I	l I	k V t s
si-	li-	con
s I	l I	k V n
si-	li-	cone
s I	l I	k @U n
si-	li-	cones
s I	l I	k @U n z
si-	lo
s aI	l @U
si-	los
s aI	l @U z
si-	ma
s i:	m V
si-	mas
s aI	m V z
si-	me-	on
s I	m i:	V n
si-	mi
s i:	m i:
si-	mi-	an
s I	m i:	V n
si-	mi-	la-	ri-	ties
s I	m I	l e@	I	t i: z
si-	mi-	la-	ri-	ty
s I	m I	l e@	I	t i:
si-	mi-	lar
s I	m I	l @r
si-	mi-	lar-	ly
s I	m I	l @r	l i:
si-	mo-	na
s I	m @U	n V
si-	mo-	net-	ta
s i:	m V	n e	t V
si-	mo-	nette
s I	m V	n e t
si-	mo-	ni-	an
s I	m @U	n i:	V n
si-	mo-	ny
s aI	m V	n i:
si-	mon
s aI	m V n
si-	mon-	sen
s I	m V n	s V n
si-	mon-	son
s I	m V n	s V n
si-	mon-	ton
s aI	m V n	t V n
si-	mone
s I	m @U n
si-	mons
s aI	m V n z
si-	mon's
s aI	m V n z
si-	mu-	la-	ted
s I m	j V	l eI	t V d
si-	mu-	la-	ting
s I m	j V	l eI	t I N
si-	mu-	la-	tion
s I m	j V	l eI	S V n
si-	mu-	la-	tions
s I m	j V	l eI	S V n z
si-	mu-	la-	tor
s I m	j V	l eI	t @r
)"
R"(si-	mu-	la-	tors
s I m	j V	l eI	t @r z
si-	mu-	late
s I m	j V	l eI t
si-	mu-	lates
s I m	j V	l eI t s
si-	mul-	cast
s aI m	j V l	k { s t
si-	mul-	ta-	ne-	ous
s aI	m V l	t eI	n i:	V s
si-	mul-	ta-	ne-	ous-	ly
s aI	m V l	t eI	n i:	V s	l i:
si-	na-	tra
s V	n Q t	r V
si-	na-	tra's
s V	n Q t	r V z
si-	nai
s aI	n aI
si-	ne-	ad
s I	n eI	{ d
si-	ne-	wy
s I n	j u:	i:
si-	nis-	ter
s I	n I s	t @r
si-	no
s aI	n @U
si-	no-	po-	li
s i:	n @U	p @U	l i:
si-	nu-	ses
s aI	n V	s V z
si-	nus
s aI	n V s
si-	pho-	ning
s aI	f V	n I N
si-	phon
s aI	f V n
si-	phoned
s aI	f V n d
si-	phons
s aI	f V n z
si-	ple
s aI	p V l
si-	ra-	cu-	sa
s I@	Q	k u:	s V
si-	re
s aI	@r
si-	re-	na
s I@	e	n V
si-	ren
s aI	r V n
si-	rens
s aI	r V n z
si-	ri
s I@	i:
si-	ris
s aI	r I s
si-	rois
s aI r	w Q
si-	son
s I	s V n
si-	tar
s I	t @r
si-	ted
s aI	t V d
si-	ting
s aI	t I N
si-	tu-	a-	ted
s I	tS u:	eI	t V d
si-	tu-	a-	tio-	nal
s I	tS u:	eI	S V	n V l
si-	tu-	a-	tion
s I	tS u:	eI	S V n
si-	tu-	a-	tions
s I	tS u:	eI	S V n z
si-	tu-	a-	tion's
s I	tS u:	eI	S V n z
si-	tu-	ate
s I	tS u:	eI t
si-	tus
s aI	t V s
si-	u
s i:	u:
si-	ver
s aI	v @r
si-	xes
s I k	s V z
si-	x's
s I k	s V z
si-	za-	ble
s aI	z V	b V l
si-	zea-	ble
s aI	z V	b V l
si-	zer
s aI	z @r
si-	zes
s aI	z V z
si-	zing
s aI	z I N
siang
s j { N
sias
Z O: z
sib
s I b
sib-	bie
s I	b i:
sib-	by
s I	b i:
sib-	ley
s I b	l i:
sib-	ling
s I b	l I N
sib-	lings
s I b	l I N z
sic
s I k
sic-	ke-	ning
s I	k V	n I N
sic-	ken
s I	k V n
sic-	kened
s I	k V n d
sic-	ker
s I	k @r
sic-	kest
s I	k V s t
sic-	kle
s I	k V l
sic-	kles
s I	k V l z
sick
s I k
sick-	ler
s I k	l @r
sick-	ly
s I k	l i:
sick-	ness
s I k	n V s
sid
s I d
sid-	dhar-	tha
s V	d Q@	t V
sid-	dons
s I	d V n z
sid-	man
s I d	m V n
sid-	ney
s I d	n i:
sid-	ra
s I d	r V
sid-	well
s I d	w e l
side
s aI d
side-	bar
s aI d	b Q@
side-	bars
s aI d	b Q@ z
side-	kick
s aI d	k I k
side-	line
s aI d	l aI n
side-	lined
s aI d	l aI n d
side-	lines
s aI d	l aI n z
side-	man
s aI d	m { n
side-	show
s aI d	S @U
side-	shows
s aI d	S @U z
side-	step
s aI d	s t e p
side-	step-	ping
s aI d	s t e	p I N
side-	stepped
s aI d	s t e p t
side-	steps
s aI d	s t e p s
side-	stream
s aI d	s t r i: m
side-	track
s aI d	t r { k
side-	tracked
s aI d	t r { k t
side-	walk
s aI d	w O: k
side-	walks
s aI d	w O: k s
side-	ways
s aI d	w eI z
side-	win-	der
s aI d	w aI n	d @r
side-	wise
s aI d	w aI z
sides
s aI d z
side's
s aI d z
sids
s I d z
sid's
s I d z
sie
s i:
sie-	ben
s i:	b V n
sie-	ber
s i:	b @r
sie-	cle
s i:	k V l
sie-	gel
s i:	g V l
sie-	gel's
s i:	g V l z
sie-	ger
s i:	g @r
sie-	ges
s i:	dZ V z
sie-	mens
s i:	m V n z
sie-	mens's
s i:	m V n z
sie-	rac-	ki
s I@	Q t	s k i:
sie-	ver
s i:	v @r
sie-	vers
s i:	v @r z
sie-	vert
s i:	v @r t
sie-	ving
s I	v I N
sieg
s i: g
sieg-	fried
s i: g	f r i: d
sieg-	ler
s i: g	l @r
sieg-	mund
s i: g	m V n d
siege
s i: dZ
siege-	craft
s i: dZ	k r { f t
sieve
s I v
sieves
s I v z
sif-	ford
s I	f @r d
sif-	ted
s I f	t V d
sif-	ting
s I f	t I N
sift
s I f t
sifts
s I f t s
sig
s I g
sig-	ma
s I g	m V
sig-	mund
s I g	m V n d
sig-	na
s I g	n V
sig-	na-	ling
s I g	n V	l I N
sig-	na-	to-	ries
s I g	n V	t O@	i: z
sig-	na-	to-	ry
s I g	n V	t O@	i:
sig-	na-	ture
s I g	n V	tS @r
sig-	na-	tures
s I g	n V	tS @r z
sig-	nage
s aI	n I dZ
sig-	nal
s I g	n V l
sig-	nal-	ling
s I g	n V	l I N
sig-	naled
s I g	n V l d
sig-	nalled
s I g	n V l d
sig-	nals
s I g	n V l z
sig-	nal's
s I g	n V l z
sig-	ner
s aI	n @r
sig-	ners
s aI	n @r z
sig-	net
s I g	n e t
sig-	ni-	fi-	cance
s I g	n I	f I	k V n s
sig-	ni-	fi-	cant
s I g	n I	f I	k V n t
sig-	ni-	fi-	cant-	ly
s I g	n I	f I	k V n	t l i:
sig-	ni-	fied
s I g	n I	f aI d
sig-	ni-	fies
s I g	n I	f aI z
sig-	ni-	fy
s I g	n I	f aI
sig-	ni-	fy-	ing
s I g	n I	f aI	I N
sig-	ning
s aI	n I N
sig-	nings
s aI	n I N z
sig-	no-	re
s i: n	j O@	eI
sig-	no-	rel-	li
s i: g	n O@	e	l i:
sig-	no-	ri
s I g	n O@	i:
sig-	nor
s i: n	j O@
sigh
s aI
sigh-	ted
s aI	t V d
sigh-	ting
s aI	t I N
sigh-	tings
s aI	t I N z
sighed
s aI d
sighs
s aI z
sight
s aI t
sight-	se-	ers
s aI t	s i:	@r z
sight-	see
s aI t	s i:
sight-	see-	ing
s aI t	s i:	I N
sight-	seer
s aI t	s i: r
sights
s aI t s
sign
s aI n
sign-	post
s aI n	p @U s t
sign-	posts
s aI n	p @U s t s
signed
s aI n d
signs
s aI n z
sign's
s aI n z
sikes
s aI k s
sikh
s i: k
sikhs
s i: k s
sil
s I l
sil-	ber
s I l	b @r
sil-	ber-	man
s I l	b @r	m V n
sil-	ho-	uet-	ted
s I	l V	w e	t I d
sil-	ho-	uette
s I	l V	w e t
sil-	ho-	uettes
s I	l V	w e t s
sil-	ky
s I l	k i:
sil-	ler
s I	l @r
sil-	li-	er
s I	l i:	@r
sil-	li-	est
s I	l i:	V s t
sil-	li-	ness
s I	l i:	n V s
sil-	ly
s I	l i:
sil-	va
s I l	v V
sil-	va-	na
s I l	v Q	n V
sil-	vas
s I l	v V z
sil-	va's
s I l	v V z
sil-	ve-	ra-	do
s I l	v @r	Q	d @U
sil-	ve-	ry
s I l	v @r	i:
sil-	ver
s I l	v @r
sil-	ver-	man
s I l	v @r	m { n
sil-	ver-	plate
s I l	v @r p	l eI t
sil-	ver-	side
s I l	v @r	s aI d
sil-	ver-	sides
s I l	v @r	s aI d z
sil-	ver-	stein
s I l	v @r s	t i: n
sil-	ver-	ware
s I l	v @r	w e@
sil-	vers
s I l	v @r z
sil-	ver's
s I l	v @r z
sil-	ves-	ter
s I l	v e s	t @r
sil-	ves-	tro
s i: l	v eI s	t r @U
sil-	vi-	a
s I l	v i:	V
sil-	vi-	o
s I l	v i:	@U
sil-	vi-	us
s I l	v i:	V s
sil-	vie
s I l	v i:
sil-	vis
s I l	v I s
silk
s I l k
silk-	wood
s I l	k w U d
silk-	worm
s I l	k w @r m
silk-	worms
s I l	k w @r m z
silks
s I l k s
sill
s I l
sills
s I l z
sils-	by
s I l	s b i:
silt
s I l t
sim
s I m
sim-	ba
s I m	b V
sim-	ba's
s I m	b V z
sim-	kin
s I m	k I n
sim-	kins
s I m	k I n z
sim-	me-	ring
s I	m @r	I N
sim-	mer
s I	m @r
sim-	mered
s I	m @r d
sim-	mers
s I	m @r z
sim-	mon
s I	m V n
sim-	mon-	s's
s I	m V n	z V z
sim-	monds
s I	m V n d z
sim-	mons
s I	m V n z
sim-	p-	ler
s I m	p V	l @r
sim-	per
s I m	p @r
sim-	ple
s I m	p V l
sim-	son
s I m	s V n
sime
s aI m
simm
s I m
simms
s I m z
simp-	kins
s I m	p k I n z
simp-	lesse
s I m	p l e s
simp-	lest
s I m	p l V s t
simp-	lex
s I m	p l e k s
simp-	li-	ci-	ty
s I m	p l I	s I	t i:
simp-	li-	fi-	ca-	tion
s I m	p l I	f I	k eI	S V n
simp-	li-	fied
s I m	p l I	f aI d
simp-	li-	fies
s I m	p l I	f aI z
simp-	li-	fy
s I m	p l I	f aI
simp-	li-	fy-	ing
s I m	p l I	f aI	I N
simp-	lis-	tic
s I m	p l I s	t I k
simp-	ly
s I m	p l i:
simp-	son
s I m	p s V n
simp-	son's
s I m	p s V n z
sims
s I m z
sims-	bu-	ry
s I m	z b e@	i:
sin
s I n
sin-	bad
s I n	b { d
sin-	ce-	ri-	ty
s I n	s e@	I	t i:
sin-	cere
s I n	s I@
sin-	cere-	ly
s I n	s I@	l i:
sin-	fo-	ni-	a
s I n	f @U	n i:	V
sin-	ful
s I n	f V l
sin-	g-	ler
s I N	g V	l @r
sin-	g-	ling
s I N	g V	l I N
sin-	ga-	po-	re-	an
s I N	g V	p O@	i:	V n
sin-	ga-	po-	re-	ans
s I N	g V	p O@	i:	V n z
sin-	ga-	pore
s I	N V	p O@
sin-	ga-	pore's
s I	N V	p O@ z
sin-	ger
s I	N @r
sin-	gers
s I	N @r z
sin-	ger's
s I	N @r z
sin-	ging
s I	N I N
sin-	gle
s I N	g V l
sin-	gle-	han-	ded
s I N	g V l	h { n	d V d
sin-	gle-	han-	ded-	ly
s I N	g V l	h { n	d V d	l i:
sin-	gle-	ta-	ry
s I N	g V l	t e@	i:
sin-	gle-	ton
s I N	g V l	t V n
sin-	gle-	ton's
s I N	g V l	t V n z
sin-	gled
s I N	g V l d
sin-	gles
s I N	g V l z
sin-	gu-	la-	ri-	za-	tion
s I N	g j V	l @r	V	z eI	S V n
sin-	gu-	lar
s I N	g j V	l @r
sin-	gu-	lar-	ly
s I N	g j V	l @r	l i:
sin-	ha-	lese
s I	n V	l i: z
sin-	ker
s I N	k @r
sin-	king
s I N	k I N
sin-	ner
s I	n @r
sin-	ners
s I	n @r z
sin-	ning
s I	n I N
sin-	ton
s I n	t V n
sinc-	lair
s I n	k l e@
since
s I n s
sind
s I n d
sine
s aI n
sines
s aI n z
sing
s I N
sing-	ly
s I N	g l i:
singe
s I n dZ
singed
s I n dZ d
singh
s I N
singh's
s I N z
sings
s I N z
sink
s I N k
sink-	field
s I N	k f i: l d
sink-	hole
s I N	k h @U l
sinks
s I N k s
sinn
s I n
sinned
s I n d
sins
s I n z
sinu-	ous
s I n	w V s
sio-	bhan
S aU	b Q n
sioux
s u:
sip
s I p
sip-	ping
s I	p I N
sip-	ple
s I	p V l
sipe
s aI p
sipes
s aI p s
sipp
s I p
sipped
s I p t
sips
s I p s
sir
s @r
sir-	kin
s @r	k I n
sir-	mons
s @r	m V n z
sires
s aI r z
sis
s I s
sis-	co
s i: s	k @U
sis-	kin
s I s	k I n
sis-	kind
s I s	k I n d
sis-	ley
s I z	l i:
sis-	sel
s I	s V l
sis-	sie
s I	s i:
sis-	son
s I	s V n
sis-	sy
s I	s i:
sis-	ter
s I s	t @r
sis-	ter-	hood
s I s	t @r	h U d
sis-	ters
s I s	t @r z
sis-	ter's
s I s	t @r z
sis-	tine
s I s	t i: n
sis-	to
s I s	t @U
sit
s I t
sit-	com
s I t	k Q m
sit-	coms
s I t	k Q m z
sit-	ka
s I t	k V
sit-	ter
s I	t @r
sit-	ters
s I	t @r z
sit-	ting
s I	t I N
site
s aI t
sites
s aI t s
site's
s aI t s
sithe
s aI D
sits
s I t s
sitz
s I t s
six
s I k s
six-	fold
s I k	s f @U l d
six-	teen
s I k	s t i: n
six-	teens
s I k	s t i: n z
six-	teen's
s I k	s t i: n z
six-	teenth
s I k	s t i: n T
six-	teenths
s I k	s t i: n T s
six-	ti-	eth
s I k	s t i:	V T
six-	ties
s I k	s t i: z
six-	ty
s I k	s t i:
six-	ty's
s I k	s t i: z
sixth
s I k s T
sixths
s I k s T s
siz-	z-	ling
s I	z V	l I N
siz-	zle
s I	z V l
siz-	zled
s I	z V l d
size
s aI z
sized
s aI z d
sizz-	ler
s I z	l @r
sjo-	berg
S @U	b @r g
ska-	ted
s k eI	t V d
ska-	ter
s k eI	t @r
ska-	ters
s k eI	t @r z
ska-	ting
s k eI	t I N
skaff
s k { f
skan-	di-	a
s k { n	d i:	V
skate
s k eI t
skate-	boar-	ding
s k eI t	b O@	d I N
skate-	board
s k eI t	b O@ d
skates
s k eI t s
ske-	le-	tal
s k e	l V	t V l
ske-	le-	ton
s k e	l V	t V n
ske-	le-	tons
s k e	l V	t V n z
ske-	wer
s k j u:	@r
ske-	wered
s k j u:	@r d
ske-	wers
s k j u:	@r z
ske-	wing
s k j u:	I N
skeat
s k i: t
skee-	ter
s k i:	t @r
skee-	ters
s k i:	t @r z
skeel
s k i: l
skeen
s k i: n
skeens
s k i: n z
skees
s k i: z
skeet
s k i: t
skeets
s k i: t s
skel-	ly
s k e	l i:
skel-	ter
s k e l	t @r
skel-	ton
s k e l	t V n
skene
s k i: n
skep-	ti-	cal
s k e p	t V	k V l
skep-	ti-	cal-	ly
s k e p	t I	k V	l i:
skep-	ti-	ci-	sm
s k e p	t I	s I	z V m
skep-	tic
s k e p	t I k
skep-	tics
s k e p	t I k s
sker-	ry
s k e@	i:
sket-	ches
s k e	tS V z
sket-	ching
s k e	tS I N
sket-	chy
s k e	tS i:
sketch
s k e tS
sketch-	book
s k e tS	b U k
sketch-	books
s k e tS	b U k s
sketched
s k e tS t
skew
s k j u:
skewed
s k j u: d
skews
s k j u: z
ski
s k i:
ski-	ba
s k aI	b V
ski-	er
s k i:	@r
ski-	ers
s k i:	@r z
ski-	ing
s k i:	I N
ski-	ver
s k aI	v @r
skid
s k I d
skid-	ded
s k I	d V d
skid-	ding
s k I	d I N
skid-	more
s k I d	m O@
skids
s k I d z
skied
s k i: d
skies
s k aI z
skiff
s k I f
skiffs
s k I f s
skil-	lern
s k I	l @r n
skil-	let
s k I	l V t
skil-	ling
s k I	l I N
skil-	lings
s k I	l I N z
skill
s k I l
skill-	ful
s k I l	f V l
skill-	ful-	ly
s k I l	f V	l i:
skill-	man
s k I l	m V n
skilled
s k I l d
skills
s k I l z
skim
s k I m
skim-	mer
s k I	m @r
skim-	mers
s k I	m @r z
skim-	ming
s k I	m I N
skim-	pi-	er
s k I m	p i:	@r
skim-	pi-	est
s k I m	p i:	V s t
skim-	ping
s k I m	p I N
skim-	py
s k I m	p i:
skimmed
s k I m d
skimp
s k I m p
skin
s k I n
skin-	head
s k I n	h e d
skin-	heads
s k I n	h e d z
skin-	less
s k I n	l V s
skin-	ner
s k I	n @r
skin-	ner's
s k I	n @r z
skin-	ni-	er
s k I	n i:	@r
skin-	ni-	est
s k I	n i:	V s t
skin-	ny
s k I	n i:
skinks
s k I N k s
skinned
s k I n d
skins
s k I n z
skin's
s k I n z
skip
s k I p
skip-	jack
s k I p	dZ { k
skip-	jacks
s k I p	dZ { k s
skip-	jack's
s k I p	dZ { k s
skip-	per
s k I	p @r
skip-	pers
s k I	p @r z
skip-	per's
s k I	p @r z
skip-	ping
s k I	p I N
skip-	py
s k I	p i:
skip-	ton
s k I p	t V n
skip-	with
s k I p	w I T
skipp
s k I p
skipped
s k I p t
skips
s k I p s
skir-	mi-	shes
s k @r	m I	S V z
skir-	mi-	shing
s k @r	m I	S I N
skir-	mish
s k @r	m I S
skir-	ted
s k @r	t V d
skir-	ting
s k @r	t I N
skirt
s k @r t
skirts
s k @r t s
skis
s k i: z
skit
s k I t
skit-	tish
s k I	t I S
skit-	tish-	ness
s k I	t I S	n V s
skit-	tle
s k I	t V l
skit-	tles
s k I	t V l z
skits
s k I t s
sklar
s k l Q@
sko-	da
s k @U	d V
sko-	kie
s k @U	k i:
skoal
s k @U l
skoff
s k O: f
skol-	nik
s k @U l	n I k
skow-	he-	gan
s k @U	h i:	g V n
skulk
s k V l k
skull
s k V l
skulls
s k V l z
skunk
s k V N k
skunks
s k V N k s
sky
s k aI
sky-	bo-	xes
s k aI	b Q k	s V z
sky-	box
s k aI	b Q k s
sky-	cap
s k aI	k { p
sky-	di-	ving
s k aI	d aI	v I N
sky-	dive
s k aI	d aI v
sky-	high
s k aI	h aI
sky-	lark
s k aI	l Q@ k
sky-	light
s k aI	l aI t
sky-	lights
s k aI	l aI t s
sky-	line
s k aI	l aI n
sky-	roc-	ke-	ted
s k aI	r Q	k V	t V d
sky-	roc-	ke-	ting
s k aI	r Q	k V	t I N
sky-	roc-	ket
s k aI	r Q	k V t
sky-	scra-	per
s k aI s	k r eI	p @r
sky-	scra-	pers
s k aI s	k r eI	p @r z
sky-	ward
s k aI	w @r d
sky-	wave
s k aI	w eI v
sky-	way
s k aI	w eI
sky-	wri-	ter
s k aI	r aI	t @r
sky-	wri-	ters
s k aI	r aI	t @r z
sky-	wri-	ting
s k aI	r aI	t I N
sky's
s k aI z
sla-	by
s l eI	b i:
sla-	gle
s l eI	g V l
sla-	lom
s l Q	l V m
sla-	sher
s l {	S @r
sla-	shes
s l {	S V z
sla-	shing
s l {	S I N
sla-	ted
s l eI	t V d
sla-	ter
s l eI	t @r
sla-	ton
s l {	t V n
sla-	ve-	ry
s l eI	v @r	i:
sla-	vic
s l Q	v I k
sla-	vin
s l {	v I n
sla-	vish
s l eI	v I S
sla-	vish-	ly
s l {	v I S	l i:
sla-	vo-	ni-	a
s l V	v @U	n i:	V
slab
s l { b
slabs
s l { b z
slac-	ke-	ning
s l {	k V	n I N
slac-	ken
s l {	k V n
slac-	kened
s l {	k V n d
slac-	kens
s l {	k V n z
slac-	ker
s l {	k @r
slac-	kers
s l {	k @r z
slack
s l { k
slack-	ness
s l { k	n V s
slacked
s l { k t
slacks
s l { k s
slade
s l eI d
slag
s l { g
slain
s l eI n
slam
s l { m
slam-	mer
s l {	m @r
slam-	ming
s l {	m I N
slammed
s l { m d
slams
s l { m z
slan-	de-	rous
s l { n	d @r	V s
slan-	der
s l { n	d @r
slan-	dered
s l { n	d @r d
slan-	ted
s l { n	t V d
slan-	ting
s l { n	t I N
slane
s l eI n
slang
s l { N
slant
s l { n t
slap
s l { p
slap-	dash
s l { p	d { S
slap-	ping
s l {	p I N
slap-	stick
s l { p	s t I k
slape
s l eI p
slapped
s l { p t
slaps
s l { p s
slash
s l { S
slashed
s l { S t
slat
s l { t
slat-	kin
s l { t	k I n
slat-	te-	ry
s l {	t @r	i:
slat-	ter
s l {	t @r
slate
s l eI t
slates
s l eI t s
slats
s l { t s
slaugh-	te-	ring
s l O:	t @r	I N
slaugh-	te-	rings
s l O:	t @r	I N z
slaugh-	ter
s l O:	t @r
slaugh-	ter-	hou-	ses
s l O:	t @r	h aU	s V z
slaugh-	ter-	house
s l O:	t @r	h aU s
slaugh-	tered
s l O:	t @r d
slaugh-	ters
s l O:	t @r z
slav
s l Q v
slave
s l eI v
slaves
s l eI v z
slavs
s l Q v z
slaw
s l O:
slay
s l eI
slay-	den
s l eI	d V n
slay-	er
s l eI	@r
slay-	ing
s l eI	I N
slay-	ings
s l eI	I N z
slay-	ton
s l eI	t V n
slea-	zy
s l i:	z i:
sleaze
s l i: z
sled
s l e d
sled-	ding
s l e	d I N
sledge
s l e dZ
sledge-	ham-	mer
s l e dZ	h {	m @r
sleds
s l e d z
slee
s l i:
slee-	ker
s l i:	k @r
slee-	kest
s l i:	k V s t
slee-	per
s l i:	p @r
slee-	pers
s l i:	p @r z
slee-	pi-	ly
s l i:	p I	l i:
slee-	pi-	ness
s l i:	p i:	n V s
slee-	ping
s l i:	p I N
slee-	py
s l i:	p i:
sleek
s l i: k
sleek-	ly
s l i: k	l i:
sleep
s l i: p
sleep-	less
s l i: p	l V s
sleep-	wal-	ker
s l i: p	w O:	k @r
sleep-	wal-	kers
s l i: p	w O:	k @r z
sleep-	wal-	king
s l i: p	w O:	k I N
sleep-	walk
s l i: p	w O: k
sleep-	wear
s l i: p	w e@
sleeps
s l i: p s
sleet
s l i: t
sleeve
s l i: v
sleeve-	less
s l i: v	l V s
sleeved
s l i: v d
sleeves
s l i: v z
sleigh
s l eI
sleight
s l aI t
slem-	mer
s l e	m @r
slemp
s l e m p
slen-	der
s l e n	d @r
slept
s l e p t
slet-	ten
s l e	t V n
sleu-	thing
s l u:	T I N
sleuth
s l u: T
sleuths
s l u: T s
slew
s l u:
sli-	cer
s l aI	s @r
sli-	ces
s l aI	s V z
sli-	cing
s l aI	s I N
sli-	der
s l aI	d @r
sli-	ding
s l aI	d I N
sli-	my
s l aI	m i:
sli-	the-	ring
s l I	D @r	I N
sli-	ther
s l I	D @r
sli-	ver
s l I	v @r
sli-	vers
s l I	v @r z
sli-	vo-	vitz
s l I	v V	v I t s
sli-	wa
s l aI	v V
slic-	ker
s l I	k @r
slic-	kers
s l I	k @r z
slic-	kest
s l I	k V s t
slice
s l aI s
sliced
s l aI s t
slick
s l I k
slick-	ly
s l I k	l i:
slicked
s l I k t
slicks
s l I k s
slid
s l I d
slide
s l aI d
slides
s l aI d z
slif-	ka
s l I f	k V
sligh-	ted
s l aI	t V d
sligh-	test
s l aI	t V s t
sligh-	ting
s l aI	t I N
slight
s l aI t
slight-	ly
s l aI t	l i:
slights
s l aI t s
slim
s l I m
slim-	mer
s l I	m @r
slim-	mest
s l I	m V s t
slim-	ming
s l I	m I N
slime
s l aI m
slimmed
s l I m d
slims
s l I m z
slin-	ger
s l I	N @r
slin-	ging
s l I	N I N
slin-	ker
s l I N	k @r
slin-	ky
s l I N	k i:
sling
s l I N
sling-	shot
s l I N	S Q t
sling-	shots
s l I N	S Q t s
slings
s l I N z
slip
s l I p
slip-	on
s l I	p Q n
slip-	page
s l I	p I dZ
slip-	pe-	ry
s l I	p @r	i:
slip-	per
s l I	p @r
slip-	pers
s l I	p @r z
slip-	ping
s l I	p I N
slip-	shod
s l I p	S Q d
slipped
s l I p t
)"
R"(slips
s l I p s
slit
s l I t
slit-	ting
s l I	t I N
slits
s l I t s
slo-	comb
s l @U	k V m
slo-	cum
s l @U	k V m
slo-	gan
s l @U	g V n
slo-	gans
s l @U	g V n z
slo-	per
s l @U	p @r
slo-	ping
s l @U	p I N
slo-	shing
s l Q	S I N
slo-	va-	ki-	a
s l @U	v Q	k i:	V
slo-	va-	ki-	a's
s l @U	v Q	k i:	V z
slo-	vak
s l @U	v { k
slo-	vaks
s l @U	v { k s
slo-	ve-	ni-	a
s l @U	v i:	n i:	V
slo-	ve-	ni-	an
s l @U	v i:	n i:	V n
slo-	ven-	li-	ness
s l V	v V n	l i:	n V s
slo-	ven-	ly
s l V	v V n	l i:
slo-	vene
s l @U	v i: n
slo-	venes
s l @U	v i: n z
slo-	wer
s l @U	@r
slo-	west
s l @U	V s t
slo-	wing
s l @U	I N
sloan
s l @U n
sloane
s l @U n
sloan's
s l @U n z
sloat
s l @U t
slob
s l Q b
slob-	be-	ring
s l Q	b @r	I N
slob-	ber
s l Q	b @r
slobs
s l Q b z
sloe
s l @U
slog
s l Q g
slog-	ging
s l Q	g I N
slogged
s l Q g d
slone
s l @U n
sloop
s l u: p
slop
s l Q p
slop-	pi-	er
s l Q	p i:	@r
slop-	pi-	est
s l Q	p i:	V s t
slop-	pi-	ly
s l Q	p I	l i:
slop-	pi-	ness
s l Q	p i:	n V s
slop-	py
s l Q	p i:
slope
s l @U p
slopes
s l @U p s
slosh
s l Q S
slot
s l Q t
slot-	nick
s l Q t	n I k
slot-	ted
s l Q	t V d
slot-	ting
s l Q	t I N
sloth
s l @U T
slots
s l Q t s
slou-	ches
s l aU	tS V z
slou-	ching
s l aU	tS I N
slouch
s l aU tS
slough
s l V f
sloughs
s l V f s
slow
s l @U
slow-	down
s l @U	d aU n
slow-	downs
s l @U	d aU n z
slow-	ly
s l @U	l i:
slow-	ness
s l @U	n V s
slow-	poke
s l @U	p @U k
slowed
s l @U d
slows
s l @U z
slu-	sher
s l V	S @r
slud-	gy
s l V	dZ i:
sludge
s l V dZ
slug
s l V g
slug-	fest
s l V g	f e s t
slug-	ger
s l V	g @r
slug-	gers
s l V	g @r z
slug-	ging
s l V	g I N
slug-	gish
s l V	g I S
slug-	gish-	ly
s l V	g I S	l i:
slug-	gish-	ness
s l V	g I S	n V s
slugged
s l V g d
slugs
s l V g z
slui-	cing
s l u:	s I N
slui-	ter
s l u:	t @r
sluice
s l u: s
slum
s l V m
slum-	be-	ring
s l V m	b @r	I N
slum-	ber
s l V m	b @r
slum-	ping
s l V m	p I N
slump
s l V m p
slumped
s l V m p t
slumps
s l V m p s
slums
s l V m z
slung
s l V N
slur
s l @r
slur-	ring
s l @r	I N
slur-	ry
s l @r	i:
slurp
s l @r p
slurred
s l @r d
slurs
s l @r z
slush
s l V S
slut
s l V t
sly
s l aI
sly-	ly
s l aI	l i:
sly-	ness
s l aI	n V s
sma-	sher
s m {	S @r
sma-	shes
s m {	S V z
sma-	shing
s m {	S I N
smac-	king
s m {	k I N
smack
s m { k
smacked
s m { k t
smacks
s m { k s
smail
s m eI l
smal-	len
s m O:	l V n
smal-	ler
s m O:	l @r
smal-	lest
s m O:	l V s t
smal-	ley
s m Q	l i:
smal-	ling
s m O:	l I N
smal-	lish
s m O:	l I S
small
s m O: l
small-	man
s m O: l	m V n
small-	ness
s m O: l	n V s
small-	pox
s m O: l	p Q k s
small-	talk
s m O: l	t O: k
small-	town
s m O: l	t aU n
small-	wood
s m O: l	w U d
smalls
s m O: l z
smaltz
s m { l t s
smar-	my
s m Q@	m i:
smar-	ter
s m Q@	t @r
smar-	test
s m Q@	t V s t
smar-	ting
s m Q@	t I N
smarr
s m { r
smart
s m Q@ t
smart-	ly
s m Q@ t	l i:
smarts
s m Q@ t s
smartt
s m Q@ t
smash
s m { S
smashed
s m { S t
smat-	te-	ring
s m {	t @r	I N
smat-	ter
s m {	t @r
sme-	ta-	na
s m e	t V	n V
smea-	ring
s m I@	I N
smear
s m I@
smeared
s m I@ d
smears
s m I@ z
smed-	ley
s m e d	l i:
smee
s m i:
smel-	ling
s m e	l I N
smel-	ly
s m e	l i:
smel-	ter
s m e l	t @r
smel-	ters
s m e l	t @r z
smel-	ter's
s m e l	t @r z
smel-	ting
s m e l	t I N
smell
s m e l
smelled
s m e l d
smells
s m e l z
smelt
s m e l t
smi-	ley
s m aI	l i:
smi-	ling
s m aI	l I N
smi-	ling-	ly
s m aI	l I N	l i:
smi-	the-	reen
s m I	D @r	i: n
smi-	the-	reens
s m I	D @r	i: n z
smi-	ther
s m I	D @r
smi-	thers
s m I	D @r z
smid-	dy
s m I	d i:
smid-	gen
s m I	dZ V n
smile
s m aI l
smiled
s m aI l d
smiles
s m aI l z
smir-	king
s m @r	k I N
smir-	noff
s m @r	n O: f
smir-	nov
s m @r	n Q f
smirk
s m @r k
smirks
s m @r k s
smit
s m I t
smit-	ten
s m I	t V n
smit-	tle
s m I	t V l
smit-	ty
s m I	t i:
smith
s m I T
smith-	burg
s m I T	b @r g
smith-	field
s m I T	f i: l d
smith-	so-	ni-	an
s m I T	s @U	n i:	V n
smith-	so-	ni-	an's
s m I T	s @U	n i:	V n z
smith-	son
s m I T	s V n
smith-	son's
s m I T	s V n z
smith-	town
s m I T	t aU n
smith-	wick
s m I T	w I k
smiths
s m I T s
smith's
s m I T s
smits
s m I t s
smo-	ker
s m @U	k @r
smo-	kers
s m @U	k @r z
smo-	ker's
s m @U	k @r z
smo-	key
s m @U	k i:
smo-	king
s m @U	k I N
smo-	king's
s m @U	k I N z
smo-	ky
s m @U	k i:
smo-	lensk
s m @U	l e n s k
smo-	the-	ring
s m V	D @r	I N
smo-	ther
s m V	D @r
smo-	thered
s m V	D @r d
smo-	thers
s m V	D @r z
smock
s m Q k
smog
s m Q g
smog-	gi-	est
s m Q	g i:	V s t
smog-	gy
s m O:	g i:
smoke
s m @U k
smoke-	jum-	per
s m @U k	dZ V m	p @r
smoke-	jum-	pers
s m @U k	dZ V m	p @r z
smoke-	less
s m @U k	l V s
smoke-	screen
s m @U k	s k r i: n
smoke-	stack
s m @U k	s t { k
smoke-	stacks
s m @U k	s t { k s
smoked
s m @U k t
smokes
s m @U k s
smol-	de-	ring
s m @U l	d @r	I N
smol-	der
s m @U l	d @r
smoo-	then
s m u:	D V n
smoo-	thens
s m u:	D V n z
smoo-	ther
s m u:	D @r
smoo-	thest
s m u:	D V s t
smoo-	thing
s m u:	D I N
smoot
s m u: t
smooth
s m u: D
smooth-	ly
s m u: D	l i:
smooth-	ness
s m u: D	n V s
smoothed
s m u: D d
smooths
s m u: D z
smoots
s m u: t s
smor-	gas-	bord
s m O@	g V s	b O@ d
smouse
s m aU s
smuc-	ker
s m V	k @r
smudge
s m V dZ
smudged
s m V dZ d
smug
s m V g
smug-	gle
s m V	g V l
smug-	gled
s m V	g V l d
smug-	ly
s m V g	l i:
smug-	ness
s m V g	n V s
smugg-	ler
s m V g	l @r
smugg-	lers
s m V g	l @r z
smugg-	ler's
s m V g	l @r z
smugg-	ling
s m V g	l I N
smurf
s m @r f
smurfs
s m @r f s
smut
s m V t
smyr-	na
s m @r	n V
smyth
s m aI T
smythe
s m aI D
sna-	fu
s n {	f u:
sna-	fus
s n {	f V s
sna-	king
s n eI	k I N
sna-	ring
s n e@	I N
snack
s n { k
snacks
s n { k s
snag
s n { g
snag-	ger
s n {	g @r
snag-	ging
s n {	g I N
snagged
s n { g d
snags
s n { g z
snail
s n eI l
snails
s n eI l z
snail's
s n eI l z
snake
s n eI k
snake-	bite
s n eI k	b aI t
snake-	bites
s n eI k	b aI t s
snake-	like
s n eI k	l aI k
snakes
s n eI k s
snake's
s n eI k s
snap
s n { p
snap-	dra-	gon
s n { p	d r {	g V n
snap-	dra-	gons
s n { p	d r {	g V n z
snap-	per
s n {	p @r
snap-	ping
s n {	p I N
snap-	ple
s n {	p V l
snap-	ple's
s n {	p V l z
snap-	py
s n {	p i:
snap-	shot
s n { p	S Q t
snap-	shots
s n { p	S Q t s
snape
s n eI p
snapp
s n { p
snapped
s n { p t
snaps
s n { p s
snar-	led
s n Q@	V l d
snar-	ling
s n Q@	l I N
snare
s n e@
snared
s n e@ d
snares
s n e@ z
snarl
s n Q@ l
snarls
s n Q@ l z
snat-	cher
s n {	tS @r
snat-	chers
s n {	tS @r z
snat-	ches
s n {	tS V z
snat-	ching
s n {	tS I N
snatch
s n { tS
snatched
s n { tS t
snaz-	zi-	er
s n {	z i:	@r
snaz-	zy
s n {	z i:
snea-	ker
s n i:	k @r
snea-	kers
s n i:	k @r z
snea-	king
s n i:	k I N
snea-	ky
s n i:	k i:
snead
s n i: d
sneak
s n i: k
sneaked
s n i: k t
sneaks
s n i: k s
sneath
s n e T
snee
s n i:
snee-	ring
s n I@	I N
snee-	zes
s n i:	z V z
snee-	zing
s n i:	z I N
sneed
s n i: d
sneer
s n I@
sneered
s n I@ d
sneers
s n I@ z
sneeze
s n i: z
sneezed
s n i: z d
snel-	len
s n e	l V n
snel-	ler
s n e	l @r
snel-	ling
s n e	l I N
snell
s n e l
sni-	der
s n aI	d @r
sni-	per
s n aI	p @r
sni-	pers
s n aI	p @r z
sni-	per's
s n aI	p @r z
sni-	ping
s n aI	p I N
snic-	ke-	ring
s n I	k @r	I N
snic-	ker
s n I	k @r
snic-	kered
s n I	k @r d
snic-	kers
s n I	k @r z
snide
s n aI d
snif-	fer
s n I	f @r
snif-	fing
s n I	f I N
snif-	fy
s n I	f i:
sniff
s n I f
sniffed
s n I f t
sniffs
s n I f s
snip
s n I p
snip-	pet
s n I	p V t
snip-	pets
s n I	p V t s
snipe
s n aI p
sniped
s n aI p t
snipes
s n aI p s
snips
s n I p s
snit-	ching
s n I	tS I N
snitch
s n I tS
snive-	ly
s n aI v	l i:
sno-	ho-	mish
s n Q	h V	m I S
sno-	ring
s n O@	I N
sno-	ver
s n @U	v @r
sno-	wing
s n @U	I N
sno-	wy
s n @U	i:
snob
s n Q b
snob-	be-	ry
s n Q	b @r	i:
snob-	bish
s n Q	b I S
snob-	by
s n Q	b i:
snobs
s n Q b z
snod-	dy
s n Q	d i:
snod-	grass
s n Q d	g r { s
snoke
s n @U k
snoo-	ker
s n U	k @r
snoo-	kered
s n U	k @r d
snoo-	ping
s n u:	p I N
snoo-	py
s n u:	p i:
snoo-	ty
s n u:	t i:
snoo-	zing
s n u:	z I N
snook
s n U k
snooks
s n U k s
snoop
s n u: p
snooze
s n u: z
snor-	ted
s n O@	t V d
snor-	ting
s n O@	t I N
snore
s n O@
snort
s n O@ t
snorts
s n O@ t s
snot
s n O: t
snout
s n aU t
snow
s n @U
snow-	bal-	ling
s n @U	b O:	l I N
snow-	ball
s n @U	b O: l
snow-	balled
s n @U	b O: l d
snow-	balls
s n @U	b O: l z
snow-	ball's
s n @U	b O: l z
snow-	bird
s n @U	b @r d
snow-	birds
s n @U	b @r d z
snow-	boar-	der
s n @U	b O@	d @r
snow-	boar-	ders
s n @U	b O@	d @r z
snow-	board
s n @U	b O@ d
snow-	boards
s n @U	b O@ d z
snow-	bound
s n @U	b aU n d
snow-	don
s n @U	d V n
snow-	fall
s n @U	f Q l
snow-	falls
s n @U	f Q l z
snow-	flake
s n @U f	l eI k
snow-	flakes
s n @U f	l eI k s
snow-	man
s n @U	m { n
snow-	mo-	bile
s n @U	m @U	b i: l
snow-	mo-	biles
s n @U	m @U	b i: l z
snow-	plow
s n @U p	l aU
snow-	plows
s n @U p	l aU z
snow-	shoe
s n @U	S u:
snow-	storm
s n @U s	t O@ m
snow-	storms
s n @U s	t O@ m z
snowed
s n @U d
snows
s n @U z
snub
s n V b
snub-	bing
s n V	b I N
snubbed
s n V b d
snuck
s n V k
snuf-	fer
s n V	f @r
snuf-	fing
s n V	f I N
snuff
s n V f
snuffed
s n V f t
snuffs
s n V f s
snug
s n V g
snug-	ging
s n V	g I N
snug-	gle
s n V	g V l
snug-	ly
s n V g	l i:
sny-	der
s n aI	d @r
sny-	der's
s n aI	d @r z
so
s @U
so-	be-	ring
s @U	b @r	I N
so-	bel
s @U	b V l
so-	ber
s @U	b @r
so-	ber-	ly
s @U	b @r	l i:
so-	bered
s @U	b @r d
so-	bers
s @U	b @r z
so-	bi-	bor
s @U	b i:	b O@
so-	ble
s @U	b V l
so-	bri-	e-	ty
s V b	r aI	V	t i:
so-	bri-	quet
s @U b	r I	k eI
so-	called
s @U	k O: l d
so-	ci-	e-	tal
s V	s aI	V	t V l
so-	ci-	e-	te
s @U	s i:	e	t eI
so-	ci-	e-	ties
s V	s aI	V	t i: z
so-	ci-	e-	ty
s V	s aI	V	t i:
so-	ci-	e-	ty's
s V	s aI	V	t i: z
so-	ci-	o
s @U	s i:	@U
so-	ci-	o-	e-	co-	no-	mic
s @U	s i:	@U	e	k V	n Q	m I k
so-	ci-	o-	lo-	gi-	cal
s @U	s i:	V	l Q	dZ I	k V l
so-	ci-	o-	lo-	gist
s @U	s i:	Q	l V	dZ V s t
so-	ci-	o-	lo-	gists
s @U	s i:	Q	l V	dZ V s t s
so-	ci-	o-	lo-	gy
s @U	s i:	Q	l V	dZ i:
so-	ci-	o-	path
s @U	s i:	@U	p { T
so-	cia-	ble
s @U	S V	b V l
so-	cia-	li-	sm
s @U	S V	l I	z V m
so-	cia-	li-	za-	tion
s @U	S V	l I	z eI	S V n
so-	cia-	li-	zing
s @U	S V	l aI	z I N
so-	cia-	lis-	tic
s @U	S V	l I s	t I k
so-	cia-	list
s @U	S V	l I s t
so-	cia-	lists
s @U	S V	l I s t s
so-	cia-	lite
s @U	S V	l aI t
so-	cia-	lites
s @U	S V	l aI t s
so-	cia-	lize
s @U	S V	l aI z
so-	cia-	lized
s @U	S V	l aI z d
so-	cial
s @U	S V l
so-	cial-	ly
s @U	S V	l i:
so-	da
s @U	d V
so-	das
s @U	d V z
so-	da's
s @U	d V z
so-	der-	blom
s @U	d @r b	l Q m
so-	der-	strom
s Q	d @r s	t r V m
so-	di-	um
s @U	d i:	V m
so-	do-	mize
s V	d V	m aI z
so-	do-	mized
s V	d V	m aI z d
so-	do-	my
s Q	d V	m i:
so-	dom
s Q	d V m
so-	dus
s @U	d V s
so-	fa
s @U	f V
so-	fas
s @U	f V z
so-	fer
s @U	f @r
so-	fer's
s @U	f @r z
so-	fi-	a
s @U	f i:	V
so-	fi-	a's
s @U	f i:	V z
so-	fie
s Q	f i:
so-	fte-	ner
s O:	f V	n @r
so-	fte-	ning
s O:	f V	n I N
so-	ftened
s O:	f V n d
so-	ftens
s O:	f V n z
so-	hi-	o
s @U	h aI	@U
so-	ho
s @U	h @U
so-	ja
s @U	dZ V
so-	journ
s @U	dZ @r n
so-	kai-	ya
s V	k aI	j V
so-	ko-	lov
s Q	k V	l Q v
so-	kol
s @U	k V l
so-	la
s @U	l V
so-	la-	na
s @U	l {	n V
so-	la-	no
s @U	l Q	n @U
so-	lace
s Q	l V s
so-	lan
s @U	l V n
so-	land
s Q	l V n d
so-	lar
s @U	l @r
so-	leil
s @U	l aI l
so-	lem-	ni-	ty
s V	l e m	n V	t i:
so-	lemn
s Q	l V m
so-	lemn-	ly
s O:	l V m	l i:
so-	ler
s @U	l @r
so-	li
s @U	l i:
so-	li-	ci-	ta-	tion
s V	l I	s V	t eI	S V n
so-	li-	ci-	ta-	tions
s V	l I	s V	t eI	S V n z
so-	li-	ci-	ted
s V	l I	s V	t V d
so-	li-	ci-	ting
s V	l I	s V	t I N
so-	li-	ci-	tor
s V	l I	s V	t @r
so-	li-	ci-	tors
s V	l I	s V	t @r z
so-	li-	ci-	tous
s V	l I	s V	t V s
so-	li-	ci-	tude
s V	l I	s V	t u: d
so-	li-	cit
s V	l I	s V t
so-	li-	cits
s V	l I	s V t s
so-	li-	da-	ri-	ty
s Q	l I	d e@	I	t i:
so-	li-	da-	ri-	ty's
s Q	l I	d e@	I	t i: z
so-	li-	di-	fied
s V	l I	d I	f aI d
so-	li-	di-	fies
s V	l I	d I	f aI z
so-	li-	di-	fy
s V	l I	d I	f aI
so-	li-	di-	fy-	ing
s V	l I	d I	f aI	I N
so-	li-	di-	ty
s V	l I	d I	t i:
so-	li-	lo-	quize
s V	l I	l V k	w aI z
so-	li-	lo-	quy
s @U	l I	l Q k	w i:
so-	li-	man
s Q	l I	m V n
so-	li-	man's
s Q	l I	m V n z
so-	li-	ta
s @U	l i:	t V
so-	li-	ta-	ri-	ness
s Q	l I	t e@	i:	n V s
so-	li-	ta-	ry
s Q	l I	t e@	i:
so-	li-	taire
s Q	l I	t e@
so-	li-	tude
s Q	l I	t u: d
so-	lid
s Q	l I d
so-	lid-	ly
s Q	l I d	l i:
so-	lids
s Q	l I d z
so-	lin-	gen
s @U	l I N	g e n
so-	lis
s @U	l I s
so-	lo
s @U	l @U
so-	lo-	ist
s @U	l @U	I s t
so-	lo-	ists
s @U	l @U	I s t s
so-	lo-	man
s @U	l @U	m { n
so-	lo-	mon
s Q	l V	m V n
so-	lo-	mon's
s Q	l V	m V n z
so-	lo-	viev
s Q	l @U	v i: v
so-	lon
s @U	l V n
so-	los
s @U	l @U z
so-	lu-	ble
s Q l	j V	b V l
so-	lu-	tion
s V	l u:	S V n
so-	lu-	tions
s V	l u:	S V n z
so-	lum
s @U	l V m
so-	ma
s @U	m V
so-	ma-	li
s V	m Q	l i:
so-	ma-	li-	a
s V	m Q	l i:	V
so-	ma-	li-	a's
s V	m Q	l i:	V z
so-	ma-	li-	land
s V	m Q	l i:	l { n d
so-	ma-	lian
s V	m Q l	j V n
so-	ma-	lians
s V	m Q l	j V n z
so-	ma-	lis
s V	m Q	l i: z
so-	ma-	to-	tro-	pin
s @U	m V	t Q t	r V	p V n
so-	mer-	saul-	ting
s V	m @r	s O: l	t I N
so-	mer-	sault
s V	m @r	s O: l t
so-	mer-	saults
s V	m @r	s O: l t s
so-	mer-	set
s V	m @r	s e t
so-	mer-	ton
s V	m @r	t V n
so-	mer-	ville
s V	m @r	v I l
so-	mers
s V	m @r z
so-	mo-	za
s V	m @U	z V
so-	na-	ta
s V	n Q	t V
so-	na-	tas
s Q	n Q	t V z
so-	nar
s @U	n Q@
so-	net
s @U	n V t
so-	ni
s @U	n i:
so-	nia
s @U n	j V
so-	nic
s Q	n I k
so-	nics
s Q	n I k s
so-	no-	gram
s O:	n V g	r { m
so-	no-	grams
s O:	n V g	r { m z
so-	no-	ma
s V	n @U	m V
so-	no-	ra
s V	n O@	V
so-	no-	rous
s Q	n @r	V s
so-	ny
s @U	n i:
so-	ny's
s @U	n i: z
so-	per
s @U	p @r
so-	pher
s Q	f @r
so-	phi-	a
s @U	f i:	V
so-	phie
s @U	f i:
so-	phie's
s @U	f i: z
so-	phis-	ti-	ca-	ted
s V	f I s	t I	k eI	t V d
so-	phis-	ti-	ca-	tion
s V	f I s	t I	k eI	S V n
so-	phis-	ti-	cate
s V	f I s	t I	k eI t
so-	phis-	ti-	cates
s V	f I s	t I	k I t s
so-	pho-	mo-	ric
s Q	f @U	m Q@	I k
so-	phoc-	les
s Q	f V k	l i: z
so-	phy
s @U	f i:
so-	rel
s O@	V l
so-	rell
s O@	V l
so-	ren-	sen
s O@	V n	s V n
so-	ren-	son
s O@	V n	s V n
so-	ren-	to
s @r	e n	t @U
so-	ren-	to's
s @r	e n	t @U z
so-	ro-	ri-	ties
s @r	O@	I	t i: z
so-	ro-	ri-	ty
s @r	O@	I	t i:
so-	rus
s O@	V s
so-	sa
s @U	s V
so-	so
s @U	s @U
so-	ter
s @U	t @r
so-	the-	by
s Q	T V	b i:
so-	the-	by's
s Q	T V	b i: z
so-	to
s @U	t @U
so-	ur
s aU	@r
so-	ur-	ing
s aU	@r	I N
so-	urs
s aU	@r z
so-	vi-	e-	to-	lo-	gist
s @U	v i:	V	t Q	l V	dZ I s t
so-	vi-	e-	to-	lo-	gists
s @U	v i:	V	t Q	l V	dZ I s t s
so-	vi-	et
s @U	v i:	V t
so-	vi-	ets
s @U	v i:	e t s
so-	vi-	et's
s @U	v i:	e t s
so-	we-	to
s @U	eI	t @U
so-	well
s Q	w e l
so-	wer
s @U	@r
so-	wers
s @U	@r z
so-	wing
s @U	I N
so-	x's
s Q k	s V z
so-	ya
s OI	V
so-	yuz
s OI	u: z
soa-	king
s @U	k I N
soa-	py
s @U	p i:
soa-	res
s O@	e s
soa-	ring
s O@	I N
soak
s @U k
soaked
s @U k t
soaks
s @U k s
soap
s @U p
soap-	box
s @U p	b Q k s
soaps
s @U p s
soar
s O@
soared
s O@ d
soars
s O@ z
soave
s @U v
sob
s Q b
sob-	bing
s Q	b I N
sob-	bing-	ly
s Q	b I N	l i:
sobbed
s Q b d
sobs
s Q b z
soc-	cer
s Q	k @r
soc-	cer's
s Q	k @r z
soc-	ha
s @U	tS V
soc-	hi
s @U	tS i:
soc-	hor
s Q	k @r
soc-	ket
s Q	k V t
soc-	kets
s Q	k V t s
soc-	king
s Q	k I N
soc-	ra-	tes
s Q k	r V	t i: z
soc-	ra-	tic
s V k	r {	t I k
sock
s Q k
socked
s Q k t
socks
s Q k s
sod
s Q d
sod-	den
s Q	d V n
sof-	fel
s O:	f V l
sof-	ten
s O:	f V n
sof-	ter
s Q f	t @r
sof-	test
s O: f	t V s t
soft
s Q f t
soft-	ball
s O: f	t b O: l
soft-	balls
s O: f	t b O: l z
soft-	ly
s O: f	t l i:
soft-	ness
s O: f	t n V s
soft-	soap
s O: f	t s @U p
soft-	spo-	ken
s O: f	t s p @U	k V n
soft-	ware
s O: f	t w e@
soft-	ware's
s O: f	t w e@ z
soft-	wood
s O: f	t w U d
sog-	gy
s Q	g i:
sohn
s Q n
soi-	ree
s w Q@	eI
soil
s OI l
soiled
s OI l d
soils
s OI l z
soil's
s OI l z
soir
s OI r
sok
s Q k
sol
s Q l
sol-	berg
s @U l	b @r g
sol-	dan
s @U l	d V n
sol-	de-	ring
s Q	d @r	I N
sol-	der
s Q	d @r
sol-	die-	ring
s @U l	dZ @r	I N
sol-	dier
s @U l	dZ @r
sol-	diers
s @U l	dZ @r z
sol-	dier's
s @U l	dZ @r z
sol-	diers'
s @U l	dZ @r z
sol-	do
s @U l	d @U
sol-	lars
s Q	l @r z
sol-	ler
s Q	l @r
sol-	lers
s Q	l @r z
sol-	ley
s Q	l i:
sol-	lie
s Q	l i:
sol-	ly
s Q	l i:
sol-	sti-	ces
s O: l	s t I	s V z
sol-	stice
s O: l	s t I s
sol-	ti
s @U l	t i:
sol-	va-	ble
s Q l	v V	b V l
sol-	vay
s @U l	v eI
sol-	ven-	cy
s O: l	v V n	s i:
)"
R"(sol-	vent
s Q l	v V n t
sol-	vents
s O: l	v V n t s
sol-	ver
s Q l	v @r
sol-	vers
s Q l	v @r z
sol-	ving
s Q l	v I N
sol-	zhe-	nit-	syn
s @U l	z V	n I t	s I n
sold
s @U l d
sole
s @U l
sole-	dad
s @U l	d { d
sole-	ly
s @U l	l i:
soles
s @U l z
soll
s Q l
solve
s Q l v
solved
s Q l v d
solves
s Q l v z
som
s Q m
som-	ber
s Q m	b @r
som-	ber-	ly
s Q m	b @r	l i:
som-	bre-	ro
s Q m	b r e@	@U
som-	ma
s Q	m V
som-	mer
s V	m @r
som-	mer-	feld
s Q	m @r	f e l d
som-	mers
s V	m @r r z
som-	no-	lent
s Q m	n V	l V n t
some
s V m
some-	bo-	dy
s V m	b Q	d i:
some-	bo-	dy's
s V m	b Q	d i:
some-	day
s V m	d eI
some-	how
s V m	h aU
some-	one
s V m	w V n
some-	one's
s V m	w V n z
some-	place
s V m	p l eI s
some-	thing
s V m	T I N
some-	things
s V m	T I N z
some-	time
s V m	t aI m
some-	times
s V m	t aI m z
some-	what
s V m	w V t
some-	where
s V m	w e@
some-	wheres
s V m	w e@ z
son
s V n
son-	ger
s O:	N @r
son-	gy
s Q n	dZ i:
son-	ja
s @U n	j V
son-	net
s Q	n e t
son-	nets
s Q	n e t s
son-	ny
s V	n i:
son-	ny's
s V	n i: z
son-	tag
s Q n	t { g
son-	ya
s @U n	j V
)"